### PR TITLE
Fix AVX2 Gather intrinsic failure with JITStress

### PR DESCRIPTION
**Pull request by fiigii**
Fix the JITStress failures in https://github.com/dotnet/coreclr/pull/19775

@CarolEidt @tannergooding

### CODE REVIEW

**Comment by fiigii** [comment]
test Ubuntu x64 Checked jitstress1
test Ubuntu x64 Checked jitstress2

test Windows_NT x64 Checked jitstress1
test Windows_NT x64 Checked jitstress2

test Windows_NT x86 Checked jitstress1
test Windows_NT x86 Checked jitstress2

**Comment by fiigii** [comment]
test Ubuntu x64 Checked Innerloop Build and Test

**Comment by fiigii** [comment]
Ubuntu x64 Checked Innerloop Build and Test (Jit - TieredCompilation=0)

**Comment by fiigii** [comment]
test Ubuntu x64 Checked Innerloop Build and Test prtest

**Comment by fiigii** [comment]
test Ubuntu x64 Checked Innerloop no_tiered_compilation_innerloop Build and Test

**Comment by CarolEidt** [comment]
test Ubuntu x64 Checked Innerloop no_tiered_compilation_innerloop Build and Test

**Comment by fiigii** [comment]
The ubuntu x64 test failure is not related (I/O error), and I cannot trigger it again...

**Comment by fiigii** [comment]
The ubuntu x64 notired test failed on other PRs also.

**Pull request merged**
