### PR TITLE
Remove _syncRoot field from collections

### PR DESCRIPTION
**Pull request by danmoseley**
CoreCLR part of dotnet/corefx#34149.

### CODE REVIEW

**Comment by danmosemsft** [comment]
@dotnet-bot test this please (jenkins unhappy it's about to be replaced)

**Comment by danmosemsft** [comment]
Test fixes in https://github.com/dotnet/corefx/pull/34198/commits/8db135c07bc0963ef3c9e01c370f06494a988a1f

**Comment by jkotas** [comment]
Disable outdated tests in https://github.com/dotnet/coreclr/blob/master/tests/CoreFX/CoreFX.issues.json

**Comment by danmosemsft** [comment]
@dotnet-bot test Ubuntu x64 Formatting
@dotnet-bot test Windows_NT x64 Checked Innerloop Build and Test

jenkins

**Comment by danmosemsft** [comment]
@dotnet-bot test Ubuntu x64 Formatting please
@dotnet-bot test Windows_NT x64 Checked Innerloop Build and Test please

**Comment by danmosemsft** [comment]
@dotnet/dnceng Jenkins is pretty unreliable still
```
11:22:56 Running: clang-format  -style=file /mnt/j/workspace/dotnet_coreclr/master/x64_ubuntu_formatting_prtest/src/jit/smallhash.h
11:22:56 FATAL: command execution failed
11:22:56 java.io.EOFException
11:22:56 	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2681)
11:22:56 	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3156)
11:22:56 	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:862)
11:22:56 	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
11:22:56 	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
```

Also it's not responded to my requests to rerun jobs

**Comment by MattGal** [comment]
@danmosemsft sorry to hear, Matt M is taking a look.

**Pull request merged**
