### PR TITLE
Added additional .NET standards and technical reports to documentation

### PR DESCRIPTION
**Pull request by jack-pappas**
This PR adds additional .NET-related standards (ECMA-372) and technical reports (TR-084, TR-089) to the documentation.

### CODE REVIEW

**Comment by jack-pappas** [comment]
@dnfclas I've already signed a Microsoft CLA (for contributing to F#). Is the .NET Foundation CLA separate from that?

**Comment by richlander** [comment]
@jack-pappas - yes, the two CLAs are different. One is for MS and the other is for .NET Foundation. Please sign the .NET Foundation one, too. Sorry that this is complicated. It's a function of creating a separate foundation for .NET.

**Comment by richlander** [comment]
CC: @CarolEidt

**Comment by CarolEidt** [comment]
@jack-pappas - TR 89 has been obsoleted (it's in the withdrawn list at ECMA: http://www.ecma-international.org/publications/techreports/TRwithdrawn.htm) since it has been superceded by the generics support in ECMA-335.  So, I would suggest that you not add that one.  Also, you should mention that C++/CLI (ECMA-372) is not supported by .NET Core.

**Comment by richlander** [comment]
@jack-pappas thoughts on @CarolEidt's feedback? Would like to merge this PR.

**Comment by jack-pappas** [comment]
@richlander The feedback @CarolEidt provided is good, I'll update my changes accordingly ASAP.

**Comment by richlander** [comment]
@jack-pappas No need. I made the required updates, as you can see from PR #482. No worries. Thanks for this PR. Look forward to your next ones!

**Pull request merged**
