### PR TITLE
Use "test reg, reg" instead of "cmp reg, 0" for cast overflow checks

### PR DESCRIPTION
**Pull request by mikedn**

### CODE REVIEW

**Comment by mikedn** [comment]
Minor diff but the issue is too lame not to fix:
```
Total bytes of diff: -46 (0.00% of base)
    diff is an improvement.
Total byte diff includes 0 bytes from reconciling methods
        Base had    0 unique methods,        0 unique bytes
        Diff had    0 unique methods,        0 unique bytes
Top file improvements by size (bytes):
         -12 : System.Private.CoreLib.dasm (0.00% of base)
         -10 : Microsoft.VisualBasic.dasm (-0.01% of base)
          -9 : System.Net.Security.dasm (-0.01% of base)
          -8 : System.Linq.Expressions.dasm (0.00% of base)
          -3 : Microsoft.CodeAnalysis.dasm (0.00% of base)
7 total files with size differences (7 improved, 0 regressed), 72 unchanged.
Top method improvements by size (bytes):
          -5 : System.Linq.Expressions.dasm - Checked:ConvertInt64(long):ref:this
          -5 : System.Net.Security.dasm - SecPkgContext_StreamSizes:.ctor(ref):this
          -4 : Microsoft.VisualBasic.dasm - Conversions:ToULong(ref):long (2 methods)
          -4 : System.Net.Security.dasm - SecPkgContext_Sizes:.ctor(ref):this
          -3 : Microsoft.CodeAnalysis.dasm - SwitchIntegralJumpTableEmitter:CreateBucketLabels(struct):ref:this
24 total methods with size differences (24 improved, 0 regressed), 65734 unchanged.
```
All diffs of the type
```diff
-        cmp      eax, 0
+        test     eax, eax
```

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib PTAL

**Comment by BruceForstall** [comment]
@mikedn @CarolEidt I wonder if we should put this (and lots of other optimizations happening in lower, like using BT) under `!comp->opts.MinOpts()`.

**Comment by BruceForstall** [comment]
Another thing: should we never mark things contained for minopts?

**Comment by sandreenko** [comment]
> Another thing: should we never mark things contained for minopts?

In the current model `IsContained` must be `true` for field list head nodes and some other artificial structs. So we will have more mess if we try to forbid this flag in minopts.

**Comment by mikedn** [comment]
Hmm, I don't see anything interesting about this particular "optimization" regarding minopts, it just emits a different instruction. 

The stuff happening in `LowerCompare`, yes, there maybe a case for not doing that under minopts. Though if minopts throughput is the goal then it's best to measure, AFAIR some of those optimizations reduce the number of nodes and thus subsequent phases have less work to do. I'll give it a try and see what happens.

**Comment by mikedn** [comment]
I tried to remove all the optimization code from `LowerCompare` (almost all the code since only the very last `if` is needed on 64 bit) and I got an increase in instructions retired of 0.14-0.22%.

https://1drv.ms/x/s!Av4baJYSo5pjgrser0xvX51_iCj2OQ

That's a bit surprising. It may be that LSRA+CodeGen+Emit do a significant amount of per node work and that removing nodes improves throughput but 0.14% seems a bit much.

Still, it may be useful to split `LowerCompare` in 3 - `DecomposeLongCompare`, `OptimizeCompare` and `LowerCompare`. Then it's trivial to add a minopts check before calling `OptimizeCompare` if we ever find evidence that it improves throughput.

**Comment by BruceForstall** [comment]
This just happened to be the first thing I noticed that does a bunch of apparent optimization work; there might be others.

I think of MinOpts as the simplest, most reliable possible path through the JIT to generate legal code. This might not be the fastest, though it often has been overloaded to mean that as well. We use MinOpts as a fallback path when a noway_assert hits. We tell customers to annotate their functions with NoOptimization (aka minopts) if they encounter an optimization bug. @AndyAyersMS has talked about having a "fast path" that might include more inlining (MinOpts does none), for example. So, MinOpts could/should diverge from "fast path" at some point.

**Comment by mikedn** [comment]
> I think of MinOpts as the simplest, most reliable possible path through the JIT to generate legal code. 

I that case it certainly makes sense to not do all that work in `LowerCompare`. I'll take care of this.

**Comment by mikedn** [comment]
Let's continue in #15454

**Pull request merged**
