### PR TITLE
Move some local declaration into exceptionhandling.cpp

### PR DESCRIPTION
**Pull request by parjong**
This commit moves HandlerFn and ClrUnwindEx declaration from exceptionhandling.h into exceptionahandling.cpp as these are currently used  only in exceptionhandling.cpp.

### CODE REVIEW

**Comment by parjong** [comment]
@dotnet-bot test Windows_NT arm Cross Debug Build please

**Comment by janvorli** [comment]
@dotnet-bot test Windows_NT x86 CoreCLR Perf Tests Correctness please

**Comment by janvorli** [comment]
@dotnet-bot test Windows_NT x64 CoreCLR Perf Tests Correctness please

**Comment by janvorli** [comment]
@dotnet-bot test Tizen armel Cross Debug Build please

**Comment by janvorli** [comment]
@dotnet-bot test Tizen armel Cross Release Build please

**Pull request merged**
