### PR TITLE
Restore handling of __PassThroughArg for `--`

### PR DESCRIPTION
**Pull request by BruceForstall**
Fixes https://github.com/dotnet/coreclr/issues/19360

### CODE REVIEW

**Comment by BruceForstall** [comment]
Reverts part of https://github.com/dotnet/coreclr/pull/19291

**Comment by RussKeldorph** [comment]
If it works locally, I would merge before all CI jobs complete.  I don't think you're going to make the build more broken than it already is.

**Comment by BruceForstall** [comment]
Only builds that pass "extra" arguments are broken. That does NOT include the Jenkins builds, only, apparently, the Official Builds.

**Comment by AaronRobinsonMSFT** [comment]
Related: #19358

**Pull request merged**
