### PR TITLE
Add directions for debugging CoreClr on Linux

### PR DESCRIPTION
**Pull request by mikem8361**

### CODE REVIEW

**Comment by mikem8361** [comment]
@richlander could you review this doc change?

**Comment by OtherCrashOverride** [comment]
Is it possible to remotely debug CoreCLR on Linux from within Visual Studio 2015?  If not, that should probably be explicitly stated.

**Comment by mikem8361** [comment]
Hopefully my latest commit addresses your concern.

**Comment by OtherCrashOverride** [comment]
I think "Visual Studio 2015 RTM remote debugging isn't currently support." is probably better.  The confusion is whether this changed with release.

**Comment by OtherCrashOverride** [comment]
Thanks.  I know it seems pedantic but you would be amazed how often the question is asked.

**Pull request merged**
