### PR TITLE
Change how PAL file I/O functions treat symbolic links

### LINKED ISSUE #3450: FILEGetFileNameFromSymLink in PAL does not work correctly
When the target of a symbolic link is given as a relative path, FILEGetFileNameFromSymLink function (src/pal/src/file/file.cpp) attempts to resolve it relative to the current directory. This is incorrect. A relative symbolic link should be resolved relative to the parent directory that contains the symbolic link. For example, if /foo/bar is a symlink with a value of xyz, it should be resolved to /foo/xyz, not to xyz in the current directory.

I think it is questionable whether FILEGetFileNameFromSymLink should even exists. It is currently used by DeleteFileA, MoveFileExA, and RemoveDirectoryHelper. These functions try to resolve symlinks to their final destination before doing the delete or move. But this is against the expectation of normal Linux users. Also, deleting or moving the final destination makes the original symlink into a dangling link, which seems to be undesirable as well.

### PR DESCRIPTION
**Pull request by adityamandaleeka**
This change removes `FILEGetFileNameFromSymLink`, which attempted to resolve the target that a symbolic link pointed to (and would get it wrong for relative links).

It was being used in a few PAL functions for file/directory deletion and moving/renaming. For instance, deleting a symlink would delete the file it pointed to. With this change, those operations will work as expected (moving or deleting a symlink won't affect the target of the symlink).

I've also added checks for symlink handling in the PAL tests for `DeleteFileA `and `RemoveDirectoryA`.

@janvorli PTAL

Fixes #3450

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
Looks like the test changes introduce some conflicts with system headers on FreeBSD. I'll let the CI continue to see whether there are any other problems.

**Comment by adityamandaleeka** [comment]
I've now also removed `CorUnix::InternalDeleteFile` since it was making OS X behave differently than other non-Windows platforms (using the `SYS_delete` syscall instead of `unlink`). `SYS_delete` doesn't seem to work with symlinks at all, and there doesn't seem to be any compelling reason to have OS X behavior be different from other platforms.

**Comment by adityamandaleeka** [comment]
@janvorli @sergiy-k PTAL

**Comment by janvorli** [comment]
Oh, I am sorry, I have thought I have already said LGTM.

**Comment by sergiy-k** [comment]
LGTM

**Pull request merged**
