### PR TITLE
Default gcAllowVeryLargeObjects to true

### LINKED ISSUE #8847: gcAllowVeryLargeObjects: Add switch or allow by default in .NET Core
Besides setting an environment variable (`COMPlus_gcAllowVeryLargeObjects=1`) there is no way to set `gcAllowVeryLargeObjects` in .NET Core like in `app.config` for .NET Framework:
```xml
<configuration>
  <runtime>
    <gcAllowVeryLargeObjects enabled = "true" />
  </runtime>
</configuration>
```
Either add a switch for this, or enable this by default. Or other options that could be discussed here.

This originates in https://github.com/dotnet/corefx/pull/14396 where this switch is needed to be able to test clearing managed arrays with byte size larger than `uint.MaxValue`.

cc: @jkotas

### PR DESCRIPTION
**Pull request by mikedn**
It seems to me that this option should be enabled by default in a new framework such as .NET Core. 

The only reason I can think of why one might want to disable this option is poorly written unsafe code that assumes that objects can't be larger than 2GB and thus offsets can be represented using `int`. Any compat concerns?

Fixes #8847

### CODE REVIEW

**Comment by jkotas** [comment]
@Maoni0 Could you please take a look as well?

**Comment by jkotas** [comment]
@mikedn There are a few failing tests

**Comment by mikedn** [comment]
@jkotas Yep, those tests were expecting an OutOfMemoryException to be thrown. I increase the array length so they always get the expected exception due to array length being limited to 2^31.

**Comment by sbomer** [comment]
@dotnet-bot test Ubuntu x64 Formatting please
@dotnet-bot test Windows_NT x64 Formatting

**Comment by sbomer** [comment]
FYI, the formatting job failure should be [fixed](https://github.com/dotnet/jitutils/commit/470d8d6908fc0cb85f53de91ea41ba1a20945a66).

**Comment by Maoni0** [comment]
fine by me.

**Comment by jkotas** [comment]
@mikedn The tests are still failing. Do they pass for you locally?

Thank you for fixing this!

**Comment by mikedn** [comment]
@jkotas They passed before checkin. Now that I increased my pagefile size they fail too. I didn't realize that MD arrays can actually have more than 2 billion elements, back to the drawing board.

**Comment by mikedn** [comment]
Yep, MD arrays can have up to 4 billion elements, updated tests accordingly.

**Pull request merged**
