### PR TITLE
Add test cases in directory Directed/cmov

### PR DESCRIPTION
**Pull request by libengu**
Add test cases in directory Directed/cmov. Logical operator
tests where many of the operations emit cmov instruciton on
x86\x64. Related proj, config, and sln files added and updated.
Passed build, buildtest, runtest.

### CODE REVIEW

**Comment by libengu** [comment]
@mmitche PTAL

**Comment by libengu** [comment]
@russellhadley

**Comment by russellhadley** [comment]
Looks fine.  I'd still like to understand how the tagging will work.  (filtering with out deleting)  The delete step will quickly get intractable.

**Comment by libengu** [comment]
@russellhadley It will be tracked here https://github.com/dotnet/llilc/issues/466. As I am exploring to rewrite CoreCLR runtest in Python, this is one of the issue I want to solve.

**Comment by mmitche** [comment]
LGTM

**Comment by russellhadley** [comment]
I think the tagging has more to do with how we run in xunit and synthesize attributes.  @mmitche can you comment here?

**Comment by mmitche** [comment]
@libengu There are two separate issues here:

1) How do we generate metadata for each test so that we can exclude/include them through options to xunit.
2) How do we control xunit itself to do that selection.

Your issue is more about 2.  For 1, we want to generate xunit attributes similar to the ones used in corefx based on properties in the project file associated with each test.

**Comment by libengu** [comment]
@mmitche Thanks. I will try to find out about controlling xunit for the selection.

**Pull request merged**
