### PR TITLE
Re-enable tests after fixing 18295

### PR DESCRIPTION
**Pull request by CarolEidt**
@echesakovMSFT PTAL

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstress2 Build and Test

**Comment by CarolEidt** [comment]
@echesakovMSFT - I believe I've triggered the corefx_baseline test runs that include these re-enabled tests. Could you confirm?

**Comment by CarolEidt** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by echesakovMSFT** [comment]
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstress1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstress2 Build and Test

**Comment by echesakovMSFT** [comment]
@CarolEidt Just added jitstress legs for Ubuntu arm to get more coverage

**Comment by echesakovMSFT** [comment]
LGTM

**Comment by CarolEidt** [comment]
@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstress1 Build and Test

**Comment by CarolEidt** [comment]
@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib - the arm corefx legs seem to intermittently get I/O-related failures in one of:

System.Net.Tests.ServicePointManagerTest.FindServicePoint_PropertiesRoundtrip [FAIL] 
System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteGetHostByName_EmptyString_ReturnsHostName [FAIL]

My inclination is to ignore these and check this in (the test I'm re-enabling is passing, and that's the only change in this PR).

**Pull request merged**
