### PR TITLE
Move Package config to test/src directory

### PR DESCRIPTION
**Pull request by swaroop-sridhar**
The test/src/JIT/config/... has package configuration templates
that are used by some JIT tests. The same configurations are
planned to be used for tests outside the JIT directory
(new GC tests to be ported). So, move the configurations to
the test/src root directory.

### CODE REVIEW

**Comment by swaroop-sridhar** [comment]
@richardlford please review.

**Comment by swaroop-sridhar** [comment]
Updated the source branch to change the new tests that were since added.

**Comment by swaroop-sridhar** [comment]
@richardlford  or @pgavlin please review.

**Comment by swaroop-sridhar** [comment]
@dotnet-bot retest this please

**Comment by swaroop-sridhar** [comment]
@dotnet-bot test this please

**Comment by pgavlin** [comment]
LGTM assuming tests pass.

**Pull request closed without merging**
