### PR TITLE
[x86/Linux] Enable CI unittest

### PR DESCRIPTION
**Pull request by hseok-oh**
- Copy test binary from x86 Windows build
- Copy CoreFX managed from arm CoreFX managed build
- Add archival

### CODE REVIEW

**Comment by hseok-oh** [comment]
@jashook Tests in dev/unix_test_workflow unittest works well and I cannot found any side effects on other jobs. 

https://ci.dot.net/job/dotnet_coreclr/job/dev_unix_test_workflow/job/x86_release_ubuntu_tst/2/
https://ci.dot.net/job/dotnet_coreclr/job/dev_unix_test_workflow/job/x86_debug_ubuntu_tst/2/
https://ci.dot.net/job/dotnet_coreclr/job/dev_unix_test_workflow/job/x86_checked_ubuntu_tst/2/
https://ci.dot.net/job/dotnet_coreclr/job/dev_unix_test_workflow/job/x86_release_ubuntu_tst_prtest/1/
https://ci.dot.net/job/dotnet_coreclr/job/dev_unix_test_workflow/job/x86_debug_ubuntu_tst_prtest/1/
https://ci.dot.net/job/dotnet_coreclr/job/dev_unix_test_workflow/job/x86_checked_ubuntu_tst_prtest/1/
(failure because of x86/linux bug)

It includes #13786, #14185, and #14186.
(But it excludes #14169, #14170 because these PRs are related to dev/unix_test_workflow branch specific issue)

I think we can merge this PR. PTAL

Related issue: #9903
Related PR: #12897

**Comment by hseok-oh** [comment]
@dotnet-bot test ci please

**Comment by janvorli** [comment]
@hseok-oh I am sorry the change was not merged in yet. I have just fixed a conflict in the change with the latest master branch state and I am planning to merge it after the CI completes.
As per the #9903 tracking the CI support, could you please share the Dockerfiles that you've used to build the docker images used in the CI so that we can create official ones to use in both CI and official builds based on them?

**Comment by hseok-oh** [comment]
@janvorli You can check dockerfile to run x86/linux at https://github.com/hseok-oh/dockerfiles/blob/master/docker-image-run/i386/Dockerfile
To build x86/linux coreclr, I'm add just rootfs in arm/linux build docker image.

**Comment by janvorli** [comment]
@hseok-oh thank you!

**Comment by janvorli** [comment]
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test please

**Comment by janvorli** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by janvorli** [comment]
@hseok-oh there were conflicts due to recent changes in the repo. I have tried to resolve them directly on gihub, which seemed to work, created a commit with the fix, but the GitHub still complains that there are conflicts that need to be resolved. 
Could you please sync your branch and resolve the conflicts yourselves?

**Comment by hseok-oh** [comment]
@janvorli OK. I'll try to rebase this PR based on recent master.

**Comment by hseok-oh** [comment]
@dotnet-bot test ci please

**Comment by hseok-oh** [comment]
@janvams I've updated to rebase it based on recent master.

**Pull request merged**
