### PR TITLE
Clear syncblock early when `VERIFY_HEAP && DEBUG` to prevent verification asserts.

### PR DESCRIPTION
**Pull request by VSadov**
Fixes:#24879

### CODE REVIEW

**Comment by VSadov** [comment]
CC: @janvorli

**Comment by VSadov** [comment]
This PR is green. That is expected an by itself does not tell us much. - It would be green without the fix too.

To verify that we understand the problem and that the fix works I did the following -

I have created a PR with artificially introduced delays after extending "alloc_allocated" and before cleaning up syncblock - https://github.com/dotnet/coreclr/pull/24978

It produced the failures as in #24879 
- that validates the theory for how the failures occur.

Then I cherry-picked this fix into that PR and failures no longer reproduced (even with delays still in place) 
- that validates that the fix works.

**Comment by VSadov** [comment]
Just to be clear - this PR does not contain delays. 

That was additional instrumentation added to a PR that I do not intend to merge. 
The purpose of that PR was just to demonstrate "before" and "after" behavior more deterministically.

**Comment by VSadov** [comment]
Thanks!

**Comment by VSadov** [comment]
I assume this does not need to be ported to a preview/release branch. 
Since it is debug only and a relatively rare, it does not look like it would meet the bar.

**Comment by Maoni0** [comment]
that's correct.

**Pull request merged**
