### PR TITLE
Fix Attribute implementations of Equals and GetHashCode

### LINKED ISSUE #6232: Default implementation in Attribute for GetHashCode and Equals is broken
In both implementations, it calls the following:
```
FieldInfo[] fields = type.GetFields(BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance);
```
This does not return private inherited fields of base classes, hence the code becomes nonsensical when you have the following:
```
class A : Attribute 
{
   public int Foo {get;set;}
}

class B : A
{
}
```
All instances of `B` will now have the same hashcode and be equal.

The correct way should be to get all the fields of all base types up to, but excluding `Attribute`.

This bug is present on .NET desktop too, and have probably been like that forever.

### PR DESCRIPTION
**Pull request by leppie**
Properly deals with derived types. 

Fix #6232

Please advise where to provide tests.

Note: This fix actually seems to match the same behavior as CoreRT.

**Notes:**
`Type.GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic)` will **NOT** return any non-visible fields from base classes. `NonPublic` only applies to declared fields in the type it is called on. `FlattenHierarchy` does not help here as it applies only to `static` members, but it's description is actually appropriate here. I suggest a documentation update.

This came as a surprise to me too, even after 15 years of .NET.

PS: This might be the oldest bug in existence. It is present in .NET 2.0 and the rotor sources. Unfortunately I cannot verify it again anything earlier than .NET 2.

### CODE REVIEW

**Comment by jkotas** [comment]
> This fix actually seems to match the same behavior as CoreRT.

@AtsushiKan Do we want to take this change, to reduce differences between CoreCLR and CoreRT?

**Comment by AtsushiKan** [comment]
Yep, this looks a good thing to fix.

**Comment by leppie** [comment]
@jkotas @AtsushiKan Will any of the same reflection access restrictions apply as with CoreRT? IOW, should the virtual route be taken to so every type gets it's own fields?

**Comment by danmosemsft** [comment]
@dotnet-bot test this please
@jkotas any CR feedback for @leppie ?

**Comment by jkotas** [comment]
@leppie Could you please exclude the test from this PR, and add it as xunit test to corefx instead? We prefer to have tests for framework APIs in corefx. Thank you!

The change looks good to me otherwise.

**Comment by leppie** [comment]
@jkotas Will do, but probably only during the weekend

**Comment by leppie** [comment]
@jkotas Rebased and removed the test. Will get on the test next.

**Comment by leppie** [comment]
@jkotas Now that the fix is in, can I build a test for it yet on `corefx`? If so, had a look, most natural existing place is `System.Runtime`, correct? (I do feel these should live in `mscorlib` tests)

**Comment by jkotas** [comment]
> most natural existing place is System.Runtime, correct?

Correct. It may fit well into existing http://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/AttributeTests.cs

**Pull request merged**
