### PR TITLE
Ensure we run the Crossgened test executable in R2R tests

### PR DESCRIPTION
**Pull request by wtgodbe**
CC @RussKeldorph @gkhanna79 

This will fix the Crossgen test failures introduced by https://github.com/dotnet/coreclr/pull/10525. Have tested that a test .cmd with the expected outcome will pass locally, currently in the process of testing building the branch from scratch & running tests.

### CODE REVIEW

**Comment by wtgodbe** [comment]
@dotnet-bot test Windows_NT Release pri1r2r

**Comment by wtgodbe** [comment]
@dotnet-bot test Ubuntu Release pri1r2r

**Comment by wtgodbe** [comment]
Tests seem to pass locally, will wait for them to pass in the CI as well.

**Comment by mazong1123** [comment]
Just be curious: the CI passed when I submitted #10525 . Is this test not being added to CI 
at that time?

**Comment by wtgodbe** [comment]
@mazong1123 that's correct, the R2R tests in the background. They only run in PR's if you request them (as I did above).

**Comment by gkhanna79** [comment]
CI has test failures @wtgodbe for R2R.

**Comment by wtgodbe** [comment]
Yeah, the Windows job had 1 test fail, which looks like a real issue that should be investigated - as for the Ubuntu job, it failed in trying to precompile ildasmrc.dll - it looks like similar failures have existed for a long time (about a month) - https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_release_ubuntu_pri1r2r_flow/. I'm guessing we need to either add a few .dll's to the exclusion list at https://github.com/dotnet/coreclr/blob/master/tests/skipCrossGenFiles.x64.txt, or rethink the way we do crossgening of Core_Root on non-windows.

**Comment by gkhanna79** [comment]
This is the Windows failure:

```
17:21:19         Error: Could not load file or assembly 'CSharpPart, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
17:21:19         Error compiling CSharpPart.org: Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
17:21:19         Error: compilation failed for "CSharpPart.org" (0x80131621)
17:21:19         
17:21:19   
17:21:19   Return code:      1
17:21:19   Raw output file:  
```    

Does it fail for you locally? If it does, based upon the error message, it could be related to the engineering change you are making. Can you confirm, just for this test, if the original binary was not renamed to .org, does the test pass?

**Comment by gkhanna79** [comment]
Ubuntu Failure is the following:

```
21:21:51 Unable to precompile /mnt/j/workspace/dotnet_coreclr/master/x64_release_ubuntu_pri1r2r_tst/bin/tests/Windows_NT.x64.Release/Tests/coreoverlay/superpmi-shim-simple.dll.
21:21:51 Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
21:21:51 Copyright (c) Microsoft Corporation.  All rights reserved.
21:21:51 
21:21:51 Error compiling /mnt/j/workspace/dotnet_coreclr/master/x64_release_ubuntu_pri1r2r_tst/bin/tests/Windows_NT.x64.Release/Tests/coreoverlay/superpmi-shim-simple.dll: The module was expected to contain an assembly manifest. (Exception from HRESULT: 0x80131018)
21:21:51 Error: compilation failed for "/mnt/j/workspace/dotnet_coreclr/master/x64_release_ubuntu_pri1r2r_tst/bin/tests/Windows_NT.x64.Release/Tests/coreoverlay/superpmi-shim-simple.dll" (0x80131018)
21:21:51 Build step 'Execute shell' marked build as failure
```

The infrastructure appears to be crossgenning native binary and failing - can you confirm if that is the case?

**Comment by wtgodbe** [comment]
@gkhanna79 where are you seeing the superpmi-shim-simple.dll failure? I only see ildasmrc.dll failing to precompile. Either way, this lines up with the other Ubuntu R2R failures that have been happening for the last month - we're trying to crossgen native binaries. I'll look into that. 

As for the Windows failure, I've confirmed the same happens locally, though the directory looks as expected, and the .org file is present after running the .cmd. Also, if I modify the .cmd to use the original extensions from before this change, crossgen happens successfully, and I can rename the .ni.exe to '.exe' and have the test pass. Not sure what's special about that particular test...

**Comment by wtgodbe** [comment]
Think I found the problem for non-Windows: https://github.com/dotnet/coreclr/blob/master/tests/runtest.sh#L410

The code for COR_E_ASSEMBLYEXPECTED is 0x80131018, which we do see in the error log output for the failed crossgen - I suspect that maybe up until a month ago, we printed 'COR_E_ASSEMBLYEXPECTED' in the logs, but now pring the error code instead. I'll see what happens if I change that line to use the hex code instead.

**Comment by wtgodbe** [comment]
I sent some jobs to the CI with the change I mentioned above, and we no longer fail with trying to precompile the native assemblies from before, but we do get the following failure trying to precompile System.Private.Corelib.dll:

> 13:02:19 Unable to precompile /mnt/j/workspace/dotnet_coreclr/master/x64_release_ubuntu_pri1r2r_tst_prtest/bin/tests/Windows_NT.x64.Release/Tests/coreoverlay/System.Private.CoreLib.dll.
13:02:19 Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
13:02:19 Copyright (c) Microsoft Corporation.  All rights reserved.
13:02:19 
13:02:19 Could not load file or assembly '/mnt/j/workspace/dotnet_coreclr/master/x64_release_ubuntu_pri1r2r_tst_prtest/bin/tests/Windows_NT.x64.Release/Tests/coreoverlay/System.Private.CoreLib.dll'. An attempt was made to load a program with an incorrect format.
13:02:19  (Exception from HRESULT: 0x8007000B)
13:02:19 Error: compilation failed for "/mnt/j/workspace/dotnet_coreclr/master/x64_release_ubuntu_pri1r2r_tst_prtest/bin/tests/Windows_NT.x64.Release/Tests/coreoverlay/System.Private.CoreLib.dll" (0x8007000b)

I am, however, able to successfully precompile System.Private.Corelib.dll on my Ubuntu14.04 VM locally. @gkhanna79 any idea what's going on here?

**Comment by gkhanna79** [comment]
Are you synced to latest when trying this?

**Comment by wtgodbe** [comment]
@dotnet-bot test Windows_NT Release pri1r2r

**Comment by wtgodbe** [comment]
@dotnet-bot test Ubuntu Release pri1r2r

**Comment by wtgodbe** [comment]
@dotnet-bot test Windows_NT Release pri1r2r

**Comment by wtgodbe** [comment]
@dotnet-bot test Ubuntu Release pri1r2r

**Comment by wtgodbe** [comment]
@dotnet-bot test Windows_NT Release pri1r2r

**Comment by wtgodbe** [comment]
@dotnet-bot test Ubuntu Release pri1r2r

**Comment by wtgodbe** [comment]
@dotnet-bot test Windows_NT Release pri1r2r

**Comment by wtgodbe** [comment]
@dotnet-bot test Ubuntu Release pri1r2r

**Comment by wtgodbe** [comment]
@dotnet-bot test Tizen armel Cross Release Build

**Comment by wtgodbe** [comment]
@dotnet-bot test Ubuntu Release pri1r2r

**Comment by wtgodbe** [comment]
@dotnet-bot test Windows_NT Release pri1r2r

**Comment by gkhanna79** [comment]
```
20:15:53 FAILED   - baseservices/threading/interlocked/add/CheckAddInt/CheckAddInt.sh
20:15:53                BEGIN EXECUTION
20:15:53                /mnt/j/workspace/dotnet_coreclr/master/x64_release_ubuntu_pri1r2r_tst_prtest/bin/tests/Windows_NT.x64.Release/Tests/coreoverlay/corerun CheckAddInt.exe /start:2147483647 /add:100
20:15:53                Managed assembly not found: No such file or directory
20:15:53                Expected: 100
20:15:53                Actual: 255
20:15:53                END EXECUTION - FAILED
```

Were these passing earlier? How about you merge the PR and look into if this failure persists?

**Comment by wtgodbe** [comment]
I haven't seen those failures before, and the build history for r2r jobs doesn't go back far enough to see if they were failing before the infra issue popped up. I'll merge this & keep an eye on mission control.

**Pull request merged**
