### PR TITLE
Small bug fixes on "perf.groovy"

### PR DESCRIPTION
**Pull request by jorive**
- `submission-metadata` option is `--user-email`, not `--user`
- We need to escape user input. On batch, " -> ""

### CODE REVIEW

**Comment by jorive** [comment]
@dotnet-bot test ci please

**Comment by jorive** [comment]
The "Windows_NT x64 full_opt ryujit CoreCLR Perf Tests Correctness" failure is the bug I am fixing here:
```
D:\j\w\perf_perflab_---89ec9f56>set "BENCHVIEWNAME=coreclr private Small bug fixes on \"perf.groovy\"" 

D:\j\w\perf_perflab_---89ec9f56>set "BENCHVIEWNAME=coreclr private Small bug fixes on \perf.groovy\" 

D:\j\w\perf_perflab_---89ec9f56>py "D:\j\w\perf_perflab_---89ec9f56\Microsoft.BenchView.JSONFormat\tools\submission-metadata.py" --name "coreclr private Small bug fixes on \perf.groovy\" --user "dotnet-bot@microsoft.com" 
usage: submission-metadata.py [-h] --name NAME --user-email USER_EMAIL
                              [--description DESCRIPTION]
                              [--timestamp TIMESTAMP] [--cuid CUID]
                              [-o <Output json file name>]
submission-metadata.py: error: the following arguments are required: --user-email
```

**Comment by adiaaida** [comment]
LGTM. When did that change happen?

**Comment by DrewScoggins** [comment]
We have always had both of these bugs.  The quotes thing had just not hit us or we had not noticed.  Same with the --user vs --user-email thing.

**Comment by jorive** [comment]
@adiaaida the actuall option to `submission-metadata` is `--user-email` but a bug on the parser allowed for shorter version (I'll be fixing this on next script update).
w.r.t. the double-quotes on batch, they are a special character. It previously broke and we tried removing them, but it did not cover all cases. This is the actual case for double quotes.

**Comment by DrewScoggins** [comment]
LGTM

**Pull request merged**
