### PR TITLE
Obey GTF_REVERSE_OPS in fgWalkTreePost.

### PR DESCRIPTION
**Pull request by pgavlin**
This particular sort of tree walk should correspond to the
tree execution order.

### CODE REVIEW

**Comment by pgavlin** [comment]
This change produces no diffs in mscorlib; I'm running a more expansive set of diffs now.

**Comment by pgavlin** [comment]
@dotnet/jit-contrib PTAL

**Comment by CarolEidt** [comment]
The changes look good to me. However, this seems like the kind of change that could impact the legacy code paths, so it might be prudent to run the full set of internal diffs.

**Comment by pgavlin** [comment]
> this seems like the kind of change that could impact the legacy code paths, so it might be prudent to run the full set of internal diffs.

Sure, I can do that.

**Comment by pgavlin** [comment]
The other option I considered was to add another tree walk function, `fgWalkTreeInExecutionOrder`, to do this sort of walk. That change would be safer w.r.t. diffs and may be clearer.

**Comment by CarolEidt** [comment]
I agree that a separate tree walk would be safer, but I'm not sure it would be clearer - to me, it seems like tree walks should always be in execution order. But either way is fine with me.

**Comment by briansull** [comment]
We have a tree walk that calculates the weighted local variable ref counts.
It needs to visit every node but has no requirement that it visit them in any particular order.

**Comment by pgavlin** [comment]
Interestingly enough, it looks like legacy builds never use this function--its only callers are in lowering. I'm running x86 diffs now to be sure. The larger set of x64 diffs was clean.

**Comment by pgavlin** [comment]
Legacy diffs are also clean.

**Comment by CarolEidt** [comment]
@pgavlin - Thanks for doing the legacy diffs!

**Pull request merged**
