### PR TITLE
Streamline LSRA resolution

### PR DESCRIPTION
**Pull request by CarolEidt**
Only do resolution when required, and only for variables that may need it.

### CODE REVIEW

**Comment by CarolEidt** [comment]
@sivarv @pkukol PTAL.
This reduces the % time spent in LSRA resolution phase when crossgen-ing System.Private.CoreLib from ~1.6% to ~1.2%. There are zero diffs against desktop.
I plan to look into the benefits of not splitting any edges (always resolving on the stack), at least for MinOpts, as a future change.

**Comment by sivarv** [comment]
:shipit:

**Comment by sivarv** [comment]
Looks Good.
I am assuming that you will be running LSRA stress on x86 and amd64 before merging.

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT jitstressregs0x10
@dotnet-bot test Windows_NT jitstressregs0x80
@dotnet-bot test Windows_NT jitstressregs1
@dotnet-bot test Windows_NT jitstressregs2
@dotnet-bot test Windows_NT jitstressregs3
@dotnet-bot test Windows_NT jitstressregs4
@dotnet-bot test Windows_NT jitstressregs8

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT jitstressregs0x10
@dotnet-bot test Windows_NT jitstressregs0x80
@dotnet-bot test Windows_NT jitstressregs1
@dotnet-bot test Windows_NT jitstressregs2
@dotnet-bot test Windows_NT jitstressregs3
@dotnet-bot test Windows_NT jitstressregs4
@dotnet-bot test Windows_NT jitstressregs8

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT x86 Checked Build and Test

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT jitstressregs0x10
@dotnet-bot test Windows_NT jitstressregs0x80
@dotnet-bot test Windows_NT jitstressregs1
@dotnet-bot test Windows_NT jitstressregs2
@dotnet-bot test Windows_NT jitstressregs3
@dotnet-bot test Windows_NT jitstressregs4
@dotnet-bot test Windows_NT jitstressregs8

**Comment by CarolEidt** [comment]
@dotnet-bot help

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT x86 Checked jitstressregs0x10
@dotnet-bot test Windows_NT x86 Checked jitstressregs0x80
@dotnet-bot test Windows_NT x86 Checked jitstressregs1
@dotnet-bot test Windows_NT x86 Checked jitstressregs2
@dotnet-bot test Windows_NT x86 Checked jitstressregs3
@dotnet-bot test Windows_NT x86 Checked jitstressregs4
@dotnet-bot test Windows_NT x86 Checked jitstressregs8

**Pull request merged**
