### PR TITLE
Fix cmd exit codes

### PR DESCRIPTION
**Pull request by mmitche**
Fix exit codes in build.cmd/buildtest/cmd/runtest.cmd to report if there is a failure.

Some recently added tests were failing because of this error.  I've removed these tests for now.  I kept this as a separate commit for the purposes of easy-undo.  Let me know if this should be squashed instead.

/cc @pgavlin

### CODE REVIEW

**Comment by kangaroo** [comment]
I think the commits should be split.

In addition, why should we remove the tests, if they're valid tests we should fix the failure -- no?

**Comment by pgavlin** [comment]
@kangaroo right now the tests are failing to build because the sources are a bit mangled. I have a fix for this in flight.

**Comment by kangaroo** [comment]
@pgavlin great.  I'd rather see 1b52a8e dropped from this PR like I said, and just put in another one which fixes the broken tests.  It seems more history clean to me.

Thoughts?

**Comment by pgavlin** [comment]
I'll leave that up to @mmitche.

**Comment by mmitche** [comment]
We should, but I'd like to get a clean run and a real fix could take longer.  I'll make sure to file an issue about it.

Sent from my Windows Phone
________________________________

**Comment by mmitche** [comment]
@kangaroo @pgavlin I took a look at the failing tests and couldn't see anything obvious straight out.  I filed 1036 and 1037 for the runtime failure and kept the separate commits for now.

/cc @richardlford

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by pgavlin** [comment]
LGTM. Thanks for doing this.

**Pull request merged**
