### PR TITLE
remove fedora 23 from CI

### PR DESCRIPTION
**Pull request by danmosemsft**
It was already removed from CoreFX -- I didn't realize that would have downstream effects.

@wtgodbe @gkhanna79

### CODE REVIEW

**Comment by wtgodbe** [comment]
LGTM

@dotnet-bot test CI please

**Comment by danmosemsft** [comment]
@wtgodbe @gkhanna79 this means there is no Fedora in the CoreCLR CI. Should we add, eg., Fedora 25?

**Comment by danmosemsft** [comment]
@dotnet-bot test windows_nt x64 release priority 1 build and test please (https://github.com/dotnet/coreclr/issues/10673)

**Comment by gkhanna79** [comment]
@wtgodbe Added support for Fedora 25 in official builds. Given that, please add corresponding CI support as well.

**Comment by danmosemsft** [comment]
@wtgodbe I added https://github.com/dotnet/coreclr/issues/10675 for that. Sounds like you have it.

**Pull request merged**
