### PR TITLE
Add SIMD get_Item lower bounds test

### LINKED ISSUE #14793: SIMD VectorGetIndexerOutOfRange add negative index test.
VectorGetIndexerOutOfRange does not check for negative index range check.

### PR DESCRIPTION
**Pull request by sdmaclea**
@BruceForstall This is a draft of a test.  I have not tested it (nor do I plan to).  Since it is mostly a cut paste of code from the same function, it should just work.

Fixes #14793

### CODE REVIEW

**Comment by sdmaclea** [comment]
Related to #14792

**Comment by sdmaclea** [comment]
@dotnet-bot test this please

**Comment by sdmaclea** [comment]
This originally failed on x86 & x64 before #14792 was merged.  Now that it has merged, retriggered tests

**Comment by sdmaclea** [comment]
@BruceForstall OSX is failing this test, it is not clear why.  arm64 failure looks unrelated.

**Comment by BruceForstall** [comment]
It looks like the OSX "flow job" build that the test depends on used an earlier commit than the one with your fix:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_osx10.12_prtest/8560/consoleText
```
Commit message: "Merge 3095a4df03a5711da6b848a773359238990d8369 into 019615e9f294a50cdc1d66747c5f05e6404ff76c"
```

I'm not sure why that happens. Maybe @jashook or @RussKeldorph can explain.

It looks like the arm64 issue is a newly exposed GC issue; I've seen that in another PR as well.

@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by BruceForstall** [comment]
This time, a Jenkins infrastructure failure. https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_osx10.12_flow_prtest/8853/

One more try

@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by sdmaclea** [comment]
test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Pull request merged**
