### PR TITLE
fix syntax error in build.sh

### PR DESCRIPTION
**Pull request by Buyduck**
fixed:
`./build.sh: line 404: [: : integer expression expected`

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
cc: @dpodder

**Comment by dpodder** [comment]
LGTM, thanks @adityamandaleeka. Out of curiosity what shell caught this? This was missed by my manual testing as well as all of CI. 😕

**Comment by Buyduck** [comment]
@dpodder , default ubuntu 16.04 bash (GNU bash, version 4.3.46(1)-release) :S

**Comment by dpodder** [comment]
:S

**Pull request merged**
