### PR TITLE
Fix ARMv8.1 atomics disassembly

### LINKED ISSUE #20721: ARM64 atomics: crash with ldaddal instruction
Enable JIT_FLAG_HAS_ARM64_ATOMICS, perhaps by setting it manually in compiler.cpp,  Compiler::compCompile(). Then do a PMI run over System.Private.CoreLib.dll. The method `System.SharedStatics:AddMemoryFailPointReservation(long):long` has an interlocked add -- XADD -- that is generated with a ldaddal instruction (when atomics are enabled). But it fails with a `NO_WAY("unexpected instruction")` in `emitter::emitInsTargetRegSize` during emission. (Note: it will attempt to re-jit in MinOpts mode.)

### PR DESCRIPTION
**Pull request by mikedn**
This is just an oversight in the emitter display code - it does not handle ARMv8.1 atomics such as `ldaddal`. Initially I added all these instructions to `emitInsTargetRegSize` but then decided that this is really the wrong way to do this. The actual instruction encoder does not use `emitInsTargetRegSize` and instead uses the size from `instrDesc` and the instruction code. I don't see any reason for the display code to use different logic.

Only a few of these instructions are used `swpal`, `staddl` and `ldaddal` in `genLockedInstructions` and `casal` in `genCodeForCmpXchg`. 

I also tried to enable the emitter "unit tests" and found that it passes the wrong instruction size for byte and half instructions. While these instructions do operate on byte and half word memory location, the registers they use are always 32 bit.

Fixes #20721

### CODE REVIEW

**Comment by mikedn** [comment]
Example:
```C#
        static int i4;
        static long i8;

        [MethodImpl(MethodImplOptions.NoInlining)]
        static long Test()
        {
            Interlocked.CompareExchange(ref i4, 4, 2);
            Interlocked.CompareExchange(ref i8, 4, 2);
            Interlocked.Exchange(ref i4, 4);
            Interlocked.Exchange(ref i8, 8);
            Interlocked.Add(ref i4, 4);
            Interlocked.Add(ref i8, 4);
            return Interlocked.Add(ref i4, 2) + Interlocked.Add(ref i8, 2);
        }
```
generates
```asm
        D29C2000          movz    x0, #0xe100
        F2A7F920          movk    x0, #0x3fc9 LSL #16
        F2CFFFA0          movk    x0, #0x7ffd LSL #32
        52800081          mov     w1, #4
        52800042          mov     w2, #2
        88E2FC01          casal   w2, w1, [x0]
        D5033BBF          dmb     ish
        D29C1E00          movz    x0, #0xe0f0
        F2A7F920          movk    x0, #0x3fc9 LSL #16
        F2CFFFA0          movk    x0, #0x7ffd LSL #32
        D2800042          mov     x2, #2
        C8E2FC01          casal   x2, x1, [x0]
        D5033BBF          dmb     ish
        D29C2000          movz    x0, #0xe100
        F2A7F920          movk    x0, #0x3fc9 LSL #16
        F2CFFFA0          movk    x0, #0x7ffd LSL #32
        B8E18000          swpal   w1, w0, [x0]
        D5033BBF          dmb     ish
        D29C1E00          movz    x0, #0xe0f0
        F2A7F920          movk    x0, #0x3fc9 LSL #16
        F2CFFFA0          movk    x0, #0x7ffd LSL #32
        D2800101          mov     x1, #8
        F8E18000          swpal   x1, x0, [x0]
        D5033BBF          dmb     ish
        D29C2000          movz    x0, #0xe100
        F2A7F920          movk    x0, #0x3fc9 LSL #16
        F2CFFFA0          movk    x0, #0x7ffd LSL #32
        52800081          mov     w1, #4
        B8E10000          ldaddal w1, w0, [x0]
        D5033BBF          dmb     ish
        D29C1E00          movz    x0, #0xe0f0
        F2A7F920          movk    x0, #0x3fc9 LSL #16
        F2CFFFA0          movk    x0, #0x7ffd LSL #32
        F8E10000          ldaddal x1, x0, [x0]
        D5033BBF          dmb     ish
        D29C2000          movz    x0, #0xe100
        F2A7F920          movk    x0, #0x3fc9 LSL #16
        F2CFFFA0          movk    x0, #0x7ffd LSL #32
        52800041          mov     w1, #2
        B8E10000          ldaddal w1, w0, [x0]
        D5033BBF          dmb     ish
        0B010000          add     w0, w0, w1
        93407C00          sxtw    x0, x0
        D29C1E01          movz    x1, #0xe0f0
        F2A7F921          movk    x1, #0x3fc9 LSL #16
        F2CFFFA1          movk    x1, #0x7ffd LSL #32
        D2800042          mov     x2, #2
        F8E20021          ldaddal x2, x1, [x1]
        D5033BBF          dmb     ish
        8B010000          add     x0, x0, x1
        8B020000          add     x0, x0, x2
```
The encoding does appear to be correct, according to the ARM manual. I don't have any ARM hardware to test that.

**Comment by mikedn** [comment]
As a side observation - I was expecting that `Interlocked.Add` with unused result generates `staddl`, at least that's what `genLockedInstructions` seems to be trying. But it doesn't happen, it always generates `ldaddal`.

**Comment by mikedn** [comment]
OSX failed with the typical java.nio.channels.ClosedChannelException

@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
@mikedn thanks!

**Pull request merged**
