### PR TITLE
Remove JIT_FEATURE_SSA_SKIP_DEFS.

### PR DESCRIPTION
**Pull request by pgavlin**
This symbol is always defined to `1`. Remove it and its associated
dead code.

### CODE REVIEW

**Comment by pgavlin** [comment]
@schellap @briansull @dotnet/jit-contrib PTAL

**Comment by BruceForstall** [comment]
Does anyone know why this was ever put under #if in the first place? It's never been set to zero. I thought Dave had some idea that it would be for some reason.

**Comment by pgavlin** [comment]
From Dave's original changeset:

> We add SSA phi definitions at the start of basic blocks.  Eventually,
these will be "real" statements recognized by the back end
(materialized as copys where necessary).  For the present, added 
JIT_FEATURE_SSA_SKIP_DEFS, which marks uses of the new function
FistNonPhiDef(), which returns the first non-phi defn in a basic
block.  We use that in a number of places to make things work, for
now, just as they used to.

**Comment by CarolEidt** [comment]
IMO, even when/if we support general/non-conventional SSA, where we allow the srcs and dsts of a phi to interfere, we will still want to skip the phis in most cases, and the phis would, in any case, probably require separate handing.
The changes look good to me.

**Comment by pgavlin** [comment]
Tests failed to run due to what seems to be a package restore issue:
```
11:12:24 D:\j\workspace\x86_lb_checke---9877589b\tests\tests.targets(47,5): error MSB4062: The "Xunit.Runner.MSBuild.xunit" task could not be loaded from the assembly D:\j\workspace\x86_lb_checke---9877589b\tests\..\packages\xunit.runner.msbuild\2.1.0\build\portable-net45+win8+wp8+wpa81\xunit.runner.msbuild.dll. Could not load file or assembly 'file:///D:\j\workspace\x86_lb_checke---9877589b\packages\xunit.runner.msbuild\2.1.0\build\portable-net45+win8+wp8+wpa81\xunit.runner.msbuild.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [D:\j\workspace\x86_lb_checke---9877589b\tests\runtest.proj]
```

**Comment by briansull** [comment]
LGTM

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT x86 legacy_backend Checked Build and Test

**Pull request merged**
