### PR TITLE
Add a simple span benchmark

### PR DESCRIPTION
**Pull request by AndyAyersMS**

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
Based on some span tests first developed in a galaxy far far away.

I believe this is still testing the "slow span". @russellhadley PTAL; cc @dotnet/jit-contrib 

Some results:

FillAllSpanBase: 25.3125ms
FillAllArrayBase: 0.7371ms
FillAllReverseSpanBase: 4.989ms
FillAllReverseArrayBase: 0.8999ms
BubbleSortSpanBase: 29.3914ms
BubbleSortArrayBase: 2.8808ms
QuickSortSpanBase: 30.1429ms
QuickSortArrayBase: 2.1777ms

**Comment by AndyAyersMS** [comment]
Ubuntu [failure](https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_ubuntu_flow_prtest/1710/) is an konwn open issue. Added another failure instance to #6574.

**Comment by AndyAyersMS** [comment]
Updated to get past a merge conflict.

**Comment by AndyAyersMS** [comment]
This change oddly seems to be good at triggering the ubuntu dblinkgen failure. Adding another [instance](https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_ubuntu_tst_prtest/1632/) to #6574.

@dotnet-bot retest Ubuntu x64 Checked Build and Test

**Comment by AndyAyersMS** [comment]
Latest ubuntu failure because of CoreFX update. Should be fixed now.

@dotnet-bot retest Ubuntu x64 Checked Build and Test

**Comment by russellhadley** [comment]
LGTM.  Yes CoreCLR still is on slow span.  There's a bit of runtime work left and then the package needs to be changed back to contain fast span.  Thanks for setting this up. :)

**Comment by AndyAyersMS** [comment]
Looks like I'll have to do a manual update to get past dependency merge conflicts.

**Comment by AndyAyersMS** [comment]
Updated to get past dependency merge conflicts.

**Comment by AndyAyersMS** [comment]
[Windows test failures](https://ci.dot.net/job/dotnet_coreclr/job/master/job/debug_windows_nt_prtest/2004/) are a surprise, given that I'm just adding a new test. Possibly caused by dependency updates, but then I'm just adding a new reference... will see if I can repro locally.

**Comment by AndyAyersMS** [comment]
No local repro for those failures, but GC\Features\LOHCompaction\lohcompactapi failed. Wonder if something is amiss with GC lately?

@dotnet-bot retest Windows_NT x64 Debug Build and Test

**Comment by swgillespie** [comment]
`GC._Coverage_delete_next_card_table_delete_next_card_table_._Coverage_delete_next_card_table_delete_next_card_table_cmd` makes me nervous, I haven't seen that one fail before - I'll make an issue.

**Pull request merged**
