### PR TITLE
Avoid Interval and RefPosition unnecessary initialization and copying

### PR DESCRIPTION
**Pull request by mikedn**
`RefPosition()` initializes a temporary object by using `memset`. `push_back` copies the temporary object to the list node. `memset` is called again to zero out the newly created `RefPosition` object.

Add `emplace` methods to `jitstd::list` to avoid copying. Drop the redundant `memset` call.

### CODE REVIEW

**Comment by mikedn** [comment]
As far as I can tell the repeated build failures aren't related to my changes. The build system has moved to Switzerland and transformed into cheese.

**Comment by BruceForstall** [comment]
Nice! It's too bad we can't just use the platform STL and get rid of jitstd altogether :-(

LGTM

**Comment by mikedn** [comment]
> Nice! It's too bad we can't just use the platform STL and get rid of jitstd altogether :-(

Thanks! Using the actual STL would be nice but I'm willing to settle for much less - replacing most of the custom collections (some are quite weird) with jitstd containers :)

**Comment by BruceForstall** [comment]
@dotnet-bot retest OSX x64 Checked Build and Test please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/checked_osx_flow_prtest/35/
// Retest reason:

**Comment by BruceForstall** [comment]
@dotnet-bot retest Ubuntu x64 Checked Build and Test please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/checked_ubuntu_flow_prtest/36/
// Retest reason:

**Comment by mmitche** [comment]
@dotnet-bot test OSX x64 Checked Build and Test
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Comment by mmitche** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test
@dotnet-bot test OSX x64 Checked Build and Test

**Comment by mmitche** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test
@dotnet-bot test OSX x64 Checked Build and Test

**Comment by mmitche** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test
@dotnet-bot test OSX x64 Checked Build and Test

**Comment by mmitche** [comment]
Alright I'm mostly stumped as to what is going on right now

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by BruceForstall** [comment]
@mmitche Looks like bad things are still happening? At least with this PR?

**Comment by mmitche** [comment]
This was prior to the fixes.  @dotnet-bot test this please

**Comment by BruceForstall** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Comment by BruceForstall** [comment]
@mmitche Looks like OSX is still hanging?

**Comment by mmitche** [comment]
@BruceForstall might be because I restarted the system for plugin updates.  You're good now it appears.

**Pull request merged**
