### PR TITLE
Archive coreclrtests.*.txt files

### PR DESCRIPTION
**Pull request by BruceForstall**

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet-bot test CI please

**Comment by jashook** [comment]
@BruceForstall where are these files getting generated? I am unfamiliar with them

**Comment by BruceForstall** [comment]
In the root of the test directory. I just created them. Note: this is dev/unix_test_workflow; don't worry about reviewing it (yet).

**Comment by BruceForstall** [comment]
@dotnet-bot test CI please

**Comment by BruceForstall** [comment]
@dotnet-bot test CI please

**Pull request merged**
