### PR TITLE
Mark packages as non-stable and bump to 1.1.6

### PR DESCRIPTION
**Pull request by safern**
cc: @weshaggard

### CODE REVIEW

**Comment by weshaggard** [comment]
test Ubuntu x64 Checked Build and Test

**Comment by safern** [comment]
@dotnet/dnceng Ubuntu leg is hanging after checking out the sources.

https://ci.dot.net/job/dotnet_coreclr/job/release_1.1.0/job/checked_ubuntu_flow_prtest/488/console

Test Ubuntu x64 Checked Build and Test please

**Comment by Chrisboh** [comment]
@jcagme Do you mind taking a look?

**Comment by safern** [comment]
Merging since this is an infra issue.

**Comment by mmitche** [comment]
@safern I didn't see any infra issue there:

09:28:34 -- Looking for ucol_setMaxVariable - not found
09:28:34 CMake Error at src/ToolBox/SOS/lldbplugin/CMakeLists.txt:49 (message):
09:28:34   Cannot find lldb-3.5, lldb-3.6 or lldb-3.8.  Try installing lldb-3.6-dev
09:28:34   (or the appropriate package for your platform)
09:28:34 
09:28:34 
09:28:34 -- Configuring incomplete, errors occurred!
09:28:34 See also "/mnt/j/workspace/dotnet_coreclr/release_1.1.0/checked_ubuntu_prtest/bin/obj/Linux.x64.Checked/CMakeFiles/CMakeOutput.log".
09:28:34 See also "/mnt/j/workspace/dotnet_coreclr/release_1.1.0/checked_ubuntu_prtest/bin/obj/Linux.x64.Checked/CMakeFiles/CMakeError.log".
09:28:34 /mnt/j/workspace/dotnet_coreclr/release_1.1.0/checked_ubuntu_prtest
09:28:34 /mnt/j/workspace/dotnet_coreclr/release_1.1.0/checked_ubuntu_prtest/bin/obj/Linux.x64.Checked /mnt/j/workspace/dotnet_coreclr/release_1.1.0/checked_ubuntu_prtest
09:28:34 Failed to generate native component build project!
09:28:34

**Comment by safern** [comment]
> Cannot find lldb-3.5, lldb-3.6 or lldb-3.8. Try installing lldb-3.6-dev

That seems like a infra issue where the machine doesn’t have the appropriate assets.

**Comment by mmitche** [comment]
@safern Ahh, I didn't see the issue where it was hanging.
@mikem8361 Changed these images so that lldb was a newer verison.  @mikem8361 Was lldb 3.5 supposed to stay on for release 1.1.0?

**Comment by mikem8361** [comment]
I did remove lldb 3.5 on the docker images and VMs we use to build. I thought we would just go back to the old versions for 1.1.0 and other service releases.

**Comment by mmitche** [comment]
@mikem8361 This isn't docker on this one.  It's a VM image.  We can probably roll back the VM image, or go and install lldb3.5

**Comment by mikem8361** [comment]
Rolling back the VM image is probably better because the cmake build logic in coreclr tries to use the latest lldb installed so even if we installed 3.5 it would probably still try to build with 3.9.

**Pull request merged**
