### PR TITLE
Update CI to no longer request mscorlib build for osx/ubuntu on Windows.

### PR DESCRIPTION
**Pull request by gkhanna79**
@mmitche PTAL

### CODE REVIEW

**Comment by gkhanna79** [comment]
@mmitche How should this PR be tested?

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
LGTM

**Comment by gkhanna79** [comment]
@ellismg PTAL

**Comment by ellismg** [comment]
LGTM

**Comment by gkhanna79** [comment]
Part of fixing https://github.com/dotnet/coreclr/issues/3015

**Pull request merged**
