### PR TITLE
Delete bad assert

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
This assert was assuming that the MethodDesc for JITed code is not zapped. It is not the case for code holes in the native images that we are leaving in for various reasons.

@JohnChen0 PTLA

**Comment by jkotas** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test  please

**Comment by jkotas** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by adityamandaleeka** [comment]
LGTM

**Pull request merged**
