### PR TITLE
[WIP] Small memory footprint GC optimization level

### PR DESCRIPTION
**Pull request by gbalykov**
This pull request adds small memory footprint as GC optimization level.

This pull request is based on the branch, mentioned by @swgillespie in https://github.com/dotnet/coreclr/issues/13292#issuecomment-324108583, but part with fragmentation tuning was removed because its combination with compacting was not researched.

@Maoni0 @swgillespie, please, take a look

### CODE REVIEW

**Comment by swgillespie** [comment]
I'll defer to @Maoni0 on this one. Do you think we're ready to take this or should we try and exercise the `latency_level_small_memory_footprint_unstable_perf` first?

**Comment by gbalykov** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build and Test
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Comment by Maoni0** [comment]
@gbalykov, @swgillespie, I pushed a [commit in my branch](https://github.com/Maoni0/coreclr/commit/03bfe764a5f67fa671c0c7092d47a1624005cbb9) that shows how the latency levels should be set up. you can see lots of TODO's in the code. I incorporated some of @gbalykov's changes (unfortunately I dunno how to get both your commits and make them show up as from you guys :P and I am running out of time before I go on vacation; but there weren't many changes I incorporated so it should be fine if one of you wants to take this and keep working on it). 

As you can see, I've separated out the static data for the latency levels - for now I've kept everything the same as before except the data for the memory_footprint level since we already know some of what we want to change - I expect us to be doing lots of perf tuning to set up the appropriate static data for each level (I also changed the values for the enums... I am actually thinking instead of making these at increments of 1 perhaps we should make them increments of 10 to give us more numbers for each level so we can have more detailed levels for optimizing for memory footprint and etc). 

I intentionally did not take the change that always does compacting for this level because we don't want to "always compact" - there are situations where we know compacting is completely uselss so it's not a good time to unconditionally compact; instead I changed the fragment static data to be smaller so it would compact more often.

**Comment by gbalykov** [comment]
@Maoni0 @swgillespie

I have measured the branch on few Tizen GUI applications, and results are the next

Application|Original, Peak, Private_Dirty, Kb|Modified (GCLatencyLevel=memory_footprint), Peak, Private_Dirty, Kb|Difference
-----------|---------------------------------|---------------------------------|----------
HelloWorld|396|392|4 (1.01%)
BoxViewClock|1404|760|644 (45.87%)
Puzzle|912|600|312 (34.21%)
ApplicationStoreUI|524|492|32 (6.11%)
GalleryUI|424|392|32 (7.55%)
AppCommon|764|616|148 (19.37%)
SNSUI|2364|1632|732 (30.96%)
Calculator|1080|712|368 (34.07%)

average: 22.39%

I think this results are good to start with and I will continue to work on this after finishing another CoreCLR optimization.

**Comment by Maoni0** [comment]
Sounds good, thanks for the data!

**Comment by gbalykov** [comment]
@Maoni0 @swgillespie

I have also checked on the balanced level and it seems to increase memory consumption. 

Application|Original, Peak, Private_Dirty, Kb|Modified (GCLatencyLevel=balanced), Peak, Private_Dirty, Kb|Difference
-----------|---------------------------------|---------------------------------|----------
HelloWorld|396|448| -52 (-13.13%)
BoxViewClock|1404|2252| -847 (-60.33%)
Puzzle|912|1136| -224 (-24.56%)
ApplicationStoreUI|524|696| -172 (-32.82%)
GalleryUI|424|600| -176 (-41.51%)
AppCommon|764|944| -180 (-23.56%)
SNSUI|2364|2512| -148 (-6.26%)
Calculator|1080|1264| -184 (-17.04%)

average memory consumption increase: 27.40%

**Comment by Maoni0** [comment]
Yes, that's expected for memory consumption. Do you also have throughput numbers?

**Comment by gbalykov** [comment]
@Maoni0 

Sorry for the delay, I've been busy doing another optimization.

These are the results for your patch (base 97d9d593ae44438fab85044e2a189316e7f3cbc4):

Test|base GC heap (Kb), startup time (s)|"memory_consumption" level GC heap (Kb), startup time (s)
----|---------|----
HelloWorld.Tizen|368; 1.99158|288 (-21.74%); 1.9505 (-2.06%)
Settings.Tizen.Mobile|632; 2.54684|520 (-17.72%); 2.522 (-0.98%)
VolumeController.Tizen.Mobile|512; 2.391|472 (-7.81%); 2.343 (-2.01%)
AppCommon.Tizen.Mobile|838.4; 3.824|612 (-27.00%); 3.8325 (+0.22%)
EmailUI.Tizen.Mobile|1384; 3.1115|1016 (-26.59%); 3.0865 (-0.80%)
ApplicationControl.Tizen.Mobile|706.8; 3.2635|552 (-21.90%); 3.229 (-1.06%)
SNSUI.Tizen.Mobile|2292; 4.424|1732.4 (-24.42%); 4.511 (+1.97%)
ApplicationStoreUI.Tizen.Mobile|1203.2; 2.425|884 (-26.53%); 2.41842 (-0.27%)
Puzzle.Tizen.Mobile|970; 3.001|701.2 (-27.71%); 3.0 (-0.03%)
System_info.Tizen.Mobile|368; 2.366|288 (-21.74%); 2.3355 (-1.29%)
GalleryUI.Tizen.Mobile|368; 2.4585|328 (-10.87%); 2.3985 (-2.44%)
Calculator.Tizen.Mobile|2078.6; 4.855|792 (-61.90%); 5.1805 (+6.70%)

average: -24.66%; -0.17%

Test|base GC heap (Kb), startup time (s)|"balanced" level GC heap (Kb), startup time (s)
----|---------|----
HelloWorld.Tizen|368; 1.99158|388 (+5.43%); 1.93 (-3.09%)
Settings.Tizen.Mobile|632; 2.54684|816 (+29.11%); 2.4945 (-2.06%)
VolumeController.Tizen.Mobile|512; 2.391|696 (+35.94%); 2.32526 (-2.75%)
AppCommon.Tizen.Mobile|838.4; 3.824|1024 (+22.14%); 3.802 (-0.58%)
EmailUI.Tizen.Mobile|1384; 3.1115|1560 (+12.72%); 3.0655 (-1.48%)
ApplicationControl.Tizen.Mobile|706.8; 3.2635|890.4 (+25.98%); 3.228 (-1.09%)
SNSUI.Tizen.Mobile|2292; 4.424|2537 (+10.69%); 4.4175 (-0.15%)
ApplicationStoreUI.Tizen.Mobile|1203.2; 2.425|1388.4 (+15.39%); 2.39053 (-1.42%)
Puzzle.Tizen.Mobile|970; 3.001|1155.6 (+19.13%); 2.968 (-1.10%)
System_info.Tizen.Mobile|368; 2.366|444 (+20.65%); 2.329 (-1.56%)
GalleryUI.Tizen.Mobile|368; 2.4585|540 (+46.73%); 2.4085 (-2.03%)
Calculator.Tizen.Mobile|2078.6; 4.855|5324 (+156.13%); 4.8145 (-0.83%)

average: +33.34%; -1.51%

</br>

Also, I have been performing tuning of parameters from static_data structure on Tizen Xamarin GUI applications and GC benchmarks and I always seem to obtain the same results with +-3% accuracy. I set fragmentation and fragmentation_burden for both gen0 and gen1 (for latency_level_memory_footprint) lower than the ones that you have specified (i.e. lower than 40000, 0.25, 80000, 0.25).

What could be the reason of this? Could it be due to reaching some kind of a minimum at your parameters, which couldn't be lowered any more?

Could you, please, also suggest a better way of tuning of parameters from static_data?

cc @kvochko

**Pull request closed without merging**
