### PR TITLE
Fix impl of ReadOnlySpan StartsWith/EndsWith for Unix.

### PR DESCRIPTION
**Pull request by ahsonkhan**
Update to https://github.com/dotnet/coreclr/pull/16223

Ran the new tests locally on OSX and they all pass now.

Fixes the test failures - https://ci3.dot.net/job/dotnet_corefx/job/master/job/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/8584/

Related PR: https://github.com/dotnet/corefx/pull/26880

cc @jkotas, @stephentoub, @KrzysztofCwalina, @tarekgh, @JeremyKuhne

### CODE REVIEW

**Comment by stephentoub** [comment]
What was the bug and what was the fix? It's not immediately obvious from the diff.

**Comment by ahsonkhan** [comment]
For StartsWith:
```C#
return Interop.Globalization.StartsWith(_sortHandle, b, prefix.Length - length, a, prefix.Length - length, options);
```

Changed to:
```C#
return Interop.Globalization.StartsWith(_sortHandle, b, length, a, length, options);
```

For EndsWith:
Instead of Slicing and calling the StartsWith helpers, which do not work well for cases such as "Hello".EndsWith("ello-"), created EndsWith helpers which process the characters backwards.

**Comment by stephentoub** [comment]
Thanks

**Comment by ahsonkhan** [comment]
Let's take this example, which is supposed to return true - "Hello".EndsWith("ello-")

```C#
return StartsWithOrdinalHelper(source.Slice(source.Length - suffix.Length), suffix, options);
```
source.Length = 5, suffix.Length = 5, source.Slice(0) => source.

Compare the first character of source with first character of suffix. H != e. Return false, which is incorrect.

**Comment by stephentoub** [comment]
In that case, don't we still have a bug?  We do length checks that return false if source.Length is < prefix/suffix.Length, but that will break an example like `"Hello".EndsWith("Hello\u00AD")`, which should return true, but `"Hello".Length`==`5` and `"Hello\u00AD"`.Length == 6.

**Comment by ahsonkhan** [comment]
> In that case, don't we still have a bug?

You are right. Good point.

`"Hello".EndsWith("Hello\u00AD")` and `"Hello".EndsWith("ello\u00AD")` should both return true but the length checks bails too early and returns false.

We need to remove these checks:
https://github.com/dotnet/coreclr/blob/154824bd47cbfe84d92f44c9f07ea7fa25f4d5bd/src/mscorlib/src/System/Globalization/CompareInfo.Unix.cs#L282-L285

https://github.com/dotnet/coreclr/blob/154824bd47cbfe84d92f44c9f07ea7fa25f4d5bd/src/mscorlib/src/System/Globalization/CompareInfo.Unix.cs#L413-L416

**Comment by tarekgh** [comment]
I recall we used to have the IsSortable check in addition to the ignore symbols which take care of that. and the conditions at that time would be correct.

**Comment by tarekgh** [comment]
```C#
if (_isAsciiEqualityOrdinal && CanUseAsciiOrdinalForOptions(options) && source.IsFastSort() && prefix.IsFastSort())
```

**Comment by tarekgh** [comment]
and we don't have to do IsFastSort check on Windows.

**Comment by tarekgh** [comment]
thinking twice, I am seeing we cannot do IsFastSort for the spans :-( so I think your proposed changes by removing the length check would make sense.

**Comment by tarekgh** [comment]
to mention, checks like 
```C#
if (_isAsciiEqualityOrdinal && CanUseAsciiOrdinalForOptions(options))
```

wouldn't be enough for Linux to optimize for ordinal.

**Comment by tarekgh** [comment]
talked offline with @ahsonkhan and he pointed we check the sortable chars in the loop 

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Globalization/CompareInfo.Unix.cs#L323

so I think removing the length check as suggested would be ok

**Pull request merged**
