### PR TITLE
ARM64: New Test Binary Update

### PR DESCRIPTION
**Pull request by kyulee1**
Currently 135 of 9661 are failing.
Those are marked as EXPECTED_FAIL.
~55: mcc failed due to changed struct calling convention in toolset [#5071].
~13: regression from the prior tests: marked as EXPECTED_FAIL;REGRESS
~22: failures from new tests: marked as NEW;EXPECTED_FAIL
~45: HFA

Tests.lst head now contains git hash number which tells us what version
we use to build such binaries. This is also used to dispatch different test folder in the lab.

### CODE REVIEW

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Release

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Checked
@dotnet-bot test Windows_NT arm64 Release

**Comment by kyulee1** [comment]
@dotnet/arm64-contrib PTAL

**Comment by rahku** [comment]
Thanks LGTM

**Comment by briansull** [comment]
LGTM

**Pull request merged**
