### PR TITLE
Move the MethodImpl iterator when checking default interface methods

### LINKED ISSUE #16064: MethodTableBuilder::HasDefaultInterfaceImplementation hangs when an interface implements methods from two different base interfaces
The scenario used to work as expected with 2.1.0-dev-di-25326-0 package, about 50 existing C# compiler unit-tests are broken because of that.

Compile and run the following C# code (IL is below):
```
public interface I2
{
    void M1(); 
}

public interface I4
{
    void M1(); 
}

public interface I1 : I2, I4
{
    void I2.M1() 
    {
        System.Console.WriteLine("I2.M1");
    }
    void I4.M1() 
    {
        System.Console.WriteLine("I4.M1");
    }
}

class Test1 : I1
{
    static void Main()
    {
        I2 i2 = new Test1();
        i2.M1();
        I4 i4 = new Test1();
        i4.M1();
    }
}
```

Expected output:
```
I2.M1
I4.M1
```

Observed:
Execution hangs 
```
0:000> k
 # Child-SP          RetAddr           Call Site
00 (Inline Function) --------`-------- coreclr!RelativePointer<MethodDesc *>::GetValueMaybeNull [e:\a\_work\1592\s\src\inc\fixuppointer.h @ 94] 
01 (Inline Function) --------`-------- coreclr!RelativePointer<MethodDesc *>::GetValueMaybeNullAtPtr [e:\a\_work\1592\s\src\inc\fixuppointer.h @ 116] 
02 00000053`aa20c100 00007ffa`7fc050b9 coreclr!MethodImpl::GetMethodDesc+0x1d [e:\a\_work\1592\s\src\vm\methodimpl.cpp @ 92] 
03 (Inline Function) --------`-------- coreclr!MethodImpl::Iterator::GetMethodDesc+0x10 [e:\a\_work\1592\s\src\vm\methodimpl.h @ 50] 
04 00000053`aa20c130 00007ffa`7facab27 coreclr!MethodTableBuilder::HasDefaultInterfaceImplementation+0x159 [e:\a\_work\1592\s\src\vm\methodtablebuilder.cpp @ 10735] 
05 00000053`aa20c1b0 00007ffa`7f9bf787 coreclr!MethodTableBuilder::VerifyVirtualMethodsImplemented+0x10d36b [e:\a\_work\1592\s\src\vm\methodtablebuilder.cpp @ 10823] 
06 00000053`aa20c250 00007ffa`7f9cb564 coreclr!MethodTableBuilder::SetupMethodTable2+0x1ec7 [e:\a\_work\1592\s\src\vm\methodtablebuilder.cpp @ 10611] 
07 00000053`aa20c790 00007ffa`7f9b7be6 coreclr!MethodTableBuilder::BuildMethodTableThrowing+0x3084 [e:\a\_work\1592\s\src\vm\methodtablebuilder.cpp @ 1839] 
08 00000053`aa20cd10 00007ffa`7f99e60f coreclr!ClassLoader::CreateTypeHandleForTypeDefThrowing+0x4e6 [e:\a\_work\1592\s\src\vm\methodtablebuilder.cpp @ 12095] 
09 00000053`aa20d020 00007ffa`7f99f4d8 coreclr!ClassLoader::CreateTypeHandleForTypeKey+0x6f [e:\a\_work\1592\s\src\vm\clsload.cpp @ 3589] 
0a 00000053`aa20d120 00007ffa`7f9a0e64 coreclr!ClassLoader::DoIncrementalLoad+0x88 [e:\a\_work\1592\s\src\vm\clsload.cpp @ 3517] 
0b 00000053`aa20d450 00007ffa`7f9a1f5a coreclr!ClassLoader::LoadTypeHandleForTypeKey_Body+0xa84 [e:\a\_work\1592\s\src\vm\clsload.cpp @ 4325] 
0c 00000053`aa20d9b0 00007ffa`7f964d0d coreclr!ClassLoader::LoadTypeHandleForTypeKey+0x9a [e:\a\_work\1592\s\src\vm\clsload.cpp @ 4044] 
0d 00000053`aa20da50 00007ffa`7f94874b coreclr!ClassLoader::LoadTypeDefThrowing+0x21d [e:\a\_work\1592\s\src\vm\clsload.cpp @ 2887] 
0e 00000053`aa20dba0 00007ffa`7f9bca1d coreclr!ClassLoader::LoadTypeDefOrRefThrowing+0x41b [e:\a\_work\1592\s\src\vm\clsload.cpp @ 3065] 
0f 00000053`aa20dcf0 00007ffa`7f9bd11a coreclr!Assembly::GetEntryPoint+0x1a1 [e:\a\_work\1592\s\src\vm\assembly.cpp @ 1918] 
10 00000053`aa20e200 00007ffa`7f95d058 coreclr!Assembly::ExecuteMainMethod+0x92 [e:\a\_work\1592\s\src\vm\assembly.cpp @ 1792] 
11 00000053`aa20e4e0 00007ffa`7fa4606e coreclr!CorHost2::ExecuteAssembly+0x188 [e:\a\_work\1592\s\src\vm\corhost.cpp @ 482] 
12 00000053`aa20e5f0 00007ffa`9dfede29 coreclr!coreclr_execute_assembly+0xde [e:\a\_work\1592\s\src\dlls\mscoree\unixinterface.cpp @ 407] 
13 00000053`aa20e680 00007ffa`9dfee4f4 hostpolicy!corehost_unload+0x12179
14 00000053`aa20ec40 00007ffa`a8aebca5 hostpolicy!corehost_main+0x164
15 00000053`aa20edc0 00007ffa`a8af427d hostfxr+0x1bca5
16 00000053`aa20ee90 00007ffa`a8af3234 hostfxr!hostfxr_resolve_sdk+0x837d
17 00000053`aa20f5e0 00007ffa`a8af0809 hostfxr!hostfxr_resolve_sdk+0x7334
18 00000053`aa20f770 00007ff7`0d0c9b52 hostfxr!hostfxr_resolve_sdk+0x4909
19 00000053`aa20f900 00007ff7`0d0ce229 dotnet+0x9b52
1a 00000053`aa20fa10 00007ffa`b02913d2 dotnet+0xe229
1b 00000053`aa20fa50 00007ffa`b2c154f4 KERNEL32!BaseThreadInitThunk+0x22 [d:\9147\base\win32\client\thread.c @ 78] 
1c 00000053`aa20fa80 00000000`00000000 ntdll!RtlUserThreadStart+0x34 [d:\blue\minkernel\ntdll\rtlstrt.c @ 1026] 
```

IL:
```

//  Microsoft (R) .NET Framework IL Disassembler.  Version 4.6.1055.0
//  Copyright (c) Microsoft Corporation.  All rights reserved.



// Metadata version: v4.0.30319
.assembly extern mscorlib
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 4:0:0:0
}
.assembly debug
{
  .custom instance void [mscorlib]System.Runtime.CompilerServices.CompilationRelaxationsAttribute::.ctor(int32) = ( 01 00 08 00 00 00 00 00 ) 
  .custom instance void [mscorlib]System.Runtime.CompilerServices.RuntimeCompatibilityAttribute::.ctor() = ( 01 00 01 00 54 02 16 57 72 61 70 4E 6F 6E 45 78   // ....T..WrapNonEx
                                                                                                             63 65 70 74 69 6F 6E 54 68 72 6F 77 73 01 )       // ceptionThrows.

  // --- The following custom attribute is added automatically, do not uncomment -------
  //  .custom instance void [mscorlib]System.Diagnostics.DebuggableAttribute::.ctor(valuetype [mscorlib]System.Diagnostics.DebuggableAttribute/DebuggingModes) = ( 01 00 07 01 00 00 00 00 ) 

  .hash algorithm 0x00008004
  .ver 0:0:0:0
}
.module debug.exe
// MVID: {DBA9D405-16A7-47FD-AEBC-05C48DC5F509}
.imagebase 0x00400000
.file alignment 0x00000200
.stackreserve 0x00100000
.subsystem 0x0003       // WINDOWS_CUI
.corflags 0x00000001    //  ILONLY
// Image base: 0x01620000


// =============== CLASS MEMBERS DECLARATION ===================

.class interface public abstract auto ansi I2
{
  .method public hidebysig newslot abstract virtual 
          instance void  M1() cil managed
  {
  } // end of method I2::M1

} // end of class I2

.class interface public abstract auto ansi I4
{
  .method public hidebysig newslot abstract virtual 
          instance void  M1() cil managed
  {
  } // end of method I4::M1

} // end of class I4

.class interface public abstract auto ansi I1
       implements I2,
                  I4
{
  .method private hidebysig virtual final 
          instance void  I2.M1() cil managed
  {
    .override I2::M1
    // Code size       13 (0xd)
    .maxstack  8
    IL_0000:  nop
    IL_0001:  ldstr      "I2.M1"
    IL_0006:  call       void [mscorlib]System.Console::WriteLine(string)
    IL_000b:  nop
    IL_000c:  ret
  } // end of method I1::I2.M1

  .method private hidebysig virtual final 
          instance void  I4.M1() cil managed
  {
    .override I4::M1
    // Code size       13 (0xd)
    .maxstack  8
    IL_0000:  nop
    IL_0001:  ldstr      "I4.M1"
    IL_0006:  call       void [mscorlib]System.Console::WriteLine(string)
    IL_000b:  nop
    IL_000c:  ret
  } // end of method I1::I4.M1

} // end of class I1

.class private auto ansi beforefieldinit Test1
       extends [mscorlib]System.Object
       implements I1,
                  I2,
                  I4
{
  .method private hidebysig static void  Main() cil managed
  {
    .entrypoint
    // Code size       28 (0x1c)
    .maxstack  1
    .locals init (class I2 V_0,
             class I4 V_1)
    IL_0000:  nop
    IL_0001:  newobj     instance void Test1::.ctor()
    IL_0006:  stloc.0
    IL_0007:  ldloc.0
    IL_0008:  callvirt   instance void I2::M1()
    IL_000d:  nop
    IL_000e:  newobj     instance void Test1::.ctor()
    IL_0013:  stloc.1
    IL_0014:  ldloc.1
    IL_0015:  callvirt   instance void I4::M1()
    IL_001a:  nop
    IL_001b:  ret
  } // end of method Test1::Main

  .method public hidebysig specialname rtspecialname 
          instance void  .ctor() cil managed
  {
    // Code size       8 (0x8)
    .maxstack  8
    IL_0000:  ldarg.0
    IL_0001:  call       instance void [mscorlib]System.Object::.ctor()
    IL_0006:  nop
    IL_0007:  ret
  } // end of method Test1::.ctor

} // end of class Test1


// =============================================================

// *********** DISASSEMBLY COMPLETE ***********************
```

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Fixes #16064.

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
@jkotas Could you please have a look?

Cc @sergiy-k

**Comment by MichalStrehovsky** [comment]
@dotnet/dnceng Seems like this only triggered the Alpine build - should I open and close this pull request to re-trigger the CI? Is there anything interesting you would like to collect before I do that?

**Comment by MichalStrehovsky** [comment]
Never mind, commenting on the pull request triggered all the tests...

**Comment by MattGal** [comment]
@MichalStrehovsky no specific requests, but we have been having issues with web-hook triggering that should have gone away, so if this continues please ping dnceng or myself directly.

**Pull request merged**
