### PR TITLE
 Use libc.so as default libc name

### PR DESCRIPTION
**Pull request by jasonwilliams200OK**
Based on dotnet#5727 (comment),
it turned out `/lib/libc.musl-x86_64.so.1` was just a symlink in
Alpine Linux to actual lib `/lib/ld-musl-x86_64.so.1`.

This delta makes libc.so as default name for libc and removes all the
detection for musl and FreeBSD from cmake etc.

### CODE REVIEW

**Comment by jasonwilliams200OK** [comment]
@rofl0r, @jkotas, PTAL .. based on this discussion: https://github.com/dotnet/coreclr/pull/5727#discussion_r68369439.

**Comment by jkotas** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build and Test  please

**Comment by jkotas** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test please

**Comment by jasonwilliams200OK** [comment]
@jkotas, since `libc.so` is clearly in majority here, should we just use "libc.so" by default and special case for platform where it has different names? At the moment only Apple requires the dylib in name and FreeBSD requires the special case (with .7 suffix), so we can inline it here like `"libc.so.7"` (no need for absolute path and CMake wiring IMO): http://lists.freebsd.org/pipermail/freebsd-bugs/2013-July/053276.html.

Some people are showing concern on IRC that the general approach taken here https://github.com/dotnet/coreclr/blob/af687f4600df72a103b1e0bb83d2b26a1d26a499/src/pal/src/loader/module.cpp#L1605 is bad and suggesting  `libc.so` would work in most cases and branch out only for `__APPLE__` (dylib) case. Also someone commented:

> this will also fix multiarch setups (where there are multiple libc.so and you cannot easily guess which one is right)

Do you think we should consider this approach?

**Comment by jkotas** [comment]
Yes, I think just using `libc.so` where it works would be preferable.

**Comment by richfelker** [comment]
I'm not sure where the result of this check is used, but passing an absolute pathname for libc.so to dlopen is not safe under any past or current version of musl. musl has logic to prevent reloading of libc.so when you access it properly via the library path (passing an argument not containing any slashes to dlopen, e.g. just "libc.so") but when you pass an absolute path, it trusts that you know what you're doing and opens the file. As a result you'll end up with multiple copies of libc in-core and serious memory corruption can result if you use the second one at all. Fixing this on our side (to detect attempts to load a second libc and redirect it to the existing one) is an open issue, but in the mean time "libc.so" (without any path components) is the only name you should expose to applications for libc.

**Comment by jasonwilliams200OK** [comment]
Thanks @richfelker, I think the (abs. path) approach taken for FreeBSD was also wrong for the same reason, just the lib name is enough. I have amended the commit and re-pushed.

**Comment by jkotas** [comment]
LGTM. Thanks for cleaning it up!

**Pull request merged**
