### PR TITLE
Allow to use clang 3.9 in build.sh

### PR DESCRIPTION
**Pull request by JustArchi**
Can be found e.g. in Debian Sid.

### CODE REVIEW

**Comment by jasonwilliams200OK** [comment]
:+1: llvm 3.9.0 was tagged yesterday. The release will be shipped soon.
http://llvm.org

**Comment by jasonwilliams200OK** [comment]
Similar fix would need to be made in CoreFX repo: https://github.com/dotnet/corefx/blob/6750e2b/src/Native/build-native.sh#L186-L188

**Comment by JustArchi** [comment]
Failure seems unrelated.

**Comment by jkotas** [comment]
Thanks!

**Pull request merged**
