### PR TITLE
Partial Revert "Remove global locks from Exception stack trace handling  (#26823)

### PR DESCRIPTION
**Pull request by jkotas**
The scalability improvement claimed by the change is not there after closer examination.
Reverting to avoid visible non pay-for-play overhead added by the change.

### CODE REVIEW

**Comment by jkotas** [comment]
More context https://github.com/dotnet/coreclr/pull/26823#discussion_r329338229

cc @benaadams @stephentoub 

I was so focused on the potential GC holes caused by the change, that I forgot to validate the benefits.

**Comment by kevingosse** [comment]
> The scalability improvement claimed by the change is not there after closer examination.
> Reverting to avoid visible non pay-for-play overhead added by the change.

I'm curious about the test setup. We had to change the way we handle errors in one of our apps to avoid hitting that lock (https://github.com/dotnet/coreclr/issues/23811). But it was a very heavy workload (more than 4000 requests per second on a 32 CPUs server). Also, this was on .net framework (where Monitor doesn't scale quite as well).

**Comment by benaadams** [comment]
What would be the risk in using the Exception itself as the lock? Then it has no additional cost.

As suggested by @stephentoub in the issue https://github.com/dotnet/coreclr/issues/23811#issuecomment-483092007

> That couldn't be achieved by locking on the exception object itself or on some object it contains, rather than on a static?

**Comment by jkotas** [comment]
> I'm curious about the test setup.

This:

```
using System;
using System.Threading;
using System.Runtime.ExceptionServices;

class My
{
    static void Work()
    {
        for (;;)
        {
            try
            {
                try
                {
                    throw new Exception();
                }
                catch (Exception e)
                {
                    var edi = ExceptionDispatchInfo.Capture(e);
                    edi.Throw();
                }

            }
            catch
            {
            }
        }
    }

    static void Main()
    {
        for (int i = 0; i < 30; i++) new Thread(Work).Start();
        Work();
    }
}
```

Running on a 16 core / 32 logical processors Xeon E5. The time spent in RestoreDispatchState:

image

It have not changed in significant way before/after change.

**Comment by kevingosse** [comment]
Running the code on a Xeon Silver 4108, I get:

 - 83k exceptions/seconds for the latest .net core nightly
 - 85k/s for .net core 3.0 RTM
 - 81k/s for .net framework

Then if I increase the number of threads to 200:

 - 83k exceptions/seconds for the latest .net core nightly
 - 85k/s for .net core 3.0 RTM
 - 3k/s for .net framework

So I guess this is not an issue anymore on .net core, thanks to the many improvements on how Monitor scales.

**Comment by jkotas** [comment]
> What would be the risk in using the Exception itself as the lock? 

I have deleted the managed lock completely. It is providing any interesting guarantees. The watson buckets are accessed outside this lock, and they can get out of sync with the rest of the state. The only lock that is important to guarantee integrity of the system is the unmanaged spin lock.

I have looked at the history:
1. The original version of the code had just the managed lock. 
2. It was discovered that the managed lock is not enough to guarantee integrity of the system and so the unmanaged lock was added
3. But the managed lock was left around even though it does not guarantee much anymore.

> This still keep the instance lock in Exception.cs?

I did not get the partial revert right. It should be fixed now.

**Pull request merged**
