### PR TITLE
Fixing an error in PAL_pow that caused it to return an incorrect value for a couple scenarios.

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves https://github.com/dotnet/corefx/issues/9053.

FYI. @stephentoub

### CODE REVIEW

**Comment by tannergooding** [comment]
Taking a deeper look at `PAL_pow`, it should probably be cleaned up (along with the `configure.cmake` file that checks and sets `HAVE_COMPATIBLE_POW`.

**Comment by tannergooding** [comment]
There is at least one comment which is no longer valid:
```
// Windows returns NaN for pow(NaN, 0), but POSIX specifies
// a return value of 1 for that case.  We need to return
// the same result as Windows.
```

The current windows implementation is now returning `1.0` for `pow(NAN, 0.0)`.

**Comment by tannergooding** [comment]
The PAL_pow code does not handle `pow(-0, -1)` correctly either.

**Comment by tannergooding** [comment]
FYI @janvorli, @jkotas

**Comment by tannergooding** [comment]
I also have a PR here: https://github.com/dotnet/corefx/pull/9065, which adds some new tests to `System.Math` to cover other areas where PAL has special handling.

**Comment by tannergooding** [comment]
FYI @janvorli, @jkotas

**Comment by janvorli** [comment]
LGTM, thanks!

**Comment by tannergooding** [comment]
Is this good to merge now?

**Pull request merged**
