### PR TITLE
Build arch fix to avoid mscorlib building fail in case of clean build

### PR DESCRIPTION
**Pull request by aegoroff**
&lt;BuildArch Condition="'$(__BuildArch)' == 'x64'"&gt;amd64&lt;/BuildArch&gt; caused mscorlib building failure after cloning on my maching.

&lt;BuildArch Condition="'$(__BuildArch)' == 'x64'"&gt;x64&lt;/BuildArch&gt; instead fixed the problem

### CODE REVIEW

**Comment by aegoroff** [comment]
Hack didn't solved the problem. Revert it

**Comment by aegoroff** [comment]
I always get mscorlib building problem:

C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets
(617,5): error : The OutputPath property is not set for project 'build.proj'.
Please check to make sure that you have specified a valid combination of Config
uration and Platform for this project.  Configuration='Debug'  Platform='x64'.
 You may be seeing this message because you are trying to build a project witho
ut a solution file, and have specified a non-default Configuration or Platform
that doesn't exist for this project. [D:\prj\coreclr\build.proj]

**Comment by AlexGhiondea** [comment]
Are you building from a regular command prompt (and not a developer command prompt) ?

There is an issue tracking a similar problem (#168)

**Comment by aegoroff** [comment]
i tried building both from regular command promt and from VS2013 x64 Native Tools Command Promt and always failed without this hack

**Comment by AlexGhiondea** [comment]
Were you using the build.cmd file?

**Comment by AlexGhiondea** [comment]
Thank you for your contribution. 

I am working on a different approach to this which also solves #168.

I will have a PR our for this shortly.

**Comment by AlexGhiondea** [comment]
I submitted PR #173 which should address this (and also enables building from VS).

**Comment by aegoroff** [comment]
OK. You approach is better then my :)

**Comment by weshaggard** [comment]
Thanks @aegoroff for your help here but we have merged PR #173 which should address this so I'm closing this PR.

**Pull request closed without merging**
