### PR TITLE
Include System.Private.CoreLib in the targeting pack next to the mscorlib facade

### PR DESCRIPTION
**Pull request by AlexGhiondea**

### CODE REVIEW

**Comment by AlexGhiondea** [comment]
@dotnet-bot please test Windows_NT x86 legacy_backend Checked Build and Test

**Comment by AlexGhiondea** [comment]
@dotnet-bot please test Ubuntu x64 Checked Build and Test

**Comment by AlexGhiondea** [comment]
@dotnet-bot please test OSX x64 Checked Build and Test

**Comment by weshaggard** [comment]
LGTM

**Pull request merged**
