### PR TITLE
Update xunit version to 2.1.0

### LINKED ISSUE #2158: Upgrade xunit used in tests
CoreRT repo would greatly benefit if the test suite got an upgrade in the xunit version used to 2.1.0.

We're hitting xunit/xunit#223.

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #2158. A new version of dnu and buildtools was needed as well - updated everything to the version used by corefx repo currently.

### CODE REVIEW

**Comment by jkotas** [comment]
@MichalStrehovsky PTLA

**Comment by jkotas** [comment]
@dotnet-bot test Ubuntu x64 Release

**Comment by MichalStrehovsky** [comment]
LGTM. Thank you so much!

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Pull request merged**
