### PR TITLE
CoreDisTools: Use Common Test Dependency Infrastructure

### LINKED ISSUE #7861: remove custom scripts to donwload coredistools
Remove tests\setup-runtime-dependencies.\* and associated infra 
To restore the coredistools package, just add an entry in 
https://github.com/dotnet/coreclr/blob/master/tests/src/Common/test_runtime/project.json

cc @swaroop-sridhar Please reroute accordingly

### PR DESCRIPTION
**Pull request by swaroop-sridhar**
Remove the custom script to download CoreDisTools package, and
instead add dependency via the test/common/runtime/project.json file.

Fixes #7861

### CODE REVIEW

**Comment by jkotas** [comment]
`tests/src/Common/test_runtime/notepad` looks like unintentional addition.

**Comment by swaroop-sridhar** [comment]
@dotnet-bot test Ubuntu gcstress0xc
@dotnet-bot test Windows_NT gcstress0xc
@dotnet-bot test OSX gcstress0xc

**Comment by swaroop-sridhar** [comment]
@dotnet-bot test Ubuntu gcstress0xc
@dotnet-bot test Windows_NT gcstress0xc
@dotnet-bot test OSX gcstress0xc

**Comment by swaroop-sridhar** [comment]
Thanks @jkotas, I've fixed it.

**Comment by swaroop-sridhar** [comment]
@dotnet-bot test OSX Release gcstress15_pri1r2r

**Comment by swaroop-sridhar** [comment]
CC: @dotnet/jit-contrib @ramarag

**Comment by ramarag** [comment]
The Xplat failures are because they are using windows test builds, so the platform coredist tools are missing and core_root only has the windows version

**Comment by ramarag** [comment]
my suggestion is to move https://github.com/dotnet/coreclr/blob/master/build-test.cmd#L221 to build.sh

**Comment by danmosemsft** [comment]
@swaroop-sridhar what remains to complete this old PR?

**Comment by swaroop-sridhar** [comment]
@danmosemsft, The failures in the Unix runs need to be fixed -- to download and use the correct package.
I tried applying the fix the @ramarag suggested, but it caused all tests to be run in the build step itself. I was planning on consulting with @ramarag once he is back.

**Comment by danmosemsft** [comment]
@swaroop-sridhar still in progress?

**Comment by swaroop-sridhar** [comment]
I'll close the PR for now. @ramarag said he has an alternate suggestion for fixing  runtest.sh.
I'll sync up with him and open a different PR.

**Pull request closed without merging**
