### PR TITLE
Handle E_NOTIMPL return from CoInitializeEx.

### LINKED ISSUE #21693: CoInitializeEx returns E_NOTIMPL (0x80004001) on Windows Nano Server
It seems that on Windows Nano Server `CoInitializeEx(NULL, COINIT_APARTMENTTHREADED)` returns ` E_NOTIMPL (0x80004001)` which causes almost immediate failure of Checked coreclr with the following assertion at https://github.com/dotnet/coreclr/blob/master/src/vm/threads.cpp#L5259

```
Executed on nano1709c000B98

Assert failure(PID 2088 [0x00000828], Thread: 3312 [0x0cf0]): !"Unexpected HRESULT returned from CoInitializeEx!"

CORECLR! GetCLRRuntimeHost + 0xD9169 (0x00007ff9`f3d88bd9)
CORECLR! GetCLRRuntimeHost + 0x2ED350 (0x00007ff9`f3f9cdc0)
CORECLR! GetCLRRuntimeHost + 0xE56B1 (0x00007ff9`f3d95121)
CORECLR! coreclr_shutdown_2 + 0x7AB4A (0x00007ff9`f3ca9a2a)
CORERUN! <no symbol> + 0x0 (0x00007ff6`42626166)
CORERUN! <no symbol> + 0x0 (0x00007ff6`42627626)
CORERUN! <no symbol> + 0x0 (0x00007ff6`4264f594)
CORERUN! <no symbol> + 0x0 (0x00007ff6`4264f4be)
CORERUN! <no symbol> + 0x0 (0x00007ff6`4264f37e)
CORERUN! <no symbol> + 0x0 (0x00007ff6`4264f609)

    File: d:\git\coreclr2\src\vm\threads.cpp Line: 5259

    Image: C:\work\865cd393-0258-4fdd-9d5d-ee8e2ed14dda\Payload\corerun.exe

CORE_ROOT=C:\work\865cd393-0258-4fdd-9d5d-ee8e2ed14dda\Payload

BEGIN EXECUTION

C:\work\865cd393-0258-4fdd-9d5d-ee8e2ed14dda\Payload\corerun.exe C:\work\865cd393-0258-4fdd-9d5d-ee8e2ed14dda\Payload\xunit.console.dll C:\work\865cd393-0258-4fdd-9d5d-ee8e2ed14dda\Work\c3b6e807-e614-40b9-97c2-cdabc4e814ca\Unzip\baseservices.compilerservices.XUnitWrapper.dll -noshadow -xml testResults.xml -notrait category=outerloop -notrait category=failing

Finished running tests. Exit code = -1073740286
```

Shouldn't VM handle the case of E_NOTIMPL as well?

**Steps to reproduce**:
1. `build.cmd x64 checked`
2. `build-test.cmd x64 checked`
3. *(using Docker for Windows assuming coreclr repo is cloned to D:\git\coreclr)*
```
docker run --rm -it -v D:\git\coreclr:C:\git\coreclr -e CORE_ROOT=C:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root -w C:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root mcr.microsoft.com/windows/nanoserver:latest CoreRun.exe xunit.console.dll C:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Interop\IJW\Interop.IJW.XUnitWrapper.dll -noshadow -xml testResults.xml -notrait category=outerloop -notrait category=failing
```

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Handle `E_NOTIMPL` from `CoInitializeEx` and throw a `PlatformNotSupportedException` on failure, stating which thread apartment is not supported.

I've locally tested in a Windows 10 Nano Server docker container and verified the behavior.

Remove `STAThread` from the tests that have it. As far as I can tell, none of these tests need the STA thread.

This should unblock us on adding Nano helix queues.

Fixes #21693

cc: @echesakovMSFT

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
I think we should re-enable Nano platform testing once the eng team gets the new Nano docker images working on Helix (which is tracked by dotnet/core-eng#6037).

It also looks like all of the CI legs passed on retry (the first round failed from infra issues) so I'm going to merge this in.

**Comment by ericstj** [comment]
This broke CoreFx tests which do run on nano.

**Comment by jkoritzinsky** [comment]
Yeah we just discovered that in CoreCLR. There's a fix for xunit.console.dll that we just merged in (https://github.com/dotnet/arcade/pull/2710) that should fix that once it has a chance to propagate.

**Comment by ericstj** [comment]
You may hit other problems with that Arcade update.  I haven't root caused it yet but CoreFx was blocked on consuming arcade wholesale due to some change causing InvalidProgramException on test startup.  It would have been some change checked in to arcade between 4/29 and last night. 🤕

**Comment by jkoritzinsky** [comment]
Damn... Thanks for the heads up.

**Pull request merged**
