### PR TITLE
Move helper pipeline scripts under eng/pipeline/scripts

### PR DESCRIPTION
**Pull request by trylek**
To clean up contents of the eng folder, I'm moving all YAML scripts
used by Azure pipelines under eng/pipeline/scripts. Most of the rest
of the eng folder will get merged into a common eng folder in the
composite repo.

Thanks

Tomas

### CODE REVIEW

**Comment by hoyosjs** [comment]
Just a nit. Can we use a name that's not scripts? Under scripts I'd expect to find `*.sh;*.ps1;*.cmd;*.py` we use exclusivly for pipeline configuration. Folders like `steps` or `templates` may be more telling?

**Comment by trylek** [comment]
I can easily name them templates, no problem.

**Comment by trylek** [comment]
For the three pipelines (jitstressregs-x86, jitstress-isas-x86 and runincontext) I have launched them successfully and then I canceled them to avoid wasting lab resources - I'm not changing anything in their functionality, just the yml dependency graph.

**Comment by trylek** [comment]
This change should be fixing all job dependency issues that @BruceForstall recently reported (apologies for the inconvenience). I'm investigating the r2r-extra issue separately.

**Comment by ViktorHofer** [comment]
@trylek is this ready to be merged?

**Pull request merged**
