### PR TITLE
Block ops using rep on x86 need to kill edi/esi/ecx, same as x64

### PR DESCRIPTION
**Pull request by BruceForstall**

### CODE REVIEW

**Comment by BruceForstall** [comment]
@CarolEidt @adiaaida PTAL
/cc @dotnet/jit-contrib

**Comment by CarolEidt** [comment]
Looks good.

**Comment by adiaaida** [comment]
LGTM

**Comment by BruceForstall** [comment]
@mmitche Weird error in Windows_NT x86 ryujit Checked Build and Test:
```
MSBuild Error

error MSB3554: Cannot write to the output file "D:\j\workspace\x86_ryujit_ch---7ecedcb1\bin\obj\Windows_NT.x86.Checked\mscorlib.resources". The process cannot access the file 'D:\j\workspace\x86_ryujit_ch---7ecedcb1\bin\obj\Windows_NT.x86.Checked\mscorlib.resources' because it is being used by another process. [D:\j\workspace\x86_ryujit_ch---7ecedcb1\src\mscorlib\mscorlib.csproj]
Indication 1 
```
I've never seen this before. Is it new or unique to the CI? I'll retry it.

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT x86 ryujit Checked Build and Test

**Comment by mmitche** [comment]
There is a good chance that is a build concurrency issue

**Comment by BruceForstall** [comment]
Are there multiple CI builds on the same box? Or you think a concurrency issue with a single invocation of our build.cmd script that could happen on any sufficiently parallel machine?

**Comment by mmitche** [comment]
@BruceForstall Concurrency issue with a single msbuild invocation.  These can happen if msbuild decides it needs to build the same project twice accidentally.

**Pull request merged**
