### PR TITLE
Add a check to prevent mixed-mode assemblies from being compiled into R2R

### PR DESCRIPTION
**Pull request by fadimounir**
Porting from Desktop code

### CODE REVIEW

**Comment by fadimounir** [comment]
@swaroop-sridhar this is just porting the logic that you added for Desktop. The SDK filters mixed mode assemblies out anyways, but it's always good to also do it at the crossgen level.

**Comment by fadimounir** [comment]
Fix for #22640

**Comment by jkotas** [comment]
Support for R2R of mixed mode assemblies is still open check box in https://github.com/dotnet/coreclr/issues/18013 . Are we punting on it for .NET Core 3.0?

I think it is ok as long as there are no large mixed mode WPF assemblies. Just double checking that everybody is on the same page.

cc @jkoritzinsky @AaronRobinsonMSFT

**Comment by jkoritzinsky** [comment]
Yeah we're punting it for 3.0 as of now.

**Comment by jkoritzinsky** [comment]
I've removed the checkbox in #18013. I'll open another issue for tracking it.

**Pull request merged**
