### PR TITLE
Use Azure Artifacts feed instead of MyGet

### PR DESCRIPTION
**Pull request by garath**
As part of [moving to Azure Artifacts from MyGet](https://github.com/dotnet/arcade/blob/master/Documentation/MigrationPlan/MyGetFeeds.md), point all MyGet feed sources to new Azure Artifacts feed.

### CODE REVIEW

**Review by jashook — APPROVED** [review]
Just looking at the changes this looks good. Most of these things are unused in this branch. I believe it is worth starting an official build. I will work on doing this and see if there is anything that pops out.

/cc @jkoritzinsky @hoyosjs

**Comment by markwilkie** [comment]
Thanks @jashook - any results?  Love to get this merged.

**Comment by hoyosjs** [comment]
The only things I can think for this is stress dependencies. But largely I expect 2.1 to be OK, I don't expect buildtools to hardcode a dependency. This will be more of a problem for the UWP prodcon.

**Comment by markwilkie** [comment]
Are we good to merge this then?

**Comment by jashook** [comment]
Started

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3927783&view=results

Will monitor and merge if it looks good.

**Comment by jashook** [comment]
Pipeline seems to be broken for other infra reasons. Will not block merging.

**Comment by markwilkie** [comment]
Thanks a bunch @jashook

**Pull request merged**
