### PR TITLE
[dev/unix_test_workflow] Add test job mechanic to CrossGen Comparison scenario

### PR DESCRIPTION
**Pull request by echesakovMSFT**

### CODE REVIEW

**Comment by echesakovMSFT** [comment]
@dotnet-bot test ci please

**Comment by echesakovMSFT** [comment]
@dotnet-bot test ci please

**Comment by A-And** [comment]
@echesakov Heads-up - you might see some CoreFX job failures. I think this PR might have picked up the old exclusion list.

**Comment by echesakovMSFT** [comment]
@A-And Thanks for letting me know - I will rebase on top of dotnet/master

**Comment by echesakovMSFT** [comment]
@dotnet-bot test ci please

**Pull request merged**
