### PR TITLE
Move subset of wiki files to coreclr repo

### PR DESCRIPTION
**Pull request by richlander**
- Move instructional files to coreclr (retain history of wiki).
- Leave contribution guidelines in wiki.

Left to do:

- Delete moved files from wiki
- Fixup links to these files (from within the wiki and elsewhere).

/cc @terrajobst, @janvorli

### CODE REVIEW

**Comment by ellismg** [comment]
What's the value in keeping all of these commits as atomic things?  They aren't tied to the version history of the master branch in anyway.  It also appears that a non trivial number of them are empty.

If it was me, I would just take the files you ended with and commit them atop master, instead of having tons of commits and also have another chain of history that doesn't go back to the root.

**Comment by richlander** [comment]
My thinking was to preserve the history, as if these files had been in this repo from the start. Certainly, if we ever decided to pull a subset of corefx into this repo, we'd want to preserve history. It seems useful to me to know how these files have changed. I think that the *-instructions files are the most interesting for that.

It's possible that I did the history re-writing incorrectly. I see now that you are right, that there are indeed many more commits (empty ones) than we'd want. I could probably cut this set in half. Would that help?

Anyone else have any thoughts on how to approach this?

**Comment by ellismg** [comment]
> I could probably cut this set in half. Would that help?

I think it would.  I would be fine with showing major changes to the install guides (I agree there's value there) but I would love to see all of the commits where we all fight with the wiki to get the formatting right to be squashed away.

**Comment by richlander** [comment]
@ellismg sounds right. I'll try another run at this. I also agree with you.

**Comment by richlander** [comment]
@ellismg better?

**Comment by ellismg** [comment]
Two comments:

1) Since we are rewriting history anyway, it might be nice to remove the "(markdown)" text from the commit messages.

2) The following commits you made: a9affdff1e93090d27a772ad3a1b50ae08f474e2 and a6fa106a4ab4523086140ca29f639e365b5746f6 are authored by you with your personal email address.  Perhaps you would want to update the author so it uses your microsoft email.

Otherwise, LGTM.  Thanks for taking the time to clean this up.

**Comment by richlander** [comment]
@ellismg Think I'm done. Look good?

**Comment by ellismg** [comment]
Looks great.  Thanks!

**Pull request merged**
