### PR TITLE
Disable remaining Jenkins default-PR-triggered jobs

### PR DESCRIPTION
**Pull request by RussKeldorph**

### CODE REVIEW

**Comment by RussKeldorph** [comment]
@dotnet-bot test ci please

**Comment by davmason** [comment]
Thanks Russ, I had added something to disable just the corefx tests on my PR but I'll undo that and wait for yours to merge before I merge mine

**Comment by BruceForstall** [comment]
This change disables the following remaining jobs:

```
arm64_cross_checked_windows_nt_innerloop_flow_prtest
arm_cross_checked_ubuntu_crossgen_comparison_flow_prtest
arm_cross_checked_windows_nt_innerloop_flow_prtest
arm_cross_release_ubuntu_crossgen_comparison_flow_prtest
x64_checked_ubuntu_corefx_innerloop_prtest
x64_checked_windows_nt_corefx_innerloop_prtest
x64_release_windows_nt_corefx_innerloop_prtest
x64_ubuntu_formatting_prtest
x64_windows_nt_formatting_prtest
```

I presume we have (or soon will have) replacement corefx jobs in AzDO.

But what about the others?

**Comment by RussKeldorph** [comment]
@BruceForstall The non-default jobs will need to be ported as needed.  They are all going on a backlog with appropriate priorities or being cut.  Jenkins will continue to function for a while, but the clock is ticking.

**Pull request merged**
