### PR TITLE
Eliminate array allocations in CustomAttribute.IsDefined() overloads

### PR DESCRIPTION
**Pull request by jack-pappas**
Implemented struct enumerable and corresponding enumerator wrapping ``MetadataImport`` and ``MetadataEnumResult``.

Replaced ``CustomAttributeData.GetCustomAttributeRecords(RuntimeModule, int)`` with a new method returning a value of the new struct enumerable type (``CustomAttributeRecordCollection``); modified call sites of the old method to use the new method and structs instead.

These changes eliminate the short-lived ``CustomAttributeRecord[]`` allocations which currently result from calling any of the ``CustomAttribute.IsDefined()`` overloads.

### CODE REVIEW

**Comment by RussKeldorph** [comment]
@dotnet-bot test Ubuntu x64 Release Build and Test

**Comment by RussKeldorph** [comment]
@dotnet-bot test OSX x64 Release Build and Test

**Comment by jack-pappas** [comment]
@ellismg I've updated the PR per your comments. Uses of the ``var`` keyword have been removed, and I've modified the way the empty array case is handled within ``CustomAttributeData.GetCustomAttributes(RuntimeModule,int)`` so the type of the returned instance will be consistent with the non-empty array case.

**Comment by jack-pappas** [comment]
Also -- I signed a CLA several months ago, why does @dnfclas think I haven't? Just to be certain, I signed the CLA again and have received the approval email (from the CLA admin).

**Comment by jack-pappas** [comment]
Please disregard my last comment -- turns out I'd signed the Microsoft CLA before, not the new .NET Foundation CLA.

**Comment by jack-pappas** [comment]
@ellismg Is there anything else that needs to be done for this PR before it can be merged?

cc @jkotas

**Comment by jack-pappas** [comment]
@stephentoub Would you mind taking a look at this? I believe it's ready to be merged.

**Comment by jkotas** [comment]
Could you please shared any numbers on what it is improving? (see discussion in https://github.com/dotnet/coreclr/pull/3849 on what I am looking for)

**Comment by benaadams** [comment]
I applied this to https://github.com/dotnet/coreclr/pull/6645 and the performance regressed slightly :(

**Comment by Petermarcu** [comment]
So where do we sit on this one?  @jack-pappas , can you provide some concrete numbers showing the benefits realized by the change? If there is no forward motion with the PR, we should close it until we're ready to actively work through the data and finish it up.

**Comment by jack-pappas** [comment]
I'll run some benchmarks this weekend to try to get some results so we can make a decision one way or the other on this. I also want to poke around a bit to try to figure out what might've caused the code to be slower when @benadams tried it.

**Comment by jkotas** [comment]
Closing old inactive PRs. @jack-pappas please feel free to resubmit if you get a chance to finish this. Thanks!

**Comment by benaadams** [comment]
It doesn't currently allocate for enum ToString anymore so that might have been why I saw a regression (uses Array.Empty)

**Pull request closed without merging**
