### PR TITLE
Fix packaging attributes

### PR DESCRIPTION
**Pull request by schellap**
Ex: Project, Release Notes URL and Serviceable attribute.

@ericstj PTAL.

### CODE REVIEW

**Comment by schellap** [comment]
I've added this as two commits instead of 1 because the link has to be updated when porting to release branches.

**Comment by schellap** [comment]
Cc @gkhanna79

**Comment by gkhanna79** [comment]
Can you confirm that building results in the packaging containing the attribute?

**Comment by gkhanna79** [comment]
Fixes https://github.com/dotnet/coreclr/issues/5530

**Comment by schellap** [comment]
@ericstj need your :+1: @gkhanna79 verified this in core-setup, I don't see why this would be any different. `dotnet/coreclr` needs to pick up new buildtools to get this change, who can help with that?

**Comment by ericstj** [comment]
Setting Serviceable=true is redundant, this is the default.  Also, you'll need a buildtools update to make this work, but right now that's blocked on a nuget break.

**Comment by gkhanna79** [comment]
> Setting Serviceable=true is redundant, this is the default.

@ericstj If this is correct then, @leecow, shouldn't we let everyone know that even adding this attribute in nuspec is not required? Everyone has been rushing to add this attribute.

@schellap Please try to get the ReleaseNotes/ProjectUrl change in, independent of the servicing change since we are blocked against BuildTools update.

**Comment by ericstj** [comment]
@gkhanna79 these are `pkgproj` files, not `nuspec`s.  PkgProj is our own extension that uses buildtools to build nuspecs/nupkgs.  Since it is ours and all our stuff needs to be serviceable I set the default to true in our pkgproj infrastructure.

**Comment by gkhanna79** [comment]
Thanks for the explanation @ericstj. So PkgProj pushes this attribute to the nuspec that is generated? If so, we do not need any other change, right?

**Comment by leecow** [comment]
@gkhanna79 @schellap - now is a good opportunity to run the nuspec changes through the system and be done with it rather than relying on an artifact of the RC2 implementation.

**Comment by ericstj** [comment]
You need these: https://github.com/dotnet/coreclr/pull/5547/files#diff-0b192804a6349e8c26d2b027afbd89a2R149
You don't need the serviceable property but it won't hurt anything if its there.  It's just extra boilerplate.

You can merge as is or remove the properties.

I specifically made serviceable the default so that all we needed to do was update buildtools in all the repos using it and **not** have folks firedrill on this.

**Comment by gkhanna79** [comment]
@schellap Lets undo the serviceable property (for consistency) and only push the change for ProjectUrl and ReleaseNotes.

@ericstj Do we have the build tools identified that need to be updated?

**Pull request merged**
