### PR TITLE
Freebsd symbols3

### PR DESCRIPTION
**Pull request by wfurt**
Enable symbol publish again after https://github.com/dotnet/symstore/pull/79 and #21360 

Also note that this was enabled on corefx and runs without issues so far: https://github.com/dotnet/corefx/pull/34154

I did now test build and it finished publishing.
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2289092

I will monitor builds after this goes in for some time.

### CODE REVIEW

**Comment by mikem8361** [comment]
@wfurt, you didn't ask my question/review feedback and merged this PR.

**Comment by mikem8361** [comment]
ask -> answer.

**Comment by wfurt** [comment]
sorry @mikem8361 I was not sure if you are around. Do you have any concerns?

**Comment by mikem8361** [comment]
I don't know enough about what the FEATURE_PERFMAP enables to say. I just wanted confirmation that you do.

**Pull request merged**
