### PR TITLE
Add a GC Reliability Framework job to the CI

### PR DESCRIPTION
**Pull request by swgillespie**
This PR adds a new job, `gc_reliability_framework`, that can be requested on PRs via its trigger phrase. I've left it as a PR trigger-phrase job only for now until it's verified that it works - after that, we could run it at a more regular cadence.

The job will do a build and run the GC Reliability Framework on the CI machine, which runs for quite a long time and runs several tests simultaneously within the same process. It's found many bugs in the past and is generally very useful validation that recently has been done manually.

This PR also fixes an issue where the Standalone GC CI job couldn't be triggered through PR trigger phrases.

Fixes https://github.com/dotnet/coreclr/issues/4534.

### CODE REVIEW

**Comment by swgillespie** [comment]
@dotnet-bot test CI please

**Comment by swgillespie** [comment]
@dotnet-bot test CI please

**Comment by swgillespie** [comment]
@dotnet-bot test CI please

**Comment by swgillespie** [comment]
@dotnet-bot test CI please

**Comment by swgillespie** [comment]
@dotnet-bot test CI please

**Comment by swgillespie** [comment]
@dotnet-bot test CI please

**Comment by swgillespie** [comment]
@sergiy-k @Maoni0 @adityamandaleeka PTAL? Not sure who reviews CI changes.

I was having trouble running the RF on a new Linux VM yesterday, so that will probably require some additional investigation outside of this PR. OSX and Windows should both be able to run without problems, though - I ran this on both of those machines and didn't have trouble. (Though, you never know with CI... even if it works on my machine.)

**Comment by Maoni0** [comment]
@ramarag are you the right person to review this?

**Comment by ramarag** [comment]
last i heard @mmitche was the expert on the CI

**Comment by swgillespie** [comment]
are there any objections to this PR? I think it's ready to merge otherwise - it shouldn't have any effect on currently-running CI jobs.

**Comment by Maoni0** [comment]
has @mmitche reviewed?

**Comment by swgillespie** [comment]
Not yet - @mmitche, do you mind taking look?

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by swgillespie** [comment]
@dotnet-bot test CI please

**Comment by swgillespie** [comment]
@mmitche ping - do you mind taking a look if you get a minute?

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
LGTM

**Comment by swgillespie** [comment]
thanks!

**Pull request merged**
