### PR TITLE
Expose SafeAccessHandle

### PR DESCRIPTION
**Pull request by ianhays**
Progress towards https://github.com/dotnet/corefx/issues/13291

@weshaggard

### CODE REVIEW

**Comment by weshaggard** [comment]
Did you figure out what the release does on non-windows?

**Comment by ianhays** [comment]
>Did you figure out what the release does on non-windows?

I did not.  It calls the `Microsoft.Win32.Win32Native::CloseHandle` method which seems like it would be an issue, but several of the other exposed handles (e.g. SafeWaitHandle) in mscorlib do the same thing.

**Comment by jkotas** [comment]
> several of the other exposed handles (e.g. SafeWaitHandle) in mscorlib do the same thing

coreclr has specific PAL support for these handles; but not for the security principal ones.

**Comment by jkotas** [comment]
System.Security.Principal in corefx sounds like the best place to put this into (until we figure out what/if to merge System.Security.Principal with).

**Comment by weshaggard** [comment]
@jkotas is this safe handle different from the others? I thinking was to put it into System.Runtime with all the other safe handles.

**Comment by jkotas** [comment]
The concrete SafeHandles should be always together with the sub-system that they are supporting.
- SafeFileHandle and SafeWaitHandle in System.Runtime because of FileStream and synchronization primitives live there
- SafeRegistryHandle in Microsoft.Win32.Registry
- SafeProcessHandle in System.Diagnostics.Process
...

**Comment by ianhays** [comment]
@weshaggard sounds like I'll need to split a package regardless of whether we want this in System.Runtime or System.Security.Principal.

**Comment by weshaggard** [comment]
@ianhays the other option for this type is to consider removing it from netstandard if it isn't actually used by anything beyond WindowsIdentity which has been removed from netstandard already. Can you please have a look to see if there are any other usages of it and if not please file an issue assigned to me on dotnet/standard to remove it from netstandard just keep it where it is in corefx.

**Comment by ianhays** [comment]
Discussion forked to dotnet/standard: https://github.com/dotnet/standard/issues/104

**Pull request closed without merging**
