### PR TITLE
Tweaking some APIs according to user feedback.

### PR DESCRIPTION
**Pull request by tannergooding**
CC. @CarolEidt, @GrabYourPitchforks 

This handles the first part (CoreCLR side) of https://github.com/dotnet/corefx/issues/35768 and https://github.com/dotnet/corefx/issues/34881.

There will be a follow up PR in CoreFX updating the reference assembly and then a final PR against CoreCLR removing the outdated APIs and updating the tests. This is following the process we've done for prior tweaks to avoid "tearing" the API surface if something is snapped in between the various updates.

The first issue (35768) tracks us making the `Avx2.ConvertToVector256` overloads consistent with the `Sse41.ConvertToVector128` signatures and the corresponding native intrinsics. It also adds explicit APIs for the memory encoding since they are special and read partial vectors (but not single scalars) from memory.

The second issue (34881) tracks us updating various `Compare` methods to have consistent naming and trying to make those names less confusion.

### CODE REVIEW

**Comment by tannergooding** [comment]
CoreFX side is here: https://github.com/dotnet/corefx/pull/36757

**Comment by CarolEidt** [comment]
Overall this LGTM. Am I correct in understanding that JIT support for the new/changed APIs is yet to be added? I realize that the corefx reference assemblies don't yet have them, but it seems awkward that they are in SPC.dll but won't actually be recognized currently by the JIT.
Also, I have some concerns about existing support for pointer-based overloads, so I want to make sure we don't make that situation worse once support for these is added.

**Comment by tannergooding** [comment]
> Am I correct in understanding that JIT support for the new/changed APIs is yet to be added? I realize that the corefx reference assemblies don't yet have them, but it seems awkward that they are in SPC.dll but won't actually be recognized currently by the JIT.

Correct. This PR adds the new APIs, while keeping the previous ones. The end result is that the existing tests and existing code all work without change.

Once this is merged, it will flow back to CoreFX where we will update the reference assemblies by removing the old APIs and adding the new ones. That will then flow back into CoreCLR.

Finally, there will be a final PR against CoreCLR that removes the old APIs from S.P.Corelib, and fixes the JIT/tests to use the new names.

Overall, this minimizes the code churn required (we don't need to remove and then re-add several thousand lines of test code) and reduces the risk of CoreFX/CoreCLR getting out of sync.

> Also, I have some concerns about existing support for pointer-based overloads, so I want to make sure we don't make that situation worse once support for these is added.

Could you elaborate on the concern here? We can't support containment of the `Load` intrinsics on the existing overloads due to the read being a partial vector read (rather than a full vector read or a scalar read) and the normal solution has been to expose explicit overloads that take a T* instead.

**Comment by CarolEidt** [comment]
> We can't support containment of the Load intrinsics on the existing overloads due to the read being a partial vector read (rather than a full vector read or a scalar read) and the normal solution has been to expose explicit overloads that take a T* instead.

Right, I'm fine with the overloads. It's the JIT implementation that I find problematic. I think that these pointer overloads should be imported with a `GT_IND` so that we don't have the inconsistent semantics internally.

**Pull request merged**
