### PR TITLE
Revert "Revert "Enable Win32Arm CI support""

### PR DESCRIPTION
**Pull request by gkhanna79**
Reverts dotnet/coreclr#7213 and enable CI support for WinArm32.

@mmitche PTAL

### CODE REVIEW

**Comment by gkhanna79** [comment]
@mmitche Is there a way to test this without merging this?

**Comment by mmitche** [comment]
You can @dotnet-bot test ci please, find the job generated you want, enable and run it manually.

**Comment by gkhanna79** [comment]
@dotnet-bot test ci please

**Comment by gkhanna79** [comment]
@dotnet-bot test arm_cross_debug_windows_nt_prtest please

**Comment by gkhanna79** [comment]
@mmitche What does it mean to "enable and run manually"? The jobs are generated in https://ci.dot.net/job/dotnet_coreclr/job/master/job/GenPRTest/job/generator_prtest/16/consoleFull.

**Comment by mmitche** [comment]
https://ci.dot.net/job/dotnet_coreclr/job/master/job/GenPRTest/job/generator_prtest/

That job lists all the jobs generated.  You can find the one you want, enable it, and run it.

**Comment by mmitche** [comment]
https://ci.dot.net/job/dotnet_coreclr/job/master/job/GenPRTest/job/arm_cross_checked_windows_nt/

**Comment by mmitche** [comment]
(queued one up)

**Comment by gkhanna79** [comment]
@mmitche How do I enable a generated job and queue it? Also, if I have to rerun the job you queued earlier, how should I proceed to do so?

**Comment by gkhanna79** [comment]
I have tested this change against two WinArm32 PRs - https://ci.dot.net/job/dotnet_coreclr/job/master/job/GenPRTest/job/arm_cross_checked_windows_nt/ and https://ci.dot.net/job/dotnet_coreclr/job/master/job/GenPRTest/job/arm_cross_release_windows_nt/.

Both are green, so i am merging this change in.

**Pull request merged**
