### PR TITLE
Fix timing issues in some baseservices tests

### PR DESCRIPTION
**Pull request by wtgodbe**
https://github.com/dotnet/coreclr/issues/11503

CC @RussKeldorph

### CODE REVIEW

**Comment by wtgodbe** [comment]
@dotnet-bot test test Ubuntu Release pri1r2r

**Comment by wtgodbe** [comment]
@dotnet-bot test test Ubuntu Release pri1r2r

**Comment by wtgodbe** [comment]
Ubuntu R2R job is failing in the Ubuntu product build, which is surprising. I'm testing the same locally to see if it's an issue with my change or with the job

**Comment by wtgodbe** [comment]
@dotnet-bot test test OSX Release pri1r2r

**Comment by wtgodbe** [comment]
@dotnet-bot test OSX Checked pri1r2r

**Comment by wtgodbe** [comment]
@dotnet-bot test Ubuntu Checked pri1r2r

**Comment by wtgodbe** [comment]
The build command there is "./build.sh verbose release x64", versus "./build.sh verbose checked x64" in the CI job that succeeded (Ubuntu checked build and test), so unless it's a Release vs. Checked thing, I'm not sure what's happening. Still digging.

**Comment by wtgodbe** [comment]
OK, I've just confirmed that running "./build.sh verbose release x64" from master produces the same error, which is a problem. @janvorli can you take a look at the failures in the 
Ubuntu x64 Release R2R pri1 Build & Test job here?

**Comment by wtgodbe** [comment]
Official builds run "./build.sh Release x64 skipnuget -skiprestore stripSymbols -OfficialBuildId=20170613-01 -- /flp:v=diag", so it's either an issue in the package restore/package generation steps, or a machine issue.

**Comment by wtgodbe** [comment]
We see the same issue in all of these jobs, which run against master: https://ci.dot.net/job/dotnet_coreclr/job/master/job/release_ubuntu/

**Comment by wtgodbe** [comment]
The same doesn't happen for checked builds: https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_ubuntu/

So if the checked R2R job passes here, I think we can consider this PR to be a successful resolution of its issue, and we should open another issue to track the product build failure.

**Comment by wtgodbe** [comment]
@dotnet-bot test Windows_NT Release pri1r2r

**Comment by wtgodbe** [comment]
@dotnet-bot test Ubuntu Checked pri1r2r

**Comment by wtgodbe** [comment]
@dotnet-bot test Windows_NT Release pri1r2r

**Comment by wtgodbe** [comment]
Trying a new approach, which is to just surround the invocation of corerun with a takelock/releaselock, if we're running crossgen tests. My previous approach didn't work because it _assumed_ parallelism - if the tests were running serially, and a RunOnly was queued for execution before its BuildOnly, it would spin and wait forever for the BuildOnly to crossgen the .exe. I worry that this new approach will slow down non-Windows R2R runs, since it's taking away the parallelism there, so I'm going to see if there's a way to do the takelock/releaselock, ONLY when we're running a BuildOnly that has corresponding RunOnly's.

**Comment by wtgodbe** [comment]
@dotnet-bot test Ubuntu Checked pri1r2r
@dotnet-bot test Windows_NT Release pri1r2r

**Comment by wtgodbe** [comment]
@dotnet-bot test Ubuntu Checked pri1r2r
@dotnet-bot test Windows_NT Release pri1r2r

**Comment by wtgodbe** [comment]
@dotnet-bot test Ubuntu Checked pri1r2r
@dotnet-bot test Windows_NT Release pri1r2r

**Comment by wtgodbe** [comment]
Doesn't look like we lost much, if any, execution time - the R2R test run was 20 minutes slower than the IL test run, but that can probably be explained by the fact that the R2R run was running all pri-1 tests, while the IL run was running pri-0's. Merging.

**Comment by RussKeldorph** [comment]
@wtgodbe @gkhanna79 @Petermarcu Can we port this to release/2.0.0?  This should turn 40+ jobs from red to green, which is the majority of jobs with failures that we are tracking.

**Comment by gkhanna79** [comment]
I think it is reasonable to do so - @wtgodbe Can you please prepare a PR for Preview3 and email shiproom?

**Comment by wtgodbe** [comment]
I have put up https://github.com/dotnet/coreclr/pull/12371, and sent the email to shiproom.

**Pull request merged**
