### PR TITLE
Fixup Span<T> implementation to be more similar to the corefx one

### PR DESCRIPTION
**Pull request by jkotas**
- Reorder methods, adjust comments and formatting to make it easier to see the diff with corefx
- Delete extra implicit conversion operator

### CODE REVIEW

**Comment by jkotas** [comment]
@ahsonkhan @AtsushiKan @KrzysztofCwalina

**Comment by AtsushiKan** [comment]
The Span.Span(T[], int, int) overload still has the K&R-style "if (default(T)==null)" check that doesn't diff with the corefx one.

**Comment by AtsushiKan** [comment]
Span.TryCopyTo()
 if ((uint)_length > (uint)destination.Length)

Changing "destination.Length" to "destination._length" would make it diff perfectly.

**Comment by AtsushiKan** [comment]
Span.DangerousGetPinnableReference() is in a pretty different place in the two files.

**Comment by AtsushiKan** [comment]
LGTM modulo comments. (Which probably apply to ReadOnlySpan, though I didn't check each other.)

**Comment by jkotas** [comment]
> The Span.Span(T[], int, int) overload still has the K&R-style

Fixed.

> if ((uint)_length > (uint)destination.Length)

All other places in the implementation are using `_length` or `span._length` directly, so I have left this one as is for internal consistency. There are a few other similar nits that did not look like an improvement, so I have left them as is. It may be nice to fix them in the slow span instead.

**Pull request merged**
