### PR TITLE
Adjust plug_size_to_fit to consider large alignment on ARM32

### PR DESCRIPTION
**Pull request by VSadov**
Fixes:#22422

### CODE REVIEW

**Comment by VSadov** [comment]
all tests passed

**Comment by VSadov** [comment]
I am pretty convinced this fixes the original repro.

I see no failures at 400 iterations and counting, while without the fix it takes ~150/200 iterations to the first failure.

**Comment by VSadov** [comment]
880 iterations of the original test without a repro.

**Comment by Maoni0** [comment]
good to hear!

**Pull request merged**
