### PR TITLE
Linux/ARM: Unifying the redundant usages of objcopy

### PR DESCRIPTION
**Pull request by leemgs**
Let's remove the redundent file names using unified structure.

Signed-off-by: Geunsik Lim <geunsik.lim@samsung.com>

### CODE REVIEW

**Comment by leemgs** [comment]
> benpye commented 14 days ago
> Ah then sure, if that's also identified as an issue then yes this is a step toward. 
> LGTM modulo the one comment.

This PR is based on the existing merged PRs:                                                                             
  * https://github.com/dotnet/coreclr/pull/3944
  * https://github.com/dotnet/coreclr/pull/3946

\CC: @jkotas , @benpye , @mikem8361

**Comment by manu-silicon** [comment]
There is a typo for ARM64.

**Comment by leemgs** [comment]
Thanks. Fixed.

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by leemgs** [comment]
It's strange. Actually, the error report that CI have generated is not related to the PR. 

 * http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/debug_windows_nt_prtest/878/console

`C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomizations\masm.targets(50,5): error MSB4175: The task factory "XamlTaskFactory" could not be loaded from the assembly "Microsoft.Build.Tasks.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Could not find file 'C:\Users\dotnet-bot\AppData\Local\Temp\3gexwhvc.dll'. [D:\j\workspace\debug_windows---17180f1b\bin\obj\Windows_NT.x64.Debug\src\vm\wks\cee_wks.vcxproj]`

**Comment by jkotas** [comment]
LGTM.

**Pull request merged**
