### PR TITLE
Archive CI perf results

### PR DESCRIPTION
**Pull request by noahfalk**
I need to diagnose a failure that only reproes in CI but the CI scripts don't archive the logs on failure. This change should fix that.

### CODE REVIEW

**Comment by noahfalk** [comment]
PTAL @jorive

cc @nategraf @adiaaida

**Comment by adiaaida** [comment]
@noahfalk Can you also update the buildpipeline/perf-pipeline.groovy file with this change? You'd need to find the archiveArtifacts lines and add onlyIfSuccessful: false to them.

**Comment by noahfalk** [comment]
@dotnet-bot test perf build and test please

**Comment by noahfalk** [comment]
@adiaaida - sure, new PR running now. Is there any background material on why we have a second set of groovy scripts that we need to maintain in parallel?

**Comment by adiaaida** [comment]
@noahfalk We are working on switching over to the pipeline job only, but it's taking time. We tried turning the perf pipeline job on by default, but they were taking too long, though we have mostly addressed that issue. The pipeline jobs, ultimately, are meant to decrease the total amount of resources we need to use per perf job, since they can supply the same build to multiple perf test runs, and build on vms, while running on the physical hardware we use for perf testing (thus freeing up the perf machines for other runs).

**Comment by noahfalk** [comment]
Oddly two of the legs in CI are complete when I check Jenkins but GitHub still shows them to me as 'in process'. As best I can tell the perf run went fine.

**Pull request merged**
