### PR TITLE
Fix directory casing of `regressions' in test/src

### PR DESCRIPTION
**Pull request by ellismg**
We had both tests/src/Regressions and tests/src/regressions which causes
problems because the on disc casing of files now differs based on if you
have a case insensitive file system or not.

This was confusing the the mirror a great deal because the casing of the
files is unified on the TFS side but the mirror was seeing these files
as renames.

### CODE REVIEW

**Comment by joshfree** [comment]
LGTM

**Comment by stephentoub** [comment]
LGTM.  GitHub does a nice job showing the file name changes by clicking on the "showing 237 files changed" link.

**Comment by joshfree** [comment]
cat-hotdog

**Pull request merged**
