### PR TITLE
Use half-fences for volatile loads/stores on Windows ARM64

### PR DESCRIPTION
**Pull request by VSadov**
Needed for https://github.com/dotnet/coreclr/pull/23548

### CODE REVIEW

**Comment by VSadov** [comment]
In particular the perf sensitive part of `TryGet` from https://github.com/dotnet/coreclr/pull/23548

Before:
```asm
00000001`800f0c6c 9b0831c8 madd    x8, x14, x8, x12
00000001`800f0c70 9100a10a add     x10, x8, #0x28
00000001`800f0c74 b9400149 ldr     w9, [x10]
00000001`800f0c78 d5033fbf dmb     sy                             <---
00000001`800f0c7c f9400548 ldr     x8, [x10, #8]
00000001`800f0c80 eb00011f cmp     x8, x0
00000001`800f0c84 540000c1 bne     coreclr!CastCache::TryGet+0x64 (00000001`800f0c9c)
00000001`800f0c88 f9400948 ldr     x8, [x10, #0x10]
00000001`800f0c8c d5033fbf dmb     sy                             <---
00000001`800f0c90 ca01010b eor     x11, x8, x1
00000001`800f0c94 f100057f cmp     x11, #1
```

After:

```asm
00000001`800f0674 9b0831e8 madd    x8, x15, x8, x12
00000001`800f0678 9100a10b add     x11, x8, #0x28
00000001`800f067c 88dffd6a ldar    w10, [x11]                <---
00000001`800f0680 f9400568 ldr     x8, [x11, #8]
00000001`800f0684 eb00011f cmp     x8, x0
00000001`800f0688 540000c1 bne     coreclr!CastCache::TryGet+0x60 (00000001`800f06a0)
00000001`800f068c 91004168 add     x8, x11, #0x10
00000001`800f0690 c8dffd09 ldar    x9, [x8]                  <---
00000001`800f0694 ca01012d eor     x13, x9, x1
00000001`800f0698 f10005bf cmp     x13, #1
```

**Comment by VSadov** [comment]
CC @jkotas @davidwrighton @sdmaclea

**Comment by jkotas** [comment]
```
f:\workspace\_work\1\s\src\inc\volatile.h(163): error C3861: '__ldar16': identifier not found [F:\workspace\_work\1\s\bin\obj\Windows_NT.arm64.Checked\src\debug\ee\wks\cordbee_wks.vcxproj]
f:\workspace\_work\1\s\src\inc\volatile.h(166): error C3861: '__ldar32': identifier not found [F:\workspace\_work\1\s\bin\obj\Windows_NT.arm64.Checked\src\debug\ee\wks\cordbee_wks.vcxproj]
f:\workspace\_work\1\s\src\inc\volatile.h(169): error C3861: '__ldar64': identifier not found [F:\workspace\_work\1\s\bin\obj\Windows_NT.arm64.Checked\src\debug\ee\wks\cordbee_wks.vcxproj]
```

**Comment by stephentoub** [comment]
Related: https://github.com/dotnet/coreclr/issues/11545

**Comment by VSadov** [comment]
Build machine uses VS2017 ?

**Comment by VSadov** [comment]
https://github.com/dotnet/coreclr/issues/11545  Is related. However this is not about JIT-ed code. This tweaks c++ Volatile helpers when MSVC is used.
We do the right thing on GCC already.

**Comment by sdmaclea** [comment]
Possibly related #11885

**Comment by VSadov** [comment]
Yes, we are using VS2017 in the build.

```
BUILD: Commencing build of cross architecture native components for Windows_NT.arm64.Release
BUILD: Using environment: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\\..\..\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.16
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86_x64'
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.
-- The C compiler identification is MSVC 19.16.27034.0
-- The CXX compiler identification is MSVC 19.16.27034.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
```

**Comment by MichalStrehovsky** [comment]
Should this also be replicated in GC's copy of volatile.h under src\gc\env?

**Comment by VSadov** [comment]
Our build instructions require VS2019. https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-instructions.md

Why the lab uses 2017? How can this be fixed?

**Comment by sdmaclea** [comment]
> Our build instructions require VS2019. https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-instructions.md
> 
> Why the lab uses 2017? How can this be fixed?

/cc @jashook

**Comment by VSadov** [comment]
Yes.  gc\env\volatile.h  also needs updating. I did not realize it is a copy. Thanks!

**Comment by janvorli** [comment]
> Why the lab uses 2017? How can this be fixed?

There was a problem with optimizations in VS2019 breaking our explicit frames stuff during EH.  Release builds would crash when exception was thrown from some places in the runtime. While I've fixed that some time ago, @jkotas has discovered there is still an issue that needs to be fixed before we can migrate our builds to VS2019 (#27247).

**Comment by jkotas** [comment]
> there is still an issue that needs to be fixed before we can migrate our builds to VS2019 (#27247).

This issue should not be blocking upgrade to VS2019.

**Comment by janvorli** [comment]
> This issue should not be blocking upgrade to VS2019.

You are right, the issue now exists with both VS2019 and 2017.

**Comment by VSadov** [comment]
outerloop tests passed on Windows ARM64.

**Comment by VSadov** [comment]
Thanks!!

**Comment by BruceForstall** [comment]
@VSadov You state here, 
>outerloop tests passed on Windows ARM64.

However, the CI system currently does not run any tests on Windows arm64. If you look at the jobs, the important "Send tests to Helix" step is skipped for the two Windows arm64 Pri1 test runs.

So it seems this change got zero testing in the CI.

**Comment by VSadov** [comment]
I thought we skip running in inner loop, but that outer loop does some running on Win-arm64

**Comment by VSadov** [comment]
Also the changes make windows to use the same fences in Volatile as was used on Unix for a while. 
Do we have the issues on Windows only or on Unix as well?

**Comment by VSadov** [comment]
Oh, I see it is the type switch that could turn float into int.

Now, if we do a fix - how can we have _any_ CI coverage for the fix?

**Comment by BruceForstall** [comment]
> how can we have any CI coverage for the fix?

There is currently no support for any Windows arm64 testing in the CI today. Talk to @jashook about when we might get some... hopefully soon.

**Comment by jashook** [comment]
@VSadov for you change only please remove the skip for helix testing on arm64

**Pull request merged**
