### PR TITLE
Port to 1.0.0 - Fix passing struct with four floats in registers via reflection

### PR DESCRIPTION
**Pull request by janvorli**
This change ports a fix for a bug in the code that copies a struct into the transition
frame. When it contains four floats, the first two are put to the right place,
but the following two are placed to an address that's offset by 8 instead of
by 16.

It also ports regression test for this problem as Pri 1 test.

### CODE REVIEW

**Comment by eerhardt** [comment]
Fixes #14391

**Comment by janvorli** [comment]
@dotnet-bot test CentOS7.1 x64 Release Priority 1 Build and Test please

**Comment by janvorli** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test  please

**Comment by janvorli** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test  please

**Comment by janvorli** [comment]
The Pri 1 tests are failing due to the new test. It looks like the project needs to be tweaked for the 1.0.0 somehow:
```
test7685.cs(7,14): error CS0518: Predefined type 'System.Object' is not defined or imported [D:\j\workspace\x64_release_w---708a25ee\tests\src\Regressions\coreclr\GitHub_7685\Test7685.csproj]
07:44:27 test7685.cs(33,15): error CS0518: Predefined type 'System.ValueType' is not defined or imported [D:\j\workspace\x64_release_w---708a25ee\tests\src\Regressions\coreclr\GitHub_7685\Test7685.csproj]
```

**Comment by janvorli** [comment]
@mmitche, the build "Ubuntu x64 Checked Build and Test" in 1.0.0 branch has failed due to missing lldb-3.6-dev package.  @mikem8361 have you removed it when you were adding the support for llvm3.9?
See:
```
03:39:09 Re-run cmake no build system arguments
03:39:21 -- The C compiler identification is Clang 3.5.0
03:39:22 -- The CXX compiler identification is Clang 3.5.0
03:39:22 -- Check for working C compiler: /usr/bin/clang-3.5
03:39:22 -- Check for working C compiler: /usr/bin/clang-3.5 -- works
03:39:22 -- Detecting C compiler ABI info
03:39:22 -- Detecting C compiler ABI info - done
03:39:22 -- Check for working CXX compiler: /usr/bin/clang++-3.5
03:39:22 -- Check for working CXX compiler: /usr/bin/clang++-3.5 -- works
03:39:22 -- Detecting CXX compiler ABI info
03:39:22 -- Detecting CXX compiler ABI info - done
03:39:22 -- The ASM compiler identification is Clang
03:39:22 -- Found assembler: /usr/bin/clang-3.5
03:39:22 Detected Linux x86_64
03:39:23 -- Performing Test HAVE_UDAT_STANDALONE_SHORTER_WEEKDAYS
03:39:28 -- Performing Test HAVE_UDAT_STANDALONE_SHORTER_WEEKDAYS - Success
03:39:28 -- Looking for ucol_setMaxVariable
03:39:28 -- Looking for ucol_setMaxVariable - not found
03:39:28 CMake Error at src/ToolBox/SOS/lldbplugin/CMakeLists.txt:47 (message):
03:39:28   Cannot find lldb-3.5, lldb-3.6 or lldb-3.8.  Try installing lldb-3.6-dev
03:39:28   (or the appropriate package for your platform)
03:39:28 
03:39:28 
03:39:28 -- Configuring incomplete, errors occurred!
03:39:28 See also "/mnt/j/workspace/dotnet_coreclr/release_1.0.0/checked_ubuntu_prtest/bin/obj/Linux.x64.Checked/CMakeFiles/CMakeOutput.log".
03:39:28 See also "/mnt/j/workspace/dotnet_coreclr/release_1.0.0/checked_ubuntu_prtest/bin/obj/Linux.x64.Checked/CMakeFiles/CMakeError.log".
03:39:28 Failed to generate native component build project!
```

**Comment by mmitche** [comment]
@mikem8361 I didn't remove it...did you?

**Comment by mikem8361** [comment]
Yes I did remove lldb dev 3.6. I didn't think about older builds like this that doesn't look for 3.9. I was making sure we always built with 3.9 in the later.


-------- Original message --------

**Comment by mikem8361** [comment]
Should we go through all the VMs again (at the ones that will do 1.x builds) and re-install lldb-3.6-dev?  I'm sorry Matt to put you through all of that again because of my mistake.

**Comment by mmitche** [comment]
We could also roll back to the previous image for 1.0.  How many did you remove 3.6 from?

Matt

**Comment by mikem8361** [comment]
Pretty much all of them that had it installed.

**Pull request merged**
