### PR TITLE
update branding for coreclr to 3.1.4

### PR DESCRIPTION
**Pull request by Anipik**

### CODE REVIEW

**Comment by ericstj** [comment]
Didn’t we also need to suppress stable versioning for a short time?

**Comment by Anipik** [comment]
There are no stable packages produced in coreclr repo. We even the stabile Version properties from coreclr

**Review by wtgodbe — APPROVED** [review]

**Comment by wtgodbe** [comment]
Are the `System.Text.RegularExpressions.Tests` failures known?

**Comment by Anipik** [comment]
It seems just like a random timeout failure as it has no history of failure in coreclr or corefx

**Pull request merged**
