### PR TITLE
Enable tests to run under a specified GCStress mode

### PR DESCRIPTION
**Pull request by gkhanna79**
@jkotas PTAL

### CODE REVIEW

**Comment by jkotas** [comment]
LGTM

**Comment by jkotas** [comment]
(It is not something that you are introducing ... having GCStress, etc. as an argument to test build seems pretty broken. It should be argument for test run - the same test built binaries should be usable for all different test runs.)

**Comment by gkhanna79** [comment]
> the same test built binaries should be usable for all different test runs

I agree. The current broken behaviour is due to the test build generating the scripts required for test execution. If runtest would generate them, then this issue would be addressed. I have filed https://github.com/dotnet/coreclr/issues/3759 to track the issue.

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test please

**Comment by gkhanna79** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by gkhanna79** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by gkhanna79** [comment]
@briansull @jashook I see two tests failing in Ubuntu and OSX:

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/checked_osx_tst_prtest/70/testReport/
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/checked_ubuntu_tst_prtest/79/testReport/

These are failing due to missing assemblies. Is this due to the test refresh?

**Comment by briansull** [comment]
My test refresh can only impact ARM64 testing using Smarty.

**Comment by jashook** [comment]
Correct, as mentioned in #3763 the refresh is entirely independent from the new regressions.

**Pull request merged**
