### PR TITLE
Move SSE/SSE2/AVX Load* intrinsic tests to the template framework

### PR DESCRIPTION
**Pull request by fiigii**

### CODE REVIEW

**Comment by fiigii** [comment]
@dotnet-bot test Ubuntu arm Cross Checked no_tiered_compilation_innerloop Build and Test

**Comment by fiigii** [comment]
@CarolEidt @tannergooding PTAL

**Comment by fiigii** [comment]
Some tests failed on `DecimalRemainder` with `COMPlus_EnableAVX=0` and `COMPlus_EnableAVX2=0`, seems from https://github.com/dotnet/coreclr/pull/20305? @jkotas @pentp 
```  CoreMangLib_cti._system_decimal_DecimalRemainder_DecimalRemainder_._system_decimal_DecimalRemainder_DecimalRemainder_cmd [FAIL]
13:56:12         
13:56:12   
13:56:12   Return code:      1
13:56:12   Raw output file:      D:\j\workspace\x64_checked_w---c04c733a\bin\tests\Windows_NT.x64.Checked\Reports\CoreMangLib.cti\system\decimal\DecimalRemainder\DecimalRemainder.output.txt
13:56:12   Raw output:
13:56:12   BEGIN EXECUTION
13:56:12          "D:\j\workspace\x64_checked_w---c04c733a\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" DecimalRemainder.exe 
13:56:12         Beginning test case DecimalRemainder at 10/26/2018 1:56:11 PM
13:56:12         Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
13:56:12         
13:56:12         [Positive]
13:56:12         Beginning scenario: PosTest1: check Two Decimal Remainder.
13:56:12         ERROR!!!-001.4: Remainder should  return 0.000000000983
13:56:12         [Negtive]
13:56:12         Beginning scenario: NegTest1: d2 is zero.
13:56:12         
13:56:12         Ending test case at 10/26/2018 1:56:11 PM
13:56:12         FAIL
13:56:12         Expected: 100
13:56:12         Actual: 0
13:56:12         END EXECUTION - FAILED
13:56:12         FAILED
13:56:12         Test Harness Exitcode is : 1
13:56:12         
13:56:12   To run the test:
13:56:12   > set CORE_ROOT=D:\j\workspace\x64_checked_w---c04c733a\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root
13:56:12   > D:\j\workspace\x64_checked_w---c04c733a\bin\tests\Windows_NT.x64.Checked\CoreMangLib\cti\system\decimal\DecimalRemainder\DecimalRemainder.cmd
```

**Comment by fiigii** [comment]
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnoavx
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnoavx2

**Comment by pentp** [comment]
Yes, these tests are broken.
The failing case is 12345678900000000m % 0.0000000012345678m where it expects 0.000000000983m but the actual result is now 0.0000000009832122m (which is correct).
I'll create a PR with fixes.

**Comment by pentp** [comment]
#20648 should fix that test. I'm not sure why it's showing the file as binary (and doesn't show a diff).

**Comment by fiigii** [comment]
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnoavx
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnoavx2
@dotnet-bot test Windows_NT x64 Checked jitnox86hwintrinsic
@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnoavx
@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnoavx2
@dotnet-bot test Windows_NT x86 Checked jitnox86hwintrinsic
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnoavx
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnoavx2
@dotnet-bot test Ubuntu x64 Checked jitnox86hwintrinsic

**Comment by fiigii** [comment]
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnoavx2

**Pull request merged**
