### PR TITLE
Add all remaining JIT/Regression test cases for JIT

### PR DESCRIPTION
**Pull request by libengu**
Add all remaining JIT/Regression test cases for JIT. All under CLR-x86-JIT.
Related proj, config files added. AllTestProjects.sln update delayed for a
batch adding. Passed build, buildtest, runtest.

### CODE REVIEW

**Comment by libengu** [comment]
@AndyAyersMS @pgavlin PTAL. LLILC exclusion work under way.

**Comment by pgavlin** [comment]
Looks like at least one test is failing to build.

**Comment by libengu** [comment]
f14b317 fixed the issue. That was one added after a previous validation.

**Comment by libengu** [comment]
@AndyAyersMS @pgavlin Passed testing.

**Comment by AndyAyersMS** [comment]
LGTM.

I wonder if we should go back and clean up the compilation warnings?

**Comment by libengu** [comment]
@AndyAyersMS I think we'd better have a warning cleaning pass on all test cases including newer and older test cases.

**Pull request merged**
