### PR TITLE
Fixing JitBench

### PR DESCRIPTION
**Pull request by jorive**
- In the lab, the path where the JitBench sources are downloaded is already too long, which eventially causes `dotnet-install.ps1` to fail. Part of the changes are to reduce the PATH where the tests are placed.
- Updated the JitBench version/commit being used. This one is already on 2.1

### CODE REVIEW

**Comment by jorive** [comment]
@dotnet/rap-team PTAL

**Comment by jorive** [comment]
@dotnet-bot test Windows_NT x64 Performance Scenarios Tests please
@dotnet-bot test Windows_NT x86 Performance Scenarios Tests please

**Comment by jorive** [comment]
@dotnet-bot help

**Comment by jorive** [comment]
@dotnet-bot test ci please

**Comment by jorive** [comment]
@dotnet-bot test perf please

**Comment by jorive** [comment]
@dotnet-bot test ci please

**Comment by jorive** [comment]
@dotnet-bot test ci please

**Comment by jorive** [comment]
@dotnet-bot test ci please

**Comment by jorive** [comment]
@dotnet-bot test perf please

**Comment by DrewScoggins** [comment]
LGTM

**Pull request merged**
