### PR TITLE
Switch ubuntu PR tests from Release to Checked, and run Pri 1 tests on each commit

### PR DESCRIPTION
**Pull request by wtgodbe**

### CODE REVIEW

**Comment by wtgodbe** [comment]
@mmitche

**Comment by wtgodbe** [comment]
@dotnet-bot test CI please

**Comment by mmitche** [comment]
LGTM.  I'd like to get the rest of the configurations changed over too...using checked for the other OS's too (maybe we a few debug sanity builds)

**Comment by wtgodbe** [comment]
@mmitche do you think I should change OSX/FreeBSD for this PR as well, or just merge this one then take a look on Monday?

**Comment by mmitche** [comment]
@wtgodbe If they are passing right now, I'd change them.  I'd eliminate the debug build in one of those cases too.

**Comment by wtgodbe** [comment]
@mmitche how about now? I switched OS X, CentOS, FreeBSD and OpenSUSE to Checked

**Comment by wtgodbe** [comment]
@dotnet-bot test CI please

**Comment by mmitche** [comment]
@wtgodbe Perfect.  We can adjust as needed if we see breaks in release/debug configs.

**Comment by wtgodbe** [comment]
@dotnet-bot test CI please

**Pull request merged**
