### PR TITLE
JIT: port extra check to struct of struct of x promotion to relase/2.1

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Port of #19156.

Avoid promoting structs that contain struct fields that themselves
wrap single simple fields, if those single simple fields are smaller
than their enclosing struct.

Otherwise we run the risk of losing track of the "extra" bytes in the
innner struct.

Addresses #19149.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
Blocked by #19138.

Not comfortable merging this with this amount of CI failure.

**Comment by AndyAyersMS** [comment]
@dotnet-bot retest this please

**Comment by mikedn** [comment]
> OSX testing bailed right after starting pal tests:

Is there anyone looking at these CI random failures? Especially the OSX builds fail relatively often for unknown or at leas unobvious reasons.

**Comment by AndyAyersMS** [comment]
The [arm](https://ci.dot.net/job/dotnet_coreclr/job/release_2.1/job/arm64_cross_checked_windows_nt_innerloop_flow_prtest/71/) tests timed out, but the [OSX](https://ci.dot.net/job/dotnet_coreclr/job/release_2.1/job/x64_checked_osx10.12_innerloop_flow_prtest/278/) tests only ran for 13 minutes...

Anyways, will retry, I guess.

@dotnet-bot retest OSX10.12 x64 Checked Innerloop Build and Test
@dotnet-bot retest Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by AndyAyersMS** [comment]
[Arm64](https://ci.dot.net/job/dotnet_coreclr/job/release_2.1/job/arm64_cross_checked_windows_nt_innerloop_flow_prtest/72/) tests finally ran and there are about 20 test failures, all in interop tests.

Don't know how much we care about Arm64 in release 2.1.... @BruceForstall @jashook FYI.

Am going to go ahead and merge as these failures should be unrelated to this change.

**Pull request merged**
