### PR TITLE
Re-enable multi-queue for coreclr

### PR DESCRIPTION
**Pull request by smile21prc**
This PR includes Will's original multi-queue changes in coreclr, plus some fixes:

1. Stop using ConfigurationGroup as it's dedicated for CoreFx and means nothing to CoreCLR. Use "BuildType" instead (as below), because CoreCLR uses BuildType/BuildOS/BuildType to construct TestWorkingDir (in dir.props) 
    <HelixConfigLabel>$(BuildType)</HelixConfigLabel>

The correct value of BuildType is passed as param of script in "Send job to Helix" step.

2. I can't update the build tools to a newer version (which includes my support on "+" delimiter), because the "package build" steps will fail due to error below with newer version of build tools:

2017-03-28T23:00:14.6937120Z /root/coreclr/Tools/Microsoft.CSharp.CurrentVersion.targets(321,5): error MSB4019: The imported project "/root/coreclr/Tools/Microsoft.Net.Compilers/2.0.0-rc/tools/Microsoft.CSharp.Core.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [/root/coreclr/src/ToolBox/SOS/NETCore/SOS.NETCore.csproj]

This is unrelated to my change in build tools, which might be why coreclr hasn't updated to the tool version yet. As a result, I'm using current version of build tool (which does NOT include my support on "+" delimiter), and use ";" as delimiter for multi-queue. Different from CoreFx, Linux runs seem to work fine with ";", see:

Will Enqueue to 6 Queue(s) : debian.82.amd64;fedora.23.amd64;redhat.72.amd64;ubuntu.1404.amd64;ubuntu.1604.amd64;ubuntu.1610.amd64

in:
https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=643346&_a=summary

As long as it's working fine in official coreclr runs, there isn't a need to use "+" instead of "；“ for coreclr.

### CODE REVIEW

**Comment by smile21prc** [comment]
@MattGal , @wtgodbe , @mmitche, @dagood

**Comment by smile21prc** [comment]
@dotnet-bot test this please

**Comment by MattGal** [comment]
LGTM, but what about Fedora.25.Amd64?  Should also await signoff from someone from CoreCLR in Will's absence.

**Comment by gkhanna79** [comment]
@wtgodbe Will be in tomorrow, so if you can wait, please do.

**Comment by mmitche** [comment]
@smile21prc Nice work!

**Comment by smile21prc** [comment]
Thanks @mmitche . I'm applying build definition changes to coreclr official build and will babysitting it to make sure it runs successfully.

**Pull request merged**
