### PR TITLE
Fix #23905

### LINKED ISSUE #23905: Fix Windows arm break introduced by #23740
Error is
```
  Assert failure(PID 148 [0x00000094], Thread: 5892 [0x1704]): Consistency check failed: Managed object size does not match unmanaged object size
12:54:05   man: 0x30, unman: 0x2c, Name: System.Runtime.Loader.AssemblyLoadContext
12:54:05   FAILED: size == expectedsize
12:54:05   
12:54:05   <no module>! <no symbol> + 0x0 (0x00000000)
12:54:05       File: d:\j\workspace\arm_cross_che---7ce81708\src\vm\binder.cpp Line: 564
12:54:05       Image: C:\j\workspace\arm_cross_che---c874ca48\bin\tests\Windows_NT.arm.Checked\Tests\Core_Root\CoreRun.exe
```
possibly from #23740 ?

_Originally posted by @AndyAyersMS in https://github.com/dotnet/coreclr/pull/23889#issuecomment-482293883_

### PR DESCRIPTION
**Pull request by sdmaclea**
Adjust AssemblyLoadContextBaseObject packing for Windows arm.

Fixes #23905

### CODE REVIEW

**Comment by sdmaclea** [comment]
@dotnet-bot help

**Comment by sdmaclea** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test

**Comment by sdmaclea** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test

**Comment by sdmaclea** [comment]
@dotnet-bot help

**Comment by AndyAyersMS** [comment]
Hmm, let me see if I can start the testing for you

@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test

**Comment by sdmaclea** [comment]
@dotnet-bot test Ubuntu x86 Checked

**Comment by sdmaclea** [comment]
Last I knew x86 Ubuntu was not a supported platform.  Looks like the `Ubuntu x86 Checked` job has only run 10 times, there is no history of a passing test.  I am going to ignore the failure.

**Pull request merged**
