### PR TITLE
WIP: Fix gc-longrunning pipeline definition

### PR DESCRIPTION
**Pull request by trylek**

### CODE REVIEW

**Comment by trylek** [comment]
coreclr-gc-longrunning pipeline (started): https://dev.azure.com/dnceng/public/_build/results?buildId=416504

**Comment by VSadov** [comment]
I think we do not need to wait until this finishes. :-) 
It will take hours.

I have another PR where I will use this shortly and I can report if something is off.

**Comment by trylek** [comment]
Merging this in right away as I demonstrated that the change makes the GC long-running pipeline launch and the change is not actually exercised in any of the PR jobs.

**Comment by VSadov** [comment]
@trylek - Thanks!!!

**Pull request merged**
