### PR TITLE
Fix debuggertests failures OSX.

### PR DESCRIPTION
**Pull request by mikem8361**
The change that triggered the failures was going to a separate JIT module with its own PAL. The reason is a problem in the OSX exception forwarding a single-step exception: to forward/chain an exception to the next PAL the exception we restore the registers at the point of the exception and retry the it. For all the hardware exceptions this is fine, but for single-step the register state is after the instruction has been stepped so when it is retried and chained to the next PAL another instruction is stepped so the debugger gets notified an instruction after where it wanted. Chaining the single-step exception on Linux doesn’t have this problem because we just basically “jump” to the next PAL/signal handler.

The fix is too only “hook” single-step/breakpoint exceptions in the coreclr module/PAL (yet another PAL_INITIALIZE flag) and not in the JIT module (or any other non-coreclr PALs).

### CODE REVIEW

**Comment by mikem8361** [comment]
@janvorli and @jkotas could you review?

**Comment by mikem8361** [comment]
Fixes this issue: https://github.com/dotnet/coreclr/issues/5268

**Comment by jkotas** [comment]
LGTM

**Comment by janvorli** [comment]
LGTM

**Pull request merged**
