### PR TITLE
Do nothing if double is on stack.

### LINKED ISSUE #14375: [RyuJIT/arm32][TailcallStress=1] Assertion failed 'genIsValidFloatReg(reg)'
Found in x86_arm_altjit job with `COMPlus_TailcallStress=1`.

```
Assert failure(PID 6552 [0x00001998], Thread: 7164 [0x1bfc]): Assertion failed 'genIsValidFloatReg(reg)' in 'Fourier:thefunction(double,double,int):double' (IL size 102)

    File: d:\j\workspace\x86_arm_altji---58f521f4\src\jit\target.h Line: 2088
    Image: D:\j\workspace\x86_arm_altji---58f521f4\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
```

Test:
```
JIT\Performance\CodeQuality\Bytemark\Bytemark\Bytemark.cmd
```

### PR DESCRIPTION
**Pull request by sandreenko**
We need to copy only registers, if the source is located on the stack - do nothing.
Fix #14375.

After the fix Bytemark passes FOURIER, but fails further with another unconnected problem:
`Assert failure(PID 1348 [0x00000544], Thread: 27916 [0x6d0c]): Assertion failed 'tgtReg != tmpReg' in 'Neural:read_data_file():this' (IL size 844)

    File: c:\git\coreclr\src\jit\codegenarmarch.cpp Line: 1410
    Image: C:\git\coreclr\bin\tests\Windows_NT.x86.Debug\Tests\Core_Root\CoreRun.exe`

### CODE REVIEW

**Comment by sandreenko** [comment]
CentOS7 and Ubuntu formatting failures are unrelated to this change.

**Comment by sandreenko** [comment]
PTAL @dotnet/arm32-contrib

**Comment by hseok-oh** [comment]
@sandreenko I think this is to fix #14375, not #14603, right?

**Comment by BruceForstall** [comment]
@dotnet-bot
test Windows_NT x64_arm64_altjit Checked Build and Test
test Windows_NT x86_arm_altjit Checked Build and Test
test Windows_NT x86_arm_altjit Checked jitstress1
test Windows_NT x86_arm_altjit Checked tailcallstress
test Windows_NT x64_arm64_altjit Checked jitstress1
test Windows_NT x64_arm64_altjit Checked tailcallstress

**Comment by BruceForstall** [comment]
I opened #14617 for the tgtReg assert.

**Comment by sandreenko** [comment]
> @sandreenko I think this is to fix #14375, not #14603, right?
Yes, thanks.

**Pull request merged**
