### PR TITLE
Adding function Compiler::lvaGetVarNum(const LclVarDsc*) 

### PR DESCRIPTION
**Pull request by BrianBohe**
As a way of getting the index of a variable in compiler::lvaTable. There is a property of LclVarDsc for this purpose called lvSlotNum, which is not set for every variable.

### CODE REVIEW

**Comment by mikedn** [comment]
Overall I think this is a good improvement but I'm a bit concerned that this legitimizes a pattern that's not common in the JIT and if it were common it could be a perf issue.

Pointer difference hides a division operation and while the compiler will use magic division that's still going to be slower than the opposite operation, array indexing. Unless you're lucky and `sizeof(LclVarDsc)` is a power of 2 so that division is only a shift. But that's actually just another problem because it means that adding/removing `LclVarDsc` members could impact throughput.

Anyway, it looks like this mostly affects debug only code now so perhaps it's fine.

**Comment by BrianBohe** [comment]
The other approach is, always forward the varNum. Can we be sure that it doesn't increment the number of access to memory?

**Comment by mikedn** [comment]
> Can we be sure that it doesn't increment the number of access to memory?

I suppose it could, since now you may need to read both the array pointer and the index from somewhere. But in those cases where this might actually matter - small, hot loops - I would expect that the array pointer would be enregistered. And even if not enregistered, it will likely be in L1 cache where the load latency is 3-4 cycles. That's still less that the latency of magic division (~10 cycles AFAIR).

**Comment by BrianBohe** [comment]
I was expecting to use this in code that is not debug only. So we should consider it more. We can always leave it for just debug code putting the function between debug flags and explaining this.

**Comment by BrianBohe** [comment]
@mikedn I think the best is to close this PR.

**Comment by mikedn** [comment]
> I think the best is to close this PR.

Hmm, I think it might be a waste considering:

> We can always leave it for just debug code putting the function between debug flags and explaining this.

IMO pretty much any change that adds some sort of abstraction/encapsulation around LclVar access is a good change. We just need to be careful not to use `lvaGetVarNum` unnecessarily.

**Comment by mikedn** [comment]
> IMO pretty much any change that adds some sort of abstraction/encapsulation around LclVar access is a good change

Disclaimer: I added `lvaGetDesc`. And I have a pending PR that adds `lvaGetDescByTrackedIndex` and `lvaTrackedIndexToLclNum` :)

**Comment by BrianBohe** [comment]
It seems there was an update on jitutils

**Comment by BrianBohe** [comment]
> 
> 
> It seems there was an update on jitutils

There is no change to commit after running jit-format --fix

**Pull request closed without merging**
