### PR TITLE
Morph assert fix.

### LINKED ISSUE #9983: [SpanTests] Assertion failed 'genActualType(initVal->gtType) == TYP_INT
Assertion failure while running CoreFx System.Memory.Tests

**Commits**
54a84d07af050b6948cd54dc28cc694010623cb4
dotnet/corefx@b4c8c018d0b46ddf4def281574b0a1df51087e3f

**Output**
```
  Assert failure(PID 3056 [0x00000bf0], Thread: 7972 [0x1f24]): Assertion failed 'genActualType(initVal->gtType) == TYP_INT' in 'System.SpanTests.ReadOnlySpanTests:DangerousGetPinnableReferenceEmpty()' (IL size 33)
  
      File: d:\j\workspace\x64_checked_w---a7bd363e\src\jit\morph.cpp Line: 9101

D:\j\workspace\x64_checked_w---a7bd363e\_\fx\Tools\tests.targets(255,5): error : One or more tests failed while running tests from 'System.Memory.Tests' please check D:\j\workspace\x64_checked_w---a7bd363e\_\fx\bin/AnyOS.AnyCPU.Release/System.Memory.Tests/netcoreapp/testResults.xml for details! [D:\j\workspace\x64_checked_w---a7bd363e\_\fx\src\System.Memory\tests\System.Memory.Tests.csproj]
```

### PR DESCRIPTION
**Pull request by sivarv**
Fixes https://github.com/dotnet/coreclr/issues/9983

Promotion of structs containing fields which are in turn structs of single pointer-sized field can lead to an IR where blockop-asg (e.g. copyblk) RHS is a scalar.  AssertionProp can constant propagate and replace RHS scalar with a constant.  Morph will interpret such a blockop-asg with a constant on RHS as initblk incorrectly and hence the assert.

The short-term fix is to mark RHS scalar type local as DONT_CSE so that AssertionProp will not replace it with a constant.  

Fixes #9983

### CODE REVIEW

**Comment by sivarv** [comment]
@briansull - please review this.
CC @dotnet/jit-contrib 

I am in the process of collecting SPMI diffs due to this change.

**Comment by briansull** [comment]
LGTM

**Comment by sivarv** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test

**Comment by sivarv** [comment]
@dotnet-bot test Windows_NT Jitstress2
@dotnet-bot test Ubuntu Jitstress2

**Comment by sivarv** [comment]
There were no SPMI asm diffs due to this change.

**Comment by russellhadley** [comment]
How hard is dealing with the copy prop correctly and continuing to optimize?  If it's too hard get, please open an issue with an extracted repro so we can come back and get it.

**Comment by sivarv** [comment]
The issue here is that RyuJIT requires blockop assignment ops to be in certain IR form. With the current approach, if we let assertionprop do const replacement for the specific case exposed by this issue will violate blockop IR form and that is leading to asserts in morph logic.  To address this doing proper recursive struct promotion is the way to go than the current approach.

I have already filed the below issue listing the limitations of the current approach, which includes this one as well.
https://github.com/dotnet/coreclr/issues/10019

**Comment by sivarv** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test

**Comment by sivarv** [comment]
@mmitche - I am seeing random test failures with Windows_NT x64 release priority 1 leg.  So far I have triggered 3 runs and each time a different failure, which i could not repro locally on my machine.

Here is the failure message of the lone test that failed this time:
```
MESSAGE:
Test Infrastructure Failure: The paging file is too small for this operation to complete\r\nExpected: True\r\nActual: False

```

Any idea what is going on.

**Comment by sivarv** [comment]
@dotnet-bot test Windows_NT corefx_baseline

**Comment by sivarv** [comment]
@dotnet-bot help

**Comment by sivarv** [comment]
@dotnet-bot test Windows_NT x64 corefx_baseline

**Comment by sivarv** [comment]
Going to close and open this PR to see if it fixes flakiness.

**Comment by mmitche** [comment]
@sivarv The paging files on these machines are normal (and there is plenty of disk space). We've seen this a few times before but it may actually be a real issue (or at least a test issue)

**Pull request merged**
