### PR TITLE
Fix missing format specifier in Utilities.py

### PR DESCRIPTION
**Pull request by janvorli**
The Utilities.py script was missing the `%s` format specifier in
one of the prints and it was causing a build failure for me.

### CODE REVIEW

**Comment by janvorli** [comment]
@ramarag can you take a look please?

**Comment by ramarag** [comment]
LGTM

**Comment by janvorli** [comment]
@dotnet-bot test Windows_NT x86 Debug Build

**Comment by janvorli** [comment]
@dotnet-bot test Windows_NT x86 Release Build

**Pull request merged**
