### PR TITLE
Make Unix event tracing conditionally enabled

### PR DESCRIPTION
**Pull request by jkotas**
Add condition around the expensive event tracing code to enable it conditionally only if the event tracing is enabled

### CODE REVIEW

**Comment by jkotas** [comment]
cc @brianrob @ramarag

**Comment by jkotas** [comment]
This is one part of the fix for https://github.com/dotnet/coreclr/issues/3101

**Comment by brianrob** [comment]
LGTM

**Comment by ramarag** [comment]
LGTM

**Pull request merged**
