### PR TITLE
Unique-ify name of TestList.json to avoid collisions

### LINKED ISSUE #16840: CoreClr Official runs are overwriting their test list JSONs, which break the repro tool
@RussKeldorph , @maririos  FYI

Russ just showed me this problem, which you can see using the Helix API here:
https://helix.dot.net/api/jobs/422dc66a-f9f3-4e85-9cc2-c85b292521da/details?access_token=**your token**

The Job list is getting written here:
https://dotnetbuildoutput.blob.core.windows.net/coreclr-master-20180304-01/TestList.json
... but you'll note that there's nothing about this job list's url that separates it from a Windows, OSX, other linux, etc run;  what's happening is apparently some or all test builds are uploading the test list to the same path.   

Helix doesn't really care, as long as you leave the file alone for 4-5 seconds for us to parse it and distribute the work, but if two builds submitted simultaneously this would break regular runs.  It breaks the repro tool though because we need to keep this file around to see where the test bits are stored.

**To fix this:**

There's a few ways to do this:
- Use a distinct test list name by specifying TestListFilename : https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.Helix.targets#L83
- Use a distinct or default container name (CoreCLR is providing the container, here: https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.Helix.targets#L81)

I'd recommend the distinct test list name, assuming the blobs aren't all overwriting each other as well.

### PR DESCRIPTION
**Pull request by RussKeldorph**
Fixes #16840

### CODE REVIEW

**Comment by RussKeldorph** [comment]
> assuming the following builds look good.

@wtgodbe: Is there any way this change affects CI?  I was thinking of merging immediately and kicking off official build.  I could of course push a private branch, but it didn't seem worth it.

**Comment by RussKeldorph** [comment]
@jashook @brianrob FYI

**Comment by wtgodbe** [comment]
@RussKeldorph this will not affect CI. I think it'd be fine to merge & queue an official build, then revert if anything goes wrong.

**Comment by RussKeldorph** [comment]
@wtgodbe Great.  Thanks for confirming.  Will do.

**Pull request merged**
