### PR TITLE
Remove Span(T[], int) ctor

### PR DESCRIPTION
**Pull request by ahsonkhan**
~Step 1 to resolve issue https://github.com/dotnet/corefx/issues/23471~
**Edit:** Step 2 to resolve issue https://github.com/dotnet/corefx/issues/23471

cc @shiftylogic, @stephentoub, @jkotas

### CODE REVIEW

**Comment by jkotas** [comment]
You should get the corefx PR through first. This one should be second.

**Comment by jkotas** [comment]
Actually, it would be best to split this PR into 2 PRs, and use this order to get them in:

1. Test update in CoreCLR
2. CoreFX change
3. CoreLib update in CoreCLR

This would minimize the disruption from tests failing temporarily.

**Comment by wtgodbe** [comment]
@ahsonkhan @jkotas @stephentoub since this PR merged, all of our xunit wrappers have been failing with:

> Unhandled Exception: System.MissingMethodException: Method not found: 'Void System.Span`1..ctor(!0[], Int32)'.

This is causing mission control tests to be on the floor:  https://mc.dot.net/#/product/netcore/master/source/official~2Fcoreclr~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170825.03

Can one of you take a look at this, or revert this PR while I try to figure out where we're using that instance of this method?

**Comment by jkotas** [comment]
We need to get https://github.com/dotnet/coreclr/pull/13510 through to fix this.

**Comment by jkotas** [comment]
This should be fixed now.

**Pull request merged**
