### PR TITLE
Fix lclVar move node type inserted on lsra resolve phase 

### PR DESCRIPTION
**Pull request by hseok-oh**
When we try to insert lclVal move node (load, store) on lsra resolve phase,
fix type as TYP_INT if size is smaller than TYP_INT.

Related issue: #13156

### CODE REVIEW

**Comment by hseok-oh** [comment]
### Example
https://github.com/dotnet/coreclr/issues/13156#issuecomment-321437758

### Before

Generated code for inserted node
```
Generating: N001 (  1,  1) [000800] ------------Z      t800 =    LCL_VAR   char   V09 loc5          r1 REG r1
IN0045:             strh    r1, [sp+0x1c]       // [V09 loc5]

.......

Generating: N001 (  1,  1) [000801] ------------Z      t801 =    LCL_VAR   char   V09 loc5          r10 REG r10
IN0056:             strh    r10, [sp+0x1c]      // [V09 loc5]
```

Other node using V09
```
enerating: N457 (  9,  8) [000328] a--XG--------      t328 = *  IND       char   REG r2 <l:$375, c:$780>
                                                        Byref regs: 0004 {r2} => 0000 {}
IN005d:             ldrh    r2, [r2+8]
Generating: N459 (  1,  1) [000329] ------------z      t329 =    LCL_VAR   int    V09 loc5         u:3 r10 REG r10 <l:$344, c:$4c0>
                                                              /--*  t328   char
                                                              +--*  t329   int
Generating: N461 ( 17, 19) [000330] J--XG--N--S--      t330 = *  EQ        int    REG NA <l:$379, c:$37a>
IN005e:             ldr     r10, [sp+0x1c]      // [V09 loc5]
IN005f:             cmp     r2, r10
```

### After

Generated code for inserted node
```
Generating: N001 (  1,  1) [000800] ------------Z      t800 =    LCL_VAR   int    V09 loc5          r1 REG r1
IN0045:             str     r1, [sp+0x1c]       // [V09 loc5]

.......

Generating: N001 (  1,  1) [000801] ------------Z      t801 =    LCL_VAR   int    V09 loc5          r10 REG r10
IN0056:             str     r10, [sp+0x1c]      // [V09 loc5]
```

Other node using V09
```
Generating: N457 (  9,  8) [000328] a--XG--------      t328 = *  IND       char   REG r2 <l:$375, c:$780>
                                                        Byref regs: 0004 {r2} => 0000 {}
IN005d:             ldrh    r2, [r2+8]
Generating: N459 (  1,  1) [000329] ------------z      t329 =    LCL_VAR   int    V09 loc5         u:3 r10 REG r10 <l:$344, c:$4c0>
                                                              /--*  t328   char
                                                              +--*  t329   int
Generating: N461 ( 17, 19) [000330] J--XG--N--S--      t330 = *  EQ        int    REG NA <l:$379, c:$37a>
IN005e:             ldr     r10, [sp+0x1c]      // [V09 loc5]
                                                        V09 in reg r10 is becoming live  [000329]
                                                        Live regs: 03FB {r0 r1 r3 r4 r5 r6 r7 r8 r9} => 07FB {r0 r1 r3 r4 r5 r6 r7 r8 r9 r10}
IN005f:             cmp     r2, r10

```

**Comment by hseok-oh** [comment]
I have a question: this issue is architecture-specific (ARM32) issue or general issue?
cc/ @dotnet/arm32-contrib @dotnet/jit-contrib

**Comment by CarolEidt** [comment]
> Is this issue architecture-specific (ARM32) issue or general issue?

This is "sort of" an architecture-specific issue. If you look at the comments above the code you added, it says this:
```
    // There are three cases we need to handle:
    // - We are loading a lclVar from the stack.
    // - We are storing a lclVar to the stack.
    // - We are copying a lclVar between registers.
    //
    // In the first and second cases, the lclVar node will be marked with GTF_SPILLED and GTF_SPILL, respectively.
    // It is up to the code generator to ensure that any necessary normalization is done when loading or storing the
    // lclVar's value.
```
This is the second case, and it is being spilled by `genSpillVar()` in codegenlinear.cpp. It appears that the problem arises there. Although it talks about using the normalized type, it actually uses the tree type when getting the `instruction` to use. For x86/x64 it's the same `instruction`, and the size is what is used by `inst_TT_RV()`. That's why those targets don't have this issue.
I think the right fix is to change this: https://github.com/dotnet/coreclr/blob/master/src/jit/codegenlinear.cpp#L738
from
```
        instruction storeIns = ins_Store(tree->TypeGet(), compiler->isSIMDTypeLocalAligned(varNum));
```
to
```
        instruction storeIns = ins_Store(lclTyp, compiler->isSIMDTypeLocalAligned(varNum));
```

**Comment by hseok-oh** [comment]
@CarolEidt Thank you for your answer about my question. I'll fix it soon.

**Comment by hseok-oh** [comment]
@CarolEidt I've updated it. PTAL

**Pull request merged**
