### PR TITLE
Remove excessive console output in debug builds in a set of monitor tests

### PR DESCRIPTION
**Pull request by kouvel**

### CODE REVIEW

**Comment by kouvel** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test
test Ubuntu x64 Checked Innerloop Build and Test
test Ubuntu16.04 armlb Cross Debug Innerloop Build
help

**Comment by kouvel** [comment]
@dotnet-bot help

**Comment by kouvel** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test
test Ubuntu x64 Checked Innerloop Build and Test

**Comment by BruceForstall** [comment]
@kouvel Is this ready to merge? The remaining test failures are affecting every job.

**Pull request merged**
