### PR TITLE
Expose members of ExecutionContext and AsyncFlowControl

### PR DESCRIPTION
**Pull request by kouvel**
Missed these in PR #8042

### CODE REVIEW

**Comment by kouvel** [comment]
@rahku

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by kouvel** [comment]
Actually, hold off on reviewing this for now, I need to fix ExecutionContext implementation for compatibility with the desktop framework.

**Comment by kouvel** [comment]
Fixed, CC @stephentoub as well (PR #8042 has the previous changes to ExecutionContext for suppressing flow)

**Comment by kouvel** [comment]
Note that there were already a few differences before my changes between desktop and core, which I have retained:
- Desktop does not allow ExecutionContext.Run on the context acquired from Thread.CurrentThread.ExecutionContext, while core does
- Desktop does not allow ExecutionContext.Run more than once on a captured context, while core does

With my changes, there a couple more differences:
- Desktop does not allow CreateCopy on an execution context that has been passed into ExecutionContext.Run, or from an execution context obtained from Thread.CurrentThread.ExecutionContext, while core does
- Desktop has what looks like a bug, where Capture(), followed by SuppressFlow(), followed by Run(capturedContext), runs the callback in a state where the current execution context's flow is suppressed. That especially looks like a bug, since it transforms to the expected behavior by changing an async local value between Capture() and SuppressFlow(). Looks like a bug in the fast path where Capture() does not create a new instance, and SuppressFlow() mutates the same captured instance.

**Comment by rahku** [comment]
LGTM

**Pull request merged**
