### PR TITLE
Expose missing members of Array to prep for dotnet/corefx#9998. 

### PR DESCRIPTION
**Pull request by danmoseley**
modelgen.exe is helpful.

@stephentoub

### CODE REVIEW

**Comment by stephentoub** [comment]
The build failures are legitimate.  At least one of the members you're trying to add back are missing implementations for CoreCLR, e.g.
https://github.com/dotnet/coreclr/blob/08786f20e89eb5f518d8d25f3e7f886f69d994ea/src/vm/ecalllist.h#L1522-L1524
That's resulting in the failure:
```
Generating native image for System.Private.CoreLib.

Assert failure(PID 43633 [0x0000aa71], Thread: 43633 [0xaa71]): Consistency check failed: No method entry found for System.Array::get_LongLength.
FAILED: 0 != id
    File: /mnt/resource/j/workspace/dotnet_coreclr/master/debug_centos7.1_prtest/src/vm/ecall.cpp Line: 270
    Image: /mnt/resource/j/workspace/dotnet_coreclr/master/debug_centos7.1_prtest/bin/Product/Linux.x64.Debug/crossgen

Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

./build.sh: line 268: 43633 Aborted                 $__BinDir/crossgen $__BinDir/System.Private.CoreLib.dll
Failed to generate native image for System.Private.CoreLib.
```

**Comment by danmosemsft** [comment]
Ah. I naively believed I only needed to build mscorlib locally. Let me see..

**Comment by danmosemsft** [comment]
@stephentoub Good to go?

**Comment by stephentoub** [comment]
It looks ok to me, but it'd be good for @jkotas to confirm we're ok with changing the LongLength implementation like this.  To my knowledge, the longest possible array length in the runtime is less than int.MaxValue (https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Array.cs#L614), but we seem to have gone out of our way here to add this to the runtime, so it'd be good to get his perspective before it's deleted.

**Comment by danmosemsft** [comment]
In the apicatalog note about removing it, it says "this was added for standardization purposes but is not useful because the CLR does not support it". Good to get Jan's confirmation..

**Comment by jkotas** [comment]
In full framework, we do have option that allows creating multi-dimensional arrays with more than `Int32.MaxValue` elements (https://www.bing.com/search?q=gcallowverylargeobjects).

You should leave the implementation as is, and just remove the `FEATURE_CORECLR` ifdef around `ArrayNative::GetLongLengthNoRank` in vm\ecalllist.h.

**Comment by mikedn** [comment]
> In full framework, we do have option that allows creating multi-dimensional arrays with more than Int32.MaxValue elements (https://www.bing.com/search?q=gcallowverylargeobjects).

I don't think that's the case. gcallowverylargeobjects allow arrays greater than 2GB, not arrays with length > `Int32.MaxValue`.

**Comment by jkotas** [comment]
@mikedn You are right ... I forgot that we ended up not enabling the 2GB+ elements case. Thanks!

@danmosemsft My other comment about leaving the Length implementation as is, and just removing the ifdef in ecalllist.h still applies.

**Comment by jkotas** [comment]
LGTM

**Comment by stephentoub** [comment]
LGTM2 as long as it's squashed when merging.

Is this going to cause internal build failures due to the asmmeta file needing to be updated?

**Comment by jkotas** [comment]
> asmmeta file needing to be updated?

asmmeta file needs to be updated only for changes that affect full framework. This one is not affecting full framework.

**Pull request merged**
