### PR TITLE
Back patching #21804 to the 2.1 LTS branch

### PR DESCRIPTION
**Pull request by Tomius**
See the issue #22385

### CODE REVIEW

**Comment by danmosemsft** [comment]
Thanks. Servicing changes have to go through an approval process, especially for 2.1. Normally we start with discussion in an issue.

@briansull @RussKeldorph

**Comment by Tomius** [comment]
@RussKeldorph Yes, I discovered this bug in production code, and it has signifact financial consequnces for us.  .NET Core 2.2 is still vulnerable by this bug (I've tested both 2.2.0 and 2.2.1), so I don't see why would that be a solution.

**Comment by RussKeldorph** [comment]
@Tomius It will be much easier to service 2.2, so whether you can move to 2.2 needs to be taken into account.

**Comment by Tomius** [comment]
@RussKeldorph Using 2.2 is slightly more difficult to us, but if it's easier to service 2.2, I am happy with that compromise. I am closing this PR now, and reopening it based on the 2.2 (#22418).
On the other hand, leaving this bug on the long term support branch makes me feel uneasy, even if I personally won't be affected by it. I don't know how much more work does it take to backpatch to 2.1, but please do consider the option of having the fix available to a larger audience, even if after discussing you choose not to.

**Comment by RussKeldorph** [comment]
@Tomius 2.1 is harder to service because it has a lower risk tolerance than 2.2, and any change, including a bug fix, introduces risk.  The key for us is whether your client requires the LTS "feature" of 2.1 along with this bug fix.  If not, we might prefer to limit this to 2.2 if that is acceptable, though I will still ask whether this can be ported to 2.1 since it would be easier for you.  I hope to get back to you with an answer this week.  Thank you for the information.

**Comment by Tomius** [comment]
I have spoken to the representative people, and we do not require this to be patched onto 2.1. Having this patched only to 2.2 is fine with us.

**Comment by RussKeldorph** [comment]
@Tomius Ok, thanks for following up!

**Pull request closed without merging**
