### PR TITLE
Change default file permissions on Unix to 666

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/corefx/issues/13342

### CODE REVIEW

**Comment by ellismg** [comment]
Does this break MSBuild?  IIRC their Exec task writes out a shell script and then invokes it...

**Comment by jkotas** [comment]
msbuild is explicitly using `sh` so it should work fine: https://github.com/Microsoft/msbuild/blob/xplat/src/XMakeTasks/Exec.cs#L521. (Also, I believe that msbuild works on Mono that has the default that this PR is changing to.)

@rainersigwald @AndyGerlicher Do you see any problem with changing this default wrt. msbuild?

**Comment by rainersigwald** [comment]
I agree with your reasoning @jkotas. MSBuild should be fine.

**Comment by jkotas** [comment]
Thanks!

**Pull request merged**
