### PR TITLE
Import missing JIT tests.

### PR DESCRIPTION
**Pull request by pgavlin**
These tests were thought to have been ported earlier.

### CODE REVIEW

**Comment by pgavlin** [comment]
@richardlford @hoyMS PTAL

**Comment by richardlford** [comment]
@pgavlin, there are a bunch of files that appear to have no changes. 
Where these passing previously? Or will these require some exclusions
for CoreClr and LLILC?

**Comment by pgavlin** [comment]
I'm not sure why those files are marked as "no changes", but it's probably related to the warning "Sorry, we could not display the entire diff because too many files (1,219) changed". Essentially every file in this change is new.

It does look like there is a single failure in release builds--I'm investigating now. [The test in question](https://github.com/pgavlin/coreclr/blob/8036aa987b6a2df1ce71a1c5da3ce4b622050074/tests/src/JIT/Regression/CLR-x86-JIT/V1-M13-RTM/b99969/b99969.cs) looks a bit suspicious in its use of shared state. /cc @stephentoub @ericeil, who may be able to comment on the ordering of writes/reads to/from shared state.

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT x64 Release

**Comment by pgavlin** [comment]
@dotnet-bot test this please

**Comment by pgavlin** [comment]
This test failure does appear to be a real bug. I've filed #2286 to track.

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT x64 Debug Build

**Comment by pgavlin** [comment]
Windows_NT x86 Debug Build

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT x86 Debug Build

**Comment by pgavlin** [comment]
@dotnet-bot test Ubuntu x64 Release Build and Test

**Comment by pgavlin** [comment]
@dotnet-bot test this please

**Pull request merged**
