### PR TITLE
Fix class names for benchmarks

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Fix a couple of class names for benchmarks so they more accurately
describe the benchmark.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@chrismck PTAL
cc @dotnet/jit-contrib

**Comment by mikedn** [comment]
I suspect you wanted to mention @cmckinsey  and not chrismck :)

**Comment by chrismck** [comment]
Lol, it's funny how easy it is to get the wrong destination. Sorry 
chrismck is NOT your https://github.com/cmckinsey - I've got email 
before on the
dotnet fixes - forward to @cmckinsey who's the correct destination.

Chris McKernan

**Comment by AndyAyersMS** [comment]
Thanks all for the forwards.. believe I've even made this mistake before.

**Comment by CarolEidt** [comment]
LGTM

**Comment by AndyAyersMS** [comment]
There's really no risk in this change, so will merge despite the CI failure on OSX (networking issue after the real test pass had successfully finished.

**Pull request merged**
