### PR TITLE
Fix VN propagation for binops.

### PR DESCRIPTION
**Pull request by pgavlin**
When value numbering processes certain binary operators, it may attempt
to propagate the value number of one operand to the operator itself.
Unfortunately, this propagation was done irrespective of the type of the
operand, and therefore produced incorrect results when the type of the
operand did not match the type of the operator. This change only
performs this sort of propagation only when the types of the operator
and the operand agree.

### CODE REVIEW

**Comment by pgavlin** [comment]
@briansull @erozenfeld @dotnet/jit-contrib PTAL.

Fixes VSO 278369.

**Comment by erozenfeld** [comment]
LGTM. Any diffs with this change?

**Comment by pgavlin** [comment]
@erozenfeld: I will check. Which set of diffs are you interested in? S.P.CoreLib, FX, SPMI, etc.?

**Comment by erozenfeld** [comment]
SPMI

**Comment by briansull** [comment]
LGTM

**Comment by pgavlin** [comment]
I see no diffs in the S.P.CoreLib or the framework assemblies.

**Pull request merged**
