### PR TITLE
Enable Win32Arm CI support

### PR DESCRIPTION
**Pull request by gkhanna79**
At this point, we only want product and test build to happen as part of a PR - we will not be running any tests yet.

@mmitche @wtgodbe PTAL

### CODE REVIEW

**Comment by gkhanna79** [comment]
@mmitche Is there a way for me to test the new trigger I am adding, as part of this PR?

**Comment by mmitche** [comment]
@gkhanna79 Not easily, but that is coming to a CI system near you quite soon (hopefully next week).

**Comment by mmitche** [comment]
LGTM.  Does the build work today?

**Comment by gkhanna79** [comment]
The build did work last week. I will check if it has regressed since.

**Comment by wtgodbe** [comment]
LGTM

**Comment by gkhanna79** [comment]
Confirmed that latest master builds for Arm. Merging the PR.

**Pull request merged**
