### PR TITLE
Ensure PAL_Random returns unpredictable results.

### PR DESCRIPTION
**Pull request by eerhardt**
Update PAL_Random to read a single blocking byte from /dev/random for "strong" requests.  On newer kernel builds, once this single byte is read, then /dev/urandom will be initialized and return unpredictable results.  From then on, we can just read /dev/urandom to get unpredictable numbers.

Also, fixed PAL_Random to return FALSE if it was unable to ensure a "strong" random result.

@bartonjs, @morganbr, @ellismg, @stephentoub

### CODE REVIEW

**Comment by janvorli** [comment]
@eerhardt I have found "Myths about /dev/urandom" here:
http://www.2uo.de/myths-about-urandom/
From that I would assume that we should just be using /dev/urandom all the time without any tricks with the /dev/random readings.

Also, /dev/random and /dev/urandom behave the same way on OSX and FreeBSD, both being non-blocking, according to wikipedia (https://en.wikipedia.org/wiki//dev/random).

**Comment by eerhardt** [comment]
>http://www.2uo.de/myths-about-urandom/
 From that I would assume that we should just be using /dev/urandom all the time without any tricks with the /dev/random readings.

The issue we are addressing is described in the section "Not everything is perfect" of that article.

>Linux's /dev/urandom happily gives you not-so-random numbers before the kernel even had the chance to gather entropy. When is that? At system start, booting the computer. 
> And it doesn't help you the very first time a machine is running...
> Virtual machines are the other problem. Because people like to clone them...

This is why we are reading from /dev/random the first time, but then /dev/urandom for all other calls after that.

Another thing I forgot to mention in the description is that we have further plans to enhance PAL_Random to check for [getrandom()](http://man7.org/linux/man-pages/man2/getrandom.2.html), which is only available in kernel 3.17 and later.  If getrandom() is available, we will use that instead.  But if getrandom() isn't available, then we will use the current behavior that is being enhanced here.

**Comment by stephentoub** [comment]
But the blocking behavior seems really dangerous, even for just reading a single byte.  I try doing ```cat /dev/random```, and I find that it quickly blocks after outputting a few bytes.  I ctrl-c, then do it again... this time it blocks without reading any bytes.  If something else on the system has read from /dev/random and exhausted the bytes it's willing to provide, this could block for an arbitrarily long time, especially if there's little else happening on the system from which the kernel could source entropy.

**Comment by janvorli** [comment]
@eerhardt Ok, makes sense then. But then we should exclude this trick for OSX / FreeBSD, since it is Linux specific and the /dev/random is not blocking.

**Comment by eerhardt** [comment]
After some internal discussions, we've decided not to take these changes for Beta8.  I've opened https://github.com/dotnet/corefx/issues/3474 to track this for the future.

**Pull request closed without merging**
