### PR TITLE
Brand coreclr 2.2 as servicing and bump to 2.2.1

### PR DESCRIPTION
**Pull request by safern**
cc: @mmitche @karelz

### CODE REVIEW

**Comment by danmosemsft** [comment]
@safern I'd like to merge this so I can merge #20735.

**Comment by safern** [comment]
@dotnet-bot test this please

**Comment by safern** [comment]
Now that you merged the other PR we can merge this one if OK without having CI green.

**Comment by mmitche** [comment]
All these failures are unrelated.

**Pull request merged**
