### PR TITLE
Add empty System.Runtime.CompilerServices.RuntimeFeature.IsSupported() API

### PR DESCRIPTION
**Pull request by OmarTawfik**
Proposal is in: https://github.com/dotnet/corefx/issues/17116

Questions for area owners:

1) Is this the correct branch to use? is a rebase needed?
2) Do I need to run any additional tools? I see that `model.xml` is no longer used in the repo.
3) ~~Is there any additional work needed to copy this to corert repo? or is the mirroring tool going to handle it?~~

cc @jcouv @dotnet/roslyn-compiler

### CODE REVIEW

**Comment by jcouv** [comment]
Thanks! 👍 
FYI @AlekseyTs

**Comment by jkotas** [comment]
> Is there any additional work needed to copy this to corert repo?

You need to add it under `src\mscorlib\shared` for this to happen.

**Comment by OmarTawfik** [comment]
cc @VSadov for the proposal.

**Comment by OmarTawfik** [comment]
@jkotas fixed.
@terrajobst @karelz do I need another sign off from API before merging in?

**Comment by karelz** [comment]
Only 1 approval is needed - on the main CoreFX issue. You just need to implement exactly what was approved, no additional changes (not even arg names ;))

**Comment by danmosemsft** [comment]
@dotnet-bot Test OSX10.12 x64 Checked Build and Test (build break fix)

**Comment by OmarTawfik** [comment]
@jkotas comments addressed and resolved a minor conflict. Can you please take a look?

**Comment by jkotas** [comment]
LGTM

**Pull request merged**
