### PR TITLE
Fix missing checkout step in several pipelines

### PR DESCRIPTION
**Pull request by trylek**
I have apparently missed some of the pipelines in my "one checkout"
change. I have gone over all yml files under eng/pipelines and
fixed the four remaining yml files by adding the missing step.

Thanks

Tomas

### CODE REVIEW

**Comment by trylek** [comment]
coreclr-jitstress pipeline (running): https://dev.azure.com/dnceng/public/_build/results?buildId=359102

I don't know why it cannot be run from the PR using the /azp syntax.

**Comment by BruceForstall** [comment]
> I don't know why it cannot be run from the PR using the /azp syntax.

I think we limit which pipelines can be manually triggered because an unqualified "a_z_p run" causes *all* jobs to run, which is disastrous for machine utilization. I thought AzDO was going to fix this, or allow an opt-out, but I haven't heard further.

**Comment by trylek** [comment]
I see, that makes sense, thanks @BruceForstall for explanation!

**Pull request merged**
