### PR TITLE
Add 15 more Benchstone floating-point (BenchF) benchmarks in Xunit fo…

### PR DESCRIPTION
**Pull request by cmckinsey**
…rmat.

Each Benchmark runs in a few seconds in Release.

### CODE REVIEW

**Comment by cmckinsey** [comment]
@AndyAyersMS PTAL

**Comment by cmckinsey** [comment]
@dotnet/jit-contrib

**Comment by CarolEidt** [comment]
I'm glad to see these added. Although I realize that these are intended to be used primarily for performance testing, it would be great if there were a mechanism to test the results, so that we can ensure that we aren't breaking the functionality when we optimize the performance.

**Comment by AndyAyersMS** [comment]
Agreed it would be nice to add validation. Realize this is not always easy.

Overall this LGTM, with one important note: we've generally been running all the test sources through [codeformatter](https://github.com/dotnet/codeformatter). I'll leave it up to you to decide if you think there is merit in preserving the current formatting.

I'm tempted to say that for things like the Livermore Loops it would be nicer having one `[Benchmark]` per loop, but that's something we can do later if we think it is valuable to break them out individually.

**Comment by cmckinsey** [comment]
@AndyAyersMS I thought we talked about the validation issue at the start and agreed we'd preserve the benchmarks as is during this step and consider adding new validation code later if necessary.

I'm happy to run the codeformatter over it.

Regarding one [Benchmark] per loop, not sure its extra valuable. I'm mostly trying to preserve them in current form as much as possible.

**Comment by AndyAyersMS** [comment]
I"m fine with the change as is (modulo formatting). We can revisit validation and such down the road.

**Comment by cmckinsey** [comment]
@AndyAyersMS @CarolEidt I've pushed up the changes after running the codeformatter tool. This includes running the formatter over the previous 5 BenchF benchmarks for which this had not been done previously. Take another look.

@dotnet-bot test this please.

**Comment by AndyAyersMS** [comment]
Thanks, LGTM

**Comment by CarolEidt** [comment]
LGTM. Maybe we could add an issue to consider adding validation to the benchmarks.

**Comment by cmckinsey** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Comment by cmckinsey** [comment]
@AndyAyersMS @CarolEidt Added #2975 to cover adding validation code.

**Comment by CarolEidt** [comment]
Excellent thanks

**Comment by cmckinsey** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Pull request merged**
