### PR TITLE
[Arm64 Unix] Drive CI testing green [WIP]

### PR DESCRIPTION
**Pull request by jashook**
This adds a few excludes for arm64 unix.

### CODE REVIEW

**Comment by jashook** [comment]
@dotnet-bot help

**Comment by jashook** [comment]
@dotnet-bot test Ubuntu arm64 Checked

**Comment by jashook** [comment]
@dotnet-bot test Ubuntu arm64 Checked

**Comment by jashook** [comment]
@dotnet-bot test Ubuntu arm64 Checked

**Comment by karelz** [comment]
What is status of this PR? Do we still need it? There's no update for last 2 months ...

**Comment by jashook** [comment]
Will close for now.

**Pull request closed without merging**
