### PR TITLE
Add instructions for making idl file changes

### PR DESCRIPTION
**Pull request by noahfalk**
@davmason - do these instructions look accurate? I think you were the last person to do this operation in the profiler space

cc @bobuva @dotnet/dotnet-diag

### CODE REVIEW

**Comment by davmason** [comment]
That's it, as far as I can remember.

**Comment by bobuva** [comment]
@noahfalk @davmason I got a large number of compiler errors after copying changed files from `bin\obj\Windows_NT.x64.Debug\src\inc\idls_out\` to `src\pal\prebuilt\inc\`.  How do you go about building this if this type of thing is what you run into? I had 104 errors. Here are a few at the beginning of the list:

```
c:\src\dotnet\coreclr\src\debug\daccess\dacdbiimpl.cpp(211): error C2259: 'DacDbiInterfaceImpl': cannot instantiate abstract class [C:\src\dotnet\coreclr\bin\obj\Windows_NT.x64.Deb
ug\src\debug\daccess\daccess.vcxproj]
c:\src\dotnet\coreclr\src\debug\daccess\daccess.cpp(7481): error C2259: 'ClrDataAccess': cannot instantiate abstract class [C:\src\dotnet\coreclr\bin\obj\Windows_NT.x64.Debug\src\d
ebug\daccess\daccess.vcxproj]
c:\src\dotnet\coreclr\src\debug\daccess\nidump.cpp(611): error C2664: 'HRESULT IXCLRDataDisplay::WriteFieldStringW(const unsigned char *const ,unsigned int,unsigned int,const WCHAR
 *const )': cannot convert argument 1 from 'const char [5]' to 'const unsigned char *const ' [C:\src\dotnet\coreclr\bin\obj\Windows_NT.x64.Debug\src\debug\daccess\daccess.vcxproj]
c:\src\dotnet\coreclr\src\debug\daccess\nidump.cpp(615): error C2664: 'HRESULT IXCLRDataDisplay::WriteFieldInt(const unsigned char *const ,unsigned int,unsigned int,int)': cannot c
onvert argument 1 from 'const char [10]' to 'const unsigned char *const ' 
```

**Comment by noahfalk** [comment]
@bobuva - I'm guessing you copied all of the header files? What happens if you only copy corprof.h? Its possible someone hand edited some of them, but if so I don't want the burden on you to resolve it.

**Comment by bobuva** [comment]
Thanks @noahfalk I thought of just moving that over and dismissed it. Should have listened to myself :) That worked. Build succeeded!

**Pull request merged**
