### PR TITLE
Refactor JIT test projects.

### PR DESCRIPTION
**Pull request by pgavlin**
This change replaces the template projects used for the ported JIT tests
with a single project file per test. This refactoring is intended to
clarify exactly which tests from the legacy testbed have been ported
and what their dependencies are; this should make later reasoning about
these tests more straightforward.

This change also disables a number of innocuous warnings in the ported
tests for hygenic purposes.

### CODE REVIEW

**Comment by pgavlin** [comment]
@libengu @AndyAyersMS @russellhadley PTAL

**Comment by pgavlin** [comment]
(+ @mmitche )

**Comment by mmitche** [comment]
I cherry picked a couple dozen projects to look at as well as the master list of files.  They looked fine to me. :shipit:

**Comment by AndyAyersMS** [comment]
It looks like the project guid 
```
<ProjectGuid>{95DFC527-4DC1-495E-97D7-E94EE1F7140D}</ProjectGuid>
```
is the same in the the various project files (or at least is not unique). Not sure if this will cause problems.

**Pull request merged**
