### PR TITLE
Properly spell class name in comments

### PR DESCRIPTION
**Pull request by Dmitry-Me**

### CODE REVIEW

**Comment by danmosemsft** [comment]
@mmitche it seems that the formatting job can't find the jitformat tool; or the version of llvm is too old, according to the log. Who would be best to investigate that? I don't see this in the build tools repo.

**Comment by danmosemsft** [comment]
@mmitche for the ARM ones, do you know what this means? `06:55:38 ERROR: Unable to find project for artifact copy: dotnet_corefx/master/linuxarmemulator_cross_debug`

**Comment by mmitche** [comment]
@danmosemsft   It looks like someone renamed the jobs in coreclr without a correspoding change in corefx (also, the coreclr builds are failing at the moment too).

dotnet/corefx@98ec77e

This job copies from the corefx build.

/cc @wateret

**Comment by danmosemsft** [comment]
@mmitche is that the jitformat issue also?

**Comment by wateret** [comment]
Sorry for Linux ARM fails. It will be fixed when #7820 is merged.

**Comment by wateret** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please
@dotnet-bot test Linux ARM Emulator Cross Release Build please

**Comment by mmitche** [comment]
@danmosemsft No i have no idea what that is.  @adiaaida Who's responsible for the formatting job?

**Comment by adiaaida** [comment]
@danmosemsft That's an issue with the formatting tool itself. I checked in a fix yesterday, but after you opened your PR. Feel free to ignore as the Ubuntu leg passed.

**Comment by mmitche** [comment]
You can also rerun to verify @dotnet-bot test Windows_NT x64 Formatting

**Comment by mmitche** [comment]
(because your PR has no merge conflicts, the tests will be run against your PR 'merged' against the target branch)

**Comment by adiaaida** [comment]
His code doesn't touch jit code, so it won't affect the formatting legs.

**Pull request merged**
