### PR TITLE
Change referenced common.dll assembly to lower-case

### LINKED ISSUE #3235: New tests failing on Ubuntu Linux, but passing on Windows and OS X.
The following new tests fail on Unbuntu Linux, but pass on Windows and OS X:

```
JIT/jit64/localloc/eh/eh01_dynamic/eh01_dynamic.sh
JIT/jit64/localloc/eh/eh01_large/eh01_large.sh
JIT/jit64/localloc/eh/eh01_small/eh01_small.sh
JIT/jit64/localloc/eh/eh02_dynamic/eh02_dynamic.sh
JIT/jit64/localloc/eh/eh02_large/eh02_large.sh
JIT/jit64/localloc/eh/eh02_small/eh02_small.sh
JIT/jit64/localloc/ehverify/eh09_dynamic/eh09_dynamic.sh
JIT/jit64/localloc/ehverify/eh09_large/eh09_large.sh
JIT/jit64/localloc/ehverify/eh09_small/eh09_small.sh
JIT/jit64/localloc/unwind/unwind01_dynamic/unwind01_dynamic.sh
JIT/jit64/localloc/unwind/unwind01_large/unwind01_large.sh
JIT/jit64/localloc/unwind/unwind01_small/unwind01_small.sh
JIT/jit64/localloc/unwind/unwind02_dynamic/unwind02_dynamic.sh
JIT/jit64/localloc/unwind/unwind02_large/unwind02_large.sh
JIT/jit64/localloc/unwind/unwind02_small/unwind02_small.sh
JIT/jit64/localloc/unwind/unwind03_dynamic/unwind03_dynamic.sh
JIT/jit64/localloc/unwind/unwind03_large/unwind03_large.sh
JIT/jit64/localloc/unwind/unwind03_small/unwind03_small.sh
JIT/Regression/Dev11/External/dev11_145295/CSharpPart/CSharpPart.sh
JIT/Methodical/localloc/call/call01_small/call01_small.sh
```

They have been added to the non-Windows failure list.

### PR DESCRIPTION
**Pull request by BruceForstall**
Fixes a bunch of tests that were failing on Ubuntu. Re-enable those.

Fixes #3235.

### CODE REVIEW

**Comment by RussKeldorph** [comment]
LGTM

**Comment by BruceForstall** [comment]
Looks like there's still a problem with CSharpPart:
```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'ILPart, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
```
Maybe the same thing. I'll investigate.

**Comment by BruceForstall** [comment]
Ugh. On Ubuntu:
```
MSBuild Error

error MSB3554: Cannot write to the output file "D:\j\workspace\checked_windo---f6dc6fe4\bin\obj\Windows_NT.x64.Checked\mscorlib.resources". The process cannot access the file 'D:\j\workspace\checked_windo---f6dc6fe4\bin\obj\Windows_NT.x64.Checked\mscorlib.resources' because it is being used by another process. [D:\j\workspace\checked_windo---f6dc6fe4\src\mscorlib\System.Private.CoreLib.csproj]
Indication 1 
```

**Comment by BruceForstall** [comment]
@dotnet-bot test  Ubuntu x64 Checked Build and Test

**Comment by BruceForstall** [comment]
Same on Mac.

@dotnet-bot test OSX x64 Checked Build and Test

**Pull request merged**
