### PR TITLE
Allow a RET_EXPR as a BYREF operand for SIMD intrinsics.

### LINKED ISSUE #13568: [RyuJIT] Assertion failed 'tree->IsLocal() || (tree->gtOper == GT_ADDR) && varTypeIsSIMD(tree->gtGetOp1())'
From https://github.com/dotnet/coreclr/issues/13024

```
Assert failure(PID 4088 [0x00000ff8], Thread: 8120 [0x1fb8]): 
Assertion failed 'tree->IsLocal() || (tree->gtOper == GT_ADDR) && varTypeIsSIMD(tree->gtGetOp1())' in 
'VectorWiden.Program:TryGetAsciiStringVectorized(long,long,int):bool' (IL size 417)

    File: c:\github\coreclr\src\jit\simd.cpp Line: 694
    Image: C:\GitHub\PerfTesting\src\VectorWiden\bin\Release\netcoreapp2.0\win10-x64\publish\VectorWiden.exe
```

Repo project https://github.com/benaadams/PerfTesting/tree/master/src/VectorWiden

```csharp
Vector.Widen(
 vector,
 out Unsafe.AsRef<Vector<short>>(output),
 out Unsafe.AsRef<Vector<short>>(output + Vector<short>.Count)
);
```
Causes the issue, changing to
```csharp
Vector.Widen(vector, out var vector1, out var vector2);

Unsafe.AsRef<Vector<short>>(output) = vector1;
Unsafe.AsRef<Vector<short>>(output + Vector<short>.Count) = vector2;
```
Stops the assert

### PR DESCRIPTION
**Pull request by CarolEidt**
Fix #13568

### CODE REVIEW

**Comment by CarolEidt** [comment]
@benaadams - I copied your example almost verbatim for the test case. Let me know if you would prefer that I use a scaled-down test case.

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

**Comment by benaadams** [comment]
👍

**Comment by benaadams** [comment]
I have an improved version [TryGetAsciiStringVectorWiden](https://github.com/benaadams/KestrelHttpServer/blob/9afebd4b855bd9512c9c550db0615a82d63370fc/benchmarks/Kestrel.Performance/AsciiBytesToStringBenchmark.cs#L126-L225) the aspnet team frowned on my carefree application of gotos

**Comment by CarolEidt** [comment]
@dotnet-bot test Ubuntu x64 Formatting

**Pull request merged**
