### PR TITLE
Enable official builds from dev/defaultintf

### PR DESCRIPTION
**Pull request by jcagme**
Updating the PreReleaseLabel name so we get official Default Interface's builds.

/cc: @yizhang82 @ellismg

### CODE REVIEW

**Comment by yizhang82** [comment]
@jcagme Thanks! Feel free to merge once you got sign off from @ellismg.

**Comment by ellismg** [comment]
LGTM.

**Comment by jcagme** [comment]
Thanks @yizhang82 & @ellismg. Merging now.

**Comment by yizhang82** [comment]
Thanks @jcagme @ellismg When can we expect seeing official builds/packages getting produced?

**Comment by ellismg** [comment]
> Thanks @jcagme @ellismg When can we expect seeing official builds/packages getting produced?

Probably tomorrow, @jcagme is working on doing this.  We have build definitions for CoreCLR set up but they are currently not working.

**Comment by yizhang82** [comment]
@ellismg Cool. Let me know when it's done. I need to consume that package in corefx as a dependency since I'm adding a new API as well.

**Comment by jcagme** [comment]
> @ellismg Cool. Let me know when it's done. I need to consume that package in corefx as a dependency since I'm adding a new API as well.
Yes, I am aiming to have this done by tomorrow tops. I'll let you guys know when this is done and validated

**Pull request merged**
