### PR TITLE
[WIP] Fix SIGSEGV in GC when dealing with large double[] on ARM32 (#25403)

### PR DESCRIPTION
**Pull request by VSadov**
* Fix for #25252
* revert to special casing 8-alignement for double[] in GC helpers for x86

### CODE REVIEW

**Comment by VSadov** [comment]
Cherry-picked https://github.com/dotnet/coreclr/pull/25403 from master

**Comment by jashook** [comment]
Related to #25480

**Comment by VSadov** [comment]
Do not merge this just yet. See https://github.com/dotnet/coreclr/issues/25480

**Comment by sergiy-k** [comment]
Let's not port this into the release branch right now. The fix from the master branch will be included in Preview 8.

**Comment by VSadov** [comment]
It looks like the failures were all in the old PRs. No failures in the new PRs or builds.

I wonder if it is possible that re-running tests on a PR may occasionally pick new tests, but use the old build?

**Pull request closed without merging**
