### PR TITLE
Small fixes of compiler warnings

### PR DESCRIPTION
**Pull request by jo-so**

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
@jo-so Thanks for submitting the PR. Please let me know where/how you see these warnings. We should already be treating all warnings that aren't explicitly disabled as errors, so I'm curious how you caught these.

**Comment by swgillespie** [comment]
These have already been fixed on master by https://github.com/dotnet/coreclr/pull/11226.

**Comment by adityamandaleeka** [comment]
@swgillespie Ah, I missed that PR. I guess we can just close this PR, since I believe the code in master will flow to 2.0.0 soon.

**Comment by jo-so** [comment]
@adityamandaleeka I've saw them while I've tried to build with clang-4.0. It's a little more pickier.

**Pull request closed without merging**
