### PR TITLE
[WIP] test Egor's arm fix

### PR DESCRIPTION
**Pull request by sandreenko**

### CODE REVIEW

**Comment by sandreenko** [comment]
@dotnet-bot test Ubuntu arm Cross Release normal Build and Test
@dotnet-bot test Ubuntu arm Cross Debug normal Build and Test

**Comment by sandreenko** [comment]
All arm Ubuntu jobs say:
"(pending—There are no nodes with the label ‘ubuntu.1404.arm32.open’) "
[Example](https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_release_ubuntu_tst_prtest/).
Is it expected @jashook, @mmitche ? 
cc @echesakov, @BruceForstall

**Comment by BruceForstall** [comment]
This is the job that runs for every PR:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/arm_cross_checked_ubuntu_innerloop_tst_prtest/

They were successful up until 3:10pm today.

**Comment by BruceForstall** [comment]
I opened https://github.com/dotnet/core-eng/issues/3244 (is that what you're supposed to do?)

@RussKeldorph

**Pull request closed without merging**
