### PR TITLE
Fix CoreLib build warnings

### LINKED ISSUE #13848: Over a thousand warnings when building coreclr
Building coreclr now produces over a thousand warnings.  Most if not all of them appear to be non-CLS-compliance warnings stemming from the recently merged intrinsics work, e.g.
```
...
src\System\Runtime\Intrinsics\X86\Avx2.cs(1326,90): warning CS3001: Argument type 'Vector256<ulong>' is not CLS-complia
nt [c:\Users\stoub\Source\Repos\coreclr\src\mscorlib\System.Private.CoreLib.csproj]
src\System\Runtime\Intrinsics\X86\Avx2.cs(1359,40): warning CS3002: Return type of 'Avx2.Xor(Vector256<ulong>, Vector25
6<ulong>)' is not CLS-compliant [c:\Users\stoub\Source\Repos\coreclr\src\mscorlib\System.Private.CoreLib.csproj]
src\System\Runtime\Intrinsics\X86\Avx2.cs(1331,40): warning CS3002: Return type of 'Avx2.Xor(Vector256<sbyte>, Vector25
6<sbyte>)' is not CLS-compliant [c:\Users\stoub\Source\Repos\coreclr\src\mscorlib\System.Private.CoreLib.csproj]
src\System\Runtime\Intrinsics\X86\Avx2.cs(1359,61): warning CS3001: Argument type 'Vector256<ulong>' is not CLS-complia
nt [c:\Users\stoub\Source\Repos\coreclr\src\mscorlib\System.Private.CoreLib.csproj]
src\System\Runtime\Intrinsics\X86\Avx2.cs(1331,61): warning CS3001: Argument type 'Vector256<sbyte>' is not CLS-complia
nt [c:\Users\stoub\Source\Repos\coreclr\src\mscorlib\System.Private.CoreLib.csproj]
src\System\Runtime\Intrinsics\X86\Avx2.cs(1359,84): warning CS3001: Argument type 'Vector256<ulong>' is not CLS-complia
nt [c:\Users\stoub\Source\Repos\coreclr\src\mscorlib\System.Private.CoreLib.csproj]
src\System\Runtime\Intrinsics\X86\Avx2.cs(1331,84): warning CS3001: Argument type 'Vector256<sbyte>' is not CLS-complia
nt [c:\Users\stoub\Source\Repos\coreclr\src\mscorlib\System.Private.CoreLib.csproj]
    1192 Warning(s)
```

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #13848

### CODE REVIEW

**Comment by jkotas** [comment]
cc @stephentoub @fiigii

**Comment by jkotas** [comment]
@fiigii There may be matching changes needed for your corefx part of the change.

**Comment by fiigii** [comment]
@jkotas Thanks for the work. I already set `<ClsCompliant>false</ClsCompliant>` in the corefx PR to avoid CLS compliant **errors**.

**Comment by jkotas** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test please
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Pull request merged**
