### PR TITLE
Move the error that is emitted when libunwind is missing into CMake.

### PR DESCRIPTION
**Pull request by pgavlin**
This provides a friendlier user experience when libunwind is not
installed, as configuration fails earlier than the build does.

### CODE REVIEW

**Comment by pgavlin** [comment]
@janvorli @kangaroo PTAL

**Comment by janvorli** [comment]
LGTM

**Comment by kangaroo** [comment]
LGTM, only comment is the unset from the cache is something we're doing _nowhere_, so its not really consistent (but it is more user friendly).  Not blocking tho.

**Comment by pgavlin** [comment]
I noticed that as well. Issue #315 tracks fixing this.

**Pull request merged**
