### PR TITLE
Add test coverage for custom modifiers

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Custom modifiers are only lightly tested within the CLR test codebase (both closed and open). This adds targeted tests for:

* Resolution and overriding
* Various places that should ignore them
* Reflection

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
Cc @marek-safar @sergiy-k

**Comment by marek-safar** [comment]
@MichalStrehovsky very much appreciated! Could you extend it with aggregated types checks (like array, pointers, byrefs) ?

**Comment by MichalStrehovsky** [comment]
There is some coverage for arrays of modified types and pointers to modified types, but reflection doesn't seem to really represent them, so there's not much to test besides overload resolution. The test that actually tests them with reflection is around here:

https://github.com/dotnet/coreclr/pull/20546/commits/93108a399f1147ded3c7df17fb30b81a5462d3aa#diff-b0796e5081fa6afbfeef8893ece78c84R83

It's trying to access one of these methods:

https://github.com/dotnet/coreclr/commit/93108a399f1147ded3c7df17fb30b81a5462d3aa#diff-50789f8f1183310a4f01c7b8d6216b0eR57

**Comment by MichalStrehovsky** [comment]
@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test

**Pull request merged**
