### PR TITLE
Scalarize single-field-to-lclVar block copy

### PR DESCRIPTION
**Pull request by JosephTremoulet**
Morph has some logic to scalarize struct copies where the RHS is a scalar
and the LHS is a single-field struct.  This change adds the symmetric
logic where the LHS is a scalar and the RHS is a single-field struct.
This pattern shows up in Span<T> methods that initialize the data pointer
field, due to the way scalar replacement operates on spans.

### CODE REVIEW

**Comment by JosephTremoulet** [comment]
@briansull, @dotnet/jit-contrib PTAL.

This addresses the first bullet in #10019.

Here's an example diff from System.Private.Corelib:

before:
```asm
G_M8439_IG04:
       mov      qword ptr [rsp+50H], r15
       mov      qword ptr [rsp+48H], rax
       mov      qword ptr [rsp+40H], r14
       mov      rax, qword ptr [rsp+50H]
       mov      qword ptr [rdi], rax
       mov      rax, qword ptr [rsp+48H]
       mov      qword ptr [rdi+8], rax
       mov      rax, qword ptr [rsp+40H]
       mov      qword ptr [rdi+16], rax
       mov      rax, rdi
```

after:
```asm
G_M8439_IG04:
       mov      qword ptr [rdi], r15
       mov      qword ptr [rdi+8], rax
       mov      qword ptr [rdi+16], r14
       mov      rax, rdi
```

SuperPMI asm diffs report 1.22% codesize improvement across 440 affected methods.

jit-diff summary (full release tests/frameworks):
```
Summary:
(Note: Lower is better)

Total bytes of diff: -1559 (0.00 % of base)
    diff is an improvement.

Total byte diff includes 0 bytes from reconciling methods
        Base had    0 unique methods,        0 unique bytes
        Diff had    0 unique methods,        0 unique bytes

Top file improvements by size (bytes):
        -410 : dasmset_1\base\System.Private.CoreLib.dasm (-0.01 % of base)
        -344 : dasmset_1\base\Microsoft.CodeAnalysis.CSharp.dasm (-0.02 % of base)
        -210 : dasmset_1\base\Microsoft.CodeAnalysis.dasm (-0.03 % of base)
         -71 : dasmset_1\base\Microsoft.CodeAnalysis.VisualBasic.dasm (0.00 % of base)
         -65 : dasmset_1\base\System.Reflection.Metadata.dasm (-0.02 % of base)

27 total files with size differences (27 improved, 0 regressed).

Top method regessions by size (bytes):
           6 : dasmset_1\base\System.Private.CoreLib.dasm - Dictionary`2:CopyTo(ref,int):this (29 methods)
           5 : dasmset_1\base\Microsoft.CodeAnalysis.CSharp.dasm - ConversionsBase:AnalyzeImplicitUserDefinedConversions(ref,ref,ref,byref):struct:this
           4 : dasmset_1\base\Microsoft.CodeAnalysis.VisualBasic.dasm - _Closure$__20-2:_Lambda$__1(int):struct:this
           3 : dasmset_1\base\System.Private.CoreLib.dasm - Dictionary`2:System.Collections.ICollection.CopyTo(ref,int):this (29 methods)
           2 : dasmset_1\base\System.Private.CoreLib.dasm - Enumerator:MoveNext():bool:this (117 methods)

Top method improvements by size (bytes):
         -66 : dasmset_1\base\Microsoft.CodeAnalysis.CSharp.dasm - MethodCompiler:CompileNamedType(ref):this
         -56 : dasmset_1\base\System.Private.CoreLib.dasm - Span`1:op_Implicit(struct):struct (6 methods)
         -49 : dasmset_1\base\Regression\JitBlue\GitHub_2610\GitHub_2610\GitHub_2610.dasm - Program:Main():int
         -47 : dasmset_1\base\Microsoft.CodeAnalysis.CSharp.dasm - OverloadResolution:AnalyzeArguments(ref,ref,bool,bool):struct
         -35 : dasmset_1\base\Microsoft.CodeAnalysis.dasm - LocalScopeManager:GetAllScopesWithLocals():struct:this

120 total methods with size differences (114 improved, 6 regressed).```

**Comment by JosephTremoulet** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test

**Comment by JosephTremoulet** [comment]
@briansull, @dotnet/jit-contrib ping.

**Comment by briansull** [comment]
LGTM

**Comment by JosephTremoulet** [comment]
Regressions were all extra reg-reg copies; sometimes the slightly different input leads the RA down a different path and it winds up unable to remove the copies.  For example, here's the relevant snippet from compiling the top regression:

Coming into Rationalize, we still have the indirection in one case but not the other:
```
*************** In IR Rationalize
Trees before IR Rationalize
...
***** BB07, stmt 22
     (  8,  7) [000187] ------------             *  stmtExpr  void  (IL   ???...  ???)
N006 (  1,  1) [000300] -------N----             |  /--*  lclVar    long   V17 tmp11        u:3 (last use) <l:$444, c:$580>
N007 (  8,  7) [000301] -A----------             \--*  =         long   $VN.Void
N005 (  6,  5) [000299] *------N----                \--*  indir     long   <l:$444, c:$580>
N003 (  1,  1) [000297] ------------                   |  /--*  const     long   0 Fseq[m_value] $180
N004 (  5,  5) [000298] -------N----                   \--*  +         byref  $34d
N002 (  3,  3) [000295] L-----------                      \--*  addr      byref  $34c
N001 (  3,  2) [000296] D------N----                         \--*  lclVar    long   V15 tmp9         d:3
```
vs
```
*************** In IR Rationalize
Trees before IR Rationalize
...
***** BB07, stmt 22
     (  1,  3) [000187] ------------             *  stmtExpr  void  (IL   ???...  ???)
N001 (  1,  1) [000296] -------N----             |  /--*  lclVar    long   V17 tmp11        u:3 (last use) <l:$444, c:$580>
N003 (  1,  3) [000297] -A------R---             \--*  =         long   <l:$444, c:$580>
N002 (  1,  1) [000295] D------N----                \--*  lclVar    long   V15 tmp9         d:3 <l:$444, c:$580>
```

the rewrite in Rationalize actually reduces this to the same IR, but leaves the different costs:
```
Rewriting GT_IND(GT_ADD(LCL_VAR_ADDR,0)) to LCL_VAR
rewriting asg(lclVar, X) to st.lclVar(X)
N007 (  8,  7) [000301] DA----------             *  st.lclVar long   V15 tmp9         d:3
```
vs
```
rewriting asg(lclVar, X) to st.lclVar(X)
N003 (  1,  3) [000297] DA----------             *  st.lclVar long   V15 tmp9         d:3
```

leading to IR that really only differs in costs:

```
                                                 /--*  t293   long   
N003 (  1,  3) [000294] DA----------             *  st.lclVar long   V17 tmp11        d:3
N006 (  1,  1) [000300] -------N----      t300 =    lclVar    long   V17 tmp11        u:3 (last use) <l:$444, c:$580>
                                                 /--*  t300   long   
N007 (  8,  7) [000301] DA----------             *  st.lclVar long   V15 tmp9         d:3
N001 (  1,  1) [000113] ------------      t113 =    lclVar    ref    V11 tmp5         u:3 (last use) <l:$38f, c:$401>
                                                 /--*  t113   ref    
N003 (  1,  3) [000191] DA----------             *  st.lclVar ref    V14 tmp8         d:3
     ( 33, 36) [000151] ------------                il_offset void   IL offset: 112
N001 (  1,  1) [000318] ------------      t318 =    lclVar    int    V07 tmp1         u:3 $3c0
N002 (  1,  1) [000411] ------------      t411 =    lclVar    int    V24 cse4          $141
```
vs
```
                                                 /--*  t293   long   
N003 (  1,  3) [000294] DA----------             *  st.lclVar long   V17 tmp11        d:3
N001 (  1,  1) [000296] -------N----      t296 =    lclVar    long   V17 tmp11        u:3 (last use) <l:$444, c:$580>
                                                 /--*  t296   long   
N003 (  1,  3) [000297] DA----------             *  st.lclVar long   V15 tmp9         d:3
N001 (  1,  1) [000113] ------------      t113 =    lclVar    ref    V11 tmp5         u:3 (last use) <l:$38f, c:$401>
                                                 /--*  t113   ref    
N003 (  1,  3) [000191] DA----------             *  st.lclVar ref    V14 tmp8         d:3
     ( 31, 35) [000151] ------------                il_offset void   IL offset: 112
N001 (  1,  1) [000314] ------------      t314 =    lclVar    int    V07 tmp1         u:3 $3c0
N002 (  1,  1) [000407] ------------      t407 =    lclVar    int    V24 cse4          $141
```

which just happens to push the RA down a different path that leaves reg-reg copies in the code.

**Comment by briansull** [comment]
So the RA is useing the node costs to make decisions.

Maybe we should have the Rationalize phase update the node costs to be more correct after is changes the trees.

**Pull request merged**
