### PR TITLE
Add all JIT/Generics test cases

### PR DESCRIPTION
**Pull request by libengu**
Add all remaining JIT/Generics test cases for JIT. Related proj, config,
and sln files added and updated. Passed build, buildtest, runtest.

### CODE REVIEW

**Comment by libengu** [comment]
@AndyAyersMS @pgavlin PTAL

**Comment by libengu** [comment]
@CarolEidt PTAL.

**Comment by pgavlin** [comment]
LGTM.

**Comment by pgavlin** [comment]
Are there any new exclusions necessary for LLILC?

**Comment by libengu** [comment]
Yes. See https://github.com/dotnet/llilc/issues/596

**Comment by pgavlin** [comment]
Is there a corresponding PR to add the exclusions?

**Pull request merged**
