### PR TITLE
Fix etl rundown test with crossgen

### PR DESCRIPTION
**Pull request by nategraf**
Addresses #16710

### CODE REVIEW

**Comment by nategraf** [comment]
@dotnet-bot test Windows_NT x86 Checked r2r
@dotnet-bot test Windows_NT x64 Checked r2r

**Comment by nategraf** [comment]
@dotnet-bot test Windows_NT x86 Checked r2r
@dotnet-bot test Windows_NT x64 Checked r2r

**Comment by nategraf** [comment]
@dotnet-bot test Windows_NT x86 Checked r2r
@dotnet-bot test Windows_NT x64 Checked r2r

**Comment by nategraf** [comment]
The x64 R2R tests have been failing due to timeouts or unrelated errors, but if you look at the logs your can see that all trace validation tests (including Rundown) passed

**Comment by brianrob** [comment]
LGTM!

**Comment by RussKeldorph** [comment]
@nategraf "Addresses" isn't in the [list of magic keywords](https://help.github.com/articles/closing-issues-using-keywords/).

Did you mean to close #16710?

**Comment by nategraf** [comment]
Ya, I wasn't trying to try it automatically, but I did forget. Thanks Russ!

**Pull request merged**
