### PR TITLE
Fixes for building the Desktop JIT in CodegenMirror

### PR DESCRIPTION
**Pull request by briansull**
This PR contains fixes to enable building of the JIT in CodegenMirror

### CODE REVIEW

**Comment by briansull** [comment]
@BruceForstall @CarolEidt PTAL

**Comment by mjsabby** [comment]
@brinsull can you please squash and merge your commits? This keep the history linear and clean.

https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/contributing.md#merging-pull-requests-for-contributors-with-write-access

**Comment by briansull** [comment]
This was a single commit, not sure what  else you are asking for here?

**Comment by mjsabby** [comment]
You used the GitHub option that says "Create a merge commit", instead of "Squash and merge".

When that happens, the history in certain tools like the the following. Notice that most commits follow linear history, but yours is pointing back to the commit upon which your working on when you merged.

image

**Pull request merged**
