### PR TITLE
[x86/Linux] 16-byte aligned ResolveWorkerChainLookupAsmStub

### PR DESCRIPTION
**Pull request by parjong**

### CODE REVIEW

**Comment by parjong** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test please

**Comment by parjong** [comment]
@janvorli Please take a look. (OSX CI failure seems to be infra issue).

**Comment by parjong** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test please

**Comment by danmosemsft** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test  (network)

**Comment by parjong** [comment]
@janvorli Please take a look.

**Pull request merged**
