### PR TITLE
JIT: fix regression when returning struct with no fields on SysV

### PR DESCRIPTION
**Pull request by AndyAyersMS**
The runtime classifies such structs as being returned by reference, so we
need to follow suit in the jit. If the classifier says the value can't be
returned in a register, then so be it.

Add a test case.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@briansull PTAL
Should address failures seen in integrating a new coreclr into corefx: dotnet/corefx#30725

Verified CSharp tests pass on Unix with this change. One minor (and inconsequential diff) from PMI over fx (as the jit was self-consistent, but did not agree w/ the runtime). Expected diffs in new test case and in the CoreFX test case code.

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib

**Comment by jakobbotsch** [comment]
Would this explain the difference seen in https://github.com/dotnet/coreclr/issues/18672#issuecomment-400806623?

**Comment by AndyAyersMS** [comment]
@jakobbotsch I don't think so -- even though #18672 has a struct `S1` with no fields, it's not the return type for any calls.

**Pull request merged**
