### PR TITLE
Limit the libcoreclr.so exports to the necessary minimum

### PR DESCRIPTION
**Pull request by janvorli**
This change limits the libcoreclr.so exports on Linux / FreeBSD to functions that are PInvoked by the managed mscorlib / corefx and the DllMain, CoreDllMain and ExecuteAssembly.

### CODE REVIEW

**Comment by kangaroo** [comment]
@janvorli I'll give you a PR for the OS X side of this shortly into your fork.

**Comment by janvorli** [comment]
This is just a preliminary PR.
@ellismg, @stephentoub Could you please take a look at the new coreclr.ver file and confirm that the list of functions is complete? I have included all that I've found in Win32Native.cs and that exist in PAL and also the ones that were in the Interop.XXX.cs files in corefx.

**Comment by janvorli** [comment]
I still need to figure out how to make change in the coreclr.ver trigger libcoreclr.so relink.

**Comment by janvorli** [comment]
@kangaroo Thanks, that would be awesome.

**Comment by kangaroo** [comment]
PR https://github.com/janvorli/coreclr/pull/3

Please see my comment, you may want to refactor the build a smidgen.

**Comment by stephentoub** [comment]
> Could you please take a look at the new coreclr.ver file and confirm that the list of functions is complete?

I didn't notice any missing.

**Comment by pgavlin** [comment]
@janvorli I think that this is going to break LLILC. Can you hold off on merging until I've had a chance to verify?

**Comment by pgavlin** [comment]
Nevermind, looks like we're all good. This is green on my end as well.

**Comment by janvorli** [comment]
@kangaroo I have refactored it to generate the exports file from a single source for both OSX and Linux/FreeBSD and added the OSX specific linker option based on your PR. I have just modified the way the linker option is set to use TARGET LINK_DEPENDS property to make it the same on all systems, since your way didn't work on Linux.

**Comment by kangaroo** [comment]
LGTM -- but I haven't tested the refactor on OS X yet.  I'll do that after my bike ride.

**Comment by pgavlin** [comment]
Hm, I must have done something wrong when I tested this earlier. LLILC needs libcoreclr to export RaiseException.

**Comment by janvorli** [comment]
Thanks @pgavlin, I've added the RaiseException to the list of exports.

**Comment by janvorli** [comment]
@kangaroo, I've tested it on my Mac and it seems to work fine. Here is my nm -gU libcoreclr.dylib output:
```
0000000000067720 T _CloseHandle
0000000000bdc230 T _CoCreateGuid
0000000000bdc960 T _CoTaskMemAlloc
0000000000bdc980 T _CoTaskMemFree
0000000000044ef0 T _CopyFileW
000000000012fec0 T _CoreDllMain
000000000003c9f0 T _CreateDirectoryW
00000000000de200 T _CreateEventW
0000000000044870 T _CreateFileW
00000000000e38c0 T _CreateMutexW
00000000000e0fc0 T _CreateSemaphoreW
0000000000046d40 T _DeleteFileW
00000000001300f0 T _DllMain
0000000000066420 T _DuplicateHandle
00000000001317b0 T _ExecuteAssembly
0000000000059760 T _FindClose
0000000000058db0 T _FindFirstFileW
0000000000059a30 T _FindNextFileW
000000000004f260 T _FlushFileBuffers
000000000008e450 T _ForkAndExecProcess
00000000000945b0 T _FormatMessageW
0000000000093cb0 T _FreeEnvironmentStringsW
0000000000077ca0 T _GetACP
0000000000078290 T _GetConsoleCP
0000000000078420 T _GetConsoleOutputCP
000000000003ec50 T _GetCurrentDirectoryW
000000000010b2e0 T _GetCurrentProcess
000000000010b160 T _GetCurrentProcessId
00000000000935b0 T _GetEnvironmentStringsW
0000000000091b30 T _GetEnvironmentVariableW
0000000000049690 T _GetFileAttributesExW
000000000008f870 T _GetFileInformationFromFd
000000000008f520 T _GetFileInformationFromPath
000000000004e980 T _GetFileSize
000000000004fa00 T _GetFileType
000000000005c680 T _GetFullPathNameW
000000000005ce20 T _GetLongPathNameW
0000000000070b00 T _GetProcAddress
000000000004d150 T _GetStdHandle
000000000009dc10 T _GetSystemInfo
0000000000050a00 T _GetTempFileNameW
000000000005de10 T _GetTempPathW
000000000008d070 T _LocalAlloc
000000000008d440 T _LocalFree
0000000000052800 T _LockFile
000000000007eef0 T _MapViewOfFile
0000000000048320 T _MoveFileExW
0000000000078c40 T _MultiByteToWideChar
00000000000df080 T _OpenEventW
00000000000e4f70 T _OpenMutexW
00000000000e2020 T _OpenSemaphoreW
0000000000099e90 T _PAL_Random
000000000009f070 T _QueryPerformanceCounter
000000000009f3c0 T _QueryPerformanceFrequency
000000000004cf10 T _ReadFile
00000000000e3b40 T _ReleaseMutex
00000000000e1270 T _ReleaseSemaphore
000000000003e300 T _RemoveDirectoryW
00000000000dee70 T _ResetEvent
000000000008ad60 T _RtlZeroMemory
000000000003b0d0 T _SetConsoleCtrlHandler
000000000003f0b0 T _SetCurrentDirectoryW
000000000004dc70 T _SetEndOfFile
00000000000924e0 T _SetEnvironmentVariableW
00000000000940f0 T _SetErrorMode
00000000000de4b0 T _SetEvent
000000000004a180 T _SetFileAttributesW
000000000004e0b0 T _SetFilePointer
0000000000054a00 T _SetFileTime
0000000000052cd0 T _UnlockFile
0000000000080840 T _UnmapViewOfFile
00000000000850d0 T _VirtualAlloc
00000000000873a0 T _VirtualFree
0000000000089640 T _VirtualQuery
00000000000795f0 T _WideCharToMultiByte
000000000004c1e0 T _WriteFile
000000000000f220 T _lstrlenA
000000000000f480 T _lstrlenW
```

**Comment by kangaroo** [comment]
LGTM

**Comment by pgavlin** [comment]
LGTM as well.

**Comment by stephentoub** [comment]
@janvorli, I'd thought that EnsureOpenSslInitialized had been moved to System.Security.Cryptography.Native, but it looks like it wasn't... as such, it does need to be exported, and the fact that it's now not is causing failures in corefx CI build unfortunately.

**Comment by janvorli** [comment]
Added the missing EnsureOpenSslInitialized in #1074

**Pull request merged**
