### PR TITLE
Update PreRelease label for release/1.1.0 branch

### PR DESCRIPTION
**Pull request by gkhanna79**
@weshaggard @joperezr PTAL

### CODE REVIEW

**Comment by joperezr** [comment]
LGTM. Once you merge your CI change, you should be able to run a "test this please" to this PR and you should see the CI getting triggered.

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
I issued the command - @mmitche can I expect the CI to kick in given that corresponding change is merged in dotnet-ci?

**Comment by joperezr** [comment]
AFAIK you have to wait a bit for the deployment to finish. Yesterday I waited ~15 mins

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@gkhanna79 Once you get a few builds in, the arm emu stuff will start working (it's missing an input build right now)

**Comment by gkhanna79** [comment]
@dotnet-bot test Windows_NT x86 legacy_backend Checked Build and Test please

**Comment by mmitche** [comment]
@gkhanna79 If you see that again, let me know.  Java is crashing in a way that suggests that there may be some underlying OS bug (it crashes continually even after a new one is spawned until the parent powershell process is killed.  After that, it works as if nothing ever happened).  I enabled crash dumps for it, but will need to find a repro case.

**Comment by mmitche** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Comment by gkhanna79** [comment]
@mmitche OSX build failed with the following:

FATAL: channel is already closed
13:13:51 hudson.remoting.ChannelClosedException: channel is already closed
13:13:51 	at hudson.remoting.Channel.send(Channel.java:578)
13:13:51 	at hudson.remoting.Request.call(Request.java:130)
13:13:51 	at hudson.remoting.Channel.call(Channel.java:780)

**Comment by gkhanna79** [comment]
Also, the Linux ARM builds failed with the following:

```
ERROR: Unable to find a build for artifact copy from: dotnet_coreclr/release_1.1.0/release_windows_nt_bld
09:57:45 [Current build status] check if current [FAILURE] is worse or equals then [SUCCESS] and better or equals then [SUCCESS]
09:57:45 Run condition [Current build status] preventing perform for step [[Archive the artifacts]]
09:57:45 [BFA] Scanning build for known causes...
09:57:45 [BFA] Found failure cause(s):
09:57:45 [BFA] Missing upstream artifact from category Infrastructure
09:57:45 [BFA] Done. 0s
```

Does this ring a bell @mmitche ?

**Comment by gkhanna79** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build please

**Comment by gkhanna79** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by gkhanna79** [comment]
Merging since the issues are infra failures. Validated OSX build manually.

**Comment by mmitche** [comment]
@gkhanna79 That just looks like there isn't a current arm emu build available.  Apparently it's copying the last successful.

**Pull request merged**
