### PR TITLE
Fix marshaling IntPtr.Zero to UTF8 strings, add unit tests

### LINKED ISSUE #14084: Marshal.PtrToStringUTF8 does not handle IntPtr.Zero
Calling `Marshal.PtrToStringUTF8` with a value of `IntPtr.Zero` causes an access violation.
Calling the other `PtrToString*` variants return `null` in this case.

The offending code seems to be this line:
```
int nbBytes = System.StubHelpers.StubHelpers.strlen((sbyte*)ptr.ToPointer());
```

i.e. calling `strlen` on a possible null pointer.

### PR DESCRIPTION
**Pull request by qmfrederik**
Should fix #14084

### CODE REVIEW

**Comment by qmfrederik** [comment]
@dotnet-bot test Windows_NT x64 Formatting please

**Comment by tijoytom** [comment]
@qmfrederik thanks for fixing it.

**Comment by stephentoub** [comment]
Do we have / can we ensure we have corresponding tests in corefx?

**Comment by tijoytom** [comment]
We don't have any UTF8 marshaling related API test in CoreFX . I will submit a PR for it .

**Comment by stephentoub** [comment]
Thanks, @tijoytom.

**Pull request merged**
