### PR TITLE
Fallback for enum.Format(G) when not enum value

### PR DESCRIPTION
**Pull request by benaadams**
Resolves https://github.com/dotnet/corefx/issues/17730 in corefx

/cc @hughbe @svick @jkotas

### CODE REVIEW

**Comment by jkotas** [comment]
LGTM. Thanks for fixing this quickly! 

We should also add regression test for this to corefx.

**Comment by hughbe** [comment]
The tests already exist, but were testing the wrong behaviour. Should be as simple as running the tests and fixing the failures where `null` is expected

**Comment by benaadams** [comment]
Get to try the dotnet corefx test then; and it should fail :)

**Comment by benaadams** [comment]
@dotnet-bot test Windows_NT corefx_baseline

**Comment by benaadams** [comment]
@dotnet-bot help

**Comment by benaadams** [comment]
@dotnet-bot test Windows_NT x64 corefx_baseline

**Comment by benaadams** [comment]
Ubutntu failure

> Unhandled Exception: System.TypeLoadException: Could not load type 'System.Span' from assembly 'System.Memory, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

**Comment by jkotas** [comment]
> Could not load type 'System.Span' from assembly 'System.Memory'

@ahsonkhan Could you please finish the Span cleanup changes? The corefx and coreclr are out of sync now that is causing the tests to fail.

**Comment by benaadams** [comment]
Windows_NT x64 Checked Build and Test (Jit - CoreFx) failed for the correct reasons
```
Test Result (10 failures / +10)
System.Tests.EnumTests.GetName(enumType: typeof(System.SByteEnum), value: 3, expected: null)
System.Tests.EnumTests.GetName(enumType: typeof(System.ByteEnum), value: 3, expected: null)
System.Tests.EnumTests.GetName(enumType: typeof(System.Int16Enum), value: 3, expected: null)
System.Tests.EnumTests.GetName(enumType: typeof(System.UInt16Enum), value: 3, expected: null)
System.Tests.EnumTests.GetName(enumType: typeof(System.Int32Enum), value: 3, expected: null)
System.Tests.EnumTests.GetName(enumType: typeof(System.SimpleEnum), value: 99, expected: null)
System.Tests.EnumTests.GetName(enumType: typeof(System.UInt32Enum), value: 3, expected: null)
System.Tests.EnumTests.GetName(enumType: typeof(System.Int64Enum), value: 3, expected: null)
System.Tests.EnumTests.GetName(enumType: typeof(System.UInt64Enum), value: 3, expected: null)
System.Tests.EnumTests.GetName(enumType: typeof(TestName_Char), value: 0x0004, expected: null)
```

**Pull request merged**
