### PR TITLE
[x86/Linux] Restore PTR_MethodTable in FastPrimitiveArrayAllocator

### PR DESCRIPTION
**Pull request by parjong**
FastPrimitiveArrayAllocator (that JIT_TrialAlloc::GenAllocArray generates) should pass PTR_MethodTable, but currently passes RelativeFixupPointer<PTR_MethodTable>.

This bug results in #12545.

This commit revises JIT_TrialAlloc::GenAllocArray) to generate FastPrimitiveArrayAllocator that restores PTR_MethodTable from RelativeFixupPointer<PTR_MethodTable>.

In addition, this PR removes unnecessary ifdef introduces in #12562.

### CODE REVIEW

**Comment by parjong** [comment]
@dotnet-bot test Tizen armel Cross Release Build please

**Comment by jkotas** [comment]
@dotnet-bot test Windows_NT x86 Checked Build and Test please

**Comment by jkotas** [comment]
There is a ton of failures on Windows x86. I do not think that the change is good.

**Comment by parjong** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test please

**Comment by parjong** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test please

**Comment by parjong** [comment]
@dotnet-bot test 
Windows_NT x64 Release Priority 1 Build and Test please

**Comment by parjong** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by parjong** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test please

**Comment by parjong** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Comment by parjong** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test please

**Pull request merged**
