### PR TITLE
Reenable CoreFX tests that were marked as fixed.

### PR DESCRIPTION
**Pull request by sandreenko**

### CODE REVIEW

**Comment by sandreenko** [comment]
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_minopts Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstress2 Build and Test

**Comment by sandreenko** [comment]
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_minopts Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test CentOS7.1 x64 Checked Innerloop Build and Test

**Comment by filipnavara** [comment]
The ARM tests are actually failing on floating point formatting, re-run won't help. /cc @tannergooding

**Comment by sandreenko** [comment]
@filipnavara I thought https://github.com/dotnet/corefx/pull/35016 fixed that, did not it?

**Comment by filipnavara** [comment]
I didn't immediately pinpoint the cause when looking at it. Hopefully @tannergooding will have better idea what is going on.

**Comment by sandreenko** [comment]
@tannergooding it did not change, we need to wait another sync like https://github.com/dotnet/coreclr/pull/18557 to have these tests passed.

**Comment by filipnavara** [comment]
> The CoreFX tests, AFAIK, are not running against a live copy of CoreFX, but an older copy.

That's still the case (but I don't know who updates it and when).

**Comment by jkotas** [comment]
There are two different systems to run CoreFX tests in CoreCLR CI:

(1) A system that uses the fixed test snapshot. It is what the CoreFX legs that are on by default in CoreCLR CI use. 

(2) A system that builds a live copy of CoreFX and then runs the tests. This system is suffers from multiple source of flakiness (e.g. https://github.com/dotnet/coreclr/issues/22344#issuecomment-459913137). This system is used for optional JIT stress mode legs. This is the system that is being updated in this PR.

The plan how to move this forward and unify these systems is being discussed in https://github.com/dotnet/corefx/issues/34957#issuecomment-459415999

**Comment by sandreenko** [comment]
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_minopts Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstress2 Build and Test

**Comment by sandreenko** [comment]
is ci dead again?

**Comment by sandreenko** [comment]
@dotnet-bot test this please

**Comment by sandreenko** [comment]
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_minopts Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstress2 Build and Test

**Comment by filipnavara** [comment]
> is ci dead again?

nah (except for the AzurePipelines bot trigger words)

**Comment by sandreenko** [comment]
@dotnet-bot test this please

          @dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_minopts Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstress2 Build and Test

**Comment by sandreenko** [comment]
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_minopts Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstress2 Build and Test

**Comment by sandreenko** [comment]
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_minopts Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstress2 Build and Test

**Comment by filipnavara** [comment]
"CentOS7.1 x64 Debug Innerloop Build" looks like build infrastructure failure

"Ubuntu16.04 arm64 Cross Checked corefx_jitstress2 Build and Test" fails on
`System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Proxy_Test.ProxyAuth_Digest_Succeeds`. I don't see any issue filed for that (the one in CoreFX repository for the same test is an unrelated problem).

**Comment by sandreenko** [comment]
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_minopts Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstress2 Build and Test

**Comment by sandreenko** [comment]
> "Ubuntu16.04 arm64 Cross Checked corefx_jitstress2 Build and Test" fails on
> `System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Proxy_Test.ProxyAuth_Digest_Succeeds`. I don't see any issue filed for that (the one in CoreFX repository for the same test is an unrelated problem).

Created #22449 and excluded this test for this PR.

**Comment by sandreenko** [comment]
ci doesn't want to test it again: `1 in progress, 5 pending, and 2 successful checks`

@dotnet-bot test this please

**Comment by sandreenko** [comment]
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_minopts Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstress2 Build and Test

**Comment by sandreenko** [comment]
test Ubuntu16.04 arm64 Cross Checked corefx_jitstress2 Build and Test

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by sandreenko** [comment]
PTAL @BruceForstall @dotnet/jit-contrib 
This PR reenables CoreFX tests that were fixed and updates some issue numbers (that were incorrect or we moved).

**Comment by sandreenko** [comment]
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_minopts Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstress2 Build and Test


@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by sandreenko** [comment]
We have new failures in CoreFX after #22331 like: `System.MissingMethodException : Method not found: 'System.Range System.Range.Create(System.Index, System.Index)`.

@tarekgh do we need to wait a CoreFX update?

**Comment by tarekgh** [comment]
> do we need to wait a CoreFX update?

Yes we do. I hope we can get this done by tomorrow.

**Comment by tarekgh** [comment]
The other idea is to get this in and disable the failing test in corefx.issues.json. we can do that if we think we need to rush getting the new drop from corefx

**Comment by sandreenko** [comment]
> The other idea is to get this in and disable the failing test in corefx.issues.json. we can do that if we think we need to rush getting the new drop from corefx

This PR has been waiting for 5 days, it can wait another, don't worry.

**Comment by sandreenko** [comment]
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_minopts Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstress2 Build and Test

**Comment by sandreenko** [comment]
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_minopts Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstress2 Build and Test

**Comment by sandreenko** [comment]
test Ubuntu16.04 arm64 Cross Checked corefx_jitstress2 Build and Tes

**Comment by sandreenko** [comment]
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_jitstress2 Build and Test
looks like it doesn't want to restart.

**Comment by tarekgh** [comment]
@sandreenko to let you know, the changes for fixing the Range/Index in corefx is delayed because we have been not getting the coreclr new build to corefx.

**Comment by sandreenko** [comment]
I thought CoreFX part was merged with https://github.com/dotnet/corefx/commit/b0b16179288058f42d95fe89faa76bf86496bbb9, was not it?

**Comment by tarekgh** [comment]
@sandreenko no, this PR was just the mirroring of the shared files between coreclr and corefx. The needed changes in corefx is in the PR https://github.com/dotnet/corefx/pull/35003. As I mentioned before we have the option to disable the failing tests in https://github.com/dotnet/coreclr/blob/master/tests/CoreFX/CoreFX.issues.json if you don't want to wait.

**Comment by sandreenko** [comment]
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_minopts Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstress2 Build and Test

**Pull request closed without merging**
