### PR TITLE
Decompose GT_IND for x86

### PR DESCRIPTION
**Pull request by sejongoh**
Issue #4170

### CODE REVIEW

**Comment by sejongoh** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build

**Comment by sejongoh** [comment]
@BruceForstall @adiaaida PTAL

**Comment by sejongoh** [comment]
There are two failures that look related to #6219. I will check them once the fix is checked in.

**Comment by BruceForstall** [comment]
cc @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
LGTM

**Comment by adiaaida** [comment]
LGTM, I just checked in, so you should rerun your x86 tests.

**Comment by sejongoh** [comment]
@dotnet-bot test Windows_NT x86 ryujit Checked Build and Test

**Pull request merged**
