### PR TITLE
Implement AVX SetHighLow

### PR DESCRIPTION
**Pull request by fiigii**
I missed `Avx.SetHighLow` in https://github.com/dotnet/coreclr/pull/17030 ...

@CarolEidt @tannergooding PTAL

### CODE REVIEW

**Comment by fiigii** [comment]
test Windows_NT x86 Checked gcstress0xc_jitstress1
test Windows_NT x86 Checked gcstress0xc_jitstress2

**Comment by fiigii** [comment]
@CarolEidt can we merge this PR for 2.1 if it looks good to you?

**Comment by CarolEidt** [comment]
I would prefer not to merge this for 2.1. We are in the final stages of wrapping up as many bugs as possible for 2.1, and I'd prefer not to take the risk of new functionality & tests.

**Comment by fiigii** [comment]
But we have exposed this API in the corefx package.. sorry my bad.

**Comment by fiigii** [comment]
There was an oversight that `Avx.SetHighLow` was missed when I submitted PR https://github.com/dotnet/coreclr/pull/17030. I know that tomorrow is the ZBB date, and we have decided to stop enabling new intrinsic in the runtime. 
However, the API of `Avx.SetHighLow` has been exposed in the CoreFX package. So, **I suggest merging this PR for 2.1 to avoid propagating this mistake to CoreFX workflow**. Meanwhile, this is just a simple "NoCodegen" helper-intrinsic, which will be converted to `Avx.InsertVector128` in the importer, so I believe it won't has any codegen bug to disturb the ZBB plan.

@CarolEidt @AndyAyersMS @tannergooding @eerhardt Do you agree?

**Comment by tannergooding** [comment]
I think we will need to do one of:
* Take this PR
* Take a PR removing the API from CoreFX
* Do nothing and tell people using the preview to not use `SetHighLow`

**Comment by 4creators** [comment]
IMO the best option currently is:

- Take a PR removing the API from CoreFX

as it explictly avoids any risks.

**Comment by CarolEidt** [comment]
Another possible option is to remove the tests from this PR and merge it. It *may* be better to have u functionality w/o tests than to risk adding further noise to existing test challenges.

Note that taking a PR to remove the API from CoreFX definitely does *not* avoid any risks. It's almost as easy to break things when removing something as when adding.

**Comment by fiigii** [comment]
> Another possible option is to remove the tests from this PR and merge it.

Agree, will do.

**Comment by fiigii** [comment]
Removed the tests.

**Comment by 4creators** [comment]
> taking a PR to remove the API from CoreFX definitely does not avoid any risks

I do not agree as API is not used anywhere and in CoreFX we have only facade to S.P.C implementation.

However, I am equally OK with adding implementation of `Avx.SetHighLow`

**Comment by fiigii** [comment]
@CarolEidt Can we merge this PR?

**Pull request merged**
