### PR TITLE
Removing ref T Span.GetItem and updating Indexer to return ref

### PR DESCRIPTION
**Pull request by ahsonkhan**
Related PR for slow span: https://github.com/dotnet/corefx/pull/16460

Fixes this issue: https://github.com/dotnet/corefx/issues/13681

### CODE REVIEW

**Comment by jkotas** [comment]
Looks like you need to temporarily disable or do something about the Span tests. The CI is failing with:

```
Unhandled Exception: System.MissingMethodException: Method not found: 'Void System.Span`1.set_Item(Int32, !0)'.
```

**Comment by ahsonkhan** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test
@dotnet-bot test OSX x64 Checked Build and Test

**Comment by ahsonkhan** [comment]
> Looks like you need to temporarily disable or do something about the Span tests. The CI is failing with:

```
Unhandled Exception: System.MissingMethodException: Method not found: 'Void System.Span`1.set_Item(Int32, !0)'.
```

Where do you see this exception? Is it from tests in CoreMangLib\system\span\BasicSpanTest.cs?

**Comment by jkotas** [comment]
It is coming from the SpanBench. Look at the log file https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_osx_tst_prtest/2814/consoleFull#2096352037c7af6a29-b465-404a-b249-90a3911e4354

```
02:25:25 FAILED   - JIT/Performance/CodeQuality/Span/SpanBench/SpanBench.sh
02:25:25                BEGIN EXECUTION
02:25:25                /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/checked_osx_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun SpanBench.exe
02:25:25                
02:25:25                Unhandled Exception: System.MissingMethodException: Method not found: 'Void System.Span`1.set_Item(Int32, !0)'.
02:25:25                   at Tests.TestFillAllSpan(Span`1 span)
02:25:25                   at Tests.FillAllSpanBase()
02:25:25                   at Tests.Bench(Action f)
02:25:25                   at Tests.Main(String[] args)
02:25:25                ./SpanBench.sh: line 132:  5856 Abort trap: 6           (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" SpanBench.exe $CLRTestExecutionArguments
02:25:25                Expected: 100
02:25:25                Actual: 134
02:25:25                END EXECUTION - FAILED
```

**Comment by jkotas** [comment]
Wait for the current CoreCLR drop to stabilize in corefx before pushing this through (see https://github.com/dotnet/corefx/pull/16454)

**Comment by ahsonkhan** [comment]
@dotnet-bot test

**Comment by ahsonkhan** [comment]
@dotnet-bot test this

**Comment by ahsonkhan** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Comment by ahsonkhan** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by ahsonkhan** [comment]
@jkotas, can this be merged now?

**Pull request merged**
