### PR TITLE
Update license header in most .il files.

### PR DESCRIPTION
**Pull request by RussKeldorph**

### CODE REVIEW

**Comment by RussKeldorph** [comment]
Legacy_backend failure looks like infrastructure http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x86_lb_checked_windows_nt_prtest/126/.  @mmitche FYI.

@dotnet-bot Windows_NT x86 legacy_backend Checked Build and Test

**Comment by RussKeldorph** [comment]
Oops

@dotnet-bot test Windows_NT x86 legacy_backend Checked Build and Test

**Comment by RussKeldorph** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Comment by jkotas** [comment]
LGTM

**Pull request merged**
