### PR TITLE
Add a way to get a span from a memory stream

### PR DESCRIPTION
**Pull request by RUSshy**

### CODE REVIEW

**Comment by GrabYourPitchforks** [comment]
Is the existing `MemoryStream.TryGetBuffer` method insufficient?

**Comment by AaronRobinsonMSFT** [comment]
@RUSshy Has this API gone through review? I believe this will propagate to the public API surface and any new APIs must be reviewed.

**Comment by RUSshy** [comment]
@GrabYourPitchforks Span is more efficient no? or it is the same?

@AaronRobinsonMSFT I didn't thought about this sorry, i'll do it properly

**Comment by GrabYourPitchforks** [comment]
`TryGetBuffer` returns an `ArraySegment<byte>`, from which the caller can extract the original `byte[]` or turn it into a `Span<byte>`. This proposed method seems to be redundant with the existing method.

**Pull request closed without merging**
