### PR TITLE
Fix for duplicate call to Set when we run out of budget

### PR DESCRIPTION
**Pull request by briansull**

### CODE REVIEW

**Comment by briansull** [comment]
PTAL @AndyAyersMS

**Comment by briansull** [comment]
I notice that; so I re-ran the JIT formatter and that it what it produced.

I will double check.

**Comment by AndyAyersMS** [comment]
Did you mean to merge this? There are a lot of CI issues including a formatter failure.

**Comment by briansull** [comment]
I did run:

jit-format -a x64 -b Checked -o Windows_NT -c D:\fxkit\coreclr --verbose --fix --projects dll

on the source

**Pull request merged**
