### PR TITLE
Guard Windows code under PLATFORM_WINDOWS

### PR DESCRIPTION
**Pull request by marek-safar**

### CODE REVIEW

**Comment by stephentoub** [comment]
Why this one in particular?  I see all of these in corelib using PLATFORM_UNIX:
```
  D:\repos\coreclr\src\System.Private.CoreLib\shared\System\String.cs(218):#if PLATFORM_UNIX
  D:\repos\coreclr\src\System.Private.CoreLib\src\System\Text\StringBuilder.CoreCLR.cs(84):#if PLATFORM_UNIX
  D:\repos\coreclr\src\System.Private.CoreLib\src\System\Threading\EventWaitHandle.cs(50):#if PLATFORM_UNIX
  D:\repos\coreclr\src\System.Private.CoreLib\src\System\Threading\EventWaitHandle.cs(98):#if PLATFORM_UNIX
  D:\repos\coreclr\src\System.Private.CoreLib\src\System\Threading\EventWaitHandle.cs(174):#if PLATFORM_UNIX
  D:\repos\coreclr\src\System.Private.CoreLib\src\System\Threading\Mutex.cs(22):#if PLATFORM_UNIX
  D:\repos\coreclr\src\System.Private.CoreLib\src\System\Threading\Mutex.cs(29):#if !PLATFORM_UNIX
  D:\repos\coreclr\src\System.Private.CoreLib\src\System\Threading\Mutex.cs(37):#if !PLATFORM_UNIX
  D:\repos\coreclr\src\System.Private.CoreLib\src\System\Threading\Mutex.cs(90):#if !PLATFORM_UNIX
  D:\repos\coreclr\src\System.Private.CoreLib\src\System\Threading\Mutex.cs(102):#if !PLATFORM_UNIX
  D:\repos\coreclr\src\System.Private.CoreLib\src\System\Threading\Mutex.cs(114):#if PLATFORM_UNIX
  D:\repos\coreclr\src\System.Private.CoreLib\src\System\Threading\Mutex.cs(140):#if !PLATFORM_UNIX
  D:\repos\coreclr\src\System.Private.CoreLib\src\System\Threading\Mutex.cs(155):#if PLATFORM_UNIX
  D:\repos\coreclr\src\System.Private.CoreLib\src\System\Threading\Semaphore.cs(93):#if PLATFORM_UNIX
  D:\repos\coreclr\src\System.Private.CoreLib\src\System\Threading\Semaphore.cs(131):#if PLATFORM_UNIX
```
Is it because it's the only one in `shared`?

**Comment by marek-safar** [comment]
Yes, we use this code via CoreFX so only `/shared` applies

**Comment by stephentoub** [comment]
@jkotas, any reason not to convert all of the `PLATFORM_UNIX` in corelib in this manner?

**Comment by jkotas** [comment]
I would be fine with me. Most of the current ones should go away anyway - e.g. #18320 is removing a bunch.

**Comment by marek-safar** [comment]
What do I need to do to get it mirrored to corefx?

**Comment by stephentoub** [comment]
@anipik, looks like this got missed by the mirror?

**Comment by Anipik** [comment]
@stephentoub i am on it

**Comment by stephentoub** [comment]
Thanks, @Anipik.

**Pull request merged**
