### PR TITLE
Adding CoreCLR Perf support for Jenkins

### PR DESCRIPTION
**Pull request by DrewScoggins**
This contains several commits covering work I and @john-soklaski did to enable perflab and jit performance tests on Jenkins.

### CODE REVIEW

**Comment by DrewScoggins** [comment]
cc: @brianrob

**Comment by brianrob** [comment]
@DrewScoggins, looks like the CI jobs are failing because the test build is complaining about the performance project.json.

**Comment by DrewScoggins** [comment]
You might need to refresh the page.  On mine I am seeing all check marks except ARM Emulator stuff and those seems busted.  Also OSX and Ubuntu have not finished.

**Comment by DrewScoggins** [comment]
Let me be clearer.  I saw that problem as well and fixed it and re-ran the tests.

**Comment by brianrob** [comment]
Yes, you're right.  Thanks.

**Comment by russellhadley** [comment]
@DrewScoggins I'm assuming this enabled the PR check in runs, but is there some documentation that can some with this about submitting jobs?  I know there are a lot of people chomping at the bit to get at this.

**Comment by brianrob** [comment]
LGTM modulo the failing CI legs.  Can you look into those please?

**Comment by DrewScoggins** [comment]
This is the error in both runs:
Run condition [Current build status] enabling prebuild for step [[Archive the artifacts]]
16:17:08 Copied 147 artifacts from "dotnet_coreclr » master » debug_windows_nt_bld" build number 401
16:17:08 ERROR: Unable to find project for artifact copy: dotnet_corefx/master/linuxarmemulator_cross_debug
16:17:08 This may be due to incorrect project name or permission settings; see help for project name in job configuration.

It doesn't seem related to my changes as we never even start doing anything, but I don't know exactly.

**Comment by DrewScoggins** [comment]
I manually retired those tests and they seem to be running now.  If they go green I am going to go ahead and merge this.

**Comment by brianrob** [comment]
@DrewScoggins, looks like they passed.  LGTM.

**Pull request merged**
