### PR TITLE
add a switch test

### PR DESCRIPTION
**Pull request by kyulee1**
add a switch test in JIT.

### CODE REVIEW

**Comment by libengu** [comment]
The test case should return correct pass/fail code.

**Comment by libengu** [comment]
My wrong observation. You already did that.

**Comment by libengu** [comment]
Should it be "i <= 4"

**Comment by kyulee1** [comment]
@libengu Thx for catching this. I updated the test and tested locally without error.

**Comment by pgavlin** [comment]
@kyulee1 Please squash your commits together and expand the comment a bit before merging this.

**Comment by kyulee1** [comment]
@pgavlin somehow the squashed one failed probably because I did during the previous run.
What should I do to let this in?

**Comment by pgavlin** [comment]
@mmitche is there any way to re-run tests?

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@pgavlin PS I haven't seen that error before

**Comment by pgavlin** [comment]
@kyulee1 it doesn't look like the recent failures are due to your change, so this should be OK as far as the code goes. Would you mind rewording your commit message to be a bit more descriptive (and remove the "fix test error" bit)? You can do so by running "git commit --amend" and then pushing the result.

**Comment by kyulee1** [comment]
@mmitche What's wrong with this build? Can I have access to merge? Then how?

**Comment by mmitche** [comment]
The path to the pal tests was wrong because of a change to the build layout yesterday.  You're good to go.

**Pull request merged**
