### PR TITLE
Fix code generation for array length check in legacy JIT

### PR DESCRIPTION
**Pull request by hseok-oh**
check array index is in register and reload it if spilled

related issue: #9442

### CODE REVIEW

**Comment by hseok-oh** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by hseok-oh** [comment]
@dotnet/jit-contrib PTAL

**Comment by pgavlin** [comment]
LGTM.

@BruceForstall, would you mind taking a quick look?

**Comment by BruceForstall** [comment]
LGTM

btw, I saw this assert in internal testing but hadn't had time to investigate. Thanks for fixing this!

**Pull request merged**
