### PR TITLE
[Arm64/Unix] Correct ControlPC when unwinding

### LINKED ISSUE #9585: [Arm64/Unix] Unwinding to call site produces incorrect ControlPC
The result of to fthe discussion of Fix exception catch clause off by one error (#9515) was that the CLR-ABI documentation was correct and a EH region should not end in a BL, but should be padded with a breakpoint.

#9515 is an incorrect workaround for a symptom of the underlying problem. 

This issue will track progress until the root issue is resolved

@janvorli 
@BruceForstall

### PR DESCRIPTION
**Pull request by sdmaclea**
Fixes #9585

@janvorli @BruceForstall @parjong

### CODE REVIEW

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Checked

**Comment by BruceForstall** [comment]
@jashook there are a lot of failures in arm64 like this:
```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'test2': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```
Is this an infra issue?

**Comment by BruceForstall** [comment]
@jashook @briansull I would have thought we would have hit this bug on Windows arm64. Have we done gc stress or unwinding stress testing on arm64?

**Comment by janvorli** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked Build and Test  please

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Checked

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Checked

**Pull request merged**
