### PR TITLE
Update Nuget package versions to be 1.0.5 for servicing.

### PR DESCRIPTION
**Pull request by gkhanna79**
@weshaggard @ericstj PTAL

CC @leecow @wtgodbe @dagood

### CODE REVIEW

**Comment by dagood** [comment]
Not marking them as stable means they'll end up as `1.0.5-servicing-*`, right? I believe that's what we want, but want to make sure.

**Comment by gkhanna79** [comment]
Correct - that is what we want for now until we have the next release and attempt to stablize them.

**Comment by gkhanna79** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by gkhanna79** [comment]
Fixes https://github.com/dotnet/coreclr/issues/7321

**Comment by gkhanna79** [comment]
@weshaggard PTAL

**Comment by weshaggard** [comment]
LGTM. 

If the goal is for these to all share the same version, can I suggest that we put it in common props file and use that property in each of these pkgproj's? That will make future updates easier and less error prone.

**Comment by gkhanna79** [comment]
Same version is by default right now though components could choose not to have it. Either way, I will make that change in master and not here.

**Pull request merged**
