### PR TITLE
Add TypeForwardedFrom to DayOfWeek for serialization

### PR DESCRIPTION
**Pull request by safern**
Contributes to: https://github.com/dotnet/corefx/issues/31477

I will add test data in a follow up PR in corefx.

cc: @ViktorHofer

### CODE REVIEW

**Comment by jkotas** [comment]
Do you have an example where `DayOfWeek` is used in WinForms resources? I can understand the Drawing related types, but this one feels pretty random.

**Comment by safern** [comment]
> Do you have an example where DayOfWeek is used in WinForms resources?

I don't have an example and not sure where @danmosemsft got that data from -- I was just following the issue. I can investigate and figure out if it is used and needed. 

@Tanya-Solyanik might be able to respond better than me.

**Comment by ericstj** [comment]
@ViktorHofer can correct me if I'm wrong, but I think we never need typeforwardedfrom to represent types that are in the core assembly on both sides.

**Comment by safern** [comment]
Closing as this is not needed since the type in NETFX lives in mscorlib.

**Pull request closed without merging**
