### PR TITLE
Make sure RuntimeEventSource is passed to EventListener.OnEventSourceCreated

### PR DESCRIPTION
**Pull request by brianrob**
```RuntimeEventSource``` is special because it doesn't actually emit any events.  Instead, its metadata is used to properly deserialize events that come from the runtime.  Because of this, ```RuntimeEventSource``` does not ever get created on its own - it is only created when needed to dispatch an event.  This can only occur after an ```EventListener``` subscribes to the ```EventSource```.

Thus, we must explicitly initialize ```RuntimeEventSource``` so that it gets passed to ```EventListener.OnEventSourceCreated```.

I have also updated ```RuntimeEventSourceTest``` to no longer use reflection to load ```RuntimeEventSource``` to better match what users should expect to do.

### CODE REVIEW

**Comment by brianrob** [comment]
The CI failures require a change in the CoreFX tests - https://github.com/dotnet/corefx/pull/31691.

**Comment by brianrob** [comment]
Thanks much @a-and.

**Comment by brianrob** [comment]
@dotnet-bot test this please

**Comment by brianrob** [comment]
The Ubuntu leg is failing because the CoreFX tests that execute on the Linux runs aren't built off of the same SHA as the WIndows binaries.  I've sent e-mail offline to @A-And to follow-up on this.

**Comment by A-And** [comment]
@dotnet-bot test Ubuntu x64 Checked CoreFX Tests please

**Comment by A-And** [comment]
@dotnet-bot test Ubuntu x64 Checked CoreFX Tests please

**Comment by brianrob** [comment]
@dotnet-bot test Ubuntu x64 Checked CoreFX Tests please

**Comment by brianrob** [comment]
The arm failure is a real failure which appears to be caused by changing when class constructors are called.  The issue is that ```EventListener.Validate``` is called when we're in the middle of adding a new ```EventListener``` to the system.  This happens when ```EventListener.OnEventSourceCreated``` does something that causes a new ```EventSource``` to be created.  The solution is to disable validation during these time periods where the data structure is inconsistent.  ```EventListener.Validate``` will ultimately be called after all of the new ```EventListener``` and ```EventSource``` objects are added, and will validate the entire system in one pass.

For reference, this is the stack that exposes the issue (see annotations to the right of the stack, starting with arrows:

```
               /ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun runtimeeventsource.exe
               Assertion Failed
               Listener is not on all eventSources.
               
                  at System.Diagnostics.Tracing.EventListener.Validate()
                  at System.Diagnostics.Tracing.EventListener.AddEventSource(EventSource newEventSource)
                  at System.Diagnostics.Tracing.EventSource.Initialize(Guid eventSourceGuid, String eventSourceName, String[] traits)
                  at System.Buffers.ArrayPoolEventSource..ctor()
                  at System.Buffers.ArrayPoolEventSource..cctor()  <---- It happens again here when creating yet another EventSource!
                  at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Rent(Int32 minimumLength)
                  at System.Text.ValueUtf8Converter.ConvertAndTerminateString(ReadOnlySpan`1 value)
                  at Interop.Sys.Stat(ReadOnlySpan`1 path, FileStatus& output)
                  at System.IO.FileSystem.FileExists(ReadOnlySpan`1 fullPath, Int32 fileType, ErrorInfo& errorInfo)
                  at System.IO.FileSystem.FileExists(ReadOnlySpan`1 fullPath)
                  at System.IO.File.Exists(String path)
                  at System.Diagnostics.StackTraceSymbols.TryOpenFile(String path)
                  at System.Diagnostics.StackTraceSymbols.TryGetPEReader(String assemblyPath, IntPtr loadedPeAddress, Int32 loadedPeSize)
                  at System.Diagnostics.StackTraceSymbols.TryOpenReaderFromAssemblyFile(String assemblyPath, IntPtr loadedPeAddress, Int32 loadedPeSize)
                  at System.Diagnostics.StackTraceSymbols.TryGetReader(String assemblyPath, IntPtr loadedPeAddress, Int32 loadedPeSize, IntPtr inMemoryPdbAddress, Int32 inMemoryPdbSize)
                  at System.Diagnostics.StackTraceSymbols.GetSourceLineInfo(String assemblyPath, IntPtr loadedPeAddress, Int32 loadedPeSize, IntPtr inMemoryPdbAddress, Int32 inMemoryPdbSize, Int32 methodToken, Int32 ilOffset, String& sourceFile, Int32& sourceLine, Int32& sourceColumn)
                  at System.Diagnostics.StackFrameHelper.InitializeSourceInfo(Int32 iSkip, Boolean fNeedFileInfo, Exception exception)
                  at System.Diagnostics.StackTrace.CaptureStackTrace(Int32 iSkip, Boolean fNeedFileInfo, Thread targetThread, Exception e)
                  at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
                  at System.Diagnostics.Tracing.EventListener.Validate()
                  at System.Diagnostics.Tracing.EventListener.AddEventSource(EventSource newEventSource) <---- FrameworkEventSource must now be added to all EventListeners, but remember that the original EventListener hasn't been added to all EventSources, and so calling Validate here is invalid (thus the assert).
                  at System.Diagnostics.Tracing.EventSource.Initialize(Guid eventSourceGuid, String eventSourceName, String[] traits)
                  at System.Diagnostics.Tracing.FrameworkEventSource..ctor()
                  at System.Diagnostics.Tracing.FrameworkEventSource..cctor()
                  at System.Threading.ThreadPoolWorkQueue..ctor()
                  at System.Threading.ThreadPoolGlobals..cctor()
                  at System.Threading.ThreadPool.TryPopCustomWorkItem(IThreadPoolWorkItem workItem)
                  at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(Task task, Boolean taskWasPreviouslyQueued)
                  at System.Threading.Tasks.TaskScheduler.TryRunInline(Task task, Boolean taskWasPreviouslyQueued)
                  at System.Threading.Tasks.Task.WrappedTryRunInline()
                  at System.Threading.Tasks.Task.InternalWaitCore(Int32 millisecondsTimeout, CancellationToken cancellationToken)
                  at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
                  at System.Threading.Tasks.Task.Wait()
                  at System.Diagnostics.Tracing.EventPipeEventDispatcher.StopDispatchTask()
                  at System.Diagnostics.Tracing.EventPipeEventDispatcher.CommitDispatchConfiguration()
                  at System.Diagnostics.Tracing.EventPipeEventDispatcher.SendCommand(EventListener eventListener, EventCommand command, Boolean enable, EventLevel level, EventKeywords matchAnyKeywords)
                  at System.Diagnostics.Tracing.EventListener.EnableEvents(EventSource eventSource, EventLevel level, EventKeywords matchAnyKeyword, IDictionary`2 arguments)
                  at System.Diagnostics.Tracing.EventListener.EnableEvents(EventSource eventSource, EventLevel level, EventKeywords matchAnyKeyword)
                  at Tracing.Tests.SimpleEventListener.OnEventSourceCreated(EventSource eventSource)
                  at System.Diagnostics.Tracing.EventSource.AddListener(EventListener listener)
                  at System.Diagnostics.Tracing.EventListener.<>c.<.ctor>b__10_0(Object obj, EventSourceCreatedEventArgs args)
                  at System.Diagnostics.Tracing.EventListener.CallBackForExistingEventSources(Boolean addToListenersList, EventHandler`1 callback)    <---- EventListener is being added to all existing EventSources.
                  at System.Diagnostics.Tracing.EventListener..ctor()
                  at Tracing.Tests.SimpleEventListener..ctor(String name)
                  at Tracing.Tests.RuntimeEventSourceTest.Main(String[] args)
```

**Pull request merged**
