### PR TITLE
Fix conversion warning

### PR DESCRIPTION
**Pull request by franksinankaya**
@am11 @jkotas @janvorli

### CODE REVIEW

**Comment by janvorli** [comment]
@franksinankaya please do not restart the coreclr-ci, there is some strange error I want to consult with people that may know what's wrong.
@echesakovMSFT, @jashook, @RussKeldorph - the coreclr-ci Linux arm64 leg has failed with a strange error:
`/home/helixbot_azpcontainer/.nuget/packages/microsoft.dotnet.helix.sdk/2.0.0-beta.19179.2/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(67,5): error : This task can only be used on completed jobs. There are 9 of 60 unfinished work items. [/__w/1/s/tests/helixpublishwitharcade.proj]`
Is it something that one of you can look into or does it rather look like an infra issue?

**Comment by echesakovMSFT** [comment]
@janvorli Linux arm64 Helix queue machines are now broken (https://github.com/dotnet/core-eng/issues/5744)

**Comment by franksinankaya** [comment]
@dotnet-bot retest coreclr-ci (Test pri0 Linux arm64 checked)
@dotnet-bot retest coreclr-ci

**Comment by franksinankaya** [comment]
ping for merge

**Pull request merged**
