### PR TITLE
Heap allocation fix

### PR DESCRIPTION
**Pull request by kouvel**
The first two commits are from Aditya, see https://github.com/dotnet/coreclr/pull/1572. I just added the third commit to fix the test failure. I was not able to push the change into his fork, so creating a new PR.

### CODE REVIEW

**Comment by kouvel** [comment]
@sergiy-k @jkotas @gregg-miskelly, please take a look at the third commit.

**Comment by sergiy-k** [comment]
LGTM

**Comment by gregg-miskelly** [comment]
:+1:

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Pull request merged**
