### PR TITLE
[X86/Linux] Fix fail to SkipCrossgen when enabled Interpreter issue

### PR DESCRIPTION
**Pull request by xiangzhai**
Hi,

PR: https://github.com/dotnet/coreclr/issues/24627

How to prove that skipcrossgen works:

```
diff --git a/src/inc/switches.h b/src/inc/switches.h
index 60034602c3..19833330ac 100644
--- a/src/inc/switches.h
+++ b/src/inc/switches.h
@@ -193,6 +193,10 @@
 #define FEATURE_STACK_SAMPLING
 #endif // defined (ALLOW_SXS_JIT)
 
+#ifdef FEATURE_INTERPRETER
+#pragma message("just enable FEATURE_INTERPRETER but disable CROSSGEN_COMPILE for hacking Interpreter")
+#endif
+
 #endif // !defined(CROSSGEN_COMPILE)
 
 #if defined(FEATURE_INTERPRETER) && defined(CROSSGEN_COMPILE)
```

Then run `./build.sh cmakeargs "-DFEATURE_INTERPRETER=1" ignorewarnings skipcrossgen`

```
[ 74%] Building CXX object src/utilcode/dyncrt/CMakeFiles/utilcode.dir/__/clrhost_nodependencies.cpp.o
In file included from /home/loongson/zhaixiang/coreclr-mips64/src/strongname/api/strongname.cpp:11:
In file included from /home/loongson/zhaixiang/coreclr-mips64/src/strongname/api/common.h:76:
In file included from /home/loongson/zhaixiang/coreclr-mips64/src/inc/stdmacros.h:22:
In file included from /home/loongson/zhaixiang/coreclr-mips64/src/inc/contract.h:254:
In file included from /home/loongson/zhaixiang/coreclr-mips64/src/inc/check.h:17:
In file included from /home/loongson/zhaixiang/coreclr-mips64/src/inc/daccess.h:531:
/home/loongson/zhaixiang/coreclr-mips64/src/inc/switches.h:197:9: warning: just enable FEATURE_INTERPRETER but disable
      CROSSGEN_COMPILE for hacking Interpreter [-W#pragma-messages]
#pragma message("just enable FEATURE_INTERPRETER but disable CROSSGEN_COMPILE for hacking Interpreter")
        ^
```

So skipcrossgen works!

Please review it.

Thanks,
Leslie Zhai

### CODE REVIEW

**Comment by xiangzhai** [comment]
Hi @jkoritzinsky 

Thanks for your review!

> Can you change the if() conditions to wrap the add_subdirectory calls that include these CMake files instead of wrapping the whole files themselves?

Like this?

```
diff --git a/src/binder/CMakeLists.txt b/src/binder/CMakeLists.txt
index 84b35b9cbc..445955be70 100644
--- a/src/binder/CMakeLists.txt
+++ b/src/binder/CMakeLists.txt
@@ -42,4 +42,6 @@ if(CLR_CMAKE_PLATFORM_UNIX)
 endif(CLR_CMAKE_PLATFORM_UNIX)
 
 add_subdirectory(v3binder)
-add_subdirectory(v3binder_crossgen)
+if(NOT DEFINED CLR_SKIP_BUILD_CROSSGEN)
+  add_subdirectory(v3binder_crossgen)
+endif()
```

Thanks,
Leslie Zhai

**Comment by jkoritzinsky** [comment]
Yep! That’s exactly what I was thinking!

**Comment by xiangzhai** [comment]
Hi @jkoritzinsky 

Please review the [V2](https://github.com/dotnet/coreclr/pull/24653/commits/ae2e0031ec0c0fcd2346a69abdeefc7b1eef091b) again.

Thanks,
Leslie Zhai

**Comment by xiangzhai** [comment]
Interpreter is able to work at release/2.1 branch now https://github.com/dotnet/coreclr/issues/24654#issuecomment-493729356

Thanks @mattwarren great blog https://github.com/dotnet/coreclr/issues/17294#issuecomment-377259627

**Comment by xiangzhai** [comment]
> The change I had in mind to fix the problem you have hit was much simpler. Just a single line here:
> 
> [jkotas@0b00027](https://github.com/jkotas/coreclr/commit/0b00027c6e90f5edd25f1acd5ea2ca00139ca282)
> 
> Could you please give it a try whether it fixes the problem?

Could you provide the build option? just like:

```
./build.sh cmakeargs "-DFEATURE_INTERPRETER=1" ignorewarnings skipcrossgen
```

We desire a *workable* (not just buildable) Interpreter when porting CoreCLR to mips64el https://github.com/theaoqi/coreclr  So it must to enable `FEATURE_INTERPRETER` and *disable* `CROSSGEN_COMPILE`,  but what you did is disable `FEATURE_INTERPRETER` and enable `CROSSGEN_COMPILE`.

**Comment by jkotas** [comment]
> `./build.sh cmakeargs "-DFEATURE_INTERPRETER=1" ignorewarnings skipcrossgen`

Yes, this should be the command line. 

> what you did is just disable `FEATURE_INTERPRETER` but enable `CROSSGEN_COMPILE`

`CROSSGEN_COMPILE` is defined for building crossgen AOT tool. It is never defined for building the runtime itself.

My change undefined `FEATURE_INTERPRETER` when building the crossgen tool. It uses the same pattern as other `FEATURE_*` defines that are not meant to be defined when building the crossgen tool. 

You change disabled build of the crossgen tool completely.

**Comment by xiangzhai** [comment]
> > `./build.sh cmakeargs "-DFEATURE_INTERPRETER=1" ignorewarnings skipcrossgen`
> 
> Yes, this should be the command line.

Your patch works for release/2.1 branch :)

But failed to work for the master https://github.com/dotnet/coreclr/issues/24659
Please merge your patch to release/2.1 branch.
Thanks!

> 
> > what you did is just disable `FEATURE_INTERPRETER` but enable `CROSSGEN_COMPILE`
> 
> `CROSSGEN_COMPILE` is defined for building crossgen AOT tool. It is never defined for building the runtime itself.
> 
> My change undefined `FEATURE_INTERPRETER` when building the crossgen tool. It uses the same pattern as other `FEATURE_*` defines that are not meant to be defined when building the crossgen tool.
> 
> You change disabled build of the crossgen tool completely by overloading meaning of skipcrossgen flag.

Yes, we totally disable crossgen instead of skipping.

**Comment by jkotas** [comment]
> Please merge your patch to release/2.1 branch.

Release branches receive patches for officially supported configurations only. This problem is in a configuration that is not officially supported. It won't be merged into release/2.1 branch.

> But failed to work for the master #24659

That is different issue. Both my and your patch would hit it, correct?

**Comment by xiangzhai** [comment]
> > Please merge your patch to release/2.1 branch.
> 
> Release branches receive patches for officially supported configurations only. This problem is in a configuration that is not officially supported. It won't be merged into release/2.1 branch.

I see.

> 
> > But failed to work for the master #24659
> 
> That is different issue. Both my and your patch would hit it, correct?

Yes, both!

**Pull request closed without merging**
