### PR TITLE
Fix bytemark benchmark

### PR DESCRIPTION
**Pull request by AndyAyersMS**
I misunderstood how bytemark uses the `adjust` parameter and inadvertently
enabled self-adjustment for the xunit-perf versions of these tests. Not
surprisingly the results showed crazy run to run variations.

Update these tests to set `adjust = 1` to stop the self-adjustment.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@JosephTremoulet PTAL
cc @dotnet/jit-contrib 

@dotnet-bot test Windows_NT_x64 perf
@dotnet-bot test Windows_NT_x86 perf

**Comment by AndyAyersMS** [comment]
Looks like some of the parts are now failing. Will have to debug.
```
13:01:11    ByteMark.BenchFourier [FAIL]
13:01:11       System.IndexOutOfRangeException : Index was outside the bounds of the array.
13:01:11       Stack Trace:
13:01:11             at Fourier.DoFPUTransIteration(Double[] abase, Double[] bbase, Int32 arraysize)
13:01:11             at Fourier.Run()
13:01:11             at ByteMark.BenchFourier()
```

**Comment by AndyAyersMS** [comment]
Fixed the crash but now the thing is running way too long. Sp I also need to adjust the iterations, which is unfortunately a slow process.

**Comment by AndyAyersMS** [comment]
FWIW a part of the slowness is that there's no way I know to incrementally rebuild just one test in the test tree.

**Comment by pgavlin** [comment]
> FWIW a part of the slowness is that there's no way I know to incrementally rebuild just one test in the test tree.

You can do this by opening a VS command prompt with the correct target architecture, navigating to the directory that contains the test project, and running msbuild manually. For example:

```
[open an x64 command prompt]
> cd [enlistment_root]\tests\src\JIT\Performance\CodeQuality\Bytemark
> msbuild /p:Platform=x64 /p:Configuration=Release
```

**Comment by AndyAyersMS** [comment]
Thanks Pat! This info really should be in the docs somewhere, if it isn't already.

**Comment by AndyAyersMS** [comment]
@dotnet-bot test Windows_NT_x64 perf
@dotnet-bot test Windows_NT_x86 perf

**Comment by AndyAyersMS** [comment]
x64 perf hit the following error [(log)](https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_perflab_Windows_NT_x64_prtest/9/): Cannot delete workspace: remote file operation failed

@dotnet-bot test Windows_NT_x64 perf

**Comment by AndyAyersMS** [comment]
@dotnet-bot test Windows_NT_x64 perf
@dotnet-bot test Windows_NT_x86 perf

**Comment by AndyAyersMS** [comment]
@dotnet-bot test Windows_NT_x64 perf
@dotnet-bot test Windows_NT_x86 perf

**Comment by AndyAyersMS** [comment]
Some odd ETW error in this run [(log)](https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_perflab_Windows_NT_x64_prtest/13/) caused many (but not all) tests to fail.

@dotnet-bot test Windows_NT_x64 perf

**Comment by AndyAyersMS** [comment]
Perf job still messed up; things fail with:
```
13:58:14    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
13:58:14    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
13:58:14    at Microsoft.Xunit.Performance.EtwPerformanceMetricLogger.StartLogging(ProcessStartInfo runnerStartInfo) in D:\git\xunit-performance-master\src\xunit.performance.run\EtwPerformanceMetricLogger.cs:line 67
13:58:14    at Microsoft.Xunit.Performance.ProgramCore.RunTests(XunitPerformanceProject project) in D:\git\xunit-performance-master\src\xunit.performance.run\ProgramCore.cs:line 165
13:58:14    at Microsoft.Xunit.Performance.ProgramCore.Run(String[] args) in D:\git\xunit-performance-master\src\xunit.performance.run\ProgramCore.cs:line 56
```

**Comment by AndyAyersMS** [comment]
@DrewScoggins can you look at the last few logs and figure out what is going wrong? It looks like an issue with enabling ETW or some similar startup problem.

**Comment by DrewScoggins** [comment]
Yes, I'll take a look at this.

**Comment by DrewScoggins** [comment]
OK, it looks like this is a machine dependent issue.  We are only seeing this happen to jobs that are running on Perfsnake13 and 14.  And we are seeing this error even on runs in master, so it does not seem related to this PR.  I am going to spend some time digging into what is going on.

**Comment by AndyAyersMS** [comment]
Ok. The per-test running times are fairly good now (goal is nominally 1 sec) so I'll merge this one.

**Comment by DrewScoggins** [comment]
You can see what happened in this log file, [https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_perflab_Windows_NT_x64_prtest/8/console](https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_perflab_Windows_NT_x64_prtest/8/console).  When we were attempting to run the tests before the number of iterations was dialed in correctly we spent longer then the timeout time of a run (2 hours) and had the job forcibly killed by Jenkins.  When this happened we cannot clean up our open ETL sessions correctly and so as a result the machines that this initial PR test ran on cannot have new ETL sesssions opened.  I am going to restart the affected machines and then we should be good.

**Pull request merged**
