### PR TITLE
Import JIT tests.

### PR DESCRIPTION
**Pull request by pgavlin**
This brings over most of the tests from `JIT/Directed` that are
able to target CoreCLR.

### CODE REVIEW

**Comment by pgavlin** [comment]
@jkotas @BruceForstall PTAL

**Comment by pgavlin** [comment]
Bruce is going to be on vacation, so @CarolEidt can you take a look?

**Comment by pgavlin** [comment]
Or @AndyAyersMS.

**Comment by AndyAyersMS** [comment]
LGTM.

**Comment by CarolEidt** [comment]
LGTM.  Thanks for adding these!

**Pull request merged**
