### PR TITLE
 Revert "[Local GC] Move knowledge of overlapped I/O objects to the EE through four callbacks (#14982)"

### PR DESCRIPTION
**Pull request by swgillespie**
These two associated PRs are causing test instability in CoreFX and are blocking a Maestro update (https://github.com/dotnet/corefx/pull/25872). I'm reverting them here so that I have time to fully investigate the root cause.

I'm currently running the affected CoreFX test suites locally on this change to ensure that the issue is actually fixed by reverting these commits.

cc @ahsonkhan @jkotas @sergiy-k

### CODE REVIEW

**Comment by ahsonkhan** [comment]
@dotnet-bot test Ubuntu16.04 armlb Cross Debug Innerloop Build

**Comment by ahsonkhan** [comment]
Wow... 1 second race condition :)

image

**Comment by ahsonkhan** [comment]
**Question:** How long does it take for a new build to be kicked off, or should I manually start one?

**Comment by jkotas** [comment]
> I am assuming it is on a 2-4x a day schedule.

Yes. I do not know how to trigger one manually.

**Comment by ahsonkhan** [comment]
> Yes. I do not know how to trigger one manually.

OK. I have queued up a new build.

**Pull request merged**
