### PR TITLE
[WIP] Test PR.

### PR DESCRIPTION
**Pull request by sandreenko**

### CODE REVIEW

**Comment by mikedn** [comment]
Beware that I tried this in the past and PIN showed a small regression (0.2% if memory serves me well). I haven't tried to investigate back then why it happens, my guess is that it's due to an extra indirection needed to access `Compiler` members.

> Fix the order in which we pop defs from the stack.

I'm not sure this is worth doing in the current implementation. The proper fix is probably to change the whole thing to match `SsaBuilder` (which this code is supposed to be doing anyway) - that is, use the `SsaRenameState` approach.

> Can side-effects change? I do not see how.

I'm pretty sure I tried this too and failed :). Maybe my memory is fuzzy but it's not impossible to find that some variables have wrong side effects on them.

**Comment by sandreenko** [comment]
>> Can side-effects change? I do not see how.

> I'm pretty sure I tried this too and failed :). Maybe my memory is fuzzy but it's not impossible to find that some variables have wrong side effects on them.

I have not found any side-effects that depend on SSANum or local num in  `gtUpdateNodeSideEffects` and even if there are any we will see an assert during `void Compiler::fgDebugCheckFlags(GenTree* tree)` that we run after each phase.

> > Fix the order in which we pop defs from the stack.

> I'm not sure this is worth doing in the current implementation. The proper fix is probably to change the whole thing to match SsaBuilder (which this code is supposed to be doing anyway) - that is, use the SsaRenameState approach.

That PR is a subset of my changes that improves TP by 0.5% (by optimizing https://github.com/dotnet/coreclr/blob/6abccbb7a6bcf6049f8ba964d85b09943643abbd/src/jit/copyprop.cpp#L190 this loop) and I need that change for correctness. 

> Beware that I tried this in the past and PIN showed a small regression (0.2% if memory serves me well). I haven't tried to investigate back then why it happens, my guess is that it's due to an extra indirection needed to access Compiler members.

0.2% sounds big, but if I hide it with other improvements probably I will be ready to pay that price to have a separate phase.

**Comment by mikedn** [comment]
> I have not found any side-effects that depend on SSANum or local num in gtUpdateNodeSideEffects and even if there are any we will see an assert during void Compiler::fgDebugCheckFlags(GenTree* tree) that we run after each phase.

Well, attempting to comment out `gtUpdateNodeSideEffects` results in an assert:
```
Extra flags on parent tree [701E0AA0]: --XG-------
N005 (  4,  4) CSE #01 (use)[000409] *--XG-------              *  IND       int    <l:$2ce, c:$2cd>
N004 (  2,  2)              [000922] -------N----              \--*  ADD       byref  $201
N002 (  1,  1)              [000084] ------------                 +--*  LCL_VAR   byref  V01 arg1         u:1 $80
N003 (  1,  1)              [000921] ------------                 \--*  CNS_INT   long   8 field offset Fseq[_length] $102

Assert failure(PID 11376 [0x00002c70], Thread: 9500 [0x251c]): Assertion failed '!"Extra flags on tree"' in '<>c:<JoinInternal>b__38_0(System.Span`1[Char],System.ValueTuple`8[IntPtr,Int32,IntPtr,Int32,IntPtr,Int32,Boolean,ValueTuple`1]):this' (IL size 202)

    File: D:\Projects\coreclr\src\jit\flowgraph.cpp Line: 21545
    Image: D:\Projects\coreclr\bin\Product\Windows_NT.x64.Checked\crossgen.exe
```
Most likely due to `GTF_GLOB_REF`, that one is a bit weird when it comes to locals.

**Comment by sandreenko** [comment]
@mikedn did not you by chance look at this part? https://github.com/dotnet/coreclr/blob/96e08af2e7f246ad2efe9ebe68c4d4ca51f1b638/src/jit/copyprop.cpp#L220-L231

It looks like we are doing the whole liveness during copyProp only because of the pruning that could be postponed. I think without liveness we will get much better TP here, but I have not checked it yes.

**Comment by mikedn** [comment]
> It looks like we are doing the whole liveness during copyProp only because of the pruning that could be postponed. 

AFAIR it's a bit more complicated than that.

This particular copy propagation implementation is a bit bizarre in that it has no idea if substituting `x` with `y` is actually an improvement. It is possible that the live range of `y` has ended at some point before `x` and now by performing this substitution the live range of `y` gets extended.

Is that a bad thing? Well, it depends on what's going on with `x`. If this was the only/last use of `x` then this should be fine, its own live range disappears (or at least gets shorter), making room (in registers) for `y`'s longer range.

But if this isn't the last use of `x` and if its live range exceeds the one of `y` you may end up in a situation where not all uses of `x` can be substituted and thus its live range does not disappear. Great, now you have 2 overlapping ranges - `y`'s extended range and `x`'s existing one. This may lead to poorer register allocation.

I also suspect that the use of a hashtable to keep track of the stacks doesn't help either - the iteration order of a hashtable is usually undefined. Since the code more or less picks up the first suitable variable it finds, I'm not quite sure what prevents some sort of ping-pong between variables - replace `x` with `y` in one place and then `x` with `z` in another place.

So the liveness check is also a heuristic, since copy prop doesn't know for sure what happens to `x` it at least tries to prevent making `y` worse by not using it if it's not alive. Beyond the cost of keeping track of liveness (I'm not sure it's that big) this also is responsible for the rather infamous copy chain elimination issue that resulted in funny code like `mov eax, ebx  mov ebx, eax  mov eax, ebx`.

I've tried in the past to fix this but you can't fix a heuristic, at best you can try to improve it. No matter what I tried there were CQ regressions as well so I sort of gave up. Copy chains have been at least partially handled in LSRA and my forward substitution little experiment is also able to eliminate those. So copy prop... well, I don't know.

**Comment by sandreenko** [comment]
Thanks, @mikedn for the detailed explanation. I will still try to get 0.5% that I saw locally and then probably forget about that phase because it is too unreliable.

**Comment by mikedn** [comment]
FWIW copy prop is also a mess as far as throughput is concerned. 

It starts on the wrong foot by building the dominator tree. Wait a moment, didn't `SsaBuilder` already built it? Yes, it did but did not save it anywhere so copy prop has to do it again. I'll fix that in #27282

And since building the dominator tree twice is not enough, it also manages to traverse the entire IR 3 times. First time it calls `optCopyProp` on every node, the 2nd time it adds defs to `curSsaName` and the 3rd time it pops the defs. Both the 2nd and 3rd traversal are dubious and none exist in `SsaBuilder`, which copy prop is supposed to imitate in order to maintain the SSA form.

The use of a hashtable to maintain the SSA stacks is also problematic, especially that "pop" removes empty stacks from the table. Due to the way memory allocation works in the JIT, repeatedly adding and removing stuff from a hashtable is not a good idea because the memory allocated to removed nodes is never reused.

And there are some other minor warts, such as checking `lvAddrExposed` and `lvTracked`, even if there's no way for SSA variables to be address exposed.

**Comment by maryamariyan** [comment]
Thank you for your contribution. As announced in dotnet/coreclr#27549 this repository will be moving to dotnet/runtime on November 13. If you would like to continue working on this PR after this date, the easiest way to move the change to dotnet/runtime is:
1.	In your coreclr repository clone, create patch by running `git format-patch origin`
2.	In your runtime repository clone, apply the patch by running `git apply --directory src/coreclr <path to the patch created in step 1>`

**Comment by maryamariyan** [comment]
Thank you for your contribution. As announced in #27549 the dotnet/runtime repository will be used going forward for changes to this code base. Closing this PR as no more changes will be accepted into master for this repository. If you’d like to continue working on this change please move it to dotnet/runtime.

**Pull request closed without merging**
