### PR TITLE
[WIP] treat custom as overlapping for inlining

### PR DESCRIPTION
**Pull request by sandreenko**
This is a test PR that reverts part of #20141 that caused #21491.

### CODE REVIEW

**Comment by sandreenko** [comment]
@dotnet-bot help

**Comment by sandreenko** [comment]
@dotnet-bot test linux perf flow
@dotnet-bot test Windows_NT x64 perf

Hope Linux perf job will reproduce the issue, because my local runs can't.

**Comment by sandreenko** [comment]
Looks like `Linux Perf Test Flow` is broken, I do not see any issues about that, @jashook do you know who takes care of perf jobs now?

**Comment by sandreenko** [comment]
@dotnet-bot test linux perf flow

**Comment by sandreenko** [comment]
@adiaaida could you please remind me who takes care of perf jobs?

**Comment by adiaaida** [comment]
The failure looks like it is probably a test failure. I'm not sure who is now looking at those, and I don't have good history looking back at the non-pr jobs, as they have been failing since yesterday with an, it appears, unrelated issue. I would test the perf tests locally and see if you have the same failures.

**Comment by sandreenko** [comment]
@dotnet-bot test linux perf flow
@dotnet-bot test Windows_NT x64 perf

**Pull request closed without merging**
