### PR TITLE
Port BenchmarksGame updates to release/1.1.0

### PR DESCRIPTION
**Pull request by JosephTremoulet**
Update the release branches to be in sync with master, to simplify comparing the performance of these benchmarks across releases.

### CODE REVIEW

**Comment by jorive** [comment]
@dotnet-bot test Windows_NT x64 perf

**Comment by JosephTremoulet** [comment]
> Might as well do the other two, it makes it clearer what pattern is used.

Not sure what you're referring to... the part where I changed the base of the literals?

**Comment by AndyAyersMS** [comment]
Yes, change `task18` and `task12` to have hex literals too.

**Comment by JosephTremoulet** [comment]
Ok; updated.

**Comment by JosephTremoulet** [comment]
CI [error](https://ci.dot.net/job/dotnet_coreclr/job/release_1.1.0/job/x86_ryujit_checked_windows_nt_prtest/470/consoleFull#-2745591062d31e50d-1517-49fc-92b3-2ca637122019) is a timeout in one of the new tests.  Need to see if it's just timing out or if 1.1 has bad codegen for this test somehow...

**Comment by JosephTremoulet** [comment]
Other CI [error](https://ci.dot.net/job/dotnet_coreclr/job/release_1.1.0/job/arm_emulator_cross_debug_ubuntu_prtest/501/consoleFull#-16758747638101fac1-935e-4556-95f9-7a0e25ca0b52) is also a timeout, though this one doesn't indicate which test was long-running, just that the test run as a whole timed out.

Suspicious that there were timeouts on two legs using x86 ryujit for codegen.  When I build locally, though:
 - a release x86 build of this test takes only 162 ms to run
 - I can't seem to create a checked x86 build (which is what failed in the lab), I'm running into some sort of toolset issue and getting errors about illegal constexprs and such

Not sure what to make of this / how to proceed... I'm tempted to add the test to an exclusion list (and file an issue?), since matching it to current official BenchmarkDotNet sources is still what we want and what this change does.  @AndyAyersMS, @jorive, any opinions?

**Comment by jorive** [comment]
@JosephTremoulet What VS version do you have locally? I think VS2015 is required to build 1.1

**Comment by JosephTremoulet** [comment]
Building with VS2015 succeeded, but the x86 checked variant of the test completes in 1.2 seconds... going to retry the legs.

@dotnet-bot test Windows_NT x86 ryujit Checked Build and Test, test Linux ARM Emulator Cross Debug Build

**Comment by JosephTremoulet** [comment]
@dotnet-bot help

**Comment by JosephTremoulet** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build

**Comment by JosephTremoulet** [comment]
Linux rerun passed. Windows rerun [failed](https://ci.dot.net/job/dotnet_coreclr/job/release_1.1.0/job/x86_ryujit_checked_windows_nt_prtest/471/consoleFull#-20488866542d31e50d-1517-49fc-92b3-2ca637122019) again, this time with timeouts in both reverse-complement-6 (as before) and fasta-1... :(

**Comment by jorive** [comment]
@JosephTremoulet what are the next steps? open an issue and disable the tests?

**Comment by JosephTremoulet** [comment]
@jorive yes, I think so; I've opened issue #14191 and pushed an update with the exclusions.

**Comment by jorive** [comment]
Would the exclusion work for performance? Or would it become a bottleneck there?

**Comment by JosephTremoulet** [comment]
> Would the exclusion work for performance? Or would it become a bottleneck there?

Hard to say, I haven't been able to reproduce the problem outside of CI runs.  Is there a trigger phrase to get the CI system to run the performance tests you're concerned about to see how they fare?

**Comment by jorive** [comment]
@dotnet-bot test Windows_NT x64 perf
@dotnet-bot test Windows_NT x86 perf
@dotnet-bot test linux perf flow

**Pull request merged**
