### PR TITLE
Restore logic for when to use satellite resource lookup under AppX

### PR DESCRIPTION
**Pull request by jkotas**
Remove unused cache of Assembly flags while I was on it

### CODE REVIEW

**Comment by tarekgh** [comment]
LGTM.

**Comment by tarekgh** [comment]
@jkotas do we need to include this for v2? I am not sure of that as this is UWP issue so would be OK to have the fix in UWP6. right?

**Comment by jkotas** [comment]
I think so

**Comment by tarekgh** [comment]
https://github.com/dotnet/coreclr/pull/3888

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by danmosemsft** [comment]
@safern could this be the cause of the resourcel oad failures that just started happening in the coreclr appx runs?

**Comment by jkotas** [comment]
If you are not doing the PRI resource reprocessing for tests that happens for regular AppX apps, this will certainly break them.

You can workaround it by including the tests in `PLATFORM_RESOURCE_ROOTS`. Or if you need a quick fix, change `bool fUseSatelliteAssemblyResourceLookupUnderAppX` to be unconditionally true like what it was before this fix. I will reintroduce the bug that this change fixed though.

**Pull request merged**
