### PR TITLE
Disable stringarr_cs_ro for x86 RyuJIT

### PR DESCRIPTION
**Pull request by adiaaida**
This tests fails intermittently in the CI.

This change also fixes some indentation mismatching in the issues.targets file.

### CODE REVIEW

**Comment by adiaaida** [comment]
@jashook @RussKeldorph 
@dotnet/jit-contrib PTAL

**Comment by jashook** [comment]
lgtm

**Comment by RussKeldorph** [comment]
If it's only the "o" projects that are susceptible to this issue, then this LGTM.  Otherwise, I'd just as soon proactively disable all the  stringarr_cs_* tests.

**Comment by adiaaida** [comment]
this appears to only be an issue for the o tests. I ran the non-o tests 10,000 times and they did not fail once. I ran one of the o tests, and in less than 10000 it had failed multiple times.

**Pull request merged**
