### PR TITLE
Remove the UseLatestBehaviorWhenTFMNotSpecified compat switch

### LINKED ISSUE #5706: Remove uses of UseLatestBehaviorWhenTFMNotSpecified compatibility switch

### PR DESCRIPTION
**Pull request by AlexGhiondea**
Fixes #5706.

It should be merged after https://github.com/dotnet/coreclr/pull/5695

### CODE REVIEW

**Comment by AlexGhiondea** [comment]
This might introduce a change to asmmeta files in the internal build.

**Comment by danmosemsft** [comment]
@AlexGhiondea this is old. is it still relevant? can we merge it.

**Comment by AlexGhiondea** [comment]
Yes - I believe this is still relevant. Will take a look to see if the code change is right.

**Comment by AlexGhiondea** [comment]
@jkotas @weshaggard let me know if you have any concerns with this -- we have removed the need for this switch and this is just cleaning up some dead code. (I will take care of the internal asmmeta file after this is merged).

**Comment by jkotas** [comment]
Looks fine to me.

> I will take care of the internal asmmeta file after this is merged).

This is not necessary anymore.

**Comment by danmosemsft** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Build ("triggered" but with no log -- @mmitche ?)

**Comment by mmitche** [comment]
@danmosemsft This is because the job was removed.  Order of operations:
1) Probably got launched by default
2) gaurav or whoever changed the job definition removed the checked build
3) before this thing could run, the new generation of jobs disabled the old job.  That would remove the job from the queue (running jobs are fine and maintain the old state)
4) No way of removing statuses on GH.

**Comment by mmitche** [comment]
(as in, ignore that leg)

**Pull request merged**
