### PR TITLE
Add a switch to suppress crossgen warnings

### PR DESCRIPTION
**Pull request by fadimounir**
This switch will be used by the SDK to suppress warnings by default. The SDK will have an optional property that could be set to show warnings again.

### CODE REVIEW

**Comment by mjsabby** [comment]
@fadimounir Could you please squash and merge instead of creating a merge commit in your next commit? Thank you.

**Comment by fadimounir** [comment]
@mjsabby Interesting... That's what I thought I did. The PR only showed one commit anyways. What's there to squash before merging? I also see a single commit in the history (https://github.com/dotnet/coreclr/commits/master). Maybe i'm missing something

**Comment by jkotas** [comment]
@fadimounir There are two commits in the history for your change:

https://github.com/dotnet/coreclr/commit/a8f832b54f6e5db551de9427aea040da2bf4ca66
https://github.com/dotnet/coreclr/commit/27c76ae6df4b117ee10668b0b0b5fef43c4e0d38

There is difference between "Merge pull request" and "Squash and Merge" even on PRs with a single commit.

"Merge pull request" adds two commits to the history (one commit with the change and second commit for the merge) and makes the history non-linear.

"Squash and Merge" adds one commit to the history, keeping the linear.

Our convention is to always do "Squash and Merge" unless there is a good reason to do something else: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/contributing.md#merging-pull-requests-for-contributors-with-write-access

**Comment by fadimounir** [comment]
@jkotas Thanks for the clarification. I didn't know that even a PR with a single commit would show two commits when merging.

**Pull request merged**
