### PR TITLE
Release/2.0.0 - Make coreclr exceptions serializable and add typeforwards

### PR DESCRIPTION
**Pull request by ViktorHofer**
Related https://github.com/dotnet/corefx/issues/24424

### CODE REVIEW

**Comment by danmosemsft** [comment]
@dotnet-bot test windows_NT x64 Formatting Ubuntu x64 Formatting (unrelated issues)

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by ViktorHofer** [comment]
@mmitche the formatting legs are still failing. This PR should be merged into the release branch by EOD today. Should we just ignore the formatting errors?

**Comment by mmitche** [comment]
@ViktorHofer If those are real formatting errors, they should be fixed.

**Comment by ViktorHofer** [comment]
@dotnet/jit-contrib 

The formatting legs are failing with this error. I talked to @jkotas and it seems the error is unrelated to my changes. Jan suggested to disable the legs in the release branch.

> diff.cs(22,31): error CS8137: Cannot define a class or member that utilizes tuples because the compiler required type 'System.Runtime.CompilerServices.TupleElementNamesAttribute' cannot be found. Are you missing a reference? [/mnt/j/workspace/dotnet_coreclr/release_2.0.0/x64_ubuntu_formatting_prtest/jitutils/src/jit-diff/jit-diff.csproj]
08:56:08 diff.cs(22,31): error CS8179: Predefined type 'System.ValueTuple`2' is not defined or imported [/mnt/j/workspace/dotnet_coreclr/release_2.0.0/x64_ubuntu_formatting_prtest/jitutils/src/jit-diff/jit-diff.csproj]
08:56:08 diff.cs(53,26): error CS8179: Predefined type 'System.ValueTuple`2' is not defined or imported [/mnt/j/workspace/dotnet_coreclr/release_2.0.0/x64_ubuntu_formatting_prtest/jitutils/src/jit-diff/jit-diff.csproj]

**Comment by AndyAyersMS** [comment]
We could also merge #14785 which should fix the issues with the formatter.

**Comment by ViktorHofer** [comment]
> We could also merge #14785 which should fix the issues with the formatter. 
Need 2.0 SDK now. Not sure of the best URLs but these seem to work.

Just to make sure, this change won't introduce any issues with requiring the 2.0 SDK in the release branch?

**Comment by AndyAyersMS** [comment]
The changes are all in the formatting script, so they only affect the formatting test leg.

**Comment by ViktorHofer** [comment]
@mmitche Are the failing arm legs expected?

> ERROR: Unable to find project for artifact copy: dotnet_corefx/release_2.0.0/ubuntu14.04_arm_cross_release

**Comment by ViktorHofer** [comment]
@AndyAyersMS thanks! that solved the issue 👍

**Comment by weshaggard** [comment]
>It looks like some of the leg dependencies got removed from corefx/2.0.0.... @weshaggard Any idea what's going on?

Yes I just recently merged the dev/release/2.0.0 changes into release/2.0.0 which should have shifted the CI to match what is in master (see https://github.com/dotnet/corefx/pull/25091). I would expect that the legs coreclr depends on to still exists but just be disabled by default, unless @chcosta ported the master changes incorrectly.

**Comment by mmitche** [comment]
@weshaggard I think those were done properly, but this repo's release 2.0 doesn't match master well enough.  Some of the leg names were changed.

**Comment by ViktorHofer** [comment]
For the sake of this PR the two failing legs shouldn't be a blocker.

**Comment by weshaggard** [comment]
>@weshaggard I think those were done properly, but this repo's release 2.0 doesn't match master well enough. Some of the leg names were changed.

I'm not sure what needs to happen to fix these legs. Do we need to update some CI scripts in coreclr or corefx release branches?

**Pull request merged**
