### PR TITLE
  Build both Hostx86 and Hostx64 arm32 CrossGens on Linux

### PR DESCRIPTION
**Pull request by echesakovMSFT**
Build both Hostx86 and Hostx64 arm32 CrossGens. 
Continue to use Hostx86 CrossGen to crossgen System.Private.CoreLib.dll

### CODE REVIEW

**Comment by echesakovMSFT** [comment]
@dotnet-bot help

**Comment by echesakovMSFT** [comment]
@dotnet-bot test Ubuntu arm Cross Checked normal Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r Build and Test
@dotnet-bot test Ubuntu arm Cross Debug normal Build
@dotnet-bot test Ubuntu arm Cross Release normal Build and Test
@dotnet-bot test Ubuntu arm Cross Release r2r Build and Test

**Comment by echesakovMSFT** [comment]
@dotnet-bot test Ubuntu arm Cross Checked normal Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r Build and Test
@dotnet-bot test Ubuntu arm Cross Debug normal Build
@dotnet-bot test Ubuntu arm Cross Release normal Build and Test
@dotnet-bot test Ubuntu arm Cross Release r2r Build and Test

**Comment by echesakovMSFT** [comment]
@dotnet-bot test Ubuntu arm Cross Checked normal Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r Build and Test
@dotnet-bot test Ubuntu arm Cross Debug normal Build
@dotnet-bot test Ubuntu arm Cross Release normal Build and Test
@dotnet-bot test Ubuntu arm Cross Release r2r Build and Test

**Comment by echesakovMSFT** [comment]
@dotnet/dnceng All the "Ubuntu arm" legs failed the same way - with timeout during rm command
```
12:58:11 rm /ssd/j/workspace/dotnet_coreclr/master/arm_cross_release_ubuntu_r2r_tst_prtest/bin/tests/Linux.arm.Release/baseservices/regression/baseservices.regression.XUnitWrapper.dll
12:58:11 rm /ssd/j/workspace/dotnet_coreclr/master/arm_cross_release_ubuntu_r2r_tst_prtesBuild timed out (after 360 minutes). Marking the build as aborted.
18:48:02 Build was aborted
18:48:02 [xUnit] [INFO] - Starting to record.
```
This is happening also in master branch (e.g., see https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_forcerelocs_tst/22/console) Is this a known issue?

**Comment by MattGal** [comment]
@echesakov not a known issue to me, filed https://github.com/dotnet/core-eng/issues/4175 to investigate.  Please update that issue if you have any other useful observations.

**Comment by echesakovMSFT** [comment]
@BruceForstall PTAL
/cc @dotnet/jit-contrib

**Pull request merged**
