### PR TITLE
Improve Bmi2.MultiplyNoFlags codegen

### LINKED ISSUE #21899: Bmi2.MultiplyNoFlags issues
I have a working version of `decimal.DecCalc` which uses `MultiplyNoFlags` from #21480 in a [branch](https://github.com/pentp/coreclr/tree/decimal-mulx), but I discovered two issues.

If `MultiplyNoFlags` is called without having its result used, then it's assumed to be a no-op, even if the `low` part is used. While such use would be sub-optimal, it should still be valid.
``` C#
static unsafe ulong mulxbug(ulong a, ulong b)
{
	ulong r;
	X86.Bmi2.X64.MultiplyNoFlags(a, b, &r);
	return r;
}
```

The second problem is that performance is increased only up to 3% for some methods, while others suffer a performance penalty up to 20%! This is primarily caused by forcing the low result to be written to memory and excessive temporary register use, compounded by forced zero-init of the locals (even with no `.locals init`) which affects all code paths of the function.
``` C#
static unsafe ulong mulx(ulong a, ulong b)
{
	ulong r;
	return X86.Bmi2.X64.MultiplyNoFlags(a, b, &r) + r;
}
```
Is compiled into:
``` asm
; Assembly listing for method DecCalc:mulx(long,long):long
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
; optimized code
; rsp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 arg0         [V00,T00] (  3,  3   )    long  ->  rcx        
;  V01 arg1         [V01,T01] (  3,  3   )    long  ->  [rsp+0x18]  
;  V02 loc0         [V02    ] (  2,  2   )    long  ->  [rsp+0x00]   do-not-enreg[X] must-init addr-exposed ld-addr-op
;# V03 OutArgs      [V03    ] (  1,  1   )  lclBlk ( 0) [rsp+0x00]   "OutgoingArgSpace"
;
; Lcl frame size = 8

G_M42317_IG01:
       push     rax
       xor      rax, rax
       mov      qword ptr [rsp], rax
       mov      qword ptr [rsp+18H], rdx

G_M42317_IG02:
       lea      rax, bword ptr [rsp]
       mov      rdx, rcx
       mulx     rdx, r8, qword ptr [rsp+18H]
       mov      qword ptr [rax], r8
       mov      rax, rdx
       add      rax, qword ptr [rsp]

G_M42317_IG03:
       add      rsp, 8
       ret      

; Total bytes of code 41, prolog size 7 for method DecCalc:mulx(long,long):long
```
While ideally this should be just:
``` asm
       mulx     rax, rcx, rcx
       add      rax, rcx
       ret      
```

### PR DESCRIPTION
**Pull request by pentp**
I went with the magic load route in lowering. It works out quite well (codegen is ideal, if a local var is used for the low result). Fixes #21899.

@mikedn, @fiigii, @CarolEidt do you think this might be acceptable, as all changes are limited to BMI specific functions?

### CODE REVIEW

**Comment by fiigii** [comment]
All the MultiplyNoFlags tests failed. Could you please address them at first?

**Comment by pentp** [comment]
@dotnet-bot test Windows_NT x64 min_opt ryujit CoreCLR Perf Tests Correctness

**Comment by pentp** [comment]
@dotnet-bot test Windows_NT x86 full_opt ryujit CoreCLR Perf Tests Correctness

**Comment by pentp** [comment]
Fixed a problem with tier0, this is ready for review now.

**Comment by pentp** [comment]
@fiigii could you take a look at this?

**Comment by fiigii** [comment]
I will take a look tonight.
@mikedn @CarolEidt PTAL

**Comment by mikedn** [comment]
I'd wait for @CarolEidt's feedback before going further with this. The "magic" way wasn't exactly the favored approach.

**Comment by tannergooding** [comment]
It's likely also worth keeping in mind that there are other APIs (such as `Math.DivRem`) that would possibly benefit from whatever optimization we decide to do here (whether it is something like this as an interim solution, or something that isn't so "magic" as a more permanent solution).

**Comment by pentp** [comment]
I explored the MultiRegOp path used in 32-bit mode also, but that looked more complicated and most importantly, would not be pay-for-play as this magic load solution.

**Comment by pentp** [comment]
@CarolEidt could you take a look at this? I know this solution feels like an hack, but at least it's pretty contained and I'd like to use MULX in `decimal` math, but in it's current form it's not really usable because of the memory accesses.

**Comment by CarolEidt** [comment]
I'm still not keen on this approach, though it is cleaner than I feared.
It will take me some time to get to this, but the review would go faster if there were more detailed comments about what's being done at each stage (and they will be needed if/when this is merged in any case). So if you could add some comments that would be great. Thanks!

**Comment by maryamariyan** [comment]
Thank you for your contribution. As announced in dotnet/coreclr#27549 this repository will be moving to dotnet/runtime on November 13. If you would like to continue working on this PR after this date, the easiest way to move the change to dotnet/runtime is:
1.	In your coreclr repository clone, create patch by running `git format-patch origin`
2.	In your runtime repository clone, apply the patch by running `git apply --directory src/coreclr <path to the patch created in step 1>`

**Comment by BruceForstall** [comment]
Given the lack of activity in this PR, I'm going to close it. Feel free to re-open if work resumes. Note that the repo will move soon, so it would be best to wait until the new repo opens to create a new PR.

**Pull request closed without merging**
