### PR TITLE
[Documentation] Projects Use licenses

### PR DESCRIPTION
**Pull request by shahid-pk**
A minor correction.

### CODE REVIEW

**Comment by jkotas** [comment]
cc @richlander

**Comment by richlander** [comment]
Thanks. I can see how that's a better format. Let's simplify this further. My suggestion, including an update to the end of the paragraph that comes just before it.

See the license file at the root of project repos for the specific license, such as with the following examples:

- [CoreCLR](https://github.com/dotnet/coreclr/blob/master/LICENSE.TXT) ([MIT](https://opensource.org/licenses/MIT))
- other examples with the same format

**Comment by shahid-pk** [comment]
feed addressed.

**Comment by richlander** [comment]
Thanks.

**Pull request merged**
