### PR TITLE
Delete unused AppDomain{Setup} types/members

### PR DESCRIPTION
**Pull request by jamesqo**
There were quite a lot of entries for `AppDomain` / `AppDomainSetup` in [the list](https://gist.githubusercontent.com/jamesqo/2b848c6fec404726ac7bee1faae94324/raw/2aaa3b5eddffe3ca224d49b78421fcafec5495e6/RemovableTypesAndMembers.txt), so I removed some members from those types.

/cc @jkotas

### CODE REVIEW

**Comment by jkotas** [comment]
Error: CrossGen System.Private.CoreLib build failed

**Comment by danmosemsft** [comment]
@dotnet-bot test this (logs gone)

**Comment by jamesqo** [comment]
@jkotas @danmosemsft I have not forgotten about this PR, but I have been busy recently. Will work on this when I can get back to it.

**Comment by danmosemsft** [comment]
@dotnet-bot test this please (forgot the please!)

**Comment by jamesqo** [comment]
Test Windows_NT x86 Checked Build and Test

**Comment by jamesqo** [comment]
@jkotas CI is passing after I removed the changes to the native side. Should be safe to merge.

**Comment by jkotas** [comment]
Thanks!

**Pull request merged**
