### PR TITLE
[WIP] add test for #18988

### PR DESCRIPTION
**Pull request by sandreenko**
This PR is for test purpose only.

### CODE REVIEW

**Comment by sandreenko** [comment]
@dotnet/dnceng I think this PR hits the same issue as #19588, there are only 7 ci jobs started for this PR (The PR was opened 12 minutes ago).
Do I need to wait longer?

**Comment by sandreenko** [comment]
Looks like jobs were spawned immediately after I added the last comment.
I have checked that there were no jobs before I have clicked "comment".

**Comment by jonfortescue** [comment]
@sandreenko I've actually seen this before, too, where jobs don't seem to spawn until commenting. We'll take a look and see if we can get a better idea of what's going on.

**Comment by mikedn** [comment]
@sandreenko Erm, was there something wrong with the prototype I had in https://github.com/dotnet/coreclr/issues/16472? I asked about it and got no reply.

**Comment by mmitche** [comment]
I wonder whether this a GitHiub live-ui issue.  Did you refresh the page?

**Comment by jonfortescue** [comment]
@sandreenko In chatting with some others, this tends to be an issue with GitHub not refreshing fast enough. Leaving a comment definitely seems to be a workaround.

**Comment by mikedn** [comment]
> Does it pass test from #18988?

Not yet. The main goal was to replace the existing code, get it to pass existing tests and get 0 diffs. In particular I wanted the 0 diffs part because, as mentioned somewhere else, discrepancies between `fgAddressTaken` and `fgMorph` seem risky. With 0 diffs I'm hopeful that it's equivalent to the current implementation, because it's really difficult to tell what the current implementation does in some more exotic cases.

Fixing #18988 should be trivial - it's just a matter of checking if the size of the indir type is greater than the size of the lclvar those address you get via the value stack, if any. Right it does not check so it behaves like the existing code.

> Could you make a PR where we can discuss it?

Will do. Perhaps I should have already done so to avoid you wasting your time working on this. But I already have a bunch of opened PRs so I'm trying to be a bit more conservative with opening new ones.

**Comment by sandreenko** [comment]
@dotnet-bot help

**Comment by sandreenko** [comment]
@dotnet-bot test this please

**Pull request closed without merging**
