### PR TITLE
Updating the x86 HWIntrinsic tests to include embedded pdbs

### PR DESCRIPTION
**Pull request by tannergooding**
This updates all 379 x86 HWIntrinsic test projects to include embedded pdbs.

This results in a size increase of ~2.09MB (or ~5.64kb per project), but ensures that any crashes/etc include enough information to assist with debugging.

### CODE REVIEW

**Comment by tannergooding** [comment]
FYI. @CarolEidt, @fiigii, @eerhardt

**Comment by tannergooding** [comment]
NOTE: I went with `embedded` (rather than `full` or `portable`) because it produces no additional files and results in the smallest size increase.

Portable PDBs would have resulted in 379 new files and a ~5.98MB total increase in size.

image

**Comment by eerhardt** [comment]
This may not be the "coreclr" way, but would it make sense to create a `.props` file and set these common properties in it?

**Comment by tannergooding** [comment]
@eerhardt, I checked, we can't move it there because of `CheckProjects`. I can minimally update (`CheckProjects`) to support `DebugType=Embedded`, but updating it to support `dir.props` is much more complicated

**Comment by eerhardt** [comment]
Sounds good to me.  I assumed the answer was going to be "no", but I felt like I had to ask.

**Comment by tannergooding** [comment]
Added a second commit which updates `CheckProjects` to support `DebugType=Embedded`

**Pull request merged**
