### PR TITLE
Add alpine3.10 testing to 3.0

### PR DESCRIPTION
**Pull request by jashook**
/cc @MeiChin-Tsai @mmitche @janvorli 

/cc @dotnet/coreclr-infra

### CODE REVIEW

**Comment by jashook** [comment]
Releted to https://github.com/dotnet/coreclr/issues/26661

**Comment by MeiChin-Tsai** [comment]
Approved.

**Review by mmitche — APPROVED** [review]

**Comment by mmitche** [comment]
Can you wait on this for 3.0.2 to open?

**Comment by jashook** [comment]
@mmitche when should this be merged

**Comment by mmitche** [comment]
> @mmitche when should this be merged

In a few days when 3.0.1 is done done.

**Comment by maryamariyan** [comment]
Thank you for your contribution. As announced in dotnet/coreclr#27549 this repository will be moving to dotnet/runtime on November 13. If you would like to continue working on this PR after this date, the easiest way to move the change to dotnet/runtime is:
1.	In your coreclr repository clone, create patch by running `git format-patch origin`
2.	In your runtime repository clone, apply the patch by running `git apply --directory src/coreclr <path to the patch created in step 1>`

**Comment by maryamariyan** [comment]
Please ignore my previous comment. Since this PR is not targeting master branch, no action would be needed here. Thanks.

**Pull request merged**
