### PR TITLE
Ryu jit overview

### PR DESCRIPTION
**Pull request by CarolEidt**

### CODE REVIEW

**Comment by CarolEidt** [comment]
@cheers00 @cmckinsey - here's the updated jit overview doc

**Comment by cmckinsey** [comment]
@CarolEidt LTGM

You should also remove/change the comment referenced in issue #636 since it is referring to the wrong document path.

**Comment by cmckinsey** [comment]
@CarolEidt Btw, feel free to make the comment change in a later checkin. Just calling it out.

**Comment by richlander** [comment]
Great. Nice to see this. Haven't read the content (don't block on merge on that!).

Superficially:

- It would be nice to rename the file to ryujit-overview.md for readability.
- Please do link directly to source files, like; [src/jit/ee_il_dll.cpp](https://github.com/dotnet/coreclr/blob/master/src/jit/ee_il_dll.cpp). Preferably don't use Windows style paths if it can be avoided.
- There is a numbered header. Is that necessary? Would prefer to see those deleted.
- There are "A" anchor tags in the headers. Is that necessary? Would prefer to see those deleted.
- Please squash before merging.

**Comment by cheers00** [comment]
Thank you @CarolEidt

**Comment by CarolEidt** [comment]
@dotnet-bot please test this

**Comment by CarolEidt** [comment]
@cmckinsey I edited the path name in compiler.cpp. @richlander I renamed the doc, added direct source links and removed the numbered headers.  Barring strong objections, I plan to keep the anchor tags - this seemed to be the best way to link within docs.  In future, I believe that some of these may link to separate docs, rather than separate sections within this one, but it is likely to remain useful to have links within docs.

**Pull request merged**
