### PR TITLE
Add subfolders to Documentation folder

### PR DESCRIPTION
**Pull request by blackdwarf**
As raised in #1075 by @akoeplinger, the Documentation folder's file
list forces the user to scroll way down to see the README.md. This
PR fixes that by storing the documents in separate sub-folders one
per hierarchy of related documents. Also changed
Documentation\README.md and root README.md to take into account
the new paths.

/cc @richlander @akoeplinger @terrajobst @kangaroo

### CODE REVIEW

**Comment by akoeplinger** [comment]
LGTM, thanks for doing this work :+1:

Can we integrate the content of dotnetcore-intro.md into README.md as well? It's just a single paragraph so I don't think it warrants a separate file at the root.

**Comment by kangaroo** [comment]
LGTM

**Comment by blackdwarf** [comment]
@akoeplinger Agreed. @richlander are you ok with this suggestion?

**Comment by richlander** [comment]
Thanks for doing this @blackdwarf. Few comments.

- Including the brief intro in the readme is fine.

I'd prefer to following directories:

- installing -> install
- building -> build
- project-docs
- coding-guidelines
- botr
- decoders -> project-docs
- misc -> project-docs

Basically, I'd prefer not to use gerunds.

**Comment by richlander** [comment]
Looks like you should rebase master on your change. I merged in an update earlier tonight. Not surprisingly not compatible with a rename PR.

**Comment by blackdwarf** [comment]
OK, fixed the folder name as per @richlander suggestion, However, I cannot rename building to build, since build/ is in .gitignore. Don't want to mess with that at this point, so I suggest we just leave it as is, unless someone can educate me on the best way to do this. :)

**Comment by richlander** [comment]
@blackdwarf good point! Please ignore my aesthetics on that issue. It is not worth futzing with .gitignore to make it work.

**Pull request merged**
