### PR TITLE
Correctly handle variable argument SIMDScalar (#26421)

### LINKED ISSUE #26286: JIT/HardwareIntrinsics/X86/Sse41_Overloaded consistently asserts on my Linux box
My box is a relatively old machine with Intel Xeon  E5530  @ 2.40GHz
The test fails with
`Assert failure(PID 65156 [0x0000fe84], Thread: 65156 [0xfe84]): Assertion failed '(insCodesMI[ins] != BAD_CODE)' in 'JIT.HardwareIntrinsics.X86.SimpleUnaryOpTest__RoundCurrentDirectionScalarDouble:RunBasicScenario_UnsafeRead():this' (IL size 87)`

The `ins` is `INS_roundsd`.
Here is a relevant top portion of the stack trace:
```
* thread #1, name = 'corerun', stop reason = signal SIGTRAP
  * frame #0: 0x00007ffff0dc6209 libclrjit.so`DBG_DebugBreak at debugbreak.S:10
    frame #1: 0x00007ffff0d2afe1 libclrjit.so`::DebugBreak() at debug.cpp:405
    frame #2: 0x00007ffff0a5f662 libclrjit.so`::assertAbort(why="(insCodesMI[ins] != BAD_CODE)", file="/home/janvorli/git/coreclr2/src/jit/emitxarch.cpp", line=1345) at error.cpp:293
    frame #3: 0x00007ffff0c8b8a6 libclrjit.so`insCodeMI(ins=INS_roundsd) at emitxarch.cpp:1345
    frame #4: 0x00007ffff0c72c53 libclrjit.so`emitter::emitIns_R_I(this=0x00000000007f9fb8, ins=INS_roundsd, attr=EA_16BYTE, reg=REG_XMM0, val=4) at emitxarch.cpp:3765
    frame #5: 0x00007ffff0c785d0 libclrjit.so`emitter::emitIns_SIMD_R_R_I(this=0x00000000007f9fb8, ins=INS_roundsd, attr=EA_16BYTE, targetReg=REG_XMM0, op1Reg=REG_XMM0, ival=4) at emitxarch.cpp:5774
    frame #6: 0x00007ffff0b3f005 libclrjit.so`CodeGen::inst_RV_TT_IV(this=0x00000000007f9b48, ins=INS_roundsd, attr=EA_16BYTE, reg1=REG_XMM0, rmOp=0x00000000007fbd78, ival=4) at instr.cpp:1165
    frame #7: 0x00007ffff0cba616 libclrjit.so`CodeGen::genHWIntrinsic_R_RM_I(this=0x00000000007f9b48, node=0x00000000007fbde8, ins=INS_roundsd, ival='\x04') at hwintrinsiccodegenxarch.cpp:555
    frame #8: 0x00007ffff0cb9815 libclrjit.so`CodeGen::genHWIntrinsic(this=0x00000000007f9b48, node=0x00000000007fbde8) at hwintrinsiccodegenxarch.cpp:128
    frame #9: 0x00007ffff0c5f000 libclrjit.so`CodeGen::genCodeForTreeNode(this=0x00000000007f9b48, treeNode=0x00000000007fbde8) at codegenxarch.cpp:1818
```

### PR DESCRIPTION
**Pull request by CarolEidt**
* Correctly handle variable argument SIMDScalar

Fix #26286

### CODE REVIEW

**Comment by CarolEidt** [comment]
This fixes a SBCG bug. It was found by @janvorli  while running HW intrinsic tests on a non-AVX machine. This affects only 7 HW intrinsics, and there is a workaround. In the case of the tests, it hit an illegal instruction, though in some cases it could generate valid (i.e. not actually illegal) instructions like `ENTER`, `LEAVE`, `RET`, `INT`, `INTO` and `IRET. If it were always an illegal instruction I’m not sure this would meet the bar for 3.1, but given that it could silently do weird things for other cases, I think we should take this.

**Comment by MeiChin-Tsai** [comment]
@CarolEidt can you explain your definition of "weird thing"?

**Comment by erozenfeld** [comment]
@dotnet/jit-contrib

**Comment by wtgodbe** [comment]
@CarolEidt does this need to be included with `release/3.1-preview1`? If so, it needs to be merged by EOD today (as we start the build process tomorrow morning)

**Comment by CarolEidt** [comment]
I believe that @MeiChin-Tsai was planning to approve this, but I haven't seen her approval yet.

**Comment by CarolEidt** [comment]
I thought I had previously responded to the question about "weird thing" but apparently not. I list above the instructions that could be incorrectly generated without this fix. These instructions are intended to be used in specific contexts, e.g. an `INT` or `INTO` is used to call the interrupt procedure specified by the immediate operand (or implicit). The `ENTER` and `LEAVE` instructions modify the frame and stack pointers, and the `RET` and `IRET` instructions modify the flow of control. The precise behavior is unpredictable, as it depends on context.

**Comment by MeiChin-Tsai** [comment]
Approved for 3.1

**Pull request merged**
