### PR TITLE
ARM64: Tests update

### PR DESCRIPTION
**Pull request by kyulee1**
- Delete bad test (sql_stress4) which uses Thread.Abort which is not in
  .NET Core.
- Delete non-existing test (MarshalBoolArray)
- Update time-out for StringConcat4/StringConcat8 which usualy failed due to time-out.
- Made _opt_dbgexplicit5/_opt_relexplicit5 EXPECTED_PASS which seem to
  always pass in the recent lab runs.

### CODE REVIEW

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Release

**Comment by kyulee1** [comment]
@dotnet/arm64-contrib PTAL

**Comment by rahku** [comment]
LGTM

**Comment by kyulee1** [comment]
Two more tests are excluded. Since the prior run passed, I'm just merging it.

**Pull request merged**
