### PR TITLE
JIT: implement assembly name dissassembly filtering

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Add `COMPlus_JitDisasmAssemblies` to specify a whitelist of assemblies
whose methods will be disassembled.

Intended use is for PMI asm diffing. Since PMI runs in process, current
disassembly will dissassemble various methods in PMI itself as well
as framework methods that did not get prejitted.

With this new config option we can restrict disassembly to just the assemblies
that we're processing via PMI.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@BruceForstall PTAL
cc @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
Hmm, looks like I need to filter some of the non-disasm outputs too.

**Comment by AndyAyersMS** [comment]
@BruceForstall you ok with the update? This now suppresses dumping EH, GCinfo, etc too.

I would generalize the name of the config variable but it's hard to get it to be both succinct and fully descriptive. Open to suggestions....

**Comment by BruceForstall** [comment]
Yes, LGTM

**Pull request merged**
