### PR TITLE
Disable R2RDumpTest

### PR DESCRIPTION
**Pull request by BruceForstall**
Tracked by issue 19277

### CODE REVIEW

**Comment by acmyu** [comment]
The Windows x64 Release test fails because the xml files it's looking for hasn't been added yet. I've added the files in https://github.com/dotnet/coreclr/pull/19315 so it should work on both x64 and x86 Released and Checked. Are there other platforms it should support, such as Debug?

**Comment by BruceForstall** [comment]
Yes, it is legal to run tests on Debug, so either the required files should be there, or the test should pass if they are not there. (Jenkins probably doesn't run tests on Debug, but users do.)

In general, every test needs either run successfully on every OS/architecture/build flavor/stress mode, or needs to be disabled for the appropriate subset. I see this test is currently disabled for non-Windows platforms (in testsUnsupportedOutsideWindows.txt).

I also see this in the test:
```
COPY /Y $(CoreClrDir)tests\src\readytorun\r2rdump\files\$(BuildOS).$(BuildArch).$(BuildType)\*.xml .   
```

What about Windows arm32 or arm64? It turns out they currently use a different test list (arm\Tests.lst, arm64\Tests.lst), but that is changing soon.

How often will these all need to be updated? Is that documented?


Secondly, I am worried about one aspect of this test, namely that "copy" line above. What if you run a Checked test run, then a Debug test run in the same tree? Currently, the test will fail the second copy, because the Debug directories don't exist. But will the test pass or fail, when running against the Checked .XML files that were copied?

Can you at least delete the copied files after the test? Or maybe delete all *.xml in the directory before the copy (less preferable)?

It's not clear if our tree would support running two test flavors concurrently, but this test could definitely break in that scenario.

**Comment by acmyu** [comment]
I think it would be possible to avoid copying the xml files by passing the path of the original file to R2RDumpTest.

I'll disable the test for ARM and ARM64 and add the Debug xml files

**Comment by BruceForstall** [comment]
I'll close this PR, since the Release case was fixed with https://github.com/dotnet/coreclr/pull/19315. But the comments here still apply, especially the comments about making the Debug runs work.

**Comment by acmyu** [comment]
I've added the missing Debug files and avoided copying the expected xml files in pr: https://github.com/dotnet/coreclr/pull/19321

**Pull request closed without merging**
