### PR TITLE
Port more CoreClr and Desktop JIT Selfhost ILASM tests.

### PR DESCRIPTION
**Pull request by richardlford**
This adds 450 new ilproj files which derived from
a larger number of tests instances (because of some duplication
between CoreClr and Desktop tests).

### CODE REVIEW

**Comment by richardlford** [comment]
I will not merge this until #2312 is first merged and I'll rebase after that.
I will also need to add any needed exclusions (for coreclr or LLILC)
before merging.

@pgavlin, PTAL.

**Comment by richardlford** [comment]
Some tests were not automatically edited correctly when removing trailing comments.
I fixed those and pushed the update.

**Comment by richardlford** [comment]
@pgavlin, I've rebased this.

**Comment by richardlford** [comment]
@pgavlin, tests are all now passing (at least they were before I just squashed). I'm going to check
LLILC next and add any needed exclusions. OK to merge this (when LLILC is ready)?

**Comment by richardlford** [comment]
@AndyAyersMS, can you take a look. Not sure if Pat is available.

**Comment by AndyAyersMS** [comment]
LGTM

**Comment by richardlford** [comment]
The LLILC exclusions are not merged so I'll go ahead with this merge.

**Pull request merged**
