### PR TITLE
Initial draft for inlining plans

### PR DESCRIPTION
**Pull request by AndyAyersMS**
I am pushing these early drafts out to be transparent about the work we anticipate doing for improving inlining in both RyuJit and LLILC. Expect revisions and more details to emerge over time.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@cmckinsey PTAL.

Not sure this is the right place for these sorts of notes, but they have to go somewhere. I expect to have a lot more writeups eventually as we flesh out everything.

**Comment by cmckinsey** [comment]
@AndyAyersMS LGTM. Seems like the right place for these kinds of notes.

**Comment by jkotas** [comment]
Documentation/project-docs contains engineering system type of docs (how to run tests, how to contribute, etc.)

I would suggest creating a new directory for this type of docs (e.g. Documentation\design-docs).

**Comment by AndyAyersMS** [comment]
Created Documentation\design-docs and moved the writeups there.

**Comment by AndyAyersMS** [comment]
@lic9 take a look...

**Comment by lic9** [comment]
Thanks for sharing this :)

**Pull request merged**
