### PR TITLE
Add a trigger for gc-longrunning pipeline for "every day at 3AM"

### PR DESCRIPTION
**Pull request by VSadov**

### CODE REVIEW

**Comment by sergiy-k** [comment]
@echesakovMSFT, there are jobs scheduled at various times during the evening and night but without knowing how long each of them takes, it is hard to say how many of them actually overlap.   The corefx test job is the only one that is scheduled at 3am.

**Comment by echesakovMSFT** [comment]
> there are jobs scheduled at various times during the evening and night but without knowing how long each of them takes, it is hard to say how many of them actually overlap.   The corefx test job is the only one that is scheduled at 3am.

@sergiy-k Agree, we probably should merge this and see whether the jobs conflicts with others (if any).

**Comment by VSadov** [comment]
Considering the time it takes, this will likely to overlap with some scheduled runs. I picked 3am to have fewer chances to overlap with PRs.

**Comment by VSadov** [comment]
Thanks!!

**Pull request merged**
