### PR TITLE
Actually lock the project.lock.json

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Hopefully this clears up some test issues on ubuntu with the serialization benchmarks.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
No luck with the locked json, so added a second commit to disable the tests outside of windows until we can get this sorted.

@adityamandaleeka PTAL

**Comment by adityamandaleeka** [comment]
LGTM

**Comment by weshaggard** [comment]
Fwiw corefx have stopped committing lock files and instead removed and * versions in the project.json files. I don't know if this will help here but something to consider for the tests.

**Comment by AndyAyersMS** [comment]
See #2264 for context.

**Pull request merged**
