### PR TITLE
[ARM] Disable ARM_HAZARD_AVOIDANCE

### LINKED ISSUE #7003: [ARM/Linux] Is `ARM_HAZARD_AVOIDANCE` for Krait still effective?
While working on #7002, I found that an extra `nop.w` instructions is added sometimes for direct calls. According to the comment, it says it is a Krait processor bug. Actually I can't find more information about this on the web.

Is it still effective? If so, I was just thinking that we may not need to have this flag on by default.

/cc @dotnet/jit-contrib @hqueue

### PR DESCRIPTION
**Pull request by wateret**
Disable `ARM_HAZARD_AVOIDANCE` by default as it is a rare case.

Fix #7003

### CODE REVIEW

**Comment by wateret** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build

**Comment by jkotas** [comment]
cc @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
@briansull @jkotas If we're going to disable the Krait fix, why don't we just delete all the code completely?

**Comment by BruceForstall** [comment]
cc @gkhanna79 @rahku

**Comment by briansull** [comment]
Seems odd to change the undef/def to a 0/1 #define 
 
I'm OK with removing the code entirely as well.

@briansull @jkotas

**Comment by wateret** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build

**Comment by wateret** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build

**Comment by wateret** [comment]
@BruceForstall @briansull 
I have made the commit to remove the whole code related to krait fix.

**Comment by gkhanna79** [comment]
@JohnChen0 Can you PTAL at Zap related changes?

**Comment by JohnChen0** [comment]
Zap related changes LGTM.

**Comment by BruceForstall** [comment]
LGTM

**Pull request merged**
