### PR TITLE
Added Array tests to CodeGenBringUpTests

### PR DESCRIPTION
**Pull request by alpencolt**
Added tests from  #9679 task

### CODE REVIEW

**Comment by alpencolt** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Comment by alpencolt** [comment]
+ @Dmitri-Botcharnikov 
Part of #8496

**Comment by alpencolt** [comment]
@BruceForstall could you look take a look at this PR?
Also I little bit confused about content of `CORECLR/tests/scripts/test/` folder. Should I add tests into this list? Is there any tools to update this lists?

**Comment by BruceForstall** [comment]
cc @dotnet/jit-contrib

**Comment by alpencolt** [comment]
It generates mostly the same code even even `/o+` is used. But  I've updated `Array1` and `Array2` tests to make them more fair.

**Comment by alpencolt** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test

**Pull request merged**
