### PR TITLE
Improve LLDB probing and fix a small bug in umthunkstub.S.

### PR DESCRIPTION
**Pull request by pgavlin**
- Replace the LLDB_{INCLUDE,LIB}_DIR environment variables with
  WITH_LLDB_{INCLUDES,LIBS} variables in lldbplugin/CMakeLists.txt. These
  variables are instead picked up in gen-buildsys-clang.sh.
- Look for a typical lldb installation as well as the Ubuntu-specific
  lldb-3.5 installationin the usual location as well as the Ubuntu-specific
  location for lldb-3.5.
- Unify the probing logic for Linux and OS X.
- In addition to ensuring the presence of LLDB.h, ensure that liblldb is
  present.
- Fix an ambiguously-sized comparison in umthunkstub.S.

### CODE REVIEW

**Comment by pgavlin** [comment]
@mikem8361 @sergiy-k PTAL

@kangaroo you may also want to take a look at this--I don't have a Mac with which to check the OS X build.

**Comment by pgavlin** [comment]
@kangaroo Where do you have liblldb and LLDB.h installed, and how did you obtain them? Are they provided with XCode or the command line tools package?

**Comment by kangaroo** [comment]
@pgavlin Apple does not ship things in a nice way unfortunately.  They ship LLDB.framework as a private framework with Xcode, but no headers.  My current workflow is:

1. Check out LLDB to get public API headers
2. Set LLDB_INCLUDE_DIR=<path_to_checkout>/include
3. Set LLDB_LIB_DIR=/Library/Developer/CommandLineTools/Library/PrivateFrameworks/

**Comment by pgavlin** [comment]
@kangaroo Got my hands on a Mac for testing; https://github.com/pgavlin/coreclr/commit/abb7b0ecfd7b7c589b2e9d775da615416343a19f works with the setup you describe. Please feel free to verify this independently if you'd like :)

**Comment by kangaroo** [comment]
Do we really want to set rpath?  Otherwise LGTM

**Comment by pgavlin** [comment]
All of the guidance I could find pointed to yes. Is there a good reason not to?

**Comment by kangaroo** [comment]
Well, what are we setting it to?  rpath is for helping an executable find a library in a non-standard location (i.e. -- install path), but we don't have a real install path?  Since corerun is sxs libcoreclr.dylib, it still resolves without rpath.

I don't think we should be setting it until we have a longer term install strategy and location.

**Comment by pgavlin** [comment]
My impression was that rpath was particularly useful for finding libraries embedded within an app bundle, which AFAIK is the deployment plan for coreclr. @sergiy-k , am I correct here?

**Comment by pgavlin** [comment]
FWIW, rpath is currently being set to "@rpath/coreclr.dylib" or similar.

**Comment by kangaroo** [comment]
Right, but are we leaving it as a dylib or a framework?  If its a framework that @rpath is wrong.

We can change it in the future or fork this off to a separate discussion.  I don't think it blocks this merge.

**Comment by mikem8361** [comment]
LGTM

**Comment by pgavlin** [comment]
Ah, fair point. Forking a separate discussion SGTM; filed #377 to track.

**Comment by kangaroo** [comment]
@pgavlin I just realize the change to make the error into a warning didn't make it.  This means that OS X builds out of the box are broken.

**Comment by kangaroo** [comment]
What about something like https://gist.github.com/kangaroo/a3b10599b63cc06b7106

**Comment by pgavlin** [comment]
@kangaroo D'oh; thanks for the reminder. I'll make the changes and submit another PR.

**Pull request merged**
