### PR TITLE
Fix CI tizen build error

### PR DESCRIPTION
**Pull request by hseok-oh**
Fix CI tizen build error caused by chmod

### CODE REVIEW

**Comment by hseok-oh** [comment]
@dotnet-bot test ci

**Comment by hseok-oh** [comment]
related issue: #10897 

@danmosemsft @gkhanna79 PTAL

**Comment by hseok-oh** [comment]
Tizen test failed in this PR because fixed netci.groovy did net affect build test.

**Comment by jkotas** [comment]
Thanks. I am going to merge this to see whether it fixes the problem.

**Pull request merged**
