### PR TITLE
Refactor genEventing script to remove SELECTANY from provider context struct definitions

### PR DESCRIPTION
**Pull request by sywhang**
This refactors the genEventing script so that the static runtime context definitions don't contain SELECTANY.

### CODE REVIEW

**Comment by sywhang** [comment]
FYI @franksinankaya

**Comment by franksinankaya** [comment]
Thanks for the heads up. I'll rebase.

**Comment by franksinankaya** [comment]
There is still more

`coreclr/bin/obj/Linux.x64.Debug/src/inc/clrproviders.h:39:31: error: ‘MICROSOFT_WINDOWS_DOTNETRUNTIME_PROVIDER_LTTNG_Context’ initialized and declared ‘extern’ [-Werror]
 SELECTANY LTTNG_TRACE_CONTEXT MICROSOFT_WINDOWS_DOTNETRUNTIME_PROVIDER_LTTNG_Context = { W("Microsoft-Windows-DotNETRuntime"), 0, false, 0 };
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 36%] Building CXX object src/utilcode/CMakeFiles/utilcode_crossgen.dir/util_nodependencies.cpp.o
coreclr/bin/obj/Linux.x64.Debug/src/inc/clrproviders.h:252:35: error: ‘MICROSOFT_WINDOWS_DOTNETRUNTIME_RUNDOWN_PROVIDER_EVENTPIPE_Context’ initialized and declared ‘extern’ [-Werror]
 SELECTANY EVENTPIPE_TRACE_CONTEXT MICROSOFT_WINDOWS_DOTNETRUNTIME_RUNDOWN_PROVIDER_EVENTPIPE_Context = { W("Microsoft-Windows-DotNETRuntimeRundown"), 0, false, 0 };
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
coreclr/bin/obj/Linux.x64.Debug/src/inc/clrproviders.h:253:31: error: ‘MICROSOFT_WINDOWS_DOTNETRUNTIME_RUNDOWN_PROVIDER_LTTNG_Context’ initialized and declared ‘extern’ [-Werror]
 SELECTANY LTTNG_TRACE_CONTEXT MICROSOFT_WINDOWS_DOTNETRUNTIME_RUNDOWN_PROVIDER_LTTNG_Context = { W("Microsoft-Windows-DotNETRuntimeRundown"), 0, false, 0 };
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
coreclr/bin/obj/Linux.x64.Debug/src/inc/clrproviders.h:313:35: error: ‘MICROSOFT_WINDOWS_DOTNETRUNTIME_STRESS_PROVIDER_EVENTPIPE_Context’ initialized and declared ‘extern’ [-Werror]
 SELECTANY EVENTPIPE_TRACE_CONTEXT MICROSOFT_WINDOWS_DOTNETRUNTIME_STRESS_PROVIDER_EVENTPIPE_Context = { W("Microsoft-Windows-DotNETRuntimeStress"), 0, false, 0 };
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
coreclr/bin/obj/Linux.x64.Debug/src/inc/clrproviders.h:314:31: error: ‘MICROSOFT_WINDOWS_DOTNETRUNTIME_STRESS_PROVIDER_LTTNG_Context’ initialized and declared ‘extern’ [-Werror]
 SELECTANY LTTNG_TRACE_CONTEXT MICROSOFT_WINDOWS_DOTNETRUNTIME_STRESS_PROVIDER_LTTNG_Context = { W("Microsoft-Windows-DotNETRuntimeStress"), 0, false, 0 };
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
coreclr/bin/obj/Linux.x64.Debug/src/inc/clrproviders.h:320:35: error: ‘MICROSOFT_WINDOWS_DOTNETRUNTIME_PRIVATE_PROVIDER_EVENTPIPE_Context’ initialized and declared ‘extern’ [-Werror]
 SELECTANY EVENTPIPE_TRACE_CONTEXT MICROSOFT_WINDOWS_DOTNETRUNTIME_PRIVATE_PROVIDER_EVENTPIPE_Context = { W("Microsoft-Windows-DotNETRuntimePrivate"), 0, false, 0 };
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
coreclr/bin/obj/Linux.x64.Debug/src/inc/clrproviders.h:321:31: error: ‘MICROSOFT_WINDOWS_DOTNETRUNTIME_PRIVATE_PROVIDER_LTTNG_Context’ initialized and declared ‘extern’ [-Werror]
 SELECTANY LTTNG_TRACE_CONTEXT MICROSOFT_WINDOWS_DOTNETRUNTIME_PRIVATE_PROVIDER_LTTNG_Context = { W("Microsoft-Windows-DotNETRuntimePrivate"), 0, false, 0 };
 `

**Comment by franksinankaya** [comment]
@jkotas FYI

**Comment by jkotas** [comment]
Thank you!

**Pull request merged**
