### PR TITLE
Fix version issue with System.IO for serialization tests

### PR DESCRIPTION
**Pull request by AndyAyersMS**
@BruceForstall PTAL

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
Failures on windows are not directly related, but I'd like to see the tests run, so will retry.

**Comment by AndyAyersMS** [comment]
@dotnet-bot retest Windows_NT x64 Release Build and Test

**Comment by AndyAyersMS** [comment]
@dotnet-bot retest Windows_NT x86 Release Build

**Comment by AndyAyersMS** [comment]
@mmitche PTAL

**Comment by jkotas** [comment]
LGTM

**Pull request merged**
