### PR TITLE
Initial removal of thread suspension code from PAL

### PR DESCRIPTION
**Pull request by adityamandaleeka**
This change removes SuspendThread and a bunch of associated code that is no longer needed once it goes away (such as everything related to suspension-safe regions and THREADMarkDiagnostic).

There is still some more to remove, but at this point this PR is already touching a ton of code, so I decided to send out all the changes so far to avoid making the diff harder to look at. For example, in this PR, USE_SIGNALS_FOR_THREAD_SUSPENSION is disabled on every platform, but the switch and the code under it is still in place. It will be removed entirely in an upcoming PR.

I've also tried to make each commit address logically related chunks where possible.

Addresses #1795

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
@janvorli @jkotas @sergiy-k PTAL. The diff is not as bad as it initially looks :smile:

**Comment by adityamandaleeka** [comment]
Looking at the failure on Windows...

**Comment by sergiy-k** [comment]
Nice! Thank you.

**Comment by janvorli** [comment]
@adityamandaleeka Thanks a lot for making this change! @sergiy-k, I wonder if it also causes a visible perf gain.

**Pull request merged**
