### PR TITLE
WIP DO NOT MERGE Dummy change

### PR DESCRIPTION
**Pull request by BruceForstall**

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT x64_arm64_altjit Checked Build and Test
@dotnet-bot test Windows_NT x64_arm64_altjit Debug Build and Test
@dotnet-bot test Windows_NT x64_arm64_altjit Release Build and Test
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_baseline
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_jitstress1
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_jitstress2
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_jitstressregs0x1000
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_jitstressregs0x10
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_jitstressregs0x80
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_jitstressregs1
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_jitstressregs2
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_jitstressregs3
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_jitstressregs4
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_jitstressregs8
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_minopts
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_tieredcompilation
@dotnet-bot test Windows_NT x64_arm64_altjit Checked forcerelocs
@dotnet-bot test Windows_NT x64_arm64_altjit Checked jitsse2only
@dotnet-bot test Windows_NT x64_arm64_altjit Checked jitstress1
@dotnet-bot test Windows_NT x64_arm64_altjit Checked jitstress2_jitstressregs0x1000
@dotnet-bot test Windows_NT x64_arm64_altjit Checked jitstress2_jitstressregs0x10
@dotnet-bot test Windows_NT x64_arm64_altjit Checked jitstress2_jitstressregs0x80
@dotnet-bot test Windows_NT x64_arm64_altjit Checked jitstress2_jitstressregs1
@dotnet-bot test Windows_NT x64_arm64_altjit Checked jitstress2_jitstressregs2
@dotnet-bot test Windows_NT x64_arm64_altjit Checked jitstress2_jitstressregs3
@dotnet-bot test Windows_NT x64_arm64_altjit Checked jitstress2_jitstressregs4
@dotnet-bot test Windows_NT x64_arm64_altjit Checked jitstress2_jitstressregs8
@dotnet-bot test Windows_NT x64_arm64_altjit Checked jitstress2
@dotnet-bot test Windows_NT x64_arm64_altjit Checked jitstressregs0x1000
@dotnet-bot test Windows_NT x64_arm64_altjit Checked jitstressregs0x10
@dotnet-bot test Windows_NT x64_arm64_altjit Checked jitstressregs0x80
@dotnet-bot test Windows_NT x64_arm64_altjit Checked jitstressregs1
@dotnet-bot test Windows_NT x64_arm64_altjit Checked jitstressregs2
@dotnet-bot test Windows_NT x64_arm64_altjit Checked jitstressregs3
@dotnet-bot test Windows_NT x64_arm64_altjit Checked jitstressregs4
@dotnet-bot test Windows_NT x64_arm64_altjit Checked jitstressregs8
@dotnet-bot test Windows_NT x64_arm64_altjit Checked minopts
@dotnet-bot test Windows_NT x64_arm64_altjit Checked tailcallstress
@dotnet-bot test Windows_NT x64_arm64_altjit Checked tieredcompilation
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_baseline
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_jitstress1
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_jitstress2
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_jitstressregs0x1000
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_jitstressregs0x10
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_jitstressregs0x80
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_jitstressregs1
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_jitstressregs2
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_jitstressregs3
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_jitstressregs4
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_jitstressregs8
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_minopts
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_tieredcompilation
@dotnet-bot test Windows_NT x86_arm_altjit Checked forcerelocs
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitsse2only
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress1
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2_jitstressregs0x1000
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2_jitstressregs0x10
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2_jitstressregs0x80
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2_jitstressregs1
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2_jitstressregs2
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2_jitstressregs3
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2_jitstressregs4
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2_jitstressregs8
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs0x1000
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs0x10
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs0x80
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs1
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs2
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs3
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs4
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs8
@dotnet-bot test Windows_NT x86_arm_altjit Checked minopts
@dotnet-bot test Windows_NT x86_arm_altjit Checked tailcallstress
@dotnet-bot test Windows_NT x86_arm_altjit Checked tieredcompilation
@dotnet-bot test Windows_NT x86_arm_altjit Checked Build and Test
@dotnet-bot test Windows_NT x86_arm_altjit Debug Build and Test
@dotnet-bot test Windows_NT x86_arm_altjit Release Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT jitstress1
@dotnet-bot test Windows_NT jitstress2
@dotnet-bot test Windows_NT jitstress2_jitstressregs4
@dotnet-bot test Windows_NT tailcallstress
@dotnet-bot test Ubuntu jitstress1
@dotnet-bot test Ubuntu jitstress2
@dotnet-bot test Ubuntu tailcallstress
@dotnet-bot test Windows_NT arm64 Cross Checked tailcallstress
@dotnet-bot test Windows_NT arm64 Cross Checked jitstress1
@dotnet-bot test Windows_NT arm64 Cross Checked jitstress2
@dotnet-bot test Ubuntu arm64 Cross Debug Innerloop Build

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_baseline
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_jitstress1
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_jitstress2
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_jitstressregs0x1000
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_jitstressregs0x10
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_jitstressregs0x80
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_jitstressregs1
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_jitstressregs2
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_jitstressregs3
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_jitstressregs4
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_jitstressregs8
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_minopts
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_tieredcompilation
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_baseline
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_jitstress1
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_jitstress2
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_jitstressregs0x1000
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_jitstressregs0x10
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_jitstressregs0x80
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_jitstressregs1
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_jitstressregs2
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_jitstressregs3
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_jitstressregs4
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_jitstressregs8
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_minopts
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_tieredcompilation

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT jitstress2
@dotnet-bot test Windows_NT jitstress2_jitstressregs4

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT jitstress1
@dotnet-bot test Windows_NT jitstress2
@dotnet-bot test Windows_NT jitstress2_jitstressregs4
@dotnet-bot test Windows_NT tailcallstress
@dotnet-bot test Ubuntu jitstress1
@dotnet-bot test Ubuntu jitstress2
@dotnet-bot test Ubuntu tailcallstress
@dotnet-bot test Windows_NT arm64 Cross Checked tailcallstress
@dotnet-bot test Windows_NT arm64 Cross Checked jitstress1
@dotnet-bot test Windows_NT arm64 Cross Checked jitstress2
@dotnet-bot test Ubuntu arm64 Cross Debug Innerloop Build

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu x64 corefx_baseline
@dotnet-bot test Windows_NT x64 corefx_baseline
@dotnet-bot test Windows_NT x86 corefx_baseline

**Comment by jashook** [comment]
@dotnet-bot help

**Comment by jashook** [comment]
@dotnet-bot test Ubuntu x64 corefx_baseline

**Comment by BruceForstall** [comment]
ok, now it looks like they triggered.

**Comment by mmitche** [comment]
@BruceForstall It could be either of two things:
- GitHub takes a while to update or send the message to Jenkins (this happens occasionally).
- Jenkins was slower than expected.

Can you link the couple runs that you just triggered? i'm not able to identify them.

**Comment by BruceForstall** [comment]
What's odd is it seems more jobs than I triggered actually went to "pending" state. Maybe once Jenkins "saw" this PR again, it started updating things it "forgot" to in the past?

E.g.,
"Ubuntu armlb Cross Debug Innerloop Build"

The ones I triggered:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_corefx_baseline_prtest/129/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_corefx_baseline_prtest/68/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_corefx_baseline_prtest/109/

**Comment by mmitche** [comment]
@BruceForstall Maybe overlapping phrases?  Anyways it looked like it started immediately, but github didn't update.

I have definitely seen cases where the page needs a manual refresh.

**Comment by BruceForstall** [comment]
I actually did a manual page update / refresh, but didn't see a change.

**Pull request closed without merging**
