### PR TITLE
Revert "Fast-path for ASCII & UTF8 Encoding ASCII data"

### PR DESCRIPTION
**Pull request by tarekgh**
Reverts dotnet/coreclr#8969

### CODE REVIEW

**Comment by tarekgh** [comment]
@stephentoub

**Comment by stephentoub** [comment]
For reference, failing corefx tests:
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/2492/consoleText

**Comment by tarekgh** [comment]
looks this change caused a lot of failures. so reverting till we fix the triggered failures

**Comment by stephentoub** [comment]
cc: @benaadams

**Comment by benaadams** [comment]
Checking

**Comment by benaadams** [comment]
Checking the failures

**Comment by tarekgh** [comment]
@benaadams we'll revert the change here anyway to unblock coreclr from ported to corefx and then you can take your time to investigate

**Comment by benaadams** [comment]
Definitely Encoder issues; might have comparer issues also?

>      System.Collections.Immutable.Tests.ImmutableArrayBuilderTest.SortComparer [FAIL]
>        Assert.Equal() Failure
>        Expected: String[] ["a", "B", "c"]
>        Actual:   Builder<String> ["B", "a", "c"]

**Comment by stephentoub** [comment]
Might comparer failures be due to https://github.com/dotnet/coreclr/pull/9091?

**Comment by benaadams** [comment]
That's what I was thinking due to order; but also seems to be wrong types?

**Comment by benaadams** [comment]
Types might just be a diagnostic output difference (e.g. might be comparing Enumerables)

**Comment by jkotas** [comment]
Yes, there is a bug in #9091. It incorrectly computes the result from the original characters; not from the case insensitive difference. I guess we should roll it back too.

cc @bbowyersmyth

**Comment by tarekgh** [comment]
test OSX x64 Checked Build and Test please
test Ubuntu x64 Checked Build and Test please

**Comment by tarekgh** [comment]
https://github.com/dotnet/coreclr/pull/9104

**Comment by tarekgh** [comment]
test Ubuntu x64 Checked Build and Test please

**Comment by tarekgh** [comment]
test OSX x64 Checked Build and Test please

**Comment by benaadams** [comment]
Have resolved this; however am writing some more tests for corefx to make sure everything is covered before making a PR

**Comment by tarekgh** [comment]
@benaadams thanks.

I assume you are going to run all corefx tests on your changes before submitting the PR, right?

**Comment by benaadams** [comment]
Yes, I had done previously; but hadn't for the subsequent tweaks which I thought were mostly cosmetic - I guess that's why there are tests 😉

**Comment by tarekgh** [comment]
Great! I guess the fixes should be trivial then.

**Comment by benaadams** [comment]
> I guess the fixes should be trivial then.

Writing the tests to cope with the algorithm changing halfway through processing on the other hand...

**Pull request merged**
