### PR TITLE
Fix ARM cast codegen

### LINKED ISSUE #18040: Broken conv.ovf.i8.un decomposition
IL sample:
```
ldind.i1
conv.ovf.i8.un
```
IR post decomposition:
```
N001 (  1,  1) [000002] -------------        t2 =    LCL_VAR   byref  V00 arg0         u:2 (last use) $80
                                                  /--*  t2     byref  
N002 (  4,  3) [000003] *--XG--------        t3 = *  IND       byte   <l:$140, c:$180>
                                                  /--*  t3     byte   
               [000012] ---XG----U---       t12 = *  CAST      int <- byte <- uint
               [000013] -------------       t13 =    CNS_INT   int    0
                                                  /--*  t12    int    
                                                  +--*  t13    int    
               [000014] ---XG--------       t14 = *  LONG      long  
```
x86 generated code:
```asm
       0FBE01       movsx    eax, byte  ptr [ecx]
       0FBEC0       movsx    eax, al
       8902         mov      dword ptr [edx], eax
       33C0         xor      eax, eax
       894204       mov      dword ptr [edx+4], eax
```
ARM32 generated code:
```asm
000006  F990 3000      ldrsb   r3, [r0]
00000A  B2DB           uxtb    r3, r3
00000C  460A           mov     r2, r1
00000E  6013           str     r3, [r2]
000010  2300           movs    r3, 0
000012  6053           str     r3, [r2+4]
```
There seem to be 2 distinct issues:
* This is a zero extending cast from U4 to I8. Neither `movsx` nor `uxtb` make sense in this context. Sign extending from I1 to I4 is the job of the load.
* For the same cast node x86 and ARM32 emit different instructions, one sign extends and the other zero extends. One of them is wrong but probably that's a side effect of the unusual cast - the IL equivalent of that cast would be `conv.i1.un` but that does not exist. On x86 `movsx` hides the issue since is sign extends again the byte previously loaded.

Found while adding tests for #12676. Test coverage for casts seems to be lacking, I keep running into bugs (either existing or of my own doing) and existing tests fail to catch them so I generated some. This case failed on ARM32 but not on x86.

### PR DESCRIPTION
**Pull request by mikedn**
ARM cast codegen is rather convoluted and sometimes does the wrong thing by applying `GTF_UNSIGNED` to the destination type even though this flag is only about the source type.

Fixes #18040

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Checked normal Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2 Build and Test

@dotnet-bot test Windows_NT arm64 Cross Checked normal Build and Test

**Comment by mikedn** [comment]
Presumably the failure of FixedAddressValueType is a glitch? I tried to run it locally with AltJit and I don't see any differences in the generated code.

**Comment by BruceForstall** [comment]
Perhaps, although I don't see any other example of it failing. Try again:

@dotnet-bot test Ubuntu arm Cross Checked jitstress1 Build and Test

**Comment by CarolEidt** [comment]
ping @BruceForstall - are you still wanting to review this?

**Comment by mikedn** [comment]
Hopefully you aren't trying to review those 11000 lines of test code :)

**Comment by BruceForstall** [comment]
All the tests I triggered passed, so I'll sign off. (Was mostly out today)

**Pull request merged**
