### PR TITLE
[Experimental/WIP] Allow min thread pool workers to go below NumProcessors

### PR DESCRIPTION
**Pull request by sdmaclea**

### CODE REVIEW

**Comment by sdmaclea** [comment]
@kouvel @stephentoub @benaadams 

This results in a 30-60% improvement on Arm64 techempower plaintext on top of #13007, #12771 & #13002.

There are several justifications for this.

When running this benchmark coreclr seem to use 3 x ThreadPoolThreads + 2.  This is in part because libuv is also using threads.

When I was testing running wrk on localhost produced the best score.  Higher pool thread count starves wrk threads and throughput decreases.  There seems to need to be one wrk thread for every thread in the thread pool.  So on a 48 core system peak performance is currently found with a thread pool thread count of about 12.

Also it should be noted that due to security issues one primary ASP.NET configuration has CoreCLR behind NGINX reverse proxy.  CoreCLR needs to avoid starving NGINX.  So in many ways this is similar to wrk running on the same machine driving localhost.

Observation is that Hill Climbing is slow to converge to optimal threads and is also noisy choosing different amount of threads each run.  Hillclimbing algorithm will probably need to be tuned/redesigned to accomodate this patch.

**Comment by 4creators** [comment]
Hill Climbing is not very good at avoiding local minimum in convex optimizations and once there usually it cannot escape from it. This would explain behaviour you have described.

> Observation is that Hill Climbing is slow to converge to optimal threads and is also noisy choosing different amount of threads each run. 

I would suggest using Simulated Annealing instead as it is superior to Hill Climbing and solves local minima escaping problem leading to expected optimization result.

**Comment by benaadams** [comment]
> Also it should be noted that due to security issues one primary ASP.NET configuration has CoreCLR behind NGINX reverse proxy. CoreCLR needs to avoid starving NGINX. So in many ways this is similar to wrk running on the same machine driving localhost.

In 2.0 using Kestrel as an edge server is on the cards

**Comment by kouvel** [comment]
I believe changing the default min would need a significant amount of testing on many different types of scenarios. The current hill climbing works when there is a constant stream of short work items that are mostly similar in nature, to for instance compensate for the occasional blocking work items by increasing the number of worker threads. Even then, it is pretty slow at choosing the right number of threads, and sometimes doesn't get there in reasonable time. When the work is bursty or includes different types of work items, the current hill climbing doesn't work very well.

Once hill climbing reduces the number of threads, if the thread pool then receives bursty work that runs optimally on proc count number of threads, hill climbing may not be able to compensate very quickly or at all, and that work would run much slower than otherwise. Longer-running work may be compensated for by the starvation heuristic but the threshold for triggering that is pretty high and typically unlikely to happen except when all currently running work in long-running or blocking. I don't think it's a good idea to decrease the default min threads without fixing these issues and doing more extensive testing on several types of scenarios.

The perf gain in this scenario is very nice, but I don't think it's critical to change the default in order to get this perf gain. The min thread count can be configured as appropriate for the app.

That said, I think the change to initialize MaxWorking to a value close to the proc count instead of to the min thread count is a good change. In my tests with a configured lower minimum, the thread count seems to start at the proc count even without the MaxWorking initialization change for some reason, but  I suspect it is an unintended consequence of something else.

**Comment by sdmaclea** [comment]
@4creators Thanks I'll watch out for local maxima.  

@kouvel I opened an issue to allow tuning the threadPool threads in asp.net benchmarks.  

If I want to make forward progress on this optimization, perhaps it should be initially limited to [ARM64/Unix].  

For hillclimbing, threadpool optimization.  I assume we are looking at improving the step response as load changes.  We want a somewhat underdamped but stable response.  A compromise between minimizing the loss in throughput and minimizing wasted CPU cycles.  Also handling noisy erratic workloads.

It would be nice to optimize across various workload characteristics

- Non thread pool thread usage (libuv ...)
- I/O, Memory, CPU bound, CPU usage, blocking
- Arrival rate, variability, modes
- Homogenous, Mixed, Modes 

I am not sure when I'll have sufficient bandwidth to create a systematic stimulus.  I looked briefly at @benaadams benchmark, it looked interesting, but I have not had a chance to fully understand it.

I'll probably play with plaintext with threadpool dispatch off.  So I may not get to this immediately.

**Comment by kouvel** [comment]
I was thinking about what kind of potential issues there would be and how to fix, and I haven't yet convinced myself that it would be easy to get a good balance when considering many different types of situations. Maybe we can introduce a config variable and use this calculated min when that config is enabled, and new asp.net projects could turn that on by default. If we are able to find a good balance and change the default, the config variable could be ignored.

Regarding the hill climbing issues, just one idea, we could certainly get and use some better information, for instance to detect the cases where there isn't a continuous stream of work or when the average throughput of work items is regularly changing when the thread count isn't, etc. If we can identify cases where hill climbing does not perform well, it could trigger some action to for instance reset the thread count to proc count if the thread count is lower, and reduce the thread count by some % if it's higher than the proc count.

I have filed an issue for looking into this in more detail: https://github.com/dotnet/coreclr/issues/13085

**Comment by sdmaclea** [comment]
@kouvel As this no longer seems to be bneficial, I am closing

**Pull request closed without merging**
