### PR TITLE
[x86/Linux] Create minimal frame for funclets

### PR DESCRIPTION
**Pull request by parjong**
This commit makes each funclet to have minimal frame.

### CODE REVIEW

**Comment by parjong** [comment]
\CC @seanshpark @wateret

**Comment by parjong** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test please

**Comment by parjong** [comment]
@dotnet/jit-contrib Please take a look.

**Comment by parjong** [comment]
@jkotas @BruceForstall Please take a look.

**Comment by jkotas** [comment]
Is this needed to make something work, or are you just fixing TODO? 

We are not consistent between platforms ... but the preferred funclet convention is that the funclet does not need to save any calllee saved registers; and that the exception handling subsystem restores them to what they were when the control left the function originally.

**Comment by parjong** [comment]
I currently have no issue related with callee-saved registers. I just want to fix TODO before starting PSPSym-related fixes. 

For that purpose, it seems that EBP should be stored/restored, but I'm not sure about other callee saved registers. I just mimic the corresponding code in AMD64.

**Comment by BruceForstall** [comment]
It would be useful to have a comment like the one above the amd64 version of `CodeGen::genFuncletProlog()` that shows the calling convention and stack layout for linux/x86.

You need to determine what the register convention is for the EH subsystem, as @jkotas says. This will affect register liveness into and out of funclets. Currently, we kill all registers, and local vars need to get reloaded from the stack. We use the PSPSym because we can't trust that the frame pointer is re-established to what the parent frame had. If the EH subsystem can guarantee it gets re-established, you wouldn't need that.

**Comment by parjong** [comment]
@jkotas @BruceForstall Thank you for comments. It would be better to consider this issue when we consider PSPSym-related issues. I'll create another PR when we are ready later.

**Pull request closed without merging**
