### PR TITLE
Fix hardware intrinsc API XML comments

### PR DESCRIPTION
**Pull request by fiigii**
Fix https://github.com/dotnet/coreclr/issues/21514

@BruceForstall

### CODE REVIEW

**Comment by BruceForstall** [comment]
@fiigii I found some more cases in the Windows x64 pri-1 build:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/checked_windows_nt/10934/consoleFull
```
shared\System\Runtime\Intrinsics\Arm\Arm64\Aes.cs(19,1): warning CS1570: XML comment has badly formed XML -- 'End tag was not expected at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Aes.cs(25,1): warning CS1570: XML comment has badly formed XML -- 'End tag was not expected at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Aes.cs(31,1): warning CS1570: XML comment has badly formed XML -- 'End tag was not expected at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Aes.cs(37,1): warning CS1570: XML comment has badly formed XML -- 'End tag was not expected at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Sha1.cs(20,1): warning CS1570: XML comment has badly formed XML -- 'End tag was not expected at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Sha1.cs(26,1): warning CS1570: XML comment has badly formed XML -- 'End tag was not expected at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Sha1.cs(32,1): warning CS1570: XML comment has badly formed XML -- 'End tag was not expected at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Sha1.cs(38,1): warning CS1570: XML comment has badly formed XML -- 'End tag was not expected at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Sha1.cs(44,1): warning CS1570: XML comment has badly formed XML -- 'End tag was not expected at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Sha1.cs(50,1): warning CS1570: XML comment has badly formed XML -- 'End tag was not expected at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Sha256.cs(20,1): warning CS1570: XML comment has badly formed XML -- 'End tag was not expected at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Sha256.cs(26,1): warning CS1570: XML comment has badly formed XML -- 'End tag was not expected at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Sha256.cs(32,1): warning CS1570: XML comment has badly formed XML -- 'End tag was not expected at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Sha256.cs(38,1): warning CS1570: XML comment has badly formed XML -- 'End tag was not expected at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Simd.cs(101,60): warning CS1570: XML comment has badly formed XML -- 'Whitespace is not allowed at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Simd.cs(109,55): warning CS1570: XML comment has badly formed XML -- 'Whitespace is not allowed at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Simd.cs(116,58): warning CS1570: XML comment has badly formed XML -- '0' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Simd.cs(116,58): warning CS1570: XML comment has badly formed XML -- 'An identifier was expected.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Simd.cs(124,58): warning CS1570: XML comment has badly formed XML -- '0' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Simd.cs(124,58): warning CS1570: XML comment has badly formed XML -- 'An identifier was expected.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Simd.cs(132,57): warning CS1570: XML comment has badly formed XML -- 'Whitespace is not allowed at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Simd.cs(205,61): warning CS1570: XML comment has badly formed XML -- 'Whitespace is not allowed at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Simd.cs(225,61): warning CS1570: XML comment has badly formed XML -- 'Whitespace is not allowed at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Simd.cs(24,54): warning CS1570: XML comment has badly formed XML -- 'Whitespace is not allowed at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Simd.cs(250,54): warning CS1570: XML comment has badly formed XML -- 'Whitespace is not allowed at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Simd.cs(270,54): warning CS1570: XML comment has badly formed XML -- 'Whitespace is not allowed at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Simd.cs(331,54): warning CS1570: XML comment has badly formed XML -- 'Whitespace is not allowed at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Simd.cs(39,54): warning CS1570: XML comment has badly formed XML -- 'Whitespace is not allowed at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Simd.cs(61,64): warning CS1570: XML comment has badly formed XML -- 'Whitespace is not allowed at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Simd.cs(69,55): warning CS1570: XML comment has badly formed XML -- 'Whitespace is not allowed at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Simd.cs(77,55): warning CS1570: XML comment has badly formed XML -- 'Whitespace is not allowed at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Simd.cs(85,60): warning CS1570: XML comment has badly formed XML -- 'Whitespace is not allowed at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
shared\System\Runtime\Intrinsics\Arm\Arm64\Simd.cs(93,55): warning CS1570: XML comment has badly formed XML -- 'Whitespace is not allowed at this location.' [D:\j\workspace\checked_windo---14fb495b\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
```

Can you make sure these are fixed, also?

**Comment by fiigii** [comment]
Thank you, will fix.

**Comment by fiigii** [comment]
Fixed ARM intrinsic comments as well. @BruceForstall PTAL

**Comment by danmosemsft** [comment]
It wounds be good to enable warning as errors for malformed XML comments. There is a list in the PR working towards that in corefx: https://github.com/dotnet/corefx/pull/32934

Any of these we got clean on, we should make errors.

**Comment by tannergooding** [comment]
Merging, the four failing jobs had all tests succeed but failed due to a Jenkins infrastructure issue.

**Pull request merged**
