### PR TITLE
[x86/Linux] Fix codegen to handle GT_OBJ

### PR DESCRIPTION
**Pull request by seanshpark**
Add to handle GT_OBJ in genCodeForTreeNode()
- fixes unit test Loader/classloader/generics/Instantiation/Recursion/genrecur
- IL_STUB_UnboxingStub geneates GT_OBJ with register

### CODE REVIEW

**Comment by seanshpark** [comment]
Fixes #9706

**Comment by seanshpark** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by seanshpark** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by seanshpark** [comment]
@BruceForstall , PTAL, I've slightly changed to code and rebased.

**Comment by janvorli** [comment]
@BruceForstall can you take a look please?

**Comment by seanshpark** [comment]
I'll close this PR as #10538 solve the problem.

**Pull request closed without merging**
