### PR TITLE
Revert "For corefx testing, use a matching corefx repo version git hash"

### PR DESCRIPTION
**Pull request by jkotas**
Reverts dotnet/coreclr#15944

### CODE REVIEW

**Comment by jkotas** [comment]
This change made the corefx_baseline jobs to fail 2x more often (for ~2x longer periods of time) than before. I think we should revert it.

What was happening before:

1. CoreFX build breaking change is made in CoreCLR
2. Official build produces Update CoreCLR PR in corefx.
3. Update PR is merged. corefx_baseline jobs are green again.

What is happening after this change:

1. CoreFX build breaking change is made in CoreCLR
2. Official build produces Update CoreCLR PR in corefx.
3. Update PR is merged. corefx_baseline jobs are still failing.
4. Official build produces Update CoreFX PR in coreclr.
5. Update PR is merged. corefx_baseline jobs are green again.

**Comment by jkotas** [comment]
Related discussion https://github.com/dotnet/coreclr/pull/16190#issuecomment-362920679

**Comment by jkotas** [comment]
@dotnet-bot test Windows_NT x64 Checked corefx_baseline
@dotnet-bot test Ubuntu x64 Checked corefx_baseline

**Comment by jkotas** [comment]
Windows x64 Checked failing with:

https://github.com/dotnet/coreclr/issues/16201
https://github.com/dotnet/corefx/issues/26821

**Comment by BruceForstall** [comment]
Seems reasonable. The reverted code had one possibly minor benefit that the version of corefx tested was discoverable, and repeatable. Now, the version of corefx tested is time-based, so even multiple consecutive job runs potentially (and likely) pick different corefx code to run and test.

Presumably, if breaking changes were initially introduced in the corefx repo, the reverted change protected against them breaking coreclr. You've indicated that is the less likely scenario.

Obviously, we still haven't created a situation where breaking changes in coreclr don't break the CI.

**Pull request merged**
