### PR TITLE
Introduce NetBSD target in init-tools.sh

### PR DESCRIPTION
**Pull request by krytarowski**

### CODE REVIEW

**Comment by ellismg** [comment]
The dotnet cli doesn't produce a netbsd version, so even if this is merged I don't believe it moves much along.

I would structure things so that we don't need to run init-tools.sh when building native code in CoreCLR and then continue the work to bring up the runtime.  If you need managed code either cross build it on another platform or just pick up bits from the CI system.  When things are further along we can use BUILDTOOLS_OVERIDE_RUNTIME stuff to be able to bootstrap a runtime you can use to build managed code.  Once CoreFX and CoreCLR are up and running we can get CLI building and then update this script go restore a correct prebuilt tool chain.

I think merging this gives a false sense of what's working today.

Just my two cents.

**Comment by triciap** [comment]
I Know You Got This .


Sent from my MetroPCS 4G LTE Android device-------- Original message --------From: Matt Ellis <notifications@github.com> Date: 2/2/2016  9:39 PM  (GMT-08:00) To: dotnet/coreclr <coreclr@noreply.github.com> Subject: Re: [coreclr] Introduce NetBSD target in init-tools.sh (#2996) 
The dotnet cli doesn't produce a netbsd version, so even if this is merged I don't believe it moves much along.

I would structure things so that we don't need to run init-tools.sh when building native code in CoreCLR and then continue the work to bring up the runtime.  If you need managed code either cross build it on another platform or just pick up bits from the CI system.  When things are further along we can use BUILDTOOLS_OVERIDE_RUNTIME stuff to be able to bootstrap a runtime you can use to build managed code.  Once CoreFX and CoreCLR are up and running we can get CLI building and then update this script go restore a correct prebuilt tool chain.

I think merging this gives a false sense of what's working today.

Just my two cents.

**Comment by krytarowski** [comment]
Adding new platform might be a chicken-egg problem.

**Comment by krytarowski** [comment]
Since it's a part of external tools where at this moment there is no NetBSD full-support -- I want to first finish up CoreCLR before the release (in March?) and move on to as many .Net Core components as time reduced from sleep will allow me. If I will be too late, I prefer to get coreclr-1.0 with patched cli-1.0 rather than coreclr-1.0 patched + cli-1.0 patched.

Your help to make it happen is appreciated. I'm posting issues in the ticket system for parts that needs investigation.

**Comment by ellismg** [comment]
I'm going to close this.  When we get closer to having NetBSD CoreCLR and can work to bootstrap a CLI tool chain (even if it is hacky) we can revisit this.

One note:

> I want to first finish up CoreCLR before the release (in March?) and move on to as many .Net Core components as time reduced from sleep will allow me.

I think this a good plan of attack.  FWIW, the CoreCLR release dates are now TBD (we haven't updated the milestones because we don't know what the dates are).  Work at whatever pace is reasonable for the porting team and we'll look at release vectors when the port is in a good state.

Thanks again for all the patches, it's great to see this stuff starting to come online.

**Comment by krytarowski** [comment]
Thank you.. be prepared for being pinged on bootstrapping CLI once CoreCLR/FX and RT will be ready!

**Pull request closed without merging**
