### PR TITLE
Fix MacOS Build Break

### PR DESCRIPTION
**Pull request by ellismg**
Fix an issue with newest Apple SDK.

### CODE REVIEW

**Comment by ellismg** [comment]
@jkotas @kangaroo.  Thoughts on doing this?  The other option would be to simply downgrade the CI system back to the 6.2 version of the compilers, but I worry folks who upgrade will run into issues until Apple can fix the underlying problem.

**Comment by jkotas** [comment]
It looks good to me. It may be nice to add a comment in _debug and the makefile that it is workaround for issue in XCode 6.3.

**Comment by ellismg** [comment]
Sure, will do.

**Comment by kangaroo** [comment]
@ellismg I tend to agree with @jkotas.  It is a bit of an ugly workaround, so putting a nice big description in there will help.

**Pull request merged**
