### PR TITLE
Create common files for ARM32 and ARM64 common code

### PR DESCRIPTION
**Pull request by BruceForstall**
Create codegenarmarch.cpp, lowerarmarch.cpp, lsraarmarch.cpp.

For codegenarmarch.cpp, I copied over a bunch of functions that
are almost identical between arm and arm64. I left the functions
intact (didn't change anything), so created one for ARM32 and
one for ARM64, unless they were truly identical. A follow-up
will be to actually merge the functions.

For lowerarmarch.cpp and lsraarmarch.cpp, I did the function
merge for nearly (or completely) identical functions, since
there were so many that were so similar.

### CODE REVIEW

**Comment by BruceForstall** [comment]
This is a start to #10660.

@briansull @dotnet/arm32-contrib PTAL
cc @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm64 Checked
@dotnet-bot test OSX10.12 x64 Checked Build and Test
@dotnet-bot test Ubuntu arm Cross Release Build
@dotnet-bot test Ubuntu x64 Checked Build and Test
@dotnet-bot test Ubuntu16.04 arm Cross Debug Build

**Comment by hqueue** [comment]
I didn't look into ARM CI failure in detail, but it seems that `armel` is passed but only `arm` is failing.
One of  differences between  `arm Cross` and `armel Cross` is ABI.
- `armel Cross`: built with  `ARM_SOFTFP` defined
- `arm Cross`: `ARM_SOFTFP` not defined.

**Comment by hqueue** [comment]
@dotnet-bot test Ubuntu arm Cross Checked Build
@dotnet-bot test Ubuntu arm Cross Debug Build
@dotnet-bot test Ubuntu16.04 arm Cross Release Build
@dotnet-bot test Ubuntu16.04 arm Cross Checked Build
@dotnet-bot test Tizen armel Cross Checked Build

**Comment by BruceForstall** [comment]
@hqueue Do these Ubuntu arm tests normally pass? I wonder if the "permission issue" is a code problem in the JIT that I introduced. Or, is there an infrastructure problem in the CI?

**Comment by hqueue** [comment]
@BruceForstall I don't think it's related to this PR.
 I'm also confused, since it is failing suddenly from several hours ago, although there is no change in ARM CI recently.

@hseok-oh Just posted a PR #10886 for this issue. Let's see.

**Comment by sdmaclea** [comment]
@BruceForstall  FWIW, I ran the 0029a42 version of this patch on Arm64/Unix.  There was no regression

**Comment by BruceForstall** [comment]
Will close and re-open to re-test.

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by BruceForstall** [comment]
Everything passed except the Tizen tests, due to #10886

**Pull request merged**
