### PR TITLE
Add payload size case for GC events

### PR DESCRIPTION
**Pull request by hoyosjs**

### CODE REVIEW

**Comment by cshung** [comment]
@dotnet-bot Test Windows_NT x86 full_opt ryujit CoreCLR Perf Tests Correctness
@dotnet-bot Test Windows_NT arm Cross Debug Innerloop Build

**Comment by hoyosjs** [comment]
@dotnet-bot Windows_NT x86 full_opt ryujit CoreCLR Perf Tests Correctness

Jenkins I/O failure.

**Comment by hoyosjs** [comment]
@dotnet-bot Windows_NT x86 full_opt ryujit CoreCLR Perf Tests Correctness

**Comment by hoyosjs** [comment]
@dotnet-bot Test Windows_NT x86 full_opt ryujit CoreCLR Perf Tests Correctness

**Pull request merged**
