### PR TITLE
[Arm64] Optimize JIT_WriteBarriers

### LINKED ISSUE #5833: ARM64: Sane contract for WriteBarrier helper
The WriteBarrier helper on contract on ARM64 includes incrementing the target pointer. See https://github.com/dotnet/coreclr/pull/5821

It is very odd contract that we do not have anywhere else. It makes the hottest write barrier one instruction longer for no good reason, and it is not desirable to standardize this contract for ReadyToRun.

### LINKED ISSUE #11374: [Arm64] Optimize JIT_WriteBarriers*
They appear to be on the critical path to writing object references to the heap.

AMD64 went to significant length to optimize these functions.

### LINKED ISSUE #12197: [Arm64] COMPlus_gcServer=1 fails
I only ran one test, but it failed.  (Passes when gcServer=0)

```
$ corerun JIT/Directed/nullabletypes/Desktop/boxunboxvaluetype_do/boxunboxvaluetype_do.exe 
--- char? s = Helper.Create(default(char)) ---
--- char? s = null ---

Assert failure(PID 1041 [0x00000411], Thread: 1041 [0x0411]): (dac_cast<TADDR>(m_pMethTab) & MARKED_BIT) == 0
    File: src/vm/object.h Line: 242
    Image: /home/sdmaclea/coreoverlay/corerun

Aborted
```

Relevant section of the backtrace
```
#9  0x0000ffffb7409d40 in Object::GetMethodTable (this=<optimized out>)
     at src/vm/object.h:242
#10 PtrArray::GetArrayElementTypeHandle (this=0xfff03000b298) 
    at src/vm/object.h:916
#11 JIT_Stelem_Ref_Portable (array=0xfff03000b298, idx=0, val=0xfff03001e018)
    at src/vm/jithelpers.cpp
```

### PR DESCRIPTION
**Pull request by sdmaclea**
Fixes #5833
Fixes #11374
Fixes #12197

### CODE REVIEW

**Comment by sdmaclea** [comment]
@jashook @jkotas This is another try after the revert.  Only changes
+ Rebase
+ Squash commits
+ Revised comments to fix #5833

**Comment by sdmaclea** [comment]
@dotnet-bot test Tizen armel Cross Release Build please

**Comment by sdmaclea** [comment]
@jashook @jkotas @janvorli Assuming the tizen armel build passes, this is ready to merge

**Comment by sdmaclea** [comment]
On second thought, I see the arm64 runs did not include test.

@dotnet-bot help

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Checked

**Comment by sdmaclea** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by jashook** [comment]
@sdmaclea currently the windows testing seems broken I am looking into it. If I can get it online in a reasonable amount of time I will retry testing and merge.

**Comment by sdmaclea** [comment]
@jashook Thanks, I saw my PR were auto triggering Arm64 builds, but I didn't notice they were not triggering tests.  I am in no hurry.

**Comment by jashook** [comment]
@sdmaclea correct we had removed the tests from the debug build some time ago and removed checked testing (which tests) as a pr trigger. The reasons for doing this have since been obsoleted. @RussKeldorph and I spoke about adding the testing to auto trigger this morning. I have not yet got around to it. I will probably push that to later next week as a heads up.

**Comment by sdmaclea** [comment]
@jashook What is going on with the deleted comment from dotnet-bot?  Twice today I saw that.  This time I notice that the original dotnet-bot message is truncated and no longer shows all the options available to me.  It also shows an incomplete list of auto triggers....

**Comment by jashook** [comment]
Ah I think some of us delete the comments out of habit sorry.

**Comment by sdmaclea** [comment]
No problem.  I can see the original in my inbox.  I was just wondering if we weren't supposed to trigger help

**Comment by jashook** [comment]
No you are good trigger away.

**Comment by sdmaclea** [comment]
@dotnet-bot 
test Ubuntu arm64 Cross Debug Build please
test Windows_NT arm64 Cross Checked Build and Test please

**Comment by sdmaclea** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by sdmaclea** [comment]
@jashook Do we expect Windows_NT arm64 Checked to pass?  I only see two runs in the history.  6/7 run passed.

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by jkotas** [comment]
@sdmaclea Could you please resolve the conflict?

**Comment by sdmaclea** [comment]
Rebased and resolved conflict

**Comment by sdmaclea** [comment]
@dotnet-bot test Tizen armel Cross Release Build

**Comment by sdmaclea** [comment]
Build timeout
@dotnet-bot test Tizen armel Cross Release Build

**Comment by sdmaclea** [comment]
@dotnet-bot test Ubuntu arm64 Cross Debug Build

**Comment by sdmaclea** [comment]
@dotnet-bot test Tizen armel Cross Release Build

**Comment by sdmaclea** [comment]
"Ubuntu arm64 Cross Debug Build" error can be ignored per @jashook , can this be reviewed/merged

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Checked

**Comment by sdmaclea** [comment]
@dotnet-bot test Windows_NT Arm64 Checked

**Comment by sdmaclea** [comment]
The Window AV looks like the same issue we saw when this merged last time and was reverted.  Apparently, there is a bug in the Window Arm64 side of this patch.

**Comment by karelz** [comment]
What is status of this PR? 1 month of no update ...

**Comment by sdmaclea** [comment]
@karelz This is next on my ToDo list.  Windows arm64 build is failing.  Plan to disable Windows portion of the patch and create a separate issue.

**Comment by karelz** [comment]
OK, if it should take you more than 1-2 weeks to get to it, I would suggest to close the PR, while it is inactive. It can be easily reopened when you have time to work on it again. Thanks!

**Comment by sdmaclea** [comment]
@jkotas @dotnet/arm64-contrib I have disabled the optimization on Windows as it was causing a contract Violation.  I opened #13592 to enable.  The disable is a separate patch hopefully to make it easy to reenable, debug ...

**Comment by sdmaclea** [comment]
@jashook @jkotas I have tested this on arm64/unix.  There are several unrelated fails on arm64 tip, see #13593.  This can be reviewed/merged.

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Checked

**Comment by sdmaclea** [comment]
@jashook  Looks like all recent arm64 PRs are failing.

**Comment by sdmaclea** [comment]
@dotnet-bot test Windows_NT Arm64 Checked

**Comment by karelz** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked Build and Test

**Comment by sdmaclea** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked Build and Test

**Comment by sdmaclea** [comment]
@dotnet-bot test Windows_NT Arm64 Checked

**Comment by sdmaclea** [comment]
@jashook @jkotas All tests are passing including Windows_NT arm64 Cross Checked Build and Test.  I have tested [Arm64/Unix] .  Please merge.

**Comment by jashook** [comment]
Thank you!

**Comment by xiangzhai** [comment]
:mips-interest

**Pull request merged**
