### PR TITLE
Fix coredistools download script now that Packages layout has changed

### LINKED ISSUE #18321: setup-stress-dependencies.cmd failing
This is causing x86 GCStress testing to fail.

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_gcstress0xc/

e.g.,

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_gcstress0xc/83/consoleText
```
Downloading CoreDisTools package
"D:\j\workspace\x86_checked_w---e5963ece\tests\..\Tools\dotnetcli\dotnet.exe " restore "D:\j\workspace\x86_checked_w---e5963ece\tests\\src\Common\stress_dependencies\stress_dependencies.csproj" --source https://dotnet.myget.org/F/dotnet-core/ --packages "D:\j\workspace\x86_checked_w---e5963ece\tests\..\Packages"
  Restoring packages for D:\j\workspace\x86_checked_w---e5963ece\tests\src\Common\stress_dependencies\stress_dependencies.csproj...
  Installing Microsoft.NETCore.CoreDisTools 1.0.1-prerelease-00003.
  Generating MSBuild file D:\j\workspace\x86_checked_w---e5963ece\tests\src\Common\stress_dependencies\obj\stress_dependencies.csproj.nuget.g.props.
  Generating MSBuild file D:\j\workspace\x86_checked_w---e5963ece\tests\src\Common\stress_dependencies\obj\stress_dependencies.csproj.nuget.g.targets.
  Restore completed in 1.38 sec for D:\j\workspace\x86_checked_w---e5963ece\tests\src\Common\stress_dependencies\stress_dependencies.csproj.
Locating coredistools.dll
CoreDisTools library path: 
Failed to locate the downloaded library: 
```

### PR DESCRIPTION
**Pull request by RussKeldorph**
Fixes #18321

### CODE REVIEW

**Comment by RussKeldorph** [comment]
@dotnet-bot help

**Comment by RussKeldorph** [comment]
@dotnet-bot test Windows_NT x86 gcstress0xc

**Comment by RussKeldorph** [comment]
@dotnet-bot test Windows_NT x86 checked gcstress0xc

**Comment by RussKeldorph** [comment]
Jenkins went down in the middle of [the GCStress=0xC job](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_gcstress0xc_prtest/70/consoleText), but I verified that it found CoreDisTools as intended:
```
Locating coredistools.dll
CoreDisTools library path: D:\j\workspace\x86_checked_w---344a5564\Packages\microsoft.netcore.coredistools\1.0.1-prerelease-00003\runtimes\win-x86\native\coredistools.dll
```

**Comment by BruceForstall** [comment]
Yes, please merge.

**Pull request merged**
