### PR TITLE
Added UnixEpoch to DateTime and DateTimeOffset.

### PR DESCRIPTION
**Pull request by adriangodong**

### CODE REVIEW

**Comment by adriangodong** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test

**Comment by TylerBrinkley** [comment]
Why not use the `DateTime.TicksTo1970` field? I'd suggest making the field internal and renaming it to `UnixEpochTicks` if possible and then remove the existing `DateTimeOffset.UnixEpochTicks` field as it's identical and use it instead. Also I didn't realize you had started working on this since you hadn't linked the PR to the [proposal](dotnet/corefx#24449).

**Comment by adriangodong** [comment]
Sure, I’ll take a look in a few hours.

**Comment by adriangodong** [comment]
+1 on ticks, not sure on changing `private` -> `internal`. @tarekgh ?

**Comment by tarekgh** [comment]
@adriangodong changing the private static field to internal would be fine.

**Comment by tarekgh** [comment]
CC @safern as we need to monitor the change mirroring to corert

**Comment by TylerBrinkley** [comment]
@tarekgh There's still an existing `DateTimeOffset.UnixEpochTicks` which is identical to `DateTime.TicksTo1970`. Can we rename `DateTime.TicksTo1970` to `DateTime.UnixEpochTicks` and then remove the `DateTimeOffset.UnixEpochTicks` and where ever it's being used switch it to use `DateTime.UnixEpochTicks`?

**Comment by tarekgh** [comment]
@TylerBrinkley yes we can do that. make sure if there is any reference to the old TicksTo1970 will get renamed accordingly. Thanks.

**Comment by adriangodong** [comment]
@tarekgh Can you help me merge this PR? I checked build log, seems to error on webhook but not the build+test.

**Comment by TylerBrinkley** [comment]
@adriangodong are you going to implement the changes @tarekgh okayed regarding renaming to `DateTime.UnixEpochTicks` and removing `DateTimeOffset.UnixEpochTicks` before merging?

**Comment by tarekgh** [comment]
@adriangodong would be nice before merging the change to do the suggestion 

```
Rename DateTime.TicksTo1970 to DateTime.UnixEpochTicks and then remove the DateTimeOffset.UnixEpochTicks and where ever it's being used switch it to use DateTime.UnixEpochTicks
```

**Comment by adriangodong** [comment]
Will do.

**Comment by adriangodong** [comment]
Done! Sorry about the delay, I blanked after the previous commit was pushed and didn't see the change request.

**Comment by tarekgh** [comment]
@adriangodong thank you for finishing this. are you willing to enable this functionality in corefx? we'll need to wait to have coreclr/corert packages built and ported to corefx but we can start preparing the changes in corefx from now

**Comment by adriangodong** [comment]
Yep, I’ve done that before. Hopefully it’ll be smoother this time.

**Comment by tarekgh** [comment]
let me know if you face any issue. I suggest you build your private coreclr bits and then use it when building corefx repo (through the property /p:CoreCLROverridePath) and this should simulate having the coreclr new package porting to corefx.

**Comment by TylerBrinkley** [comment]
Looks like `TicksTo1970` is being used [here](https://github.com/dotnet/corert/blob/2137ae6b870c3f75ce192ab301646a9c6aa305e6/src/System.Private.CoreLib/src/System/DateTime.Unix.CoreRT.cs#L14) in corert so a PR will be needed to fix that to the mirror-merge-9394110 branch before merging to master.

**Comment by tarekgh** [comment]
I pushed the fix to corert

**Comment by tarekgh** [comment]
https://github.com/dotnet/corert/pull/4905

**Pull request merged**
