### PR TITLE
[TEST] Test memory protection issue

### PR DESCRIPTION
**Pull request by janvorli**

### CODE REVIEW

**Comment by janvorli** [comment]
@dotnet-bot test RHEL7.2 pri1

**Comment by janvorli** [comment]
@dotnet-bot test RedHat x64 Release Priority 1 Build & Test please

**Comment by adityamandaleeka** [comment]
@dotnet-bot test RHEL7.2 pri1.

**Comment by janvorli** [comment]
@dotnet-bot test RedHat x64 Release Priority 1 Build & Test please

**Comment by janvorli** [comment]
@dotnet-bot test RedHat x64 Release Priority 1 Build & Test please.

**Comment by janvorli** [comment]
@dotnet-bot test RHEL7.2 pri1.

**Comment by adityamandaleeka** [comment]
@dotnet-bot test RHEL7.2 pri1

**Comment by janvorli** [comment]
@dotnet-bot test RHEL7.2 x64 Release Pri 1 Build & Test please

**Comment by janvorli** [comment]
@dotnet-bot test RHEL7.2 pri1

**Comment by janvorli** [comment]
@dotnet-bot test RHEL7.2 pri1

**Comment by janvorli** [comment]
@dotnet-bot test RHEL7.2 pri1

**Comment by janvorli** [comment]
@dotnet-bot test RHEL7.2 pri1

**Comment by janvorli** [comment]
@dotnet-bot test RHEL7.2 pri1

**Pull request closed without merging**
