### PR TITLE
Fix PreRelease label

### PR DESCRIPTION
**Pull request by gkhanna79**
Currently, the props file forces a specific preRelease label used in versioning. Instead of doing so, rely on the build infrastructure to generate the same.

Post this change, both CoreCLR and JIT packages have "rc2" prerelease label, which comes from the infra, instead of "rc3".

@ericstj PTAL.

CC @pgavlin @russellhadley

### CODE REVIEW

**Comment by pgavlin** [comment]
What's responsible for setting the appropriate envvar? It seems like it would be easy to break this--should/do we take the complete version from the environment and error out if it's not set?

**Comment by gkhanna79** [comment]
@pgavlin The build infrastructure is expected to set it. After removing it, I see the build infra set it to RC2. This will enable us to play well with the build pipeline infrastructure when packages will be produced for RTM with RTM version number as opposed to pre-release set.

> should/do we take the complete version from the environment and error out if it's not set?

It is expected to be set - otherwise nuget packaging (and other such infra) would just break.

**Comment by gkhanna79** [comment]
@ericstj Thoughts on the change?

**Comment by ericstj** [comment]
The expectation is that repos override the value in buildtools.  EG: https://github.com/dotnet/corefx/blob/07d1d36328d414f52cb55d8f3c1b263b0998c468/Packaging.props

**Comment by gkhanna79** [comment]
@ericstj We already have that in our repo for the packages. If the repo overrides with properties like PreRelease, then how would the pre-release version get removed from RTM version of the packages that will be used for shipping?

**Comment by jhendrixMSFT** [comment]
/cc @jhendrixMSFT @wtgodbe @markwilkie 
For RTM milestone I would think a repo would *not* want to override the value indicating that no pre-release suffix should be added yes?

**Comment by ericstj** [comment]
> PreRelease, then how would the pre-release version get removed from RTM version of the packages that will be used for shipping?

We mark packages stable at a more granular level with https://github.com/dotnet/corefx/blob/07d1d36328d414f52cb55d8f3c1b263b0998c468/pkg/Microsoft.Private.PackageBaseline/stable.packages.props.

This allows individual packages to be marked stable and then anytime we see the dependency we'll give it the right marking.

**Comment by gkhanna79** [comment]
Thanks for the explanation @ericstj. My concerns are addressed and I will close this PR.

**Pull request closed without merging**
