### PR TITLE
Add a "GCSimulator" CI run

### PR DESCRIPTION
**Pull request by swgillespie**
This PR adds 432 "GCSimulator" tests, which consist of invoking `GCSimulator` with a variety of different parameters designed to stress the GC. This test run takes about 10 hours on a release build, so I'm aiming to run this weekly.

### CODE REVIEW

**Comment by swgillespie** [comment]
@dotnet-bot test CI please

**Comment by swgillespie** [comment]
@dotnet test CI please

**Comment by mmitche** [comment]
LGTM on netci.groovy changes

**Comment by mmitche** [comment]
@smile21prc PTAL at the groovy changes.

**Comment by swgillespie** [comment]
cc @sergiy-k @wtgodbe

**Comment by wtgodbe** [comment]
Neat! LGTM.

**Comment by sergiy-k** [comment]
LGTM

**Comment by swgillespie** [comment]
@dotnet-bot test CI please

**Pull request merged**
