### PR TITLE
Use CMake's built-in toolchain detection

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Try removing manual resolution of toolchain for non-cross builds and let CMake resolve the toolchain itself.

### CODE REVIEW

**Comment by jkotas** [comment]
@janvorli understands the cmake plumbing

**Comment by janvorli** [comment]
I've looked why we have added the stuff that is now being removed. It comes from the ancient #35 and it looks like it was fixing a problem related to building with clang 3.4 or 3.5. 
But I want to verify that it always picks the same version of the llvm-xxx tools as the clang. I have many llvm versions installed on my Linux box side by side, so I can do that.

**Comment by jkoritzinsky** [comment]
@janvorli sounds good. If you can take a look at that when you have some free cycles that'd be great!

**Comment by janvorli** [comment]
Unfortunately, the results of my testing show this change is problematic. With your change, the cmake variables are set as follows for all versions of clang:
```
CMAKE_AR: /usr/bin/ar
CMAKE_LINKER: /usr/bin/ld
CMAKE_NM: /usr/bin/nm
CMAKE_OBJDUMP /usr/bin/objdump
```
Without your change, the correct llvm versions of the tools are used. Example - clang 4.0:
```
CMAKE_AR: /usr/bin/llvm-ar-4.0
CMAKE_LINKER: /usr/bin/llvm-link-4.0
CMAKE_NM: /usr/bin/llvm-nm-4.0
CMAKE_OBJDUMP /usr/bin/llvm-objdump-4.0
```

**Comment by jkoritzinsky** [comment]
Ah well. Guess this isn’t gonna work without some additional work to preserve the behavior. I’ll close this for now and take another stab at it some time.

**Comment by janvorli** [comment]
It causes the same issue for cross build. For example alpine arm32 build
```
CMAKE_AR: /usr/bin/armv6-alpine-linux-musleabihf-ar
CMAKE_LINKER: /usr/bin/armv6-alpine-linux-musleabihf-ld
CMAKE_NM: /usr/bin/armv6-alpine-linux-musleabihf-nm
CMAKE_OBJDUMP /usr/bin/armv6-alpine-linux-musleabihf-objdump
```
while the state before your change was the same as for x64.

**Pull request closed without merging**
