### PR TITLE
Port #14287 to release/1.1.0

### PR DESCRIPTION
**Pull request by tannergooding**
FYI. @JosephTremoulet

### CODE REVIEW

**Comment by tannergooding** [comment]
Also FYI. @jorive, @AndyAyersMS, and @RussKeldorph

**Comment by tannergooding** [comment]
Ubuntu job failure looks to be machine related:

```
16:28:28 CMake Error at src/ToolBox/SOS/lldbplugin/CMakeLists.txt:49 (message):
16:28:28   Cannot find lldb-3.5, lldb-3.6 or lldb-3.8.  Try installing lldb-3.6-dev
16:28:28   (or the appropriate package for your platform)
```

**Comment by tannergooding** [comment]
test Ubuntu x64 Checked Build and Test please

**Comment by tannergooding** [comment]
@jorive, what do you suggest be done about the error?

It is independent of this change being made.

**Comment by tannergooding** [comment]
test Ubuntu x64 Checked Build and Test please

**Comment by jorive** [comment]
@tannergooding I'm fine with merging this PR if the error is not related to the changes being made (I only realized this PR wasn't merged).

**Comment by tannergooding** [comment]
@jorive, merging. The normal commit jobs are failing with the same error:
Ex: https://ci.dot.net/job/dotnet_coreclr/job/release_1.1.0/job/checked_ubuntu_flow/145/console

**Pull request merged**
