### PR TITLE
Rename "MultiplyHorizontalAdd_ro.cmd_12141" to "Popcnt_r.cmd_12141"

### PR DESCRIPTION
**Pull request by echesakovMSFT**
Fix Windows_NT arm64 tests exclusion list

### CODE REVIEW

**Comment by echesakovMSFT** [comment]
test Windows_NT arm64 Cross Checked normal Build and Test
test Windows_NT arm64 Cross Release normal Build and Test

**Comment by fiigii** [comment]
Thanks for the work. This was a mistake from my PR https://github.com/dotnet/coreclr/pull/20173

**Comment by echesakovMSFT** [comment]
test Windows_NT arm Cross Checked Innerloop Build and Test
test Windows_NT arm64 Cross Checked Innerloop Build and Test
test Windows_NT arm64 Cross Checked normal Build and Test
test Windows_NT arm64 Cross Release normal Build and Test

**Comment by echesakovMSFT** [comment]
test Windows_NT arm Cross Checked Innerloop Build and Test
test Windows_NT arm64 Cross Checked Innerloop Build and Test
test Windows_NT arm64 Cross Checked normal Build and Test
test Windows_NT arm64 Cross Release normal Build and Test

**Pull request closed without merging**
