### PR TITLE
Add fedora24 native packages

### PR DESCRIPTION
**Pull request by mellinoe**
Same as the previous PR for Ubuntu 16.10 and openSUSE 42.1, but this time for Fedora 24.

### CODE REVIEW

**Comment by mellinoe** [comment]
Added another commit: Allows Fedora 24 to build using MSBuild.

**Comment by jasonwilliams200OK** [comment]
@mmitche, Gentoo also builds CoreCLR, can it also have a build worker (maybe inactive by default and only run on demand)?

Steps to build CoreCLR and CoreFX on Gentoo: https://gist.github.com/jasonwilliams200OK/1a2e2c0e904ffa95faf6333fcd88d9b8

**Comment by mmitche** [comment]
@jasonwilliams200OK We can simply put an image in the store that builds it and will get spun up when needed.

**Comment by jasonwilliams200OK** [comment]
That would be really nice to have @mmitche! AFAIR, Gentoo was one of the Future goal that used to be documented in CoreCLR's Wiki by @richlander (since the docs are reorganized from Wiki to source-tree, that future plan section is missing). :)

**Pull request merged**
