### PR TITLE
Update arm CI to follow up corefx changes

### PR DESCRIPTION
**Pull request by hqueue**
Update coreclr CI for arm/armel cross to follow up changes in corefx CI (https://github.com/dotnet/corefx/issues/21135).

This will fix build break in following coreclr CI legs 
- Ubuntu arm Cross Release Build
- Ubuntu16.04 arm Cross Debug Build

### CODE REVIEW

**Comment by hqueue** [comment]
@dotnet-bot help

**Comment by hqueue** [comment]
@dotnet-bot test ci please

**Comment by hqueue** [comment]
@dotnet-bot please test Ubuntu arm Cross Release Build
@dotnet-bot please test Ubuntu16.04 arm Cross Debug Build

**Comment by hqueue** [comment]
@dotnet-bot please test Ubuntu x64 Formatting

**Comment by hqueue** [comment]
@dotnet-bot test ci please

**Comment by hqueue** [comment]
@weshaggard I've update coreclr CI for arm to follow up corefx changes.

/cc: @weshaggard @jashook  @BruceForstall  @gkhanna79 PTAL

**Comment by weshaggard** [comment]
LGTM thanks for fixing @hqueue. I didn't realize these were so tightly coupled. Sorry for breaking.

**Comment by hqueue** [comment]
@weshaggard Thank you for merging :)
And I also should have prepared this PR earlier when https://github.com/dotnet/corefx/issues/21135 was being discussed.

**Pull request merged**
