### PR TITLE
Enable the stack-protector compiler option for all coreclr code on Unix.

### PR DESCRIPTION
**Pull request by sergiy-k**

### CODE REVIEW

**Comment by janvorli** [comment]
LGTM

**Comment by sergiy-k** [comment]
@dotnet-bot test this please

**Comment by sergiy-k** [comment]
@dotnet-bot test this please

**Comment by sergiy-k** [comment]
@dotnet-bot test this please

**Comment by sergiy-k** [comment]
@dotnet-bot test this please

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by sergiy-k** [comment]
Apparently there is a bug in the compiler on OS X that causes incorrect code generation. On OSX x64 Release I see this:

```
(lldb) disassemble -n Compiler::gtFoldExprConst
libcoreclr.dylib`Compiler::gtFoldExprConst:
    0x101410870 <+0>:    pushq  %rbp
    0x101410871 <+1>:    movq   %rsp, %rbp
    0x101410874 <+4>:    pushq  %r15
    0x101410876 <+6>:    pushq  %r14
    0x101410878 <+8>:    pushq  %r13
    0x10141087a <+10>:   pushq  %r12
    0x10141087c <+12>:   pushq  %rbx
    0x10141087d <+13>:   subq   $0xd8, %rsp
    0x101410884 <+20>:   movq   0x1ded7d(%rip), %rax      ; (void *)0x00007fff7c959070: __stack_chk_guard
    0x10141088b <+27>:   movq   (%rax), %rax
    0x10141088e <+30>:   movq   %rax, -0x30(%rbp)
    0x101410892 <+34>:   movq   %rdi, -0x50(%rbp)
    0x101410896 <+38>:   movq   %rsi, -0x58(%rbp)
    0x10141089a <+42>:   movq   -0x50(%rbp), %r14
    0x10141089e <+46>:   movq   -0x58(%rbp), %rdi
    0x1014108a2 <+50>:   callq  0x101418690               ; GenTree::OperKind() const
    0x1014108a7 <+55>:   leaq   0x2181aa(%rip), %rcx      ; FieldSeqStore::s_notAField
    0x1014108ae <+62>:   movl   %eax, -0x5c(%rbp)
    0x1014108b1 <+65>:   movq   %rcx, -0xb8(%rbp)
    0x1014108b8 <+72>:   movq   -0x58(%rbp), %rdi
    0x1014108bc <+76>:   callq  0x1014186c0               ; GenTree::AsOpRef()
    0x1014108c1 <+81>:   movq   %rax, %r12     <===== this the last place where r12 is updated

...
check at the end of the function:

    0x1014128b6 <+8262>: movq   -0x30(%rbp), %rcx <===== load the stack guard
    0x1014128ba <+8266>: subq   %rcx, %r12    <===== r12 does not contain correct value here
    0x1014128bd <+8269>: jne    0x1014128c1               ; <+8273>
    0x1014128bf <+8271>: jmp    0x1014128c6               ; <+8278>
    0x1014128c1 <+8273>: callq  0x101530ade               ; symbol stub for: __stack_chk_fail

```
This causes the stack check to fail. I need to see if I can disable optimizations for this function to workaround the problem.

**Comment by sergiy-k** [comment]
I have changed the code to use “-fstack-protector” instead of “-fstack-protector-strong” on OS X in order to work around a bug in clang (current version 7.0.2).

**Pull request merged**
