### PR TITLE
Move CoreCLR to the modern build tools and dnx

### PR DESCRIPTION
**Pull request by mmitche**
This changes moves coreclr onto DNX (same version as corefx).  Theoretically, this should allow these tests to target the desktop CLR.  All of the old package.config files are gone and replaced with corresponding project.json files.  The up front restore behavior is retained.  Tests are now buildable individually, though not runnable in a similar fashion.

### CODE REVIEW

**Comment by pgavlin** [comment]
LGTM, but please squash your commits.

**Comment by jasonwilliams200OK** [comment]
:+1: 
(wow 3131 files! I mistakenly clicked on `Files` tab in IE11, it jammed the whole window!) :smile_cat:

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by jasonwilliams200OK** [comment]
:+1: 
@mmitche does this also cover the changes made in 1144?

**Comment by mmitche** [comment]
@jasonwilliams200OK Unfortunately no, I kept getting test failures with an Od coreclr but have not had time to look into them.

**Pull request merged**
