### PR TITLE
Add a documentation link to the missing resources exception messages

### PR DESCRIPTION
**Pull request by tarekgh**
Add a documentation link to the missing resources exception messages

The link would include more information regarding what can cause this exception to help developers diagnose and fix it. Note, the link is pointing at the exception documentation and we have a tracking doc issue https://github.com/dotnet/docs/issues/10031 to capture the needed information there.

### CODE REVIEW

**Comment by tarekgh** [comment]
CC @nguerrera @danmosemsft @rpetrusha

**Comment by tarekgh** [comment]
CC @krwq

**Comment by jkotas** [comment]
> Add a documentation link to the missing resources exception messages

What is special about `MissingManifestResourceException` that it deserves an explicit link to the docs for the exception?

**Comment by tarekgh** [comment]
@jkotas 

> What is special about MissingManifestResourceException that it deserves an explicit link to the docs for the exception?

The issue https://github.com/dotnet/corefx/issues/34190 has more details. basically, we want to add some more details to the docs to help users to diagnose teh missing resources issue. The issue https://github.com/dotnet/docs/issues/10031 is tracking enhancing the documentation which we are pointing at in the exception message.

**Comment by jkotas** [comment]
This does not explain why we want to do this for MissingManifestResourceException, but not to the hundred other exceptions that we have in the framework. The docs for every other exception contain troubleshooting tips. For example, take a look at FileLoadException - that is way more common than MissingManifestResourceException.

I do not think that adding links for exceptions manually scales well, and it clutters the message.

What is the experience that you are to improve? If you want to streamline the experience to get from the exception to the docs, would it be better to work with VS to turn the exception name in the unhandled exception message into a link?

image

**Comment by tarekgh** [comment]
@nguerrera could you answer @jkotas question as you are the one requested to have this?

**Comment by danmosemsft** [comment]
I think it would be great if that was a link, but that is not a short term solution. My impression was that the request was for a temporary, tactical way to address a common stumbling block we are seeing as customers port to Core, not a long term approach.

**Comment by danmosemsft** [comment]
I agree it is super ugly and if there is some better way to alleviate this stumbling block that is great.

**Comment by krwq** [comment]
I'm fine with the link assuming we do that elsewhere

**Comment by nguerrera** [comment]
> would it be better to work with VS to turn the exception name

That would be great though it won't help non-VS users. Ideally, we'd think about the experience for all IDEs and for all circumstances where the exception info appears. 

> Of course if the link only goes to the existing documentation for the exception it has little value since anyone can find that. My impression was that someone proposed to write a document.

Yes, the hope is that this would point to a document explaining how resource names are chosen in the build and what to do when the name chosen is not what your code elsewhere is expecting.

Mind you, if we had excellent exception -> exception doc navigation, then we could just put a prominent link to such a document on the exception doc page.

I personally think it is OK to have links for a few commonly misunderstood exception messages without a general system. But I don't feel strongly enough about this to push hard on it.. I also sympathize with not wanting to do something one-off. If we decide not to take this, we can instead focus on good SEO from exception type and message to this information.

**Comment by nguerrera** [comment]
^ @davkean Who would we talk to about better navigation from exceptions to docs in VS

**Comment by tarekgh** [comment]
I am closing this PR as we'll not add a link to the exception message and instead we can add some more info to the message as suggested in the comment https://github.com/dotnet/corefx/issues/34190#issuecomment-492375044

**Pull request closed without merging**
