### PR TITLE
Disable Perf Runs on Commit

### PR DESCRIPTION
**Pull request by adiaaida**
We need to disable these jobs on commit until https://github.com/dotnet/core-eng/issues/2808 is fixed.

### CODE REVIEW

**Comment by adiaaida** [comment]
@dotnet-bot test ci please

**Comment by jorive** [comment]
Is there anything we need to disable PR perf runs too?

**Comment by adiaaida** [comment]
PRs are only on comments, so they're off by default anyway.

**Comment by jorive** [comment]
OK, I thought we enable it to always run on PR.

**Comment by DrewScoggins** [comment]
test ci please

**Comment by DrewScoggins** [comment]
LGTM

**Pull request merged**
