### PR TITLE
Preserve Marshal.GetLastWin32Error in SafeHandle.DangerousRelease

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
This piece of logic was missed during the unmanaged->managed rewrite. It may cause PInvokes to return bogus last errors.

I found this issue while looking for potential causes for https://github.com/dotnet/corefx/issues/35351. However, do not have a good exact explanation how this bug can lead to https://github.com/dotnet/corefx/issues/35351

cc @stephentoub @wfurt

**Comment by stephentoub** [comment]
Thanks, Jan! I've been trying to track down the root cause of https://github.com/dotnet/corefx/issues/35493... wondering now if this is related. Will try...

**Comment by stephentoub** [comment]
Still need to test it, but I expect it is the root cause. If the TransmitFile operation completed asynchronously but very quickly, the continuation could Dispose of the safe handle used in the p/invoke before the p/invoke returned, and then the DangerousRelease would cause the non-zero error code from TransmitFile to become zero.

**Comment by wfurt** [comment]
thanks @jkotas . This is also probably root cause for the recent ping failures.

**Pull request merged**
