### PR TITLE
Fix opinfo: InlineR should only read 8 bytes

### PR DESCRIPTION
**Pull request by sunnycase**
This must be a typo.

### CODE REVIEW

**Comment by jkotas** [comment]
Used by ildasm
cc @RussKeldorph

**Comment by RussKeldorph** [comment]
This appears to be almost dead code since as far as I can tell it's only used in `DEBUG` builds and only if you force `ildasm`'s global `g_fPrettyPrint` to `TRUE`, e.g. by changing [this](https://github.com/dotnet/coreclr/blob/3f4e0c7d2a281c2232fde6421b4a9fc18e889eac/src/ildasm/dasm.cpp#L94) line.

At any rate, I verified that the intended functionality is currently broken when dealing with `InlineR`s and is fixed by this change, so it looks good to me.  Thanks for the fix!

**Comment by RussKeldorph** [comment]
@dotnet-bot test this please

**Comment by RussKeldorph** [comment]
@dotnet-bot test this please

**Comment by jkotas** [comment]
@dotnet-bot test Windows_NT x64 Checked CoreFX Tests please
@dotnet-bot test Windows_NT x64 Release CoreFX Tests please

**Pull request merged**
