### PR TITLE
Do not rerun LVA if only live-out has changed.

### PR DESCRIPTION
**Pull request by pgavlin**
If only the live-out set for a block changes during live variable
analysis, the LVA algorithm does not need to be re-run. As per the
dataflow equations for LVA:

    liveOut(block) = union(liveIn(s) for all s in successors(block))

Thus, unless a change to the live-out set for a block propagates through
to a change to the live-in set for that block, it will not affect the
live-in/out sets of any of its predecessors and liveness need not be
re-run.

### CODE REVIEW

**Comment by pgavlin** [comment]
@CarolEidt @sivarv @dotnet/jit-contrib PTAL.

SuperPMI reports no diffs for this change.

**Comment by CarolEidt** [comment]
| SuperPMI reports no diffs for this change.

Did you run diffs for the other desktop targets?

**Comment by pgavlin** [comment]
> Did you run diffs for the other desktop targets?

No. I've kicked them off now.

**Comment by sivarv** [comment]
Looks good.
You might want to measure throughput to see if it has improved.

**Comment by pgavlin** [comment]
@CarolEidt: jitAsmDiffs also reports no diffs.

**Comment by CarolEidt** [comment]
> jitAsmDiffs also reports no diffs.

Thanks for checking!

**Comment by mikedn** [comment]
> You might want to measure throughput to see if it has improved.

Last I checked liveness performance wasn't significant so it's unlikely that this would change anything.

**Pull request merged**
