### PR TITLE
[Arm/Arm64] LowerCast remove small int widen cast

### PR DESCRIPTION
**Pull request by sdmaclea**
This is not expected to modify code generation.  It is simply a code cleanup.

@dotnet/jit-contrib @dotnet/arm32-contrib @dotnet/arm64-contrib PTAL

### CODE REVIEW

**Comment by sdmaclea** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by sdmaclea** [comment]
All tests have passed including Windows_NT Arm64 Checked.  This can be reviewed/merged

**Comment by sdmaclea** [comment]
Adding a comment will trigger a new CI check

**Comment by sdmaclea** [comment]
Looks like every "Windows_NT armlb Cross Checked Build and Test" test is failing with "No output was generated!". Looks like an unrelated CI issue.

@briansull If you are willing to ignore the CI issues, this can be merged too

**Comment by briansull** [comment]
OK I will merge this PR

**Pull request merged**
