### PR TITLE
Add runtimeconfig.json support for tiered compilation

### PR DESCRIPTION
**Pull request by noahfalk**

### CODE REVIEW

**Comment by noahfalk** [comment]
cc @kouvel @4creators

**Comment by RussKeldorph** [comment]
@dotnet-bot help

**Comment by RussKeldorph** [comment]
@dotnet-bot test Linux-musl x64 Debug Build

**Comment by noahfalk** [comment]
@dotnet-bot test Ubuntu x64 Formatting
@dotnet-bot test Windows_NT x64 Formatting
@dotnet-bot test CentOS7.1 x64 Checked Innerloop Build and Test

**Comment by noahfalk** [comment]
@dotnet-bot test Alpine.3.6 x64 Debug Build

**Pull request merged**
