### PR TITLE
Simplify next command output for build-test.sh

### PR DESCRIPTION
**Pull request by BruceForstall**

### CODE REVIEW

**Comment by BruceForstall** [comment]
I am trying to reduce the duplication of first echoing the command line, then invoking it, especially when the command lines are long. Also, I am reducing the super long command lines, especially related to msbuild logging, by constructing them in steps, as is done in build.cmd/build-test.cmd.

**Comment by BruceForstall** [comment]
Any suggestion for additional testing?

**Comment by jashook** [comment]
Unfortunately the only additional testing would be manual.

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Checked normal Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked normal Build and Test
@dotnet-bot test OSX10.12 x64 Checked Build and Test
@dotnet-bot test CentOS7.1 x64 Checked Build and Test

**Pull request merged**
