### PR TITLE
Remove useless security checks

### PR DESCRIPTION
**Pull request by stephentoub**
Replaces https://github.com/dotnet/coreclr/pull/2830.  Simply rebases on top of the latest master and squashes the commits.

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test this please

(lots of errors like:
07:27:29 EXEC : error : FindPackagesById: xunit.abstractions [d:\j\workspace\dotnet_coreclr\x86_release_windows_nt_prtest\tests\build.proj]
07:27:29     Response status code does not indicate success: 404 (Not Found).)

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
Test Ubuntu x64 Checked Build and Test please

(build timeout)

**Comment by jkotas** [comment]
Opened issue https://github.com/dotnet/coreclr/issues/3064 to get this removed again.

**Pull request merged**
