### PR TITLE
Add Test Cases for FSharp

### PR DESCRIPTION
**Pull request by KevinRansom**
The Jit Guys break F# on a fairly regular basis, because only FSharp uses the .tail command, and tail call optimizations are our bread and butter.

This PR contains a wide range of FSHarp Test Cases, containing a large set od scenarios.

on my mac book the test cases take between 3-5 to run.

To build use the dotnet cli, I usually use the following command, this builds and runs for net46, and netcoreapp2.0.

````
dotnet test FSharp.Core.UnitTests.fsproj /v:verbose
````

This builds and runs the tests, and dumps a spew of tests while they are executing.

On the MAC use:
````
dotnet test FSharp.Core.UnitTests.fsproj /v:normal -c release -f netcoreapp2.0
````

The project loads in Visual Studio, and the tests use xunit and can be used with test explorer.

Note:  I have a Tests.Builds.props and targets checked in to unhook my project from your build.

I expect that you can fairly easily wire this into your build and test infrastructure.  Note that buildtools drops a fairly recent dotnet cli which contains an F# compiler.

/CC  @briansull , @brettfo, @ericstj 

Let me know if you have any questions

Kevin

I'm guessing someone from your team

### CODE REVIEW

**Comment by jkotas** [comment]
This is duplicating ~100,000 lines from FSharp repo. It is pretty large source code duplication.

Would it be better to publish a NuGet package with FSharp tests binaries instead and make the CoreCLR test runs consume it?

**Comment by jkotas** [comment]
We have the general need to run other projects tests in CoreCLR, e.g. running ASP.NET tests would be pretty useful too for some PRs. We need to have a scallable way to do that - we cannot affort to xcopy  100,000 line worth of tests into CoreCLR repo for each such project.

**Comment by KevinRansom** [comment]
@jkotas, we certainly can consider doing it that way.  My preference would be to deliver test binaries in a nuget package for you to run.  There really is no reason for you to actually build this stuff.

**Comment by jkotas** [comment]
I think this can be closed for now.

**Pull request closed without merging**
