### PR TITLE
[Arm64] Update GCHeap::GetValidGen0MaxSize

### PR DESCRIPTION
**Pull request by sdmaclea**
Arm64 does not provide GetLargestOnDieCacheSize() info and used a
fixed 256KB size for gen0size.  This is too small.  For comparison,
AMD64 is currently using 3*GetLargestOnDieCacheSize() for the
maximum gen0size for each heap in GCServer mode.  This can easily be
100x 256KB.

Provide alternate mechanism to calculate GetValidGen0MaxSize().
Calculate based on fair share of physical memory per processor
per process per gen0 heap.

### CODE REVIEW

**Comment by sdmaclea** [comment]
@dotnet/arm64-contrib @Maoni0 @swgillespie PTAL

Fixes excess GC which was root cause of #12640

**Comment by Maoni0** [comment]
`size_t physMemPerProcessor = GCToOSInterface::GetPhysicalMemoryLimit() / GCToOSInterface::GetTotalProcessorCount();`

what are the common ranges of physical memory and process counts? wanna get an idea what this size looks like. if I think something similar to amd64 machines I normally see, the gen0 size based on this calculation can be huge.

**Comment by sdmaclea** [comment]
@Maoni0 I set the number to be similar to my older SkyLake desktop.  SkyLake has 8MB on die cache and sets maxGen0Size to 24MB (1.5 * (1 << 24) in GCServer=1 mode.  

For mobile phone or tablet processor a common 2017 config would be 4GB of memory and 8 processors.  This would lead to a maxGen0Size of 16MB (1 << (32 - 3 - 3 -2)).  This gen0 size would represent **1/256th** of physical memory.

For a server Physical memory increases somewhat proportional to processor count.  I happen to have a server configured with ~1GB per CPU leading to ~32MB gen0 size. 

The disadvantage of having an excessive gen0size might be poor cache utilization.  As long as GC runs regularly and compacts, large maximum GC size should have insignificant cost to system performance.

**Comment by sdmaclea** [comment]
For reference the ASP.NET plaintext benchmark creates 50MB of garbage per second on SkyLake.  This would lead to 2Hz GC.

**Comment by sdmaclea** [comment]
@Maoni0 1MB largest on die cache per CPU would also be a reasonable estimate for current CPUs.  My SkyLake desktop has 8 Hyper threads and 8MB largest on die cache.  This leads to 24MB as gen0size.  Arm64 is/will be in roughly the same size range.

The reason I did not choose this estimate as it is likely to get stale every few years as CPU technology moves.  Estimating gen0size based on physical memory seemed better.  As ultimately that was the resource that was being wasted by larger sizes.  

There is also some cache utilization loss for small objects as cache line may be partially filled with garbage.  Periodic GC should fix the cache losses.

**Comment by sdmaclea** [comment]
Ubuntu arm64 failure is a CI issue.  Please ignore and review/merge

**Comment by Maoni0** [comment]
@sdmaclea would it be possible for you to implement GetLargestOnDieCacheSize? :-) Our current implementation was provided by various hardware companies so if you could provide the implementation for arm64 that'd be awesome.

**Comment by sdmaclea** [comment]
@janvorli FYI 

@Maoni0 The problem with GetLargestOnDieCacheSize() is the arm64 ISA does not expose that to user space apps.  The Linux kernel also does not expose that info.  Windows kernel TBD, might just work.

Philosophically each arm64 vendor could provide vendor specific cache size info based on MIDR .  There are currently 11 such vendors registered in the ARM64 ARM Reference Manual.  Each one will have 0 or more parts.  For Qualcomm Datacenter Technologies we do not publish cache size info before parts are released, so there would need to be a reasonable default.  Especially if we want to use releases of CoreCLR on new parts.

Here are simple reasonable options to implement GetLargestOnDieCacheSize(), but they do violate the return 0 requirement for "unknown size"
- I could make a heuristic implementation which returned 1MB * Number CPUs (or if available cpus in numa group)
- I could make an environment variable
- On Linux I could return heuristic, implementer is exposed, so each vendor could provide precise or imprecise info/heuristic.  Windows might not have an issue at all.

**Comment by sdmaclea** [comment]
Abandoned in favor of #13071

**Pull request closed without merging**
