### PR TITLE
Open source even more threading tests

### PR DESCRIPTION
**Pull request by adityamandaleeka**
This is the last of the giant ports of threading tests. There are now 350 new tests in baseservices/threading.

### CODE REVIEW

**Comment by stephentoub** [comment]
It's great to see more tests coming online.  Thanks, @adityamandaleeka.

What's our plan, though, for whether the tests live in corefx or coreclr?  I thought our high-level goal was for tests of public surface are to live in corefx?

cc: @jkotas

**Comment by adityamandaleeka** [comment]
@stephentoub 

As of now, it hasn't been finalized where the tests should live long-term (coreclr, corefx, or something else like a standalone repo). For now, everyone involved in this porting effort is adding tests in coreclr while that gets decided.

cc: @sergiy-k as well

**Comment by jkotas** [comment]
It was agreed upon a long time ago that tests for surface area should live in corefx repo, next to the contracts that they are testing. I have reminded folks about it multiple times. This guidance was violated in name of expediency since the start of CoreCLR test porting effort by being driven by raw numbers of tests only. I have done a random sampling of non-codegen tests in coreclr repo a couple of weeks ago. I found that more than 40% of these tests have same (literally) or improved copy in corefx repo, so there is a lot of redundancy. This should be cleaned up once we have time for it.

I see a number of tests that are testing surface that is either not supported by .NET Core (e.g. threadabort), or implemented and tested in corefx (e.g. readerwriterlockslim). Could you please at least delete these from your batch?

**Comment by adityamandaleeka** [comment]
@dotnet-bot retest this please

**Comment by wtgodbe** [comment]
@dotnet-bot test this please

**Comment by adityamandaleeka** [comment]
Looks like there is a real error, but I'm not sure why. I'm able to build the test (and run buildtest.cmd) just fine on my machine (even after deleting the packages directory and all the test binaries to make sure there's no caching going on).

```error CS0103: The name 'ThreadPool' does not exist in the current context [d:\j\workspace\x86_lb_releas---8c318281\tests\src\baseservices\threading\monitor\enter\monitorenter.csproj]```

**Comment by akoeplinger** [comment]
@adityamandaleeka ThreadPool is in the `System.Threading.ThreadPool` nuget package which isn't mentioned in project.json of the test.

**Comment by wtgodbe** [comment]
@adityamandaleeka I was able to repro this manually on my machine - I got several errors of the same type as the one you mentioned, I would guess they're all related to the same issue suggested by @akoeplinger .

`MonitorEnter.cs(92,9): error CS0103: The name 'ThreadPool' does not exist in the current context [C:\Users\wigodbe\Docu
ments\GithubFork\adit\coreclr\tests\src\baseservices\threading\monitor\enter\monitorenter.csproj]
MultiInstance.cs(177,26): error CS1061: 'Assembly' does not contain a definition for 'EntryPoint' and no extension meth
od 'EntryPoint' accepting a first argument of type 'Assembly' could be found (are you missing a using directive or an a
ssembly reference?) [C:\Users\wigodbe\Documents\GithubFork\adit\coreclr\tests\src\baseservices\threading\multiinstance\
multiinstance.csproj]
437017.cs(30,13): error CS0246: The type or namespace name 'RegisteredWaitHandle' could not be found (are you missing a
 using directive or an assembly reference?) [C:\Users\wigodbe\Documents\GithubFork\adit\coreclr\tests\src\baseservices\
threading\regressions\beta2\437017.csproj]
437017.cs(30,88): error CS0246: The type or namespace name 'WaitOrTimerCallback' could not be found (are you missing a
using directive or an assembly reference?) [C:\Users\wigodbe\Documents\GithubFork\adit\coreclr\tests\src\baseservices\t
hreading\regressions\beta2\437017.csproj]
437017.cs(30,40): error CS0103: The name 'ThreadPool' does not exist in the current context [C:\Users\wigodbe\Documents
\GithubFork\adit\coreclr\tests\src\baseservices\threading\regressions\beta2\437017.csproj]
200176.cs(16,36): error CS0246: The type or namespace name 'WaitCallback' could not be found (are you missing a using d
irective or an assembly reference?) [C:\Users\wigodbe\Documents\GithubFork\adit\coreclr\tests\src\baseservices\threadin
g\regressions\whidbey_m3\200176.csproj]
200176.cs(16,3): error CS0103: The name 'ThreadPool' does not exist in the current context [C:\Users\wigodbe\Documents\
GithubFork\adit\coreclr\tests\src\baseservices\threading\regressions\whidbey_m3\200176.csproj]
BindHandle1.cs(33,25): error CS0103: The name 'ThreadPool' does not exist in the current context [C:\Users\wigodbe\Docu
ments\GithubFork\adit\coreclr\tests\src\baseservices\threading\threadpool\bindhandle\bindhandle1.csproj]
BindHandleInvalid.cs(22,13): error CS0103: The name 'ThreadPool' does not exist in the current context [C:\Users\wigodb
e\Documents\GithubFork\adit\coreclr\tests\src\baseservices\threading\threadpool\bindhandle\bindhandleinvalid.csproj]
BindHandleInvalid3.cs(34,21): error CS0103: The name 'ThreadPool' does not exist in the current context [C:\Users\wigod
be\Documents\GithubFork\adit\coreclr\tests\src\baseservices\threading\threadpool\bindhandle\bindhandleinvalid3.csproj]
BindHandleInvalid4.cs(29,21): error CS0103: The name 'ThreadPool' does not exist in the current context [C:\Users\wigod
be\Documents\GithubFork\adit\coreclr\tests\src\baseservices\threading\threadpool\bindhandle\bindhandleinvalid4.csproj]
BindHandleInvalid5.cs(35,21): error CS0103: The name 'ThreadPool' does not exist in the current context [C:\Users\wigod
be\Documents\GithubFork\adit\coreclr\tests\src\baseservices\threading\threadpool\bindhandle\bindhandleinvalid5.csproj]
BindHandleInvalid6.cs(35,29): error CS0103: The name 'ThreadPool' does not exist in the current context [C:\Users\wigod
be\Documents\GithubFork\adit\coreclr\tests\src\baseservices\threading\threadpool\bindhandle\bindhandleinvalid6.csproj]
BindHandleInvalid6.cs(51,21): error CS0103: The name 'ThreadPool' does not exist in the current context [C:\Users\wigod
be\Documents\GithubFork\adit\coreclr\tests\src\baseservices\threading\threadpool\bindhandle\bindhandleinvalid6.csproj]
CtorChk.cs(15,38): error CS0246: The type or namespace name 'ThreadPool' could not be found (are you missing a using di
rective or an assembly reference?) [C:\Users\wigodbe\Documents\GithubFork\adit\coreclr\tests\src\baseservices\threading
\threadpool\ctorchk\ctorchk.csproj]
BindHandleNull.cs(19,13): error CS0103: The name 'ThreadPool' does not exist in the current context [C:\Users\wigodbe\D
ocuments\GithubFork\adit\coreclr\tests\src\baseservices\threading\threadpool\bindhandle\bindhandlenull.csproj]
Unregister01.cs(28,9): error CS0246: The type or namespace name 'RegisteredWaitHandle' could not be found (are you miss
ing a using directive or an assembly reference?) [C:\Users\wigodbe\Documents\GithubFork\adit\coreclr\tests\src\baseserv
ices\threading\threadpool\unregister\unregister01.csproj]
Regression_749068.cs(27,9): error CS0246: The type or namespace name 'RegisteredWaitHandle' could not be found (are you
 missing a using directive or an assembly reference?) [C:\Users\wigodbe\Documents\GithubFork\adit\coreclr\tests\src\bas
eservices\threading\threadpool\unregister\regression_749068.csproj]
Unregister03.cs(28,9): error CS0246: The type or namespace name 'RegisteredWaitHandle' could not be found (are you miss
ing a using directive or an assembly reference?) [C:\Users\wigodbe\Documents\GithubFork\adit\coreclr\tests\src\baseserv
ices\threading\threadpool\unregister\unregister03.csproj]
threadstatic07.cs(80,36): error CS0246: The type or namespace name 'WaitCallback' could not be found (are you missing a
 using directive or an assembly reference?) [C:\Users\wigodbe\Documents\GithubFork\adit\coreclr\tests\src\baseservices\
threading\threadstatic\threadstatic07.csproj]
threadstatic07.cs(80,3): error CS0103: The name 'ThreadPool' does not exist in the current context [C:\Users\wigodbe\Do
cuments\GithubFork\adit\coreclr\tests\src\baseservices\threading\threadstatic\threadstatic07.csproj]
threadstatic07.cs(83,36): error CS0246: The type or namespace name 'WaitCallback' could not be found (are you missing a
 using directive or an assembly reference?) [C:\Users\wigodbe\Documents\GithubFork\adit\coreclr\tests\src\baseservices\
threading\threadstatic\threadstatic07.csproj]
threadstatic07.cs(83,3): error CS0103: The name 'ThreadPool' does not exist in the current context [C:\Users\wigodbe\Do
cuments\GithubFork\adit\coreclr\tests\src\baseservices\threading\threadstatic\threadstatic07.csproj]`

**Comment by adityamandaleeka** [comment]
Thanks @akoeplinger and @wtgodbe. I'm not sure why these failures don't reproduce locally, but I've including the ThreadPool reference in all the project.json files for the projects in the error output pasted above.

**Comment by wtgodbe** [comment]
@adityamandaleeka looks like you're still getting errors - 

`MultiInstance.cs(177,26): error CS1061: 'Assembly' does not contain a definition for 'EntryPoint' and no extension meth od 'EntryPoint' accepting a first argument of type 'Assembly' could be found (are you missing a using directive or an a ssembly reference?) [C:\Users\wigodbe\Documents\GithubFork\adit\coreclr\tests\src\baseservices\threading\multiinstance\ multiinstance.csproj]`

But at least the ThreadPool ones seem to be gone. I'm building locally now, I'll let you know what errors are still there.

**Comment by wtgodbe** [comment]
Huh - I couldn't repro the error locally this time. That is bizarre.

**Comment by adityamandaleeka** [comment]
The error about `EntryPoint` seems to indicate that the CI build is not using the requested version of the reference assembly when building. I took a look in the CoreFX repo at [System.Reflection.cs](https://github.com/dotnet/corefx/blob/master/src/System.Reflection/ref/System.Reflection.cs) and `EntryPoint` seems to have been exposed in October.

The version of the reference assembly used when I build locally is 4.1.0-beta-23516 (as requested in the project.json), and ILDASM shows the `EntryPoint` definition as expected. I'm not sure which version the CI build is using, but I suspect that it's using something much older. 

I tried searching in the console output for the build on Jenkins but couldn't find anything about which System.Reflection.dll was used. Does anyone know how to determine that and/or why it would choose to ignore the version specified in the project.json file?

**Comment by adityamandaleeka** [comment]
@dotnet-bot Windows_NT x64 Debug Build and Test

**Comment by adityamandaleeka** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test

**Comment by adityamandaleeka** [comment]
I've looked at the two failures in x86 Release, and think it may be a real runtime bug.

The tests that are failing do the following:

```c#
        try
        {
            WaitHandle.WaitAll(wh);
        }
        catch(ArgumentException)
        {
            ...
        }
        catch(Exception e)
        {
            ...
        }
```
and we crash with `Unhandled Exception: System.ArgumentException: Value does not fall within the expected range.`

I looked at `CorWaitMultipleNative` and its callees, and the source of the exception is in `Thread::DoAppropriateWaitWorker` (vm/threads.cpp, near line 4495):

```c++
    if (ret == WAIT_FAILED)
    {
        DWORD errorCode = ::GetLastError();
        if (errorCode == ERROR_INVALID_PARAMETER)
        {
            if (CheckForDuplicateHandles(countHandles, handles))
                COMPlusThrow(kDuplicateWaitObjectException);
            else
                COMPlusThrowHR(HRESULT_FROM_WIN32(errorCode));  /////// <--------- here is where we throw
        }
```

The thrown exception appears to be handled properly on everything except x86 release. I haven't looked into all the exception handling code to understand why this is occurring yet.

**Comment by sergiy-k** [comment]
Please disable the failing tests, open an issue to track the failures, merge your pull request once everything is green.

**Comment by adityamandaleeka** [comment]
@dotnet-bot test Windows_NT x86 Release Legacy Backend Build and Test

**Comment by adityamandaleeka** [comment]
@dotnet-bot test Windows_NT x86 Release Legacy Backend Build and Test

**Comment by adityamandaleeka** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test

**Comment by adityamandaleeka** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test

**Pull request merged**
