### PR TITLE
Fix a race condition in the test build

### LINKED ISSUE #7762: Test build error: The process cannot access the file '[...]\Managed\GC\Stress\Tests\StressAllocator\StressAllocator.exe' because it is being used by another process.
For example:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_release_windows_nt_pri1_prtest/1152/console

```
15:52:41 D:\j\workspace\x64_release_w---0575cb46\Tools\sign.targets(70,5): error : 
D:\j\workspace\x64_release_w--
-0575cb46\bin\int\Managed\GC\Stress\Tests\StressAllocator\StressAllocator.exe: I/O error reading or 
writing PE file: The process cannot access the file 'D:\j\workspace\x64_release_w--
-0575cb46\bin\int\Managed\GC\Stress\Tests\StressAllocator\StressAllocator.exe' because it is being used by another process. [D:\j\workspace\x64_release_w--
-0575cb46\tests\src\GC\Stress\Tests\StressAllocator.csproj]
```

Also seen as:

```
16:39:01 D:\j\workspace\x64_release_w---0575cb46\Tools\sign.targets(70,5): error : 
D:\j\workspace\x64_release_w--
-0575cb46\bin\int\Managed\GC\Stress\Tests\ThdTreeGrowingObj\ThdTreeGrowingObj.exe: PE file is 
already strong-name signed. [D:\j\workspace\x64_release_w--
-0575cb46\tests\src\GC\Stress\Tests\ThdTreeGrowingObj.csproj]
```

Perhaps there's some sort of race condition when building these tests.

### PR DESCRIPTION
**Pull request by swgillespie**
Both `ReliabilityFramework.csproj` and each individual stress test's `csproj` are registered to build as a part of the Pri 1 test build. Since `ReliabilityFramework.csproj` contains references to each individual test's project and builds them, there can be multiple builds of the test projects occurring at the same time, which can result in concurrent build errors. This ensures that `ReliabilityFramework.csproj` is solely responsible for the building of test assets. Fixes #7762

### CODE REVIEW

**Comment by ramarag** [comment]
by removing the Buildonly tag you are making the  test project as BuildAndRun [that't the default]
instead i would suggest you add something like 

<DisableProjectBuild Condition=" ' $(BuidinForReliabilitiyFramework)' == '' ">true</DisableProjectBuild> into a tests\src\GC\Stress\dir.targets file 

and set BuidinForReliabilitiyFramework to be true in tests\src\GC\Stress\Framework\ReliabilityFramework.csproj

**Comment by swgillespie** [comment]
@ramarag thanks! I'll give that a try.

**Comment by swgillespie** [comment]
@ramarag PTAL again? I made a change to the top level `dir.targets` because it seemed that the conditional for `BuildAllProjects` was off and forced my disabled projects to build anyway. I think the lack of quotes around the `true` in the `BuildAllProjects` conditional made it always reject the condition.

**Comment by ramarag** [comment]
i don't think you need to modify the top level targets file. Do let me know what is the exact problem you are facing. There are already projects using DisableProjectBuild to disable them

**Comment by swgillespie** [comment]
@ramarag So without the changes to the top level targets, the tests in `GC\Stress\Tests` still compile, despite having `DisableProjectBuild` set in their properties (this is from the output of msbuild /v:diag):

```
DisableProjectBuild = true
_WillCLRTestProjectBuild = true
BuildAllProjects = false
```

I'm looking at the top-level dirs.targets here:

```xml
  <PropertyGroup> 
    <BuildAllProjects Condition=" '$(BuildAllProjects)' == ''">false</BuildAllProjects>
    <_WillCLRTestProjectBuild Condition="'$(_WillCLRTestProjectBuild)' == ''">false</_WillCLRTestProjectBuild>
    <_WillCLRTestProjectBuild Condition="'$(BuildAllProjects)' != true">true</_WillCLRTestProjectBuild>
    <_WillCLRTestProjectBuild Condition="'$(DisableProjectBuild)' != true And '$(BuildAllProjects)' == true And '$(CLRTestPriority)' &lt;= '$(CLRTestPriorityToBuild)'">true</_WillCLRTestProjectBuild>
  </PropertyGroup>
```

The first binding to `_WillCLRTestProjectBuild` will initialize it to false, the second one sets it to true if `BuildAllProjects` is not true (which it isn't), and the last one will set it to true if DisableProjectBuild is not true, BuildAllProjects is true, and the priority is within the priority being built. This seems to me that it will always be true, because `BuildAllProjects` is false. Perhaps I'm misunderstanding what MSBuild is doing here?

**Comment by swgillespie** [comment]
@ramarag I verified that with the last commit this works for my scenario. I ended up moving the `dir.targets` into `GC\Stress\Tests` because it was also preventing `GC\Stress\Framework` from building.

**Comment by ramarag** [comment]
LGTM

**Comment by swgillespie** [comment]
@ramarag thanks for the help!

**Pull request merged**
