### PR TITLE
Fast Append one StringBuilder to other

### PR DESCRIPTION
**Pull request by AlexRadch**
I suggest add methods to fast append one StringBuilder to other. https://github.com/dotnet/corefx/issues/4928

Advantage:
1. If possible it do not copy buffers from one StringBuilder to other. Instead of copy, it share buffers between two or more StringBuilders. For shared buffers if set m_ChunkCopyOnChange flag.
2. Shared buffers reduce processor time and reduce memory consumption also.

Disadvantage:
1. Shared buffers should be copped before changing (see  m_ChunkCopyOnChange flag). So all methods that changing buffers should be rewritten to do such copy before buffer changing.
2. For fast appending it can create gaps between chunks when chunks in middle can be not fully fill up. m_ChunkLength can be less than m_ChunkChars.Length in middle chunks. It is cost for fast appending.

Usual StringBuilder use cases perform only append operations, so shared buffers will not be copied, just shared. Now appending one StringBulider to other perform coping two times.

### CODE REVIEW

**Comment by danmosemsft** [comment]
@AlexRadch please track this in https://github.com/dotnet/corefx/issues/4928. Let's let that API proposal develop. Also, we track all managed code issues in the corefx repo.

**Comment by AlexRadch** [comment]
@danmosemsft , I did not find in corefx repo any StringBuilder class code.

**Comment by danmosemsft** [comment]
@AlexRadch it is a little confusing. We track all managed code issues [even issues in mscorlib/System.Private.Corelib](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/adding_new_public_apis.md) in the corefx repo. This keeps everything together even when we move types and implementations between those and CoreFX proper.

Incidentally reference assemblies for everything are in CoreFX and all the tests (eg src\System.Runtime\tests\System\Text\StringBuilderTests.cs). To write tests against changes in CoreCLR one must wait for a new drop to be ingested which can take anything from a few hours to a few days.

**Comment by danmosemsft** [comment]
BTW you couldn't have known this -- and many thanks for your contributions so far.

**Pull request closed without merging**
