### PR TITLE
1. Change the coreclr perf run script to .sh type instead of .ph.

### PR DESCRIPTION
**Pull request by smile21prc**
2. Add a few debugging statements for Jenkens run debugging.
3. Fixed the usage of the script.

### CODE REVIEW

**Comment by smile21prc** [comment]
@adityam 

Hi Aditya, this is the pull request containing the file type change and a few debugging statements. We don't need to wait for the check run results as the script won't affect any of them.

**Comment by adityamandaleeka** [comment]
@smile21prc 

I don't see the change to the py file in this PR. The branch you're pushing from isn't synced with the commit you pushed directly into dotnet:master, so I guess you should rebase this branch and then rename the file. If it's committed as is, we'll have both copies in the repo.

As for the script itself, most of it appears to be a copy of what's in runtest.sh. Would it make sense to just call runtest from this script and have it do the overlay building and stuff that you need? That way, any changes to that logic would only need to happen in one place, and this script could focus on the parts that are exclusive to these perf runs.

cc: @wtgodbe

**Comment by smile21prc** [comment]
@adityam

Sure, I'll rebase this branch to get sync with dotnet/coreclr and then make commit on top of that.

Concerning the reuse of runtest.sh, the problem of calling it in my script is, runtest.sh doesn't provide a switch that can only generate the coreoverlay dir (the logic I need) without running the tests on Linux. And its test running part hang Jenkins Linux machine in ALL recent runs (see http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_checked_ubuntu_gcstress15_pri1r2r_tst/ for an example).

That's why I have to split out the coreoverlay generation part into my perf run script to avoid hanging Jenkins machine even before executing coreclr perf tests.

**Comment by adityamandaleeka** [comment]
@smile21prc I believe this PR might be adding the switch you're looking for: https://github.com/dotnet/coreclr/pull/6807

BTW, feel free to add another switch if there's some other part of the runtest.sh functionality you want to be able to call without having it actually run everything.

**Comment by smile21prc** [comment]
@adityam

Thanks for the info Aditya -- that's exactly what I need, and good timing as well. I'll comment on that one to ask him merge it ASAP so I can use it.

**Pull request closed without merging**
