### PR TITLE
[x86/Linux] Fix cannot jump from this goto statement to its label

### PR DESCRIPTION
**Pull request by seanshpark**
Fix compile error for x86/Linux
- move variable declaration before jump
- fix "cannot jump from this goto statement to its label"

### CODE REVIEW

**Comment by seanshpark** [comment]
cc @parjong

**Comment by seanshpark** [comment]
@janvorli , formatting error logs shows this but I don't know how to fix this. Can you please help?
```
clang-format: there are formatting errors in /mnt/j/workspace/dotnet_coreclr/master/x64_ubuntu_formatting_prtest/src/jit/codegenlegacy.cpp
05:26:42 At Line 459 Before:
05:26:42     bool setFlags = (tree != NULL) && tree->gtSetFlags();
05:26:42 After:
05:26:42     bool     setFlags = (tree != NULL) && tree->gtSetFlags();
05:26:42 At Line 460 Before:
05:26:42     insFlags flags = INS_FLAGS_DONT_CARE;
05:26:42 After:
05:26:42     insFlags flags    = INS_FLAGS_DONT_CARE;
05:26:42 At Line 6955 Before:
05:26:42     regMaskTP addrReg = genMakeRvalueAddressable(op2, RBM_ALLINT, RegSet::KEEP_REG, isSmallConst);
05:26:42 After:
05:26:42     regMaskTP addrReg     = genMakeRvalueAddressable(op2, RBM_ALLINT, RegSet::KEEP_REG, isSmallConst);
05:26:42 At Line 6956 Before:
05:26:42     bool op2Released = false;
05:26:42 After:
05:26:42     bool      op2Released = false;
05:26:42 At Line 6957 Before:
05:26:42     emitAttr opSize = EA_UNKNOWN;
05:26:42 After:
05:26:42     emitAttr  opSize = EA_UNKNOWN;
05:26:42 At Line 6957 Before:
05:26:42     emitAttr  opSize = EA_UNKNOWN;
05:26:42 After:
05:26:42     emitAttr  opSize      = EA_UNKNOWN;
05:26:42 
05:26:42 Clang-format found formatting errors.
```

**Comment by seanshpark** [comment]
@dotnet-bot test Ubuntu x64 Formatting please

**Comment by janvorli** [comment]
@dotnet/jit-contrib can one of you help figure out the formatting problem here? I am not familiar with the output of the formatting error and it looks quite strange.

**Comment by adiaaida** [comment]
@janvorli download https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_windows_nt_formatting_prtest/538/artifact/format.patch and run git apply format.patch

**Comment by janvorli** [comment]
@adiaaida thank you for the advice. @seanshpark can you please do that?

**Comment by seanshpark** [comment]
Problem of this PR has been fixed with #8337.

**Pull request closed without merging**
