### PR TITLE
Use the "open" key for strong-name signing SOS.NETCore.dll.

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
Switch to using the OSS strong name instead of the default MSFT one.

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
@weshaggard please take a look.
@mikem8361, @gkhanna79 FYI

**Comment by gkhanna79** [comment]
LGTM

**Comment by mikem8361** [comment]
LGTM

**Comment by weshaggard** [comment]
LGTM

**Pull request merged**
