### PR TITLE
Strip symbols on release builds into separate binaries

### PR DESCRIPTION
**Pull request by mikem8361**
Issue #3669

Created a common cmake strip_symbols function that all the modules and programs
use to strip the symbols out of the main into a separate .dbg (Linux) or .dSYM (OSX)
file.

Added an install_clr cmake function to encapsulate the install logic.

Changed all the library module cmake install lines from a TARGETS to a FILES one. The
TARGETS based install directives caused cmake to relink the binary and copy the unstripped
version to the install path. Left the all programs like corerun or ildasm as TARGETS
installs because on OSX FILES type installs don't get marked as executable.

Need to use "get_property(strip_source_file TARGET ${targetName} PROPERTY LOCATION)" for
the older versions of cmake and "set(strip_source_file $<TARGET_FILE:${targetName}>)" on
newer versions (v3 or greater).

### CODE REVIEW

**Comment by mikem8361** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Comment by mikem8361** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Comment by ellismg** [comment]
You will want to remove my commit (7022fc9) from this, as we need to keep RC3 as the pre-release specifier in master.

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mikem8361** [comment]
I don’t understand. My PR is in release/1.0.0-rc2 the branch.

**Comment by mikem8361** [comment]
Oops, I was wrong.  I created this PR in master and I meant it to be in release/1.0.0-rc2.

From: Mike McLaughlin
Sent: Tuesday, March 22, 2016 5:14 PM
To: 'dotnet/coreclr' <reply@reply.github.com>; dotnet/coreclr <coreclr@noreply.github.com>
Subject: RE: [coreclr] Strip symbols on release builds into separate binaries (#3865)

I don’t understand. My PR is in release/1.0.0-rc2 the branch.

**Comment by ellismg** [comment]
Github doesn't let you change the target of a PR, without opening a new one.  So closing this up.

**Pull request closed without merging**
