### PR TITLE
Permit to inject additional CMake arguments via environment variables

### PR DESCRIPTION
**Pull request by krytarowski**
Introduce new variable `CMAKE_ARGS_EXTRA` settable during `build.sh` call.

### CODE REVIEW

**Comment by krytarowski** [comment]
If you think that there is a cleaner way to do it, please let me know. An alternative would be to reuse `$cmake_extra_defines`.

**Comment by janvorli** [comment]
@krytarowski Could you please explain the motivation for this change?

**Comment by krytarowski** [comment]
I've integrated CoreCLR (and CoreRT, CoreFX) with pkgsrc -- the portable package framework which originated from NetBSD http://pkgsrc.org/ 

The pkgsrc framework uses custom paths and is prepared to be hosted on a POSIX-similar (BSD, Cygwin, Darwin, Haiku, Interix, Linux, Minix, SunOS etc) host with minimal dependencies - compiler and basic tools -- while the rest is satisfied from the its own packages. For example Perl and Python are owned by pkgsrc and they don't interfere (to some extend) with system-wide resources. The default path for prebuilt pkgsrc packages is `/usr/pkg` (or `/opt/pkg` on recent MacOSX due to `El Captain`) for privileged user (`root`) or `$HOME/pkg` for unprivileged.

To make this all work, we need to inject customized configure and build environment variables, as well as customized configure parameters (for `GNU`-like configure or `CMake`, or `waf` or similar).

I'm currently calling `build.sh` this way:

```
do-build:
        ${RUN} cd ${WRKSRC} && \
        ${PKGSRC_SETENV} ${CONFIGURE_ENV} CMAKE_ARGS_EXTRA=${CMAKE_ARGS:Q} PYTHON=${PYTHONBIN:Q} ./build.sh
```

Where on my system (`NetBSD`) in my configuration:
- `PKGSRC_SETENV` evaluates to `/usr/bin/env`
- `CONFIGURE_ENV` evaluates to `PTHREAD_CFLAGS= -pthread  PTHREAD_LDFLAGS= -pthread PTHREAD_LIBS= PTHREADBASE=/usr DL_CFLAGS= -pthread  DL_LDFLAGS= -pthread DL_LIBS= INSTALL_INFO= MAKEINFO=/tmp/pkgsrc-tmp/wip/coreclr-git/work/.tools/bin/makeinfo FLEX= BISON= PKG_CONFIG= PKG_CONFIG_LIBDIR=/tmp/pkgsrc-tmp/wip/coreclr-git/work/.buildlink/lib/pkgconfig:/tmp/pkgsrc-tmp/wip/coreclr-git/work/.buildlink/share/pkgconfig PKG_CONFIG_LOG=/tmp/pkgsrc-tmp/wip/coreclr-git/work/.pkg-config.log PKG_CONFIG_PATH= MAKE=make WRAPPER_DEBUG=no WRAPPER_UPDATE_CACHE=yes PYTHON=/usr/pkg/bin/python2.7 CC=gcc CFLAGS=-O2 -g -ggdb -I/usr/pkg/include -I/usr/include CPPFLAGS=-I/usr/pkg/include -I/usr/include CXX=c++ CXXFLAGS=-O2 -g -ggdb -I/usr/pkg/include -I/usr/include -g -ggdb COMPILER_RPATH_FLAG=-Wl,-R F77=g77 FC=g77 FFLAGS=-O LANG=C LC_ALL=C LC_COLLATE=C LC_CTYPE=C LC_MESSAGES=C LC_MONETARY=C LC_NUMERIC=C LC_TIME=C LDFLAGS=-L/usr/pkg/lib -Wl,-R/usr/pkg/lib -L/usr/lib -Wl,-R/usr/lib LINKER_RPATH_FLAG=-R PATH=/tmp/pkgsrc-tmp/wip/coreclr-git/work/.wrapper/bin:/tmp/pkgsrc-tmp/wip/coreclr-git/work/.buildlink/bin:/tmp/pkgsrc-tmp/wip/coreclr-git/work/.gcc/bin:/tmp/pkgsrc-tmp/wip/coreclr-git/work/.tools/bin:/usr/pkg/bin:/home/kamil/.cabal/bin:/home/kamil/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R7/bin:/usr/X11R6/bin:/usr/pkg/bin:/usr/pkg/sbin:/usr/games:/usr/local/bin:/usr/local/sbin:/usr/pkg/bin:/usr/X11R7/bin PREFIX=/usr/pkg MAKELEVEL=0 PKG_SYSCONFDIR=/usr/pkg/etc HOME=/tmp/pkgsrc-tmp/wip/coreclr-git/work/.home`
- `CMAKE_ARGS` evaluates to `-DPYVERSSUFFIX:STRING=2.7 -DCMAKE_INSTALL_PREFIX:PATH=/usr/pkg -DCMAKE_MODULE_PATH:PATH=/tmp/pkgsrc-tmp/wip/coreclr-git/work/.buildlink/cmake-Modules -DCMAKE_SKIP_RPATH:BOOL=TRUE -DCMAKE_INSTALL_LIBDIR:PATH=lib -DCMAKE_INSTALL_MANDIR:PATH=man`

Please note the `:Q` symbol, it means in the BSD `make`(1) enabling escaping to queries (so we don't need to round it with additional apostrophes or similar).

While I can pass environment variables easily during incovation of `build.sh`, I require a helper to pass arguments to the `CMake` call. Otherwise the package won't work properly.

NB. Some variables are overridden by `build.sh`, like `CC`/`CXX`. Which is for now good enough. In future build.sh should respect these variables set by end-user -- please don't worry, `CC` will be set to `clang` in the package. The same applies for the number of threads to build application -- this is user-settable, and I will propose an environment variable to pass it via `env`, similarly like the `Python` executable path (`python2.7` for us)

**Comment by krytarowski** [comment]
Currently CoreCLR resides in `pkgsrc-wip` (work-in-progress packages): https://wip.pkgsrc.org/cgi-bin/gitweb.cgi?p=pkgsrc-wip.git;a=tree;f=coreclr-git Once released, it will be packages for the main `pkgsrc` repository.

**Comment by janvorli** [comment]
@krytarowski Thanks a lot for the detailed explanation!
Regarding passing the extra parameters, I wonder, would it work for you to pass the options you now have in the CMAKE_ARGS_EXTRA as a command line parameter to the build.sh and then pass it through to the gen-buildsys-clang.sh as a command line parameter too? I would prefer it that way so that we don't need to use env variables.

**Comment by krytarowski** [comment]
Currently we pass these additional trailing parameters for a make tool (it might be `make` or `ninja`) and they are different than those required for `CMake`. At the moment I'm not aware of a cleaner way to handle it - except decomposition `build.sh` into three of four invocations: `configure`, `build` and `install` (optionally `test`).

NB. The same patch has to be applied for the other core .Net projects.

**Comment by krytarowski** [comment]
A nit: I don't know if it matters for `CMake`, but the canonical way to pass options in Unix is to pass them before the file/path-name.

**Comment by janvorli** [comment]
I think I am confused by your reply. You have shown above that the CMAKE_ARGS evaluate to a bunch of command line options for Cmake. You put those to CMAKE_ARGS_EXTRA env variable and then run build.sh, which in turn calls gen-buildsys-clang.sh. And that one extracts them again from the CMAKE_ARGS_EXTRA env variable and passes them to cmake.
So it seemed to me that passing them as a command line option to the build.sh, which would then pass it as another command line option to the gen-buildsys-clang.sh would be functionally equivalent. I don't understand why would it require splitting the build.sh into separate invocations. I think I must be missing something.

**Comment by krytarowski** [comment]
Ah, do you mean something like:
`build.sh cmake-params=-DCMAKE_SKIP_RPATH:BOOL=TRUE`

I was thinking about so called `__UnprocessedBuildArgs` passed to `-DCMAKE_SKIP_RPATH:BOOL=TRUE`.

It's now clear. What's your proposed command-line parameter? We can do the same for the Python executable path and make-jobs later as well.

**Comment by janvorli** [comment]
Right, now we are on the same page. My idea on the option name is cmakeextraargs or cmakeargs. (we have dotnetclipath option in the corert build.sh named using this convention).
And instead of using =, use a space separator. This is what the corert uses:
```bash
        -dotnetclipath) 
            shift
            __dotnetclipath=$1
```

**Comment by krytarowski** [comment]
Just asking, how about general name `config[ure]args`? Just in case the project will be moved into another build-system.

**Comment by janvorli** [comment]
The configure seems too abstract. But I get your point. How about buildtoolargs?

**Comment by krytarowski** [comment]
`buildtoolargs` sounds to me like for a `make` invocation.

**Comment by krytarowski** [comment]
I think we can settle with `cmakeargs`, as they are `CMake` specific anyway. I'm going to prepare a patch.

**Comment by janvorli** [comment]
Ok, thanks. I was trying to figure out some other name, but I have no more ideas.

**Comment by jasonwilliams200OK** [comment]
@krytarowski, environment variable:

```sh
KEY=VALUE ./build.sh
```

vs.  argument list

```sh
./build.sh key=value
```

I have seen argument list being a preferred approach in dotnet family projects.

In coreclr, the env vars are considered as 'external knobs' (term from repo docs).

We can either have both ways: argument list and external knobs; or the argument list if only one approach is desired.

My hunch was correct. :wink:

**Comment by krytarowski** [comment]
Done!

**Comment by krytarowski** [comment]
There are the same changes waiting to be uploaded for CoreFX and CoreCLR.

**Comment by jasonwilliams200OK** [comment]
:+1: 

We need the same addition in CoreFX. For the time begin, I have locally added a hard coded path in CoreFX to deliver the patches.

@janvorli, can you please take a look again and advise if there is anything we need to fix here? Thanks.

**Comment by janvorli** [comment]
LGTM

**Pull request merged**
