### PR TITLE
Revising raw demo instructions

### PR DESCRIPTION
**Pull request by bgribaudo**
Changes made:
* Revised package version to reflect versions currently available from the MyGet (most versions previously listed were no longer available). Removed a couple unnecessary packages.
* Fixed command line for... statement so that it works with paths containing spaces and doesn't accidentally copy reference assemblies. Adjusted filter to reflect that this is .Net Core, not ASP Net Core.
* Added NETCore.Runtime.ApiSets-x64 package and copying instructions so that the tutorial works for Windows 7 users.
* Minor edits, including formatting adjustments and a spelling fix.

### CODE REVIEW

**Comment by jkotas** [comment]
LGTM Thanks for updating the documentation!

cc @richlander

**Comment by bgribaudo** [comment]
Thanks, @jkotas! Would you be open to my proposing some re-writing of that page to make it clearer and more informative?

**Comment by jkotas** [comment]
Absolutely. Documentation improvements are very welcomed.

**Comment by richlander** [comment]
Yup. We did an initial push on these instructions and have been a bit focussed on other things. This is definitely an opportunity for collaboration.

**Pull request merged**
