### PR TITLE
Enable /guard:cf only on Release builds

### PR DESCRIPTION
**Pull request by BruceForstall**
Many people in the JIT team (and others?) have experienced problems
with debug/checked builds and /guard:cf. Perhaps there is an incremental
build problem with /guard?

However, we don't need the protection for debug/checked builds. So
stop building using /guard:cf for those builds, to avoid this problem.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@janvorli @jkotas @dotnet/jit-contrib PTAL

**Comment by jkotas** [comment]
cc @morganbr

**Comment by morganbr** [comment]
@BruceForstall, please don't make this change. If you're hitting a guard failure in a debug build, it's a sign of a potential security problem that we should catch as early as possible.

**Comment by pgavlin** [comment]
> If you're hitting a guard failure in a debug build, it's a sign of a potential security problem that we should catch as early as possible.

Thus far our investigations have indicated otherwise: many of these appear to be difficult-to-reproduce issues with CFG itself, especially in incremental builds. One of our most recent issues was a CFG failure that only happened after an incremental build even if the contents of the source files had not changed (e.g. if a build was performed after `touch`ing a file).

**Comment by jkotas** [comment]
@pgavlin Was it with the latest C++ compiler (Dev15.3)? There used to be bugs like this in the older C++ compiler, but I believe that they got fixed.

**Comment by pgavlin** [comment]
> Was it with the latest C++ compiler (Dev15.3)? There used to be bugs like this in the older C++ compiler, but I believe that they got fixed.

@sandreenko and @BruceForstall may be able to answer that question.

**Comment by sandreenko** [comment]
When I met this problem I tried both VS2015 and the last preview of 2017. Both had this problem.

**Comment by jkotas** [comment]
Are the C++ compiler folks aware of it and going to fix it?

**Comment by BruceForstall** [comment]
Ian was not aware of any bugs in this area; he was surprised to hear it. (He's the one who asked why we bother to do this for debug builds). If we could generate a repro, I suppose that would help. But repros are very hard to come by. However, I see no need to penalize our development process for this.

**Comment by jkotas** [comment]
If Ian is aware of the problems, I am fine with the change.

**Comment by mikedn** [comment]
> Perhaps there is an incremental build problem with /guard?

But do we do incremental builds? The debug/checked builds are full of warnings like `LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/OPT:REF' specification`.

Also, AFAIR Windows itself had an issue with /guard:cf, presumably that's fixed these days so the issue is really in the compiler? I haven't encountered any issues with /guard:cf lately, there use to be some tests that failed on some Win 10 builds but that doesn't happen anymore on the latest Win 10 insider preview build.

**Comment by BruceForstall** [comment]
I'm going to close this for now.

**Pull request closed without merging**
