### PR TITLE
Properly check return value of OpenProcessToken()

### PR DESCRIPTION
**Pull request by maksqwe**
Return type of OpenProcessToken() is BOOL.

### CODE REVIEW

**Comment by jkotas** [comment]
There are commented out LGTM

@mmitche @sergiy-k Could you please check why the Linux build is failing? It does not seem to be related to this change.

**Comment by jkotas** [comment]
LGTM

@mmitche @sergiy-k Could you please check why the Linux build is failing? It does not seem to be related to this change.

**Comment by shahid-pk** [comment]
@jkotas 
these are some tests failing probably related to this #161

**Comment by poizan42** [comment]
What about these tests?
```
/mnt/j/workspace/dotnet_coreclr_linux_release_prtest/binaries/CMake/src/pal/tests/palsuite/threading/CreateProcessA/test1/paltest_createprocessa_test1
GetCurrentDirectory call failed.  Could not get current working directory
.  Exiting.
```

and

```
/mnt/j/workspace/dotnet_coreclr_linux_release_prtest/binaries/CMake/src/pal/tests/palsuite/threading/CreateProcessW/test1/paltest_createprocessw_test1
GetCurrentDirectory call failed.  Could not get current working directory
.  Exiting.
```

**Comment by mmitche** [comment]
I added the PAL tests into the Linux PR test last night.  Looks like they pass for debug but not for release @sergiy-k Can you take a look?

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Pull request merged**
