### PR TITLE
Fix a segfault in perf map generation

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Make sure instance vars get initialized to nullptr.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@brianrob PTAL

**Comment by adityamandaleeka** [comment]
LGTM. One minor comment: it looks like those two files both use NULL everywhere but you've added nullptrs. In the interest of consistency, can you change everything to nullptr?

**Comment by AndyAyersMS** [comment]
Sure, I'll update.

I am seeing some other strange behavior from `/CreatePerfMap` (eg creating zero length files). Might just be user error, but I'm going to investigate and make sure this isn't caused by my change.

**Comment by brianrob** [comment]
I'm actually a bit surprised that you saw seg faults, just because we've been using this code a bunch lately and haven't seen it.  Did you experience this with crossgen /CreatePerfMap or was this during program execution when the runtime emits the perf-%pid.map file?

**Comment by AndyAyersMS** [comment]
This was with crossgen of mscorlib, on ubuntu.

**Comment by brianrob** [comment]
LGTM

**Comment by brianrob** [comment]
cc: @Lucrecious

**Comment by AndyAyersMS** [comment]
Updated with more `nullptr`.

**Comment by brianrob** [comment]
@adityamandaleeka, are we standardizing on nullptr instead of NULL?  I don't necessarily want to ask @AndyAyersMS to change everything back to NULL, but want to understand which direction we're going.

**Comment by AndyAyersMS** [comment]
OSX same pal test failure I've seen elsewhere:
```
00:16:18.451 .............ERROR: Failed to delete "testfile".
00:16:18.453  Error is 170
00:16:18.453 
00:16:18.453 
00:16:18.453 FAILED: c_runtime/_wfopen/test6/paltest_wfopen_test6. Exit code: 1
```
Will retry I suppose.

@dotnet-bot retest OSX x64 Checked Build and Test

**Comment by AndyAyersMS** [comment]
Now ubuntu failing a test:
```
00:12:54.854 FAILED   - GC/Scenarios/LeakWheel/leakwheel/leakwheel.sh
```
almost certainly unrelated to this change.

@dotnet-bot retest Ubuntu x64 Checked Build and Test

**Comment by adityamandaleeka** [comment]
@brianrob My comment about NULL/nullptr was more about consistency than which is more correct. All the nulls in the code @AndyAyersMS added were nullptr, while the existing code in those files used NULL.

As for a concerted effort around standardizing throughout the codebase, I don't think there is one. We already have both NULL and nullptr scattered throughout. Personally, when I make any significant changes in a file, I've been using nullptr everywhere and changing the surrounding code to match.

**Comment by AndyAyersMS** [comment]
@dotnet-bot retest  FreeBSD x64 Checked Build

**Comment by AndyAyersMS** [comment]
@brianrob Let me know about the NULL vs nullptr thing. 

FWIW I agree with @adityamandaleeka, now that there's a language-standard concept for null pointers we should use it.

**Comment by jkotas** [comment]
LGTM

**Pull request merged**
