### PR TITLE
Fix GetProcessAffinityMask

### LINKED ISSUE #22961: return correct pmask when there are multiple NUMA nodes on linux
on Linux we need to return the correct pmask when there are multiple NUMA nodes on machines with > 64 cores. discussion is on issue #22861 starting [here](https://github.com/dotnet/coreclr/pull/22861#issuecomment-468807720).

### PR DESCRIPTION
**Pull request by janvorli**
The function was returning mask not expected by runtime for coreclr
built with NUMA enabled on machines with multiple NUMA nodes.
The mask was 0 in case the current process was affinitized to CPUs
from multiple NUMA nodes. It was following MSDN doc, however the
doc turned out to be ambiguous. Moreover, the runtime depended
on the fact that on Windows, a process is never run on multiple
NUMA nodes unless is explicitly calls APIs to set ideal processor
for threads. But on Unix, there is no such case and by default, a
process is affinitized to all existing processors over all NUMA
nodes.

And there was one more issue. The GetProcessAffinityMask was returning
a mask within a single CPU group, which is a transformed view of
NUMA node on Windows. So the CPU indices in the mask didn't necessarily
correspond to the native Unix CPU indices. But, the SetThreadAffinityMask
was using the native Unix CPU indices.

To fix the problem, the GetProcessAffinityMask is changed so that
it always returns a mask corresponding to the native Unix CPU indices
(reporting upto 64 processors as the mask is 64 bit wide). Thus it
corresponds to what the SetThreadAffinityMask expects. And it also exactly
matches the behavior when NUMA support is not compiled in.
Moreover, the COMPlus_GCHeapAffinitizeMask bits now correspond to
the native Unix CPU indices.

The GetProcessAffinityMask is used by GC and thread pool only when
NUMA is not enabled using the COMPlus_GCCpuGroup env variable.

Close #22961

### CODE REVIEW

**Comment by janvorli** [comment]
CC: @vkvenkat, @sergiy-k

**Comment by janvorli** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test please

**Comment by jkotas** [comment]
Known test failures (https://github.com/dotnet/coreclr/issues/23262)

**Comment by vkvenkat** [comment]
@janvorli I just tested this on my 96 core Linux machine. The smask is set to 0 in `GetFullAffinityMask` because of an overflow (1 is left shifted 64 times and KAFFINITY is only 8 bytes long). A bigger datatype may be needed here.

**Pull request merged**
