### PR TITLE
User the PR trigger email for benchview submit

### PR DESCRIPTION
**Pull request by adiaaida**
When users trigger perf runs for PRs, the alias used to submit in
submission-metadata.json should be that user's email. We should only
use dotnet-bot for official runs.

### CODE REVIEW

**Comment by adiaaida** [comment]
@dotnet-bot test ci please

**Comment by adiaaida** [comment]
@dpodder I'll change it to how we use ghprbPullTitle/BenchviewCommitName.

**Comment by adiaaida** [comment]
@dotnet-bot test ci please

**Comment by adiaaida** [comment]
@dpodder PTAL

**Comment by jkotas** [comment]
@adiaaida All jobs are failing with:

```
16:58:14 [2017-08-28 16:58][ERROR] <class 'ValueError'>: Specified submission-metadata json file "D:\j\workspace\perf_perflab_---89ec9f56\submission-metadata.json" does not exist.
```

It started around this PR was committed.

Could you please take a look?

**Comment by dpodder** [comment]
@jkotas thanks for raising this; @dotnet/rap-team is taking a look

**Comment by dpodder** [comment]
Bug should be fixed (but we need to wait until new PRs open to really validate).
Existing PRs that failed can be fixed by re-triggering the failed leg. (This actually works around the original bug, even before the fix went in.)

**Comment by adiaaida** [comment]
Thanks Daniel, for fixing that.

**Pull request merged**
