### PR TITLE
Span Slice method AggressiveInlining

### PR DESCRIPTION
**Pull request by ahsonkhan**
[MethodImpl(MethodImplOptions.AggressiveInlining)]

### CODE REVIEW

**Comment by ahsonkhan** [comment]
cc @jkotas good to go?

**Comment by jkotas** [comment]
There are more methods in span.cs that should be marked:

- `public ref T GetItem(int index)` , also delete the link to the issue that is fixed now
- Constructor that takes `void*`
- ...

**Comment by ahsonkhan** [comment]
> also delete the link to the issue that is fixed now
Has the issue been resolved? public T this[int index] does not return ref T still.

**Comment by jkotas** [comment]
You are right - I thought that it is link to the issue with the GC crash.

**Pull request merged**
