### PR TITLE
Port from 5.0: Fix Position Independent Code in CMake files

### PR DESCRIPTION
**Pull request by ivdiazsa**
# Port Description

This is a direct port from PR #26323 in this same repo. This one was added during .NET Core 5.0 development but there is a customer need to also have it in the .NET Core 3.1 release.

In summary, the `-pie` linker option was missing and while the code was being compiled as Position Independent, the executables weren't, and therefore ASLR was not applied to them. This resulted in them being loaded to fixed addresses, which might potentially open vulnerabilities.

This port also automates the appliance of the `-fPIC/-fPIE` settings to all targets from a single centralized setting called `CMAKE_POSITION_INDEPENDENT_CODE`, which allows CMake to apply the appropriate compiler options without further need of manual specification.

# Customer Impact
Having these flags enabled provides the built binaries with an additional layer of security, which has become a necessary requirement for some compliance checks, as well as safer applications overall. This port was requested by teams in Azure.

# Regression
This was not a regression.

# Testing
The [checksec](https://github.com/slimm609/checksec.sh) tool was used to verify the executables and shared objects had been indeed built with `PIE` and `Full RELRO` enabled.

# Risk
The risk of this is pretty low, since it's been well tested in the current `main` branch, as well as .NET 5.0 releases.

### CODE REVIEW

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by aik-jahoda** [comment]
@janvorli, @ivdiazsa can we consider it as infrastructure PR or it affect product? If it is infra, feel free to merge it - I will not be available today to do it. If it is product change we need `Servicing-approved` from tactic and then we can merge.

**Comment by mangod9** [comment]
Yeah this will need Tactics approval, we will work on that once we have a similar change done in corefx. Thanks

**Review by mangod9 — APPROVED** [review]

**Comment by aik-jahoda** [comment]
> Yeah this will need Tactics approval, we will work on that once we have a similar change done in corefx. Thanks

Is there any progress? The branch is open.

**Review by jeffschwMSFT — APPROVED** [review]
Approved.  I will take for consideration in 3.1.x

cc @blowdart and @GrabYourPitchforks

**Comment by mangod9** [comment]
FYI, this is fixing this issue: https://github.com/dotnet/runtime/issues/45862

**Pull request merged**
