### PR TITLE
Remove Encoding FEATURE_* defines from mscorlib

### PR DESCRIPTION
**Pull request by jamesqo**
Removes a bunch of `FEATURE_` defines related to Encodings; I'm assuming since these APIs are stable that the #ifdefs can be removed.

cc @jkotas

### CODE REVIEW

**Comment by jkotas** [comment]
cc @tarekgh

**Comment by tarekgh** [comment]
LGTM

**Comment by jamesqo** [comment]
Test OSX x64 Checked Build and Test

**Comment by jkotas** [comment]
Thanks!

**Pull request merged**
