### PR TITLE
build-test - fix ~ 2.1k MSBuild warnings due to bad framework and bad project references

### PR DESCRIPTION
**Pull request by 4creators**
This is one of the largest work chunks with fixes split into 3 commits to separate area of interest

1. commit 91f40df549c8f100a8889ed7b37d5e0935f36d3b fixes warnings caused by wrong framework targets
2. commit 2d1a86806ef50b9b49cd95fc336a4fa73f6765ce fixes separately performance and HW intrinsics tests
3. commit d265f21fdcbba61d8421b6941c2fb078ae9fc06d fixes large number of simple project reference errors

### CODE REVIEW

**Comment by 4creators** [comment]
@dotnet-bot test Windows_NT x86 Release Innerloop Build and Test  jitstress2_jitstressregs_3
@dotnet-bot test Windows_NT x64 Release Innerloop Build and Test  jitstress2_jitstressregs_3
@dotnet-bot test Ubuntu x64 Release Innerloop Build and Test  jitstress2_jitstressregs_3

**Comment by 4creators** [comment]
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs3
@dotnet-bot test Windows_NT x64 Checked jitstress2_jitstressregs3
@dotnet-bot test Ubuntu x64 Checked jitstress2_jitstressregs3
@dotnet-bot test OSX10.12 x64 Checked jitstress2_jitstressregs3

**Comment by 4creators** [comment]
cc @AaronRobinsonMSFT @jkotas @AndyAyersMS @tannergooding PTAL

This fixes are spread through different part of the test pls involve anyone who should be interested by this PR

**Comment by AaronRobinsonMSFT** [comment]
@4creators Really appreciate this work, but this large of a PR is almost impossible to review. I am going to have to pull it down and check it out. Please stand by. Thanks.

**Comment by AaronRobinsonMSFT** [comment]
This is a largely mechanical change and is good house keeping 👍 

@tannergooding Can you take a look at the changes under `tests/src/performance`? I have no idea on who might have a good idea on what is the right thing here.

**Comment by 4creators** [comment]
@AndyAyersMS was working on performance test dependencies.

**Comment by 4creators** [comment]
cc @BruceForstall

**Comment by jorive** [comment]
@dotnet/rap-team PTAL

**Comment by jorive** [comment]
Changes seem reasonable to me, but I did noticed that [this](https://github.com/dotnet/coreclr/blob/5306f704e8b4bb30315313033880c36adca6e7f0/tests/src/Common/PerfHarness/PerfHarness.csproj#L7) file did not get updated. Is that intended?

**Comment by jorive** [comment]
@dotnet-bot test Windows_NT x64 perf
@dotnet-bot test Windows_NT x86 perf
@dotnet-bot test linux perf flow

**Comment by 4creators** [comment]
>  I did noticed that this file did not get updated. Is that intended?

This file controls dotnet cli based build of tests which were converted to SDK style projects. At the time of writing there were no commits accepted and not reverted in master branch converting one of the test groups to SDK projects. IMO there is some overlap with work done in project type conversion and my fixes and it would be necessary to reconcile changes but it should be done on working build with new project types.

**Comment by BruceForstall** [comment]
This change LGTM. Does anyone else have any reason why we shouldn't merge it?

**Comment by 4creators** [comment]
@BruceForstall My understandng is that we are waiting for approval from  [@dotnet/rap-team](https://github.com/orgs/dotnet/teams/rap-team) or from @jorive / @noahfalk

**Pull request merged**
