### PR TITLE
Programmatically find the version of TraceEvents

### PR DESCRIPTION
**Pull request by adiaaida**
We have to copy TraceEvents binaries to the sandbox, but sometimes the
version we are using changes. This hardens testing against version changes
by programmatically figuring out which version has been installed.

### CODE REVIEW

**Comment by adiaaida** [comment]
@dotnet-bot test windows_nt x64 perf please

**Comment by adiaaida** [comment]
@dotnet-bot test windows_nt x64 perf please

**Comment by adiaaida** [comment]
@dotnet-bot test windows_nt x64 perf please

**Comment by danmosemsft** [comment]
@adiaaida what is the status of htis PR?

**Comment by karelz** [comment]
Looks like abandoned PR. Closing.
Feel free to reopen when it is ready again ...

**Pull request closed without merging**
