### PR TITLE
Parenthesize macros

### PR DESCRIPTION
**Pull request by bdebaere**
Add parenthesis to parameters in macros or around macros themselves. This alleviates potential concerns. Consider the macro below.

#define MULTIPLY(a,b) a * b

When used like so MULTIPLY(2, 2 + 2) this suddenly becomes 2 * 2 + 2 and renders 6 as output whereas 8 would be expected. Or when used like 2 / MULTIPLY(2, 2) this suddenly becomes 2 / 2 * 2 and renders 1 as output whereas 0.5 would be expected.

### CODE REVIEW

**Comment by bdebaere** [comment]
As far as I'm aware this has no downsides. Only upsides.

**Comment by sandreenko** [comment]
Hello  @bdebaere, sorry we have missed your PR, could you please do a rebase so there are no merge conflicts and we get a fresh testing?

**Comment by erozenfeld** [comment]
@dotnet/jit-contrib

**Comment by bdebaere** [comment]
@sandreenko I'll merge this weekend.

**Comment by bdebaere** [comment]
@sandreenko Can you help me find out why the build fails?

**Comment by sandreenko** [comment]
> @sandreenko Can you help me find out why the build fails?

Sure, have you tried to build it locally with "build.cmd x64 checked" on Windows or with "build.sh x64 checked" on Linux?

To see the testing system (ci) log:
1. click "[details](https://github.com/dotnet/coreclr/pull/23982/checks?check_run_id=240607122)" at any failed job;
2. then click "[View more details on Azure Pipelines](https://dev.azure.com/dnceng/public/_build/results?buildId=370106&view=logs&jobId=d37b6b50-5a2d-5da1-80ef-d0fdb8e5bff2)"
3. then click "Build product" and scroll down to the errors:

in your case they are:
/__w/1/s/src/vm/excep.h:614:9: error: 'IS_UNWINDING' macro redefined [-Werror,-Wmacro-redefined]
#define IS_UNWINDING(Flag) (((Flag) & EXCEPTION_UNWIND) != 0)

if you grep in the source code you will see that there is another definition in `coreclr\src\pal\inc\pal.h` that was not changed and this PR, so they become different. 
https://github.com/dotnet/coreclr/blob/7fd79859530d6d6a05ae3b69adf2e0ca8a746bab/src/pal/inc/pal.h#L3015

So if you change that definition as well it should build (or it will show next error).

Note: I do not see why we need `#define IS_UNWINDING(Flag) ((Flag & EXCEPTION_UNWIND) != 0)` in pal.h, probably it can be deleted.

**Comment by bdebaere** [comment]
@sandreenko It looks like the current error is out of my reach to solve.

**Comment by sandreenko** [comment]
> @sandreenko It looks like the current error is out of my reach to solve. Please advise. :)

Something is wrong with our test system, these jobs are failing everywhere, you can ignore this redness. 

PTAL @dotnet/dnceng or @dotnet/coreclr-infra (what is the right group for such issues now?).

What has happened with `IS_UNWINDING`?

**Comment by sandreenko** [comment]
There are many changes in VM/GC/zap files, PTAL @jkotas, @Maoni0.

Jit changes LGTM, cc @dotnet/jit-contrib .

Thanks for doing (and redoing) this, @bdebaere!

**Comment by MattGal** [comment]
> > @sandreenko It looks like the current error is out of my reach to solve. Please advise. :)
> 
> Something is wrong with our test system, these jobs are failing everywhere, you can ignore this redness.
> 
> PTAL @dotnet/dnceng or @dotnet/coreclr-infra (what is the right group for such issues now?).
> 
> What has happened with `IS_UNWINDING`?

@sandreenko dnceng is the right team to talk to:

The two AzDO builds associated with this had two problems:
- ubuntu.1604.arm32.open is being overloaded (there were ~403 other work items around the same time, doing literally 17 hours in that time our 35 machines, so if you must run these tests an increased timeout is a good idea.
- The other failure was a package restore issue, likely a transient build problem. 

The only persistent problem here is just using a queue too much and  constantly restarting the runs which only makes the problem worse.  The only fix is to use the queue less or wait more.  If you want to discuss further please stop by my desk or ping me on teams.

**Pull request merged**
