### PR TITLE
Delete test 366085

### LINKED ISSUE #25271: Test failed: baseservices_exceptions._regressions_whidbeybeta2_366085_366085_366085_._regressions_whidbeybeta2_366085_366085_366085_cmd
**Job:**
https://mc.dot.net/#/user/coreclr-ci/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F/20190619.37/workItem/PayloadGroup0/analysis/xunit/baseservices_exceptions._regressions_whidbeybeta2_366085_366085_366085_~2F_regressions_whidbeybeta2_366085_366085_366085_cmd

**Failed tests:**
baseservices_exceptions._regressions_whidbeybeta2_366085_366085_366085_._regressions_whidbeybeta2_366085_366085_366085_cmd

**Log:**
```
Return code:      1
Raw output file:      C:\\dotnetbuild\\work\\92434049-1cc5-4d45-b521-4a71bc8ab0b9\\Work\\94782cb1-9504-4ac8-b1c5-fc4485042de4\\Exec\\baseservices\\exceptions\\Reports\\baseservices.exceptions\\regressions\\whidbeybeta2\\366085\\366085\\366085.output.txt
Raw output:
BEGIN EXECUTION
 \"C:\\dotnetbuild\\work\\92434049-1cc5-4d45-b521-4a71bc8ab0b9\\Payload\\corerun.exe\" 366085.exe 
Caught ArgumentNullException
Value cannot be null. (Parameter 's')
Test FAILED
Expected: 100
Actual: 99
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\\dotnetbuild\\work\\92434049-1cc5-4d45-b521-4a71bc8ab0b9\\Payload
> C:\\dotnetbuild\\work\\92434049-1cc5-4d45-b521-4a71bc8ab0b9\\Work\\94782cb1-9504-4ac8-b1c5-fc4485042de4\\Exec\\baseservices\\exceptions\\regressions\\whidbeybeta2\\366085\\366085\\366085.cmd
Expected: True
Actual:   False
```

### PR DESCRIPTION
**Pull request by janvorli**
This test was checking for "Parameter name:" substring in the
ArgumentNullException message. But a recent change #25185 modified
that string to just "Parameter".

We also have a coverage for this in corefx tests, so I am removing this test.

Close #25271

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @danmosemsft

**Comment by jkotas** [comment]
Test like this belongs to CoreFX. I have added coverage for this case in https://github.com/dotnet/corefx/pull/38724. Could you please delete this test here instead?

**Comment by janvorli** [comment]
@danmosemsft yes, this is a Pri 1 test.

**Comment by janvorli** [comment]
@jkotas ok, I've deleted it instead.

**Pull request merged**
