### PR TITLE
Fix HW intrinsics test projects naming and optimisation levels according to repo conventions

### LINKED ISSUE #19131: Incorrect naming for JIT\HardwareIntrinsics\X86\Sse2 test projects
The naming of the following doesn't follow the correct naming scheme:
```
MoveScalar_r.Int64.csproj
MoveScalar_r.UInt64.csproj
MoveScalar_ro.Int64.csproj
MoveScalar_ro.UInt64.csproj
```
The `_r` or `_ro` suffix needs to be the _last_ thing before the file extension. Thus, they should be:
```
MoveScalar.Int64_r.csproj
MoveScalar.UInt64_r.csproj
MoveScalar.Int64_ro.csproj
MoveScalar.UInt64_ro.csproj
```

### LINKED ISSUE #19132: Incorrect Optimization setting for tests
The naming convention is that `*_ro` tests are optimized (`<Optimize>True</Optimize>`) and `*_r` tests are not (`<Optimize></Optimize>`).

The following are not built optimized and should be (and the build is the same as the `_r` versions):
```
JIT\HardwareIntrinsics\X86\Sse2\CompareGreaterThanOrEqualScalar_ro.csproj
JIT\HardwareIntrinsics\X86\Sse2\CompareGreaterThanOrEqualUnorderedScalar_ro.csproj
```

The following are built optimized and should not be (the `_ro` versions are built optimized):
```
Sse2\MaskMove_r.csproj
Sse2\MoveMask_r.csproj
Sse2\MoveScalar_r.csproj
Sse2\MoveScalar_r.Int64.csproj
Sse2\MoveScalar_r.UInt64.csproj
Avx\InsertExtractVector128_r.csproj
Avx\MoveMask_r.csproj
Avx2\MoveMask_r.csproj
```

(related: https://github.com/dotnet/coreclr/pull/19083)

### PR DESCRIPTION
**Pull request by 4creators**
Fixes #19131 
Fixes #19132 

Checked all x86 HW intrinsics test projects.

### CODE REVIEW

**Comment by 4creators** [comment]
@dotnet-bot test Windows_NT x64 Checked jitincompletehwintrinsic
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnoavx
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnoavx2
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnosimd
@dotnet-bot test Windows_NT x64 Checked jitnox86hwintrinsic

@dotnet-bot test Windows_NT x86 Checked jitincompletehwintrinsic
@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnoavx
@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnoavx2
@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnosimd
@dotnet-bot test Windows_NT x86 Checked jitnox86hwintrinsic

@dotnet-bot test Ubuntu x64 Checked jitincompletehwintrinsic
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnoavx
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnoavx2
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnosimd
@dotnet-bot test Ubuntu x64 Checked jitnox86hwintrinsic

@dotnet-bot test Windows_NT x64 Checked jitincompletehwintrinsic
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnoavx
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnoavx2
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnosimd
@dotnet-bot test Windows_NT x64 Checked jitnox86hwintrinsic

@dotnet-bot test Windows_NT x86 Checked jitincompletehwintrinsic
@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnoavx
@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnoavx2
@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnosimd
@dotnet-bot test Windows_NT x86 Checked jitnox86hwintrinsic

@dotnet-bot test Ubuntu x64 Checked jitincompletehwintrinsic
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnoavx
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnoavx2
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnosimd
@dotnet-bot test Ubuntu x64 Checked jitnox86hwintrinsic

@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs3
@dotnet-bot test Windows_NT x64 Checked jitstress2_jitstressregs3
@dotnet-bot test OSX10.12 x64 Checked jitstress2_jitstressregs3
@dotnet-bot test Ubuntu x64 Checked jitstress2_jitstressregs3

**Comment by 4creators** [comment]
@dotnet-bot test OSX10.12 x64 Checked jitincompletehwintrinsic
@dotnet-bot test OSX10.12 x64 Checked jitx86hwintrinsicnoavx
@dotnet-bot test OSX10.12 x64 Checked jitx86hwintrinsicnoavx2
@dotnet-bot test OSX10.12 x64 Checked jitx86hwintrinsicnosimd
@dotnet-bot test OSX10.12 x64 Checked jitnox86hwintrinsic

**Comment by 4creators** [comment]
@dotnet-bot test Ubuntu x64 Checked jitincompletehwintrinsic
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnoavx
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnoavx2
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnosimd
@dotnet-bot test Ubuntu x64 Checked jitnox86hwintrinsic

**Comment by 4creators** [comment]
@dotnet-bot test Ubuntu x64 Checked jitstress2

**Comment by 4creators** [comment]
@CarolEidt @tannergooding @fiigii PTAL

Surprisingly OSX jitstress tests passed, despite that nothing changed in failing ro projects. Could be some intermittent failures. see $19190

**Comment by 4creators** [comment]
see #19190

**Comment by tannergooding** [comment]
@BruceForstall, what would you think of a general `Target` that errors if the project name ends with `_r` or `_ro` and the "proper" optimize value isn't set?

**Comment by tannergooding** [comment]
Thanks @4creators

**Comment by BruceForstall** [comment]
> @BruceForstall, what would you think of a general Target that errors if the project name ends with _r or _ro and the "proper" optimize value isn't set?

@tannergooding fyi, it turns out we have such a test already, but we discovered some limitations in it, tracked by https://github.com/dotnet/coreclr/issues/19166.

**Pull request merged**
