### PR TITLE
Minor fixups for CoreFX test instructions

### PR DESCRIPTION
**Pull request by jamesqo**
Fixed the schema and install location.

### CODE REVIEW

**Comment by jasonwilliams200OK** [comment]
:+1:

**Comment by ellismg** [comment]
@jamesqo Does this still work?  I am pretty sure that our strategy for getting CoreCLR on windows no longer uses these packages :-(.

**Comment by ellismg** [comment]
Even if we used this package, I think this is update is incorrect.  The InstallLocation item needs to point at the CoreFX pacakges folder, but the localpublish.props file needs to be in the CoreCLR pacakges folder, if I understand the logic in the targets correctly.

**Comment by jamesqo** [comment]
Whoops, didn't see that. In that case I'll close this PR.

**Pull request closed without merging**
