### PR TITLE
Enable MemoryFailPoint functionality on Unix

### PR DESCRIPTION
**Pull request by hughbe**
As per comment in https://github.com/dotnet/coreclr/issues/7807

Corefx has a disabled test this issue

### CODE REVIEW

**Comment by janvorli** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test  please

**Comment by janvorli** [comment]
@dotnet-bot  test Tizen armel Cross Debug Build please

**Comment by janvorli** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test please

**Comment by hughbe** [comment]
@janvorli are you happy with this? thanks

**Comment by danmosemsft** [comment]
@hughbe can you resolve conflicts?
@janvorli do you sign off?

**Comment by janvorli** [comment]
@danmosemsft I am reviewing it now.

**Comment by janvorli** [comment]
@danmosemsft, @hughbe we still cannot enable this for Unix. There is one additional thing that would not work. The VirtualQuery implementation in the PAL never returns size of the free region (always returns 0 for them), since it has no knowledge about free regions ranges.  That means that the MemFreeAfterAddress function would end up running in an infinite loop.

**Comment by danmosemsft** [comment]
@janvorli is this feasible to fix,? if so I will open an issue.

**Comment by janvorli** [comment]
@danmosemsft I think it would be feasible, so creating an issue for it sounds good. We could possibly augment the VirtualQuery implementation in PAL to read and parse the /proc/self/maps memory map when the address is not in the allocated blocks we keep track of (and the equivalent of that on OSX). 
If that would cause perf issues in other places where VirtualQuery is used, we could create a new PAL function that would be used in the MemFreeAfterAddress managed function only and PInvoke into that.

**Comment by karelz** [comment]
What is status of this PR? What are the next steps to move it forward? Is it blocked on something?

**Comment by janvorli** [comment]
@karelz this PR should be closed. We have #13560 to make the necessary fixes so that it could work on Unix.

**Pull request closed without merging**
