### PR TITLE
The !HeapStat sos command emits difficult to read output

### PR DESCRIPTION
**Pull request by tvass83**
The "Percentage" column is not aligned properly (no leading space), see my next comment for the detailed output.

### CODE REVIEW

**Comment by danmosemsft** [comment]
@tvass83 you can use triple backticks to make a block of text monospace in github

**Comment by tvass83** [comment]
Thanks for the tip @danmosemsft! I updated my comment.

**Comment by mikem8361** [comment]
LGTM

**Comment by janvorli** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test please

**Comment by janvorli** [comment]
@dotnet-bot test Tizen armel Cross Debug Build please

**Comment by janvorli** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by janvorli** [comment]
@dotnet-bot test Ubuntu16.04 arm Cross Debug Build  please

**Pull request merged**
