### PR TITLE
ARM64: Disable Two Tests

### PR DESCRIPTION
**Pull request by kyulee1**
https://github.com/dotnet/coreclr/issues/6583

### CODE REVIEW

**Comment by kyulee1** [comment]
@dotnet/arm64-contrib PTAL

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 checked

**Comment by kyulee1** [comment]
@dotnet/arm64-contrib PTAL

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 checked

**Comment by briansull** [comment]
LGTM

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 checked

**Comment by kyulee1** [comment]
Although running tests come back green, building tests are failing which caused the leg to fail since  @Priya91 change on build-test.cmd.
I will follow it up tomorrow.

**Comment by gkhanna79** [comment]
> building tests are failing which caused the leg to fail since @Priya91 change on build-test.cmd.

Is there an issue for this that @Priya91 can look into?

**Comment by kyulee1** [comment]
The fix for test build is in a PR https://github.com/dotnet/coreclr/pull/6586

**Pull request merged**
