### PR TITLE
build-test - fix ilasm warnings caused by missing/incorrect extern assembly declarations

### LINKED ISSUE #14689: Many CI Perf Tests Correctness Warnings: about targeting .NETFramework,Version=v4.0
Build **Windows_NT x64 full_opt ryujit CoreCLR Perf Tests Correctness**

perf_perflab_Windows_NT_x64_full_opt_ryujit_smoketest_prtest

> could not be resolved because it has an indirect dependency on the framework assembly "System.Runtime.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/Microsoft.CodeAnalysis.dll" or retarget your application to a framework version which contains "System.Runtime.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".

```
02:04:33 C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3268: The primary reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/Microsoft.CodeAnalysis.dll" could not be resolved because it has an indirect dependency on the framework assembly "System.Runtime.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/Microsoft.CodeAnalysis.dll" or retarget your application to a framework version which contains "System.Runtime.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". [D:\j\w\perf_perflab_---89ec9f56\tests\src\JIT\IL_Conformance\Old\Conformance_Base\conv_ovf_i8_i.ilproj]
02:04:33 C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3268: The primary reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/Microsoft.CodeAnalysis.CSharp.dll" could not be resolved because it has an indirect dependency on the framework assembly "System.Runtime.Serialization.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/Microsoft.CodeAnalysis.CSharp.dll" or retarget your application to a framework version which contains "System.Runtime.Serialization.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". [D:\j\w\perf_perflab_---89ec9f56\tests\src\JIT\IL_Conformance\Old\Conformance_Base\conv_ovf_i8_i.ilproj]
02:04:33 C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3268: The primary reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/Microsoft.CodeAnalysis.VisualBasic.dll" could not be resolved because it has an indirect dependency on the framework assembly "System.Runtime.Serialization.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/Microsoft.CodeAnalysis.VisualBasic.dll" or retarget your application to a framework version which contains "System.Runtime.Serialization.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". [D:\j\w\perf_perflab_---89ec9f56\tests\src\JIT\IL_Conformance\Old\Conformance_Base\conv_ovf_i8_i.ilproj]
02:04:33 C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3268: The primary reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/Microsoft.CodeAnalysis.dll" could not be resolved because it has an indirect dependency on the framework assembly "System.Runtime.Serialization.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/Microsoft.CodeAnalysis.dll" or retarget your application to a framework version which contains "System.Runtime.Serialization.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". [D:\j\w\perf_perflab_---89ec9f56\tests\src\JIT\IL_Conformance\Old\Conformance_Base\conv_ovf_i8_i.ilproj]
02:04:33 C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3268: The primary reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/Microsoft.Diagnostics.Tracing.TraceEvent.dll" could not be resolved because it has an indirect dependency on the framework assembly "System.Runtime.InteropServices, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/Microsoft.Diagnostics.Tracing.TraceEvent.dll" or retarget your application to a framework version which contains "System.Runtime.InteropServices, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". [D:\j\w\perf_perflab_---89ec9f56\tests\src\JIT\IL_Conformance\Old\Conformance_Base\conv_ovf_i8_i.ilproj]
02:04:33 C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3268: The primary reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/xunit.performance.api.dll" could not be resolved because it has an indirect dependency on the framework assembly "System.Runtime.InteropServices, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/xunit.performance.api.dll" or retarget your application to a framework version which contains "System.Runtime.InteropServices, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". [D:\j\w\perf_perflab_---89ec9f56\tests\src\JIT\IL_Conformance\Old\Conformance_Base\conv_ovf_i8_i.ilproj]
02:04:33 C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3268: The primary reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/xunit.performance.metrics.dll" could not be resolved because it has an indirect dependency on the framework assembly "System.Runtime.InteropServices, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/xunit.performance.metrics.dll" or retarget your application to a framework version which contains "System.Runtime.InteropServices, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". [D:\j\w\perf_perflab_---89ec9f56\tests\src\JIT\IL_Conformance\Old\Conformance_Base\conv_ovf_i8_i.ilproj]
02:04:33 C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3268: The primary reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/Microsoft.Diagnostics.Tracing.TraceEvent.dll" could not be resolved because it has an indirect dependency on the framework assembly "System.Xml.ReaderWriter, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/Microsoft.Diagnostics.Tracing.TraceEvent.dll" or retarget your application to a framework version which contains "System.Xml.ReaderWriter, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". [D:\j\w\perf_perflab_---89ec9f56\tests\src\JIT\IL_Conformance\Old\Conformance_Base\conv_ovf_i8_i.ilproj]
02:04:33 C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3268: The primary reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/xunit.performance.api.dll" could not be resolved because it has an indirect dependency on the framework assembly "System.Xml.ReaderWriter, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/xunit.performance.api.dll" or retarget your application to a framework version which contains "System.Xml.ReaderWriter, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". [D:\j\w\perf_perflab_---89ec9f56\tests\src\JIT\IL_Conformance\Old\Conformance_Base\conv_ovf_i8_i.ilproj]
02:04:33 C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3268: The primary reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/xunit.performance.metrics.dll" could not be resolved because it has an indirect dependency on the framework assembly "System.Xml.ReaderWriter, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/xunit.performance.metrics.dll" or retarget your application to a framework version which contains "System.Xml.ReaderWriter, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". [D:\j\w\perf_perflab_---89ec9f56\tests\src\JIT\IL_Conformance\Old\Conformance_Base\conv_ovf_i8_i.ilproj]
02:04:33 C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3268: The primary reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/Microsoft.Diagnostics.Tracing.TraceEvent.dll" could not be resolved because it has an indirect dependency on the framework assembly "System.IO.Compression, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/Microsoft.Diagnostics.Tracing.TraceEvent.dll" or retarget your application to a framework version which contains "System.IO.Compression, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b77a5c561934e089". [D:\j\w\perf_perflab_---89ec9f56\tests\src\JIT\IL_Conformance\Old\Conformance_Base\conv_ovf_i8_i.ilproj]
02:04:33 C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3268: The primary reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/xunit.performance.api.dll" could not be resolved because it has an indirect dependency on the framework assembly "System.IO.Compression, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/xunit.performance.api.dll" or retarget your application to a framework version which contains "System.IO.Compression, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b77a5c561934e089". [D:\j\w\perf_perflab_---89ec9f56\tests\src\JIT\IL_Conformance\Old\Conformance_Base\conv_ovf_i8_i.ilproj]
02:04:33 C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3268: The primary reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/xunit.performance.metrics.dll" could not be resolved because it has an indirect dependency on the framework assembly "System.IO.Compression, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/xunit.performance.metrics.dll" or retarget your application to a framework version which contains "System.IO.Compression, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b77a5c561934e089". [D:\j\w\perf_perflab_---89ec9f56\tests\src\JIT\IL_Conformance\Old\Conformance_Base\conv_ovf_i8_i.ilproj]
02:04:33 C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3268: The primary reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/Microsoft.Diagnostics.Tracing.TraceEvent.dll" could not be resolved because it has an indirect dependency on the framework assembly "System.Net.Primitives, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "D:\j\w\perf_perflab_---89ec9f56\bin\TargetingPack\/Microsoft.Diagnostics.Tracing.TraceEvent.dll" or retarget your application to a framework version which contains "System.Net.Primitives, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". [D:\j\w\perf_perflab_---89ec9f56\tests\src\JIT\IL_Conformance\Old\Conformance_Base\conv_ovf_i8_i.ilproj]
```
etc

Followed by

```
02:04:33 ..\common\common.il(210): warning : Reference to undeclared extern assembly 'system.runtime.extensions'. Attempting autodetect [D:\j\w\perf_perflab_---89ec9f56\tests\src\JIT\jit64\mcc\interop\mcc_i07.ilproj]
02:04:33 ..\common\common.il(210): warning : Reference to undeclared extern assembly 'system.runtime.extensions'. Attempting autodetect [D:\j\w\perf_perflab_---89ec9f56\tests\src\JIT\jit64\mcc\interop\mcc_i16.ilproj]
02:04:33 ..\common\common.il(210): warning : Reference to undeclared extern assembly 'system.runtime.extensions'. Attempting autodetect [D:\j\w\perf_perflab_---89ec9f56\tests\src\JIT\jit64\mcc\interop\mcc_i17.ilproj]
02:04:33 ..\common\common.il(210): warning : Reference to undeclared extern assembly 'system.runtime.extensions'. Attempting autodetect [D:\j\w\perf_perflab_---89ec9f56\tests\src\JIT\jit64\mcc\interop\mcc_i06.ilproj]
02:04:33 ..\common\common.il(210): warning : Reference to undeclared extern assembly 'system.runtime.extensions'. Attempting autodetect [D:\j\w\perf_perflab_---89ec9f56\tests\src\JIT\jit64\mcc\interop\mcc_i37.ilproj]
02:04:33 ..\common\common.il(210): warning : Reference to undeclared extern assembly 'system.runtime.extensions'. Attempting autodetect [D:\j\w\perf_perflab_---89ec9f56\tests\src\JIT\jit64\mcc\interop\mcc_i36.ilproj]
```

### PR DESCRIPTION
**Pull request by 4creators**
Fixes #14689

While working on #19109 fixed all ilasm warnings for priority 0 and 1 builds.

Since my editor is automatically enforcing .editorconfig coding style white space was fixed in all files which were edited (tabs -> spaces, no white space at the end of line)

Will create separate issue to track not fixed #14689 warnings - MSB3268

### CODE REVIEW

**Comment by 4creators** [comment]
@dotnet-bot test OSX10.12 x64 Checked jitstress2_jitstressregs3
@dotnet-bot test Ubuntu x64 Checked jitstress2_jitstressregs3

**Comment by 4creators** [comment]
@jkotas @CarolEidt @AndyAyersMS PTAL

**Comment by CarolEidt** [comment]
I don't believe that we should need to put explicit `publickeytoken` specifications in the IL tests (or at least not for most of them). I wonder if these are here simply because the original IL was created from ildasm, and in many cases it should probably be using `.assembly extern BLAH { auto }`.

**Comment by 4creators** [comment]
Will fix

**Comment by 4creators** [comment]
@CarolEidt Addressed review feedback PTAL

Assembly declarations has been correct with script, if you think we can do it to all il source files I can run script for all of them. Please let me now.

**Comment by CarolEidt** [comment]
@dotnet-bot test OSX10.12 x64 Checked CoreFX Tests
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by CarolEidt** [comment]
> if you think we can do it to all il source files I could run script for all of them. Please let me now.

I don't think it's necessary. I don't know if we have any tests that explicitly test the use of non-auto assembly declarations.

**Comment by 4creators** [comment]
@CarolEidt I will replace my "Remove unnecessry assembly declaration metadata" with new version with some improvements to white space and mscorlib handling.

**Pull request merged**
