### PR TITLE
Fix & test for #18362

### PR DESCRIPTION
**Pull request by CarolEidt**
Also add to the arm & arm64 tests.lst

### CODE REVIEW

**Comment by CarolEidt** [comment]
I have a fix for this, but wanted to ensure that the test fails as expected on arm (it doesn't fail with the altjit).

**Comment by CarolEidt** [comment]
The problem was that LSRA was creating only a singe use for multi-reg ops under FIELD_LIST. We need to build a use for each reg.
Also, dump the defList if it's not empty at end of block, to make it easier to track down the cause of this assert in future.

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

**Comment by BruceForstall** [comment]
Link: #18362

**Comment by CarolEidt** [comment]
Fix #18362

**Comment by CarolEidt** [comment]
@BruceForstall @jashook the reason this didn't repro with the altjit is that `getTailCallCopyArgsThunk` returns null, so it doesn't do the tail copy (which leads to the split args case that this bug needs to repro). Do you think it's worth making it return a dummy value for the altjit?

**Comment by jashook** [comment]
I will let Bruce comment further; however, adding in altjit specific return values to me sounds dangerous.

**Pull request merged**
