### PR TITLE
Fix jit test projects to specify debug type and optimization flags

### PR DESCRIPTION
**Pull request by AndyAyersMS**
This partially addresses the issues raised in #4124 and #4724 by explicitly
and unconditionally setting DebugType and Optimize flags for various test
project files.

The projects that were fixed are those that did not specify any debug
flag settings at all.  The fix is to set DebugType to PdbOnly and to set
Optimization to true, unless the test has an _r or _rel suffix, in which
case Optimization is set false.

This impacts 1497 projects, skipping over 311 other projects flagged as needing
fixes. The projects that remain are the CodeGenBringUp set (for which we plan
to clone projects to test the various flag combinations), projects that
specify flags but do so in ways where the effective flag settings may vary
from DBG to RET, projects that specify the flags redundantly, or projects
where the flags are not consistent with the "test case name suffix" rules.

The edits were done by a tool using linq-to-xml and so some incidental
reformatting has happened.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@pgavlin PTAL
cc @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
Actually there are at least 374 left to fix, I missed out on cases where DebugType is set under either Debug or Release configs but not both.

**Comment by AndyAyersMS** [comment]
Pushed an update to fix the remaining projects that aren't bring up tests.

**Comment by AndyAyersMS** [comment]
Windows test failure [(log)](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_release_windows_nt_pri1_prtest/3145/) seems unrelated. I didn't change any test project outside of the JIT dir.
```
Unhandled Exception: D:\j\workspace\x64_release_w---0575cb46\tests\tests.targets(47,5): error : CoreMangLib._cti_system_decimal_DecimalParse3_DecimalParse3_._cti_system_decimal_DecimalParse3_DecimalParse3_cmd [FAIL] [D:\j\workspace\x64_release_w---0575cb46\tests\runtest.proj]
10:16:01         Test Infrastructure Failure: The paging file is too small for this operation to complete
10:16:01 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```

CentOS test failure [(log)](https://ci.dot.net/job/dotnet_coreclr/job/master/job/debug_centos7.1_prtest/3068/) also seemingly unrelated:
```
threading.SleepEx.test2
MESSAGE:
Expected thread to sleep for 2000 ms (and not be interrupted). Average delta: 858993432 ms, acceptable delta: 150
```

Am going to rerun both...

@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test
@dotnet-bot test CentOS7.1 x64 Debug Build and Test

**Comment by jashook** [comment]
@AndyAyersMS the CentOS failure has happened as well on an Arm64 specific change. Seems like it is flaky see #9653 for the failure.

**Comment by briansull** [comment]
LGTM, Thanks Andy

**Comment by AndyAyersMS** [comment]
Once this goes in, I plan to add the project checker itself as a test case to catch any future project file issues.

If that seems too clever, stop me now.

**Comment by pgavlin** [comment]
> Once this goes in, I plan to add the project checker itself as a test case to catch any future project file issues.
>
> If that seems too clever, stop me now.

As long as this doesn't unduly impact our test times (esp. in CI--I'm not sure what the I/O performance is like on our VMs), I think this seems fine.

**Comment by AndyAyersMS** [comment]
Locally it runs in about 2 seconds. I suppose my file cache is all warmed up by now though.

**Comment by AndyAyersMS** [comment]
@pgavlin any concerns with the second commit?

**Comment by pgavlin** [comment]
Nope, LGTM

**Pull request merged**
