### PR TITLE
Fix thread wait to be resilient to real time clock changes on Linux

### PR DESCRIPTION
**Pull request by janvorli**
This change fixes a problem that happens when a thread uses a timed wait
and the real time clock change in the system (e.g. due to the user action,
time server sync, leap second, etc). In such case, the wait may end up waiting
for shorter or longer period of time.
It fixes the issue for Thread.Sleep and timed wait on a process local synchronization
primitives by using CLOCK_MONOTONIC instead of CLOCK_REALTIME for waiting on
cond vars.
Unfortunately, the waits on cross process synchronication primitives like
named mutexes always use CLOCK_REALTIME, so this fix works on process local primitives
only.

### CODE REVIEW

**Comment by janvorli** [comment]
Fixes #10918

**Comment by janvorli** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test please

**Comment by janvorli** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by janvorli** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test please

**Comment by janvorli** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test please

**Comment by joepeer** [comment]
Shouldn't this be merged for at least the LTS version 1.0.5?
Without the fix we will get weird behavior when the clock gets adjusted for day light saving time.

**Comment by janvorli** [comment]
@gkhanna79 I think that @joepeer is right that this change should be made to the LTS version too. Do you agree?

**Comment by gkhanna79** [comment]
@janvorli Sounds reasonable. Please feel free to get PRs for 1.0.0 and 1.1.0 branches and email shiproom for them.

**Comment by janvorli** [comment]
@joepeer I've ported the change to both 1.0.x and 1.1.x

**Comment by joepeer** [comment]
Thanks.
Any idea when the new LTS that should include the fix will get released?

**Comment by janvorli** [comment]
@gkhanna79 would probably be able to give you at least an approximate answer.

**Comment by gkhanna79** [comment]
Actually, @leecow can give the timeframe of the next release for the 1.x servicing builds.

**Comment by leecow** [comment]
We have been releasing 1.x updates roughly every 2 months. That said, a possible July release will be dependent upon the high impact issues submitted as candidates for the release.

**Pull request merged**
