### PR TITLE
Disable PGO for CentOS

### PR DESCRIPTION
**Pull request by benaadams**
Allows clean CI: https://github.com/dotnet/coreclr/issues/14581

### CODE REVIEW

**Comment by benaadams** [comment]
@dotnet-bot test Tizen armel Cross Debug Build

**Comment by benaadams** [comment]
Doesn't seem to help? :(

```
15:07:13 FAILED   - JIT/jit64/localloc/ehverify/eh05_small/eh05_small.sh
15:07:13                BEGIN EXECUTION
15:07:13                /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_pri1_tst_prtest/bin/tests/Windows_NT.x64.Release/Tests/coreoverlay/corerun eh05_small.exe
15:07:13                terminate called after throwing an instance of 'PAL_SEHException'
15:07:13                ./eh05_small.sh: line 243: 61932 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
15:07:13                Expected: 100
15:07:13                Actual: 134
15:07:13                END EXECUTION - FAILED
15:07:14 GDB was not found. Unable to print core file.
```

**Comment by benaadams** [comment]
Have done a fully revert; if it doesn't pass then its a different issue?

**Comment by benaadams** [comment]
Nope

> 16:36:00                terminate called after throwing an instance of 'PAL_SEHException'

**Comment by jkotas** [comment]
I have submitted a full revert as https://github.com/dotnet/coreclr/pull/14645 - let's see whether it helps

**Pull request closed without merging**
