### PR TITLE
Add Marshal.GetExceptionPointers

### PR DESCRIPTION
**Pull request by yizhang82**
Debugger folks need this to capture exceptions in dumps. We might need to throw PNSE in .NET native (or make up something there). 
Any objections? @jkotas @janvorli @AntonLapounov

### CODE REVIEW

**Comment by jkotas** [comment]
LGTM otherwise

**Comment by sunitaw** [comment]
I am using .net core 2.0 and still getting - cannot resolve symbol for GetExceptionPointers

**Comment by luqunl** [comment]
@sunitaw, We are investigating this.

**Comment by pharring** [comment]
We (Snapshot Debugger) use reflection to call this method in .NET Core / .NET Standard 2.0

**Pull request merged**
