### PR TITLE
Correction of typos in several infrastructure files

### PR DESCRIPTION
**Pull request by 4creators**
PR contains fixes for several typos which I have found while scrutinizing some build and CI related files - white space fixes were added as well this time however not by me but by my editor 😄

### CODE REVIEW

**Comment by BruceForstall** [comment]
```
09:57:09 D:\j\workspace\perf_perflab_---89ec9f56\Tools\dotnetcli\sdk\2.0.0-preview1-005977\NuGet.targets(97,5): error : An error occurred while sending the request. [D:\j\workspace\perf_perflab_---89ec9f56\tests\src\JIT\config\benchmark+roslyn\benchmark+roslyn.csproj] [D:\j\workspace\perf_perflab_---89ec9f56\tests\build.proj]
09:57:09 D:\j\workspace\perf_perflab_---89ec9f56\Tools\dotnetcli\sdk\2.0.0-preview1-005977\NuGet.targets(97,5): error : The connection with the server was terminated abnormally [D:\j\workspace\perf_perflab_---89ec9f56\tests\src\JIT\config\benchmark+roslyn\benchmark+roslyn.csproj] [D:\j\workspace\perf_perflab_---89ec9f56\tests\build.proj]
09:57:26 
```

try again
@dotnet-bot test Windows_NT x64 full_opt ryujit CoreCLR Perf Tests Correctness

**Comment by 4creators** [comment]
PTAL
/cc @wtgodbe @weshaggard

**Comment by wtgodbe** [comment]
LGTM, but are the whitespace fixes necessary?

**Comment by BruceForstall** [comment]
IMO, the whitespace changes aren't necessary, but many editors/tools like to remove trailing whitespace (and git itself gets upset when merging such files)

**Pull request merged**
