### PR TITLE
correct the casing of CentOS and OpenSUSE in the README

### PR DESCRIPTION
**Pull request by joshfree**

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
This is a nit, but if we're correcting casing, I think it should be 'openSUSE'.

**Comment by mellinoe** [comment]
>  I think it should be 'openSUSE'.

:+1:

**Comment by ellismg** [comment]
Josh, if you fix the casing, I'll merge this...

**Comment by ellismg** [comment]
I will take care of this when I do my updates shortly.

**Pull request closed without merging**
