### PR TITLE
Improve SSA topological sort

### PR DESCRIPTION
**Pull request by mikedn**
The iterator model isn't a very good fit for block successor iteration. These iterators are quite large (`AllSuccessorIter` has 64 bytes on 64 bit hosts) and the need to maintain 2 iterators (current and end) only make things worse when iterators need to be stored in containers. `SsaBuilder::TopologicalSort` uses 3 stacks, 2 containing iterators and one containing `BasicBlock` pointers. Visiting a block practically requires pushing 136 bytes containing a lot of redundant stuff:
* the second iterator should not be needed
* the block pointer is already present in the first iterator (and it appears twice in `AllSuccessorIter`)
* the compiler pointer isn't really needed and also appears twice in `AllSuccessorIter`

This change extracts the iteration logic into "position" classes that contain only the state need to maintain the current successor. These classes can then be used to build iterators or other mechanism that are more useful in some scenarios - an "enumerator" for example.

This reduces memory usage by 0.3% (`CMK_ArrayStack` drops by more than half) and also provides a small reduction in instructions retired.

Mem stats diff: https://gist.github.com/mikedn/45d7a3873965c627a080191a4c4f51bf

PIN data: https://1drv.ms/x/s!Av4baJYSo5pjgr5i7PW4L3NcAyr9sQ

### CODE REVIEW

**Comment by mikedn** [comment]
Some of this stuff seems too convoluted - the only use of EH successor iterator/position is to implement "all" successor iterator/position so maybe we should merge EH iterator into the "all" iterator. But I'm not familiar enough with EH to tell if having the EH iterator around could be useful in the future so I chose to maintain the status quo.

**Comment by sandreenko** [comment]
> Some of this stuff seems too convoluted - the only use of EH successor iterator/position is to implement "all" successor iterator/position so maybe we should merge EH iterator into the "all" iterator. But I'm not familiar enough with EH to tell if having the EH iterator around could be useful in the future so I chose to maintain the status quo.

Usually compilers do not have such strong separation between normal and exception blocks; the fact that we do have it creates many problems in different parts, for example this mess with 3 types of successors (GetAll, GetAllWithEH, GetSuccs for computing preds). It is another big task that needs to be designed before it is implemented.

**Comment by mikedn** [comment]
@sandreenko Note that `GetEHSuccs` is not even used now, it's only use was in the dump code from `TopologicalSort`. And that was bogus too.

Thanks!

**Comment by sandreenko** [comment]
As well as `IsNextEHSuccessor` and `IsCurrentEH`.

**Comment by mikedn** [comment]
Yes, those are pretty much useless as well. They're only used by the dump code to display "[EH]" in front of EH blocks. I considered removing that stuff since it seems overkill but then I noticed we have comments like this in the code
https://github.com/dotnet/coreclr/blob/5fe6e952f7a9f60ae190a746f2446d255d0e5bea/src/jit/copyprop.cpp#L139-L143
so I thought it might still be useful to keep the dump unchanged until I figure out what's that comment about.

**Pull request merged**
