### PR TITLE
Enable ReadyToRun feature on Unix

### PR DESCRIPTION
**Pull request by janvorli**
This change enables building the ReadyToRun feature on Unix systems.

### CODE REVIEW

**Comment by janvorli** [comment]
@jkotas, can you take a look please?

**Comment by jkotas** [comment]
LGTM

**Comment by linquize** [comment]
What is ReadyToRun feature?

**Comment by janvorli** [comment]
It is a flavor of native images - command line switch of crossgen. We do plan to add docs as part of #227.

**Pull request merged**
