### PR TITLE
CSG stop-gap change on AsyncLocal for .NET Core 3.1

### PR DESCRIPTION
**Pull request by WenningQiu**
Stop-gap change for https://github.com/dotnet/docs/issues/9965

### CODE REVIEW

**Comment by stephentoub** [comment]
@WenningQiu, thank you for your interest in contributing.  This repo is effectively archived, used now only for servicing previous releases of .NET Core.  Any new feature work needs to be done in the dotnet/runtime repo.  Additionally, this PR is attempting to add new features and new APIs.  Such things need to be discussed in issues first.  You're welcome to open an issue in dotnet/runtime with your proposal, at which point it can be discussed, and if agreed upon, then you'd be welcome to submit a PR with the additions.  For reference, the API approval process is outlined at https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md.  Thanks for your interest in contributing.

**Comment by WenningQiu** [comment]
@stephentoub The issue was opened a year ago: https://github.com/dotnet/docs/issues/9965 in dotnet/coreclr. Is it converted to dotnet/runtime automatically or should I create a new one?

**Comment by stephentoub** [comment]
That's in dotnet/docs, not dotnet/coreclr. It'd be best for you to close that and open a new suggestion on dotnet/runtime. Thanks.

**Comment by WenningQiu** [comment]
I re-created the issue under dotnet/runtime as https://github.com/dotnet/runtime/issues/31783 per suggestion in dotnet/coreclr#28007.

**Pull request closed without merging**
