### PR TITLE
Hackathon 2018

### PR DESCRIPTION
**Pull request by juliusfriedman**
June 01 2018 - Optimize Encoding.ASCII #18208
https://github.com/dotnet/coreclr/commit/a60c654373b3a712d5a56774f451b170fc5020bf Small fixes contributed before I was disqualified for LGPL reference.

June 5th 2018 - Eliminate GenTreeRegVar and GT_REG_VAR #18201
https://github.com/dotnet/coreclr/commit/e212cb7c2a59cd6f117f838dc26aa081fc73e41e

Thanks!

### CODE REVIEW

**Comment by mikedn** [comment]
You should not address multiple issues in a single PR, especially when those issues are completely unrelated.

**Comment by jkotas** [comment]
And not mix a large formatting changes with the actual code changes.

**Comment by jkotas** [comment]
https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/contributing.md#dos-and-donts
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/contributing.md

**Comment by juliusfriedman** [comment]
Sorry, I didn't see an easy way to submit a PR from a single commit without branching again, I assumed you could cherry pick the latter contents from the PR, let me know if and how you want me to proceed.

**Comment by juliusfriedman** [comment]
I think I have reverted all changes unrelated to 18208, I will close this PR and open a new one. Sorry for the trouble.

**Pull request closed without merging**
