### PR TITLE
Link for PerfView Download is outdated

### PR DESCRIPTION
**Pull request by cdemi**

### CODE REVIEW

**Comment by jkotas** [comment]
cc @vnacem @brianrob

**Comment by brianrob** [comment]
@vancem, do you want to update http://aka.ms/PerfView to point at GitHub?

**Comment by vancem** [comment]
Yes, http://aka.ms/PerfView should point at https://github.com/Microsoft/perfview#perfview-overview

**Comment by vancem** [comment]
I was not involved with setting up http://aka.ms/PerfView (I think karelz was), but he thankfully made me co-owner.  I have updated the URL to point where I suggested.   

Thanks for the pointer Brian.

**Pull request closed without merging**
