### PR TITLE
Add some tests for optimization of booleans

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Test case to stress inlining, expression opts, and control flow
simplification for booleans.

Test case has 100 methods named Idxx. All 100 should generate identical
code. On x64 windows we expect to get the 4 byte sequence
```
       0FB6C1               movzx    rax, cl
       C3                   ret
```

Only 22 of the variants get this codegen; there are at least 12 other
sequences ranging in size from 9 to 32 bytes of code.

Likely touches on the same issues raised in #914.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@JosephTremoulet PTAL
cc @dotnet/jit-contrib

**Comment by JosephTremoulet** [comment]
Looks great, just some incidental observations:

 - I'm somewhat curious how you chose where to put `AggressiveInlining`.  Was it all the functions that are called by others, or do we need to worry that the test is assuming the current always-inline heuristics?
 - I notice that all the `Id` functions of the `_ ? IdN(x) : IdM(x)` form, you have N == M.  Do you want to include cases with N != M (to catch cases where you have to simplify the two sides to realize they are equivalent rather than having lexically identical expressions)?
 - I'd like to dream that we could inline all that `Func<>.Invoke()` stuff some day :).  Consider using `NoInlining` instead?

**Comment by AndyAyersMS** [comment]
`AggressiveInlining` was added to ensure each `Idxx` gets flattened with the current heuristics.

I could have added more variants. I was trying to think of some clever way to get variation without reams of typing. This probably cries out for a program generator that can crank exhaustively through the variations. But there's enough there for now to keep us busy a while.

I probably could have just forced on debug codegen for Main and done direct calls. If you think that makes more sense I'll revise.

**Comment by JosephTremoulet** [comment]
> `AggressiveInlining` was added to ensure each `Idxx` gets flattened with the current heuristics.

I'd be inclined to sprinkle it more liberally, though I can see the argument against if your expectation is that the heuristics will only get more aggressive for cases like these.

>  probably could have just forced on debug codegen for Main and done direct calls. If you think that makes more sense I'll revise.

I do think that makes a bit more sense, but not terribly strongly; I'd be fine with it being committed as-is.

**Comment by AndyAyersMS** [comment]
Added aggressive inline for the stuff called now plus a bit more, and reworked main.

**Comment by AndyAyersMS** [comment]
OSX uhappy again, lots of test failures with
```
00:14:25.263                BEGIN EXECUTION
00:14:25.263                /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/checked_osx_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun testExplicitOverride.exe
00:14:25.264                {0x66b01cc-0x10a14b3a0} ASSERT [PROCESS] at /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/checked_osx_prtest/src/pal/src/thread/process.cpp.1848: sem_open(/clrct000127db0000000057299d2b) failed: 28 (No space left on device)
```
am going to ignore.

**Pull request merged**
