### PR TITLE
Share arg validation runtest and run-pmi-diff

### PR DESCRIPTION
**Pull request by jashook**
Use the same arg validation in runtests.py and run-pmi-diffs.py

~~Note this also changes run-pmi-diffs to run using python3~~

### CODE REVIEW

**Comment by BruceForstall** [comment]
Also, make sure you trigger a variety of jobs to ensure everything still works. E.g., PMI jobs, etc.

**Comment by jashook** [comment]
@dotnet-bot help

**Comment by jashook** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by jashook** [comment]
@dotnet-bot test Ubuntu16.10 x64 Checked pmi_asm_diffs
@dotnet-bot test Windows_NT x86 Checked pmi_asm_diffs
@dotnet-bot test Windows_NT x64 Checked pmi_asm_diffs

**Comment by jashook** [comment]
@dotnet-bot test Ubuntu16.10 x64 Checked pmi_asm_diffs
@dotnet-bot test Windows_NT x86 Checked pmi_asm_diffs
@dotnet-bot test Windows_NT x64 Checked pmi_asm_diffs

**Comment by jashook** [comment]
Failures look unrelated to the changes.

**Comment by adiaaida** [comment]
Does this change require us to pass core_root as a parameter to run test.py now? We are getting this error in the optimization repo after this change:

`Error, incorrect core_root location`

**Comment by jashook** [comment]
@adiaaida there hopefully should be no difference in use. Can you send me a link of a failure?

**Comment by adiaaida** [comment]
https://ci2.dot.net/job/Private/job/dotnet_optimization/job/master/job/CLRx64WINmasPGO/517/console

**Comment by adiaaida** [comment]
It looks like my issue might be that require_built_core_root is set as true, which requires the directory to already exist. I've got a change that I hope will handle this.

**Pull request merged**
