### PR TITLE
Update Viewing JIT dumps to 2.0 and csproj

### PR DESCRIPTION
**Pull request by svick**
CC: @jamesqo, @AndyAyersMS

### CODE REVIEW

**Comment by hseok-oh** [comment]
@dotnet-bot test Ubuntu arm Cross Release Build

**Comment by benaadams** [comment]
I think you need a 
`<RuntimeFrameworkVersion>2.0.0-*</RuntimeFrameworkVersion>`
in the csproj also?

**Comment by svick** [comment]
@benaadams Why should that be necessary? The guide as written (with my modifications) works for me.

**Comment by benaadams** [comment]
I get this without it
```
Restoring packages for C:\GitHub\protobuf-net\src\TheAwaitingGame\TheAwaitingGame.csproj...
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : 
Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0)' for '.NETCoreApp,Version=v2.0'. [C:\GitHub\protobuf-net\src\TheAwaitingGame\TheAwaitingGame.csproj]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : 
Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0)' for '.NETCoreApp,Version=v2.0 (win10-x64)'. [C:\GitHub\protobuf-net\src\TheAwaitingGame\TheAwaitingGame.csproj]
```
Which is a pretty weird error, it must be said 😄

**Comment by benaadams** [comment]
Also says it in the dogfooding instructions https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md#option-1-framework-dependent

**Comment by benaadams** [comment]
Following instructions step by step to see how it goes

**Comment by benaadams** [comment]
Wow, take it all back... that works better than what I'm doing now!

😄

**Comment by benaadams** [comment]
LGTM

**Comment by AndyAyersMS** [comment]
Thanks for updating this.

**Comment by omariom** [comment]
@svick Thanks 👍

**Comment by benaadams** [comment]
As aside dogfooding needs to be updated to match the project settings here https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md#option-1-framework-dependent

This is so much less painful; everything has come together again 😄

**Pull request merged**
