### PR TITLE
[CI] [Linux/x86] Change os name to test in dev/unix_test_workflow

### PR DESCRIPTION
**Pull request by hseok-oh**
In dev/unix_test_workflow, only Ubuntu16.04 is used to test ubuntu.
To test Linux/x86 correctly, this commit change os name for linux/x86 from Ubuntu to Ubuntu16.04.

### CODE REVIEW

**Comment by hseok-oh** [comment]
#13786 (#12897) was not tested correctly because of os name. 

cc/ @jashook

**Comment by jashook** [comment]
@dotnet-bot test CI please

**Comment by jashook** [comment]
@hseok-oh let me know how testing goes.

**Comment by jashook** [comment]
Also let me know if you need any help or when the pr is ready for master.

Thanks!

**Comment by hseok-oh** [comment]
@jashook Thanks for your help.

**Comment by philippweidhas** [comment]
Hi im actually looking for a possibility to run .Net Core on 32 Bit Linux. Could you gave me a short Answer how realistic the chances are to get it working with the current status? I would like to understand how far you have come with your efforts. Greetings Philipp

**Comment by hseok-oh** [comment]
@philippweidhas Please make new issue to discuss your questions. Then many people can join that discussion to answer your questions.. And here is not a proper area to discuss that.

**Comment by philippweidhas** [comment]
#14431

**Pull request merged**
