### PR TITLE
Extra semicolons left at the end of Combine function taking 4 paths.

### PR DESCRIPTION
**Pull request by Anipik**
Related PR- https://github.com/dotnet/corefx/pull/26940

### CODE REVIEW

**Comment by Anipik** [comment]
```
11:52:32 Fetching upstream changes from https://github.com/dotnet/coreclr
11:52:32  > git --version # timeout=10
11:52:32  > git fetch --tags --progress https://github.com/dotnet/coreclr +refs/heads/*:refs/remotes/origin/* # timeout=90
11:52:32 
ERROR: Error cloning remote repo 'origin'
11:52:32 hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/dotnet/coreclr +refs/heads/*:refs/remotes/origin/*" returned status code 128:
11:52:32 stdout: 
11:52:32 stderr: fatal: unable to access 'https://github.com/dotnet/coreclr/': Peer reports incompatible or unsupported protocol version.
11:52:32 
11:52:32 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1924)
11:52:32 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1643)
11:52:32 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:71)
11:52:32 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:352)
11:52:32 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:559)
11:52:32 	at org.jenkinsci.plugins.
```
@dotnet/dnceng can someone take a look ?

**Comment by JeremyKuhne** [comment]
@dotnet-bot help

**Comment by MattGal** [comment]
@Anipik GitHub randomly failing seems unlikely to repro and Jeremy's comment just invalidated all the other jobs anyways, let's revisit this if it reproduces.

**Comment by JeremyKuhne** [comment]
Ugh, sorry, was looking for the CoreFX test build, which I've forgotten the command for. I don't seem to be picking it out of the list either...

**Comment by Anipik** [comment]
@dotnet-bot test this please

**Comment by JeremyKuhne** [comment]
@Anipik The correct line is `Windows_NT x64 Checked corefx_baseline` or `Ubuntu x64 Checked corefx_baseline` to kick of test runs against the CoreFX tests. These CI's were busted a few days ago apparently, so I'm not sure if you'll get good results. Ideally you'd count on these.

I'm fine with the changes, I'm assuming that you've validated them against CoreFX locally.

**Comment by Anipik** [comment]
Yeah I validated them locally for windows 
@dotnet-bot test Windows_NT x64 Checked corefx_baseline
@dotnet-bot test Ubuntu x64 Checked corefx_baseline

**Pull request merged**
