### PR TITLE
Move TimerQueue.TickCount Windows implementation to shared CoreLib

### PR DESCRIPTION
**Pull request by filipnavara**
Counter-part to https://github.com/dotnet/corert/pull/7273.

/cc @jkotas @marek-safar

### CODE REVIEW

**Comment by safern** [comment]
> @Anipik @safern Could you please take a look at the CoreLib mirror?

Yep, we're taking a look. Fixing merge conflicts was a little bit painful so we did some minor fixes in the mirror and we just need to restart it.

**Comment by filipnavara** [comment]
@Anipik @safern The mirror didn't pick this up after the merge :/

**Comment by safern** [comment]
> @Anipik @safern The mirror didn't pick this up after the merge :/

I think there is still a PR open from the mirror, which needs to be merged for the mirror to pick it up.

**Comment by filipnavara** [comment]
> I think there is still a PR open from the mirror, which needs to be merged for the mirror to pick it up.

That would be the most invisible PR ever :) None are pending on Mono or CoreRT.

**Comment by safern** [comment]
🤣 it was merged yesterday around the same time this one was merged, missed the merge 😄 -- https://github.com/dotnet/corert/pull/7277 (taking a look at the mirror).

**Comment by Anipik** [comment]
@filipnavara its picked up by the corefx mirror https://github.com/dotnet/corefx/pull/36796
I will add these commit to mirror prs after the current open mirror prs are merged

**Comment by filipnavara** [comment]
@Anipik All PRs are merged now (CoreFX, CoreCLR, Mono and CoreRT) as far as I can see.

**Comment by Anipik** [comment]
@filipnavara I just open the pr containg this commit for corert and mono as well. Sry for the delay

**Comment by filipnavara** [comment]
@Anipik Thanks. I think https://github.com/dotnet/coreclr/pull/23737 was missed by the mirror though.

**Comment by Anipik** [comment]
@filipnavara yes mirror was broken for some time due to the nullable prs. there are some more missing commits. i am working on making all the repos consistent again

**Comment by filipnavara** [comment]
Thanks. This linked one landed at around the same time as this one. Both have counter-part PRs on the CoreRT side that have to be cherry-picked for landing the merge commits. I know the merge PRs will create conflicts so I want to make sure it's minimised as much as possible.

**Comment by Anipik** [comment]
@filipnavara I closed the current pr to add #23737 and some other missing commits. I have opened the pr in corert and I will do same thing for mono

**Pull request merged**
