### PR TITLE
Use packages.builds when generating nuget packages

### PR DESCRIPTION
**Pull request by wtgodbe**
https://github.com/dotnet/coreclr/issues/6610#event-745798205

CC @gkhanna79 @Priya91

### CODE REVIEW

**Comment by gkhanna79** [comment]
LGTM - please do a test VSO build to confirm it works as expected for building/publishing packages.

**Comment by wtgodbe** [comment]
@gkhanna79 setting that up now

**Comment by Priya91** [comment]
LGTM

**Comment by wtgodbe** [comment]
VSO builds look good.

**Comment by weshaggard** [comment]
For consistency can we do this exactly like corefx? 
https://github.com/dotnet/corefx/blob/master/build-packages.cmd
https://github.com/dotnet/corefx/blob/master/build-packages.sh
https://github.com/dotnet/corefx/blob/master/config.json#L360

**Comment by wtgodbe** [comment]
@Priya91 is there any reason we can't do this (e.g. where do arch/configuration come from)?

**Comment by Priya91** [comment]
> is there any reason we can't do this (e.g. where do arch/configuration come from)?

Not sure what you meant.

@weshaggard Are you implying to change ```build-packages``` to ```packages``` alias under ```build``` command? We can do that. Although we can't move specifying -Project alias to config.json, because coreclr expects absolute paths (I caused build breaks in partner teams and arm64 builds when using relative paths), and we haven't figured out how we can use other property values in config.json. For ex, in config.json,
```
"Project" : "{__ProjectDir <get value of this property here>}\<path-to-project>"
```

**Comment by weshaggard** [comment]
@Priya91 I'm ok if we have a command where we specify the project (packages.builds) in the scripts if we cannot correctly configure that in the config.json file. However my biggest thing is to remove as much of the logic from the scripts as possible and let msbuild do most of the heavy lifting.

**Comment by danmosemsft** [comment]
@wtgodbe where do we stand on this one?

**Comment by wtgodbe** [comment]
@danmosemsft huh, I thought I had already merged this. I think we should be fine to merge it now.

@dotnet-bot test this please

**Comment by danmosemsft** [comment]
@wtgodbe go ahead ;)

**Pull request merged**
