### PR TITLE
Fixed ChunkEnumerator.Current NRE

### PR DESCRIPTION
**Pull request by bbartels**
Fixes https://github.com/dotnet/corefx/issues/36973

To keep in line with IEnumerable behaviour, ChunkEnumerator should throw an InvalidOperationException as well, if MoveNext() has not been called yet.

```csharp
public static void Main(string[] args)
{
    var sb = new StringBuilder();
    sb.Insert(0, new [] {'t', 'e', 's', 't'});
    var enumerator = sb.GetChunks();
    Console.WriteLine(enumerator.Current);
}
```

Before:

`Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Text.StringBuilder.ChunkEnumerator.get_Current()
   at ConsoleApp.Program.Main(String[] args) in C:\repos\ConsoleApp\Program.cs:line 19`

After:

`Unhandled Exception: System.InvalidOperationException: Enumeration has either not started or has already finished.
   at System.Text.StringBuilder.ChunkEnumerator.get_Current()
   at ConsoleApp.Program.Main(String[] args) in C:\repos\ConsoleApp\Program.cs:line 19
`

### CODE REVIEW

**Comment by safern** [comment]
We just merged from NullableFeature branch into master, hence the merge conflicts. Would you mind fixing the conflicts and respecting the nullable annotations. Please let me know if you need help for that :smile:

**Comment by bbartels** [comment]
What is the default way of dealing with ThrowHelpers and Nullable? Flow analysis doesn't seem to detect that ThrowHelpers is throwing in any case.

```csharp
public ReadOnlyMemory<char> Current
{
    get
    {
        if (_currentChunk == null)
        {
            ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumOpCantHappen();
        }
        // Flow analysis doesn't detect _currentChunk is non-null
        return new ReadOnlyMemory<char>(_currentChunk.m_ChunkChars, 0, _currentChunk.m_ChunkLength);
    }
}
```

**Comment by safern** [comment]
Yes, the problem is because the compiler doesn't have a way to know that `ThrowHelper` will never return, therfore it is not enough for it to know that `_currentChunk` is not `null`. 

You will need to use a `!` when accessing `_currentChunk` -- i.e:
```diff
public ReadOnlyMemory<char> Current
{
    get
    {
        if (_currentChunk == null)
        {
            // Always throws
            ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumOpCantHappen();
        }
         // Flow analysis doesn't detect _currentChunk is non-null
-        return new ReadOnlyMemory<char>(_currentChunk.m_ChunkChars, 0, _currentChunk.m_ChunkLength);
+       return new ReadOnlyMemory<char>(_currentChunk!.m_ChunkChars, 0, _currentChunk.m_ChunkLength); // TODO-NULLABLE: https://github.com/dotnet/roslyn/issues/26761
    }
}
```

Could you also include the TODO-NULLABLE comment at the end? That way we track whenever there is an attribute available to tell the compiler that `ThrowHelper` will not return, we revisit this and remove the unnecessary `!`.

The reason why you only need 1 `!` here is because the compiler understand you already suppressed the warning, so it will not warn for another access to `_currentChunk` under the same tree.

**Comment by bbartels** [comment]
> Yes, the problem is because the compiler doesn't have a way to know that `ThrowHelper` will never return, therfore it is not enough for it to know that `_currentChunk` is not `null`.
> 
> You will need to use a `!` when accessing `_currentChunk` -- i.e:
> 
> ```diff
> public ReadOnlyMemory<char> Current
> {
>     get
>     {
>         if (_currentChunk == null)
>         {
>             // Always throws
>             ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumOpCantHappen();
>         }
>          // Flow analysis doesn't detect _currentChunk is non-null
> -        return new ReadOnlyMemory<char>(_currentChunk.m_ChunkChars, 0, _currentChunk.m_ChunkLength);
> +       return new ReadOnlyMemory<char>(_currentChunk!.m_ChunkChars, 0, _currentChunk.m_ChunkLength); // TODO-NULLABLE: https://github.com/dotnet/roslyn/issues/26761
>     }
> }
> ```
> 
> Could you also include the TODO-NULLABLE comment at the end? That way we track whenever there is an attribute available to tell the compiler that `ThrowHelper` will not return, we revisit this and remove the unnecessary `!`.
> 
> The reason why you only need 1 `!` here is because the compiler understand you already suppressed the warning, so it will not warn for another access to `_currentChunk` under the same tree.

Ah that makes sense, thanks for the explanation!
Should be fine now!

**Comment by stephentoub** [comment]
Nit: that particular TODO-NULLABLE should mention https://github.com/dotnet/csharplang/issues/538 instead.

**Comment by bbartels** [comment]
> Nit: that particular TODO-NULLABLE should mention [dotnet/csharplang#538](https://github.com/dotnet/csharplang/issues/538) instead.

The one @safern provided seems to have been used in the same context throughout the file though.
https://github.com/dotnet/coreclr/blob/91afda39f4575151756d85568352cb063df97ef1/src/System.Private.CoreLib/shared/System/Text/StringBuilder.cs#L1937-L1939

**Comment by danmosemsft** [comment]
Thanks. Is there a PR in corefx to test this?

**Pull request merged**
