### PR TITLE
Disable min_opt and tiered jit permutations on the release branch.

### PR DESCRIPTION
**Pull request by jorive**

### CODE REVIEW

**Comment by adiaaida** [comment]
@dotnet-bot test ci please

**Comment by AndyAyersMS** [comment]
I would appreciate it if you would describe the motivation for this change.

**Comment by adiaaida** [comment]
@AndyAyersMS Essentially, we want to minimize the number of configurations that we test in the release branches (this is going to release/2.1). In master, it's important to track various configurations because things are active, but in the release branches, things are relatively constant (not many changes come in and there's no active development), so we don't need to maintain perf testing for more configurations than the ones we are actually releasing.

**Comment by jorive** [comment]
@dotnet-bot test ci please

**Pull request merged**
