### PR TITLE
Hoist calls to IsBitwiseEquatable

### PR DESCRIPTION
**Pull request by jkotas**
Smaller IL is easier for JIT

### CODE REVIEW

**Comment by jkotas** [comment]
cc @GrabYourPitchforks

**Comment by jkotas** [comment]
Easier to review with: https://github.com/dotnet/coreclr/pull/23381/files?w=1

**Comment by GrabYourPitchforks** [comment]
Does it matter that `IsBitwiseEquatable` is called before `Unsafe.SizeOf` now in these methods? Consider the line below.

```cs
if (Unsafe.SizeOf<T>() == sizeof(byte) && RuntimeHelpers.IsBitwiseEquatable<T>()) { /* ... */ }
```

In particular, if _T_ is a reference type or contains references, it must by construction be at least the size of a pointer. This means that the first clause in this if statement would be _false_, which perhaps would've kept the JIT from ever trying to call `IsBitwiseEquatable` with the reference type _T_.

In all honestly I don't know the answer to this, but I wanted to raise it as a potential concern, especially given how the JIT treats reference types _T_ when used as generic type parameters.

**Comment by jkotas** [comment]
Here is what happens in the JIT today:
1. The JIT imports the main method body. It just sees calls to `Unsafe.SizeOf` and `IsBitwiseEquatable` while doing so. It does not know yet what these methods do.
2. The JIT inlines all methods worth inlining. All calls to `Unsafe.SizeOf` and `IsBitwiseEquatable` are inlined.
3. The JIT runs optimizations on the whole grapth. It is where the unreachable code elimination finally happens. Majority of work done in 1 and 2 is thrown away as dead code.

This change reduces how much gets inlined in step 2 a bit.

**Pull request merged**
