### PR TITLE
Use absolute paths for specifying projects to build.

### PR DESCRIPTION
**Pull request by Priya91**
cc @jashook

### CODE REVIEW

**Comment by Priya91** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 debug

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 checked

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 release

**Comment by kyulee1** [comment]
LGTM. Let's merge after test results come back though.

**Comment by briansull** [comment]
LGTM. Good to merge after test results come back.

**Comment by jashook** [comment]
@mmitche why are we timing out sending notifications to Jared Parson's server?

13:11:22 ERROR: Failed to notify endpoint 'HTTP:https://jaredpar.azurewebsites.net/api/BuildEvent?code=tts2pvyelahoiliwu7lo6flxr8ps9kaip4hyr4m0ofa3o3l3di77tzcdpk22kf9gex5m6cbrcnmi'
13:11:22 java.net.SocketTimeoutException: Read timed out
13:11:22 	at java.net.SocketInputStream.socketRead0(Native Method)
13:11:22 	at java.net.SocketInputStream.read(SocketInputStream.java:152)
13:11:22 	at java.net.SocketInputStream.read(SocketInputStream.java:122)
13:11:22 	at sun.security.ssl.InputRecord.readFully(InputRecord.java:442)
13:11:22 	at sun.security.ssl.InputRecord.read(InputRecord.java:480)
13:11:22 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:946)
13:11:22 	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:903)
13:11:22 	at sun.security.ssl.AppInputStream.read(AppInputStream.java:102)
13:11:22 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
13:11:22 	at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
13:11:22 	at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
13:11:22 	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:690)
13:11:22 	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:633)
13:11:22 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1325)
13:11:22 	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
13:11:22 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
13:11:22 	at com.tikal.hudson.plugins.notification.Protocol$3.send(Protocol.java:115)
13:11:22 	at com.tikal.hudson.plugins.notification.Phase.handle(Phase.java:45)
13:11:22 	at com.tikal.hudson.plugins.notification.JobListener.onStarted(JobListener.java:31)
13:11:22 	at hudson.model.listeners.RunListener.fireStarted(RunListener.java:215)
13:11:22 	at hudson.model.Run.execute(Run.java:1734)
13:11:22 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
13:11:22 	at hudson.model.ResourceController.execute(ResourceController.java:98)
13:11:22 	at hudson.model.Executor.run(Executor.java:410)

**Comment by jashook** [comment]
@mmitche correct, the question is why is it timing out?

**Comment by mmitche** [comment]
I haven't the faintest, but the rest seemed to not time out.  So...maybe a momentary hiccup in the web service?

**Comment by briansull** [comment]
These two failure  are unrelated to this fix for the build break, so IMO you can go ahead and merge.

There are two tests failing on Arm64 with this assertion:
"C:\Users\DDJOIN\scratch\corerun.exe" CscBench.exe Assert failure(PID 8572 [0x0000217c], Thread: 17720 [0x4538]): Assertion failed '((consume == 0) && (produce == 0)) || (ComputeAvailableSrcCount(tree) == consume)' in 'Microsoft.Cci.PeWriter:WritePeToStream(ref,ref,ref,ref):bool:this' (IL size 908) File: d:\j\workspace\arm64_cross_c---f41ee988\src\jit\lsra.cpp Line: 3311 Image: C:\Users\DDJOIN\scratch\CoreRun.exe

**Comment by kyulee1** [comment]
Yep. I created an issue https://github.com/dotnet/coreclr/issues/6583. You can merge it.

**Pull request merged**
