### PR TITLE
Remove test exclusions for tests that now pass

### PR DESCRIPTION
**Pull request by adiaaida**
This change removes tests that have been fixed for x86 RyuJIT. It also
updates the Issues for the remaining tests with additional details.

### CODE REVIEW

**Comment by adiaaida** [comment]
@pgavlin PTAL
/cc: @dotnet/jit-contrib 

Note: We probably need to open an issue for the mismatch32 and mismatch64 failures.

**Comment by AndyAyersMS** [comment]
@adiaaida I wrote those two tests so you can assign the issue to me.

**Comment by adiaaida** [comment]
@AndyAyersMS Thanks.  Assigned #8152 to you.

**Comment by pgavlin** [comment]
LGTM

**Pull request merged**
