### PR TITLE
Remove release only check.

### PR DESCRIPTION
**Pull request by jashook**
Allows debug and checked builds to run tests on arm64 machines.

@mmitche @briansull PTAL

### CODE REVIEW

**Comment by jashook** [comment]
@dotnet-bot test ci please

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64

**Comment by jashook** [comment]
@mmitche PTAL

**Comment by jashook** [comment]
@adiaaida PTAL

**Comment by adiaaida** [comment]
LGTM

**Pull request merged**
