### PR TITLE
Introduce additional type forwards for mscorlib.

### PR DESCRIPTION
**Pull request by AlexGhiondea**
The new types are being forwarded to the types in the new implementation assembly.

### CODE REVIEW

**Comment by mjsabby** [comment]
@AlexGhiondea If possible I'd pick an entire assembly rather than just a few types. For example you can imagine the slight confusion that SymmetricAlgorithm is there but Assymetric is not.

That said, Bing's use case for the RTM is covered by that.

A couple more that are there, 

System.Security.Claims assembly types --> Claim, ClaimTypes, ClaimsIdentity, ClaimsPrincipal

**Comment by AlexGhiondea** [comment]
@dotnet-bot please test OSX x64 Checked Build and Test

**Comment by gkhanna79** [comment]
@AlexGhiondea Are you taking this for RTM?

**Comment by mjsabby** [comment]
@AlexGhiondea you'll have a separate change for the System.Security.Claims?

**Comment by AlexGhiondea** [comment]
This needs a couple changes in the internal build so I will make the change directly there.

**Pull request closed without merging**
