### PR TITLE
Use DynamicSecurityMethod attribute to mark methods with StackCrawlMark

### LINKED ISSUE #8102: Enable callers of S.P.CoreLib NoInlining methods to inline.
Currently, methods that are marked with `NoInlining` within S.P.CoreLib are assumed to contain a StackCrawlMark local variable. Because of this, it is assumed it is not safe to inline the caller, which can unnecessarily degrade performance under certain circumstances where StackCrawlMark is not being used. There needs to be a better way for identifying `StackCrawlMark` methods so we can overcome this limitation.

Moved from #7449

### PR DESCRIPTION
**Pull request by jkotas**
CoreCLR does not have CAS, and so we can conveniently use it to mark methods with StackCrawlMark to
decouple it from NoInlining. The original purpose of DynamicSecurityMethod was to disable inlining
of the caller and to insert CAS security checks, so we are basically just keeping the first part.

Fixes #8102

### CODE REVIEW

**Comment by benaadams** [comment]
@dotnet-bot test Windows_NT arm64 Cross Debug Build

**Comment by stephentoub** [comment]
This error message that was fixed yesterday by @AndyAyersMS is now wrong, again, right?
https://github.com/dotnet/coreclr/pull/9470/files#diff-edc46b80f57431489a82311948a8234dR6522

**Comment by benaadams** [comment]
I feel I should ask if the Jit changes will break on desktop; but have no idea about the relationship between the code bases to know if that's a valid question.

**Comment by jkotas** [comment]
The part shared with desktop is https://github.com/dotnet/coreclr/tree/master/src/jit . There are no changes in this part.

**Comment by jkotas** [comment]
> This error message that was fixed yesterday by @AndyAyersMS is now wrong, again, right?

Yes, the original message was more accurate. I will revert it.

**Comment by AndyAyersMS** [comment]
LGTM. Nice to have this finally ironed out.

**Comment by jamesqo** [comment]
Nice! This will be useful in a bunch of places, e.g. `Char` to separate out the uncommon path so the more used one can be inlined.

**Pull request merged**
