### PR TITLE
Fix GC info for `ByReference<T>`

### PR DESCRIPTION
**Pull request by kouvel**
When `ByRefernece<T>` is directly on the stack, not inside a `Span<T>`, ComputeGCLayout was missing to include in the GC info. This was causing many span tests to fail in GCStress=c mode.

### CODE REVIEW

**Comment by kouvel** [comment]
@jkotas, this fixes deterministic GCStress issues I've seen on x64 and x86, but there are still nondeterminitic GCStress=c issues on x86 which I haven't figured out yet.

**Comment by jkotas** [comment]
failing to crossgen mscorlib on Windows arm - I guess the arm JIT has a problem with handling the correct GC info

**Comment by jkotas** [comment]
LGTM otherwise. Thanks!

**Comment by kouvel** [comment]
Hmm I can't find the log file saved anywhere. I'll try a rerun to make sure it's consistent.

**Comment by kouvel** [comment]
@sivarv, please take a look at the second commit and let me know if it tests ok

**Comment by kouvel** [comment]
@sivarv, I have changed the fix to what you have suggested. This one also works on cross arm crossgen, and looks like it does not generate write barrier on x64.

**Comment by sivarv** [comment]
Looks good to me.
CC @briansull and @dotnet/jit-contrib  - please review gcinfo.cpp change.

**Comment by sivarv** [comment]
I have verified that gcinfo.cpp change no SPMI diffs on desktop framework assemblies.

**Comment by kouvel** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test

**Comment by kouvel** [comment]
@sivarv, should I wait for more reviews, or can this be satisfactorily be merged once the tests pass?

**Pull request merged**
