### PR TITLE
Delete mscorlib facade

### LINKED ISSUE #7607: Move mscorlib facade from CoreCLR to CoreFX
cc: @jkotas @weshaggard 

Today we version mscorlib and System.Private.CoreLib as netstandard1.0 which means that we use the same two dlls across different frameworks (i.e. netcoreapp1.0 and netcoreapp1.1). This started being an issue since PR #7578 caused the mscorlib facade to type forward some types to System.IO. The problem with that, is that in netcoreapp1.0 world, System.IO.dll implementation type-forwards System.IO.Stream to mscorlib.dll facade, which used to type-forward it System.Private.CoreLib.dll where the implementation lives, but that is not the case anymore, and it now type-forwards it back to System.IO causing a type not found.

```
Resolution of System.IO.Stream type
netcoreapp1.1: System.IO(v.4.2.0.0) -> System.Runtime(v.4.2.0.0) -> System.Private.CoreLib (type lives here)
netcoreapp1.0: System.IO(v.4.1.0.0) -> mscorlib -> System.IO(v.4.1.0)....
```

This causes:

```
Unhandled Exception: System.TypeLoadException: Could not load type 'System.IO.Stream' from assembly 'System.IO, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

This would get fixed if we version the mscorlib facade

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #7607

### CODE REVIEW

**Comment by jkotas** [comment]
cc @AlexGhiondea @danmosemsft 

There may still be things that need fixing ...

**Comment by danmosemsft** [comment]
@weshaggard pointed out the CLR tests use it, unless @RussKeldorph made the change that we were talking about to refer to the CoreFX package. Will CI show that if it's the case?

**Comment by danmosemsft** [comment]
LGTM. Is it worth a grep for other references to "mscorlib" in the repo? There are also mscorlib.shared.sources.props, src\mscorlib.Friends.cs etc. Very optional...

**Comment by jkotas** [comment]
> Is it worth a grep for other references to "mscorlib" in the repo?

Agree. Number of these should be renamed ... e.g. the top level directory should be renamed to S.P.CoreLib, but it would make for interesting conflict with your cleanup changes ...

**Comment by danmosemsft** [comment]
`cp: cannot stat ‘./bin/Product/Linux.armel.Debug/mscorlib.dll’: No such file or directory`

you missed
`https://github.com/dotnet/coreclr/blob/165fa5cebf0b937f74855584ca5b658e7e83c41b/tests/scripts/arm32_ci_script.sh#L250`

**Comment by jkotas** [comment]
Waiting for https://github.com/dotnet/corefx/pull/15643 to propagate through the system

**Comment by danmosemsft** [comment]
I believe this is blocked on @wtgodbe https://github.com/dotnet/coreclr/issues/8937

**Comment by jkotas** [comment]
> I believe this is blocked on @wtgodbe #8937

Right.

**Comment by jkotas** [comment]
I will open a new PR once this is unblocked.

**Comment by wtgodbe** [comment]
Working on that right now, hoping to have a PR up today or tomorrow.

**Pull request closed without merging**
