### PR TITLE
Introduce REGDISPLAY_BASE

### LINKED ISSUE #8643: Introduce a base class for REGDISPLAY
While bring up x86/Linux, I found that the current definition of ``REGDISPLAY`` has several duplicated code  (especially code related with ``WIN64EXCEPTIONS``).

It would be better to introduce a base class to remove such code duplication.

### PR DESCRIPTION
**Pull request by parjong**
This PR introduces REGDISPLAY_BASE as a common base for REGDISPLAY in order to fix #8643.

### CODE REVIEW

**Comment by parjong** [comment]
@jkotas @janvorli Please take a look.

**Comment by parjong** [comment]
@janvorli Could you let me know if there is a problem with this PR?

**Comment by janvorli** [comment]
@parjong no, there is no problem. I just went to bed yesterday when the CI was still running and today it went out of my radar.

**Comment by parjong** [comment]
@janvorli Thank you! I wish that Github will introduce merge if test passes...

**Pull request merged**
