### PR TITLE
Format spmi sources with clang-format

### PR DESCRIPTION
**Pull request by sandreenko**
The jit style was used.
My GitHub application was not able to pack all changes into one commit. It is why I separated them by folders.

### CODE REVIEW

**Comment by sandreenko** [comment]
PTAL @BruceForstall, cc @dotnet/jit-contrib

**Comment by jashook** [comment]
Are we going to be auto formatting the toolbox directory going forward?

**Comment by sandreenko** [comment]
> Are we going to be auto formatting the toolbox directory going forward?

As I understand it is possible to add spmi or toolbox folders into jit-format list, but I am not familiar enough with jit-format source code.

**Comment by BruceForstall** [comment]
> Are we going to be auto formatting the toolbox directory going forward?

I see no need to do that.

**Pull request merged**
