### PR TITLE
Use C++ ranged 'for' for AllSuccessorIter use

### PR DESCRIPTION
**Pull request by BruceForstall**

### CODE REVIEW

**Comment by mikedn** [comment]
Side-question: What do you think about using range for to iterate over basic blocks and statements?

**Comment by BruceForstall** [comment]
> Side-question: What do you think about using range for to iterate over basic blocks and statements?

As long as it's simple, easy-to-understand, and as performant, then great!

We have foreach_block and foreach_treenode_execution_order macros, but it would be nicer to use built-in language constructs. (Note that it was only recently that we didn't have to worry about older compilers that didn't support ranged-for, which is why we have those macros in the first place.)

**Comment by BruceForstall** [comment]
@swgillespie 2 GC tests failed in "Windows_NT x64 Debug Build and Test":
```
GC_LargeMemory._API_gc_gettotalmemory_gettotalmemory_._API_gc_gettotalmemory_gettotalmemory_cmd
GC_Regressions._v2_0_beta1_149926_149926_149926_._v2_0_beta1_149926_149926_149926_cmd
```
with:
```
Large Memory Machine required
and:
OOM while allocating a byte array of size 16774256
```

why? Is there some kind of infrastructure or test flakiness here?

**Comment by mikedn** [comment]
> As long as it's simple, easy-to-understand, and as performant, then great!

Yes, with one exception: one needs to be careful with iterating and editing the list at the same time. Oh well, I'll try it and see how it looks.

**Comment by swgillespie** [comment]
@BruceForstall I've never seen those two fail in that way before, I'll take a look.

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by BruceForstall** [comment]
@pgavlin PTAL
cc @dotnet/jit-contrib

**Pull request merged**
