### PR TITLE
Disable RVA statics tests outside Windows.

### PR DESCRIPTION
**Pull request by pgavlin**
These tests are not supported in general and are already disabled
for Windows. Disable them for *nix as well.

### CODE REVIEW

**Comment by pgavlin** [comment]
@jashook @RussKeldorph PTAL

**Comment by RussKeldorph** [comment]
I'd prefer to use testsFailingOutsideWindows.txt for now since I believe they still need some work.  I believe rvastatics are supposed to be supported as read-only in non-R2R.  However, I'm fine with this change as is, though, since there is little practical difference and hopefully it will go away soon.

LGTM.

**Comment by jashook** [comment]
lgtm

**Comment by pgavlin** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Comment by pgavlin** [comment]
The previous Ubuntu failure may be interesting, but is unrelated to this change: http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/checked_ubuntu_tst_prtest/2321/consoleFull

cc @gkhanna79 @janvorli

**Comment by gkhanna79** [comment]
@dotnet-bot test Ubuntu Checked pri1r2r please

**Comment by pgavlin** [comment]
I have verified that the intended tests are excluded. The other failures in the R2R job are already under investigation.

**Comment by gkhanna79** [comment]
Ported to release as well?

**Comment by pgavlin** [comment]
Working on it.

**Pull request merged**
