### PR TITLE
Disable Automatic PR Perf Jobs

### PR DESCRIPTION
**Pull request by brianrob**
Due to the current throughput issues, we are disabling automatic performance PR jobs.

They will still run post-merge and can be requested via trigger phrase.

These will be back once throughput issues are addressed.

Filed #15175 to bring these runs back.

cc: @valenis, @adiaaida

### CODE REVIEW

**Comment by brianrob** [comment]
@dotnet-bot test ci please

**Comment by adiaaida** [comment]
Can we actually just change it to use triggerPipelineOnGithubPRComment?

**Comment by brianrob** [comment]
@adiaaida, sorry I missed that this was commented out.  I've updated this now.

**Comment by brianrob** [comment]
@dotnet-bot test ci please

**Pull request merged**
