### PR TITLE
Release/2.0.0 - Make EventArgs serializable

### PR DESCRIPTION
**Pull request by ViktorHofer**
Relates to https://github.com/dotnet/corefx/issues/25930

### CODE REVIEW

**Comment by danmosemsft** [comment]
It looks like some of these legs have never passed eg arm_cross_debug_windows_nt_prtest https://ci.dot.net/job/dotnet_coreclr/job/release_2.0.0/job/arm_cross_debug_windows_nt_prtest/
I don't understand why it ran.

@dotnet/dnceng some failures are due to insufficient page file? 
https://ci.dot.net/job/dotnet_coreclr/job/release_2.0.0/job/x64_release_windows_nt_pri1_prtest/531/testReport/junit/Regressions_coreclr/_0014_avtest_avtest_/_0014_avtest_avtest_cmd/

**Comment by maririos** [comment]
@danmosemsft issue https://github.com/dotnet/core-eng/issues/2324 created

**Comment by danmosemsft** [comment]
@dotnet-bot test this please

**Comment by ViktorHofer** [comment]
I wouldn't wait for the arm legs to pass as this change is minor but as it hasn't yet been approved by shiproom we can't merge either.

**Comment by danmosemsft** [comment]
I agree to not wait for the ARM legs.

**Pull request merged**
