### PR TITLE
Fixing Michal's fork of CPAOT to CoreCLR

### PR DESCRIPTION
**Pull request by trylek**

### CODE REVIEW

**Comment by trylek** [comment]
For reference: https://github.com/dotnet/coreclr/pull/26513

**Comment by MichalStrehovsky** [comment]
Thank you so much for investigating and fixing it Tomas! I've cherry picked your commit into #26513 and refreshed the CoreRT sources commit to include David's change from Friday. If the CI is green, hopefully we'll be able to merge soon.

**Comment by trylek** [comment]
Closing the review as it has fulfilled its validation role and Michal has cherry-picked the CoreFX.depproj script change into his mainline change.

**Pull request closed without merging**
