### PR TITLE
Update build docker images to enable NUMA  support

### PR DESCRIPTION
**Pull request by janvorli**
So far, the NUMA support for Linux was disabled due to the fact that the
build docker images didn't have libnuma development package installed.
This change updates the images to ones that have the libnuma added that
were created recently.

### CODE REVIEW

**Comment by echesakovMSFT** [comment]
@janvorli Just to confirm - your change affects **all** Linux Docker images?

**Comment by janvorli** [comment]
@echesakovMSFT  My recent change to add the libnuma to docker images affected all the Linux docker images except of ubuntu 16.04 and debian 9 images for arm32 (where the package is not present for some reason).
However, the new Ubuntu 14.04 arm32 image has broken crossrootfs for arm for some reason, so I am going to investigate that. It seems it is the same issue as https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/120.
In fact, there is something strange going on with the new images and they all seem to fail during the build for various reasons. So I need to look into all of those.

**Comment by jashook** [comment]
Note that the change looks good but the docker images seem to be incorrectly setup.

See:

https://dev.azure.com/dnceng/public/_build/results?buildId=193000

```
Linking C executable cmTryCompileExec950536467

  /usr/bin/cmake -E cmake_link_script
  CMakeFiles/cmTryCompileExec950536467.dir/link.txt --verbose=1

  /usr/bin/clang-5.0 -Wall -std=c11 --sysroot=/crossrootfs/arm
  --gcc-toolchain=/crossrootfs/arm/usr --target=arm-linux-gnueabihf
  CMakeFiles/cmTryCompileExec950536467.dir/testCCompiler.c.o -o
  cmTryCompileExec950536467 -rdynamic

  /usr/bin/arm-linux-gnueabihf-ld: cannot find crt1.o: No such file or
  directory

  /usr/bin/arm-linux-gnueabihf-ld: cannot find crti.o: No such file or
  directory

  /usr/bin/arm-linux-gnueabihf-ld: cannot find crtbegin.o: No such file or
  directory

  /usr/bin/arm-linux-gnueabihf-ld: cannot find -lgcc

  /usr/bin/arm-linux-gnueabihf-ld: cannot find -lgcc_s

  /usr/bin/arm-linux-gnueabihf-ld: cannot find -lc

  /usr/bin/arm-linux-gnueabihf-ld: cannot find -lgcc

  /usr/bin/arm-linux-gnueabihf-ld: cannot find -lgcc_s

  /usr/bin/arm-linux-gnueabihf-ld: cannot find crtend.o: No such file or
  directory

  /usr/bin/arm-linux-gnueabihf-ld: cannot find crtn.o: No such file or
  directory

  clang: error: linker command failed with exit code 1 (use -v to see
  invocation)

  make[1]: *** [cmTryCompileExec950536467] Error 1

  make[1]: Leaving directory
  `/__w/1/s/bin/obj/Linux.arm.Checked/CMakeFiles/CMakeTmp'

  make: *** [cmTryCompileExec950536467/fast] Error 2
```

**Comment by janvorli** [comment]
> the docker images seem to be incorrectly setup

Yes, I was looking into it last week, issue was identified and a fix should be made soon. See https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/120

**Pull request merged**
