### PR TITLE
Assorted fixes for VS2015 build breaks

### PR DESCRIPTION
**Pull request by jkotas**
I have done builds using VS2015 with different settings in different environment and fixed all build breaks that I have run into.

This is first batch of the fixes.

### CODE REVIEW

**Comment by DickvdBrink** [comment]
Does this fix https://github.com/dotnet/coreclr/issues/1033?

**Comment by jkotas** [comment]
@DickvdBrink 

I have just split the commit into two parts.

**Comment by janvorli** [comment]
LGTM

**Comment by jasonwilliams200OK** [comment]
Would it be a good idea to set default to vs2015 at [build.cmd#L9-L11](https://github.com/dotnet/coreclr/blob/f24a985a6f6d1eb64d16df26eb43c6e9ddac4e48/build.cmd#L9-L11)?

```bat
:: Default to VS2015
set __VSVersion=VS2015
set __VSProductVersion=140
```

**Comment by jkotas** [comment]
Yes, once it actually works...

**Comment by jkotas** [comment]
@jasonwilliams200OK The build scripts auto-detect the VS version now, and VS2015 build and tests should be fully functional. Let me know if you run into anything that is still broken...

**Comment by jasonwilliams200OK** [comment]
@jkotas, thanks for the heads-up, the build and tests succeeded! :congratulations: 

On Windows 10 with VS2015 installed using PowerShell (with `git` in `PATH`), I executed the following:

```powershell
git clone https://github.com/dotnet/coreclr ; cd .\coreclr ; .\build.cmd
```

After sometime, produces:

>
Repo successfully built.
>
Product binaries are available at C:\repos\coreclr\bin\Product\Windows_NT.x64.Debug
Test binaries are available at C:\repos\coreclr\bin\tests\Windows_NT.x64.Debug

**Pull request merged**
