### PR TITLE
Setting xunit package version info

### PR DESCRIPTION
**Pull request by dsgouda**
Since xunit package version is no longer specified in build tools, setting it in CoreCLR
Also modifying path to dotnet according to latest changes in build tools
@rahku @MattGal @lt72

### CODE REVIEW

**Comment by dsgouda** [comment]
@dotnet-bot Test CentOS7.1 x64 Debug Build and Test

**Comment by dsgouda** [comment]
@dotnet-bot Test Ubuntu x64 Checked Build and Test

**Comment by MattGal** [comment]
LGTM pending successful CI build

**Comment by dsgouda** [comment]
@dotnet-bot Test OSX x64 Checked Build and Test

**Comment by dsgouda** [comment]
@dotnet-bot Test Linux ARM Emulator Cross Release Build

**Comment by dsgouda** [comment]
@dotnet-bot Test  Linux ARM Emulator Cross Debug Build

**Comment by dsgouda** [comment]
@dotnet-bot Test Linux ARM Emulator Cross Release Build

**Comment by dsgouda** [comment]
@dotnet-bot Test  Linux ARM Emulator Cross Debug Build

**Comment by dsgouda** [comment]
@dotnet-bot Test CentOS7.1 x64 Debug Build and Test

**Comment by dsgouda** [comment]
@dotnet Test this

**Comment by dsgouda** [comment]
@dotnet-bot Test Ubuntu x64 Checked Build and Test

**Comment by dsgouda** [comment]
@dotnet-bot Test this

**Comment by dsgouda** [comment]
Updating Buildtools version seems to bring in changes that break CIs here. Even if XunitPerfAnalysisPackageVersion is not set under CoreCLR perf runs should not be affected since none of the related targets are invoked. 
However, will set this when current problems are fixed just to be on the safer side.

**Pull request closed without merging**
