### PR TITLE
Add IsFrozenObject Profiler API

### PR DESCRIPTION
**Pull request by mjsabby**
Fixes https://github.com/dotnet/coreclr/issues/24231.

### CODE REVIEW

**Comment by mjsabby** [comment]
Still not sure how to rerun only specific failures. I would imagine they are unrelated.

**Comment by mjsabby** [comment]
cc @Maoni0 @davmason @noahfalk

**Comment by davmason** [comment]
@mjsabby In the new infrastructure if you click on details you'll end up at a page like this: https://github.com/dotnet/coreclr/pull/24239/checks?check_run_id=111163045 and there will be a list of tests on the left hand side. There will be a re-run link next to the failing jobs. 

Your failure was because the linux leg had a test fail to build so I reset it.

**Comment by mjsabby** [comment]
@davmason I don't see it, maybe you can share a screenshot?

**Comment by davmason** [comment]
It might be a permissions thing since you're not on the runtime team then. Here is a screenshot from a different PR with a leg failing since yours no longer has the re-run link after I reset it


image

**Comment by mjsabby** [comment]
Yeah I don't have it. But maybe you reran it or someone did, so thank you!

**Comment by Maoni0** [comment]
btw I'm fine with adding these but I'm relying on diagnostics folks to decide whether this is ok from the API POV.

**Comment by mjsabby** [comment]
@Maoni0 both@davmason and @noahfalk have agreed on the issue or the PR.

**Pull request merged**
