### PR TITLE
Update ARM32 Cross Build Docker Image

### PR DESCRIPTION
**Pull request by brianrob**
Port #17819 to release/2.1 to fix LTTng tracing on arm32 Linux.

### CODE REVIEW

**Comment by brianrob** [comment]
@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test ("Agent went offline during the build")

**Comment by echesakovMSFT** [comment]
LGTM as soon it's get proper testing on top of release/2.1 (as suggested in #17819 this can be done in dev:unix_test_workflow)
Ask @jashook @BruceForstall for their opinions

**Comment by brianrob** [comment]
@dotnet-bot test ci

**Comment by brianrob** [comment]
Thanks @echesakovMSFT.  I will do the same validation I did for #17819.

**Comment by brianrob** [comment]
I used the CI test jobs to trigger https://ci.dot.net/job/dotnet_coreclr/job/release_2.1/job/GenPRTest/view/arm/job/arm_cross_checked_ubuntu/1, which has passed - this validates that the docker image was properly updated and that the build succeeded.

**Pull request merged**
