### PR TITLE
ARM64: Fix for recording SP for handler.

### PR DESCRIPTION
**Pull request by kyulee1**
Fixes https://github.com/dotnet/coreclr/issues/3701.

When GC occurs in a catch handler, we compare the current frame with the one
saved before the funclet was invoked.
The recorded SP address was wrong (offset by 16 byte), which caused FindParentStackFrameForStackWalk to null frame.
So, we ended up with assert on `ExceptionTracker::HasFrameBeenUnwoundByAnyActiveException(&m_crawl)`.
The issue was assembly helper, CallEHFunclet records FP instead of SP while SP is adjusted in prolog.

### CODE REVIEW

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Release

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Debug

**Comment by kyulee1** [comment]
@dotnet/arm64-contrib PTAL. /cc @dotnet/jit-contrib

**Comment by kyulee1** [comment]
@rahku  Can you take a look? All tests are passed.

FYI. Here is summary from the log. 
```
[countpassfail] SUMMARY: Pass/Fail/Unstable counts expected from Tests.lst
  Total: 8345
  EXPECTED_PASS: 8197(98.2%)
  EXPECTED_FAIL: 130(1.6%)
  UNSTABLE: 18(0.2%)
```

**Comment by rahku** [comment]
Looks good. Thanks. Don't know how I assumed fp to be same as sp.

**Pull request merged**
