### PR TITLE
Suppress DEBUG option for ilproj

### PR DESCRIPTION
**Pull request by kyulee1**

### CODE REVIEW

**Comment by kyulee1** [comment]
@BruceForstall PTAL

**Comment by BruceForstall** [comment]
LGTM

**Comment by CarolEidt** [comment]
LGTM

**Comment by kyulee1** [comment]
@dotnet-bot retest it

**Comment by kyulee1** [comment]
We've decided not to change the test flags but suppress warning with a GH issue. https://github.com/dotnet/coreclr/pull/2983 
So just close this PR.

**Pull request closed without merging**
