### PR TITLE
Revert #13647 and #13638

### PR DESCRIPTION
**Pull request by dpodder**
#13638 and #13647 attempted to replace the generic 'dotnet-bot' e-mail address with PR authors' e-mail addresses when uploading perf data to BenchView. Unfortunately, these changes are still broken for some users (specifically, if a user's e-mail address is not published/visible on their GitHub profile).

There is no clean way to implement the proper fix, and the right fix will change once pipeline support is available. Rather than putting in something hacky now, I'm reverting these changes to unblock PRs. We should revisit these changes after pipeline jobs are available.

### CODE REVIEW

**Comment by dpodder** [comment]
@adiaaida FYI... :cry:
@DrewScoggins PTAL
/cc @dotnet/rap-team

**Comment by DrewScoggins** [comment]
test ci please

**Comment by dpodder** [comment]
A bit more info for logging purposes:
* I tried actually fixing this in #13660, but turns out that Jenkins doesn't support anything other than trivial expansion in job parameters. So that PR was completely busted.
* The best way to get around this right now would be to add a new script to the repo that tests the values of `ghprb` variables at runtime, and returns the correct e-mail to be used by `submission-metadata.py`. But once pipeline jobs are available, it'll be better to just do it in groovy; and with the way the current job is defined, it would take a lot of refactoring to be able to consume the output of such a script. Hence, the decision to revert for now.

**Comment by adiaaida** [comment]
Could submission-metadata.py be change to handle it if --user is ""?

**Comment by dpodder** [comment]
@jorive has the ultimate authority here, but my take is, submission-metadata.py can't. That script is tied only to BenchView, and is (and should remain) agnostic towards coreclr, or even dotnet in general. Thus, we can't put any default fallback in there. (The only sensible fallback would be for there to be no owner, but I believe that's currently disallowed in the data schema, and I'm not sure we want to change that.)

The only sensible workaround is to write something like submission-metadata-wrapper.py, adding that to CoreCLR, for doing CoreCLR-specific logic (like the fallback e-mail) and calling submission-metadata.py accordingly. This, we can do. But, I have it from @mmitche that once pipeline jobs are available it's best to do this kind of dynamic logic in groovy again. So... my vote is to rollback this for now, and wait until pipeline jobs for the proper fix.

**Comment by dpodder** [comment]
@dotnet-bot test Ubuntu16.04 arm Cross Debug Build

**Comment by jorive** [comment]
I believe this is a limitation of the current Jenkins instance, and it should not be "fixed" within BenchView. If this is urgent, then the work around could be, as @dpodder suggested, to add a script wrapper to CoreClr, which, as I understand, it will be thrown away once pipelines are in place.

**Comment by adiaaida** [comment]
Pipelines are going to have the same issue with emails. If someone doesn't have a public email, then there won't be a pull trigger email listed. So we're going to have to have some sort of wrapper anyway.

**Comment by jorive** [comment]
On pipelines, we could do something like this: `${ghprbActualCommitAuthorEmail} ?? ${ghprbPullAuthorEmail} ?? ${ghprbPullAuthorLogin}@github.usr`

If anything fails, you will always have a GitHub login :)

**Comment by dpodder** [comment]
My understanding from what @mmitche described, it's possible to do dynamic expression evaluation in groovy in pipeline jobs, unlike in legacy jobs. That's what would enable doing the fallback in groovy, without a new/wrapper script.

I think we may still want to have another conversation regarding what exact field(s) to use and in what order. This to me is somewhat unclear:
* `${ghprbPullAuthorEmail}` should be the e-mail mapped to the GitHub profile of the PR author, unless they have it hidden by default.
* `${gphrbActualCommitAuthorEmail}` looks to be the e-mail pulled from git commit logs for the changes being merged. I'm not sure what value is used here if there are multiple contributors though... does it take the last contributing author's e-mail? Or all of them, combined in some way? Or is the value then undefined? In any case, are we sure we want to use this, since it might not be the same as the PR author?
  - Does git ensure in any way that this is a valid e-mail? If this is unsanitized user input, we need to avoid using it to ensure both security and sanity.

**Comment by dpodder** [comment]
@DrewScoggins @adiaaida can this be merged?

**Comment by adiaaida** [comment]
Sure. LGTM

**Comment by dpodder** [comment]
Thanks @adiaaida!

**Pull request merged**
