### PR TITLE
Use clock_gettime(CLOCK_REALTIME) in DateTime.UtcNow

### PR DESCRIPTION
**Pull request by stephentoub**
gettimeofday() is currently used in DateTime.UtcNow.  Depending on the system, it may have accuracy and precision in line with either clock_gettime(CLOCK_REALTIME) or clock_gettime(CLOCK_REALTIME_COARSE), but in returning its data it's necessarily limited by struct timeval's tv_usec field (microseconds), whereas clock_gettime uses struct timespec which has tv_nsec (nanoseconds).  This commit switches to use clock_gettime(CLOCK_REALTIME) to gain the additional precision (though the FILETIME through which the data is returned only supports 100-nsec precision).  On my machine, there was no measurable impact to throughput.

cc: @vancem, @mj1856

### CODE REVIEW

**Comment by janvorli** [comment]
@stephentoub the CLOCK_REALTIME is not avaiable on OSX.

**Comment by stephentoub** [comment]
Yeah, I'm fixing that now :)

**Comment by stephentoub** [comment]
@janvorli, look ok now?

**Comment by mj1856** [comment]
Thanks!

**Pull request merged**
