### PR TITLE
Making sure the nativeCodeVersion flowing change works with Rejit and EnC

### PR DESCRIPTION
**Pull request by cshung**
This change is done to address the unfinished business in pull request #21925.

### CODE REVIEW

**Comment by cshung** [comment]
@dotnet-bot Test OSX10.12 x64 Checked Innerloop Build and Test
@dotnet-bot Test Tizen armel Cross Checked Innerloop Build and Test

**Comment by cshung** [comment]
@dotnet-bot Test Tizen armel Cross Checked Innerloop Build and Test

**Comment by hoyosjs** [comment]
@dotnet-bot Test Tizen armel Cross Checked Innerloop Build and Test

**Comment by cshung** [comment]
@dotnet-bot Test Tizen armel Cross Checked Innerloop Build and Test

**Pull request merged**
