### PR TITLE
Reenable parallel msbuild execution - 2x faster test build

### LINKED ISSUE #19386: [Win/Infrastructure] Regression introduced by #19324 - removed parallel msbuild for tests
PR #19324 lost default MSBuild argument  /maxcpucount which enabled parallel MSBuild test build. Build time on my laptop increased 2x.

cc @AaronRobinsonMSFT

### PR DESCRIPTION
**Pull request by 4creators**
Fixes #19386 regression introduced in #19324

cc @AaronRobinsonMSFT @BruceForstall

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT x64 Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT x86 Checked Build and Test

**Comment by AaronRobinsonMSFT** [comment]
@dotnet-bot tests Ubuntu x64 Checked Innerloop Build and Test

**Comment by 4creators** [comment]
https://ci.dot.net/job/dotnet_coreclr/job/master/job/x86_checked_windows_nt_prtest/14697/

```

Test Result (4 failures / +4)baseservices_threading._generics_threadstart_GThread24_GThread24_._generics_threadstart_GThread24_GThread24_cmdbaseservices_threading._generics_threadstart_GThread22_GThread22_._generics_threadstart_GThread22_GThread22_cmdJIT_Generics._Coverage_chaos65204782cs_o_chaos65204782cs_o_._Coverage_chaos65204782cs_o_chaos65204782cs_o_cmdRegressions_coreclr._1514_InterlockExchange_InterlockExchange_._1514_InterlockExchange_InterlockExchange_cmd
--

**Comment by 4creators** [comment]
@dotnet-bot test OSX10.12 x64 Debug CoreFX Tests

**Comment by 4creators** [comment]
@dotnet-bot test OSX10.12 x64 Debug CoreFX Tests

**Comment by 4creators** [comment]
Previous OSX failure was a timeout after more than 7 hour run

**Comment by 4creators** [comment]
OSX filed again due to timeout:
```
11:01:29 Build timed out (after 420 minutes). Marking the build as aborted.
11:01:29 Build was aborted
```

**Comment by 4creators** [comment]
@BruceForstall IMO we can merge it since failures are unrelated

**Comment by BruceForstall** [comment]
@4creators Thanks for keeping an eye on this; it's great to have this improvement.

**Pull request merged**
