### PR TITLE
Reduce struct copies in ValueTask.GetAwaiter

### PR DESCRIPTION
**Pull request by benaadams**
Work around for part of https://github.com/dotnet/coreclr/issues/18542#issuecomment-465621796

Using Unsafe casting rather than .ctors

Cuts
```asm
; Lcl frame size = 408
G_M43654_IG04:
       mov      rdx, bword ptr [rbp+10H]
       mov      rcx, gword ptr [rdx+8]
       lea      rdx, bword ptr [rbp-E0H]
       xor      r8, r8
       mov      rax, qword ptr [rcx]
       mov      rax, qword ptr [rax+64]
       call     qword ptr [rax+40]PipeReader:ReadAsync(struct):struct:this

G_M43654_IG05:
       vmovdqu  xmm0, qword ptr [rbp-E0H]
       vmovdqu  qword ptr [rbp-158H], xmm0
       vmovdqu  xmm0, qword ptr [rbp-D0H]
       vmovdqu  qword ptr [rbp-148H], xmm0
       vmovdqu  xmm0, qword ptr [rbp-C0H]
       vmovdqu  qword ptr [rbp-138H], xmm0
       mov      rdx, qword ptr [rbp-B0H]
       mov      qword ptr [rbp-128H], rdx

G_M43654_IG06:
       vmovdqu  xmm0, qword ptr [rbp-158H]
       vmovdqu  qword ptr [rbp-120H], xmm0
       vmovdqu  xmm0, qword ptr [rbp-148H]
       vmovdqu  qword ptr [rbp-110H], xmm0
       vmovdqu  xmm0, qword ptr [rbp-138H]
       vmovdqu  qword ptr [rbp-100H], xmm0
       mov      rdx, qword ptr [rbp-128H]
       mov      qword ptr [rbp-F0H], rdx

G_M43661_IG07:
       vmovdqu  xmm0, qword ptr [rbp-120H]
       vmovdqu  qword ptr [rbp-A8H], xmm0
       vmovdqu  xmm0, qword ptr [rbp-110H]
       vmovdqu  qword ptr [rbp-98H], xmm0
       vmovdqu  xmm0, qword ptr [rbp-100H]
       vmovdqu  qword ptr [rbp-88H], xmm0
       mov      rdx, qword ptr [rbp-F0H]
       mov      qword ptr [rbp-78H], rdx

G_M43663_IG08:
       mov      rsi, gword ptr [rbp-A8H]
       test     rsi, rsi
       jne      SHORT G_M43663_IG09
       mov      edi, 1
       jmp      SHORT G_M43663_IG11

; Total bytes of code 1525, prolog size 59 for method <ProcessSends>d__26:MoveNext():this
```
To
```asm
; Lcl frame size = 296
G_M43654_IG04:
       mov      rdx, bword ptr [rbp+10H]
       mov      rcx, gword ptr [rdx+8]
       lea      rdx, bword ptr [rbp-E0H]
       xor      r8, r8
       mov      rax, qword ptr [rcx]
       mov      rax, qword ptr [rax+64]
       call     qword ptr [rax+40]PipeReader:ReadAsync(struct):struct:this

G_M43664_IG05:
       vmovdqu  xmm0, qword ptr [rbp-E0H]
       vmovdqu  qword ptr [rbp-A8H], xmm0
       vmovdqu  xmm0, qword ptr [rbp-D0H]
       vmovdqu  qword ptr [rbp-98H], xmm0
       vmovdqu  xmm0, qword ptr [rbp-C0H]
       vmovdqu  qword ptr [rbp-88H], xmm0
       mov      rdx, qword ptr [rbp-B0H]
       mov      qword ptr [rbp-78H], rdx

G_M43664_IG06:
       mov      rsi, gword ptr [rbp-A8H]
       test     rsi, rsi
       jne      SHORT G_M43664_IG07
       mov      edi, 1
       jmp      SHORT G_M43664_IG09

; Total bytes of code 1401, prolog size 59 for method <ProcessSends>d__26:MoveNext():this
```

Acceptable workaround?

/cc @stephentoub @jkotas @CarolEidt @AndyAyersMS @mikedn

### CODE REVIEW

**Comment by stephentoub** [comment]
Does this make a massive difference in a key end-to-end benchmark?  If not, I'd really prefer waiting for a proper fix.

**Comment by jkotas** [comment]
Changing `ValueTaskAwaiter(ValueTask value)` to `ValueTaskAwaiter(in ValueTask value)` should help too (maybe not as much), without unsafe code.

**Comment by stephentoub** [comment]
> Changing ValueTaskAwaiter(ValueTask value) to ValueTaskAwaiter(in ValueTask value) should help too

I'd be fine with that, assuming it does help.  Presumably that could be done for the configured-variations as well.

**Comment by benaadams** [comment]
> Changing `ValueTaskAwaiter(ValueTask value)` to `ValueTaskAwaiter(in ValueTask value)` should help too (maybe not as much)

Gets rid of one of the copies 
```asm
       call     qword ptr [rax+40]PipeReader:ReadAsync(struct):struct:this

G_M43655_IG05:
       vmovdqu  xmm0, qword ptr [rbp-E0H]
       vmovdqu  qword ptr [rbp-120H], xmm0
       vmovdqu  xmm0, qword ptr [rbp-D0H]
       vmovdqu  qword ptr [rbp-110H], xmm0
       vmovdqu  xmm0, qword ptr [rbp-C0H]
       vmovdqu  qword ptr [rbp-100H], xmm0
       mov      rdx, qword ptr [rbp-B0H]
       mov      qword ptr [rbp-F0H], rdx

G_M43661_IG06:
       vmovdqu  xmm0, qword ptr [rbp-120H]
       vmovdqu  qword ptr [rbp-A8H], xmm0
       vmovdqu  xmm0, qword ptr [rbp-110H]
       vmovdqu  qword ptr [rbp-98H], xmm0
       vmovdqu  xmm0, qword ptr [rbp-100H]
       vmovdqu  qword ptr [rbp-88H], xmm0
       mov      rdx, qword ptr [rbp-F0H]
       mov      qword ptr [rbp-78H], rdx

G_M43663_IG07:
       mov      rsi, gword ptr [rbp-A8H]
       test     rsi, rsi
       jne      SHORT G_M43663_IG08
       mov      edi, 1
       jmp      SHORT G_M43663_IG10
```

Will do a PR for that

**Comment by benaadams** [comment]
Safe version: https://github.com/dotnet/coreclr/pull/22738

**Comment by benaadams** [comment]
> Presumably that could be done for the configured-variations as well.

Looks like `ConfiguredValueTaskAwaitable`; `ConfiguredValueTaskAwaiter` and `ValueTask` are all the same layout, so this could work too 😉

**Comment by stephentoub** [comment]
> Looks like ConfiguredValueTaskAwaitable; ConfiguredValueTaskAwaiter and ValueTask are all the same layout

Ah, right, I forgot I stored the bool in the ValueTask itself to take advantage of the padding space.

**Comment by benaadams** [comment]
> If not, I'd really prefer waiting for a proper fix.

Ideally it would use the stack it gave to the method call and ditch the copies that are immediately dead; so end up as:
```asm
G_M43654_IG04:
       mov      rdx, bword ptr [rbp+10H]
       mov      rcx, gword ptr [rdx+8]
       lea      rdx, bword ptr [rbp-E0H]
       xor      r8, r8
       mov      rax, qword ptr [rcx]
       mov      rax, qword ptr [rax+64]
       call     qword ptr [rax+40]PipeReader:ReadAsync(struct):struct:this

G_M43664_IG06:
       mov      rsi, gword ptr [rbp-E0H]
       test     rsi, rsi
       jne      SHORT G_M43664_IG07
       mov      edi, 1
       jmp      SHORT G_M43664_IG09
```

**Comment by benaadams** [comment]
Though to do that it would also need to recognise `rbp-E0H` instead of `rbp-A8H` as the location for local `6`:
```
IL_0037: callvirt instance class ...::GetAwaiter()
IL_003c: stloc.s 6
IL_003e: ldloc.s 6
IL_0040: callvirt instance bool ...::get_IsCompleted()
```

**Comment by benaadams** [comment]
> If not, I'd really prefer waiting for a proper fix.

Ideally it would use the stack it gave to the method call and remove the final copy so end up as:
```asm
G_M43654_IG04:
       mov      rdx, bword ptr [rbp+10H]
       mov      rcx, gword ptr [rdx+8]
       lea      rdx, bword ptr [rbp-E0H]
       xor      r8, r8
       mov      rax, qword ptr [rcx]
       mov      rax, qword ptr [rax+64]
       call     qword ptr [rax+40]PipeReader:ReadAsync(struct):struct:this

G_M43664_IG06:
       mov      rsi, gword ptr [rbp-E0H]
       test     rsi, rsi
       jne      SHORT G_M43664_IG07
       mov      edi, 1
       jmp      SHORT G_M43664_IG09
```

Though to do that it would also need to recognise `rbp-E0H` instead of `rbp-A8H` as the location for local `6`; as its in the il
```
IL_0037: callvirt instance class ...::GetAwaiter()
IL_003c: stloc.s 6
IL_003e: ldloc.s 6
IL_0040: callvirt instance bool ...::get_IsCompleted()
```
As it uses it further down e.g.
```
IL_005e: ldloca.s 6
IL_0060: ldarg.0
IL_0061: call instance void ...::AwaitUnsafeOnCompleted<...>(!!0&, !!1&)
```

```asm
lea      rdx, bword ptr [rbp-A8H]
mov      r8, bword ptr [rbp+10H]
call     AsyncTaskMethodBuilder`1:AwaitUnsafeOnCompleted(byref,byref):this
```

**Comment by benaadams** [comment]
> If not, I'd really prefer waiting for a proper fix.

Ideally the Jit would use the return assignment as the stack it gave to the method call and remove the final copy so end up as:
```asm
G_M43654_IG04:
       mov      rdx, bword ptr [rbp+10H]
       mov      rcx, gword ptr [rdx+8]
       lea      rdx, bword ptr [rbp-A8H]   ; A8H rather than E0H
       xor      r8, r8
       mov      rax, qword ptr [rcx]
       mov      rax, qword ptr [rax+64]
       call     qword ptr [rax+40]PipeReader:ReadAsync(struct):struct:this

G_M43664_IG06:
       mov      rsi, gword ptr [rbp-A8H]
       test     rsi, rsi
       jne      SHORT G_M43664_IG07
       mov      edi, 1
       jmp      SHORT G_M43664_IG09
```

**Comment by benaadams** [comment]
> Ideally the Jit would use the return assignment as the stack it gave to the method call and remove the final copy so end up as...

@mikedn points out in "Out-Returns" https://github.com/dotnet/csharplang/issues/2217#issuecomment-463084461 that causes compilations if the called method throws an exception and it ends up half initialized.

**Comment by mikedn** [comment]
I see, structs containing a single field... these tend to give JIT headaches. Still, some of this stuff could probably be fixed.

**Pull request closed without merging**
