### PR TITLE
Add tests for arm64 il issues.

### PR DESCRIPTION
**Pull request by sandreenko**
The PR adds tests that are failing in our internal test system with arm64 altjit.
Failures are:
```
codegencommon_cpp__6797____Assertion_failed__NYI__Initialize_floating_point_register_to_zero
liveness_cpp__39____Assertion_failed____We_should_never_encounter_a_reference_to_a_lclVar_that_has_a_zero_refCnt__
lsraarm64_cpp__241____Assertion_failed____Shouldn_t_see_an_integer_typed_GT_MOD_node_in_ARM64_
```

### CODE REVIEW

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT x64_arm64_altjit Checked r2r_jitstress1
@dotnet-bot test Windows_NT x64_arm64_altjit Checked r2r_jitstressregs1
@dotnet-bot test Windows_NT x64_arm64_altjit Checked r2r_jitstressregs2

**Comment by sandreenko** [comment]
to repro:
```
build x64 debug 
open coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\crossgen.exe
arguments: /Platform_Assemblies_Paths coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root "coreclr\bin\tests\Windows_NT.x64.Debug\JIT\Regression\JitBlue\DevDiv_605447\DevDiv_605447\DevDiv_605447.exe"
environment: 
   complus_altjit = *
   complus_altjitassertonnyi = 1
   complus_altjitname = protononjit.dll
   complus_altjitngen = *
```

**Comment by sandreenko** [comment]
PTAL @sdmaclea @dotnet/arm64-contrib.

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT x64_arm64_altjit Checked r2r_jitstress1
@dotnet-bot test Windows_NT x64_arm64_altjit Checked r2r_jitstressregs1
@dotnet-bot test Windows_NT x64_arm64_altjit Checked r2r_jitstressregs2

**Comment by sandreenko** [comment]
> These tests fail, which will cause failures when running linux arm64 testing and on windows when the arm64 windows lst file is updated.
> I believe these tests should be excluded on both OS.

I will wait until ci reproduces these errors in this PR;
then I will create issues for them;
then I will add a commit that disables these tests with issues numbers;

**Comment by sdmaclea** [comment]
I think the Windows tests will not run unless they are added to the test lst first.

**Comment by sandreenko** [comment]
> I think the Windows tests will not run unless they are added to the test lst first.

Do altjit jobs use test lists?

**Comment by sdmaclea** [comment]
I don't happen to know.  Looks like it is used by smarty.  I would guess smarty is only used for running on target, so I expect not.

**Comment by BruceForstall** [comment]
Altjit jobs don't use the smarty test.lst files.

These will need to be added to:
1. tests\arm64\Tests.lst to run on Windows arm64 (and tests\arm\Tests.lst to run on Windows arm). Adding the right Categories tag will disable them for now.
2. tests\testsFailing.arm64.txt to disable them for arm64 for now.

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT x64_arm64_altjit Checked r2r_jitstress1

**Comment by sandreenko** [comment]
@dotnet-bot test Ubuntu arm64 Cross Checked r2r Build and Test

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked r2r Build and Test

**Comment by sandreenko** [comment]
@dotnet-bot test Ubuntu arm64 Cross Checked r2r Build and Test
@dotnet-bot test Windows_NT arm64 Cross Checked r2r Build and Test
@dotnet-bot test Windows_NT x64_arm64_altjit Checked r2r_jitstress1

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked r2r Build and Test
@dotnet-bot test Windows_NT x64_arm64_altjit Checked r2r_jitstress1

**Comment by sandreenko** [comment]
@jashook the PR was updated, could you please take another look?

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT x64_arm64_altjit Checked r2r_jitstress1

**Pull request merged**
