### PR TITLE
Stop including utilcode in the GC info encoder.

### PR DESCRIPTION
**Pull request by pgavlin**
This required inlining simplified but equivalent definitions
for StructArrayList, SList, SimplerHashMap, CQuickSort, and
BitPosition() into the GC info encoder's sources.

### CODE REVIEW

**Comment by pgavlin** [comment]
@BruceForstall @jkotas @dotnet/jit-contrib PTAL

**Comment by BruceForstall** [comment]
" This required inlining simplified but equivalent definitions for StructArrayList, SList, SimplerHashMap, CQuickSort, and BitPosition() into the GC info encoder's sources."

Ugh. Why don't you just make those shared sources independent, so they don't depend on other utilcode functionality, instead of creating all new copies of the functionality?

**Comment by pgavlin** [comment]
> Ugh. Why don't you just make those shared sources independent, so they don't depend on other utilcode functionality, instead of creating all new copies of the functionality?

Two reasons:
- This was the most conservative direction. Only the GC info encoder is affected by this change.
- This removes the encoder's dependency on external data structures, thus simplifying its consumption. As an example, LLILC previously had to define its own versions of these dependencies in order to consume the GC info sources; now it will not need to do so.

The other option I considered was copying the encoder itself into the JIT, but that seemed less than ideal. The general direction that I'd like to take here is to move most of the GC-info-related functionality (encoding, decoding, and dumping) into a single easily-consumed library.

**Comment by BruceForstall** [comment]
Why can't we have shared sources with no dependencies? E.g., JIT also depends on some of these, and I wouldn't want to see them copied into the JIT as well.

**Comment by pgavlin** [comment]
> Why can't we have shared sources with no dependencies? E.g., JIT also depends on some of these, and I wouldn't want to see them copied into the JIT as well.

The logistics of source sharing are likely to become complicated in the future unless we do decide that the GC info support code (at least the encoder, but perhaps also a decoder and a dumper) will always be colocated with the JIT. At that point we would change the encoder to use the data structures from `jitstd`.

**Comment by jkotas** [comment]
The logistics of sharing of C++ libs has logistics issues as well (matching compiler versions, etc.).

I would lean towards source code sharing for components like GCInfo encoder. To make it work well,  `jitstd` should be close enough to standard C++ `std` - I believe it is pretty close today. Once/if the RyuJIT is portable enough codebase (e.g. does not depend on PAL on Unix), `jitstd` can be even retired.

When compiling GCInfo encoder as part of the RyuJIT, use  `jitstd` underneath. When compiling GCInfo encoder as part of random other projects, use the system provided `std` underneath.

Either way, this change looks fine to me as an incremental step.

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by russellhadley** [comment]
I agree that shared source would be fine.  We just have to figure out where the code will go/come from  once we have RyuJIT pulled out into it's own repo.  I'm ok with this as an incremental step as well.

**Comment by BruceForstall** [comment]
I disagree. I think this change is unacceptable. It creates unnecessary code duplication. But it's not duplication, it's new, unnecessary code, with new and unnecessary bug risk. We should go straight for a good code sharing solution. We have no need for this change.

**Comment by pgavlin** [comment]
I'm closing this in favor of #4037.

**Pull request closed without merging**
