### PR TITLE
Integrate GC changes from CoreRT

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
cc @janvorli

**Comment by adityamandaleeka** [comment]
Not sure if you've looked at the failures yet, but it looks like they're all because of a static assert in the templated LogMsgOL which verifies that the size of the template type is <= pointer size, so it's now failing on 32-bit platforms because the type has been changed to uint64_t.

Thought I'd share since it's a little hard to find in the Ubuntu CI logs.

**Comment by jkotas** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by jkotas** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Pull request merged**
