### PR TITLE
Detect if HW Intrinsic imm const arg is non folded const expression during import phase

### LINKED ISSUE #19888: HW intrinsics: Poor codegen for operations requiring imm8 when the value is calculated to constant during JIT
In the repro code below `sizeof(TChar)` is known during JIT, still code is suboptimal in disasm - some helper (?) method is invoked instead of instruction and SIMD vector value is placed on stack due to this.
This issue is quite notable with shifts and typecasting during concrete value calculation, but to my memory there were similar cases with other instructions.

------------
Repro code:

```
[MethodImpl(MethodImplOptions.NoInlining)]
static void Test<TChar>() where TChar : unmanaged
{
    Vector128<byte> v = Sse2.SetZeroVector128<byte>();
    v = Sse2.ShiftRightLogical128BitLane(v, (byte)sizeof(TChar)); // <======
    Console.WriteLine(Sse41.Extract(v, 0));
}

static void Main(string[] args)
{
    Test<byte>();
    Test<ushort>();
}
```
-------
Disasm:

--- ...\Program2.cs ---
            Vector128<byte> v = Sse2.SetZeroVector128<byte>();
000007FE75244A20  sub         rsp,58h  
000007FE75244A24  xor         eax,eax  
000007FE75244A26  mov         qword ptr [rsp+40h],rax  
000007FE75244A2B  mov         qword ptr [rsp+48h],rax  
000007FE75244A30  pxor        xmm0,xmm0  
000007FE75244A34  movaps      xmmword ptr [rsp+40h],xmm0  

            v = Sse2.ShiftRightLogical128BitLane(v, (byte)sizeof(TChar));
000007FE75244A39  movaps      xmm0,xmmword ptr [rsp+40h]  
000007FE75244A3E  movaps      xmmword ptr [rsp+30h],xmm0  
000007FE75244A43  lea         rcx,[rsp+40h]  
000007FE75244A48  lea         rdx,[rsp+20h]  
000007FE75244A4D  mov         r8,qword ptr [rsp+30h]  
000007FE75244A52  mov         qword ptr [rdx],r8  
000007FE75244A55  mov         r8,qword ptr [rsp+38h]  
000007FE75244A5A  mov         qword ptr [rdx+8],r8  
000007FE75244A5E  lea         rdx,[rsp+20h]  
000007FE75244A63  mov         r8d,1  
000007FE75244A69  call        000007FE752421A0  <=================

            Console.WriteLine(Sse41.Extract(v, 0));
000007FE75244A6E  movaps      xmm0,xmmword ptr [rsp+40h]  
000007FE75244A73  pextrb      ecx,xmm0,0  
000007FE75244A79  call        000007FE75241AC8  
000007FE75244A7E  nop  
000007FE75244A7F  add         rsp,58h  
000007FE75244A83  ret  
--- No source file -------------------------------------------------------------

### PR DESCRIPTION
**Pull request by 4creators**
Fixes #19888

### CODE REVIEW

**Comment by 4creators** [comment]
CI failures are caused by IO

@dotnet-bot Windows_NT x64 Checked Innerloop Build and Test

**Comment by 4creators** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by 4creators** [comment]
Filed bug for OSX test errors #19890

**Comment by 4creators** [comment]
@dotnet-bot Windows_NT x64 Checked Innerloop Build and Test

**Comment by 4creators** [comment]
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test 
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test (Jit - TieredCompilation=0)
@dotnet-bot test Windows_NT x64 Checked Innerloop Build and Test

**Comment by 4creators** [comment]
@dotnet-bot     test Ubuntu x64 Checked Innerloop Build and Test (Jit - TieredCompilation=0)

**Comment by tannergooding** [comment]
CC. @CarolEidt, @fiigii 

I don't think this is the right fix. The correct fix is likely moving the logic that determines if we should inline or call the intrinsic to after the point where the JIT completes its own constant folding (rather than trying to do it during import).

**Comment by mikedn** [comment]
> The correct fix is likely moving the logic that determines if we should inline or call the intrinsic to after the point where the JIT completes its own constant folding (rather than trying to do it during import).

No.

**Comment by AndyAyersMS** [comment]
I think the idea is ok, but please use something like `gtFoldExpr` here so we use the same folding logic we use elsewhere (including other intrinsics like type equality ops).

**Comment by 4creators** [comment]
@AndyAyersMS @mikedn @tannergooding @CarolEidt 

This is generalized rewrite based on `gtFoldExprConst` and custom implementation of `tryFoldExpressionConst`. Unfortunately `gtFoldExpr` did not work as expected as it did not walk all the tree.

**Comment by fiigii** [comment]
I remember that the current gtFoldExpr doesn’t work with GT_CAST 
https://github.com/dotnet/coreclr/pull/16903#issuecomment-372932248.
Shall we try to correctly fold cast in gtFoldExpr? Or push a more sophisticated solution like 
https://github.com/dotnet/coreclr/issues/17108

**Comment by tannergooding** [comment]
@mikedn. Commenting just "no" is not helpful and does not move the general discussion forward.

I suggested we delay the inlining decision to outside the importer based on previous discussions we had in https://github.com/dotnet/coreclr/issues/17108. Which itself suggests delaying the decision to do the call vs directly inline to as late as possible (so that we can rely on all the optimization stages and constant folding the JIT may do in later stages).

**Comment by 4creators** [comment]
> we delay the inlining decision to outside the importer

Folding of const expressions is done during morphing. I do not think that delaying imm expansion to later stages is good design bcs it forces compiler to handle all the unfolded tree down the pipeline.

**Comment by fiigii** [comment]
> I do not think that delaying imm expansion to later stages is good design

Not delay const folding, it is trying to delay the const detection.

**Comment by AndyAyersMS** [comment]
If there are relatively simple constant expressions that `gtFoldExpr` can't optimize, then perhaps we should fix that.

**Comment by CarolEidt** [comment]
In general, I don't like pushing constant folding into the importer, as it is not in keeping with the normal sequence of things, and therefore could potentially create additional problems.

My preference would be to first determine whether making the call/intrinsic decision in `Lowering` is feasible. Then, if it is not, we should then determine whether we can address the limitations in `gtFoldExpr` that prevent it from being used directly, before creating a new method to do basically the same thing.

**Comment by 4creators** [comment]
Changed title to better indicate scope of changes in this PR

**Comment by 4creators** [comment]
> My preference would be to first determine whether making the call/intrinsic decision in Lowering is feasible.

Will work on this

**Comment by mikedn** [comment]
> In general, I don't like pushing constant folding into the importer, as it is not in keeping with the normal sequence of things, and therefore could potentially create additional problems.

Yes but attempting to pass a bunch of calls through the JIT is far more likely to create problems. They're large, complicated nodes with specific processing. They have side effects. They're difficult to optimize in any way. They offer no advantage basically.

And constant folding in the importer isn't that unnatural, if you consider IL realities. I already provided an example in the associated issue where the C# compiler generates IL that could be considered unnatural just to save size. And the importer blindly produces IR that then needs additional work to cleanup.

Besides, this kind of constant folding has the advantage of being deterministic. You can tell people that X, Y, Z IL instructions are guaranteed to be constant folded and that should useful, at least because of `sizeof`, which happens to be a JIT time constant but not a C# compile time constant.

**Comment by CarolEidt** [comment]
> attempting to pass a bunch of calls through the JIT is far more likely to create problems

Right. IIRC what was discussed previously was the idea that you would *always* create the intrinsic node. Then, in `Lowering` you would turn it into a call if an operand was not an intrinsic where one was required. That was where the discussion of introducing calls in `Lowering` came from.

**Comment by mikedn** [comment]
> Then, in Lowering you would turn it into a call if an operand was not an intrinsic where one was required. That was where the discussion of introducing calls in Lowering came from.

Yes, that would work but currently it's a lot of trouble to create calls in lowering and it's not clear what advantages it would have.

I think we can look at this from another angle:
* do "deterministic" constant folding in the importer so something `2 * sizeof(T)` is practically guaranteed to work
* if someone comes with a good real world example where additional constant folding performed by the optimizer would help, attempt transforming intrinsics imported as calls in lowering, as a best effort optimization

**Comment by 4creators** [comment]
Changed approach to simplest one - detection if immediate argument is const expression without performing any operations on tree.

**Comment by 4creators** [comment]
@CarolEidt @mikedn @AndyAyersMS 

The code replicates essentially very simple folding logic used by `gtFoldExpr` and `gtFoldExprCnst` and detects if expression will pass it. If yes it should be folded to `const integral` of type required by intrinsic. If any overflow/underflow or other exception will happen it will be accounted for by folding and cast logic so any errors will be raised independently of expanding imm HW intrinsic now.

**Comment by 4creators** [comment]
> Having a helper method which constructs the shuffle control word.

It's trivial using binary literals. Don't think it's worth implementing it while trivial alternative exists.

**Comment by mikedn** [comment]
> Changed approach to simplest one - detection if immediate argument is const expression without performing any operations on tree.

I'm not sure why would you do that. What happens if `isImmExprConst` decides that the tree is a constant but for some reason the optimizer fails to transform the tree into a constant? Designs that put similar logic in 2 places and expect that the logic is kept in sync are prone to failure.

> Having a helper method which constructs the shuffle control word.

That should be an intrinsic, it's simpler and safer.

**Comment by 4creators** [comment]
In attachment there is complete dump for jitting of the following test methods:

```C#
        [MethodImpl(MethodImplOptions.NoInlining)]
        private static unsafe void Test<TChar>() where TChar : unmanaged
        {
            Vector128<byte> v = Sse2.SetZeroVector128<byte>();
            v = Sse2.ShiftRightLogical128BitLane(v, (byte)sizeof(TChar));
            Console.WriteLine(Sse41.Extract(v, 0));
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        private static unsafe void Test1<TChar>() where TChar : unmanaged
        {
            Vector128<byte> v = Sse2.SetZeroVector128<byte>();
            v = Sse2.ShiftRightLogical128BitLane(v, (byte)((3 * sizeof(TChar)) / 2 + 4 - sizeof(TChar)));
            Console.WriteLine(Sse41.Extract(v, 0));
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        private static unsafe void Test2<TChar>() where TChar : unmanaged
        {
            Vector128<byte> v = Sse2.SetZeroVector128<byte>();

            byte C;
            if (sizeof(TChar) == sizeof(byte))
            {
                v = Sse2.ShiftRightLogical128BitLane(v, 1);
            }
            else if (sizeof(TChar) == sizeof(ushort))
            {
                v = Sse2.ShiftRightLogical128BitLane(v, 2);
            }
            else
            {
                throw new InvalidOperationException();
            }

            Console.WriteLine(Sse41.Extract(v, 0));
        }
```

In every case disasm is identical module const value:

Method Test2
```asm
*************** After end code gen, before unwindEmit()
G_M17451_IG01:        ; func=00, offs=000000H, size=0005H, gcrefRegs=00000000 {}, byrefRegs=00000000 {}, byref, nogc <-- Prolog IG

IN0006: 000000 sub      rsp, 40
IN0007: 000004 nop      

G_M17451_IG02:        ; offs=000005H, size=0017H, gcrefRegs=00000000 {}, byrefRegs=00000000 {}, byref

IN0001: 000005 vpxor    xmm0, xmm0, xmm0
IN0002: 00000A vpsrldq  xmm0, xmm0, 2
IN0003: 000010 vpextrb  ecx, xmm0, 0
IN0004: 000016 call     System.Console:WriteLine(int)
IN0005: 00001B nop      

G_M17451_IG03:        ; offs=00001CH, size=0005H, epilog, nogc, emitadd

IN0008: 00001C add      rsp, 40
IN0009: 000020 ret     

```

**Comment by 4creators** [comment]
[ShiftRight128BitLane.Importer.Problems.log](https://github.com/dotnet/coreclr/files/2372246/ShiftRight128BitLane.Importer.Problems.log)

**Comment by tannergooding** [comment]
> That should be an intrinsic, it's simpler and safer.

I agree for this general case. However, people will likely be writing helper methods in general, and we should support emitting efficient code if they choose to do so.

**Comment by fiigii** [comment]
> we should then determine whether we can address the limitations in gtFoldExpr that prevent it from being used directly

If adding call-nodes in lowering is too hard now, I think we need to **generally** deal with GT_CAST in `gtFoldExpr`. Maybe, we can just support "cast to byte" now for hwintrinsic only, which would be simpler. But this PR's approach is (was) incorrect, as we need to check the truncation (chain) rather than unconditionally removing GT_CAST node. BTW, `gtFoldExpr` would need to manually cast the IMM value if it is a truncated const, otherwise, you will break some assertions of the backend.

**Comment by 4creators** [comment]
@dotnet-bot test Ubuntu x64 Checked CoreFX Tests
@dotnet-bot test Ubuntu x64 Formatting

**Comment by CarolEidt** [comment]
@AndyAyersMS - Is there general value (beyond this case) in doing simple constant folding in the importer? That is, would it improve inlining and/or simplify the trees such that it would be worth the investment beyond the intrinsic case?

**Comment by AndyAyersMS** [comment]
There is some value, yes.

Throughput: the sooner we can simplify the IR, the better. For instance If we can fold away a branch we may be able to avoid importing some parts of the method IL. For generic methods with lots of specialization this can really speed up importation. Other special case importer only transformations also rely on availability of constants (eg stackalloc to local conversion). 

Code quality: We do some early simple constant propagation -- eg the inliner will forward sub constants into inlinees and use constant args to boost inlining profitability estimates (which are made in the importer). So the more constants we can make available sooner the better.

There are already a half-dozen or so invocations of folding in the importer to try and catch cases like the above.

I would expect us to add more over time, and perhaps start enabling importer folding for things like Tier0.

**Comment by 4creators** [comment]
Closing in favor of  #19898

**Comment by AndyAyersMS** [comment]
My preference would be to have just one utility that can be called from various places (either for the specific purpose of surfacing constants, or as a general expression optimizer, perhaps with some control options). And it seems like the morph versions are the most capable -- the `gtxxx` variants don't tend to do full top-down bottom up traversals. But doing so likely means splitting morph apart and that is a tall order.

**Pull request closed without merging**
