### PR TITLE
Add GC stress modes

### PR DESCRIPTION
**Pull request by sejongoh**

### CODE REVIEW

**Comment by sejongoh** [comment]
@swaroop-sridhar @RussKeldorph Could you please review the changes?

/cc  @mmitche

**Comment by sejongoh** [comment]
@dotnet-bot test ci please

**Comment by sivarv** [comment]
My understanding is that gc-stress runs also need LD_LIBRARY_PATH to be set to the folder where disassembler shared library is present.  Is that also getting taken care?

**Comment by RussKeldorph** [comment]
Yeah, there's more work required here.  We first have to add the ability to pull down the coredistools package and configure gcstress properly.  That should be a separate change before this is merged.

**Comment by sejongoh** [comment]
Once I figure out how to pull down the package, I will prepare a separate changeset.

**Comment by mmitche** [comment]
@sejongoh LGTM, can you wait till tomorrow to merge this so I can get the workspace shortener enabled again?

**Comment by sejongoh** [comment]
I need to do more work for this, so I don't need to merge this today.

**Comment by sejongoh** [comment]
Waiting for  [https://github.com/dotnet/dotnet-ci/issues/209]()

**Comment by sejongoh** [comment]
@dotnet-bot test ci please.

**Comment by sejongoh** [comment]
@mmitche @RussKeldorph  Since #3284 is done, I will check this in. If any changes are needed, please let me know.

**Comment by RussKeldorph** [comment]
LGTM

**Pull request merged**
