### PR TITLE
Updating the xUnit Performance Api with bug fixes to the benchmark scenarios

### PR DESCRIPTION
**Pull request by jorive**
This newer version fixes collecting data on x86 where:
1. The Jit generate methods at runtime and that are not associated with any loaded module
2. Modules are loaded/unloaded multiple times
3. This newer version of the Api added some breaking changes to the Api interface

### CODE REVIEW

**Comment by jorive** [comment]
@dotnet/rap-team PTAL

**Comment by DrewScoggins** [comment]
LGTM

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by jkotas** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test please
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test please
@dotnet-bot test Windows_NT armlb Cross Checked Innerloop Build and Test please
@dotnet-bot test Windows_NT x64 Checked Innerloop Build and Test please
@dotnet-bot test Windows_NT x86 Checked Innerloop Build and Test please

**Comment by jkotas** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test please

**Comment by jkotas** [comment]
@BruceForstall @dotnet/arm32-contrib There are 2 tests failing in `Windows_NT arm Cross Checked` leg on all PRs.

**Comment by BruceForstall** [comment]
@jkotas I opened #15013 to disable the failing tests

**Pull request merged**
