### PR TITLE
Fix load from

### PR DESCRIPTION
**Pull request by gkhanna79**
@jkotas PTAL

### CODE REVIEW

**Comment by jkotas** [comment]
@dotnet-bot test Tizen armel Cross Debug Build please

**Comment by gkhanna79** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by gkhanna79** [comment]
@dotnet-bot test Tizen armel Cross Debug Build  please

**Comment by gkhanna79** [comment]
@kouvel Have you seen the test failures in CI legs above before?

**Comment by gkhanna79** [comment]
x64 failure passes locally.

**Comment by gkhanna79** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test please

**Comment by gkhanna79** [comment]
@dotnet-bot test Windows_NT x86 Checked Build and Test please

**Comment by gkhanna79** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test  please

**Comment by gkhanna79** [comment]
@dotnet-bot test Tizen armel Cross Debug Build please

**Comment by kouvel** [comment]
@gkhanna79, I'm not sure which test failures you're referring to, I only see the following in the build history:
> ERROR: Unable to find a build for artifact copy from: dotnet_coreclr/master/x86_debug_windows_nt_bld

**Comment by gkhanna79** [comment]
@mmitche @hqueue @hseok-oh Do you know why the Tizen Armel CI leg is failing with the following error (details at https://ci.dot.net/job/dotnet_coreclr/job/master/job/armel_cross_debug_tizen_prtest/1950/consoleFull#89948061375a84384-3f25-4dc5-89a4-860fe36ba035)?

`ERROR: Unable to find a build for artifact copy from: dotnet_coreclr/master/x86_debug_windows_nt_bld`

**Comment by gkhanna79** [comment]
I see the same failure in https://github.com/dotnet/coreclr/pull/11359 as well @mmitche @hqueue @hseok-oh

**Comment by gkhanna79** [comment]
@dotnet-bot test Tizen armel Cross Debug Build please

**Comment by mmitche** [comment]
@gkhanna79 Why is it set up to copy from x86?

**Comment by gkhanna79** [comment]
@mmitche I do not know but it seems like it was an infra issue since the latest attempt to run the leg is green.

**Comment by gkhanna79** [comment]
@mmitche Looking at the logs of the two Perf Test legs (https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_perflab_Windows_NT_x64_smoketest_prtest/3/console and https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_perflab_Windows_NT_x86_smoketest_prtest/3/console), I see that they both have finished successfully. 

If so, why is CI still showing them as running?

**Comment by gkhanna79** [comment]
Merging since everything is green.

**Comment by mmitche** [comment]
@gkhanna79 Not sure actually.  Jenkins shows that it contacted GitHub to update status.  Let me know if you see it again.

**Pull request merged**
