### PR TITLE
[WIP] FileStream.Windows Append mode shouldn't allow seeking

### PR DESCRIPTION
**Pull request by benaadams**
x5 speed up

For `useAsync == true`

Pre 
image

Post
image

Resolves: https://github.com/dotnet/corefx/issues/29129

/cc @stephentoub @jkotas  is this a valid change?

### CODE REVIEW

**Comment by benaadams** [comment]
From the test app in the issue:

Pre
```
netcoreapp2.1\win-x64\publish>AsyncFileWriterTester.exe
100,000 bounded capacity.
Total Time: 9.2379032 seconds
Total Bytes: 116,888,890
Aggregate Waiting: 00:00:51.9054476
------------------------

10,000 bounded capacity.
Total Time: 10.4082898 seconds
Total Bytes: 116,888,890
Aggregate Waiting: 00:01:07.2506591
------------------------

1,000 bounded capacity.
Total Time: 10.5997765 seconds
Total Bytes: 116,888,890
Aggregate Waiting: 00:01:10.7627665
------------------------

500 bounded capacity.
Total Time: 10.0306642 seconds
Total Bytes: 116,888,890
Aggregate Waiting: 00:01:06.5325461
------------------------

100 bounded capacity.
Total Time: 10.7193698 seconds
Total Bytes: 116,888,890
Aggregate Waiting: 00:01:08.3325643
------------------------

Press ENTER to continue.
```
Post
```
netcoreapp2.1\win-x64\publish>AsyncFileWriterTester.exe
100,000 bounded capacity.
Total Time: 2.2788458 seconds
Total Bytes: 116,888,890
Aggregate Waiting: 00:00:04.6358343
------------------------

10,000 bounded capacity.
Total Time: 2.0491854 seconds
Total Bytes: 116,888,890
Aggregate Waiting: 00:00:05.0332742
------------------------

1,000 bounded capacity.
Total Time: 1.8854354 seconds
Total Bytes: 116,888,890
Aggregate Waiting: 00:00:03.7733625
------------------------

500 bounded capacity.
Total Time: 1.880664 seconds
Total Bytes: 116,888,890
Aggregate Waiting: 00:00:03.7166907
------------------------

100 bounded capacity.
Total Time: 1.9010611 seconds
Total Bytes: 116,888,890
Aggregate Waiting: 00:00:03.8017758
------------------------

Press ENTER to continue.
```

**Comment by mikedn** [comment]
Hmm, did seek actually work in append mode? AFAIR Windows ignores seek requests for file handles opened in append mode but it's been a while since I bothered with such things...

**Comment by benaadams** [comment]
It passes the correct flag https://github.com/dotnet/coreclr/blob/91ce6edff7b897f1356ba43af7b26565639fb6fc/src/mscorlib/shared/System/IO/FileStream.Win32.cs#L28-L30
```
 // Must use a valid Win32 constant here... 
 if (mode == FileMode.Append) 
     mode = FileMode.OpenOrCreate; 
```

`OpenOrCreate` == 4

4 == [`FILE_APPEND_DATA  For a file object, the right to append data to the file`](https://msdn.microsoft.com/en-us/library/windows/desktop/gg258116(v=vs.85).aspx)

[WriteFile says](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365747(v=vs.85).aspx)

> **To write to the end of file**, specify both the Offset and OffsetHigh members of the OVERLAPPED structure as 0xFFFFFFFF. **This is functionally equivalent to previously calling the CreateFile function to open hFile using FILE_APPEND_DATA access.**

Don't know what `SetFilePointerEx` is supposed to do with `FILE_APPEND_DATA`; though it doesn't seem to be erroring (perhaps because its always being set to end of file?)

**Comment by omariom** [comment]
Hasn't it been already discussed?

https://github.com/dotnet/corefx/issues/6039

**Comment by mikedn** [comment]
> Haven't it been already discussed?

Ha ha, looks like. But it seems that people still don't get that `FileStream` is a somewhat poor abstraction for high performance file I/O. At least on Windows, if not on Linux as well.

**Comment by benaadams** [comment]
> Haven't it been already discussed?

Related, but you can't read if you [open in Append mode](https://github.com/dotnet/coreclr/blob/91ce6edff7b897f1356ba43af7b26565639fb6fc/src/mscorlib/shared/System/IO/FileStream.cs#L220-L221)
```csharp
if ((access & FileAccess.Read) != 0 && mode == FileMode.Append)
    throw new ArgumentException(SR.Argument_InvalidAppendMode, nameof(access));
```

**Comment by benaadams** [comment]
> Nah, this just emulates append mode, it doesn't actually use Win32 append mode. So seek works, sort of. As far as I can tell it actually allows you to expand the file by seeking past end and writing at that position.

So maybe Seek is valid; however it shouldn't try to Seek in when writing?

**Comment by omariom** [comment]
Pipeline based file reading/writing might be the answer to the burden of backward compability

https://github.com/dotnet/corefxlab/tree/master/src/System.IO.Pipelines.File

**Comment by benaadams** [comment]
Though the blocking `Write` doesn't try to do any Seeking, only async writing... which I don't completely understand.

**Comment by mikedn** [comment]
> Though the blocking Write doesn't try to do any Seeking, only async writing... which I don't completely understand.

That's probably because Win32 doesn't update the file pointer after an overlapped operation. Current file position and asynchronous I/O notions are kind of conflicting but that doesn't mean that `FileStream` didn't go out of its way to support that.

**Comment by benaadams** [comment]
> That's probably because Win32 doesn't update the file pointer after an overlapped operation. 

Ah, yes... looks like it keeps writing to the same location :(

**Comment by mikedn** [comment]
Right, since Win32 doesn't update the file pointer and since `WriteAsync` doesn't specify the write offset (as Win32's WriteFile does via OVERLAPPED) it means that `FileStream` has to maintain the file pointer by itself to simulate the notion of stream.

Maybe you can improve things by not calling `SetFilePointerEx` when the file handle has been opened for overlapped IO. It looks like right now `FileStream` does that even if there's probably no point.

**Comment by benaadams** [comment]
```csharp
intOverlapped->OffsetLow = -1;
intOverlapped->OffsetHigh = -1;
```
Works, but presumably I need to update the FileStream's Position?

**Comment by mikedn** [comment]
> Works, but presumably I need to update the FileStream's Position?

That seems to be the other way around. You need to update FileStream's position no matter what, doing otherwise is likely a breaking change. The idea is that you might be able to do that without calling `Interop.Kernel32.SetFilePointerEx` and then it would be faster.

**Comment by benaadams** [comment]
It doesn't need to call `SetEndOfFile` either as `Write` will increase the length

> Note that it is not an error to set the file pointer to a position beyond the end of the file. The size of the file does not increase until you call the SetEndOfFile, WriteFile, or WriteFileEx function. A write operation increases the size of the file to the file pointer position plus the size of the buffer written, leaving the intervening bytes uninitialized.

**Comment by benaadams** [comment]
There's definitely scope to improve async Write; but it would take me time to study the interactions, so wouldn't be soon :-/

**Comment by electricessence** [comment]
Interesting. @benaadams: Good catch no?

**Comment by stephentoub** [comment]
I'm having trouble doing the discussion. Is the current state of this PR something to actually be reviewed? What problem is the current state solving and what are the positive and negative ramifications of the change?

**Comment by benaadams** [comment]
Closing this for now, might revisit again

**Comment by electricessence** [comment]
So is this fixed then?  Or is it dependent on something else to get fixed?

**Comment by benaadams** [comment]
> So is this fixed then?

No, its kinda an overly complicated bit of code (sync and async iterations)

**Pull request closed without merging**
