### PR TITLE
[WIP] Attempt to fix the ARM test builds

### PR DESCRIPTION
**Pull request by weshaggard**
cc @RussKeldorph @jashook @4creators 

Continuation on the ARM builds. I sure my first commit isn't going to do but hopefully it will help figure out if the directory change is causing the issue.

### CODE REVIEW

**Comment by weshaggard** [comment]
test Ubuntu x64 Checked Build and Test

**Comment by weshaggard** [comment]
OK apparently fixing the path around the calls to VsDevCmd didn't help this issue.

**Comment by 4creators** [comment]
@weshaggard 
This is caused by multiple side effects of VsDevCmd execution: (i) it changes directory, (ii) it removes all entries from cmd directory stack. When pushd and popd are inserted before and after VsDevCmd call they have no effect. 

I have created fix for the problem which fixes arm build from windows command prompt as well from VS developer command prompt on my local machine. In my case I have had errors earlier than in CI, already in build.cmd - but my machine has a very large PATH.

Please see: https://github.com/dotnet/coreclr/compare/release/2.0.0...4creators:fixarmbuild2.0.0?expand=1

**Comment by weshaggard** [comment]
Thanks @4creators I've pushed a minimal change just to test the test build if that works I will pull in your larger clean-up chanages.

**Comment by weshaggard** [comment]
@RussKeldorph @jashook I've not been able to spend any more cycles on figuring this out could you guys try and get the ARM CI legs correctly building?

**Comment by weshaggard** [comment]
@jashook I'm going to let you take over this PR to fix the ARM legs in release/2.0.0 branches. Feel free to close this PR and open another if needed.

**Comment by weshaggard** [comment]
@jashook is looking at this so I'm closing this PR.

**Pull request closed without merging**
