### PR TITLE
Fix overflow when computing dwWeight in CPUGroupInfo::InitCPUGroupInfoArray

### PR DESCRIPTION
**Pull request by hanblee**
`dwWeight` is computed as nr_active<sup>m_nGroups</sup> which can overflow as the number of CPU groups increase.  This fix uses least common multiple of nr_active of different CPU groups to  compute `dwWeight` instead.
@Maoni0 PTAL - this should address `DivideByZeroException` issue on machines with large number of cores, but I don't have access to such machine to test at the moment.

### CODE REVIEW

**Comment by Maoni0** [comment]
thanks @hanblee. could you please also update the comment below this to reflect your change? it still says it can only address 4*64 CPUs.

**Comment by hanblee** [comment]
Thanks for your feedback @Maoni0. I updated the comment to reflect the change.

**Comment by hanblee** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by hanblee** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Pull request merged**
