### PR TITLE
Revert some changed files from an incorrectly merged commit

### PR DESCRIPTION
**Pull request by adityamandaleeka**
Commit [4cf34fe](https://github.com/dotnet/coreclr/commit/4cf34fe7988ad04eaa7f699a5d0faea8a8394f95) seems to have included some unintentional changes, some of which are
currently breaking the product. This reverts the affected files to what they should be.

@bryanar, can you confirm that the rest of the changes from your commit were intentional? I left everything under the 'tests' directory alone.

@janvorli  @Priya91 @kouvel, I think I applied your changes correctly, but if there's something amiss, please let me know.

/cc: @mmitche

### CODE REVIEW

**Comment by janvorli** [comment]
CC: @LLITCHEV

**Comment by janvorli** [comment]
LGTM, thanks a lot for fixing it!

**Comment by sergiy-k** [comment]
LGTM

**Comment by adityamandaleeka** [comment]
@dotnet-bot test this please

**Comment by adityamandaleeka** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
Aditya what are you seeing?

Sent from my Windows Phone
________________________________

**Comment by adityamandaleeka** [comment]
@mmitche I saw an unrelated failure earlier about not being able to find "CodeTaskFactory" and reran to get a clean run. Looks like it's fine now.

**Pull request merged**
