### PR TITLE
JIT: fix some instruction size estimates

### LINKED ISSUE #13398: JIT: some instruction sizes mis-estimated on x64
Known cases:

- GT_LABELs via emitIns_R_L -- size is estimated before the relocation flags are applied
- reg-reg movs via emitInsSizeRR -- REX prefix can be counted twice

I believe the intention is that these mis-estimates are tolerable (the true size may not be knowable and the actual size is known later) but they expose other issues.

The label case leads to an error in the code recording the inline pinvoke return address, as the jit stores the address one (or more) bytes into the return instruction instead of the address of the instruction. Not clear if this causes any observable problems as being close enough to the right value may be sufficient.

I have plausible fixes for both that I'll send out in a PR shortly.

This was discovered while looking for CHK/RET codegen differences.

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by AndyAyersMS**
The jit might double-count the REX prefix for certain reg-reg moves, and
could overestimate the size of a code-referent LEA.

While the downstream emitter code can tolerate overestimates, it is better
not to have them.

Closes #13398

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib 

Will hold off merging pending resolution of #13399. 

Also there may be more cases like this out there.

**Comment by AndyAyersMS** [comment]
Jit-diffs results (over corelib and fx):  diffs are jumps changing to short displacement forms.
```
Total bytes of diff: -1283 (-0.01 % of base)
    diff is an improvement.
Total byte diff includes 0 bytes from reconciling methods
        Base had    0 unique methods,        0 unique bytes
        Diff had    0 unique methods,        0 unique bytes
Top file improvements by size (bytes):
       -1165 : System.Private.CoreLib.dasm (-0.03 % of base)
         -24 : Microsoft.CodeAnalysis.dasm (0.00 % of base)
         -12 : System.Text.RegularExpressions.dasm (-0.01 % of base)
          -8 : Microsoft.CodeAnalysis.VisualBasic.dasm (0.00 % of base)
          -8 : Microsoft.VisualBasic.dasm (0.00 % of base)
17 total files with size differences (17 improved, 0 regressed), 62 unchanged.
Top method improvements by size (bytes):
        -128 : System.Private.CoreLib.dasm - System.DefaultBinder:BindToMethod(int,ref,byref,ref,ref,ref,byref):ref:this
         -42 : System.Private.CoreLib.dasm - System.Array:Reverse(ref,int,int) (24 methods)
         -26 : System.Private.CoreLib.dasm - System.DefaultBinder:SelectProperty(int,ref,ref,ref,ref):ref:this
         -15 : System.Private.CoreLib.dasm - System.DefaultBinder:SelectMethod(int,ref,ref,ref):ref:this
         -15 : System.Private.CoreLib.dasm - System.Text.StringBuilder:AppendFormatHelper(ref,ref,struct):ref:this
519 total methods with size differences (519 improved, 0 regressed), 77828 unchanged.
```
Am going to hunt around for other cases like this.

**Comment by AndyAyersMS** [comment]
@dotnet/dnceng bad stuff happening in CI since sometime this AM

**Comment by mmitche** [comment]
It's attempting to find the rhel6 packages.  That's odd

@smile21prc Can you take a look?

**Comment by jashook** [comment]
Similar issues with #12489

**Comment by AndyAyersMS** [comment]
Looks like `call[reg]` and `call[reg + disp]` also get overestimated, fix appears similar to LEA: set the reloc bit before calling `emitInsSizeAM`.

**Comment by AndyAyersMS** [comment]
Fixed the remaining cases in the jit-diff + fx set. Net size impact is now
```
Total bytes of diff: -1410 (-0.01 % of base)
    diff is an improvement.

Total byte diff includes 0 bytes from reconciling methods
        Base had    0 unique methods,        0 unique bytes
        Diff had    0 unique methods,        0 unique bytes

Top file improvements by size (bytes):
       -1281 : System.Private.CoreLib.dasm (-0.04 % of base)
         -24 : Microsoft.CodeAnalysis.dasm (0.00 % of base)
         -12 : Microsoft.CodeAnalysis.VisualBasic.dasm (0.00 % of base)
         -12 : System.Text.RegularExpressions.dasm (-0.01 % of base)
         -11 : Microsoft.CodeAnalysis.CSharp.dasm (0.00 % of base)

17 total files with size differences (17 improved, 0 regressed), 62 unchanged.

Top method improvements by size (bytes):
        -128 : System.Private.CoreLib.dasm - System.DefaultBinder:BindToMethod(int,ref,byref,ref,ref,ref,byref):ref:this
         -42 : System.Private.CoreLib.dasm - System.Array:Reverse(ref,int,int) (24 methods)
         -26 : System.Private.CoreLib.dasm - System.DefaultBinder:SelectProperty(int,ref,ref,ref,ref):ref:this
         -15 : System.Private.CoreLib.dasm - System.DefaultBinder:SelectMethod(int,ref,ref,ref):ref:this
         -15 : System.Private.CoreLib.dasm - System.Text.StringBuilder:AppendFormatHelper(ref,ref,struct):ref:this

562 total methods with size differences (562 improved, 0 regressed), 77785 unchanged.
```
Note the number of mis-estimated instructions was higher than this; we only see size savings if estimating one of these correctly helped shorten a branch.

**Comment by AndyAyersMS** [comment]
@BruceForstall @CarolEidt I added some more cases, so you might want to take another look....

**Comment by BruceForstall** [comment]
LGTM

**Comment by AndyAyersMS** [comment]
@BruceForstall do you still think I should hold this until we sort out #13399? We can always re-introduce this issue when testing that one -- or perhaps add an "overestimate stress" to show  CHK/REL behavior does not change because of overestimates.

**Comment by BruceForstall** [comment]
@AndyAyersMS No need to wait; go ahead and merge.

**Comment by AndyAyersMS** [comment]
Am going to retest since it's been a while.

@dotnet-bot retest this please

**Comment by AndyAyersMS** [comment]
@dotnet-bot retest Ubuntu x64 Checked Build and Test

**Comment by AndyAyersMS** [comment]
Lots of Ubuntu leg failures recently...

**Pull request merged**
