### PR TITLE
Replace MAX_PATH with new defines in clr\src\binder.

### PR DESCRIPTION
**Pull request by Priya91**
cc @JeremyKuhne @jkotas

### CODE REVIEW

**Comment by jkotas** [comment]
LGTM

**Comment by Priya91** [comment]
@jkotas @JeremyKuhne Added new commit to change defines in clr\vm.

**Comment by JeremyKuhne** [comment]
LGTM as well. You'll need to see why the debug windows build is failing.

**Comment by Priya91** [comment]
```
 C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\CodeAnalysis\Microsoft.CodeAnalysis.targets(214,5): error MSB4175: The task factory "CodeTaskFactory" could not be loaded from the assembly "C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Build.Tasks.Core.dll". Could not find file 'C:\Users\dotnet-bot\AppData\Local\Temp\3bzifrsm.dll'. [D:\j\workspace\dotnet_coreclr_windows_debug_prtest\bin\obj\Windows_NT.x64.Debug\src\tools\InjectResource\InjectResource.vcxproj]
```

Don't think this is related to this change.

@dotnet-bot test this please

**Comment by Priya91** [comment]
@dotnet-bot test this please

**Pull request merged**
