### PR TITLE
Make createdump build and work on ARM

### PR DESCRIPTION
**Pull request by kbaladurin**

### CODE REVIEW

**Comment by kbaladurin** [comment]
CC: @Dmitri-Botcharnikov @ayuckhulk

**Comment by BruceForstall** [comment]
@mikem8361 PTAL

**Comment by mikem8361** [comment]
Have you created a dump with either the env var COMPlus_CreateDumpDiagnostics=1 set or the command line --diag to make sure the tracing still works both on arm and x64?

The debuggertests repo tests should be run to verify that ubuntu x64 isn't broken. I can help with setup or I can even run the tests for you.

**Comment by kbaladurin** [comment]
@mikem8361, yes, I've created minidump with the env var COMPlus_CreateDumpDiagnostics=1 set. Tracing works both on arm and x64:
[x64 trace](https://gist.github.com/kbaladurin/60b84bd0c0e8210cdadae66b0747aeb7)
[arm trace](https://gist.github.com/kbaladurin/e4eda3babfb56af788acb92943bd40a2)

Thank you, It would be great if you help with debuggertests. I tried to use setup-debuggertests.sh script but it failed because it couldn't download [Linux.DebuggerTests.tar](https://dotnetbuilddrops.blob.core.windows.net/debugger-container/Linux.DebuggerTests.tar).

**Comment by kbaladurin** [comment]
@dotnet-bot test Tizen armel Cross Release Build

**Comment by kbaladurin** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test

**Comment by Dmitri-Botcharnikov** [comment]
CC @chunseoklee @seanshpark @lemmaa

**Comment by mikem8361** [comment]
I have run the debuggertests with your changes and everything was successful.

You are good to merge.

**Comment by kbaladurin** [comment]
Thank you.

**Pull request merged**
