### PR TITLE
Normalize array element type of ldnull to stack size for verification

### PR DESCRIPTION
**Pull request by cmckinsey**
Stephen Toub reported a RyuJIT assertion failure in System.Linq.Expressions.Tests.dll on unix.
The debug assertion was firing to ensure that the verification element type is normalized to
the stack slot sized type for verification purpose in later code that expects this convention.

Testing: DDR_And_JitSelfHost_diffs al clean with no asm diffs.
Performance: 0 asm diffs so no impact

### CODE REVIEW

**Comment by cmckinsey** [comment]
@brucefo @stephentoub

**Comment by cmckinsey** [comment]
@BruceForstall

**Comment by BruceForstall** [comment]
LGTM

**Comment by jkotas** [comment]
LGTM

**Pull request merged**
