### PR TITLE
[RyuJIT/ARM32] GT_ARR_INDEX/GT_ARR_OFFSET support in codegen.

### PR DESCRIPTION
**Pull request by alpencolt**
Code is mostly the same as for ARM64 except register size and some
emitted instructions.

### CODE REVIEW

**Comment by alpencolt** [comment]
#9648 
@Dmitri-Botcharnikov

**Comment by danmosemsft** [comment]
@dotnet/jit-contrib are you needed for CR on this older PR?

**Comment by BruceForstall** [comment]
@danmosemsft yes. I'll look at it.

@alpencolt I assume you still want and need this PR merged?

**Comment by alpencolt** [comment]
@BruceForstall yes, we are need in it. Also could you take  a look at #9979
Both PRs can be checked with tiny test, current with debug version and the second with optimized:
```C#
public class BringUpTest
{
    const int Pass = 100;
    const int Fail = -1;

    static int test0(int i) {
        int[] a = {1, 2, 3, 4};
        return a[i];
    }

    static void test1()
    {
        int[] a = {1, 2, 3, 4};
        a[1] = 5;
    }

    static int test2()
    {
        int[] a = {1, 2, 3, 4};
        return a[1];
    }

    static int test3()
    {
        int[] a = {1, 2, 3, 4};
        a[1] = 5;
        return a[1];
    }

    static int test4()
    {
        int[,] a = {{1, 2}, {3, 4}};
        return a[0, 1];
    }

    static int test5(int i)
    {
        Dummy[] a = {new Dummy(0), new Dummy(1), new Dummy(2), new Dummy(3), new Dummy(4),
                     new Dummy(5), new Dummy(6), new Dummy(7), new Dummy(8), new Dummy(9)};
        return a[i].field;
    }

    static int test6(int i)
    {
        int[][] a = new int[2][];
        a[0] = new int[2] {0, 1};
        a[1] = new int[2] {2, 3};
        return a[1][i];
    }

    static int test7(int x, int y)
    {
        int[,] a = new int[2, 3];
        a[x, y] = 42;
        return a[x, y];
    }

    static int test_ex()
    {
        int[] a = {1, 2, 3, 4};
        return a[5];
    }

    static int Main()
    {
        test0(1);

        test1();
        if (test2() != 2) return Fail;
        if (test3() != 5) return Fail;
        if (test4() != 2) return Fail;
        if (test5(1) != 1) return Fail;
        if (test6(1) != 3) return Fail;
        if (test7(1, 1) != 42) return Fail;

        try
        {
            test_ex();
            return Fail;
        }
        catch (System.IndexOutOfRangeException)
        {
            // OK
        }

        return Pass;
    }

    class Dummy
    {
        public int field;
        public Dummy(int f)
        {
            field = f;
        }
    }
}
```

**Comment by BruceForstall** [comment]
It would be useful to add these test cases as a set of tests to the tests\src\JIT\CodeGenBringUpTests directory. It looks like that directory has very few array tests.

Note that tests in this directory follow a very simple pattern: a single function named the same as the filename, marked NoInlining, that tests the thing in question (e.g., arrays). The idea is that you set `COMPlus_AltJit=foo` for test foo.cs, with function foo(), and it tests exactly one thing.

**Comment by BruceForstall** [comment]
LGTM

**Pull request merged**
