### PR TITLE
Anchor Tag fix

### PR DESCRIPTION
**Pull request by fujiy**

### CODE REVIEW

**Comment by fujiy** [comment]
@dotnet-bot retest FreeBSD x64 Checked Build please

**Comment by fujiy** [comment]
@dotnet-bot retest Ubuntu x64 Checked Build please

**Comment by fujiy** [comment]
@dotnet-bot retest Ubuntu x64 Checked Build and Test please

**Comment by fujiy** [comment]
@dotnet-bot retest Ubuntu x64 Checked Build and Test please

**Comment by fujiy** [comment]
@dotnet-bot retest Ubuntu x64 Checked Build and Test please

**Comment by fujiy** [comment]
HI?

**Comment by adityamandaleeka** [comment]
:+1:

**Pull request merged**
