### PR TITLE
Disable StringJoin test14

### PR DESCRIPTION
**Pull request by wtgodbe**
Will resolve https://github.com/dotnet/coreclr/issues/12491#issuecomment-314885154

This test is redundant with test cases in CoreFX. I think disabling this one but keeping the other test cases in the project is a fine compromise.

CC @jkotas @BruceForstall @tijoytom

### CODE REVIEW

**Comment by tijoytom** [comment]
@wtgodbe It's showing up as binary file , not sure why .. it's c# file change right?

**Comment by wtgodbe** [comment]
Huh. Weird. I just commented out the test & its invocation, not sure why it's showing up as binaries. Lemme see if I can fix it

**Comment by wtgodbe** [comment]
In any case, diffs are at https://github.com/wtgodbe/coreclr/blob/e5866cb3675c30209020b70210da8d0329063a03/tests/src/CoreMangLib/cti/system/string/stringjoin.cs#L49, https://github.com/wtgodbe/coreclr/blob/e5866cb3675c30209020b70210da8d0329063a03/tests/src/CoreMangLib/cti/system/string/stringjoin.cs#L75, and https://github.com/wtgodbe/coreclr/blob/e5866cb3675c30209020b70210da8d0329063a03/tests/src/CoreMangLib/cti/system/string/stringjoin.cs#L85

**Comment by tijoytom** [comment]
Do you want to delete it ? What's the point in keeping it commented if it's not going to ever run..
LGTM

**Comment by adityamandaleeka** [comment]
I have no comment on the actual review, but I was curious about why this was showing up as a binary file. Looking at this file, it has a byte order mark at the first two bytes, which is causing git to treat it as binary. Sure enough, removing the BOM makes git operations like diff work properly again.

**Pull request merged**
