### PR TITLE
Fix P1 test build break

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by tannergooding** [comment]
Should we log a bug to add a CI leg that just builds, but does not run, the pri-1 tests by default (in order to catch changes like this)?

**Comment by jkotas** [comment]
@dotnet-bot Windows_NT x64 Checked Build and Test

**Comment by jkotas** [comment]
@dotnet-bot test Windows_NT x64 Checked Build and Test please

**Comment by jkotas** [comment]
@dotnet-bot test Windows_NT x64 Checked Build and Test (Jit - EnableIncompleteISAClass=1)  please

**Comment by jkotas** [comment]
test Windows_NT x86 Checked jitnox86hwintrinsic

**Comment by jkotas** [comment]
> Should we log a bug to add a CI leg that just builds, but does not run, the pri-1 tests by default (in order to catch changes like this)?

I do think that this happens that often to be worth it.

**Pull request merged**
