### PR TITLE
Refactor TreeNodeInfoInit

### PR DESCRIPTION
**Pull request by CarolEidt**
Move all the register requirements (TreeNodeInfoInit) code into lsra{arch}.cpp.
Split methods that currently do both tree transformation and register requirements.

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT jitstress1
@dotnet-bot test Windows_NT jitstress2
@dotnet-bot test Windows_NT jitstressregs0x10
@dotnet-bot test Windows_NT jitstressregs0x80
@dotnet-bot test Windows_NT jitstressregs1
@dotnet-bot test Windows_NT jitstressregs2
@dotnet-bot test Windows_NT jitstressregs3
@dotnet-bot test Windows_NT jitstressregs4
@dotnet-bot test Windows_NT jitstressregs8
@dotnet-bot test Windows_NT x86 Checked jitstressregs0x10
@dotnet-bot test Windows_NT x86 Checked jitstressregs0x80
@dotnet-bot test Windows_NT x86 Checked jitstressregs1
@dotnet-bot test Windows_NT x86 Checked jitstressregs2
@dotnet-bot test Windows_NT x86 Checked jitstressregs3
@dotnet-bot test Windows_NT x86 Checked jitstressregs4
@dotnet-bot test Windows_NT x86 Checked jitstressregs8

**Comment by sivarv** [comment]
>                     SetContainsAVXFlags();

This if stmnt can also be moved to lsraxarch.cpp, because it is closer to register specification?

Note that this flag is set by block ops and by SIMD reg specification.  The latter is moved to  lsraxarch.cpp

---
Refers to: src/jit/lowerxarch.cpp:188 in f5a9b4a. [](commit_id = f5a9b4a22925dca9c87d3bb152d96ed9fea18500, deletion_comment = False)

**Comment by sivarv** [comment]
> {

This routine too can be moved to lowerxarch.cpp as it is required for register specification.

---
Refers to: src/jit/lowerxarch.cpp:1058 in f5a9b4a. [](commit_id = f5a9b4a22925dca9c87d3bb152d96ed9fea18500, deletion_comment = False)

**Comment by sivarv** [comment]
> bool Lowering::IsContainableImmed(GenTree* parentNode, GenTree* childNode)

This can be moved to lsraarm64.cpp since it is related to register specification?

---
Refers to: src/jit/lowerarm64.cpp:351 in f5a9b4a. [](commit_id = f5a9b4a22925dca9c87d3bb152d96ed9fea18500, deletion_comment = False)

**Comment by sivarv** [comment]
> bool Lowering::IsContainableImmed(GenTree* parentNode, GenTree* childNode)

This routine can be moved to lsraxarch.cpp since it is related to register specification?

---
Refers to: src/jit/lowerxarch.cpp:1017 in f5a9b4a. [](commit_id = f5a9b4a22925dca9c87d3bb152d96ed9fea18500, deletion_comment = False)

**Comment by sivarv** [comment]
> {

This routine can be moved to lsraarm.cpp since it is related to register specification?

---
Refers to: src/jit/lowerarm.cpp:234 in f5a9b4a. [](commit_id = f5a9b4a22925dca9c87d3bb152d96ed9fea18500, deletion_comment = False)

**Comment by sivarv** [comment]
> bool Lowering::IsCallTargetInRange(void* addr)

This routine can be moved to lsraarm.cpp since it is related to register specification?

---
Refers to: src/jit/lowerarm.cpp:222 in f5a9b4a. [](commit_id = f5a9b4a22925dca9c87d3bb152d96ed9fea18500, deletion_comment = False)

**Comment by sivarv** [comment]
> {

This routine can be moved to lsraarm64.cpp as it is required for register specification?

---
Refers to: src/jit/lowerarm64.cpp:337 in f5a9b4a. [](commit_id = f5a9b4a22925dca9c87d3bb152d96ed9fea18500, deletion_comment = False)

**Comment by sivarv** [comment]
> {

I see this is used for lowering of IR.

---
In reply to: [277134256](https://github.com/dotnet/coreclr/pull/9256#issuecomment-277134256) [](ancestors = 277134256)

---
Refers to: src/jit/lowerarm64.cpp:337 in f5a9b4a. [](commit_id = f5a9b4a22925dca9c87d3bb152d96ed9fea18500, deletion_comment = False)

**Comment by sivarv** [comment]
:shipit:

**Comment by BruceForstall** [comment]
> {

Ugh... merge hell, coming soon...

---
Refers to: src/jit/lowerxarch.cpp:351 in f5a9b4a. [](commit_id = f5a9b4a22925dca9c87d3bb152d96ed9fea18500, deletion_comment = False)

**Comment by CarolEidt** [comment]
> {

Yes, I've already experienced that a couple of times trying to get this rather simple refactoring done :-(
Sorry to spread the pain around!

---
In reply to: [277135826](https://github.com/dotnet/coreclr/pull/9256#issuecomment-277135826) [](ancestors = 277135826)

---
Refers to: src/jit/lowerxarch.cpp:351 in f5a9b4a. [](commit_id = f5a9b4a22925dca9c87d3bb152d96ed9fea18500, deletion_comment = False)

**Comment by CarolEidt** [comment]
>                     SetContainsAVXFlags();

Yes, I think you're right.

---
In reply to: [277131423](https://github.com/dotnet/coreclr/pull/9256#issuecomment-277131423) [](ancestors = 277131423)

---
Refers to: src/jit/lowerxarch.cpp:188 in f5a9b4a. [](commit_id = f5a9b4a22925dca9c87d3bb152d96ed9fea18500, deletion_comment = False)

**Comment by CarolEidt** [comment]
> {

I debated about this (and the others), but intentionally left these kinds of methods in Lowering, as they are sort of "support" methods that might be useful (and possibly abstracted) for other things such as peephole optimizations. I'm going to leave them in the lower{arch}.cpp methods for now; they can be moved later if need be.

---
In reply to: [277133914](https://github.com/dotnet/coreclr/pull/9256#issuecomment-277133914) [](ancestors = 277133914)

---
Refers to: src/jit/lowerarm.cpp:234 in f5a9b4a. [](commit_id = f5a9b4a22925dca9c87d3bb152d96ed9fea18500, deletion_comment = False)

**Comment by CarolEidt** [comment]
>                     SetContainsAVXFlags();

In fact, I had duplicated it, and it was missing altogether for putArgStk, so I have added it.

---
In reply to: [277141698](https://github.com/dotnet/coreclr/pull/9256#issuecomment-277141698) [](ancestors = 277141698,277131423)

---
Refers to: src/jit/lowerxarch.cpp:188 in f5a9b4a. [](commit_id = f5a9b4a22925dca9c87d3bb152d96ed9fea18500, deletion_comment = False)

**Comment by CarolEidt** [comment]
Next step toward #7255

**Pull request merged**
