### PR TITLE
[GDB-JIT][Linux] Add support of base classes introspection  

### PR DESCRIPTION
**Pull request by lucenticus**
This PR adds generation of DWARF information for base classes. Now lldb shows values for fields from base classes.
Sample code: 
```
using System;

public class Parent
{
    public short p1;
    public double p2;
}
public class Child1 : Parent
{
    public int a;
    public double f;
    public static int sch1;
}
public class Child2 : Parent
{
    public int b;
    public long l;
    public static int sch2;
}
public class TestProgram
{
    public static void Main()
    {
        Child1.sch1 = 2;
        Child2.sch2 = 12;
        Child1 ch1 = new Child1();
        Child2 ch2 = new Child2();
        ch1.a = -1;
        ch1.f = 1.5;
        ch1.p1 = -100;
        ch1.p2 = -5.5;
        ch2.b = 11;
        ch2.l = 22;
        ch2.p1 = 100;
        ch2.p2 = 5.5;
    }
}
```

Here is lldb output: 

```
$ CORECLR_GDBJIT='test-parents.exe' ~/FP/LLVM/release/bin/lldb -o "breakpoint set -m false -f test-parents.cs -l 40" -o "r" -o "fr v" ./corerun test-parents.exe
(lldb) target create "./corerun"
Current executable set to './corerun' (x86_64).
(lldb) settings set -- target.run-args  "test-parents.exe"
(lldb) breakpoint set -m false -f test-parents.cs -l 40
Breakpoint 1: no locations (pending).
WARNING:  Unable to resolve breakpoint to any actual locations.
(lldb) r
1 location added to breakpoint 1
Process 8544 stopped
* thread #1: tid = 8544, 0x00007fff7d7286b0 JIT(0x71cc20)`TestProgram::Main() + 240 at test-parents.cs:40, name = 'corerun', stop reason = breakpoint 1.1
    frame #0: 0x00007fff7d7286b0 JIT(0x71cc20)`TestProgram::Main() + 240 at test-parents.cs:40
   37  	        ch2.b = 11;
   38  	        ch2.l = 22;
   39  	        ch2.p1 = 100;
-> 40  	        ch2.p2 = 5.5;
   41  	    }
   42  	}

Process 8544 launched: './corerun' (x86_64)
(lldb) fr v
(Child1 *) ch1 = 0x00007fff60030338
(Child2 *) ch2 = 0x00007fff6003f6a8
(lldb) p *ch1
(Child1) $0 = {
  Parent = (p1 = -100, p2 = -5.5)
  a = -1
  f = 1.5
}
(lldb) p *ch2
(Child2) $1 = {
  Parent = (p1 = 100, p2 = 0)
  b = 11
  l = 22
}
(lldb) 
```
@mikem8361, @janvorli, PTAL

\CC: @Dmitri-Botcharnikov @chunseoklee @ayuckhulk

### CODE REVIEW

**Comment by mikem8361** [comment]
Looks good to me.

**Comment by lucenticus** [comment]
Some issue with recursive inheritance was detected, i'll reopen the PR after fix this issue.

**Comment by lucenticus** [comment]
Done, the issue was detected with the following sample:

```
using System;

public class Grand
{
    static int i = 0;
    
    Son S;
    int j;

    public Grand()
    {
        j = i;
        if (i++ < 100)
        {
            Console.WriteLine(String.Format("I am Son number {0}", i));
            S = new Son();
        }
    }
}
    
public class Son : Grand {}

public class Test
{
    public static void Main()
    {
        Grand G = new Grand();
    }
}

```

**Comment by lucenticus** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test please

**Comment by lucenticus** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test please

**Comment by lucenticus** [comment]
@janvorli, @mikem8361 Please take a look at the updated PR

**Comment by lucenticus** [comment]
Thank you!

**Pull request merged**
