### PR TITLE
Correct casing of file paths in mscorlib

### PR DESCRIPTION
**Pull request by akoeplinger**
Some of the files had a different path/filename casing in the project reference than on disk.

### CODE REVIEW

**Comment by AlexGhiondea** [comment]
Thanks for the contribution! Yes, please squash the commits.

Once we figure out why the build fails we can merge this.

**Comment by mmitche** [comment]
Here's what I see from the log:

d:\j\workspace\dotnet_coreclr_windows_release_prtest\tests\src\TestWrappers_x64_release\managed\managed.XUnitWrapper.cs(82): error : managed.managed._Compilation_Compilation_cmd: \r\nUnhandled Exception: System.TypeInitializationException: The type initializer for 'System.Globalization.CharUnicodeInfo' threw an exception. ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.\r\n   at System.Globalization.GlobalizationAssembly.GetGlobalizationResourceBytePtr(Assembly assembly, String tableName)\r\n   at System.Globalization.CharUnicodeInfo.InitTable()\r\n   at System.Globalization.CharUnicodeInfo..cctor()\r\n   --- End of inner exception stack trace ---\r\n   at System.Globalization.CharUnicodeInfo.InternalGetCategoryValue(Int32 ch, Int32 offset)\r\n   at Microsoft.CodeAnalysis.CSharp.SyntaxFacts.IsWhitespace(Char ch)\r\n   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.Lexer.LexSyntaxTrivia(Boolean afterFirstToken, Boolean isTrailing, SyntaxListBuilder& triviaList)\r\n   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.Lexer.LexSyntaxToken()\r\n   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxParser.PreLex()\r\n   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxParser..ctor(Lexer lexer, LexerMode mode, CSharpSyntaxNode oldTree, IEnumerable`1 changes, Boolean allowModeReset, Boolean preLexIfNotIncremental, CancellationToken cancellationToken)\r\n   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser..ctor(Lexer lexer, CSharpSyntaxNode oldTree, IEnumerable`1 changes, LexerMode lexerMode, CancellationToken cancellationToken)\r\n   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseText(SourceText text, CSharpParseOptions options, String path, CancellationToken cancellationToken)\r\n   at Program.Main(String[] args)\r\n\r\nRaw Output          :d:\j\workspace\dotnet_coreclr_windows_release_prtest\binaries\tests\x64\release\Reports\managed\Compilation\Compilation.output.txt\nTo Run the test     :Step 1. set Core_Root=d:\j\workspace\dotnet_coreclr_windows_release_prtest\binaries\tests\x64\release\Tests\Core_Root\n                     Step 2. d:\j\workspace\dotnet_coreclr_windows_release_prtest\binaries\tests\x64\release\managed\Compilation\Compilation.cmd\n [d:\j\workspace\dotnet_coreclr_windows_release_prtest\tests\runtest.proj]
d:\j\workspace\dotnet_coreclr_windows_release_prtest\tests\src\TestWrappers_x64_release\managed\managed.XUnitWrapper.cs(82): error :    at managed.managed._Compilation_Compilation_cmd() in d:\j\workspace\dotnet_coreclr_windows_release_prtest\tests\src\TestWrappers_x64_release\managed\managed.XUnitWrapper.cs:line 82 [d:\j\workspace\dotnet_coreclr_windows_release_prtest\tests\runtest.proj]
    Finished:    managed.XUnitWrapper
    Finished:    Threading.XUnitWrapper
d:\j\workspace\dotnet_coreclr_windows_release_prtest\tests\src\TestWrappers_x64_release\Regressions\Regressions.XUnitWrapper.cs(277): error : Regressions.Regressions._common_date_cmd: \r\nUnhandled Exception: System.TypeInitializationException: The type initializer for 'System.Globalization.CharUnicodeInfo' threw an exception. ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.\r\n   at System.Globalization.GlobalizationAssembly.GetGlobalizationResourceBytePtr(Assembly assembly, String tableName)\r\n   at System.Globalization.CharUnicodeInfo.InitTable()\r\n   at System.Globalization.CharUnicodeInfo..cctor()\r\n   --- End of inner exception stack trace ---\r\n   at System.Globalization.CharUnicodeInfo.InternalGetCategoryValue(Int32 ch, Int32 offset)\r\n   at System.Globalization.CharUnicodeInfo.IsWhiteSpace(Char c)\r\n   at System.Globalization.DateTimeFormatInfo.InsertHash(TokenHashValue[] hashTable, String str, TokenType tokenType, Int32 tokenValue)\r\n   at System.Globalization.DateTimeFormatInfo.CreateTokenHashTable()\r\n   at System.Globalization.DateTimeFormatInfo.Tokenize(TokenType TokenMask, TokenType& tokenType, Int32& tokenValue, __DTString& str)\r\n   at System.__DTString.GetRegularToken(TokenType& tokenType, Int32& tokenValue, DateTimeFormatInfo dtfi)\r\n   at System.DateTimeParse.Lex(DS dps, __DTString& str, DateTimeToken& dtok, DateTimeRawInfo& raw, DateTimeResult& result, DateTimeFormatInfo& dtfi, DateTimeStyles styles)\r\n   at System.DateTimeParse.TryParse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles, DateTimeResult& result)\r\n   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)\r\n   at DateRepro.Main()\r\n\r\nRaw Output          :d:\j\workspace\dotnet_coreclr_windows_release_prtest\binaries\tests\x64\release\Reports\Regressions\common\date.output.txt\nTo Run the test     :Step 1. set Core_Root=d:\j\workspace\dotnet_coreclr_windows_release_prtest\binaries\tests\x64\release\Tests\Core_Root\n                     Step 2. d:\j\workspace\dotnet_coreclr_windows_release_prtest\binaries\tests\x64\release\Regressions\common\date.cmd\n [d:\j\workspace\dotnet_coreclr_windows_release_prtest\tests\runtest.proj]
d:\j\workspace\dotnet_coreclr_windows_release_prtest\tests\src\TestWrappers_x64_release\Regressions\Regressions.XUnitWrapper.cs(277): error :    at Regressions.Regressions._common_date_cmd() in d:\j\workspace\dotnet_coreclr_windows_release_prtest\tests\src\TestWrappers_x64_release\Regressions\Regressions.XUnitWrapper.cs:line 277 [d:\j\workspace\dotnet_coreclr_windows_release_prtest\tests\runtest.proj]

**Comment by akoeplinger** [comment]
Ok, I fixed the build error and squashed.

The problem was that [CharUnicodeInfo.cs#L71](https://github.com/dotnet/coreclr/blob/cbf46fb0b6a0b209ed1caf4a680910b383e68cba/src/mscorlib/src/System/Globalization/CharUnicodeInfo.cs#L71) hardcodes the lower-case `charinfo.nlp` and this apparently caused the error when I renamed the EmbeddedResource in msbuild.csproj to match `CharInfo.nlp` as it is called on disk.

I decided to rename the file instead of changing the hardcoded values, seemed somehow safer to me :)

**Comment by AlexGhiondea** [comment]
@akoeplinger Yes -- that seems safer to me too! :)

Did we need to rename the nuget.config file as well?

**Comment by akoeplinger** [comment]
@AlexGhiondea yes, NuGet.Config (uppercase C) is used in [dir.props#L43](https://github.com/dotnet/coreclr/blob/b8c186b18496ee71c21e77ba4132b711df6242a2/dir.props#L43) (and there's another NuGet.Config file in the repo so I made it consistent instead of changing dir.props)

**Comment by AlexGhiondea** [comment]
@akoeplinger thanks for cleaning it all up! :)

**Comment by AlexGhiondea** [comment]
LGTM

**Comment by AlexGhiondea** [comment]
Thank you for your contribution!

**Pull request merged**
