### PR TITLE
Embrace echo message with ".." in bash

### LINKED ISSUE #4631: 'runtest.sh' shows some suspicious messages
I found the following message while running CoreCLR unittests:
```
SKIPPED  - JIT/Directed/IL/Tailcall/JitTailcall2/JitTailcall2.sh
               ./JitTailcall2.sh: line 13: syntax error near unexpected token `('
               ./JitTailcall2.sh: line 13: `  echo SKIPPING EXECUTION BECAUSE ONE OR MORE OF (COMPlus_JitStress, COMPlus_JitStressRegs, COMPlus_JITMinOpts) IS SET'
```
It seems that there is some type in the test script.

### PR DESCRIPTION
**Pull request by parjong**
This commit tries to fix #4631.

### CODE REVIEW

**Comment by jkotas** [comment]
LGTM. Thanks!

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by parjong** [comment]
@jkotas It looks like Windows_NT x64 Release Priority 1 Build and Test failed with the following case:
```
D:\j\workspace\x64_release_w---0575cb46\bin\tests\Windows_NT.x64.Release\TestWrappers\baseservices\baseservices.XUnitWrapper.cs(27084): error : baseservices._threading_mutex_misc_waitone2_waitone2_._threading_mutex_misc_waitone2_waitone2_cmd [FAIL] [D:\j\workspace\x64_release_w---0575cb46\tests\runtest.proj]
        
  
  Return code:      1
  Raw output file:      D:\j\workspace\x64_release_w---0575cb46\bin\tests\Windows_NT.x64.Release\Reports\baseservices\threading\mutex\misc\waitone2\waitone2.output.txt
  Raw output:
  BEGIN EXECUTION
         "D:\j\workspace\x64_release_w---0575cb46\tests\..\bin\tests\Windows_NT.x64.Release\Tests\Core_Root\corerun.exe" waitone2.exe  
        Beginning test case MutexWaitOne2 at 4/28/2016 6:48:17 PM
        Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
        
        [Positive]
        Beginning scenario: PosTest1: Wait Infinite
        Beginning scenario: PosTest2: Wait some finite time
        Beginning scenario: PosTest3: Wait some finite time will quit for timeout
        ERROR!!!-004: WaitOne returns true when wait time out
        Beginning scenario: PosTest4: Wait some finite time will quit for timeout when another thread is in nondefault managed context
        Beginning scenario: PosTest5: Wait some finite time will quit for timeout when another thread is in nondefault managed context
        Beginning scenario: PosTest6: Wait infinite time when another thread is in nondefault managed context
        Beginning scenario: PosTest7: Wait infinite time when another thread is in nondefault managed context
        [Negative]
        Beginning scenario: NegTest1: AbandonedMutexException should be thrown if a thread exited without releasing a mutex
        Beginning scenario: NegTest2: ObjectDisposedException should be thrown if current instance has already been disposed
        Beginning scenario: NegTest3: Check ArgumentOutOfRangeException will be thrown if millisecondsTimeout is a negative number other than -1
        
        Ending test case at 4/28/2016 6:48:50 PM
        FAIL
        Expected: 100
        Actual: 0
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        
  To run the test:
  > set CORE_ROOT=D:\j\workspace\x64_release_w---0575cb46\bin\tests\Windows_NT.x64.Release\Tests\Core_Root
  > D:\j\workspace\x64_release_w---0575cb46\bin\tests\Windows_NT.x64.Release\baseservices\threading\mutex\misc\waitone2\waitone2.cmd
  
        Expected: True
        Actual:   False
          D:\j\workspace\x64_release_w---0575cb46\bin\tests\Windows_NT.x64.Release\TestWrappers\baseservices\baseservices.XUnitWrapper.cs(27084,0): at baseservices._threading_mutex_misc_waitone2_waitone2_._threading_mutex_misc_waitone2_waitone2_cmd()
```

Is it related with this change?

**Comment by jkotas** [comment]
It is not related ...

**Comment by parjong** [comment]
@jkotas Thank you :+1:

**Comment by jkotas** [comment]
@parjong Thank you for your contribution and patience as well...

**Pull request merged**
