### PR TITLE
Fix Platform reporting parameters for build pipeline

### PR DESCRIPTION
**Pull request by karajas**
Correctly report platform data
Distinguish the two different sets of Windows test builds

/cc @MattGal @wtgodbe

### CODE REVIEW

**Comment by ChadNedzlek** [comment]
We should change the view config if we can, because that will fix old builds too (and across all the various branches). Changing this means old builds will still use a weird version an not line up with newer builds for any historical data we might want to mine.

**Comment by MattGal** [comment]
@ChadNedzlek  I agree and should probably keep using the wrong properties, but we do need to plumb the wrong properties through to all the jobs so they show up.

**Comment by ChadNedzlek** [comment]
Oh, yes, I didn't notice the last two were adds instead of changes. Agreed.

**Comment by karajas** [comment]
Reverted back to Architecture and added the missing params. 
https://github.com/dotnet/core-eng/pull/1261

**Pull request merged**
