### PR TITLE
Port: Invoke correct pinvoke resolution override for dynamically generated assembly.

### PR DESCRIPTION
**Pull request by gkhanna79**
Fixes https://github.com/dotnet/coreclr/issues/7797

CC @jkotas

### CODE REVIEW

**Comment by gkhanna79** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build  please

**Comment by gkhanna79** [comment]
@mmitche the Linux Arm Debug build timed out twice. Is this a known issue?

**Comment by gkhanna79** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build  please

**Comment by mmitche** [comment]
@gkhanna79 There were no timeouts for any other recent build except for this PR.

**Comment by AndyAyersMS** [comment]
@mmitche I got a timeout on this yesterday, see #7798, specifically [here](https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_emulator_cross_release_ubuntu_prtest/1232/)

**Pull request merged**
