### PR TITLE
Don't try to fold constants for GT_HWIntrinsic

### LINKED ISSUE #25133: JIT: Assert in BMI intrinsic from random inline stress
Have been randomly playing with different seeds for random inline stress and hit this.

To repro (on windows or Linux)
```
COMPlus_TieredCompilation=0
COMPlus_JitInlinePolicyRandom=3

corerun tests\Windows_NT.x64.Checked\jit\HardwareIntrinsics\X86\Bmi1.X64\Bmi1.X64_ro\Bmi1.X64_ro.exe

Assert failure(PID 22518 [0x000057f6], Thread: 22518 [0x57f6]): 
Assertion failed 'tree->gtType == TYP_INT || varTypeIsGC(tree->TypeGet()) || tree->gtOper == GT_MKREFANY'
in 'JIT.HardwareIntrinsics.X86.ScalarTernOpTest__BitFieldExtractUInt64:RunStructLclFldScenario():this' (IL size 71)

              File: /home/andy/repos/coreclr/src/jit/gentree.cpp Line: 13547
              Image: /home/andy/repos/coreclr/bin/tests/Linux.x64.Checked/Tests/Core_Root/corerun
```
Saw this at b5199393; haven't tried newer bits yet.

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by CarolEidt**
Fix #25133

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

**Comment by CarolEidt** [comment]
> do we know why we don't try to fold them for SIMD? Is it a fundamental restriction or a thing to do?

It is not a fundamental restriction, but would require quite a bit of case-specific code to support it for `GT_SIMD` and even more for hardware intrinsics.

**Comment by AndyAyersMS** [comment]
> It is not a fundamental restriction, but would require quite a bit of case-specific code 

Can you give a bit more detail here? What is it that we'd need to do? What (if any) opportunities are we missing out on?

**Comment by CarolEidt** [comment]
In order to fold these constants, we'd have to "emulate" the instruction. For HW intrinsics, we might just have a switch on the intrinsic id, and then invoke the native C++ intrinsic. That said, if the value was a vector type we'd then have to instantiate the constant vector, and we don't really support that yet either.

I don't know how often we would expect to be able to fold constants into intrinsics. My intuition says that it would not be common. But then my intuition has been wrong more than I'd care to say ...

@tannergooding - opinions?

**Comment by tannergooding** [comment]
> @tannergooding - opinions?

In my opinion, it is something that we would ideally support eventually. Clang/GCC already support this and MSVC recently added support for the same (and blogged about it back in Jan): 
<https://devblogs.microsoft.com/cppblog/msvc-backend-updates-in-visual-studio-2019-preview-2/>
> * Added constant-folding and arithmetic simplifications for expressions using SIMD (vector) intrinsic, for both float and integer forms. Most of the usual expression optimizations now handle SSE2 and AVX2 intrinsics, either from user code or a result of automatic vectorization.
> * Several new scalar fused multiply-add (FMA) patterns are identified with /arch:AVX2 /fp:fast. These include the following common expressions: (x + 1.0) * y; (x – 1.0) * y; (1.0 – x) * y; (-1.0 – x) * y
> * Sequences of code that initialize a __m128 SIMD (vector) value element-by-element are identified and replaced by a _mm_set_ps intrinsic. This allows the new SIMD optimizations to consider the value as part of expressions, useful especially if the value has only constant elements. A future update will support more value types.

This may also come up as part of any work towards supporting auto-vectorization.

**Pull request merged**
