### PR TITLE
Add unit test for loading native library from host-provided native se…

### PR DESCRIPTION
**Pull request by kouvel**
…arch paths

Miscellaneous changes:
- Also used and added to existing macros for separator chars and removed the new members I had added to the Path class.
- Fixed tests/runtest.sh to change to the test root directory after setup and before running tests, to allow for relative paths in arguments

Related to #1680

### CODE REVIEW

**Comment by kouvel** [comment]
@janvorli @sergiy-k

**Comment by kouvel** [comment]
Paths are too long :(
Please hold off on reviewing this until I rename some stuff

**Comment by kouvel** [comment]
Updated, should be good to go now

**Comment by janvorli** [comment]
LGTM

**Comment by sergiy-k** [comment]
LGTM. Thank you!

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Pull request merged**
