### PR TITLE
Remove API Set dependency

### PR DESCRIPTION
**Pull request by JohnChen0**

### CODE REVIEW

**Comment by JohnChen0** [comment]
@gkhanna79 PTAL

**Comment by gkhanna79** [comment]
LGTM.

@Maoni0 PTAL as well.

**Comment by gkhanna79** [comment]
@JohnChen0 Will you be enabling PInvoke checker for CoreCLR in a seperate change?

**Comment by JohnChen0** [comment]
@gkhanna79 I'm currently working on enabling PInvoke checker for CoreCLR.

**Comment by jkotas** [comment]
@Maoni0 is OOF till end of the year. The GC changes LGTM.

cc @swgillespie

**Comment by swgillespie** [comment]
👍

**Pull request merged**
