### PR TITLE
Fixed string Join method

### PR DESCRIPTION
**Pull request by AlexRadch**
Fixed string Join(string separator, params object[] values) method.
Calling string.Join(",", null, 1, 2, 3); return empty string but should ",1,2,3".

### CODE REVIEW

**Comment by danmosemsft** [comment]
@AlexRadch unfortunately compatibility with the .NET Framework is very important to us, and that returns "" also. I don't think there is good enough reason to break compatibility here even though it presumably isn't doucmented behavior.

**Comment by AlexRadch** [comment]
How many programs use this unusual behavior as useful? I think no one. 
I think many programs use this Join and in some rare cases can return empty string when should not do it. In other words many programs have erroneous behavior because this method have error and no one use this error as future.
So why .NET Framework still support this bug? And do not fix it?

**Comment by jnm2** [comment]
@danmosemsft I was about to follow this up with, how soon until this fix makes it into full framework? If it has to be quirked, so be it; I seriously hope .NET vNext ships this fix.

**Comment by danmosemsft** [comment]
@jnm2 it looks like the object[] overload of Join has had this bug since it was introduced in 4.0. It seems to me indeed a bug since it's inconsistent with the original string[] overload of Join. Given that I think we might take this change but backporting might take a while. @stephentoub thoughts?

**Comment by jnm2** [comment]
I've already identified two places in the codebase I happen to have open where this bug could cause some very interesting debugging sessions.

**Comment by danmosemsft** [comment]
@stephentoub are you comfortable with this change?

@AlexRadch it would need a follow up change in corefx to add a test

**Comment by stephentoub** [comment]
> @stephentoub are you comfortable with this change?

See my comment at https://github.com/dotnet/coreclr/issues/4506#issuecomment-261016448.  As long as we port the fix back to desktop (under a quirk I guess, in particular since the behavior is documented) and fix the documentation, I'm ok with it.

**Comment by danmosemsft** [comment]
@AlexRadch in a day or two (supposed to be less) corefx will receive this coreclr change. When that happens could you please submit a PR to add tests to protect this? They will go in here corefx\src\System.Runtime\tests\System\StringTests.cs.

**Comment by jamesqo** [comment]
Nice to see this finally fixed! :tada:

**Comment by danmosemsft** [comment]
We have a PR to update our breaking change guidelines here https://github.com/dotnet/corefx/pull/13718

**Comment by AlexRadch** [comment]
@danmosemsft I created pull request https://github.com/dotnet/corefx/pull/13747 with fixed tests.

**Pull request merged**
