### PR TITLE
Fix ARM build break

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by tarekgh** [comment]
@jkotas thanks for fixing this. Why are you marking this as no-merge? do you expect more breaks?

**Comment by jkotas** [comment]
There are more breaks, but they are not related to this. I have removed the no merge label already.

**Comment by tarekgh** [comment]
@jkotas 

could you confirm the failures in  ```Windows_NT arm Cross Checked Build and Test ``` are unrelated? 

```
10:33:34  "C:\Users\DDJOIN\arm64_ci\tests\tests\Tests\Core_Root\corerun.exe" mainv1.exe 
10:33:34 Expected: 100
10:33:34 Actual: 3
```

should we merge this change?

**Comment by jashook** [comment]
These failures were introduced by https://github.com/dotnet/coreclr/pull/13733. @jkotas thank you for fixing this.

**Comment by hqueue** [comment]
It is surprising this bug was still alive.

Thanks for the fix. :)

**Pull request merged**
