### PR TITLE
Arm64:return buffer arg should be passed in x8

### PR DESCRIPTION
**Pull request by rahku**

### CODE REVIEW

**Comment by rahku** [comment]
@dotnet-bot test Windows_NT arm64 Checked
@dotnet-bot test Windows_NT arm64 Release

**Comment by rahku** [comment]
@dotnet-bot test Windows_NT arm64 Checked pr1r2r

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Checked pr1r2r

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Release pr1r2r

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Release

**Comment by rahku** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by rahku** [comment]
@dotnet-bot test Windows_NT arm64 Release

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Checked pri1r2r

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Release pri1r2r

**Comment by briansull** [comment]
I checked in the fix for crossgen

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked pri1r2r

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Release pri1r2r

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked pri1r2r

**Comment by briansull** [comment]
LGTM

**Comment by briansull** [comment]
The only test failure in the Checked Pri1R2R tests is the test that is being disabled by kyulee1  
https://github.com/dotnet/coreclr/pull/5926

**Comment by rahku** [comment]
PTAL @dotnet/arm64-contrib

**Pull request merged**
