### PR TITLE
Move Assert class from Interop into the CoreCLRTestLibrary

### PR DESCRIPTION
**Pull request by vitek-karas**
Moving the Assert class to the common library so that it can be used
by tests outside of the Interop tree.

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test  please

**Comment by jashook** [comment]
This change has broken the pri1 test build.

**Comment by jashook** [comment]
There are two tests that now fail to build:

>Interop\NativeCallable\NativeCallableTest.csproj
>Interop\PrimitiveMarshalling\UIntPtr\PInvokeUIntPtrTest.csproj

```
"C:\Users\shook\projects\coreclr\tests\src\Interop\NativeCallable\NativeCallableTest.csproj" (default target) (1) ->
(CoreCompile target) ->
  NativeCallableTest.cs(12,7): error CS0246: The type or namespace name 'CoreFXTestLibrary' could not be found (are you
 missing a using directive or an assembly reference?) [C:\Users\shook\projects\coreclr\tests\src\Interop\NativeCallable
\NativeCallableTest.csproj]
```

**Pull request merged**
