### PR TITLE
Fix left shift of signed integer - issue 1526

### PR DESCRIPTION
**Pull request by Dmitry-Me**
Should resolve https://github.com/dotnet/coreclr/issues/1526 I isolated the change into a smaller piece and validated it on clang v3.7 The change is explained here http://stackoverflow.com/a/26555274

### CODE REVIEW

**Comment by jasonwilliams200OK** [comment]
Thanks @Dmitry-Me! 
Aside, there is one more thing which breaks the build on FreeBSD with Clang3.6+: [CMakeLists.txt#L22](https://github.com/dotnet/coreclr/blob/167f6cf5da60315946ca3d621c20a2530c0b42ae/src/pal/src/CMakeLists.txt#L22). Would you like to add this petty fix (mark it as `SYSTEM` include) as part of this PR: https://github.com/dotnet/corefx/commit/40ee8c0bf4d8fcdd46cc3058bf1f7eb379a47130? Thanks!

**Comment by Dmitry-Me** [comment]
@jasonwilliams200OK I'm not sure I can address that problem.

**Comment by jasonwilliams200OK** [comment]
Oh come on, you can! ;)

**Comment by Dmitry-Me** [comment]
@jasonwilliams200OK Come on, I haven't touched a makefile for 5+ years.

**Comment by jkotas** [comment]
LGTM. Thanks!

**Pull request merged**
