### PR TITLE
Remove duplicate call to SetProfilerMayHaveActivatedNonDefaultCodeVersion

### PR DESCRIPTION
**Pull request by davmason**
The second call was causing SetProfilerMayHaveActivatedNonDefaultCodeVersion to assert since it was already set

### CODE REVIEW

**Comment by kouvel** [comment]
Ah, I missed that. I added calls to both of the sections that do callbacks to the profiler (before and after jitting) because I figured the profiler could attach (or detach) while jitting, in which case it may skip the first section and only run the second section or vice versa. Is that possible?

Maybe removing the assert would work better.

**Comment by davmason** [comment]
What is your concern if the profiler modifies IL? 

If a profiler is calling `SetILFunctionBody` it would either be during the `ModuleLoadFinished` callback or `JITComplilationStarted` callback, it wouldn't be legal to call during `JITCompilationFinished`. But I wouldn't expect `SetILFunctionBody` to cause tiered compilation any issues, because we effectively just replace the IL with new IL before jitting.

A profiler can call `RequestReJIT` at any point, from before initial jitting to after the method is jitted, including while jitting is happening. It would be possible with ReJIT for a profiler to attach during jitting (or after) and expect methods to be versionable.

**Comment by kouvel** [comment]
The concern was regarding this comment:
https://github.com/dotnet/coreclr/blob/f5437ac095272f1ab5e8ca79960add974fa96f2d/src/vm/codeversion.cpp#L2449-L2452

If the default native code version may be changed synchronously on the same thread during one of the callbacks, to preserve the backward compatibility this call to `SetProfilerMayHaveActivatedNonDefaultCodeVersion` would force the Publish function to recheck the default native code version after jitting so that it does not run an older code version from what was requested by the profiler.

So the call to `SetProfilerMayHaveActivatedNonDefaultCodeVersion` is just conservatively passing back info saying that "the profiler was called and may have changed the default native code version synchronously, preserve backward compatibility and recheck the default code version after jitting". It sounds like this can happen during `JITCompilationStarted` (through `SetILFunctionBody` or through `RequestReJIT`) and during `JITCompilationFinished` (through `RequestReJIT`). I'm not sure which of those cases the backward compatibility comment is referring to, but it specifically mentions `JITCompilationFinished`.

@noahfalk

**Comment by davmason** [comment]
I don't think `SetILFunctionBody` concerns this at all, that wouldn't cause a race. It would just replace the default IL with some new IL, but not trigger a jitting. The profiler can use it to rewrite a method once at load time.

The real concern here is ReJIT, which I don't think the active case (even the way it is before my PR) covers. A profiler doesn't have to subscribe to JIT notifications to be able to ReJIT. In the loop you pointed to the check for `profilerMayHaveActivatedNonDefaultCodeVersion` should probably check if a profiler is present, or if you were really concerned about perf checking if a profiler is present and ReJIT is enabled.

**Comment by kouvel** [comment]
The Publish function doesn't (and can't) provide any guarantees about which version of the method will run due to races (just as it's about to return the native code address for a code version, something may change the default code version). So there wouldn't be any guarantees for ReJIT requests that come in from different threads anyway. If a ReJIT request came in during one of the profiler callbacks synchronously from the same thread, the comment above seems to indicate that for compatibility the thread should check the default native code version after jitting (after all of the profiler callbacks) to ensure that an older version of the method doesn't run on that thread (other threads may still run the older code version).

**Comment by davmason** [comment]
Ok, that makes sense. It seems like the right call is to just remove the assert here, right?

**Pull request merged**
