### PR TITLE
[WIP]  Simple experiment raising the switch limit

### PR DESCRIPTION
**Pull request by russellhadley**
Allows a higher limit for expanding switch tables into if/else linear
searches.  Initial code is to get an idea of the diffs/perf.

### CODE REVIEW

**Comment by russellhadley** [comment]
@dotnet-bot help

**Comment by russellhadley** [comment]
@dotnet-bot test Windows_NT x64 perf

**Comment by russellhadley** [comment]
Diffs are a general code size win across the frameworks:

Found files with textual diffs.

Summary:
(Note: Lower is better)

Total bytes of diff: -3578 (-0.03 % of base)
    diff is an improvement.

Total byte diff includes 0 bytes from reconciling methods
        Base had    0 unique methods,        0 unique bytes
        Diff had    0 unique methods,        0 unique bytes

Top file improvements by size (bytes):
       -1399 : Microsoft.CodeAnalysis.VisualBasic.dasm (-0.06 % of base)
        -912 : Microsoft.CodeAnalysis.CSharp.dasm (-0.04 % of base)
        -217 : System.Linq.Expressions.dasm (-0.04 % of base)
        -202 : Microsoft.VisualBasic.dasm (-0.13 % of base)
        -146 : System.Private.CoreLib.dasm (0.00 % of base)
        -129 : Microsoft.CSharp.dasm (-0.04 % of base)
        -120 : System.Net.Http.dasm (-0.04 % of base)
        -103 : Microsoft.CodeAnalysis.dasm (-0.01 % of base)
         -46 : System.IO.Compression.dasm (-0.06 % of base)
         -38 : System.Linq.dasm (-0.03 % of base)

27 total files with size differences (27 improved, 0 regressed), 52 unchanged.

Top method regessions by size (bytes):
           4 : System.Private.CoreLib.dasm - <GetQueuedWorkItems>d__19:MoveNext():bool:this

Top method improvements by size (bytes):
         -27 : Microsoft.CodeAnalysis.CSharp.dasm - Microsoft.CodeAnalysis.CSharp.SyntaxExtensions:IsInContextWhichNeeds
DynamicAttribute(ref):bool
         -26 : System.Net.Http.dasm - System.Net.Http.Headers.KnownHeaders:GetCandidate(struct):ref (2 methods)
         -21 : System.Linq.Expressions.dasm -
 System.Linq.Expressions.Interpreter.LightCompiler:CompileTypeIsExpression(
ref):this
         -20 : Microsoft.CodeAnalysis.VisualBasic.dasm - Microsoft.CodeAnalysis.VisualBasic.Syntax.CrefReferenceSyntax:G
etNodeSlot(int):ref:this
         -20 : System.IO.Compression.dasm - System.IO.Compression.ZipArchive:Dispose(bool):this
         -19 : Microsoft.CodeAnalysis.VisualBasic.dasm - Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbo
l:FirstDeclarationWithExplicitInterfaces():ref:this
         -19 : Microsoft.CSharp.dasm - Microsoft.CSharp.RuntimeBinder.Semantics.Symbol:IsOverride():bool:this
         -19 : Microsoft.CSharp.dasm - Microsoft.CSharp.RuntimeBinder.Semantics.Symbol:IsHideByName():bool:this
         -19 : Microsoft.VisualBasic.dasm - Microsoft.VisualBasic.CompilerServices.OverloadResolution:CanConvert(ref,ref
,bool,ref,ref,bool,byref,byref):bool
         -19 : Microsoft.Win32.Registry.dasm - Microsoft.Win32.RegistryKey:GetRegistryKeyAccess(int):int

301 total methods with size differences (300 improved, 1 regressed), 78147 unchanged.

Diffs be come more rare when evaluating the tests and only occur in the target case in Bytemark in the benchmarks.

**Comment by mikedn** [comment]
> Total bytes of diff: -3578 (-0.03 % of base)

Hopefully you're not stealing from my BT switch diff :smile:

**Comment by russellhadley** [comment]
@dotnet-bot test Windows_NT x86 Checked Build and Test

**Comment by russellhadley** [comment]
@dotnet-bot Windows_NT arm Cross Checked Build and Test

**Comment by russellhadley** [comment]
Looks like 5 arms on Windows is the sweet spot.  (6 has 3709 reduction due to more wins but the regressions start pulling things down again)

Summary:
(Note: Lower is better)
Total bytes of diff: -5507 (-0.04 % of base)
    diff is an improvement.
Total byte diff includes 0 bytes from reconciling methods
        Base had    0 unique methods,        0 unique bytes
        Diff had    0 unique methods,        0 unique bytes
Top file regressions by size (bytes):
         140 : System.Collections.Immutable.dasm (0.10 % of base)
          18 : System.Text.Encoding.CodePages.dasm (0.03 % of base)
           8 : System.Security.Principal.Windows.dasm (0.02 % of base)
           7 : System.Security.Cryptography.Primitives.dasm (0.04 % of base)
           5 : System.Runtime.Extensions.dasm (0.00 % of base)
Top file improvements by size (bytes):
       -2101 : Microsoft.CodeAnalysis.VisualBasic.dasm (-0.09 % of base)
       -1483 : Microsoft.CodeAnalysis.CSharp.dasm (-0.07 % of base)
        -330 : System.Linq.Expressions.dasm (-0.06 % of base)
        -328 : Microsoft.CodeAnalysis.dasm (-0.04 % of base)
        -320 : System.Private.CoreLib.dasm (-0.01 % of base)
38 total files with size differences (32 improved, 6 regressed), 41 unchanged.
Top method regessions by size (bytes):
          38 : Microsoft.CodeAnalysis.VisualBasic.dasm - Microsoft.CodeAnalysis.VisualBasic.Binder:BindTypeParameterCons
traint(ref,ref,byref,ref,ref):this
          36 : Microsoft.CodeAnalysis.CSharp.dasm - Microsoft.CodeAnalysis.CSharp.Imports:LookupSymbolInUsings(struct,re
f,ref,ref,int,ref,int,bool,byref)
          31 : Microsoft.CodeAnalysis.VisualBasic.dasm - Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel:GetSemanticS
ymbols(struct,ref,int,byref,byref):struct:this
          28 : Microsoft.CodeAnalysis.CSharp.dasm - Microsoft.CodeAnalysis.CSharp.LocalRewriter:MakeBinaryOperator(ref,r
ef,int,ref,ref,ref,ref,bool,bool,ref):ref:this
          26 : Microsoft.CodeAnalysis.CSharp.dasm - <GetMethodsToEmit>d__68:MoveNext():bool:this
Top method improvements by size (bytes):
         -51 : System.Net.Http.dasm - System.Net.Http.Headers.KnownHeaders:GetCandidate(struct):ref (2 methods)
         -33 : Microsoft.CodeAnalysis.dasm - <ComputeAnalyzerDiagnosticsAsync>d__51:MoveNext():this
         -30 : Microsoft.CodeAnalysis.VisualBasic.dasm - Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.Parser
:PeekDeclarationStatement(int):bool:this
         -28 : Microsoft.CodeAnalysis.dasm - BasicBlock:GetReversedBranchOp():char:this
         -28 : System.Private.CoreLib.dasm - System.DefaultBinder:FindMostSpecific(ref,ref,ref,ref,ref,ref,ref,ref):int
686 total methods with size differences (578 improved, 108 regressed), 77762 unchanged.

**Comment by AndyAyersMS** [comment]
@russellhadley anything here worth following up on?

**Comment by AndyAyersMS** [comment]
See also #12868.

**Comment by russellhadley** [comment]
@BruceForstall I never checked these changes in.  So this win is probably still sitting here.  (though as @AndyAyersMS notes CoreFx coded around it in one place)   So your call, is it worth doing the work to get the perf?

**Comment by BruceForstall** [comment]
@russellhadley Seems like something we should implement. Not sure the best way to ensure someone picks it up and it doesn't get lost. Maybe we should open an issue pointing to this PR, since we do queries for open issues, but not for PRs.

**Comment by jkotas** [comment]
Opened https://github.com/dotnet/coreclr/issues/21323 on this.

**Pull request closed without merging**
