### PR TITLE
Add 2.2 sdk/runtime to JitBench

### PR DESCRIPTION
**Pull request by kouvel**

### CODE REVIEW

**Comment by kouvel** [comment]
@dotnet-bot test Windows_NT x64 perf scenarios
@dotnet-bot test Windows_NT x64 min_opts perf scenarios
@dotnet-bot test Windows_NT x86 perf scenarios
@dotnet-bot test Windows_NT x86 min_opts perf scenarios

**Comment by hoyosjs** [comment]
@dotnet-bot Ubuntu arm Cross Checked no_tiered_compilation_innerloop Build and Test
@dotnet-bot Ubuntu arm Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT x64 perf scenarios
@dotnet-bot test Windows_NT x64 min_opts perf scenarios
@dotnet-bot test Windows_NT x86 perf scenarios
@dotnet-bot test Windows_NT x86 min_opts perf scenarios

**Comment by hoyosjs** [comment]
@dotnet-bot Ubuntu arm Cross Checked no_tiered_compilation_innerloop Build and Test
@dotnet-bot Ubuntu arm Cross Checked Innerloop Build and Test

**Comment by kouvel** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test
test Ubuntu x64 Checked CoreFX Tests
test Ubuntu x64 Checked Innerloop Build and Test

**Pull request merged**
