### PR TITLE
Adding System.TimeZone

### PR DESCRIPTION
**Pull request by joperezr**
Adding System.TimeZone to System.Private.CoreLib

cc: @weshaggard 

FYI: @hann013

### CODE REVIEW

**Comment by weshaggard** [comment]
LGTM

**Comment by joperezr** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by joperezr** [comment]
@dotnet-bot test Windows_NT x86 ryujit Checked Build and Test please

**Comment by joperezr** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by joperezr** [comment]
@dotnet-bot test Windows_NT x86 ryujit Checked Build and Test please

**Pull request merged**
