### PR TITLE
Use our local-built instances of tools from Microsoft.DotNet.BuildTools.CoreClr instead of using the package.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Three years ago we moved the all of the sources for the tools in Microsoft.DotNet.BuildTools.CoreClr into the coreclr repo. For most of the tools, we never actually hooked up our CMake build to build the tools locally and use them.

This PR changes our build to use the local tool builds and removes our dependency on the Microsoft.DotNet.BuildTools.CoreClr package.

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
@mikem8361 I was looking at one of @vancem's old PRs in this area (https://github.com/dotnet/coreclr/pull/17004) and he commented that we should look at moving to the Linux way of generating the DAC information so we can move off all of these tools that support the Windows method. Any chance you have some insight on to why that wasn't done or if we should do it?

**Comment by jkoritzinsky** [comment]
Looks like we need to figure out a way to build these tools targetting the host architecture instead of the target architecture. That might explain why this was never done.

**Comment by mikem8361** [comment]
We have talked about doing what we do in Linux with the DAC table which doesn't require these tools but we really never have any time to do this work.  It could introduce race conditions on when the DAC table is available (it did on Linux) made the change some what risky.

I don't know all the reasons or problems with building and using the tools in coreclr like this PR is doing. I only had experience with the Linux mechanism.

**Comment by jkoritzinsky** [comment]
The diff in build.cmd looks pretty ugly. What I did there was move the cross-native build before the native build (and added a few extra CMake defines).

**Comment by jkoritzinsky** [comment]
@BruceForstall the _il_relthread-race test timed out on the Linux arm64 checked run.

**Comment by jkoritzinsky** [comment]
As this change is Windows-only I'm going to merge this in.

**Comment by BruceForstall** [comment]
> @BruceForstall the _il_relthread-race test timed out on the Linux arm64 checked run.

Ugh. I recently disable it, but only under GCStress: https://github.com/dotnet/coreclr/pull/24174

**Pull request merged**
