### PR TITLE
Don't mark calls to allocation helpers as CSE candidates.

### PR DESCRIPTION
**Pull request by erozenfeld**
Marking them as CSE candidates usually blocks CSEs rather than enables them.
A typical case is:
 [1] GT_IND(x) = GT_CALL ALLOC_HELPER
...
[2] y = GT_IND(x)
...
[3] z = GT_IND(x)
If we mark CALL ALLOC_HELPER as a CSE candidate, we later discover
that it can't be a CSE def because GT_INDs in [2] and [3] can cause
more exceptions (NullRef) so we abandon this CSE.
If we don't mark CALL ALLOC_HELPER as a CSE candidate, we are able
to use GT_IND(x) in [2] as a CSE def and do a CSE on [2] and [3].

### CODE REVIEW

**Comment by erozenfeld** [comment]
x64 pmi diffs:

```
Found 26 files with textual diffs.
PMI Diffs for System.Private.CoreLib.dll, framework assemblies for  default jit
Summary:
(Lower is better)
Total bytes of diff: -168 (0.00% of base)
    diff is an improvement.
Top file regressions by size (bytes):
          34 : System.Private.CoreLib.dasm (0.00% of base)
          22 : System.Net.Primitives.dasm (0.03% of base)
          13 : System.Security.Principal.Windows.dasm (0.03% of base)
           3 : System.Diagnostics.Process.dasm (0.00% of base)
           3 : System.Net.Ping.dasm (0.01% of base)
Top file improvements by size (bytes):
         -53 : System.Private.Xml.dasm (0.00% of base)
         -32 : Microsoft.CSharp.dasm (-0.01% of base)
         -28 : Microsoft.CodeAnalysis.VisualBasic.dasm (0.00% of base)
         -27 : System.Reflection.Metadata.dasm (-0.01% of base)
         -24 : Microsoft.CodeAnalysis.CSharp.dasm (0.00% of base)
25 total files with size differences (19 improved, 6 regressed), 104 unchanged.
Top method regressions by size (bytes):
          27 ( 6.32% of base) : System.Private.CoreLib.dasm - UTF7Encoding:MakeTables():this
          13 ( 4.42% of base) : System.Net.Primitives.dasm - IPAddress:.ctor(struct):this
          13 ( 1.75% of base) : System.Security.Principal.Windows.dasm - SecurityIdentifier:CreateFromParts(long,ref):this
          12 ( 3.73% of base) : System.Private.CoreLib.dasm - Random:.ctor(int):this
           9 ( 2.63% of base) : System.Net.Primitives.dasm - IPAddress:.ctor(struct,long):this
Top method improvements by size (bytes):
         -32 (-8.77% of base) : Microsoft.CSharp.dasm - ErrArg:.ctor(ref):this (6 methods)
         -28 (-8.02% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - PEModuleBuilder:SetMethodTestData(ref):this
         -25 (-1.25% of base) : System.Reflection.Metadata.dasm - <OrderBy>d__3`1:MoveNext():bool:this (5 methods)
         -24 (-7.00% of base) : Microsoft.CodeAnalysis.CSharp.dasm - PEModuleBuilder:SetMethodTestData(ref):this
         -24 (-4.06% of base) : System.Private.Xml.dasm - XmlTextReaderImpl:.ctor(ref,ref,ref,ref):this (2 methods)
Top method regressions by size (percentage):
          27 ( 6.32% of base) : System.Private.CoreLib.dasm - UTF7Encoding:MakeTables():this
          13 ( 4.42% of base) : System.Net.Primitives.dasm - IPAddress:.ctor(struct):this
          12 ( 3.73% of base) : System.Private.CoreLib.dasm - Random:.ctor(int):this
           5 ( 3.38% of base) : Microsoft.CodeAnalysis.dasm - LargeEncodedText:.ctor(struct,ref,struct,int):this
           9 ( 2.63% of base) : System.Net.Primitives.dasm - IPAddress:.ctor(struct,long):this
Top method improvements by size (percentage):
         -12 (-9.52% of base) : System.Security.Cryptography.Csp.dasm - CspKeyContainerInfo:.ctor(ref,bool):this
         -32 (-8.77% of base) : Microsoft.CSharp.dasm - ErrArg:.ctor(ref):this (6 methods)
         -28 (-8.02% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - PEModuleBuilder:SetMethodTestData(ref):this
         -24 (-7.00% of base) : Microsoft.CodeAnalysis.CSharp.dasm - PEModuleBuilder:SetMethodTestData(ref):this
         -24 (-4.06% of base) : System.Private.Xml.dasm - XmlTextReaderImpl:.ctor(ref,ref,ref,ref):this (2 methods)
67 total methods with size differences (45 improved, 22 regressed), 188941 unchanged.
1 files had text diffs but not size diffs.
System.Collections.dasm had 116 diffs
```

**Comment by erozenfeld** [comment]
Sometimes extra CSEs result in code size increases so some methods regressed.

**Comment by erozenfeld** [comment]
@AndyAyersMS @sandreenko @dotnet/jit-contrib PTAL

**Comment by erozenfeld** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test (Jit - TieredCompilation=0)

**Comment by briansull** [comment]
I have seen similar issues around this.

The underlying issue is that indirections of the left-hand-side of an assignment are currently prevent CSE's because of the reason that you stated.  I have a idea on how to fix this by removing the NullRef exceptions on the ValueNumbers foe the subsequent uses.
So we may need to back out this change in the future, if and when I make the changes to fxi this.

**Comment by erozenfeld** [comment]
@briansull Are you ok with checking in this change until we have a more general solution?

**Comment by briansull** [comment]
yes i am ok with this change

**Comment by erozenfeld** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by erozenfeld** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by erozenfeld** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by erozenfeld** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by erozenfeld** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by erozenfeld** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Pull request merged**
