### PR TITLE
Update BuildTools version

### PR DESCRIPTION
**Pull request by jcagme**
Improvements where don to the way we download things from Azure on the sync step

### CODE REVIEW

**Comment by jkotas** [comment]
This is part of #15007 already.

**Comment by jcagme** [comment]
Thanks @jkotas for pointing this out

**Comment by jcagme** [comment]
Actually as @weshaggard pointed out the maestro PR change is for master not for release/2.0.0 as this one

**Comment by jcagme** [comment]
@dotnet-bot test Ubuntu arm Cross Release Build please
@dotnet-bot test Ubuntu16.04 arm Cross Debug Build please

**Comment by jcagme** [comment]
This PR is an attempt to fix https://github.com/dotnet/core-eng/issues/2071

**Comment by jcagme** [comment]
@dotnet-bot test this please

**Comment by jcagme** [comment]
@dotnet-bot test Tizen armel Cross Release Build please

**Comment by jcagme** [comment]
@dotnet-bot test this please

**Pull request closed without merging**
