### PR TITLE
Convert all Sse2.Compare* tests to template based

### PR DESCRIPTION
**Pull request by 4creators**
Work toward #19245

### CODE REVIEW

**Comment by 4creators** [comment]
@dotnet-bot test Windows_NT x64 Checked jitincompletehwintrinsic
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnoavx
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnoavx2
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnosimd
@dotnet-bot test Windows_NT x64 Checked jitnox86hwintrinsic

@dotnet-bot test Windows_NT x86 Checked jitincompletehwintrinsic
@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnoavx
@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnoavx2
@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnosimd
@dotnet-bot test Windows_NT x86 Checked jitnox86hwintrinsic

@dotnet-bot test Ubuntu x64 Checked jitincompletehwintrinsic
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnoavx
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnoavx2
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnosimd
@dotnet-bot test Ubuntu x64 Checked jitnox86hwintrinsic

**Comment by tannergooding** [comment]
Please don't include the same commit in multiple PRs (3c284d2) 😄 It makes it harder to review code and leads to the same feedback being left in multiple places.

**Comment by 4creators** [comment]
This is not the same commit, the second one fixes error in first one.

**Comment by tannergooding** [comment]
> This is not the same commit, the second one fixes error in first one

Same point. You have two commits, with the same commit message, in two different PRs, that do basically the same thing, but with some slight variation.

That type of change would be best suited to its own PR, where it can be measured on its own. With you needing to fixup whatever PRs were left open after the initial one was merged.

**Comment by 4creators** [comment]
@tannergooding Corrected, sorry for confusion 😄

**Comment by 4creators** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by 4creators** [comment]
@dotnet-bot test Windows_NT x64 Checked jitincompletehwintrinsic
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnoavx
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnoavx2
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnosimd
@dotnet-bot test Windows_NT x64 Checked jitnox86hwintrinsic

@dotnet-bot test Windows_NT x86 Checked jitincompletehwintrinsic
@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnoavx
@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnoavx2
@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnosimd
@dotnet-bot test Windows_NT x86 Checked jitnox86hwintrinsic

@dotnet-bot test Ubuntu x64 Checked jitincompletehwintrinsic
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnoavx
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnoavx2
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnosimd
@dotnet-bot test Ubuntu x64 Checked jitnox86hwintrinsic

**Comment by 4creators** [comment]
@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnosimd

**Comment by 4creators** [comment]
Rerunning test due to known failure
```cli
baseservices_threading._waithandle_waitany_waitanyex2_waitanyex2_._waithandle_waitany_waitanyex2_waitanyex2_cmd
```

**Comment by 4creators** [comment]
@CarolEidt @eerhardt @fiigii @tannergooding PR is ready for review PTAL

**Comment by 4creators** [comment]
@CarolEidt @eerhardt @fiigii @tannergooding Ping, PR is already 10 days old and awaits for code review. PTAL

**Comment by tannergooding** [comment]
@4creators, it looks like this also included the `PackSignedSaturate`, `PackUnsignedSaturate`, `UnpackHigh`, and `UnpackLow` changes that were supposed to be part of https://github.com/dotnet/coreclr/pull/19670

The feedback given here: https://github.com/dotnet/coreclr/pull/19670#issuecomment-418540815 still applies and we should probably update #19670 to resolve it 😄

**Pull request merged**
