### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by pborreli**

### CODE REVIEW

**Comment by AlexGhiondea** [comment]
Hi

Thanks for the contribution.

Could you update the commit message to follow the published guidelines?

https://github.com/dotnet/corefx/wiki/Contributing#commits

**Comment by pborreli** [comment]
@AlexGhiondea would you mind to explain what is wrong in this commit message please ?

**Comment by AlexGhiondea** [comment]
@pborreli In my opinion the commit message is too short and too vague. Looking at it I can't tell which files (or at least which areas) where touched. I see that there are changes not jut to comments but to some code as well.

Also, I don't think it follows the git standard of using the verb at present tense (but that is just nit-picking).

**Comment by pborreli** [comment]
@AlexGhiondea already made more than 1000 pull request on GitHub using same commit message (`Fixed typo` or `Fixed typos`) and it's the first time I have this kind of feedback.

**Comment by AlexGhiondea** [comment]
I can see your point in this particular case, and I don't have a better commit message in mind right now.

But please understand that we have to maintain this code going forward and having meaningful comments will help years from now to understand why a change was made.

Internally we are pushing hard to write better commit messages so sorry if I came in too strong about this.

Please do take a look at the link I provided as it contains the same guidance we are pushing people to follow internally.

**Comment by luxe** [comment]
@pborreli  Also, I think it would be better if you gave the definition of each word that you corrected.  This will make it easier to understand what exactly the typos were.  Follow the guidelines given to you, and don't forget to provide the etymology of these words, as well as the manufacturer of the keyboard you used.

**Comment by copumpkin** [comment]
@AlexGhiondea it seems unlikely that even several years from now, there would be any confusion when a new developer comes along, runs a git blame on a file, and sees a commit message saying "Fixed typo". I struggle to imagine any sort of clarification that would add more actual information. Artificially inflating the commit message just to meet an arbitrary standard (one that I mostly agree with, for semantically meaningful changes) feels like it would just decrease the signal to noise ratio, if anything.

**Comment by jkotas** [comment]
Thank you for fixing the typos

**Pull request merged**
