### PR TITLE
Port desktop tests that had references

### PR DESCRIPTION
**Pull request by richardlford**
This change ports desktop tests that had references to dlls.
It also fixes some of the dll project files.
In addition there are some additional tests that were not
previously ported (but that do not reference dlls).

There are 4 tests that are excluded because of issue #3216.

### CODE REVIEW

**Comment by richardlford** [comment]
@pgavlin, PTAL.

**Comment by pgavlin** [comment]
@richardlford: it looks like we should leave JIT\Regression\CLR-x86-JIT\V1.2-M02\b102447 unported since it depends on features that are not available in .Net Core.

**Comment by pgavlin** [comment]
LGTM otherwise.

**Comment by richardlford** [comment]
@pgavlin, Thanks. I've deleted JIT\Regression\CLR-x86-JIT\V1.2-M02\b102447 and also add exclusions for tests failing on non-Windows platforms.

**Pull request merged**
