### PR TITLE
[ARM/Linux] Disable unittest `_il_reltypeEqualOp`

### PR DESCRIPTION
**Pull request by wateret**
Following test contains undefined behaviour.
(Casting double to ulong for a value that cannot be represent as ulong.)

- JIT.Methodical.casts.ilseq._il_reltypeEqualOp._il_reltypeEqualOp

For #5949

### CODE REVIEW

**Comment by wateret** [comment]
```
 585 FORCEINLINE INT64 FastDbl2Lng(double val)
 586 {       
 587 #ifdef _TARGET_X86_
 588     FCALL_CONTRACT;       
 589     return HCCALL1_V(JIT_Dbl2Lng, val);
 590 #else
 591     FCALL_CONTRACT; 
 592     return((__int64) val);
 593 #endif  
 594 }
```

For arm, casting double to ulong is just c-style cast. AFAIK it is undefined behaviour if the integer part of the double value is not representable as ulong.

Please let me know if I'm wrong. Otherwise I think we need to merge this. or even get rid of the test case.

**Comment by wateret** [comment]
Added `JIT.Regression.CLR-x86-JIT.V1-M10.b08107` to the unsupported test list as it has the same issue. (`double` to `long` in this case)

**Comment by wateret** [comment]
cc: @dotnet/jit-contrib Please take a look.

**Comment by kyulee1** [comment]
Undefined behavior from double to long conversion is not arm specific. I would delete the tests instead of skipping them for arm. I recall b08107 is such case for arm64 as well.

I haven't seen such issue for _il_reltypeEqualOp yet in arm64 testings. Can you point which part of il assembly/machine code has this issue (w/ input value)?

**Comment by wateret** [comment]
@jkotas Please take a look. (and issue #5949)

**Comment by jkotas** [comment]
I agree that tests testing unspecified behavior are bad and should be deleted.

**Comment by wateret** [comment]
@kyulee1 

For each test:
- https://github.com/dotnet/coreclr/blob/master/tests/src/JIT/Methodical/casts/ilseq/typeEqualOp.il#L570
- https://github.com/dotnet/coreclr/blob/master/tests/src/JIT/Regression/CLR-x86-JIT/V1-M10/b08107/b08107.il#L7728

In _il_reltypeEqualOp, I tested it like:
```
+dup
+call void [System.Console]System.Console::WriteLine(float32)
conv.u8
+dup
+call void [System.Console]System.Console::WriteLine(uint64)
```

And the results were:
```
[x64]
-7.001131E+34
9223372036854775808
 
[arm]
-7.001131E+34
1
```
I also reproduced this part as C# in #5949.

**Comment by wateret** [comment]
@kyulee1, @jkotas 
Definitely I agree with removing these test cases if they are not valid. Then I'd rather change this PR to delete them instead of skipping.

@kyulee1 
Could you please check _il_reltypeEqualOp on arm64 and see if I'm right. IMHO, even if it passes on arm64, it could be a coincidence.

**Comment by kyulee1** [comment]
Thanks for the test case and update arm64 as well. LGTM.

**Comment by RussKeldorph** [comment]
@wateret @kyulee1: Since you have more familiarity with the tests: do you know if it would likely be a small amount of work to surgically remove the invalid portions of these tests and retain the valid portions (assuming there are some)?  I certainly don't object to this change as is; I'm just wondering if it might be worth it to analyze these tests once we have a decent code coverage story to see if we have thrown out something valuable.

**Comment by wateret** [comment]
@RussKeldorph Basically I agree with what you said, but given TCs are in CIL and don't seem to be written by a human.

`b08107` is way too big(15000+ LOC) and I'm not sure how many invalid portions it has. However I think I could do that for `_il_reltypeEqualOp` as I know that it has few invalid portions.

**Comment by RussKeldorph** [comment]
@wateret Thanks.  To be clear, I'm not asking you to fix the tests.  I'm just wondering if you think it would be worth it for someone (anyone) to revisit these tests in the future when we have coverage tools that can tell if there is something unique worth retaining.

**Pull request merged**
