### PR TITLE
Fix event pipe session provider list clear

### LINKED ISSUE #24772: Investigate "tests/src/tracing/*" failures on Alpine amd64
Test has been disabled with https://github.com/dotnet/coreclr/pull/24417

The logs show a segfault on tracing disable (only Alpine):
```log
  Starting:    tracing.eventsource.XUnitWrapper
    tracing/eventsource/eventsourcetrace/eventsourcetrace/eventsourcetrace.sh [FAIL]
      /root/helix/work/workitem/tracing/eventsource/eventsourcetrace/eventsourcetrace/eventsourcetrace.sh: line 271:  9005 Segmentation fault      (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/tracing/eventsource/Reports/tracing.eventsource/eventsourcetrace/eventsourcetrace/eventsourcetrace.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun eventsourcetrace.exe ''
          Start: Enable tracing.
          End: Enable tracing.
      
          Start: Messaging.
          End: Messaging.
      
          Start: Disable tracing.
      Expected: 100
      Actual: 139
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/root/helix/work/correlation
      > /root/helix/work/workitem/tracing/eventsource/eventsourcetrace/eventsourcetrace/eventsourcetrace.sh
      Expected: True
      Actual:   False
      Stack Trace:
        /__w/1/s/bin/tests/Linux.x64.Release/TestWrappers/tracing.eventsource/tracing.eventsource.XUnitWrapper.cs(131,0): at tracing_eventsource._eventsourcetrace_eventsourcetrace_eventsourcetrace_._eventsourcetrace_eventsourcetrace_eventsourcetrace_sh()
      Output:
        /root/helix/work/workitem/tracing/eventsource/eventsourcetrace/eventsourcetrace/eventsourcetrace.sh: line 271:  9005 Segmentation fault      (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
        
        Return code:      1
        Raw output file:      /root/helix/work/workitem/tracing/eventsource/Reports/tracing.eventsource/eventsourcetrace/eventsourcetrace/eventsourcetrace.output.txt
        Raw output:
        BEGIN EXECUTION
        /root/helix/work/correlation/corerun eventsourcetrace.exe ''
            Start: Enable tracing.
            End: Enable tracing.
        
            Start: Messaging.
            End: Messaging.
        
            Start: Disable tracing.
        Expected: 100
        Actual: 139
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/root/helix/work/correlation
        > /root/helix/work/workitem/tracing/eventsource/eventsourcetrace/eventsourcetrace/eventsourcetrace.sh
```

### LINKED ISSUE #24839: Several tracing test failures in official build on Linux/ARM, Linux/ARM64 and Win7
https://mc.dot.net/#/product/netcore/master/source/official~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190529.1/workItem/PayloadGroup0

@sywhang @jorive @noahfalk @dotnet/dotnet-diag

### LINKED ISSUE #24851: Test failure: tracing_eventsource._eventsourcetrace_eventsourcetrace_eventsourcetrace_/_eventsourcetrace_eventsourcetrace_eventsourcetrace_cmd
The test `tracing_eventsource._eventsourcetrace_eventsourcetrace_eventsourcetrace_/_eventsourcetrace_eventsourcetrace_eventsourcetrace_cmd` has failed.

Failure Message:
```
Internal CLR error. (0x80131506)\r
   at System.Diagnostics.Tracing.EventPipe.Disable()\r
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean, Boolean)\r
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)\r
   at Tracing.Tests.Common.TraceControl.Disable()\r
   at Tracing.Tests.EventSourceTrace.Main(System.String[])\r
\r
Return code:      1\r
Raw output file:      C:\\dotnetbuild\\work\\2ce71b63-3ca8-41a6-879c-d253aeed7a53\\Work\\ed226a49-4ace-4bc5-a8cb-c7f068fc5d65\\Exec\\tracing\\eventsource\\Reports\\tracing.eventsource\\eventsourcetrace\\eventsourcetrace\\eventsourcetrace.output.txt\r
Raw output:\r
BEGIN EXECUTION\r
        1 file(s) copied.\r
\" C:\\dotnetbuild\\work\\2ce71b63-3ca8-41a6-879c-d253aeed7a53\\Payload\\crossgen.exe\"  /Platform_Assemblies_Paths C:\\dotnetbuild\\work\\2ce71b63-3ca8-41a6-879c-d253aeed7a53\\Payload;C:\\dotnetbuild\\work\\2ce71b63-3ca8-41a6-879c-d253aeed7a53\\Work\\ed226a49-4ace-4bc5-a8cb-c7f068fc5d65\\Exec\\tracing\\eventsource\\eventsourcetrace\\eventsourcetrace\\IL;C:\\dotnetbuild\\work\\2ce71b63-3ca8-41a6-879c-d253aeed7a53\\Work\\ed226a49-4ace-4bc5-a8cb-c7f068fc5d65\\Exec\\tracing\\eventsource\\eventsourcetrace\\eventsourcetrace /in eventsourcetrace.org /out eventsourcetrace.exe\r
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0\r
Copyright (c) Microsoft Corporation.  All rights reserved.\r
\r
Native image eventsourcetrace.exe generated successfully.\r
 \"C:\\dotnetbuild\\work\\2ce71b63-3ca8-41a6-879c-d253aeed7a53\\Payload\\corerun.exe\" eventsourcetrace.exe \r
\tStart: Enable tracing.\r
\tEnd: Enable tracing.\r
\r
\tStart: Messaging.\r
\tEnd: Messaging.\r
\r
\tStart: Disable tracing.\r
Expected: 100\r
Actual: -1073741819\r
END EXECUTION - FAILED\r
FAILED\r
Test Harness Exitcode is : 1\r
To run the test:\r
> set CORE_ROOT=C:\\dotnetbuild\\work\\2ce71b63-3ca8-41a6-879c-d253aeed7a53\\Payload\r
> C:\\dotnetbuild\\work\\2ce71b63-3ca8-41a6-879c-d253aeed7a53\\Work\\ed226a49-4ace-4bc5-a8cb-c7f068fc5d65\\Exec\\tracing\\eventsource\\eventsourcetrace\\eventsourcetrace\\eventsourcetrace.cmd\r
Expected: True\r
Actual:   False
```

Stack Trace:
```
   at tracing_eventsource._eventsourcetrace_eventsourcetrace_eventsourcetrace_._eventsourcetrace_eventsourcetrace_eventsourcetrace_cmd() in F:\workspace\_work\1\s\bin\tests\Windows_NT.x86.Release\TestWrappers\tracing.eventsource\tracing.eventsource.XUnitWrapper.cs:line 126
```

Build : Master - 20190529.4 (Ready-To-Run Tests)
Failing configurations:
- Windows.7.Amd64
  - x86
  - x64

Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fr2r~2Fcli~2F/build/20190529.4/workItem/PayloadGroup0/analysis/xunit/tracing_eventsource._eventsourcetrace_eventsourcetrace_eventsourcetrace_~2F_eventsourcetrace_eventsourcetrace_eventsourcetrace_cmd

### PR DESCRIPTION
**Pull request by hoyosjs**
During disable, we clear the provider list. There was a use on a freed pointer, so just reorder the deletion order.

Fixes #24772

Fixes for parts of:
Fixes #24851
Fixes #24839

### CODE REVIEW

**Comment by cshung** [comment]
I am working on the code review for this one, based on code reading, I suspect we might have two bugs here:

-Deleting the sentinel in the list, and
- Never deleting the very first element value in the list.

That's said - this is based on code reading of `slist.h`. The code is not long, but it is terse with operators, it is much safer for us to conclude with an experiment instead.

**Comment by mjsabby** [comment]
Looks like you rebased your PR, instead of squash and merge. Was that intentional? I'm trying everyone to use squash and merge unless there is a strong reason not to.

**Comment by cshung** [comment]
> Looks like you rebased your PR, instead of squash and merge. Was that intentional? I'm trying everyone to use squash and merge unless there is a strong reason not to.

That was an unintentional mistake.

**Pull request merged**
