### PR TITLE
Fix MaskMove_r test build configuration to not optimized

### LINKED ISSUE #19000: [x86/Windows] Failure in JIT\HardwareIntrinsics\X86\Sse2\MaskMove_r\MaskMove_r.cmd
x86 Windows JitStress=2 JitStressRegs=3 failure

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_jitstress2_jitstressregs3/555/consoleText

```
  BEGIN EXECUTION
         "D:\j\workspace\x86_checked_w---508bfa85\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" MaskMove_r.exe 
        Expected: 100
        Actual: 85026320
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        
  To run the test:
  > set CORE_ROOT=D:\j\workspace\x86_checked_w---508bfa85\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root
  > D:\j\workspace\x86_checked_w---508bfa85\bin\tests\Windows_NT.x86.Checked\JIT\HardwareIntrinsics\X86\Sse2\MaskMove_r\MaskMove_r.cmd
  
        Expected: True
        Actual:   False
          D:\j\workspace\x86_checked_w---508bfa85\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT.HardwareIntrinsics\JIT.HardwareIntrinsics.XUnitWrapper.cs(14737,0): at JIT_HardwareIntrinsics._X86_Sse2_MaskMove_r_MaskMove_r_._X86_Sse2_MaskMove_r_MaskMove_r_cmd()
```

Same test failure previously: https://github.com/dotnet/coreclr/issues/17634

### PR DESCRIPTION
**Pull request by 4creators**
~~Fixes #19000 issue~~

~~Fix is masked by #19075.~~

PR cannot be tested as long as #19075 issues is not fixed.

Confirmed locally that solution works, however it is unclear to me what is the mechanism which fixes it - I am not sufficiently familiar with test framework to workout intricacies of _r project type interactions with optimised C# compilation.

### CODE REVIEW

**Comment by CarolEidt** [comment]
@4creators - While this may make the failure go away, we need to determine *why* turning on optimization causes this to fail. I see that you posted the before & after disasm; presumably there's a functional difference there that's causing the failure. Let me know if you'd like me to have a deeper look into it.

**Comment by 4creators** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

OSX failures are unrelated. Cannot test CI as f48801ea7c1412e228a5230ec6cbeabdf5277ec0 blocks CI test run for last couple of days for `JitStress=2`/`JitStressRegs=3`.

**Comment by 4creators** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test please

**Comment by CarolEidt** [comment]
@4creators - I assume this PR can be closed now?

**Comment by 4creators** [comment]
Right, closing.

**Pull request closed without merging**
