### PR TITLE
Temporarily disable some WaitAny tests that have been failing periodically in the CI

### PR DESCRIPTION
**Pull request by kouvel**
There have been failures on various archs and platforms. Issues:
- https://github.com/dotnet/coreclr/issues/19515
- https://github.com/dotnet/coreclr/issues/19406
- https://github.com/dotnet/coreclr/issues/14249

### CODE REVIEW

**Comment by benaadams** [comment]
Hmm; wonder if related https://github.com/dotnet/coreclr/pull/21245

**Comment by benaadams** [comment]
> Hmm; wonder if related #21245

nvm, these errors were way before that PR

**Comment by kouvel** [comment]
@dotnet-bot test Ubuntu x64 Checked CoreFX Tests

**Comment by jashook** [comment]
Merging to hopefully get a clean official build test run.

**Pull request merged**
