### PR TITLE
[release/2.2] Added Close On Exec Attribute for Mutex files

### PR DESCRIPTION
**Pull request by odhanson**
Fixes: #21455
Backport: bc03ef9aeb

### CODE REVIEW

**Comment by odhanson** [comment]
cc: @danmosemsft

**Comment by kouvel** [comment]
#### Description

From @odhanson:

The issue occurs when the parent process creates and acquires a named Mutex. Then a child process is spawned which opens the named mutex and tries to acquire a lock. Then the parent process ends without releasing the mutex. According to documentation (and also verified behavior on windows) an AbandonedMutexException should be thrown in the child process.

I have debugged the issue, and it turns out that the problem is with how we spawn new processes. We are basically using Fork and Exec in Unix systems. However, by default, the parent's opened file descriptors are kept open after fork and exec. Also, exclusive locks are [inherited by fork/exec](https://en.wikipedia.org/wiki/File_locking). So it turns out that the child process already has an exclusive lock to the mutex file (without knowing about it) and when the parent dies, this lock remains, thus we do not receive the abandoned exception.

#### Customer Impact

A child process may not be able to identify a mutex abandoned by a parent process in some cases. This could lead to a thread of the child process waiting for the lock indefinitely.

#### Regression?

No

#### Packaging reviewed?

N/A - CoreCLR only

#### Risk

A new flag is added to `open()` calls relevant to named mutexes that prevents those file descriptors from being duplicated by `fork()` and file locks associated with those descriptors from being inherited by the new process. The child process does not use duplicated file descriptors, so all it can do is to hold on to the file lock beyond the lifetime of the parent process, preventing detecting the mutex as abandoned by any other process. The risk is minimal, as the new behavior is the intended behavior.

**Comment by danmosemsft** [comment]
@kouvel do you concur that the risk is minimal? Eg could code be depending on current behavior?

**Comment by kouvel** [comment]
It's unlikely that existing code would depend on the current incorrect behavior, it's more likely that the current behavior is unknown/unexpected and may lead to a hang. I feel the risk is minimal.

**Comment by kouvel** [comment]
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test

**Comment by danmosemsft** [comment]
Shiproom says: approved, but we should include a test (either in coreclr pal tests or corefx whichever is easiest). @odhanson is that something you can help create?

**Comment by danmosemsft** [comment]
Branch not yet open for 2.2.2

**Comment by kouvel** [comment]
I can include the test from https://github.com/dotnet/coreclr/pull/21496

**Comment by danmosemsft** [comment]
Thanks @kouvel 

@dotnet-bot test this please ("FATAL: command execution failed
java.nio.channels.ClosedChannelException")

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by odhanson** [comment]
@danmosemsft  any estimate when we can complete this PR ?

**Comment by danmosemsft** [comment]
@odhanson branch expected to open for 2.2.2  on 1/9.

**Pull request merged**
