### PR TITLE
[release/2.1] Determine memory load based on cgroup usage.

### PR DESCRIPTION
**Pull request by tmds**
Port #19518 to 2.1

CC @janvorli

### CODE REVIEW

**Comment by janvorli** [comment]
#### Description
.NET core applications are killed by OpenShift because they exceed their assigned memory. OpenShift/Kubernetes informs the app via the sysfs limit_in_bytes. Then memory is monitored by the oom killer based on sysfs usage_in_bytes. .NET Core is using /proc/self/statm instead, which includes only RSS and not memory in cache as the usage_in_bytes.

#### Customer Impact
Customer’s applications are killed by OpenShift because they exceed their assigned memory.

#### Regression?
No
		 
#### Risk
No

Original issue: #19060

**Comment by chrisgilbert** [comment]
Thanks for fixing this! We think we've been hitting this issue in ECS, so I'll give a +1 for having it fixed in a 2.1 patch.

**Comment by jamshedd** [comment]
Approved for 2.1.5

**Comment by danmosemsft** [comment]
This is expected to go out in October patch.

**Comment by devKlausS** [comment]
will this solve https://github.com/dotnet/coreclr/issues/18044 as well?

**Comment by tmds** [comment]
@devKlausS it should, .NET Core now uses the same limit as the Linux OOM killer.

**Comment by devKlausS** [comment]
@tmds thanks for the quick reply! I did a retest with 2.1.5 and I am afraid the issued is not solved yet. See my update https://github.com/dotnet/coreclr/issues/18044#issuecomment-426688885 If you need more details please let me know.

**Pull request merged**
