### PR TITLE
Enable Tiered Compilation by default

### PR DESCRIPTION
**Pull request by kouvel**
1) Changes the default state of the tiered compilation feature check to be ON BY DEFAULT
2) Removed comments about the source about this being a work in progress. Although it will surely continue to evolve and improve, remaining issues would be better tracked in our issue tracking system with the same default presumption as other runtime features - assume it works unless noted otherwise.
3) Adjusts a number of tests and automated scripts that made assumptions that the default setting of this feature is off.
4) Stop accepting the deprecated env var COMPLUS_EXPERIMENTAL_TieredCompilation. I'm not aware it has any remaining usage but if so we're going to find out.
5) Adjust config names for JitBench

### CODE REVIEW

**Comment by kouvel** [comment]
@dotnet-bot help

**Comment by kouvel** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by kouvel** [comment]
I believe this is ready to go. @noahfalk I added a commit on top of your previous enable commit to clean up the JitBench config names.

**Comment by kouvel** [comment]
Not sure why it's still showing the WIP check, there's no WIP anywhere

**Comment by AndreyAkinshin** [comment]
Is it possible to introduce a reliable API which checks that the Tiered Compilation is enabled? (An ugly hack which takes this information from the runtime internals will be also OK.) We really need this API in BenchmarkDotNet.

**Comment by kouvel** [comment]
@AndreyAkinshin, how would you use that API? I would like to add some trace events (perhaps also in API surface if that's useful) along the lines of what I described [here](https://github.com/dotnet/coreclr/pull/19121#issuecomment-409925789), which I thought would be useful for BenchmarkDotNet. There are some thoughts on info that would be useful to provide for debugging and analyzing perf traces and we are planning to do some work in that area.

**Pull request merged**
