### PR TITLE
Only export CMake compile commands when requested

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Move definition of CMAKE_EXPORT_COMPILE_COMMANDS into build.cmd (tied to the usenmakemakefiles option that jit-format uses) for Windows and remove from the Unix scripts (because jitformat can request it via the -cmakeargs parameter to the build script).

This is a coreclr counterpart to dotnet/jitutils#205

### CODE REVIEW

**Comment by janvorli** [comment]
I actually use the exported commands very often to look for issues and details, so I would prefer if we kept generating them always as before. What is the benefit of not doing that?

**Comment by janvorli** [comment]
Btw, the support for generating the commands file was not added for jit purposes, but rather to support rtagz. See https://github.com/dotnet/coreclr/commit/605bc815300dd5e3de0d4d23458e0ad8bc0eca20

**Comment by jkoritzinsky** [comment]
My understanding was that the only thing that used it was jit-format, so we shouldn't make it an always-on thing and localize it to where it's used. If you use it though (and if there's something else in our pipeline that always uses it), then we might as well leave it always on.

**Comment by jkoritzinsky** [comment]
And off-Windows you could always specify that you want it via the `cmakeargs` flag in build.sh.

**Comment by janvorli** [comment]
We don't use the rtags, but some of our customers do. Generating the exported commands doesn't add any cost to the build and usually when I need to look at that, the build has just completed and I would need to re-run it with the option added.

**Pull request closed without merging**
