### PR TITLE
Fix FieldDesc::GetExactFieldType when FieldDesc doesn't exactly represent the owner type

### PR DESCRIPTION
**Pull request by ayuckhulk**
This PR is a copy of #10941 but for release/2.0.0 branch.
We will upgrade coreclr upstream branch on Tizen soon from release/2.0.0 branch.

This PR fix FieldDesc::GetExactFieldType when FieldDesc doesn't exactly represent the owner type (like in generics).

To get the exact type from FieldDesc, field signature should point past the calling convention.

@janvorli, @jkotas PTAL

cc @Dmitri-Botcharnikov @chunseoklee @seanshpark

### CODE REVIEW

**Comment by ayuckhulk** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test

**Comment by chunseoklee** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test

**Comment by chunseoklee** [comment]
@gkhanna79 PTAL As ayuckhulk mentioned, it is need for tizen release. 
@janvorli PTAL

**Comment by gkhanna79** [comment]
Is there a test that needs to be added for this? Also, can you please help me understand why is this required for 2.0.0?

**Comment by chunseoklee** [comment]
@gkhanna79 please refer to https://github.com/dotnet/coreclr/pull/10941 for technical details.
Since current GetExactFieldType returns the wrong type, gdbjit does not show proper type to VS Tizen debugger. For tizen release, this feature is needed.

**Comment by gkhanna79** [comment]
Thanks. Should any tests be added to accompany the change?

**Comment by gkhanna79** [comment]
Also, aside from CI, what kind of testing has been done for the change?

**Comment by chunseoklee** [comment]
@ayuckhulk Please review gkhanna79's question.

**Comment by ayuckhulk** [comment]
@gkhanna79 We have a bunch of internal tests for GDBJIT, CoreCLR and LLDB. Some of them (related to generics) were failing because of this issue.

**Comment by gkhanna79** [comment]
@janvorli @jkotas Are you good with this change?

**Comment by janvorli** [comment]
@gkhanna79 strange, I was sure I have commented here few hours ago, probably forgotten to push the `Comment` button. I don't know this stuff well so I cannot tell if there are possible side effects of this change to other coreclr stuff. I think @jkotas would know.

**Comment by jkotas** [comment]
This code is only reachable from gdbjit in CoreCLR.

I am fine with this change. It has no risk for MS release.

**Pull request merged**
