### PR TITLE
Add Lazy<T>(T value) constructor

### PR DESCRIPTION
**Pull request by jasonwilliams200OK**
Fix dotnet/corefx#2578

### CODE REVIEW

**Comment by jasonwilliams200OK** [comment]
@AlexGhiondea, @justinvp, please take a look and let me know where to add tests for this addition. :)

**Comment by justinvp** [comment]
[model.xml](https://github.com/dotnet/coreclr/blob/bdfce9ed7fb93086f0b10ce999e2c21f34e08ada/src/mscorlib/model.xml#L3135) needs to be updated with the new constructor.

After that, the following will need to happen:
 1. Porting the change to Lazy.cs in the CoreRT repo.
 2. Updating the contract (ref assembly) for `System.Runtime` in the CoreFX repo and incrementing the version as appropriate. I'm not sure how versioning of `System.Runtime` is being handled (i.e. when we're allowed to add new APIs to this contract), but this may have to wait until the new `Lazy` constructor is added to a future version of the desktop framework.

**Comment by jasonwilliams200OK** [comment]
@justinvp, thanks. I have updated `model.xml` and opened a PR in CoreRT repo dotnet/corert#1538.

**Comment by jkotas** [comment]
@AlexGhiondea is offline till September. 
cc @danmosemsft @weshaggard 

Looks like this was approved in dotnet/corert#1538 and it is pretty straightforward. LGTM.

This will need to a special care on TFS side, so whoever merges it need to be prepared to take care of it. (I cannot take care of it at the moment.)

**Comment by danmosemsft** [comment]
If the question for me was versioning of the corefx contract - I don't know when that will happen as it's not clear when the larger API work will get into master. This change LGTM though.

**Comment by danmosemsft** [comment]
(And such versioning can happen w/o the larger APi work of course.)

**Pull request merged**
