### PR TITLE
Change the debian and ubuntu docker images

### PR DESCRIPTION
**Pull request by mikem8361**
To ones that build the sos plugin with lldb 3.9.

### CODE REVIEW

**Comment by mikem8361** [comment]
@dotnet-bot test portable linux debug pipeline
@dotnet-bot test portable linux release pipeline

**Comment by gkhanna79** [comment]
What about RH Docker image (at https://github.com/dotnet/coreclr/pull/11522/files#diff-3cf7efd8c2595e8fb3f019495384240fR28)?

**Comment by gkhanna79** [comment]
Also at https://github.com/mikem8361/coreclr/blob/49b87b3fdb03dfa73939918fc7fe5b947d949958/buildpipeline/pipelines.json#L106 where we use RHEL7.2 to build portable linux binaries.

@mikem8361 @lt72 Given that .NET Core 2.0 will be shipping portable binaries that build on RHEL7.2 (and not from the distro specific builds), how will this work for that build?

**Comment by mikem8361** [comment]
I didn't know enough about our the RHEL packages and to me it looked like they were "private" ones. From the RHEL DockerFile:

        https://matell.blob.core.windows.net/rpms/lldb-3.6.2-1.el7.centos.x86_64.rpm \
        https://matell.blob.core.windows.net/rpms/lldb-devel-3.6.2-1.el7.centos.x86_64.rpm \

**Comment by mikem8361** [comment]
So I didn't create any new RHEL images.

**Comment by mikem8361** [comment]
I think the RHEL changes need to be another PR since we will need to wait for the LLDB 3.9 rpm packages, create another PR in the DotNetCore repro to change the DockerFiles, generate new images and then change the coreclr repo files.

**Comment by mikem8361** [comment]
@gkhanna79 Can we merge this PR?

**Pull request closed without merging**
