### PR TITLE
Fix stack trace population to get proper source/line info for tier 1 methods

### PR DESCRIPTION
**Pull request by kouvel**
Fixes https://github.com/dotnet/coreclr/issues/16224

### CODE REVIEW

**Comment by kouvel** [comment]
In that test case I'm seeing a regression at steady-state (operations per ms):

No tiering:
Baseline - 4.42
Changed - 4.28

Tiering:
Baseline: 4.28
Changed: 4.23

If this is significant I can look into how to reduce the regression.

**Comment by kouvel** [comment]
The error on those numbers is pretty high but the difference is significant

**Comment by kouvel** [comment]
I said significant twice with different meaning, I meant to say that there is definitely a repeatably measurable gap but I'm not sure if the gap is large enough to look into further.?

**Comment by kouvel** [comment]
@dotnet-bot test Tizen armel Cross Checked Innerloop Build and Test

**Comment by kouvel** [comment]
From a few profiles the gap might be due to getting the method start address. We can either do that lazily like now, or get it at the same time the MethodDesc is looked up and store it, I'm not sure if the latter would negatively affect other perf scenarios.

**Comment by noahfalk** [comment]
I don't think 1% on this microbenchmark is worth fretting over. My imagination would be worst case someone complains about it and we look into it, but even there it would be in the context that something is running just slightly slower and it would be nice to speed it up. In 529 the regression was significant enough (2500%) that it blocked customers from reasonably performing the same tasks.

**Pull request merged**
