### PR TITLE
Instead of using Win8+ api-sets use legacy DLL entrypoint to support downleve…

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
…l versions of Windows.

see #21465

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
@dotnet-bot test Windows_NT x64 Checked Innerloop Build and Test (Jit - TieredCompilation=0) please

**Comment by danmosemsft** [comment]
Maybe one of the CI legs should change to Windows 7?

**Comment by jkotas** [comment]
CI coverage is about having good trade-off between number of legs and coverage. Win7-specific breaks are very rare in CoreCLR. I do not remember when I have seen last one. I do not think it is worth it to have Win7 leg in CoreCLR repo.

BTW: I think we have way too many legs in CoreCLR CI today. I think we should be rather looking at removing legs that are not adding substantial extra coverage - to improve CI reliability and reduce costs.

**Comment by danmosemsft** [comment]
I was not suggesting adding any legs, just considering whether all the Windows legs need to be Win 10 (which I assume they are)

**Comment by jkotas** [comment]
Yes, switching one of the existing Windows legs to run on Windows 7 sounds reasonable to me. I am not sure whether it is possible/easy in Jenkins-based CoreCLR CI today. It may need to wait for migration to Azure DevOps.

**Comment by danmosemsft** [comment]
@jashook..yes on migration to AZDO

**Comment by jashook** [comment]
With some more thought, it is probably possible to fiddle with the issues.targets using wildcards to exclude almost all the tests but what is interestingly different.

**Comment by jkotas** [comment]
> It is unclear if the eng service team has these queues available 

CoreFX CI runs tests on Windows 7 in Helix. For example, look for `Windows.7.Amd64.Open` in https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/19464/ . Can you submit the tests same way as CoreFX? 

>  fiddle with the issues.targets using wildcards to exclude almost all the tests except what is interestingly differen

It is hard to tell what is interesting upfront. We have number of Windows legs. Can we switch one of them (e.g. `Windows_NT x86 Release Innerloop Build and Test`) to run the tests on Windows 7 instead of Windows 10 ?

**Comment by AaronRobinsonMSFT** [comment]
>It is hard to tell what is interesting upfront.

@jkotas is right here. Most of the differences will be with API surface, but there could be some semantic differences with environment as well. There should be little to no different between x86 or amd64, so sacrificing a Windows 10 x86 run for a Windows 7 x86 run is worth it to me.

**Comment by jashook** [comment]
>CoreFX CI runs tests on Windows 7 in Helix. For example, look for Windows.7.Amd64.Open in https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/19464/ . Can we submit the tests same way as CoreFX?

Cool I simply did not know of the queue, I assume there is a closed queue as well for the official build. Either way it makes things easier.

For the CI the proposal sounds fine to me. I believe it should be easy to change the machine affinity by arch in netci.groovy. /cc @BruceForstall in case I am wrong. For the official build, I would suggest adding another queue to submit tests to entirely instead of changing the target queue for x86 and waiting for the AZDO official build move-over.

@BruceForstall @sbomer @RussKeldorph opinions?

**Comment by jkotas** [comment]
> For the official build

Official builds are fine. They clearly run the tests on Win7 since they have found this Win7-specific issue (look at #21465).

**Comment by BruceForstall** [comment]
I'm very skeptical that it is worthwhile to replace Win10 with Win7 in the CI. I think it would add cost, and would only extremely rarely find an issue. If the official build tests are testing Win7, that seems good enough.

**Comment by danmosemsft** [comment]
It's your repo, but can you explain how it would add cost? Generally the CI is all about getting the broadest test coverage possible in acceptable time. This should add coverage without adding more time, or more legs - is Windows 7 intrinsically less reliable?

**Comment by BruceForstall** [comment]
The more different things we have, the less reliable it is. That's my experience.

**Comment by danmosemsft** [comment]
Fair enough

**Pull request merged**
