### PR TITLE
Fix link for up-for-grabs issues

### PR DESCRIPTION
**Pull request by borsna**

### CODE REVIEW

**Comment by jkotas** [comment]
@karelz Looks like this was broken by issue renaming. It should have been renamed the other way: CoreCLR was using the github standard `up-for-grabs` - 

 



CoreFX has

**Comment by karelz** [comment]
Yeah, I wasn't aware of that github standard when I was aligning our repos and I blindly used what CoreFX had, trusting it is "right". I am fine changing it to up-for-grabs on our repos (incl. documentation updates and up-for-grabs.net update) - I'll be happy to make the changes myself.
Does it sound like a reasonable change to you?

**Comment by jkotas** [comment]
> Does it sound like a reasonable change to you?

Yes.

**Comment by karelz** [comment]
Filed #17533

**Comment by karelz** [comment]
I will run it by area owners in both repos. Just want to make sure no one is affected too much.

@borsna thanks a lot for you contribution! We are likely going to decide to swing the other way, sorry for that.
Are you interested in helping make the change in https://github.com/dotnet/corefx/issues/17533? (after we have agreement among key repo owners)

**Comment by borsna** [comment]
@karelz just wanted to make a quick fix suggestion, the change for `up-for-grabs` sound better (was not aware of up-for-grabs.net)👍 
Can do a pull request fro dotnet/corefx when the renaming of the labels is done.

**Comment by karelz** [comment]
@borsna thanks!
BTW: I plan to do label rename and merging of PRs at the same-ish moment. As soon as we have team-wide agreement ;-).

**Comment by karelz** [comment]
@gkhanna79 @jkotas I see 3 failures on doc change, is that expected failure rate?
* Build failure: https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_osx10.12_flow_prtest/526/
* Build failure: https://ci.dot.net/job/dotnet_coreclr/job/master/job/x86_checked_windows_nt_prtest/4221/
* Test failure: https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_release_windows_nt_pri1_prtest/4634/testReport/junit/baseservices_threading/_waithandle_waitany_waitanyex2_waitanyex2_/_waithandle_waitany_waitanyex2_waitanyex2_cmd/

baseservices_threading._waithandle_waitany_waitanyex2_waitanyex2_._waithandle_waitany_waitanyex2_waitanyex2_cmd (from baseservices.threading.XUnitWrapper)
```
MESSAGE:
\n\nReturn code: 1\nRaw output file: D:\\j\\workspace\\x64_release_w---0575cb46\\bin\\tests\\Windows_NT.x64.Release\\Reports\\baseservices.threading\\waithandle\\waitany\\waitanyex2\\waitanyex2.output.txt\nRaw output:\nBEGIN EXECUTION\r\n \"D:\\j\\workspace\\x64_release_w---0575cb46\\tests\\..\\bin\\tests\\Windows_NT.x64.Release\\Tests\\Core_Root\\corerun.exe\" waitanyex2.exe \r\nName created: fb0ff97a-57c0-499b-b3a9-6cf60dea23b0\r\nTesting Mutex and non-Mutex, and signaling the other element\r\nAcquire the Mutex\r\nHolding the Mutex\r\nWaiting...\r\nWaitAny did not throw AbandonedMutexException\r\nTest Failed\r\nExpected: 100\r\nActual: -1\r\nEND EXECUTION - FAILED\r\nFAILED\r\nTest Harness Exitcode is : 1\r\n\nTo run the test:\n> set CORE_ROOT=D:\\j\\workspace\\x64_release_w---0575cb46\\bin\\tests\\Windows_NT.x64.Release\\Tests\\Core_Root\n> D:\\j\\workspace\\x64_release_w---0575cb46\\bin\\tests\\Windows_NT.x64.Release\\baseservices\\threading\\waithandle\\waitany\\waitanyex2\\waitanyex2.cmd\n\r\nExpected: True\r\nActual: False
+++++++++++++++++++
STACK TRACE:
at baseservices_threading._waithandle_waitany_waitanyex2_waitanyex2_._waithandle_waitany_waitanyex2_waitanyex2_cmd() in D:\j\workspace\x64_release_w---0575cb46\bin\tests\Windows_NT.x64.Release\TestWrappers\baseservices.threading\baseservices.threading.XUnitWrapper.cs:line 28667
```

**Comment by jkotas** [comment]
Looks like this run got really unlucky:

#1 is infrastructure issue
#2 is known #10022 
#3 is a failure not seen before. Opened #10514 .

**Comment by jkotas** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test please
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test please
@dotnet-bot test Windows_NT x86 Checked Build and Test please

**Comment by danmosemsft** [comment]
@karelz you can bypass or ignore CI for changes under documentation/...

**Comment by karelz** [comment]
@danmosemsft I know - it was just surprising number of failures ...

**Pull request merged**
