### PR TITLE
Remove buildpipelines

### PR DESCRIPTION
**Pull request by sdmaclea**
It is not clear to me why these files are still present.

The easiest way to find out is to try to remove them

### CODE REVIEW

**Comment by jashook** [comment]
I think this should be ok. @sbomer opinions

**Comment by sdmaclea** [comment]
It is possible `eng/Signing.props` shouldn't be removed.  I didn't see any reference to it.  We are using microbuild signing now.

**Comment by RussKeldorph** [comment]
Though it does appear that Signing.props may still be relevant.

**Comment by echesakovMSFT** [comment]
Should we remove **tests\helixpublish.proj** and **tests\helixprep.proj** (and also related logic in build-test.cmd and build-test.sh)?

**Comment by hoyosjs** [comment]
eng/Signing.props is necessary unless something changed under the rug. This is the file that tells the SignTool in Arcade what to sign.

**Comment by sdmaclea** [comment]
The musl failure looks real at the moment.  It is somehow using the buildpipeline/linux-musl.groovy script. Maybe someone manually configured the musl CI jobs.

**Comment by sdmaclea** [comment]
@hoyosjs Thanks
@echesakovMSFT I'll look at those.  There are some perf scripts to send to helix.  I would like to fix those as they are referencing buildtools.

**Comment by sdmaclea** [comment]
The musl job was created by `buildpipeline/pipelinejobs.grovvy` by https://ci3.dot.net/job/dotnet_coreclr/job/master/job/generator.  
I manually disabled `https://ci3.dot.net/job/dotnet_coreclr/job/master/job/linux-musl-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/` by clicking disable job.
I think all the musl pipelines and generator in https://ci3.dot.net/job/dotnet_coreclr/job/master/* can/should be removed.

**Comment by sdmaclea** [comment]
> Should we remove tests\helixpublish.proj and tests\helixprep.proj (and also related logic in build-test.cmd and build-test.sh)?

Removed those and `tests/helixperftasks.targets`.  I also removed the reletad logic `ziptests` and `PerfTests`.

> eng/Signing.props is necessary

Fixed

**Comment by sdmaclea** [comment]
Three separate unrelated failures:
+ 1 instance of #22045 (Test Pri0 Windows_NT x64 checked)
+ 1 instance of `Internal Server Error 500` (Pri0 Linux x64 checked)
+ 1 one test aborted (OSX10.12 x64 Checked)

The re-run button is not working for the coreclr-ci failures

Retriggering the OSX failure.

@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test please

**Comment by sdmaclea** [comment]
All the OSX10.12 x64 Checked Innerloop runs are failing.  Ignoring

**Pull request merged**
