### PR TITLE
Add support for easily collecting JitFuncInfoLogFile for the tests

### PR DESCRIPTION
**Pull request by BruceForstall**
This is useful for RyuJIT/x86 bring-up.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@adiaaida @RussKeldorph PTAL
/cc @dotnet/jit-contrib

**Comment by adityamandaleeka** [comment]
@dotnet-bot test this please

**Comment by RussKeldorph** [comment]
Could you achieve "good enough" with `%CD%` inside ryujit_x86_testenv.cmd?  Would prefer not to change the .targets file if we don't have to.

**Comment by BruceForstall** [comment]
It looks like that will work, if only due to two "quirks" of the current system: (1) each and every test gets its own directory, and (2) the current directory is changed to that directory before running the test.

I don't really understand the hesitance to change the .targets file, though.

**Comment by BruceForstall** [comment]
Updated the change

**Comment by BruceForstall** [comment]
@RussKeldorph PTAL

**Comment by adiaaida** [comment]
LGTM

**Comment by CarolEidt** [comment]
LGTM

**Comment by RussKeldorph** [comment]
LGTM.  Thanks.

**Pull request merged**
