### PR TITLE
Check the optimize settings of JIT test projects.

### PR DESCRIPTION
**Pull request by mazong1123**
This PR will output the projects that have mismatched optimize settings
but won't fix them. This is part of tasks in #19166

### CODE REVIEW

**Comment by mazong1123** [comment]
@AndyAyersMS Would you please take a look if you have time? :)

**Comment by mazong1123** [comment]
Seems I need to fix all the abnormal projects to make the CI green. Before that I need to confirm whether following *.ilproj should be considered as failed (as I stated in https://github.com/dotnet/coreclr/issues/19166#issuecomment-450703354):

```
D:\j\workspace\x64_checked_w---eac6a79c\tests\src\JIT\Methodical\nonvirtualcall\classic_r.ilproj Optimize-Odd-MultipleConflictValues
23:36:03         D:\j\workspace\x64_checked_w---eac6a79c\tests\src\JIT\Methodical\nonvirtualcall\delegate_r.ilproj Optimize-Odd-MultipleConflictValues
23:36:03         D:\j\workspace\x64_checked_w---eac6a79c\tests\src\JIT\Methodical\nonvirtualcall\generics2_r.ilproj Optimize-Odd-MultipleConflictValues
23:36:03         D:\j\workspace\x64_checked_w---eac6a79c\tests\src\JIT\Methodical\nonvirtualcall\generics_r.ilproj Optimize-Odd-MultipleConflictValues
23:36:03         D:\j\workspace\x64_checked_w---eac6a79c\tests\src\JIT\Methodical\nonvirtualcall\tailcall_r.ilproj Optimize-Odd-MultipleConflictValues
23:36:03         D:\j\workspace\x64_checked_w---eac6a79c\tests\src\JIT\Methodical\nonvirtualcall\valuetype_r.ilproj Optimize-Odd-MultipleConflictValues
23:36:03         D:\j\workspace\x64_checked_w---eac6a79c\tests\src\JIT\jit64\mcc\interop\mcc_i10.ilproj Optimize-Odd-MultipleConflictValues
23:36:03         D:\j\workspace\x64_checked_w---eac6a79c\tests\src\JIT\jit64\mcc\interop\mcc_i11.ilproj Optimize-Odd-MultipleConflictValues
23:36:03         D:\j\workspace\x64_checked_w---eac6a79c\tests\src\JIT\jit64\mcc\interop\mcc_i12.ilproj Optimize-Odd-MultipleConflictValues
23:36:03         D:\j\workspace\x64_checked_w---eac6a79c\tests\src\JIT\jit64\mcc\interop\mcc_i13.ilproj Optimize-Odd-MultipleConflictValues
23:36:03         6982 projects, 11 needed fixes, 0 were fixed
23:36:03         Expected: 100
23:36:03         Actual: -1
23:36:03         END EXECUTION - FAILED
23:36:03         FAILED
23:36:03         Test Harness Exitcode is : 1
```

**Comment by AndyAyersMS** [comment]
Yes you should fix the broken projects. 

When there are multiple conflicting entries for the optimization setting, remove all but one entry and make that one correct (so it matches the suffix convention).

**Comment by mazong1123** [comment]
@AndyAyersMS what's the default value of <Optimize/> property if no suffix `r` or `ro` specified? I guess we allow either true or false in this scenario?

**Comment by AndyAyersMS** [comment]
Yes, if there's no suffix then we may have to guess -- or for older tests, get someone to track down how they were originally built for desktop  -- looking at these tests I'd say optimized is fine.

**Comment by mazong1123** [comment]
@AndyAyersMS Thanks. The PR is ready for review. Please take a look when you have time :)

**Comment by mazong1123** [comment]
Friendly ping @AndyAyersMS :)

**Pull request merged**
