### PR TITLE
Refactor the windows text resources processing

### PR DESCRIPTION
**Pull request by janvorli**
This change refactors the windows text resource processing into
a parsing script and a script with platform specific function
responsible for writing to the output file.

### CODE REVIEW

**Comment by janvorli** [comment]
@sergiy-k When you have a chance, could you please take a look?

**Comment by janvorli** [comment]
I've amended the commit by adding the ability to output target resource file header / footer. I am planning to use it for a PAL string resource test, but it might be useful for other platforms in general.

**Comment by sergiy-k** [comment]
LGTM

**Comment by janvorli** [comment]
@dotnet-bot test this please

**Pull request merged**
