### PR TITLE
Remove silent catch

### PR DESCRIPTION
**Pull request by filipnavara**
Dry run of CI for #26730.

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky Would like to hear your thoughts here. If we do wind up removing the `try`/`catch`, are there any other scenario we should consider writing tests for?

**Comment by jkoritzinsky** [comment]
The only scenario that this changes would be if the user had a broken SafeHandle ref-count on P/Invoke cleanup. Before this change, we would correctly clean up the rest of the parameters (while swallowing the failure). With this change, we will throw for the failure.

I have a strong feeling that this try/catch is one of the many locations in the runtime's interop code where we don't tell the user about user errors and instead "do the right thing" by silently handling them.


Also, sorry about marking this ready-for-review. The page re-rendered and I mis-clicked.

**Comment by filipnavara** [comment]
The original motivation for removing this is that we hit an issue in Mono where the `SafeHandle`s got corrupted (like issue with GC, or possibly even broken native compiler optimizations). I wanted to make sure whether the same problem would affect CoreCLR but I discovered that it would hide the error if it was happening. I, as a user, would prefer to get an error for this.

**Comment by AaronRobinsonMSFT** [comment]
> I, as a user, would prefer to get an error for this.

@filipnavara Fully agreed. The only concern here or previously is the backwards compatibility issues that it would introduce. @jkoritzinsky isn't saying we shouldn't do it, but in .NET Framework changing this behavior just wasn't an option. For .NET Core, I think we should consider this change for a major version update (e.g. 3 to 5) and so the present PR seems appropriate for the master branch.

**Comment by jkotas** [comment]
@AaronRobinsonMSFT @jkoritzinsky Any concerns with getting this merged?

@jkoritzinsky Is there a good place where to add a test for this?

**Comment by AaronRobinsonMSFT** [comment]
@jkotas No concerns.

> Is there a good place where to add a test for this?

I don't think we have a specific policy on testing this. Since the name of the API is `DangerousRelease()` I am unclear how we could effectively test this scenario.

**Comment by jkotas** [comment]
> I am unclear how we could effectively test this scenario.

The test can look like this:

```
        static void ReleaseTestHandle()
        {
            t_testSafeHandle.DangerousRelease();
        }

        [DllImport(...)]
        static void DangerousReleaseExceptionOnReturn(TestSafeHandle handle, Callback callback);

        [ThreadStatic]        
        static TestSafeHandle t_testSafeHandle;

         ...
             // This test validates that mismatched refcount during SafeHandle unmarshalling results into exception
             t_testSafeHandle = new TestSafeHandle();
             Assert.Throws<ObjectDisposedException>(DangerousReleaseExceptionOnReturn(h, ReleaseTestHandle);
         ...
```

I guess that test should go either to tests\src\Interop\PInvoke\SafeHandles\ReliableUnmarshalTest.cs, or to a new file in the same directory. @filipnavara Could you please add this test? If you do not have cycles to do that, let us know and somebody

**Comment by filipnavara** [comment]
I'll try to look into it this week.

**Comment by AaronRobinsonMSFT** [comment]
@jkotas Just so we are clear here, the test then is validating that we don't swallow the exception? It doesn't seem to validate anything else about how we marshal or ensure that other marshaling logic is executed.

**Comment by jkotas** [comment]
> the test then is validating that we don't swallow the exception?

Right. It is the behavior modified by this change.

> It doesn't seem to validate anything else about how we marshal or ensure that other marshaling logic is executed.

We have existing tests for that.

**Comment by maryamariyan** [comment]
Thank you for your contribution. As announced in dotnet/coreclr#27549 this repository will be moving to dotnet/runtime on November 13. If you would like to continue working on this PR after this date, the easiest way to move the change to dotnet/runtime is:
1.	In your coreclr repository clone, create patch by running `git format-patch origin`
2.	In your runtime repository clone, apply the patch by running `git apply --directory src/coreclr <path to the patch created in step 1>`

**Comment by AaronRobinsonMSFT** [comment]
Missed this. I am going to merge this now.

**Comment by filipnavara** [comment]
It's my fault. I was supposed to write a test for it. I got side-tracked but it's still on my backlog.

**Comment by AaronRobinsonMSFT** [comment]
@filipnavara According to @jkotas we have tests so we are all good. Thanks!

**Comment by jkotas** [comment]
> @jkotas we have tests so we are all good.

We do not have tests for the specific behavior modified in this change. If we had them, they would need to be fixed as part of the change...

**Pull request merged**
