### PR TITLE
Remove unnecessary "Attribute" suffix

### PR DESCRIPTION
**Pull request by justinvp**

### CODE REVIEW

**Comment by weshaggard** [comment]
@justinvp I don't think this change meets our contribution bar https://github.com/dotnet/coreclr/wiki/Contributing#contribution-bar. What problem are you trying to solve with this change? We don't like to churn the code for no demonstrable impact.

**Comment by justinvp** [comment]
> What problem are you trying to solve with this change? We don't like to churn the code for no demonstrable impact.

I saw new commits using the `Attribute` suffix and noticed the inconsistency throughout the codebase, including inconsistent usage between multiple attributes applied to the same members.

So the C# code in this repo is effectively "on ice"?

**Comment by MattWhilden** [comment]
Maybe we can jam this kind of correction (which is really a style issue) into the autoformatter?

**Comment by ellismg** [comment]
+1 to @MattWhilden's comment.  I think we should figure out a way that we feel like we can make these low risk style improvements.  If that's by having them done via automated tooling, then let's work to get that tooling setup.

I think there's value in having consistency across the codebase.

**Comment by MattWhilden** [comment]
It also makes it harder for me to absentmindedly screw up this reasonable guidance in future checkins!

**Comment by weshaggard** [comment]
Thanks for putting this trying to improve things @justinvp but I'm going to close this PR because we don't know our full plans of how code will flow or not. I've opened issue https://github.com/dotnet/coreclr/issues/972 about running the code formatter tool on mscorlib and if we do decide to do that then we should add this as part of the clean-up.

**Pull request closed without merging**
