### PR TITLE
Exposed List<T>.ConvertAll

### PR DESCRIPTION
**Pull request by KrzysztofCwalina**

### CODE REVIEW

**Comment by KrzysztofCwalina** [comment]
@weshaggard

**Comment by weshaggard** [comment]
You need to expose this in System.Private.CoreLib as well (assuming it isn't already).

**Comment by stephentoub** [comment]
> You need to expose this in System.Private.CoreLib as well (assuming it isn't already). 

Just looked; it is already included in model.xml.

**Comment by stephentoub** [comment]
LGTM

**Pull request merged**
