### PR TITLE
Android - Fix duplicate definitions of INT_MIN and PAGE_SIZE in unit tests

### PR DESCRIPTION
**Pull request by qmfrederik**
Both `INT_MIN` and `PAGE_SIZE` already exist on Android, but are redefined for the unit tests. This PR fixes that conflict.

### CODE REVIEW

**Comment by qmfrederik** [comment]
@janvorli Another Android PR. Alternatives are:

```
#ifndef INT_MIN
#define INT_MIN (-2147483647 - 1)
#endif
```

This one has the advantage of being working on other platforms where INT_MIN is defined, but re-using the platform definition of INT_MIN

or
```
#undef INT_MIN
#define INT_MIN (-2147483647 - 1)
```

This one is perhaps the most portable one?

**Comment by janvorli** [comment]
@qmfrederik Since it is in the tests, I don't really care which way we choose. But I would slightly prefer the the latter.

**Comment by qmfrederik** [comment]
@janvorli OK, done

**Comment by qmfrederik** [comment]
@janvorli Is this one good to go? Anything else you need from my side?

**Comment by janvorli** [comment]
@qmfrederik I am sorry, I've just lost track of this one.

**Pull request merged**
