### PR TITLE
     Generate efficient code for rotation patterns.

### LINKED ISSUE #1619: RyuJIT: Understand the idiomatic rotate bits
This kind of code is pretty usual in hot paths for Hash Function implementations like XXHash, Metro128, FarmHash, etc.

```csharp
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static ulong RotateRight64(ulong value, int count)
{
    return (value >> count) | (value << (64 - count));
}
```

Now the JIT (both legacy and RyuJIT) generate the following code:

```asm
mov         rdx,rax  
shr         rdx,1  
shl         rax,3Fh  
or          eax,edx  
```

While a more efficient code could be generated if such an idiom is detected:

```asm
ror         rax,1  
```

The same applies for different sizes (8, 16, 32 and 64) and also the RotateLeft direction. Needless to say the throughput of such functions would improve by more than 2X.

### PR DESCRIPTION
**Pull request by erozenfeld**
This change adds code to recognize rotation idioms and generate efficient instructions for them.

     Two new operators are added: GT_ROL and GT_ROR.

     The patterns recognized:
     (x << c1) | (x >>> c2) => x rol c1
     (x >>> c1) | (x << c2) => x ror c2

     where c1 and c2  are constant and c1 + c2 == bitsize(x)

     (x << y) | (x >>> (N - y)) => x rol y
     (x >>> y) | (x << (N - y)) => x ror y

     where N == bitsize(x)

     (x << y & M1) | (x >>> (N - y) & M2) => x rol y
     (x >>> y & M1) | (x << (N - y) & M2) => x ror y

     where N == bitsize(x)
     M1 & (N - 1) == N - 1
     M2 & (N - 1) == N - 1

     For a simple benchmark with 4 rotation patterns in a tight loop
     time goes from 7.324 to 2.600 (2.8 speedup).

     Rotations found and optimized in mscorlib:
     System.Security.Cryptography.SHA256Managed::RotateRight
     System.Security.Cryptography.SHA384Managed::RotateRight
     System.Security.Cryptography.SHA512Managed::RotateRight
     System.Security.Cryptography.RIPEMD160Managed:MDTransform (320 instances!)
     System.Diagnostics.Tracing.EventSource.Sha1ForNonSecretPurposes::Rol1
     System.Diagnostics.Tracing.EventSource.Sha1ForNonSecretPurposes::Rol5
     System.Diagnostics.Tracing.EventSource.Sha1ForNonSecretPurposes::Rol30
     System.Diagnostics.Tracing.EventSource.Sha1ForNonSecretPurposes::Drain
     (9 instances of Sha1ForNonSecretPurposes::Rol* inlined)

     Closes #1619.

### CODE REVIEW

**Comment by erozenfeld** [comment]
@sivarv PTAL

**Comment by CarolEidt** [comment]
Reviewed offline - thanks for adding the test!
LGTM

**Comment by sivarv** [comment]
LGTM

**Comment by jamesqo** [comment]
This does not appear to be working for 32-bit... for this function

```cs
[MethodImpl(MethodImplOptions.NoInlining)]
private static int Foo(int left)
{
    uint rol5 = ((uint)left << 5) | ((uint)left >> 27);
    return (int)rol5;
}
```

a rol is getting emitted for x64, but not for regular x86.

```asm
; x64
G_M30394_IG01:

G_M30394_IG02:
       8BC1                 mov      eax, ecx
       C1C005               rol      eax, 5

G_M30394_IG03:
       C3                   ret

; x86
G_M30394_IG01:
       55           push     ebp
       8BEC         mov      ebp, esp

G_M30394_IG02:
       8BC1         mov      eax, ecx
       C1E005       shl      eax, 5
       C1E91B       shr      ecx, 27
       0BC1         or       eax, ecx

G_M30394_IG03:
       5D           pop      ebp
       C3           ret
```

**Comment by erozenfeld** [comment]
Yes, this optimization was added only to RyuJIT (which is the default for 64 bit), not to the current 32-bit jit. 32-bit RyuJIT work is in progress and it will support this optimization.

**Comment by jamesqo** [comment]
Ah, so that explains it. Thank you for clarifying :smile:

**Comment by LMLB** [comment]
In the case with the masks, does the `N == bitsize(x)` test take into account that N will be masked?

**Comment by erozenfeld** [comment]
No, these patterns are not recognized with the current implementation.

**Pull request merged**
