### PR TITLE
Improve the dump for inline return expressions

### PR DESCRIPTION
**Pull request by briansull**
Also don't do a deep copy of the inline return expression

### CODE REVIEW

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT jitstress2
@dotnet-bot test Windows_NT arm64 Checked

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT jitstress2

**Comment by briansull** [comment]
@AndyAyersMS PTAL
@dotnet/jit-contrib PTAL

**Comment by briansull** [comment]
There are no Asm diffs with this change.
There is a memory savings when allocating GenTree nodes for return expressions, as we now no longer make a full duplicate copy for the common non-leaf return expressions.

**Comment by AndyAyersMS** [comment]
LGTM

**Pull request merged**
