### PR TITLE
Renumber blocks before computing loop nest

### LINKED ISSUE #13919: F# compiler is broken with latest CoreCLR runtime
Trying to take the latest 2.1 runtime into dotnet/cli is currently blocked because the F# compiler is running into what appears to be a JIT issue.

See https://github.com/dotnet/cli/pull/7606#issuecomment-328694723 for my analysis of debugging the issue.

To repro:

1. Unzip [JITBug.zip](https://github.com/dotnet/coreclr/files/1296754/JITBug.zip) to a folder.
1. Set your CWD into the `JITBug` folder you extracted
1. Using the [latest shared runtime](https://dotnetcli.blob.core.windows.net/dotnet/Runtime/master/dotnet-runtime-latest-win-x64.zip) execute:
`dotnet.exe fsc.exe -o:obj\Debug\netcoreapp2.0\FSharpTest.dll -g --debug:portable --noframework --optimize- -r:refs\FSharp.Core.dll -r:refs\System.Runtime.dll --target:exe --warn:3 --fullpaths --flaterrors --highentropyva- --targetprofile:netcore --simpleresolution --nocopyfsharpcore .NETCoreApp,Version=v2.0.AssemblyAttributes.fs Program.fs`

You will get an error like:

```
FailFast: Unknown exception seen in compiler: System.InvalidCastException: Unable to cast object of type 'Ident' to type 'LongIdentWithDots'.
   at Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.UnboxGeneric[T](Object source)
   at Microsoft.FSharp.Compiler.Parser._fsyacc_reductions@14808-1158.Invoke(IParseState parseState)
   at Internal.Utilities.Text.Parsing.Implementation.interpret[tok](Tables`1 tables, FSharpFunc`2 lexer, LexBuffer`1 lexbuf, Int32 initialState)
   at Microsoft.FSharp.Compiler.CompileOps.ParseInput(FSharpFunc`2 lexer, ErrorLogger errorLogger, LexBuffer`1 lexbuf, FSharpOption`1 defaultNamespace, String filename, Tuple`2 isLastCompiland)
   at Microsoft.FSharp.Compiler.CompileOps.ParseOneInputLexbuf@3575.Invoke(LexBuffer`1 lexbuf)
   at Microsoft.FSharp.Compiler.Lexhelp.reusingLexbufForParsing[a](LexBuffer`1 lexbuf, FSharpFunc`2 f)
```

/cc @jkotas @briansull

### PR DESCRIPTION
**Pull request by JosephTremoulet**
The loop nest computation expects to be able to test block numbers for
lexical inclusion, so do a renumbering pass first if blocks have been
moved.

Fixes #13919.

### CODE REVIEW

**Comment by JosephTremoulet** [comment]
@briansull / @AndyAyersMS PTAL
/cc @dotnet/jit-contrib 

This also fixes VSO bug 486439

Minimal diffs:

```
Summary:
(Note: Lower is better)

Total bytes of diff: -103 (0.00 % of base)
    diff is an improvement.

Total byte diff includes 0 bytes from reconciling methods
        Base had    0 unique methods,        0 unique bytes
        Diff had    0 unique methods,        0 unique bytes

Top file regressions by size (bytes):
           1 : System.Net.Http.dasm (0.00 % of base)

Top file improvements by size (bytes):
         -63 : Microsoft.CodeAnalysis.CSharp.dasm (0.00 % of base)
         -17 : Microsoft.CodeAnalysis.VisualBasic.dasm (0.00 % of base)
         -12 : Microsoft.CodeAnalysis.dasm (0.00 % of base)
          -7 : Microsoft.CSharp.dasm (0.00 % of base)
          -5 : JIT\Regression\JitBlue\GitHub_13919\GitHub_13919\GitHub_13919.dasm (-2.62 % of base)

6 total files with size differences (5 improved, 1 regressed), 2037 unchanged.

Top method regessions by size (bytes):
           4 : System.Net.Http.dasm - ContentReadStream:set_Position(long):this
           1 : Microsoft.CodeAnalysis.VisualBasic.dasm - TypeSymbolExtensions:IsCompatibleWithGenericIEnumerableOfType(ref,ref,byref):bool

Top method improvements by size (bytes):
         -18 : Microsoft.CodeAnalysis.CSharp.dasm - LanguageParser:ParseNamespaceBody(byref,byref,byref,char):this
         -15 : Microsoft.CodeAnalysis.CSharp.dasm - LanguageParser:ParseArgumentList(byref,byref,byref,char,char):this
         -15 : Microsoft.CodeAnalysis.CSharp.dasm - LocalScopeBinder:BuildLocals(struct):struct:this
         -12 : Microsoft.CodeAnalysis.dasm - TypeNameDecoder`2:GetTypeSymbol(struct,byref):ref:this
          -7 : Microsoft.CodeAnalysis.CSharp.dasm - AnonymousTypeManager:AssignTemplatesNamesAndCompile(ref,ref,ref):this

17 total methods with size differences (15 improved, 2 regressed), 202622 unchanged.
```

**Comment by JosephTremoulet** [comment]
> The switch map stuff is just an incidental optimization to avoid allocation?

No.  The `SimplerHashTable` type's `Remove` method requires that something (anything) has been inserted into the table before it's called (`Remove` computes a bucket number by taking a hash modulo table size, but `SimplerHashTable`'s default constructor sets table size to zero).  This was probably inadvertent, but given how hot we'd expect the `SimplerHashTable` code to be, I figured it's best to avoid trying the removal on the empty table (here in the cold code that's canonicalizing loops), rather than harden `Remove` against it.

**Comment by JosephTremoulet** [comment]
...and the new call to `fgRenumberBlocks` in turn [calls](https://github.com/dotnet/coreclr/blob/0d309876c9c5dd5a8e2d34341ba49fe89bf15404/src/jit/flowgraph.cpp#L11478) `InvalidateUniqueSwitchSuccMap`, so now this code path is seeing null switch map for the first time.

**Comment by AndyAyersMS** [comment]
Thanks for explaining it...

**Comment by briansull** [comment]
If you can think of any additional guards to add so that we insure that the blocks are renumbered properly, so that we don't run into more issues like this.

**Comment by JosephTremoulet** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Build and Test (a known issue was just resolved)

**Comment by JosephTremoulet** [comment]
> If you can think of any additional guards to add so that we insure that the blocks are renumbered properly, so that we don't run into more issues like this

I'll give it more thought, but nothing leaps to mind -- the obvious thing would be for the loop nest calculation code to loop through the blocks and check they're in order since it's about to depend on that, but that would go in the exact same place that the call to renumber blocks goes (and do equivalent work), so no additional benefit.  The other obvious thing to do would be to have a flag on the compiler indicating whether block numbers are valid, then change the code to access block numbers through property getters that assert they are valid, but adding this would require auditing the code and flagging all the places that invalidate them (which is messy since sometimes code will be calling into utilities to shuffle blocks around in a way that it "knows what it's doing" and will fix the numbers when it finishes).  The third thing that springs to mind is again a flag for when the numbers are valid, but instead of using it to gate access to the numbers themselves, rewrite all comparisons on block numbers to go through some new method like `block->IsLexicallyBefore(otherBlock)` (which of course gets awkward when a data structure records just the numbers and not the blocks themselves...).

Since my first idea seems useless and my other two would be somewhat involved, I plan to check this in as-is if testing completes successfully.  I'll also try to think a bit more about what guard might make sense.

**Comment by JosephTremoulet** [comment]
That arm leg is still failing in the same way in other PRs, and this change fixes an issue that's holding up cli CI, so I'm going to go ahead and merge.

**Pull request merged**
