### PR TITLE
Add Generics/Arrays test cases for JIT

### PR DESCRIPTION
**Pull request by libengu**
Add test cases in directory JIT/Generics/Arrays. Related proj, config, and sln files
added and updated. Passed build, buildtest, runtest.

### CODE REVIEW

**Comment by libengu** [comment]
@mmitche PTAL

**Comment by libengu** [comment]
@russellhadley PTAL

**Comment by mmitche** [comment]
LGTM

**Comment by libengu** [comment]
@mmitche Thanks for reviewing. For new test cases, please let me control the merge because sometimes there is probably an accompanying PR in LLILC that should be merged immediately following this one. For this set, it is OK.

**Pull request merged**
