### PR TITLE
Revert "Less conservative gt obj"

### LINKED ISSUE #6179: [ARM/Linux] Regression in Unittest - Exception.ToString() failed
Running unittest using Release build CoreCLR from aab8856ce03 and Release build TC incurs many TC failures with the following message:
```
FAILED   - [ 000 :    3 sec ] baseservices/compilerservices/dynamicobjectproperties/Dev10_535767/Dev10_535767.sh
               BEGIN EXECUTION
               /opt/dotnet/Linux.tm1.Release/corerun Dev10_535767.exe
               
               Unhandled Exception: 
                  Cannot print exception string because Exception.ToString() failed.
               ./Dev10_535767.sh: line 117: 18972 Aborted                 $_DebuggerFullPath "$CORE_ROOT/corerun" Dev10_535767.exe $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
```

I observed that 85 TC shows the similar failure (when I running 905 tests). 

Is there any change that may be related with this?

### PR DESCRIPTION
**Pull request by parjong**
Reverts dotnet/coreclr#6021 to fix #6179

### CODE REVIEW

**Comment by leemgs** [comment]
Actually, We have been getting the 400+ unit-test failures on Raspberry Pi2 board after merging #6021.
Acked-by: Geunsik Lim <geunsik.lim@samsung.com>

**Comment by leemgs** [comment]
@jkotas , Please, take a look at the regression issue of #6021.

**Comment by jkotas** [comment]
@CarolEidt @dotnet/jit-contrib What is the best way to proceed on this one?

**Comment by CarolEidt** [comment]
I have not been able to install the emulator to attempt to repro this issue. Before backing out the change, I would like to be able to repro the failure - otherwise I see no way forward. In the meantime, I am attempting to repro #6222 to see if it is related or the same.

**Comment by RussKeldorph** [comment]
@parjong Could you close this and create a new PR with the same change against current master so we can see the Linux test results with the latest CI changes?  Note that it's not sufficient to simply request re-test due to a bug in the CI system.

**Comment by jasonwilliams200OK** [comment]
@RussKeldorph, perhaps @parjong can just rebase against the master and re-pushed:

```sh
cd coreclr
git checkout revert-6021-LessConservativeGtObj
git remote add dotnet https://github.com/dotnet/coreclr
git pull --rebase dotnet master
git push -f
```

**Comment by parjong** [comment]
@RussKeldorph I rebased this PR as per @jasonwilliams200OK's suggestion. (Thank you @jasonwilliams200OK :+1: )

**Comment by RussKeldorph** [comment]
@parjong Thank you.  I wasn't expecting that to work due to the CI bug I mentioned, but perhaps it did.  It looks like the tests in question (b26496 & b539509) are passing as expected.

**Comment by briansull** [comment]
@RussKeldorph I note that the ARM32 Release tests still are hitting the Seg-Fault failure:

Tests b26863.exe gets a Seg Fault in this test run
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/arm_emulator_cross_release_ubuntu_prtest/548/

**Comment by RussKeldorph** [comment]
@briansull Yes, I noticed that as well.

@dotnet-bot test Linux ARM Emulator Cross Release Build

**Comment by CarolEidt** [comment]
I'm going to merge this, as I am still unable to successfully build and run the emulator to track down the regression.

**Comment by RussKeldorph** [comment]
We'd like to try to get a repro on Raspberry Pi 2 so @CarolEidt can investigate these failures.  @leemgs, you mention above that you are seeing 400+ failures on Raspberry Pi 2 with #6021.  Is that running under Ubuntu?  If so, which version?  We're trying 14.04 and 16.04 and in both cases seeing
```
coreclr_initialize failed - status: 0x80004005
```
when attempting to run any test.  Are the [ARM instructions](https://github.com/dotnet/coreclr/blob/master/Documentation/building/cross-building.md) up to date and confirmed working on current sources?

**Comment by leemgs** [comment]
> Is that running under Ubuntu? If so, which version?

Under Ubuntu/ARM 14.04 32bit, On Raspberry Pi2 & ARM ChromeBook

**Pull request merged**
