### PR TITLE
Add check for out of memory

### LINKED ISSUE #2650: runtime get crashed when allocate a large string
In src/mscorlib/src/System/StubHelpers.cs code line 175:

ptrToFirstChar = (byte *)Win32Native.SysAllocStringByteLen(null, lengthInBytes).ToPointer();

it seems we should check whether ptrToFirstChar is NULL.  we get runtime crashed when we run a stress test and find runtime get crashed at this code line

### PR DESCRIPTION
**Pull request by DionYe**
add none point checking after string allocation

fix #2650

### CODE REVIEW

**Comment by jkotas** [comment]
Could you please update the commit title to something like "Add check for out of memory" so that it better describes the issue being fixed?

The change looks good otherwise. Thanks for the fix!

**Comment by DionYe** [comment]
Got it, I have changed the title,  thanks.

**Comment by jkotas** [comment]
I meant update the commit title - it would something like:
```
git commit --amend
git push -f
```

**Comment by DionYe** [comment]
Done.. thx!

**Pull request merged**
