### PR TITLE
Add ability to use pipes for creating threads suspended

### PR DESCRIPTION
**Pull request by adityamandaleeka**
Added the ability in PAL to create a thread in suspended state by
specifying a pipe which ResumeThread will write to in order to
wake it up. This functionality is protected behind
`USE_PIPES_FOR_CREATING_SUSPENDED_THREADS` which is enabled on
everything except Darwin.

Issue #907

### CODE REVIEW

**Comment by janvorli** [comment]
LGTM

**Comment by kangaroo** [comment]
Why disabled on darwin?

**Comment by sergiy-k** [comment]
I agree with @kangaroo. One of the purposes of this change should be to pave the road to removing thread suspension APIs. The fact that we are still using the old InternalSuspendThreadFromData in InternalSuspendNewThreadFromData on OSX creates debt that we will have to pay in the future.

If for some reason we cannot use pipes on OSX, should we consider using mutex/cond var to implement this functionality?

**Comment by adityamandaleeka** [comment]
@kangaroo @sergiy-k 

I don't know of any reason not to enable this on OS X as well. I left it out originally because the issue was about removing the usage of signals for starting suspended threads, but I agree that it's better to be consistent.

I'll update the PR shortly and merge it.

**Pull request merged**
