### PR TITLE
ARM64: Change the fixed return buffer argument to be handled as a non-standard argument

### PR DESCRIPTION
**Pull request by briansull**
We already have support for the handling of non-standard arguments and
it is simpler and better to handle the fixed return buffer argument as a non-standard argument.

### CODE REVIEW

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by briansull** [comment]
@BruceForstall PTAL
@dotnet/jit-contrib PTAL
@dotnet/arm64-contrib PTAL

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked pri1r2r

**Comment by briansull** [comment]
I have withdrawn this PTAL request:

There are 6 test failures that I need to investigate further:

Test Result (6 failures / +6)JIT\Performance\CodeQuality\BenchmarksGame\pidigits\pi-digits.pi-digits
JIT\Performance\CodeQuality\Linq\Linq.Linq
JIT\Performance\CodeQuality\Serialization\Serialize.Serialize
JIT\Performance\CodeQuality\Serialization\Deserialize.Deserialize
JIT\Performance\CodeQuality\Roslyn\CscBench.CscBench
managed\Compilation\Compilation.Compilation

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked pri1r2r

**Comment by briansull** [comment]
@BruceForstall PTAL
@dotnet/jit-contrib PTAL
@dotnet/arm64-contrib PTAL

**Comment by kyulee1** [comment]
LGTM

**Comment by briansull** [comment]
Random comment

**Comment by mmitche** [comment]
@briansull What actually most likely happened here is that since the triggers have been modified a bunch, when you commented the random comment, it went back and checked previous comments for arm64 phrases.  It found one and launched.

**Comment by briansull** [comment]
Actually I noticed that the two Arm32 jobs (which are new) were running after Kylee1 commented.
However since they are so quick they were finishing up, so since I had already sent email to you.
I added the Random Comment, but they did not restart. So I believe that you are correct.

**Pull request merged**
