### PR TITLE
Add an .editorconfig file

### PR DESCRIPTION
**Pull request by KindDragon**
EditorConfig allow all developers use same space/tab settings for all files if they install EditorConfig plugin

Similar to that PR https://github.com/dotnet/corefx/pull/56

### CODE REVIEW

**Comment by mmitche** [comment]
LGTM

**Comment by AlexGhiondea** [comment]
Why 2 and not 4 spaces for *proj and XML files?

I would say 4 for cmd files as well.

**Comment by KindDragon** [comment]
@AlexGhiondea I checked the files in your repository, and it uses these settings. I can change these settings to 4 spaces.

**Comment by KindDragon** [comment]
Cmd files settings easy to change, it is rarely used indentation. But you have a lot xml files with 2 space indentation.

**Comment by weshaggard** [comment]
@KindDragon @AlexGhiondea we have traditionally used 2 spaces for xml/project files we have the same configuration in the corefx repo. I'm fine with them being 2 spaces.

**Comment by AlexGhiondea** [comment]
LGTM

**Comment by kangaroo** [comment]
The current .editorconfig has:

trim_trailing_whitespace = true

This is causing noise all over the repo, and will cause a lot of noise in future commits.  Suggest to disabling it by default, or someone going over everything and cleaning it up one time.

**Comment by AlexGhiondea** [comment]
@kangaroo That makes sense. I will create an issue for this.

**Comment by KindDragon** [comment]
@kangaroo Which file types cause troubles with  `trim_trailing_whitespace = true`?

**Comment by kangaroo** [comment]
@KindDragon pretty much every .cpp file I touched yesterday.

**Pull request merged**
