### PR TITLE
Harden resolveVirtualMethod against invalid types

### LINKED ISSUE #9945: JIT: bug in devirtualization where type information gets lost
Following test case, if compiled /o+ /debug:pdbonly, and run in a debug/check CoreCLR, will trigger an assert in resolveVirtualMethod:
```
Consistency check failed: FAILED: slotNumber < GetNumVtableSlots()
```
This it triggered by aggressive use of `dup` in the generated IL.

Likely two fixes needed.

First, have the VM side validate that the method being invoked is really a virtual method of the derived class, and if not, fail devirtualization. Would be nice to get the diagnostic information back too since this case represents a modelling error in the jit, so perhaps in addition to failing, `resolveVirtualMethod` should return some kind of status code. 

Second, need to fix the jit not to lose the type information in this case.

This can also result in silent bad code, if it turns out the slot number presented to B is a valid one, and the method found there happens to be final.
```
using System;

public class Base
{
    public int value;
    public void B0() { value += 12; }
    public virtual void B1() { value += 33; }
}

// Ensure that D1 and D2 have enough virtuals that the slot number for
// the virtual M1 is greater than any virtual's slot number in B.

public class D1 : Base
{
    public virtual void MA() { }
    public virtual void MB() { }
    public virtual void MC() { }
    public virtual void MD() { }

    public virtual void M1() { value += 44; }
}

public class D2 : Base
{
    public virtual void MA() { }
    public virtual void MB() { }
    public virtual void MC() { }
    public virtual void MD() { }

    public virtual void M1() { value += 55; }
}

// Aggressive use of 'dup' here by CSC will confuse the jit, and it
// will effectively substitute 'b' for uses of d1 and d2. This is not
// value-incorrect but loses type information.
//
// This loss of type information subsequently triggers an assert in
// devirtualization because b does not have M1 as virtual method.

public class Test
{
    public static int Main(string[] args)
    {
        Base b;

        if (args.Length > 0)
        {
            D1 d1 = new D1();
            b = d1;
            d1.B1();
            d1.M1();
        }
        else
        {
            D2 d2 = new D2();
            b = d2;
            d2.B1();
            d2.M1();
        }

        b.B0();
        return b.value;
    }
}
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Split resolveVirtualMethod into a wrapper/helper to allow early
returns as failure reasons are discovered.

Before devirtualizing, ensure that the derived class claimed by the jit
is really a subclass of the class that introduces the virtual method.
Fail early if this is not the case.

Also add early out for interface call devirtualization. The jit currently
does not ask for this but asking for it should not trigger an assert.

Closes #9945 (along with #9959).

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@jkotas PTAL
cc @davidwrighton @dotnet/jit-contrib 

No impact on codegen in the jit-diff set.

**Comment by davidwrighton** [comment]
This looks much better. Is it possible to add a test to verify that the old bugs don't regress?

**Comment by AndyAyersMS** [comment]
I added a test with the jit side of the fix (see #9959). I think I can work up an IL level test for the cases that can get past that.

**Comment by AndyAyersMS** [comment]
Added another test case that requires this fix.

**Pull request merged**
