### PR TITLE
Add ItemRef and ValueRef to List/Dict (C# 7.2 constructs)

### PR DESCRIPTION
**Pull request by benaadams**
Contributes to https://github.com/dotnet/corefx/issues/25189
Contributes to https://github.com/dotnet/corefx/issues/20684

* Adds ItemRef() to `List<T>`
* Adds ValueRef() to `Dictionary<TKey, TValue>`

As per https://github.com/dotnet/corefx/pull/25738

/cc @jkotas

### CODE REVIEW

**Comment by jkotas** [comment]
Wow, I have notice that this was approved. I think that this is pretty broken API for List/Dictionary.

This belongs to power collections.

**Comment by benaadams** [comment]
> I think that this is pretty broken API for List/Dictionary. 

Are you concerned `_version` won't update on set?

**Comment by benaadams** [comment]
Or `ref` validity after an `Resize`

**Comment by jkotas** [comment]
All of these.

**Comment by benaadams** [comment]
What about with a `[EditorBrowsable(EditorBrowsableState.Never)]` attribute?

**Comment by benaadams** [comment]
What about with a `[EditorBrowsable(EditorBrowsableState.Never)]` attribute?

> This belongs to power collections.

Seems a lot of effort to create List and Dictionary plus all their tests just to add two ref accessors?

**Comment by jkotas** [comment]
> Seems a lot of effort to create List and Dictionary plus all their tests; then keep them all in sync just to add a ref accessor?

It is not just this one API. There are number of features that power collection version of Dictionary may have (most of these have been touched on during various discussions):
- Key is required to implement `IEquatable<T>`, no IEqualityComparer overhead
- No version checks overhead
- No `KeyCollection/ValueCollection/_syncRoot` overhead
- APIs for fine grained control over resing and copies
- ...

**Comment by ufcpp** [comment]
Would you consider adding TryGet versions?

```cs
// returns a null reference or have an extra out boll parameter without throwing an exception
public ref TValue TryValueRef(TKey key, out bool success);
```

**Comment by stephentoub** [comment]
Per https://github.com/dotnet/corefx/issues/25189#issuecomment-400418417, apparently these APIs haven't actually been approved.  I'm going to close this until/if they are, at which point it can be re-opened (or a new one opened). Thanks.

**Comment by benaadams** [comment]
Added api proposal https://github.com/dotnet/corefx/issues/31598

**Pull request closed without merging**
