### PR TITLE
Don't Free UpperVector

### LINKED ISSUE #23861: [x64] Test failed: System.Numerics.Tests.GenericVectorTests.LessThanAllDouble
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_corefx_jitstressregs1/822/

**Failed tests:**
System.Numerics.Tests.GenericVectorTests.LessThanAllDouble
System.Numerics.Tests.GenericVectorTests.LessThanAllSingle

**Log:**
```
System.Numerics.Tests.GenericVectorTests.LessThanAllDouble [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\x64_checked_w---8f525dba\_\fx\src\System.Numerics.Vectors\tests\GenericVectorTests.cs(1469,0): at System.Numerics.Tests.GenericVectorTests.TestVectorLessThanAll[T]()
```

### PR DESCRIPTION
**Pull request by CarolEidt**
UpperVector regs are freed at their time of use, and shouldn't be freed when the last RefPosition is encountered.

Fix #23861

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL
The arm job failed twice in the same way. It's hard to imagine that it's related (on arm32 the `IsUpperVector()` method on an `Interval` always returns `false`), but I'm building it just to see if it repros.

**Comment by CarolEidt** [comment]
OK, it looks like #23850 hit the same failure, and the retry of the `Test Pri0 Linux_musl x64 release` leg passed, though it still reports failure.

**Comment by AndyAyersMS** [comment]
Error is
```
  Assert failure(PID 148 [0x00000094], Thread: 5892 [0x1704]): Consistency check failed: Managed object size does not match unmanaged object size
12:54:05   man: 0x30, unman: 0x2c, Name: System.Runtime.Loader.AssemblyLoadContext
12:54:05   FAILED: size == expectedsize
12:54:05   
12:54:05   <no module>! <no symbol> + 0x0 (0x00000000)
12:54:05       File: d:\j\workspace\arm_cross_che---7ce81708\src\vm\binder.cpp Line: 564
12:54:05       Image: C:\j\workspace\arm_cross_che---c874ca48\bin\tests\Windows_NT.arm.Checked\Tests\Core_Root\CoreRun.exe
```
possibly from #23740 ?

**Comment by AndyAyersMS** [comment]
cc @sdmaclea -- #23740 didn't run any windows arm tests in CI

**Comment by sandreenko** [comment]
Fixes #23904 and fixes #23804.

The change LGTM if https://dev.azure.com/dnceng/public/_build/results?buildId=152561 passes.

**Comment by sandreenko** [comment]
Failures in coreclr-ci (Test Pri0 Windows_NT x64 checked) look unrelated (probably the jit sources were taken before the Andy's PR and the test sources were taken after, so the testing job got the repro case but not the fix for it, there was an issue somewhere about this behaviour).

But jitstress2-jitstressregs shows some actual issues with Linux arm64:
JIT/Regression/VS-ia64-JIT/V1.2-M02/b28158/b28158/b28158.sh:
`Assert failure(PID 977 [0x000003d1], Thread: 977 [0x03d1]): Assertion failed 'isValidSimm19(distVal)' in 'test:Main():int' (IL size 267730)\n\n File: /__w/7/s/src/jit/emitarm64.cpp Line: 8841 Image: /root/helix/work/correlation/corerun\n\n/root/helix/work/workitem/JIT/Regression/VS-ia64-JIT/V1.2-M02/b28158/b28158/b28158.sh: line 252: 977 Aborted (core dumped) $LAUNCHER $ExePath \"${CLRTestExecutionArguments[@]}`

**Comment by CarolEidt** [comment]
@sandreenko - I can't repro the JIT/Regression/VS-ia64-JIT/V1.2-M02/b28158/b28158/b28158.sh failure - not on the altjit, not on Linux/arm64, and not on Windows/arm64, with variations on the jitStressRegs value (it takes a *very* long time to execute).
I find it hard to imagine that this failure is related either to the original UpperVector changes, or to this fix, as the assert happens in Main and there are no uses of vector types there, nor would any such uses be inlined into this (huge) method.

**Comment by CarolEidt** [comment]
Thanks @sandreenko !

**Pull request merged**
