### PR TITLE
Documentation - building mscorlib.dll using Mono on Linux

### PR DESCRIPTION
**Pull request by gitchomik**
Some information about building mscorlib.dll without Windows

### CODE REVIEW

**Comment by jkotas** [comment]
Could you please squash everything into single commit?

**Comment by gitchomik** [comment]
@jkotas I tried some solutions but I can't , could somebody tell me how to do this ?
1. should I close this Pull request, and create new one ?
2. should I create new branch for it ? then squash and create new pull request ?

**Comment by jkotas** [comment]
@gitchomik You should not need to create a new pull request or branch. Run `git rebase -i master`, pick the first commit and squash the second one. Then push changes into your PR with `--force` option. This assumes that you have typical git setup. If it does not work for some reason, creating new one will work too.

**Comment by gitchomik** [comment]
OK, I squashed everything to one commit.

**Comment by jkotas** [comment]
Perfect!

**Pull request merged**
