### PR TITLE
Move ReportingParameters for publish tasks into Definition entries

### PR DESCRIPTION
**Pull request by MattGal**
...  mirroring CoreFX's behavior on the same thing.

@wtgodbe @ChadNedzlek

### CODE REVIEW

**Comment by wtgodbe** [comment]
https://github.com/dotnet/coreclr/pull/10899 does this + fixes the x86 job which falls under 'unknown'. I also attempt to pass 'PB_BuildType' as a ReportingParameter there, pending @chcosta's investigation into exactly how that works.

**Comment by chcosta** [comment]
You can set a pipeline reporting parameter like this...

```
  "Pipelines": [
    {
      "Name": "Trusted-All-Release",
      "Parameters": {
        "TreatWarningsAsErrors": "false"
      },
      "BuildParameters": {
        "PB_BuildType": "Release"
      },
      "ReportingParameters": {
        "PB_BuildType": { }
      },
      "DefinitionGroupRefs": [
        "Product-Build"
      ]
    },
```

**Comment by wtgodbe** [comment]
@chcosta awesome, I'll update my change! Out of curiosity, how'd you figure that out?

**Comment by chcosta** [comment]
I looked at how this used to be done in CoreFx and then I tried the same thing against CoreClr, but with PipeBuild under the debugger.  I set a breakpoint on the PipeBuild instance right before PipeBuild queued a job so that I could see what reporting parameters it had loaded in memory.

**Comment by wtgodbe** [comment]
@gkhanna79 see above for the solution to the problem we were talking about earlier - I'm guessing that MergeReportingParameters fills in empty values in Key/Value ReportingParamater pairs with the value from the corresponding Key/Value BuildParameter pair

**Comment by gkhanna79** [comment]
> fills in empty values in Key/Value ReportingParamater pairs with the value from the corresponding Key/Value BuildParameter pair

This is what I was pointing to you in the code as well. Glad to know it works :)

**Comment by wtgodbe** [comment]
Yep, looks like you were right - I just wasn't sure what the syntax should be in pipelines.json

**Comment by MattGal** [comment]
Closing as this is covered by Will's PR.

**Pull request closed without merging**
