### PR TITLE
JIT: emit debug info for locals for minopts/tier0

### LINKED ISSUE #20421: Much worse debugging experience with Attach + Tier0 methods
If you attach to a .NET Core 3.0 application (Release build), and try to debug a tier0 method, you can't see any locals or args. The jitter only reports that they're available in the prolog, so a debugger can't read them. That makes debugging optimized release builds much more difficult than it used to be.

Note that this is not a problem with tier1 methods. They work as before, locals and args are visible (most of the time).

Repro:

- Compile (release build) the following program with the latest .NET Core 3.0 daily build
- Start it from the console
- Attach to it
- Have a look in the locals window in Main() and in SomeMethod(). The locals/args are only shown if IP == END_OF_PROLOG
- Let it run so SomeMethod becomes a tier1 method
- Step into SomeMethod() again and notice that locals/args are shown

```C#
using System;

namespace ConsoleApp16 {
    class Program {
        static void Main(string[] args) {
            var p = new Program();
            Console.WriteLine("Attach to it now");
            Console.ReadKey();
            var array = new byte[] { 1, 2, 3, 4 };
            p.SomeMethod(0x1234, "hello", array);
            Console.WriteLine("Warming up");
            for (int i = 0; i < 1000; i++)
                p.SomeMethod(0x1234, "hello", array);
            Console.WriteLine("Should be tier1 now, if it's not, try iterating 10K times instead of 1K times");
            Console.ReadKey();
            p.SomeMethod(0x1234, "hello", array);
        }

        // if it's a tier0 method or if MethodImplOptions.NoOptimization is enabled, it's not possible to
        // see the locals and args except when it's stopped right after the prolog.
        // It works if it's a tier1 method (and I assume, but I haven't tested, if AggressiveOptimization is enabled)
        int SomeMethod(int magic, string str, byte[] array) {
            int ret = magic ^ str.Length ^ array.GetHashCode();
            Console.Write("");
            for (int i = 0; i < str.Length; i++) {
                ret += str[i];
                ret += str.GetHashCode();
            }
            ret += magic;
            Console.WriteLine($"{ret} {str}");
            return ret;
        }
    }
}
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
The jit no longer tracks locals when running at minopts. But untracked
local debug emission was tied to `cmpDebugCode. Change untracked local
debug emission to instead check if there are no tracked locals.

Fixes #20421.

Note we could improve things further in the case where there is a mixture
of tracked and untracked locals. I have opened #20465 for that as my first
attempts here had that ambition but ran into problems.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
`BAD_STK_OFFS` only there in debug currently. Need to expose it more broadly or find some more robust test for untracked locals that didn't get a stack slot.

**Comment by AndyAyersMS** [comment]
For the test case from #20421, variable debug info at Tier0 is now:
```
*************** Variable debug info
10 vars
  1(   UNKNOWN) : From 00000000h to 00000021h, in rdx
  2(   UNKNOWN) : From 00000000h to 00000021h, in r8
  3(   UNKNOWN) : From 00000000h to 00000021h, in r9
  0(   UNKNOWN) : From 00000000h to 00000021h, in rcx
  1(   UNKNOWN) : From 00000021h to 000000B3h, in rbp[24] (1 slot)
  2(   UNKNOWN) : From 00000021h to 000000B3h, in rbp[32] (1 slot)
  3(   UNKNOWN) : From 00000021h to 000000B3h, in rbp[40] (1 slot)
  4(   UNKNOWN) : From 00000021h to 000000B3h, in rbp[-4] (1 slot)
  5(   UNKNOWN) : From 00000021h to 000000B3h, in rbp[-8] (1 slot)
  0(   UNKNOWN) : From 00000021h to 000000B3h, in rbp[16] (1 slot)
```

**Comment by AndyAyersMS** [comment]
For regular opts (Tier1)
```
Found 53 files with textual diffs.
PMI Diffs for System.Private.CoreLib.dll, framework assemblies for x64 default jit
Summary:
(Lower is better)
Total bytes of diff: 0 (0.00% of base)
0 total files with size differences (0 improved, 0 regressed), 129 unchanged.
0 total methods with size differences (0 improved, 0 regressed), 192592 unchanged.
53 files had text diffs but not size diffs.
System.Private.CoreLib.dasm had 275 diffs
System.Runtime.Extensions.dasm had 261 diffs
Microsoft.CodeAnalysis.dasm had 109 diffs
System.Threading.Tasks.Dataflow.dasm had 93 diffs
System.Collections.Immutable.dasm had 90 diffs
```
Debug diffs seen mostly (exclusively?) in `.cctor` methods, where we now emit two debug records for the type context instead of one (seems odd we'd even emit one).

With minopts:
```
Found 126 files with textual diffs.
PMI Diffs for System.Private.CoreLib.dll, framework assemblies for x64 default jit
Summary:
(Lower is better)
Total bytes of diff: 0 (0.00% of base)
0 total files with size differences (0 improved, 0 regressed), 129 unchanged.
0 total methods with size differences (0 improved, 0 regressed), 192603 unchanged.
126 files had text diffs but not size diffs.
Microsoft.CodeAnalysis.VisualBasic.dasm had 174325 diffs
Microsoft.CodeAnalysis.CSharp.dasm had 143840 diffs
System.Private.CoreLib.dasm had 127918 diffs
Microsoft.Diagnostics.Tracing.TraceEvent.dasm had 90087 diffs
System.Private.Xml.dasm had 85386 diffs
```
Pretty much every method impacted; debug info diffs similar to the test program diff shown above.

**Comment by AndyAyersMS** [comment]
Failure on x64 is from block merging: we have
```
BB01 [0000]  1                             0     [000..046)                                     i rare label target LIR 
BB02 [0001]  1  0    BB01                  0     [046..3ED)        (throw ) T0      try { }     keep i try rare label idxlen new[] LIR 
```
and we merge to
```
BB02 [0001]  1  0                          0     [046..3ED)        (throw ) T0      try { }     keep i try rare label target idxlen new[] LIR 
```
and so the initial block offset skips some scopes.

**Comment by BruceForstall** [comment]
Seems odd (a bug?) we would merge a block into a `try` block unless it was empty.

**Comment by AndyAyersMS** [comment]
Seems like it is allowed, per `fgOptimizeEmptyBlock`.

One option is to disallow deletion if the upstream block has a different starting IL offset; another is to update the start IL offset of the survivor.

**Comment by AndyAyersMS** [comment]
Trying the update route first -- not convinced it will always work as we probably are somewhat lax about block offset maintenance if not doing debug codegen.

**Comment by AndyAyersMS** [comment]
Can't drill into these failures as jenkins itself seems to be in a bad way:
```
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1378)
```
cc @dotnet/dnceng

**Comment by MattGal** [comment]
@AndyAyersMS my apologies, we're having the same issue on ci.dot.net as Monday.  Tracked by https://github.com/dotnet/core-eng/issues/4414, I'll send mail to partners shortly.

**Comment by AndyAyersMS** [comment]
Finally isolated the corefx failing case... we're optimizing and reorder blocks so not surprisingly we see blocks out of IL offset order. And we only have untracked lifetimes for locals.

```
*************** In fgReorderBlocks()

Initial BasicBlocks
--------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight    [IL range]     [jump]      [EH region]         [flags]
--------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1     [000..005)-> BB03 (always)                     i label target 
BB02 [0001]  1       BB03                  1     [005..007)        (return)                     i label target bwd 
BB03 [0002]  1  0    BB01                  1     [007..00C)-> BB02 (always) T0      try { }     keep i try label target bwd 
BB05 [0005]  1       BB04                  1     [017..019)        (return)                     i label target 
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ funclets follow
BB04 [0004]  1     0                       1     [011..017)-> BB05 ( cret )    H0 F catch { }   keep i label target flet 
--------------------------------------------------------------------------------------------------------------------------------------

Decided to straighten unconditional branch at block BB01 branch to BB03 because of IBC profile data
fgFindInsertPoint(regionIndex=0, putInTryRegion=true, startBlk=BB01, endBlk=BB04, nearBlk=BB03, jumpBlk=BB00, runRarely=false)
Relocated uncommon block BB02
Relocated block [BB02..BB02] inserted after BB03
Changed an unconditional jump from BB01 to the next block BB03 into a BBJ_NONE block
Changed an unconditional jump from BB03 to the next block BB02 into a BBJ_NONE block

After this change in fgReorderBlocks the BB graph is:
--------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight    [IL range]     [jump]      [EH region]         [flags]
--------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1     [000..005)                                     i label target 
BB03 [0002]  1  0    BB01                  1     [007..00C)                 T0      try { }     keep i try label target bwd 
BB02 [0001]  1       BB03                  1     [005..007)        (return)                     i label target bwd 
BB05 [0005]  1       BB04                  1     [017..019)        (return)                     i label target 
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ funclets follow
BB04 [0004]  1     0                       1     [011..017)-> BB05 ( cret )    H0 F catch { }   keep i label target flet 
--------------------------------------------------------------------------------------------------------------------------------------


*************** In fgUpdateFlowGraph()
Before updating the flow graph:

--------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight    [IL range]     [jump]      [EH region]         [flags]
--------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1     [000..005)                                     i label target 
BB03 [0002]  1  0    BB01                  1     [007..00C)                 T0      try { }     keep i try label target bwd 
BB02 [0001]  1       BB03                  1     [005..007)        (return)                     i label target bwd 
BB05 [0005]  1       BB04                  1     [017..019)        (return)                     i label target 
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ funclets follow
BB04 [0004]  1     0                       1     [011..017)-> BB05 ( cret )    H0 F catch { }   keep i label target flet 
--------------------------------------------------------------------------------------------------------------------------------------

fgRemoveBlock BB01
Removing empty BB01

After updating the flow graph:

--------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight    [IL range]     [jump]      [EH region]         [flags]
--------------------------------------------------------------------------------------------------------------------------------------
BB03 [0002]  1  0                          1     [007..00C)                 T0      try { }     keep i try label target bwd 
BB02 [0001]  1       BB03                  1     [005..007)        (return)                     i label target bwd 
BB05 [0005]  1       BB04                  1     [017..019)        (return)                     i label target 
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ funclets follow
BB04 [0004]  1     0                       1     [011..017)-> BB05 ( cret )    H0 F catch { }   keep i label target flet 
--------------------------------------------------------------------------------------------------------------------------------------
```

Prospective fix to not enable the untracked reporting if we're optimizing. We can try and do better if/when we address #20465,

**Comment by AndyAyersMS** [comment]
Four failures from minopts runs. However these rarely run, and at first glance none of the failures seem likely to be caused by this change. Will investigate to confirm.

EG one of the failures is:
```
Assertion failed '!siVerifyLocalVarTab()' in 'JitTest.Test:TestFunc(long):int' (IL size 362)
File: d:\\j\\workspace\\x86_arm_altji---e41d7265\\src\\jit\\scopeinfo.cpp Line: 268
```
which is an assert that the local var info provided to the jit failed verification. And this verification is only done for debug codegen and I don't believe I have changed debug behavior in that mode.

**Comment by AndyAyersMS** [comment]
Ok, that particular error turned out to be my change restricting debug codegen a bit too much. Pushed a fix.

**Comment by AndyAyersMS** [comment]
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked minopts Build and Test
@dotnet-bot test Ubuntu x64 Checked corefx_minopts
@dotnet-bot test Ubuntu x64 Checked minopts
@dotnet-bot test Windows_NT x64 Checked corefx_minopts
@dotnet-bot test Windows_NT x64 Checked minopts
@dotnet-bot test Windows_NT x86 Checked minopts
@dotnet-bot test Windows_NT x86_arm_altjit Checked minopts

**Comment by AndyAyersMS** [comment]
Various remaining failures all appear to happen in the rolling legs for these jobs. I perhaps need to be smarter about screening which jobs to kick off to avoid having to check for pre-existing issues.

**Comment by briansull** [comment]
Can we add some kind of regression test for this?
THis seems like an area that we will be modifying goong forwards.

**Comment by AndyAyersMS** [comment]
@mikem8361 is there any way to look at the jit-generated debug info in process, or would we need to write a debugger test?

Do we have any debugger tests that track what the jit creates for debug info when it is generating non-debuggable code?

**Comment by mikem8361** [comment]
I don’t know off hand.  I’ll look at our tests. Maybe @noahfalk knows more.

**Comment by AndyAyersMS** [comment]
@dotnet/jit-contrib any last comments? 

Any thoughts on if/when/how we should test debug emission from non-debug codegen modes?

**Pull request merged**
