### PR TITLE
[release/3.0-preview9] Enable PRs for preview9 branch

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@wtgodbe Do you know why the PR triggers are overridden for coreclr's public build?

**Comment by wtgodbe** [comment]
I don't, @hoyosjs @jashook @jeffschwMSFT might know

**Comment by jashook** [comment]
Based on a conversation with @echesakovMSFT we seem to have it as is for legacy reasons we do not entirely understand.

**Pull request merged**
