### PR TITLE
ARM64: Update email notification

### PR DESCRIPTION
**Pull request by kyulee1**
Only sending email for Windows run when push occurs.
Skip sending email for private run (PR).

### CODE REVIEW

**Comment by kyulee1** [comment]
@dotnet-bot test ci

**Comment by kyulee1** [comment]
@dotnet/arm64-contrib PTAL

**Comment by kyulee1** [comment]
@mmitche test ci doen't work for me. PTAL.

**Comment by jashook** [comment]
LGTM

**Comment by swgillespie** [comment]
@kyulee1 I'm getting email from this and the previous email PR on my personal email address, is there a way I can change the target mail address?

**Comment by kyulee1** [comment]
It was sent to default recipients that Jenkins record. I don't know how to change the address. 
In fact, sending everybody is not my intention, either. I'm figuring out a way just to send it to arm64 group.

**Comment by swgillespie** [comment]
@kyulee1 okay, thanks! I'll go look on Jenkins.

**Pull request merged**
