### PR TITLE
Remove -Rebuild option from build scripts

### LINKED ISSUE #18042: CoreCLR failed when build with MSVC on Windows
Hello,

I tried to build CoreCLR on Windows with VS2017 Update2. It failed to build due to the error CS2001: Source file 'D:\CoreCLR\src\bin\obj\Windows_NT.x86.Release\System.Private.CoreLib\..\eventing\DotNETRuntimeEventSource.cs' could not be found. This issue is caused by master branch revision [0fbd0f5](https://github.com/dotnet/coreclr/commit/0fbd0f535e566bcde591701adc2de51ee0f020af). Could you please help take a look at this? Thank you!

**You can repro this issue as the steps below:**
1. git clone https://github.com/dotnet/coreclr D:\CoreCLR\src
2. Open a clean x86 prompt (C:\windows\syswow64\cmd.exe) and browse to D:\CoreCLR\src
3. build x86 release -Rebuild -- /clp:ShowCommandLine

**Error info:**
CSC : error CS2001: Source file 'D:\CoreCLR\src\bin\obj\Windows_NT.x86.Release\System.Private.CoreLib\..\eventing\DotNETRuntimeEventSource.cs' could not be found. [D:\CoreCLR\src\src\System.Private.CoreLib\System.Private.CoreLib.csproj]

### PR DESCRIPTION
**Pull request by brianrob**
Fixes #18042.

Removes -Rebuild option from build scripts after discussion on #18042.

### CODE REVIEW

**Comment by brianrob** [comment]
@BruceForstall can you help me trigger the CI leg that will test the change to arm32_ci_script.sh?

**Comment by BruceForstall** [comment]
@dotnet-bot test Tizen armel Cross Checked Build

**Comment by jkotas** [comment]
Remove it from https://github.com/dotnet/coreclr/blob/master/config.json#L285 as well? This file controls the command line options supported by `run.exe`.

**Comment by brianrob** [comment]
Pushed https://github.com/dotnet/coreclr/pull/18089/commits/69047062b2bfa5c20003ccf73c9b21a625b41991 to update config.json.

**Comment by brianrob** [comment]
@dotnet-bot test Tizen armel Cross Checked Build

**Pull request merged**
