### PR TITLE
Fix value numbering for FieldSeqStore::NotAField.

### LINKED ISSUE #8133: Value numbering of `FieldSeqStore::NotAField()` has incorrect semantics.
Value numbering produces the same value number for each occurrence of `FieldSeqStore::NotAField`. This semantics is not logically consistent with the semantics of `NotAField`, however: `NotAField` indicates that we cannot reason about the address expression that it annotates, therefore we cannot reason about the value stored at the corresponding location. A recent change to admit the VN for `NotAField` in `ExtendPtrVN` (#8086) exposed SBCG due to this mismatch in semantics: distinct array elements were assigned the same value number because each had the same base coupled with the `NotAField` VN.

Value numbering should instead produce a unique value number for each occurrence of `NotAField`. This is complicated somewhat by the need to map back from a VN to a `FieldSeq*`.

### PR DESCRIPTION
**Pull request by pgavlin**
Before this change, value numbering produced the same value number for
each occurrence of `FieldSeqStore::NotAField`. This semantics is not
logically consistent with the semantics of `NotAField`, however:
`NotAField` indicates that we cannot reason about the address expression
that it annotates, therefore we cannot reason about the value stored at
the corresponding location. A recent change to admit the VN for
`NotAField` in `ExtendPtrVN` exposed SBCG due to this mismatch in
semantics: distinct array elements were assigned the same value number
because each had the same base coupled with the `NotAField` VN.

This change revises the representation of `NotAField` during value
numbering: instead of reusing the same value number for each
occurrence of `NotAField`, each occurrence is instead assigned a new,
unique value number. These value numbers are represented using a new
chunk attribute to retain the ability to decide whether or not a value
number represents `NotAField` without the use of a more heavyweight map
(e.g. a `VNMap`).

Fixes #8133.

### CODE REVIEW

**Comment by pgavlin** [comment]
@JosephTremoulet @AndyAyersMS @dotnet/jit-contrib PTAL

**Comment by pgavlin** [comment]
cc @jkotas. This is the fix for #8133, which is causing the failures in https://github.com/dotnet/corefx/pull/13655.

**Comment by sivarv** [comment]
Any SuperPMI diffs?

**Comment by pgavlin** [comment]
@sivarv: I am currently unable to run SuperPMI diffs, as I have not been able to access corpnet. I am working on collecting diffs using jitutils.

**Comment by pgavlin** [comment]
@sivarv: there are no diffs due to this change across the core library and the framework assemblies.

**Comment by sivarv** [comment]
@pgavlin - Thanks.

**Comment by AndyAyersMS** [comment]
Realize you merged this one already, but I'd like to see a test case for this in CoreCLR if possible.

**Comment by pgavlin** [comment]
@AndyAyersMS: I added a regression test with this PR. Are you referring to a test that uses ref returns and locals as expressed in C# (rather than IL)?

**Comment by AndyAyersMS** [comment]
No, what you did is good.  I just didn't scroll down far enough to see the test case.

**Pull request merged**
