### PR TITLE
Marking {ReadOnly}Span with IsReadOnly attribute

### PR DESCRIPTION
**Pull request by ahsonkhan**
Fixes issue https://github.com/dotnet/corefx/issues/23809

Related PR for corefx: https://github.com/dotnet/corefx/pull/23908

cc @KrzysztofCwalina, @VSadov, @jkotas

### CODE REVIEW

**Comment by KrzysztofCwalina** [comment]
looks good, but I think Memory<T> and ROMemory<T> should be marked as well.

**Comment by VSadov** [comment]
Span _needs_ to be readonly so that `ordinarySpan.CopyTo(stackallocatedSpan)` would work.

For regular structs being readonly is not functionally important. Since they cannot contain references, they do not participate in escape analysis. 

That said, it is a _good to have_ thing. 
It is beneficial to mark struct readonly for perf reasons though. How much benefit will depend on the usage, but there is no downside.

On the other bug, I mentioned that threshold is the size to be > 2 or 4 pointers. I was confusing that with choice whether to use pass-by-value vs. pass-by-readonly-ref.

There are no unwanted consequences, however, in making a struct readonly (other than future compat issues if struct needs to drop readonly). Otherwise readonly struct behave exactly the same as ordinary structs and in some cases compiler can skip making defensive copies.

**Comment by stephentoub** [comment]
FWIW, I expect we're going to want to go through the BCL and mark many structs as readonly if they can be.

**Comment by VSadov** [comment]
Right, ordinary-->readonly is not a breaking change. 
(intentionally, so that existing structs could be made readonly too)

**Pull request merged**
