### PR TITLE
Fix SIGSEGV in EventPipe on Shutdown (#14123)

### PR DESCRIPTION
**Pull request by brianrob**
Port the fix contained in #14123 to release/2.0.

### CODE REVIEW

**Comment by brianrob** [comment]
@nategraf, this fix is just for the crash.  I had to modify it a bit from the version in master because in master the provider ID is no longer a GUID, but I didn't want to bring that into release/2.0 as well.

**Comment by nategraf** [comment]
So I realised that the commit I link to is also incomplete. There was another issue where the use of `CreateProvider` was adding the config provider to the registered provider list and it would be deleted along with the other providers as well as in the destructor. 

To avoid this the `CreateProvider` method should not be used to build the config provider. This also means some of the changes in the commit I linked above are not needed. 

https://github.com/nategraf/coreclr/commit/28eedfef4a63b60580d749683fb90b65af598a1f

**Comment by chunseoklee** [comment]
@brianrob @nategraf This commit will be merged or wait for enhancement ?

**Comment by nategraf** [comment]
This is intended to be merged without dependency on any other enhancements. If you are referring to the enablement of EventPipe on Windows when you say "enhancement" I don't think that change will be backported to release 2.0. (I however do not make that call)

Is this issue affecting you? If so I can take this over and get it through before Brian comes back

**Comment by Imisnew2** [comment]
@netgraf If I may chime in, this issue is affecting me as well. It causes failures in our continuous integration infrastructure as well as for various developers. Though it can wait until the 15th or so, at least for me.

**Comment by brianrob** [comment]
Closing this as it looks like #15765 contains this fix plus more.

**Pull request closed without merging**
