### PR TITLE
Improved preprocessor check for WRITE_0_BYTES_HANGS_TTY

### PR DESCRIPTION
**Pull request by heinzo**
- replaced #ifdef with #if so that setting WRITE_0_BYTES_HANGS_TTY
  to 0 would effectively deactivate the enclosing code block
- setting WRITE_0_BYTES_HANGS_TTY to the value of 1 to preserve the
  original behavior

### CODE REVIEW

**Comment by heinzo** [comment]
This should resolve #263

**Comment by janvorli** [comment]
LGTM

**Comment by heinzo** [comment]
Hmmm...I was trying to resolve the merge conflict by doing a rebase on my branch from coreclr/master and after pushing my issue-263 branch, this pull request seemed to contain a lot more commits than it really is.  Let me know if I could have done this better (and how) to avoid this situation.

**Comment by kangaroo** [comment]
@heinzo The rebase has made the PR rather 'cluttered'.  Can you delete your local branch, cherry pick over the fix, and force push up to your repo?  This should clean up the PR and make it easy to merge.

**Comment by heinzo** [comment]
@kangaroo : thanks for fixing the cluttered PR

**Pull request closed without merging**
