### PR TITLE
Introduce hierarchy into the Jenkins CI jobs, to improve UI

### PR DESCRIPTION
**Pull request by BruceForstall**
Introduce hierarchy into the Jenkins CI jobs, to improve UI

The Jenkins jobs UI is super cluttered right now, due to dotnet/coreclr
having so many jobs. This change proposes to move all PR jobs to a separate
folder. It lays the groundwork to make it easy to create additional hierarchy.

For example, you might find jobs:

```
dotnet_coreclr/pr/arm64_cross_checked_windows_nt_prtest
dotnet_coreclr/pr/x64_checked_osx10.12_gcstress15_r2r_tst_prtest
dotnet_coreclr/x64_checked_ubuntu_standalone_gc_tst
dotnet_coreclr/jitstress/arm64_cross_checked_windows_nt_gcstress0xc
```

The advantages:
1. Separate PR and non-PR tests. This is important, since non-PR tests
should always be passing (otherwise there is a regression), while PR
tests can fail due to a bug in a proposed change.
2. Jenkins UI would hopefully be more responsive.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet-bot test CI please

**Comment by BruceForstall** [comment]
First, what do you think of this idea?

Second, what am I missing here? Will things break that I'm not considering?

**Comment by BruceForstall** [comment]
@dotnet-bot test CI please

**Comment by BruceForstall** [comment]
@dotnet-bot test CI please

**Comment by BruceForstall** [comment]
@dotnet-bot test CI please

**Comment by BruceForstall** [comment]
@dotnet-bot test CI please

**Comment by BruceForstall** [comment]
@dotnet-bot test CI please

**Comment by BruceForstall** [comment]
@dotnet-bot test CI please

**Comment by BruceForstall** [comment]
Error in "GenCI":
```
ERROR: Could not create item, unknown parent path in "pr/jitstress/x64_checked_windows_nt_r2r_jitstress1_prtest"
```

https://ci.dot.net/job/dotnet_coreclr/job/master/job/GenPRTest/job/generator_prtest/579/

saved: https://gist.github.com/BruceForstall/35e56b230ff58629e064aa4cd8c9e6fa

**Comment by BruceForstall** [comment]
@jashook @mmitche @RussKeldorph I've updated the change to only move the PR jobs into a sub-directory, but everything else stays the same, and there is no hierarchy created (currently) for architecture or OS.

PTAL

**Comment by BruceForstall** [comment]
ping. Any comments / opinions here? Any help/suggestions to fix the remaining error?

**Comment by jashook** [comment]
I have reservations on this PR. I am worried these changes will make policing our outerloop jobs even more difficult.

**Comment by BruceForstall** [comment]
> I have reservations on this PR. I am worried these changes will make policing our outerloop jobs even more difficult.

Can you explain why you think that? The intent of the change, and my expectation, was that this change would do exactly the opposite. With PR jobs split to a separate directory, you could more easily see exactly the "outerloop" (push/cron) jobs in one place, not "polluted" by the PR jobs which could easily be failing due to PRs with failures.

**Comment by jashook** [comment]
>Can you explain why you think that? The intent of the change, and my expectation, was that this change would do exactly the opposite.

Yes sorry, I think the PR as it is now does solve this problem; however, it in my opinion adds complicated logic to allow creating folders by arch and os. The value that logic has, to me, is questionable because further implementation of that, would make it difficult to police our outerloop jobs.

I think it is better to simplify this PR to just create the pr folder and not include the os/arch which is not necessary.

**Comment by BruceForstall** [comment]
Note that the current change does NOT do anything with OS or ARCH (such as create folders), though I did leave those options in the function I added. IMO, it would be better to segregate by these as well, but this PR does not do that.

**Comment by jashook** [comment]
I understand; however, I am still skeptical about including the variables specifically because there is no functionality added now. Either way, it is a nit at best and am ok with the overall change.

**Comment by BruceForstall** [comment]
@dotnet-bot test CI please

**Comment by BruceForstall** [comment]
@dotnet-bot test CI please

**Comment by BruceForstall** [comment]
@jashook @mmitche @RussKeldorph This change is now error-free, so if there are no further comments, I plan to merge it later today.

**Comment by BruceForstall** [comment]
@mmitche pointed out that Jenkins has the concept of "Views", of which "Official Builds" is one we precreate that excludes all PR jobs. That might be sufficient, and better than this.

Presumably we could also create more tuned views, e.g., "x86 Windows_NT jitstress", "arm32 Linux", etc.

I'll hold off on this for now.

**Comment by BruceForstall** [comment]
Closing. Now we have views that serve most of this purpose.

**Pull request closed without merging**
