### PR TITLE
Memory growth algorithm improvement in coreconsole

### PR DESCRIPTION
**Pull request by QtRoS**
In my version _Append_ will work properly if _strLen_ is **very** big (for example 3*_m_capacity_). And I used value _1.5_ as memory growth factor because it is better (strictly speaking because 2 is the worst value).
Please not that I didn't change program logic in this commit. I've just changed the way how new value is computed. I made this code rock-solid and invulnerable to big input.

### CODE REVIEW

**Comment by danmosemsft** [comment]
Confusing -- this is an old PR with a new comment? @mikedn can you please review and merge if appropriate.

**Comment by mikedn** [comment]
@QtRoS 
> while" makes this code more robust with minimal changes.
"max(oldCapacity * 2, requiredCapacity)" - will cause new allocation at next oeration, so I don't think that it is better.

Then use `newCapacity = (m_length + strLen + 1) * 3 / 2` instead. There's no need for a loop here and I've never seen a resize implementation that uses one.

@danmosemsft 
The PR was created from the same branch as the old one and it looks like it somehow kept some of the old comments. The following comment from @gkhanna79 was lost:

> Can you please explain why while is needed if the new capacity is going to be computed to be greater than the existing m_capacity?
And why the factor of 1.5 vs 2?

To speed things up I'll answer that myself:
* It is incorrect to compute `newCapacity` as `m_capacity * 2`. If we append a 42 characters string and the old capacity is 8 the new capacity will be 16 and then we'll overflow the buffer when copying those 42 characters.
* Both 1.5 and 2 are commonly used. In fact CLR's own `SString` class seems to be using 1.5. AFAIR VC++'s `std::string` uses 1.5 too.

And speaking of CLR's `SString`: I wonder why `coreconsole` doesn't use that like `corerun` does. It looks like `corerun` was updated with the long paths work but `coreconsole` was not. I'm not sure if `coreconsole` is actually used to worth the trouble but it seems to me that we should update it to match `corerun` and then this fix wouldn't be necessary.

> can you please review and merge if appropriate.

For the merge part you'll have to ask someone from Microsoft :).

**Comment by danmosemsft** [comment]
@QtRoS can you address feedback here so we keep this PR moving? thanks!

**Comment by QtRoS** [comment]
I've explained motivation of this pull request multiple times. What can I do now?

**Comment by danmosemsft** [comment]
I agree with @mikedn that `newCapacity = (m_length + strLen + 1) * 3 / 2` (or `* 2`) makes more sense than a loop. A loop isn't needed.

**Comment by QtRoS** [comment]
@danmosemsft But in such case next reallocation will happen in the very next operation.

**Comment by danmosemsft** [comment]
@QtRoS that depends on the size of the next Append right? @jkotas is this code used for anything particular, does it matter much?

**Comment by mikedn** [comment]
> But in such case next reallocation will happen in the very next operation. 

That was the case for `max(oldCapacity * 2, requiredCapacity)`, not for `newCapacity = (m_length + strLen + 1) * 2`.

**Comment by jkotas** [comment]
This code is executed during startup of the corerun host. The corerun host is really only used by tests, and folks who do not want to use the default nuget-enabled `dotnet` host (the sources live in https://github.com/dotnet/core-setup/). So tweaks in the corerun host do not matter a whole lot for what most people our there actually use.

Wrt above discussion, it should be better to grow the buffer more aggressively (ie keep the original 2* factor) - it good for avoiding unnecessary copies. And to minimize amount of wasted memory while the process is running - allocate the exact right about of memory once the desired string is built and copy the string into it.

**Comment by QtRoS** [comment]
So, I should change code or just close this request?

**Comment by danmosemsft** [comment]
@QtRoS let's change it to `newCapacity = (m_length + strLen + 1) * 2`

**Comment by danmosemsft** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build (https://github.com/dotnet/coreclr/issues/6298)

**Comment by danmosemsft** [comment]
I don't understand the jit diff job:

```
11:24:17 RUNTEST: Invoking msbuild
11:24:19 RUNTEST:  Created the runtime layout with all dependencies in jitdisasm
11:24:19 RUNTEST: Error: Ensure you have done a successful build of the Product and jitdisasm contains runtime binaries.
11:24:19 Build step 'Execute Windows batch command' marked build as failure
```

@dotnet-bot test  {os} x64 Checked Jit Diff Build and Test

**Comment by danmosemsft** [comment]
@mmitche The job name contains {os} which I guess is a placeholder. Not sure the incantation to make it rerun.

**Comment by mmitche** [comment]
@danmosemsft This got enabled as part of someone's attempt to work on a diff job.  It shouldn't be running in your PR.  Please ignore.

**Pull request merged**
