### PR TITLE
Revert "TimeSpan.FromMilliseconds(TimeSpan.MaxValue.TotalMilliseconds…

### PR DESCRIPTION
**Pull request by stephentoub**
…) exception fix (#10352)"

This reverts commit 7951bc9accbbf9552d9b5c8105df8f5a32d6c3ab.

https://github.com/dotnet/corefx/pull/17648#issuecomment-290052104

cc: @jkotas, @tarekgh, @ezverev

### CODE REVIEW

**Comment by ezverev** [comment]
The tests that broke here i.e. test based on incorrect rounding in existing TimeSpan version are expected to get broken. The fix is intended to remove the incorrect rounding in TimeSpan. Former TimeSpan was rounding milliseconds instead of ticks.

**Comment by stephentoub** [comment]
> The tests that broke here i.e. test based on incorrect rounding in existing TimeSpan version are expected to get broken.

In that case, please submit a PR to CoreFx that addresses the breaks. We are blocked from upgrading corefx to the newer coreclr until this is resolved.  Thanks.

**Comment by ezverev** [comment]
Will do so asap.

**Comment by stephentoub** [comment]
> Will do so asap.

Thanks.  Appreciated.

**Comment by tarekgh** [comment]
@ezverev let me know if you'll not be able to submit the PR so I can do it. 

Also please when changing the test make sure you keep the old behavior for the full desktop runs and have a new cases for the new behavior. you can control that by using SkipOnTargetFramwork attribute on the test methods.

**Comment by ezverev** [comment]
@stephentoub Working on the unit tests for modified TimeSpan I found a huge flaw in my fix. I got into the kid's trap with the overflow check. Existing unit tests do not cover it:

With my fix the TimeSpan.FromMilliseconds(922337203685477.62) gives incorrect result.

Please do revert the change that I've made. I will have to work on the issue further and enhance the unit tests before I resubmit the PR.

**Comment by tarekgh** [comment]
@stephentoub I'll revert the change and then we'll need to update the tests one more time when picking up coreclr in corefx.

**Comment by stephentoub** [comment]
@tarekgh, I reverted your test changes here:
https://github.com/dotnet/corefx/pull/17680/commits/928a2be6d810ca0328e3a9dc461ba3a4f26db810

**Comment by tarekgh** [comment]
thanks @stephentoub

**Pull request merged**
