### PR TITLE
[Arm64/Unix] Add list of known arm64 fails

### PR DESCRIPTION
**Pull request by sdmaclea**
@jkotas 
@jashook

### CODE REVIEW

**Comment by RussKeldorph** [comment]
@sdmaclea, is this intended to close #9531?  If so, you can edit the description (first comment) to include "Fixes #9531" and it will be auto-closed when this PR is merged.  If you know that and intentionally left it out apologies.

**Comment by sdmaclea** [comment]
I thought of #9531 as a proposal to treat the inline comments in failed test lists as standard practice.  It was just a conversation starter.  I am happy to close #9531, but I thought of it as completely orthogonal

I am always happier if I can see a categorized view of the issues.

**Comment by RussKeldorph** [comment]
@sdmaclea Ok, thanks.  I wasn't sure if the issue and this PR were linked.

**Comment by wtgodbe** [comment]
I think a got start would be to get everything folded into issues.targets, then see if we can come up with a better solution from there

**Pull request merged**
