### PR TITLE
Revert " Fix the calling convention for P/Invokes and delegates to hostpolicy"

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Reverts dotnet/coreclr#23249

Fixes: https://github.com/dotnet/coreclr/issues/23268

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test please
@dotnet-bot test Ubuntu arm Cross Checked no_tiered_compilation_innerloop Build and Test please

**Comment by AaronRobinsonMSFT** [comment]
@dotnet-bot test this please

**Comment by AaronRobinsonMSFT** [comment]
@dotnet-bot test this please

**Comment by AaronRobinsonMSFT** [comment]
@dotnet-bot test this please

**Comment by sandreenko** [comment]
@mmitche @MattGal could somebody please take a look at [arm32 ubuntu machines](https://ci.dot.net/label/ubuntu.1404.arm32.open/
)? They all are offline. Do they need reboot?

**Comment by AaronRobinsonMSFT** [comment]
@sandreenko I would prefer to checking https://github.com/dotnet/coreclr/pull/23270 which is a better fix for the problem. The entire Azure pipeline is green - including ARM - is that enough to verify the fix worked?

**Comment by AaronRobinsonMSFT** [comment]
@sandreenko The OSX failure is for https://github.com/dotnet/coreclr/issues/23224, other than that both this and #23270 are green Azure. Is there any concern that the ARM32 legs mentioned have something that the Azure pipeline does not?

**Comment by sandreenko** [comment]
> @sandreenko I would prefer to checking #23270 which is a better fix for the problem. The entire Azure pipeline is green - including ARM - is that enough to verify the fix worked?

Yes, please merge which one you think is better. I completely lost in all our runs and infrastructure failures that I can't really say about difference between ADO/Jenkins arm ubuntu builds. They should be the same, using the same docker container but obviously the second failed after the original PR, and the first worked fine. We will check why it happened tomorrow.

**Pull request closed without merging**
