### PR TITLE
Fix dangling else warnings

### PR DESCRIPTION
**Pull request by janvorli**
This change fixes all dangling else warnings and removes the
compiler flag that was disabling their reporting.

### CODE REVIEW

**Comment by janvorli** [comment]
@jkotas, can you take a look please?

**Comment by kangaroo** [comment]
LGTM fwiw

**Comment by jkotas** [comment]
The fix breaks windows build: ex.cpp(492): fatal error C1061: compiler limit : blocks nested too deeply

**Comment by janvorli** [comment]
Fixed the fatal compiler error

**Comment by jkotas** [comment]
LGTM

**Pull request merged**
