### PR TITLE
Precompile FX assemblies for test run

### PR DESCRIPTION
**Pull request by gkhanna79**
Preocmpile test FX as R2R before running the tests

### CODE REVIEW

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
@jkotas PTAL
@wtgodbe - FYI

**Comment by jkotas** [comment]
LGTM

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by gkhanna79** [comment]
Merging since OSX failure is a HW issue and all others are clean.

**Comment by gkhanna79** [comment]
@wtgodbe Can you please enable "crossgen/--crossgen" support for R2R scenarios (GCstress and non-GCStress)?

**Pull request merged**
