### PR TITLE
Add source instructions more prominently

### PR DESCRIPTION
**Pull request by richlander**

### CODE REVIEW

**Comment by ellismg** [comment]
To me, the entries in that table don't scream: "Here's how to build the product" which is what you want, I think?  What if we had a large heading at near the top of the readme.MD called "Getting Started" which had the links?  Alternately, you could just rename the "Product instructions" bullet to "How to build and run the CLR"

**Comment by richlander** [comment]
I agree with you, @ellismg. I'll try something different.

Note that I was going to add "Binaries" as another row. I could just make another table, with those 2 rows and more clearly title it. Thoughts?

**Comment by richlander** [comment]
@ellismg Here's another run at it. Thoughts?

**Comment by ellismg** [comment]
I sort of wish the Build Status table was up higher.  In my mind the intro would come first, followed by the build status and the gitter and then the new table.  I think the status and gitter are of more general interest to folks that want to interact with the github project on a day to day basis.

**Comment by richlander** [comment]
@ellismg That occured to me, too. I'll do that. I didn't sweat the order until I had more feedback. I'm happy to go with your suggestion.

How's the update look?

**Comment by ellismg** [comment]
It's not clear to me if moving the gitter badge down more would be better.  The page feels little weird to look at with it sandwiched between the two tables.  Why don't you decide if you like it better there or if you swap it with the binaries tables.  Either will LGTM.

**Pull request merged**
