### PR TITLE
Improve detection of error condition when using StringBuilder

### LINKED ISSUE #4507: StringBuilder is being internally corrupted if exceeding the maximum allowable length
static void StringBuilderNRE()
        {
            var length = checked(1024 * 1024 * 256);
            var str = new string('x', length);

            var sb = new StringBuilder();
            try
            {
                for (int i = 0; i < 10000; i++)
                {
                    sb.Append(str);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex); //This is expected.
            }

            sb.Append("x"); //Crashes with NRE.
        }

### PR DESCRIPTION
**Pull request by AlexGhiondea**
Fixes #4507 #4508 #4511 

/cc @jkotas

### CODE REVIEW

**Comment by jkotas** [comment]
LGTM

**Comment by AlexGhiondea** [comment]
@dotnet-bot please test OSX x64 Checked Build and Test

**Comment by jkotas** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by GSPP** [comment]
I always prefer `long` arithmetic to such funky "impossible" integer conditions.

**Pull request merged**
