### PR TITLE
Add proper support for custom installed llvm tool chain.

### PR DESCRIPTION
**Pull request by lemmaa**
* Add LLVM_HOME environment variable support for LLDB reference search.

### CODE REVIEW

**Comment by jkotas** [comment]
@dotnet-bot test OSX x64 Checked Build and Test  please

**Comment by jkotas** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by jkotas** [comment]
LGTM

**Comment by lemmaa** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Pull request merged**
