### PR TITLE
Port more JIT tests.

### PR DESCRIPTION
**Pull request by pgavlin**
Most of these tests were blocked on unnecessary usage
of SerializableAttribute and Environment.ExitCode.

### CODE REVIEW

**Comment by pgavlin** [comment]
@richardlford PTAL

**Comment by richardlford** [comment]
@pgavlin:

-  the tests in the JIT/Generics/Instantiation/delegates directory
   have "using System.Threading" but do not actually use it. 
- For the tests in JIT/Methodical/stringintern, you have the csproj
  files, but not the source files.

Other than those issues, LGTM.

**Comment by pgavlin** [comment]
> For the tests in JIT/Methodical/stringintern, you have the csproj files, but not the source files.

The source files for these tests already exist.

**Comment by richardlford** [comment]
@pgavlin, ok. LGTM.

**Pull request merged**
