### PR TITLE
Prevent compiler optimization that could cause local var values to change in multithreaded environments, in some places (#16089)

### PR DESCRIPTION
**Pull request by kouvel**
Port of https://github.com/dotnet/coreclr/pull/16089 (2f14b350960af0354608c041d7df501c44dc5640) to release/2.1

Fixes https://github.com/dotnet/coreclr/issues/15592

### CODE REVIEW

**Comment by maririos** [comment]
@dotnet-bot test Tizen armel Cross Checked Innerloop Build and Test please

**Comment by kouvel** [comment]
@dotnet-bot test Tizen armel Cross Checked Innerloop Build and Test

**Comment by kouvel** [comment]
Looks like Tizen armel is still broken

**Comment by kouvel** [comment]
@dotnet-bot test Tizen armel Cross Checked Innerloop Build and Test

**Comment by kouvel** [comment]
Tizen is stuck

**Pull request merged**
