### PR TITLE
Fix tracing lib problems in multiple PALs. Issue #3164.

### PR DESCRIPTION
**Pull request by mikem8361**
Moved the tracepointprovider loading in miscpalapi.cpp to separate library that
is only linked by libcoreclr.so.

### CODE REVIEW

**Comment by mikem8361** [comment]
@brianrob could you review this when you can?

**Comment by brianrob** [comment]
The tracing changes look good to me.  It looks like the commit has more than just the tracing changes.  Can you confirm?

**Comment by mikem8361** [comment]
Yes there are a cuple of other clean up changes.


-------- Original message --------

**Comment by brianrob** [comment]
Ok. I don't have any expertise on the other changes, but the tracing changes look good.  Thanks.

**Comment by janvorli** [comment]
LGTM too

**Pull request merged**
