### PR TITLE
Unconditionally capture output of xUnit tests

### PR DESCRIPTION
**Pull request by echesakovMSFT**
So we can check the output of passing tests in Azure DevOps Tests explorer.

### CODE REVIEW

**Comment by echesakovMSFT** [comment]
@dotnet/jit-contrib PTAL

**Comment by sandreenko** [comment]
Have you fixed the problem when failing output was not shown? What was the issue there?

Do we have enough space to keep all these results?

**Comment by echesakovMSFT** [comment]
@sandreenko This issue in Helix Sdk - tracked by https://github.com/dotnet/arcade/issues/2759. 

The space shouldn't be a problem here - AzDO has a retention policy for the pipeline artifacts and related data. This change wouldn't increase the size that much - it just captures an output of the passing tests in testresult.xml file.

**Pull request merged**
