### PR TITLE
Fix code comments in Utf16Utility

### PR DESCRIPTION
**Pull request by GrabYourPitchforks**

### CODE REVIEW

**Comment by AntonLapounov** [comment]
Thanks!

**Comment by jkotas** [comment]
@Anipik Could you please check why the mirror is not picking up this change?

**Comment by jkotas** [comment]
@Anipik CoreCLR->CoreRT works fine now. CoreCLR->CoreFX seems to be still stuck. Could you please take a look?

**Comment by Anipik** [comment]
@jkotas Coreclr->Corefx mirror has wrongly marked some commits as mirrored. i will open the mirror PR for them tomorrow

**Pull request merged**
