### PR TITLE
Remove filter for Exception type during registry inquiry.

### LINKED ISSUE #24661: Test failure: Interop_WinRT._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_/_NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_cmd
The test `Interop_WinRT._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_/_NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_cmd` has failed.

Failure Message:
```
\r
Return code:      1\r
Raw output file:      C:\\work\\a41b0e25-9123-49be-81b6-6d0e4c6a89b9\\Work\\5ff48737-f514-4c3e-a14e-6fea1160135f\\Exec\\Interop\\WinRT\\Reports\\Interop.WinRT\\NETClients\\Primitives\\NETClientPrimitives\\NETClientPrimitives.output.txt\r
Raw output:\r
BEGIN EXECUTION\r
 \"C:\\work\\a41b0e25-9123-49be-81b6-6d0e4c6a89b9\\Payload\\corerun.exe\" NETClientPrimitives.exe \r
System.Runtime.InteropServices.COMException (0x80040154): Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))\r
   at System.StubHelpers.UriMarshaler.CreateNativeUriInstanceHelper(Char* rawUri, Int32 strLen)\r
   at System.StubHelpers.UriMarshaler.CreateNativeUriInstance(String rawUri)\r
   at Component.Contracts.IUriTesting.GetFromUri(Uri uri)\r
   at NetClient.UriTests.RunTest() in F:\\workspace\\_work\\1\\s\\tests\\src\\Interop\\WinRT\\NETClients\\Primitives\\UriTests.cs:line 15\r
   at NetClient.Program.Main(String[] args) in F:\\workspace\\_work\\1\\s\\tests\\src\\Interop\\WinRT\\NETClients\\Primitives\\Program.cs:line 28\r
Expected: 100\r
Actual: 101\r
END EXECUTION - FAILED\r
FAILED\r
Test Harness Exitcode is : 1\r
To run the test:\r
> set CORE_ROOT=C:\\work\\a41b0e25-9123-49be-81b6-6d0e4c6a89b9\\Payload\r
> C:\\work\\a41b0e25-9123-49be-81b6-6d0e4c6a89b9\\Work\\5ff48737-f514-4c3e-a14e-6fea1160135f\\Exec\\Interop\\WinRT\\NETClients\\Primitives\\NETClientPrimitives\\NETClientPrimitives.cmd\r
Expected: True\r
Actual:   False
```

Stack Trace:
```
   at Interop_WinRT._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_cmd() in F:\workspace\_work\1\s\bin\tests\Windows_NT.x64.Release\TestWrappers\Interop.WinRT\Interop.WinRT.XUnitWrapper.cs:line 218
```

Build : Master - 20190519.72 (Core Tests)
Failing configurations:
- Windows.10.Nano.Amd64-x64
  - 
  - 

Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190519.72/workItem/Interop/analysis/xunit/Interop_WinRT._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_~2F_NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_cmd

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Update Console output with more details.

Fixes #24661 

cc @jkoritzinsky @RussKeldorph

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
@riarenas Is this related to the aforementioned lack of pushback to github from AzDO? I am not observing anything from the AzDO dashboard so it looks like the CI wasn't triggered at all.

**Comment by riarenas** [comment]
There is an ongoing GitHub outage. No webhooks are being delivered right now, which explains why CI is not getting triggered.

https://www.githubstatus.com/incidents/nf4gcjtcsqdb has the details.

**Pull request merged**
