### PR TITLE
Add Fedora 23 runs

### PR DESCRIPTION
**Pull request by ellismg**

### CODE REVIEW

**Comment by ellismg** [comment]
@dotnet-bot test ci please

**Comment by ellismg** [comment]
I looked at the generated jobs and I believe they are correct.

**Comment by ellismg** [comment]
@Priya91 @wtgodbe Can one of you take a look?  We need this to consume in CoreFX.

**Comment by wtgodbe** [comment]
LGTM. You might want to try putting up a dummy PR & triggering a fedora job after you merge this, just to be safe (and maybe an Ubuntu16.04 job as well).

**Comment by ellismg** [comment]
> You might want to try putting up a dummy PR & triggering a fedora job after you merge this, just to be safe (and maybe an Ubuntu16.04 job as well).

I will launch some jobs manually, thanks!

**Pull request merged**
