### PR TITLE
Fix CoreCLR debug launch

### PR DESCRIPTION
**Pull request by cshung**
The new/delete operator can potentially trash last error (in debug build, it always happens), therefore we should obtain the last error code right after the kernel32!EnumProcessModules() call.

### CODE REVIEW

**Comment by cshung** [comment]
@dotnet-bot Test this please

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by cshung** [comment]
@mikem8361?

**Comment by cshung** [comment]
@dotnet-bot test this please

**Pull request merged**
