### PR TITLE
Throw the right exception when interface dispatch is ambiguous

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Throw the approved exception per dotnet/corefx#34124.

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
Cc @sergiy-k

**Comment by jkotas** [comment]
Do we need to update tests to check for this?

**Comment by MichalStrehovsky** [comment]
> Do we need to update tests to check for this?

My plan was to find the test that fails and fix that one (I don't know where are the tests for this is, but I know we have at least one). If nothing fails in the CI, I'll go dig it out.

**Comment by MichalStrehovsky** [comment]
Windows_NT x64 Checked CoreFX Tests fails with:

```
Starting:    System.Text.Encoding.Tests

Assert failure(PID 8936 [0x000022e8], Thread: 2724 [0x0aa4]): Precondition failure: FAILED: pParentData == 0 || (pMT->ParentEquals(pParentData->GetDeclMethodTable()) && pMT->ParentEquals(pParentData->GetImplMethodTable()))

CORECLR! CHECK::Trigger + 0x2C4 (0x00007ffb`c957cf94)
CORECLR! MethodTable::MethodDataObject::Init + 0x67A (0x00007ffb`c9a5cc02)
CORECLR! MethodTable::GetMethodDataHelper + 0x642 (0x00007ffb`c9a53d0a)
CORECLR! MethodTable::GetMethodData + 0xDE (0x00007ffb`c9a53126)
CORECLR! MethodTable::MethodIterator::Init + 0x3CB (0x00007ffb`c9a5d01b)
CORECLR! MethodTable::MethodIterator::MethodIterator + 0x11 (0x00007ffb`c9a3d321)
CORECLR! MethodTableBuilder::ImportParentMethods + 0x137 (0x00007ffb`c9c395fb)
CORECLR! MethodTableBuilder::BuildMethodTableThrowing + 0x14AD (0x00007ffb`c9c28111)
CORECLR! ClassLoader::CreateTypeHandleForTypeDefThrowing + 0x113F (0x00007ffb`c9c2dffb)
CORECLR! ClassLoader::CreateTypeHandleForTypeKey + 0x444 (0x00007ffb`c979eb98)
    File: d:\j\workspace\x64_checked_w---43686a05\src\vm\methodtable.cpp Line: 8447
    Image: D:\j\workspace\x64_checked_w---43686a05\bin\tests\Windows_NT.x64.Checked\testhost\dotnet.exe

Finished:    System.Net.Http.Functional.Tests
```

Is this known?

**Comment by MichalStrehovsky** [comment]
> I have not seen this before.

Seems intermittent. FWIW, filed #22382. I don't see how it could be related/caused by this check in.

**Pull request merged**
