### PR TITLE
port #24973 into release/2.1

### PR DESCRIPTION
**Pull request by adamsitnik**
Port #24973 into release/2.1

Replaces the lock which caused performance issues for our customers with a lock-free approach.

Before:

obraz

After:

obraz

Note: in order to implement the lock-free approach I had to switch from map to an array. I used the existing concept from 3.0

/cc  @wangzhaoguan @danmosemsft

### CODE REVIEW

**Comment by jkotas** [comment]
@adamsitnik You need to fill a servicing request form (see https://github.com/dotnet/coreclr/pull/24858#issuecomment-497375461 for example what it looks) and get it approved by servicing shiproom.

IMHO, this fix does not make the bar for back port to LTS release.

**Comment by tarekgh** [comment]
The last we heard from the customer is willing to use net core 3.0.

**Comment by adamsitnik** [comment]
> The last we heard from the customer is willing to use net core 3.0. 

are you sure?

https://github.com/dotnet/coreclr/pull/24973#discussion_r291421426

> We will consider the upgrade after the 3.0 release, but this is about 10 months later, so if you can, please update the relevant fix optimization to version 2.1, thank you.

**Comment by stephentoub** [comment]
Even if that's true, I agree it doesn't meet the bar. But you can run it through the process to see.

**Comment by adamsitnik** [comment]
No :shipit: this time ;)

**Pull request closed without merging**
