### PR TITLE
Disable a couple of tests that are not supported outside Windows

### PR DESCRIPTION
**Pull request by kouvel**

### CODE REVIEW

**Comment by kouvel** [comment]
@LLITCHEV @wtgodbe

**Comment by LLITCHEV** [comment]
Looks fine to me.

**Comment by LLITCHEV** [comment]
There is a failure on one test on FreeBSD. I doubt it is related to your change. Does it happen without the changes?
Here is the log:
threading.WaitForMultipleObjectsEx.test2 (from (empty)) 

Failing for the past 1 build (Since Failed#115 ) 

Took 0 ms.



Stacktrace
MESSAGE:
Expected thread to wait for 1000 ms (and get interrupted). Interrupt Time: 500 ms, ThreadWaitDelta 492
+++++++++++++++++++
STACK TRACE:

**Comment by kouvel** [comment]
Strange, my change wouldn't cause that. Let me try a rerun.

@dotnet-bot test this please

**Pull request merged**
