### PR TITLE
Adding the new fastest mandelbrot implementation to benchmarks-game.

### PR DESCRIPTION
**Pull request by tannergooding**
FYI. @JosephTremoulet, @AndyAyersMS, @ViktorHofer, @danmosemsft 

New fastest implementation. At this point, I'm pretty certain the only reason it isn't even faster is because the `Q6600` processor the official benches use likely doesn't support the optimization where `movups` is as fast as `movaps` (it looks like that optimization was added in the subsequent microarchitecture).

### CODE REVIEW

**Comment by tannergooding** [comment]
Also FYI. @mellinoe

**Comment by tannergooding** [comment]
@dotnet-bot test Windows_NT x64 perf
@dotnet-bot test Windows_NT x86 perf
@dotnet-bot test linux perf flow

**Comment by JosephTremoulet** [comment]
Thanks for updating.  You should remove mandelbrot-4 in this change, we generally don't want to keep more than two variants of each to avoid cluttering the reporting tracking these.  You'll also, once this gets merged, want to port it to the release/1.1.0 and release/2.0.0 branches, like #14094 and #14095.  Since you're just touching files in these directories, simple cherry-picks should work.

/cc @jorive

**Comment by benaadams** [comment]
There is an issue with the benchmark games in that they also include Jit time; so vectorizing isn't as fast because the Jit startup for Vectors is longer :-/

I was hoping https://github.com/dotnet/coreclr/pull/14244 would elevate this

**Comment by tannergooding** [comment]
Will fix up the build errors shortly.

**Comment by tannergooding** [comment]
> You should remove mandelbrot-4 in this change

@JosephTremoulet, any particular reason why `mandelbrot-4` over `mandelbrot-2`?

**Comment by JosephTremoulet** [comment]
> any particular reason why mandelbrot-4 over mandelbrot-2?

https://github.com/dotnet/coreclr/blob/8eb9adbe7f069638c1457b458c2c5a569eaaabf8/tests/src/JIT/Performance/CodeQuality/BenchmarksGame/README.TXT#L32-L37

**Comment by tannergooding** [comment]
@dotnet-bot test Windows_NT x64 perf
@dotnet-bot test Windows_NT x86 perf
@dotnet-bot test linux perf flow

**Comment by jorive** [comment]
@JosephTremoulet I think you meant to say 1000ms, right?

**Comment by JosephTremoulet** [comment]
> @JosephTremoulet I think you meant to say 1000ms, right?

Whoops!  Yes, ms, good catch, thanks.

**Comment by tannergooding** [comment]
@JosephTremoulet, what is the correct way to validate that? Still not quite sure how to properly navigate bench view.

**Comment by ViktorHofer** [comment]
> Still not quite sure how to properly navigate bench view.

+1

**Comment by tannergooding** [comment]
That is, I can see the numbers for the jobs, etc. I just don't know how to properly compare them for improvement/etc, since Mandelbrot 4 and Mandelbrot 7 are "separate" scenarios.

I see 5619.01ms for Mandelbrot 4 and 6196.77ms for Mandelbrot 7 (duration), which seems backwards since 7 is measurably faster.

**Comment by JosephTremoulet** [comment]
What we've been doing to validate the iteration count is just run the benchmark via [run-xunit-performance.cmd](https://github.com/dotnet/coreclr/blob/master/tests/scripts/run-xunit-perf.cmd) locally.  The point is just to make sure it's neither too fast-running to produce good measurements and profiles nor so long-running that it wastes lab resources.

The different variants of each test had their iteration counts set independently, to make sure we're getting usable measurements for each.  Yes, this means that comparing them to each other in benchview is meaningless, but the goal there is to have usable measurements and look independently at their improvements/regressions over time, not to rank them against each other (which, of course, is what happens over at BenchmarksGame).

**Comment by tannergooding** [comment]
> run the benchmark via run-xunit-performance.cmd locally
@JosephTremoulet, what hardware are the actual jobs run against?

If you have a 8-core, 16-thread machine (or higher) this can seriously skew the results as compared to a 4-core, 8-thread machine.

**Comment by JosephTremoulet** [comment]
> @JosephTremoulet, what hardware are the actual jobs run against?

Not sure... @jorive?

**Comment by jorive** [comment]
Haswell machines with: 4 cores, 8 threads, 3.6GHz

**Comment by tannergooding** [comment]
7 seems to be fine for the iteration count.

**Comment by tannergooding** [comment]
Am I good to merge?

**Comment by JosephTremoulet** [comment]
> Am I good to merge?

Yes.  And please port to release/1.1.0 and release/2.0.0 afterward.

**Pull request merged**
