### PR TITLE
Avoid implicit forward labels in context2.S

### PR DESCRIPTION
**Pull request by jkotas**
Partial fix for #615

### CODE REVIEW

**Comment by josteink** [comment]
I can also confirm this PR fixes most build-errors in the references issue, except the last one (mov DWRD PTR).

Clearly an improvement.

**Comment by janvorli** [comment]
@jkotas, non-local labels inside asm functions are not nice at least for GDB debugging experience. The debugger shows such labels as the current function names when stepping through the code and crossing such label. If such a function calls another one, then the last label before the call is shown on the call stack as the function at that stack frame.
@josteink, could you please try to wrap the labels that @jkotas has modified in the LOCAL_LABEL macro? Both at the declaration and usage points. So e.g:
```asm
je LOCAL_LABEL(Done_CONTEXT_INTEGER)
.
.
LOCAL_LABEL(Done_CONTEXT_INTEGER):
```
If that works, I'd prefer modifying the function code this way.

**Comment by kangaroo** [comment]
What @janvorli said. These should be local labels

**Comment by josteink** [comment]
@janvorli I've tested with LOCAL_LABEL macros and that works fine on FreeBSD with clang3.5.

**Pull request merged**
