### PR TITLE
Add optimization tiers to the Linux perf maps for perfcollect

### PR DESCRIPTION
**Pull request by kouvel**
Fixes https://github.com/dotnet/coreclr/issues/23222:
- It looks like module unloads are currently not taken into account. Once they would be taken into account, Although we have method JIT events from `lttng` with the code address and optimization tier, samples can only be associated with method JIT events by associating the time range when the module is loaded with times of samples, and the event times from `lttng` would not necessarily correspond with times from samples taken by `perf`.
- Updated to include the optimization tier in the perf map for each jitted or R2R method code address

### CODE REVIEW

**Comment by brianrob** [comment]
@kouvel thanks for implementing this.  Is this on by default as long as tiering is on?  I'm conflicted here as I think the data is useful in some cases, but I don't think I want this on by default.  Unfortunately, the contract that ```perf``` uses doesn't really allow for us to decide after collection.

**Comment by kouvel** [comment]
Yea that's true, when viewing a trace with `perf` the optimization tiers would show up. I'll make it optional under an env var, and off by default. It wouldn't be possible to switch back and forth when viewing the trace with `perf`. When opened in PerfView it's preferable to include the tiers, the corresponding change https://github.com/microsoft/perfview/pull/947 extracts the tiers and shows them when the PerfView switch is enabled, so it would be possible to enable and disable showing tiers on the same trace.

**Comment by kouvel** [comment]
Actually looking closer, `perf` does not seem to merge stack frames for methods with different map entries and with the same method name. In a trace without tiers in the perf map it looks like this when multiple tiers of a method are involved:

```
+    7.88%     7.87%          2690  perf-4078.map                     [.] void [test] PerfViewTierEventsTest::Run(bool)               
+    7.44%     7.43%          2538  perf-4078.map                     [.] void [test] PerfViewTierEventsTest::Run(bool)               
```

And in a trace with tiers in the perf map it looks like this:

```
+    9.96%     9.96%          2837  perf-4601.map               [.] void [test] PerfViewTierEventsTest::Run(bool)[QuickJitted]
+    8.93%     8.92%          2541  perf-4601.map               [.] void [test] PerfViewTierEventsTest::Run(bool)[OptimizedTier1]
```

There seems to be no advantage in not showing the optimization tiers, it's actually more confusing having multiple frames with the same method name, different stacks, and nothing to distinguish those frames. So with that, I'm now leaning towards showing tiers in the map enabled by default. I'll still add the config option but enabled by default, so if anyone really wants to, they can turn off the option to show tiers in perf maps.

**Comment by brianrob** [comment]
Interesting.  Can you share the trace where you got this?

**Comment by kouvel** [comment]
Shared offline

**Comment by brianrob** [comment]
Thanks, I will take a look.  There are a few viewing modes and I want to make sure that none of them collapse before we leave this on by default.

**Comment by brianrob** [comment]
Yes, you're right - the symbol resolution algorithm knows that the methods are different based on the code address ranges that are provided via /tmp/perf-pid.map.  Based on that, let's leave it on by default.  PerfView won't experience this behavior unless you ask for it, and users of perf won't wonder why there are two instances of the method.

**Pull request merged**
