### PR TITLE
Expose Assembly::GetFile(s) apis

### PR DESCRIPTION
**Pull request by rahku**
FileStream type was moved from corefx to coreclr repo but it was missing from ref file. This PR add it to ref file. It also exposes Assembly::GetFile(s) apis from corelib. Tests will be added in corefx.

### CODE REVIEW

**Comment by rahku** [comment]
PTAL @kouvel @jkotas

**Comment by mmitche** [comment]
@dotnet-bot test ci please  (ignore)

**Comment by mmitche** [comment]
@dotnet-bot test ci please (ignore)

**Comment by jkotas** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Comment by jkotas** [comment]
@dotnet-bot test Windows_NT x86 legacy_backend Checked Build and Test

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by jkotas** [comment]
@dotnet-bot test Windows_NT x86 legacy_backend Checked Build and Test please

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Pull request merged**
