### PR TITLE
Removing Slice on string overloads that return ROS and adding AsSpan

### PR DESCRIPTION
**Pull request by ahsonkhan**
Related to: https://github.com/dotnet/corefx/pull/17407

### CODE REVIEW

**Comment by ahsonkhan** [comment]
cc @jkotas, @KrzysztofCwalina

**Comment by jkotas** [comment]
What is the plan for Span vs. SpanExtensions?
LGTM

**Comment by jkotas** [comment]
I guess you will have to do this from corefx first. 1. Remove the APIs in corefx, 2. Wait for updated corefx to be published to coreclr, 3. Remove the APIs in coreclr

**Comment by ahsonkhan** [comment]
@dotnet-bot test this please

**Comment by ahsonkhan** [comment]
@jkotas, can this be merged now?

**Comment by ahsonkhan** [comment]
@dotnet-bot test this please

**Comment by jkotas** [comment]
Yes ... once the CI is green.

**Comment by ahsonkhan** [comment]
I do not understand why this error is occuring on ubuntu:
Why is it looking for the type System.Span?

12:04:25                Unhandled Exception: System.TypeLoadException: Could not load type 'System.Span' from assembly 'System.Memory, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
12:04:25                   at Span.SpanBench.TestSpanAsBytes[T](T[] array, Int32 iterationCount, Boolean untrue)
12:04:25                   at Span.SpanBench.Invoke(Action`1 innerLoop, String nameFormat, Object[] nameArgs)
12:04:25                   at Span.SpanBench.Main(String[] args)
12:04:25                ./SpanBench.sh: line 200: 18010 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments

**Comment by jkotas** [comment]
Some of the CI tests in coreclr repo are using live builds of corefx. It leads to CI breaks like these when a breaking change is propagating through the system.

Talk to @wtgodbe if you would like to know the details.

**Comment by jkotas** [comment]
Also, you change to disable the SpanBench test has to go first or together with this.

**Comment by ahsonkhan** [comment]
@dotnet-bot test this please

**Pull request merged**
