### PR TITLE
Build tests for arm64 runs.

### PR DESCRIPTION
**Pull request by jashook**
This has been separated to allow coreclr #11423 to be tested
incrementally in the PR.

### CODE REVIEW

**Comment by jashook** [comment]
@dotnet-bot test CI Please

**Comment by RussKeldorph** [comment]
Have you tried this locally?  At one point I wasn't sure `toolset_dir` was correctly plumbed through to build-test, but I could easily be wrong.

**Comment by jashook** [comment]
Unless it has been regressed locally, my normal workflow is to use this command to publish new tests. That being said it is worth testing. Running a local build now.

**Comment by RussKeldorph** [comment]
Ok, nevermind then.  If you've tried in the past with success, it's probably fine.

**Comment by jashook** [comment]
Confirmed this works as expected.

**Pull request merged**
