### PR TITLE
Convert go_through_object macros to be a lambda in checked and debug …

### PR DESCRIPTION
**Pull request by davidwrighton**
…builds of gc

- Lambda conversion for release builds did not provide significant diagnostic improvements
- However, for debug builds there are visible improvements
- This change is focussed on doing the best job possible for debug cases

### CODE REVIEW

**Comment by davidwrighton** [comment]
@PeterSolMS @Maoni0  I spoke to Peter yesterday about this change, and as I was doing so, it occurred to me a way to produce a rather less impactful change for debug time benefits for folks who debug using the debug variant of the debugger. 

In general, I would expect a compiler to generate equivalent code for this vs the previous completely macro solution, as the only meaningful difference is that cases which performed a goto outside of the lambda now goto a landing pad, which then has a goto to the same location as before. I expect that any decent optimizer could just optimize that away. For debug builds, this should be nicely debuggable. For retail builds it should be the same as before. For checked builds this change enables the lambda's but I haven't investigated what they look like. We could come up with a way to disable lambdas for checked builds, but I'm not familiar at this moment with what define would need to be checked.

**Comment by jkotas** [comment]
> debug time benefits for folks who debug using the debug variant of the debugger.

Are there folks like this?

FWIW, I have tried to debug the GC using debugger multiple times, but I was never really worked for me. The way to debug GC is using logs.

**Comment by davidwrighton** [comment]
The ability to do this has come up when I was talking to Peter. Logs are a much better way to understand the overall system, but debugging for him was good for figuring out what something in particular was doing when coming to the code inexperienced with a particular portion of it. Effectively, based on my conversations with Peter/Maoni (and my previous efforts in the GC), I've come to believe that debugging is valuable, but not for making the GC actually better, but it is valuable for understanding what the code is doing when one has relatively little context. My cases where I've been stuck debugging in the GC has been valuable have largely focused on .. so the type system did something subtly wrong, and I need to know with fair detail exactly what the GC is doing so I can figure out how the other parts of the runtime generated invalid data structures.

**Comment by Maoni0** [comment]
we agreed offline to revisit this in post 3.0 time frame as we already have other higher priority items that the GC team has to focus on for 3.0.

**Comment by VSadov** [comment]
I've spent some time debugging GC code recently. It is generally ok. These macros were basically the only places where I was forced into "printf debugging" mode.  Stepping around these and variable introspection is pretty bad. It would be nice to convert these macro into lambdas.  Not at the cost of performance of course.

---
In reply to: [495435666](https://github.com/dotnet/coreclr/pull/24754#issuecomment-495435666) [](ancestors = 495435666)

**Comment by davidwrighton** [comment]
Due to lack of improvements when this is done, I'm closing this PR.

**Pull request closed without merging**
