### PR TITLE
Fix jit warning.

### PR DESCRIPTION
**Pull request by erozenfeld**

### CODE REVIEW

**Comment by erozenfeld** [comment]
The warning is disabled in coreclr but causes a build break in desktop builds.

**Comment by erozenfeld** [comment]
@sandreenko @dotnet/jit-contrib PTAL

**Comment by erozenfeld** [comment]
@dotnet-bot test Windows_NT x64 Checked CoreFX Tests
@dotnet-bot test Windows_NT x64 Formatting

**Comment by CarolEidt** [comment]
@erozenfeld - The desktop build still fails with this change. It doesn't seem to have been mirrored yet, but after manually adding this fix the crossgen build complains about `lookup` being undefined.

**Comment by sandreenko** [comment]
I have restarted the mirror (there was a windows update there). it will be mirrored soon.

> after manually adding this fix the crossgen build complains about lookup being undefined.

about which one? 2 days ago this fix allowed me to build x64 checked at least.

**Comment by erozenfeld** [comment]
I also didn't see any warnings in desktop x64 checked build with this change.

**Comment by sandreenko** [comment]
The change was mirrored and I have checked that I can build x86/x64 (at least checked).
`00.30: Incremental build of clrjit completed.`

**Comment by erozenfeld** [comment]
The warning is in crossgen build and is reproducible by a full build. I'll create a fix PR shortly.

**Comment by erozenfeld** [comment]
#21623 fixes the crossgen warning.

**Pull request merged**
