### PR TITLE
Added missing JIT test V1-M15-SP2/b124443/b124443.cs

### PR DESCRIPTION
**Pull request by briansull**
This test was missing and I am adding it

### CODE REVIEW

**Comment by briansull** [comment]
@AndyAyersMS @mikedn @dotnet/jit-contrib PTAL

**Comment by mikedn** [comment]
It looks like this contains only the test itself. What about the IBC data or whatever makes it special?

**Comment by mikedn** [comment]
The IL included in the dumps you have provided seems to indicate that what makes this test special is the C# compiler and/or its compilation options. However, I tried various things (old C# compiler, using /debug:full) and still can't get the code you got in internal testing. Compiling the IL directly does generate code similar to what you have posted in the other PR:

Without the `Limit::vn` fix the IL code generates the same broken assembly code, without the range check:

```asm
G_M55886_IG01:
       4883EC28             sub      rsp, 40
G_M55886_IG02:
       48B9984435EFFB7F0000 mov      rcx, 0x7FFBEF354498
       BA04000000           mov      edx, 4
       E80812845F           call     CORINFO_HELP_NEWARR_1_VC
       33D2                 xor      edx, edx
       EB0D                 jmp      SHORT G_M55886_IG04
G_M55886_IG03:
       4863CA               movsxd   rcx, edx
       C744881001000000     mov      dword ptr [rax+4*rcx+16], 1
       FFC2                 inc      edx
G_M55886_IG04:
       83FA04               cmp      edx, 4
       0F9EC1               setle    cl
       0FB6C9               movzx    rcx, cl
       85C9                 test     ecx, ecx
       75E6                 jne      SHORT G_M55886_IG03
G_M55886_IG05:
       4883C428             add      rsp, 40
       C3                   ret
```

IL code in https://gist.github.com/mikedn/ca0d286c9a8aba9fd5e6987fbc93c745

**Comment by briansull** [comment]
Actually there was't any IBC data, that was from accidentally running this with  JitStress=1

**Comment by briansull** [comment]
@dotnet-bot Test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by briansull** [comment]
I have now added the IL version of this test as well.

**Pull request merged**
