### PR TITLE
Import additional JIT tests.

### PR DESCRIPTION
**Pull request by pgavlin**
Most of these tests were missed in the first round because they rely on
TypedReference.

### CODE REVIEW

**Comment by pgavlin** [comment]
@richardlford @hoyMS PTAL

**Comment by hoyMS** [comment]
There are two logs failing. Could you please take a look?

**Comment by pgavlin** [comment]
Added exclusions for the failing tests. These tests are failing because they need to directly reference mscorlib in order to use TypedReference. This leads to a reference to System.Console in mscorlib, which is not present on non-Windows platforms. Perhaps we should consider adding a test-only NuGet package that exposes TypedReference--if we did so, we could use NuGet as usual for these tests.

**Comment by hoyMS** [comment]
Still failing.

**Comment by hoyMS** [comment]
But looks unrelated to your change.

LGTM.

**Pull request merged**
