### PR TITLE
Delete unused tests\arm64\fails.testlist

### PR DESCRIPTION
**Pull request by sandreenko**
The original issue #9481 was closed long time ago.

### CODE REVIEW

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked r2r Build and Test

**Comment by sandreenko** [comment]
> This file is unused AFAIK. It could be removed.

Then how do we control what is excluded for arm64? `coreclr\tests\issues.targets` doesn't have arm64 section. 

Maybe all existing tests are passing now (looks unlikely)? I need to add several tests that are failing now, how can I do that?

cc @dotnet/arm64-contrib

**Comment by BruceForstall** [comment]
For Windows, `tests\arm64\Tests.lst`. For Linux, `tests\testsFailing.arm64.txt`.

**Comment by sandreenko** [comment]
PR was updated to delete this file.

**Pull request merged**
