### PR TITLE
Add debugger launch to dbgshim for xplat.

### PR DESCRIPTION
**Pull request by mikem8361**
Add the RegisterForRuntimeStartup/UnregisterForRuntimeStartup to dbghim. Executes
the callback when the coreclr runtime starts in the specified process. The callback
is passed the proper ICorDebug instance for the version of the runtime or an error if
something fails. This API works for launch and attach (and even the attach scenario
if the runtime hasn't been loaded yet) equally on both xplat and Windows. The callback
is always called on a separate thread. This API returns immediately.

The callback is invoke when the coreclr runtime module is loaded during early
initialization. The runtime is blocked during initialization until the callback
returns.

HRESULT
RegisterForRuntimeStartup(
    __in DWORD dwProcessId,
    __in PSTARTUP_CALLBACK pfnCallback,
    __in PVOID parameter,
    __out PVOID *ppUnregisterToken)

HRESULT
UnregisterForRuntimeStartup(
    __in PVOID pUnregisterToken)

Most of the work is done for xplat in the PAL_RegisterForRuntimeStartup and
PAL_UnregisterForRuntimeStartup. On Windows, the APIs are implemented on top
of the old dbgshim ones.

Added reference counting to DbgTransportSession so the cleanup can be done after
the transport worker and the main code is finished.

Fix a hang in OSX initializing multiple PALs in the debugging test dbg, dbgshim
and mscordaccore by not calling FILEInitStdHandles() from PAL_InitializeDLL.

Fixed a minor EnumerateCLRs bug in an error path. A ThrowHR instead of returning
the HRESULT.

Better pipe file/dbg transport cleanup. Now also call the dbg transport connection
abort for an unhandled native exception. Added PROCAbort to replace most calls to
abort(). The shutdown handler is called in PROCAbort().

Cleanup process code; remove now useless CProcSharedData.

Added "PROCESS" PAL trace type.

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
The test failure on Ubuntu is in JIT.RyuJIT.DoWhileBndChk, which seems to have been added yesterday. I see that it's failing on other PR's as well. @RussKeldorph can you take a look?

**Comment by mikem8361** [comment]
@noahfalk and @janvorli could you guys review this? Thanks.

**Comment by RussKeldorph** [comment]
@adityamandaleeka looking

**Comment by mikem8361** [comment]
@noahfalk can you review the CR feedback changes?

**Comment by noahfalk** [comment]
LGTM.

I'm not sure where the earlier review comments went to? I was going to follow up on the security comment I made last night. That comment is somewhat overstated... the risk for the startup API is that a malicious user could block other user's processes from continuing. The risk of using the debugger to maliciously do arbitrary things with other user's processes is in the transport which is separate and already checked in. In either case we agreed the debugger startup/transport needs some security review (and potentially additional work) before its truly done.

**Pull request merged**
