### PR TITLE
Port EventSource Nuget Package Changes

### PR DESCRIPTION
**Pull request by brianrob**
Several code changes have been made to the EventSource codebase in order to support producing the Microsoft.Diagnostics.Tracing.EventSource.Redist package.  This PR brings these changes back from CoreFx.

These changes are a combination of the shared source changes from https://github.com/dotnet/corefx/pull/24405 and https://github.com/dotnet/corefx/pull/24808.

Following this PR, we will start mirroring the shared source to CoreFx to avoid needing these manual port PRs.

### CODE REVIEW

**Comment by brianrob** [comment]
Should not be merged until https://github.com/dotnet/corert/pull/4786 is merged.

**Comment by brianrob** [comment]
@dotnet-bot test Ubuntu x64 corefx_baseline
@dotnet-bot test Windows_NT x64 corefx_baseline

**Comment by brianrob** [comment]
The Jit - CoreFx CI legs are broken, so I have run the System.Diagnostics.Tracing tests manually on my machine to confirm that they are passing.

**Comment by vancem** [comment]
LGTM

**Pull request merged**
