### PR TITLE
Add call to setup-stress-dependencies.sh to build-test.sh.

### PR DESCRIPTION
**Pull request by sandreenko**
I had to revert #23354 because of OSX failure.

This PR adds a condition not to initialize CoreDisTools on OSX.

### CODE REVIEW

**Comment by sandreenko** [comment]
cc @sbomer

**Comment by sandreenko** [comment]
@MattGal I canceled azure-pipelines runs yesterday near 7:30PM and then called `/Azp run coreclr-ci` hoping that it will rerun the testing. Looks like it did not want I wanted. Could you please say what is the right way to rerun stuck ADO jobs and rerun them here?

**Comment by MattGal** [comment]
@sandreenko we just came back online, I think you may have to close and reopen the PR to get it right (@mmitche ?)

**Comment by sandreenko** [comment]
@MattGal  thanks, looks like it helped. It did not restart `coreclr-ci (Test Pri0 OSX x64 checked) Cancelled after 240m — Test Pri0 OSX x64 checked was canceled ` but I am ok with that.

**Comment by sandreenko** [comment]
@MattGal @mmitche something is not right, several jobs are marked as cancelled:
`coreclr-ci (build OSX x64 Checked) Cancelled after 1m`,
`coreclr-ci (build OSX x64 Debug)` etc.

Maybe it is because I and @mmitche closed and reopened PR at the same moment?

>  sandreenko closed this 7 minutes ago 
>  sandreenko reopened this 7 minutes ago 
>  mmitche closed this 7 minutes ago 
>  mmitche reopened this 7 minutes ago

**Comment by sandreenko** [comment]
@dotnet-bot test Ubuntu arm Cross Checked crossgen_comparison Build and Test 
@dotnet-bot test Ubuntu arm Cross Release crossgen_comparison Build and Test

**Comment by sandreenko** [comment]
The wrong results are shown for this PR. I mean for ADO jobs details link goes to https://dev.azure.com/dnceng/public/_build/results?buildId=133842&view=results  that shows 
"The requested build 133842 could not be found.".
The actual results are here https://dev.azure.com/dnceng/public/_build/results?buildId=133844

cc @echesakov

**Comment by sandreenko** [comment]
I am going to merge this because the actual test run is clear.
There is failure in Test pri0 Linux_rhel6 x64 checked Job:
```
ERROR: An error occurred in /__w/2/s/.dotnet/dotnet msbuild /nologo /verbosity:minimal /clp:Summary /p:RestoreDefaultOptimizationDataPackage=false /p:PortableBuild=true /p:UsePartialNGENOptimization=false /maxcpucount /__w/2/s/tests/build.proj /flp:Verbosity=normal;LogFile=/__w/2/s/bin/Logs/Tests_Managed.Linux.x64.Checked.log;Append=true /flp1:WarningsOnly;LogFile=/__w/2/s/bin/Logs/Tests_Managed.Linux.x64.Checked.wrn;Append=true /flp2:ErrorsOnly;LogFile=/__w/2/s/bin/Logs/Tests_Managed.Linux.x64.Checked.err;Append=true /l:BinClashLogger,Tools/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log /p:__BuildArch=x64 /p:__BuildType=Checked /p:__BuildOS=Linux. Check logs under /__w/2/s.
Failed to build Managed tests build (build tests). See the build logs:
    /__w/2/s/bin/Logs/Tests_Managed.Linux.x64.Checked.log
```
but I do not think it was caused by this change.

**Pull request merged**
