### PR TITLE
Change CoreCLR to use Sierra

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by jkotas** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@jkotas the build didn't pass all the tests.  This check-in only tested it by copying from the 10.12 machine.  We need to move all of coreclr to 10.12 too.  I did a smoke test of full 10.12 and hit an issue in the PAL test.  Can you verify that those work on Sierra?

**Comment by jkotas** [comment]
Ok

> Can you verify that those work on Sierra?

I do not have MacBook with me. What is the PAL test failing with? Does everything else work?

**Comment by mmitche** [comment]
@jkotas Not sure, but it was the QueryPerformanceCounter test.

@dotnet-bot test ci please

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@jkotas Please see: https://ci.dot.net/job/dotnet_coreclr/job/master/job/GenPRTest/job/checked_osx10.12/1/

**Comment by jkotas** [comment]
> @jkotas Verified that the workflow completes if I disable the PAL test

Sounds good to me.

**Comment by jkotas** [comment]
I have opened https://github.com/dotnet/coreclr/issues/10209 to track the disabled test.

**Comment by mmitche** [comment]
@gkhanna79 Any objection here?

**Comment by gkhanna79** [comment]
OSX 10.12 is going to be the min OS for 2.0.0 - I am fine with this.

**Comment by gkhanna79** [comment]
What about corresponding changes for official builds @markwilkie @chcosta ?

**Comment by mmitche** [comment]
@gkhanna79 Good point, will add those changes.

**Comment by mmitche** [comment]
@gkhanna79 I know the changes to make that happen, though they happen in another repo.  That will go in as soon as we have this committed.

**Pull request merged**
