### PR TITLE
Fix Task so that RunContinuationsAsynchronously flag works with all continuations

### PR DESCRIPTION
**Pull request by AlfredoMS**
4.6 introduced a new flag in TaskContinuationOptions named RunContinuationsAsynchronously, that forces continuations to be run async.
However there is one type of continuations (derived from ITaskCompletionAction) that was not being affected by this flag. Commonly this means using Task.WhenAll/Task.WhenAny.

This fixes issue https://github.com/dotnet/coreclr/issues/2021

### CODE REVIEW

**Comment by AlfredoMS** [comment]
@stephentoub

**Comment by stephentoub** [comment]
LGTM.  Please also submit a PR to corefx to add tests.

**Comment by jam40jeff** [comment]
@stephentoub It looks as if the last 3 files you changed (in commit fa4c715) were never merged into master.  Was this intentional?

**Comment by stephentoub** [comment]
I'm not understanding the concern.  Which changes are missing?

**Comment by jam40jeff** [comment]
Sorry, that was my mistake.  I'm not sure what I was looking at, but I do see the expected changes. 
 (Specifically, I mistakenly thought something was missing from Stream.cs and made a bad assumption.)

**Pull request merged**
