### PR TITLE
ARM, SOS: Fix libsos.so load fail and changes for SOS to work with ARM-Linux

### PR DESCRIPTION
**Pull request by seanshpark**
This PR includes two patches so that SOS works for ARM-Linux with LLDB-3.8

1) ARM: Fix ARM-Linux in SOS with lldb
Fix ARM architecture type in SOS so that it works for ARM-Linux.
Before this patch, lldb stops with architecture not supported.
SOS ARM-Linux works with LLDB-3.8 and higher.
Actual SOS commands for ARM may need testing and fixing.

2) ARM, SOS: Fix fail to load libsos.so while debugging with lldb
Related issue: #4428
With minor fix for ARM compile in SOS

### CODE REVIEW

**Comment by seanshpark** [comment]
To test this patch, #4258, #4473 and #4456 also should be applied if not landed.
I used lldb-3.8 build from source and this is how I build CoreCLR.
```
sudo ROOTFS_DIR=/home/maxwell/zarm-rootfs-wily ./cross/build-rootfs.sh arm wily

ROOTFS_DIR=/home/maxwell/zarm-rootfs-wily \
LLVM_ARM_HOME=/home/maxwell/xp_seanrpi2/llvm/install-38.arm/llvm \
./build.sh arm cross skipmscorlib clang3.8 clean
```

**Comment by janvorli** [comment]
@mikem8361 - could you take a look please?

**Comment by mikem8361** [comment]
LGTM

**Comment by seanshpark** [comment]
@janvorli , @mikem8361 , is there anything else for this PR?

**Comment by mikem8361** [comment]
No.  It can be merged after the 2 commits are squashed.

**Pull request merged**
