### PR TITLE
[ARM] Implement BitPosition with arm-intrinsics

### PR DESCRIPTION
**Pull request by wateret**
Minor improvement for compiler.

### CODE REVIEW

**Comment by wateret** [comment]
JIT compile time is almost same as before, but there was a small size reduction in`libclrjit.so` (by 358 bytes).

```
-rw-rw-r-- 1 hanjoung hanjoung 2020902 Oct 26 17:09 libclrjit-a.so
-rw-rw-r-- 1 hanjoung hanjoung 2020544 Oct 26 17:09 libclrjit-b.so
```

**Comment by jkotas** [comment]
The Windows ARM build fails with `error C3861: '__builtin_arm_rbit': identifier not found`. This needs to be also undef `__GNUC__` or `__llvm__` ifdef.

**Comment by cmckinsey** [comment]
@pkukol /cc @dotnet/jit-contrib

**Comment by wateret** [comment]
@jkotas I added `__llvm__`, thanks.

**Pull request merged**
