### PR TITLE
Change non_virtual_calls_to_instance_methods test to non-il-sdk format

### PR DESCRIPTION
**Pull request by hoyosjs**
Branch 3.1 doesn't have the changes necessary to build ilproj using the SDK. PR #27868 ported a bug fix and added this test, so just use the old format.

### CODE REVIEW

**Comment by hoyosjs** [comment]
@jashook

**Review by jashook — APPROVED** [review]
Thank you for tracking this down

**Comment by mmitche** [comment]
Is this ready or are those other failures interestnig?

**Comment by hoyosjs** [comment]
Changing the test name as we hit max path by a large margin on windows queues

**Comment by jashook** [comment]
Opened https://github.com/dotnet/core-eng/issues/8370 as well.

**Comment by mmitche** [comment]
@hoyosjs Looks like maybe another issue has popped up here.

**Comment by hoyosjs** [comment]
@mmitche this is ready to merge whenever

**Pull request merged**
