### PR TITLE
Cross-bitness changes in value numbering

### PR DESCRIPTION
**Pull request by echesakovMSFT**
1. Changes in **src/jit/gentree.cpp** **src/jit/gentree.h** are replacing ssize_t with target_ssize_t in GenTree::ParseArrayAddress and GenTree::ParseArrayAddressWork and adding castings for gtIconVal to target_ssize_t. This is needed to get rid of compilation warnings.

2. Changes in **src/jit/valuenum.cpp** is using VNForHandle(addrValue, GTF_ICON_FTN_ADDR) instead of VNForPtrSizeIntCon for function address. As far as I understood, VNForPtrSizeIntCon should be left target-specific and used only for target IntPtr sized (non-relocatable) constants.

@briansull Can you please review this?

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@echesakovMSFT I don't think the closing/reopening is helping things.  I think we are just seeing large delays in processing.

**Comment by echesakovMSFT** [comment]
test Ubuntu x64 Formatting

**Comment by echesakovMSFT** [comment]
@dotnet-bot test Ubuntu x64 Formatting

**Comment by echesakovMSFT** [comment]
@dotnet/jit-contrib PTAL

**Comment by BruceForstall** [comment]
@echesakovMSFT should you remove the "WIP"?

**Comment by echesakovMSFT** [comment]
@BruceForstall Forgot to do this, thanks

**Comment by echesakovMSFT** [comment]
@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test
@dotnet-bot test Ubuntu arm Cross Checked no_tiered_compilation_innerloop Build and Test
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by echesakovMSFT** [comment]
**Windows_NT arm Cross Checked Innerloop Build and Test** and **Windows_NT arm64 Cross Checked Innerloop Build and Test** are known failures (#19853)

**Pull request merged**
