### PR TITLE
Remove code about testNativeBinDir in runtest.sh

### PR DESCRIPTION
**Pull request by YongseopKim**
Single quotes(' ') doesn't permit referencing var because $ is turned off.
Changes double quotes instead of single quotes.

### CODE REVIEW

**Comment by YongseopKim** [comment]
I din't know that I should write issue before commiting. Sorry for that. I'll write.

**Comment by adityamandaleeka** [comment]
Thanks @YongseopKim. The change looks fine, but looking at the history, it's been broken since last November: https://github.com/dotnet/coreclr/commit/69ea93da545052013c7c689bdac53aded6cd7b1d#diff-e99015da4fdea5ed8c0b58186a5e4b70

The fact that this hasn't caused test failures for tests using native libraries leads me to believe that this code may not be necessary (perhaps other parts of the system have since compensated for the fact that it doesn't do what it's supposed to). 

@wtgodbe Any ideas?

**Comment by lemmaa** [comment]
@YongseopKim, nice catch!

@adityamandaleeka, during ARM porting, we usually use the test sets built on WindowsNT.x64 platform for testing Linux.arm platform. In this situation, it makes effect on overlay composition, I think. :)

**Comment by wtgodbe** [comment]
Hmm, I'm not sure how we haven't been seeing failures before this... I did a local build/test, and as far as I can tell, we aren't copying any of the native components (.so files) from the Linux build of the tests, into the test folders from which the tests get run - so it seems like those tests should be failing. But, they aren't - see an example here (http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/checked_ubuntu_tst_prtest/3194/testReport/Interop.ArrayMarshalling.BoolArray/MarshalBoolArrayTest/MarshalBoolArrayTest/). I'm not sure why this would be the case

**Comment by wtgodbe** [comment]
Hmm - it looks like the .so files that we expect to be copied into the individual test folders (what the code in this PR's change should be doing) aren't being copied into the test folders, but they ARE being copied into coreoverlay (for example, I see libMarshalBoolArrayNative.so in my coreoverlay folder, but not in the folder for the MarshalBoolArray test). These must be getting copied to coreoverlay by some other part of runtest.sh and resolving the dependency that way.

**Comment by wtgodbe** [comment]
Yep, looks like these .so files also live at bin/Product/{os}.{arch}.{configuration}, so they get copied to coreoverlay here - https://github.com/YongseopKim/coreclr/blob/663e6974a76d3d571fc0572903e5607658f35d93/tests/runtest.sh#L377. So if I'm interpreting this right, the step that this PR is modifying is a redundant step. @adityam, do you read this the same way?

**Comment by YongseopKim** [comment]
@wtgodbe Hello. I don't understand one thing. The so files in code which I'll modify are for native unit tests. I think the so files which you mentioned are for coreclr cross-built, and the former so files & the latter so files are different.

**Comment by adityamandaleeka** [comment]
@YongseopKim I believe @wtgodbe is referring to the shared libraries used by test code that are dropped in bin/Product/{os}.{arch}.{configuration}/bin. As a side note, they probably shouldn't be under "Product" long term since they're unrelated to product code.

@wtgodbe I think the native binaries for a test or a group of tests should end up somewhere where they can only affect the test(s) they belong to. If these binaries are ending up in the common core overlay, that's wrong and should be changed.

**Comment by adityam** [comment]
Guys, could you please stop tagging me in these issues.

**Comment by wtgodbe** [comment]
This change should cause the native binaries for tests to end up in the right place (the test folder), but they'll also still be duplicated in coreoverlay, because they somehow wind up in bin/Product. So if we can figure out how they're getting there, we can stop that from happening. If you want I can take a look at that later today.

**Comment by adityamandaleeka** [comment]
@adityam sorry you're getting spammed... that must be annoying. You contributed a PR last year, so I guess you're on the list of collaborators for this repo. GitHub username autocompletion makes it easy for someone to accidentally mention you when they mean to address me.

You can try the [steps here](https://help.github.com/articles/removing-yourself-from-a-collaborator-s-repository/) to remove yourself from the list of collaborators on this repo. I'm not 100% sure, but I suspect that will stop the autocompletion from suggesting your handle.

**Comment by wtgodbe** [comment]
@dotnet-bot test this please.

**Comment by jyoungyun** [comment]
> This change should cause the native binaries for tests to end up in the right place (the test folder), but they'll also still be duplicated in coreoverlay, because they somehow wind up in bin/Product. 
I'm for @wtgodbe comments. :) @YongseopKim I think if we do not install the native binaries in the bin directory, we do not consider the duplicated files. You can see the detail in CMakeLists.txt file of native binaries. And we need consider one more thing about the target directory.  The native binaries should be located in the same place with executable binary. Currently the code makes a directory for the native binareis and copy to there.

**Comment by YongseopKim** [comment]
@jyoungyun I'll modify CMakeLists.txt files not to install so files to bin directory and others.

**Comment by YongseopKim** [comment]
I did
1) removing install so files into bin/ in CMakeLists.txt in tests/src/
2) copying so files into proper directories

**Comment by YongseopKim** [comment]
After applying this commit, you can see the process of copying the native test binaries. 

However one problem may be there. If you specify coreOverlayDir and testDir as options when you execute runtest.sh, you may expect to skip the process of copying the native binaries, but the process executes. 

I'd like you to tell me whether executing the copy process is right or not.

**Comment by lemmaa** [comment]
@YongseopKim IMHO, after long observation, keep `CMakeLists.txt` and remove whole duplicated lines `function copy_test_native_bin_to_test_root` from `runtest.sh` looks much simple and better solution than others. :)

**Comment by YongseopKim** [comment]
Remove function copy_test_native_bin_to_test_root which duplicates so files in testNativeBinDir and then, the option 'testNativeBinDir' doesn't need anymore.

Remove also code about the option testNativeBinDir.

**Comment by wtgodbe** [comment]
@YongseopKim we actually want to make sure that native test .so files _are_ getting copied into the test directories, and we want to _stop_ placing those .so files into bin/Product, and therefore to stop copying them into coreoverlay. I believe this change is doing the opposite of that - @adityamandaleeka what do you think?

**Comment by adityamandaleeka** [comment]
@wtgodbe Yes, I agree. The first step is to stop copying the native binaries into the overlay. They should only be dropped near the test(s) that need them. 

Also, yes, the test assets shouldn't end up in bin/Product when they're built. If that's orthogonal to the work needed for the above, then it doesn't need to be done right away.

**Comment by YongseopKim** [comment]
@wtgodbe @adityamandaleeka 

The reasons why I modified so are

1) If we stop copying the native binaries into the overlay and do dropping them into the tests, there will be too duplicated files in each test.

For example, JIT/jit64/mcc/interop tests need native binaries.
native_i0c.so is needed by mcc_i00, mcc_i01, mcc_i02, ..., and mcc_i87.
For them, the native_i0c.so file should be in all of tests(mcc_i00, mcc_i01, ...).
I think dropping so files in bin directory can protect us from the complexity of this dependency.

2) Also, we need to check which test needs a native binary, but can't know when the test compiles. So we should search this dependency(which a test native binary is needed by a test(*.exe)) when runtest.sh is executed. However, the way is just using grep with the test native binary name or find with the test native binary on Windows(xxx.dll). 

If you have any good idea or think I'm wrong, please to inform me. :)

**Comment by adityamandaleeka** [comment]
@YongseopKim 

> 1) If we stop copying the native binaries into the overlay and do dropping them into the tests, there will be too duplicated files in each test.

This is a valid point, but dumping everything into the overlay is not the right solution. In cases like this, one solution is to have a common directory (maybe located at the lowest common ancestor of all the tests that share a native library) where the shared components are dropped, which the tests can load from. Dropping everything in the overlay is messy and can cause problems if two or more tests have native components that are named the same but are actually different.

> 2) Also, we need to check which test needs a native binary, but can't know when the test compiles. So we should search this dependency(which a test native binary is needed by a test(*.exe)) when runtest.sh is executed. However, the way is just using 'grep' with the test native binary name or 'find' with the test native binary on Windows(xxx.dll).

This is pretty straightforward if the relative path to a native component (from the root of wherever these things end up after build) matches the relative path of the managed DLL(s) it's associated with). We specify the paths in the CMakeLists for each test, so we can put things where they need to go. Copying the native components into the test tree will make everything end up where it's needed.

I hope that answers your questions.

**Comment by adityamandaleeka** [comment]
BTW, I hope it doesn't sound like I'm telling _you_ to do this work or that it needs to be done today. I just think it should be done at some point.

**Comment by YongseopKim** [comment]
@adityamandaleeka sure, don't mind.

I just want to finish this PR well, and that's why I asked you.

I agree with you at this point. 
> Dropping everything in the overlay is messy and can cause problems if two or more tests have native components that are named the same but are actually different.

So, I'm preparing new patch-set according to your suggestion. Thank you, @adityamandaleeka.

**Comment by YongseopKim** [comment]
@adityamandaleeka I have a question.

You said,
> This is pretty straightforward if the relative path to a native component (from the root of wherever these things end up after build) matches the relative path of the managed DLL(s) it's associated with). We specify the paths in the CMakeLists for each test, so we can put things where they need to go. Copying the native components into the test tree will make everything end up where it's needed.

So, if the native components moves to somewhere such as $coreoverlay/native/ or $test_dir_which_has_testexe/native/ , I think the associated unit test source files should be modified to set proper path for the native component by pinvoke(or dllimport). 

For example, 
as-is)
`
[DllImport(Config.DllName, EntryPoint = "init_HFA01", CallingConvention = CallingConvention.StdCall)]
        public static extern void Init_HFA01(out HFA01 hfa);
`

to-be)
`
[DllImport(Config.DllName, EntryPoint = "native/init_HFA01", CallingConvention = CallingConvention.StdCall)]
        public static extern void Init_HFA01(out HFA01 hfa);
`

or
`
use SetDllDirectory() or Environment.SetEnvironmentVariable("PATH", path) in source files.
`

Is it your intention? If so, it may be heavy workload...

Dropping native components in all of tests which need them can be better way.

**Comment by adityamandaleeka** [comment]
@YongseopKim I haven't had time to look into this yet, but there are other things we can do without modifying the source code for the tests. For instance, I believe the infrastructure allows for specifying environment variables in the csproj files that will be set in the generated shell scripts prior to test execution. Specifying LD_LIBRARY_PATH in there might be a way to get multiple tests sharing a set of native components.

I'm currently in the middle of some other stuff, but when I have some downtime I can try to come up with a design for how to make this work for one project, which can then be used as the model for the rest.

BTW, since we're having a discussion unrelated to what this PR started as, my recommendation is to close the PR and open an issue (which can include a link to this thread) where we can continue this discussion/work. What do you think?

**Comment by YongseopKim** [comment]
Thank you @adityamandaleeka. This talking can keep going #6214 .

**Pull request closed without merging**
