### PR TITLE
Update CoreLib sources path and import runtime

### PR DESCRIPTION
**Pull request by ViktorHofer**
cc @jkotas as we just discussed offline.

### CODE REVIEW

**Comment by ViktorHofer** [comment]
Should I be concerned about the failing leg?

**Comment by jashook** [comment]
No, the state of the CI is pretty bad today. @jkoritzinsky is working on the rhel build.

**Comment by jashook** [comment]
https://github.com/dotnet/core-eng/issues/8277 will probably cause the arm and osx jobs to fail as well. As a heads up

**Comment by jashook** [comment]
https://github.com/dotnet/coreclr/issues/27231 for known issues.

**Pull request merged**
