### PR TITLE
Fix an assert condition in lowering.

### PR DESCRIPTION
**Pull request by pgavlin**
Tail calls via the tail call helper must live in GC-safe blocks. A block
is GC-safe if either it or all of its dominators are also GC-safe. If we
are not optimizing, we will not compute dominators, and will therfore
not mark blocks whose dominators are all GC-safe. When deciding whether
or not we need to make a block GC-safe during tail call morphing,
however, we allow a tail call in an unmarked block iff the entry block
is GC-safe, as the entry block trivially dominates every reachable
block. This change fixes an assert that was not allowing for a tail call
in a block that is not marked GC-safe where the entry block is marked
GC-safe.

### CODE REVIEW

**Comment by pgavlin** [comment]
@BruceForstall @adiaaida @dotnet/jit-contrib PTAL

Fixes VSO 280116.

**Comment by pgavlin** [comment]
Note that an alternative direction would be to mark all blocks in a function GC safe even when we are not optimizing if the entry block is marked GC safe.

**Comment by sivarv** [comment]
Looks good to me.

**Comment by adiaaida** [comment]
LGTM

**Pull request merged**
