### PR TITLE
Initial support of lldb-3.8 for libsosplugin

### PR DESCRIPTION
**Pull request by lucenticus**
This pull request enable support of lldb-3.8 for libsosplugin.so.
To build libsosplugin.so for arm you should  set LLVM_ARM_HOME variable like this:
LLVM_ARM_HOME=<path-to-llvm-for-arm> ./build.sh arm cross
If LLVM_ARM_HOME is not defined, then we use lldb-3.6.
Related to issue  #4264
@Dmitri-Botcharnikov,@kvochko, @seanshpark, please have a look

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
@mikem8361 PTAL

**Comment by mikem8361** [comment]
LGTM

**Comment by seanshpark** [comment]
@lucenticus , one minor thing. TABs and Spaces are mixed in the patch. Can you fix them?

**Comment by lucenticus** [comment]
@seanshpark, whitespaces were fixed, thanks!

**Comment by seanshpark** [comment]
LGTM

**Comment by Dmitri-Botcharnikov** [comment]
LGTM

**Comment by kvochko** [comment]
LGTM

**Comment by seanshpark** [comment]
@dotnet-bot test Windows_NT x86 please

**Comment by seanshpark** [comment]
@dotnet-bot test Windows_NT x86 Debug Legacy Backend Build and Test please

**Comment by seanshpark** [comment]
@lucenticus , #4258 landed and made a conflict to this PR. please resolve.

**Comment by lucenticus** [comment]
@seanshpark, done

**Comment by lucenticus** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by jkotas** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test  please

**Comment by lucenticus** [comment]
@jkotas, it seems that "Ubuntu x64 Checked Build and Test" fails. I don't understand the reason of the error, do I need fix something?

**Comment by seanshpark** [comment]
somewhere in the log...
```
11:47:19 FAILED   - JIT/SIMD/Sums_ro/Sums_ro.sh
11:47:19                BEGIN EXECUTION
11:47:19                /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun Sums_ro.exe
11:47:19                
11:47:19                Unhandled Exception: System.TypeInitializationException: The type initializer for 'System.Diagnostics.Stopwatch' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-profile-l1-1-0.dll': The specified module could not be found.
11:47:19                 (Exception from HRESULT: 0x8007007E)
11:47:19                   at Interop.mincore.QueryPerformanceFrequency(Int64& value)
11:47:19                   at System.Diagnostics.Stopwatch..cctor()
11:47:19                   --- End of inner exception stack trace ---
11:47:19                   at VectorMathTests.Program.Main(String[] args)
11:47:19                ./Sums_ro.sh: line 62: 19019 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" Sums_ro.exe $CLRTestExecutionArguments $Host_Args
```

`Unable to load DLL 'api-ms-win-core-profile-l1-1-0.dll': The specified module could not be found.`

I think it's CI problem, Linux asking for Windows DLL.

**Comment by lucenticus** [comment]
@seanshpark, Ok, thank you for clarification

**Comment by jkotas** [comment]
Right - the Ubuntu failures are not related to your change.

**Comment by jkotas** [comment]
Thanks!

**Comment by lucenticus** [comment]
Thank you!

**Pull request merged**
