### PR TITLE
Fix for JitStress test failures

### LINKED ISSUE #10461: Assertion failed 'firstILBlock->hasProfileWeight()'
**Repro (of many)**
x64 checked
set COMPlus_JitStress=2
run coreclr tests

**Example CI run**
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_jitstress2/124/

**Sample output**
```
D:\j\workspace\x64_checked_w---8a0029a8\bin\tests\Windows_NT.x64.Checked\TestWrappers\JIT.Directed\JIT.Directed.XUnitWrapper.cs(21527): error : JIT_Directed._nullabletypes_castclassinterface_r_castclassinterface_r_._nullabletypes_castclassinterface_r_castclassinterface_r_cmd [FAIL] [D:\j\workspace\x64_checked_w---8a0029a8\tests\runtest.proj]
        
        Assert failure(PID 3148 [0x00000c4c], Thread: 3532 [0x0dcc]): Assertion failed 'firstILBlock->hasProfileWeight()' in 'NullableTest5:BoxUnboxToNQ(ref):bool' (IL size 46)
        
            File: d:\j\workspace\x64_checked_w---8a0029a8\src\jit\flowgraph.cpp Line: 12704
            Image: D:\j\workspace\x64_checked_w---8a0029a8\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe
```

### PR DESCRIPTION
**Pull request by briansull**
Fixes #10461 - Assertion failed 'firstILBlock->hasProfileWeight()'

### CODE REVIEW

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT Jitstress2
@dotnet-bot test Ubuntu Jitstress2

**Comment by briansull** [comment]
@dotnet/jit-contrib PTAL

**Comment by AndyAyersMS** [comment]
Do we ever go back and add weights to all the skipped internal blocks? Looks like we only do it for the first one.

Also it seems odd to me that there is an odd mixture of predicates here -- seems like the initial `if` should check the internal flag and then, inside the if, you could assert that when this first block is internal it is also scratch.

**Comment by briansull** [comment]
I believe that the weights for the first and other internal blocks have already been added and we don't really need the code here that sets the profile weight at all.  

I'm not trying to fix everything that might be incorrect with this checkin, just getting the JIT-CI unblocked.

Currently there are several cases where the weight don't get set properly 
and these cases cause us to fail when calculating the edge weights.

We still use the the profile weights that we have and there aren't any correctness issues that are exposed by having incorrect weights.

**Comment by briansull** [comment]
I'm also going to have to investigate the remaining couple of JitStress=2 failures
Where the inserted blocks aren't BBJ_NONE.

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT Jitstress2
@dotnet-bot test Ubuntu Jitstress2

**Comment by briansull** [comment]
Passes JitStress=2

**Pull request merged**
