### PR TITLE
Add support for ninja to the CoreCLR build.

### PR DESCRIPTION
**Pull request by pgavlin**
Just what it says on the tin.

### CODE REVIEW

**Comment by pgavlin** [comment]
@mmitche PTAL

**Comment by janvorli** [comment]
@pgavlin Just curious - what is the benefit of using ninja compared to the standard make files?

**Comment by pgavlin** [comment]
Anectodally (i.e. on my 4-core laptop), ninja saves ~2 minutes during the build through better parallelization.

**Comment by mmitche** [comment]
LGTM

**Comment by pgavlin** [comment]
Also, ninja appears to be quite a bit faster for incremental builds.

**Pull request merged**
