### PR TITLE
Revert "Fix bracket expression matches a character at gawk"

### PR DESCRIPTION
**Pull request by jkotas**
Reverts dotnet/coreclr#3943

### CODE REVIEW

**Comment by jkotas** [comment]
@leemgs  I am sorry but I have to revert this change. It is breaking build on Ubuntu 14.04:

```
Linking CXX shared library libcoreclr.so
/usr/bin/ld:/root/coreclr/bin/obj/Linux.x64.Release/src/dlls/mscoree/coreclr/coreclr.exports:3: syntax error in VERSION script
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jkotas** [comment]
The first couple of lines of the bad `coreclr.exports` looks like this:

```
V1.0 {
    global:
        ; Unix hosting API;
        coreclr_create_delegate;
```

**Comment by leemgs** [comment]
@jkotas , You are welcome. I will check log of CI. For reference, I had checked build test on my own Ubuntu 14.04 x64 PC before submitting the PR to prevent a regression. 

Here is my self test case. For example, 
```
a. native-build for X64
    ./build.sh debug
    ./build.sh release
b. cross-build for Linux/ARM
    time ROOTFS_DIR=/work/dotnet/rootfs-coreclr/arm ./build.sh arm debug   clean cross skiptests
    time ROOTFS_DIR=/work/dotnet/rootfs-coreclr/arm ./build.sh arm release clean cross skiptests 
```

**Comment by leemgs** [comment]
@jkotas , Here is my self test result on my `Ubuntu 14.04 X64 PC`. No build-break. Could you add a person that is in charge of the CI about this issue with `\CC`? 


```

invain@target:/work/dotnet/arm32/coreclr$ ./build.sh debug  skiptests skipmscorlib

    . . . OMISSION  . . . 
Skipping building mscorlib.
Unable to generate Microsoft.NETCore.Runtime.CoreCLR nuget package since mscorlib was not built.
Repo successfully built.
Product binaries are available at /work/dotnet/arm32/coreclr/bin/Product/Linux.x64.Release


invain@target:/work/dotnet/arm32/coreclr$ ./build.sh release  skiptests skipmscorlib

    . . . OMISSION  . . . 
Skipping building mscorlib.
Unable to generate Microsoft.NETCore.Runtime.CoreCLR nuget package since mscorlib was not built.
Repo successfully built.
Product binaries are available at /work/dotnet/arm32/coreclr/bin/Product/Linux.x64.Release
```

Below is version information of my Ubuntu PC. 
```
invain@target:/work/dotnet/arm32/coreclr$ 
invain@target:/work/dotnet/arm32/coreclr$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
invain@target:/work/dotnet/arm32/coreclr$ 
invain@target:/work/dotnet/arm32/coreclr$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
invain@target:/work/dotnet/arm32/coreclr$ 

```

**Comment by jkotas** [comment]
@chcosta runs the daily builds machines that hit this.

@leemgs What are the first couple of lines in `coreclr.exports` file on your system? What is the clang version that you are using?

**Comment by leemgs** [comment]
> @leemgs What are the first couple of lines in coreclr.exports file on your system? What is the clang version that you are using?

Below is the first couple of lines in `coreclr.exports` and the clang version on my Ubuntu 14.04 X64 PC. 

```
leemgs@u14.04:/work/dotnet/arm32/coreclr$ 
leemgs@u14.04:/work/dotnet/arm32/coreclr$  clang
clang++-3.5                   clang-check-3.5               clang-tidy-3.5
clang-3.5                     clang-query-3.5               
clang-apply-replacements-3.5  clang-tblgen-3.5              
invain@target:/work/dotnet/arm32/coreclr$ dpkg -l | grep clang
ii  clang-3.5                                                   1:3.5-4ubuntu2~trusty2                              amd64        C, C++ and Objective-C compiler (LLVM based)
ii  libclang-common-3.5-dev                                     1:3.5-4ubuntu2~trusty2                              amd64        clang library - Common development package
ii  libclang1-3.5:amd64                                         1:3.5-4ubuntu2~trusty2                              amd64        C interface to the clang library
leemgs@u14.04:/work/dotnet/arm32/coreclr$ 
leemgs@u14.04:/work/dotnet/arm32/coreclr$ 

```


leemgs@u14.04:/work/dotnet/arm32/coreclr$ cat ./bin/obj/Linux.x64.Debug/src/dlls/mscoree/coreclr/coreclr.exports
```
V1.0 {
    global:
        coreclr_create_delegate;
        coreclr_execute_assembly;
        coreclr_initialize;
        coreclr_shutdown;
        MetaDataGetDispenser;
        GetMetaDataInternalInterface;
        GetMetaDataInternalInterfaceFromPublic;
        GetMetaDataPublicInterfaceFromInternal;
        ExecuteAssembly;
        PAL_RegisterModule;
        PAL_UnregisterModule;
        CoreDllMain;
        DllMain;
        GetCLRRuntimeHost;
            . . . BELOW OMISSION . . . . 

```



leemgs@u14.04:/work/dotnet/arm32/coreclr$ cat ./bin/obj/Linux.x64.Release/src/dlls/mscoree/coreclr/coreclr.exports
```
V1.0 {
    global:
        coreclr_create_delegate;
        coreclr_execute_assembly;
        coreclr_initialize;
        coreclr_shutdown;
        MetaDataGetDispenser;
        GetMetaDataInternalInterface;
        GetMetaDataInternalInterfaceFromPublic;
        GetMetaDataPublicInterfaceFromInternal;
        ExecuteAssembly;
        PAL_RegisterModule;
        PAL_UnregisterModule;
        CoreDllMain;
        DllMain;
        GetCLRRuntimeHost;
        CloseHandle;
        CoCreateGuid;
        CopyFileW;
        CoTaskMemAlloc;
        CoTaskMemRealloc;
        CoTaskMemFree;
            . . . BELOW OMISSION . . . . 
```



leemgs@u14.04:/work/dotnet/arm32/coreclr$ cat ./bin/obj/Linux.arm.Release/src/dlls/mscoree/coreclr/coreclr.exports
```
V1.0 {
    global:
        coreclr_create_delegate;
        coreclr_execute_assembly;
        coreclr_initialize;
        coreclr_shutdown;
        MetaDataGetDispenser;
        GetMetaDataInternalInterface;
        GetMetaDataInternalInterfaceFromPublic;
        GetMetaDataPublicInterfaceFromInternal;
        ExecuteAssembly;
        PAL_RegisterModule;
        PAL_UnregisterModule;
        CoreDllMain;
        DllMain;
        GetCLRRuntimeHost;
        CloseHandle;
        CoCreateGuid;
        CopyFileW;
        CoTaskMemAlloc;
        CoTaskMemRealloc;
        CoTaskMemFree;
        CreateDirectoryW;
        CreateEventW;
        CreateFileW;
        CreateMutexW;
        CreateSemaphoreW;
            . . . BELOW OMISSION . . . . 

```

**Comment by jkotas** [comment]
The `; Unix hosting API;` line - that is causing the break - is missing in your case. So maybe it is caused by different awk versions?

**Comment by leemgs** [comment]
> So maybe it is caused by different awk versions?

Yes. it is caused by different awk versions. 
The gawk version that is installed on my ubuntu 14.04 x64, is `4.0.1`. 

```
invain@target:~$ dpkg -l | grep gawk
ii  gawk                                                        1:4.0.1+dfsg-2.1ubuntu2                             amd64        GNU awk, a pattern scanning and processing language
invain@target:~$ 
invain@target:~$ gawk --version
GNU Awk 4.0.1
Copyright (C) 1989, 1991-2012 Free Software Foundation.
```

I think that we need to make exception handling at `function(generate_exports_file ......)`.  I will make next PR if you agree. 

[./coreclr/CMakeLists.txt]
```
    241 function(generate_exports_file inputFilename outputFilename)
    242 
    243   if(CMAKE_SYSTEM_NAME STREQUAL Darwin)
    244     set(AWK_SCRIPT generateexportedsymbols.awk)
    245   else()
    246     set(AWK_SCRIPT generateversionscript.awk)
    247   endif(CMAKE_SYSTEM_NAME STREQUAL Darwin)
    248 

```

**Comment by jkotas** [comment]
Is it possible to fix the awk script such that it works fine on either version?

**Comment by leemgs** [comment]
Yes. I think so. I will submit a PR after making 'awk version of Linux distribution'-aware patch.

**Comment by janvorli** [comment]
@leemgs I can see that by default, the AWK used on Ubuntu is "mawk", so the difference likely stems from that. You can try to change the ```^[:space:]``` to ```\S``` (note the S is uppercase). This is another way to express "not space" and this works in the mawk on Ubuntu.

**Comment by janvorli** [comment]
Actually, I have found that the mawk we use on Ubuntu is version 1.3.3 and that version doesn't support character classes (like ```[:space:]```) at all. So it matches the comments just because it considers ```[:space:]``` as "any of :, s, p, a, c, e" and since all comments start at the beginning of the line and the ```[:space:]``` has the ```*``` which means zero or more of those, it matches the comment.
So it looks like the ```\S``` I've suggested is the most compatible solution.

**Comment by leemgs** [comment]
@janvorli , Thank you for sharing mawk version 1.3.3 on your Ubuntu. BTW, Which Ubuntu version did you use for the version 1.3.3? In my own Ubuntu 14.04 64x PC, two awks are installed such as gawk and mawk. It seems that the default awk is "GNU Awk 4.0.1". 

[Below is awk software on my Ubuntu 14.04 X64]
```
invain@u1404:~$ dpkg -l |grep awk
ii  gawk                                                        1:4.0.1+dfsg-2.1ubuntu2                             amd64        GNU awk, a pattern scanning and processing language
ii  mawk                                                        1.3.3-17ubuntu2                                     amd64        a pattern scanning and text processing language
invain@u1404:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
invain@u1404:~$ 

```

There are a lot of different AWK software (e.g. awk, gawk, bwk, mawk, awka, tawk, xgawk, etc) and versions among Linux distributions. If we can, Let's make an effort to aware different awk name and version. I will try make a patch and send a PR for review.
* https://en.wikipedia.org/wiki/AWK#Versions_and_implementations

**Pull request merged**
