### PR TITLE
Port to Release: Add some extra checks to BinaryReader/Writer buffers

### PR DESCRIPTION
**Pull request by ianhays**
master PR: https://github.com/dotnet/coreclr/pull/7778
resolves https://github.com/dotnet/corefx/issues/12837#
@gkhanna79

### CODE REVIEW

**Comment by gkhanna79** [comment]
@weshaggard Can you please review this change?

**Comment by weshaggard** [comment]
LGTM

**Comment by ianhays** [comment]
@gkhanna79 need another shiproom mail for this one?

**Comment by gkhanna79** [comment]
@ianhays yes.

**Comment by ianhays** [comment]
@gkhanna79 email sent. This PR is good to merge whenever it makes its way through shiproom.

**Pull request merged**
