### PR TITLE
Pr fix lldb regression typo

### PR DESCRIPTION
**Pull request by sdmaclea**
@janvorli 
@gkhanna79

### CODE REVIEW

**Comment by sdmaclea** [comment]
Diff against the head before my original change on my local tree,
```
git diff 94d1639d5d0b969489abbb3ce78b11a72c4493c4..HEAD -- cross/build-rootfs.shdiff --git a/cross/build-rootfs.sh b/cross/build-rootfs.sh
index 6b4d184..4b695ab 100755
--- a/cross/build-rootfs.sh
+++ b/cross/build-rootfs.sh
@@ -5,7 +5,7 @@ usage()
     echo "Usage: $0 [BuildArch] [LinuxCodeName] [lldbx.y] [--skipunmount]"
     echo "BuildArch can be: arm(default), armel, arm64, x86"
     echo "LinuxCodeName - optional, Code name for Linux, can be: trusty(default), vivid, wily, xenial. If BuildArch is armel, LinuxCodeName is jessie(default) or tizen."
-    echo "lldbx.y - optional, LLDB version, can be: lldb3.6(default), lldb3.8"
+    echo "lldbx.y - optional, LLDB version, can be: lldb3.6(default), lldb3.8, no-lldb"
     echo "--skipunmount - optional, will skip the unmount of rootfs folder."
     exit 1
 }
@@ -70,6 +70,9 @@ for i in "$@" ; do
         lldb3.8)
             __LLDB_Package="lldb-3.8-dev"
             ;;
+        no-lldb)
+            unset __LLDB_Package
+            ;;
         vivid)
             if [ "$__LinuxCodeName" != "jessie" ]; then
                 __LinuxCodeName=vivid
```

**Comment by janvorli** [comment]
@gkhanna79 there seems to be some problem with nuget packages, half of the CI runs here have failed with errors like this:
```
05:37:35   Errors in D:\j\workspace\debug_windows---17180f1b\tests\src\Common\build_against_pkg_dependencies\project.json
05:37:35       Unable to resolve 'runtime.osx.10.10-x64.Microsoft.NETCore.TestHost (>= 2.0.0-beta-25015-04)' for '.NETCoreApp,Version=v1.1 (osx.10.10-x64)'.
05:37:35       Unable to resolve 'runtime.osx.10.10-x64.Microsoft.NETCore.Runtime.CoreCLR (>= 2.0.0-beta-25015-04)' for '.NETCoreApp,Version=v1.1 (osx.10.10-x64)'.
05:37:35       Unable to resolve 'runtime.ubuntu.14.04-x64.Microsoft.NETCore.Runtime.CoreCLR (>= 2.0.0-beta-25015-04)' for '.NETCoreApp,Version=v1.1 (ubuntu.14.04-x64)'.
05:37:35       Unable to resolve 'runtime.ubuntu.14.04-x64.Microsoft.NETCore.TestHost (>= 2.0.0-beta-25015-04)' for '.NETCoreApp,Version=v1.1 (ubuntu.14.04-x64)'.
05:37:35 
```

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
Arm64 PR again failed due to the following:

Failure to restore a package: Unable to resolve 'runtime.win7-arm.Microsoft.NETCore.CoreDisTools (>= 1.0.1-prerelease)' for 'DNXCore,Version=v5.0'.

@RussKeldorph @swaroop-sridhar Can you PTAL? Also, Win7-arm is incorrect RID since Win7 never supported ARM.

CC @wtgodbe

**Comment by RussKeldorph** [comment]
@gkhanna79 The coredistools failure is non-fatal.  The actual errors are at the bottom of the output.  Agree we should fix the output in this case, but it's not blocking.

**Comment by gkhanna79** [comment]
This is broken due to myget issues. I am merging this since change looks good and is not excercised in CI.

**Pull request merged**
