### PR TITLE
Add a option to exclude libSystem.Globalization.Native.a from artifacts

### PR DESCRIPTION
**Pull request by parjong**
As discussed in #11997, libSystem.Globalization.Native.a is necessary for Core RT, but not necessary for CLR. 

This commit adds a build option to exclude libSystem.Globalization.Native.a from CLR artifacts. This commit does not change default behavior.

### CODE REVIEW

**Comment by parjong** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test please

**Comment by janvorli** [comment]
@parjong why is the fact that we build the library a problem for you?
CC: @gkhanna79

**Comment by parjong** [comment]
I just want to slightly reduce the size of binaries (about 700Kb?). Actually, this commit does not prevent build, it just prevent installation.

**Comment by jkotas** [comment]
The actual content of the installation is controlled by the content of the nuget packages. This file is not packaged into CoreCLR nuget package. The extra files in binaries directory should not matter.

Why does the size of files in binaries directory matter to you?

**Comment by parjong** [comment]
We are currently integrating .NET Core into Tizen which uses its own build/package system. That system does not use NuGet packages, and accesses these binaries directly (that is why I proposed this PR at first).

However, @jyoungyun confirms that there is a manually managed list of files to be included in the package, and thus this change is not necessary.

**Pull request closed without merging**
