### PR TITLE
Restore concurrent GC for non-Windows AMD64 platforms

### PR DESCRIPTION
**Pull request by swgillespie**
When a number of feature definitions were moved from `CMakeLists.txt` to `clrdefinitions.cmake` recently, it looks like `FEATURE_USE_SOFTWARE_WRITE_WATCH_FOR_GC_HEAP` didn't make it. This had the effect of disabling concurrent GC across non-Windows platforms. This PR restores the definition to what it was before. It looks to me that this was the only define that got left behind with the move to `clrdefinitions.cmake`. 

This fixes two test failures in the long running GC CI job.

cc @sergiy-k @Maoni0 @kouvel

### CODE REVIEW

**Comment by swgillespie** [comment]
@dotnet-bot test Ubuntu x64 Release longgc
@dotnet-bot test OSX x64 Release longgc

**Comment by swgillespie** [comment]
@dotnet-bot test Ubuntu Release longgc
@dotnet-bot test OSX Release longgc

**Comment by Maoni0** [comment]
👍

**Comment by sergiy-k** [comment]
LGTM. Thank you!

**Comment by kouvel** [comment]
LGTM, thanks!

**Comment by swgillespie** [comment]
It looks like I broke the long-running GC CI job with my changes to runtest.sh yesterday, I'll look into that.

**Pull request merged**
