### PR TITLE
Disable Build number for Preview1

### PR DESCRIPTION
**Pull request by gkhanna79**
Disable build number in packages for Preview1 build.

@weshaggard PTAL.

CC @Petermarcu

### CODE REVIEW

**Comment by gkhanna79** [comment]
@Petermarcu Can this be merged so that we can get Preview1 packages out?

CC @weshaggard @leecow

**Comment by gkhanna79** [comment]
@Petermarcu Can I merge this and get the build going?

**Comment by Petermarcu** [comment]
No, we're going to discuss today to decide if we're ready for our final build.

**Comment by weshaggard** [comment]
Decided not to do this.

**Pull request closed without merging**
