### PR TITLE
Fix region info test on Debian

### PR DESCRIPTION
**Pull request by wtgodbe**
CC @ellismg (Is this what you had in mind?)

### CODE REVIEW

**Comment by wtgodbe** [comment]
@dotnet-bot test Debian8.2 pri1

**Comment by wtgodbe** [comment]
test Debian8.4 pri1

**Comment by wtgodbe** [comment]
Looks like something that just got merged in is causing these build breaks (I'm seeing the same thing in other PRs) - will investigate

**Comment by wtgodbe** [comment]
@dotnet-bot test this please

**Comment by ellismg** [comment]
I don't actually know if this is going to work or not, because I am not sure if the variables set by Environment.SetEnvironmentVarbile will be seen by the native shim that actually computes this stuff.

I would just modify the netci.groovy such that we do export LANG="en_US.UTF-8" before doing any work or possibly modify [runtest.sh](https://github.com/dotnet/coreclr/blob/master/tests/runtest.sh) to do this.  That's what we did in [CoreFX's run-test script](https://github.com/dotnet/corefx/blob/master/run-test.sh#L388).

**Comment by wtgodbe** [comment]
@dotnet-bot test Debian8.4 pri1

**Comment by jkotas** [comment]
All globalization tests should be in corefx. If we have globalization tests in CoreCLR repo that require special treatment like this, we should delete them instead.

**Comment by sergiy-k** [comment]
Yes

**Comment by wtgodbe** [comment]
Changed to delete the test instead.

**Comment by sergiy-k** [comment]
LGTM

**Comment by jkotas** [comment]
👍

**Pull request merged**
