### PR TITLE
Stop forcing jumpstamp nops in ngen images

### PR DESCRIPTION
**Pull request by briansull**

### CODE REVIEW

**Comment by briansull** [comment]
@kouvel @davidma @noahfalk PTAL

**Comment by noahfalk** [comment]
This change looks straightforward, I think the issue is just whether @davmason and @kouvel have made appropriate runtime changes so that we aren't relying on the JumpStamps any longer.

**Comment by davmason** [comment]
This change as is will cause issues with profiler rejit (I think this is expected based on our previous conversation).

In the current logic precode versioning is tied directly to tiered compilation. So any methods that are not tiered compilation eligible but are rejit eligible will blindly use a jumpstamp even though the padding is no longer there. I verified this occurs by taking this change, adding an assert that the method isn't part of a R2R module right before we actually do the jumpstamp in the rejit path. The assert is hit when running rejit tests.

Based on the previous conversation with @noahfalk I believe it is safe to start using precode versioning more broadly than tiering (i.e. for any rejit eligible methods), but that work hasn't happened.

**Comment by kouvel** [comment]
Yes, I believe other changes are necessary along with removing nops and jump stamps. The changes suggested in https://github.com/dotnet/coreclr/pull/24838#issuecomment-501879398 may be sufficient and would need to be verified.

**Comment by briansull** [comment]
I had all of the profiler tests run on this change and there weren't any failures.

**Comment by davmason** [comment]
> I had all of the profiler tests run on this change and there weren't any failures.
> 
> But it is possible that they were just "bllindly using a jumpstamp even though the padding is no longer there. "

That is what is happening. As long as the method is long enough for a jumpstamp and we don't happen to suspend the runtime with a thread in the middle of a location we jumpstamp over it won't cause failures. Nothing in the tests or product currently check if the jumpstamp is legal, we just assume if it is NGEN/R2R then it has jumpstamp padding.
 
> Seems like the checked version should check that we are overwriting the expected Nop, instead of just doing it blindly.

I agree we should be doing that now. I have a very simple form of that I used for running the tests here: https://github.com/davmason/coreclr/commit/57ad0d882fb5d4350198b7c0cbd66b92aa535a54. It would be better to have a more sophisticated check, although I suspect where we'll end up is that jumpstamps will be removed entirely from rejit (and I think the product as a whole since I don't believe anyone else uses them) unless there is a type of method that precode versioning can't handle. If we get rid of jumpstamps entirely then it becomes moot.

**Pull request closed without merging**
