### PR TITLE
[Arm64] Set compFloatingPointUsed for SIMD HWIntrincsics

### PR DESCRIPTION
**Pull request by sdmaclea**

### CODE REVIEW

**Comment by CarolEidt** [comment]
I'm not sure that this takes care of all cases - specifically the Crypto assertion failure, since AFAICT, `simdType` would not be set for that node, but it does require an internal float register.

**Review by briansull — APPROVED** [review]
Looks Good

**Review by CarolEidt — APPROVED** [review]
LGTM - thanks!

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by CarolEidt** [comment]
@jashook @BruceForstall - any idea what's going on with the arm64 testing? I restarted it after it seemed that the ci system was back up, but there are two outstanding jobs that have been going for >15 hours.

**Pull request merged**
