### PR TITLE
Get rid of codegenlinear.h and x86_instrs.h 

### PR DESCRIPTION
**Pull request by mikedn**
These files don't serve any purpose. `codegenlinear.h` also seems to confuse VS's Intellisense.

### CODE REVIEW

**Comment by mikedn** [comment]
Windows_NT x86 min_opt ryujit CoreCLR Perf Tests Correctness appears to have simply hung while building the tests:
```
10:46:31 CSC : warning CS1685: The predefined type 'MarshalByRefObject' is defined in multiple assemblies in the global alias; using definition from 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [D:\j\w\perf_perflab_---6af0d14a\tests\src\tracing\eventsource\eventsourcetrace\eventsourcetrace.csproj]
10:46:31   eventsourcetrace -> D:\j\w\perf_perflab_---6af0d14a\bin\tests\Windows_NT.x86.Release\tracing\eventsource\eventsourcetrace\eventsourcetrace\eventsourcetrace.exe
13:46:01 
Build timed out (after 240 minutes). Marking the build as aborted.
13:46:01 
Build was aborted
```
@dotnet-bot test Windows_NT x86 min_opt ryujit CoreCLR Perf Tests Correctness

**Comment by mikedn** [comment]
The test failure in https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_osx10.12_corefx_innerloop_prtest/801/ seems a bit suspect. But the test itself didn't fail but rather failed to connect to a socket, perhaps it's a timing issue. Anyway, this change is very unlikely to cause issues.

@dotnet-bot  test OSX10.12 x64 Checked CoreFX Tests

**Comment by mikedn** [comment]
OSX10.12 x64 Checked CoreFX Tests failed again with "Could not restore build tools correctly."...

@dotnet/jit-contrib Could someone please take a look at this simple cleanup change? The codegenlinear.h file is a leftover from the legacy backend days and it confuses VS's Go To Definition/Declaration functionality.

**Comment by CarolEidt** [comment]
I like this cleanup and, now that we've eliminated the legacy backend it might be nice to do a little more cleanup (e.g. codegenlinear.cpp might now be renamed to codegen.cpp, though I'm not sure how badly that will mess up peoples' ability to look at history.

**Comment by tannergooding** [comment]
> though I'm not sure how badly that will mess up peoples' ability to look at history.

Provided you have a commit where the only change you make is renaming the file, Git should probably track that as a rename (GitHub still has issues displaying this info in its own history view, however).

**Comment by mikedn** [comment]
> I like this cleanup and, now that we've eliminated the legacy backend it might be nice to do a little more cleanup

Yes, there's a lot of cleanup that can be done and the value varies a lot. Getting rid of a separate header for some of the members of the calls seems reasonable because such a split is unusual in C++. Renaming a file when the name is not totally wrong is a bit on the "meh" side. Getting rid of `GT_ASG` would be awesome as it's likely to have many positive implications and very few negative ones, too bad that it's a ton of work...

> I looked once at getting rid of INS_lea in arm/arm64 entirely, but it wasn't trivial, and wasn't clear it would be valuable in the end.

I don't think I checked to see how INS_lea is actually used on ARM. But I know that ARM has problems with lea/address mode formation so probably that's more useful to look at. Even x86 has some problems with `lea`...

Thanks for review!

**Pull request merged**
