### PR TITLE
[x86/Linux] Use Portable SHIFT JIT Helpers

### PR DESCRIPTION
**Pull request by parjong**
This commit enables portable SHFIT JIT Helpers for x86/Linux.

### CODE REVIEW

**Comment by parjong** [comment]
\CC @seanshpark

**Comment by jkotas** [comment]
This won't work for x86. These JIT helpers have custom calling convention on x86. They have to be implemented in assembly on x86.

The alternative would be to change the JIT, but it is more complex change and it would introduce divergence between x86 Windows and x86 Unix codegen. We may end up with some divergence between x86 Windows and x86 Unix codegen, but it would be good idea to minimize it.

**Comment by parjong** [comment]
@jkotas Is it same for all the other JIT helpers?

**Comment by jkotas** [comment]
The custom calling convention applies only for the shift helpers that you are touching in this PR.

**Comment by parjong** [comment]
@jkotas Thank you for comment!

**Pull request closed without merging**
