### PR TITLE
Disable the 'trim_trailing_whitespace' fixes issue 225

### LINKED ISSUE #225: Disable the 'trim_trailing_whitespace' setting from .editorconfig

### PR DESCRIPTION
**Pull request by shahid-pk**
fixes #225

### CODE REVIEW

**Comment by KindDragon** [comment]
Better remove thsi line and comment `# Trim trailing whitespace`

**Comment by shahid-pk** [comment]
@KindDragon 
like this ?

**Comment by AlexGhiondea** [comment]
Is the comment really needed? I find it a bit confusing. 
If you want to add a comment then it should contain the reason why we have disabled white pace trimming.

**Comment by shahid-pk** [comment]
@AlexGhiondea  done

**Comment by KindDragon** [comment]
@AlexGhiondea Yes we can remove comments
@shahid-pk Also remove at least line with comment `# Trim trailing whitespace`

**Comment by shahid-pk** [comment]
@KindDragon this was exactly what i did before @AlexGhiondea comment. I unfortunately squashed those commits.

**Comment by AlexGhiondea** [comment]
LGTM

**Pull request merged**
