### PR TITLE
Changing Span/Memory to return default on null instead of throwing.

### PR DESCRIPTION
**Pull request by ahsonkhan**
This keeps the behavior of implicit casts and constructor calls consistent.

Complimentary PR in corefx: https://github.com/dotnet/corefx/pull/26807

Related to https://github.com/dotnet/corefx/issues/24409 which was fixed here https://github.com/dotnet/corefx/pull/25257.

cc @jkotas, @KrzysztofCwalina, @VSadov, @stephentoub, @JeremyKuhne

### CODE REVIEW

**Comment by jkotas** [comment]
@safern @Anipik Could you please check why the mirror is not picking up this PR?

**Comment by Anipik** [comment]
@jkotas mirrors are stuck due to merge conflicts and I am working on resolving them.

**Comment by Anipik** [comment]
I am resolving merge conflicts for this PR

**Comment by Anipik** [comment]
@jkotas https://github.com/dotnet/corefx/pull/26872

**Comment by jkotas** [comment]
@Anipik Thank!

**Pull request merged**
