### PR TITLE
Support other toolsets in Win/ARM64 build

### PR DESCRIPTION
**Pull request by RussKeldorph**

### CODE REVIEW

**Comment by RussKeldorph** [comment]
@dotnet-bot help

**Comment by RussKeldorph** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by RussKeldorph** [comment]
@jashook PTAL

/cc @dotnet/arm64-contrib

**Comment by sdmaclea** [comment]
@RussKeldorph Thanks

**Comment by RussKeldorph** [comment]
Known ARM64 failures.

**Pull request merged**
