### PR TITLE
ARM64: Test.lst update with the latest lab run

### PR DESCRIPTION
**Pull request by kyulee1**
Fixes https://github.com/dotnet/coreclr/issues/4028
Enabled a few more PASS tests as well based on the lab results.

### CODE REVIEW

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64

**Comment by kyulee1** [comment]
@dotnet/arm64-contrib PTAL

**Comment by briansull** [comment]
LGTM

**Comment by kyulee1** [comment]
Also skipped xunit xml publication for debug build which is not relevant.

**Pull request merged**
