### PR TITLE
Test CI

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
`Error downloading tests from: https://cloudcijobs.blob.core.windows.net/coreclrci/CoreFXArchives_Linux/TestList.json`

@dotnet/dnceng @safern The CoreFX test drop used by CoreCLR CI disappeared from the Azure blob storage. This is causing all CoreFX-test legs in CoreCLR CI to fail. Could you please recover it?

**Comment by safern** [comment]
I'm talking offline to @riarenas and we're trying to figure out what happened.

**Comment by jkotas** [comment]
@safern Thank you for jumping on this!

**Comment by riarenas** [comment]
I see that the file is present, but the container is marked as private. I'm afraid I'm not familiar with this process so I don't know if this is expected?

**Comment by safern** [comment]
It seems like permissions to the container where changed today by @ilyas1974 due to a new security policy. He just reverted it to have public read access. I'm going to retry the builds.

**Comment by riarenas** [comment]
Spoke to @ilyas1974, As a security feature they made the containers private as part of a security sweep. He has reverted the change for now and will follow up with the correct way to handle this going forward. This should be unblocked now.

**Comment by safern** [comment]
@dotnet-bot test Ubuntu x64 Checked CoreFX Tests
@dotnet-bot test Windows_NT x64 Checked CoreFX Tests
@dotnet-bot test Windows_NT x64 Release CoreFX Tests

I also confirmed and download the file manually with `curl -O url` and it succeeded.

**Pull request closed without merging**
