### PR TITLE
Fix run-corefx-tests.py for Arm64 Linux cross build

### PR DESCRIPTION
**Pull request by debayang**
Modified the  **run-corefx-tests.py**  script to allow corefx cross build on x64  linux and generate arm64 corefx runtime  , along with the corefx tests.
This was needed as the arm64 `dotnet ` is not yet available.

CI integration yet to be done.

Command for above on X64 Linux:
  

> python tests/scripts/run-corefx-tests.py  -arch=arm64  -ci_arch=x64_arm64_cross  -build_type=release -no_run_tests

The generated runtime  **netcoreapp-Linux-Release-arm64** and **tests** can be copied on arm64 platform .
To run the tests on arm64 Linux, the existing corefx `run-test.sh` script can be invoked as below:

>  ./run-test.sh --runtime < path to netcoreapp-Linux-Release-arm64 >  --arch arm64  --corefx-tests < path >  --configurationGroup Release 

 The initial corefx **failed tests** on arm64 Ubuntu with the above scripts were as below:
 
  ```
   System.Composition.Tests  Total: 137, Errors: 0, Failed: 2, Skipped: 0, Time: 1.759s
   Invariant.Tests  Total: 289, Errors: 0, Failed: 79, Skipped: 0, Time: 3.292s
   System.Diagnostics.Process.Tests  Total: 236, Errors: 0, Failed: 3, Skipped: 1, Time: 21.367s
   System.Linq.Queryable.Tests  Total: 1324, Errors: 0, Failed: 2, Skipped: 0, Time: 2.768s
   System.IO.Pipes.Tests  Total: 505, Errors: 0, Failed: 1, Skipped: 0, Time: 6.255s
   System.Dynamic.Runtime.Tests  Total: 2900, Errors: 0, Failed: 1, Skipped: 0, Time: 13.187s
   System.Linq.Expressions.Tests  Total: 35203, Errors: 0, Failed: 4, Skipped: 5, Time: 48.791s
   System.Reflection.Emit.ILGeneration.Tests  Total: 221, Errors: 0, Failed: 2, Skipped: 0, Time: 1.417s
   System.Numerics.Vectors.Tests  Total: 1150, Errors: 0, Failed: 3, Skipped: 0, Time: 4.280s
   System.Runtime.Extensions.Tests  Total: 3855, Errors: 0, Failed: 2, Skipped: 15, Time: 8.340s
   System.Net.Requests.Tests  Total: 314, Errors: 0, Failed: 1, Skipped: 6, Time: 9.843s
   System.Xml.Xsl.XslCompiledTransformApi.Tests  Total: 1620, Errors: 0, Failed: 1, Skipped: 0, Time: 17.345s
```
Will add some more details on the failed cases in follow up.

### CODE REVIEW

**Comment by sdmaclea** [comment]
@BruceForstall PTAL

**Comment by debayang** [comment]
Note: `System.IO.Pipes.Tests` failure noted above was due to a Permission issue and passed now.
The remaining failures are discussed in #17020

**Comment by sdmaclea** [comment]
@debayang Can you try running with the `--sequential` option to see if it resolves the OutOfMemory issues.

**Comment by debayang** [comment]
@sdmaclea I tried running the failed tests individually with the same errors.

```
#corerun xunit.console.netcore.exe System.Composition.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait  category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Composition.Tests
Discovered:  System.Composition.Tests
Starting:    System.Composition.Tests
   System.Composition.UnitTests.MetadataTests.MultipleMetadataAttributesWithAPropertyThatReturnsNull [FAIL]
      System.OutOfMemoryException : Insufficient memory within specified address space range to continue the execution of the program.
      Stack Trace:
            at System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method)
            at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target)
         /home/debayan/coreclr/_/fx/src/System.Linq.Expressions/src/System/Linq/Expressions/Compiler/LambdaCompiler.cs(185,0): at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
         /home/debayan/coreclr/_/fx/src/System.Linq.Expressions/src/System/Linq/Expressions/LambdaExpression.cs(206,0): at System.Linq.Expressions.Expression`1.Compile(Boolean preferInterpretation)
         /home/debayan/coreclr/_/fx/src/System.Composition.Hosting/src/System/Composition/Hosting/Providers/Lazy/LazyWithMetadataExportDescriptorProvider.cs(31,0): at System.Composition.Hosting.Providers.Lazy.LazyWithMetadataExportDescriptorProvider.GetLazyDefinitions[TValue,TMetadata](CompositionContract lazyContract, DependencyAccessor definitionAccessor)

```

**Comment by sdmaclea** [comment]
@RussKeldorph @jkotas @BruceForstall PTAL

**Comment by sdmaclea** [comment]
> System.IO.Pipes.Tests failure noted above was due to a Permission issue and passed now

Can you explain the permissions issue.  I hit the same thing when trying to reproduce your results

**Comment by debayang** [comment]
@sdmaclea I just ran the test with sudo permission

**Comment by sdmaclea** [comment]
I reproduced @debayang results while working on enabling running corefx tests in QDT CI.

I took more time checking exit codes and found a few issues which never were not reported above, because xunit run never finished so results were not reported.

I have opened issues for "every" failure.  The exception being those which were clearly duplicates.

**Comment by sdmaclea** [comment]
> Maybe we'll get "dotnet" SDK tool soon on arm32 and arm64 so we won't need to do the magic linking with dotnet/corerun soon?

I think the `dotnet` piece should be available in the core-setup/runtime myget packages for both arm32 and arm64.  It is definitely there for arm64.

**Comment by BruceForstall** [comment]
Sanity check:

@dotnet-bot test Windows_NT x64 Checked corefx_baseline

**Comment by BruceForstall** [comment]
@sdmaclea @debayang FYI: as of https://github.com/dotnet/coreclr/pull/17729 (plus fixes https://github.com/dotnet/coreclr/pull/17742 and https://github.com/dotnet/coreclr/pull/17746), we have Ubuntu arm32 corefx testing in the CI.

We are cross-compiling the corefx tests using Docker in the same Docker container used for the official ARM builds. This required passing `'-AdditionalArgs:"-portable -cross" -Clang:clang5.0'` to the corefx build-native.sh script (note that arm32 builds require clang5.0 due to bugs in clang3.9). But otherwise, the `run-corefx-tests.py` script could be used intact. With your changes here, it looks like you're building on x64 but without passing "cross" to the build-native.sh script, which necessitates a bunch of copying and renaming. Could you build "cross" instead, and simplify that?

**Comment by sdmaclea** [comment]
@BruceForstall Looks like the arm64 version of the script is not attempting to do the native build.  We could probably follow the arm32 design w/o an issue.

**Pull request merged**
