### PR TITLE
Merge changes with .net native

### PR DESCRIPTION
**Pull request by davmason**
These are the changes that existed in .net native that weren't in coreclr.

### CODE REVIEW

**Comment by davmason** [comment]
CC @vancem

**Comment by vancem** [comment]
It looks like ParameterTypes was not ported to N (I see from the build failures).

Also, I don't see the fix for the race in DisposeOnShutdown.   Was that intentional?

**Comment by vancem** [comment]
Otherwise looks good to me.

**Comment by davmason** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build

**Pull request merged**
