### PR TITLE
Switch to BYOC pools

### PR DESCRIPTION
**Pull request by echesakovMSFT**
Don't merge unless https://github.com/dotnet/core-eng/issues/5701 is resolved

### CODE REVIEW

**Comment by MattGal** [comment]
Seems fine, waiting to synch with @mmitche about the pool provider problem

**Comment by echesakovMSFT** [comment]
@MattGal @mmitche Can you please tell what's status of https://github.com/dotnet/core-eng/issues/5701 ? Is it "safe" to move on BYOC pools now?

**Comment by MattGal** [comment]
@echesakov I believe so;  the outage correlated with an AzDO bug / rollback and hasn't repro'ed since.  We're on the hook if the provider goes bad again, but has been fine for over 16 hours so I think optimistically you're good to go.

**Comment by dagood** [comment]
Any plans to migrate the BAR publish job too? Noticing an official build being delayed waiting for agents here:

https://github.com/dotnet/coreclr/blob/358d9d2559bd57cee7b2d4d0bc6d03ea252f4da8/eng/finalize-publish.yml#L14-L20

**Comment by echesakovMSFT** [comment]
@dagood Thanks for pointing this out - I'll open a PR shortly

**Pull request merged**
