### PR TITLE
Port interopt tests. Disable tests using stdcall pinvoke calls for

### PR DESCRIPTION
**Pull request by hoyMS**
non-windows platform.

jit\jit64\mcc\interop\mcc_i00.il
jit\jit64\mcc\interop\mcc_i01.il
jit\jit64\mcc\interop\mcc_i02.il
jit\jit64\mcc\interop\mcc_i03.il
jit\jit64\mcc\interop\mcc_i04.il
jit\jit64\mcc\interop\mcc_i05.il
jit\jit64\mcc\interop\mcc_i06.il
jit\jit64\mcc\interop\mcc_i07.il
jit\jit64\mcc\interop\mcc_i14.il
jit\jit64\mcc\interop\mcc_i15.il
jit\jit64\mcc\interop\mcc_i16.il
jit\jit64\mcc\interop\mcc_i17.il
jit\jit64\mcc\interop\mcc_i30.il
jit\jit64\mcc\interop\mcc_i31.il
jit\jit64\mcc\interop\mcc_i32.il
jit\jit64\mcc\interop\mcc_i32.il
jit\jit64\mcc\interop\mcc_i33.il
jit\jit64\mcc\interop\mcc_i34.il
jit\jit64\mcc\interop\mcc_i35.il
jit\jit64\mcc\interop\mcc_i36.il
jit\jit64\mcc\interop\mcc_i37.il
jit\jit64\mcc\interop\mcc_i50.il
jit\jit64\mcc\interop\mcc_i51.il
jit\jit64\mcc\interop\mcc_i52.il
jit\jit64\mcc\interop\mcc_i53.il
jit\jit64\mcc\interop\mcc_i54.il
jit\jit64\mcc\interop\mcc_i55.il
jit\jit64\mcc\interop\mcc_i56.il
jit\jit64\mcc\interop\mcc_i57.il
jit\jit64\mcc\interop\mcc_i60.il
jit\jit64\mcc\interop\mcc_i61.il
jit\jit64\mcc\interop\mcc_i62.il
jit\jit64\mcc\interop\mcc_i63.il
jit\jit64\mcc\interop\mcc_i64.il
jit\jit64\mcc\interop\mcc_i65.il
jit\jit64\mcc\interop\mcc_i66.il
jit\jit64\mcc\interop\mcc_i67.il
jit\jit64\mcc\interop\mcc_i70.il
jit\jit64\mcc\interop\mcc_i71.il
jit\jit64\mcc\interop\mcc_i72.il
jit\jit64\mcc\interop\mcc_i73.il
jit\jit64\mcc\interop\mcc_i74.il
jit\jit64\mcc\interop\mcc_i75.il
jit\jit64\mcc\interop\mcc_i76.il
jit\jit64\mcc\interop\mcc_i77.il
jit\jit64\mcc\interop\mcc_i80.il
jit\jit64\mcc\interop\mcc_i81.il
jit\jit64\mcc\interop\mcc_i82.il
jit\jit64\mcc\interop\mcc_i83.il
jit\jit64\mcc\interop\mcc_i84.il
jit\jit64\mcc\interop\mcc_i85.il
jit\jit64\mcc\interop\mcc_i86.il
jit\jit64\mcc\interop\mcc_i87.il

### CODE REVIEW

**Comment by hoyMS** [comment]
@pgavlin please review this. I saw a weird error in OSX x64 Release Build and Test  

11:47:06 [release_osx_tst_prtest@2] $ /bin/sh -xe /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/hudson8650222003678315642.sh
11:47:06 /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/hudson8650222003678315642.sh: /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/hudson8650222003678315642.sh: cannot execute binary file
11:47:07 Build step 'Execute shell' marked build as failure

How do I rerun it?

**Comment by pgavlin** [comment]
@dotnet-bot test OSX x64 Release

**Comment by hoyMS** [comment]
@dotnet-bot test OSX x64 Release

**Comment by hoyMS** [comment]
@dotnet-bot test OSX x64 Release Build and Test

**Comment by hoyMS** [comment]
@dotnet-bot test OSX x64 Release

**Comment by hoyMS** [comment]
It was triggered but then quick failed again.

**Comment by hoyMS** [comment]
Error: Possible issue connecting to GitHub or cloning the repository. This could be caused by a lack of network connectivity or a lack of disk space. Please email netciadmin.

**Comment by pgavlin** [comment]
Nit: please squash the two commits together and move the bit about disabled tests from the title of the commit to the body. LGTM otherwise.

**Comment by hoyMS** [comment]
@dotnet-bot test this please

**Comment by hoyMS** [comment]
There are three jobs always failing due to network issue. Do we want to do the merge ?

**Comment by pgavlin** [comment]
@mmitche: are the Macs offline? If so, are we clear to merge?

**Comment by mmitche** [comment]
@pgavlin Yeah they are at the moment, and one is dead.

**Comment by hoyMS** [comment]
@pgavlin please help merge it. I don't seem to have the write access. Thanks.

**Pull request merged**
