### PR TITLE
Avoid throwing in the globalization managed callbacks

### LINKED ISSUE #11432: Crash in System.Globalization on CentOS
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_centos7.1_release/37/
```
  FAILURE_HASH:
  SIGABRT_System.ExecutionEngineException_libgcc_s.so.1!_Unwind_RaiseException
   
  FAULT_STACK:
  libc.so.6!__GI_raise
  libc.so.6!__GI_abort
  libcoreclr.so!UNKNOWN
  libcoreclr.so!UNKNOWN
  libcoreclr.so!SafeExitProcess(unsigned int, int, ShutdownCompleteAction)
  libcoreclr.so!EEPolicy::HandleFatalError(unsigned int, unsigned long, char16_t const*, _EXCEPTION_POINTERS*)
  libcoreclr.so!UNKNOWN
  libgcc_s.so.1!_Unwind_RaiseException
  libstdc++.so.6!__cxa_throw
  libcoreclr.so!UNKNOWN
  libcoreclr.so!RaiseException
  libcoreclr.so!COMPlusThrowBoot(int)
  libcoreclr.so!TheUMEntryPrestubWorker
  libcoreclr.so!TheUMEntryPrestub
  System.Globalization.Native.so!InvokeCallbackForDatePattern(char const*, UDateFormatStyle, void (*)(unsigned short const*, void const*), void const*)
  System.Globalization.Native.so!GlobalizationNative_EnumCalendarInfo
  System.Private.CoreLib.dll!DomainNeutralILStubClass.IL_STUB_PInvoke(EnumCalendarInfoCallback, System.String, System.Globalization.CalendarId, System.Globalization.CalendarDataType, IntPtr)
  System.Private.CoreLib.dll!System.Globalization.CalendarData.EnumCalendarInfo(System.String, System.Globalization.CalendarId, System.Globalization.CalendarDataType, CallbackContext)
  System.Private.CoreLib.dll!System.Globalization.CalendarData.EnumDatePatterns(System.String, System.Globalization.CalendarId, System.Globalization.CalendarDataType, System.String[] ByRef)
  System.Private.CoreLib.dll!System.Globalization.CalendarData.LoadCalendarDataFromSystem(System.String, System.Globalization.CalendarId)
  System.Private.CoreLib.dll!System.Globalization.CalendarData..ctor(System.String, System.Globalization.CalendarId, Boolean)
  System.Private.CoreLib.dll!System.Globalization.CultureData.GetCalendar(System.Globalization.CalendarId)
  System.Private.CoreLib.dll!System.Globalization.DateTimeFormatInfo.InitializeOverridableProperties(System.Globalization.CultureData, System.Globalization.CalendarId)
  System.Private.CoreLib.dll!System.Globalization.CultureInfo.get_DateTimeFormat()
  System.Private.CoreLib.dll!System.Globalization.DateTimeFormatInfo.get_CurrentInfo()
  System.Private.CoreLib.dll!System.DateTimeOffset.ToString(System.String, System.IFormatProvider)
  System.Private.CoreLib.dll!System.Text.StringBuilder.AppendFormatHelper(System.IFormatProvider, System.String, System.ParamsArray)
  System.Private.CoreLib.dll!System.String.FormatHelper(System.IFormatProvider, System.String, System.ParamsArray)
  System.Net.Http.Functional.Tests.dll!System.Net.Test.Common.LoopbackServer.get_DefaultHttpResponse()
  System.Net.Http.Functional.Tests.dll!System.Net.Test.Common.LoopbackServer+<ReadWriteAcceptedAsync>d__8.MoveNext()
  System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib]].Start[[System.Net.Test.Common.LoopbackServer+<ReadWriteAcceptedAsync>d__8, System.Net.Http.Functional.Tests]](<ReadWriteAcceptedAsync>d__8 ByRef)
  System.Net.Http.Functional.Tests.dll!System.Net.Test.Common.LoopbackServer.ReadWriteAcceptedAsync(System.Net.Sockets.Socket, System.IO.StreamReader, System.IO.StreamWriter, System.String)
  System.Net.Http.Functional.Tests.dll!System.Net.Test.Common.LoopbackServer+<AcceptSocketAsync>d__9.MoveNext()
  System.Private.CoreLib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
  System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
  System.Private.CoreLib.dll!System.Threading.Tasks.Task.RunContinuations(System.Object)
  System.Private.CoreLib.dll!System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib]].TrySetResult(System.__Canon)
  System.Private.CoreLib.dll!System.Threading.Tasks.TaskCompletionSource`1[[System.__Canon, System.Private.CoreLib]].TrySetResult(System.__Canon)
  System.Net.Http.Functional.Tests.dll!System.Net.Test.Common.LoopbackServer+<>c.<AcceptAsyncApm>b__13_0(System.IAsyncResult)
  System.Net.Sockets.dll!System.Net.LazyAsyncResult.Complete(IntPtr)
  System.Private.CoreLib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
  System.Net.Sockets.dll!System.Net.ContextAwareResult.Complete(IntPtr)
  System.Private.CoreLib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
  System.Private.CoreLib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()
  libcoreclr.so!CallDescrWorkerInternal
  libcoreclr.so!MethodDescCallSite::CallTargetWorker(unsigned long const*, unsigned long*, int)
  libcoreclr.so!QueueUserWorkItemManagedCallback(void*)
  libcoreclr.so!ManagedThreadBase_DispatchOuter(ManagedThreadCallState*)
  libcoreclr.so!ManagedThreadBase::ThreadPool(ADID, void (*)(void*), void*)
  libcoreclr.so!ManagedPerAppDomainTPCount::DispatchWorkItem(bool*, bool*)
  libcoreclr.so!ThreadpoolMgr::WorkerThreadStart(void*)
  libcoreclr.so!CorUnix::CPalThread::ThreadEntry(void*)
  libpthread.so.0!start_thread
  libc.so.6!__clone
```

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes #11432

This fix is for catching and ignoring the exceptions thrown in the managed callback called from the native side. 
For the exceptions thrown from the native side, it is tracked by the issue #11404

### CODE REVIEW

**Comment by tarekgh** [comment]
CC @jkotas @stephentoub

**Comment by jkotas** [comment]
It looks questionable that we are ignoring the error here. It maybe better to propagate it instead. But I do see that the general pattern in globalization code is to ignore the errors. If it is intentional, LGTM.

**Comment by stephentoub** [comment]
I was assuming we'd propagate exceptions as well.  Presumably the best way to do that would be to create an ExceptionDispatchInfo for the caught exception, create a GCHandle for it and return the handle for it back to native which could in turn return it back to managed, which could then retrieve, free, and throw it?

**Comment by tarekgh** [comment]
I prefer for now not to propagate the exception as we did in Windows side. these callback for enumeration which is fine to ignore the one throwing such exception and continue. In the future, if proved we need to propagate it we can do that consistently across the board.

**Comment by stephentoub** [comment]
> these callback for enumeration which is fine to ignore the one throwing such exception and continue

Why?  What's the cause of the exception?

**Comment by tarekgh** [comment]
> Why? What's the cause of the exception?

On Windows, sometime we got some corrupted data (not clear why but happened).

**Comment by stephentoub** [comment]
> On Windows, sometime we got some corrupted data (not clear why but happened).

I mean, what exceptions are we getting here on Unix.  Obviously we got one that triggered this issue in the first place.  And if we don't know what the exception was, seems bad to just proactively ignore any.

**Comment by tarekgh** [comment]
It is not clear what exception is thrown in this Linux case. and even this is fist time we see it there.

**Comment by stephentoub** [comment]
> It is not clear what exception is thrown in this Linux case. and even this is fist time we see it there.

How do we know it's safe to ignore then?

**Comment by tarekgh** [comment]
> How do we know it's safe to ignore then?

As I mentioned we have done the same in Windows. and this is done in the enumeration of calendar properties which is ok to ignore one or few of the enumerated values. If you think we should propagate the exception, then we should do it across the board and that will not small change to do it now for v2.0. This is why I said if proven we need to propagate the exception we can do it at that time.

let me know what you think?

**Comment by tarekgh** [comment]
@stephentoub can I merge this change and I can look at propagating the exception in different PR.

**Comment by stephentoub** [comment]
> can I merge this change and I can look at propagating the exception in different PR.

For now can you at least add a debug assert that'll fire with the exception details so we can better understand what the cause is if this happens again?  That should fail fast, but fail fast from managed with the exception object.

Also open an issue to track any subsequent work here?

Thanks.

**Comment by tarekgh** [comment]
I have opened the issue #11461 tracking the exception propagation

**Pull request merged**
