### PR TITLE
NetBSD has RAND_MAX = 0x7fffffff

### PR DESCRIPTION
**Pull request by krytarowski**

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
I'm not sure about the cost:benefit ratio of including the value of RAND_MAX on each platform in this comment, especially with the number of platforms we're on. OS X has a RAND_MAX of 0x7FFFFFFF too for instance. Perhaps it's better to just call out that RAND_MAX can vary by platform and leave it at that. If someone is really interested, they can look up what it is pretty easily.

**Comment by krytarowski** [comment]
Done!

**Comment by janvorli** [comment]
LGTM

**Comment by adityamandaleeka** [comment]
LGTM

**Pull request merged**
