### PR TITLE
Add reboot step to end of perf runs

### PR DESCRIPTION
**Pull request by DrewScoggins**
We are seeing machines get into bad states and corrupt other runs.  To fix this we are just going to introduce a reboot at the end of each run.

### CODE REVIEW

**Comment by DrewScoggins** [comment]
test ci please

**Comment by DrewScoggins** [comment]
test ci please

**Comment by mmitche** [comment]
@DrewScoggins I have some questions about this.

1. It won't work to reboot the machine in the postbuild step.  The build will simply fail (because the agent will disconnect)
2. There are two potential right ways to do this.  First is to write a plugin for a different node type that reboots upon tasks being finished.  The second is is to utilize the Helix allocation plugin, along with an additional (currently unimplemented) feature in Helix that would allow us to reboot or delete nodes after they are disconnected from Jenkins.  I think the second approach is better.
3. Is this to combat the ETW issue?  Can we work around that (by putting a postbuild step like you have above to shutdown ETW while we transition to a 'better' solution?)

**Comment by DrewScoggins** [comment]
Thanks for the input @mmitche!  I assumed that the post-build step idea would not work, and that the build would just show as failed after we disconnect the machine, but I wanted to go ahead and give this a try.  The issue that we are trying to solve is that, in general, we see instability in both correctness of our perf runs (unable to delete a working directory because of VBCSCompiler.exe running, ETW logger not propery shutdown) and in the actual measuring of results (we have had machines that were giving data that fluctuated wildly on tests, and upon inspection the entire machine was running very slowly until a reboot).  Given that we have more than one type of issue that can cause build failures, and one that is only really solved by rebooting the machine, I am not sure how effective workarounds for individual issues will be.

The perf machines are physical hardware that is not currently managed by Helix.  If we wanted to go with the second solution that you proposed in bullet two, would we have to move our machines into Helix?  I am not against this per se, but it would be a decent amount of effort, particularly with all the verification that results would remain consistent and possible rebaselining of old releases.  Given this I would like to avoid this unless we absolutely have to.

**Comment by mmitche** [comment]
@DrewScoggins The move into Helix doesn't imply actually onboarding any of your testing into Helix, it simply means connecting the machine up to Helix as a client to a queue (say a "perf" queue).  Whereas today you launch the Jenkins client on startup, later you launch the Helix client.  That's it.

We wrote a Jenkins cloud plugin that uses Helix to run the Jenkins client.  So for instance Jenkins asks for an OSX machine, and the plugin submits the command to launch a client on an OSX machine to Helix. 
 The upside of this is that the machines connected via that method will 'migrate' across Jenkins instances.  This makes better use of our hardware and software resources.

Is a reboot needed after every run?  It's possible we could take a different tack and set the machines to reboot every few hours if idle.

**Comment by jorive** [comment]
I like the option to "write a plugin for a different node type that reboots upon tasks being finished", a very common lab scenario.

**Comment by mmitche** [comment]
@jorive @DrewScoggins I think that this should be implemented in the Helix plugin + Helix, the implementation is much more straightforward there and has several other advantages. https://github.com/dotnet/core-eng/issues/1546 covers this work.

**Comment by DrewScoggins** [comment]
@dotnet-bot help

**Comment by DrewScoggins** [comment]
Going to close this and we will wait for dotnet/core-eng#1546.

**Pull request closed without merging**
