### PR TITLE
Update Nuget package versions to 1.2.0

### PR DESCRIPTION
**Pull request by gkhanna79**
Bump package versions in CoreCLR master to 1.2.0

@weshaggard @ericstj @RussKeldorph PTAL

CC @leecow

### CODE REVIEW

**Comment by RussKeldorph** [comment]
LGTM

**Comment by weshaggard** [comment]
LGTM

cc @ericstj

**Comment by ericstj** [comment]
Looks ok to me, though if I were you I'd just define this centrally like we do in CoreFx:  https://github.com/dotnet/corefx/blob/b44eb9f4b4f2e27226833894436a6871e19fb40b/Packaging.props#L24

**Comment by gkhanna79** [comment]
@ericstj If it is defined as PAckageVersion, as you pointed, do we still need to have a Version property (which is what I am currently updating)?

**Comment by gkhanna79** [comment]
I ask since https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/Microsoft.NETCore.Platforms.pkgproj#L6 shows CoreFX specifying PackageVersion explicitly as well.

**Comment by ericstj** [comment]
We define a common one for the repo then let packages over-ride it if they want to be different.

**Pull request merged**
