### PR TITLE
Disable PInvoke inlining within try regions on ARM64

### PR DESCRIPTION
**Pull request by adityamandaleeka**
PInvoke inlining within try blocks causes exception handling to lose track of the context pointers during unwind, which in turn causes us to crash when attempting to restore the nonvolatile registers at the end of the exception handling process. This change makes it so ARM64 follows the same behavior as AMD64, where pinvoke inlining is not allowed inside of try regions. 

Fixes https://github.com/dotnet/coreclr/issues/21964

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
Pinging @BruceForstall. Andy, I think you have the wrong Bruce 😄

**Comment by AndyAyersMS** [comment]
Yes, thanks.... not the first time that's happened. Sorry to bother you, brucefo.

**Comment by BruceForstall** [comment]
I'm pretty hazy on this, but `Lowering::InsertPInvokeCallProlog` (as well as `Lowering::InsertPInvokeMethodProlog()`) indicates that 64-bit targets for non-IL stub pinvokes link the InlinedCallFrame into the frame list at the call site, but 32-bit targets do not. Is that the crux of the issue?

**Comment by AndyAyersMS** [comment]
Probably so.

I take it the question is that if we pinvoke from some method X, and that pinvoke throws an exception, and control passes back to some code within X, is the inline pinvoke frame in X properly deactivated? Sounds like no for 64 bit targets. So instead we have to use an actual frame for the pinvoke.

**Comment by adityamandaleeka** [comment]
The macOS x64 run timed out. ARM64 looks good and I see that the re-enabled test passed, so I'm merging this.

**Pull request merged**
