### PR TITLE
Change string.Compare(...) == 0 occurrences to string.Equals(...)

### PR DESCRIPTION
**Pull request by stephentoub**

### CODE REVIEW

**Comment by jkotas** [comment]
@A-And The new CoreFX Tests legs are failing.

**Comment by A-And** [comment]
@jkotas - the fix is in https://github.com/dotnet/coreclr/pull/18615 - I'm waiting for someone knowledgeable about how CI machines handles paths to review

**Comment by AaronRobinsonMSFT** [comment]
@stephentoub Just for my own curiosity, is using `Equals()` preferred in general or is there a more pragmatic reason?

**Comment by jkotas** [comment]
Equals is faster than Compare.

**Pull request merged**
