### PR TITLE
Resolve libdl to LIBDL_SO on glibc Linux.

### PR DESCRIPTION
**Pull request by tmds**
This makes "libdl" resolvable without the user having to install
glibc development packages.

@janvorli ptal

### CODE REVIEW

**Comment by tmds** [comment]
err.. I took the wrong define, this needs to be LIBDL_SO
```
#define LIBDL_SO                        "libdl.so.2"
```

**Comment by jkotas** [comment]
Do we need any tests?

What makes libdl special to include it in this special handling plan? In other words, what is the rule how we decide whether to special handle the library here?

**Comment by janvorli** [comment]
> What makes libdl special to include it in this special handling plan?

I had the same thought and I've found we use it in DllImport inside corefx. E.g.
https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/Common/src/Interop/Unix/libdl/Interop.dlsym.cs#L12

So that makes it special.

**Comment by jkotas** [comment]
> I've found we use it in DllImport inside corefx.

We have fixed this problem by exposing proper APIs to load the library in .NET Core 3.0 and converting corefx to use it. The file you have referenced is only used to build downlevel flavors of the libraries.

**Comment by janvorli** [comment]
Ok, in that case (corefx not pinvoking into the libdl) it seems we don't need to make this change. @tmds have you hit problems that lead you to make this change?
@jkotas if I understand the ifdefs in the code correctly, corefx in .NET core 2.1 and 2.2 still pinvokes into that library. Am I right? If that's the case, it seems that we may want to make this change in 2.1 / 2.2 branches only.

**Comment by jkotas** [comment]
Right, it is https://github.com/dotnet/corefx/issues/25102 . It is known problem for ~2 years that makes it hard to justify port to 2.1/2.2 now.

**Comment by tmds** [comment]
> have you hit problems that lead you to make this change?

I'm trying out the dotnet-dump tool which uses clrmd, which is using dlopen: https://github.com/microsoft/clrmd/blob/ba3425b85e970f393603e12717e9378c07bbc182/src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/LinuxFunctions.cs#L41-L51

There seems to be some [code directly using libdl](https://github.com/search?l=&q=dlsym+language%3AC%23&type=Code).

> by exposing proper APIs to load the library in .NET Core 3.0

I think the main downside is that it requires libraries to target netcoreapp3.0.
If DllImport handles this, it's netstandard1.1+.

**Comment by jkotas** [comment]
I think it would be better to fix this is in `Microsoft.Diagnostics.Runtime`. The fix can use reflection light-up, if targeting netcoreapp3.0 is not an option.

**Comment by hoyosjs** [comment]
cc @mikem8361 @leculver

**Comment by mikem8361** [comment]
@jkotas can you explain the "reflection light-up" fix details to apply to clrmd?  If there is some way to workaround this problem in clrmd, I'm all for it and will implement it.

**Comment by jkotas** [comment]
It can look like this:


`Func<string, IntPtr> _loadLibrary;`

In LinuxFunctions constructor:

```
Type nativeLibraryType = Type.GetType("System.Runtime.InteropServices.NativeLibrary, System.Runtime.InteropServices", throwOnError: false);

if (nativeLibraryType != null)
{
    _loadLibrary = (Func<string, IntPtr>)nativeLibraryType.GetMethod("Load", new Type[] { typeof(string) })?.CreateDelegate(typeof(Func<string, IntPtr>))
    ... similar for TryGetExport and Free ...
}
```


```
        public override IntPtr LoadLibrary(string filename)
        {
            if (_loadLibrary != null) 
                return _loadLibrary(filename);

            return dlopen(filename, RTLD_NOW);
        }
```

**Comment by tmds** [comment]
@mikem8361 if you want, I can look into the changes to clrmd.

@jkotas I'll close this based on your recommendation to use `NativeLibrary` instead.

**Comment by mikem8361** [comment]
@tmds I'm fine with you working on the clrmd changes.

/cc: @leculver

**Pull request closed without merging**
