### PR TITLE
New x86 excludes and turn on ci testing for x86.

### PR DESCRIPTION
**Pull request by jashook**
Updated x86_exclude targets file to account for all added tests and recent regressions. As well as the ci changes to test the legacy backend on each pr.

@adiaaida @mmitche ptal

### CODE REVIEW

**Comment by adiaaida** [comment]
LGTM

**Comment by jashook** [comment]
Note: failure is unrelated.

**Comment by jashook** [comment]
@mmitche ping

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
Ahh that's not going to get picked up.  LGTM anyway.

**Comment by mmitche** [comment]
Oh nvm.  Merge after the generator test passes.

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT arm64 Release

**Comment by jashook** [comment]
@dotnet-bot test ci please

**Pull request merged**
