### PR TITLE
Replace hasTailCalls with GetTailCalls()

### PR DESCRIPTION
**Pull request by franksinankaya**
Replace setTailCalls with SetTailCalls()

@am11 @janvorli @jkotas @jit-contrib

### CODE REVIEW

**Comment by sandreenko** [comment]
It is @dotnet/jit-contrib, not @jit-contrib

**Comment by franksinankaya** [comment]
yup, on the other hand; it doesn't like me typing @dotnet/jit-contrib per my previous tests.

It won't mark it as a http link.

**Comment by jakobbotsch** [comment]
Right, you need to be a member of this group (or another group with access) to be able to tag it. If you just tag one of us directly it should be ok.

**Comment by BruceForstall** [comment]
@franksinankaya In that case, please tag @sandreenko and he can tag the group.

**Comment by sandreenko** [comment]
> Right, you need to be a member of this group (or another group with access) to be able to tag it. If you just tag one of us directly it should be ok.

Thanks, I did not know that. That should be changed.

**Pull request merged**
