### PR TITLE
Enable linux corefx testing

### PR DESCRIPTION
**Pull request by sejongoh**

### CODE REVIEW

**Comment by sejongoh** [comment]
@dotnet-bot test Windows_NT fx

**Comment by sejongoh** [comment]
@dotnet-bot test Windows_NT fxjs1

**Comment by ellismg** [comment]
NIT: It looks like we've started to intermix tabs and spaces in this file.  Can we align on spaces?

**Comment by sejongoh** [comment]
Sure. I will update the changes.

**Comment by sejongoh** [comment]
@dotnet-bot test Windows_NT fxjs2

**Comment by sejongoh** [comment]
@RussKeldorph @mmitche  Could you please review the changes? This changeset enables Linux corefx testing based on the new build flow.

**Comment by RussKeldorph** [comment]
LGTM.

**Comment by mmitche** [comment]
LGTM, can you wait on merging this till tomorrow?

**Comment by sejongoh** [comment]
Build.sh is broken now (https://github.com/dotnet/corefx/issues/6128). I think that we can check this in tomorrow.

**Comment by joperezr** [comment]
@sejongoh FYI: corefx build in linux has been fixed

**Comment by sejongoh** [comment]
@mmitche Can you let me know if merging is okay? Msbuild on Linux doesn't have the long path problem that I had, so it doesn't seem to need the path shortening plugin. Windows still needs the plugin.

**Comment by sejongoh** [comment]
@dotnet-bot test Windows_NT fxjs2

**Comment by mmitche** [comment]
Merge away, the plugin is installed now.

Sent from my Windows Phone
________________________________

**Comment by sejongoh** [comment]
@mmitche  Thanks!!

**Pull request merged**
