### PR TITLE
Import JIT tests.

### PR DESCRIPTION
**Pull request by pgavlin**
This imports the remainder of the tests under JIT/jit64 that are able
to target CoreCLR.

### CODE REVIEW

**Comment by pgavlin** [comment]
@libengu @AndyAyersMS PTAL

**Comment by libengu** [comment]
Just remind you finally we need to update AllTestProjects.sln also. We can delay it for now and add it together just to remove the dependency between PRs.

**Comment by pgavlin** [comment]
Hm. What is AllTestProjects.sln used for?

**Comment by libengu** [comment]
Currently I think it has no consumer yet. But in the future I think there is potential usage. See this: https://github.com/dotnet/coreclr/wiki/Test-instructions. We don't have to do it right away. We can do it all together so that we can work in parallel.

**Comment by pgavlin** [comment]
The linked instructions imply that the solution is used to sequence the build from VS, which seems pretty important :)

I'll add the projects to the solution in a follow-up change.

**Pull request merged**
