### PR TITLE
Fix DevDiv bug 255263

### PR DESCRIPTION
**Pull request by CarolEidt**
This issue arose because we were not considering punpckldq as
one of the 3-operand AVX instructions (which require us to duplicate
the source register when encoding an SSE 2-operand form).
This bug showed up in managed C++, so the test is in IL.

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib  PTAL

**Comment by pgavlin** [comment]
LGTM

**Comment by adiaaida** [comment]
LGTM

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT x86 ryujit Checked Build and Test

**Comment by briansull** [comment]
LGTM

**Pull request merged**
