### PR TITLE
[ARM/CI] Fix arm32 CI scripts

### PR DESCRIPTION
**Pull request by wateret**
The name of CoreFX Native build directory has changed.

### CODE REVIEW

**Comment by wateret** [comment]
These changes must be merged after https://github.com/dotnet/corefx/pull/15311 landed.
Once CoreFX arm CI works again, all CoreCLR arm PRtests will fail so we need these changes.

cc: @hseok-oh

**Comment by wateret** [comment]
Or maybe it would be better to revert the directory in CoreFX. The directory name changed only case of a letter. It wouldn't matter on Windows anyway.

**Comment by hseok-oh** [comment]
@wateret CoreFX managed code bin also changed. Here is my work.
https://github.com/hseok-oh/coreclr/tree/fix_runtest

**Comment by wateret** [comment]
@hseok-oh I was not aware of that. I'd would be nicer if you create a new PR with your work. Then I'll close this.

**Comment by hseok-oh** [comment]
@wateret I've create a new PR. Thanks.

**Pull request closed without merging**
