### PR TITLE
FileStream should not truncate files when opening fails.

### PR DESCRIPTION
**Pull request by poizan42**
Truncate at the end of initialization if required by the filemode instead. Fixes dotnet/corefx#24081

### CODE REVIEW

**Comment by poizan42** [comment]
@chlowell @stephentoub

**Comment by stephentoub** [comment]
Thanks, @poizan42.  This seems reasonable.  Could you put up a PR for one or more tests in corefx that'll fail before this change and succeed after?

cc: @JeremyKuhne

**Comment by stephentoub** [comment]
Also, is there any measurable perf difference that stems from having the extra call?

**Comment by poizan42** [comment]
PR for test: dotnet/corefx#24163

**Comment by pjanotti** [comment]
Thanks for your contribution @poizan42.

**Pull request merged**
