### PR TITLE
Changed GetDirectoryNameOfFileAbove to GetPathOfFileAbove

### PR DESCRIPTION
**Pull request by ivdiazsa**
Issue #20582: Changed the occurrences of GetDirectoryNameOfFileAbove to the newer GetPathOfFileAbove function call.

### CODE REVIEW

**Comment by ivdiazsa** [comment]
Yes, we tried opening and building some *proj files in VS2017 and everything went fine.

**Comment by nattress** [comment]
The CI also uses VS 2017 by the way

**Comment by danmosemsft** [comment]
Thanks @ivdiazsa. @safern any reason this wouldn't be a good idea in corefx also? Perhaps @ivdiazsa tips be willing to offer a PR for the corefx repo?

**Comment by safern** [comment]
>@safern any reason this wouldn't be a good idea in corefx also? 

If it is available in MSBuild 15 (which comes with VS2017) it would be nice to have in corefx. @ivdiazsa interested in putting up a PR in corefx?

**Comment by ivdiazsa** [comment]
@danmosemsft @safern I can definitely take a look at the CoreFX repo and put up a PR with these changes as well. I see there is no Issue filed, so I can also add one just to keep track.

**Comment by ViktorHofer** [comment]
You can't use GetPathOfFileAbove if the file's name is the same as the msbuild file where the command is in. Means it won't work for Directory.Build.* recursive imports. That's the main reason why I didn't change it everywhere.

**Comment by danmosemsft** [comment]
Bug in their implementation?

Looks like it won't affect cases in this PR though.

**Comment by ivdiazsa** [comment]
@ViktorHofer Do you mean that any `"GetPathOfFileAbove(Directory.Build.*)"` call would fail, or only if it is done inside a file named `Directory.Build.*`?

I ask to know better about the scope of this function and also because our test builds passed without any problems whatsoever.

**Comment by safern** [comment]
> @ViktorHofer Do you mean that any "GetPathOfFileAbove(Directory.Build.*)" call would fail, or only if it is done inside a file named Directory.Build.*?

I think he meant, if you're in a file called `foo.props` and you're trying to get a file from a directory above recursively that has the same name, in this example `foo.props`.  So he's saying that using `GetPathOfFileAbove(Directory.Build.props)` won't work in files named `Directory.Build.props`

Which I just confirmed locally and it's correct:

```
E:\repos\NimbusML\tmp\src\Directory.Build.props(2,3): warning MSB4011: "E:\repos\NimbusML\tmp\src\Directory.Build.props" cannot be imported again. It was already imported at "E:\repos\dotnet\sdk\3.0.100-preview8-012980\Current\Microsoft.Common.props (32,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\repos\NimbusML\tmp\src\tmp.csproj]
```

However as @danmosemsft suggest that might be a bug in their implementation. @rainersigwald is this behavior expected?

**Comment by rainersigwald** [comment]
It's expected, but not ideal. microsoft/msbuild#3160

**Comment by danmosemsft** [comment]
I added comments in https://github.com/microsoft/msbuild/issues/2456.

**Pull request merged**
