### PR TITLE
Add fwrapv compile option

### PR DESCRIPTION
**Pull request by adityamandaleeka**
The behavior of signed integer overflow is undefined per the C++ spec. This change adds the `fwrapv` option to compileoptions.cmake so that signed arithmetic overflow of addition, subtraction, and multiplication wraps around using twos-complement representation.

I've also reverted the previous fix for the bounds check in array allocation since adding this compile option means that it's no longer necessary.

@janvorli PTAL

### CODE REVIEW

**Comment by janvorli** [comment]
LGTM

**Comment by AndyAyersMS** [comment]
Is this a temporary fix? I'd hate to have us depend on something like this long term.

**Comment by adityamandaleeka** [comment]
@AndyAyersMS The original fix for the bounds check in multidimensional array allocation was correct, but the idea with this change is that there are probably other places in the codebase where we do this type of overflow check. Depending on the surrounding code, this could lead to silent but harmful behavior (such as in this case, where in release mode, clang removed a branch entirely which meant we would never throw the expected exception).

**Comment by adityamandaleeka** [comment]
cc: @jkotas

**Comment by jkotas** [comment]
LGTM

**Comment by AndyAyersMS** [comment]
I get why we added it. I just wish we had a plan to fix the code to be standards conformant instead.

One of the clang santitizers can flag this: `-fsanitize=signed-integer-overflow`. Might be worth trying out to see how pervasive this stuff is.

Also, there are various discussions floating about that recommend `-fno-strict-overflow` as the thing to use here.

**Comment by adityamandaleeka** [comment]
@AndyAyersMS I completely agree that we shouldn't be using code that doesn't adhere to the standard. However, it appears that all of the tools available today for detecting this issue work at run time. Unlike GCC, Clang doesn't seem to have an option to emit warnings when optimizations are done based on the assumption that signed integer overflow doesn't occur (it accepts the Wstrict-overflow option but doesn't do anything with it).

Until we have something that can warn us at compile time (or we have test coverage that covers every possible codepath), I think we need to enable -fwrapv. I'll continue to investigate this problem, though, and see whether it's possible to write something like a Clang analyzer that catches this case.

**Comment by swgillespie** [comment]
In the near future, it looks like MSVC will begin taking advantage of the fact that signed integer overflow is undefined: https://blogs.msdn.microsoft.com/vcblog/2016/05/04/new-code-optimizer/, so we could possibly have the same problems on Windows. That blog post mentions not optimizing patterns such as this one for security reasons, but it could be worth auditing the code that gets generated for expressions such as this one with the new backend.

**Pull request merged**
