### PR TITLE
Simplify test dependencies for benchmarks

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Remove the special benchmark configs and update benchmark projects accordingly.
Also update other random projects that were referencing benchmark configs.

Benchmarks now build against netstandard 2.0.

Addresses #14124, #16126.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@jorive please look this over -- preliminary. Want to get some wider testing as things build ok locally.
cc @dotnet/jit-contrib 

Tried updating xunit to 2.2.0 without success; we can do that later I suppose.

**Comment by AndyAyersMS** [comment]
Making sure something runs the pri-1s w/o too many exclusions...

@dotnet-bot test Windows_NT x64 Checked jitsse2only

**Comment by AndyAyersMS** [comment]
Ok, maybe the noSSE wasn't the best way to run all the pri-1 tests. Looks like it has what are likely unrelated issues.

@BruceForstall @jashook I can't see any way to just run all the pri-1 tests that doesn't also run some kind of stress mode. Am I missing something?

In the meantime let's give zap disable a try...

@dotnet-bot test Windows_NT x64 Checked zapdisable

**Comment by BruceForstall** [comment]
Maybe "Windows_NT x64 Build and Test" and "Windows_NT x86 Checked Build and Test"? I think for arm/arm64/armlb the pri-1 contain the work "normal" instead of "innerloop".

**Comment by AndyAyersMS** [comment]
@fiigii @tannergooding [these "sse2 only"](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_jitsse2only_prtest/10/) failures might be worth a closer look.

**Comment by tannergooding** [comment]
> these "sse2 only" failures might be worth a closer look.

A quick grep looks to be code size estimation issues. Possibly related to the recent changes to support 4-byte SSE4 instructions.

**Comment by AndyAyersMS** [comment]
Note there are ~2300 warnings for pri-1 tests, but for the most part these seem to match what was there before. Most of them are bogus or duplicate project includes.

Pri-0 test build generates 61 warnings in managed code (and some in native code too). These too look like they are pre-existing.

**Comment by tannergooding** [comment]
@AndyAyersMS, I see the problem.

We have two ways of tracking SSE4 support (`opts.compCanUseSSE4` and `opts.compSupportsISA`) and we only check one of them. Will update shortly.

**Comment by jashook** [comment]
@AndyAyersMS, as Bruce mentioned

@dotnet-bot test Windows_NT x64 Build and Test
 @dotnet-bot test Windows_NT x86 Checked Build and Test

**Comment by AndyAyersMS** [comment]
The [x64 full pri 1 run](https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_windows_nt_prtest/3273/) timed out after the windows test run, when building linux bits. So I don't see a need to rerun.

@jorive PTAL
cc @dotnet/jit-contrib feel free to chime in, if anyone's interested....

**Comment by jorive** [comment]
@AndyAyersMS LGTM if there is no need to run these benchmarks in `netcoreapp1.1`. To be more conservative, I think we should keep the benchmarks that do not need to move forward in their `netstandard1.x`

**Comment by AndyAyersMS** [comment]
@jorive I don't see us back porting this to 1.1. We can run more or less the same benchmarks there in their current form.

**Comment by jorive** [comment]
@AndyAyersMS OK, sounds good.

**Comment by tannergooding** [comment]
`EnableSSE3_4` issue should be resolved now.

**Comment by AndyAyersMS** [comment]
Double checking this hasn't gone stale: 

@dotnet-bot test this please

**Comment by AndyAyersMS** [comment]
@dotnet-bot test Windows_NT x64 Build and Test

**Comment by AndyAyersMS** [comment]
@dotnet-bot test Windows_NT x64 Checked jitsse2only

**Comment by AndyAyersMS** [comment]
@dotnet-bot test Windows_NT x86 Checked Build and Test
@dotnet-bot test Windows_NT x64 Checked zapdisable

**Comment by AndyAyersMS** [comment]
Reverted via #16647.

**Pull request merged**
