### PR TITLE
Fix importer spilling in the presence of assignment side effects

### LINKED ISSUE #19583: RyuJIT: Incorrect ordering around Interlocked.Exchange and Interlocked.CompareExchange
Example:
```csharp
// Debug: Outputs 0
// Release: Outputs 1
public class Program
{
    static long s_1;
    static int s_3;
    public static void Main()
    {
        int vr16 = s_3;
        int vr19 = System.Threading.Interlocked.Exchange(ref s_3, 1);
        s_1 = vr16;
        System.Console.WriteLine(s_1);
    }
}
```
It also reproduces if `Exchange(ref s_3, 1)` is replaced by `CompareExchange(ref s_3, 1, s_3)`.

[Quoting @mikedn](https://github.com/dotnet/coreclr/issues/18770#issuecomment-414626759):
> a quick look at the dump shows that the load from s_3 moved past exchange quite early, possibly as early as import time.
```
Importing BB01 (PC=000) of 'Program:Main()'
    [ 0]   0 (0x000) ldsfld 04000002
    [ 1]   5 (0x005) ldsflda 04000002
    [ 2]  10 (0x00a) ldc.i4.1 1
    [ 3]  11 (0x00b) call 0A000006
In Compiler::impImportCall: opcode is call, kind=0, callRetType is int, structSize is 0

    [ 2]  16 (0x010) pop

               [000007] ------------              *  STMT      void  (IL 0x000...  ???)
               [000005] ------------              |  /--*  NOP       void  
               [000006] -A--G-------              \--*  COMMA     void  
               [000003] ------------                 |  /--*  CNS_INT   int    1
               [000004] -A--G-------                 \--*  XCHG      int   
               [000002] ------------                    \--*  CNS_INT(h) long   0x7ffb4ffb4598 static Fseq[s_3]

    [ 1]  17 (0x011) conv.i8
    [ 1]  18 (0x012) stsfld 04000001

               [000011] ------------              *  STMT      void  (IL   ???...  ???)
               [000008] ----G-------              |  /--*  CAST      long <- int
               [000001] ----G-------              |  |  \--*  FIELD     int    s_3
               [000010] -A--G-------              \--*  ASG       long  
               [000009] ----G--N----                 \--*  FIELD     long   s_1
```

### PR DESCRIPTION
**Pull request by mikedn**
Atomic ops like `GT_CMPXCHG` and some HW intrinsic nodes act like assignements so `impAppendStmt` has to account for them. They can be top level nodes or they can appear in the RHS of a `GT_ASG` node that perhaps is not considered to have an assignment side effect itself.

No FX diffs.

Fixes #19583

### CODE REVIEW

**Comment by mikedn** [comment]
Only 6 CI legs started.... @dotnet-bot test this please

**Comment by erozenfeld** [comment]
@dotnet/jit-contrib

**Comment by erozenfeld** [comment]
Restarting the tests since it's been a while since the last run.
@dotnet-bot test this
\Azure Pipelines Run coreclr-ci

**Comment by erozenfeld** [comment]
@dotnet/jit-contrib Anyone else wants to add a review?

**Comment by erozenfeld** [comment]
@mikedn Looks like tests need to be updated.

**Comment by mikedn** [comment]
Yep, they changed SetAllVector128 to Create. I verified that the updated test still generates bad code without the fix applied:
```asm
       33C0                 xor      eax, eax
       89442408             mov      dword ptr [rsp+08H], eax
       8944240C             mov      dword ptr [rsp+0CH], eax
       89442410             mov      dword ptr [rsp+10H], eax
       89442414             mov      dword ptr [rsp+14H], eax
       B801000000           mov      eax, 1
       C5F96EC0             vmovd    xmm0, eax
       C4E27958C0           vpbroadcastd xmm0, xmm0
       488D442408           lea      rax, bword ptr [rsp+08H]
       C5FA7F00             vmovdqu  xmmword ptr [rax], xmm0
; v.y load moved past store
       8B44240C             mov      eax, dword ptr [rsp+0CH]
```

**Comment by mikedn** [comment]
Meh, coreclr-ci failed while building tests, apparently due to an "out of memory" issue:
```
2019-01-24T10:15:17.2653976Z /__w/1/s/Tools/IL.targets(49,5): error MSB6003: The specified task executable "sh" could not be run. Cannot allocate memory [/__w/1/s/tests/src/readytorun/tests/fieldgetter.ilproj]
```
Is coreclr-ci something worth retrying or is it still work in progress?

**Comment by echesakovMSFT** [comment]
The "out of memory" issue one of the common MSBuild issues in new Azure DevOps CI (other than https://github.com/dotnet/coreclr/issues/20236) /cc @RussKeldorph 

@mikedn Answering your question "is it still work in progress?" - yes, it is, but it was retry-ing the failing build since only failed job would be restarted. I will do it for you

**Comment by erozenfeld** [comment]
@mikedn Thank you for the fix!

**Pull request merged**
