### PR TITLE
JIT: fix return type mismatch inline block for literal argument

### LINKED ISSUE #16944: JIT produces suboptimal code (unnecessary call) when using recent ReadOnlySpan compiler optimizations
Roslyn recently made a change (https://github.com/dotnet/roslyn/pull/24621) where they're able to optimize code of the form `ReadOnlySpan<byte> span = new byte[] { /* literal data */ }`. However, this produces IL that seems to defeat JIT optimizations, resulting in unnecessary calls and suboptimal performance.

**Sample code (control)**

```cs
[MethodImpl(MethodImplOptions.NoInlining)]
private static unsafe uint Foo(int x)
{
    var span = new ReadOnlySpan<byte>(&x, 4);
    return span[1];
}
```
```text
  .method private hidebysig static uint32 
          Foo(int32 x) cil managed noinlining
  {
    // Code size       21 (0x15)
    .maxstack  3
    .locals init (valuetype [System.Runtime]System.ReadOnlySpan`1<uint8> V_0)
    IL_0000:  ldloca.s   V_0
    IL_0002:  ldarga.s   x
    IL_0004:  conv.u
    IL_0005:  ldc.i4.4
    IL_0006:  call       instance void valuetype [System.Runtime]System.ReadOnlySpan`1<uint8>::.ctor(void*,
                                                                                                     int32)
    IL_000b:  ldloca.s   V_0
    IL_000d:  ldc.i4.1
    IL_000e:  call       instance !0& modreq([System.Runtime]System.Runtime.InteropServices.InAttribute) valuetype [System.Runtime]System.ReadOnlySpan`1<uint8>::get_Item(int32)
    IL_0013:  ldind.u1
    IL_0014:  ret
  } // end of method Program::Foo
```
```asm
ConsoleApp8!ConsoleApp8.Program.Foo(Int32):
00007ffe`cf3714c0 894c2408        mov     dword ptr [rsp+8],ecx
00007ffe`cf3714c4 488d442408      lea     rax,[rsp+8]
00007ffe`cf3714c9 0fb64001        movzx   eax,byte ptr [rax+1]
00007ffe`cf3714cd c3              ret
```

**Sample code (experimental)**

```cs
[MethodImpl(MethodImplOptions.NoInlining)]
private static unsafe uint Foo(int x)
{
    var span = new ReadOnlySpan<byte>(new byte[] { 1, 2, 3, 4, 5 });
    return span[1];
}
```
```text
  .method private hidebysig static uint32 
          Foo(int32 x) cil managed noinlining
  {
    // Code size       23 (0x17)
    .maxstack  3
    .locals init (valuetype [System.Runtime]System.ReadOnlySpan`1<uint8> V_0)
    IL_0000:  ldloca.s   V_0
    IL_0002:  ldsflda    valuetype '<PrivateImplementationDetails>'/'__StaticArrayInitTypeSize=5' '<PrivateImplementationDetails>'::'11966AB9C099F8FABEFAC54C08D5BE2BD8C903AF'
    IL_0007:  ldc.i4.5
    IL_0008:  call       instance void valuetype [System.Runtime]System.ReadOnlySpan`1<uint8>::.ctor(void*,
                                                                                                     int32)
    IL_000d:  ldloca.s   V_0
    IL_000f:  ldc.i4.1
    IL_0010:  call       instance !0& modreq([System.Runtime]System.Runtime.InteropServices.InAttribute) valuetype [System.Runtime]System.ReadOnlySpan`1<uint8>::get_Item(int32)
    IL_0015:  ldind.u1
    IL_0016:  ret
  } // end of method Program::Foo
```
```asm
ConsoleApp8!ConsoleApp8.Program.Foo(Int32):
00007ffe`cf3a14c0 4883ec28        sub     rsp,28h
00007ffe`cf3a14c4 48b9493a3c8562020000 mov rcx,offset ConsoleApp8+0x3a49 (00000262`853c3a49)
00007ffe`cf3a14ce e86dd52458      call    System_Private_CoreLib!Internal.Runtime.CompilerServices.Unsafe.As[[...]](...)+0xffffffff`fffffe90 (00007fff`275eea40)
00007ffe`cf3a14d3 0fb64001        movzx   eax,byte ptr [rax+1]
00007ffe`cf3a14d7 4883c428        add     rsp,28h
00007ffe`cf3a14db c3              ret
```

Note the unnecessary `call` instruction, which should have been inlined into the caller. (The method's implementation is to return its input, so the entire call should've been optimized away as in the control sample.)

If I modify the MSIL manually by inserting a `conv.i` instruction immediately after the `ldsflda` and recompile, the JIT instead produces this codegen:

```asm
ConsoleApp8!ConsoleApp8.Program.Foo(Int32):
00007ffe`cf3a14c0 48b85120fa1d41020000 mov rax,offset ConsoleApp8+0x2051 (00000241`1dfa2051)
00007ffe`cf3a14ca 0fb600          movzx   eax,byte ptr [rax]
00007ffe`cf3a14cd c3              ret
```

This is the desired codegen for this method. The JIT seems to incorrectly require the `conv.i` instruction to get full optimization.

### PR DESCRIPTION
**Pull request by AndyAyersMS**
When we inline a method that returns one of its arguments, we need to make sure
to apply the callee's view of the argument type.

We fixed this for arguments that are caller locals in #11218. This change applies
similar logic to handle the case where the caller passes a literal constant.

Closes #16944.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@briansull PTAL
cc @dotnet/jit-contrib 

Don't expect any diffs from this -- will verify soon.

**Comment by AndyAyersMS** [comment]
[Arm failure](https://ci.dot.net/job/dotnet_coreclr/job/master/job/armlb_cross_checked_windows_nt_innerloop_flow_prtest/427/) seems to be a known issue (#16961).

I have verified this is no diff.

**Comment by briansull** [comment]
Should this fix go into 4.7.3?

**Comment by AndyAyersMS** [comment]
I don't think it needs to be in 4.7.3.

**Comment by GrabYourPitchforks** [comment]
I build coreclr locally off this PR and confirmed that it produces correct code gen for the `ReadOnlySpan<byte> span = new byte[] { /* ... */ };` scenario.

**Comment by AndyAyersMS** [comment]
@briansull you ok with this change?

**Pull request merged**
