### PR TITLE
Add warning banner and sos threads -special fix

### PR DESCRIPTION
**Pull request by mikem8361**
Issue https://github.com/dotnet/diagnostics/issues/38

### CODE REVIEW

**Comment by mjsabby** [comment]
@mikem8361 could you please squash and merge your future PRs? It keeps the git history linear and clean.

**Comment by mikem8361** [comment]
I usually do and this PR seems to be squashed (only one commit).

**Comment by jkotas** [comment]
@mikem8361 There is difference between "Merge pull request" and "Squash and Merge" even on PRs with a single commit.

"Merge pull request" adds two commits to the history (one commit with the change and second commit for the merge) and makes the history non-linear.

"Squash and Merge" adds one commit to the history, keeping the linear.

Our convention is to always do "Squash and Merge" unless there is a good reason to do something else: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/contributing.md#merging-pull-requests-for-contributors-with-write-access

**Comment by mikem8361** [comment]
Thanks. Is clear now. I guess I never picked up on the difference.

**Pull request merged**
