### PR TITLE
Fix for missing symbol OnHijackTripThread

### PR DESCRIPTION
**Pull request by jashook**
PR #6522 changed from OnHijackScalarTripThread to OnHijackTripThread; however,
missed changing this definition for arm windows.

### CODE REVIEW

**Comment by jashook** [comment]
@jkotas ptal

/cc @dotnet/jit-contrib

**Comment by briansull** [comment]
LGTM.


By the way there is still one remaining occurence of OnHijackScalarTripThread in a comment...

```
D:\ProjectK\src\NDP\clr\src\vm>findstr /n /s OnHijackScalarTripThread  *.*
amd64\unixasmhelpers.S:177:// OnHijackScalarTripThread
arm\asmhelpers.asm:1708:        NESTED_ENTRY OnHijackScalarTripThread
```

**Comment by jkotas** [comment]
Could you please also delete `OnHijackGCTripThread` from this file? It is unused after PR #6522.

**Comment by jashook** [comment]
Comments addressed

**Comment by jkotas** [comment]
👍

**Comment by briansull** [comment]
LGTM

**Comment by jashook** [comment]
Test failures are unrelated.

**Pull request merged**
