### PR TITLE
Added TryParse to StandardFormat

### PR DESCRIPTION
**Pull request by AlexejLiebenthal**
Related to dotnet/corefx#33687
Fixes issue dotnet/corefx#32950

### CODE REVIEW

**Comment by ahsonkhan** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test
@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test
@dotnet-bot test Ubuntu arm Cross Release crossgen_comparison Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT x64 Release CoreFX Tests

**Comment by AlexejLiebenthal** [comment]
@ahsonkhan Are these build errors in my scope or should a rerun of the failed builds do it?

**Comment by ahsonkhan** [comment]
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT x64 Release CoreFX Tests

**Comment by AlexejLiebenthal** [comment]
@ahsonkhan seems like `Ubuntu x64 Checked Innerloop Build and Test` and `Ubuntu x64 Checked Innerloop Build and Test (Jit - TieredCompilation=0)` were suspended?

**Comment by ahsonkhan** [comment]
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test (Jit - TieredCompilation=0)

**Comment by AlexejLiebenthal** [comment]
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test

**Pull request merged**
