### PR TITLE
 Intrinsicify SpanHelpers.IndexOfAny(char,char,char)

### LINKED ISSUE #12095: Use Intrinsics.X86 for SpanHelpers.IndexOfAny(char,char,char)
Tracking issue

Implementation available https://github.com/dotnet/coreclr/pull/22187, pending https://github.com/dotnet/coreclr/pull/22505

### PR DESCRIPTION
**Pull request by benaadams**
From #22187

Based on #22875 which is first commit

Resolves https://github.com/dotnet/coreclr/issues/22765

### CODE REVIEW

**Comment by benaadams** [comment]
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnoavx
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnosimd
@dotnet-bot test Windows_NT x64 Checked jitnox86hwintrinsic

@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnoavx
@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnosimd
@dotnet-bot test Windows_NT x86 Checked jitnox86hwintrinsic

@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnoavx
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnosimd
@dotnet-bot test Ubuntu x64 Checked jitnox86hwintrinsic

**Comment by benaadams** [comment]
Will follow up after https://github.com/dotnet/coreclr/pull/22505

**Comment by maryamariyan** [comment]
Thank you for your contribution. As announced in dotnet/coreclr#27549 this repository will be moving to dotnet/runtime on November 13. If you would like to continue working on this PR after this date, the easiest way to move the change to dotnet/runtime is:
1.	In your coreclr repository clone, create patch by running `git format-patch origin`
2.	In your runtime repository clone, apply the patch by running `git apply --directory src/coreclr <path to the patch created in step 1>`

**Comment by benaadams** [comment]
Rebased

**Comment by benaadams** [comment]
Rebased ready for review /cc @tannergooding @CarolEidt @GrabYourPitchforks

**Comment by maryamariyan** [comment]
Thank you for your contribution. As announced in #27549 the dotnet/runtime repository will be used going forward for changes to this code base. Closing this PR as no more changes will be accepted into master for this repository. If you’d like to continue working on this change please move it to dotnet/runtime.

**Pull request closed without merging**
