### PR TITLE
Marshal tests for various scenarios.

### PR DESCRIPTION
**Pull request by tijoytom**

### CODE REVIEW

**Comment by sergiy-k** [comment]
@dotnet-bot test this please

**Comment by sergiy-k** [comment]
Hi @tijoytom, please don't forget to add license header to all source files that you are adding.

**Comment by tijoytom** [comment]
@dotnet-bot test  CentOS7.1 x64 Checked Build please

**Comment by tijoytom** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Pull request merged**
