### PR TITLE
Update arm/arm64 test lists

### PR DESCRIPTION
**Pull request by sandreenko**
Update test list files with new tests that we were building, but did not run on arm.

`JIT\HardwareIntrinsics\X86` tests are excluded except one.

This PR allows me to finish adding ILGen tests for arm64(#17759).

Summary:
for arm32 490 tests were added (354 were excluded as `JIT\HardwareIntrinsics\X86`),
for arm64 489 tests were added (354 were excluded as `JIT\HardwareIntrinsics\X86`).

### CODE REVIEW

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked normal Build and Test
@dotnet-bot test Windows_NT arm Cross Checked normal Build and Test

**Comment by sandreenko** [comment]
PTAL @dotnet/jit-contrib .

**Comment by sdmaclea** [comment]
> JIT\HardwareIntrinsics\X86 tests are excluded except one.

These tests should pass on arm and arm64.  They have exposed JIT and gcstress failures on arm64.  My guess would be they would have short runtimes, because most subtests would be skipped.

**Comment by sandreenko** [comment]
> These tests should pass on arm and arm64. They have exposed JIT and gcstress failures on arm64. My guess would be they would have short runtimes, because most subtests would be skipped.

They are expected to pass, but because there won't be any recognized intrinsic it won't give as a valuable coverage. cc @CarolEidt.

We are limited in arm64 hardware in ci right now, maybe later we will be able to turn them on.

**Comment by sdmaclea** [comment]
> because there won't be any recognized intrinsic it won't give as a valuable coverage

They are the only coverage that they are not recognized as intrinsics on arm/arm64.

> limited in arm64 hardware

Understood.

**Comment by CarolEidt** [comment]
@sdmaclea - I agree that the coverage is not totally negligible, but in the interest of maximizing usage of limited resources, it seems best to not include these for now.

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT arm Cross Checked normal Build and Test
@dotnet-bot test
Windows_NT arm64 Cross Checked Innerloop Build and Test
@dotnet-bot test
Windows_NT arm64 Cross Checked normal Build and Test

**Comment by sandreenko** [comment]
@dotnet-bot test 
Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by sandreenko** [comment]
There are 3 arm failures:
```
Tests.lst=constrainedcall.cmd_11616, , , Smrt00000001, , # Loader\classloader\DefaultInterfaceMethods\constrainedcall\constrainedcall\constrainedcall.cmd  CATS: EXPECTED_PASS;NEW
Tests.lst=tracelogging.cmd_11638, , , Smrt00000001, , # tracing\tracevalidation\tracelogging\tracelogging\tracelogging.cmd  CATS: EXPECTED_PASS;NEW
Tests.lst=eventsourcetrace.cmd_11806, , , Smrt00000001, , # tracing\eventsourcetrace\eventsourcetrace\eventsourcetrace.cmd  CATS: EXPECTED_PASS;NEW
```

and many arm64:
```
Tests.lst=sharedgenerics_r.cmd_11737, , , Smrt00000001, , # Loader\classloader\DefaultInterfaceMethods\sharedgenerics\sharedgenerics_r\sharedgenerics_r.cmd  CATS: EXPECTED_PASS;NEW
Tests.lst=Tier1StackTrace.cmd_11793, , , Smrt00000001, , # baseservices\exceptions\stacktrace\Tier1StackTrace\Tier1StackTrace.cmd  CATS: EXPECTED_PASS;Pri1;NEW
Tests.lst=diamondshape_d.cmd_11786, , , Smrt00000001, , # Loader\classloader\DefaultInterfaceMethods\diamondshape\diamondshape_d\diamondshape_d.cmd  CATS: EXPECTED_PASS;NEW
Tests.lst=simple.cmd_11819, , , Smrt00000001, , # Loader\classloader\DefaultInterfaceMethods\simple\simple\simple.cmd  CATS: EXPECTED_PASS;NEW
Tests.lst=valuetypes.cmd_11883, , , Smrt00000001, , # Loader\classloader\DefaultInterfaceMethods\valuetypes\valuetypes\valuetypes.cmd  CATS: EXPECTED_PASS;NEW
Tests.lst=constrainedcall.cmd_11936, , , Smrt00000001, , # Loader\classloader\DefaultInterfaceMethods\constrainedcall\constrainedcall\constrainedcall.cmd  CATS: EXPECTED_PASS;NEW
Tests.lst=Tier1Collectible.cmd_11978, , , Smrt00000001, , # reflection\Tier1Collectible\Tier1Collectible\Tier1Collectible.cmd  CATS: EXPECTED_PASS;Pri1;NEW
Tests.lst=interfacecctor.cmd_11979, , , Smrt00000001, , # Regressions\coreclr\15650\interfacecctor\interfacecctor.cmd  CATS: EXPECTED_PASS;NEW
Tests.lst=tracelogging.cmd_11957, , , Smrt00000001, , # tracing\tracevalidation\tracelogging\tracelogging\tracelogging.cmd  CATS: EXPECTED_PASS;NEW
Tests.lst=nonvirtualcall.cmd_12018, , , Smrt00000001, , # Regressions\coreclr\15827\nonvirtualcall\nonvirtualcall.cmd  CATS: EXPECTED_PASS;NEW
Tests.lst=sharedgenerics_d.cmd_12024, , , Smrt00000001, , # Loader\classloader\DefaultInterfaceMethods\sharedgenerics\sharedgenerics_d\sharedgenerics_d.cmd  CATS: EXPECTED_PASS;NEW
Tests.lst=methodimpl.cmd_12054, , , Smrt00000001, , # Loader\classloader\DefaultInterfaceMethods\methodimpl\methodimpl\methodimpl.cmd  CATS: EXPECTED_PASS;NEW
Tests.lst=methodimpl.cmd_12058, , , Smrt00000001, , # Regressions\coreclr\16064\methodimpl\methodimpl.cmd  CATS: EXPECTED_PASS;NEW
Tests.lst=InvokeConsumer.cmd_12068, , , Smrt00000001, , # reflection\DefaultInterfaceMethods\InvokeConsumer\InvokeConsumer.cmd  CATS: EXPECTED_PASS;NEW
Tests.lst=Emit.cmd_12114, , , Smrt00000001, , # reflection\DefaultInterfaceMethods\Emit\Emit.cmd  CATS: EXPECTED_PASS;NEW
Tests.lst=eventsourcetrace.cmd_12124, , , Smrt00000001, , # tracing\eventsourcetrace\eventsourcetrace\eventsourcetrace.cmd  CATS: EXPECTED_PASS;NEW
Tests.lst=genericcontext.cmd_12173, , , Smrt00000001, , # Regressions\coreclr\15241\genericcontext\genericcontext.cmd  CATS: EXPECTED_PASS;NEW
Tests.lst=diamondshape_r.cmd_12207, , , Smrt00000001, , # Loader\classloader\DefaultInterfaceMethods\diamondshape\diamondshape_r\diamondshape_r.cmd  CATS: EXPECTED_PASS;NEW
```

**Comment by sdmaclea** [comment]
> and many arm64:

I haven't seen that many `linux-arm64` failures.  Are you seeing those on Windows or Linux?

**Comment by sandreenko** [comment]
> I haven't seen that many linux-arm64 failures. Are you seeing those on Windows or Linux?

It is from "Windows_NT arm64 Cross Checked normal Build and Test" in this PR([link](https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_checked_windows_nt_tst_prtest/579/artifact/bin/tests/Windows_NT.arm64.Checked/Smarty.run.0/Smarty.0.fail.smrt/*view*/)).

**Comment by sdmaclea** [comment]
There aren't many places arm64 should differ between linux and windows.  (ABI should be the same) #13592 & #13590 are two known unintended differences.  The assembly code is all hand ported between windows and linux so the issue could also be there.

**Comment by sandreenko** [comment]
PR was updated to exclude failing tests, I will merge it once tests pass.

**Comment by sandreenko** [comment]
@dotnet-bot test 
CentOS7.1 x64 Checked Innerloop Build and Test

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT arm Cross Checked normal Build and Test
@dotnet-bot test
Windows_NT arm64 Cross Checked Innerloop Build and Test
@dotnet-bot test
Windows_NT arm64 Cross Checked normal Build and Test

**Comment by sandreenko** [comment]
@dotnet-bot test CentOS7.1 x64 Checked Innerloop Build and Test

**Pull request merged**
