### PR TITLE
Eliminate duplicate SSA number bookkeeping

### PR DESCRIPTION
**Pull request by mikedn**
During SSA construction `SsaRenameState` keeps a definition count for each variable in an array. But each variable has a `lvPerSsaData` array that does almost the same thing, count definitions. "Almost" because `lvPerSsaData` is a `JitExpandArray` that tracks only the array size and not the number of elements actually stored in the array.

Replace `JitExpandArray` with purposely designed "array" that is in charge with allocating new SSA numbers  and handles their intricacies - `RESERVED_SSA_NUM`, `UNINIT_SSA_NUM` and `FIRST_SSA_NUM`.

This also allows the removal of the allocator from the array. Allocating new SSA numbers happens only during SSA construction and it's reasonable to pass the allocator to `AllocSsaNum` rather than increase the size of `PerSsaArray` and `LclVarDsc`.

While working on this I realized that `UNINIT_SSA_NUM` isn't actually needed. `SsaBuilder::RenameVariables` starts by assigning SSA numbers to all variables that are live at the start of `fgFirstBB` so it's not possible to encounter an use without a def on the SSA rename stack. And if it happens, well, there's a bug somewhere and falling back to minopts via a `noway_assert` is the appropriate thing to do.

No jit diffs.

0.28% less instructions retired and 0.6% less used memory.

PIN data: https://1drv.ms/x/s!Av4baJYSo5pjgr15HNl1qFfUxIWI8g

MemStats diff: https://gist.github.com/mikedn/68c76ebca65ce1c26e9d145eee420eb3

### CODE REVIEW

**Comment by mikedn** [comment]
Test [failure](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x86_release_windows_nt_innerloop_prtest/2825/testReport/junit/JIT_HardwareIntrinsics/_X86_General_VectorRet_ro_VectorRet_ro_/_X86_General_VectorRet_ro_VectorRet_ro_cmd/
) in x86 Release build appears to be unrelated:
```
D:\j\workspace\x86_release_w---80850631\bin\tests\Windows_NT.x86.Release\TestWrappers\JIT.HardwareIntrinsics\JIT.HardwareIntrinsics.XUnitWrapper.cs(6197): error : JIT_HardwareIntrinsics._X86_General_VectorRet_ro_VectorRet_ro_._X86_General_VectorRet_ro_VectorRet_ro_cmd [FAIL] [D:\j\workspace\x86_release_w---80850631\tests\runtest.proj]
        
  
  Return code:      1
  Raw output file:      D:\j\workspace\x86_release_w---80850631\bin\tests\Windows_NT.x86.Release\Reports\JIT.HardwareIntrinsics\X86\General\VectorRet_ro\VectorRet_ro.output.txt
  Raw output:
  BEGIN EXECUTION
         "D:\j\workspace\x86_release_w---80850631\tests\..\bin\tests\Windows_NT.x86.Release\Tests\Core_Root\corerun.exe" VectorRet_ro.exe 
        Expected: 100
        Actual: 1073741855
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        
  To run the test:
  > set CORE_ROOT=D:\j\workspace\x86_release_w---80850631\bin\tests\Windows_NT.x86.Release\Tests\Core_Root
  > D:\j\workspace\x86_release_w---80850631\bin\tests\Windows_NT.x86.Release\JIT\HardwareIntrinsics\X86\General\VectorRet_ro\VectorRet_ro.cmd
  
        Expected: True
        Actual:   False
          D:\j\workspace\x86_release_w---80850631\bin\tests\Windows_NT.x86.Release\TestWrappers\JIT.HardwareIntrinsics\JIT.HardwareIntrinsics.XUnitWrapper.cs(6197,0): at JIT_HardwareIntrinsics._X86_General_VectorRet_ro_VectorRet_ro_._X86_General_VectorRet_ro_VectorRet_ro_cmd()
```
Exit code seems to match [`STATUS_WX86_BREAKPOINT`](https://msdn.microsoft.com/en-us/library/cc704588.aspx), whatever that means.


Retrying.

@dotnet-bot test Windows_NT x86 Release Innerloop Build and Test

**Comment by mikedn** [comment]
@dotnet/jit-contrib Has anyone seen a test failing as above, with that specific exit code? I can't reproduce the failure locally and I don't get any jit-diffs. I thought that it's just some sort of glitch in CI but on retry it failed exactly the same way. Any suggestions how to figure out what's going on?

**Comment by CarolEidt** [comment]
@mikedn - excellent! Thanks for tracking that down.

**Comment by AndyAyersMS** [comment]
Seems like we should tag this with jit throughput too.

@mikedn anything else we need here other than review signoff?

**Comment by mikedn** [comment]
`SsaDefArray` comment fixed. 2 builds appear to have failed due to some kind of timeout:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_osx10.12_corefx_innerloop_prtest/378/consoleText
https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_ubuntu_innerloop_prtest/5452/consoleText

@dotnet-bot test OSX10.12 x64 Checked CoreFX Tests
test Ubuntu x64 Checked Innerloop Build and Test

**Comment by AndyAyersMS** [comment]
Might as well retry one more time.

@dotnet-bot retest OSX10.12 x64 Checked CoreFX Tests
@dotnet-bot retest Ubuntu x64 Checked Innerloop Build and Test

**Comment by AndyAyersMS** [comment]
Seems odd to me that we have a per-local dense array mapping ssa numbers to `LclSsaVarDsc`. Seems like this would be mostly wasted space. But maybe I don't understand what is going on well enough.

**Comment by mikedn** [comment]
> Seems odd to me that we have a per-local dense array mapping ssa numbers to LclSsaVarDsc.

You mean that perhaps there should be a single array of LclSsaVarDsc? I though about that a bit back then when I did this. Right now it's not clear if it would be better/worse/useful:
* It's not clear what it would do throughput wise - large allocations are kind of worse for arena allocator as they may leave large unused holes at the end of arena pages. It could be that resizing the array would be more costly if it turns out that many vars have only one SSA def.
* There are more changes required to make that happen. At the very least we need to do something about the VN code that assigns `VNF_InitVal` to parameters and initialized variables - it assumes that their SSA number is `FIRST_SSA_NUM`.
* Right now it doesn't seem to be useful. It may be useful if the JIT starts doing more with SSA, like relying on it for register allocation. Then it probably look at SSA definition/numbers instead of lclvars and their numbers. And then probably copy propagation wouldn't have to maintain the SSA form as it does now. And who knows what else. But that's probably far in the future.
* And if the JIT starts doing more with SSA it's not clear if this side representation of SSA defs is best. Maybe we should just get rid of lclvars and have only `GT_DEF` nodes that carry the basic block and VN pair that's now in LclSsaVarDsc.

**Comment by mikedn** [comment]
Your comment got me thinking a bit more about using a single array for SSA definitions. It's actually pretty easy to implement on top of this, we just need a bit of care with array sizing. Using `lvaTrackedCount * some small constant` should do the job.

Using a single array has the advantage of making `LclVarDsc` 16 bytes smaller, on top of this PR that already removes 8 bytes. It also seems to reduce instructions retired by a further ~0.5%.

But it's a change that can go in a separate PR, this one can be considered as a step along the way. And will probably need #15351 as well to get rid of SSA numbers being assigned to non tracked lclvars.

**Comment by mikedn** [comment]
FWIW, it looks like it would be possible to replace the SSA number stored in LclVar nodes with a pointer, without increasing the node size. Then we wouldn't need the SSA def array anymore. But that starts to move into SSA redesign territory. With a bit more work we may discover that we don't need even LclVar nodes. But that's far in the future, if ever.

**Comment by CarolEidt** [comment]
I was kind of hoping to see another, more "front-end" oriented JIT dev review this, but I've taken a look and it LGTM. I'm less familiar with the memory SSA than the lclVar SSA, but both sets of changes look reasonable to me.

These changes definitely improve the clarity - I might suggest (in future) that we change the "count" terminology (which has always thrown me).

**Comment by mikedn** [comment]
> I might suggest (in future) that we change the "count" terminology (which has always thrown me)

@CarolEidt Where? I already made many `count` -> `ssaNum` renames.

**Comment by CarolEidt** [comment]
We still refer to the ssa names / ssaNums as "counts" in places like `CountForUse` and `CountForMemoryUse`, which in that particular context seems particularly weird to me.

However, IMO we should merge this and consider doing that at another time.

**Comment by mikedn** [comment]
> We still refer to the ssa names / ssaNums as "counts" in places like CountForUse and CountForMemoryUse, which in that particular context seems particularly weird to me.

Ah, those, I'm planning to rename as part of #15000 since that cleans up the rest of the rename stack code.

**Comment by CarolEidt** [comment]
> I'm planning to rename as part of #15000 since that cleans up the rest of the rename stack code.

Awesome! A quick glance at that looks like it will be quite an improvement

**Pull request merged**
