### PR TITLE
Use nameof for parse failures

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
cc @stephentoub Using your neat pattern in more places.

**Comment by jkotas** [comment]
@dotnet/jit-contrib ARM legs are trying to run tests that I have deleted in #13510 to fix build breaks with new CoreFX. ARM legs in #13510 were green. What needs to be done to fix it?

**Comment by jashook** [comment]
These tests need to also be deleted from the arm64/arm32 lstFiles.

/cc @dotnet/jit-contrib @dotnet/arm32-contrib @dotnet/arm64-contrib

**Comment by jkotas** [comment]
@jashook Could you please take care of it?

**Pull request merged**
