### PR TITLE
Add missing System.IO APIs

### PR DESCRIPTION
**Pull request by ianhays**
This is the last chunk of APIs missing from System.IO that will be included in netstandard20 and that live in mscorlib.

progress towards https://github.com/dotnet/corefx/issues/9465

@danmosemsft I included the fusionlog property since it's listed in https://github.com/dotnet/standard/blob/master/netstandard/ref/mscorlib.cs still.

@joperezr

### CODE REVIEW

**Comment by ianhays** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by ianhays** [comment]
Thanks @joperezr, I'm all green except for some failing JIT tests for Linux-ARM. Not sure if those are expected failures as they don't seem related at all.

**Comment by joperezr** [comment]
Looks like it's not, I'm seeing some other open PRs with same issue. @jkotas should we wait for that to get fixed and the CI to pass, or is it ok to merge given that I don't believe the break is related to these changes?

**Comment by jkotas** [comment]
Yes, the Linux ARM builds are flaky,

**Pull request merged**
