### PR TITLE
Add more JIT stress modes to corefx testing

### PR DESCRIPTION
**Pull request by sejongoh**
- Add more JIT stress modes
- Checking if corefx test works well.

### CODE REVIEW

**Comment by sejongoh** [comment]
@dotnet-bot test ci

**Comment by sejongoh** [comment]
@dotnet-bot test Windows_NT corefx_jitstress1

**Comment by sejongoh** [comment]
@dotnet-bot test Windows_NT corefx_jitstress1

**Comment by sejongoh** [comment]
@dotnet-bot test ci

**Comment by sejongoh** [comment]
@mmitche Could you review the changes? I changed the scenario names to shorten the length of the workspace absolute path. Otherwise, cloning corefx fails due to long file names like below.

```
Checking out files:  84% (8037/9567)   
error: unable to create file src/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.TestNativeService/System.ServiceProcess.ServiceController.TestNativeService.vcxproj.filters (Filename too long)
17:16:50 Checking out files:  85% (8132/9567)   
Checking out files:  86% (8228/9567)   
```

**Comment by sejongoh** [comment]
@dotnet-bot test Windows_NT corefx_jitstress1

**Comment by mmitche** [comment]
@sejongoh Not sure what the deal is with the checkout failing.  Have you tried that locally?  Maybe there is something odd with the nested repos?

**Comment by mmitche** [comment]
LGTM

**Pull request merged**
