### PR TITLE
Changing Math.Max, Math.Min, Math.MaxMagnitude, and Math.MinMagnitudeto propagate NaN inputs

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves the CoreCLR side of https://github.com/dotnet/corefx/issues/36931

### CODE REVIEW

**Comment by tannergooding** [comment]
The CoreFX side is here: https://github.com/dotnet/corefx/pull/36935

**Comment by tannergooding** [comment]
CC. @karelz as an FYI

**Comment by AaronRobinsonMSFT** [comment]
Do we have tests to ensure this behavior? This is one of those behaviors that people come to rely on and shouldn't be regressed less someone's models become invalid.

**Comment by jkotas** [comment]
> Do we have tests to ensure this behavior

Yes: https://github.com/dotnet/corefx/pull/36935

**Comment by jkotas** [comment]
@Anipik Could you please check the mirror?

**Comment by Anipik** [comment]
Yes, there were some merge conflicts with mono. I resolved them and its up again. Sry for the delay

**Pull request merged**
