### PR TITLE
Unexpose IdnMapping class from corelib

### PR DESCRIPTION
**Pull request by tarekgh**
IdnMapping is already exposed from System.Globalization.Extensions and currently the libraries use that. this change is to un-expose IdnMapping from the corelib to prevent anyone take dependency on it by mistake.

### CODE REVIEW

**Comment by tarekgh** [comment]
CC @jkotas @weshaggard @danmosemsft

**Comment by jkotas** [comment]
IdnMapping is used by System.Private.Uri. We have duplicate code for IdbMapping in System.Private.Uri today because of that. Are we happy with this duplication?

**Comment by tarekgh** [comment]
> IdnMapping is used by System.Private.Uri. We have duplicate code for IdbMapping in System.Private.Uri today because of that. Are we happy with this duplication?

Yes it is sharing same code and I think this is ok as we have one copy of the source code. 
@weshaggard what you think?

**Comment by jkotas** [comment]
Also, System.Globalization.Extensions is tiny contract that I expect will be folded into some other contract...

**Comment by tarekgh** [comment]
> Also, System.Globalization.Extensions is tiny contract that I expect will be folded into some other contract...

That is a good point too. I think we already moved most of S.G.Extensions to S.Runtime. so we may consider this class too. I'll try to talk to Wes to know what he think.

**Comment by weshaggard** [comment]
We probably should fold System.Globalization.Extensions into System.Runtime and eliminate the duplication in System.Private.Uri.

**Comment by tarekgh** [comment]
ok, I'll recall this PR and will work on moving IdnMapping to System.Runtime

**Comment by weshaggard** [comment]
Why recall this PR? I still think it makes sense to remove this from CoreLib and instead just have it implemented directly in System.Runtime.

**Comment by jkotas** [comment]
> Why recall this PR? I still think it makes sense to remove this from CoreLib and instead just have it implemented directly in System.Runtime. 

System.Private.Uri cannot use it if you implement it directly in System.Runtime

**Comment by tarekgh** [comment]
@jkotas is right. System.Private.Uri is referencing the corelib and not referencing System.Runtime 

      /reference:F:\OSS\corefx\packages/Microsoft.TargetingPack.Private.CoreCLR\1.2.0-beta-24709-03\lib\netstandard1.0\System.Private.CoreLib.dll

**Comment by weshaggard** [comment]
Is there any reason it cannot reference both System.Private.CoreLib as well as the System.Runtime partial facade? I'm not aware of any and that would still allow us to remove this from CoreLib.

**Comment by jkotas** [comment]
This would be a cycle. System.Runtime partial façade depends on System.Private.Uri.

The entire globalization lives in CoreLib. Having one more globalization type to live in CoreLib does not look like a problem to me.

**Comment by weshaggard** [comment]
duh.. your right I was thinking about it the opposite direction.

**Pull request closed without merging**
