### PR TITLE
Build mscorlib on linux

### PR DESCRIPTION
**Pull request by ellismg**

### CODE REVIEW

**Comment by ellismg** [comment]
I did not notice that @atsushieno had a PR for a similar approach here until after I had completed this work (which I did because working split across Windows and Linux was getting frustrating) Some key differences are I did not copy all of the CoreFX Managed Build stuff, since much of it did not seem like we needed it.  I also didn't add code to generate a native image while running build.sh.  That's a clever idea and if @atsushieno wants me to, I'm happy to add it myself or take a patch from him.

@akoeplinger might also be interested in these changes.

**Comment by JeremyKuhne** [comment]
Awesome! LGTM

**Comment by atsushieno** [comment]
Feel free to reuse any of my changes there :-)

**Comment by akoeplinger** [comment]
Linking to @atsushieno's PR as it's not mentioned in this thread: https://github.com/dotnet/coreclr/pull/1275

Changes look good to me, cool to see that we are no longer blocked on BclRewriter :)

**Comment by ellismg** [comment]
@akoeplinger I agree.  We are working internally on porting it to the .NET Core surface area and then open sourcing it, as well.

**Comment by stephentoub** [comment]
cc: @AlexGhiondea 

LGTM

**Comment by AlexGhiondea** [comment]
LGTM! Thanks!

**Comment by atsushieno** [comment]
awesome!

**Comment by weshaggard** [comment]
Thanks @ellismg if there is any further work items please file tracking issues.

**Comment by jasonwilliams200OK** [comment]
Thanks @ellismg! 
Parenthetically, is this related: https://github.com/Microsoft/msbuild/pull/156 ?

**Comment by ellismg** [comment]
@jasonwilliams200OK.  Yes.   Our goal is to get MSBuild to target .NET Core so we can run it on CoreCLR and remove the mono dependency from our build.  I don't know how long the work is expected to take however.  I do know folks from the MSBuild team are actively engaged and we think completing the work is a high priority.

**Pull request merged**
