### PR TITLE
Fix UmAlQuraCalendar static data initilaization

### PR DESCRIPTION
**Pull request by tarekgh**
The current way of declaring the static data is cauing null reference exception
when the static constructor get called. the reason is the static initialization
method InitDateMapping is using the static array rawData which is not really
get initilaized yet when InitDateMapping execute.

The fix is moving rawData inside InitDateMapping.

https://github.com/dotnet/corefx/issues/6774#issuecomment-196044580

### CODE REVIEW

**Comment by tarekgh** [comment]
CC @jkotas

**Comment by jkotas** [comment]
LGTM

**Comment by tarekgh** [comment]
test Windows_NT x64 Debug Build and Test please

**Comment by tarekgh** [comment]
test Windows_NT x86 Release Legacy Backend Build and Test please

**Comment by tarekgh** [comment]
test Windows_NT x64 Debug Build and Test please

**Pull request merged**
