### PR TITLE
Fix all powershell invocations in scripts, CI code and tests to include -NoProfile

### PR DESCRIPTION
**Pull request by 4creators**
Code execution in several scripts and tests can be affected by powershell profile
execution at startup. Adding -NoProfile option to all powershell invocations which
may be affected by execution of profile startup code.

### CODE REVIEW

**Comment by 4creators** [comment]
Proposal to add requirement to coding guidelines to always invoke powershell with -NoProfile option is here #15165

**Comment by 4creators** [comment]
cc @weshaggard @jkotas PTAL
Changes span several areas and I am not sure who should be asked for review besides @weshaggard .

**Comment by jkotas** [comment]
@dotnet/dnceng Do you see any issues with changing all powershell invocations to pass `-NoProfile` argument?

**Comment by mmitche** [comment]
@jkotas Fine by me

**Pull request merged**
