### PR TITLE
[release/2.1] Optimize Array.Clear using SpanHelpers (#18101)

### PR DESCRIPTION
**Pull request by jkotas**
Reimplement most of Array.Clear in managed code using Span Clear helpers.

Fixes dotnet/corefx#29848

### CODE REVIEW

**Comment by danmosemsft** [comment]
This was approved and can merge when green.

@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test 
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by danmosemsft** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test please

**Comment by danmosemsft** [comment]
@dotnet/dnceng I cannot get the `@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test` job to restart?

**Comment by jkotas** [comment]
ARM64 is failure is know issue: https://github.com/dotnet/coreclr/pull/18384#issuecomment-400666730

**Pull request merged**
