### PR TITLE
Jit doesn't reload shift index if it was spilled to rcx.

### PR DESCRIPTION
**Pull request by sandreenko**
It is  DevDiv_487699 issue. Strange that we didn't see this problem before.
I am not sure does it exist in 2.0 or not.

I added commits with test and the right assert to make sure that ci repro the problem.
The fix will be added later.

### CODE REVIEW

**Comment by sandreenko** [comment]
cc @dotnet/jit-contrib

**Comment by CarolEidt** [comment]
I would wait to add the assert and test until you have a fix

**Comment by sandreenko** [comment]
Yes, of course. I will add it in this PR.

**Comment by sandreenko** [comment]
PR was finished, PTAL @CarolEidt.

**Comment by sandreenko** [comment]
@dotnet-bot test Tizen armel Cross Debug Build

**Comment by sandreenko** [comment]
@dotnet-bot test Tizen armel Cross Debug Build

**Pull request merged**
