### PR TITLE
Build core_root layout before doing PMI asm diffs

### PR DESCRIPTION
**Pull request by BruceForstall**

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet-bot test ci please

**Comment by mikedn** [comment]
Hmm, asm diffs in CI, nice. But I'm curious, how do all these CI changes you're making play with arcade and the new CI?

**Comment by BruceForstall** [comment]
> Hmm, asm diffs in CI, nice. But I'm curious, how do all these CI changes you're making play with arcade and the new CI?

No idea! I'm sure there will be a transition, maybe painful. But this will give us experience to determine if this is a good system, or how it should be different.

**Comment by mikedn** [comment]
> No idea! I'm sure there will be a transition, maybe painful. But this will give us experience to determine if this is a good system, or how it should be different.

Hmm, I guess what bugs me the most is that now there's this giant groovy script that pulls build definitions out of a hat and keeps getting tweaked, this doesn't seem to have a place in the new CI :smile:

**Comment by BruceForstall** [comment]
Yeah, I don't know how that works in the "new world". But if we waited for the "new world", we'd never get anything done. FWIW, we're trying to put more logic in the scripts (for the asm diffing), namely tests\scripts\run-pmi-diffs.py added as part of this effort. If our builds were easier (like, a single consistent command, compared to where we are now), that would make the groovy file much smaller.

**Pull request merged**
