### PR TITLE
Update CoreCLR repo nuget packages to version as 1.1.1.

### PR DESCRIPTION
**Pull request by gkhanna79**
@ericstj PTAL

CC @leecow @schellap

### CODE REVIEW

**Comment by gkhanna79** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build and Test please

**Comment by gkhanna79** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build and Test please

**Comment by gkhanna79** [comment]
@dotnet test Linux ARM Emulator Cross Release Build please

**Comment by gkhanna79** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by gkhanna79** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by gkhanna79** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by gkhanna79** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by gkhanna79** [comment]
@ericstj @weshaggard Could one of you PTAL?

**Comment by weshaggard** [comment]
LGTM - Are you doing this preemptively or do we expect to ship a 1.1.1?

**Pull request merged**
