### PR TITLE
Add optional arguments for choosing clang version and verbose build output

### LINKED ISSUE #740: Bump Clang version to 3.6?
I want to discuss switch to Clang 3.6 for compiling CoreCLR. We are already using LLDB from the LLVM 3.6 release. It would be more consistent to use Clang from the same release.

For the Ubuntu 14.04 machines I created a PPA, which brings the LLVM 3.6 release from Ubuntu 15.04 to Ubuntu 14.04. It is available here: https://launchpad.net/~jhe/+archive/ubuntu/llvm-toolchain

### PR DESCRIPTION
**Pull request by janhenke**
This commit adds two optional arguments to build.sh. The "verbose" option
enables verbose build output. This can be useful to debug build failures by
seeing the complete command line used to invoke the build.
The other option is "clangx.y", which allows to specify the clang version used
for the build. This makes it easy to test different clang versions and aid
future migration to newer clang releases and other platforms. Closes #740

### CODE REVIEW

**Comment by richlander** [comment]
I see that the Clang versions are hard-coded in the script. This has two challenges:

- The script grows over time (with Clang releases) while we wait to re-set the Clang baseline.
- People have to wait for us or edit the script in order to use a new Clang version.

Thoughts?

**Comment by janhenke** [comment]
It is the most simple solution. Dynamically parsing the version adds a lot of complexity to the script, which I think is not worth the effort at the moment.
If the number of possible version grows too big (thus the complexity of this way grows too big) we can still switch to a more sophisticated solution.
New Clang version are released roughly once every 6 month, I think the second point is a non issue. I already added 3.7, even though it is not going to be released until much later this year.

**Comment by jkotas** [comment]
LGTM

**Comment by kangaroo** [comment]
LGTM

**Pull request merged**
