### PR TITLE
Branchless `System.Index.GetOffset`

### PR DESCRIPTION
**Pull request by VSadov**

### CODE REVIEW

**Comment by VSadov** [comment]
Will have to do some benchmarking to be sure it is faster.

**Comment by GrabYourPitchforks** [comment]
If `_value` is constant (e.g., the literal `^5` is passed to the indexer), wouldn't this change make the `GetOffset` method now three instructions (add | and | add) where previously it would've been at most one (lea)?

**Comment by GrabYourPitchforks** [comment]
Possibly something that could benefit from https://github.com/dotnet/coreclr/issues/21033, where we'd want to choose the branching vs. branchless code path based on whether or not `_value` is known to be const.

**Comment by mikedn** [comment]
Seems like the JIT should fold the `_value` constant case just fine:

* `_value + ((length + 1) & (_value >> 31))`
* `_value + ((length + 1) & (0 or -1))`
* `_value or _value + length + 1`
* `_value or length + (1 + _value)`

Not sure if it actually does that but I don't see any obvious problem that would prevent it from doing it. Maybe addition re-association.

**Comment by GrabYourPitchforks** [comment]
Ah, good point!

**Comment by mikedn** [comment]
Blargh, JIT doesn't know that `x & -1 == x`. We'll need to fix that so we actually get
```asm
       8D41FB               lea      eax, [rcx-5]       8D41FB               lea      eax, [rcx-5]

**Comment by VSadov** [comment]
Yes. The JIT seems to know that `x & 0 == 0`, but not that `x & -1 == x`. 
I.E. it folds `5`, but not `^5`.

Must be an easy thing to add.
@AndyAyersMS

**Comment by VSadov** [comment]
Sadly this is slower than original.

```
|        Method |     Mean |     Error |    StdDev |
|-------------- |---------:|----------:|----------:|
|  NewFromStart | 757.4 ms | 1.2315 ms | 1.0917 ms |
| OrigFromStart | 742.8 ms | 0.7013 ms | 0.6217 ms |
|    NewFromEnd | 833.1 ms | 0.8280 ms | 0.7745 ms |
|   OrigFromEnd | 793.7 ms | 0.9547 ms | 0.8463 ms |
```

That is on Kaby Lake x64. 

I guess the level of speculation in modern CPUs makes predictable branches nearly free and "poor man's predication" is no longer a profitable pattern. 
I also think most interesting cases of indexing will be very predictable (loops, contiguous accesses).

**Comment by VSadov** [comment]
My benchmark, if anyone is interested.
( run with  `set COMPlus_TieredCompilation=0`, otherwise everything takes roughly the same time )

```CS
        string str = new string('a', 2048);

        static void Main(string[] args)
        {
            var summary = BenchmarkRunner.Run<Program>();
        }

        [Benchmark]
        public int NewFromStart()
        {
            ReadOnlySpan<char> span = str.AsSpan();

            char result = ' ';

            for (int i = 0; i < 1000000; i++)
            {
                for (int j = 0; j < 1023; j++)
                {
                    result ^= span[GetOffset(j, span.Length)];
                }
            }

            return result;
        }

        [Benchmark]
        public int OrigFromStart()
        {
            ReadOnlySpan<char> span = str.AsSpan();

            char result = ' ';

            for (int i = 0; i < 1000000; i++)
            {
                for (int j = 0; j < 1023; j++)
                {
                    result ^= span[GetOffset1(j, span.Length)];
                }
            }

            return result;
        }

        [Benchmark]
        public int NewFromEnd()
        {
            ReadOnlySpan<char> span = str.AsSpan();

            char result = ' ';

            for (int i = 0; i < 1000000; i++)
            {
                for (int j = 1; j < 1024; j++)
                {
                    result ^= span[GetOffset(~j, span.Length)];
                }
            }

            return result;
        }

        [Benchmark]
        public int OrigFromEnd()
        {
            ReadOnlySpan<char> span = str.AsSpan();

            char result = ' ';

            for (int i = 0; i < 1000000; i++)
            {
                for (int j = 1; j < 1024; j++)
                {
                    result ^= span[GetOffset1(~j, span.Length)];
                }
            }

            return result;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe int GetOffset(int _value, int length)
        {
            return unchecked(_value + ((_value >> 31) & (length + 1)));
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe int GetOffset1(int _value, int length)
        {
            int offset = _value;
            if (_value < 0)
            {
                offset += length + 1;
            }
            return offset;
        }
```

**Comment by GrabYourPitchforks** [comment]
I wonder if it would make sense to make `Span.get_Item[Index]` aware of the internal structure of the `Index` type. If for whatever reason the branching version is faster due to the "from beginning" branch being generally predicted, this could be collapsed such that the common case has a single correctly predicted branch rather than two correctly predicted branches.

```cs
public ref T this[Index index]
{
    get
    {
        int value = index._value;
        if ((uint)value < (uint)this.Length)
        {
            return ref Unsafe.Add(ref this._pointer.Value, value);
        }
        else
        {
            value += this.Length + 1;
            if ((uint)value < (uint)this.Length)
            {
                return ref Unsafe.Add(ref this._pointer.Value, value);
            }
            else
            {
                /* FAIL */
            }
        }
    }
}
```

**Comment by GrabYourPitchforks** [comment]
If the second branch in my comment immediately above could somehow be converted to the following, that would be even better.

```asm
mov newIndex, length
neg value
sub newIndex, value
jnb FAIL    ; use flags from previous sub instruction rather than requiring a brand new cmp
```

**Comment by mikedn** [comment]
> Must be an easy thing to add.

Yes, adding `x & -1 == x` is trivial. But there are only a couple of hits in the entire FX so I'm not sure it's worthwhile unless this gets in. And as seen above this is more complicated than it seems.

I'll try to run the benchmark too, I'm curious if it makes any difference on my CPU (a Haswell).

**Comment by mikedn** [comment]
I ran the benchmark and I too see lower performance. In fact on my machine the difference is even bigger, NewFromStart is 20% slower.

Not that surprising, it's kind of difficult to beat a predictable branch
```asm
G_M33347_IG07:
       458BD1               mov      r10d, r9d
       4585D2               test     r10d, r10d
       7D05                 jge      SHORT G_M33347_IG08
       478D540201           lea      r10d, [r10+r8+1]
G_M33347_IG08:
       453BD0               cmp      r10d, r8d
       732F                 jae      SHORT G_M33347_IG12
       4D63D2               movsxd   r10, r10d
       460FB71450           movzx    r10, word  ptr [rax+2*r10]
       4133D2               xor      edx, r10d
       0FB7D2               movzx    rdx, dx
       41FFC1               inc      r9d
       4181F9FF030000       cmp      r9d, 0x3FF
       7CD4                 jl       SHORT G_M33347_IG07
```
with
```asm
       458D5001             lea      r10d, [r8+1]
G_M48188_IG07:
       458BD9               mov      r11d, r9d
       41C1FB1F             sar      r11d, 31
       4523DA               and      r11d, r10d
       4503D9               add      r11d, r9d
       453BD8               cmp      r11d, r8d
       732F                 jae      SHORT G_M48188_IG11
       4D63DB               movsxd   r11, r11d
       460FB71C58           movzx    r11, word  ptr [rax+2*r11]
       4133D3               xor      edx, r11d
       0FB7D2               movzx    rdx, dx
       41FFC1               inc      r9d
       4181F9FF030000       cmp      r9d, 0x3FF
       7CD4                 jl       SHORT G_M48188_IG07
```
when the code is part of a giant dependency chain. The branchless implementation just adds latency.

**Comment by VSadov** [comment]
Yeah. Perhaps a tweak like this might work in a case of unpredictable branch, but heavy indexing, I believe, will generally form a predictable pattern - such as loop or repeated access.

And for predictable cases current implementation works better.

**Pull request closed without merging**
