### PR TITLE
Fix validation code in Sse2.MultiplyLow tests

### LINKED ISSUE #16153: [Test Failure] the `Sse2.MultiplyLow` test fails for some inputs.
See https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_jitx86hwintrinsicnoavx_prtest/56/, for an example.

### PR DESCRIPTION
**Pull request by 4creators**
Fixes #16153

### CODE REVIEW

**Comment by 4creators** [comment]
@tannergooding This PR fixes MultiplyLow problems. Should I run all 16 stress jobs or only those which failing?

**Comment by 4creators** [comment]
test Windows_NT x64 Checked jitincompletehwintrinsic
test Windows_NT x64 Checked jitx86hwintrinsicnoavx
test Windows_NT x64 Checked jitx86hwintrinsicnoavx2
test Windows_NT x64 Checked jitx86hwintrinsicnosimd
test Windows_NT x64 Checked jitnox86hwintrinsic

test Windows_NT x86 Checked jitincompletehwintrinsic
test Windows_NT x86 Checked jitx86hwintrinsicnoavx
test Windows_NT x86 Checked jitx86hwintrinsicnoavx2
test Windows_NT x86 Checked jitx86hwintrinsicnosimd
test Windows_NT x86 Checked jitnox86hwintrinsic

test Ubuntu x64 Checked jitincompletehwintrinsic
test Ubuntu x64 Checked jitx86hwintrinsicnoavx
test Ubuntu x64 Checked jitx86hwintrinsicnoavx2
test Ubuntu x64 Checked jitx86hwintrinsicnosimd
test Ubuntu x64 Checked jitnox86hwintrinsic

test OSX10.12 x64 Checked jitincompletehwintrinsic
test OSX10.12 x64 Checked jitx86hwintrinsicnoavx
test OSX10.12 x64 Checked jitx86hwintrinsicnoavx2
test OSX10.12 x64 Checked jitx86hwintrinsicnosimd
test OSX10.12 x64 Checked jitnox86hwintrinsic

**Comment by tannergooding** [comment]
Sorry. Missed your comment. All 16 is desirable, since this was flaky and could happen on any job

**Comment by 4creators** [comment]
@dotnet-bot test Tizen armel Cross Checked Innerloop Build and Test please

**Comment by 4creators** [comment]
All three failures are timeouts. Rerunning tests:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_osx10.12_jitx86hwintrinsicnosimd_flow_prtest/23/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_jitincompletehwintrinsic_flow_prtest/37/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_jitx86hwintrinsicnoavx2_flow_prtest/39/

**Comment by 4creators** [comment]
test OSX10.12 x64 Checked jitx86hwintrinsicnosimd
test Ubuntu x64 Checked jitx86hwintrinsicnoavx2
test Ubuntu x64 Checked jitincompletehwintrinsic

**Comment by 4creators** [comment]
@CarolEidt @fiigii  PTAL

**Pull request merged**
