### PR TITLE
Add windowsmscorlib option to build.cmd

### PR DESCRIPTION
**Pull request by stephentoub**

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @AlexGhiondea, @jkotas

**Comment by justinvp** [comment]
:+1:

**Comment by jasonwilliams200OK** [comment]
Should we have one for BSD as well? Although it will call the subroutine meant for Linux (for now?), but it would make it bit less confusing for BSD guys.
@josteink

**Comment by jkotas** [comment]
LGTM

**Comment by josteink** [comment]
@jasonwilliams200OK good idea. Sound like you have a pr to author :)

**Pull request merged**
