### PR TITLE
Fix script ERRORLEVEL typo

### PR DESCRIPTION
**Pull request by sdmaclea**
@wtgodbe PTAL

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
Looks like the same mistake is also in the ILASM section right below.

cc: @kyulee1

**Comment by sdmaclea** [comment]
Thanks, I should have caught that...  Fixed.

**Comment by sdmaclea** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test please

**Comment by sdmaclea** [comment]
@dotnet-bot test Windows_NT x86 Checked Build and Test please

**Comment by adityamandaleeka** [comment]
Thanks @sdmaclea.

**Pull request merged**
