### PR TITLE
Delete a bad test (b06435) for double to long conversion

### PR DESCRIPTION
**Pull request by kyulee1**
This test relies on unspecified value when a large double value
is converted to a long value where overflow occurs.
For x64(cvttsd2si), this value is MIN_INT(0x8000000000000000) while ARM64(fcvtzs) produces MAX_INT(0x7fffffffffffffff).
According to ECMA spec, the value is unspecified, so I simply delete this test.

### CODE REVIEW

**Comment by kyulee1** [comment]
@dotnet/jit-contrib PTAL

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test

**Comment by kyulee1** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Comment by pgavlin** [comment]
LGTM

**Pull request merged**
