### PR TITLE
Add identity.cpp to build.

### PR DESCRIPTION
**Pull request by Priya91**
Required for ```GetComputerNameW``` to be exposed in Environment.MachineName.

### CODE REVIEW

**Comment by stephentoub** [comment]
```
01:43:58 /mnt/j/workspace/dotnet_coreclr/release_ubuntu_prtest/src/pal/src/misc/identity.cpp:170:29: error: no matching function for call to 'InternalMalloc'
01:43:58         pchBuffer = (char*) InternalMalloc(pPalThread, sizeof(pchBuffer[0]) * dwBufLen);
01:43:58                             ^~~~~~~~~~~~~~
01:43:58 /mnt/j/workspace/dotnet_coreclr/release_ubuntu_prtest/src/pal/src/include/pal/malloc.hpp:73:5: note: candidate function not viable: requires single argument 'szSize', but 2 arguments were provided
01:43:58     InternalMalloc(
01:43:58     ^
01:43:58 /mnt/j/workspace/dotnet_coreclr/release_ubuntu_prtest/src/pal/src/misc/identity.cpp:185:17: error: no matching function for call to 'InternalFree'
01:43:58                 InternalFree(pPalThread, pchBuffer);
01:43:58                 ^~~~~~~~~~~~
01:43:58 /mnt/j/workspace/dotnet_coreclr/release_ubuntu_prtest/src/pal/src/include/pal/malloc.hpp:78:5: note: candidate function not viable: requires single argument 'pvMem', but 2 arguments were provided
01:43:58     InternalFree(
01:43:58     ^
01:43:58 /mnt/j/workspace/dotnet_coreclr/release_ubuntu_prtest/src/pal/src/misc/identity.cpp:277:9: error: no matching function for call to 'InternalFree'
01:43:58         InternalFree(pPalThread, pchBuffer);
01:43:58         ^~~~~~~~~~~~
01:43:58 /mnt/j/workspace/dotnet_coreclr/release_ubuntu_prtest/src/pal/src/include/pal/malloc.hpp:78:5: note: candidate function not viable: requires single argument 'pvMem', but 2 arguments were provided
01:43:58     InternalFree(
01:43:58     ^
01:43:58 3 errors generated.
01:43:58 make[2]: *** [src/pal/src/CMakeFiles/coreclrpal.dir/misc/identity.cpp.o] Error 1
```

**Comment by jkotas** [comment]
Also, could you please verify that the implementation actually works by running the tests that you have written?

I suspect that there will be more fixes required - e.g. the logic that clips the name to 15 characters does not look like something we want on Unix.

**Comment by Priya91** [comment]
@jkotas Ran the corefx and the pal tests. It works locally.

**Comment by Priya91** [comment]
On FREEBSD, the gethostname returns the value set by sethostname. Looking at the code [here](https://github.com/freebsd/freebsd/blob/0f2211c30ded7871b441bfaa1647843f1b4fd0c2/lib/libc/gen/gethostname.c), these functions are reading the kernel state KERN_HOSTNAME. It is not clear how this is set, and hence it's possible that this string is empty. Modifying tests to allow for empty strings from gethostname to unblock test failures on FREEBSD.

**Comment by Priya91** [comment]
@jkotas Can you please review for merge. Thanks!

**Comment by jkotas** [comment]
LGTM

**Pull request merged**
