### PR TITLE
Fix handling of incorrect assemblies on Unix

### PR DESCRIPTION
**Pull request by ruben-ayrapetyan**
This fixes the regression introduced by #10772.
The regression was caused by a missing check for validity of loaded assembly file.

Related issue: #15544

### CODE REVIEW

**Comment by ruben-ayrapetyan** [comment]
@dotnet-bot Help, please

**Comment by ruben-ayrapetyan** [comment]
@jkotas, @maryamariyan, @gbalykov,
Please, take a look.

**Comment by jkotas** [comment]
Thanks for fixing this!

**Comment by jkotas** [comment]
@ruben-ayrapetyan I am sorry, but I had to revert this because of broke CoreFX: https://github.com/dotnet/coreclr/pull/16790

**Comment by ruben-ayrapetyan** [comment]
> @ruben-ayrapetyan I am sorry, but I had to revert this because of broke CoreFX: #16790

// Brief summary

There were several issues. Detailed debugging revealed that this change is not the cause of failure.
The revert is now reverted by https://github.com/dotnet/coreclr/pull/16917
<br/>
Details are in this thread: https://github.com/dotnet/corefx/pull/27737#issuecomment-372596193

**Pull request merged**
