### PR TITLE
Preserve VNs in fgMorphIntoHelperCall.

### PR DESCRIPTION
**Pull request by pgavlin**
This method is used to transform a node into a semantically-equivalent
helper call, and should preserve any value numbers that are present on
the the node.

### CODE REVIEW

**Comment by pgavlin** [comment]
@briansull @JosephTremoulet @dotnet/jit-contrib PTAL

**Comment by pgavlin** [comment]
> Wouldn't hurt to put some comments in the testcase indicating what the issue was. Does it fail to compile without this fix, or just produce slower code?

Can do. The original repro was yet another remorphing bug: remorphing during CSE was changing a long-typed `GT_UMOD` to a helper call without preserving the value number, which was causing some code that attempted to extract exceptions from VNs to fail.

**Comment by briansull** [comment]
Looks fine

**Comment by pgavlin** [comment]
The two failing builds timed out.

@dotnet-bot 
test Ubuntu arm Cross Release Build
test Windows_NT x64 Debug Build and Test

**Pull request merged**
