### PR TITLE
Remove FEATURE_ACTIVITYSAMPLING and Associated Code

### PR DESCRIPTION
**Pull request by brianrob**
ActivitySampling is not available on Core, ProjectN or the EventSource nuget package.  Thus, it can be removed from the source base to simplify maintenance of EventSource.

### CODE REVIEW

**Comment by brianrob** [comment]
@vancem, I have confirmed that FEATURE_ACTIVITYSAMPLING is not enabled on Core, ProjectN or the EventSource nuget package, which makes it dead code in this source base.

Most of this review is deletions, but EventSource_CoreCLR.cs does contain some small simplifications to code, so please be sure to look at this.

**Comment by brianrob** [comment]
Run EventSource tests: @dotnet-bot test Windows_NT x64 Checked corefx_baseline

**Comment by stephentoub** [comment]
What is the activity sampling feature? Should it be enabled in core, or it's only applicable to netfx?

**Comment by brianrob** [comment]
@stephentoub, it is a feature designed to allow for sampling of activities.  Basically, you can attempt to reduce the size of your trace files by sampling, but rather than sampling at the event level you sample at the activity level so that you can get full-fidelity traces, but just for single activities.  Unfortunately, it doesn't actually work, has some fundamental issues, and arguably should have been removed earlier.

The feature has only ever been enabled on desktop, but has never been documented.  Per my conversation with @vancem, we should remove it from core (I'm doing this as a preemptive step before doing some EventSource refactoring) and then we should look at the possibility of removing it from desktop - it does not have any public APIs and has never been documented.

**Comment by stephentoub** [comment]
Ok, thanks for the explanation.

**Comment by brianrob** [comment]
Run EventSource tests one more time due to failures around moving Vector<T> to System.Private.CoreLib: @dotnet-bot test Windows_NT x64 Checked corefx_baseline

**Comment by brianrob** [comment]
I am validating that the corefx failures are unrelated before merging.

**Comment by brianrob** [comment]
These failures are not related to this change and are occurring in other CI jobs.

**Pull request merged**
