### PR TITLE
Fix GitHub #20389

### LINKED ISSUE #20389: Test failure: JIT_HardwareIntrinsics._X86_General_VectorUnused_r_VectorUnused_r_/_X86_General_VectorUnused_r_VectorUnused_r_cmd
Opened on behalf of @Sunny-pu

The test `JIT_HardwareIntrinsics._X86_General_VectorUnused_r_VectorUnused_r_/_X86_General_VectorUnused_r_VectorUnused_r_cmd` has failed.

    Unhandled Exception: System.PlatformNotSupportedException: Operation is not supported on this platform.
       at System.Runtime.Intrinsics.X86.Avx2.Add(Vector256`1 left, Vector256`1 right)
       at IntelHardwareIntrinsicTest.Vector256Add[T](Vector256`1 left, Vector256`1 right) in E:\\A\\_work\\4\\s\\tests\\src\\JIT\\HardwareIntrinsics\\X86\\General\\VectorHelpers.cs:line 82
       at IntelHardwareIntrinsicTest.Vector256UnusedTest`1.VectorUnused(T t1, T t2) in E:\\A\\_work\\4\\s\\tests\\src\\JIT\\HardwareIntrinsics\\X86\\General\\VectorUnused.cs:line 39
       at IntelHardwareIntrinsicTest.Main() in E:\\A\\_work\\4\\s\\tests\\src\\JIT\\HardwareIntrinsics\\X86\\General\\VectorUnused.cs:line 65
    /Users/dotnet-bot/dotnetbuild/work/1baa3d18-4140-4589-b81d-ccec4bcd2361/Work/d8936dc9-b719-4aa4-95e5-4b8ba624b8dc/Unzip/X86/General/VectorUnused_r/VectorUnused_r.sh: line 244: 50876 Abort trap: 6           $_DebuggerFullPath \"$CORE_ROOT/corerun\" $ExePath $CLRTestExecutionArguments
    
    
    Return code:      1
    Raw output file:      /Users/dotnet-bot/dotnetbuild/work/1baa3d18-4140-4589-b81d-ccec4bcd2361/Work/d8936dc9-b719-4aa4-95e5-4b8ba624b8dc/Unzip/Reports\\JIT.HardwareIntrinsics\\X86\\General\\VectorUnused_r\\VectorUnused_r.output.txt
    Raw output:
    BEGIN EXECUTION
    in takeLock
    /Users/dotnet-bot/dotnetbuild/work/1baa3d18-4140-4589-b81d-ccec4bcd2361/Payload/crossgen /Platform_Assemblies_Paths /Users/dotnet-bot/dotnetbuild/work/1baa3d18-4140-4589-b81d-ccec4bcd2361/Payload:/Users/dotnet-bot/dotnetbuild/work/1baa3d18-4140-4589-b81d-ccec4bcd2361/Work/d8936dc9-b719-4aa4-95e5-4b8ba624b8dc/Unzip/X86/General/VectorUnused_r/IL:/Users/dotnet-bot/dotnetbuild/work/1baa3d18-4140-4589-b81d-ccec4bcd2361/Work/d8936dc9-b719-4aa4-95e5-4b8ba624b8dc/Unzip/X86/General/VectorUnused_r /in VectorUnused_r.org /out VectorUnused_r.exe
    Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
    Copyright (c) Microsoft Corporation.  All rights reserved.
    
    Native image VectorUnused_r.exe generated successfully.
    in ReleaseLock
    in takeLock
    /Users/dotnet-bot/dotnetbuild/work/1baa3d18-4140-4589-b81d-ccec4bcd2361/Payload/corerun VectorUnused_r.exe
    in ReleaseLock
    Expected: 100
    Actual: 134
    END EXECUTION - FAILED
    Test Harness Exitcode is : 1
    
    To run the test:
    > set CORE_ROOT=/Users/dotnet-bot/dotnetbuild/work/1baa3d18-4140-4589-b81d-ccec4bcd2361/Payload
    > /Users/dotnet-bot/dotnetbuild/work/1baa3d18-4140-4589-b81d-ccec4bcd2361/Work/d8936dc9-b719-4aa4-95e5-4b8ba624b8dc/Unzip/X86/General/VectorUnused_r/VectorUnused_r.sh
    
    Expected: True
    Actual:   False

        Stack Trace:

           at JIT_HardwareIntrinsics._X86_General_VectorUnused_r_VectorUnused_r_._X86_General_VectorUnused_r_VectorUnused_r_cmd() in E:\A\_work\4\s\bin\tests\Windows_NT.x64.Release\TestWrappers\JIT.HardwareIntrinsics\JIT.HardwareIntrinsics.XUnitWrapper.cs:line 8091
Build : 3.0 - 20181012.01 (Ready-To-Run Tests)
Failing configurations:
- osx.1013.amd64
  - x64

Details: https://mc.dot.net/#/product/netcore/30/source/official~2Fcoreclr~2Fmaster~2F/type/test~2Ffunctional~2Fr2r~2Fcli~2F/build/20181012.01/workItem/JIT.HardwareIntrinsics.XUnitWrapper/analysis/xunit/JIT_HardwareIntrinsics._X86_General_VectorUnused_r_VectorUnused_r_~2F_X86_General_VectorUnused_r_VectorUnused_r_cmd

### PR DESCRIPTION
**Pull request by fiigii**
Fix #20389

@CarolEidt @AriNuer @Sunny-pu

### CODE REVIEW

**Comment by danmosemsft** [comment]
Why does it need to check for Avx2 if its only using Avx?

**Comment by fiigii** [comment]
Integer SIMD addition instructions are provided by AVX2 (AVX just has floating point instructions).

**Comment by danmosemsft** [comment]
So if I understand right, `public static Vector256<T> SetAllVector256<T>(T value) where T : struct` (which is not on the Avx2 class) requires Avx2 when T is an integer type? If so, it seems to me this is likely to be a common mistake, which presumably will only show up when someone tests on a machine that does not support AVX2?

@tannergooding

**Comment by tannergooding** [comment]
Correct.

**Comment by fiigii** [comment]
@tannergooding Thanks for the reply 😄 
@danmosemsft Can we merge this PR?

**Comment by danmosemsft** [comment]
@tannergooding can sign off

**Pull request merged**
