### PR TITLE
Enable multi-byte NOP in RyuJIT/x86

### LINKED ISSUE #14128: Enable multi-byte NOP in RyuJIT/x86
Multi-byte NOP is always preferred over multiple one-byte NOPs on modern x86 architectures. Currently, RyuJIT generates multi-byte NOPs for x64 but uses multiple one-byte NOP for x86.
```cpp
#ifndef _TARGET_AMD64_
    // TODO-X86-CQ: when VIA C3 CPU's are out of circulation, switch to the
    // more efficient real NOP: 0x0F 0x1F +modR/M
    // Also can't use AMD recommended, multiple size prefixes (i.e. 0x66 0x66 0x90 for 3 byte NOP)
    // because debugger and msdis don't like it, so maybe VIA doesn't either
    // So instead just stick to repeating single byte nops

    switch (nBytes)
    {
        case 15:
            *dst++ = 0x90;
            __fallthrough;
        case 14:
            *dst++ = 0x90;
            __fallthrough;
        case 13:
            *dst++ = 0x90;
            __fallthrough;
        case 12:
            *dst++ = 0x90;
            __fallthrough;
```
Since RyuJIT requires SSE2 as the bottom-line target for its codegen, we should optimize RyuJIT/x86 to generate multi-byte NOP.

cc @russellhadley @BruceForstall @jkotas

### PR DESCRIPTION
**Pull request by fiigii**
Fix #14128

### CODE REVIEW

**Comment by jkotas** [comment]
There are a lot of x86 tests failing because this is ABI breaking change - the runtime is looking for the nops as a marked, and it does not recognizes the new encoding. What needs to happen:
- This ABI for nops around stub dispatch calls should be documented in https://github.com/dotnet/coreclr/blob/master/Documentation/botr/clr-abi.md. I see it is missing there.
- Runtime needs to be updated to recognize the new encoding (in addition to the old one)
- `READYTORUN_MAJOR_VERSION` needs to be bumped up because of the new R2R images will only run on the new runtime now.

**Comment by jkotas** [comment]
The GC encoding `vm\eetwain.cpp` seems to be sensitive to nop encoding as well.

**Comment by fiigii** [comment]
@jkotas Thank you! I will look into the vm side and try to solve these ABI breaking.

**Comment by BruceForstall** [comment]
The "TODO" comment mentions debugging and msdis also having a problem with the multi-byte NOPs. How are you testing to make sure those can handle all lengths of the new NOP sequences?

**Comment by fiigii** [comment]
> The "TODO" comment mentions debugging and msdis also having a problem with the multi-byte NOPs. 
> // Also can't use AMD recommended, multiple size prefixes (i.e. 0x66 0x66 0x90 for 3 byte NOP)

The comment seems to mean that the "debugging" problem is only from "0x66 0x66 0x90 for 3 byte NOP". Did I misunderstand? 

> How are you testing to make sure those can handle all lengths of the new NOP sequences?

I am not sure how hard it is to keep the compatibility with 1-byte NOP in RyuJIT/x86, so I am just following @jkotas 's suggestions to check the vm's code now. @BruceForstall Do you have any suggestion?

**Comment by jkotas** [comment]
Closing inactive PR. Feel free to submit a new PR if you get a chance to finish this.

**Pull request closed without merging**
