### PR TITLE
Port Span.IndexOf/SequentialEqual to fast Span

### PR DESCRIPTION
**Pull request by AtsushiKan**
This is literally a copy-paste (or in some cases,
a copy file) from corefx - model.xml and
mscorlib.shared.sources.props contain the
only manually written changes.

### CODE REVIEW

**Comment by AtsushiKan** [comment]
cc @KrzysztofCwalina

**Comment by KrzysztofCwalina** [comment]
I expected the code to be slightly different. If it's the same, can't we just keep it in corefx? We would build two System.Memory binaries, one type forwarding Spans to corlib and one that does not. Rest of the type would always come from System.Memory.

@weshaggard, @ericstj, is that the best way to do it?

**Comment by AtsushiKan** [comment]
It might not stay the same once we start optimizing for real…

One problem is that these won’t be the only methods in SpanExtensions – they all have to be “portable” for this to work.

**Comment by jkotas** [comment]
> It might not stay the same once we start optimizing for real…

We should move it once we have a good reason for it to be in CoreLib. Until then, we should keep these extension methods in corefx.

**Comment by jkotas** [comment]
> they all have to be “portable” for this to work

If needed, you can have a CoreCLR-specific tweaks in corefx as well. The code will be build twice anyway. The only real advantage you get in CoreLib is writing stuff in C++ or assembly; or access to runtime internals. I do not think we are going to need it for these extension methods.

**Comment by AtsushiKan** [comment]
Looks like the plan going forward is to not type-forward SpanExtensions - just Span itself.

**Pull request closed without merging**
