### PR TITLE
Initial Ready-to-Run tests for generics

### PR DESCRIPTION
**Pull request by JohnChen0**
* Added some generics tests intended for testing Ready-to-Run feature.
* Added capability to set ZapRequire=1, to  ensure methods are
  pre-compiled.
* Fix spelling of environment variables for case-sensitive platforms.

### CODE REVIEW

**Comment by JohnChen0** [comment]
@fadimounir @jkotas PTAL

**Comment by jkotas** [comment]
I assume that you are going to turn this into the versioning test as a next step. Would it make sense to add all R2R tests under `tests\src\readytorun`?

**Comment by JohnChen0** [comment]
This part of the test is intended to be a functional test for generics in r2r. It covers the problematic areas that I encountered during coding this feature. It supplements existing generics tests, with the addition of `ZapRequire=1` to ensure that all methods are compiled by r2r. I can move this to `tests\src\readytorun`. There are also additional function tests that @fadimounir had given me, which I'll merge in later.

I'll be adding versioning tests to `tests\src\readytorun` sometime later, though some generics-related versioning tests already exist there.

**Comment by jkotas** [comment]
My point was that it is impossible to tell from `Loader/classloader/generics/Misc` that these are tests for R2R...

**Comment by JohnChen0** [comment]
Agreed. I'll move the test. I'll also need to resolve some conflicts since there were changes yesterday on how CrossGen is invoked during testing.

**Comment by JohnChen0** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Pull request merged**
