### PR TITLE
Fix formatting in files

### PR DESCRIPTION
**Pull request by adiaaida**
In morph and flowgraph, we had an instance where an opening/closing
brace was inside a #if when it should not have been, which broke our
formatting on these files. This change fixes that error and reformats
the files.

### CODE REVIEW

**Comment by adiaaida** [comment]
@RussKeldorph @BruceForstall PTAL
/cc: @dotnet/jit-contrib

**Comment by RussKeldorph** [comment]
Use https://github.com/dotnet/coreclr/pull/8355/files?w=1 to see the "interesting" diffs.

**Comment by BruceForstall** [comment]
LGTM

**Comment by pgavlin** [comment]
LGTM

**Comment by adiaaida** [comment]
@dotnet-bot test this please

**Pull request merged**
