### PR TITLE
Refactor genPutStructArgStk for clarity.

### PR DESCRIPTION
**Pull request by pgavlin**
This also contains a minor CQ improvement: instead of always
incrementing the source and destination pointers when copying a struct
argument to the stack, we now only do so if there are more slots to
copy.

### CODE REVIEW

**Comment by pgavlin** [comment]
@BruceForstall @dotnet/jit-contrib PTAL

**Comment by pgavlin** [comment]
This change produces ~150 beneficial diffs when crossgen'ing S.P.CoreLib for x64 *nix. Here's an example:

```udiff
--- putstructargstk/dasmset_1/base/split/03f48d96d6f2372ec5f440c8ef391fc0dcf7b347       2016-10-07 11:05:40.693163400 -0700
+++ putstructargstk/dasmset_1/diff/split/03f48d96d6f2372ec5f440c8ef391fc0dcf7b347       2016-10-07 11:05:56.396545528 -0700
@@ -118,33 +118,31 @@
        mov      r14, rax
        mov      edi, 0x11508
        call     CORINFO_HELP_STRCNS_CURRENT_MODULE
        mov      r15, rax
        lea      rdi, [rsp]
        lea      rsi, [rbp-48H]
        mov      rcx, gword ptr [rsi]
        mov      gword ptr [rsp], rcx
        add      rsi, 8
        add      rdi, 8
        mov      rcx, gword ptr [rsi]
        mov      gword ptr [rsp+08H], rcx
        add      rsi, 8
        add      rdi, 8
        mov      rcx, gword ptr [rsi]
        mov      gword ptr [rsp+10H], rcx
        add      rsi, 8
        add      rdi, 8
        mov      rcx, gword ptr [rsi]
        mov      gword ptr [rsp+18H], rcx
-       add      rsi, 8
-       add      rdi, 8
        mov      rdi, rbx
        mov      rsi, r12
        call     System.String:FormatHelper(ref,ref,struct):ref
        mov      rdx, rax
        mov      rsi, r15
        mov      rdi, r14
        call     System.ArgumentOutOfRangeException:.ctor(ref,ref):this
        mov      rdi, r14
        call     CORINFO_HELP_THROW
        int3
-; Total bytes of code 442, prolog size 44 for method System.Globalization.GregorianCalendarHelper:TimeToTicks(int,int,int,int):long
+; Total bytes of code 434, prolog size 44 for method System.Globalization.GregorianCalendarHelper:TimeToTicks(int,int,int,int):long
```

**Comment by BruceForstall** [comment]
Generally, LGTM.

Nits: I don't like a couple of the name choices: (1) `slots` generally implies a count to me, an `unsigned`. I would leave this as gcPtrs, which is commonly used. (2) adjacentNonRefSlotCount I would call adjacentNonGcSlotCount. (3) numRefSlotsCopied I would call numGcSlotsCopied.

**Comment by pgavlin** [comment]
> I would leave this as gcPtrs

Although it's common, I really don't like that name: it seems to imply that all of the slots are GC references, which is emphatically not the case. The other changes SGTM, though.

**Comment by BruceForstall** [comment]
That's well understood, though. It's assigned from `gtGcPtrs`, which has the same properties.

**Comment by pgavlin** [comment]
@BruceForstall: in the long term I think we should also rename that field, as it is in direct disagreement with `gtNumSlots` and `gtNumReferenceSlots`. In the short term, the consistency argument has persuaded me. I'll change the name before merging.

**Pull request merged**
