### PR TITLE
Fix x86 build break.

### PR DESCRIPTION
**Pull request by jashook**
Changes unreached to NYI.

### CODE REVIEW

**Comment by jashook** [comment]
@sivarv @LLITCHEV PTAL

**Comment by LLITCHEV** [comment]
LGTM

**Comment by sivarv** [comment]
Looks good.

**Comment by jashook** [comment]
@dotnet-bot retest OSX x64 Release Build and Test

**Comment by jashook** [comment]
@dotnet-bot test Ubuntu x64 Release Build and Test

**Comment by jashook** [comment]
Seeing that this change does not effect x64, the failing tests are unrelated.

**Pull request merged**
