### PR TITLE
[RyuJIT/ARM32] Fix assertion failed 'gcPtrCount == 0'

### PR DESCRIPTION
**Pull request by YongseopKim**
Change wrong `gcPtrCount`'s value from `gtNumSlots` to `gtNumberReferenceSlots` of `GenTreePutArgStk`

### CODE REVIEW

**Comment by YongseopKim** [comment]
https://github.com/dotnet/coreclr/issues/12616

**Comment by YongseopKim** [comment]
\cc @hseok-oh

**Comment by YongseopKim** [comment]
PTAL @dotnet/jit-contrib

**Comment by hseok-oh** [comment]
LGTM. Thanks.

**Comment by BruceForstall** [comment]
@YongseopKim Can you please fix the formatting errors?

**Comment by YongseopKim** [comment]
@dotnet-bot test Ubuntu x64 Formatting please

**Comment by YongseopKim** [comment]
@BruceForstall I did. PTAL.

**Pull request merged**
