### PR TITLE
[release/3.1] Fix Mac ICU errors by porting over dotnet/runtime#47346

### PR DESCRIPTION
**Pull request by agocke**
Changes in System.Globalization.Native:
  - Replace `TRUE` with `true` and `FALSE` with `false`
  - Add `#include <stdbool.h>`

### CODE REVIEW

**Comment by agocke** [comment]
@jkoritzinsky Any idea what the policy is for merging infra changes into 3.1?

**Review by jkoritzinsky — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
Merging changes into 3.1 goes through servicing. Tagging @jeffschwMSFT

**Comment by jeffschwMSFT** [comment]
@agocke I am not sure I agree this is infra.  Can you explain?  

cc @danmoseley

**Comment by agocke** [comment]
Maybe I'm misunderstanding what's going on here: my assumption is that the underlying ICU library on the platform updated, and this change is simply reacting to the platform change. It's not necessarily infra in that there's shipping code that's changing, but if the underlying library changed I'm not sure what choice we have.

If this test is failing doesn't it mean that the product is broken on Mac?

**Comment by jeffschwMSFT** [comment]
> If this test is failing doesn't it mean that the product is broken on Mac?

@danmoseley?

**Comment by danmoseley** [comment]
@safern ?

**Comment by danmoseley** [comment]
Linking to ported PR: https://github.com/dotnet/runtime/pull/47352

I would be surprised if this was necessary to fix anything for customers. Previously, ICU was defining FALSE=0, TRUE=1, now we change to stdbool to supply true=0, false=1. It is necessary to fix the build when building against ICU headers in version 68+. If that's something we now do (I don't see a link to the break) then this change is unavoidable. But should not change the binary.

**Comment by danmoseley** [comment]
So this wasn't a question for @safern, my mistake.

**Comment by danmoseley** [comment]
actually the ICU doc implies they preserved binary compat:

> As of ICU 68, we are not changing ICU4C API from UBool to bool. Doing so in C API, or in structs that cross the library boundary, would break binary compatibility. Doing so only in other places in C++ could be confusingly inconsistent. We may revisit this.

https://github.com/unicode-org/icu/blob/main/docs/userguide/dev/codingguidelines.md#primitive-types

The test failures are unrelated, and very likely need a port of the test fix https://github.com/dotnet/runtime/pull/47209. I'll put up a PR to port that.

In short, this is an infra fix and I believe we should just merge it.

**Comment by danmoseley** [comment]
Test fix: https://github.com/dotnet/corefx/pull/43071

**Comment by safern** [comment]
> In short, this is an infra fix and I believe we should just merge it.

Yes this is an infra fix, and this is needed to build against the new ICU headers because of what you explained above. We are only seeing this on Mac because there we use Hosted Pools which doesn't have ICU installed by default and we use brew to get it. i.e: https://github.com/dotnet/runtime/blob/a32ed471d3398625d6741de8af271e711506f3da/eng/Brewfile#L2 and it is now getting a newer version of ICU headers.

**Comment by danmoseley** [comment]
@jeffschwMSFT any concerns?

**Comment by jeffschwMSFT** [comment]
lgtm cc @Anipik on timing.

**Pull request merged**
