### PR TITLE
Fixed lldb header related build errors on FreeBSD

### PR DESCRIPTION
**Pull request by ajensenwaud**
... no platform specific ifdefs)

### CODE REVIEW

**Comment by jkotas** [comment]
Could you please remove the "(this time around without ...)" comment from the commit description? It is irrelevant for the history, and it makes the first line way too long - http://www.bing.com/search?q=writing%20git%20good%20commit%20messages. I am sorry for the nitpicking - trying to establish good habits on a simple PR, hope you will understand.

BTW: The typical workflow is to update the pull request with feedback in place, not to submit a new PR. You just need to update the branch that you created the PR from and it will be automatically reflected  - it requires "git push -f ..." if you are overwriting existing commits, e.g. after squashing.

**Comment by ajensenwaud** [comment]
Sure I can. Sorry I am a long time hg user and not an expert in the workflow (yet). Is it possible to edit the PR description from within the GitHub interface or do I need to resubmit from my own fork?

Anders Jensen-Waud

**Comment by ajensenwaud** [comment]
Figured out how to do it, is the PR ok now?

**Comment by ellismg** [comment]
The commit header is still not wrapped.  You just updated the title of the PR itself.

Please try the following:

```
# git commit --amend
 <edit the commit message so the first line is 50 characters or less and save and quit your editor
# git push origin +freebsd-lldb1
```

The + infront of the ref name tells git to push the reference even though it will cause you to lose history on the server (you will be overwriting the old commit with the long titled message).

**Comment by richlander** [comment]
FYI: https://github.com/dotnet/corefx/wiki/Contributing#commit-messages

**Comment by ajensenwaud** [comment]
Thanks a lot for your help, I have changed the commit on my forked repository side so it should work.

**Comment by josteink** [comment]
LGTM

**Comment by akoeplinger** [comment]
@ajensenwaud one other nit: it appears you haven't set up the name+email in your Git config, that's why the commit shows as from `Anders <aj@freebsd-frankfurt.csaaeguest.vdc>`.

You should configure it by using the following commands:

``` bash
$ git config --global user.name "Your Name"
$ git config --global user.email email@example.com

$ git commit --amend --author "Your Name <email@example.com>"
```

The last command changes the existing commit as well, just force push that to the remote after that and it should be fine.

**Comment by ajensenwaud** [comment]
Sorry, this is because I was working from a remote box. Will submit now.

**Comment by ajensenwaud** [comment]
It has been corrected now after running git push origin +freebsd-lldb1. Did it work?

**Comment by jkotas** [comment]
It says now "ajensenwaud authored 14 hours ago Anders committed 38 minutes ago". It means that the change is still pushed under the previous name - http://www.bing.com/search?q=git+author+vs+committer  has more details.

It should not matter - it should be overwritten as it is merged. Thank you!

**Comment by jkotas** [comment]
Oh well, it did not actually get overwritten ...

**Comment by josteink** [comment]
A pretty long PR-process for 2 tiny lines of C++, but I guess being strict about stuff like this is important to keep the main log clean :)

**Comment by richlander** [comment]
@josteink It's true. It's also the exact opposite of repo maintainers that wait two weeks or more to bother responding to community PRs ;)

The hope is that @ajensenwaud has more PRs coming, so the team is taking the time to get him on the right track.

**Pull request merged**
