### PR TITLE
Add `KeepAlive` for marshalled classes in `tests\src\Interop\PInvoke\Delegate\MarshalDelegateAsField`

### LINKED ISSUE #20689: 2 test failed in x86_checked_windows_nt_gcstress0x3
**job**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_gcstress0x3/101/#showFailuresLink

**failed tests**
Interop_PInvoke._Delegate_MarshalDelegateAsField_AsFunctionPtr_AsFunctionPtrTest_AsFunctionPtrTest_._Delegate_MarshalDelegateAsField_AsFunctionPtr_AsFunctionPtrTest_AsFunctionPtrTest_cmd
Interop_PInvoke._Delegate_MarshalDelegateAsField_AsDefault_AsDefaultTest_AsDefaultTest_._Delegate_MarshalDelegateAsField_AsDefault_AsDefaultTest_AsDefaultTest_cmd
**log:**
```
Interop_PInvoke._Delegate_MarshalDelegateAsField_AsFunctionPtr_AsFunctionPtrTest_AsFunctionPtrTest_._Delegate_MarshalDelegateAsField_AsFunctionPtr_AsFunctionPtrTest_AsFunctionPtrTest_cmd [FAIL]
        
  
  Return code:      1
  Raw output file:      D:\j\workspace\x86_checked_w---71335245\bin\tests\Windows_NT.x86.Checked\Reports\Interop.PInvoke\Delegate\MarshalDelegateAsField\AsFunctionPtr\AsFunctionPtrTest\AsFunctionPtrTest.output.txt
  Raw output:
  BEGIN EXECUTION
         "D:\j\workspace\x86_checked_w---71335245\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" AsFunctionPtrTest.exe 
        Scenario 1 : Delegate marshaled as field in struct with Sequential.
        
  
  Scenario 2 : Delegate marshaled as field in struct with Explicit.
        
  
  Scenario 3 : Delegate marshaled as field in class with Sequential.
        Expected: 100
        Actual: -1073741819
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        
  To run the test:
  > set CORE_ROOT=D:\j\workspace\x86_checked_w---71335245\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root
  > D:\j\workspace\x86_checked_w---71335245\bin\tests\Windows_NT.x86.Checked\Interop\PInvoke\Delegate\MarshalDelegateAsField\AsFunctionPtr\AsFunctionPtrTest\AsFunctionPtrTest.cmd
  
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\x86_checked_w---71335245\bin\tests\Windows_NT.x86.Checked\TestWrappers\Interop.PInvoke\Interop.PInvoke.XUnitWrapper.cs(249,0): at Interop_PInvoke._Delegate_MarshalDelegateAsField_AsFunctionPtr_AsFunctionPtrTest_AsFunctionPtrTest_._Delegate_MarshalDelegateAsField_AsFunctionPtr_AsFunctionPtrTest_AsFunctionPtrTest_cmd()
```

```
Interop_PInvoke._Delegate_MarshalDelegateAsField_AsDefault_AsDefaultTest_AsDefaultTest_._Delegate_MarshalDelegateAsField_AsDefault_AsDefaultTest_AsDefaultTest_cmd [FAIL]
        
  
  Return code:      1
  Raw output file:      D:\j\workspace\x86_checked_w---71335245\bin\tests\Windows_NT.x86.Checked\Reports\Interop.PInvoke\Delegate\MarshalDelegateAsField\AsDefault\AsDefaultTest\AsDefaultTest.output.txt
  Raw output:
  BEGIN EXECUTION
         "D:\j\workspace\x86_checked_w---71335245\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" AsDefaultTest.exe 
        Scenario 1 : Delegate marshaled as field in struct with Sequential.
        
  
  Scenario 2 : Delegate marshaled as field in struct with Explicit.
        
  
  Scenario 3 : Delegate marshaled as field in class with Sequential.
        Expected: 100
        Actual: -1073741819
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        
  To run the test:
  > set CORE_ROOT=D:\j\workspace\x86_checked_w---71335245\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root
  > D:\j\workspace\x86_checked_w---71335245\bin\tests\Windows_NT.x86.Checked\Interop\PInvoke\Delegate\MarshalDelegateAsField\AsDefault\AsDefaultTest\AsDefaultTest.cmd
  
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\x86_checked_w---71335245\bin\tests\Windows_NT.x86.Checked\TestWrappers\Interop.PInvoke\Interop.PInvoke.XUnitWrapper.cs(179,0): at Interop_PInvoke._Delegate_MarshalDelegateAsField_AsDefault_AsDefaultTest_AsDefaultTest_._Delegate_MarshalDelegateAsField_AsDefault_AsDefaultTest_AsDefaultTest_cmd()
```

### PR DESCRIPTION
**Pull request by sandreenko**
Fixes #20689.

If these classes are collected during tranfer from `preemptive` to `cooperative` mode when native function calls our delegate then we collect the delegate as well.

`extern "C" DLL_EXPORT BOOL STDMETHODCALLTYPE TakeDelegateAsFieldInClass_Exp(Class1_FuncPtrAsField4_Exp *cfe)
` 
does: 
`return cfe->verification && (cfe->funcPtr() == COMMONMETHODCALLED_RIGHT_RETVAL);`

`cfe->funcPtr()` is unmanaged to managed transition, at this point `cfe` must be kept alive.

Note: `AsInterfaceTest` did not fail, but I think it is safer to fix them as well.

### CODE REVIEW

**Comment by sandreenko** [comment]
PTAL @morganbr @jkoritzinsky
cc @dotnet/jit-contrib 

Also these tests were added in #19323, but I do not know where did they come from, could somebody port this fix to the right place?

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT x64 Checked gcstress0x3
@dotnet-bot test Windows_NT x86 Checked gcstress0x3

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT x64 Checked gcstress0x3
@dotnet-bot test Windows_NT x86 Checked gcstress0x3

**Comment by sandreenko** [comment]
@dotnet-bot test this please

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT x64 Checked gcstress0x3
@dotnet-bot test Windows_NT x86 Checked gcstress0x3

**Comment by jkoritzinsky** [comment]
Superceded by #20896

**Pull request closed without merging**
