### PR TITLE
Reduce size of array enumerators for x86

### PR DESCRIPTION
**Pull request by jamesqo**
This is just a revived version of an old PR: https://github.com/dotnet/coreclr/pull/9524. In there, TLDR I closed it because removing an `int` field from the enumerator wasn't making a difference for x64, and I was unsure how to test it with x86 because I only have x64 machines.

I was recently able to get around to testing on x86 via running [this program](https://gist.github.com/jamesqo/540268a41a54214033b24ee047a2093f), and verified that commenting out the `int j` field indeed causes the allocated memory to decrease by 20%. So I'm reopening a PR to eliminate the field.

/cc @benaadams, @jkotas

### CODE REVIEW

**Comment by jkotas** [comment]
> cache array length, since it's a little slow.

You have removed this caching. What is the impact on the enumerator throughput from this change?

**Comment by jkotas** [comment]
Added System.Array owners per https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md

**Comment by benaadams** [comment]
Any reason you removed `_endIndex` from `SZGenericArrayEnumerator<T>` but not `SZArrayEnumerator`? 

(Checking as both enumerators are otherwise changed)

**Comment by jamesqo** [comment]
@benaadams @jkotas Please see [this comment](https://github.com/dotnet/coreclr/pull/9524#discussion_r100679401). TLDR The `_endIndex` field exists because the code was copy-and-pasted from `SZArrayEnumerator` (same exact comment [here](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Array.cs#L2423)), which handles general `Array` objects. Calling `Length` on an `Array` *is* slow because it's a call, but `Length` on a `T[]` is just a pointer deref.

**Comment by benaadams** [comment]
K, makes sense. Also `Current` will elide the second bounds on access check as you directly test against Length, whereas the cached length would be two checks.

**Pull request merged**
