### PR TITLE
Marking {ReadOnly}Memory structs as readonly

### PR DESCRIPTION
**Pull request by ahsonkhan**
Fixes issue https://github.com/dotnet/corefx/issues/23809
https://github.com/dotnet/coreclr/pull/13886#issuecomment-328285541

Related PR for corefx: https://github.com/dotnet/corefx/pull/24245

Previous PR was closed: https://github.com/dotnet/coreclr/pull/14180

cc @KrzysztofCwalina, @VSadov, @jkotas

### CODE REVIEW

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by benaadams** [comment]
OSX Failure: https://github.com/dotnet/coreclr/issues/14688

**Comment by ravimeda** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test please

**Comment by benaadams** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test please

**Comment by benaadams** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Pull request merged**
