### PR TITLE
Reject struct promotion of parameters when -GS checks are enabled

### PR DESCRIPTION
**Pull request by briansull**
This causes bad codegen when we introduce shadow copies for them.

### CODE REVIEW

**Comment by briansull** [comment]
Introduced with #16220

**Comment by briansull** [comment]
@AndyAyersMS PTAL
@dotnet/jit-contrib  PTAL

**Comment by briansull** [comment]
I will try to work up a repro case for this issue.

**Comment by AndyAyersMS** [comment]
Can you verify we still get the same codegen for the span-stackalloc cases in #16197?

Seeing running diffs would be valuable. Likely there should be no diffs in core and framework assemblies. Perhaps a few in tests if we have some IL tests that have unsafe value classes.

**Comment by briansull** [comment]
I saw a handful of diffs on the desktop.  '
It loosk like IL_STUB's sometimes have an unsafe buffer.
The diffs I saaw were typically just in the locals variable names used in the header. 
Often the generated code was exactly the same.

**Comment by briansull** [comment]
ONe such diff occurs in 
; Assembly listing for method System.Reflection.Associates:AssignAssociates(struct,int,ref,ref,byref,byref,byref,byref,byref,byref,byref,byref)

where local 4 is an unsafe-buffer 
;  V15 loc3         [V15    ] (  8, 11.24)  struct (80) [rsp+0x20]   do-not-enreg[XSF] must-init addr-exposed ld-addr-op ptr unsafe-buffer

That struct is a MetadataEnumResult

which is defined:

    internal unsafe struct MetadataEnumResult

So it looks like there are two ways to mark a struct as being an unsafe-buffer

Either use the full Attribute name like I did in my test case:
[UnsafeValueTypeAttribute]
struct DangerousBuffer

or by simply using the C# keyword unsafe in your struct definition as is done for MetadataEnumResult:

    internal unsafe struct MetadataEnumResult

**Pull request merged**
