### PR TITLE
Enable overriding TPA assemblies

### PR DESCRIPTION
**Pull request by gkhanna79**
Also removed InitializeDefaultContext.

@jkotas PTAL

@davidfowl FYI

### CODE REVIEW

**Comment by jkotas** [comment]
:+1:

**Comment by gkhanna79** [comment]
Infra failure in x86 legacy backend run:

18:08:37 
18:08:37 D:\j\workspace\x86_lb_checke---9877589b>tests\runtest.cmd checked x86 Exclude0 x86_legacy_backend_issues.targets 
18:08:37 RUNTEST: Using environment: "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\VsDevCmd.bat"
18:08:39 ERROR: Build step failed with exception
18:08:39 java.lang.IllegalStateException: Invalid object ID 288 iota=289
18:08:39 	at hudson.remoting.ExportTable.diagnoseInvalidId(ExportTable.java:386)
18:08:39 	at hudson.remoting.ExportTable.get(ExportTable.java:330)
18:08:39 	at hudson.remoting.Channel.getExportedObject(Channel.java:633)
18:08:39 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:599)
18:08:39 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:583)
18:08:39 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:542)
18:08:39 	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
18:08:39 	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
18:08:39 	at hudson.remoting.Request$2.run(Request.java:326)

@mmitche FYI

**Comment by gkhanna79** [comment]
@dotnet-bot test Windows_NT x86 legacy_backend Checked Build and Test please

**Comment by gkhanna79** [comment]
Fixes https://github.com/dotnet/coreclr/issues/5149

**Comment by gkhanna79** [comment]
Blocked against https://github.com/dotnet/corefx/issues/8755

**Pull request merged**
