### PR TITLE
WIP: Create portable PEDecoder wrapper library for IJW Host

### PR DESCRIPTION
**Pull request by jkoritzinsky**
The IJW Host needs to have access to the PEDecoder class from coreclr. The IJW host has to live in core-setup since it needs to share code from the hosting layer.  Additionally, because of technical constraints on the IJW host, the host must have access to the PEDecoder class while under the Windows loader lock (aka we cannot dynamically load any dlls/call LoadLibrary at the time we need the PEDecoder). Also, the PEDecoder class is written very heavily in a coreclr-centric design with `CONTRACT`s and `CHECK`s, making it difficult to port over to core-setup without effectively rewriting it completely.

So, one option we came up with was creating a portable standard C or C++ wrapper around the PEDecoder class, create a static library out of it, and flow it from coreclr to core-setup, where the IJW host could link to it.

Current progress:

- [X] Create a wrapper that exposes the APIs needed by the IJW host.
- [X] Binplace the static library and header into expected output locations.
- [] Create package for the static library.

cc: @jeffschwMSFT @AaronRobinsonMSFT @vitek-karas

### CODE REVIEW

**Comment by jkotas** [comment]
Getting COR header and the entrypoints from the PE file is pretty trivial. I think you should just build a small  piece of PE file decoding logic where you need it. I do not think creating a dependency from corsetup on the full CoreCLR PEDecoder is a good idea.

**Comment by jkoritzinsky** [comment]
It was pretty trivial to port over the methods that retrieve the different headers from the PE file. However, the implementation of `CheckCORFormat` brings in almost the entire PEDecoder class. I can work again on porting that over, but I'd effectively be rewriting it wholesale. If you think that's a better avenue, then I'll take that route.

**Comment by jkotas** [comment]
You do not need CheckCORFormat for what you need to do for IJW files. If you got IJW file loaded by Windows in memory, it is fine to assume that it is valid.

The PEDecoder checks exist for when we are loading IL from memory (we cannot depend on OS to do the validation for us), and they were originally designed for partial trust (they did a very comprehensive validation to make sure that nothing malformed can squeeze in).

**Comment by jkoritzinsky** [comment]
Well in that case, we won't need this! I can just port over what I need to core-setup.

Thanks for the insight!

**Pull request closed without merging**
