### PR TITLE
Remove System.Security.Permissions.SecurityPermissionAttribute from System.Private.CoreLib.

### PR DESCRIPTION
**Pull request by erozenfeld**
When compiling with /unsafe+ Roslyn emits
  .permissionset reqmin
             = {class 'System.Security.Permissions.SecurityPermissionAttribute, System.Private.CoreLib,
             Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' =
             {property bool 'SkipVerification' = bool(true)}}
if System.Security.Permissions.SecurityPermissionAttribute is present.

In particular, System.Private.CoreLib.dll is compiled with /unsafe+ and has the above in the manifest.

https://github.com/dotnet/coreclr/commit/e516211b2d3a3ae2dbd80f2c94b129910a9e280d
made BclRewriter remove System.Security.Permissions.SecurityPermissionAttribute
from System.Private.CoreLib.dll but the above reference remained.

This change removes System.Security.Permissions.SecurityPermissionAttribute completely
to avoid confusion when tools are analyzing msil and try to resolve the manifest
of System.Private.CoreLib.dll.

### CODE REVIEW

**Comment by erozenfeld** [comment]
@rahku PTAL

**Comment by rahku** [comment]
LGTM. I would just confirm that type is actually private in the generated assembly.

**Comment by erozenfeld** [comment]
Yes, I confirmed that the type is private in the generated assembly.

**Comment by erozenfeld** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Comment by erozenfeld** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Comment by erozenfeld** [comment]
1. I don't know if anyone is compiling against CoreLib. I'm working on a tool that's analyzing assemblies in order to reduce their size and it stumbles on this reference. I can hard-code this case in the tool but I think we shouldn't be producing assemblies with references that can't be resolved.
2. I agree, it shouldn't. But even after we fix Roslyn, older versions of csc may be compiling System.Private.CoreLib on developers' machines and producing this bogus reference.

In general, what's our process for removing/refactoring classes in System.Private.CoreLib that Roslyn assumes are always present. I assume System.Security.Permissions.SecurityPermissionAttribute is not the only such class.

**Comment by jkotas** [comment]
>  analyzing assemblies in order to reduce their size and it stumbles on this reference

What is this assembly? Where did this assembly came from?

> System.Private.CoreLib that Roslyn assumes are always present

I do not think that Roslyn assumes that this type is present in CoreLib.

**Comment by erozenfeld** [comment]
The assembly is System.Private.Corelib.dll itself. Just build coreclr normally from the repo and look at the manifest. The assembly is compiled with /unsafe+ and that causes Roslyn to emit this attribute.

**Comment by jkotas** [comment]
>  what's our process for removing/refactoring classes in System.Private.CoreLib 

System.Private.CoreLib is our internal implementation detail. We reserve the right to remove/refactor any types in or out of it.

**Comment by erozenfeld** [comment]
Actually, here is what happens. System.Security.Permissions.SecurityPermissionAttribute is present in System.Private.CoreLib.dll initially. Roslyn emits the reference (because of /unsafe) but then BclRewriter removes the class from System.Private.CoreLib.dll. Should the right fix be to modify BclRewriter to remove the reference once  System.Security.Permissions.SecurityPermissionAttribute is removed?

**Comment by jkotas** [comment]
This is bug in the BCL rewriter tool that is used to post-process the sources: It removes SecurityPermissionAttribute definition, but leaves a reference to it in .permissionset directive.

The right fix for this is to delete the source for SecurityPermissionAttribute from CoreLib. It is dead code. We are working on cleaning up the dead code from CoreLib (https://github.com/dotnet/coreclr/issues/972). If this one is preventing from making progress, I would suggest deleting SecurityPermissionAttribute from CoreLib instead of adding more references to it.

**Comment by erozenfeld** [comment]
@jkotas I removed System.Security.Permissions.SecurityPermissionAttribute. PTAL.

**Pull request merged**
