### PR TITLE
Add CI Job to list all trigger phrases for coreCLR (WIP)

### PR DESCRIPTION
**Pull request by wtgodbe**
This is a first crack at adding a job to the CI that will list all available trigger phrases in its console output. Right now I have that job triggered by phrase, but once I know it's working I think it should be a default job. Currently a WIP.

### CODE REVIEW

**Comment by wtgodbe** [comment]
@dotnet-bot test CI please

**Comment by wtgodbe** [comment]
@mmitche PTAL - do you think this needs to be refactored in any way? What do you think about adding this job/making it a default job (it's not currently default, but I'm planning on changing it to default after I make sure it works)

**Comment by mmitche** [comment]
@wtgodbe Looks interesting.  I actually have a reporting thing in the works that records all the trigger phrases.

**Comment by wtgodbe** [comment]
@mmitche what does that look like? I'm not sure this is the best way to do this, since you'd have to go into the console output of the job to see the phrases, but I figured more documentation couldn't hurt.

**Comment by mmitche** [comment]
@wtgodbe Theoretically we could also comment on the PR with the prhases, however without some way of ignoring the comment, it will trigger all the builds.  My stuff will print the data to the console of the generator jobs (there's no way to create a file).  We could pull that output and update a doc though.

**Comment by wtgodbe** [comment]
Hmm, yeah the comment doesn't seem like it'd be the best idea, but I like the idea of pulling the output from the console and updating the Documentation file (https://github.com/wtgodbe/coreclr/blob/master/Documentation/project-docs/ci-trigger-phrases.md). 

How does your change get the trigger phrases/what would they look like? I couldn't figure it out by looking at the change (where does jobs.generation.JobReport come from? I couldn't find it next to Utilities.groovy)

**Comment by mmitche** [comment]
CHeck out: http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/GenPRTest/job/generator_prtest/67/consoleText

**Comment by wtgodbe** [comment]
Oh that makes me very happy. Is there a way to get dotnet-bot to scrape that for differences against the trigger document & submit a PR when something changes?

**Comment by mmitche** [comment]
@wtgodbe SHouldn't be too hard to put somethign like that together.  Or scrape against the previous build and just diff CSV's

**Comment by wtgodbe** [comment]
@mmitche sweet, do you have a good idea how to do it? I'm happy to make the change if you want to point me in the right direction - otherwise are you able to do it?

(Also can you comment on PRs after closing them? If so I'll close this)

**Comment by mmitche** [comment]
Apparenlty you can.

**Comment by wtgodbe** [comment]
Sweet. Any thoughts on how to get dotnet to do the scraping/updating?

**Comment by mmitche** [comment]
@wtgodbe Hmm.  We already have logic in some service (I think the mirror) to open PRs.  I think the basic workflow is this:
1) Watch every so often (daily?) for new builds of the generator
2) Parse the console output (this can just be curled from the page) and create the CSV files  from the text.
3) Compare to the previous job's output, either in a structured form (compare CSV otuput ignoring job names, for instance) or just a straight diff
4) Munge into .md form and submit a PR if there are changes.

**Comment by wtgodbe** [comment]
@mmitche is there an example somewhere of the mirror being used?

**Comment by mmitche** [comment]
@ellismg May know more.  The basics are pretty simple and not related to teh mirror code.  The mirror also creates a PR. which is pretty simple (just POST a json blob with info to the github API)

**Comment by wtgodbe** [comment]
@ellismg did you have a chance to take a look at this? I think it'd be really cool/helpful to have the trigger phrase doc self-update. You can see Matt's change here - https://github.com/dotnet/coreclr/pull/4320

**Comment by ellismg** [comment]
I can share the mirror code with you, if you think that would be helpful. I think it's probably overkill for what you want, however.

 You can create a [new PR using the API with a simple HTTP request](https://developer.github.com/v3/pulls/#create-a-pull-request).  We have some automation in CoreFX that [does something similar](https://github.com/dotnet/corefx/blob/master/UpdateDependencies.ps1#L52) (here it pends a bunch of local changes to update package versions and submits a PR).

My recommendation would be to do what @mmitche says, have some job that runs once a day (maybe an Azure Web Job?) that parses the output and then opens a PR if needed.

**Comment by wtgodbe** [comment]
@ellismg thanks, that's very helpful. I'll take a look.

**Pull request closed without merging**
