### PR TITLE
Explicitly enable relro

### PR DESCRIPTION
**Pull request by kbaladurin**
We need to enable relro explicitly because in some cases it isn't enabled by default. For example, clang does it only for openSUSE, ubuntu, alpine and android.

### CODE REVIEW

**Comment by kbaladurin** [comment]
@lpereira good idea, I've enabled full relro

**Comment by maryamariyan** [comment]
Thank you for your contribution. As announced in dotnet/coreclr#27549 this repository will be moving to dotnet/runtime on November 13. If you would like to continue working on this PR after this date, the easiest way to move the change to dotnet/runtime is:
1.	In your coreclr repository clone, create patch by running `git format-patch origin`
2.	In your runtime repository clone, apply the patch by running `git apply --directory src/coreclr <path to the patch created in step 1>`

**Comment by janvorli** [comment]
@kbaladurin could you please resolve the conflict so that we can merge this change? I am sorry that I have missed this change when you have created it back in July, likely due to summer vacation.

**Comment by kbaladurin** [comment]
@janvorli I've resolved conflicts, thank you!

**Comment by janvorli** [comment]
@kbaladurin thank you!

**Pull request merged**
