### PR TITLE
Document Visual Studio 2015 support

### PR DESCRIPTION
**Pull request by DickvdBrink**
Removed the link to issue #30 because according to my testing it works correctly now on VS2015.

Also @jasonwilliams200OK did managed to get it working on VS2015 if I recall correctly (can you confirm?)

I guess issue #1033 can be closed now as it seems to be resolved by some other recent changes!

### CODE REVIEW

**Comment by jasonwilliams200OK** [comment]
@DickvdBrink, yes it builds the whole `bin\obj\Windows_NT.x64.Release\install.vcxproj` with both VS2015 and VS2013, but in both cases, it fails many tests with the log showing great amount of these errors:

> CSC : error CS0518: Predefined type 'System.Object' is not defined or imported [C:\github\coreclr\tes
ts\src\JIT\Regression\CLR-x86-JIT\V1-M09\b16294\cs_template.proj]

@mmitche, any idea why this error only appears locally? Any advice / recommendation for people who are landing on this repo for the first time, with VS2013 and/or VS2015 installed and want to test CoreCLR with the following steps:

```powershell
md \experiment
cd \experiment
git clone https://github.com/dotnet/coreclr --recursive
cd coreclr
.\build release vs2013   # or even vs2015 
# a lot of spew then it says `***\install.vcxproj` built successfully
# with 0 Errors and 0 Warnings
# but when it runs the tests subsequently, it fails with the
# aforementioned error followed by final message:
# Test build failed. ...
```

**Comment by DickvdBrink** [comment]
@jasonwilliams200OK, that is weird. On my system everything succeeded just fine without errors and ended with something like this in both release and debug. In both cases I did a clean build

(it ended with something **like** this, don't have the full logs at hand because I'm not at home)
>Repo successfully built.
Product binaries available at <location>
Test binaries available at <location

**Comment by jasonwilliams200OK** [comment]
> Are that different machines or is it the same machine?

You nailed it! :ok_hand:  It succeeds build and all tests on my work computer, where I don't have Xamarin installed, but failing on my personal computer (where I probably have Xamarin). Tested with both VS2013 and VS2015 and it works like a charm!

Incidentally, does the Xamarin installation (that emerged with VS2015 RC) affects both VS2013 and VS2015 builds?

Separately:
In case you missed it, there is this notification

> #### This pull request contains merge conflicts that must be resolved. 

You may want to rebase. :)

**Comment by DickvdBrink** [comment]
@jasonwilliams200OK, thanks didn't saw the notification.. rebased

**Comment by jasonwilliams200OK** [comment]
:+1:
Should we add the pitfall note about Xamarin pointing to gh-927 and https://github.com/dotnet/corefx/issues/449, until those are fixed?
FYI: @jkotas, @richlander 

@kzu, perhaps these steps help you figure out the root cause (if that is the blocker): install VS2015 RC with Xamarin and use these step to build CoreCLR: https://github.com/dotnet/coreclr/pull/1124#issuecomment-110590799 either with vs2013 or vs2015 on the same machine.

**Comment by DickvdBrink** [comment]
Is this change oke? If not feel free to close but building does work (when I last tried)

**Comment by mmitche** [comment]
LGTM

**Comment by kzu** [comment]
Looping @joj

**Comment by richlander** [comment]
LGTM modulo comments

**Comment by DickvdBrink** [comment]
Oops, forgot to comment but updated this PR

**Comment by DickvdBrink** [comment]
Commits are lost because I rebased again because it didn't merge anymore.. might have been better to merge master in to this.. sorry about that...
Is it oke now?

**Comment by mmitche** [comment]
LGTM

**Pull request merged**
