### PR TITLE
Porting jit\opt\tailcall\TailcallVerifyWithPrefix.il

### PR DESCRIPTION
**Pull request by hoyMS**
The test orginally requires passing a command line arguemnt to run. This
change modifies the Main method by renaming it to MainRun and adds a
wrapper method called Main which explicitly passes original commandline
strings to MainRun.

### CODE REVIEW

**Comment by hoyMS** [comment]
@pgavlin  PTAL

**Comment by pgavlin** [comment]
I can't seem to comment on `TailcallVerifyWithPrefix.il`, so I'll leave comments here w/ line links.

[Line 2789](https://github.com/hoyMS/coreclr/blob/testWithArgs/tests/src/JIT/opt/Tailcall/TailcallVerifyWithPrefix.il#L2789): What happens if the callee fails? Shouldn't we check the exit code and fail the test if it's not 100? This comment applies to every invocation of `TailcallVerify.Program::Run` except the final invocation.

**Comment by hoyMS** [comment]
If callee fails, the return code will be saved to TailcallVerify.Program::result by TailcallVerify.Program::set_Result(int32). If callee succeeds, the result won't be updated.

.method public hidebysig specialname static 
          void  set_Result(int32 'value') cil managed
  {
    // Code size       16 (0x10)
    .maxstack  8
    IL_0000:  ldsfld     int32 TailcallVerify.Program::result
    IL_0005:  ldc.i4.s   100
    IL_0007:  bne.un.s   IL_000f

    IL_0009:  ldarg.0
    IL_000a:  stsfld     int32 TailcallVerify.Program::result
    IL_000f:  ret
  } // end of method Program::set_Result

The result will be returned to caller, i.e., Main :

.method private hidebysig static int32 
          Run(string arg) cil managed
  {
    ....
    IL_0797:  call       void [mscorlib]System.Console::WriteLine(string)
    IL_079c:  call       int32 TailcallVerify.Condition23::Test1()
    IL_07a1:  call       void TailcallVerify.Program::set_Result(int32)
    IL_07a6:  call       int32 TailcallVerify.Program::get_Result()
    IL_07ab:  ret
  } // end of method Program::Run

In a word, if all callees succeed, Main will return the initial return code 100 which is initialized in

  .method private hidebysig specialname rtspecialname static 
          void  .cctor() cil managed
  {
    // Code size       8 (0x8)
    .maxstack  8
    IL_0000:  ldc.i4.s   100
    IL_0002:  stsfld     int32 TailcallVerify.Program::result
    IL_0007:  ret
  } // end of method Program::.cctor

If any callee fail, Main will return the last recent failling callee's code.

**Comment by pgavlin** [comment]
Okay; thanks for the explanation.

**Comment by hoyMS** [comment]
@dotnet-bot test OSX x64 Release

**Comment by hoyMS** [comment]
@dotnet-bot test OSX x64 Debug

**Pull request closed without merging**
