### PR TITLE
Disable ETW calls on UNIX

### LINKED ISSUE #11592: EventSource still broken on Unix after recent refactoring
e.g.
https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug_prtest/7805/consoleText
https://ci.dot.net/job/dotnet_corefx/job/master/job/centos7.1_debug_prtest/7795/consoleText
```
BasicEventSourceTests.TestsWriteEventToListener.Test_WriteEvent_ArgsCornerCases [FAIL]
        System.Diagnostics.Tracing.EventSourceException : An error occurred when writing to a listener.
        ---- System.DllNotFoundException : Unable to load DLL 'advapi32.dll': The specified module or one of its dependencies could not be found.
         (Exception from HRESULT: 0x8007007E)
        Stack Trace:
              at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
              at System.Diagnostics.Tracing.EventSource.WriteEventVarargs(Int32 eventId, Guid* childActivityID, Object[] args)
           /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/src/System.Diagnostics.Tracing/tests/CustomEventSources/EventSourceTest.cs(147,0): at SdtEventSources.EventSourceTest.EventWith7Strings(String s0, String s1, String s2, String s3, String s4, String s5, String s6)
           /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/src/System.Diagnostics.Tracing/tests/BasicEventSourceTest/TestsWriteEventToListener.cs(194,0): at BasicEventSourceTests.TestsWriteEventToListener.Test_WriteEvent_ArgsCornerCases()
           ----- Inner Stack Trace -----
              at Microsoft.Win32.UnsafeNativeMethods.ManifestEtw.EventActivityIdControl(ActivityControl ControlCode, Guid& ActivityId)
              at System.Diagnostics.Tracing.EventSource.get_CurrentThreadActivityId()
              at System.Diagnostics.Tracing.EventWrittenEventArgs.get_ActivityId()
           /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/src/System.Diagnostics.Tracing/tests/BasicEventSourceTest/LoudListener.cs(29,0): at BasicEventSourceTests.LoudListener.OnEventWritten(EventWrittenEventArgs eventData)
              at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
```

### PR DESCRIPTION
**Pull request by brianrob**
Fixes #11592.

### CODE REVIEW

**Comment by brianrob** [comment]
I did a more thorough review of the code base and found a few more places in addition to the one in #11592.  Hopefully this is it.

**Comment by brianrob** [comment]
@dotnet-bot test Tizen armel Cross Release Build ("FAILED   - JIT/Regression/CLR-x86-JIT/V1-M11-Beta1/b37131/b37131/b37131.sh
")

**Comment by danmosemsft** [comment]
@brianrob can you help me understand why this churn is happening so late? I also see you've opened a number of new 2.0 issues, are they caused by recent churn, or only recently discovered? 

@stephentoub

**Comment by stephentoub** [comment]
Merging to try to unblock CoreFx...

**Pull request merged**
