### PR TITLE
Fix handle leak when creating or opening named mutex fails

### PR DESCRIPTION
**Pull request by kouvel**
Port bf6e190fe6ef7289d94545304b5c409f379658b9 to release/1.0.0

- After the pal object is registered, it gets a second reference from the handle. Upon an error after that, the handle needs to be revoked in addition to releasing the initial reference.

Issue: #5364
master PR: #5365

### CODE REVIEW

**Comment by kouvel** [comment]
@sergiy-k @adityamandaleeka

**Comment by kouvel** [comment]
@dotnet-bot test this

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by sergiy-k** [comment]
LGTM

**Pull request merged**
