### PR TITLE
Update badges to new job locations

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
The old pr test and commit jobs have now been disabled (though not deleted yet)

**Comment by jasonwilliams200OK** [comment]
@mmitche, can we also get hook to [`codecov-io`](https://codecov.io) summary in PRs with this cool new groovy-driven infrastructure? :)

It will look something like:
https://github.com/twitter/diffy/pull/8#issuecomment-137976910
https://github.com/TTTAttributedLabel/TTTAttributedLabel/pull/581#issuecomment-139821031.

(it will be just one comment per PR regardless of number of rebase, as they mentioned here: https://github.com/dotnet/corefx/pull/3368)

**Comment by mmitche** [comment]
We don't today run code coverage on every PR, but I'll probably add it as an on-demand thing.  I can look to add the hook then.

**Comment by mmitche** [comment]
Anyone have objections to me merging this?

**Comment by jasonwilliams200OK** [comment]
@mmitche, 
That sounds good. Probably @sharwell and co. can help us configuring code coverage and codecov hook, as they already have done it for several repos under https://github.com/DotNetAnalyzers.

Sorry I forgot to comment on the organization of badges earlier, but wouldn't it be nice to have it transposed such that Debug/Release become columns and platforms rows; essentially to get rid of the scroll bars with the ever growing matrix?
Also, in future the platform names may grow in length; "FreeBSD 10.2 x86 Release" or "Linux on ARM v7 (64-bit) Debug" etc.

**Comment by sharwell** [comment]
@jasonwilliams200OK codecov.io automatically detects when the build is running on AppVeyor and links the information to the parent repository, so there's no need to set up any hooks or authentication keys or anything. Our configuration to enable code coverage reporting is contained within the `test_script` section of our [appveyor.yml](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/appveyor.yml#L13-L16), plus one line in our solution-level [packages.config](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/.nuget/packages.config#L4) file. After setting everything up I contributed some (hopefully) helpful information back in codecov/example-csharp#3.

**Pull request merged**
