### PR TITLE
Move String.Manipulation.cs to shared

### PR DESCRIPTION
**Pull request by jkotas**
Reconciled formatting and minor tweaks with CoreRT version.

### CODE REVIEW

**Comment by jkotas** [comment]
@tannergooding The recently added intrinsics tests are failing on OSX:

```
BEGIN EXECUTION /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/x64_checked_osx10.12_innerloop_tst_prtest/bin/tests/OSX.x64.Checked/Tests/Core_Root/corerun Prefetch_ro.exe Expected: 100 Actual: 0 END EXECUTION - FAILED
```

**Comment by tannergooding** [comment]
Hmm, looking at the general job failures, they consecutively failed twice on this PR, but nowhere else.
They also failed in a way that makes me assume the test job was in some weird state.

I'm going to monitor the general failures to see if it crops up again...

**Comment by jkotas** [comment]
@Anipik Could you please take a look at the CoreCLR->CoreRT mirror? It is not picking up this and other PRs.

**Comment by Anipik** [comment]
There are some merge conflicts. i am just resolving them

**Comment by Anipik** [comment]
@jkotas  I have started the mirror for this one

**Pull request merged**
