### PR TITLE
[WIP] additional refactoring for multireg return

### PR DESCRIPTION
**Pull request by briansull**

### CODE REVIEW

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked pri1r2r

**Comment by briansull** [comment]
@dotnet-bot Test Windows Arm64 Checked pri1r2r

**Comment by briansull** [comment]
@dotnet-bot Test Windows_NT arm64 Checked Pri1r2r

**Comment by briansull** [comment]
@dotnet-bot Test   Linux ARM Emulator Cross Release Build

**Comment by briansull** [comment]
@dotnet-bot Test Linux ARM Emulator Cross Release Build

**Comment by briansull** [comment]
@dotnet-bot Test Windows_NT arm64 Checked Pri1r2r

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by briansull** [comment]
@dotnet-bot Test Linux ARM Emulator Cross Release Build

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by briansull** [comment]
@dotnet-bot Test Windows_NT arm64 Checked

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by briansull** [comment]
@dotnet-bot Test Windows_NT arm64 Checked

**Comment by briansull** [comment]
@dotnet-bot Test Windows_NT Arm64 Checked Build and Test

**Comment by briansull** [comment]
@dotnet-bot Test Windows_NT arm64 Checked

**Comment by briansull** [comment]
@dotnet-bot Test Linux ARM Emulator Cross Release Build

**Comment by briansull** [comment]
@dotnet-bot Test Windows_NT arm64 Checked

**Comment by briansull** [comment]
@dotnet-bot Test Windows Arm64 Checked pri1r2r

**Comment by briansull** [comment]
@dotnet-bot Test Linux ARM Emulator Cross Release Build

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by briansull** [comment]
@dotnet-bot Test Windows Arm64 Checked pri1r2r

**Comment by briansull** [comment]
@dotnet-bot Test Windows_NT x64 Debug Build and Test

**Comment by briansull** [comment]
@dotnet-bot Test  Linux ARM Emulator Cross Release Build

**Comment by briansull** [comment]
@dotnet-bot Test  Windows_NT x64 Debug Build and Test

**Comment by briansull** [comment]
@dotnet-bot Test Windows Arm64 Checked pri1r2r

**Comment by briansull** [comment]
@dotnet-bot Test Linux ARM Emulator Cross Release Build

**Comment by briansull** [comment]
@dotnet-bot Test Windows Arm64 Checked pri1r2r

**Comment by briansull** [comment]
@dotnet-bot Test Windows Arm64 Checked pri1r2r

**Comment by briansull** [comment]
@dotnet-bot Test Linux ARM Emulator Cross Release Build

**Comment by briansull** [comment]
@dotnet-bot Test Linux ARM Emulator Cross Debug Build

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by briansull** [comment]
@dotnet-bot Test Windows_NT Arm64 Checked Build

**Comment by briansull** [comment]
@russellhadley 

Multireg Return support for Arm64
28 changed files, 1687 lines of code added

**Comment by briansull** [comment]
@mmitche  Only two test jobs got started by Jenkins

**Comment by briansull** [comment]
Adding that comment started the other eight

**Comment by briansull** [comment]
@dotnet-bot Test Windows_NT Arm64 Checked Build and Test

**Comment by mmitche** [comment]
As if on cue :D. It was probably because of the restart earlier

**Comment by mmitche** [comment]
(the reason this did this is that the system restarted while it was running your job, but when you commented it went back and looked at the previous comments and noted things needed a rerun.

**Comment by briansull** [comment]
@dotnet-bot Test Windows_NT arm64 Checked

**Comment by briansull** [comment]
@dotnet-bot Test Windows_NT arm64 Checked

**Comment by briansull** [comment]
@dotnet-bot Test Windows_NT arm64 Checked

**Comment by briansull** [comment]
@dotnet-bot Test Windows_NT arm64 Checked

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked pri1r2r

**Comment by briansull** [comment]
@dotnet-bot Test Windows_NT arm64 Checked

**Comment by briansull** [comment]
@dotnet-bot Test Windows_NT arm64 Checked
@dotnet-bot Test Windows_NT arm64 Checked Pri1r2r

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 checked

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 checked pri1r2r

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 checked

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 checked pri1r2r

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 checked

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 checked pri1r2r

**Comment by briansull** [comment]
@kyulee1 Can you see if I am whitelisted to run Arm64 testing
They never/hardly-ever start for me.


@dotnet-bot test Windows_NT arm64 checked

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 checked

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 checked pri1r2r

**Comment by kyulee1** [comment]
Your alias is 'briansull', right? I think yours is listed in arm64Users in netci.groovy. I'm not sure why it's not triggered by your command.

**Comment by mmitche** [comment]
Next time you're about to trigger this briansull, ping me and I'll watch.  It should be working for you.

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 checked

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 checked pri1r2r

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 checked pri1r2r

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 checked

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 checked

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 checked pri1r2r

**Pull request closed without merging**
