### PR TITLE
Switch per-commit CentOS jobs from Checked to Release

### PR DESCRIPTION
**Pull request by wtgodbe**

### CODE REVIEW

**Comment by wtgodbe** [comment]
@stephentoub it seems like it makes sense to just switch the per-commit jobs from Checked to Release - what do you think? Is there anything that depends on there being Checked CentOS builds?

**Comment by stephentoub** [comment]
LGTM

> Is there anything that depends on there being Checked CentOS builds?

Nothing from corefx.

**Comment by wtgodbe** [comment]
@dotnet-bot test CI please

**Comment by wtgodbe** [comment]
@dotnet-bot test CI please

**Comment by wtgodbe** [comment]
@dotnet-bot test this please

**Comment by wtgodbe** [comment]
@dotnet-bot test CI please

**Comment by sergiy-k** [comment]
@dotnet-bot test this please

**Comment by sergiy-k** [comment]
LGTM

**Pull request merged**
