### PR TITLE
Disable manual COM registration logic on ARM32

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
see #19020

cc @jkotas @BruceForstall

### CODE REVIEW

**Comment by BruceForstall** [comment]
Wouldn't this need to use `_TARGET_ARM_` instead of `_ARM_`?

Are you disabling this for ARM (but not ARM64?) because it shouldn't be supported?

Is it just missing the right import library (advapi32.lib?) in tests\src\Interop\CMakeLists.txt:
```
if(WIN32)
    if(CLR_CMAKE_HOST_ARCH STREQUAL arm)
        list(APPEND LINK_LIBRARIES_ADDITIONAL
            ole32.lib
        )
    endif(CLR_CMAKE_HOST_ARCH STREQUAL arm)
endif(WIN32)
```

**Comment by AaronRobinsonMSFT** [comment]
@BruceForstall Good catch. That section is before my time so I have no idea why it is there. I will re-submit by updating that instead.

**Comment by AaronRobinsonMSFT** [comment]
@BruceForstall I chose `_ARM_` because that is what I found in the codebase. Is `_TARGET_ARM_` the preferred value to use?

**Comment by jkotas** [comment]
> Wouldn't this need to use `_TARGET_ARM_` instead of `_ARM_`?

`_ARM_` is right. `_TARGET_ARM_` is only used in the runtime itself, in places that need host/target separation.

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by AaronRobinsonMSFT** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by AaronRobinsonMSFT** [comment]
@BruceForstall I didn't mean to try ARM64 - but that is good to know - Thanks! 😄 I meant to retry the Tizen and Ubuntu since Jenkins failed.

**Comment by AaronRobinsonMSFT** [comment]
@dotnet-bot test Windows_NT x86 Release Innerloop Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by BruceForstall** [comment]
@AaronRobinsonMSFT We've had two problems: (1) a Jenkins hiccup that required re-triggering testing; you might need to re-trigger all the other jobs, and (2) a problem where the machines used to run arm32/arm64 testing were misbehaving.

Both should be fixed now.

**Comment by AaronRobinsonMSFT** [comment]
@BruceForstall Thanks! Is there a notification list for these kinds of announcements? Just so I know in the future if the build system goes wonky?

**Comment by AaronRobinsonMSFT** [comment]
@dotnet-bot  test Windows_NT x86 Release Innerloop Build and Test 
@dotnet-bot  test Ubuntu x64 Checked Innerloop Build and Test 
@dotnet-bot  test Ubuntu arm64 Cross Debug Innerloop Build
@dotnet-bot  test Ubuntu arm Cross Checked Innerloop Build and Test
@dotnet-bot  test Tizen armel Cross Checked Innerloop Build and Test
@dotnet-bot  test OSX10.12 x64 Checked Innerloop Build and Test 
@dotnet-bot  test CentOS7.1 x64 Checked Innerloop Build and Test

**Comment by AaronRobinsonMSFT** [comment]
@dotnet-bot test Ubuntu x64 Checked CoreFX Tests
@dotnet-bot test Windows_NT x64 Checked Innerloop Build and Test
@dotnet-bot test Windows_NT x86 Checked Innerloop Build and Test

**Comment by AaronRobinsonMSFT** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by AaronRobinsonMSFT** [comment]
@BruceForstall There are no words for how silly this is. Why does ARM and ARM64 have checked in auto-generated lists of tests? Is the test environment different?

https://github.com/dotnet/coreclr/blob/master/tests/arm/Tests.lst
https://github.com/dotnet/coreclr/blob/master/tests/arm64/Tests.lst

Both files have banners that indicate they are auto-generated - is this still the case? How can I update them?

cc @jeffschwMSFT

**Comment by AaronRobinsonMSFT** [comment]
@jashook or @BruceForstall I don't have permissions to trigger ARM64 tests, can one of you do that after I update the `Tests.lst`?

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by BruceForstall** [comment]
> Is there a notification list for these kinds of announcements? Just so I know in the future if the build system goes wonky?

There isn't, although I've often thought there should be.

> Do you happen to know why ARM and ARM64 have checked in auto-generated lists of tests? Is the test environment different?

tests.lst are used by the Windows (but not Linux) arm32/arm64 test runs, which use the legacy smarty.exe test runner. They used to be (and maybe still could be) auto-generated, but lately we just manually add/modify the test lists. You modify them by, essentially, following the lead of what is already there.

**Comment by jkotas** [comment]
> Is there a notification list for these kinds of announcements

Notifications about the wide-impact engineering system outages (like the Jenkins one) are sent to dncpartners ms alias.

**Comment by jkotas** [comment]
> Any ideas on why these runs are taking so long?

The engineering team is usually the best default contact for infrastructure questions like these. Details are in https://github.com/dotnet/core-eng/wiki/How-to-get-a-hold-of-Engineering-Servicing

**Comment by AaronRobinsonMSFT** [comment]
@dotnet-bot tests OSX10.12 x64 Checked Innerloop Build and Test

**Comment by AaronRobinsonMSFT** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by AaronRobinsonMSFT** [comment]
OSX build failed due to #19001 - committing.

**Pull request merged**
