### PR TITLE
Introduce "IGCToCLR" and use it within the GC to interface with the EE

### PR DESCRIPTION
**Pull request by swgillespie**
In the interest of decoupling the GC and the rest of the EE, this PR populates the `IGCToCLR` interface with what is currently on `GCToEEInterface` and changes the GC to refer to an instance of `IGCToCLR` instead of calling static methods on `GCToEEInterface` directly. The rationale for this change is to avoid linking the GC directly to the implementation of the GCToEEInterface, as it does today. 

With this change `GCToEEInterface` becomes a subclass of `IGCToCLR` which is initialized on EE startup. The GC calls into the EE by dispatching virtually on this interface.

### CODE REVIEW

**Comment by swgillespie** [comment]
@Maoni0 @jkotas @janvorli PTAL if you're interested?

**Comment by swgillespie** [comment]
Do you mean keeping all of the calls to `GCToEEInterface` from within the GC and providing a GC-internal `GCToEEInterface` whose responsibility is forwarding calls to the `IGCToCLR` instance?

**Comment by jkotas** [comment]
> providing a GC-internal GCToEEInterface whose responsibility is forwarding calls to the IGCToCLR instance?

Right. The indirection via virtual interface should be only used if the GC is built as standalone .dll. It does not make sense to go through it when the GC is statically linked with the runtime.

**Comment by janvorli** [comment]
I agree with @jkotas.

**Comment by swgillespie** [comment]
Ok! My understanding is that building as a standalone DLL was an eventual goal - if we plan on linking statically, there's no need for this PR at all, right? Or is the intention to support both static and dynamic linking of the GC? Or perhaps I'm mistaken on what I need to do next.

**Comment by jkotas** [comment]
> the intention to support both static and dynamic linking of the GC

We should keep both options. Different products may only ship with one or the other.

**Comment by Maoni0** [comment]
Our goal is to just have GC code live in gc.dll, eventually (with Sean's work). We are not planning to make it so that for some products it's statically linked and for others it's dynamically loaded. GC code eventually may live in its own repo too.

**Comment by jkotas** [comment]
> We are not planning to make it so that for some products it's statically linked and for others it's dynamically loaded

This does not make sense. It would imply that we will never ever support single .exe - we have been always talking about having single .exe as an option for AOT.

> GC code eventually may live in its own repo too.

This is fine. The repo may produce .lib/.a file for configurations with static linking.

**Comment by Maoni0** [comment]
The single .exe thing is certainly news to me. That's unfortunate.

Sean, this means you'll need to do some extra work. Sorry about that...

**Comment by swgillespie** [comment]
no problem! I'll go ahead and close this since I have some more work to do before it's ready to be looked at again.

**Pull request closed without merging**
