### PR TITLE
Addressing https://github.com/dotnet/coreclr/issues/21461

### PR DESCRIPTION
**Pull request by jorive**
Addressing https://github.com/dotnet/coreclr/issues/21461
- Increase the polling interval to 20 seconds.
- Add an option to opt-out from EventSource

### CODE REVIEW

**Comment by jorive** [comment]
@vancem Thanks for the proposed fix.

**Comment by jorive** [comment]
Testing is pending.

**Comment by brianrob** [comment]
From @jkotas's comment in the associated issue, it sounds like @jkotas is proposing that this be opt-in not opt-out.  The current implementation enables polling by default and lets you disable it.  Is that the desired outcome?  If so, LGTM.

**Comment by jorive** [comment]
Yes, from @jkotas 's comment, it sounds like it should be opt-in.

**Comment by vancem** [comment]
I don't want EventSource to be opt-in if we can at all help it.   It REALLY degrades its usefulness since some sort of redeploy of config is needed to get profiling data.   

As mentioned in #21461 the number of users who will care about the polling inefficiency should be very small (very sophisticated, high scale), thus asking them to opt-out is reasonable (they will notice the problem and we should document in #21461 how to opt-out.   

Then in V3.0 it all gets fixed  (because we no longer poll).  

So I like it the way it is (this just allows it to be disabled).

**Comment by brianrob** [comment]
I'm with you @vancem.  Just wanted to make sure that this wasn't a bug.

**Comment by jorive** [comment]
@vancem makes sense

**Comment by jkotas** [comment]
You should talk about the opt-in vs. opt-out with AzureWebsites and AzureFunctions teams. I expect that both of them will need to do work to apply pretty broad opt out if this stays on by default. If both of these teams have a good way to apply the broad opt out, I am fine with this staying on by default in 2.2.

**Comment by jorive** [comment]
Adding some folks that use this feature: @davidfowl @mjsabby

**Comment by noahfalk** [comment]
I'm going to defer any code review until you've been able to talk with Azure Functions / Azure Websites and we've got concensus on the policy we are trying to implement. If we end with an opt-out and a 20 sec timeout, then this code looked fine.

**Comment by vancem** [comment]
My recommendation is the following

1. Check this change in immediately.    It is clearly better than what we have (users can opt out), and the faster we get that capability in the better).  
2. Don't resolve the issue however until we have followed up with Azure Functions / Azure Websites.  

I note that the likelihood is very high that the current change will work for both Azure Functions and Azure WebSites (if they have not capability to set our special modes (e.g. setting environment variables or config file entries), then that really needs to be fixed as they will need that capability sooner or later.

**Comment by jorive** [comment]
@dotnet-bot test this please

**Comment by jorive** [comment]
@dotnet-bot test Windows_NT x64 Checked CoreFX Tests

**Comment by jorive** [comment]
Any idea what this error mean on the CentOS7.1 leg failure?
```log
/mnt/resource/j/workspace/dotnet_coreclr/master/x64_debug_centos7.1_innerloop_prtest/Tools/dotnetcli/sdk/2.1.301/Microsoft.Common.CurrentVersion.targets(783,5): error MSB3511: "Configuration=Debug" is an invalid value for the "Importance" parameter. Valid values are: High, Normal and Low. [/mnt/resource/j/workspace/dotnet_coreclr/master/x64_debug_centos7.1_innerloop_prtest/tests/src/JIT/Directed/IL/rethrow/Rethrow1.ilproj]
```

**Comment by brianrob** [comment]
I've not seen that before, but looking at the run long I suspect this might be the actual failure:

```
ambiguousconstraint.il(39): warning : Non-sealed value class, made sealed [/mnt/resource/j/workspace/dotnet_coreclr/master/x64_debug_centos7.1_innerloop_prtest/tests/src/Regressions/coreclr/16123/ambiguousconstraint.ilproj]
```

**Comment by brianrob** [comment]
Nevermind, that's a warning.

**Comment by vancem** [comment]
> Any idea what this error mean on the CentOS7.1 leg failure?

Looks alot like a infrastructure error (it is confused about its command line).   I would try re-running it (someone might have fixed it), and/or also trying a 'noop' pull request to see if it is happening uniformly

**Comment by benaadams** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Innerloop Build

**Comment by jorive** [comment]
@brianrob Should https://github.com/dotnet/coreclr/blob/0a2ceb3fd146d9171b8c362aa8679d996d3e5bde/tests/src/tracing/tracecontrol/TraceControl.cs#L43 and https://github.com/dotnet/coreclr/blob/0a2ceb3fd146d9171b8c362aa8679d996d3e5bde/tests/src/tracing/tracecontrol/TraceControl.cs#L83 be updated too? CI tests passed, but it seems that this test is disabled.

**Comment by vancem** [comment]
@jorive - yes, you should update those delays as well.  Ideally they should be tied into a constant so we can update it easily in one place.

**Comment by jorive** [comment]
@vancem I updated the test. Running CI now.

**Comment by jorive** [comment]
If everything is green, can I merge this PR? and then port it to `release/2.2`?

**Comment by vancem** [comment]
> If everything is green, can I merge this PR? and then port it to release/2.2?

Yes.   Above there is a concern about whether the polling should be opt-in or opt-out, but I don't want that to delay getting the ability to OPT-OUT at all in (which is what this does).    This change is strictly better that what we have regardless of policy, so we should pus that though.

However the original issue should NOT be resolved until we have addressed Jan's concern of confirming with two partners whether the opt-out is good enough.

**Comment by vancem** [comment]
@dotnet-bot  test  Ubuntu arm Cross Checked Innerloop Build and Test

**Comment by vancem** [comment]
The CI above had the Ubuntu ARM build and test fail.

However other previous CI jobs have failed in exactly the same way.  

https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_ubuntu_innerloop_flow_prtest/8997/ https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_ubuntu_innerloop_flow_prtest/8995/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_ubuntu_innerloop_flow_prtest/8990/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_ubuntu_innerloop_flow_prtest/8989/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_ubuntu_innerloop_flow_prtest/8988/

On the other hand, while there have been these failures there also have been several successful runs as well.     There does seem to be a infrastructure problem (maybe a particular machine has bad config).    I would not however allow this failure to stop the merge, as we do believe it is infrastructure, and we have no reason to believe that this change is likely to cause a failure in the tests that this job runs.   

I will contact the CI owners to have them take a closer look.

**Comment by jorive** [comment]
@vancem The `Ubuntu arm Cross Checked Innerloop Build and Test` failure seems to be related to https://github.com/dotnet/coreclr/issues/17129.

**Comment by vancem** [comment]
adding @dotnet/dnceng.   We seem to have an issue that is causing about 1/2 of the Unbuntu ARM tests to fail.   Thus all currnet CI jobs are likely to be impacted by it.    THere seems to be a lead that is it related to #17129, but it might take a while to track down and fix.   If possible we should disable tests while a more permanent resolution is reached.

**Comment by MattGal** [comment]
@vancem  I am taking a look at the Unbuntu stuff and will reply back if I find anything interesting.

**Comment by vancem** [comment]
@jorive you can go ahead and merge this.  We will want it ported to the 2.2 servicing branch

**Comment by MattGal** [comment]
Filed https://github.com/dotnet/core-eng/issues/4954, and the machines which have failed this job in the last week or so are now offline.  We'll want to keep an eye on the next PR to see what happens.

**Pull request merged**
