### PR TITLE
Exclude DevDiv_255294.cmd for jit32 due to timeout

### PR DESCRIPTION
**Pull request by jashook**
@RussKeldorph @adiaaida ptal
/cc @dotnet/jit-contrib

### CODE REVIEW

**Comment by adiaaida** [comment]
LGTM

**Comment by CarolEidt** [comment]
LGTM

**Comment by jashook** [comment]
This change has no impact on the jobs running. Merging early.

**Comment by RussKeldorph** [comment]
LGTM

**Pull request merged**
