### PR TITLE
Check for new blocks after `entry`

### LINKED ISSUE #13507: [Arm64/Unix] tip broken
`Assertion failed 'objChild->isContained()' `
File: /home/vmjenkins/workspace/Dotnet/build_and_test/src/jit/lsraarmarch.cpp Line: 672

`Assertion failed '((consume == 0) && (produce == 0)) || (ComputeAvailableSrcCount(tree) == consume)'`
File: /home/vmjenkins/workspace/Dotnet/build_and_test/src/jit/lsra.cpp Line: 3638

crossgen of Microsoft.CodeAnalysis.VisualBasic.dll leads to this assertion
`Assertion failed 'block->bbPreds->flBlock == block->bbPrev'`
File: /home/vmjenkins/workspace/Dotnet/build_and_test/src/jit/optimizer.cpp Line: 1958

**New failing tests (due to assertions above)**
```
JIT/jit64/hfa/main/testG/hfa_nd0G_d/hfa_nd0G_d.sh
JIT/jit64/hfa/main/testG/hfa_nd0G_r/hfa_nd0G_r.sh
JIT/jit64/hfa/main/testG/hfa_nd1G_d/hfa_nd1G_d.sh
JIT/jit64/hfa/main/testG/hfa_nd1G_r/hfa_nd1G_r.sh
JIT/jit64/hfa/main/testG/hfa_nd2G_d/hfa_nd2G_d.sh
JIT/jit64/hfa/main/testG/hfa_nd2G_r/hfa_nd2G_r.sh
JIT/jit64/hfa/main/testG/hfa_nf0G_d/hfa_nf0G_d.sh
JIT/jit64/hfa/main/testG/hfa_nf0G_r/hfa_nf0G_r.sh
JIT/jit64/hfa/main/testG/hfa_nf1G_d/hfa_nf1G_d.sh
JIT/jit64/hfa/main/testG/hfa_nf1G_r/hfa_nf1G_r.sh
JIT/jit64/hfa/main/testG/hfa_nf2G_d/hfa_nf2G_d.sh
JIT/jit64/hfa/main/testG/hfa_nf2G_r/hfa_nf2G_r.sh
JIT/jit64/hfa/main/testG/hfa_sd0G_d/hfa_sd0G_d.sh
JIT/jit64/hfa/main/testG/hfa_sd0G_r/hfa_sd0G_r.sh
JIT/jit64/hfa/main/testG/hfa_sd1G_d/hfa_sd1G_d.sh
JIT/jit64/hfa/main/testG/hfa_sd1G_r/hfa_sd1G_r.sh
JIT/jit64/hfa/main/testG/hfa_sd2G_d/hfa_sd2G_d.sh
JIT/jit64/hfa/main/testG/hfa_sd2G_r/hfa_sd2G_r.sh
JIT/jit64/hfa/main/testG/hfa_sf0G_d/hfa_sf0G_d.sh
JIT/jit64/hfa/main/testG/hfa_sf0G_r/hfa_sf0G_r.sh
JIT/jit64/hfa/main/testG/hfa_sf1G_d/hfa_sf1G_d.sh
JIT/jit64/hfa/main/testG/hfa_sf1G_r/hfa_sf1G_r.sh
JIT/jit64/hfa/main/testG/hfa_sf2G_d/hfa_sf2G_d.sh
JIT/jit64/hfa/main/testG/hfa_sf2G_r/hfa_sf2G_r.sh
JIT/opt/Inline/tests/UnsafeBlockCopy/UnsafeBlockCopy.sh
```

@dotnet/arm64-contrib @jkotas @jashook

### PR DESCRIPTION
**Pull request by JosephTremoulet**
Loop construction has a check for the case that an in-loop block has a
`bbNext` block that is a new block but not visited in the loop flow
walk; make sure that check fires for `entry` as well as other loop
blocks.

Fixes #13507.

### CODE REVIEW

**Comment by JosephTremoulet** [comment]
@dotnet-bot help

**Comment by JosephTremoulet** [comment]
@dotnet-bot test Ubuntu arm64 Checked pri1r2r

**Comment by JosephTremoulet** [comment]
@sdmaclea this should address #13507; let me know if I haven't kicked off the right CI jobs

@briansull and/or @AndyAyersMS PTAL.

/cc @dotnet/jit-contrib

**Comment by JosephTremoulet** [comment]
@dotnet-bot test Windows_NT x64 full_opt ryujit CoreCLR Perf Tests Correctness test Windows_NT x86 full_opt legacy_backend CoreCLR Perf Tests Correctness test Windows_NT x86 full_opt ryujit CoreCLR Perf Tests Correctness  ([error log](https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_perflab_Windows_NT_x64_full_opt_ryujit_smoketest_prtest/334/console) reports only `Specified submission-metadata json file "D:\j\workspace\perf_perflab_---89ec9f56\submission-metadata.json" does not exist.`, which matches other [recent runs](https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_perflab_Windows_NT_x64_full_opt_ryujit_smoketest_prtest/) but latest runs are succeeding, so I'm thinking this may be a transient issue that's been resolved)

**Comment by JosephTremoulet** [comment]
Ubuntu arm64 Checked failure [reports](https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_checked_small_page_size_tst_prtest/13/testReport/) several failed tests, but I don't see any [recent runs](https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_checked_small_page_size_tst_prtest/) to compare to as a baseline, so I don't know what to make of that.

**Comment by JosephTremoulet** [comment]
Windows_NT arm Cross Checked Build and Test failure's [log](https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_windows_nt_prtest/433/console) doesn't give a clear failure reason, which seems to match other [recent runs](https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_windows_nt_prtest/)

**Comment by sdmaclea** [comment]
> Ubuntu arm64 Checked failure reports several failed tests, but I don't see any recent runs to compare to as a baseline, so I don't know what to make of that.

@jashook Can you comment on the status of Ubuntu arm64 CI?  What Ubuntu job should be triggered?

**Comment by JosephTremoulet** [comment]
Perf test correctness runs failed again, but it's really hard to believe this change is breaking them and nothing else.  @DrewScoggins, any ideas what's going on with those tests?  The console output isn't giving me much to go by...

**Comment by mikedn** [comment]
> Perf test correctness runs failed again, but it's really hard to believe this change is breaking them and nothing else

It's not this change, I have the same failures in another PR

**Comment by JosephTremoulet** [comment]
@sdmaclea, over in #13507 you [quoted](https://github.com/dotnet/coreclr/issues/13507#issuecomment-324726663)

```
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assert failure(PID 23751 [0x00005cc7], Thread: 23751 [0x5cc7]): Assertion failed 'block->bbPreds->flBlock == block->bbPrev' in 'Microsoft.CodeAnalysis.VisualBasic.Symbols.Metadata.PE.MetadataDecoder:IsOrClosedOverATypeFromAssemblies(ref,struct):bool' (IL size 213)

    File: /home/vmjenkins/workspace/Dotnet/build_and_test/src/jit/optimizer.cpp Line: 1958
    Image: /home/vmjenkins/workspace/Dotnet/build_and_test/bin/tests/pr1/Tests/coreoverlay/crossgen
```

Was that from a CI run, do you have a link to it?

**Comment by sdmaclea** [comment]
> Was that from a CI run, do you have a link to it?

@JosephTremoulet It was from my internal CI.  I just pulled your change and can confirm that the issue is resolved on Ubuntu arm64.  There were no new regressions.  Note however that I did not run your new test.

**Comment by jashook** [comment]
This seems related to https://github.com/dotnet/coreclr/pull/13640#issuecomment-325716084

**Comment by JosephTremoulet** [comment]
So then it seems this fixes the regression and the errors reported in CI runs here are unrelated, so it's good to go pending review.

**Comment by DrewScoggins** [comment]
And the perf failures are from https://github.com/dotnet/coreclr/pull/13638#issuecomment-325520695.  I have restarted the correctness runs and they should be fine.

**Comment by DrewScoggins** [comment]
I looked again and it seems like that fix that I linked did not entirely fix the issue.  @dpodder is currently working on a fix for this, but in the meantime the change does not look like it should break the perf testing.  So don't worry about the failures

**Pull request merged**
