### PR TITLE
Remove conflicting proj files

### PR DESCRIPTION
**Pull request by JohnChen0**
Some test cases have both .ilproj and .csproj files, resulting
in a race condition during build. Removing the .csproj files,
as the MSIL versions appear to be the intended ones.

### CODE REVIEW

**Comment by gkhanna79** [comment]
@mmitche Why dont we see other platform legs in CI here?

**Comment by gkhanna79** [comment]
@mmitche Is CI slow today? Or were the legs trimmed?

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@dotnet-bot test ci please (ignore)

**Comment by mmitche** [comment]
@dotnet-bot test ci please (please ignore)

**Comment by danmosemsft** [comment]
> 14:13:42 FAILED   - JIT/Regression/VS-ia64-JIT/V1.2-M02/b26496/b26496/b26496.sh
> 14:13:42                BEGIN EXECUTION
> 14:13:42                /bindings/tmp/arm32_ci_temp/coreclr/Windows_NT.x64.Release/Tests/coreoverlay/corerun b26496.exe
> 14:13:42                coreclr_initialize failed - status: 0x80004005
> 14:13:42                Expected: 100
> 14:13:42                Actual: 255
> 14:13:42                END EXECUTION - FAILED

**Comment by mmitche** [comment]
@dotnet-bot test ci please (please ignore)

**Comment by mmitche** [comment]
@dotnet-bot test ci please (ignore)

**Comment by mmitche** [comment]
@dotnet-bot test ci please (ignore)

**Comment by JohnChen0** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build please

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Pull request merged**
