### PR TITLE
[x86/Linux] Remove legacyjit and compatjit build

### PR DESCRIPTION
**Pull request by seanshpark**
Enable legacyjit and compatjit build on i386 for Win32 but disable for Linux

### CODE REVIEW

**Comment by seanshpark** [comment]
Related issue: #8590

**Comment by janvorli** [comment]
@dotnet-bot test Ubuntu x64 Formatting please

**Comment by seanshpark** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test please

**Comment by seanshpark** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by pgavlin** [comment]
LGTM as well.

**Pull request merged**
