### PR TITLE
Support docker cgroup limits

### PR DESCRIPTION
**Pull request by tmds**
- The parsing would find the wrong '-' in lines like this:
354 347 0:28 /system.slice/docker-654dd7b6b8bbfe1739ae3309b471e95ccc82b3a3f56b7879f0a811d68b5c4e1d.scope /sys/fs/cgroup/cpuacct,cpu ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpuacct,cpu
- In a docker container, the mount root and relative path in the cgroup have the same value, the relative path must not be appended to the mount point.

### CODE REVIEW

**Comment by tmds** [comment]
I've tested this as follows:
main.cpp
```
#include "/home/tmds/repos/coreclr/src/gc/unix/cgroup.cpp"

int main()
{
	CGroup cgroup;
	unsigned int cpus = 0;
	size_t mem = 0;
	if (cgroup.GetPhysicalMemoryLimit(&mem))
	{
		printf("mem: %zu\n", mem);
	}
	if (cgroup.GetCpuLimit(&cpus))
	{
		printf("cpu: %d\n", cpus);
	}
	return 0;
}
```
```
g++ main.cpp
```
Dockerfile
```
FROM fedora:25
RUN yum install -y libstdc++.so.6
WORKDIR /root
ADD ./a.out .
CMD ./a.out
```
```
$ docker build -t docker_limit .
$ docker run docker_limit
mem: 9223372036854771712
$ docker run --memory 300m docker_limit
mem: 314572800
$ docker run --cpu-period 1000 --cpu-quota 1000  docker_limit
mem: 9223372036854771712
cpu: 1
$ docker run --cpu-period 1000 --cpu-quota 2000  docker_limit
mem: 9223372036854771712
cpu: 2
```

**Comment by janvorli** [comment]
@dotnet-bot test Tizen armel Cross Debug Build please

**Comment by tmds** [comment]
Thanks @janvorli

**Comment by tmds** [comment]
@janvorli I'm having a look at what commits could be picked to bring this to 2.0.x.
These can be cherry-picked without merge-conflicts and add support for docker mem&cpu limits:
https://github.com/dotnet/coreclr/commit/16baed5f6a3f89fc28105bf82a8754d047ff115c, https://github.com/dotnet/coreclr/commit/0d53e1411cbea53adb252e854cd9a6c60e0101d2, https://github.com/dotnet/coreclr/commit/559671783f82703e48998e60a030f79aaeda15c9
Does that seem like a proper set?
Can I do a PR for these to be included in a 2.0 branch? which branch?

**Comment by janvorli** [comment]
@tmds the release/2.0.0  branch is now frozen for the 2.0.1 release, we can back port it after it opens again.

**Comment by janvorli** [comment]
@tmds I've ported these three commits to release/2.0.0 branch, so it will be part of the 2.0.2 release.

**Comment by tmds** [comment]
Thanks @janvorli !

**Pull request merged**
