### PR TITLE
Fix SysV calling convention bug in interop. We need to treat delegate…

### PR DESCRIPTION
**Pull request by yizhang82**
… field (NFT_DELEGATE) as INTEGER (as per SysV spec) since it is a pointer type, otherwise we would end up passing it via stack which would cause all sorts of badness. Same for SAFEHANDLE/CRITICALHANDLE. It's not clear to me what the right semantics for DATE/CURRENCY is but they are Windows-only types, so we probably don't care yet.

### CODE REVIEW

**Comment by yizhang82** [comment]
@jkotas Turns out there is actually a bug in the code you mentioned earlier today which is failing one of our test. I made a fix based on my limited understanding of the SysV calling convention. Can you take a look?
CC @tijoytom @botaberg

**Comment by yizhang82** [comment]
Fix #4196

**Comment by jkotas** [comment]
LGTM

cc @LLITCHEV

**Comment by jkotas** [comment]
@mmitche All Ubuntu jobs in CoreCLR repo are failing with:

```
ERROR: Unable to find project for artifact copy: dotnet_corefx/master/nativecomp_ubuntu_release
```

Any ideas?

**Comment by LLITCHEV** [comment]
LGTM

**Comment by LLITCHEV** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by mmitche** [comment]
Ahh, @mellinoe removed that job yesterday.  Forgot we'll need to update this side also.  I'll take a look

**Comment by pgavlin** [comment]
@yizhang82 @LLITCHEV we should reenable the failing test as well as part of this PR.

**Comment by yizhang82** [comment]
@pgavlin Thanks for the reminder. PR updated.

**Comment by pgavlin** [comment]
LGTM. Thanks!

**Comment by yizhang82** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by yizhang82** [comment]
@mmitche Is the Ubuntu issue fixed? It looks like you've merged a PR https://github.com/dotnet/coreclr/pull/4415

**Comment by yizhang82** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Pull request merged**
