### PR TITLE
ARM-CI: Improve readability of the ARM CI script

### PR DESCRIPTION
**Pull request by prajwal-aithal**
Low priority PR to improve readability of the ARM CI script

Signed-off-by: Prajwal A N <an.prajwal@samsung.com>

### CODE REVIEW

**Comment by RussKeldorph** [comment]
@jashook

**Comment by prajwal-aithal** [comment]
@dotnet-bot test CI please

**Comment by prajwal-aithal** [comment]
@jashook Could you please review this PR?

I have tested its working on my local machine and think that it should work as expected on the CI system as well (no changes need to be made to the emulator).

**Comment by prajwal-aithal** [comment]
The ARM emulator CI checks are failing currently as this PR makes changes to the `tests/scripts/arm32_ci_script.sh` script and the same changes are not yet reflected in the CI system call to this script.

**Comment by jashook** [comment]
lgtm

**Pull request merged**
