### PR TITLE
Fix for a bug in recursive tail call to loop transformation.

### PR DESCRIPTION
**Pull request by erozenfeld**
The bug affects recursive tail calls where there is both a this arg and
an argument passed in outgoing arg space.

I brought over RecursiveTailCall tests and added TestStackParam test
that was a repro for the bug.

/cc @dotnet/jit-contrib

### CODE REVIEW

**Comment by erozenfeld** [comment]
@sivarv PTAL

**Comment by LLITCHEV** [comment]
@dotnet-bot test this please

**Comment by LLITCHEV** [comment]
@dotnet-bot test this please

**Comment by LLITCHEV** [comment]
LGTM, assuming the test in the CI passes.

**Comment by erozenfeld** [comment]
@dotnet-bot test this please

**Comment by sivarv** [comment]
Please add comments to morph.cpp and unit test case.
Otherwise, LGTM.

**Comment by erozenfeld** [comment]
Comments added.

**Comment by CarolEidt** [comment]
LGTM

**Comment by sivarv** [comment]
I see Just above the logic in morph.cpp

   // Hoist arg setup statement for the 'this' argument.
    GenTreePtr thisArg = recursiveTailCall->gtCallObjp;
    if (thisArg && !thisArg->IsNothingNode() && !thisArg->IsArgPlaceHolderNode())
    {
        GenTreePtr thisArgStmt = gtNewStmt(thisArg, callILOffset);
        fgInsertStmtBefore(block, earlyArgInsertionPoint, thisArgStmt);

    }

That is the condition we use for adding 'thisptr' is a compound condition.  Whereas to account for 'thisptr' in early args we are just checking whether it is non-null.  Don't these two conditions should be in sync?

**Comment by erozenfeld** [comment]
@sivarv No. If thisArg->IsArgPlaceholderNode() is true, there is no setup statement to hoist and `this` arg will appear as a late arg; however, we sill need to account for `this` argument when calculating indexes of early args.

**Pull request merged**
