### PR TITLE
Enable crossgen /createpdb command on Windows

### PR DESCRIPTION
**Pull request by JohnChen0**
This commit addresses issue #3131, and allows Windows version of CrossGen built from GitHub to create PDBs for native images and Ready to Run images.

New header files cvinfo.h and cvconst.h were copied from https://github.com/Microsoft/microsoft-pdb/blob/master/include.

This feature is currently only available on Windows, since it requires an additional module diasymreader.dll, which is not yet available on other platforms.

### CODE REVIEW

**Comment by JohnChen0** [comment]
@brianrob PTAL

**Comment by rahku** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by JohnChen0** [comment]
@dotnet-bot test OSX x64 Checked

**Comment by jkotas** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by brianrob** [comment]
LGTM

**Pull request merged**
