### PR TITLE
Update format.py to use dotnet cli rc3

### PR DESCRIPTION
**Pull request by JosephTremoulet**
This will be necessary once dotnet/jitutils#79 gets merged.

### CODE REVIEW

**Comment by JosephTremoulet** [comment]
@adiaaida PTAL

**Comment by JosephTremoulet** [comment]
Formatting legs are failing because this isn't backwards-compatible with the current project.json setup in jitutils, so this and dotnet/jitutils#79 will need to get merged at the same time.

**Comment by adiaaida** [comment]
LGTM

**Comment by JosephTremoulet** [comment]
@dotnet-bot test Ubuntu x64 Formatting
@dotnet-bot test Windows_NT x64 Formatting

**Comment by JosephTremoulet** [comment]
@dotnet-bot test Ubuntu x64 Formatting
@dotnet-bot test Windows_NT x64 Formatting

**Pull request merged**
