### PR TITLE
Only set THREAD_IS_SUSPENDED if we are truly doing an async stack walk

### PR DESCRIPTION
**Pull request by davmason**
There are some checks in the stack walker that abort if we are doing something that could deadlock. This are valuable when the profiler is doing an async stackwalk, but when the runtime is suspended via `ICorProfilerInfo10::SuspendRuntime` there is no risk of a deadlock so we should let the stackwalk proceed.

### CODE REVIEW

**Comment by davmason** [comment]
Fixes #26579

**Comment by k15tfu** [comment]
@davmason @noahfalk kindly reminder

**Comment by noahfalk** [comment]
@davmason is out of the office for a bit, but I don't think this is urgent? 
Leaving it unmerged until he returns.

**Comment by k15tfu** [comment]
@noahfalk As I said here (https://github.com/dotnet/coreclr/issues/26579#issuecomment-530835595) I want it to be included in 3.1. How much time do we have?

**Pull request merged**
