### PR TITLE
Update the build system to use llvm-ranlib.  llvm-ar is not compatibl…

### PR DESCRIPTION
**Pull request by kangaroo**
…e with the system ranlib on all targets [aarch64]

### CODE REVIEW

**Comment by janvorli** [comment]
LGTM, thank you!

**Comment by jkotas** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build and Test  please

**Comment by jkotas** [comment]
CentOS build is failing with: Unable to locate llvm-ranlib

**Comment by kangaroo** [comment]
My CentOS box is 7.2, and the llvm package provides llvm-ranlib (that said it is just a symlink to llvm-ar).  I'm not sure why it would be missing on 7.1?

**Comment by danmosemsft** [comment]
@dotnet-bot test this please

**Comment by danmosemsft** [comment]
@kangaroo do you plan to take a further look at this build error so we can close this PR one way or another?

**Comment by kangaroo** [comment]
@dotnet-bot build this

**Comment by danmosemsft** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build and Test ("not found")
@dotnet-bot test Linux ARM Emulator Cross Release Build ("not found")
@mmitche why not found? these were only 2 days ago. example: https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_emulator_cross_release_ubuntu_prtest/851/

**Comment by mmitche** [comment]
@danmosemsft It was 4 days ago.   There is a max number of builds kept also.  This should be more generous in the future.,

**Comment by danmosemsft** [comment]
@kangaroo centos failed again with 'Unable to locate llvm-ranlib'

**Comment by danmosemsft** [comment]
@kangaroo thoughts about the centos 7.1 problem?

**Comment by danmosemsft** [comment]
@kangaroo ?

**Comment by jkotas** [comment]
Closing old inactive PRs. @kangaroo please feel free to resubmit if you get a chance to finish this. Thanks!

**Pull request closed without merging**
