### PR TITLE
Update the version of the xUnit Performance Api

### PR DESCRIPTION
**Pull request by jorive**
- This version fail broken benchmarks, so we can catch bugs earlier.
- Changed the harness to exit with non-zero code when an exception is thrown.

### CODE REVIEW

**Comment by jorive** [comment]
@dotnet/rap-team PTAL

**Comment by nategraf** [comment]
Will `ex.ToString()` give stack trace?

**Comment by jorive** [comment]
Yes, it will give the exception type, message and stack trace.

**Comment by jorive** [comment]
@dotnet-bot help

**Comment by jorive** [comment]
@dotnet-bot test Windows_NT x64 perf
@dotnet-bot test Windows_NT x86 perf
@dotnet-bot test linux perf

**Comment by jorive** [comment]
@dotnet-bot test Windows_NT x64 perf scenarios
@dotnet-bot test Windows_NT x86 perf scenarios

**Comment by jorive** [comment]
The "Performance Scenarios Tests" have been failing for 5 days now (unrelated to these changes).

**Comment by jorive** [comment]
Anyone familiar with the InnerLoop build failures?

**Comment by adiaaida** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Innerloop Build please

**Comment by adiaaida** [comment]
LGTM

**Pull request merged**
