### PR TITLE
[Proposal] Force the inlining of StringBuilder.Append(char)

### PR DESCRIPTION
**Pull request by adamsitnik**
`StringBuilder.Append(char)` can benefit a lot from inlining (the same way as [List.Add](https://github.com/dotnet/coreclr/blob/111b71a65bce77e63d2463a972fe78aa042c5c0a/src/System.Private.CoreLib/shared/System/Collections/Generic/List.cs#L197) does)

It's a very frequently used method and I believe that the performance improvement is worth the size growth. 

The "before" includes https://github.com/dotnet/coreclr/pull/27340 from yesterday:

|               Method | Toolchain | length |         Mean | Ratio | Allocated |
|--------------------- |---------- |------- |-------------:|------:|----------:|
|          Append_Char |     after |    100 |     263.8 ns |  0.86 |     544 B |
|          Append_Char |    before |    100 |     308.5 ns |  1.00 |     544 B |
|                      |           |        |              |       |           |
| Append_Char_Capacity |     after |    100 |     187.7 ns |  0.68 |     272 B |
| Append_Char_Capacity |    before |    100 |     277.2 ns |  1.00 |     272 B |
|                      |           |        |              |       |           |
|          Append_Char |     after | 100000 | 176,884.8 ns |  0.84 |  209968 B |
|          Append_Char |    before | 100000 | 210,701.6 ns |  1.00 |  209968 B |
|                      |           |        |              |       |           |
| Append_Char_Capacity |     after | 100000 | 190,679.7 ns |  0.75 |  200072 B |
| Append_Char_Capacity |    before | 100000 | 253,892.5 ns |  1.00 |  200072 B |

```cs
[Benchmark]
[Arguments(100)]
[Arguments(100_000)]
public StringBuilder Append_Char(int length)
{
    StringBuilder builder = new StringBuilder();

    for (int i = 0; i < length; i++)
    {
        builder.Append('a');
    }

    return builder;
}

[Benchmark]
[Arguments(100)]
[Arguments(100_000)]
public StringBuilder Append_Char_Capacity(int length)
{
    StringBuilder builder = new StringBuilder(length);

    for (int i = 0; i < length; i++)
    {
        builder.Append('a');
    }

    return builder;
}
```

### CODE REVIEW

**Comment by jkotas** [comment]
I do not think that this is the right throughput/codesize trade-off to make.

**Comment by EgorBo** [comment]
@adamsitnik I do it this way:
1) Builld CoreCLR repo, ideally full build with tests and `Checked` config:
```
build.cmd -checked
```
2) Clone & build https://github.com/dotnet/jitutils
3) run
```
jit-diff diff --output C:\prj\jit-diff -f --pmi --core_root C:\prj\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root --base C:\prj\coreclr\bin\Product\Windows_NT.x64.Checked
```
Apply change, build corelib:
```
build.cmd -checked -skiptests -skipnative
```
4) run command from 3) again
5) run
```
jit-analyze.bat --base C:\prj\jit-diff\dasmset_1\base --diff C:\prj\jit-diff\dasmset_2\base\ --recursive -c 100
```
Should print a diff.

**Comment by danmosemsft** [comment]
>> the same way as List.Add does

> I think this change is still debatable.

I just noticed List<T>.Clear was force inlined. That was more surprising to me. I would have thought that was significantly less common. It also seems maybe larger than Add. https://github.com/dotnet/coreclr/pull/11104

**Comment by jkotas** [comment]
> List.Clear 

List.Clear has a large opportunity for dead-code removal. See the discussion in the issue that introduced this.

>  thought that was significantly less common.

That means the cost of aggressively inlining it is significantly less. Aggressive inlining is most problematic on methods that are used frequently.

**Comment by jkotas** [comment]
The string building methods are often big, with a mix of logic and Append calls. The problem with aggresively inlining code into such methods is that the JIT will hit the threshold where it gives up optimizations much faster and the method overall will get much slower. It should be easy to build a micro-benchmark based on pattern like this that shows a significant regression due to this change.

**Comment by jkotas** [comment]
It is unlikely that somebody will be calling `builder.Append` in a loop like the micro-benchmark. `builder.Append('a', length);` is both faster and more concise.

**Comment by JeremyKuhne** [comment]
I agree with @jkotas- I don't think we should inline this particular method.

**Comment by adamsitnik** [comment]
> It is unlikely that somebody will be calling builder.Append in a loop like the micro-benchmark

`StringBuilder.Append(char)` is frequently used in a loop that filters out some characters from the source string. An example:

https://github.com/dotnet/BenchmarkDotNet/blob/0768b7206be0078516034f0e6a1690b61561c55c/src/BenchmarkDotNet/Diagnosers/DisassemblyPrettifier.cs#L123-L126

I must admit that when I was creating this PR I forgot about the other use case - multiple calls to `Append(char)` from a single method:

https://github.com/Bunny83/SimpleJSON/blob/1945ecb12b54ab84f62f43609b82616ae16742e2/SimpleJSON.cs#L712-L725

In this case, inlining would decrease performance.

I agree that forcing the inlining of this method is a bad idea. Ideally, JIT should inline it only in loops that call this method once. Thank you for the productive discussion!

**Pull request closed without merging**
