### PR TITLE
increase timeout for altjit jobs

### PR DESCRIPTION
**Pull request by sandreenko**
Windows_NT x86_arm_altjit Checked r2r  fails with timeout, increase timeout for altjit jobs.

### CODE REVIEW

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT x86_arm_altjit Checked r2r

**Comment by sandreenko** [comment]
PTAL @jashook , @BruceForstall 
cc @dotnet/jit-contrib

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT x64_arm_altjit Checked r2r

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT x64_arm64_altjit Checked r2r

**Comment by BruceForstall** [comment]
@dotnet-bot test CI please

**Pull request merged**
