### PR TITLE
Stop building x86 LEGACY_BACKEND

### PR DESCRIPTION
**Pull request by BruceForstall**
Since we require a compatjit.dll to be built so the JIT NuGet
package can be built, even if JIT32 isn't being built, change
the compatjit.dll build (when JIT32 isn't being built) to just
a normal JIT build.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@pgavlin PTAL
cc @dotnet/jit-contrib

**Comment by adiaaida** [comment]
You should make sure you delete all the legacy backend jobs in the lab along with this change.

**Comment by BruceForstall** [comment]
@adiaaida updated.

**Comment by BruceForstall** [comment]
@dotnet-bot test ci please

**Comment by pgavlin** [comment]
Build changes LGTM

**Comment by adiaaida** [comment]
job changes lgtm

**Comment by BruceForstall** [comment]
@dotnet-bot test this please

**Pull request merged**
