### PR TITLE
Suppress ms_struct warnings for non-Intel arches

### PR DESCRIPTION
**Pull request by franksinankaya**
@am11 @jkotas @janvorli

### CODE REVIEW

**Comment by am11** [comment]
Out of curiosity, what was the warning message?

**Comment by franksinankaya** [comment]
Sure: "src/inc/dacprivate.h:835:17: warning: ‘ms_struct’ attribute directive ignored [-Wattributes]"

src/inc/dacprivate.h:41:47: warning: ‘ms_struct’ attribute directive ignored [-Wattributes]
 #define MSLAYOUT __attribute__((__ms_struct__))

GCC page says attribute is x86 only.

**Comment by jkotas** [comment]
> GCC page says attribute is x86 only.

So make the ifdef positive for x86 only? Otherwise, it will need to be touched for every new platform.

**Comment by am11** [comment]
During my previous PR work, I found that this padding is in fact only required for x86-32, not even by 64-bit platforms.

**Comment by franksinankaya** [comment]
My web search says ms_struct is x86 and x86-64 specific.

**Comment by franksinankaya** [comment]
I'm posting a change to limit it to x86 only.

**Comment by am11** [comment]
Specific to dacprivate.h case, the only reason `MSLAYOUT` was added was x86-32: https://github.com/dotnet/coreclr/issues/8369. 64-bit was working long before that happened.

**Pull request merged**
