### PR TITLE
Don't generate explicit newlines in SIMD tests

### PR DESCRIPTION
**Pull request by BruceForstall**
Use Console.WriteLine() instead.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@CarolEidt PTAL
cc @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build

**Comment by BruceForstall** [comment]
@mmitche  how reliable is `Linux ARM Emulator Cross Debug Build`? Seems like it fails on my PRs about 70% of the time, unrelated to my changes.

**Comment by mmitche** [comment]
@BruceForstall Not very reliable right now.  Perhaps @jashook knows more.  I haven't lookat it at all.

**Comment by jashook** [comment]
I am in the same spot as @mmitche

**Comment by BruceForstall** [comment]
@mmitche @jashook Should we even bother running it, given the noise?

**Pull request merged**
