### PR TITLE
Disable 3 failing ARM tests on Windows

### PR DESCRIPTION
**Pull request by BruceForstall**
mainv1, mainv2 against #15150 (JitStressRegs=1; JitStressRegs=8)
dlstack against #15156 (JitStress=2 + JitStressRegs=3)

### CODE REVIEW

**Comment by BruceForstall** [comment]
test Windows_NT arm Cross Checked jitstressregs1 Build and Test
test Windows_NT arm Cross Checked jitstressregs8 Build and Test
test Windows_NT arm Cross Checked jitstress2_jitstressregs3 Build and Test

**Comment by BruceForstall** [comment]
@jashook @dotnet/arm32-contrib @dotnet/jit-contrib PTAL

**Comment by jashook** [comment]
If these are stress specific we can disable them only for stress modes.

**Comment by BruceForstall** [comment]
test Windows_NT arm Cross Checked jitstressregs1 Build and Test
test Windows_NT arm Cross Checked jitstressregs8 Build and Test
test Windows_NT arm Cross Checked jitstress2_jitstressregs3 Build and Test

**Comment by BruceForstall** [comment]
@jashook Updated to disable with `PROTOJIT_JITSTRESS_FAIL`

**Comment by jashook** [comment]
I dont think we have PROTOJIT_JITSTRESS_FAIL in netci.groovy hooked up yet. Until then we may have to just use JITSTRESS_FAIL. Unless we add PROTOJIT_JITSTRESS_FAIL before this pr.

**Comment by BruceForstall** [comment]
@jashook It's already there. See:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_jitstressregs1_tst/4/consoleText

```
C:\Users\robox\j\workspace\arm_cross_che---17ba3c86\bin\tests\Windows_NT.arm.Checked>C:\Tools\Smarty.exe /noecid /noie /workers 9 /inc EXPECTED_PASS /exc PROTOJIT_FAIL /exc PROTOJIT_JITSTRESS_FAIL /exc PROTOJIT_JITSTRESS_EXCLUDE /lstFile Tests.lst 
```

Also, this is super temporary as I'll have to change it for https://github.com/dotnet/coreclr/pull/15134.

**Pull request merged**
