### PR TITLE
Build managed tests with dotnet

### PR DESCRIPTION
**Pull request by chsienki**
This is a re-PR of #19230 as the previous one broke the priority flag, which is fixed here.

### CODE REVIEW

**Comment by chsienki** [comment]
@dotnet-bot test Windows_NT x64 Checked please

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT x86 Checked Build and Test
@dotnet-bot test Windows_NT x64 Build and Test

**Comment by BruceForstall** [comment]
@chsienki Looks like the arm64 release pri-1 builds are failing all the pri-1 tests. From what I can tell, the pri-1 tests are not getting built, even though I do see "-priority=1" in various places in the build log.

Any ideas?

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/arm64_cross_release_windows_nt_flow/

The thing is that arm32/arm64 use a different test list, that explicitly lists all tests to run. I'm worried that what could happen to the other architectures is that we pass "-priority=1" but for some reason we don't actually build pri-1 tests, and we don't notice that because when we run tests, we only run what we find.

**Comment by BruceForstall** [comment]
In fact, this appears to be what has happened:

The last x64 checked Windows NT pri-1 job that runs on every merge, before your change:
```
GRAND TOTAL: 12278          0          0           0        31864.892s (2683.353s)
```
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/checked_windows_nt/10089/consoleText

After your change:
```
GRAND TOTAL: 2541          0          0           0        9475.166s (757.343s)
```
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/checked_windows_nt/10092/consoleText

You can also see that the time these jobs are taking has dropped from almost 2 hours to under 1 hour.

**Comment by BruceForstall** [comment]
@chsienki Seeing as how this is going to break arm32/arm64 pri-1 Windows testing, and cause us to silently lose coverage everywhere else, and how it's the weekend, I'm going to revert this.

cc @RussKeldorph

**Comment by BruceForstall** [comment]
Revert with: https://github.com/dotnet/coreclr/pull/19287

**Comment by chsienki** [comment]
Dang, ok thanks @BruceForstall. I'll take a look and see if we can eventually get this in without breaking everything.

**Pull request merged**
