### PR TITLE
Use lea for multiply by 3, 5 or 9

### PR DESCRIPTION
**Pull request by briansull**
When choosing an instruction for a GT_MUL we will now use an LEA instruction for a MUL by an immediate 3, 5 or 9

The multiply has to be a non overflow checking multiply as a LEA does not set the condition codes.
In Lowering we also must make sure that we don't 'contain' an indirection as the source operand.

### CODE REVIEW

**Comment by jkotas** [comment]
Could you please fix the typo in the title, and rebase the merge away from the PR.

**Comment by cmckinsey** [comment]
Since we talked offline about this we know there was good impact on our benchmarks/FX-code size. You might just re-iterate that info here so others know we measured the impact of this already.

Change is LGTM.

**Comment by cmckinsey** [comment]
This change is in reference to issue #447

**Comment by jkotas** [comment]
LGTM

**Comment by briansull** [comment]
Code size differences:

The assembly code size for the 'lea' instruction will usually be the same size as the 'imul' instruction.  n the rare case when the register used is rbp, the 'lea' instruction be two byte larger than the 'imul'.  Also when could have contained an indirection as a source operand, such as [rax+8], for the 'imul', the new code will have an additional 'mov' (load) instruction and the code size for this sequence will be one byte larger.

**Pull request merged**
