### PR TITLE
Remove thread parameter from InternalMalloc/Free/New/Delete

### PR DESCRIPTION
**Pull request by adityamandaleeka**
Remove thread parameter from InternalMalloc/Free/New/Delete and related functions. It's no longer needed due to the recent removal of thread suspension and the associated bookkeeping from PAL. This saves us from having to GetCurrentThread in a bunch of places, which should be a perf win. There are a few more functions (not related to malloc) where this can be done, so I will send at least one more PR for those.

Also remove USE_SIGNALS_FOR_THREAD_SUSPENSION and all the code under it since it's no longer needed.

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
This is also related to #1795

**Comment by sergiy-k** [comment]
LGTM

**Comment by janvorli** [comment]
LGTM

**Comment by janvorli** [comment]
@dotnet-bot test Windows_NT x64 Debug Build

**Comment by janvorli** [comment]
@dotnet-bot test Windows_NT

**Comment by janvorli** [comment]
@dotnet-bot test x64

**Pull request merged**
