### PR TITLE
Add some additional cases to the struct ABI test.

### PR DESCRIPTION
**Pull request by pgavlin**
These tests cover boundary cases for the SysV ABI.

### CODE REVIEW

**Comment by pgavlin** [comment]
@LLITCHEV PTAL

**Comment by LLITCHEV** [comment]
The failing Windows x86 Release build looks interesting, but I don't think it is related to this change.
LGTM

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT x86 Release

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT x86

**Comment by pgavlin** [comment]
Filed #2022 to track the Windows x86 Release build failure. /cc @mmitche

**Comment by pgavlin** [comment]
@dotnet-bot test this please

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@dotnet-bot test Windows_NT x86 Release Build

**Pull request merged**
