### PR TITLE
Enabled more SOS commands and fixed various issues.

### PR DESCRIPTION
**Pull request by mikem8361**
Create a version resilient interface between sos (libsos.so) and the lldb plugin (libsosplugin.so). There is a ILLDBServices interface between the two with a proper QI/Addref/Release interface so we can add new interfaces later and still be backwards and forward compatible. Internally in sos there is a DebugClient wrapper around this interface that makes it look like all the individual dbgeng interfaces (IDebugControl4, IDebugSymbols, IDebugDataSpaces, etc) even with QI, etc.

Enable the sos the u (clru), DumpStack (dumpstack), EEStack (eestack), DumpIL (dumpil), DumpSig and DumpSigElem commands (aliases in parans).

Add the clrstack -f option that displays the intermixed native and managed frames when managed assembly and offsets.

Implement GetContextFromFrame. Enable the _EFN_* exported functions.

Add source file/line number support (native only) via GetLineByOffset.

Fix bug when executed just "sos". Displays help now.

Fixed a problem where some HelperMethodFrames were not unwinding; clrstack would stop without displaying managed functions on the stack. The HelperMethodFrames were not sometimes unwinding because the lldb VirtualUnwind used by the DAC was using (via the data target) to do the out of context unwind has some limitations.  lldb doesn't have a way to unwind an arbitrary register context so the VirtualUnwind implementation searches through the thread's frames until it finds a match and returns the next one. The match was an exact match and in some cases it didn't find a frame. Changed it to check if the incoming context's SP is in between frames and return the next one if so.

### CODE REVIEW

**Comment by mikem8361** [comment]
@noahfalk and @janvorli could you review?

**Comment by noahfalk** [comment]
A lot of changes there, I'll try to set aside some time tomorrow to go through it all : )

**Comment by janvorli** [comment]
LGTM. I can't wait to start using it, it will make my debugging experience much better!

**Comment by janvorli** [comment]
@dotnet-bot test this please

**Comment by janvorli** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Comment by mikem8361** [comment]
@noahfalk ping (CR)

**Comment by stephentoub** [comment]
> Add the clrstack -f option that displays the intermixed native and managed frames when managed assembly and offsets.

Very excited for this. Thanks!

**Comment by adityamandaleeka** [comment]
This is minor, but it looks like `PrintNativeStack` only prints the symbol at the given address. Should it be renamed?

**Comment by mikem8361** [comment]
It prints (see the WriteColumn's) all the information about a native frame that the clrstack command displays about a managed frame. It also displays the symbol and displacement from the symbol. So I think it is named appropriately.

**Comment by adityamandaleeka** [comment]
Right, I guess I meant that it only prints info about a frame, not the entire stack. If there's already a precedent for naming it that way, though, I'm fine with it.

**Comment by mikem8361** [comment]
Ok, I get it now. Sorry for being so dense.  Yes it probably should be called PrintNativeStackFrame. I'll try to change with any other review changes I get.

**Pull request merged**
