### PR TITLE
Undo StompWriteBarrierResize reordering

### PR DESCRIPTION
**Pull request by jkotas**
The recent commit introduced race by changing where StompWriteBarrierResize is called relative to other global state updates. Revert this change to fix the intermittent crashes that we are seeing because of that. We will look at fixing the theoretical problem that this reordering was trying to address in better way separately.

### CODE REVIEW

**Comment by jkotas** [comment]
cc @sergiy-k @gkhanna79 @kouvel

**Comment by jkotas** [comment]
Fixes https://github.com/dotnet/corefx/issues/8992

**Comment by jkotas** [comment]
Opened https://github.com/dotnet/coreclr/issues/5741 on fixing the theoretical problem that undoing this change may introduce

**Comment by sergiy-k** [comment]
LGTM

**Comment by gkhanna79** [comment]
LGTM

**Comment by kouvel** [comment]
LGTM

**Pull request merged**
