### PR TITLE
ARM64: Test Update (d3f5a70b404386c538053cb0fe1746338ac4d342)

### PR DESCRIPTION
**Pull request by kyulee1**
Fixes https://github.com/dotnet/coreclr/issues/6060

### CODE REVIEW

**Comment by kyulee1** [comment]
@dotnet test Windows_NT arm64 checked

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 checked

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 release

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 checked pri1r2r

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 release pri1r2r

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 checked gcstress0x3

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 checked

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 checked

**Comment by danmosemsft** [comment]
@kyulee1 is this PR still active? I can't access the logs of the old failures.

**Comment by danmosemsft** [comment]
@dotnet-bot test this please  (Machine went offline)

**Comment by danmosemsft** [comment]
@dotnet-bot test this please ("Arm64 generic infrastructure failure")_

**Comment by danmosemsft** [comment]
@mmitche @kyulee1  who owns the ARM64 infrastructure? it seems broken.

**Comment by mmitche** [comment]
@danmosemsft Broken because of lab policy changes, fixes are in the works.

**Comment by gkhanna79** [comment]
@jashook is looking into this.

**Comment by danmosemsft** [comment]
@dotnet-bot test this please

**Comment by jkotas** [comment]
Closing old stale PRs. @dotnet/jit-contrib please create a new PR once this is ready.

**Pull request closed without merging**
