### PR TITLE
Fix exception tracker popping in a corner case

### PR DESCRIPTION
**Pull request by janvorli**
This change fixes exception tracker popping in case a managed exception is handled in
the CoreCLR native code. The current exception tracker has an empty scanned stack
range in that case and the existing code in the ExceptionTracker::PopTrackers was
skipping the popping in such case, considering it a case when an exception happened
while the exception tracker was being setup.
Adding check that the tracker is in the first pass to that condition fixes the problem,
since when the tracker is in the second pass, it cannot be the case in which the PopTrackers
wanted to skip the popping.
The tracker is then popped correctly in the code below.

### CODE REVIEW

**Comment by janvorli** [comment]
@jkotas can you take a look please?
@sergiy-k - FYI - this fixes the docker hang issue in the release build.

**Comment by janvorli** [comment]
It looks like the fix has broken handling exceptions in exception filters, I need to look into that. I think I know what's going on and I need to modify or revert my previous fix for exception handling in filters.

**Comment by janvorli** [comment]
I've reverted #2031, since this change fixes it too and it was conflicting with the other one.

**Comment by jkotas** [comment]
LGTM

**Pull request merged**
