### PR TITLE
[SOS][ARM/Linux] Enable clru SOS command

### PR DESCRIPTION
**Pull request by lucenticus**
This PR removes `#ifndef FEATURE_PAL ` to enable `clru` command on ARM/Linux. From CoreCLR side we just need to remove #ifdefs, on `lldb` side we have to slightly change the code to enable armv7l architechture.
Related issue: https://github.com/dotnet/coreclr/issues/6458
CC: @Dmitri-Botcharnikov @chunseoklee @mikem8361

### CODE REVIEW

**Comment by mikem8361** [comment]
LGTM

**Comment by lucenticus** [comment]
@mikem8361 I've added commit which fix incorrect dissasm of thumb code on ARM/Linux. 
Please note that we have to add `settings set target.default-arch thumbv7` to lldb.

**Comment by lucenticus** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please
@dotnet-bot test Windows_NT x86 ryujit Checked Build and Test please

**Comment by Dmitri-Botcharnikov** [comment]
LGTM

**Comment by lucenticus** [comment]
@dotnet-bot test Windows_NT x86 ryujit Checked Build and Test please

**Comment by lucenticus** [comment]
@dotnet-bot test Windows_NT x86 ryujit Checked Build and Test please

**Comment by Dmitri-Botcharnikov** [comment]
@seanshpark

**Pull request merged**
