### PR TITLE
Fix JIT allocator shutdown race

### LINKED ISSUE #18777: JIT alloc assert "!s_pagePool.isPoolPage(page)" running corefx tests in CI
https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_windows_nt_corefx_innerloop_prtest/388/consoleText
```
Assert failure(PID 7036 [0x00001b7c], Thread: 6744 [0x1a58]): Assertion failed '!s_pagePool.isPoolPage(page)' in 'Xunit.Sdk.ExtensibilityPointFactory:Dispose()' (IL size 21)

    File: d:\j\workspace\x64_checked_w---43686a05\src\jit\alloc.cpp Line: 301
    Image: D:\j\workspace\x64_checked_w---43686a05\bin\tests\Windows_NT.x64.Checked\testhost\dotnet.exe
```

### PR DESCRIPTION
**Pull request by mikedn**
Fixes #18777

### CODE REVIEW

**Comment by mikedn** [comment]
> Is there an assumption that every arena allocator is properly destroyed before shutdown is called? I am not sure we can guarantee this.

Nope, it would have been simpler if such a guarantee existed. A compilation thread may run in parallel with `shutdown` and can even allocate new memory - that's what triggered the assert in the first place, the pool page that was freed by shutdown was allocated again by `VirtualAlloc`.

`shutdown` simply frees the pool page if it's available. Otherwise it prevents it from being made available again when `releasePage` is called.

**Comment by mikedn** [comment]
It might be worth noting that both my previous "acquire" implementation and the one that it replaced allowed the pool to be resurrected post shutdown. They allowed transition from random states to the "acquired" state and then back to "available" state, even if the pool was shutdown. Fortunately the only negative consequence of that seems to have been leaking the pool page.

This change prevents this problem by making the state transition between "available" and "acquired" conditional.

Eh, lock freed code...

**Comment by AndyAyersMS** [comment]
Now that Jan has pushed ahead with #18924 perhaps we should hold off on this.

**Comment by mikedn** [comment]
Superseded by #8924

**Pull request closed without merging**
