### PR TITLE
fix the Incorrect EventPipe Assert, fixes #16158

### LINKED ISSUE #16158: Incorrect EventPipe Assert
I believe this assert is incorrect, but likely hasn't been hit for events that have no arguments:

```
_ASSERTE((pInstance->GetData() != NULL && pInstance->GetLength() > 0) || (pInstance->GetData() != NULL && pInstance->GetLength() == 0));
```

https://github.com/dotnet/coreclr/blob/master/src/vm/eventpipebuffer.cpp#L263

I think it should be:

```
_ASSERTE((pInstance->GetData() != NULL && pInstance->GetLength() > 0) || (pInstance->GetData() == NULL && pInstance->GetLength() == 0));
```

### PR DESCRIPTION
**Pull request by adamsitnik**
Fix for  #16158

### CODE REVIEW

**Comment by brianrob** [comment]
@adamsitnik, the test that I sent you offline yesterday is for validation of this fix.  I just can't check it in yet because it won't work on Windows since EventSource events don't flow to EventPipe yet.  Were you able to use something like that test to validate this on Linux?

**Comment by brianrob** [comment]
Other than the testing issue, LGTM.

**Comment by adamsitnik** [comment]
@brianrob  I have not checked Linux

**Comment by brianrob** [comment]
If you were able to validate this on Windows, that is sufficient.  I'm not sure we have an events with no payload arguments built-in to the runtime though.  Were you able to find one and test it?

**Comment by brianrob** [comment]
If not, it would be good to validate this on Linux with an EventSource.

**Comment by adamsitnik** [comment]
@brianrob I am going to find some event without payload and add test for it.

**Comment by adamsitnik** [comment]
>  I just can't check it in yet because it won't work on Windows since EventSource events don't flow to EventPipe yet.

@brianrob @nategraf is there any easy/quick way to enable it on Windows for debugging purposes? afaik it conflicts with ETW so I am not going to push it anywhere, but it would be very helpful for me if I could enable it on Windows

**Comment by nategraf** [comment]
You can try setting `FeaturePerfTracing` to true in the [clr.coreclr.props](https://github.com/dotnet/coreclr/blob/master/clr.coreclr.props) file before you build, but if I remember corectly this isn't suffcient and there is outstanding work to do.

**Comment by adamsitnik** [comment]
@brianrob  I tested it on Linux, your test is passing

image

**Pull request merged**
