### PR TITLE
Fix corerun to support argv[0] that's not a full path

### PR DESCRIPTION
**Pull request by stephentoub**
Unix's corerun tries to parse a path out of argv[0], and blows up in std::string if no '/' is found.  This commit adds a check to make sure that there was a '/' found, and if there wasn't, uses the current directory instead.  argv[0] without a path often happens when some tool uses exec and provides a "beautified" name in argv[0].

### CODE REVIEW

**Comment by stephentoub** [comment]
Sure, will fix.

**Comment by stephentoub** [comment]
@mmitche, I think the OSX machines are unavailable; this PR has been stuck in CI since Friday.

**Comment by mmitche** [comment]
@stephentoub They got caught up in the building power maintenance over the weekend, up now.

**Comment by stephentoub** [comment]
@janvorli, could you re-review when you get a chance?

**Comment by janvorli** [comment]
LGTM, thank you for fixing it.

**Pull request merged**
