### PR TITLE
[ARM64/Linux] Fix 'array index xx is past the end of the array' error.

### PR DESCRIPTION
**Pull request by lemmaa**
This fixes ARM64 Linux compilation error

### CODE REVIEW

**Comment by lemmaa** [comment]
CC: @swaroop-sridhar, @ramarag

**Comment by swaroop-sridhar** [comment]
@first-hand test arm64 checked

**Comment by swaroop-sridhar** [comment]
@dotnet-bot test arm64 checked

**Comment by swaroop-sridhar** [comment]
@dotnet-bot test Windows_NT Arm64 checked

**Comment by rahku** [comment]
X30 is LR register. What is the reason for it being saved? We do not save that for arm32 as well. MachState is used during GCStackwalk when we need to update managed object references after they  have been relocated.

**Comment by lemmaa** [comment]
@rahku I got the history from PR ARM64: Fix LR update in a few stubs (#5013). @swaroop-sridhar Would you please explain in detail?

**Comment by swaroop-sridhar** [comment]
@lemmaa: I spoke to @rahku  a little while ago;  Updating the LR register should be unnecessary, since the register should never contain an object reference per convention. There was an issue wrt updating contextpointers corresponding to Lr register (previously nulled out). I'll look into it a bit more and reply.

**Comment by swaroop-sridhar** [comment]
The confusion here is caused by the way `MachState` structure is written:
The [`_pc` and `_sp` fields](https://github.com/dotnet/coreclr/blob/master/src/vm/arm64/gmscpu.h#L26-L27) actually refer to the caller's PC and SP values. 

We can see this from the fact that [`GetRetAddr()`](https://github.com/dotnet/coreclr/blob/master/src/vm/arm64/gmscpu.h#L31) returns `_pc` , and the fact that they are [captured](https://github.com/dotnet/coreclr/blob/master/src/vm/arm64/stubs.cpp#L390-L391) after the [VirtualUnwind](https://github.com/dotnet/coreclr/blob/master/src/vm/arm64/stubs.cpp#L322-L327)

The [`CaptureIp` and `CaptureSp`](https://github.com/dotnet/coreclr/blob/master/src/vm/arm64/gmscpu.h#L36-L37) fields in LazyMachState actually point to the `PC/SP` of the current frame.
 
The `_pc` / `_sp` fields of `MachState` should be renamed to `LR` and `CallerSP` instead. 
So, there's no requirement to store `LR` in `captureX19_X29` or change the size of the array.
That is, we should delete the references to `captureX19_X29[11]`.

**Comment by swaroop-sridhar** [comment]
Alternate fix based on my notes above is here https://github.com/dotnet/coreclr/pull/5666

**Comment by lemmaa** [comment]
Thanks @swaroop-sridhar.

**Pull request closed without merging**
