### PR TITLE
Add pipeline schedules to YAML file

### PR DESCRIPTION
**Pull request by BruceForstall**
Schedules can no longer be specified in the UI; they must be
specified in the YAML file.

Extremely minimal documentation is here: https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-153-update#use-cron-syntax-to-specify-schedules-in-a-yaml-file

### CODE REVIEW

**Comment by BruceForstall** [comment]
Here's a start, but I have the syntax wrong currently.

**Comment by BruceForstall** [comment]
Well, I'm not sure how to conditionalize the schedules (or if it's even possible?)

**Comment by BruceForstall** [comment]
@RussKeldorph

**Comment by RussKeldorph** [comment]
Sigh.  Please confirm they intended to roll this out before merging.

**Comment by BruceForstall** [comment]
This is getting implemented by splitting the YML files, e.g., https://github.com/dotnet/coreclr/pull/25325

**Pull request closed without merging**
