### PR TITLE
ARM64: Major Update for new tests to run using Smarty.exe

### PR DESCRIPTION
**Pull request by briansull**
Updated Tests.lst and preserved Categories tags
We can ask Smarty to run all of the Pro, Pri1 or Pri2 tests
By default we still only run the ones that were passing from the previous Tests.lst file

### CODE REVIEW

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64

**Comment by briansull** [comment]
@jashook PTAL
I don't see the arm64 tests job starting

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT arm64

**Comment by jashook** [comment]
@mmitche PTAL, looks like the tests did not start for Brian.

**Comment by mmitche** [comment]
Looks like it's because the private trigger has his gh alias spelled incorrectly :D

**Comment by kyulee1** [comment]
LGTM

**Pull request merged**
