### PR TITLE
The ftruncate tests eat up a lot of disk space, and build time -- disabl...

### PR DESCRIPTION
**Pull request by kangaroo**
...e them

### CODE REVIEW

**Comment by janvorli** [comment]
LGTM

**Comment by sergiy-k** [comment]
LGTM

**Comment by janvorli** [comment]
@kangaroo I have missed the fact that the HAVE_FTRUNCATE_LARGE_LENGTH_SUPPORT definition is now duplicated in the config.h.in. One at line 78 as
```c
#cmakedefine01 HAVE_FTRUNCATE_LARGE_LENGTH_SUPPORT
```
and the other at line 143 as
```c
#define HAVE_FTRUNCATE_LARGE_LENGTH_SUPPORT 1
```
So the Linux build generates a lot of warnings.

**Comment by kangaroo** [comment]
@janvorli whoops

PR: https://github.com/dotnet/coreclr/pull/289

**Pull request merged**
