### PR TITLE
arm64 test update

### PR DESCRIPTION
**Pull request by rahku**
@dotnet test Windows_NT arm64 checked 
@dotnet test Windows_NT arm64 release 
@dotnet test Windows_NT arm64 checked pri1r2r 
@dotnet test Windows_NT arm64 release pri1r2r

### CODE REVIEW

**Comment by rahku** [comment]
@dotnet test Windows_NT arm64 checked

**Comment by rahku** [comment]
@dotnet test Windows_NT arm64 checked pri1r2r

**Comment by rahku** [comment]
@dotnet test Windows_NT arm64 release pri1r2r

**Comment by rahku** [comment]
@dotnet test Windows_NT arm64 release

**Comment by kyulee1** [comment]
Your new tests.lst includes priority 0 only. You should've built it like:
```
build arm64 checked priority 1 toolset_dir <path>
```
Apology about misleading instructions before.

**Pull request closed without merging**
