### PR TITLE
[Arm64] Implement genZeroInitFltRegs for float

### LINKED ISSUE #17966: [arm64/RyuJit] NYI("Initialize floating-point register to zero");
It was found in our internal test runs, I have added an IL test for this issue: tests/src/JIT/Regression/JitBlue/DevDiv_605447/DevDiv_605447.il (#17759)

To repro crossgen this test with altjit_arm64 or on arm64 itself.

Once it fixed delete change `tests/arm64/Tests.lst` to enable the test.

### LINKED ISSUE #17968: [arm64/RyuJit] assert(!"Shouldn't see an integer typed GT_MOD node in ARM64");
It was found in our internal test runs, I have added an IL test for this issue: tests/src/JIT/Regression/JitBlue/DevDiv_590772/DevDiv_590772.il  (#17759)
To repro crossgen this test with altjit_arm64 or on arm64 itself.
Once it fixed delete change tests/arm64/Tests.lst to enable the test.

### PR DESCRIPTION
**Pull request by sdmaclea**
Fixes #17966

@dotnet/arm64-contrib @briansull @CarolEidt @sandreenko PTAL

### CODE REVIEW

**Review by BruceForstall — APPROVED** [review]

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT x64_arm64_altjit Checked r2r_jitstress1
@dotnet-bot test Windows_NT x64_arm64_altjit Checked r2r_jitstressregs1

**Comment by sandreenko** [comment]
Thank you,
but I do not understand how it fixes #17968. 
The problem there is `a umod b`, where `b == CNT_INT int 1` and morph thinks that lower will transform it into `a % b = a & (b - 1)`, but then Jit understand that `a == 0` and lower reject this optimization.

**Comment by sdmaclea** [comment]
>  I do not understand how it fixes #17968.

When I ran on Linix-arm64, I did not see the symptoms you described in #17968.  
I saw `NYI("Initialize floating-point register to zero");`
Test is passing on Linux-Arm64.

The symptom you describe is similar to #8648 #10111, but I didn't see it on #17968

**Comment by sdmaclea** [comment]
Before
```
corerun ~vmjenkins/workspace/Dotnet/test_coreclr/bin/tests/pr1/JIT/Regression/JitBlue/DevDiv_605447/DevDiv_605447/DevDiv_605447.exe 
Compiling    0 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 41, hsh=0xab04618a
Compiling    1 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 83, hsh=0xab04618a
Compiling    2 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 86, hsh=0xab04618a
Compiling    3 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 152, hsh=0xab04618a
Compiling    4 DevDiv_605447::Main, IL size = 33, hsh=0x6c343d6e
Compiling    5 DevDiv_605447::ILGEN_METHOD, IL size = 143, hsh=0x542f79cc

Assert failure(PID 35368 [0x00008a28], Thread: 35368 [0x8a28]): Assertion failed 'NYI: Initialize floating-point register to zero' in 'DevDiv_605447:ILGEN_METHOD(int,int,int,ushort,float):ushort' (IL size 143)

    File: /home/vmjenkins/workspace/Dotnet/build_coreclr/src/jit/codegencommon.cpp Line: 5828
    Image: /home/sdmaclea/coreoverlay/corerun
```
After 
```
corerun ~vmjenkins/workspace/Dotnet/test_coreclr/bin/tests/pr1/JIT/Regression/JitBlue/DevDiv_605447/DevDiv_605447/DevDiv_605447.exe 
Compiling    0 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 41, hsh=0xab04618a
Compiling    1 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 83, hsh=0xab04618a
Compiling    2 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 86, hsh=0xab04618a
Compiling    3 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 152, hsh=0xab04618a
Compiling    4 DevDiv_605447::Main, IL size = 33, hsh=0x6c343d6e
Compiling    5 DevDiv_605447::ILGEN_METHOD, IL size = 143, hsh=0x542f79cc
Compiling    6 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 80, hsh=0xab04618a
Compiling    7 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 52, hsh=0xab04618a
Compiling    8 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 77, hsh=0xab04618a
Compiling    9 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 52, hsh=0xab04618a
Compiling   10 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 77, hsh=0xab04618a
Compiling   11 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 81, hsh=0xab04618a
Compiling   12 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 26, hsh=0xab04618a
Compiling   13 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 193, hsh=0xab04618a
Compiling   14 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 104, hsh=0xab04618a
Compiling   15 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 206, hsh=0xab04618a
Compiling   16 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 32, hsh=0xab04618a
Compiling   17 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 165, hsh=0xab04618a
Compiling   18 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 114, hsh=0xab04618a
Compiling   19 System.Resources.ResourceReader::LoadString, IL size = 222, hsh=0xf2b0df71
```

**Comment by sdmaclea** [comment]
It is possible DevDiv_605447 was the incorrect test for #17968

**Comment by sdmaclea** [comment]
Deleted a few comments because I was citing the wrong tests.

I never saw the symptoms described in #17968, but rather saw #17966 symptoms for both tests.

With this fix both tests are passing on Linux-arm64 with this change...
```
corerun ~vmjenkins/workspace/Dotnet/test_coreclr/bin/tests/pr1/JIT/Regression/JitBlue/DevDiv_590772/DevDiv_590772/DevDiv_590772.exe
Compiling    0 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 41, hsh=0xab04618a
Compiling    1 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 83, hsh=0xab04618a
Compiling    2 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 86, hsh=0xab04618a
Compiling    3 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 152, hsh=0xab04618a
Compiling    4 DevDiv_590772::Main, IL size = 35, hsh=0x92b756ae
Compiling    5 DevDiv_590772::ILGEN_METHOD, IL size = 143, hsh=0xaaac120c
Compiling    6 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 80, hsh=0xab04618a
Compiling    7 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 52, hsh=0xab04618a
Compiling    8 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 77, hsh=0xab04618a
Compiling    9 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 52, hsh=0xab04618a
Compiling   10 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 77, hsh=0xab04618a
Compiling   11 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 81, hsh=0xab04618a
Compiling   12 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 26, hsh=0xab04618a
Compiling   13 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 193, hsh=0xab04618a
Compiling   14 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 104, hsh=0xab04618a
Compiling   15 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 206, hsh=0xab04618a
Compiling   16 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 32, hsh=0xab04618a
Compiling   17 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 165, hsh=0xab04618a
Compiling   18 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 114, hsh=0xab04618a
Compiling   19 System.Resources.ResourceReader::LoadString, IL size = 222, hsh=0xf2b0df71
[sdmaclea@rtpart-aw11-04h coreclr (master)]$ echo $?
100
```
```
corerun ~vmjenkins/workspace/Dotnet/test_coreclr/bin/tests/pr1/JIT/Regression/JitBlue/DevDiv_605447/DevDiv_605447/DevDiv_605447.exe 
Compiling    0 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 41, hsh=0xab04618a
Compiling    1 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 83, hsh=0xab04618a
Compiling    2 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 86, hsh=0xab04618a
Compiling    3 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 152, hsh=0xab04618a
Compiling    4 DevDiv_605447::Main, IL size = 33, hsh=0x6c343d6e
Compiling    5 DevDiv_605447::ILGEN_METHOD, IL size = 143, hsh=0x542f79cc
Compiling    6 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 80, hsh=0xab04618a
Compiling    7 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 52, hsh=0xab04618a
Compiling    8 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 77, hsh=0xab04618a
Compiling    9 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 52, hsh=0xab04618a
Compiling   10 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 77, hsh=0xab04618a
Compiling   11 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 81, hsh=0xab04618a
Compiling   12 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 26, hsh=0xab04618a
Compiling   13 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 193, hsh=0xab04618a
Compiling   14 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 104, hsh=0xab04618a
Compiling   15 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 206, hsh=0xab04618a
Compiling   16 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 32, hsh=0xab04618a
Compiling   17 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 165, hsh=0xab04618a
Compiling   18 DomainNeutralILStubClass::IL_STUB_PInvoke, IL size = 114, hsh=0xab04618a
Compiling   19 System.Resources.ResourceReader::LoadString, IL size = 222, hsh=0xf2b0df71
[sdmaclea@rtpart-aw11-04h coreclr (master)]$ echo $?
100
```

**Comment by sandreenko** [comment]
Hmm, looks like I added the wrong repro for #17968.
I will update and fix it soon.

Fix for #17966 looks good.

**Review by sandreenko — APPROVED** [review]

**Comment by sdmaclea** [comment]
> I will update and fix it soon.

Remove #17968 from top post, so that it does not close it.
I assume you will create a new test name, so I can leave the changes to the arm64 test.lst.

**Comment by BruceForstall** [comment]
@sandreenko Can you re-enable 605447 in issues.targets?
```
<!-- The following are ARM64_altjit crossgen failures. For x64_arm64_altjit buildArm==x64. -->

<ItemGroup Condition="'$(XunitTestBinBase)' != '' and '$(BuildArch)' == 'x64'">
...
    <ExcludeList Include="$(XunitTestBinBase)\JIT\Regression\JitBlue\DevDiv_605447\DevDiv_605447\DevDiv_605447.cmd">
        <Issue>17966</Issue>
    </ExcludeList>
...
</ItemGroup>
```

**Pull request merged**
