### PR TITLE
update order of locks so gcstress is unblocked

### PR DESCRIPTION
**Pull request by davmason**

### CODE REVIEW

**Comment by davmason** [comment]
@dotnet-bot test Windows_NT x86 Checked gcstress0xc_minopts_heapverify1

**Comment by nerdcorerising** [comment]
@dotnet-bot test Ubuntu x64 Checked CoreFX Tests

**Comment by davmason** [comment]
@dotnet-bot test Windows_NT x64 Debug CoreFX Tests

**Comment by davmason** [comment]
@dotnet-bot test Windows_NT x86 Checked gcstress0xc_minopts_heapverify1

**Comment by davmason** [comment]
@dotnet-bot test OSX10.12 x64 Debug CoreFX Tests

**Comment by davmason** [comment]
@dotnet-bot test OSX10.12 x64 Release CoreFX Tests

**Comment by AndyAyersMS** [comment]
GC stress obviously working again for x86 -- for the purposes of this PR you can ignore the point failures, though we should get to the bottom of the DevDiv_278372 failure.

@dotnet-bot test Windows_NT x64 Checked gcstress0xc
@dotnet-bot test Ubuntu x64 Checked gcstress0xc
@dotnet-bot test Windows_NT arm64 Cross Checked gcstress0xc Build and Test

**Comment by AndyAyersMS** [comment]
I think we have enough evidence that gcstress is working to merge this. We can sort through isolated gcstress failures via our normal process.

**Pull request merged**
