### PR TITLE
Restore the package version to 1.0.2 for the CoreCLR package

### LINKED ISSUE #5213: Reset CoreCLR nuget package version to be 1.0.2 (instead of 1.0.3).
This was introduced in https://github.com/dotnet/coreclr/commit/3fd0bcbb2717fe5944a808b8a2324807ad406e18#diff-56e260e2165edb286c148b56e11191fe.

Please fix all the individual Nuget package versions and the outer container package version.

@AlexGhiondea  PTAL

CC @ericstj

### PR DESCRIPTION
**Pull request by AlexGhiondea**
This will ensure the package version is consistent with our other packages.

Fixes #5213

### CODE REVIEW

**Comment by gkhanna79** [comment]
LGTM - thanks for getting this done.

**Comment by kyulee1** [comment]
Can you please update the same thing for ilasm/ildasm packages?

**Comment by gkhanna79** [comment]
@AlexGhiondea ILDasm/ILAsm have a reference to CoreCLR package and that reference needs to be updated.

@kyulee1 Do you want to keep ILAsm/ILDasm package versions (and not the CoreCLR version they reference - Alex will fix that) 1.0.3?

**Comment by AlexGhiondea** [comment]
@kyulee1 I have updated both the package versions and the dependencies to 1.0.2.

**Comment by kyulee1** [comment]
Thanks! LGTM

**Comment by AlexGhiondea** [comment]
@dotnet-bot please test

**Comment by AlexGhiondea** [comment]
@dotnet-bot  please test Windows_NT x86 legacy_backend Checked Build and Test

**Comment by gkhanna79** [comment]
@ellismg @sergiy-k http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/checked_ubuntu_tst_prtest/2085/ is failing due to System.Runtime.InteropServices issue. Do you know if a fix for this is inplace?

**Comment by ellismg** [comment]
>  you know if a fix for this is inplace?

It has not been merged yet, I have a PR out to test things.

**Comment by weshaggard** [comment]
LGTM.

I'm assuming we haven't publish these packages with the 1.0.3 version number yet, correct? If we have then we will likely run into some trouble.

**Comment by gkhanna79** [comment]
@weshaggard The open build has only recently (2 days ago) started to publish these (1.0.3) packages to test feed. There are not on the real feed.

We should merge the change once CI is green (Ubuntu failure is unrelated to the change).

**Comment by AlexGhiondea** [comment]
@gkhanna79 @ellismg both failures were caused by the interop issue. 

I will merge this in shortly unless I hear otherwise.

**Comment by gkhanna79** [comment]
@AlexGhiondea Is there anything outstanding prior to merging in? If not, lets get this in for both master and release branches for tonight.

**Comment by AlexGhiondea** [comment]
@gkhanna79 porting this to release requires #5214 to be merged.

**Pull request merged**
