### PR TITLE
Add chmod +x to individual test scripts in runtest.sh

### PR DESCRIPTION
**Pull request by adityamandaleeka**
Do a `chmod +x` in runtest.sh before trying to run each test script. This hasn't been needed when running tests locally after copying the scripts (and binaries) from a mounted Windows share, because doing so automatically sets the executable bit on the scripts. However, we need it now because these scripts will be run as part of the CI process, which doesn't involve directly copying files from Windows shares.

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
@dotnet-bot test linux

**Comment by mmitche** [comment]
LGTM assuming it passes.

**Comment by mmitche** [comment]
@dotnet-bot show commands

**Comment by mmitche** [comment]
@dotnet-bot show commands

**Comment by mmitche** [comment]
@dotnet-bot show commands

**Comment by mmitche** [comment]
I'm a little unsure of what happened there, not seen that before.  git couldn't determine that the commit hash passed from the root job was an actual commit;  I am wondering whether this is set up improperly.  Let's see if it happens again.

**Comment by mmitche** [comment]
@dotnet-bot test linux

**Comment by mmitche** [comment]
@dotnet-bot test linux

**Comment by adityamandaleeka** [comment]
Fixing the permissions got the scripts running on the CI machine, but there was a problem where the corefx binaries weren't being copied to the overlay directory. Turns out there's a `find` command in the script that excludes anything with 'test' in its path (in order to avoid copying corefx test binaries over, I guess). This is fine, except for the fact that the CI job (and therefore the directory where all this stuff is on the CI machine) has 'test' in its name :smile:

I just pushed another commit that changes the `find` command so it only checks the relative path from `$coreFxBinDir`.

**Comment by adityamandaleeka** [comment]
@dotnet-bot test linux

**Comment by adityamandaleeka** [comment]
FYI: We should expect some failing tests because it looks like a recent change (I think https://github.com/dotnet/coreclr/commit/f0e0ebc0624e690dcebd0f3d31b36daf7750c295) changed where the tests end up but didn't update the exclusion files for tests that fail/aren't supported outside Windows. It also breaks the assumptions in runtest.sh about where the native components for tests should be.

**Comment by adityamandaleeka** [comment]
@dotnet-bot test linux

**Comment by ellismg** [comment]
FWIW, I find this whole find business incredibly brittle.  I realize you are not making things worse, but I think we need to come up with a better long term version.  It would be helpful to understand exactly what you need from CoreFX.  E.G. does this test run need to use bleeding edge copies of all the CoreFX DLLs or do you just want LKG copies?  If it's the latter case, we should work on pulling down what you need from myget/nuget.

**Comment by mmitche** [comment]
@ellismg If that's possible today, that would be great and we should implement it.

**Comment by mmitche** [comment]
@adityamandaleeka What was the second test Linux for?

**Comment by adityamandaleeka** [comment]
@ellismg I agree, and if the tests under CoreCLR are only testing runtime stuff and aren't affected by framework changes, we shouldn't need bleeding edge CoreFX binaries.

@mmitche The first 'test Linux' seemed to have the same problem that we saw previously where it couldn't get the git commit.

**Comment by mmitche** [comment]
Thanks for the info.  I wanted to go check out what was going on there.  I put some logging in.

**Pull request merged**
