### PR TITLE
Don't change PUTARG_REG spill type on arm64

### LINKED ISSUE #18746: regressions in arm64_altjit r2r jobs: temp != nullptr
Some tests are failing after #18346, for example [b393481](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_arm64_altjit_checked_windows_nt_r2r_prtest/12/testReport/junit/JIT_Regression/_CLR_x86_JIT_dev10_b393481_b393481_b393481_/_CLR_x86_JIT_dev10_b393481_b393481_b393481_cmd/) fails with `Assertion failed 'temp != nullptr' in 'TestAnonymousTypes.Program:Main(ref):int' (IL size 534)\r\n\r\n File: d:\\j\\workspace\\x64_arm64_alt---840786b4\\src\\jit\\regset.cpp Line: 676`.

### PR DESCRIPTION
**Pull request by CarolEidt**
Fix #18746

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT x64_arm64_altjit Checked r2r

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT x64_arm64_altjit Checked r2r

**Comment by CarolEidt** [comment]
@jashook @dotnet/jit-contrib PTAL
Hopefully the CI will run the r2r tests eventually to validate

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT x64_arm64_altjit Checked r2r

**Comment by jashook** [comment]
Thank you for catching this!

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT x64_arm64_altjit Checked r2r

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Pull request merged**
