### PR TITLE
Enable running of the full Pri0 and Pri1 set of tests

### PR DESCRIPTION
**Pull request by briansull**
Updated with EXPECTED_PASS and EXPECT_FAIL

For the arm64 check build we now have
8069 tests EXPECTED_PASS
301 tests EXPECTED_FAIL
96.4% passing

Additionally another 104 tests are currently disabled for these two reasons:
63 tests in NATIVE_INTEROP
41 tests in UNSTABLE 

and it should no longer be necessary to set the Gen0 size using  COMPLUS_GCgen0size

### CODE REVIEW

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64

**Comment by jashook** [comment]
Are these test failures the regressions being addressed in #3742?

**Comment by kyulee1** [comment]
@jashook I think so.

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64

**Comment by kyulee1** [comment]
This says it fails but not list of failing tests.

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/arm64_cross_release_windows_nt_prtest/10/consoleText

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64

**Comment by jashook** [comment]
That is pretty strange looking into it now

**Comment by jashook** [comment]
@kyulee1 one of the machines failed to copy the lst file. This should not happen again.

**Comment by kyulee1** [comment]
Thanks for the investigation. It might be good to display each step, if possible, to reason about such case. And also smarty produces a nice summary html file as a result of run, and I wonder if we can capture or store it somewhere at minimum.

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT arm64

**Comment by jashook** [comment]
@briansull please wait to merge this, we are hitting the timeout of 2 hours for the jobs. This pr is adding to that problem. I am trying to up the timeout and disable debug testing in PR #3786. Once that merges we can restart the tests here.

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT arm64

**Pull request merged**
