### PR TITLE
Fix AllocationTick_V3 depending on _V2 to be enabled

### PR DESCRIPTION
**Pull request by tmds**

### CODE REVIEW

**Comment by tmds** [comment]
> thanks for fixing this!

No problem. @Maoni0 are you merging this?

**Comment by Maoni0** [comment]
@tmds I haven't merged 'cause there is a failure - "Windows_NT x86 full_opt ryujit CoreCLR Perf Tests Correctness". have you had a chance to take a look? probably just something not related but would be good to be sure.

**Comment by tmds** [comment]
It doesn't look related. Going to restart it and see what happens.

**Comment by tmds** [comment]
@dotnet-bot Test Windows_NT x86 full_opt ryujit CoreCLR Perf Tests Correctness please

**Pull request merged**
