### PR TITLE
Fix JitBench

### PR DESCRIPTION
**Pull request by kouvel**
Fixes https://github.com/dotnet/coreclr/issues/19569
- I believe the issue was that JitBench (which was a netstandard1.6 project) was running against a netcoreapp3.0 layout with corerun (layout built using build + recent packages by runtests.cmd), and XmlDocument is in a different place now
- Copied the unofficial project and replaced the official one
- Switched to netcoreapp3.0 along with other miscellaneous fixes to get it working
- I haven't figured out yet how to get one project that builds with the test build and works with dotnet. TargetFramework would have to be different anyway if running with dotnet runtime 2.1. So the unofficial project is still there for use with dotnet.

### CODE REVIEW

**Comment by kouvel** [comment]
@dotnet-bot help

**Comment by kouvel** [comment]
@dotnet-bot test Windows_NT x64 perf scenarios
@dotnet-bot test Windows_NT x64 min_opts perf scenarios
@dotnet-bot test Windows_NT x64 perf scenarios
@dotnet-bot test Windows_NT x86 perf scenarios
@dotnet-bot test Windows_NT x86 min_opts perf scenarios
@dotnet-bot test Windows_NT x86 perf scenarios

**Comment by jorive** [comment]
Why are we replacing the `csproj`? Isn't the problem a missing package dependency not being copied to the output folder?

**Comment by kouvel** [comment]
I believe the problem is that we're trying something funky - to run a netstandard1.6 project on top of a netcoreapp3.0 layout. Sooner or later, that would cause issues. The only reason I replaced the .csproj is because I saw a lot of things in there that weren't in most test projects. I tried to keep it similar to other test projects that run against netcoreapp3.0. The project in the `unofficial_dotnet` was a good starting point.

**Comment by jorive** [comment]
I agree, the test project on the coreclr repo are not the cleanest, but here you can find more benchmark projects: https://github.com/dotnet/coreclr/blob/master/tests/src/JIT/Performance/CodeQuality/.

It looks like the project you need to update is this one: https://github.com/dotnet/coreclr/blob/master/tests/src/performance/performance.csproj

**Comment by kouvel** [comment]
I had removed the `JitBench.csproj` dependency on `performance.csproj`. Other projects using assets from `performance.csproj` should continue to work as before, though it would be nice to update them at some point. For JitBench I'd like to eventually figure out a way of being able to use one project with dotnet and in the official build/test system. Not sure how to do that at the moment but I'd like to not have that dependency if possible.

**Comment by kouvel** [comment]
@dotnet-bot test Windows_NT x64 Release CoreFX Tests

**Pull request merged**
