### PR TITLE
Block Ops Refactor

### PR DESCRIPTION
**Pull request by CarolEidt**
Refactor the legacy code dealing with block ops to minimize diffs when they are replaced with assignments.
Also a couple of comment edits and a small cleanup in rationalizer.

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

**Comment by briansull** [comment]
Looks Good

**Comment by pgavlin** [comment]
LGTM as well. The Ubuntu failure looks like an infrastructure problem (cc @mmitche).

**Comment by CarolEidt** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Comment by mmitche** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Comment by CarolEidt** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Pull request merged**
