### PR TITLE
Test case for store (non-GC) value type to static field

### PR DESCRIPTION
**Pull request by kyulee1**
It adds a test case that stores non-GC value type to static field.

### CODE REVIEW

**Comment by kyulee1** [comment]
@libengu PTAL

**Comment by libengu** [comment]
Copyright missing. You need to re-format the file in Visual Studio wit Ctrl-K D. Also it would be good to have some descriptions in the test case, like comments in a factual way. Code itself looks OK.

**Comment by kyulee1** [comment]
Added copyright and did formatting/commenting.

**Comment by AndyAyersMS** [comment]
@kyulee1 We also want to add this to the project file so it gets built, right? Anything else we need along these lines, @libengu ?

**Comment by libengu** [comment]
No. You don't need to. The project file is written in a way that every .cs in the directory will be automatically picked up.

**Comment by AndyAyersMS** [comment]
Ah, good. Thanks.

**Comment by kyulee1** [comment]
Appears the build failure is unrelated. How to do test again?

**Comment by libengu** [comment]
Looks like failure is from Linux side. @mmitche Do you have any idea what is going on?

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by libengu** [comment]
Merge it on behalf of @kyulee1 as his account has some issue with this Repo.

**Pull request merged**
