### PR TITLE
Widen basic block flag field to 64 bits

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Flag field is currently full, and I need at least one more bit to identify
the start of a cloned finally.

Widen to 64 bits and update a few uses. Also removed an unused copy.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib 

No diffs on x64 windows CoreCLR+FX

**Comment by AndyAyersMS** [comment]
Pushed an update for formatting/gotos.

**Comment by mikedn** [comment]
Perhaps we should have a `typedef unsigned __int64 BBFlags;`? Though I don't think the type will be changed again anytime soon...

**Comment by AndyAyersMS** [comment]
I find typedefs of basic types to be more confusing than helpful -- I suppose it makes search and replace easier, but you usually end up having to know what the real type is anyways when you do anything other than make copies. So will leave this as is...

**Pull request merged**
