### PR TITLE
Optimize Join, Concat taking an IEnumerable<string> for ICollections

### PR DESCRIPTION
**Pull request by jamesqo**
As of right now, `Join` and `Concat` which take an `IEnumerable<string>` use a StringBuilder to append all the items of the enumerable. This is quite slow, since even for length 1 collections where we just return the first string we are incurring the cost of 5 interface calls (`GetEnumerator`, `MoveNext`, `Current`, `MoveNext`, `Dispose`) as well as a heap allocation for the enumerator. Larger collections are even more costly, since in addition to those we are doing 3 thread-static field accesses to `StringBuilderCache`, in addition to 2 interface calls (`MoveNext`, `Current`) and calls to `StringBuilder.Append` and `Buffer.Memmove` per iteration.

I have changed it to try and detect first if the enumerable is an `ICollection`, and allocate an intermediary string array and `CopyTo` that. Then, we just call `Join(string, string[])` or `Concat(string[])`. This means we will only ever invoke 2 virtual calls (`Count` and `CopyTo`), and we don't have to copy the chars into an intermediary buffer.

The downside of this approach is we are now making 3 passes over the strings (1 for `CopyTo`, 1 to calculate the result's length, 1 to copy them into the result string) whereas before we were only making 1. Additionally, we are making more allocations than we were previously; assuming the StringBuilder was cached and the result string fit into the buffer, the only allocation we were making before was the enumerator, whereas now we are allocating a new `string[]` of length N.

## Performance results

In spite of these additional allocations/passes, the new implementation is consistently faster than the old one. You can see the perf test/results I have here: https://gist.github.com/jamesqo/7f1509d899396b0c724d2b73e402e19b

As you can see there are increased gen0 allocations for collections of length 3 and above, however all of the times are consistently faster.

/cc @jkotas, @bbowyersmyth, @benaadams 

edit: Also cc'ing @justinvp

### CODE REVIEW

**Comment by jamesqo** [comment]
Also ccing @justinvp

**Comment by jkotas** [comment]
These Join methods that take IEnumerable are slow convenience methods. I do dot think it is worth the extra code to optimize them like this. Bigger code, larger test matrix, some cases faster, some cases slower - hard to tell whether it is a net win.

**Comment by jamesqo** [comment]
> Bigger code, larger test matrix, some cases faster, some cases slower - hard to tell whether it is a net win.

*All* of the cases are faster-- the test I wrote was the most favorable scenario for the StringBuilderCache, since the strings were small enough that the buffer was always kept cached. Also, the gains here are not necessarily limited to this method-- for example, there could be a StringBuilder that we take from the cache, and after appending a few strings it's no longer allowed into the cache. So then if someone calls another method that uses `StringBuilderCache.Acquire` it will have to allocate a new StringBuilder, since nothing's available in the cache.

**Comment by stephentoub** [comment]
> All of the cases are faster ... they increase perf in all scenarios

How is it faster for the (common) case where the input is not a collection (e.g. the result of a LINQ query)?  In that case you're purely doing extra work over what's already there without any benefit.

**Comment by jamesqo** [comment]
@stephentoub I was trying to say it would always be faster if the enumerable implemented ICollection and went down the new route.

I made a new benchmark calling `Select(s => s)` on the List so it calls the old code: https://gist.github.com/jamesqo/dacc0f493a3ed15cf8bf80dfea029b6a

The difference stops being measurable after 0/1-length 'lazy' enumerables.

**Comment by stephentoub** [comment]
"The difference stops being measureable after..." suggests that at one point the difference was measurable, which highlights that there is a case where this hurts.

Plus, even the data you shared shows that there are performance downsides.  After 2 items, all of the "new" results show more memory allocations than the corresponding "old" results, e.g. for 14 items, the "new" results show almost 50% more gen0 GCs than the "old" results.

**Comment by redknightlois** [comment]
@jamesqo if I read that properly we are talking about 20% more collections. Can you run this under the BenchmarkDotNet memory allocation profile run? Because in the usual tradeoff 20% more memory allocated is worse than higher CPU cost.

**Comment by jamesqo** [comment]
@stephentoub 

> "The difference stops being measureable after..." suggests that at one point the difference was measurable, which highlights that there is a case where this hurts.

Yes, by 20% for 0-length lazy enumerables, and < 10% for 1-length lazy enumerables. I am assuming those will not be very common inputs to `Join` or `Concat`, at least compared to any class that implements ICollection. So therefore these changes should benefit much more than they hurt.

> Plus, even the data you shared shows that there are performance downsides. After 2 items, all of the "new" results show more memory allocations than the corresponding "old" results

Yes, and my version is still consistently faster (by 1.2 seconds when it comes to 14 items).

@redknightlois 

> Because in the usual tradeoff 20% more memory allocated is worse than higher CPU cost.

Can you explain why? Regardless of which is worse, the timings are consistently faster. Also, all of these are gen0 allocations so AFAICS they should be very cheap to collect.

**Comment by stephentoub** [comment]
> Yes, and my version is still consistently faster

Allocations  can have a global impact. That's why we pay attention to them. They may have little effect on your single-threaded microbenchmark's throughout, but a much greater impact on a real-world, multi-threaded server scenario.

**Comment by stephentoub** [comment]
> I am assuming those will not be very common inputs

Based on what? What reference set of applications and code is that based on?

**Comment by jamesqo** [comment]
> Allocations can have a global impact. That's why we pay attention to them. They may have little effect on your single-threaded microbenchmark's throughout, but a much greater impact on a real-world, multi-threaded server scenario.

OK, I see. Thanks for clarifying.

**Pull request closed without merging**
