### PR TITLE
Removed Check Invalid Path Chars

### PR DESCRIPTION
**Pull request by Anipik**
issue - https://github.com/dotnet/corefx/issues/25450
corefx pr - https://github.com/dotnet/corefx/pull/25458

### CODE REVIEW

**Comment by jkotas** [comment]
@Anipik You have mixed this up with your other PR. The way to fix it is to `git rebase -i master`, delete the commits that belong to the other PR, and then `git push -f origin invalidpath`. (This assumes that you have setup origin to point to your github fork.)

**Comment by JeremyKuhne** [comment]
This is generally correct (outside of both PRs being in it).  You'll need to temporarily disable all tests that check invalid chars (should mostly be in System.IO.FileSystem) so the updated CoreCLR can be consumed, then fix the tests after that happens.

**Comment by danmosemsft** [comment]
@Anipik you left this one:
```
        internal static int FindFileNameIndex(string path)
        {
            Debug.Assert(path != null);
            CheckInvalidPathChars(path);
```

**Comment by danmosemsft** [comment]
>You'll need to temporarily disable all tests that check invalid chars (should mostly be in System.IO.FileSystem) so the updated CoreCLR can be consumed, then fix the tests after that happens.

Alternatively (what I would do) throw up a PR that fixes the tests, leave it open, then when the CoreCLR update job comes along and fails, you or someone can just rebase your PR branch onto that brnach to fix them.

**Comment by Anipik** [comment]
@dotnet-bot  help

**Comment by Anipik** [comment]
@danmosemsft by tests you mean tests in coreclr or corefx ? I am not able to find any tests using this CheckInvalidPathChars api

**Comment by danmosemsft** [comment]
@anipik could be either...just see what folks if anything.

**Comment by Anipik** [comment]
@dotnet-bot test CentOS7.1 x64 Checked Innerloop Build and Test

**Comment by danmosemsft** [comment]
Looks like no CoreCLR tests fail, at least. When this gets mirrored into CoreFX, the mirror job may hit test failures, you can then set up a remote to that branch and push up the necessary fixes. 

Exactly like I did here for a different change: https://github.com/dotnet/corefx/pull/25514

**Comment by JeremyKuhne** [comment]
@dotnet-bot test CentOS7.1 x64 Checked Innerloop Build and Test

```
11:23:51                Unhandled Exception: System.TypeLoadException: Could not load type 'System.MemoryExtensions' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
11:23:51                   at Span.SpanBench.TestSpanAsBytes[T](T[] array, Int32 iterationCount, Boolean untrue)
11:23:51                   at Span.SpanBench.Invoke(Action`1 innerLoop, String nameFormat, Object[] nameArgs)
11:23:51                   at Span.SpanBench.Main(String[] args)
11:23:51                ./SpanBench.sh: line 243: 49251 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
```

**Comment by Anipik** [comment]
@JeremyKuhne is this failure caused by removing "Check Invalid Path Chars "api. If not can we merge this ?

**Comment by danmosemsft** [comment]
@Anipik ify ou look in the log you can see the failure:
```
16:06:16 GDB was not found. Unable to print core file.
16:06:16 FAILED   - JIT/Performance/CodeQuality/Span/SpanBench/SpanBench.sh
16:06:16                BEGIN EXECUTION
16:06:16                /mnt/resource/j/workspace/dotnet_coreclr/master/checked_centos7.1_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun SpanBench.exe
16:06:16                TestSpanClear<Byte>(100): 0.5895ms
16:06:16                TestSpanClear<String>(100): 0.0077ms
16:06:16                TestArrayClear<Byte>(100): 0.0079ms
16:06:16                TestArrayClear<String>(100): 0.0084ms
16:06:16                
16:06:16                Unhandled Exception: System.TypeLoadException: Could not load type 'System.MemoryExtensions' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
16:06:16                   at Span.SpanBench.TestSpanAsBytes[T](T[] array, Int32 iterationCount, Boolean untrue)
16:06:16                   at Span.SpanBench.Invoke(Action`1 innerLoop, String nameFormat, Object[] nameArgs)
16:06:16                   at Span.SpanBench.Main(String[] args)
16:06:16                ./SpanBench.sh: line 243: 34878 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
16:06:16                Expected: 100
16:06:16                Actual: 134
16:06:16                END EXECUTION - FAILED
```
You did not cause this so you can ignore it. You just need @JeremyKuhne signoff.

**Comment by Anipik** [comment]
Yah i saw that ...iwas just confirming :)

**Comment by Anipik** [comment]
@JeremyKuhne can you take a look whether its ready to merge or not ?

**Pull request merged**
