### PR TITLE
CoreCLR tests on Linux

### PR DESCRIPTION
**Pull request by adityamandaleeka**
This change gives us the ability to easily run the existing CoreCLR tests on Linux.
 
What's inside:
* Changes necessary to enable building the native test components on Linux. This is done only when passing a new argument to the existing build.sh script, so existing scenarios are not affected by this.
* The runner for the tests is changed from mono to corerun.
* Changes to the bash script generation logic to deal with problems such as tests with multiple arguments, and tests with pre- or post-commands written in batch syntax.
* A new script (runtests.sh) to easily run tests on Linux (either all tests or only those specified in a specified text file).

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
@sergiy-k @kouvel @mmitche 

Please take a look.

**Comment by sergiy-k** [comment]
LGTM

**Comment by kouvel** [comment]
LGTM

**Comment by AndyAyersMS** [comment]
Is this work in progress? I don't see any tests getting built.

**Comment by mmitche** [comment]
this is still WIP for the CI side

**Comment by kouvel** [comment]
The tests will still need to be built on Windows. Other than that, there are currently some more manual steps involved to run the tests, I'm working on that.

**Pull request merged**
