### PR TITLE
Bulk port of TypeSystem test cases

### PR DESCRIPTION
**Pull request by fadimounir**
This port increases the number of TypeSystem test cases in the Loader\ClassLoader directory to 535 tests (from 50).

Tests are typically simple helloworld style tests that cover various parts of the TypeSystem.

@gkhanna79, @ramarag, please review this port.

### CODE REVIEW

**Comment by ramarag** [comment]
@fadimounir : was it a conscious decision to port all of these tests as pri 0?

**Comment by fadimounir** [comment]
@ramarag  Yes, it was a conscious decision :). These tests are super quick to run. There are some longer running tests that I ported as P1

**Comment by ramarag** [comment]
LGTM

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Pull request merged**
