### PR TITLE
Fix Register selection refactor bugs

### LINKED ISSUE #14617: [RyuJIT/arm32] Assertion failed 'tgtReg != tmpReg'
This seems like a recent regression.

```
Assert failure(PID 24376 [0x00005f38], Thread: 27324 [0x6abc]): Assertion failed 'tgtReg != tmpReg' in 'classarr:gaussj(ref,int,ref,int)' (IL size 763)

    File: e:\gh\coreclr3\src\jit\codegenarmarch.cpp Line: 1410
    Image: E:\gh\coreclr3\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
```

Tests:
```
JIT\Methodical\MDArray\GaussJordan\jaggedarr_cs_ro\jaggedarr_cs_ro.cmd
JIT\Methodical\MDArray\InnerProd\intarr_cs_ro\intarr_cs_ro.cmd
JIT\Performance\CodeQuality\Bytemark\Bytemark\Bytemark.cmd
JIT\Methodical\MDArray\GaussJordan\plainarr_cs_ro\plainarr_cs_ro.cmd
JIT\Methodical\MDArray\InnerProd\intarr_cs_do\intarr_cs_do.cmd
JIT\Methodical\MDArray\GaussJordan\structarr_cs_ro\structarr_cs_ro.cmd
JIT\Methodical\MDArray\GaussJordan\classarr_cs_do\classarr_cs_do.cmd
JIT\Methodical\MDArray\GaussJordan\plainarr_cs_do\plainarr_cs_do.cmd
JIT\Methodical\MDArray\GaussJordan\jaggedarr_cs_do\jaggedarr_cs_do.cmd
JIT\Methodical\MDArray\GaussJordan\structarr_cs_do\structarr_cs_do.cmd
JIT\Methodical\MDArray\GaussJordan\classarr_cs_ro\classarr_cs_ro.cmd
```

### LINKED ISSUE #14618: [RyuJIT/arm32] Assertion failed 'recentAssignedRefWeight == farthestRefPosWeight'
This is a recent regression.

```
Assert failure(PID 23576 [0x00005c18], Thread: 17092 [0x42c4]): Assertion failed 'recentAssignedRefWeight == farthestRefPosWeight' in 'Benchstone.BenchF.Lorenz:Bench():bool' (IL size 613)

    File: e:\gh\coreclr3\src\jit\lsra.cpp Line: 6400
    Image: E:\gh\coreclr3\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
```

Test:
```
JIT\Performance\CodeQuality\BenchF\Lorenz\Lorenz\Lorenz.cmd
```

### PR DESCRIPTION
**Pull request by CarolEidt**
Fix #14617
Fix #14618

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT x86_arm_altjit Checked

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs0x80
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs1
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs4
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs8

**Comment by CarolEidt** [comment]
Windows_NT x86_arm_altjit Checked build and test

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT x86_arm_altjit Checked Build and Test

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

**Review by BruceForstall — APPROVED** [review]

**Comment by CarolEidt** [comment]
@dotnet-bot tesWindows_NT x64 Release Priority 1 Build and Test

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test

**Pull request merged**
