### PR TITLE
Move DebugProvider.Windows to shared CoreLib.

### PR DESCRIPTION
**Pull request by filipnavara**

### CODE REVIEW

**Comment by filipnavara** [comment]
The CoreRT version seems to have diverged a little. While CoreCLR uses `Interop.Kernel32.OutputDebugString` (kernel32.dll), CoreRT uses `Interop.mincore.OutputDebugString` (api-ms-win-core-debug-l1-1-0.dll). I am not sure which one is preferred and if it should be unified at all.

**Comment by danmosemsft** [comment]
In CoreFX we do not use the type forwarder dll's because they don't exist downlevel. For a while we used them. In this case my guess is that kernel32 exports OutputDebugString even on "mincore" (?) so we should use that.

**Comment by filipnavara** [comment]
That makes sense. I was quite surprised when I noticed that CoreRT uses those since I expected it to target the same downlevel platforms (ie. Windows 7+).

**Comment by filipnavara** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test (GetFileSize, SetFilePointer failed tests)

**Comment by filipnavara** [comment]
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test
@dotnet-bot test CentOS7.1 x64 Debug Innerloop Build

**Comment by filipnavara** [comment]
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test (Jit - TieredCompilation=0)

**Comment by jkotas** [comment]
> I am not sure which one is preferred and if it should be unified at all.

`Kernel32` is the right one. `mincore` in CoreRT are left overs that have not been cleaned up yet.

**Comment by jkotas** [comment]
@MichalStrehovsky Do you expect issues with taking this change to CoreRT/ProjectN?

**Comment by jkotas** [comment]
Thanks!

**Pull request merged**
