### PR TITLE
Initial bringup of new set of ported GC tests.

### PR DESCRIPTION
**Pull request by swgillespie**
This PR contains approximately 150 new GC tests ported from the Desktop CLR, all testing various aspects of the garbage collector, `System.GC` `GCHandle`, and other related core classes. Not all of these tests are passing - I added a number of tests to the exclusion list and opened issues #3391 and #3392 to track the failing issues. This is also not all of the tests - I will be porting more tests piece-by-piece in the near future.

This PR is not quite ready to merge - I have tested all of these on Windows but have not yet run these new tests through the CI gauntlet to see how they do on other platforms. Currently, all of these tests are set to Priority 0 for testing purposes, but I am not sure if that's the correct priority for these.

These tests add about 7-10 minutes of running time on a Debug test run on Windows, so it is not a hefty penalty.

### CODE REVIEW

**Comment by swgillespie** [comment]
@dotnet-bot retest Windows_NT x86 Debug Build please

**Comment by pgavlin** [comment]
cc @swaroop-sridhar

**Comment by swgillespie** [comment]
I'm going to rebase and try this again once #3405 lands (seems like it'll be soon), since I think that it might resolve the package restore problems that I'm having in the CI.

**Comment by swgillespie** [comment]
@dotnet-bot test this please

**Comment by swgillespie** [comment]
Couple tests failing:

OOM killer (OSX):
```
17:50:45 FAILED   - GC/Coverage/smalloom/smalloom.sh
17:50:45                BEGIN EXECUTION
17:50:45                /Users/dotnet-bot/j/workspace/dotnet_coreclr/checked_osx_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun smalloom.exe
17:50:45                ./smalloom.sh: line 58: 49554 Killed: 9               $_DebuggerFullPath "$CORE_ROOT/corerun" smalloom.exe $CLRTestExecutionArguments $Host_Args
17:50:45                Expected: 100
17:50:45                Actual: 137
17:50:45                END EXECUTION - FAILED
```

Loading `Thread.Abort` through reflection:
```
17:50:45 FAILED   - GC/Features/Finalizer/finalizeother/finalizestop/finalizestop.sh
17:50:45                BEGIN EXECUTION
17:50:45                /Users/dotnet-bot/j/workspace/dotnet_coreclr/checked_osx_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun finalizestop.exe
17:50:45                In Finalize() of Dummy
17:50:45                
17:50:45                Unhandled Exception: System.Exception: Failed to get Thread.Abort method
17:50:45                   at Test.Dummy.ThreadAbort(Thread thread)
17:50:45                   at Test.Dummy.Finalize()
17:50:45                ./finalizestop.sh: line 58: 49764 Abort trap: 6           $_DebuggerFullPath "$CORE_ROOT/corerun" finalizestop.exe $CLRTestExecutionArguments $Host_Args
17:50:45                Expected: 100
17:50:45                Actual: 134
17:50:45                END EXECUTION - FAILED
```

Will address these.

**Comment by swgillespie** [comment]
:tada: 

PTAL @sergiy-k , @wtgodbe - any thoughts on whether these tests should be pri1/pri0?

**Comment by wtgodbe** [comment]
I would think more GC test coverage is always a good thing, so my vote goes to Pri 0, but I'm not digging my heels in on that.

**Comment by swgillespie** [comment]
Sounds good. Just rebased against master to fix a merge conflict, if the CI is green I'll merge.

**Pull request merged**
