### PR TITLE
[Back Port] of PR #21771 Issue #21461 Added opt-out of runtime polling

### PR DESCRIPTION
**Pull request by jorive**
#### Description
In V2.2 to support starting and stopping of EventPipe profiling on already started processes, the runtime wakes up every 5 seconds to check for profiling commands.    V2.1 did not have this behavior.  

For the vast majority of use cases, this polling is not an issue, as it is on its own thread and does very little (check for the existence of a file) each time.   

However it is possible that if users have 
    1. A large number of processes (e.g. hundreds or more) and 
    2. Expect that these processes will stay asleep for long periods (minutes to hours).  

Then this polling could have a noticeable negative effect on their performance (since waking up the process requires things to be paged back in).   

To insure that this polling does not block adoption of V2.2 it is prudent to have the ability to opt-out.   

This change address #21461 by:
- Increasing the polling interval to 20 seconds (thus making it less likely to even have impact)
- Add an option to opt-out from polling of EventPipe commands.   (Setting COMPLUS_EventPipeEnabled=0 will stop polling).  

#### Customer Impact

Most customers are not affected, but some high profile internal teams such as Bing, AzureWebSites and AzureFunctions may see an impact (they are still on 2.1 so have not run into the issue one way or the other).    We have contacted these teams, and while it is not clear how much they would be affected, having the opt-out is good 'insurance' (the alternative is take the risk that they would be prevented from upgrading to 2.2. because of this issue).  

#### Regression?
V2.2 behavior is different than V2.1 and in this sense it is a regression, however we are actually not changing the behavior, just providing an opt-out.   

#### Risk

Very small.   Consumers wishing to control the EventPipe after startup will  wait longer (before 5 sec, after 20 sec).  The code path that is changed is executed on every startup and thus is well tested.   

#### Issue
https://github.com/dotnet/coreclr/issues/21461  Also see PR #21771.

### CODE REVIEW

**Comment by jorive** [comment]
@dotnet-bot test this please

**Comment by jorive** [comment]
@dotnet-bot test Windows_NT x64 Checked CoreFX Tests

**Comment by jorive** [comment]
@dotnet-bot test Ubuntu x64 Checked CoreFX Tests

**Comment by leecow** [comment]
Need to consider no polling change but include the opt out. Please sync with @DamianEdwards on the change design.

**Comment by jorive** [comment]
@dotnet-bot test this please
@dotnet-bot test Windows_NT x64 Checked CoreFX Tests

**Comment by RussKeldorph** [comment]
Ubuntu x64 Checked Innerloop Build and Test (Jit - TieredCompilation=0) failure is #16061.

**Comment by RussKeldorph** [comment]
Approved per @Eilon and @DamianEdwards

**Pull request merged**
