### PR TITLE
Arm32: Handle live-out double reg in resolution

### PR DESCRIPTION
**Pull request by CarolEidt**
When handling critical edges, live-in and live-out reg masks must contain both halves of double regs.

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by CarolEidt** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test
@dotnet-bot test Ubuntu arm Cross Checked no_tiered_compilation_innerloop Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked Innerloop Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked no_tiered_compilation_innerloop Build and Test
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test

**Comment by CarolEidt** [comment]
@dotnet-bot test Ubuntu arm Cross Checked no_tiered_compilation_innerloop Build and Test
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test
@dotnet-bot test Ubuntu x64 Cross Checked no_tiered_compilation_innerloop Build and Test

**Comment by CarolEidt** [comment]
@dotnet-bot test Ubuntu x64 Cross Checked no_tiered_compilation_innerloop Build and Test

**Comment by CarolEidt** [comment]
@dotnet-bot help

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

**Comment by CarolEidt** [comment]
> Looks like there is an issue between genRegMaskFloat and genRegMask with two arguments.
The first should be probably defined for arm32 only, the second should be used everywhere where we currently call genRegMaskFloat.

Note that `genRegMaskFloat` was pre-existing. And I don't think there's any need to eliminate it.

> even after that it won't be clear where we need to call regMaskTP genRegMask(regNumber regNum, var_types type) and where regMaskTP genRegMask(regNumber reg). Looks like the second can't be called for a reg that has float type on arm32, so can we try to add assert(!genIsValidFloatReg(reg)) into regMaskTP genRegMask(regNumber reg) to catch other cases like this?

It's not the case that the second can't be called for a reg that has float type. In the register allocator, there are many contexts where we only need (indeed, only want) the single register in the case of the float register file. Requiring a type there would make the code more complex and costly.

**Comment by sandreenko** [comment]
> In the register allocator, there are many contexts where we only need (indeed, only want) the single register in the case of the float register file.

Do we have a case where we only need a single register for a double type arm32?

**Comment by CarolEidt** [comment]
> Do we have a case where we only need a single register for a double type arm32?

Sort of; when we are doing register moves at block boundaries, we may be separately moving the two halves of a double register. Indeed, that code doesn't even need to consider whether it is dealing with float or int registers.

Also, during allocation we have already constrained the register set to only include double regs when we're allocating a double interval. It would be unfortunate to have to modify all that code to deal with `genRegMask` returning two bits in the `TYP_DOUBLE` case, not to mention making generating the mask more costly.

It would be really great to audit the current support for these tricky register pairs, but I think that's best undertaken holistically. https://github.com/dotnet/coreclr/issues/11286 is the issue I would associate with doing this.

**Pull request merged**
