### PR TITLE
Fixed issue #3987 "Debugger fails to stop on entry due to stack walk failure"

### PR DESCRIPTION
**Pull request by mikem8361**
By initializing m_rgHijackFunction to NULL.

### CODE REVIEW

**Comment by mikem8361** [comment]
@noahfalk, @jkotas and @sergiy-k code review?

@gregg-miskelly can you verify this fixes the problem?

**Comment by gregg-miskelly** [comment]
Linux is verified. I am working on verifying OSX.

**Comment by mikem8361** [comment]
Thanks.

**Comment by gregg-miskelly** [comment]
OSX works as well. Woohoo!

**Comment by mellinoe** [comment]
OSX CI failed. Is that expected?

**Comment by mikem8361** [comment]
The OSX test failure was a paltest:
foo 0000bfoo bfoo b.foo 42foo 65535foo -1foo 42foo 42foo  42foo 42 foo 42foo 042foo 042foo 42foo +42foo  42foo -42foo -42.foo 42foo 65535foo -1foo 42foo 42foo  42foo 42 foo 42foo 042foo 042foo 42foo +42foo  42foo -42foo -42..............Testing for 64 Bit Platforms 
17:42:51 ..................Testing for 64 Bit Platforms 
17:42:51 ...............................hello world..................................Testing for 64 Bit Platforms 
17:42:53 ..................Testing for 64 Bit Platforms 
17:42:53 .......................Testing for 64 Bit Platforms 
17:42:54 ..................Testing for 64 Bit Platforms 
17:42:54 ..........................................................................................................DeleteFileA: ERROR: Couldn't delete DeleteFileA's "testFile01.txt"
17:42:57 
17:42:57 
17:42:57 FAILED: file_io/DeleteFileA/test1/paltest_deletefilea_test1. Exit code: 1
17:42:57 

This has nothing to do with my change and it passed locally. Rerunning the OSX leg.

**Comment by mikem8361** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Comment by noahfalk** [comment]
lgtm

**Pull request merged**
