### PR TITLE
Port stage work for 3.0

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
#### Description
This work is needed to consume Arcade publishing steps.

Changes have been validated on the internal build as well.
Changes for .NET 5: https://github.com/dotnet/coreclr/pull/26020

/cc @jeffschwMSFT @dotnet/coreclr-infra @JohnTortugo @mmitche 

#### Customer Impact
Enables servicing the product.

#### Regression?
N/A

#### Risk
Minimal since we are now using the same steps as other repos. This should lower risk for this repo going forward.

### CODE REVIEW

**Comment by MeiChin-Tsai** [comment]
approved for .NET Core 3.0

**Comment by AaronRobinsonMSFT** [comment]
Unrelated RegEx test failure in CoreFX.

**Pull request merged**
