### PR TITLE
WIP NO-MERGE Testing

### PR DESCRIPTION
**Pull request by BruceForstall**

### CODE REVIEW

**Comment by BruceForstall** [comment]
https://ci.dot.net/job/dotnet_coreclr/job/dev_unix_test_workflow/job/arm_cross_checked_ubuntu_innerloop_flow_prtest/1/console
```
15:01:02 FATAL: java.nio.channels.ClosedChannelException
15:01:02 java.nio.channels.ClosedChannelException
15:01:02 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 131.107.58.44/131.107.58.44:44266
15:01:02 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1693)
15:01:02 		at hudson.remoting.Request.call(Request.java:192)
15:01:02 		at hudson.remoting.Channel.call(Channel.java:907)
15:01:02 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
15:01:02 		at sun.reflect.GeneratedMethodAccessor578.invoke(Unknown Source)
15:01:02 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:01:02 		at java.lang.reflect.Method.invoke(Method.java:498)
15:01:02 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
15:01:02 		at com.sun.proxy.$Proxy183.execute(Unknown Source)
15:01:02 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1167)
15:01:02 		at hudson.scm.SCM.checkout(SCM.java:495)
15:01:02 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1202)
15:01:02 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
15:01:02 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
15:01:02 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
15:01:02 		at hudson.model.Run.execute(Run.java:1724)
15:01:02 		at com.cloudbees.plugins.flow.FlowRun.run(FlowRun.java:153)
15:01:02 		at hudson.model.ResourceController.execute(ResourceController.java:97)
15:01:02 		at hudson.model.Executor.run(Executor.java:429)
15:01:02 Caused: hudson.remoting.RequestAbortedException
15:01:02 	at hudson.remoting.Request.abort(Request.java:329)
15:01:02 	at hudson.remoting.Channel.terminate(Channel.java:992)
15:01:02 	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:208)
15:01:02 	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:222)
15:01:02 	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:832)
15:01:02 	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)
15:01:02 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:181)
15:01:02 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:283)
15:01:02 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:503)
15:01:02 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:248)
15:01:02 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:200)
15:01:02 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:213)
15:01:02 	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:800)
15:01:02 	at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:173)
15:01:02 	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:311)
15:01:02 	at hudson.remoting.Channel.close(Channel.java:1405)
15:01:02 	at hudson.remoting.Channel.close(Channel.java:1358)
15:01:02 	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:737)
15:01:02 	at hudson.slaves.SlaveComputer.access$800(SlaveComputer.java:96)
15:01:02 	at hudson.slaves.SlaveComputer$3.run(SlaveComputer.java:655)
15:01:02 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
15:01:02 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
15:01:02 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
15:01:02 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
15:01:02 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
15:01:02 	at java.lang.Thread.run(Thread.java:748)
15:01:02 [BFA] Scanning build for known causes...
15:01:02 [BFA] No failure causes found
15:01:02 [BFA] Done. 0s
15:01:02 Notifying endpoint with credentials id 'helix-int-notification-url'
15:01:02 Notifying endpoint with credentials id 'helix-prod-notification-url'
15:01:03 Setting status of ecc9292678a86d95a2b0db8f67f0b40752d5381b to FAILURE with url https://ci.dot.net/job/dotnet_coreclr/job/dev_unix_test_workflow/job/arm_cross_checked_ubuntu_innerloop_flow_prtest/1/ and message: 'Build finished. '
15:01:03 Using context: Ubuntu arm Cross Checked Innerloop Build and Test
15:01:04 ERROR: Step ‘Delete workspace when build is done’ failed: no workspace for dotnet_coreclr/dev_unix_test_workflow/arm_cross_checked_ubuntu_innerloop_flow_prtest #1
15:01:04 ERROR: Step ‘Delete workspace when build is done’ failed: no workspace for dotnet_coreclr/dev_unix_test_workflow/arm_cross_checked_ubuntu_innerloop_flow_prtest #1
```

trying again

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test

**Comment by briansull** [comment]
Please this this PR open until this GC stress run completes, Thanks
ETA 4:15 PM

@dotnet-bot test Windows_NT x64 Checked gcstress0xc

**Comment by BruceForstall** [comment]
@briansull please do not use this PR for your testing. Create your own WIP PR for that purpose. (In addition, note that this is PR does NOT go to master!)

**Comment by BruceForstall** [comment]
@dotnet-bot help

**Comment by briansull** [comment]
I just wantedto see the current state of the GC stress.
I will leave this one alone now.

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Checked jitstress1
@dotnet-bot test Ubuntu arm Cross Checked jitstress2

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs1
@dotnet-bot test Ubuntu arm Cross Checked minopts Build and Test
@dotnet-bot test Ubuntu arm Cross Checked normal Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Checked jitstress1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2 Build and Test

**Comment by BruceForstall** [comment]
@briansull If you don't need the absolute latest bits, you can just check the last time Jenkins ran the job, which is weekly for this job I believe: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_gcstress0xc/

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Checked forcerelocs Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs0x10 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs0x1000 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs0x80 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs3 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs4 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs8 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs0x10 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs0x1000 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs0x80 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs3 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs4 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs8 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitminopts Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitstress1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked tailcallstress Build and Test
@dotnet-bot test Ubuntu arm Cross Debug normal Build
@dotnet-bot test Ubuntu arm Cross Release normal Build and Test
@dotnet-bot test Ubuntu arm Cross Release r2r Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked minopts Build and Test
@dotnet-bot test Ubuntu arm Cross Checked normal Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Debug normal Build
@dotnet-bot test Ubuntu arm Cross Release normal Build and Test
@dotnet-bot test Ubuntu arm Cross Release r2r Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs1
@dotnet-bot test Ubuntu arm Cross Checked minopts Build and Test
@dotnet-bot test Ubuntu arm Cross Checked normal Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs1
@dotnet-bot test Ubuntu arm Cross Checked minopts Build and Test
@dotnet-bot test Ubuntu arm Cross Checked normal Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Checked jitstress1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2 Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Checked forcerelocs Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs0x10 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs0x1000 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs0x80 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs3 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs4 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs8 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs0x10 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs0x1000 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs0x80 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs3 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs4 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs8 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitminopts Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitstress1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked tailcallstress Build and Test
@dotnet-bot test Ubuntu arm Cross Debug normal Build
@dotnet-bot test Ubuntu arm Cross Release normal Build and Test
@dotnet-bot test Ubuntu arm Cross Release r2r Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked minopts Build and Test
@dotnet-bot test Ubuntu arm Cross Checked normal Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test CentOS7.1 x64 Checked Innerloop Build and Test
@dotnet-bot test CentOS7.1 x64 Debug Innerloop Build
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test
@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT x86 Checked Innerloop Build and Test
@dotnet-bot test Windows_NT x86 Release Innerloop Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Pull request closed without merging**
