### PR TITLE
Adding Sse2.StoreScalar(long*, V128) which will replace Sse2.StoreLow(long*, V128)

### PR DESCRIPTION
**Pull request by tannergooding**
This is the CoreCLR side of https://github.com/dotnet/corefx/issues/36746.

Once this is merged and flows into CoreFX, the reference assembly can be updated. Then, that will flow back into CoreCLR at which point we can remove the old API and fixup the tests. Doing it this way (as we have in the past) minimizes the risk of CoreFX/CoreCLR getting out of sync and being in a "torn" state.

### CODE REVIEW

**Comment by tannergooding** [comment]
This is marked * NO MERGE * as it is pending @terrajobst marking it as API Approved before EOD today.

**Comment by tannergooding** [comment]
CC. @terrajobst, @GrabYourPitchforks

**Comment by tannergooding** [comment]
API has been marked approved now. Thanks!

**Comment by tannergooding** [comment]
@fadimounir, failures look related to https://github.com/dotnet/coreclr/pull/24047

**Comment by fadimounir** [comment]
@tannergooding How are the failures related to #24047?

**Comment by tannergooding** [comment]
@fadimounir, failures are:
```
      JIT\CheckProjects\CheckProjects\CheckProjects.cmd [FAIL]
16:09:35         
16:09:35         Return code:      1
16:09:35         Raw output file:      C:\j\workspace\arm_cross_che---c874ca48\bin\tests\Windows_NT.arm.Checked\Reports\JIT.CheckProjects\CheckProjects\CheckProjects.output.txt
16:09:35         Raw output:
16:09:35         BEGIN EXECUTION
16:09:35         
16:09:35         C:\j\workspace\arm_cross_che---c874ca48\bin\tests\Windows_NT.arm.Checked\JIT\CheckProjects\CheckProjects>set COMPLUS_NOGUIONASSERT=1 
16:09:35         
16:09:35         C:\j\workspace\arm_cross_che---c874ca48\bin\tests\Windows_NT.arm.Checked\JIT\CheckProjects\CheckProjects>set COMPLUS_CONTINUEONASSERT=0 
16:09:35          "C:\j\workspace\arm_cross_che---c874ca48\bin\tests\Windows_NT.arm.Checked\Tests\Core_Root\corerun.exe" CheckProjects.exe 
16:09:35         Scanning projects under C:\j\workspace\arm_cross_che---c874ca48\tests\src\JIT
16:09:35         C:\j\workspace\arm_cross_che---c874ca48\tests\src\JIT\Directed\rvastatics\RVAOrderingTest.ilproj DebugType-n/a-SuffixNone
16:09:35         C:\j\workspace\arm_cross_che---c874ca48\tests\src\JIT\Directed\rvastatics\RVAOrderingTest.ilproj Optimize-n/a
16:09:35         7030 projects, 1 needed fixes, 0 were fixed
16:09:35         Expected: 100
16:09:35         Actual: -1
16:09:35         END EXECUTION - FAILED
16:09:35         FAILED
16:09:35         Test Harness Exitcode is : 1
16:09:35         To run the test:
16:09:35         > set CORE_ROOT=C:\j\workspace\arm_cross_che---c874ca48\bin\tests\Windows_NT.arm.Checked\Tests\Core_Root
16:09:35         > C:\j\workspace\arm_cross_che---c874ca48\bin\tests\Windows_NT.arm.Checked\JIT\CheckProjects\CheckProjects\CheckProjects.cmd
16:09:35         Expected: True
16:09:35         Actual:   False
16:09:35         Stack Trace:
16:09:35           D:\j\workspace\arm_cross_che---7ce81708\bin\tests\Windows_NT.arm.Checked\TestWrappers\JIT.CheckProjects\JIT.CheckProjects.XUnitWrapper.cs(129,0): at JIT_CheckProjects._CheckProjects_CheckProjects_._CheckProjects_CheckProjects_cmd()
16:09:35         Output:
16:09:35           
16:09:35           Return code:      1
16:09:35           Raw output file:      C:\j\workspace\arm_cross_che---c874ca48\bin\tests\Windows_NT.arm.Checked\Reports\JIT.CheckProjects\CheckProjects\CheckProjects.output.txt
16:09:35           Raw output:
16:09:35           BEGIN EXECUTION
16:09:35           
16:09:35           C:\j\workspace\arm_cross_che---c874ca48\bin\tests\Windows_NT.arm.Checked\JIT\CheckProjects\CheckProjects>set COMPLUS_NOGUIONASSERT=1 
16:09:35           
16:09:35           C:\j\workspace\arm_cross_che---c874ca48\bin\tests\Windows_NT.arm.Checked\JIT\CheckProjects\CheckProjects>set COMPLUS_CONTINUEONASSERT=0 
16:09:35            "C:\j\workspace\arm_cross_che---c874ca48\bin\tests\Windows_NT.arm.Checked\Tests\Core_Root\corerun.exe" CheckProjects.exe 
16:09:35           Scanning projects under C:\j\workspace\arm_cross_che---c874ca48\tests\src\JIT
16:09:35           C:\j\workspace\arm_cross_che---c874ca48\tests\src\JIT\Directed\rvastatics\RVAOrderingTest.ilproj DebugType-n/a-SuffixNone
16:09:35           C:\j\workspace\arm_cross_che---c874ca48\tests\src\JIT\Directed\rvastatics\RVAOrderingTest.ilproj Optimize-n/a
16:09:35           7030 projects, 1 needed fixes, 0 were fixed
16:09:35           Expected: 100
16:09:35           Actual: -1
16:09:35           END EXECUTION - FAILED
16:09:35           FAILED
16:09:35           Test Harness Exitcode is : 1
16:09:35           To run the test:
16:09:36           > set CORE_ROOT=C:\j\workspace\arm_cross_che---c874ca48\bin\tests\Windows_NT.arm.Checked\Tests\Core_Root
16:09:36           > C:\j\workspace\arm_cross_che---c874ca48\bin\tests\Windows_NT.arm.Checked\JIT\CheckProjects\CheckProjects\CheckProjects.cmd
```

The projects listed look to have been just added in #24047

**Comment by tannergooding** [comment]
It looks like it can't resolve the debug type or optimization type of the project.

**Pull request merged**
