### PR TITLE
Allow arm64 to contain zero in GT_STORE_LCL_FLD

### PR DESCRIPTION
**Pull request by BruceForstall**
The codegen to handle this in codegenarm64.cpp, CodeGen::genCodeForStoreLclFld()
already exists.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked normal Build and Test

**Comment by BruceForstall** [comment]
cc @dotnet/arm64-contrib

**Comment by briansull** [comment]
This is just to mark the node as Contained rather allocating a scratch register (that is unused by Codegen)
I would expect none/little code size diffs, and a handful of register name changes in Arm64 codegen.

**Comment by BruceForstall** [comment]
There are a few diffs where we now use ZR instead of some allocated register.

**Pull request merged**
