### PR TITLE
Fix intermittent test failure in paltest_namedmutex_test1

### LINKED ISSUE #5169: Intermittent test failure in paltest_namedmutex_test1
'paltest_namedmutex_test1' failed at line 610. Expression: !TestFileExists(BuildGlobalShmFilePath(name, NamePrefix))

### PR DESCRIPTION
**Pull request by kouvel**
Fixes #5169:
- Child thread/process was not closing their test mutex before indicating completion to the parent thread/process
- Fixed by enclosing the actual child test code in braces to force closing before the cleanup code runs. This is a minimal fix for the issue, I have a separate change that generally improves and refactors the tests further.

### CODE REVIEW

**Comment by kouvel** [comment]
@sergiy-k

**Comment by sergiy-k** [comment]
LGTM

**Comment by adityamandaleeka** [comment]
LGTM. The CI failure on Windows x64 Debug looks like an infrastructure issue.

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Pull request merged**
