### PR TITLE
Expose some threading type members

### PR DESCRIPTION
**Pull request by kouvel**
- Exposed some public members of WaitHandle
- Fixed "path too long" error message to take a length parameter (as in mscorlib.txt) and uses of it to pass in the correct value for the length
- Made SignalAndWait implementation available on Windows, and throw PlatformNotSupportedException on others

Part of dotnet/corefx#10933

### CODE REVIEW

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by kouvel** [comment]
@jkotas @stephentoub @gkhanna79

**Comment by jkotas** [comment]
👍

**Comment by stephentoub** [comment]
LGTM

**Comment by gkhanna79** [comment]
LGTM. Presumably, the tests (and exposure in contracts) will be a seperate CoreFX PR, right

**Comment by kouvel** [comment]
Yea after exposing the APIs in CoreFX ref assemblies, there will be another PR for tests

**Pull request merged**
