### PR TITLE
Fix #1186: wrong Contract.Assert in Lazy<>::Value getter.

### LINKED ISSUE #1186: Incorrect Assert in Lazy<>::Value getter
See https://github.com/dotnet/coreclr/blob/4cf8a6b082d9bb1789facd996d8265d3908757b2/src/mscorlib/src/System/Lazy.cs#L325:
```csharp
LazyInternalExceptionHolder exc = m_boxed as LazyInternalExceptionHolder;
Contract.Assert(m_boxed != null);
exc.m_edi.Throw();
```
I think, `Contract.Assert(exc != null);` should be here.

### PR DESCRIPTION
**Pull request by ViIvanov**
Fixed issue #1186: a wrong Contract.Assert in a Value property getter of a class Lazy<>.

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM. Thanks.

**Comment by ViIvanov** [comment]
I am sorry, should I close this PR or not?

**Comment by mikedn** [comment]
No, you should not close it. Wait until someone merges it otherwise the change will be lost.

**Comment by jkotas** [comment]
LGTM

**Comment by ViIvanov** [comment]
@mikedn, @jkotas, @stephentoub Thanks a lot :o)

**Pull request merged**
