### PR TITLE
Enable managed heap dumps on Linux

### PR DESCRIPTION
**Pull request by davmason**
This change enables the existing heap dump infrastructure from Windows to work on Linux. It allows us to do managed memory investigations on Linux.

This is the port of the fix to RTM.

### CODE REVIEW

**Comment by joshfree** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/release_1.0.0/job/checked_osx_prtest/38/console
> 12:49:17 Undefined symbols for architecture x86_64:
12:49:17   "_s_forcedGCInProgress", referenced from:
12:49:17       FinalizerThread::FinalizerThreadWorker(void*) in libcee_wks.a(finalizerthread.cpp.o)
12:49:17 ld: symbol(s) not found for architecture x86_64
12:49:17 clang: error: linker command failed with exit code 1 (use -v to see invocation)
12:49:17 make[2]: *** [src/dlls/mscoree/coreclr/libcoreclr.dylib] Error 1
12:49:17 make[1]: *** [src/dlls/mscoree/coreclr/CMakeFiles/coreclr.dir/all] Error 2
12:49:17 make[1]: *** Waiting for unfinished jobs....
12:49:17 Linking CXX shared library libclrjit.dylib

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/release_1.0.0/job/checked_ubuntu_tst_prtest/36/testReport/junit/readytorun.genericsload/usegenericfield/usegenericfield/
>Failed
> 
> readytorun.genericsload.usegenericfield.usegenericfield (from (empty))
> 
> Failing for the past 1 build (Since Failed#36 )
> Took 0 ms.
> Stacktrace
> 
> MESSAGE:
> BEGIN EXECUTION Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0 Copyright (c) Microsoft Corporation. All rights reserved. Native image genericslib.ni.dll generated successfully. Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0 Copyright (c) Microsoft Corporation. All rights reserved. Native image usegenericfield.ni.exe generated successfully. /mnt/j/workspace/dotnet_coreclr/release_1.0.0/checked_ubuntu_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun usegenericfield.exe Assert failure(PID 64432 [0x0000fbb0], Thread: 64432 [0xfbb0]): Consistency check failed: File has not had execution verifiedFAILED: m_bDisableActivationCheck || CheckLoadLevel(FILE_ACTIVE) FAILED: pDomainFile->CheckActivated() /mnt/j/workspace/dotnet_coreclr/release_1.0.0/checked_ubuntu_prtest/src/vm/ceeload.cpp, line: 15387 FAILED: GetModule()->CheckActivated() /mnt/j/workspace/dotnet_coreclr/release_1.0.0/checked_ubuntu_prtest/src/vm/methodtable.cpp, line: 9048 FAILED: CheckActivated() /mnt/j/workspace/dotnet_coreclr/release_1.0.0/checked_ubuntu_prtest/src/vm/methodtable.cpp, line: 3703 File: /mnt/j/workspace/dotnet_coreclr/release_1.0.0/checked_ubuntu_prtest/src/vm/domainfile.cpp Line: 399 Image: /mnt/j/workspace/dotnet_coreclr/release_1.0.0/checked_ubuntu_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun **** MessageBox invoked, title 'corerun - Assert Failure (PID 64432, Thread 64432/0xfbb0)' **** Consistency check failed: File has not had execution verifiedFAILED: m_bDisableActivationCheck || CheckLoadLevel(FILE_ACTIVE) FAILED: pDomainFile->CheckActivated() /mnt/j/workspace/dotnet_coreclr/release_1.0.0/checked_ubuntu_prtest/src/vm/ceeload.cpp, line: 15387 FAILED: GetModule()->CheckActivated() /mnt/j/workspace/dotnet_coreclr/release_1.0.0/checked_ubuntu_prtest/src/vm/methodtable.cpp, line: 9048 FAILED: CheckActivated() /mnt/j/workspace/dotnet_coreclr/release_1.0.0/checked_ubuntu_prtest/src/vm/methodtable.cpp, line: 3703 /mnt/j/workspace/dotnet_coreclr/release_1.0.0/checked_ubuntu_prtest/src/vm/domainfile.cpp, Line: 399 Abort - Kill program Retry - Debug Ignore - Keep running Image: /mnt/j/workspace/dotnet_coreclr/release_1.0.0/checked_ubuntu_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun ******** ./usegenericfield.sh: line 110: 64432 Aborted (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" usegenericfield.exe $CLRTestExecutionArguments Expected: 100 Actual: 134 END EXECUTION - FAILED
+++++++++++++++++++
STACK TRACE:

**Comment by davmason** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please (jenkins had an issue with OS X earlier in the day)

**Comment by ellismg** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please (infrastructure: [machine was out of space to open the semaphores for the debugger](http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/release_1.0.0/job/checked_freebsd_prtest/51/))

/cc @mmitche

**Comment by mikem8361** [comment]
If you mean the semaphore overflow, the fix is in master, but not release 1.0 yet.

**Pull request merged**
