### PR TITLE
[release/3.1] Remove blob feeds

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@wtgodbe Are these known failures?

**Comment by wtgodbe** [comment]
`System.Net.Primitives.Unit.Tests.CookieContainerTest.SetCookies_Success`

I'm seeing this particular test failure in a few arcade ingestion PRs across 3.1 and 5.0: https://github.com/dotnet/coreclr/pull/28175, https://github.com/dotnet/corefx/pull/43081, https://github.com/dotnet/runtime/pull/53937. I thought it was related to the arcade change, but looks like it's a general failure in the runtime. @Anipik @jeffschwMSFT could somebody take a look? We'll need to get this fixed up before servicing builds kick off on Monday

**Comment by jeffschwMSFT** [comment]
Adding @danmoseley for System.Net.* test

**Comment by danmoseley** [comment]
System.Net.Primitives.Unit.Tests.CookieContainerTest.SetCookies_Success is failing for an amusing reason

We need to roll in https://github.com/dotnet/runtime/pull/53932

**Comment by danmoseley** [comment]
I'll create a PR for that in CoreFX.

The regex AV looks very like what https://github.com/dotnet/corefx/pull/43071 should have fixed. (it's being killed on Ubuntu 1804 specifically). That went into corefx release/3.1 a month ago. Is it possible we aren't picking that up?

**Comment by danmoseley** [comment]
@jeffschwMSFT there is a failure in Readytorun/DynamicMethodGCStress/DynamicMethodGCStress/DynamicMethodGCStress.sh

**Comment by jeffschwMSFT** [comment]
@mangod9 can you take a look?  https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-coreclr-refs-pull-28177-merge-d04d265aa6084e2082/PayloadGroup0/console.14985ee3.log?sv=2019-07-07&se=2021-06-29T22%3A26%3A21Z&sr=c&sp=rl&sig=NfOsVTOuW0h8vvtRCG7rYj82cZcw2l2ff%2BVABQylUXE%3D

Looks like a timeout

**Comment by wtgodbe** [comment]
> Is it possible we aren't picking that up?

The corefx -> coreclr subscription hasn't fired in a long time since it's a back edge. Should I fire that off? Or is it a shared source thing?

**Comment by danmoseley** [comment]
I've no idea - who can answer that? But yes, we should be keeping them up to date, otherwise we're in a nonsensical configuration, testing new CoreCLR with old CoreFX.

**Comment by wtgodbe** [comment]
Ok, I triggered https://github.com/dotnet/corefx/pull/43083, https://github.com/dotnet/coreclr/pull/28178, and https://github.com/dotnet/coreclr/pull/28179

**Comment by danmoseley** [comment]
@wtgodbe can we make those updates happen automatically? I see eg., for the SDK one "Microsoft.NETCore.App: from 3.1.9 to 3.1.17-servicing.21309.1". Presumably it should happen at least monthly.

**Comment by mangod9** [comment]
> Looks like a timeout

Yeah feels like its intermittent, trying to rerun it

**Comment by wtgodbe** [comment]
@danmoseley I'd suggest firing them off manually as part of branding - there isn't a day of the month when we know the branches will always be open, so if we create the PRs monthly automatically then they'd sometimes get auto-merged when branches are closed (and we don't want to lose the benefits of having auto-merge on for other maestro PRs)

**Comment by danmoseley** [comment]
@wtgodbe there's no way to tell Maestro to not automerge in dotnet/coreclr and dotnet/corefx only?

But if not -- that's OK. if we have another problem, we can kick it then.

**Comment by wtgodbe** [comment]
>  there's no way to tell Maestro to not automerge in dotnet/coreclr and dotnet/corefx only?

There is, but then we lose the automatic merging of arcade -> coreclr/corefx & coreclr -> corefx PRs, which could slow down the final builds.

**Review by Anipik — APPROVED** [review]

**Comment by aik-jahoda** [comment]
@Anipik, @mmitche is this ready for servicing?

**Pull request merged**
