### PR TITLE
Distinguish genUpdateLife and compUpdateLife for sets and trees.

### PR DESCRIPTION
**Pull request by sandreenko**
These functions are used under different `#ifdefs` and now it is easier to find all matching calls to each of them.

PR 2/3, the first is #17041.

### CODE REVIEW

**Comment by sandreenko** [comment]
PTAL @dotnet/jit-contrib.

**Comment by sandreenko** [comment]
> Hmmmm.... I don't know. You're making it easier to 'grep', which I generally like, but is it worth it?

I made this change to make #17055 clearer, that I think is worth to be merged.

> genUpdateTreeLife(GenTree* tree);
> genUpdateVarsLife(VARSET_VALARG_TP newLife);

Yes, it looks better, I will update the PR if we decide that we want to take this changes.

**Comment by CarolEidt** [comment]
> is it worth it? I might say no. What do others think?

I tend to agree.

> I might suggest:
> genUpdateLifeTree(GenTree* tree);
> genUpdateLifeVars(VARSET_VALARG_TP newLife);

Those would be my preferred names over the other suggestion.

**Comment by CarolEidt** [comment]
I would add that I wouldn't object to these changes, but it seems to me that doing it now is unnecessary churn.

**Comment by sandreenko** [comment]
Pr was updated to use

> genUpdateLifeTree(GenTree* tree);
> genUpdateLifeVars(VARSET_VALARG_TP newLife);

**Comment by sandreenko** [comment]
PR was closed, because if we delete `legacy_backend` it will delete this duplication.

**Pull request closed without merging**
