### PR TITLE
Delete some dead PAL code

### PR DESCRIPTION
**Pull request by justinvp**
`GetComputerName` and `GetUserName` are not used.

### CODE REVIEW

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by danmosemsft** [comment]
I wonder if there is some reasonable trick we could use to suggest other PAL code that may be dead now.

**Comment by janvorli** [comment]
@danmosemsft I just got an idea - remove the coreclrpal library from the list of libcoreclr.so dependencies in src/dlls/mscoree/coreclr/CMakeLists.txt, then build coreclr and run `ldd -r libcoreclr.so`. It dumps all the functions that were used by the libcoreclr.so and are not defined now. Repeat that for all libraries that link to PAL. Finally add functions that we call from the runtime via PInvoke (provided there are any left, but I think there are some). This gives you the list of functions that are used. Now scan function prototypes in pal.h and see which functions are not on the final list.
I've tried that quickly just for libcoreclr.so and it uses about 240 functions.

**Comment by danmosemsft** [comment]
Maybe you could put that in a gist and track in an issue, perhaps folks would like to work through them.

**Comment by justinvp** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test please (JIT_Generics._Coverage_chaos65204782cs_o_chaos65204782cs_o_._Coverage_chaos65204782cs_o_chaos65204782cs_o_cmd)

**Comment by justinvp** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test please (JIT_Generics.Coverage_chaos65204782cs_o_chaos65204782cs_o._Coverage_chaos65204782cs_o_chaos65204782cs_o_cmd)

**Comment by janvorli** [comment]
@danmosemsft I will put together a list of all used PAL functions as you've suggested and create an issue for removing the unused ones.

**Comment by janvorli** [comment]
I've created issue #13503 and attached the list of used PAL functions.

**Comment by justinvp** [comment]
@dotnet-bot test Windows_NT x86 min_opt legacy_backend CoreCLR Perf Tests Correctness please (The build timed out, or was forcibly aborted after reaching the maximum length.)

**Comment by danmosemsft** [comment]
@dotnet/dnceng this job "Windows_NT x64 full_opt ryujit CoreCLR Perf Tests Correctness" shows just "started" but the link https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_perflab_Windows_NT_x64_full_opt_ryujit_smoketest_prtest/10/ says it succeeded 5 hours ago. Why doesn't it show up above?

**Comment by justinvp** [comment]
Another oddity: All CI checks for this PR were green, but after Jan commented, I noticed a bunch of new "Perf Tests Correctness" legs showed up and started running. Not sure why they showed up on a PR that was already green.

**Comment by danmosemsft** [comment]
I think I've seen wierdness like this when legs are added (in the groovy file) and existing jobs pick them up (when a new change is pushed)

**Comment by justinvp** [comment]
> when a new change is pushed

Weird, in this case the new legs were added without any new changes pushed to this branch.

**Comment by mmitche** [comment]
@justinvp This can happen when someone adds a new leg.  Jenkins will notice that it was not run on the PR and add them.

**Comment by mmitche** [comment]
Also, there was a reboot of that CI server yesterday morning, so that may have been why the job showed as "finished" but didn't update on here.

**Pull request merged**
