### PR TITLE
Fix LPTSTRTest failure - it has a incorrect constant

### LINKED ISSUE #4197: LPTSTRTest test fails on non-windows platform

### PR DESCRIPTION
**Pull request by yizhang82**
Fix #4197. Probably from bad merging.

### CODE REVIEW

**Comment by yizhang82** [comment]
@dotnet-bot Test CentOS7.1 x64 Debug Build and Test please

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by yizhang82** [comment]
Looks like CI is having issues? Thanks @jkotas for keeping an eye on it!

**Comment by jkotas** [comment]
Yes, there was a bad PR committed that broke Unix pretty badly. It has been reverted and everything should be green again.

**Comment by yizhang82** [comment]
Not sure how the other commit get in this PR. Probably because when I issue the rebase command, it accidentally included that one (even though I didn't make any changes to it)...

**Comment by jkotas** [comment]
Yes, you should redo the rebase so that the PR has just your change.

**Comment by yizhang82** [comment]
Yeah. I think I've accidentally replayed a earlier non-related change in the rebase - even though I haven't touched it, it still become a brand new commit. I rebased again and dropped that commit, which technically isn't correct since this branch lost that change forever, but works for the purpose of having a clean PR.

**Comment by yizhang82** [comment]
Failing OSX is unrelated test failure Marshal.Copy tracked by #4254

**Comment by yizhang82** [comment]
@tijoytom @botaberg Note that LPSTR/LPTSTR tests was excluded in issues.targets, which i have fixed. We should make sure all of them are running on windows.

**Pull request merged**
