### PR TITLE
Implement GetProcessIdDisambiguationKey() for NetBSD

### PR DESCRIPTION
**Pull request by krytarowski**
Make use of the `kvm`(3) interface to get `struct kinfo_proc2` of the given
process.

```
struct kinfo_proc2 {
///....
        uint32_t p_ustart_sec;          /* STRUCT TIMEVAL: starting time. */
        uint32_t p_ustart_usec;         /* STRUCT TIMEVAL: starting time. */
///...
};
```

  --- /usr/include/sys/sysctl.h

### CODE REVIEW

**Comment by krytarowski** [comment]
Change to `src/pal/src/CMakeLists.txt` is duplicated with https://github.com/dotnet/coreclr/pull/4357

**Comment by krytarowski** [comment]
This commit has been rebased to master, no more duplication.

**Comment by krytarowski** [comment]
@jkotas @janvorli PTAL

**Comment by janvorli** [comment]
LGTM

**Comment by adityamandaleeka** [comment]
LGTM. Can you just change NULL to nullptr to match the rest of the function?

**Comment by krytarowski** [comment]
done!

**Comment by adityamandaleeka** [comment]
LGTM, thanks.

**Pull request merged**
