### PR TITLE
Turn off outerloop perf and make job run periodically

### PR DESCRIPTION
**Pull request by adiaaida**
This is mostly for testing purposes. Would run about 5 times an hour.

### CODE REVIEW

**Comment by adiaaida** [comment]
@dotnet-bot test ci please

**Comment by adiaaida** [comment]
@dotnet/rap-team PTAL

**Comment by DrewScoggins** [comment]
Can we make an issue to track turning this back to PR? Other than that LGTM

**Comment by adiaaida** [comment]
@DrewScoggins opened #15430

**Pull request merged**
