### PR TITLE
Decrease EventListener buffer size

### PR DESCRIPTION
**Pull request by sywhang**
Decrease the default buffer size used by EventListener sessions from 1GB to 10MB

### CODE REVIEW

**Comment by jorive** [comment]
Should we decrease the EventPipe default buffer size too? On EventPipeController?

**Comment by sywhang** [comment]
Spoke with Noah about that and he said no since the issue we’re trying to solve is in-proc scenarios using EventListener.

**Comment by jorive** [comment]
What about the `dotnet-trace` default buffer size?

**Comment by sywhang** [comment]
Same thing. Noah will probably correct me if I'm wrong, but my understanding is that the reason we're trying to decrease the buffer size for EventListener scenarios is because we know that events will get flushed about every 10 ms (or more often when David makes his change regarding this) and we don't need the buffer size to be so aggressive. 

W.r.t. other scenarios (enabling via environment variable, dotnet-trace, PerfView), I don't think this is necessarily the case. But if we do think we should fix those I can follow up with a separate PR to address that. But the issue I am trying to fix with this particular PR is the first checkbox in https://github.com/dotnet/coreclr/issues/25413 which is specific to EventListener :)

**Comment by noahfalk** [comment]
The main reason I was highlighting EventListener specifically is because:
a) Unlike all the other ways to enable a session, we don't provide any way for the user to specify the buffer size in this scenario. Thus the default is more important. (We might want to add an API to set it in the future, but too late for this release)
b) I don't think people expect EventSource -> EventListener to do large scale buffering. In the past it never did.

**Pull request merged**
