### PR TITLE
Adding tests for the new apis to convert between S.Numerics and S.R.Intrinsic vectors

### PR DESCRIPTION
**Pull request by tannergooding**
This just adds some basic tests covering the software fallback paths for the new conversion APIs.

### CODE REVIEW

**Comment by tannergooding** [comment]
CC. @CarolEidt

**Comment by tannergooding** [comment]
These, as usual, are generated from templates.

**Comment by tannergooding** [comment]
Hmmm, there is a bug on ARM32.

The method is doing:
```
            Debug.Assert(Vector256<T>.Count >= Vector<T>.Count);
            ThrowHelper.ThrowForUnsupportedVectorBaseType<T>();
 
            Vector256<T> result = default;
            Unsafe.WriteUnaligned(ref Unsafe.As<Vector256<T>, byte>(ref result), value);
            return result;
```

But `result` is not being zeroed.

**Comment by tannergooding** [comment]
The bug only repros if Tiered Compilation is disabled

**Comment by tannergooding** [comment]
Ok, so on ARM32:
* [JitDump_AsVector256_TC=1.txt](https://github.com/dotnet/coreclr/files/3785900/JitDump_AsVector256_TC.1.txt) -- Doesn't repro
* [JitDump_AsVector256_TC=0.txt](https://github.com/dotnet/coreclr/files/3785901/JitDump_AsVector256_TC.0.txt) -- Does repro

We ultimately get downto:
```
removing stmt with no side effects

Removing statement STMT00005 (IL 0x019...  ???)
N003 (  5,  4) [000015] IA------R----             *  ASG       struct (init)
N002 (  3,  2) [000012] D------N-----             +--*  LCL_VAR   struct V02 loc0         
N001 (  1,  1) [000014] -------------             \--*  CNS_INT   int    0
 in BB03 as useless:
```

I'm still not quite sure why ARM32 decides a struct initializer is useless.

**Comment by tannergooding** [comment]
I'm guessing that it fails to see that `result` is used as part of a `byref` and so liveness isn't calculated correctly; but I'm still digging through the dump 😄 

CC. @dotnet/jit-contrib

**Comment by CarolEidt** [comment]
It looks like the TC.1.txt dump is the one that has that removal of the init of V02, but it seems to me that it's indeed useless, because two statements down it is redefined, just before being used.

**Comment by mikedn** [comment]
That `WriteUnaligned` is incorrectly imported (in my own dump):
```
               [000023] -A-----------             *  ASG       struct (copy)
               [000021] D------------             +--*  LCL_VAR   struct V03 loc0         
               [000022] -------------             \--*  LCL_VAR   struct V05 tmp1         
```
with V03 and V05 having different types:
```
;  V03 loc0         [V03,T02] (  2,  2   )  struct (32) [sp+0x10]   do-not-enreg[SB] must-init ld-addr-op
;# V04 OutArgs      [V04    ] (  1,  1   )  lclBlk ( 0) [sp+0x00]   "OutgoingArgSpace"
;  V05 tmp1         [V05,T01] (  2,  4   )  struct (16) [sp+0x00]   HFA(float)  do-not-enreg[SB] "Inlining Arg"
```

**Comment by tannergooding** [comment]
> It looks like the TC.1.txt dump

Yes, somehow the file names got swapped. I've updated them to be correct (TC=0 repros the issue; TC=1 does not and calls out that it is Tier-0 and minopts).

**Comment by mikedn** [comment]
Ha ha, this is a piece of code a was starring at recently wondering how it's supposed to work:

https://github.com/dotnet/coreclr/blob/80867d1b5753ea5625b63aecccab1084c84e62af/src/jit/importer.cpp#L1185-L1195

I suppose now I found out - it does not work.

**Comment by tannergooding** [comment]
So the problem here is that both are `TYP_STRUCT` and they are later differentiated to be `TYP_SIMD12` vs `TYP_SIMD16`, correct?

**Comment by mikedn** [comment]
> So the problem here is that both are TYP_STRUCT and they are later differentiated to be TYP_SIMD12 vs TYP_SIMD16, correct?

Yes, when the type is TYP_STRUCT the class handle should be checked to ensure that it's really the same type (or at least if they are different types they have the same size).

It's not clearly visible in the current JIT dumps because they only show "struct" but in a branch I have one can clearly see that the LHS of the assignment still has type `Vector256` despite the `As` cast to `Vector4`:
```
[000023] -A-----------             *  ASG       struct (copy)
[000021] D------------             +--*  LCL_VAR   struct<System.Runtime.Intrinsics.Vector256`1[Single], 32> V03 loc0         
[000022] -------------             \--*  LCL_VAR   struct<System.Numerics.Vector4, 16> V05 tmp1         
```
So liveness correctly believes that the entire variable will be assigned to and thus the previous zero initialization is useless.

**Comment by CarolEidt** [comment]
> It actually looks like we normalize the struct type a few lines lower in this method, so maybe just reordering things a bit will allow this to fall out.

It seems to me, without analyzing this in detail, that the whole "pre-optimization" of eliminating the `ADDR` should be moved later, and, as @mikedn points out, we should be checking consistency of handles before making that optimization.

**Comment by tannergooding** [comment]
Logged https://github.com/dotnet/coreclr/issues/27551

**Comment by maryamariyan** [comment]
Thank you for your contribution. As announced in dotnet/coreclr#27549 this repository will be moving to dotnet/runtime on November 13. If you would like to continue working on this PR after this date, the easiest way to move the change to dotnet/runtime is:
1.	In your coreclr repository clone, create patch by running `git format-patch origin`
2.	In your runtime repository clone, apply the patch by running `git apply --directory src/coreclr <path to the patch created in step 1>`

**Comment by tannergooding** [comment]
I've marked this `post-consolidation` as I'm comfortable hand-porting this after the change if necessary.

This is only blocked on https://github.com/dotnet/coreclr/pull/27577, so if it gets merged, CI can rerun and this should be mergeable as well.

**Comment by CarolEidt** [comment]
@tannergooding sorry for the delay on #27551 - I was out a few days and am currently debugging an arm64 crossgen assert.

**Comment by tannergooding** [comment]
No worries, I just wanted to get thus PR off the graph of PRs being tracked for merge before the consolidation 😄

**Comment by tannergooding** [comment]
@CarolEidt, I think this should be ready for review now that the you fixed the associated bug.

It's just adding tests for the new conversion APIs and gives `Vector128.AsVector3` a function implementation while https://github.com/dotnet/coreclr/issues/27405 is being fixed (which is addressed by https://github.com/dotnet/coreclr/pull/27748).

**Comment by tannergooding** [comment]
Tests are templated and split into two commits for easier reviewing.

**Comment by tannergooding** [comment]
Rebased onto current head and ensured that `Vector128.AsVector3` has the efficient implementation now that the bug is resolved.

**Comment by tannergooding** [comment]
Also CC. @echesakovMSFT, if you are available for review.

This is just adding tests for new APIs that allow converting between the older System.Numerics and newer System.Runtime.Intrinsic vector types.

**Pull request merged**
