### PR TITLE
Port of fix for issue 5241: [RTM] Interop\ICastable\Castable\Castable.cmd CONTRACT VIOLATION by ReadyToRunInfo::TryLookupTypeTokenFromName

### PR DESCRIPTION
**Pull request by fadimounir**
Porting b79ea9b0bb8a864b3824dcb82a5c0a7e39c88583 from master to release/1.0.0

### CODE REVIEW

**Comment by fadimounir** [comment]
@dotnet-bot test  Windows_NT x64 Debug Build and Test pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu Release pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu Checked pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Windows_NT x64 Release pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Windows_NT x64 Checked pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Windows x64 Release pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Windows x64 Checked pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Windows_NT Release pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Windows_NT Checked pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu Checked pri1r2r please

**Comment by sergiy-k** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by ramarag** [comment]
@dotnet-bot test Windows_NT x64 Release R2R pri1 Build & Test

**Comment by ramarag** [comment]
@dotnet-bot test Windows_NT x64 Release R2R pri1 Build & Test

**Comment by sergiy-k** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by gkhanna79** [comment]
Infra issues:

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/release_1.0.0/job/x64_release_windows_nt_pri1r2r_prtest/2/

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/release_1.0.0/job/x64_release_ubuntu_pri1r2r_flow_prtest/1/

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/release_1.0.0/job/x64_checked_ubuntu_pri1r2r_flow_prtest/2/

Restarting the affected jobs

**Comment by gkhanna79** [comment]
@dotnet-bot test Ubuntu Checked pri1r2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test @dotnet-bot test Windows_NT x64 Release R2R pri1 Build & Test please

**Comment by gkhanna79** [comment]
@dotnet-bot test  Ubuntu x64 Release R2R pri1 Build & Test please

**Comment by gkhanna79** [comment]
@dotnet-bot test Windows_NT x64 Release R2R pri1 Build & Test please

**Comment by gkhanna79** [comment]
@dotnet-bot test Ubuntu Release pri1r2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test Windows_NT x64 Release R2R pri1 Build & Test

**Comment by gkhanna79** [comment]
@dotnet-bot test Windows_NT Release pri1r2r

**Comment by gkhanna79** [comment]
@fadimounir The failures in the Pri1R2R jobs look like known issues (e.g. assert that is being fixed at https://github.com/dotnet/coreclr/pull/5347). Can you confirm?

**Comment by sergiy-k** [comment]
According to @fadimounir all failures in R2R tests are known and have tracking issues opened.

**Pull request merged**
