### PR TITLE
Move adjustments to genStackLevel into functions

### PR DESCRIPTION
**Pull request by BruceForstall**
Add functions AddStackLevel(), SubtractStackLevel(), and SetStackLevel()
for making any changes to genStackLevel. this allows for centralized asserts,
JitDump output, and breakpoint setting.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib PTAL

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test

**Comment by pgavlin** [comment]
Did you check the code that the MSVC/clang/etc. generate? It'd be a shame if they didn't boil this down to e.g. `genStackLevel -= 4`.

**Comment by BruceForstall** [comment]
@pgavlin I didn't. But if they can't optimize that, they're pathetic. Plus, these aren't hot.

**Pull request merged**
