### PR TITLE
Fix tests/setup-runtime-dependencies.sh as per dotnet cli changes

### PR DESCRIPTION
**Pull request by sejongoh**

### CODE REVIEW

**Comment by sejongoh** [comment]
@swaroop-sridhar PTAL.

**Comment by swaroop-sridhar** [comment]
The changes loog good.
setup-runtime-dependencies.cmd will also need a similar change for the changed path,

**Comment by sejongoh** [comment]
Yeah, it is a simple change. I will update the cmd file once I test it on my local machine. My Window workspace has some issue and I am rebuilding it.

**Comment by sejongoh** [comment]
@swaroop-sridhar PTAL. I also merged the reverted changes to this PR.

**Comment by swaroop-sridhar** [comment]
Green, thanks.

**Pull request merged**
