### PR TITLE
ARM-CI: Use CI cross build script in emulator

### PR DESCRIPTION
**Pull request by prajwal-aithal**
Previous PRs added the build commands to the groovy script.
But this did not work for various reasons.
The current patch makes the CI system execute the bash script
that does the cross build. The bash script is already supplied with the emulator

Signed-off-by: Prajwal A N <an.prajwal@samsung.com>

### CODE REVIEW

**Comment by prajwal-aithal** [comment]
@jashook Please review this (after making the changes to the emulator directory).

**Comment by prajwal-aithal** [comment]
@dotnet-bot test CI please

**Comment by jashook** [comment]
@dotnet-bot test CI Please

**Comment by jashook** [comment]
lgtm

**Pull request merged**
