### PR TITLE
Replace `SList` in the GC info encoders.

### PR DESCRIPTION
**Pull request by pgavlin**
Instead of using `SList`, manage the links manually. There are only
a few list manipulations in the encoders, so this is not too onerous.

### CODE REVIEW

**Comment by pgavlin** [comment]
@russellhadley @dotnet/jit-contrib PTAL

**Comment by mikedn** [comment]
IMO dragging in a trimmed down version of SList would have been preferable to inlining its code here and there.

**Comment by pgavlin** [comment]
> IMO dragging in a trimmed down version of SList would have been preferable to inlining its code here and there.

In this case, the trimmed down version of `SList` amounts to three methods, each of which is used twice. I felt that the overhead of an additional header outweighed the benefits of retaining the abstraction, but I could be convinced otherwise.

**Comment by pgavlin** [comment]
FWIW, the only place that `SList` really provides any benefit is `InsertTail`.

**Comment by pgavlin** [comment]
I should note that this is part of #4127.

**Comment by mikedn** [comment]
>  I felt that the overhead of an additional header outweighed the benefits of retaining the abstraction

If it has to be in a different header then yes, I agree with you. But I think that `SList` could go into the existing headers, where `MemoryBlockDesc` already is.

**Comment by pgavlin** [comment]
That's not unreasonable... `MemoryBlockDesc` is already duplicated, in any case.

**Comment by pgavlin** [comment]
PTAL. I took the opportunity to merge the memory block descriptor with the memory block itself.

**Comment by mikedn** [comment]
👍

**Comment by russellhadley** [comment]
LGTM

**Pull request merged**
