### PR TITLE
Organizing the perflab tests under a common namespace.

### PR DESCRIPTION
**Pull request by jorive**
- These changes adds a hierarchy to the perflab tests under BenchView.

### CODE REVIEW

**Comment by jorive** [comment]
@dpodder @DrewScoggins @brianrob @valenis I have a small change to the perflab tests that group them on BenchView.

**Comment by DrewScoggins** [comment]
test Windows_NT perf

**Comment by DrewScoggins** [comment]
It is kind of difficult to tell from the diffs, but I assume you just added/changed the namespace for all these tests to match up PerfLabTests, yes?

**Comment by jorive** [comment]
@DrewScoggins Yes, I added namespace PerfLabTests to all tests (and formatted them accordingly).

**Comment by dpodder** [comment]
Thanks @jorive, LGTM

**Comment by jorive** [comment]
@dotnet-bot test this please

**Comment by jorive** [comment]
@dotnet-bot test Windows_NT perf

**Comment by DrewScoggins** [comment]
Just take a look at the results and make sure they look formatted right. Then LGTM.

**Pull request merged**
