### PR TITLE
PAL enable Thread affinity support

### PR DESCRIPTION
**Pull request by sdmaclea**

### CODE REVIEW

**Comment by sdmaclea** [comment]
@janvorli PTAL.  This seems to be working on ARM64 & x64 as it is also used in GCServer mode in the GC.  I have ben running in my local tree with it enabled for the last few weeks.  I have not seen an issue.
Not sure why the GC code is gated by AMD64/ARM64.  Not sure if this will need that gating too.

**Comment by janvorli** [comment]
@sdmaclea The GC/API/GC/Collect0 and / GC/API/GC/Collect1 tests are crashing in the CI with SIGSEGV. Is that expected?

**Comment by janvorli** [comment]
> Not sure why the GC code is gated by AMD64/ARM64. Not sure if this will need that gating too.

Where do you see similar GC code being gated by AMD64/ARM64? I can only see the gating in the CPUGroupInfo::InitCPUGroupInfo. That influences return value of CPUGroupInfo::CanEnableGCCPUGroups(). That gating is because there is no NUMA support for 32 bit Windows. Does 32 bit Linux support NUMA?

**Comment by sdmaclea** [comment]
@janvorli I have no knowledge of 32-bit linux.  Ubuntu arm64 has never been green.  It is actualy weird it will be green, then later turn red.  arm failure looks like it was a timeout.  When I was building arm64 natively, I saw some compile errors, but I assume I just needed to install NUMA packages.  Cross build with Xenial ROOTFS is working.

**Comment by janvorli** [comment]
@sdmaclea the build should work fine without numa dev package being installed. The cmake config script should detect that and disable the NUMA support. If the compilation fails, then it is a bug.

**Comment by janvorli** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Build and Test please

**Comment by sdmaclea** [comment]
@janvorli I found out the arm64 machine which was having trouble compiling with this patch has a corrupted filesysytem.  I will need to set up a new arm64 native build environment to see if the compilation failure was real or not.

**Comment by sdmaclea** [comment]
@janvorli I reconstructed the build environment with package `numa-dev` which probably wasn't there before.  When compiling an old tip, the compiled failed with numa_* undefined reference errors.  When I rebased to the latest upstream tip the problem was resolved.

**Comment by sdmaclea** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Build and Test

**Comment by sdmaclea** [comment]
@janvorli arm64 ubuntu failure can be ignored.  PTAL.

**Pull request merged**
