### PR TITLE
Turn on nullability for all of Corelib

### PR DESCRIPTION
**Pull request by stephentoub**
Enable nullable annotations at the project level, and remove most of the `#nullable enable`s from the source files.

cc: @dotnet/nullablefc, @danmosemsft, @jkotas

### CODE REVIEW

**Comment by safern** [comment]
I don’t think we can remove all nullable enable, because of the files that are shared with mono, corert and corefx through the mirror. If there is a `?` then the compiler will complain because a `?` is only enable on a nullable context.

**Comment by stephentoub** [comment]
> I don’t think we can remove all nullable enable

That's why I said "most" :wink:

I explicitly didn't remove the ones that would break corefx.  It's possible a few slipped through, but I successfully built corefx with a manually-copied set of these files for both Windows and Linux.

For corert, I don't expect anything to break, and if it does, it should be easy to fix.  corert uses the shared project file, which has NullableContextOptions set.

If mono is pulling in individual files and isn't setting NullableContextOptions and is pulling in individual files rather than using the shared project, then yes, this could cause a build break for mono.  @marek-safar ?

We should make this change soon, though, as without it we'll start to see the nullable annotations go stale as new files are added that don't take nullability into account and neglect to include `#nullable enable`.

**Comment by jkotas** [comment]
> For corert, I don't expect anything to break, and if it does, it should be easy to fix. corert uses the shared project file, which has NullableContextOptions set.

Agree. Number of nullability changes required fixes in CoreRT to keep the build working. This is likely going to be another one of those.

**Comment by safern** [comment]
Yes I completely agree. The reason why I mentioned that is because from taking a quick look y saw that some files had `?` for example: https://github.com/stephentoub/coreclr/blob/b9f79e90e03152325f9efb832dc4bd3eb274a0dd/src/System.Private.CoreLib/shared/Internal/Win32/RegistryKey.cs#L78

But make sense to merge this and if so fix it in other repos when the files get mirrored to make the right changes in the PR.

Thanks for doing this.

**Comment by marek-safar** [comment]
> If mono isn't setting NullableContextOptions and is pulling in individual files rather than using the shared project

We are using shared project and #nullable was causing us breakages so this change is no status quo change for us

**Comment by stephentoub** [comment]
Great.  Thanks, all.

**Pull request merged**
