### PR TITLE
Fix two "unreached" asserts

### PR DESCRIPTION
**Pull request by BruceForstall**
The asserts as written would never fire. Replace them with asserts that will.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@sivarv PTAL
/cc @dotnet/jit-contrib

**Comment by RussKeldorph** [comment]
LGTM

**Comment by CarolEidt** [comment]
LGTM, though it begs the question of why these don't simply have asserts about the types, followed by an unconditional return.

**Comment by pgavlin** [comment]
+1 to Carol's feedback. It certainly seems cleaner to assert on the types and always return a valid instruction.

**Comment by sivarv** [comment]
Looks good.

**Pull request merged**
