### PR TITLE
Fix conversion, unknown pragmas and Visibility Issues for GCC

### PR DESCRIPTION
**Pull request by franksinankaya**
@am11 @jkotas @janvorli

### CODE REVIEW

**Comment by janvorli** [comment]
@dotnet/dnceng The CentOS 7.1 legs are failing with
`Disk has run out of space and cannot get latest changes. Please contact dnceng@microsoft.com. IOException: No space left on device`.

**Comment by janvorli** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test please

**Comment by franksinankaya** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Innerloop Build please
@dotnet-bot test CentOS7.1 x64 Checked Innerloop Build and Test please

**Comment by franksinankaya** [comment]
Any other comments?

**Pull request merged**
