### PR TITLE
Include license files into the packages

### PR DESCRIPTION
**Pull request by weshaggard**
Port https://github.com/dotnet/coreclr/pull/5400 to release.

### CODE REVIEW

**Comment by weshaggard** [comment]
cc @gkhanna79

**Comment by gkhanna79** [comment]
LGTM

**Comment by joshfree** [comment]
LGTM

**Comment by weshaggard** [comment]
@dotnet-bot OSX x64 Checked Build and Test

**Comment by sergiy-k** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please
(infrastructure issue)

**Pull request merged**
