### PR TITLE
Fix an issue where GCStress allocated objects using the Gen 0 alloc context

### PR DESCRIPTION
**Pull request by swgillespie**
Fixes https://github.com/dotnet/coreclr/issues/10265

@Maoni0 PTAL?

### CODE REVIEW

**Comment by swgillespie** [comment]
@dotnet-bot test Windows_NT gcstress0x3

**Comment by Maoni0** [comment]
LGTM!

**Comment by swgillespie** [comment]
@dotnet-bot test Windows_NT gcstress0x3

**Comment by swgillespie** [comment]
Looks like I still have some heap corruption issues. Will look into it.

**Comment by swgillespie** [comment]
@pgavlin @RussKeldorph I see some of the above GCStress failures even without https://github.com/dotnet/coreclr/pull/10065 - are these my fault or are there known failures in the GCStress3 job? (Should I make bugs for them?)

**Comment by swgillespie** [comment]
I'm going to go ahead and merge this to unblock the GCStress3 job, we can create bugs for the other issues if we are tracking them.

**Comment by RussKeldorph** [comment]
@swgillespie It's possible there are additional failures.  Thanks for fixing this.  We'll figure out how to address the rest once this is out of the way.

**Comment by swgillespie** [comment]
Sounds good!

**Comment by sdmaclea** [comment]
It looks like this failed to fix all the gcStress issues introduced by the original patch 

@dotnet-bot help

**Pull request merged**
