### PR TITLE
Port to Release/3.1 - Fix available memory extraction on Linux

### LINKED ISSUE #26924: Port fix available memory extraction on Linux to 3.1 release
Issue to track porting of #26764 to 3.1

### PR DESCRIPTION
**Pull request by agoretsky**
Port #26764 to 3.1 Release

Close #26924

### CODE REVIEW

**Comment by agoretsky** [comment]
Got it working on OSX, but there are some build errors on Linux, @janvorli could you help me?

**Comment by janvorli** [comment]
@agoretsky the issue is that you have accidentally added the GetLogicalProcessorCacheSizeFromOS function to gcenv.os.cpp. That was not part of my change.

**Comment by agoretsky** [comment]
@MeiChin-Tsai

**Comment by janvorli** [comment]
Btw, if @MeiChin-Tsai supports porting this fix, I'd still like to give it a bit more time to bake in before merging this  port.

**Comment by wtgodbe** [comment]
@agoretsky @janvorli does this need to be included with `release/3.1-preview1`? If so, it needs to be merged by EOD today (as we start the build process tomorrow morning). Otherwise we can take it for preview2.

**Comment by janvorli** [comment]
@wtgodbe thank you for the heads up, I don't want to rush this. We need to do some more GC perf measurements before porting it.

**Comment by MeiChin-Tsai** [comment]
@agoretsky Can you articulate the scenario that drive the need? Or the risk of fix?

**Comment by janvorli** [comment]
@MeiChin-Tsai here is the original issue where the details were discussed:
https://github.com/dotnet/coreclr/issues/26568
Maybe the best thing to show the benefit is this p99 response time graph the Criteo guys have produced before and after the change:
https://twitter.com/KooKiz/status/1173514597061599232

**Comment by MeiChin-Tsai** [comment]
Approved

**Comment by richlander** [comment]
I also endorse this change.

**Comment by wtgodbe** [comment]
This can be merged tomorrow, that's when branches open for preview2

**Pull request merged**
