### PR TITLE
Improve runtest.sh concurrency

### PR DESCRIPTION
**Pull request by wateret**
`runtest.sh` runs next tests immediately after any of child processes is done

### CODE REVIEW

**Comment by wateret** [comment]
cc: @dotnet/jit-contrib @dotnet/arm32-contrib

**Comment by wateret** [comment]
Related Issue: #14035

**Comment by wateret** [comment]
## Comparison

On my RPi3, unit tests pri0.

### Before

```
=======================
     Test Results
=======================
# CoreCLR Bin Dir  :
# Tests Discovered : 7091
# Passed           : 6362
# Failed           : 9
# Skipped          : 720
=======================
128 minutes and 56 seconds taken to run CoreCLR tests.
```

### After

```
=======================
     Test Results
=======================
# CoreCLR Bin Dir  :
# Tests Discovered : 7091
# Passed           : 6357
# Failed           : 14
# Skipped          : 720
=======================
98 minutes and 53 seconds taken to run CoreCLR tests.
```

Duration : 129 mins -> 98mins
Failed Tests : 9 -> 14 (5 more fails due to OOM)

**Comment by wateret** [comment]
It looks like there is no easy way to wait for any of child process, so I wrote a helper for this. (There is an option of `wait` for that but requires bash version 4.3 or higher.)

**Comment by BruceForstall** [comment]
@wtgodbe PTAL

**Comment by wtgodbe** [comment]
LGTM. Any idea why we're getting more OOMs?

**Comment by wateret** [comment]
Here is the list of additional fails with OOM.

```
FAILED   - GC/Features/HeapExpansion/pluggaps/pluggaps.sh
FAILED   - GC/Regressions/v2.0-beta2/460373/460373/460373.sh
FAILED   - GC/Regressions/v2.0-beta1/149926/149926/149926.sh
FAILED   - GC/Regressions/v2.0-rtm/494226/494226/494226.sh
FAILED   - JIT/jit64/opt/cse/hugeSimpleExpr1/hugeSimpleExpr1.sh
```

I guess the reason that we get more failures is this modified script makes more chance to run big tests at the same time. With the as-is script, when we have a big(long-running and using lots of memory) test, it prevents running the next tests.
I'll try run this on x64(or x86)/Linux then share the results - which has a lot more memory.

**Comment by wtgodbe** [comment]
OK, in that case, if we take this change, you should add those tests to https://github.com/dotnet/coreclr/blob/master/tests/testsUnsupportedOutsideWindows.txt

**Comment by CarolEidt** [comment]
> OK, in that case, if we take this change, you should add those tests to https://github.com/dotnet/coreclr/blob/master/tests/testsUnsupportedOutsideWindows.txt

Wouldn't it make more sense to have a category of tests that are unsupported on systems without some threshold of memory, given that this is not really a windows/linux issue but a memory issue?

**Comment by wtgodbe** [comment]
Yeah, that probably makes more sense - then it's just a question of how to differentiate the systems that do & don't meet that threshold

**Comment by hqueue** [comment]
@wateret It seems that all QEMU based ARM CI failed due to timeout after staring the first test. CI use `--sequential` option. Can you take a look at this?

**Comment by wateret** [comment]
Fixed the CI failures. By the way, I'm not sure about how to handle OOM issues.

**Comment by BruceForstall** [comment]
Should there be a "tests that must not be run in parallel due to being large and using lots of resources" file?

Would anyone object to temporarily putting any "failing via OOM" in one of the existing exclusion files and opening an issue to fix that if/when a more appropriate OOM-specific file/solution is written? Then, this change could be merged.

**Comment by wateret** [comment]
I've added the tests that fail with OOM(mentioned above) to `testsUnsupportedOnARM32.txt`. If this temporary change looks OK, I'll raise an issue for handling these tests.

% In addition, I believe that we already have tests that fail with OOM in `testsUnsupportedOnARM32.txt`.

**Pull request merged**
