### PR TITLE
Change just-in-time debugging registry keys.

### PR DESCRIPTION
**Pull request by mikem8361**
From "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AeDebug" to "SOFTWARE\Microsoft\.NETCore\JITDebugging".

### CODE REVIEW

**Comment by noahfalk** [comment]
lgtm

**Comment by mikem8361** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by mikem8361** [comment]
This is the coreclr side of issue https://github.com/dotnet/coreclr/issues/12074.

**Comment by BruceForstall** [comment]
@mikem8361 SuperPMI source is shared between .NET Core and Desktop, so builds for both. Presumably we need it to use the "old" AeDebug keys when built for desktop.

cc @sandreenko @dotnet/jit-contrib

**Comment by mikem8361** [comment]
Sorry about that, I didn’t know.  I probably can find a conditional to basic the keys on.

**Comment by BruceForstall** [comment]
`FEATURE_CORECLR` might be the right one

**Pull request merged**
