### PR TITLE
Disable -Werror for untested compilers

### PR DESCRIPTION
**Pull request by janvorli**
This change causes the -Werror to be used only with compilers that were tested to work.

### CODE REVIEW

**Comment by janvorli** [comment]
cc: @kasper3

**Comment by janvorli** [comment]
Actually, I've forgotten about the different Apple version numbering, I'll update this PR in a minute.

**Comment by kasper3** [comment]
Thank you! 👍 This is something @rofl0r suggested in CoreFX PR as well: https://github.com/dotnet/corefx/pull/27693#issuecomment-370193082, could it be applied in CoreFX too?

**Comment by janvorli** [comment]
@rofl0r we have a build.sh command line option `-ignorewarnings` to disable the `-Werror` in the coreclr repo. It seems to me that it is a well discoverable mean that you can always use if the build fails due to warnings. I still prefer the `-Werror` to be the default on known compilers. It seems we should add `-ignorewarnings` option to the build scripts in corefx and core-setup repos too.

**Comment by jkotas** [comment]
@janvorli I do not think the `-ignorewarnings` command line option is discoverable enough. It is certainly not any kind of standard that folks will immediately go look for.

I think that the out of the box default should be to compile with warnings off.

Compiling with warnings as errors is a form of testing. We should compile with warnings as errors only where we do other kind of testing, like in the CI.

**Comment by janvorli** [comment]
The issue I see with this is that the `-Werror` is a tool for contributors to ensure that their changes are warning free before they create a PR. Turning it off by default means that many of the contributors would just not turn it on and spotting a warning in the loads of build log is a bit unlikely unless you really focus on that. And then they will hit the related errors in the PR, would have to dig through the logs generated by the CI etc. 
I understand the need to be able to build in environments where something out of our control causes warnings, like different runtime libraries, different versions of clang etc. But that seems like much less frequent scenario. That's why it seems to me that the build.sh option to disable the warnings is a better way. 
Actually, build of glibc uses the same way - it enables `-Werror` by default and the `configure` script has an option to disable it. See https://www.gnu.org/software/libc/manual/html_node/Configuring-and-compiling.html (‘--disable-werror’ option).

**Comment by jkotas** [comment]
> And then they will hit the related errors in the PR, would have to dig through the logs generated by the CI etc.

This is the state we are in already. There are many different build and test flavors in CI, as well as additional validations like the JIT formatting checks. All my PRs with non-trivial changes are failing with some combinations of these already. I do not think one more failure path would make a difference.

**Comment by janvorli** [comment]
Ok, I am going to close this PR. I've realized that all my worries can be really theoretical and based on my personal experience only. So let's go the other way - flip the polarity of the build switch so that by default, we don't error on warnings and add the new switch to the CI builds. We'll see how that works. We can always revert the decision if it turns out to be painful.

**Comment by kasper3** [comment]
@janvorli, yesterday I was building clang sources using one lesser version of clang and found tons of warnings being emitted. It seems like they don't use `-Werror` for their own sources. 😄

**Comment by janvorli** [comment]
@kasper3 I've just had a different experience today. While removing dependency on libunwind by including its sources, I've hit couple of warnings that were reported as errors in the libunwind. Two of them were real bugs - one not that bad - a missing declaration of printf. But the other was bad - a function was called with a pointer to a completely different object than the function expects. If they were just warnings, I might have missed them.

**Pull request closed without merging**
