### PR TITLE
Update build clang/llvm/lldb 3.9

### PR DESCRIPTION
**Pull request by mikem8361**
Update build scripts, docs and build pipeline docker images to clang/llvm/lldb 3.9

### CODE REVIEW

**Comment by janvorli** [comment]
@mikem8361 the Ubuntu builds are failing, the log reporting it couldn't find the clang 3.9

**Comment by jashook** [comment]
I am guessing the auto image vms are missing the dependency.  

@mmitche may know more.

**Comment by mmitche** [comment]
@janvorli Yeah, I think 3.5 is the installed version on most VMs.

**Comment by mikem8361** [comment]
I guess I assumed that updating the docke r images was enough. I guess the CI lab Cms need to be updated. Who/How does that happen?


-------- Original message --------

**Comment by am11** [comment]
https://askubuntu.com/a/799998/77893 for reference to install clang39 on Ubuntu 16.04: https://www.ubuntuupdates.org/package/xorg-edgers/xenial/main/base/llvm-toolchain-3.9.

@mikem8361, since 4.0 is also available on many distros: (ubuntu: [llvm-toolchain-xenial-3.9](https://www.ubuntuupdates.org/package/xorg-edgers/xenial/main/base/llvm-toolchain-4.0), alpine: [lldb-dev](https://pkgs.alpinelinux.org/package/edge/testing/armhf/lldb-dev)), should the build be updated to use 4.0 instead?

**Comment by mmitche** [comment]
@mikem8361 We are still using the raw VMs in some places.  The engineering team can do this, but we can't do it immediately.. Can you get decently filled out lists of the images that need updating?

**Comment by mikem8361** [comment]
The question was about getting our CI engineering team to update the VM used to run PR/CI jobs not how to install clang. But thanks for the info.

We have been using lldb 3.9 for a while now and have tested clang/llvm 3.9.  I don’t have a lot of experience with lldb 4.0 yet. It is probably just fine but I don’t want to risk it.

**Comment by mikem8361** [comment]
>>>>.. Can you get decently filled out lists of the images that need updating?

Matt, I’m not sure what you are asking. This is important for dumpling core dump loading and generally simplifying our lldb and lldb plugin story. Is there any way to get it done sooner? Anything I could do?

/cc @lt72, danmosemsft, @mellinoe

**Comment by mmitche** [comment]
@mikem8361 I'm just looking for what needs to be updated.  From that standpoint, looking above there are only a few failed legs on two images. Any idea why centos/etc. didn't fail?

You can help me.  If I give you VMs to update can you help me out and get the right things installed?

**Comment by mellinoe** [comment]
It looks like the CentOS7.1 build, at least, is locating and using clang 3.5.2:

```
Re-run cmake no build system arguments
-- The C compiler identification is Clang 3.5.2
-- The CXX compiler identification is Clang 3.5.2
-- Check for working C compiler: /usr/local/bin/clang
-- Check for working C compiler: /usr/local/bin/clang -- works
```

**Comment by mikem8361** [comment]
I noticed that too even though “3 9” (clang major/minor version) is passed to gen-buildsys-clang.sh. I’m not sure why.

Invoking "/mnt/resource/j/workspace/dotnet_coreclr/master/debug_centos7.1_prtest/src/pal/tools/gen-buildsys-clang.sh" "/mnt/resource/j/workspace/dotnet_coreclr/master/debug_centos7.1_prtest" 3 9 x64 Debug  Include_Tests
Including tests directory in build.
Re-run cmake no build system arguments
-- The C compiler identification is Clang 3.5.2
-- The CXX compiler identification is Clang 3.5.2
-- Check for working C compiler: /usr/local/bin/clang
-- Check for working C compiler: /usr/local/bin/clang -- works

**Comment by mikem8361** [comment]
Most all the Linux VMs: Ubuntu 14.04, 16.04, 16.10 x64 and arm. Debian, Centos and if any “portable build” (RHEL but we are switching to Centos 7) VMs exist.

It looks like alpine, fedora, openSUSE do NOT need to be update (because there isn’t a version of 3.9 for them as far as I can tell).

Yes, I can figure out how to update the VMs. Just point me at them.

**Comment by janvorli** [comment]
As for why asking for clang 3.9 doesn't work and it still uses 3.5, see this code that does the actual detection. As you can see, if the clang with the specified version is not found, but a "clang" and "clang++" without version are found, we use them. 
```sh
# Set up the environment to be used for building with clang.
if command -v "clang-$2.$3" > /dev/null
    then
        export CC="$(command -v clang-$2.$3)"
        export CXX="$(command -v clang++-$2.$3)"
elif command -v "clang$2$3" > /dev/null
    then
        export CC="$(command -v clang$2$3)"
        export CXX="$(command -v clang++$2$3)"
elif command -v clang > /dev/null
    then
        export CC="$(command -v clang)"
        export CXX="$(command -v clang++)"
else
    echo "Unable to find Clang Compiler"
    exit 1
fi
```

**Comment by mikem8361** [comment]
@dotnet-bot test this please

**Comment by mikem8361** [comment]
@dotnet-bot test this please

**Comment by mikem8361** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@mikem8361 This isn't quite done yet.  I'm adding all the images into Jenkins now.

**Comment by mikem8361** [comment]
Let me know when everything is ready. And if I need to merge your changes into my PR.

**Comment by mmitche** [comment]
@dotnet-bot test this please

@mikem8361 ANy idea why those other centos/etc. legs were still passing?

**Comment by mikem8361** [comment]
There is fallback logic in the build scripts (see above post by Jan) that starts with the default version (with my changes is 3.9) and ends up with whatever version the “clang” binary is if it is found.

mikem

**Comment by mikem8361** [comment]
@dotnet-bot test Ubuntu armlb Cross Release Build

**Comment by mikem8361** [comment]
@dotnet-bot test Ubuntu armlb Cross Release Build

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by danmosemsft** [comment]
yay!

**Pull request merged**
