### PR TITLE
Remove the define of FEATURE_INTERPRETER for ARM64

### PR DESCRIPTION
**Pull request by briansull**
This will remove some extra conditional code that is only use to
support the IL bytecode interpreter and will disable the fallback
to the interpreter on ARM64

### CODE REVIEW

**Comment by jkotas** [comment]
LGTM

**Comment by briansull** [comment]
Issue #3756 
@rahku  PTAL
@kyulee1 PTAL

**Comment by rahku** [comment]
Looks good

**Comment by huomm23** [comment]
good

**Pull request merged**
