### PR TITLE
Enable ReJIT on all platforms

### PR DESCRIPTION
**Pull request by mjsabby**
Fixes up the build warnings and errors for ReJIT on Linux and MacOSX.

Next Steps: Get a simple end-to-end test enabled.

### CODE REVIEW

**Comment by mjsabby** [comment]
cc @noahfalk @jkotas

**Comment by mjsabby** [comment]
@dotnet-bot test this please

**Comment by noahfalk** [comment]
These changes look fine, but definitely curious to know if the end-to-end scenario is in a functioning state.

**Comment by mjsabby** [comment]
Yup, soon I should have an update on that. Could you merge this in? Thanks!

**Comment by noahfalk** [comment]
I'd like to know that someone has seen it working first : ) Is there any particular reason we'd want to merge it blind?

**Comment by mjsabby** [comment]
old habit of keeping small changes, and it seemed harmless. I'll try it out, fingers crossed :)

**Comment by mjsabby** [comment]
Short little dump from a ReJIT on a Linux build. I don't have a MacOSX, but I presume it would also be functioning.

BEGIN ReJitManager::Dump: 0x00007FC7D06F8AE0
        Info 0x00007FC7559E3010: State=0x0, Next=0x0000000000000000, Shared=00007FC7559E2FB8, SharedState=0x0
                Module=0x00007FC755767020, Token=0x60009f6
        Info 0x00007FC7559E2D90: State=0x2, Next=0x00007FC7559E1A70, Shared=00007FC7559E1A18, SharedState=0x2
                MD=0x00007FC755986EC8, System.Threading.Monitor.Enter (void *(object,bool&))
        Info 0x00007FC7559E1A70: State=0x0, Next=0x0000000000000000, Shared=00007FC7559E1A18, SharedState=0x2
                Module=0x00007FC755767020, Token=0x6002353
        Info 0x00007FC7559CEE28: State=0x0, Next=0x0000000000000000, Shared=00007FC7559CEDD0, SharedState=0x2
                Module=0x00007FC755767020, Token=0x6002d79
        Info 0x00007FC7559E1630: State=0x2, Next=0x00007FC7559CEE28, Shared=00007FC7559CEDD0, SharedState=0x2
                MD=0x00007FC755988790, System.AppDomain.SetupDomain (instance void *(bool,string,string,string[],string[]))
END   ReJitManager::Dump: 0x00007FC7D06F8AE0

**Comment by noahfalk** [comment]
Cool glad to see it is working!

For others - I made an agreement with @mjsabby that I would help unblock him now if he promised to do some additional testing for different image formats (NGEN/R2R) and make a follow up change that improves the error handling of those cases by April 30th. If something unforeseen comes up that prevents that from happening then we can roll this back to be safe until everything is ready.

Thanks Mukul!

**Comment by mjsabby** [comment]
Current testing:

- [x] Windows JITted Methods
- [x] Windows NGEN Methods
- [ ] Windows R2R Methods
- [x] Linux JITted Methods
- [ ] Linux NGEN Methods
- [ ] Linux R2R Methods

Bugs:

``COR_PRF_USE_PROFILE_IMAGES | COR_PRF_REQUIRE_PROFILE_IMAGE | COR_PRF_DISABLE_ALL_NGEN_IMAGES``

causes the app to not start if used in the profiler.

Next test is Linux NGEN

**Comment by mjsabby** [comment]
Alright, Linux NGEN works, but boy was it hard to get FunctionIDs that are not jitted, needed to use Linux perf to get EIPs and then back to FunctionID.

**Comment by noahfalk** [comment]
Cool, almost there : ) What was the FunctionID needed for? RequestReJIT uses moduleIds and metadata tokens and I thought that was all you were testing?

**Comment by noahfalk** [comment]
Kshama has some working coming that will disable R2R when profiling is enabled so I think we are good with the testing in its current state. Thanks Mukul!

**Pull request merged**
