### PR TITLE
Skip configuration with skipnative option.

### LINKED ISSUE #4022: Build configuration is not skipped when skipnative is presented as argument to build script (Linux)
When trying to build only mscorlib on Linux using the `skipnative` argument to the `build.sh` script, the build configuration step is not skipped (in method `build_coreclr`). Due to the condition in line 99 of `build.sh`, eventprovider is not generated, but is needed later during build configuration.

This results in the following error

```
prajwal@work $ ./build.sh arm skipnative skiptests
...
Config spew
...
-- Performing Test GETPWUID_R_SETS_ERRNO - Success
-- Performing Test FILE_OPS_CHECK_FERROR_OF_PREVIOUS_CALL
-- Performing Test FILE_OPS_CHECK_FERROR_OF_PREVIOUS_CALL - Failed
-- Performing Test UNWIND_CONTEXT_IS_UCONTEXT_T
-- Performing Test UNWIND_CONTEXT_IS_UCONTEXT_T - Success
CMake Error at src/pal/src/CMakeLists.txt:281 (add_subdirectory):
  The source directory

    /home/prajwal/dotnet/coreclr/coreclr/bin/obj/Linux.arm.Debug/Generated/eventprovider does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
```

The Windows build script skips the configuration step if only mscorlib is to be built. Do we need to configure the build even though actual building of native components is skipped later?

The fix would be to move the
```
if [ $__SkipCoreCLR == 1 ]; then
        echo "Skipping CoreCLR build."
        return
fi
```
condition to the beginning of the `build_coreclr` function.

### PR DESCRIPTION
**Pull request by mkborg**
Fixes #4022 as proposed by @prajwal-aithal

### CODE REVIEW

**Comment by jkotas** [comment]
cc @ramarag Was there a reason why the event tracing generation was done unconditionally?

**Comment by ramarag** [comment]
https://github.com/dotnet/coreclr/blob/master/build.sh#L107 needs to be present as it generates etmdummy.h which is used by the runtime even if Eventing is turned off

https://github.com/dotnet/coreclr/blob/master/build.sh#L114 could be turned off if Eventing is not needed, but this information is in the CMake files, and we are just generating project which will never be compiled or linked in

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by jkotas** [comment]
@ramarag Are any of these files used by the managed build? Is there anything important that works today, but won't work anymore if this change is merged?

**Comment by ramarag** [comment]
Managed build should work fine from Eventing perspective with this change

**Comment by prajwal-aithal** [comment]
LGTM

**Pull request merged**
