### PR TITLE
[release/3.1] Change CI to also use macOS-latest to prevent differences in CI and Official build

### PR DESCRIPTION
**Pull request by hoyosjs**

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Review by trylek — APPROVED** [review]
LGTM, thanks Juan!

**Comment by hoyosjs** [comment]
This one fails because of the issue #28220 is trying to address.

**Comment by jeffschwMSFT** [comment]
@safern is it safe to merge these now?

**Review by jeffschwMSFT — APPROVED** [review]
Approved.  This is an infra change and we should treat as tell mode.

**Comment by safern** [comment]
Branch is closed till December 17th after the branding changes are made. Will mark as no merge, thanks for asking!

**Pull request merged**
