### PR TITLE
DictionarySlim backport improvements, retaining more entropy

### PR DESCRIPTION
**Pull request by MarcoRossignoli**
Replacement of https://github.com/dotnet/coreclr/pull/22832 due to CI issue
Analysis of perf/diffs are on old PR

/cc @danmosemsft @jkotas

### CODE REVIEW

**Comment by MarcoRossignoli** [comment]
CI broken unrelated due to https://github.com/dotnet/coreclr/issues/23582

**Comment by MarcoRossignoli** [comment]
@safern sorry for disturb, I cannot re-run CI sure I'm missing something...I read doc again...but no luck.

**Comment by MarcoRossignoli** [comment]
Uh...discrimination :smile:

**Comment by MarcoRossignoli** [comment]
CI issue, it seems related to https://github.com/dotnet/coreclr/issues/23545

**Comment by MarcoRossignoli** [comment]
@danmosemsft I cannot run CI anymore 😭

**Comment by danmosemsft** [comment]
Maybe @safern knows why

**Comment by safern** [comment]
I think the problem is that you're a contributor and not a Collaborator... from speaking to the azure devops team they said that you might need to turn your .net membership from private to public, but I don't know if you can actually do that:

https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops#trigger-builds-using-github-pull-request-comments

I'm sad that triggering and re-running builds became hard and painful for contributors 😢

**Comment by MarcoRossignoli** [comment]
Thank's guys!

**Comment by MarcoRossignoli** [comment]
CI issue related to https://github.com/dotnet/coreclr/issues/23429

**Comment by MarcoRossignoli** [comment]
@safern is this tab https://dev.azure.com/dnceng/public/_build/results?buildId=140379&view=ms.vss-test-web.build-test-results-tab reliable to check which test fails(I hope so, very useful)?
I mean before to go deep to https://mc.dot.net to check the errors.

**Comment by safern** [comment]
> @safern is this tab https://dev.azure.com/dnceng/public/_build/results?buildId=140379&view=ms.vss-test-web.build-test-results-tab reliable to check which test fails(I hope so, very useful)?
I mean before to go deep to https://mc.dot.net to check the errors.

For coreclr, it should be 😄 -- for corefx, we don't put results there yet (we're missing a retry feature), once that feature is available, corefx should move there :smile:

**Comment by MarcoRossignoli** [comment]
execution failed Ubuntu.1804.Arm64.Open-arm64:Checked-no_tiered_compilation https://mc.dot.net/#/user/coreclr-ci/pr~2Fdotnet~2Fcoreclr~2Frefs~2Fpull~2F23591~2Fmerge/test~2Ffunctional~2Fcli~2F/20190403.72/workItem/reflection.Modifiers/wilogs

**Comment by MarcoRossignoli** [comment]
@danmosemsft @jkotas I'm struggling  to obtain green CI, is possible at the moment or there are issue around?

**Comment by MarcoRossignoli** [comment]
unrelated outerloop fail https://mc.dot.net/#/user/coreclr-outerloop/pr~2Fdotnet~2Fcoreclr~2Frefs~2Fpull~2F23591~2Fmerge/test~2Ffunctional~2Fcli~2F/20190406.71/workItem/Loader.classloader/wilogs
other outerloop gcstress/jitminopts/jitstress seems old(3 days ago)

**Comment by danmosemsft** [comment]
@anipik can you please help this get merged? (Check the code matches what was signed off on in the linked original PR)

**Comment by MarcoRossignoli** [comment]
Thank's Dan

**Comment by Anipik** [comment]
@jkotas the code is exactly similar to the code that was approved  in the previous PR. 
The outerloop test failure is not getting repro'd on the local machine. Do you have any context on the failure ?

**Comment by jkotas** [comment]
> The outerloop test failure is not getting repro'd on the local machine. Do you have any context on the failure ?

I have not seen this failure before. It does not look related to this change.

**Comment by danmosemsft** [comment]
I agree these specific failures do not look related.

**Comment by danmosemsft** [comment]
Thanks for your patience @MarcoRossignoli

**Comment by MarcoRossignoli** [comment]
No worries!

**Pull request merged**
