### PR TITLE
Publish native test assets for consumption by performance testing

### PR DESCRIPTION
**Pull request by jkoritzinsky**
The dotnet/performance repo doesn't have any infrastructure to build native assets for the performance testing. Since native test assets are needed to accurately benchmark our interop stack, this PR publishes the native assets (zipped) to the blob feed along with an asset manifest (currently for each platform).

With these manifests and blob feed assets, we can add microbenchmarks in the dotnet/performance repo that use the packaged native assets by having the dotnet/performance build pull down the build manifests and the assets, unzip them, and copy them to the output directory as content.

In this PR, the package contains the native assets for the following Interop scenarios:

- P/Invoke native DLL load
- String marshalling
- General struct marshalling
- LayoutClass marshalling
- SafeHandle marshalling

cc: @dotnet/coreclr-infra

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
I realized that to get these assets actually publishing to BAR, I'd have to make the "Publish To BAR" job depend on the test jobs. As a result, I'm going to wait for #26191 to get in before finishing this up so I don't exasperate #26293 on master.

**Comment by trylek** [comment]
I believe I have addressed all PR feedback and I have a mostly passing run where I manually verified that the previous problems are gone - in particular, R2R test artifact name now properly includes _r2r_. One ARM test run failed but I think this was likely caused by the recent ARM pool maintenance; I retried the job just to be sure. I believe I should be able to merge the change in later today unless I receive any new blocking feedback.

**Comment by trylek** [comment]
OK, the change should be in now (as you probably noticed, Jarret had to roll back my original merge attempt from last Friday as it broke outerloop testing).

https://github.com/dotnet/coreclr/pull/26362

**Comment by jashook** [comment]
@jkoritzinsky any updates on this pr?

**Comment by jkoritzinsky** [comment]
I think given the number of cycles I have available, I'll close this for now and redo it in the consolidated repository.

**Pull request closed without merging**
