### PR TITLE
Eliminate unnecessary float->double for x86 float->int casts in fgMorphCast

### PR DESCRIPTION
**Pull request by saucecontrol**
This resolves https://github.com/dotnet/coreclr/issues/18717

Diffs for x86:

```
Crossgen Diffs for System.Private.CoreLib.dll, framework assemblies for  default jit
Summary:
(Lower is better)
Total bytes of diff: -24 (0.00% of base)
    diff is an improvement.
Top file improvements by size (bytes):
         -16 : System.Private.CoreLib.dasm (0.00% of base)
          -4 : System.Collections.NonGeneric.dasm (-0.12% of base)
          -4 : System.Diagnostics.Tracing.dasm (-0.09% of base)
3 total files with size differences (3 improved, 0 regressed), 126 unchanged.
Top method improvements by size (bytes):
          -4 : System.Collections.NonGeneric.dasm - Queue:.ctor(int,float):this
          -4 : System.Diagnostics.Tracing.dasm - EventCounterGroup:EnableTimer(float):this
          -4 : System.Private.CoreLib.dasm - MathF:Round(float):float
          -4 : System.Private.CoreLib.dasm - Hashtable:.ctor(int,float):this
          -4 : System.Private.CoreLib.dasm - Hashtable:rehash(int):this
6 total methods with size differences (6 improved, 0 regressed), 112246 unchanged.
```

### CODE REVIEW

**Comment by saucecontrol** [comment]
I tried eliminating the `float`->`double` cast for `TYP_LONG` on x86 as well, but that hit an assert in `DecomposeLongs::DecomposeCast`.  Release build passed all tests, and I assume it's safe to skip decomposition since `cvttss2si` works for `long`, but I'm not sure the best way to handle that.

@tannergooding @CarolEidt any tips?

**Comment by mikedn** [comment]
> and I assume it's safe to skip decomposition since cvttss2si works for long, but I'm not sure the best way to handle that.

cvttss2si doesn't work for long on x86, it needs a 64 bit registers and of course, those are available only on x64.

**Comment by saucecontrol** [comment]
> cvttss2si doesn't work for long on x86, it needs a 64 bit registers

Of course it does 🤦‍♂️

**Comment by saucecontrol** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test
@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test
@dotnet-bot test Ubuntu arm Cross Checked no_tiered_compilation_innerloop Build and Test
@dotnet-bot test Windows_NT arm Cross Debug Innerloop Build
@dotnet-bot test Windows_NT arm64 Cross Debug Innerloop Build
@dotnet-bot test Windows_NT x64 Checked CoreFX Tests

**Comment by 4creators** [comment]
[@dotnet/jit-contrib](https://github.com/orgs/dotnet/teams/jit-contrib) Can we merge it?

**Pull request merged**
