### PR TITLE
Update how CoreDisTools is discovered

### LINKED ISSUE #21221: Interop\COM\NativeClients\Primitives do not see files in Core_Root
If you run the test with `complus_gcstress=0xc` you will see:
```
F:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe Primitives.exe
Searching for exe to launch in F:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Interop\COM\NativeClients\Primitives...
Launching 'F:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Interop\COM\NativeClients\Primitives\COMClientPrimitives.exe'...
External disassembler is not available.
LoadLibrary failed for 'F:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Interop\COM\NativeClients\Primitives\coredistools.dll': error 126
```

It happens because the test sees only libraries in its own folders and there is no an external disassembler there. That is why in #19760 there was added `<CLRTestScriptLocalCoreShim>true</CLRTestScriptLocalCoreShim>` to copy `CoreShim.dll` to the test folder.

If you copy the test files to Core_Root and run from there it will work as expected.

@AaronRobinsonMSFT Do you know what is special about this test that it doesn't see Core_Root files as others and why do we need to copy `CoreShim.dll`? 

The simple fix for this issue would be to copy the disassembler as well, but I do not think that it is the right one.

Examples of failures you can see in #21145 and #20460. I will disable this test in gcstress mode for now.

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes #21221

Reverts #21222

cc @sandreenko @davidwrighton

### CODE REVIEW

**Comment by BruceForstall** [comment]
Please trigger some GCStress runs to verify.

**Comment by AaronRobinsonMSFT** [comment]
@dotnet-bot help

**Comment by AaronRobinsonMSFT** [comment]
@dotnet-bot test Windows_NT x64 Checked gcstress0xc

**Comment by AaronRobinsonMSFT** [comment]
@dotnet-bot test Windows_NT x64 Checked gcstress0xc please

**Comment by AaronRobinsonMSFT** [comment]
Seems that the following environment variables are causing failures on Windows_NT x64. An example of the failure is below.
`set COMPlus_TieredCompilation=0`
`set COMPlus_GCStress=0xC`

@BruceForstall any thoughts on this failure? I will try this locally tomorrow, but I really don't see how this is related to my change since my change would cause the test to not even run if it failed.

>GC_API._GC_Collect_Optimized_2_Collect_Optimized_2_._GC_Collect_Optimized_2_Collect_Optimized_2_cmd [FAIL]
>Assert failure(PID 11796 [0x00002e14], Thread: 7812 [0x1e84]): Consistency check failed: Crst Level violation: Can't take level 7 lock CrstReJITDomainTable because you already holding level 3 lock CrstGCCover
>FAILED: false
>
>        CORECLR! CHECK::Trigger + 0x2C4 (0x00007ff8`41bfd174)
>        CORECLR! CrstBase::IsSafeToTake + 0x483 (0x00007ff8`41cc29f7)
>        CORECLR! CrstBase::Enter + 0x224 (0x00007ff8`41cc2304)
>        CORECLR! PublishMethodHolder::PublishMethodHolder + 0xBC (0x00007ff8`4226d280)
>        CORECLR! PrepareCodeConfig::SetNativeCode + 0x40 (0x00007ff8`41f10570)
>        CORECLR! MethodDesc::JitCompileCodeLocked + 0x359 (0x00007ff8`41f0d9d9)
>        CORECLR! MethodDesc::JitCompileCodeLockedEventWrapper + 0x286 (0x00007ff8`41f0dd06)
>        CORECLR! MethodDesc::JitCompileCode + 0x4D2 (0x00007ff8`41f0d59e)
>        CORECLR! MethodDesc::PrepareILBasedCode + 0x110 (0x00007ff8`41f0f3d8)
>        CORECLR! MethodDesc::PrepareCode + 0xFF (0x00007ff8`41f0f087)
>            File: d:\j\workspace\x64_checked_w---aba24ae0\src\vm\crst.cpp Line: 761
>            Image: D:\j\workspace\x64_checked_w---aba24ae0\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe

**Comment by AaronRobinsonMSFT** [comment]
@dotnet-bot test Windows_NT x64 Checked gcstress0xc please

**Comment by AaronRobinsonMSFT** [comment]
I have verified the GCStress failures are the reset of #21288

cc @jkotas

**Comment by AaronRobinsonMSFT** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Innerloop Build please

**Comment by AaronRobinsonMSFT** [comment]
@dotnet-bot test Windows_NT x86 Checked Innerloop Build and Test please

**Comment by AaronRobinsonMSFT** [comment]
@dotnet-bot test Windows_NT arm64 Cross Debug Innerloop Build please

**Comment by AaronRobinsonMSFT** [comment]
@dotnet-bot test Windows_NT x64 Checked gcstress0xc please

**Comment by AaronRobinsonMSFT** [comment]
The current failures in the GCStress run appear to be existing in other runs as well. I am planning on merging this PR if there are no concerns.

cc @davidwrighton @sandreenko @adityamandaleeka

**Pull request merged**
