### PR TITLE
Revert ResourceManager change to unblock uap tests

### PR DESCRIPTION
**Pull request by safern**
cc: @jkotas @danmosemsft

### CODE REVIEW

**Comment by jkotas** [comment]
cc @tarekgh

**Comment by tarekgh** [comment]
I am not sure what is the plan here? looks to me reverting this change will help run the tests but it will bring back the regression fixing it. I think we should address this differently.

**Comment by tarekgh** [comment]
never mind I didn't see the https://github.com/dotnet/coreclr/issues/12178 so I am fine with the change here.

**Comment by safern** [comment]
Closing as we are going to fix the test infra.

**Comment by safern** [comment]
Reopening PR to unblock people that is working on fixing the tests.

**Comment by jkotas** [comment]
@dotnet-bot test Tizen armel Cross Release Build  please

**Comment by danmosemsft** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test (@weshaggard build tools restore hung)

**Comment by safern** [comment]
> @dotnet-bot test OSX10.12 x64 Checked Build and Test (@weshaggard build tools restore hung)

Seems like it hung again but I don't see the buildtools restore output.

Should we merge?

**Comment by danmosemsft** [comment]
Merging to unblock testing.

**Pull request merged**
