### PR TITLE
Make EventPipeBufferManager::m_lock a leaf crst

### PR DESCRIPTION
**Pull request by cshung**
This change is a preparatory change for moving forward with #23120 to fix issue #22502.
As the changes in the referenced pull request indicates, properly fixing the race condition requires nesting the locks, and therefore the outer one cannot be a spin lock (as SpinLock are meant to be leaf lock and not support nesting)

The lock level of the new critical section becomes a problem, as of now, the code that the critical section protects is callable through almost everywhere in the runtime. Properly analyze all possible locks that could be taken before this critical section is very tedious, if not impossible. It is much better to assert that this lock is leaf, nothing else (except SpinLock of course) could be taken after this critical section offer a much better protection.

Therefore I modified the CrstTypeTool to support the concept of leaf lock, and make EventPipeBufferManager a leaf lock. The change will allows us to detect lock violation earlier and also make sure we will have an early assert if we every violate the rule.

### CODE REVIEW

**Comment by kouvel** [comment]
Haven't looked at the details yet, but there is a crst type CrstLeafLock, which does not allow other crsts to be acquired while the leaf lock is held. I'm not sure but a CrstLeafLock may still slow SpinLocks to be acquired under them, perhaps because I assume SpinLocks don't participate in lock ordering asserts other than to disallow other locks of any type to be acquired under a SpinLock. So I'm curious why CrstLeafLock would not work in this case.

**Comment by jkotas** [comment]
Agree with Kount. We should avoid adding redundant leaf lock concept.

**Comment by noahfalk** [comment]
@cshung - If the CrstLeafLock doesn't pan out, I think we've also got options to structure things so that the locks don't nest, or to use InterlockedExchange instead. If you aren't seeing any solutions that are < ~50 lines of code changed I'm happy to give it a closer look. Maybe I'm just deluding myself, but I wasn't expecting we'd need to bring in a large hammer on this one : )

**Comment by cshung** [comment]
I was not aware of CrstLeafLock, and I believe [CrstLeafLock](https://github.com/dotnet/coreclr/blob/9c4d496071c2ffdc5a8793835694d1a8ac267522/src/inc/crsttypes.h#L255) is a lie in the sense that it isn't really a leaf lock. It looks like [CrstLoaderHeap](https://github.com/dotnet/coreclr/blob/9c4d496071c2ffdc5a8793835694d1a8ac267522/src/inc/crsttypes.h#L259) is just as leaf. This is leading to assert, yielding the CrstLeafLock unusable, as is.

I think we can modify my change a bit to accomodate this concept.

**Comment by cshung** [comment]
This is obsolete, closed.

**Pull request closed without merging**
