### PR TITLE
Invoke 'copy_test_native_bin_to_test_root' inside 'create_core_overlay'

### LINKED ISSUE #5675: runtest.sh requires --testNativeBinDir even if --coreOverlayDir is specified
``runtest.sh`` currently does not support the reuse of previously constructed overaies.

When I run ``tests/runtest.sh --verbose --testRootDir=../ut --coreOverlayDir=../dotnet-latest/Linux.x64.Debug`` (where ../dotnet-latest/Linux.x64.Debug is previosly constructed core overlay which contains all the native binaries) to run all the tests with the specified overlay, I got the following error message:
```
$ tests/runtest.sh --verbose --testRootDir=../ut --coreOverlayDir=../dotnet-latest/Linux.x64.Debug
cp: target ‘/bin/znew’ is not a directory
Skipping crossgen of FX assemblies.
--testNativeBinDir is required.
```

### PR DESCRIPTION
**Pull request by parjong**
This commit tries to fix #5675.

### CODE REVIEW

**Comment by parjong** [comment]
\CC @wateret @jyoungyun

**Comment by adityamandaleeka** [comment]
@wtgodbe Can you take a look at this?

**Comment by parjong** [comment]
@jkotas @adityamandaleeka @wtgodbe Could you please take a look? If it is not desired, I would like to close this PR.

**Comment by parjong** [comment]
@dotnet-bot help

**Comment by parjong** [comment]
@dotnet-bot test this please

**Pull request merged**
