### PR TITLE
[EventPipe] Fix linker warning on Debug/Checked build and unlink Unix Domain Socket

### PR DESCRIPTION
**Pull request by jorive**
- Attempt to close-behind unix domain socket and repurpose LF_REMOTING facility.
  - On shutdown, attempt to unlink the bound socket so it can be removed from the file system when the last reference to it it closed.
  - Rename unused LF_REMOTING to LF_DIAGNOSTICS_PORT. This new flag will be used by the diagnostic server stress log calls.
- Fix `libcmtd.lib(initializers.obj) : warning LNK4098: defaultlib 'libcmt.lib' conflicts with use of other libs; use /NODEFAULTLIB:library [S:\github.com\jorive\coreclr\bin\obj\Windows_NT.x64.Checked\src\dlls\mscoree\coreclr\coreclr.vcxproj]`
- Move some preprocessors and includes around.

Fixes: https://github.com/dotnet/coreclr/issues/23324

### CODE REVIEW

**Comment by jorive** [comment]
@dotnet-bot test this please

**Comment by jorive** [comment]
@dotnet/dnceng Is `ci.dot.net` down?

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
No it's not..or at least I don't think it is

**Comment by jorive** [comment]
I'm getting **HTTP ERROR 404** when I try to click in any of the Details [link](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_windows_nt_innerloop_prtest/13692/).
```html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /job/dotnet_coreclr/job/master/job/x64_checked_windows_nt_innerloop_prtest/13692/. Reason:
<pre>    Not Found</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/>

</body>
</html>
```

**Comment by MattGal** [comment]
That's weird, perhaps it means https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/checked_windows_nt/11664/ ?

**Comment by jorive** [comment]
@dotnet-bot test this please

**Comment by mikem8361** [comment]
LGTM.

**Comment by BruceForstall** [comment]
I think the issue is https://github.com/dotnet/coreclr/pull/23287, where we disabled innerloop Jenkins jobs, but unfortunately also deleted the jobs, so history is gone.

**Comment by BruceForstall** [comment]
I can see how removing `-MT` would fix the linker warning, but it's still not clear to me why the linker warning appeared.

**Comment by noahfalk** [comment]
@BruceForstall - I agree with you that its puzzling this wasn't a pre-existing issue. My best guess is that when Jose added his new code it caused some portion of the debug libc code to be referenced that was not referenced before, and this new portion triggered the linker to spot the conflict or perhaps exceeded the bounds of some previous filtering that was already in place. It isn't a very satisfying answer to me, but if the warning is gone I figured this was one of those mysteries we'll leave unsolved.

**Comment by jorive** [comment]
@dotnet-bot help

**Comment by jorive** [comment]
@dotnet-bot test CentOS7.1 x64 Checked Innerloop Build and Test
@dotnet-bot test CentOS7.1 x64 Debug Innerloop Build
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test
@dotnet-bot test Ubuntu arm Cross Checked no_tiered_compilation_innerloop Build and Test
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test (Jit - TieredCompilation=0)
@dotnet-bot test Windows_NT x64 Checked Innerloop Build and Test
@dotnet-bot test Windows_NT x86 Checked Innerloop Build and Test

**Comment by jorive** [comment]
@BruceForstall As mentioned above, it's still nuclear how this was not triggered before my changes. Would you prefer if I spend more time getting a concrete answer?
w.r.t. the leg errors, what should I do? It finished green (minus the WIP leg) before I pushed my last commit that removed the commented line.

**Comment by jorive** [comment]
After #23287, is it expected for this legs to fail, disappear, or not run? Can the Jenkins failed legs be ignored?
/cc @mmitche @jashook

**Comment by jorive** [comment]
I'll close this PR and attempt creating a new one.

**Comment by BruceForstall** [comment]
> @BruceForstall As mentioned above, it's still unclear how this was not triggered before my changes. Would you prefer if I spend more time getting a concrete answer?

I guess I'll go with Noah's answer that it looks to fix the problem, and if there are any other such conflicts we'll see new/additional/different warnings. Presumably it's ok to use the non-static link runtime.

**Pull request closed without merging**
