### PR TITLE
Add new IPC message for out of context unwinding

### PR DESCRIPTION
**Pull request by mikem8361**
Used to get the full context for HelperMethodFrames.

### CODE REVIEW

**Comment by mikem8361** [comment]
@janvorli, @ZhichengZhu could you guys take a look?
@tzwlai if you have time.

**Comment by janvorli** [comment]
LGTM

**Comment by sergiy-k** [comment]
LGTM

**Comment by tzwlai** [comment]
A bit late, but LGTM too.  Thanks Mike!

**Pull request merged**
