### PR TITLE
Remove vc-runtime package dependency

### PR DESCRIPTION
**Pull request by echesakovMSFT**
It doesn't look that we need this dependency anymore.
At least, testing on ARM/ARM64 Helix machines succeeded with this change.

<s>See if Jenkins machines are happy with this change.</s> Pri1 ARM/ARM64 tests succeeded

### CODE REVIEW

**Comment by echesakovMSFT** [comment]
@dotnet-bot help

**Comment by echesakovMSFT** [comment]
@dotnet-bot test Windows_NT arm Cross Checked normal Build and Test
@dotnet-bot test Windows_NT arm Cross Release normal Build and Test

@dotnet-bot test Windows_NT arm64 Cross Checked normal Build and Test
@dotnet-bot test Windows_NT arm64 Cross Release normal Build and Test

**Comment by danmosemsft** [comment]
@dotnet-bot test this please (fixed tests)

**Comment by echesakovMSFT** [comment]
@dotnet-bot test Ubuntu x64 Checked CoreFX Tests
@dotnet-bot test Windows_NT x64 Checked CoreFX Tests 
@dotnet-bot test Windows_NT x64 Release CoreFX Tests

**Pull request merged**
