### PR TITLE
Point to V2 myget feed while v3 gets fixed

### PR DESCRIPTION
**Pull request by wtgodbe**
In conjunction with https://github.com/dotnet/corefx/pull/16226

CC @MattGal @gkhanna79 @joperezr @stephentoub

### CODE REVIEW

**Comment by gkhanna79** [comment]
I see few other places that maybe affected as well. PTAL at https://github.com/dotnet/coreclr/search?utf8=%E2%9C%93&q=myget.org

**Comment by wtgodbe** [comment]
@gkhanna79 updated

**Comment by mmitche** [comment]
Closing as moving to v2 brings down myget.

**Comment by xavierdecoster** [comment]
The NuGet v3 endpoints on dotnet.myget.org should be available again. We are still working on a few mitigation's of this issue so very short intermittent hiccups may still occur. Please do stay on the v3 endpoints for performance reasons.

**Comment by mmitche** [comment]
@xavierdecoster Looks like everything is good now.

**Pull request closed without merging**
