### PR TITLE
Publish packages into folders named for their configuration groups

### PR DESCRIPTION
**Pull request by wtgodbe**

### CODE REVIEW

**Comment by wtgodbe** [comment]
@jhendrixMSFT @gkhanna79 PTAL

**Comment by gkhanna79** [comment]
LGTM. We should take this to Release/RTM branch as well.

**Comment by jhendrixMSFT** [comment]
LGTM

**Comment by wtgodbe** [comment]
@dotnet-bot test this please

**Comment by wtgodbe** [comment]
Looks like the build breaks are due to the buildtools update - any thoughts on this one @jhendrixMSFT? I'll probably have to look at this after the weekend, I have to hit the road very soon (camping this weekend)

**Comment by jhendrixMSFT** [comment]
@wtgodbe I'm seeing build breaks in CoreFX as well although they manifest different.  I'm currently investigating.

**Comment by jhendrixMSFT** [comment]
I think a new CLI is in order.  Please see https://github.com/dotnet/coreclr/pull/5290 where build tools is bumped to a recent version along with an updated CLI.  I think once that PR is merged you can rebase on top of it and resubmit.

**Comment by joperezr** [comment]
I'll merge my PR as soon as all CI finishes green.

**Pull request closed without merging**
