### PR TITLE
build.sh: fall back to portable Linux when Linux host has unknown rid

### PR DESCRIPTION
**Pull request by tmds**

### CODE REVIEW

**Comment by tmds** [comment]
CC @ellismg

**Comment by janvorli** [comment]
There is a small issue - the portable tools that we use don't have the fix for openssl on debian 9 (dotnet/corefx#19070), which means the build now fails on Debian 9 or Ubuntu 17.04 unless you explicitly add options to disable all managed parts of the build.
@ellismg how complicated would it be to move to tools version that already has that fix now?

**Comment by ellismg** [comment]
Is `initHostDistroRid()` not needed anymore?  It looks like the variables it sets up are never consumed anymore.  Can we just delete it?

> @ellismg how complicated would it be to move to tools version that already has that fix now?

It should be as simple as updating the `DotNetCLIVersion.txt` file in the root of the repository to a dotnet that has the fix.

**Comment by tmds** [comment]
@ellismg @janvorli I updated the PR to invert the logic. Instead of maintaining a list of supported, it now contains a list of unsupported RIDs.

**Comment by janvorli** [comment]
@tmds I don't understand the motivation for inverting the polarity of the distro list. It made sense before, since the supported distros are the ones for which we have the tools package  on our servers. Flipping the polarity means that for the distros that are not listed there, we would fail to download the tools, since there is no such file for their RID.

**Comment by tmds** [comment]
@janvorli I was assuming the same thing but then after @ellismg 's comment I had a closer look in the init-tools.sh script and saw it downloads the generic linux package.
The host rid in build.sh is only used to check if it can compile the managed bits (isMSBuildOnNETCoreSupported). So now I am changing that function so this defaults to true for unknown rids.

**Comment by janvorli** [comment]
@tmds ah, I didn't know that the tools were already modified that way. Makes sense then.

**Comment by tmds** [comment]
@ellismg if this is ok for you too, can you merge the PR?

**Pull request merged**
