### PR TITLE
[WIP] Delay long mul/div helper creation until decomposition

### PR DESCRIPTION
**Pull request by mikedn**

### CODE REVIEW

**Comment by mikedn** [comment]
@dotnet/jit-contrib Any opinions about delaying DIV/MUL helper creation until decomposition/lowering?

The advantage is that DIV/MUL related optimizations will work consistently on both 32 bit and 64 bit targets. For example, on 64 bit targets the JIT eliminates `long_x / 1` but on 32 bit targets we end up with a helper call.

But this requires generating calls in decomposition/lowering and that comes with a large amount of baggage - `fgMorphArgs`, `gtSetEvalOrder` and `fgSetTreeSeq`. I see that shift decomposition already does this and it seems to work fine. But it still seems a bit scary that `fgMorphArgs` affect not only the call itself but all its argument trees.

**Comment by CarolEidt** [comment]
This LGTM - I think it's a good idea to postpone this - it's arguably very target-specific. I'd also like to get another review from @dotnet/jit-contrib.
This will look even better once @BruceForstall removes the `LEGACY_BACKEND` code.
As for the baggage that comes with doing this during `Lowering`, I think we've already bought off on that. Some of that is pretty fundamental (we don't want to sprinkle all knowledge of just how argumetns should be structured all over the place). I have started working on `fgMorphArgs()` - for now I'm just trying to remove some of the special casing for Unix/x64, but longer term I hope to refactor it so that it is cleaner - and clearer exactly what it's doing when.

**Comment by sdmaclea** [comment]
Could we do this more generically to solve #8648

**Comment by mikedn** [comment]
@CarolEidt Thanks but this is still WIP IMO due to the way I'm calling fgMorphArgs - by creating dummy 0 trees and then replacing them with the original LIR nodes. The "right" way is probably to do what we do in shift decomposition - just introduce new local variables for helper call arguments. Introducing new local variables comes with its own set of issues so I was looking for a way to avoid that but I have no idea if fgMorphArgs won't do different things depending on the arg node operator. Are you sure it works correctly with these fake 0 trees?

**Comment by mikedn** [comment]
@sdmaclea Hmm, that issue if very different and I'm not sure this has any impact on that. In fact, I wonder if this won't make it worse, need to check that. It is possible that the early introduction of helper calls might prevent the wrong optimization from kicking in and now if the helper calls are gone, well, the optimization will happen in more cases.

**Comment by CarolEidt** [comment]
> I have no idea if fgMorphArgs won't do different things depending on the arg node operator. Are you sure it works correctly with these fake 0 trees?

I'm definitely not *sure*, but I would expect it to work correctly for scalar node types. It would be really nice to avoid creating lclVars, but I agree that it would be more conservatively correct.

**Comment by mikedn** [comment]
I tried to see how the lclvars version would work and remember why I avoided it, it's a bit more than "because it's not nice to create lclvars". The lclvars approach works well for the shift helper call but that one is special, it's signature is something like `(int lo, int hi, int count)` and not `(long value, int count)`. On the other hand, the div/mul helper calls have `long` parameters so you either need to create `long` lclvars or "pack" 2 `int` vars using `GT_LONG`. In the first case we'll probably need to decompose those new `long` lclvars and in the second case we end up with a `GT_LONG` in morph, a new situation.

Considering how simple these helper's ABI is I wonder if it wouldn't be simpler and safer to produce the necessary call IR directly, without going through morph.

**Comment by mikedn** [comment]
I starred at this issue a bit more and it's a rather interesting case. As far as I can tell the order in which arguments are pushed is not given by the call arg list order nor by the arg info order, it's simply the order of the nodes that produce the argument values. 

This makes it non trivial to avoid introducing new lclvars in the general case. You may need to move arg nodes around and that can be complicated (e.g. make sure you don't swap `ADD_LO` and `ADD_HI`).

It does seem to work fine in the specific case of decomposition because of the `GT_LONG` nodes, we can move these without risk. But not without CQ consequences, we go from
```asm
       8B4510       mov      eax, dword ptr [ebp+10H]
       8B5514       mov      edx, dword ptr [ebp+14H]
       83C001       add      eax, 1
       83D200       adc      edx, 0
       52           push     edx
       50           push     eax
       8B4508       mov      eax, dword ptr [ebp+08H]
       8B550C       mov      edx, dword ptr [ebp+0CH]
       83E802       sub      eax, 2
       83DA00       sbb      edx, 0
       52           push     edx
       50           push     eax
       E899EC7552   call     CORINFO_HELP_LDIV
```
to 
```asm
       8B4510       mov      eax, dword ptr [ebp+10H]
       8B5514       mov      edx, dword ptr [ebp+14H]
       83C001       add      eax, 1
       83D200       adc      edx, 0
       8B4D08       mov      ecx, dword ptr [ebp+08H]
       8B750C       mov      esi, dword ptr [ebp+0CH]
       83E902       sub      ecx, 2
       83DE00       sbb      esi, 0
       52           push     edx
       50           push     eax
       56           push     esi
       51           push     ecx
       E898EC1353   call     CORINFO_HELP_LDIV
```
So to do this it right we need to either 
* be able to move nodes around more effectively during decomposition/lowering 
* teach `gtSetEvalOrder` to treat these nodes as calls and order them properly

And then I start wondering why the evaluation order is decided so early, it would seem that it shouldn't be necessary to figure out the evaluation order until Lowering or LSRA.

Another aspect of these helper calls is that they could be treated as having 4 INT parameters instead of 2 LONG ones. In some cases (when the lo and hi parts can be evaluated independently) this would reduce the number of necessary registers:
```asm
      8B4510       mov      eax, dword ptr [ebp+10H]
       83C001       xor    eax, 2
       50           push     eax
       8B5514       mov      eax, dword ptr [ebp+14H]
       83D200       xor      eax, 4
       52           push     eax
       8B4508       mov      eax, dword ptr [ebp+08H]
       83E802       xor      eax, 4
       50           push     eax
       8B550C       mov      eax, dword ptr [ebp+0CH]
       83DA00       xor      eax, 2
       52           push     eax
       E899EC7552   call     CORINFO_HELP_LDIV
```
I kind of doubt that such an improvement would be worthwhile but this does seem to indicate that the current approach of setting the evaluation order very early is not ideal.

**Comment by karelz** [comment]
No update for 1.5 year. I recommend to close the PR until it is ready to be worked on again ... thoughts @mikedn ?

**Comment by mikedn** [comment]
Right, I'm not going to work on this in the near future, the way calls are handled in the JIT is too horrible to do this safely at the moment. Maybe I'll get back to this if I can improve that.

**Pull request closed without merging**
