### PR TITLE
JIT: modify how jit determines when to update a type

### LINKED ISSUE #22583: JIT: type equivalence leads to an assert when tracking class types
Reproing an issue that came up in desktop testing.

Compile the following to a base library (say base.dll)
```C#
using System;
using System.Runtime.InteropServices;

[assembly:Guid("a95d54f0-5e7c-46e0-a15f-59ab08d41c38")]
[assembly:ImportedFromTypeLib("test")]

public delegate int XD();
```
and then link this into a library (lib.dll)
```C#
// compile via  /t:library lib.cs /l:base.dll
using System;

public class Lib
{
    public static int F() => 33;
    public static XD GetDelegate() => F;
}
```
and separately into an executable that refers to both:
```C#
// compile via /o+ /debug- ex.cs /r:lib.dll /l:base.dll
using System;
using System.Runtime.InteropServices;

class X
{
    static int F() => 3;
    public static int Main()
    {
        XD x = F;
        XD y = Lib.GetDelegate();
        return x() + y() + 64;
    }
}
```
Then a checked jit at Tier1 (or with tiering disabled) will assert in `mergeClasses` jitting `X.Main`:
```
Assert failure(PID 27240 [0x00006a68], Thread: 26064 [0x65d0]): merged == reflexive

CORECLR! CEEInfo::mergeClasses + 0x264 (0x00007ffc`f53751f4)
CLRJIT! Compiler::lvaUpdateClass + 0x154 (0x00007ffd`031c45ac)
CLRJIT! Compiler::lvaUpdateClass + 0x59 (0x00007ffd`031c476d)
CLRJIT! Compiler::impImportBlockCode + 0x13EC (0x00007ffd`03191dc0)
```
The issue is that there are two different delegate types here -- `Lib.XD` and `X.XD` -- that are type equivalent, and so the result of `mergeClasses` is order dependent.

This doesn't cause any codegen issues in release builds because delegates are largely opaque to the jit. So one possible fix is to relax the assertion checks in `mergeClasses` for types with type equivalence.

It may be possible to find a similar example where two non-delegate classes are type equivalent, the jit's type tracking gets confused or is mislead, and optimizations misfire. Still working to see if I can arrange this somehow. It looks like perhaps one cannot expose a class type from the base library, and so we would not see other types assigned across equivalent types, so maybe delegates are a special case?

cc @dotnet/jit-contrib @jkotas 

I remember Jan you warned me that there might be issues in `mergeClasses`...

### PR DESCRIPTION
**Pull request by AndyAyersMS**
For single-def locals, the type of a reference seen at the assignment to the
local may be a more specific type than the local's declared type. If so the jit
would prefer to use the assignment type to describe the local's value, as this
will lead to better optimization. For instance in
```
    object x = "a string";  // only assignment to x
```
the jit can optimize better if it models the type of `x` as `string`.

Instead of relying on `mergeClasses` plus some jit-side screening to decide if
the assignment type is a more specific type, implement a new jit interface
method `isMoreSpecificType` that tries to answer this question more directly.

Added a test case with type equivalence that hit asserts.

Closes #22583.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib @jkotas 

No diffs either in crossgen or PMI.

**Comment by AndyAyersMS** [comment]
Newly added test is failing on non-windows test runs:
```
Unhandled Exception: System.MissingMethodException: Method not found: 'XD Lib.GetDelegate()'.
```
Seems like the test is not getting set up properly ...?

**Comment by AndyAyersMS** [comment]
Or maybe type equivalence is windows-only?
```
;; clrdefinitions.cmake

if (WIN32)
    add_definitions(-DFEATURE_TYPEEQUIVALENCE)
endif(WIN32)
```

**Comment by jkotas** [comment]
> Or maybe type equivalence is windows-only?

Correct. It is really only for COM.

**Comment by AndyAyersMS** [comment]
CoreFx failures are known, #22625.

**Comment by AndyAyersMS** [comment]
Odd error in [arm64 cross checked](https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_checked_windows_nt_innerloop_flow_prtest/3316/) run:
```
C:\j\workspace\arm64_cross_c---5cf2e9f1\tests\dir.props(111,3): error MSB4020: The value "" of the "Project" attribute in element <Import> is invalid. [C:\j\workspace\arm64_cross_c---5cf2e9f1\tests\runtest.proj]
```
Seems to have hit the past few CI runs. Should be unrelated.

**Comment by AndyAyersMS** [comment]
Similar odd failure for the [arm cross checked run](https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_windows_nt_innerloop_flow_prtest/3285/).

@RussKeldorph @echesakovMSFT any ideas what might have caused this? Looks like it started sometime around 8am today.

**Comment by RussKeldorph** [comment]
msbuild is complaining about an import of $(RoslynPropsFile) so I'm guessing #22452.  @tannergooding can you take a look?

**Comment by tannergooding** [comment]
Looking. It seems to only be impacting arm jobs at first glance.

**Comment by tannergooding** [comment]
Looks like it might also be specific to `Windows_NT arm`, which doesn't appear to have been triggered for my pr.

**Pull request merged**
