### PR TITLE
Fix hardware exception handling in native code on BSD

### PR DESCRIPTION
**Pull request by janvorli**
There is a problem with hardware exception handling when the exception
happens in native code and it is under the HardwareExceptionHolder on
FreeBSD and NetBSD. The problem was that the C++ unwinder was unable
to cross the signal trampoline.
This change fixes the problem by throwing the PAL_SEHException from
the context of the hardware exception itself rather than from the
signal handler.
Since it uses the same code as we were using for StartUnwindingNativeFrames
in CoreCLR before, I have moved that stuff to PAL and let both CoreCLR and
the signal handlers use it too.
At the same time, I have reenabled the paltest_pal_sxs_test1 for FreeBSD and
NetBSD, since it now works.

### CODE REVIEW

**Comment by janvorli** [comment]
@krytarowski FYI

**Comment by janvorli** [comment]
@adityamandaleeka can you take a look please?

**Comment by janvorli** [comment]
CC: @mikem8361

**Comment by adityamandaleeka** [comment]
LGTM

**Comment by krytarowski** [comment]
Thank you!

**Pull request merged**
