### PR TITLE
Make the COM activation check for ProgID generation.

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes https://github.com/dotnet/corefx/issues/30927

/cc @hughbe @jkoritzinsky

### CODE REVIEW

**Comment by jkotas** [comment]
Does this additional error handling adds any value?

**Comment by AaronRobinsonMSFT** [comment]
>Does this additional error handling add any value?

@jkotas This is merely to match the semantics of .NET Framework.

**Comment by AaronRobinsonMSFT** [comment]
Is there concern about adding it?

**Comment by jkotas** [comment]
- This is technically a .NET Core 3 -> .NET 5 breaking change. There may be cases where folks call this in .NET Core 3 app today and it does not throw exception. Their app will break once they switch to .NET 5.
- There are many places where we throw less exceptions than in .NET Framework. The default rule is that throwing less exceptions is compatible change.
- This error handling is best effort anyway. It does not guarantee that this ProgID is actually going to work when you pass it to COM.
- We are officially done with .NET Framework porting project: https://github.com/dotnet/announcements/issues/130.

**Comment by AaronRobinsonMSFT** [comment]
>We are officially done with .NET Framework porting project: dotnet/announcements#130.

@jkotas Sounds good. A bug still existed so I figured I would handle some of the low hanging fruit, but in this case I can close the issue.

**Comment by jkotas** [comment]
Agree. It would be best to close this as won't fix.

**Pull request closed without merging**
