### PR TITLE
Update API behavior to align with Mono

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes: https://github.com/dotnet/coreclr/issues/27754

/cc @scottj1s @jkoritzinsky

### CODE REVIEW

**Comment by jkotas** [comment]
I do not think it is a good idea to encourage more uses of these `Marshal.*` APIs. These APIs are slow and a pit of failure. Instead, I think we should be encouraging use of C# `unmanaged` constrain for this scenario (interop + generics).

If you disagree and you would like to go ahead with this:
- It needs a pile of tests, for both positive and negative cases.
- The other variants (e.g. StructureToPtr) needs to get the same fix for consistency

**Comment by jkotas** [comment]
Test failures:
```
  Starting:    System.Runtime.InteropServices.Tests (parallel test collections = on, max threads = 2)

Assert failure(PID 10147 [0x000027a3], Thread: 10305 [0x2841]): (curSP <= m_pFrame && m_pFrame < m_CacheStackBase) || m_pFrame == (Frame*) -1
    File: /__w/1/s/src/vm/threads.h Line: 1853
    Image: /home/helixbot/work/5931ddb3-319b-4032-943f-4e34e0f05221/Payload/dotnet

Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.10147.dmp
```

**Comment by AaronRobinsonMSFT** [comment]
>I think we should be encouraging use of C# unmanaged constrain for this scenario (interop + generics).

@jkotas Definitely not against trying another way here. I was only trying to match the behavior of Mono here and see what fell out. Can you provide a concrete example of what you are proposing?

The fact that Linux is failing with such a trivial change seems to imply there is something fishy in general with other things. I don't see how being more permissive in this area would cause Frame errors in the way the assert above is implying. I am sure there could be negative tests here, but how that would cause this assert to fire seems like a really bad sign that something else is the real issue.

**Comment by jkotas** [comment]
> Can you provide a concrete example of what you are proposing?

- Leave the API behavior as is in CoreCLR. Consider fixing Mono to match.
- Recommend use of unsafe code and C# unmanaged constrain for the interop on generics scenario. For example:

```csharp
    // RECOMMENDED, works fine today, fast
    Vector64<int> v = *(Vector64<int>*)p;

    // NOT RECOMMENDED, does not work today, order of magniture slower than above
    Vector64<int> v = (Vector64<int>)Marshal.PtrToStructure(p, typeof(Vector64<int>));`
```

**Comment by jkotas** [comment]
> I am sure there could be negative tests here

The API would need to throw exception for structs that cannot be marshaled. This exception throwing behavior would need to be tested -> negative test.

> how that would cause this assert to fire seems like a really bad sign that something else is the real issue.

Yes, there are likely number of fixes required to make the built-in interop marshalers to deal with generics. It is very likely that you would come to conclusion that "blittable/unmanaged types are the only ones that this can ever work well. But these types can be dealt with using the alternative pattern I have suggested above in better way.

**Comment by AaronRobinsonMSFT** [comment]
>It is very likely that you would come to conclusion that "blittable/unmanaged types are the only ones that this can ever work well.

That is all I wanted to support here. I had no plan on support anything other than blittable instantiated generic structs.

**Comment by AaronRobinsonMSFT** [comment]
Closing per @jkotas's suggested preferred workflow: https://github.com/dotnet/coreclr/pull/27840#issuecomment-553105457

**Comment by Scottj1s** [comment]
FYI - this workaround doesn't help xlang, which is using PtrToStructure on vtables, which are not blittable, converting function pointers to delegates.  Ideally, I would just marshal those function pointers as IntPtr and invoke them via calli, but that's not an option with the current C# compiler either.

**Comment by AaronRobinsonMSFT** [comment]
>which are not blittable

Hmmmm. That is odd. I will need to look into how this was working in the first place. This must have been going down a path I didn't anticipate.

**Comment by jkotas** [comment]
> > > PtrToStructure on vtables, which are not blittable, converting function pointers to delegates
> > which are not blittable
> Hmmmm. That is odd.

Delegates are not blittable. There is nothing odd about it.

We are going to have proper function pointers in .NET 5 / C# 9 that are superior to using delegates. Are you going to be able to use function pointers for this?

The originally proposed StructureToPtr change would be available in .NET 5+ only, so it would depend on .NET 5 as well.

**Comment by AaronRobinsonMSFT** [comment]
>Delegates are not blittable. There is nothing odd about it.

That wasn't what was odd to me. I was looking at some other area when proposing this and didn't see the `Delegate` issue.

>We are going to have proper function pointers in .NET 5 / C# 9 that are superior to using delegates. Are you going to be able to use function pointers for this?

Yep. Scott and I spoke offline and are talking to the Roslyn team about mitigating the issue until we get function pointers.

**Pull request closed without merging**
