### PR TITLE
Vectorize Array.{Last}IndexOf<T>(...) for byte and char

### PR DESCRIPTION
**Pull request by benaadams**
For
```csharp
// where T : byte, char
Array.IndexOf<T>(T[] array, T value)
Array.IndexOf<T>(T[] array, T value, int startIndex)
Array.IndexOf<T>(T[] array, T value, int startIndex, int count)
```

### CODE REVIEW

**Comment by benaadams** [comment]
Byte should currently go via 

`EqualityComparer<byte>.Default` => `ByteEqualityComparer` => `ReadOnlySpan` => `SpanHelpers.IndexOf`

So its just short circuiting some of that

Char currently tests `char` by `char`

**Comment by stephentoub** [comment]
LGTM. Perf results for small and large arrays?

**Comment by jkotas** [comment]
Make the same change for LastIndexOf as well?

**Comment by jkotas** [comment]
Also, `ByteEqualityComparer<T> IndexOf/LastIndexOf` can be changed to:

```
#if DEBUG
internal override int IndexOf(T[] array, T value, int startIndex, int count)
{
     Debug.Fail("Should not get here.");
     return -1;
}

internal override int LastIndexOf(T[] array, T value, int startIndex, int count)
{
     Debug.Fail("Should not get here.");
     return -1;
}
#endif
```

And the comment in front of ByteEqualityComparer that refers to `C runtime function memchr` can be deleted.

**Comment by jkotas** [comment]
Thanks!

**Comment by benaadams** [comment]
> Perf results for small and large arrays?

`char` gets the biggest bump as it wasn't vectorized at all; `byte` gets a little boost.

Item to find is last item in array:
```diff
             Method | LengthAndPosition |       Mean |
 ------------------ |------------------ |-----------:|
- ByteArray_IndexOf |                 1 |  10.662 ns |
+ ByteArray_IndexOf |                 1 |   4.815 ns |
- ByteArray_IndexOf |                 7 |  13.044 ns |
+ ByteArray_IndexOf |                 7 |   7.886 ns |
- ByteArray_IndexOf |                 8 |  11.268 ns |
+ ByteArray_IndexOf |                 8 |   5.311 ns |
- ByteArray_IndexOf |                15 |  14.898 ns |
+ ByteArray_IndexOf |                15 |   9.704 ns |
- ByteArray_IndexOf |                16 |  13.775 ns |
+ ByteArray_IndexOf |                16 |   7.718 ns |
- ByteArray_IndexOf |                31 |  18.907 ns |
+ ByteArray_IndexOf |                31 |  13.215 ns |
- ByteArray_IndexOf |                32 |  18.572 ns |
+ ByteArray_IndexOf |                32 |  10.977 ns |
- ByteArray_IndexOf |                63 |  26.331 ns |
+ ByteArray_IndexOf |                63 |  19.900 ns |
- ByteArray_IndexOf |                64 |  20.875 ns |
+ ByteArray_IndexOf |                64 |  14.305 ns |
- ByteArray_IndexOf |               127 |  24.201 ns |
+ ByteArray_IndexOf |               127 |  18.260 ns |
- ByteArray_IndexOf |               128 |  22.425 ns |
+ ByteArray_IndexOf |               128 |  15.927 ns |
- ByteArray_IndexOf |               255 |  25.669 ns |
+ ByteArray_IndexOf |               255 |  19.869 ns |
- ByteArray_IndexOf |               256 |  24.525 ns |
+ ByteArray_IndexOf |               256 |  17.505 ns |
- ByteArray_IndexOf |              1023 |  42.796 ns |
+ ByteArray_IndexOf |              1023 |  35.056 ns |
- ByteArray_IndexOf |              1024 |  39.614 ns |
+ ByteArray_IndexOf |              1024 |  32.545 ns |

- CharArray_IndexOf |                 1 |   7.941 ns |
+ CharArray_IndexOf |                 1 |   4.734 ns |
- CharArray_IndexOf |                 7 |  11.493 ns |
+ CharArray_IndexOf |                 7 |   7.275 ns |
- CharArray_IndexOf |                 8 |  11.911 ns |
+ CharArray_IndexOf |                 8 |   7.153 ns |
- CharArray_IndexOf |                15 |  15.905 ns |
+ CharArray_IndexOf |                15 |   9.498 ns |
- CharArray_IndexOf |                16 |  16.509 ns |
+ CharArray_IndexOf |                16 |   8.312 ns |
- CharArray_IndexOf |                31 |  24.862 ns |
+ CharArray_IndexOf |                31 |  12.377 ns |
- CharArray_IndexOf |                32 |  25.419 ns |
+ CharArray_IndexOf |                32 |  11.593 ns |
- CharArray_IndexOf |                63 |  54.734 ns |
+ CharArray_IndexOf |                63 |  14.740 ns |
- CharArray_IndexOf |                64 |  53.779 ns |
+ CharArray_IndexOf |                64 |  13.734 ns |
- CharArray_IndexOf |               127 |  85.854 ns |
+ CharArray_IndexOf |               127 |  17.440 ns |
- CharArray_IndexOf |               128 |  83.126 ns |
+ CharArray_IndexOf |               128 |  17.066 ns |
- CharArray_IndexOf |               255 | 146.354 ns |
+ CharArray_IndexOf |               255 |  24.950 ns |
- CharArray_IndexOf |               256 | 146.514 ns |
+ CharArray_IndexOf |               256 |  24.206 ns |
- CharArray_IndexOf |              1023 | 515.342 ns |
+ CharArray_IndexOf |              1023 |  68.844 ns |
- CharArray_IndexOf |              1024 | 525.847 ns |
+ CharArray_IndexOf |              1024 |  67.101 ns |
```

**Comment by stephentoub** [comment]
Thanks, @benaadams.

**Pull request merged**
