### PR TITLE
Add some instructions (tests, new APIs)

### PR DESCRIPTION
**Pull request by kouvel**
- Instructions for running CoreCLR and PAL tests outside Windows
- Brief instructions for running CoreFX tests with a private build of CoreCLR outside Windows
- Adding new public APIs to mscorlib

### CODE REVIEW

**Comment by kouvel** [comment]
@sergiy-k, could you please take a look at the CoreCLR test instructions?
@weshaggard, could you please take a look at the instructions for adding a new API to mscorlib?

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by sergiy-k** [comment]
LGTM. Thanks a lot for getting this done!

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by weshaggard** [comment]
I had a read over the mscorlib API instructions I think you hit on all the basics so they look reasonable to me. We can always iterate on them over time if necessary. Thanks for putting these together.

**Pull request merged**
