### PR TITLE
Add "all" command to build.cmd

### PR DESCRIPTION
**Pull request by BruceForstall**
With "all", all build architectures and type are built. If a set of architectures or types
is also given, then the set of builds is restricted to those architecturs or flavors.

For example:
    build all
       -- builds all architectures, and all build types per architecture
    build all x86
       -- builds all build types for x86
    build all x64 x86 Checked Release
       -- builds x64 and x86 architectures, Checked and Release build types for each

### CODE REVIEW

**Comment by BruceForstall** [comment]
@pgavlin @mmitche PTAL

**Comment by BruceForstall** [comment]
@dotnet-bot test OSX x64 Release Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test OSX x64 Release Build and Test

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib Not a JIT thing, but maybe someone could take a look?

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib Not JIT related, but maybe someone can take a look

**Comment by pgavlin** [comment]
Looks fine to me.

**Pull request merged**
