### PR TITLE
Fix for Retail/Checked Asm diffs

### PR DESCRIPTION
**Pull request by briansull**
Check for retail config for EnableAVX
Also disable AVX2 whenever AVX is disabled

### CODE REVIEW

**Comment by briansull** [comment]
@BruceForstall PTAL
@dotnet/jit-contrib

**Comment by BruceForstall** [comment]
@fiigii @CarolEidt PTAL

**Comment by briansull** [comment]
Will wait to  Commit

**Comment by fiigii** [comment]
Thanks for the work. Once we have this change, shall we simplify https://github.com/dotnet/coreclr/pull/17688/files#diff-de7f32a5c493a88f0958dcea62ad2f67R2670
```cpp
            if (jitFlags.IsSet(JitFlags::JIT_FLAG_USE_AVX2))
            {
                // COMPlus_EnableAVX is also used to control the code generation of
                // System.Numerics.Vectors and floating-point arithmetics
                if (configEnableISA(InstructionSet_AVX) && configEnableISA(InstructionSet_AVX2))
                {
                    opts.setSupportedISA(InstructionSet_AVX2);
                }
            }
```
to
```cpp
            if (jitFlags.IsSet(JitFlags::JIT_FLAG_USE_AVX2))
            {
                if (configEnableISA(InstructionSet_AVX2))
                {
                    opts.setSupportedISA(InstructionSet_AVX2);
                }
            }
```

**Comment by briansull** [comment]
@fiigii yes feel free to simplify the checks above, in a future PR

**Pull request merged**
