### PR TITLE
Update buildtools version. Shorten filename of tests

### PR DESCRIPTION
**Pull request by rahku**
long filename cause tests to fail in helix

### CODE REVIEW

**Comment by rahku** [comment]
PTAL @ramarag 
CC @gkhanna79

**Comment by gkhanna79** [comment]
@ellismg @jhendrixMSFT http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/debug_windows_nt_prtest/145/console indicates that BuildTools package is running into ArgNullException. Any ideas?

**Comment by ramarag** [comment]
@rahku: can you give reasons on why it is fine to merge this commit even with the above failures ?

**Comment by rahku** [comment]
I believe they are not related to my change.

**Pull request merged**
