### PR TITLE
Code cleanup in CfgParser

### PR DESCRIPTION
**Pull request by CarLuver69**
Hi, this is my first pull request ever! I've glanced through the source code for Core CLR and there's definitely lots of room for improvement. I didn't see anything regarding code cleanup anywhere, so hopefully submissions like these are acceptable. If code-cleanup turns out to be OK, then I will definitely send more pull requests in the future (with more changes, of course)!.

- Mark

### CODE REVIEW

**Comment by ErikEJ** [comment]
Did you read the general contributing guide here: https://github.com/dotnet/corefx/wiki/Contributing (bottom paragraphs) ?

**Comment by CarLuver69** [comment]
Hi Erik, definitely my bad for not reading that. I'm assuming you mean this part:

**DO NOT** send PRs for style changes. We'd rather handle them holistically and they are tough to review and merge.

My apologies! Does this include code that's difficult to read and reminds me of "spaghetti code"? Or is it really anything to do with readability?

**Comment by jkotas** [comment]
I think that the contribution guidelines are clear about this.

Putting the guidelines aside for the moment - while I agree that some of the formatting in this file is not perfect, your change does not make it uniformly better:
- The aligment of the equal signs or commas in blocks of declarations does not match the common style used for C# in general and in the rest of mscorlib
- The enum declarations in this file are intentionally written to match the format of their unmanaged equivalents that they have to be in sync with.

I am sorry, but this is not a good pull request.

**Comment by CarLuver69** [comment]
Thank you for your honesty. I'll take this as a learning experience and read the guidelines next time.

**Pull request closed without merging**
