### PR TITLE
Specify the minimum supported version of macOS

### PR DESCRIPTION
**Pull request by echesakovMSFT**
As suggested in https://github.com/dotnet/coreclr/pull/21642#issuecomment-450670464 specify the minimum supported version of macOS to make coreclr built on macOS 10.13 work on macOS 10.12 and later

Tested in https://dnceng.visualstudio.com/public/_build/results?buildId=66785 and https://dnceng.visualstudio.com/public/_build/results?buildId=66781

### CODE REVIEW

**Comment by echesakovMSFT** [comment]
@janvorli Can you please take a look at changes in configurecompiler.cmake?

**Comment by echesakovMSFT** [comment]
@janvorli I've tried on 1012 and 1013 only. I will try to run it on 1014 as well and make sure the option passed to linker. Thanks!

**Comment by danmosemsft** [comment]
Whatever the build runs on, we should be testing on 10.12 and 10.14 (as highest and lowest) and ideally 10.13 as well. CoreFX tests on all of them. CoreCLR does not seem to run tests on 10.14 judging by mission control at least. @jashook ?

**Comment by echesakovMSFT** [comment]
I have confirmed that this solution would work on all three versions of OSX: 10.12, 10.13, 10.14
(https://mc.dot.net/#/user/echesakovMSFT/echesakovmsft~2Fcoreclr/test~2Fpri1/20190108.02)

**Comment by echesakovMSFT** [comment]
@danmosemsft We will be running internal tests on all three OSX versions in AzDO (as soon as this got merged). For open project (running against a PR) - only OSX.1012 and OSX.1013 open queues are available.

**Comment by echesakovMSFT** [comment]
@janvorli Can you please confirm that the changes to pass the option to linker look good?

**Comment by echesakovMSFT** [comment]
@MattGal Am I right that there is no "OSX.1014.Amd64.Open" queue we can utilize?

**Comment by MattGal** [comment]
@echesakov there's a limited number of machines, but we do have them so I stood it up (https://helix.dot.net/api/2018-03-14/info/queues/osx.1014.amd64.open )  https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/381 tracks getting this to be a permanent change.

**Comment by echesakovMSFT** [comment]
@MattGal I see, thanks. Since there's a limited number of machines can I use this queue to run tests against each PR or not?

**Comment by MattGal** [comment]
I'd recommend against it for all PRs, but you can definitely scout it;  if you have an active need for it let me know and I can work with @ilyas1974  about when we can get more machines.

**Pull request merged**
