### PR TITLE
Fix P/Invoke call and method {pro,epi}logs in RyuJIT/x86.

### PR DESCRIPTION
**Pull request by pgavlin**
The contract for methods that contain P/Invokes differs between 64- and
32-bit targets.

In the former case, the JIT must:
- In the method prolog, initialize the P/Invoke frame with a call to
  CORINFO_HELP_INIT_PINVOKE_FRAME and push the frame on to the current
  thread's frame list if the method is an IL stub.
- Before/after each call, if the method is *not* an IL stub, push/pop
  the frame (respectively).
- In the method epilog, if the method is an IL stub, pop the P/Invoke
  frame.

In the latter case, CORINFO_HELP_INIT_PINVOKE_FRAME pushes the P/Invoke
frame on to the current thread's frame list, and the frame need only
be popped in the method epilog.

This change adjusts P/Invoke lowering s.t. the 64-bit discipline is
only followed for 64-bit targets.

### CODE REVIEW

**Comment by pgavlin** [comment]
@BruceForstall @adiaaida @dotnet/jit-contrib PTAL

**Comment by pgavlin** [comment]
This fixes all but one of the test failures I was seeing when running tests against S.P.CoreLib NI that was generated using RyuJIT/x86.

**Comment by pgavlin** [comment]
It is likely that this also fixes https://github.com/dotnet/coreclr/issues/7463.

**Comment by BruceForstall** [comment]
:shipit:

**Comment by BruceForstall** [comment]
LGTM

**Comment by adiaaida** [comment]
For the formatting failures, either move the comments or put in a CLANG_FORMATTING_COMMENT_ANCHOR.

LGTM.

**Comment by pgavlin** [comment]
Fixes #7113 and #7463.

**Comment by BruceForstall** [comment]
> This fixes all but one of the test failures I was seeing when running tests against S.P.CoreLib NI that was generated using RyuJIT/x86.

@pgavlin what is the last failure?

**Comment by pgavlin** [comment]
The last failure appears to be an infrastructural issue: one of the tests is failing to load an assembly. I need to try a clean test build to verify my hypothesis.

**Pull request merged**
