### PR TITLE
Minor performance infrastructure changes.

### PR DESCRIPTION
**Pull request by jorive**
- IlLink scenario will run on a VM (currently it is only measuring MSIL size)
- Updated the patterns of files to search for on scenario runs
- Updated the JitBench commit hash being used

### CODE REVIEW

**Comment by jorive** [comment]
@dotnet/rap-team PTAL

**Comment by jorive** [comment]
@dotnet-bot test ci please

**Comment by jorive** [comment]
@dotnet-bot test ci please

**Comment by jorive** [comment]
@dotnet/rap-team PTAL

**Comment by DrewScoggins** [comment]
@dotnet-bot help

**Comment by DrewScoggins** [comment]
@dotnet-bot test Windows_NT x64 perf

**Comment by DrewScoggins** [comment]
@dotnet-bot test Windows_NT x64 min_opts perf

**Comment by DrewScoggins** [comment]
@dotnet-bot test Windows_NT x64 min_opts legacy_backend perf

**Comment by DrewScoggins** [comment]
@dotnet-bot test Windows_NT x64min_optslegacy_backend perf

**Comment by DrewScoggins** [comment]
@dotnet-bot test Windows_NT x64 min_opts legacy_backend perf

**Comment by DrewScoggins** [comment]
@dotnet-bot test Windows_NT x86 legacy_backend perf

**Comment by DrewScoggins** [comment]
@dotnet-bot test Windows_NT x86 legacy_backend perf

**Comment by jorive** [comment]
@dotnet-bot test ci please

**Comment by DrewScoggins** [comment]
@dotnet-bot test Windows_NT x86 ryujit perf

**Comment by DrewScoggins** [comment]
@dotnet-bot test Windows_NT x86 ryujit perf

**Comment by DrewScoggins** [comment]
LGTM

**Comment by DrewScoggins** [comment]
@dotnet-bot help

**Pull request merged**
