### PR TITLE
Merge serialization changes to 2.0.0

### PR DESCRIPTION
**Pull request by krwq**
Pending validation:
- [x] CoreFX 2.0.0 build with this changes picked up

running through CI to see failures early.

cc: @danmosemsft @ViktorHofer @morganbr

### CODE REVIEW

**Comment by morganbr** [comment]
We might still need #12010 

CC @AtsushiKan

**Comment by krwq** [comment]
@dotnet-bot test Windows_NT x64 CoreCLR Perf Tests Correctness please
```
Agent went offline during the build
ERROR: Connection was broken: java.io.IOException: Connection aborted: org.jenkinsci.remoting.nio.NioChannelHub$MonoNioTransport@23b2c473[name=win2012-e97810]
```

**Comment by krwq** [comment]
@dotnet-bot test Windows_NT x64 CoreCLR Perf Tests Correctness please

**Comment by krwq** [comment]
@mmitche, could you help restarting perf tests? @dotnet-bot is not picking up this job

**Comment by krwq** [comment]
@mmitche sorry - just lagged

**Comment by krwq** [comment]
@morganbr let's merge this without Ati's change and include it with TimeZoneInfo changes

**Comment by danmosemsft** [comment]
I would like to merge what we are testing in CoreFX right now - which does not include Ati's change.

**Comment by morganbr** [comment]
@krwq is #11535 already in 2.0 or does it need to be included in this change as well?

**Comment by krwq** [comment]
@morganbr seems to be already in (everything before ~5/15 should be in)

**Comment by danmosemsft** [comment]
Obviously, please don't merge this without shiproom approval. (And testing your CoreFX PR with it of course)

**Comment by krwq** [comment]
@danmosemsft FYI it's green, please merge once shiproom approves

**Comment by krwq** [comment]
@danmosemsft this is working locally with CoreFX pending changes

**Comment by ViktorHofer** [comment]
We should now also include the TimeZoneInfo fix: https://github.com/dotnet/coreclr/pull/12024/commits/f32ce49f94086e18833236856da5a4d8f43be69b

**Comment by danmosemsft** [comment]
@viktorhofer if that has been validated with corefx test please go ahead and update the 2.0 port PRs worth the fix and the text fix.

**Comment by AtsushiKan** [comment]
If you revert the changes to Assembly.cs, Module.cs and ParameterInfo.cs (i.e. exclude them from the "changeset"), you actually have the part of #12010 that should be in 2.0. I think makes a little more sense than a second Shiproom request to undo something you're changing as part of this Shiproom request.

**Comment by danmosemsft** [comment]
@AtsushiKan one would think, but it's essential I get this in today, and arguably that would reset testing. We can follow up right away with your change.

**Comment by krwq** [comment]
CI failiure looks like a real issue but I do not think related to our changes:
https://ci.dot.net/job/dotnet_coreclr/job/release_2.0.0/job/armel_cross_release_tizen_prtest/155/consoleText

**Comment by krwq** [comment]
```
FAILED   - JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b47975/b47975/b47975.sh
               BEGIN EXECUTION
               /home/coreclr/bin/tests/Windows_NT.x64.Release/Tests/coreoverlay/corerun b47975.exe
               ./b47975.sh: line 240:   705 Segmentation fault      (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
               Expected: 100
               Actual: 139
               END EXECUTION - FAILED
```

doesn't look related to our changes

**Comment by danmosemsft** [comment]
@krwq since we didn't change the runtime, and that test 47975 does not appear to exercise our code, I think this is safe to ignore.

**Comment by danmosemsft** [comment]
@dotnet-bot Tizen armel Cross Release Build  (running again since we have some time)

**Comment by danmosemsft** [comment]
@dotnet-bot test Tizen armel Cross Release Build  (running again since we have some time)

**Comment by ViktorHofer** [comment]
Shiproom approved.

**Pull request merged**
