### PR TITLE
ARM64: Support R2R Private Run in CI

### PR DESCRIPTION
**Pull request by kyulee1**

### CODE REVIEW

**Comment by kyulee1** [comment]
@dotnet-bot test ci please

**Comment by kyulee1** [comment]
@dotnet/arm64-contrib PTAL

**Comment by rahku** [comment]
Thanks. LGTM

**Comment by gkhanna79** [comment]
@wtgodbe PTAL as well.

**Comment by wtgodbe** [comment]
LGTM

**Pull request merged**
