### PR TITLE
Add perf test (making cards) to coreclr

### PR DESCRIPTION
**Pull request by shimingsg**
1. making card of list
2. making card of large array

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
@shimingsg Please replace "Making" with "Marking" in your test names (the csproj files). These are meant to exercise the card marking paths in the GC.

**Comment by karelz** [comment]
@adityamandaleeka what is the next step? Code review from you?

**Comment by adityamandaleeka** [comment]
I have no other comments since I see this is just a copy/paste port of some old code from an internal tree. Consider me signed off.

**Comment by adityamandaleeka** [comment]
Oh, and please squash your comments prior to merging.

**Comment by shimingsg** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test

**Comment by shimingsg** [comment]
@dotnet-bot test Tizen armel Cross Release Build

**Pull request merged**
