### PR TITLE
[release/2.2] Remove the Smarty dependency and move Windows ARM to Helix queue

### PR DESCRIPTION
**Pull request by echesakov**
#### Description

Port (partially) the following changes to enable Win/ARM testing in release/2.2:

*  Build xunit wrappers the same way on windows and unix (#18695)
*  Work around cmd command length limit in xunit Exec task (#19095)
*  Update vc-runtime package to support ARM and ARM64 with current builds (#19265)
*  build-test - fix TestWrapper CS warnings (#19180)
*  Clean up build.cmd/build-test.cmd/runtest.cmd (#19291)
*  Use runtest.py to run tests for all platforms (#19213)
*  Updating runtest.py so that it works with Python 3 (#19768)
*  Fix build-test.sh wrapper build (#19779)
*  Move ARM64 Windows boxen to be Helix-provisioned (#20204)
*  Runtest.py on Windows Arm(64) (#20227)
*  Use runtest.cmd for arm(64) windows testing (#20301)
*  Do not restore or initialize buildtools for x86/arm64 (#20370)
*  Add hack for arm64/x86 to skip build tools restore (#20390)

Update Xunit to 2.4.1 prerelease version

Use the latest version (dbf0bf1) of tests/runtest.py

#### Customer impact

Allow us to get ARM bugs out of the product more easily.

#### Regression?

No

#### Packaging reviewed?

N/A

#### Risk

Low to product.  Moderate to infra.  This is a large change, though it's mostly just a port of several changes that have been in master for a while.

### CODE REVIEW

**Comment by vivmishra** [comment]
Approved for 2.2

**Comment by echesakovMSFT** [comment]
@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test

**Comment by echesakovMSFT** [comment]
All the CI changes tested in dev/unix_test_workflow branch (https://github.com/dotnet/coreclr/pull/20576)

Official build tested in https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=2154949

**Ubuntu arm64 Cross Debug Innerloop Build** failure also observed in https://github.com/dotnet/coreclr/pull/20615 so gonna ignore this

**Comment by echesakovMSFT** [comment]
@dotnet-bot test ci

**Pull request merged**
