### PR TITLE
IBC: Disable `-partialNGEN -minify` for SPC.dll

### PR DESCRIPTION
**Pull request by dpodder**
This PR adds some fixes around the use of IBCMerge in CoreCLR, along with a BuildTools patch (which the fixes are dependent upon):
* don't restore the default optdata package through BuildTools
* don't use partial ngen by default in CoreCLR for SPC.dll

### CODE REVIEW

**Comment by dpodder** [comment]
@chcosta @wtgodbe PTAL
/cc: @dagood

FYI, I tried taking a BuildTools update first, but that resulted in various failures in two buckets:
* [two errors here](https://ci.dot.net/job/dotnet_coreclr/job/master/job/debug_centos7.1_prtest/5464/)
* [one error here](https://ci.dot.net/job/dotnet_coreclr/job/master/job/armel_cross_release_tizen_prtest/1147/)

Once this is merged I'll open an Issue to track removing the override after we update BuildTools past the minimum required version (1.0.27-prerelease-01513-01)

**Comment by wtgodbe** [comment]
Sorry, missed this earlier. LGTM

**Comment by dpodder** [comment]
Thanks!

**Pull request merged**
