### PR TITLE
Clean up cleanup code in PAL

### PR DESCRIPTION
**Pull request by adityamandaleeka**
This changes removes some of the unused codepaths in the PAL cleanup logic. It also removes the calls to `PROCCondemnOtherThreads` and `PROCSuspendOtherThreads` that we were doing in `PALCommonCleanup` since they should no longer be necessary.

I left some things in `PALCommonCleanup` alone without modifying the logic since there may be risk involved in removing them (for example, there is code in `CPalSynchMgrController::PrepareForShutdown` that is intended to prevent us from leaking shared memory when the process exits).

This change helps us achieve #1795.

@jkotas @janvorli @sergiy-k

### CODE REVIEW

**Comment by jkotas** [comment]
LGTM

**Comment by janvorli** [comment]
LGTM

**Comment by janvorli** [comment]
@mmitche It looks like some of the CI Ubuntu machines are missing the lldb 3.6 package:
`Cannot find LLDB.h.  Try installing lldb-3.6-dev (or the appropriate package for your platform)`

**Comment by mmitche** [comment]
@janvorli Up until now, lldb-3.6 has been optional (since our dependency is on clang-3.5 and bringing in lldb 3.6 also brings in llvm 3.6, etc.  Bits of the repo do not build without it installed.  Is it possible to make this optional?

**Comment by mmitche** [comment]
@janvorli Actually this looks like someone installed stuff on the ub-fbld-1 machine without reverting the changes later.  You should be okay.

**Pull request merged**
