### PR TITLE
Use generic win-x86/win-x64 RIDs in stress_dependencies

### PR DESCRIPTION
**Pull request by echesakovMSFT**
Update Windows Stress Dependencies to match the changes in https://github.com/dotnet/llilc/pull/1087

### CODE REVIEW

**Comment by echesakovMSFT** [comment]
@dotnet-bot test Windows_NT x86 checked gcstress0xc
@dotnet-bot test Windows_NT x64 checked gcstress0xc

**Comment by echesakovMSFT** [comment]
Both [Windows_NT x86 Checked Build and Test (Jit - GCStress=0xC)](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_gcstress0xc_prtest/73) and [Windows_NT x64 Checked Build and Test (Jit - GCStress=0xC)](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_gcstress0xc_prtest/67) could locate coredistools.dll

```
Locating coredistools.dll
CoreDisTools library path: D:\j\workspace\x64_checked_w---aba24ae0\Packages\runtime.win-x64.microsoft.netcore.coredistools\1.0.1-prerelease-00004\runtimes\win-x64\native\coredistools.dll
Copy library: D:\j\workspace\x64_checked_w---aba24ae0\Packages\runtime.win-x64.microsoft.netcore.coredistools\1.0.1-prerelease-00004\runtimes\win-x64\native\coredistools.dll to D:\j\workspace\x64_checked_w---aba24ae0\bin\Product\Windows_NT.x64.Checked
        1 file(s) copied.
```

```
Locating coredistools.dll
CoreDisTools library path: D:\j\workspace\x86_checked_w---344a5564\Packages\runtime.win-x86.microsoft.netcore.coredistools\1.0.1-prerelease-00004\runtimes\win-x86\native\coredistools.dll
Copy library: D:\j\workspace\x86_checked_w---344a5564\Packages\runtime.win-x86.microsoft.netcore.coredistools\1.0.1-prerelease-00004\runtimes\win-x86\native\coredistools.dll to D:\j\workspace\x86_checked_w---344a5564\bin\Product\Windows_NT.x86.Checked
```

**Comment by echesakovMSFT** [comment]
@RussKeldorph PTAL

**Comment by RussKeldorph** [comment]
@dotnet-bot test Windows_NT x64 Checked gcstress0xc

**Pull request merged**
