### PR TITLE
More simple integer benchmarks for the Jit

### PR DESCRIPTION
**Pull request by AndyAyersMS**
8Queens, Ackermann, AddArray, Fib, Pi.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@cmckinsey PTAL

Note I am setting iterations so these take around 10 seconds when run under xunit-performance.

**Comment by swgillespie** [comment]
Out of curiosity, how would I go about running these tests (and the one that got merged the other day)? I'm hoping to add some xunit-performance benchmarks as well.

**Comment by AndyAyersMS** [comment]
@swgillespie Working on that now -- we need some additional packages to actually run these in performance test mode.

**Comment by swgillespie** [comment]
@AndyAyersMS Ah, I see - thanks.

**Comment by AndyAyersMS** [comment]
@swgillespie take a look at this [script](https://gist.github.com/AndyAyersMS/e0c343d9ee9106a35be4) for running under xunit-performance on CoreCLR.

Requires this PR, and then a full build of CoreCLR (including tests), and then possibly a test run.

**Comment by swgillespie** [comment]
@AndyAyersMS Thank you! That's very helpful.

**Comment by cmckinsey** [comment]
LGTM.

**Pull request merged**
