### PR TITLE
Implement GetEntrypointExecutableAbsolutePath() on NetBSD

### PR DESCRIPTION
**Pull request by krytarowski**
For `defined(KERN_PROC_PATHNAME)` use `sysctl`(7) (introduced after NetBSD-7.0).
For older NetBSD use the Linux's code.

### CODE REVIEW

**Comment by krytarowski** [comment]
@jkotas @janvorli PTAL

**Comment by janvorli** [comment]
Just so that I understand, does it mean that the Linux way does not work on the newer NetBSD?

**Comment by krytarowski** [comment]
Older NetBSD needs procfs mounted with Linux capabilities. We don't need it in never versions.

**Comment by janvorli** [comment]
Ah, got it.
LGTM

**Comment by janvorli** [comment]
Actually, I've just spotted different coding convention for curly braces in your piece of code. Could you please unify it with the existing stuff?

**Comment by krytarowski** [comment]
Done!

**Comment by janvorli** [comment]
There is one detail you've missed - the else should be on a separate line

**Comment by krytarowski** [comment]
Fixed!

**Comment by janvorli** [comment]
Thanks!

**Comment by krytarowski** [comment]
@dotnet-bot test Ubuntu x64 please

**Comment by krytarowski** [comment]
@dotnet-bot test this please

**Comment by krytarowski** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test please

**Pull request merged**
