### PR TITLE
Make  GCToOSInterface::FlushProcessWriteBuffers use MEMBARRIER_CMD_PRIVATE_EXPEDITED if available

### PR DESCRIPTION
**Pull request by VSadov**
Make  GCToOSInterface::FlushProcessWriteBuffers use MEMBARRIER_CMD_PRIVATE_EXPEDITED if available
Basically a port of  https://github.com/dotnet/coreclr/pull/20949   to  GCToOSInterface

Could be responsible for #22303, at least there is a possibility. 
Seems like a good-to-have anyways.

### CODE REVIEW

**Comment by VSadov** [comment]
I think one of the possible reasons for https://github.com/dotnet/coreclr/issues/22303  _could_ be that the current page protection based mechanism may not be 100% reliable.

The theory is that rare AV in `Interlocked.Exchange` on Linux (both ARM64 and x64, but x64 not as often) could be a result of writing to a stale card table. There is hardly anything else going on in the helper besides the exchange itself, which presumably would fail more often if it was the culprit.

Card tables updates involve FlushProcessWriteBuffers, so its platform-specific implementation may explain platform-specific failure.

That is all "in theory".  The failure is nearly impossible to reproduce on purpose. 

Anyways, MEMBARRIER_CMD_PRIVATE_EXPEDITED is also presumably a bit faster so, if available, then perhaps we should use it anyways.

**Comment by jkotas** [comment]
This is good change, but I doubt that it will fix the problem. The default GC that is built into the runtime does not used the gcenv.unix.cpp today. It is used by the standalone/local GC builds only.

**Comment by VSadov** [comment]
I see. I was suspecting that. - Why have 2 implementations after all, if not for a standalone scenario, but was not sure.

Porting the change, on the other hand was easy.

**Comment by VSadov** [comment]
@janvorli @Maoni0  - it does not look like a very consequential change, since it is for standalone scenario. Just an FYI.

**Comment by VSadov** [comment]
@jkotas - Thanks!

**Pull request merged**
