### PR TITLE
Fix #15057 MemoryStream.CopyToAsync calls Write / WriteAsync with count=0

### LINKED ISSUE #15057: MemoryStream.CopyToAsync calls destination.Write / WriteAsync with count=0 when there's nothing to copy
`MemoryStream` provides a specialized implementation of `CopyToAsync` that avoids extra allocations and buffer copies by writing the entire buffer in one go. Makes sense.

When there are no bytes to copy in the source stream, however, it should bail out early and do nothing. That would be the consistent thing to do to match the behavior of the base implementation `Stream.CopyToAsync` (`Stream.CopyToAsync` would call `ReadAsync,` which would return `0`, and that would be the end of it -- no calls to `WriteAsync`). Instead, it currently calls `destination.WriteAsync(..., count: 0)`.

The current behavior is unexpected, inconsistent, and gives rise to other problems when the destination stream cannot deal with `0`-length writes properly (see [aspnet/HttpSysServer #417](https://github.com/aspnet/HttpSysServer/issues/417) which I just filed).

Note: I don't think this problem is unique to .NET Core, and other versions of the .NET Framework are also affected.

### PR DESCRIPTION
**Pull request by davidni**

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks for the fix.

**Comment by stephentoub** [comment]
PRs are failing with:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.DotNet.Configurer.CliFallbackFolderPathCalculator.get_DotnetUserProfileFolderPath()
   at Microsoft.DotNet.Configurer.FirstTimeUseNoticeSentinel..ctor(CliFallbackFolderPathCalculator cliFallbackFolderPathCalculator)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
ERROR: Could not restore build tools correctly.
```
@eerhardt, known issue?

**Comment by eerhardt** [comment]
The code that is throwing looks like this:

https://github.com/dotnet/cli/blob/3471d437969ed52d12116f7067b02e6e12a49d03/src/Microsoft.DotNet.Configurer/CliFallbackFolderPathCalculator.cs#L19-L26

```c#
        public string DotnetUserProfileFolderPath
        {
            get
            {
                string profileDir = Environment.GetEnvironmentVariable(
                    RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? "USERPROFILE" : "HOME");

                return Path.Combine(profileDir, ".dotnet");
            }
        }
````

Is the `HOME` env var not set on the machine?

/cc @livarcocc @nguerrera

**Comment by eerhardt** [comment]
I'm also seeing:

```
FAILED   - JIT/Performance/CodeQuality/Span/SpanBench/SpanBench.sh
               BEGIN EXECUTION
               /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/checked_osx10.12_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun SpanBench.exe
               TestSpanClear<Byte>(100): 0.736ms
               TestSpanClear<String>(100): 0.013ms
               TestArrayClear<Byte>(100): 0.012ms
               TestArrayClear<String>(100): 0.011ms
               
               Unhandled Exception: System.TypeLoadException: Could not load type 'System.SpanExtensions' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
                  at Span.SpanBench.TestSpanAsBytes[T](T[] array, Int32 iterationCount, Boolean untrue)
                  at Span.SpanBench.Invoke(Action`1 innerLoop, String nameFormat, Object[] nameArgs)
                  at Span.SpanBench.Main(String[] args)
               ./SpanBench.sh: line 243:  9317 Abort trap: 6           (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
```

Which appears to be the opposite of the error in https://github.com/dotnet/coreclr/pull/15054.  This one says can't find `SpanExtensions`.  #15054 says it can't find `MemoryExtensions`.

/cc @ahsonkhan 

Is the coreclr repo broken right now?

**Comment by jkotas** [comment]
Yes, HOME variable is not set on CI machine. We keep working around it like here: `https://github.com/dotnet/coreclr/blob/master/build.sh#L944`. It would be much better to fix CLI to not assume that HOME is set. It is pretty likely that customer environments out there do not have HOME set either.

**Comment by jkotas** [comment]
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test please

**Pull request merged**
