### PR TITLE
Fix dotnet-coreclr-perf pipeline

### PR DESCRIPTION
**Pull request by trylek**

### CODE REVIEW

**Comment by trylek** [comment]
dotnet-coreclr-perf job (started): https://dev.azure.com/dnceng/internal/_build/results?buildId=416562

@DrewScoggins, can you please let me know once you manage to verify if the job does what it's supposed to again?

**Comment by DrewScoggins** [comment]
It looks like the _Framework variable is not getting passed correctly.

```
_Framework : The term '_Framework' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At F:\workspace\_work\_temp\5afaf7d0-dfca-4362-ae52-0752c10b7bf6.ps1:2 char:92
+ ... mance\performance-setup.ps1 -Internal -Framework $(_Framework) -CoreR ...
+                                                        ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (_Framework:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by trylek** [comment]
Thanks Drew! I just pushed one more commit that should hopefully fix this, we'll see in an hour or so if that's indeed the case.

**Comment by DrewScoggins** [comment]
It looks like things are working now. It made it past the step that was failing before. We should see if we are getting results in about 45 minutes.

**Comment by maryamariyan** [comment]
Thank you for your contribution. As announced in dotnet/coreclr#27549 this repository will be moving to dotnet/runtime on November 13. If you would like to continue working on this PR after this date, the easiest way to move the change to dotnet/runtime is:
1.	In your coreclr repository clone, create patch by running `git format-patch origin`
2.	In your runtime repository clone, apply the patch by running `git apply --directory src/coreclr <path to the patch created in step 1>`

**Pull request merged**
