### PR TITLE
Fix copyOrMoveRegInUse

### LINKED ISSUE #14798: [RyuJIT/x64][JitStressRegs=8] Assertion failed 'farthestRefPhysRegRecord != nullptr'
From x64 JitStressRegs=8 testing, e.g., https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_jitstressregs8/

Failure:
```
Assert failure(PID 10828 [0x00002a4c], Thread: 23592 [0x5c28]): Assertion failed 'farthestRefPhysRegRecord != nullptr' in 'ILGEN_CLASS:ILGEN_METHOD(ubyte,long,long,char):long' (IL size 106)

    File: e:\gh\coreclr2\src\jit\lsra.cpp Line: 6447
    Image: E:\gh\coreclr2\bin\tests\Windows_NT.x64.checked\Tests\Core_Root\CoreRun.exe
```

Test:
```
JIT\Regression\JitBlue\DevDiv_487701\DevDiv_487701\DevDiv_487701.cmd
```

Possibly the same as #11838?

### PR DESCRIPTION
**Pull request by CarolEidt**
When checking whether a `copyReg` or `moveReg` is still in use, only consider it in use if it is assigned to the register we care about.
We can have strings of `copyReg`s to different registers, especially in stress modes.

Fix #14798

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT jitstressregs8

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT jitstressregs0x80
@dotnet-bot test Windows_NT jitstressregs1
@dotnet-bot test Windows_NT jitstressregs2
@dotnet-bot test Windows_NT jitstressregs3
@dotnet-bot test Windows_NT jitstressregs4

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs0x80
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs1
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs2
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs3
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs4
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs8

**Comment by CarolEidt** [comment]
The x64/JitStressRegs4 failure is in baseservices\threading\generics\Monitor\EnterExit12\EnterExit12.cmd. I can't reproduce it locally.
The x86/arm-altjit/JitStressRegs3 failures are 1 timeout and 2 instances of #14372

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

**Comment by BruceForstall** [comment]
The EnterExit failures have been fixed by https://github.com/dotnet/coreclr/pull/14805

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib @mmitche - does anyone have a clue why the "Perf Build and Test" seems to be taking forever?

**Pull request merged**
