### PR TITLE
Lib unixcoreruncommon

### PR DESCRIPTION
**Pull request by kyulee1**
This is a small refactoring to make unixcoreruncommon as a library so that we can reuse the code for other purpose.

### CODE REVIEW

**Comment by janvorli** [comment]
I am curious - how do you plan to reuse it? One thing I would like to understand is why the coreClrDll was moved to the header.

**Comment by wtgodbe** [comment]
@dotnet-bot test this please

**Comment by wtgodbe** [comment]
@dotnet-bot test osx debug please

**Comment by wtgodbe** [comment]
@dotnet-bot test osx debug.

**Comment by kyulee1** [comment]
@janvorli  Basically I will use this to ildasm enabling. Similarly i need to resolve path from the executable to corclr lirbary. The change of "coreClrDll" location is arguable since it's definition, but I'd like to use the same definition without repeating them just by including such header file for ildasm, too.

**Comment by kyulee1** [comment]
@dotnet-bot retest osx debug

**Comment by kyulee1** [comment]
@janvorli @jkotas PTAL

**Comment by janvorli** [comment]
Although I think you will only need a small portion of the functions in the coreruncommon.cpp, it seems it would not make sense to split the file further, so it looks good to me as it is.

**Comment by kyulee1** [comment]
Okay. Then I will figure out a different way to use such component for my needs.

**Comment by janvorli** [comment]
@kyulee1 I meant that I am ok with it as is.

**Pull request merged**
