### PR TITLE
Update PAL name

### PR DESCRIPTION
**Pull request by ellismg**
As of 19d02824, the Win32 functions exported by the PAL are now in
libCoreClrPal instead of libcoreclr itself.  Update mscorlib's PInvokes
to match this change.

### CODE REVIEW

**Comment by ellismg** [comment]
@jkotas,  After discussion with @mikem8361, I think we need to make this change, correct?  If so, I will make a corresponding change in CoreFX to adjust to the new name as well.

**Comment by jkotas** [comment]
Yes, it looks like a required change. 

The CamelCasing of the libCoreClrPal.so name looks odd - not very Unixy, different from libcoreclr.so. It may be nice to make it all lowercase.

**Comment by ellismg** [comment]
@mikem8361 Do you have problems with me pushing through the change to lowercase the whole thing right now?

**Comment by mikem8361** [comment]
I don't like the name either but there are 100s of pal test cmake files I didn't want fix. And this module is temporary.

Sent from my Verizon Wireless 4G LTE DROID


Matt Ellis <notifications@github.com> wrote:


@mikem8361<https://github.com/mikem8361> Do you have problems with me pushing through the change to lowercase the whole thing right now?

-

**Comment by ellismg** [comment]
It is easy for me to change the name to "coreclrpal" from "CoreClrPal" so I will do so.  When it changes again, it will be easy for me to update everything, I don't mind.

**Comment by mikem8361** [comment]
Please leave it libCoreClrPal.so<http://libCoreClrPal.so>.  Anything else won't work and I don't plan to change all the PAL test make files to the lower case name.

Sent from my Verizon Wireless 4G LTE DROID


Matt Ellis <notifications@github.com> wrote:


It is easy for me to change the name to "coreclrpal" from "CoreClrPal" so I will do so. When it changes again, it will be easy for me to update everything, I don't mind.

-

**Comment by ellismg** [comment]
@mikem8361 
> Anything else won't work and I don't plan to change all the PAL test make files to the lower case name.

Right before your response, I pushed a new commit that renames it to libcoreclrpal but I also fixed up all the PAL tests and verified a clean build works and the PAL tests run without error.  What else wouldn't work?

**Comment by mikem8361** [comment]
Sorry,  I didn't know that you were changing the tests. What about all the other cmake file refs in the DAC, DBI, dbgshim and coreclr. If you got all of them then everything should be OK.  Thanks.

Sent from my Verizon Wireless 4G LTE DROID


Matt Ellis <notifications@github.com> wrote:


@mikem8361<https://github.com/mikem8361>

Anything else won't work and I don't plan to change all the PAL test make files to the lower case name.

Right before your response, I pushed a new commit that renames it to libcoreclrpal but I also fixed up all the PAL tests and verified a clean build works and the PAL tests run without error. What else wouldn't work?

-

**Comment by ellismg** [comment]
@mikem8361 Yes, I changed them all.  These are the files not under src\pal\tests that changed:

```
src/ToolBox/SOS/Strike/CMakeLists.txt
src/dlls/dbgshim/CMakeLists.txt
src/dlls/mscordac/CMakeLists.txt
src/dlls/mscordbi/CMakeLists.txt
src/dlls/mscoree/coreclr/CMakeLists.txt
src/jit/CMakeLists.txt
src/mscorlib/src/Microsoft/Win32/Win32Native.cs
src/pal/src/CMakeLists.txt
src/pal/src/examples/CMakeLists.txt
src/pal/src/loader/module.cpp
src/utilcode/dac/CMakeLists.txt
src/utilcode/dyncrt/CMakeLists.txt
```

If someone wants to spot check the second commit (I used git grep + sed to do the renames) I can merge these changes in and then merge in the changes in CoreFX.

**Comment by mikem8361** [comment]
LGTM

**Comment by janvorli** [comment]
@ellismg Thanks a lot for changing the case! It was something I wanted to do at some point anyways to be consistent with the rest of the libraries.

**Pull request merged**
