### PR TITLE
Fix GC stress setup failure on Unix-like OSes

### PR DESCRIPTION
**Pull request by sejongoh**

### CODE REVIEW

**Comment by sejongoh** [comment]
@dotnet-bot test ci please

**Comment by sejongoh** [comment]
@dotnet-bot test Windows_NT corefx_jitstress1

**Comment by sejongoh** [comment]
@dotnet-bot test Ubuntu corefx_jitstress2

**Comment by pgavlin** [comment]
cc @mmitche

**Comment by jashook** [comment]
Ignore the x86 failures, excluding them now.

**Comment by sejongoh** [comment]
Changes
- Increase time out for GC stress testing
- Execute init-tool.sh to pull down dotnet packages.

@mmitche Could you review the changes?

**Comment by sejongoh** [comment]
@dotnet-bot test ci

**Comment by mmitche** [comment]
LGTM thanks for the cleanup

**Pull request merged**
