### PR TITLE
[ARM32/Linux] Copy tests.zip only for CI test

### PR DESCRIPTION
**Pull request by hseok-oh**
Copy tests.zip only from x64 Windows build for CI test
We can reduce saved build results of linux/arm in CI machine

### CODE REVIEW

**Comment by hseok-oh** [comment]
@dotnet-bot test ci please

**Comment by hseok-oh** [comment]
@dotnet-bot test Tizen armel Cross Release Build please

**Comment by jashook** [comment]
@mmitche are these tests zipped by jenkins dynamically? Either way PTAL

**Comment by mmitche** [comment]
@jashook No, they are zipped on the client side.

**Comment by mmitche** [comment]
otherwise LGTM

**Pull request merged**
