### PR TITLE
Add Linux host support for arm32/arm64 altjit

### PR DESCRIPTION
**Pull request by BruceForstall**
Now, on Linux, the x64 build will build an arm64-targeting
altjit. The x86 build will build an arm32-targeting JIT.
The altjit is named libprotononjit.so/dylib. It can be
used for debugging or for generating asm diffs using jit-diff.

### CODE REVIEW

**Comment by BruceForstall** [comment]
With this change, you can generate ARM64 code on Linux x64 using the altjit, e.g.:
```
COMPlus_AltJit=* COMPlus_AltJitName=libprotononjit.so COMPlus_JitDisasm=* crossgen test.exe
```

**Comment by BruceForstall** [comment]
@briansull PTAL
cc @dotnet/arm32-contrib @dotnet/arm64-contrib @dotnet/jit-contrib

**Comment by sdmaclea** [comment]
@BruceForstall thanks

**Comment by sjsinju** [comment]
@BruceForstall I wanted to generate ARM64 code on ubuntu(x64). So I used commands like what you said.
> COMPlus_AltJit=* COMPlus_AltJitName=libprotononjit.so COMPlus_JitDisasm=* crossgen test.exe

but I couldn't get any results for dump. 
It was possible to get expected results if the commands are changed to below.
```
COMPlus_NgenAltJit=* COMPlus_AltJitName=libprotononjit.so COMPlus_NgenDisasm=* COMPlus_NgenDump=* crossgen test.exe
```

**Comment by BruceForstall** [comment]
@sjsinju yes, sorry about the incorrect instructions. You need to use the `COMPlus_Jit*` variables for JIT compiling or the `COMPlus_Ngen*` variables for NGEN compiling (which includes crossgen). You can, of course, set both.

**Pull request merged**
