### PR TITLE
Remove RenameUpdatedVars.

### PR DESCRIPTION
**Pull request by pgavlin**
The variable renaming performed by rationalize was originally intended
(according to its comments) to allow assignments that were embedded in
subtrees to be hoisted out into a preceding statement. It appears that
this logic has been removed, so the rename pass is no longer needed.

### CODE REVIEW

**Comment by pgavlin** [comment]
There are 5 assembly diffs due to this change. All of these diffs appear to be caused by different decisions in the RA due to fewer local vars coming out of rationalization.

**Comment by pgavlin** [comment]
@CarolEidt @dotnet/jit-contrib PTAL

**Comment by pgavlin** [comment]
Ping. Anyone?

**Comment by CarolEidt** [comment]
What asm diffs did you run? Are the diffs positive or negative? If this had the effect of splitting a lclVar, it could lead to improved RA because it no longer constrains the disjoint range to try to use the same reg.

**Comment by pgavlin** [comment]
@CarolEidt: I ran the complete set of internal diffs. The diffs are each a 1 byte code size regression that appears to arise from an extra copy.

**Comment by CarolEidt** [comment]
OK, sounds good to me. I'm guessing that it is indeed due to the effect I mentioned, but obviously not worth the extra pass!

**Comment by pgavlin** [comment]
That was my feeling as well.

**Pull request merged**
