### PR TITLE
Remove bad test: stk_bndchk.il

### LINKED ISSUE #2585: Bad test case: tests\src\JIT\Methodical\tailcall_v4\stk_bndchk.il
tests\src\JIT\Methodical\tailcall_v4\stk_bndchk.il is failing consistently for some individuals and occasionally in the cloud.  It assumes that it can create at most 1000 threads and be guaranteed that at least one of the threads' stacks will be at an address below the heap.  Presumably it did that because such addresses were required to provoke a bug repro at one point in time.  Assuming the original bug is long fixed, there doesn't appear to be much value to this test case, and it should simply be removed rather than made deterministic.

### PR DESCRIPTION
**Pull request by RussKeldorph**
stk_bndchk.il is failing consistently for some individuals and occasionally in the cloud. It assumes that it can create at most 1000 threads and be guaranteed that at least one of the threads' stacks will be
at an address below the heap. Presumably it did that because such addresses were required to provoke a bug repro at one point in time.  There doesn't appear to be much value to this test case even if it were somehow made deterministic, so it should simply be removed.

Fixes #2585

### CODE REVIEW

**Comment by RussKeldorph** [comment]
@dotnet/jit-contrib @richardlford

**Comment by RussKeldorph** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build

**Comment by RussKeldorph** [comment]
@dotnet-bot test OSX x64 Release Build and Test

**Comment by jkotas** [comment]
LGTM

**Pull request merged**
