### PR TITLE
Fix One Arm64 crossgen failure

### PR DESCRIPTION
**Pull request by CarolEidt**
The type of the ADDR node needs to be set to TYP_BYREF.

### CODE REVIEW

**Comment by CarolEidt** [comment]
@kyulee1 - this fixes the first assert, but there is now another, later in the crossgen, that happens in the register allocator.
cc @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
LGTM

**Comment by kyulee1** [comment]
LGTM. Thanks for the fix.

@dotnet-bot test Windows_NT arm64 checked

**Comment by pgavlin** [comment]
Will this work for UNIX? The original code for that ABI used the type of the struct for the GT_ADDR.

**Comment by pgavlin** [comment]
I can confirm that this does not work for the *nix AMD64 ABI. Crossgen fails with the following:

```
Assert failure(PID 22570 [0x0000582a], Thread: 22570 [0x582a]): Assertion failed 'info->isStruct == varTypeIsStruct(type)' in 'System.Reflection.Emit.TypeBuilder:DefinePropertyNoLock(ref,int,int,ref,ref,ref,ref,ref,ref):ref:this' (IL size 200)

    File: /home/pgavlin/dev/coreclr/src/jit/lower.cpp Line: 890
    Image: /home/pgavlin/dev/coreclr/bin/Product/Linux.x64.Checked/crossgen
```

**Comment by CarolEidt** [comment]
Yes, I'm testing a fix that makes it conditional.
(Though a GT_ADDR should NEVER by TYP_STRUCT)

**Comment by pgavlin** [comment]
> (Though a GT_ADDR should NEVER by TYP_STRUCT)

I agree. We should file an issue for follow-up.

**Comment by CarolEidt** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build

**Comment by CarolEidt** [comment]
Opened issue #6826 to track the issue of generating a `GT_ADDR` of `TYP_STRUCT`.

**Pull request merged**
