### PR TITLE
Explicitly make our minimum ICU version be the version available in Alpine 3.6

### LINKED ISSUE #27018: Should globalization native shim support older ICU versions on alpine?
The coreclr musl build was moved to now build on alpine-3.9. If people try to use a build of the product that contains latest .NET 5 coreclr on < alpine-3.9 and hits any globalization path, it would fail with: 

```
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
at System.Environment.FailFast(System.String)
at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
at System.Globalization.GlobalizationMode..cctor()
at System.Globalization.GlobalizationMode.get_Invariant()
at System.Globalization.CultureData.CreateCultureWithInvariantData()
at System.Globalization.CultureData.get_Invariant()
at System.Globalization.CultureInfo..cctor()
at System.Globalization.CultureInfo.get_CurrentCulture()
```

The reason for that is because we try to load the ICU version that we compiled against (defined in the headers) and 20+ versions of it. 
https://github.com/dotnet/coreclr/blob/190888373afe4f526de2bd7f366ffe53cced0325/src/corefx/System.Globalization.Native/pal_icushim.c#L57-L58

@janvorli commented:

"_The reason to not to always start from the version 50 (the first one that we can possibly work with and the one present on CentOS 7) was to ensure that we do a minimal amount of scanning when we build for specific distro. Another reason was that on glibc based distros, build from a newer distro can never work on an older one anyways.
The MUSL based distros are different though, build created on a newer Alpine actually works on an older one, so it would make sense to make the initial version constant for MUSL based distros (I would use the version from 3.6)_"

For more details see: https://github.com/dotnet/corefx/pull/41280#issuecomment-537710811 

cc: @wfurt @jkoritzinsky

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes #27018 

cc: @janvorli @wfurt

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
Looks like (as I had a feeling) that we use different libicu versions across platforms, so we can't just directly hard-code the minimum from Alpine 3.6 as our minimum and make the maximum 20 versions newer. @janvorli @wfurt what do you think is the best course of action here?

**Comment by janvorli** [comment]
@jkoritzinsky I didn't mean moving the minimum version for all platforms, only for Alpine. It should stay as it was for glibc based distros.

**Comment by tarekgh** [comment]
@janvorli what is hurt if we keep this for all distors? I understand we build in some distor will not run on older distro but I am not seeing a problem if we keep the min version fixed anyway.

**Comment by janvorli** [comment]
We could possibly keep it fixed, but it would have to be set to 50. That's the version present on CentOS 7 where we build our official builds and that we support. We would just need to do unnecessary number of scans, so it seems better to start at the oldest version we've ever supported. 
Another disadvantage would come when distros start packaging .NET core themselves. The way we have that now, the distros (other than Alpine) would not have to scan at all, since the version they were compiled with is the version that is available on that distro. If we made it constant for those distros, they would always scan unnecessarily.

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by tarekgh** [comment]
@janvorli wouldn't we scan anyway starting from (min version + 20) and we go down till we hit the highest installed version? if we use 50 as the minimum, that shouldn't make any more scans if we find higher version anyway. maybe I am missing something here.

**Comment by janvorli** [comment]
@tarekgh you are right. I've completely forgotten about the fact that we scan from max to min and not the other way.
@jkoritzinsky then we should really use 50 as the minimum version as there is no downside to that.

**Comment by tarekgh** [comment]
Thanks @janvorli 

just to confirm:

```C#
MaxICUVersion = U_ICU_VERSION_MAJOR_NUM + 20; // we should keep using U_ICU_VERSION_MAJOR_NUM here
MinICUVersion  = 50; // This is the change we'll make
```

**Comment by janvorli** [comment]
@tarekgh yes, that's correct.

**Comment by jkoritzinsky** [comment]
I'll update this on Monday with the new min of 50 and max of 20+current.

**Review by tarekgh — APPROVED** [review]

**Comment by xiangzhai** [comment]
:mips-interest

**Pull request merged**
