### PR TITLE
Support FEATURE_EVENT_TRACE override

### PR DESCRIPTION
**Pull request by parjong**
This commit allows users to override FEATURE_EVENT_TRACE variable via CMake option.

In addition, this commit introduces clrfeatures.cmake to eliminate duplication in PAL and Global CMake files.

### CODE REVIEW

**Comment by parjong** [comment]
\CC @hseok-oh

**Comment by parjong** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test please

**Comment by parjong** [comment]
@dotnet-bot test Ubuntu arm Cross Release Build please

**Comment by parjong** [comment]
@dotnet-bot test Ubuntu arm Cross Release Build please

**Comment by parjong** [comment]
@dotnet-bot test Ubuntu arm Cross Release Build please

**Comment by hseok-oh** [comment]
@dotnet-bot test Ubuntu arm Cross Release Build

**Comment by danmosemsft** [comment]
LGTM

**Pull request merged**
