### PR TITLE
Make EmptyArray private

### PR DESCRIPTION
**Pull request by danmosemsft**
Change EmptyArray usage to Array.Empty. This is just consistency.
Also make List<T> use Array.Empty. This has negligible value but is consistent.

@jkotas

### CODE REVIEW

**Comment by jkotas** [comment]
> Also make List use Array.Empty

This makes List constructor measurably slower among other things. It was discussed before quite a lot... .

**Comment by danmosemsft** [comment]
OK, I'll take that out. I thought there might be a reason!

**Comment by jkotas** [comment]
https://github.com/dotnet/coreclr/issues/2801 https://github.com/dotnet/coreclr/pull/1596 https://github.com/dotnet/coreclr/pull/1254

**Comment by danmosemsft** [comment]
This time I added a comment, so we won't have a 5th attempt.

**Comment by danmosemsft** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test please (locked file)

**Comment by jkotas** [comment]
@danmosemsft Could you please resolve the conflicts?

**Pull request merged**
