### PR TITLE
Fix build to work with binutils v2.25.0 on Linux

### PR DESCRIPTION
**Pull request by apanda**
On Linux, when using binutils version 2.25.0, XMM instructions (e.g., movdqa) requires specifying the size of the
operand (e.g., specifying xmmword ptr). With the current code it gives an error: invalid operand for instruction.

This commit changes movdqa occurances to fix the problem.

### CODE REVIEW

**Comment by jkotas** [comment]
LGTM. Thanks!

**Comment by janvorli** [comment]
@apanda I wonder why binutils play any role here. We are not using the gnu assembler to build the assembler code.

**Comment by apanda** [comment]
Sorry, I misattributed, you use clang to build .S file, but even there newer versions seem to require this. 

I think in general, it is correct to give ptr length, and in this case clang seems to error out when you don't. 

For me

```apanda@ghayegh ~/llilc/coreclr-bdb(git)-[remotes/origin/HEAD] % clang --version
clang version 3.6.0
Target: x86_64-unknown-linux-gnu
Thread model: posix```

Logs from a failed build are at http://www.cs.berkeley.edu/~apanda/cclrdbout (search for invalid operand). 

I will add logs from successful build once that is done.

**Comment by janvorli** [comment]
@apanda Ah, thanks for the details. I was really just curious, the change is good to me.

**Comment by jkotas** [comment]
@apanda Could you please resolve the merge confict so that this can be merged?

**Comment by apanda** [comment]
@jkotas Fixed, there were some conflicts due to the ARM checkin.

**Comment by jkotas** [comment]
@apanda  Could you please squash the change into a single commit?

**Comment by apanda** [comment]
@jkotas Done.

**Comment by jkotas** [comment]
Thanks!

**Pull request merged**
