### PR TITLE
[WIP] Add profiler tests

### PR DESCRIPTION
**Pull request by kspawa**
@noahfalk @dotnet/debugger-team Please give feedback about the overall design, about code partition, project based compilation partitioning, refactoring and any other issues I may have missed. This is still WIP so will be doing a lot of cleanup and some amount of refactoring, along with better error messages and verification.

### CODE REVIEW

**Comment by noahfalk** [comment]
I'll probably need to spend some more time looking through it but initial thoughts:
1) I like sharing the code for the base classes as a solution to our old multiple dlls issue that forced all the tests to link against shared library. I assume satellite_initialize in the def file is going away?
2) is using cmake on the todo list? the build seemed surprisingly decoupled from how the rest of coreclr builds
3) Having the specialized profiler dlls in a sub-directory under BaseProfiler seemed a little confusing to me. Perhaps put them in sibling directories instead?
4) I think you updated a little bit of the README but left the rest of it as-is from the sample source? That was a bit confusing, but I assume that is a point in time issue : ) A good README that described the basics of how a test works and how expect developers to add new ones would be very useful.
5) There is a bunch of our legacy code there and there is probably value in not refactoring it too much so that we don't make it really painful to port over new tests from our internal sources. At the same time it would feel a bit of a shame if people writing brand new tests followed some of those old patterns that add complexity but no longer appear to serve much purpose, like the large methodtable abstraction. One thought I had to address that would be to split CorProfiler into two types, CorProfilerBase and a derived type CorProfiler. CorProfiler could have all the current legacy code in it to make porting our old tests easier, whereas CorProfilerBase could just do a bare minimum of defining profiler callbacks as virtual functions and maybe a virtual shutdown function where the test can verify results/cleanup. The idea would be that if you are writing a new test from scratch, CorProfilerBase would be a nice clean starting point for doing that.

**Comment by kspawa** [comment]
@noahfalk Answers inline. Thanks for the quick feedback! Overall I agree there is a lot of cleanup to do. I did not want to wait on getting initial feedback in case something was way off, hence sent an early PR. Am currently working on the below and other issues related to better refactoring and cleaning up the code more.

I'll probably need to spend some more time looking through it but initial thoughts:
 1) I like sharing the code for the base classes as a solution to our old multiple dlls issue that forced all the tests to link against shared library. I assume satellite_initialize in the def file is going away?
[kspawa] Yes it is, as you have noted, there is a lot of cleanup I have to do.
 2) is using cmake on the todo list? the build seemed surprisingly decoupled from how the rest of coreclr builds
[kspawa] Yes it is. I originally planned to have this as a separate repo but I did not want to wait to send a PR till I did the cmake work. It builds on Linux and Windows using build.sh and msbuild. I will make the transition to cmake also.
 3) Having the specialized profiler dlls in a sub-directory under BaseProfiler seemed a little confusing to me. Perhaps put them in sibling directories instead?
[kspawa] Yes, ok.
 4) I think you updated a little bit of the README but left the rest of it as-is from the sample source? That was a bit confusing, but I assume that is a point in time issue : ) A good README that described the basics of how a test works and how expect developers to add new ones would be very useful.
[kspawa] Yes that is also a TODO.
 5) There is a bunch of our legacy code there and there is probably value in not refactoring it too much so that we don't make it really painful to port over new tests from our internal sources. At the same time it would feel a bit of a shame if people writing brand new tests followed some of those old patterns that add complexity but no longer appear to serve much purpose, like the large methodtable abstraction. One thought I had to address that would be to split CorProfiler into two types, CorProfilerBase and a derived type CorProfiler. CorProfiler could have all the current legacy code in it to make porting our old tests easier, whereas CorProfilerBase could just do a bare minimum of defining profiler callbacks as virtual functions and maybe a virtual shutdown function where the test can verify results/cleanup. The idea would be that if you are writing a new test from scratch, CorProfilerBase would be a nice clean starting point for doing that.
[kspawa] Good idea. Once I have finished with the initial set of cleanup and refactoring I will spend some time on this before I port the rest of the tests.

**Comment by danmosemsft** [comment]
@kspawa hello! do you plan to continue work on this PR?

**Comment by noahfalk** [comment]
Adding Lorezo (@lt72) who also has some context here.

**Comment by lt72** [comment]
We will resume this work in a few weeks, most likely around mid-november

**Comment by jkotas** [comment]
Closing old inactive PRs. @lt72 whoever gets to work on this again should submit a new one once ready.

**Comment by lt72** [comment]
Assigning to Sasha for completing work

**Pull request closed without merging**
