### PR TITLE
[RyuJIT/armel] Move returned float to float reg

### LINKED ISSUE #12574: [RyuJIT/armel] Failed CodeGenBringUpTests with wrong results
A sub-issue for #11822

These tests successfully run but fails with wrong results.

- JIT/CodeGenBringUpTests/DblRem/DblRem.sh
- JIT/CodeGenBringUpTests/FPMath/FPMath.sh

### PR DESCRIPTION
**Pull request by wateret**
Fix #12574

### CODE REVIEW

**Comment by wateret** [comment]
The returned double value must be moved to a double register before it is used.

```
G_M36738_IG02:
000008  2200           movs    r2, 0
00000A  F244 0300      movw    r3, 0x4000
00000E  F2C4 0354      movt    r3, 0x4054
000012  EC43 2B14      vmov.i2d d8, r2, r3
000016  EC51 0B14      vmov.d2i r0, r1, d8
00001A  2200           movs    r2, 0
00001C  F248 0300      movw    r3, 0x8000
000020  F2C4 0346      movt    r3, 0x4046
000024  EC43 2B14      vmov.i2d d8, r2, r3
000028  EC53 2B14      vmov.d2i r2, r3, d8
00002C  F642 1EA0      movw    lr, 0x29a0
000030  F2CB 5E98      movt    lr, 0xb598
000034  F8DE E000      ldr     lr, [lr]
000038  47F0           blx     lr               // BringUpTest:DblRem(double,double):double
00003A  EC41 0B10      vmov.i2d d0, r0, r1.     ----> ADDED!
00003E  ED8D 0B00      vstr    d0, [sp] // [V00 loc0]
000042  EC51 0B10      vmov.d2i r0, r1, d0
```

**Comment by wateret** [comment]
I thought about `double` to be MultiRegRetVal, but in other places we treat double as a single register, and also easier to generate `vmov.i2d` instruction by not doing so.

**Comment by BruceForstall** [comment]
cc @dotnet/jit-contrib @dotnet/arm32-contrib

**Comment by BruceForstall** [comment]
@wateret you've got compile errors:
```
error C2065: 'INS_vmov_i2d': undeclared identifier [D:\j\workspace\checked_windo---f6dc6fe4\bin\obj\Windows_NT.x64.Checked\src\jit\protononjit\protononjit.vcxproj]
```

**Comment by wateret** [comment]
@dotnet-bot test this please

**Comment by wateret** [comment]
@dotnet-bot Test OSX10.12 x64 Checked Build and Test please
@dotnet-bot Test Ubuntu x64 Checked Build and Test please

**Pull request merged**
