### PR TITLE
Fix Dictionary CopyTo regression

### PR DESCRIPTION
**Pull request by benaadams**
Also List set version

/cc @jkotas @stephentoub

### CODE REVIEW

**Comment by danmosemsft** [comment]
The + i caused worse codegen?

**Comment by benaadams** [comment]
> The + i caused worse codegen?

Better codegen, but items could be skipped when `hashCode < 0` so the array index doesn't always increase; however `i` always increases so it would copy both empty entries (dict side) and out of bounds (array side)

**Comment by jkotas** [comment]
@Anipik This was missed by the CoreCLR->CoreFX mirror.

**Comment by benaadams** [comment]
Think there were 3 that had it but they weren't merged https://github.com/dotnet/corefx/pull/28632 https://github.com/dotnet/corefx/pull/28633 https://github.com/dotnet/corefx/pull/28634

**Comment by Anipik** [comment]
@jkotas @benaadams I was testing something with mirror and somehow skipped this PR. I have started the Pr for it

**Pull request merged**
