### PR TITLE
Add documentation for CI Trigger Phrases

### PR DESCRIPTION
**Pull request by wtgodbe**
We don't currently have any documentation for all of the CI/Jenkins trigger phrases that are defined in netci.groovy, which renders them less useful than they could be. This is a first crack at a document to contain all of those phrases.

### CODE REVIEW

**Comment by wtgodbe** [comment]
@mmitche PTAL

**Comment by sergiy-k** [comment]
Thank you!

**Comment by mmitche** [comment]
Awesome!

________________________________

**Comment by mmitche** [comment]
LGTM

**Comment by adityamandaleeka** [comment]
LGTM

**Comment by wtgodbe** [comment]
Merging

**Pull request merged**
