### PR TITLE
Add the coreclr blob feed as a restore source for test builds.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
The test projects didn't have the dotnet-coreclr blob feed. As a result, #22691 is failing to build when upgrading packages used by `build_against_pkg_dependencies.csproj` to versions only available on the dotnet-coreclr blob feed. This should allow #22691 to pass CI and be merged in.

### CODE REVIEW

**Comment by hoyosjs** [comment]
We'd need to delete the `NuGet.config` under `src` and `tests/src` and make this the root one 

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
  </packageRestore>
  <packageSources>
    <clear />
    <add key="dotnet-coreclr" value="https://dotnetfeed.blob.core.windows.net/dotnet-coreclr/index.json" />
    <add key="dotnet-core" value="https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json" />
    <add key="myget.org dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
  <disabledPackageSources>
    <clear />
  </disabledPackageSources>
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
</configuration>
```

**Comment by jkoritzinsky** [comment]
I'm all good with simplifying it to use the one NuGet.config file. I'll combine them and test out the build.

**Comment by hoyosjs** [comment]
@dotnet-bot test this

**Comment by hoyosjs** [comment]
@dotnet-bot test this please

**Comment by hoyosjs** [comment]
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test (Jit - Tiered compilation=0)

**Comment by hoyosjs** [comment]
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test (Jit - TieredCompilation=0)

**Comment by hoyosjs** [comment]
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test (Jit - TieredCompilation=0)

**Pull request merged**
