### PR TITLE
Revert EncodingForwarder

### PR DESCRIPTION
**Pull request by tarekgh**

### CODE REVIEW

**Comment by tarekgh** [comment]
@jkotas this is the same change we did in 2.0 and in corert but now we need to do it in 1.1. please try to reply quick as today is the deadline to get this in for 1.1. thanks for your help.

cc @danmosemsft

**Comment by jkotas** [comment]
This is churning a lot more than just the encoding forwarder changes. Looks risky for servicing fix to me.

**Comment by tarekgh** [comment]
@jkotas what exactly the changes you are seeing not related so I can revert it? is it removing the security attributes? or something else?

**Comment by tarekgh** [comment]
ok, I'll return back the security stuff.

**Comment by jkotas** [comment]
Ideally, the change would be clean reverts of the commits that introduced the EncodingForwarder so that it is easy to verify that nothing else fell through the cracks.

**Comment by tarekgh** [comment]
> Ideally, the change would be clean reverts of the commits that introduced the EncodingForwarder so that it is easy to verify that nothing else fell through the cracks.

That is what I have done in the first place but I have manually after that removed the security attributes. so I am undoing this now. will send update soon

**Comment by jkotas** [comment]
I still see bits and pieces of 2.0 changes in the delta.

Here is what I have done:

```
git checkout release/1.1.0
git revert 467f06d6f01deb4905a901a9d337a8dfdef817e1
git revert a64020c8825770ccc8a83d200783a979fbac6434
git revert a4192dc80352345be2c250b4c33b5b72680069d6
git revert 4fd1bfef80fbd4ccb7625196cd841f4fa6415282
git revert 1f9cd6744fcc4c14ee402ba24e26a1b9e4ce8fcc
git revert e1818e622933da083a241963e69f36d5d6d89063
git revert ad1ad35dc03aad4822db57bcbbe1ce7b9f4958ce
git revert f09b521e334fcdf6c279466724a2e6b8f4642cce
git revert 95ff597b07cf40532f6af52beab076bd80332b0f
git revert 77fa0fb69c9113909fbbe3f896779eab26d9e250
git revert 372fcd3cfc8115233040a787e36d020edd919a22
git revert ab47c2281299f464ecddb1d04c292a37b96646dc
git revert 860434db541daf533b43491280774dc4274590b8
git revert f83ecbead207000825555393287dafbca8259137
git revert 6de8ede4e8ca98a382b066ba45a172e3f8ce2821
git revert 7c771b8b8462d0b95130cabfe0de5efbf64278bc
git revert 088943185a0469d936a8c0b6e235bdc715e6fc25
git revert fa55fd74ae3e9374468d32db7371c82e6ae13593
git revert 56c687e0afefc6c223dc0d296a4c64ab5465ebdd
git revert 9668b5f6275f9dbf24ecd0767d5d4817cde16322
git revert e61479088e1ba1f1d8756b8da1a352d518c015c8
git revert ebfc3ce64205a2a5b14c9fe487659ed02c1f3486
```

And then I have compared it with what you got.

**Comment by tarekgh** [comment]
@jkotas let me know know if you still see any differences. thanks.

**Comment by tarekgh** [comment]
test Linux ARM Emulator Cross Release Build please

**Comment by tarekgh** [comment]
test OSX x64 Checked Build and Test please

**Comment by danmosemsft** [comment]
@tarekgh I didn't notice this was for 1.1. I'll create a revert PR. Apologies. Let me know whether it was in fact approved, and I'll not submit the revert.

**Comment by danmosemsft** [comment]
Replaced by https://github.com/dotnet/coreclr/pull/10829

**Pull request merged**
