### PR TITLE
Clean up Unix twowaypipe code

### PR DESCRIPTION
**Pull request by adityamandaleeka**
This change gets rid of the special windefs.h header that was being used to compile the Unix version of twowaypipe.cpp. Instead, we will now just use pal.h. This sets up some other changes I'll be making to this area which will involve calling one or more PAL functions from `GetPipeName`.

The `remove` function from stdio.h is identical to `unlink` if the path doesn't name a directory, so with this change we'll just call `unlink` on the pipes. This together with the `snprintf` change means we no longer need to include stdio.h.

I also removed `PAL_unlink` while I was at it, since it just wraps `unlink`.

@mikem8361

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
The last commit is just a typo fix unrelated to this PR but I noticed it in the build output and it was bugging me. :smile:

**Comment by mikem8361** [comment]
LGTM

**Comment by adityamandaleeka** [comment]
I'm looking into the OS X build issues.

**Comment by krytarowski** [comment]
It broke on NetBSD:

```
In file included from /tmp/pkgsrc-tmp/wip/coreclr-git/work/coreclr/src/debug/debug-pal/unix/twowaypipe.cpp:10:
In file included from /usr/include/sys/stat.h:56:
In file included from /usr/include/sys/time.h:300:
In file included from /usr/include/sys/select.h:62:
/usr/include/time.h:75:8: error: redefinition of 'tm'
struct tm {
       ^
/tmp/pkgsrc-tmp/wip/coreclr-git/work/coreclr/src/debug/debug-pal/../../pal/inc/pal.h:6349:8: note: previous definition is here
struct tm {
       ^
1 error generated.
```

I'm working on a fix.

**Pull request merged**
