### PR TITLE
Add corefx testing with JitStress=1 on Windows

### PR DESCRIPTION
**Pull request by sejongoh**
@mmitche Could you please review the changes?

This changeset adds a test job copying corefx and run corefx/build.cmd with JitStress=1 and coreclr under test.  Copying corefx depends on https://github.com/dotnet/corefx/pull/5857 which archives corefx directory.

### CODE REVIEW

**Comment by sejongoh** [comment]
@dotnet-bot test ci please

**Comment by sejongoh** [comment]
@dotnet-bot test ci please.

**Comment by sejongoh** [comment]
@mmitche I have updated the script as you recommended.

**Comment by mmitche** [comment]
You're calling the corefx build with Configuration=Checked, which I don't think exists.  Otherwise LGTM

**Comment by sejongoh** [comment]
@mmitche Thanks for review! I think that I also missed "cd .." after running corefx build.cmd. I have fixed them with a new commit.

**Comment by mmitche** [comment]
you may not need the cd .., as each buildStep is a separate invocation of cmd.exe from workspace root.

**Comment by mmitche** [comment]
Anyways, LGTM after removing that, squash before you commit.

**Comment by sejongoh** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Comment by sejongoh** [comment]
@dotnet-bot test Windows_NT x86 Release Build

**Comment by sejongoh** [comment]
@dotnet-bot test Windows_NT x86 Debug Build

**Comment by sejongoh** [comment]
@dotnet-bot test Windows_NT x64 Release Build and Test

**Comment by sejongoh** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test

**Comment by sejongoh** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Comment by mmitche** [comment]
@sejongoh You don't need to do that.  Your change has no effect on anything currently being run

also, to restart the whole thing you can comment '@dotnet-bot tets this please' (without the spelling error)

**Comment by sejongoh** [comment]
@mmitche Thanks! I also thought that my changes shouldn't affect anything but just wanted to make sure :)

**Pull request merged**
