### PR TITLE
Centralize versioning and stabilization of nuget packages.

### PR DESCRIPTION
**Pull request by gkhanna79**
We will use a central location to set the version of packages produced in the repo. If a package needs to override, then it can explicitly specify the PackageVersion.

Also, setup a central flag, StabilizePackageVersion, that can be flipped to true to generate stabilized version packages.

@weshaggard @ericstj PTAL

CC @RussKeldorph

### CODE REVIEW

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
@mmitche How can I trigger builds here?

**Comment by mmitche** [comment]
You did trigger builds.

**Comment by RussKeldorph** [comment]
Nice.  LGTM.

**Comment by weshaggard** [comment]
LGTM

**Pull request merged**
