### PR TITLE
Add headers to all md*, v3binder*, and ceefgen vcxproj

### PR DESCRIPTION
**Pull request by 4creators**
Work toward #14884

### CODE REVIEW

**Comment by alexperovich** [comment]
@dotnet-bot test Windows_NT x64 full_opt ryujit CoreCLR Perf Tests Correctness please
@dotnet-bot test Windows_NT x86 full_opt ryujit CoreCLR Perf Tests Correctness please
@dotnet-bot test Windows_NT x86 min_opt ryujit CoreCLR Perf Tests Correctness please

**Comment by 4creators** [comment]
Known problem caused Ubuntu failure:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_no_tiered_compilation_innerloop_flow_prtest/2264/

```
Unhandled Exception: System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
     at System.Collections.Generic.Stack`1.Enumerator.MoveNext()
     at Xunit.Sdk.DisposalTracker.Dispose() in C:\projects\xunit\src\xunit.execution\Sdk\DisposalTracker.cs:line 26
     at Xunit.Sdk.ExtensibilityPointFactory.Dispose() in C:\projects\xunit\src\xunit.execution\Sdk\ExtensibilityPointFactory.cs:line 54
     at Xunit.Sdk.TestFramework.Dispose() in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\TestFramework.cs:line 49
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Threading.ThreadPoolWorkQueue.Dispatch()
  Aborted (core dumped)
```

**Comment by 4creators** [comment]
@dotnet-bot test Ubuntu x64 Checked no_tiered_compilation_innerloop Build and Test

**Comment by 4creators** [comment]
@dotnet-bot test x64_checked_ubuntu_no_tiered_compilation_innerloop_flow_prtest

**Comment by 4creators** [comment]
@dotnet-bot test Ubuntu x64 Checked no_tiered_compilation Innerloop Build and Test

**Comment by 4creators** [comment]
@dotnet-bot test Ubuntu x64 Checked no_tiered_compilation_innerloop Build and Test

**Comment by 4creators** [comment]
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test (Jit - TieredCompilation=0)

**Comment by 4creators** [comment]
@jkotas @janvorli This is one of the last PRs adding headers to vcxproj files. CI is green. PTAL

**Comment by 4creators** [comment]
@jkotas @janvorli Ping PTAL - PR has one approval and CI is green.

**Pull request merged**
