### PR TITLE
Update Microsoft.DotNet.BuildTools.CoreCLR to version 1.0.2.

### PR DESCRIPTION
**Pull request by AlexGhiondea**
This version updates BclRewriter.exe with a copy that can run on Dev15 RC

### CODE REVIEW

**Comment by AlexGhiondea** [comment]
@dotnet-bot test this please.

**Comment by AlexGhiondea** [comment]
@dotnet-bot test this please.

**Comment by DickvdBrink** [comment]
Did this fix #950? And therefore also #30?

**Comment by jkotas** [comment]
Thanks for pointing it out ... I have opened #1033 for the next issue blocking #30

**Pull request merged**
