### PR TITLE
Changes to heap allocation in PAL

### PR DESCRIPTION
**Pull request by adityamandaleeka**
The current scheme for allocating memory in HeapAlloc involves malloc’ing more space than we really need and adding some metadata (a magic number and a size) in front of the actual data, and returning a pointer to the location in the allocated chunk that points to the beginning of the “real” data. One of the implications of this is that all users either have to have special knowledge of this allocation scheme or have to call the PAL free when they need to free this memory. This is not feasible in scenarios like reverse PInvoke where a user’s native code can get a pointer to memory allocated by a managed function and try to free it.

This change solves this problem by removing the magic number and size information from the beginning of the allocated memory range and returning a proper pointer to the beginning of the allocated memory. One implication of this was the need to remove the HeapSize API from PAL, which was relying on the size information being present.

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
@sergiy-k @jkotas @gregg-miskelly

**Comment by sergiy-k** [comment]
LGTM

**Comment by gregg-miskelly** [comment]
:+1:

**Comment by jkotas** [comment]
HeapReAlloc is failing... looks related to this change.

**Comment by adityamandaleeka** [comment]
@jkotas About the name change, it appears that the type of that argument in the Windows API used to be DWORD. They changed it at some point but didn't change the 'dw' prefix. However, I'll undo the name change since we're trying to match what they have.

Also, I'm looking at that test failure. The expectation of the test directly contradicts an explicit check we have in `CorUnix::InternalRealloc`, where if the `szSize` parameter is 0 we always return a null pointer and free whatever was at the memory block previously (if anything). The test, on the other hand, passes 0 for `szSize` and fails if a null pointer is returned. I tried this out on Windows and it looks like HeapRealloc doesn't return NULL in this case.

The reason the test was working before was that we never tried to Realloc to 0 since the minimum size of an allocation was the size of the extra data we prepended (`HEAP_SIZEINFO_SIZE`).

**Comment by kouvel** [comment]
I wasn't able to push a commit into @adityamandaleeka's branch, so I have sent a separate PR including all of the changes. https://github.com/dotnet/coreclr/pull/1646

**Pull request merged**
