### PR TITLE
Update CoreFX CI packages to NetcoreApp3

### PR DESCRIPTION
**Pull request by A-And**
Updates restored packages. 
@jkotas mentioned some failures we're seeing are due to CoreFX mismatch - setting `TargetFramework`  before specifying dependencies restored `netstandard` versions of libraries. Moving `TargetFramework` up seems to have fixed the issue.

### CODE REVIEW

**Comment by A-And** [comment]
@dotnet-bot test Windows_NT x64 Release CoreFX Tests please
@dotnet-bot test Windows_NT x64 Checked CoreFX Tests please

**Comment by A-And** [comment]
@dotnet-bot test this please

**Comment by A-And** [comment]
A substantial amount of failures were fixed because of this change. 
@jkotas @RussKeldorph  - does the current exclusion list look reasonable to you?

**Comment by jkotas** [comment]
Yes, it looks a lot better.

**Pull request merged**
