### PR TITLE
 Add retry logic for setup of dotnet cli

### PR DESCRIPTION
**Pull request by dseefeld**
Copy init-tools.sh retry logic from corefx.  Also adding display_error_message() function from 

Fixes dotnet/core-eng#1966

### CODE REVIEW

**Comment by weshaggard** [comment]
Can you please wait until https://github.com/dotnet/coreclr/pull/14892 is merged to update this script in CoreCLR?

That PR will also fix the error your seeing in CI.

**Comment by dseefeld** [comment]
Yes.  I'll wait for #14892

**Comment by dseefeld** [comment]
@dotnet-bot test this please

**Comment by dseefeld** [comment]
@weshaggard @dagood Can you take a look at this?  Thanks

**Pull request merged**
