### PR TITLE
Fix superpmi arm64 build

### PR DESCRIPTION
**Pull request by BruceForstall**
@briansull PTAL

### CODE REVIEW

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked
@dotnet-bot test Windows_NT arm64 Release

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked pri1r2r

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm64 Checked
@dotnet-bot test Windows_NT arm64 Release
@dotnet-bot test Windows_NT arm64 Checked pri1r2r

**Comment by briansull** [comment]
@mmitche, @jashook - We can't get the Arm64 testing tasks to start on this PR

**Comment by mmitche** [comment]
@briansull looking into it.

**Comment by mmitche** [comment]
@briansull I think the regex may be incorrect (it may be missing a .*).  Let me try something.

**Comment by mmitche** [comment]
@dotnet-bot test Windows_NT arm64 Checked pri1r2r

**Comment by mmitche** [comment]
@dotnet-bot test Windows_NT arm64 Checked
@dotnet-bot test Windows_NT arm64 Release
@dotnet-bot test Windows_NT arm64 Checked pri1r2r

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked
@dotnet-bot test Windows_NT arm64 Release

**Comment by BruceForstall** [comment]
@mmitche @jashook Another similar failure?
```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomizations\masm.targets(50,5): error MSB4175: The task factory "XamlTaskFactory" could not be loaded from the assembly "Microsoft.Build.Tasks.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Could not find file 'C:\Users\dotnet-bot\AppData\Local\Temp\omkjtk0z.dll'. [D:\j\workspace\arm64_cross_r---b73c1291\bin\obj\Windows_NT.arm64.Release\src\debug\ee\wks\cordbee_wks.vcxproj]
16:35:28 C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomizations\masm.targets(50,5): error MSB4175: The task factory "XamlTaskFactory" could not be loaded from the assembly "Microsoft.Build.Tasks.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Could not find file 'C:\Users\dotnet-bot\AppData\Local\Temp\edkod20e.dll'. 
```

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm64 Cross Release Build and Test

**Comment by jashook** [comment]
@BruceForstall yes, same problem

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm64 Release

**Comment by mmitche** [comment]
Ack..this error is the WORST.  I'm actively trying to figure out what's going on but it's more than a little difficult.

**Comment by gkhanna79** [comment]
@dotnet-bot test Windows_NT arm64 Cross Release Build and Test please

**Comment by mmitche** [comment]
@dotnet-bot test @dotnet-bot test Windows_NT arm64 Release

**Comment by BruceForstall** [comment]
I'm ignoring the test run failures. The build at least is fixed.

**Pull request merged**
