### PR TITLE
Fix shutdown A/V issue when IBC logging with the Music Store app

### PR DESCRIPTION
**Pull request by briansull**
This app continues to run managed code on other threads after the Main thread exits and enters shutdown.
This can lead to an A/V on the threads that are still running (and logging) since we set a a pointer to null after we finished writing out the IBC data for an assembly.

We now block all IBC logging during the time that we are writing out the IBC data.

### CODE REVIEW

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT Release pri1r2r
@dotnet-bot test Windows_NT Checked pri1r2r

**Comment by briansull** [comment]
PTAL @adiaaida @dpodder @AndyAyersMS @russellhadley

**Comment by dpodder** [comment]
LGTM, pending signoff from someone who's more familiar with the runtime (I am not familiar with its workings at all 😝)

**Comment by briansull** [comment]
This issue is a blocker for  @adiaaida 
I promised to check in the fix tonight

**Pull request merged**
