### PR TITLE
Removed unused 'Stack Walking' code

### PR DESCRIPTION
**Pull request by mattwarren**
As fair as I can tell `ECWGCFCrawlCallBack(..)` is not wired-up anywhere 

(I've successfully compiled CoreCLR with this change on Windows, `x86` and `x64`)

### CODE REVIEW

**Comment by mattwarren** [comment]
> LGTM, thank you for spotting this.

No problem, I ran across it whilst researching a future blog post on 'Stack Walking'

BTW thanks for [this comment](https://github.com/dotnet/coreclr/issues/177#issuecomment-73803242) it helped me understand the differences in native v. managed unwinding. Also, kudos to you (and others) who've worked on the 'stack walking' related code, it's very complex!! (x86 v x64, Unix v Windows, ABI's etc)

**Comment by janvorli** [comment]
@mattwarren if you'll need some more details on the stack unwinding in the future, please let me know, I'll be happy to help.

**Comment by mattwarren** [comment]
> if you'll need some more details on the stack unwinding in the future, please let me know, I'll be happy to help.

Thanks! Well if you've got the time to have a look, the post is [available here](https://mattwarren.org/2019/01/21/Stackwalking-in-the-.NET-Runtime/), so any comments/corrections would be gratefully received?

I'll post some questions later on today, although here's one for starters:

- Just how hard is it to develop when 'stack-walking' isn't available for a given platform, i.e. Linux? (I'd image it's pretty hard, if I understand it correctly, no stack-walking means no GC, no exception handling and no stack-traces!!)

**Comment by jkotas** [comment]
> when 'stack-walking' isn't available for a given platform

There are two cases:
- There is no standard stackwalker built into the platform that the unmanaged CoreCLR code can be walked with. Example of such platform is Windows x86 (Linux has libunwind). It is not a major complication. The only CoreCLR part that needs to be adjusted for this are Helper Method Frames that glue managed and C/C++ code together.

- Platform does not provide the low-level access to stack or registers. Examples of such platforms are WebAssembly, or some of the Apple devices (e.g. Apple Watch). In worst case, the stackwalking needs to be simulated for these platforms to make exceptions and GC work well by manually maintaining a linked list of stack frames.
 
Another option for these constrained environments is to have no exceptions (exception = abort), and limited GC that can only run once the code returns to message loop and there are no object references on stack. Variants of this option are used by game engines scripted in C#.

**Pull request merged**
