### PR TITLE
Fixed tests build on Linux (#2)

### PR DESCRIPTION
**Pull request by rartemev**
New PR for changes from #10532.

Fixed file names in the csproj scripts, fixed ilasm issue.

>Fixed building tests on Linux (issue #8891)
>
> To build tests use the following command:
> ~> bash ./build-test.sh
> To build and run tests after:
> ~> bash ./build-test.sh runtests
> To rebuild tests:
> ~> bash ./build-test.sh rebuild

### CODE REVIEW

**Comment by rartemev** [comment]
@dotnet/jit-contrib please review and feel free to run any required CI jobs to avoid the mistakes I made in the previous PR.

**Comment by rartemev** [comment]
@dotnet-bot help

**Comment by rartemev** [comment]
@dotnet-bot test CentOS7.1 x64 Release Priority 1 Build and Test
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test

**Comment by rartemev** [comment]
@dotnet-bot test Tizen armel Cross Release Build

**Comment by RussKeldorph** [comment]
An informal test on two machines with the same specs (hopefully comparable in perf):
- Windows build-test.cmd duration: 17:28
- Ubuntu 16.04 build-test.sh duration: 75:00

**Comment by rartemev** [comment]
[Pipebuild](https://devdiv.visualstudio.com/DevDiv/_build?tracking_data=eyJTb3VyY2UiOiJFbWFpbCIsIlR5cGUiOiJOb3RpZmljYXRpb24iLCJTSUQiOiJtcy52c3MtYnVpbGQuYnVpbGQtcmVxdWVzdGVkLXBlcnNvbmFsLXN1YnNjcmlwdGlvbiIsIlNUeXBlIjoiQ09OIiwiUmVjaXAiOjEsIl94Y2kiOnsiTklEIjoxMjczNTg1OCwiTVJlY2lwIjoibTA9MSAiLCJBY3QiOiIxODFiZWQwYy05MWEwLTQwNDMtOGJjZC1hZDlhZjlmNWFhYzEiLCJmZiI6IkNHRCJ9fQ%3D%3D&buildId=778349)  has passed.

**Comment by vellozzi** [comment]
@rartemev , We're trying to build the tests on Linux.  I can see that this PR is merged into master, but not the release/1.0.0 or release/2.0.0 branches.  If I cherry-pick the commit for this PR into the release/2.0.0 branch there are no conflicts and the tests build and pass.

Is this PR safe to merge int the release/2.0.0 branch?

**Comment by vellozzi** [comment]
@RussKeldorph, can you comment on my previous post?

**Comment by RussKeldorph** [comment]
@vellozzi The change created prior to release/2.0.0 but was held back due to unknown risk.  I don't have any reason to believe it isn't safe, but I'm not absolutely certain.

**Comment by vellozzi** [comment]
Thanks.

**Pull request merged**
