### PR TITLE
Issue #5391 "libsosplugin.so getting an RPATH of /usr/lib/llvm on RHEL

### PR DESCRIPTION
**Pull request by mikem8361**
This adds an $ORIGIN RPATH for all xplat platforms.

### CODE REVIEW

**Comment by mikem8361** [comment]
@janvorli and @omajid review?

**Comment by mikem8361** [comment]
@janvorli and @omajid review?

**Comment by mikem8361** [comment]
@dotnet-bot test  OSX x64 Checked Build and Test

**Comment by janvorli** [comment]
LGTM

**Comment by mikem8361** [comment]
@jkotas what do you think of this simple change?

**Comment by jkotas** [comment]
LGTM

**Pull request merged**
