### PR TITLE
Ensure that we check for implicit ivals for single argument intrinsics before the SIMDScalar handling.

### PR DESCRIPTION
**Pull request by tannergooding**
### Description

Certain intrinsic functions which took one argument, had an implicit immediate value , and were marked as `SIMDScalar` were not being handled correctly in codegen.

### Customer Impact

Customers using functions qualifying under the above conditions would get invalid results in their program.

### Regression?

Yes, as per the description.

### Risk

Low. This just reorders the branch statements and the list of intrinsics that are impacted is small and well-defined: there are 102 intrinsics marked `SIMDScalar` and only 7 of them have both an implicit immediate value and take one argument.

### CODE REVIEW

**Comment by tannergooding** [comment]
CC. @CarolEidt, @AndyAyersMS 

This is the backport of https://github.com/dotnet/coreclr/pull/25905 to release/3.0. This needs @MeiChin-Tsai's approval as well, correct?

**Comment by AndyAyersMS** [comment]
> This needs @MeiChin-Tsai's approval as well, correct?

At a minimum -- there may be more process now.

**Comment by danmosemsft** [comment]
> At a minimum -- there may be more process now.

It needs to get ok from Tactics on Tues.

**Comment by danmosemsft** [comment]
Approved by tactics for 3.0, @wtgodbe or @Anipik will merge when branch opens for preview 9.

**Comment by danmosemsft** [comment]
(assuming CI is green)

**Comment by wtgodbe** [comment]
Branch is open, merging

**Pull request merged**
