### PR TITLE
Enable ReadyToRun for Windows CoreCLR

### PR DESCRIPTION
**Pull request by janvorli**
This change enables the FEATURE_READYTORUN for CoreCLR on Windows.

### CODE REVIEW

**Comment by janvorli** [comment]
@jkotas Can you take a look please?

**Comment by jkotas** [comment]
LGTM

**Comment by richlander** [comment]
I'll pretend to be @kangaroo this time.

"Ready to Run" sounds like Microsoft feature jargon. What is it? @janvorli @jkotas

**Comment by jkotas** [comment]
It is a flavor of native images - [command line switch of crossgen]( https://github.com/dotnet/coreclr/blob/master/src/tools/crossgen/crossgen.cpp#L166). We do plan to add docs as part of #227.

**Pull request merged**
