### PR TITLE
Rename all xxx.ni.dll's to xxx.dll for Helix Crossgen runs

### PR DESCRIPTION
**Pull request by wtgodbe**
CC @gkhanna79. Have tested this locally & it appears to work - the jobs I sent to Helix passed.

### CODE REVIEW

**Comment by wtgodbe** [comment]
@gkhanna79 I just updated this change

**Comment by gkhanna79** [comment]
Does Helix R2R test job pass with this?

**Comment by wtgodbe** [comment]
@gkhanna79 yes

**Comment by gkhanna79** [comment]
Excellent, please merge this!


Thanks,
Gaurav
________________________________

**Pull request merged**
