### PR TITLE
Cleanup VS2013 reference

### PR DESCRIPTION
**Pull request by gkhanna79**

### CODE REVIEW

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
@mmitche Is dotnet-bot not accepting requests to restart PR?

**Comment by mmitche** [comment]
@gkhanna79 It did restart them when you commented last, but they failed really quickly due to package restore issues

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
Also due to some inefficiencies in the plugin that the maintainer is resolving, it may take a bit of time for everything to requeue.

**Pull request merged**
