### PR TITLE
Fix Unable to step through Visual Studio remote debugger with coreclr xecutables on Nano Server 

### PR DESCRIPTION
**Pull request by mikem8361**
Needed to add back a dummy version of ICorDebugLegacyNetCFHostCallbackInvoker_PrivateWindowsPhoneOnly interface so
VS doesn't get the QI failure and stop working by not calling the "Continue" method.

Issue #7316

### CODE REVIEW

**Comment by gkhanna79** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build  please

**Comment by gkhanna79** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by gkhanna79** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test  please

**Comment by mikem8361** [comment]
@dotnet-bot test please

**Comment by mikem8361** [comment]
@dotnet-bot help

**Comment by mikem8361** [comment]
@dotnet-bot test this please

**Comment by mikem8361** [comment]
It looks like the 1.1.0 branch is having problems. Even without my changes it looks like almost all the tests are failing with something like:

Stacktrace
MESSAGE:
BEGIN EXECUTION /mnt/j/workspace/dotnet_coreclr/release_1.1.0/checked_ubuntu_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun AddMemoryPressureTest.exe TooSmallTest Passed Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.InteropServices, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040 (FUSION_E_REF_DEF_MISMATCH)) at AddMemoryPressureTest.TooLargeTest() at AddMemoryPressureTest.RunTest() at AddMemoryPressureTest.Main() ./AddMemoryPressureTest.sh: line 124: 26486 Aborted (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" AddMemoryPressureTest.exe $CLRTestExecutionArguments Expected: 100 Actual: 134 END EXECUTION - FAILED
+++++++++++++++++++
STACK TRACE:

**Comment by gkhanna79** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by mikem8361** [comment]
Rerunning the tests isn’t going to help. It looks like there is a problem with the 1.1.0 branch even without my changes.

**Comment by gkhanna79** [comment]
The branch was clean yesterday, so I am trying to understand where things are off.

**Comment by mikem8361** [comment]
The test failures seem to indicate that the problem is with the corefx side.  It isn’t obvious to me how the CI jobs get the corefx bits.

**Comment by gkhanna79** [comment]
@weshaggard @ericstj @dagood Do you have thoughts on this?

**Comment by ericstj** [comment]
This is caused by my change to restrict the InteropServicies API to netcoreapp1.1 specifically.
https://github.com/dotnet/corefx/pull/11886/files#diff-91c748d760bdb9d0fd8cf566300cedcbR4

Whatever build process you are using is building against old prerelease packages but then running on newer pre-release bits.

**Comment by dagood** [comment]
Auto-upgrade hasn't been merged in a while (https://github.com/dotnet/coreclr/pull/7241, explains the older compiling), but I don't know why tests would be running against newer bits.

**Comment by gkhanna79** [comment]
https://github.com/dotnet/coreclr/pull/7241 is ready for merge. should it be merged?

**Comment by dagood** [comment]
It sounds like merging #7241 and rerunning CI here would fix this problem, but we should also investigate why newer bits were used than were built with--I'd be surprised if that was intentional.

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
I have merged that PR and restarted this one.

**Comment by gkhanna79** [comment]
@mikem8361 The PR is green. I am merging this in as it was approved.

CC @leecow @Petermarcu

**Pull request merged**
