### PR TITLE
Avoid wasteful concatenation in SignatureHelper.ToString

### PR DESCRIPTION
**Pull request by jamesqo**
This is more of a method meant for debugging, but every bit helps. Additionally the newer code is clearer.

### CODE REVIEW

**Comment by justinvp** [comment]
`MethodBuilder.ToString` has similar unnecessary concatenations. Want to add that to this PR?

`MethodBuilder.ToString` actually calls `SignatureHelper.ToString`; maybe a new `internal void ToString(StringBuilder sb)` could be added to `SignatureHelper` that its `ToString` and `MethodBuilder.ToString` could call, passing the `StringBuilder` to append to.

Something like:

```c#
        public override String ToString()
        {
            StringBuilder sb = new StringBuilder();
            ToString(sb);
            return sb.ToString();
        }

        internal void ToString(StringBuilder sb)
        {
            Contract.Requires(sb != null);

            sb.Append("Length: ").Append(m_currSig).AppendLine();

            if (m_sizeLoc != -1)
            {
                sb.Append("Arguments: ").Append(m_signature[m_sizeLoc]).AppendLine();
            }
            else
            {
                sb.AppendLine("Field Signature");
            }

            sb.AppendLine("Signature: ");
            for (int i = 0; i <= m_currSig; i++)
            {
                sb.Append(m_signature[i]).AppendLine("  ");
            }

            sb.AppendLine();
        }
```

And in `MethodBuilder.ToString`:

```c#
        public override String ToString()
        {
            StringBuilder sb = new StringBuilder(1000);
            sb.Append("Name: ").Append(m_strName).Append(' ').AppendLine();
            sb.Append("Attributes: ").Append((int)m_iAttributes).AppendLine();
            sb.Append("Method Signature: ");
            GetMethodSignature().ToString(sb);
            sb.AppendLine();
            sb.AppendLine();
            return sb.ToString();
        }
```

**Comment by jkotas** [comment]
I do not think it is worth optimizing these diagnostic-only ToString overloads. It is best to keep them brain-dead simple and obvious - it does not matter that they allocate a bit more than strictly necessary.

I think changing `sb.Append` to `sb.AppendLine` in this code would be definitely improvement. I am not sure about the rest.

**Comment by jamesqo** [comment]
@jkotas Looking back on this PR, I don't think it's really that important of a change... closing for now.

**Comment by jkotas** [comment]
Thanks. I would be happy to take change that converts `sb.Append` to `sb.AppendLine` in this code.

**Pull request closed without merging**
