### PR TITLE
cordebuginfo.h out of corinfo.h

### PR DESCRIPTION
**Pull request by kyulee1**
ICorDebugInfo is almost standalone data structure.
This puts ICorDebugInfo into a new cordebuginfo.h.
This new header file is just included in corinfo.h
This way we could share this debug data structure
with ObjectWriter/LLILC by simply including this header.

### CODE REVIEW

**Comment by kyulee1** [comment]
@jkotas @dotnet/jit-contrib  PTAL. Please let me know if there is any concern about splitting this header.
cc/ @hoyMS

**Comment by jkotas** [comment]
LGTM

**Comment by BruceForstall** [comment]
LGTM

**Comment by kyulee1** [comment]
The failures are unrelated.

**Pull request merged**
