### PR TITLE
Create patches in formatting job

### PR DESCRIPTION
**Pull request by adiaaida**
In the formatting job, if there are formatting errors, we will run the
formatter in --fix mode and generate a patch which will be uploaded to
azure storage.

### CODE REVIEW

**Comment by adiaaida** [comment]
@dotnet-bot test ci please

**Comment by adiaaida** [comment]
New output will look like this:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_windows_nt_formatting_prtest/1360/consoleFull

**Comment by adiaaida** [comment]
@pgavlin @RussKeldorph PTAL
/cc: @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
I couldn't find the patch from your sample. Could you provide better, clearer, more specific instructions on how to find the patch? If I get a patch from multiple platforms (Linux, Windows, etc.) can I apply all of them, one on top of another?

**Comment by adiaaida** [comment]
There won't actually be a patch yet since this change has changes to the python (creating the patch) and the netci.groovy (archiving the patch). I am not sure exactly how to get the full path to the patch, which is why the output isn't super explicit.

As for applying the patches. I'm not sure, but I think if they changed the same code, they might conflict. I don't know a lot about patches and git in general, but maybe @pgavlin would be able to give more insight.

**Comment by JosephTremoulet** [comment]
This is maybe tangential to this PR, but is there a command line using format.py that we could print out that would run the formatter in fix mode locally (so no hunting through cloud storage) without having to manually set up a jitutils enlistment etc. first (so no barrier to entry)?

**Comment by adiaaida** [comment]
@JosephTremoulet There isn't right now, but I have my own version where I just added the --fix flag locally. I could add an option to make it easier to be run locally with --fix.

**Comment by BruceForstall** [comment]
@JosephTremoulet you know format.py is going to create a jitutils enlistment anyway, right?

**Comment by JosephTremoulet** [comment]
> you know format.py is going to create a jitutils enlistment anyway, right?

Yes, and delete it after.  The point is to have a command that anybody with a coreclr enlistment can simply run (no installing, rooting through docs, etc) to make the formatter happy.

**Comment by adiaaida** [comment]
@BruceForstall I've updated this so it will now print the following instructions at the end:

There were errors in formatting. Please run jit-format locally with: 
14:23:11 
14:23:11 	jit-format -a x64 -b Checked -o Linux -c <absolute-path-to-coreclr> --verbose --fix --projects dll
14:23:11 
14:23:11 
14:23:11 Or download and apply generated patch:
14:23:11 wget https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_ubuntu_formatting_prtest/1398/artifacts/format.patch
14:23:11 git apply format.patch

PTAL

**Comment by adiaaida** [comment]
(note that patch does not exist, but will with these changes)

**Comment by BruceForstall** [comment]
SGTM. I can't effectively review the script, though.

**Pull request merged**
