### PR TITLE
CompareOptions.IgnoreSymbols only ignores punctuation on Unix, but not other symbols 

### PR DESCRIPTION
**Pull request by eerhardt**
By default, ICU alternate shifted collation handling only ignores punctuation, not all symbols, so change the "variable top" to include all symbols and currency characters.

Fix http://github.com/dotnet/corefx/issues/4907

@ellismg @steveharter @stephentoub

### CODE REVIEW

**Comment by stephentoub** [comment]
Test FreeBSD x64 Debug Build please

**Comment by stephentoub** [comment]
Test FreeBSD x64 Release Build please

**Comment by stephentoub** [comment]
Test OSX x64 Release Build and Test please

**Comment by eerhardt** [comment]
It looks like I got the FreeBSD build errors fixed.  @ellismg - PTAL.

**Comment by ellismg** [comment]
LGTM.  I think the mac error is infrastructure related (maybe we are out of disk space?)  @mmitche might be able to help with that.

I assume this will let us enable some preexisting tests in CoreFX?  If not, might be a good idea to add a few.

Thanks for this!

**Comment by eerhardt** [comment]
> I assume this will let us enable some preexisting tests in CoreFX? If not, might be a good idea to add a few.

Yes, there were 2 marked with 4907 that are now passing.  I just haven't pushed the PR button yet.

See https://github.com/eerhardt/corefx/commit/f07c407e769465c40ecead877174a18af125a837

**Comment by eerhardt** [comment]
@dotnet-bot test OSX x64 Release Build and Test please

**Comment by kmaragon** [comment]
Thank you for this! The fix with HAVE_SET_MAX_VARIABLE is the only reason coreclr wasn't buildable on *not* Ubuntu 14.0.4. I will note that it didn't correctly detect this on Gentoo but manually adding CMAKE_CXX_FLAGS with -DHAVE_SET_MAX_VARIABLE=1 finally got it building and working. Many thanks!

**Pull request merged**
