### PR TITLE
Fix cfi annotation for NDirectImportThunk and JIT_RareDisableHelper

### PR DESCRIPTION
**Pull request by janvorli**
The title says all. I've talked to @sergiy-k who fixed it in a slightly different way and since I have fixed one more function in there, we've decided to use my change.

### CODE REVIEW

**Comment by kangaroo** [comment]
Tag @mmitche -- this seems to be the same flap my libunwind branch was seeing.

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by sergiy-k** [comment]
LGTM

**Comment by jkotas** [comment]
LGTM

**Pull request merged**
