### PR TITLE
Move DefaultBinder.cs to the shared partition.

### PR DESCRIPTION
**Pull request by AtsushiKan**

### CODE REVIEW

**Comment by AtsushiKan** [comment]
cc @jkotas

**Comment by AtsushiKan** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test

**Comment by AtsushiKan** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test

**Comment by AtsushiKan** [comment]
@dotnet-bot Linux ARM Emulator Cross Release Build

(This CI process is starting to approach Snap levels of badness 👎)

**Comment by AtsushiKan** [comment]
@dotnet-bot Test Linux ARM Emulator Cross Release Build

**Comment by jkotas** [comment]
@AtsushiKan There was a bad change merged in with failing CI: https://github.com/dotnet/coreclr/issues/10360. The ARM builds will keep failing until this gets reverted.

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Pull request merged**
