### PR TITLE
Fix incorrect switch temp lcl type

### LINKED ISSUE #13486: JIT: Assertion failed 'src1->OperIs(GT_LONG)'
Run `Windows_NT x86 Checked Build and Test (Jit - CoreFx)` CI tests will cause a failure on current master branch code:

```
20:10:24   Generated serialization assembly for assembly D:\j\workspace\x86_checked_w---92c0aac3\_\fx\bin\AnyOS.AnyCPU.Release\Microsoft.XmlSerializer.Generator.Tests\netstandard\Microsoft.XmlSerializer.Generator.Tests.dll --> 'D:\j\workspace\x86_checked_w---92c0aac3\_\fx\bin\AnyOS.AnyCPU.Release\Microsoft.XmlSerializer.Generator.Tests\netstandard\Microsoft.XmlSerializer.Generator.Tests.XmlSerializers.cs'.
20:10:25   Discovered:  Microsoft.Win32.Registry.Tests
20:10:32   Starting:    Microsoft.Win32.Registry.Tests
20:10:42   
20:10:42 
  Assert failure(PID 788 [0x00000314], Thread: 6912 [0x1b00]): Assertion failed 'src1->OperIs(GT_LONG)' in 'Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriter1:Write65_LongEnum(long):ref:this' (IL size 90)
20:10:42   
20:10:42       File: d:\j\workspace\x86_checked_w---92c0aac3\src\jit\lower.cpp Line: 2167
20:10:42       Image: D:\j\workspace\x86_checked_w---92c0aac3\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-x86\dotnet.exe
20:10:42   
20:10:43   Finished running tests.  End time=20:10:43.22, Exit code = 123456789
20:10:44 D:\j\workspace\x86_checked_w---92c0aac3\_\fx\Tools\tests.targets(445,5): warning MSB3073: The command "D:\j\workspace\x86_checked_w---92c0aac3\_\fx\bin/AnyOS.AnyCPU.Release/Microsoft.XmlSerializer.Generator.Tests/netstandard//RunTests.cmd D:\j\workspace\x86_checked_w---92c0aac3\_\fx\bin/testhost/netcoreapp-Windows_NT-Release-x86/" exited with code 123456789. [D:\j\workspace\x86_checked_w---92c0aac3\_\fx\src\Microsoft.XmlSerializer.Generator\tests\Microsoft.XmlSerializer.Generator.Tests.csproj]
20:10:44 
```

It should be introduced 3 days ago.

Please see the CI failure in this PR: https://github.com/dotnet/coreclr/pull/13480

### PR DESCRIPTION
**Pull request by mikedn**
Fixes #13486

### CODE REVIEW

**Comment by mikedn** [comment]
x64 jit-diff fx:
```
Total bytes of diff: -7 (0.00% of base)
    diff is an improvement.
Total byte diff includes 0 bytes from reconciling methods
        Base had    0 unique methods,        0 unique bytes
        Diff had    0 unique methods,        0 unique bytes
Top file regressions by size (bytes):
           2 : System.Diagnostics.Process.dasm (0.00% of base)
Top file improvements by size (bytes):
          -6 : Microsoft.CodeAnalysis.CSharp.dasm (0.00% of base)
          -2 : Microsoft.CodeAnalysis.VisualBasic.dasm (0.00% of base)
          -1 : Microsoft.CodeAnalysis.dasm (0.00% of base)
4 total files with size differences (3 improved, 1 regressed), 75 unchanged.
Top method regessions by size (bytes):
           2 : System.Diagnostics.Process.dasm - Process:GetShellError(long):int:this
           1 : Microsoft.CodeAnalysis.CSharp.dasm - BaseTypeAnalysis:IsManagedTypeHelper(ref):ubyte
           1 : Microsoft.CodeAnalysis.CSharp.dasm - SourceNamespaceSymbol:BuildSymbol(ref,ref):ref:this
           1 : Microsoft.CodeAnalysis.dasm - SwitchConstantValueHelper:IsValidSwitchCaseLabelConstant(ref):bool
Top method improvements by size (bytes):
          -1 : Microsoft.CodeAnalysis.CSharp.dasm - Lexer:ScanIdentifier_FastPath(byref):bool:this
          -1 : Microsoft.CodeAnalysis.CSharp.dasm - ConversionEasyOut:TypeToIndex(ref):int
          -1 : Microsoft.CodeAnalysis.CSharp.dasm - BinopEasyOut:TypeToIndex(ref):struct
          -1 : Microsoft.CodeAnalysis.CSharp.dasm - UnopEasyOut:TypeToIndex(ref):struct
          -1 : Microsoft.CodeAnalysis.CSharp.dasm - VarianceSafety:IsVarianceUnsafe(ref,bool,bool,ref,ref,ref,ref):bool (2 methods)
16 total methods with size differences (12 improved, 4 regressed), 66256 unchanged.
```
x86 jit-diff fx:
```
Total bytes of diff: 11 (0.00% of base)
    diff is a regression.
Total byte diff includes 0 bytes from reconciling methods
        Base had    0 unique methods,        0 unique bytes
        Diff had    0 unique methods,        0 unique bytes
Top file regressions by size (bytes):
          18 : System.Private.CoreLib.dasm (0.00% of base)
           1 : Microsoft.CodeAnalysis.dasm (0.00% of base)
Top file improvements by size (bytes):
          -5 : Microsoft.CodeAnalysis.CSharp.dasm (0.00% of base)
          -3 : Microsoft.CodeAnalysis.VisualBasic.dasm (0.00% of base)
4 total files with size differences (2 improved, 2 regressed), 75 unchanged.
Top method regessions by size (bytes):
          18 : System.Private.CoreLib.dasm - EventSource:GetHelperCallFirstArg(ref):int
           2 : Microsoft.CodeAnalysis.CSharp.dasm - ConversionEasyOut:TypeToIndex(ref):int
           1 : Microsoft.CodeAnalysis.CSharp.dasm - BaseTypeAnalysis:IsManagedTypeHelper(ref):ubyte
           1 : Microsoft.CodeAnalysis.CSharp.dasm - SourceNamespaceSymbol:BuildSymbol(ref,ref):ref:this
           1 : Microsoft.CodeAnalysis.dasm - SwitchConstantValueHelper:IsValidSwitchCaseLabelConstant(ref):bool
Top method improvements by size (bytes):
          -3 : Microsoft.CodeAnalysis.CSharp.dasm - BinderFactoryVisitor:VisitXmlNameAttribute(ref):ref:this
          -2 : Microsoft.CodeAnalysis.CSharp.dasm - DocumentationCommentCompiler:BindName(ref,ref,ref,byref,byref,ref)
          -2 : Microsoft.CodeAnalysis.VisualBasic.dasm - Binder:ReportOverloadResolutionFailureAndProduceBoundNode(ref,int,ref,struct,ref,struct,struct,ref,ref,ref,ref,bool,ref,ref,ref):ref:this
          -1 : Microsoft.CodeAnalysis.CSharp.dasm - Lexer:ScanIdentifier_FastPath(byref):bool:this
          -1 : Microsoft.CodeAnalysis.CSharp.dasm - VarianceSafety:IsVarianceUnsafe(ref,bool,bool,ref,ref,ref,ref):bool (2 methods)
13 total methods with size differences (8 improved, 5 regressed), 66198 unchanged.
```
Most of the diffs look like:
```diff
        movsx    eax, al
-       cmp      al, 38
+       cmp      eax, 38
        ja       SHORT G_M33493_IG08
```
The 18 byte regression from  EventSource:GetHelperCallFirstArg has to do with register allocation choices. While unrelated to this it looks kind of interesting so here's a full diff: https://gist.github.com/mikedn/15e61328a8fe0812268125af04fa2b89

I suspect that many of these diffs would disappear if the lclvar node type is used directly, without going through `genActualType`. But that sounds like an optimization that should be done separately instead of mixing it with this bug fix.

**Comment by mikedn** [comment]
@dotnet-bot test Tizen armel Cross Debug Build

**Comment by mikedn** [comment]
It's probably worth pointing out that on x64 this bug results in silent bad code generation. For example the JIT generated:
```asm
       4883F802             cmp      rax, 2
       7748                 ja       SHORT G_M55888_IG08
       488D0D65000000       lea      rcx, [reloc @RWD00]
       8B0C81               mov      ecx, dword ptr [rcx+4*rax]
```
instead of the correct:
```asm
       83F802               cmp      eax, 2
       774A                 ja       SHORT G_M55888_IG08
       8BC0                 mov      eax, eax
       488D0D64000000       lea      rcx, [reloc @RWD00]
       8B0C81               mov      ecx, dword ptr [rcx+4*rax]
```
But it's unlikely to hit this in practice, at least in C# where this pattern occurs when switching on longs and the C# compiler adds its own long compare before the switch:
```asm
G_M55888_IG02:
       488BC1               mov      rax, rcx
       4883F802             cmp      rax, 2
       774E                 ja       SHORT G_M55888_IG08
G_M55888_IG03:
; yeah, it's wrong if the upper 32 bits aren't 0 but that will never happen due to the above check
       4883F802             cmp      rax, 2 
       7748                 ja       SHORT G_M55888_IG08
       488D0D65000000       lea      rcx, [reloc @RWD00]
       8B0C81               mov      ecx, dword ptr [rcx+4*rax]
```

**Comment by mazong1123** [comment]
@dotnet-bot test Ubuntu x64 corefx_baseline
@dotnet-bot test Windows_NT x86 corefx_baseline

Just make sure this PR fixes the CI failure...

**Pull request merged**
