### PR TITLE
Add String.Contains overload with StringComparison

### PR DESCRIPTION
**Pull request by yvanin**
[Staging change](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/adding_new_public_apis.md) of System.Private.CoreLib for [CoreFX #20846](https://github.com/dotnet/corefx/issues/20846)

### CODE REVIEW

**Comment by yvanin** [comment]
@karelz please review, if this change is merged, I can proceed with the test suite in corefx repo

**Comment by karelz** [comment]
Thanks for your contribution @yvanin! I let also area experts to chime in -- @joperezr @AlexGhiondea 

I wonder if you discovered our docs for new contributors (under construction on CoreFX wiki) and how useful you found them. BTW: They are RW for everyone, so feel free adjust them/modify them as you go and find missing things or unclear content. Thanks!

**Comment by yvanin** [comment]
I didn't find how to deal with ref projects in the corefx docs but I discovered [the appropriate doc](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/adding_new_public_apis.md) in coreclr.

**Comment by karelz** [comment]
@ianhays can you please help make sure we have it in our new contributor docs?

**Comment by danmosemsft** [comment]
I'm going to merge so it can start moving to CoreFX -- please help finish off your tests PR there!

**Pull request merged**
