### PR TITLE
[RyuJIT/ARM32] Enabling fast tail call feature

### PR DESCRIPTION
**Pull request by alpencolt**
Rebased version of #14056

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked jitstress1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked tailcallstress Build and Test
@dotnet-bot test Windows_NT x86_arm_altjit Checked tailcallstress
@dotnet-bot test Windows_NT x86_arm_altjit Checked Build and Test

**Comment by alpencolt** [comment]
@dotnet-bot help

**Comment by alpencolt** [comment]
@dotnet-bot test Windows_NT arm Cross Checked jitstress1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked tailcallstress Build and Test

**Comment by alpencolt** [comment]
@dotnet-bot test Windows_NT arm Cross Checked jitstress1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked tailcallstress Build and Test

**Comment by alpencolt** [comment]
@dotnet-bot test Windows_NT arm Cross Checked jitstress1 Build and Test

**Comment by BruceForstall** [comment]
Someone from Microsoft needs to trigger the Windows ARM jobs for you.

@dotnet-bot test Windows_NT arm Cross Checked jitstress1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked tailcallstress Build and Test

**Comment by alpencolt** [comment]
@BruceForstall I can't see any details about failed tests

**Comment by alpencolt** [comment]
One more question. I'm trying to check tail call optimization on `coreclr/tests/src/JIT/opt/FastTailCall/FastTailCallCandidates.cs` test. And for method `FastTailCallCandidates:SimpleTestCase(int):int` it doesn't work.
Also does the IL for this method correct?

IL:
```ASM
IL_0000  02                ldarg.0     
IL_0001  17                ldc.i4.1    
IL_0002  58                add         
IL_0003  10 00             starg.s      0x0
IL_0005  02                ldarg.0     
IL_0006  1f 64             ldc.i4.s     0x64
IL_0008  33 02             bne.un.s     2 (IL_000c)
IL_000a  02                ldarg.0     
IL_000b  2a                ret         
IL_000c  02                ldarg.0     
IL_000d  28 03 00 00 06    call         0x6000003
IL_0012  2a                ret  
```
Generated code:
```ASM
; Assembly listing for method FastTailCallCandidates:SimpleTestCase(int):int
; Emitting BLENDED_CODE for generic ARM CPU
; optimized code
; r11 based frame
; partially interruptible
; Final local variable assignments
;
;  V00 arg0         [V00,T00] (  6,  5.50)     int  ->   r0        
;  V01 tmp0         [V01,T02] (  4,  2   )     int  ->   r0        
;  V02 tmp1         [V02,T01] (  5,  5   )     int  ->   r0        
;# V03 OutArgs      [V03    ] (  1,  1   )  lclBlk ( 0) [sp+0x00]  
;
; Lcl frame size = 0

G_M24343_IG01:
000000  E92D 4800      push    {r11,lr}
000004  46EB           mov     r11, sp

G_M24343_IG02:
000006  1C40           adds    r0, r0, 1
000008  2864           cmp     r0, 100
00000A  D102           bne     SHORT G_M24343_IG04
00000C  2064           movs    r0, 100

G_M24343_IG03:
00000E  E8BD 8800      pop     {r11,pc}

G_M24343_IG04:
000012  1C40           adds    r0, r0, 1
000014  2864           cmp     r0, 100
000016  D101           bne     SHORT G_M24343_IG05
000018  2064           movs    r0, 100
00001A  E005           b       SHORT G_M24343_IG06

G_M24343_IG05:
00001C  F24B 3304      movw    r3, 0xb304
000020  F2CB 53B6      movt    r3, 0xb5b6
000024  681B           ldr     r3, [r3]
000026  4798           blx     r3		// FastTailCallCandidates:SimpleTestCase(int):int

G_M24343_IG06:
000028  E8BD 8800      pop     {r11,pc}
```

**Comment by BruceForstall** [comment]
The failures are:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_tailcallstress_tst_prtest/13/

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_jitstress2_tst_prtest/19/

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_jitstress1_tst_prtest/22/

You should be able to click on the "Smarty.0.fail.smrt" link in the "Build Artifacts" section, to see the results. E.g., for tailcall stress:

```
[TESTS]
Tests.lst=ComparerCompare2.cmd_80, , , Smrt00000001, , # CoreMangLib\cti\system\collections\generic\comparer\ComparerCompare2\ComparerCompare2.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=ArraySort14.cmd_91, , , Smrt00000001, , # CoreMangLib\cti\system\array\ArraySort14\ArraySort14.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=generics.cmd_455, , , Smrt00000001, , # readytorun\tests\generics\generics.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=valuetuple.cmd_795, , , Smrt00000001, , # JIT\Methodical\structs\valuetuple\valuetuple.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=ArraySort11.cmd_954, , , Smrt00000001, , # CoreMangLib\cti\system\array\ArraySort11\ArraySort11.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=Linq.cmd_1185, , , Smrt00000001, , # JIT\Performance\CodeQuality\Linq\Linq\Linq.cmd  CATS: EXPECTED_PASS
Tests.lst=ComparerCompare1.cmd_2113, , , Smrt00000001, , # CoreMangLib\cti\system\collections\generic\comparer\ComparerCompare1\ComparerCompare1.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=CircleInConvex_r.cmd_2465, , , Smrt00000001, , # JIT\SIMD\CircleInConvex_r\CircleInConvex_r.cmd  CATS: EXPECTED_PASS
Tests.lst=ArraySort3b.cmd_2852, , , Smrt00000001, , # CoreMangLib\cti\system\array\ArraySort3b\ArraySort3b.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=Burgers.cmd_3146, , , Smrt00000001, , # JIT\Performance\CodeQuality\Burgers\Burgers\Burgers.cmd  CATS: EXPECTED_PASS
Tests.lst=CscBench.cmd_3424, , , Smrt00000001, , # JIT\Performance\CodeQuality\Roslyn\CscBench\CscBench.cmd  CATS: EXPECTED_PASS
Tests.lst=waithandlewaitone1.cmd_3753, , , Smrt00000001, , # baseservices\threading\waithandle\misc\waithandlewaitone1\waithandlewaitone1.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=ArraySort13.cmd_3993, , , Smrt00000001, , # CoreMangLib\cti\system\array\ArraySort13\ArraySort13.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=ArraySort12.cmd_4068, , , Smrt00000001, , # CoreMangLib\cti\system\array\ArraySort12\ArraySort12.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=vt1_il_d.cmd_4593, , , Smrt00000001, , # JIT\Generics\ConstrainedCall\vt1_il_d\vt1_il_d.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=ArraySort2b.cmd_5711, , , Smrt00000001, , # CoreMangLib\cti\system\array\ArraySort2b\ArraySort2b.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=Deserialize.cmd_8437, , , Smrt00000001, , # JIT\Performance\CodeQuality\Serialization\Deserialize\Deserialize.cmd  CATS: EXPECTED_PASS
Tests.lst=Serialize.cmd_9128, , , Smrt00000001, , # JIT\Performance\CodeQuality\Serialization\Serialize\Serialize.cmd  CATS: EXPECTED_PASS
Tests.lst=CircleInConvex_ro.cmd_10224, , , Smrt00000001, , # JIT\SIMD\CircleInConvex_ro\CircleInConvex_ro.cmd  CATS: EXPECTED_PASS
Tests.lst=Richards.cmd_11017, , , Smrt00000001, , # JIT\Performance\CodeQuality\V8\Richards\Richards\Richards.cmd  CATS: EXPECTED_PASS
Tests.lst=fasta-1.cmd_11039, , , Smrt00000001, , # JIT\Performance\CodeQuality\BenchmarksGame\fasta\fasta-1\fasta-1.cmd  CATS: EXPECTED_PASS
Tests.lst=Compilation.cmd_11084, , , Smrt00000001, , # managed\Compilation\Compilation\Compilation.cmd  CATS: EXPECTED_PASS
Tests.lst=DevDiv_461649.cmd_11381, , , Smrt00000001, , # JIT\Regression\JitBlue\DevDiv_461649\DevDiv_461649\DevDiv_461649.cmd  CATS: EXPECTED_PASS;NEW
```

There is also a "Smarty.run.0.zip" link that downloads the entire Windows arm test run output (it's big).

This archive contains a couple output files (one HTML, one TXT) for each test run. E.g., for ComparerCompare2.cmd_80, which failed:
```
BEGIN EXECUTION
 "C:\Users\robox\j\workspace\arm_cross_che---b8d0349b\bin\tests\Windows_NT.arm.Checked\Tests\Core_Root\corerun.exe" ComparerCompare2.exe 
Beginning test case ComparerCompare2 at 2/19/2018 12:05:05 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

[Positive]
Beginning scenario: PosTest1: Call Compare to compare two value type instance

Assert failure(PID 21948 [0x000055bc], Thread: 14720 [0x3980]): Compiler optimization assumption invalid: FAILED: pMgr != 0

<no module>! <no symbol> + 0x0 (0x00000000)
    File: d:\j\workspace\arm_cross_che---9fe37e18\src\vm\virtualcallstub.cpp Line: 1601
    Image: C:\Users\robox\j\workspace\arm_cross_che---b8d0349b\bin\tests\Windows_NT.arm.Checked\Tests\Core_Root\CoreRun.exe

Expected: 100
Actual: 123456789
END EXECUTION - FAILED
FAILED
```

**Comment by BruceForstall** [comment]
For your example, without looking too carefully, I don't see anything obviously wrong, but it obviously is not generating a fast tail call.

**Comment by karelz** [comment]
No update for 1+ year. I recommend to close the PR until it is ready to be worked on again ... thoughts @RussKeldorph?

**Pull request closed without merging**
