### PR TITLE
Fix possibly unintentional use of bit-wise or operator.

### PR DESCRIPTION
**Pull request by filipnavara**

### CODE REVIEW

**Comment by stephentoub** [comment]
While it may have been unintentional it could also have been done if someone measured and found it helped with performance by avoiding an additional branch.  Have you done any benchmarking to see that this doesn't make a perf difference?  @JonHanna added this code; maybe he can comment, too.

**Comment by filipnavara** [comment]
@stephentoub I looked at the JIT dumps are sharplab.io before submitting the PR. It may not match the JIT output of .NET Core today, but the ASM output for the `||` was in fact better and shorter. Then again, in both cases it looked like unoptimized ASM, so it may be worth doing the comparison again in more scientific manner.

**Comment by VSadov** [comment]
I think this is intentional. The assumption is that these comparisons will all have to run in nearly 100% cases anyways. Shortcircuiting would at best be ignored if branch prediction is good. 

On the other hand many CPUs nowdays could retire 2 independent compares at once. I think that is the idea here.

**Comment by filipnavara** [comment]
Any self-respecting C/C++ compiler would optimize this since it's a local variable and there are no possible side effects. I would certainly assume the JIT would do the same.

I'll show the proper benchmark and disassembly once I get back to my computer.

**Comment by jkotas** [comment]
We do not generally use similar micro-optimizations. Also, these are floating point optimizations in the middle of a lot slow floating point math. You won't be measure the effect of this even if you tried hard.

**Comment by mikedn** [comment]
> Any self-respecting C/C++ compiler would optimize this since it's a local variable and there are no possible side effects. I would certainly assume the JIT would do the same.

No, the JIT doesn't do this and even C/C++ compilers avoid doing this. The `|` version may be faster sometimes, for example if the extra branch it avoids is poorly predicted. Otherwise it is usually slower.

**Comment by filipnavara** [comment]
@mikedn My point was that it's often simpler to reason about the `||` with short-circuiting than about `|`. I didn't necessarily mean that it would change the `||` into `|` specifically. I was thinking more in line of ARM conditional instructions or doing the `|` version specifically to satisfy a processor pipeline that can compute both conditions in parallel. Then again I do trust modern branch predictors quite a lot (TinyCC performance was surprisingly good for a one-pass C compiler with nearly no optimizations ;) ). Anyway, you peaked my curiosity.

**Comment by VSadov** [comment]
I have seen cases where `|` is observably faster than `||`. That said, the difference is generally seen only in very tight loops and with trivial integer operations. 

Here we deal with floats and conversions. As Jan says, the overhead of `||`, if there is any, is unlikely to make a difference. It is really a matter of habits and style.

Interestingly,  C# can strength-reduce `||` into `|` , but only in trivial forms like  `<expression> || local`.

**Comment by mikedn** [comment]
Yes, clang does generate the same code for both versions. But not that code. This code: https://godbolt.org/z/pwxyn6

**Comment by filipnavara** [comment]
@mikedn The generated code is still the same for both of your functions, or am I missing something?

**Comment by mikedn** [comment]
> aside from the fact that now it does short circuit for the | version

Exactly. The point is that your example functions don't quite match the real world code discussed in this PR. It's one thing to transform between bitwise OR and logical OR when you're dealing with flow control and it's a completely different thing to do that when you need to materialize the result of a bool expression.

**Comment by filipnavara** [comment]
@mikedn My whole point was that it's not necessary to try to outsmart the compiler/JIT for this type of expressions. Perhaps I should have stated that more clearly.

**Comment by mikedn** [comment]
> My whole point was that it's not necessary to try to outsmart the compiler/JIT for this type of expressions. Perhaps I should have stated that more clearly.

I think there's some kind of misunderstanding here. My main point was that using `|` instead of `||` was likely an accident rather than an optimization and that it's rare for `|` to actually be an optimization. But since my comment was targeted at one of your comments things got mixed up a bit :smile:.

**Comment by JonHanna** [comment]
Yeah, it was a micro-opt. There are places where it makes an appreciable difference in a tight loop, but it was in here just because I've gotten into the habit of using it when the work done on the LHS is simple.
As it was just from that habit, I've no opinion on whether it's changed or not. If it was in a tight loop I might say differently.

**Pull request merged**
