### PR TITLE
Don't fall back to min-opts based on IL size for AggressiveOptimization or Tier1

### PR DESCRIPTION
**Pull request by kouvel**
Fixes https://github.com/dotnet/coreclr/issues/26419

### CODE REVIEW

**Comment by kouvel** [comment]
@dotnet/jit-contrib

**Comment by sandreenko** [comment]
LGTM overall.

However, some artificial methods could take hours to compile (because some of our algorithms have cubic time complexity in the worst case), for example, https://github.com/dotnet/coreclr/issues/16573.

Also, if we have tests, that are disabled under R2R because of timeouts or OOM they can fail now with tiering but from the first look we do not have them right now.

**Comment by kouvel** [comment]
It would be possible to have a higher set of limits for prejit or tier 1 (aggressive opt is easy to work around), such that we wouldn't optimize those methods at crossgen time or run time. At crossgen time it's probably less critical, at run time dynamic methods may possibly be realistic candidates for large/complex code in some cases. I'm not sure how necessary having some limits would be.

**Comment by jkotas** [comment]
I do not think it is ok to just disable these limits at runtime for the reasons @sandreenko mentioned.

**Comment by BruceForstall** [comment]
If we do keep some limits, maybe the JIT should tell the runtime the limit was invoked, and maybe the runtime should just ignore the JIT'ed code and keep using the R2R code. Maybe with @briansull 's upcoming scoring work we would know (or guess) if the new code was better or worse than the existing R2R code.

**Comment by kouvel** [comment]
Sounds good to me, the JIT is already sending back info about switching to min-opts, I'll use that to fix it from the tiering side

**Pull request closed without merging**
