### PR TITLE
arm32 build fix.

### PR DESCRIPTION
**Pull request by jashook**
Add an #else statement so that an unreachable return statement is not inserted.

### CODE REVIEW

**Comment by jashook** [comment]
@briansull @dotnet/jit-contrib ptal

**Comment by sivarv** [comment]
Looks good.

**Comment by briansull** [comment]
LGTM

**Comment by briansull** [comment]
@dotnet-bot Ubuntu x64 Checked Build and Test

**Comment by jashook** [comment]
@dotnet-bot Ubuntu x64 Checked Build and Test

**Comment by jashook** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Pull request merged**
