### PR TITLE
Fix GC exception related issue

### PR DESCRIPTION
**Pull request by janvorli**
This change fixes a problem that has occured when GC was called from
an exception handler during split exception handling. The problem
manifestated itself as a crash in the HasFrameBeenUnwoundByAnyActiveException
function due to the pInitialExplicitFrame being NULL.
The cause of this issue was caused by a combination of two issues.
First, the m_ScannedStackRange was not reset in the partial 2nd pass to
the state at the beginning of the corresponding partial 1st pass.
And second, the 'unwind has started' flag was not reset after
restoring exception flags in the new exception tracker after switching
from the 2nd back to the 1st pass during the split exception handling.

There was one additional issue, several additional members of the exception
tracker needed to be propagated to the new tracker. These members are
needed by the HasFrameBeenUnwoundByAnyActiveException function.

Since the number of state members that are propagated from the old to the
new exception tracker has grown, I've refactored the code to keep those
in a separate class.

### CODE REVIEW

**Comment by janvorli** [comment]
@jkotas Could you please take a look?

**Comment by janvorli** [comment]
I've forgotten to mention that this change fixes the issue #566

**Comment by jkotas** [comment]
LGTM

**Comment by janvorli** [comment]
@dotnet-bot test this please

**Pull request merged**
