### PR TITLE
software ww fix

### PR DESCRIPTION
**Pull request by Maoni0**
The issue is we need the software ww to account the out of range segments/portions of segments and make sure to not clear them during reset. This fix is to be ported to RTM. I will make a more performant fix post RTM so if we expand the heap during the ephemeral GC at the beginning of BGC the BGC range will cover that. That would affect all OSs.

### CODE REVIEW

**Comment by Maoni0** [comment]
@pdussud 

The issue is we need the software ww to account the out of range segments/portions of segments and make sure to not clear them during reset.

**Comment by swgillespie** [comment]
@dotnet-bot test Ubuntu Release longgc 
test OSX Release longgc

**Comment by kouvel** [comment]
LGTM

**Comment by sergiy-k** [comment]
LGTM

**Comment by swgillespie** [comment]
LGTM

**Comment by pdussud** [comment]
This looks good.

**Pull request merged**
