### PR TITLE
Support checking for HFA types in altjit

### LINKED ISSUE #13092: Enable HFA support in VM for arm32/arm64 altjit
The arm32/arm64 JITs call ICorJitInfo::getHFAType() to inquire about HFA types. When an arm32 altjit is run on x86, or an arm64 altjit is run on x64, the answer is incorrect, as the VM has been built without FEATURE_HFA defined, such that ICorJitInfo::getHFAType() always returns CORINFO_TYPE_UNDEF. This means that the altjit cannot be used to reproduce issues involving HFA types. Also, asm diffs involving HFAs aren't useful.

Since using the altjit is valuable, this should be fixed.

ICorJitInfo::getHFAType() ends up at MethodTable::GetHFAType() or EEClassLayoutInfo::GetNativeHFAType(). These depend on bits that were previously set on the MethodTable or EEClassLayoutInfo by MethodTableBuilder::CheckForHFA() and MethodTableBuilder::CheckForNativeHFA().

We don’t want to penalize x86 or x64 MethodTable building such that an arm32 or arm64 altjit can come along later and ask about HFAs. (If fact, we reuse some of the same bits, due to a lack of flags bits in some cases.) So, we need to find a way whereby the getHFAType() function on x86/x64 can do the correct calculation on demand, without depending on a pre-computed/cached value in the MethodTable itself. The only effect on x86/x64 VM should be slightly larger code size to carry along the HFA classification code (similar to how the x64 Windows VM carries the Linux/x64 struct classification code to support Linux/x64-target, Windows/x64-host altjit).

### PR DESCRIPTION
**Pull request by CarolEidt**
Fix #13092

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet-bot test Ubuntu arm Cross Release Build
@dotnet-bot test Windows_NT arm Cross Checked Build and Test

**Comment by karelz** [comment]
What is status of this PR? Not much happened to it since its creation 3 weeks ago.
Does it need more work or is it ready for code review?

**Comment by CarolEidt** [comment]
> What is status of this PR? Not much happened to it since its creation 3 weeks ago.
Does it need more work or is it ready for code review?

It needs more work, and it is currently a lower priority item. Either @BruceForstall or I will pick it up as time permits, hopefully in the next couple of weeks.

**Comment by karelz** [comment]
If you think it may take a week or two, I would recommend to close it and reopen when you are ready to work on it again.

**Comment by BruceForstall** [comment]
Why?

**Comment by karelz** [comment]
Easier to avoid long-standing forgotten PRs or work-in-progress issues which are unclear if they will be ever merged, or if they are abandoned.
PR != backlog / TODO list. Happy to chat more about it.

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Build and Test

**Comment by CarolEidt** [comment]
@BruceForstall @jashook @jkotas PTAL

**Comment by CarolEidt** [comment]
cc @dotnet/jit-contrib

**Pull request merged**
