### PR TITLE
Convert Sse2 tests to templated version - part 1

### PR DESCRIPTION
**Pull request by 4creators**
This is first part of conversion work for Sse2 tests.

### CODE REVIEW

**Comment by 4creators** [comment]
test Windows_NT x64 Checked jitincompletehwintrinsic
test Windows_NT x64 Checked jitx86hwintrinsicnoavx2
test Windows_NT x64 Checked jitx86hwintrinsicnosimd
test Windows_NT x64 Checked jitnox86hwintrinsic

test Windows_NT x86 Checked jitincompletehwintrinsic
test Windows_NT x86 Checked jitx86hwintrinsicnoavx2
test Windows_NT x86 Checked jitx86hwintrinsicnosimd
test Windows_NT x86 Checked jitnox86hwintrinsic

test Ubuntu x64 Checked jitincompletehwintrinsic
test Ubuntu x64 Checked jitx86hwintrinsicnoavx2
test Ubuntu x64 Checked jitx86hwintrinsicnosimd
test Ubuntu x64 Checked jitnox86hwintrinsic

**Comment by 4creators** [comment]
@CarolEidt @fiigii @tannergooding PTAL

**Comment by fiigii** [comment]
Thanks for the work, but you may want to wait for https://github.com/dotnet/coreclr/pull/16957

**Comment by 4creators** [comment]
> Thanks for the work, but you may want to wait for #16957

This PR could be applied before or after merging this PR in next part of conversions. It affects only couple of converted tests.

**Comment by 4creators** [comment]
test Windows_NT x64 Checked jitincompletehwintrinsic
test Windows_NT x64 Checked jitx86hwintrinsicnoavx2
test Windows_NT x64 Checked jitx86hwintrinsicnosimd
test Windows_NT x64 Checked jitnox86hwintrinsic

test Windows_NT x86 Checked jitincompletehwintrinsic
test Windows_NT x86 Checked jitx86hwintrinsicnoavx2
test Windows_NT x86 Checked jitx86hwintrinsicnosimd
test Windows_NT x86 Checked jitnox86hwintrinsic

test Ubuntu x64 Checked jitincompletehwintrinsic
test Ubuntu x64 Checked jitx86hwintrinsicnoavx2
test Ubuntu x64 Checked jitx86hwintrinsicnosimd
test Ubuntu x64 Checked jitnox86hwintrinsic

**Comment by tannergooding** [comment]
I'm going to merge this and fixup #16957, since I need to resolve the remaining GCStress test issues anyways

**Comment by 4creators** [comment]
@tannergooding Thanks

**Pull request merged**
