### PR TITLE
Fix for clrstack after bpmd

### PR DESCRIPTION
**Pull request by chunseoklee**
related issue : #4672 #5037

### CODE REVIEW

**Comment by seanshpark** [comment]
@mikem8361 , PTAL

**Comment by chunseoklee** [comment]
Another approach is to add  `EndAddress` field to `struct _IMAGE_ARM_RUNTIME_FUNCTION_ENTRY `. This seems to make code more clear. 
I checked this approach works fine on both x64 arm32 linux.

**Comment by mikem8361** [comment]
The last change looks fine with me as long it doesn't break amd64 Linux, etc.

**Comment by chunseoklee** [comment]
I updated commit as you mentioned.

**Comment by seanshpark** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by chunseoklee** [comment]
@mikem8361 Could this PR be merged ?

**Pull request merged**
