### PR TITLE
Port the fix for Issue 17969 to Rel/2.1

### PR DESCRIPTION
**Pull request by CarolEidt**

### CODE REVIEW

**Comment by RussKeldorph** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test 
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by RussKeldorph** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test
@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by CarolEidt** [comment]
@dotnet-bot test CentOS7.1 x64 Checked Innerloop Build and Test
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test
@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by danmosemsft** [comment]
@dotnet-bot test CentOS7.1 x64 Checked Innerloop Build and Test
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test
@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by CarolEidt** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by danmosemsft** [comment]
@dotnet/jit-contrib @RussKeldorph this was approved for 2.1.3 but is not submitted yet. It is about to miss 2.1.3. Are the arm jobs expected to work?

**Comment by CarolEidt** [comment]
Yes, the arm jobs are supposed to work, but the CI system has been incredibly flaky lately.

**Comment by CarolEidt** [comment]
IMO we should just merge this because this fix was tested in master, and is in no way target-specific

**Comment by AndyAyersMS** [comment]
They've been very flaky -- see [history](https://ci.dot.net/job/dotnet_coreclr/job/release_2.1/job/arm64_cross_checked_windows_nt_innerloop_flow_prtest/buildTimeTrend) -- and we have been ignoring failures when we're confident the changes are not arm specific.

**Comment by danmosemsft** [comment]
thanks !

**Pull request merged**
