### PR TITLE
Smaller ArrayPool for 32 bit

### PR DESCRIPTION
**Pull request by benaadams**
Resolves https://github.com/dotnet/coreclr/issues/15796

/cc @jkotas @stephentoub @JeremyKuhne @danmosemsft

### CODE REVIEW

**Comment by benaadams** [comment]
Couldn't find a particular reason for the size `50` https://github.com/dotnet/corefx/issues/4547#issuecomment-157532443

> In terms of defaults, the Shared pool that is in CoreFxLab uses the default parameters of the Pool constructor, which is a max buffer size of 2 MB (lazy loaded) and a max number of buffers at 50-per-bucket.

**Comment by stephentoub** [comment]
Have you looked at the perf impact of this? A max of 4 buffers per thread seems like you could end up throwing away a lot of buffers, in particular in async scenarios.

**Comment by benaadams** [comment]
> Have you looked at the perf impact of this? A max of 4 buffers per thread seems like you could end up throwing away a lot of buffers, in particular in async scenarios.

Perhaps bringing down `MaxPerCorePerArraySizeStacks` from 64 to 16 is enough?

Reduces max stored buffers for `char`+`byte` from 3GB to 767MB; reducing to 4 takes it to 383MB. As a 32bit process only has 2GB current values will OOM

**Comment by jkotas** [comment]
This should be looked at and tuned together with https://github.com/dotnet/coreclr/pull/17078

**Comment by benaadams** [comment]
Could also reduce the upper bound on stacks; bring it down from 17?

**Comment by danmosemsft** [comment]
@JeremyKuhne will continue this work after ZBB.

**Comment by stephentoub** [comment]
@JeremyKuhne, @benaadams, is this still relevant?  It's marked 2.1.

**Comment by benaadams** [comment]
Not sure; the "potential" stored buffers are too high for 32-bit; however if the ArrayPool trim https://github.com/dotnet/coreclr/pull/17078 makes sure it will never OOM due to this; then the current state is probably better (e.g. if you exclusively use one type of buffer, is better not to limit the amount available in the worry that other buffers may allocate too much)

**Comment by JeremyKuhne** [comment]
@benaadams with the trimming it is difficult to get into an OOM situation. It only impacts the shared pools, theory being that you should be responsible for pools you create. My feeling is that we should drop this proposed change for now- if we see evidence that trimming the shared pools isn't enough we can revisit. What do you think?

**Comment by benaadams** [comment]
I think that's valid

**Pull request closed without merging**
