### PR TITLE
Update command lines for building corefx repo

### PR DESCRIPTION
**Pull request by weshaggard**
Fixes https://github.com/dotnet/coreclr/issues/20405.

PTAL @BruceForstall @RussKeldorph

### CODE REVIEW

**Comment by weshaggard** [comment]
@dotnet-bot test Windows_NT x64 Checked corefx_baseline
@dotnet-bot test Ubuntu x64 Checked corefx_baseline

**Comment by BruceForstall** [comment]
@weshaggard Looks like the CI rebooted during your run. Nonetheless, looks like some arm32/arm64 problems.

arm32:
```
10:00:51 [/mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_baseline_prtest/tests/scripts/run-corefx-tests.py]: src/Native/build-native.sh -Release /p:OSGroup=Linux /p:ArchGroup=arm  portable cross clang5.0
10:00:51 Setting up directories for build
10:00:51 Checking pre-requisites...
10:00:51 Please install clang before running this script
10:00:51 [/mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_baseline_prtest/tests/scripts/run-corefx-tests.py]: Error: exit code 256
```

arm64:
```
09:53:24 [/mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_prtest/tests/scripts/run-corefx-tests.py]: src/Native/build-native.sh -Release /p:OSGroup=Linux /p:ArchGroup=arm64  portable cross
09:53:24 Setting up directories for build
09:53:24 Checking pre-requisites...
09:53:24 Commencing build of corefx native components for Linux.x64.Release
09:53:24 Invoking cmake with arguments: "/mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_prtest/_/fx/src/Native/Unix" RELEASE  -DFEATURE_DISTRO_AGNOSTIC_SSL=0 -DCMAKE_STATIC_LIB_LINK=0
09:53:24 loading initial cache file /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_prtest/_/fx/src/Native/Unix/../../../cross/tryrun.cmake
09:53:24 CMake Error at /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_prtest/_/fx/cross/tryrun.cmake:25 (message):
09:53:24   Arch is x64.  Only armel, arm, arm64 and x86 are supported!
09:53:24 
09:53:24 
09:53:24 -- Configuring incomplete, errors occurred!
09:53:24 Failed to generate native component build project!
09:53:24 [/mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_prtest/tests/scripts/run-corefx-tests.py]: Error: exit code 256
```

**Comment by weshaggard** [comment]
@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked corefx_baseline Build and Test

**Comment by BruceForstall** [comment]
@weshaggard Looks like the tests are passing. Good to merge?

**Comment by BruceForstall** [comment]
@weshaggard Looks like the Windows arm64 corefx testing is broken. In this case, we build on Windows x64, and that part seems to be failing with a missing cmake. What's odd is that just above this in the log, we've built successfully using cmake!
cc @jashook 

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_baseline_flow/
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_baseline_bld/13/consoleFull
```
17:40:46   D:\j\workspace\arm64_cross_c---efb15e6d\_\fx\src\Native\build-native.cmd arm64 Release Windows_NT
17:40:46   **********************************************************************
17:40:46   ** Visual Studio 2017 Developer Command Prompt v15.7.6
17:40:46   ** Copyright (c) 2017 Microsoft Corporation
17:40:46   **********************************************************************
17:40:49   **********************************************************************
17:40:49   ** Visual Studio 2017 Developer Command Prompt v15.7.6
17:40:49   ** Copyright (c) 2017 Microsoft Corporation
17:40:49   **********************************************************************
17:40:50   [vcvarsall.bat] Environment initialized for: 'x86_arm64'
17:40:50   Commencing build of native components
17:40:50   
17:40:55   CMake is a pre-requisite to build this repository but it was not found on the path. Please install CMake from http://www.cmake.org/download/ and ensure it is on your path.
17:40:55   Failed to generate native component build project!
17:40:55 
D:\j\workspace\arm64_cross_c---efb15e6d\_\fx\src\Native\build-native.proj(50,5): error MSB3073: The command ""D:\j\workspace\arm64_cross_c---efb15e6d\_\fx\src\Native\build-native.cmd" arm64 Release Windows_NT" exited with code 1.
17:40:55 
17:40:55 Build FAILED
```

**Comment by BruceForstall** [comment]
It works on my local machine. So what is the difference on the build machines? Is cmake not on the path, or on the path differently? Why is the VS tools banner showing up twice?

My local run:
```
  F:\gh\coreclr11\_\fx\src\Native\build-native.cmd arm64 Release Windows_NT
  **********************************************************************
  ** Visual Studio 2017 Developer Command Prompt v15.8.7
  ** Copyright (c) 2017 Microsoft Corporation
  **********************************************************************
  [vcvarsall.bat] Environment initialized for: 'x86_arm64'
  Commencing build of native components

  -- Selecting Windows SDK version 10.0.17134.0 to target Windows 10.0.
...
```

**Pull request merged**
