### PR TITLE
Fix LSRA enregisterLocalVars

### LINKED ISSUE #16578: [Perf] Investigate BenchF/BenchMk2 Regression between release/2.0.0 and release/2.1
We regressed 12% on x64.

### PR DESCRIPTION
**Pull request by CarolEidt**
We don't bother with the parts of LSRA that deal with lclVars if we have no tracked lclVars. However, we need to check that *after* liveness has run post-Lowering - otherwise we miss any lclVars created by optimizations or during Lowering.

Fix #16578

### CODE REVIEW

**Comment by CarolEidt** [comment]
This results in a reduction of 66193 bytes (.04%) for x64/windows asm-diffs (frameworks + tests), and 0 diffs on x86.

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

**Comment by AndyAyersMS** [comment]
[Arm Failures](https://ci.dot.net/job/dotnet_coreclr/job/master/job/armlb_cross_checked_windows_nt_innerloop_flow_prtest/388/) look like infrastructure issues that have since cleared up, so am going to retry.

@dotnet-bot retest Windows_NT arm Cross Checked Innerloop Build and Test
@dotnet-bot retest Windows_NT arm64 Cross Checked Innerloop Build and Test
@dotnet-bot retest Windows_NT armlb Cross Checked Innerloop Build and Test

**Comment by AndyAyersMS** [comment]
Change LGTM.

I assume that codegen for BenchMk2 and BenchMrk looks good now?

Is there any other way we could have caught this other than looking more closely at perf results?

**Comment by CarolEidt** [comment]
> I assume that codegen for BenchMk2 and BenchMrk looks good now?

Yes

> Is there any other way we could have caught this other than looking more closely at perf results?

What's odd is that I say in the PR that there were zero diffs, but perhaps these benchmarks weren't included in the diffs at that point. Also, I apparently ran perf tests and said "the perf tests don't seem to have minOpts measurements (which is what this PR is primarily focused on), but the non-noisy results were positive." which is surprising. So I'm not sure how this fell through the cracks, but normally asm-diffs and/or perf testing would have caught this.

**Comment by AndyAyersMS** [comment]
I have to confess that I don't always run diffs on tests, because building tests is still painful, we moved a lot of interesting tests to pri-1, R2R codegen often obscures things (eg no SIMD, much less inlining), you need to remember to pass extra flags to jit-diffs to get it to look at tests, and somewhere around 800 crossgens fail for various reasons when you do so, which always alarms me until I realize there are the same set of failures in base and diff.

Hoping that with the advent of PMI we can address some of this and make broader and more relevant diffs a regular practice.

**Pull request merged**
