### PR TITLE
Fix EncoderNLS / DecoderNLS regression in reporting error index

### PR DESCRIPTION
**Pull request by GrabYourPitchforks**
Fixes https://github.com/dotnet/corefx/issues/37969.

The _index_ parameter passed to the `Fallback` method should be a negative value if the buffer we're falling back contains leftover data from a previous call to the encoder / decoder instance. In this case, an index of _-x_ means "the start of the invalid sequence occurred _x_ elements _before_ the start of the buffer that was just passed in." We were incorrectly hardcoding zero in these cases rather than reporting negative indexes.

I'll link to the unit test PR in corefx when that's ready.

### CODE REVIEW

**Comment by GrabYourPitchforks** [comment]
I'm waiting for the test runs to complete and then I'll merge this.

**Comment by GrabYourPitchforks** [comment]
There's an assertion being hit that will require further investigation. I should have more information later today.

**Comment by GrabYourPitchforks** [comment]
Debriefing on the `Debug.Assert` failures. The unit tests I introduced at https://github.com/dotnet/corefx/pull/38937 were exercising a condition that we didn't have good test coverage for. This condition tests the behavior where empty input buffers are provided to the `EncoderNLS` and `DecoderNLS` instance with _flush = true_, which requires flushing any existing leftover data from the encoder or decoder instance. The runtime behavior of the `Encoding` classes is correct for these cases in release builds, but in debug builds there's an incorrect `Debug.Assert` that assumes the caller didn't pass an empty input. As part of this PR I'm changing the assertions at the method entry points to allow for this condition, which unblocks being able to write the necessary unit tests for the original reported issue.

**Comment by wtgodbe** [comment]
The error in formatting is happening in all CoreClr PRs. Expect some test build failures too. See the discussion in  https://github.com/dotnet/coreclr/pull/25439 for reference.

**Pull request merged**
