### PR TITLE
Trim Overload for one char

### PR DESCRIPTION
**Pull request by dckcosta**

### CODE REVIEW

**Comment by jkotas** [comment]
@Anniepoh  @rubybe @maggiemsft @dckcosta Could you please ask one of your coworkers to give you overview on how to work with git and github? You are spamming the repo with junk PRs.

**Comment by jkotas** [comment]
These PRs came from training exercise - the final PR will be submitted later.

**Comment by jcdickinson** [comment]
@jkotas, I love that you are getting more of your own developers on board with GitHub. Respectfully, one area is missing in your training: a detailed description of the PR. I didn't see one in any of them.

**Comment by jkotas** [comment]
This training exercise got out of control - sorry about the noise. It should be under control now.

cc @ellismg

**Pull request closed without merging**
