### PR TITLE
Port more Interop tests from Desktop CLR to CoreCLR

### PR DESCRIPTION
**Pull request by botaberg**
Port more Interop tests from the Desktop CLR test tree to CoreCLR:

EnumMarshalling
FuncPtrAsDelegateParam
SimpleStruct
Structures/MarshalStructAsLayoutExp
Structures/MarshalStructAsLayoutSeq

First draft for some of these tests. Managed and native components of all tests build on Windows; native components build on Linux.

The following tests fail on Linux:

SimpleStruct
Structures/MarshalStructAsLayoutExp
Structures/MarshalStructAsLayoutSeq

The following test fails on Windows:

Structures/MarshalStructAsLayoutSeq

Only passing tests are enabled in their environments. I will open issues for all current failures.

### CODE REVIEW

**Comment by botaberg** [comment]
@yizhang82 @tijoytom Please take a look at this pull request.

**Comment by tijoytom** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test please

**Comment by tijoytom** [comment]
@botaberg Can you move the EnumMarshalling test to PrimitiveMarshalling folder?

**Comment by botaberg** [comment]
@tijoytom Moved EnumMarshalling into PrimitiveMarshalling

**Pull request merged**
