### PR TITLE
[RyuJIT/ARM32] Dodge lowering long compares

### LINKED ISSUE #11870: [RyuJIT/arm32] All test failed after recent commit
After e5d76089a7af352759ed395ecc3c2e61bd6f9640 (https://github.com/dotnet/coreclr/pull/10275), all test failed with AltJit (ryujit/arm32) due to following exception.

```
FAILED   - [   0][   2s]JIT/CodeGenBringUpTests/Add1/Add1.sh
               BEGIN EXECUTION
               /mnt/albireo/mywork/device/rpi3/unittests/coreoverlays/coreoverlay.test20170524.checked.master/corerun Add1.exe
               
               Assert failure(PID 26798 [0x000068ae], Thread: 26798 [0x68ae]): Assertion failed 'block != nullptr' in 'System.Text.StringBuilder:VerifyClassInvariant():this' (IL size 226)
               
                   File: /opt/code/github/hqueue/coreclr/src/jit/flowgraph.cpp Line: 1033
                   Image: /mnt/albireo/mywork/device/rpi3/unittests/coreoverlays/coreoverlay.test20170524.checked.master/corerun
               
               ./Add1.sh: line 240: 26798 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED

```

For example, all tests in  `JIT/CodeGenBringUpTests` are passed with `COMPlus_AltJit=* COMPlus_AltJitAssertOnNYI=0` before the commit, but now all failed.

### PR DESCRIPTION
**Pull request by hqueue**
This is a hotfix for #11870.
This just revert https://github.com/dotnet/coreclr/commit/e5d76089a7af352759ed395ecc3c2e61bd6f9640 partially for ryujit/arm32.

Let's dodge lowering long compares to avoid ryujit/arm32 failure
and enable it later when required implementation is available.

Fix #11870

### CODE REVIEW

**Comment by mikedn** [comment]
Makes sense, I've placed the new code inside the ifdef but in the process I also took out the condition that prevented the existing code from running on long compares that aren't used by a `GT_JTRUE`. Your change restores that condition, thanks!

I'll try adding ARM support for `GT_CMP` and `GT_SETCC` one of these days, then we can get rid of a bunch of code.

**Comment by hqueue** [comment]
> I'll try adding ARM support for GT_CMP and GT_SETCC one of these days, then we can get rid of a bunch of code.

Thank you :)

**Comment by mikedn** [comment]
> I'll try adding ARM support for GT_CMP and GT_SETCC one of these days, then we can get rid of a bunch of code.

WIP here: #11884

**Comment by hqueue** [comment]
Please merge this hotfix for ruyjit/arm32.
Although #11884 will fix the problem, it seems that we need more time to bring up and tests.

**Comment by RussKeldorph** [comment]
@dotnet/jit-contrib @dotnet/arm32-contrib

**Pull request merged**
