### PR TITLE
Work around disabled MyGet servers

### PR DESCRIPTION
**Pull request by sdmaclea**
Remove finalize-publish step which broke when MyGetServers were disabled

### CODE REVIEW

**Comment by sdmaclea** [comment]
I am trying an internal build of this https://dev.azure.com/dnceng/internal/_build/results?buildId=947630&view=results

**Comment by hoyosjs** [comment]
Oops, I should've been a little more explicit. The job I was talking about was this: https://github.com/dotnet/coreclr/blob/c42cf1b9a7598eb69d945e810fb145c79c7c7ce3/eng/finalize-publish.yml#L23-L61

**Comment by sdmaclea** [comment]
I initially looked at that but thought it made sense to disable the non-existent logs

https://github.com/dotnet/coreclr/blob/c42cf1b9a7598eb69d945e810fb145c79c7c7ce3/eng/finalize-publish.yml#L63-L72

and non-existent artifacts too

https://github.com/dotnet/coreclr/blob/c42cf1b9a7598eb69d945e810fb145c79c7c7ce3/eng/finalize-publish.yml#L74-L79

So at that point the template would be empty, and it made more sense to disable the whole template.

So I thought this PR was better.

**Comment by hoyosjs** [comment]
When you delete that, publishing to BAR also goes away. Publishing then becomes hard to track.

**Comment by sdmaclea** [comment]
Revised per our discussion.

New internal test run https://dev.azure.com/dnceng/internal/_build/results?buildId=948521&view=results

**Review by hoyosjs — APPROVED** [review]

**Pull request merged**
