### PR TITLE
Update some paths, fix typos

### PR DESCRIPTION
**Pull request by BruceForstall**
cc @richlander

### CODE REVIEW

**Comment by ellismg** [comment]
One minor comment, LGTM otherwise.  Thanks for the improvements, Bruce!

**Comment by jasonwilliams200OK** [comment]
:+1: (failing build seems unrelated)
@dotnet-bot test this please.

**Comment by ellismg** [comment]
Bruce, can you squash the two commits together?  Once that's done, I'll merge.

**Comment by BruceForstall** [comment]
@ellismg I finally (!) squashed. Can you merge?

**Pull request merged**
