### PR TITLE
Add option to runtest.sh to enable limited dump generation.

### PR DESCRIPTION
**Pull request by adityamandaleeka**
This change adds an option to runtest.sh that we can use in our CI to enable limited core file generation.

@sergiy-k @wtgodbe

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
cc: @mmitche

**Comment by adityamandaleeka** [comment]
I went ahead and added the netci.groovy change to this PR as well so that the CI jobs will pass the newly added option to runtest.sh.

**Comment by wtgodbe** [comment]
LGTM

**Comment by sergiy-k** [comment]
LGTM

**Comment by adityamandaleeka** [comment]
@dotnet test this please

**Comment by sergiy-k** [comment]
@dotnet-bot test ci please

**Comment by adityamandaleeka** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Comment by adityamandaleeka** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test

**Pull request merged**
