### PR TITLE
Improve buildtest.cmd, runtest.cmd

### PR DESCRIPTION
**Pull request by BruceForstall**
Apply the same kind of changes that were applied to build.cmd:
1. Improved readability and structure of the code.
2. Make all three look similar.
3. Add "sequential" and "msbuildargs" options
4. Add better logging and less verbose console output

### CODE REVIEW

**Comment by BruceForstall** [comment]
@pgavlin @mmitche PTAL

**Comment by BruceForstall** [comment]
@dotnet-bot test windows_nt

**Comment by BruceForstall** [comment]
@dotnet-bot retest windows

**Comment by mmitche** [comment]
@dotnet-bot test Windows_NT x86 Release Build

**Comment by mmitche** [comment]
@dotnet-bot test Windows_NT x86 Debug Build

**Comment by pgavlin** [comment]
LGTM

**Pull request merged**
