### PR TITLE
Using full versions, update CoreFX dependencies to beta-24326-03

### PR DESCRIPTION
**Pull request by dagood**
Full versions ensures that major/minor/patch versions are upgraded too. Upgrading only the prerelease part made NuGet bring in old dependencies because the versions became invalid.

(If https://github.com/dotnet/buildtools/pull/919 goes well, I'll be adding full-version package upgrade to this repository sometime this week.)

This PR also adds a `test_runtime` and applies other fixes to successfully build and run after applying the upgrade.

/cc @wtgodbe

### CODE REVIEW

**Comment by wtgodbe** [comment]
I think we may want to switch from dnxcore50 to netstandard/netcoreapp (for the 'framework' property in the project.jsons). I'll play around a bit.

**Comment by wtgodbe** [comment]
Hmmm, that may not be it either. Still tinkering.

**Comment by wtgodbe** [comment]
@karajas do you have any context as to why this might be causing failures during package restore? I tried switching to netstandard1.3/netcoreapp1.1 locally and got similar errors, but about 20 times as many...

**Comment by wtgodbe** [comment]
CC @MattGal as well (This is an updated version of what I sent you this morning)

**Comment by dagood** [comment]
Focusing on one project.json, I was able to get it to restore by upgrading the stable dependencies to RTM versions and changing to netstandard1.6. https://github.com/dagood/coreclr/commit/95278d95b156349819d6f9a779dc5da309e64c24

I could make my tooling upgrade non-prerelease versions to the entries in https://github.com/dotnet/versions/blob/master/build-info/dotnet/corefx/release/1.0.0/LKG_Packages.txt for a one-time upgrade from rc2 to RTM... is that the right thing to do?

**Comment by wtgodbe** [comment]
@dagood Yes, I think that would be the right thing to do. Can you rebase your change into this PR?

**Comment by dagood** [comment]
Sure. I'll have to retool a bit first (I did that commit manually). A tricky part (unless I'm missing something) is finding a minimal netstandard. For now I'll just make everything 1.6, but I think we want that as low as possible for each project.

**Comment by wtgodbe** [comment]
Yeah, that is tricky... Assuming this works, I can keep making progress on Helix & file an issue on the frameworks thing so we can come back to it later

**Comment by wtgodbe** [comment]
@dagood  I think you may need to go through and update each project.json to 'netstandard1.6'...

**Comment by dagood** [comment]
Sorry, that was an accidental push. I added `netstandard1.6` and I'm testing locally, and `imports` for `dnxcore50` seem necessary in a few places.

**Comment by wtgodbe** [comment]
Gotcha, no worries

**Comment by dagood** [comment]
Running locally to get a repro. Fyi, the following restore error is intentional:

```
15:59:00 RUNTEST: Invoking msbuild
15:59:38   
15:59:38   Errors in D:\j\workspace\debug_windows---17180f1b\tests\\..\bin\tests\tempRestoreProject\project.json
15:59:38       Package xunit.runner.msbuild 2.1.0 is not compatible with net45 (.NETFramework,Version=v4.5). Package xunit.runner.msbuild 2.1.0 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
15:59:38 
      One or more packages are incompatible with .NETFramework,Version=v4.5.
```

That restore is supposed to happen with errors turned off because of that compatibility issue--not sure why Jenkins is pointing it out.

**Comment by wtgodbe** [comment]
Yeah, this built just fine for me locally - not sure what's happening in the CI.

**Comment by wtgodbe** [comment]
@dotnet-bot test this please

**Comment by dagood** [comment]
I got the same errors as CI when starting from clean--no System.Runtime.dll at all was copied to `CORE_ROOT`. Tried changing https://github.com/dotnet/coreclr/blob/master/tests/publishdependency.targets#L6-L7 to `.NETStandard,Version=v1.6` and `netstandard1.6`, and I got a System.Runtime but apparently the wrong version. (Frustratingly I can't get the fusion log to show up even after setting through `fuslogvw` and `ComPlus_ForceLog=1`.)

**Comment by wtgodbe** [comment]
That may have been my issue, I'm building from clean now. I'm not sure if these are relevant, but could it have anything to do with these references to dnxcore50?

https://github.com/dotnet/coreclr/blob/master/tests/setup-runtime-dependencies.cmd#L83
https://github.com/dotnet/coreclr/blob/master/tests/setup-runtime-dependencies.sh#L125
https://github.com/dotnet/coreclr/blob/master/tests/runtest.proj#L374
https://github.com/dotnet/coreclr/blob/master/src/.nuget/init/project.json#L6

**Comment by dagood** [comment]
Not sure, I wouldn't expect those to cause System.Runtime and similar to be copied wrong, though.

Looking at the dlls, it looks to me that the runtimes are coming from the wrong packages. Right now, (for System.Runtime) the runtime is coming from `runtime.any.System.Runtime` `4.1.0`, but `4.1.1-beta-...` is used in the project.jsons. (And when I drop in `runtime.any.System.Runtime` `4.1.1-beta-...`, it loads that dll and complains on a different one, at least for `readytorun\genericsload\callgenericctor\callgenericctor.cmd`. That suggests to me that `4.1.1-beta-...` is correct.)

Then I noticed that System.Runtime has a dependency on `Microsoft.NETCore.Targets` `1.0.2-beta-24326-03`, which results in `1.0.2` being restored because we're really on `1.0.3-beta-...` now. Unless I'm mistaken, that explains why the RTM runtimes are bring brought in. @ericstj This is a bug in the packages, right?

For now, I'm going to try adding a `Microsoft.NETCore.Targets` dependency to each project.json to see if bringing in the right one will fix things.

**Comment by ericstj** [comment]
> I noticed that System.Runtime has a dependency on Microsoft.NETCore.Targets 1.0.2-beta-24326-03, which results in 1.0.2 being restored because we're really on 1.0.3-beta-... now. Unless I'm mistaken, that explains why the RTM runtimes are bring brought in. @ericstj This is a bug in the packages, right?

Yeah that's a bug.

**Comment by dagood** [comment]
Adding `Targets` fixed some of those, but not all. It looks like some lockfiles are stomping over others--for example, `System.Threading.Thread` fails because it wants `4.0.1-...` but `4.0.0` is in the `CORE_ROOT`. I took all the `RunTimeDependecyCopyLocal` items and wrote them out (deduped) to a file: https://gist.github.com/dagood/bac248fb06da2a4411aaa9532795c52c.

For example, `System.Threading.Thread` shows up twice, and the later one is `4.0.0` so that one ends up copied. Searching the lockfiles for `System.Threading.Thread/4.0.0` turns up 11 projects (and searching `System.Threading.Thread"` inside the lockfile shows what depends on `4.0.0`.)

If coreclr had a test-runtime project.json or something similar (like corefx) I believe this could be solved by making sure there's an entry for the desired System.Threading.Thread. I don't have a good solution with how coreclr tests are set up.

**Comment by wtgodbe** [comment]
@dagood I'm actually planning on adding something like a test-runtime project.json to coreCLR to express a common dependency on the CoreCLR Runtime package for building tests against - I can add whatever you think is needed to that (anything more than System.Threading.Thread?). I'll work on that today/tomorrow. Is it possible for me to work in this same branch so my change can go into this PR?

**Comment by dagood** [comment]
Cool, that should help quite a bit! I've given you push access to my fork, go ahead.

I think more will be needed, it's just that the errors that show up only show the first assembly that failed to load. You might be able to use that file I linked and look for more duplicates. For example `System.Runtime.Numerics` has two conflicting entries so I imagine it will need to be added too.

**Comment by wtgodbe** [comment]
Great, I'll start working on that. To clarify, this is something you'd expect this to be imported by every test project.json, correct?

**Comment by dagood** [comment]
That's what I'd expect based on corefx, but I don't know for sure exactly how that link works. @ericstj Do you know if this sounds like a reasonable thing to do to avoid taking RTM dependencies?

**Comment by ericstj** [comment]
The app still wins if it directly references a lower version.  Restore emits warnings for these things (package downgrades) we should just treat those seriously and fix up all the projects.

**Comment by wtgodbe** [comment]
@ericstj so the solution is to go through the package downgrade warnings & bring all the project.json files up to the correct version? @dagood is there a reason your automated upgrade didn't do this/wouldn't do this in the future?

**Comment by wtgodbe** [comment]
OK, an example would be System.Diagnostics.Process relying on System.Threading.Thread >= 4.0.0, while all of our project.jsons (that reference System.Threading.Thread) rely on 4.0.1. The only place 4.0.1 shows up is in our lockfiles, so we must be getting that dependency from System.Diagnostics.Process - should we be upgrading that package's dependency list somehow? How would we go about doing that?

**Comment by ericstj** [comment]
@wtgodbe that case is fine.  In that case you are not downgrading the dependency.  Your test project is upgrading the dependency which works fine.

**Comment by dagood** [comment]
The issues here are caused by the RTM-versioned dependencies packages take, so it's only visible in the lockfile and we do minimal validation on that. I don't think it would be easy to add this validation, either--probably more worthwhile to use what NuGet tells us. It's not a problem with upgrading, it's that some packages depend on RTM versions which causes a problem with the coreclr tooling because it relies on all dependencies being the same.

I think you meant `4.0.0` in this:

> The only place 4.0.1 shows up is in our lockfiles, so we must be getting that dependency from System.Diagnostics.Process

To explain a bit more, I think this can be fixed by adding a test-runtime project with the `4.0.1-...` dependency, so we get a graph like this:

* The test
   * Process `>= 4.1.0`
      * Thread `>= 4.0.0`
   * test-runtime
      * Thread `>= 4.0.1-beta`

[Since they're cousins](https://docs.nuget.org/Consume/ProjectJson-Dependency), Thread `4.0.1-beta` is what's resolved. If the naming is intuitive, `"exclude": "compile"` on test-runtime prevents test writers from inadvertently depending on a package not listed in the "root" project.json.

**Comment by dagood** [comment]
To fill it out, a downgrade would be like this:

* The test
   * Runtime `>= 4.1.0`
   * test-runtime
      * Runtime `>= 4.1.1-beta-24326-03`

The nearer one wins, and you get restore warnings:

```
warn : Detected package downgrade: System.Runtime from 4.1.1-beta-24326-03 to 4.1.0
warn :  test (>= 1.0.0) -> test-runtime  -> System.Runtime (>= 4.1.1-beta-24326-03)
warn :  test (>= 1.0.0) -> System.Runtime (>= 4.1.0)
```

**Comment by wtgodbe** [comment]
So, here's how I'm seeing the solution looking:

Find all packages that get overwritten/downgraded & put them into a common test-runtime project.json, then import that at the bottom of all current test project.json files. If any current project.json relies on something that's going into test-runtime (i.e. System.Threading.Thread), should I remove that from the test project.json since it'll be covered by the test-runtime project.json? @dagood

**Comment by wtgodbe** [comment]
https://github.com/dotnet/coreclr/pull/6479/commits/6c36a2a82a7bce88aa51d6aa6ad830ab7b277c65 here's a crack at the test_runtime project.json, what do you think?

**Comment by dagood** [comment]
I think your plan sounds about right. I don't think you should remove any dependencies from the test project.jsons, because if I understand it, `"exclude": "compile"` means they are still necessary to build. This seems to me like a good thing, having the test-runtime's sole purpose to upgrade the runtimes. I'm also pretty sure the order doesn't matter. (I usually sort dependencies.)

I don't think there's actually a downside to putting *every* CoreFX test dependency in the test-runtime project.json, if that's easier to assemble... in fact, I think that would be more futureproof if the tests get more dependency combinations.

This isn't a fix for downgrades, though, just the CORE_ROOT overwrites... hmm. I may have made a mistake upgrading from rc2->RTM, where it should've been rc2->latest prerelease. Does the goal here involve testing RTM in any way, @wtgodbe?

**Comment by wtgodbe** [comment]
That project.json just has the dependencies that were overwritten in the file you linked. I can add more if need be. And I think rc2->latest prerelease would've been the way to go. Does that remove the need for test-runtime?

**Comment by markwilkie** [comment]
Including @chcosta because he's also been heavily involved in our test builds and might be interested in following along.

**Comment by dagood** [comment]
I don't think the `Microsoft.NETCore.Runtime.CoreCLR` is necessary (the project.json autogen in `runtest.proj` fetches that based on what kind of build is happening) but otherwise that test-runtime looks reasonable to me, and adding more as needed sounds fine.

Upgrading to latest doesn't replace the test-runtime, because the latest packages have RTM dependencies where possible. (One benefit of RTM dependencies is that people can upgrade individual packages without having to bring in the entire prerelease set.) I'll redo that upgrade on top of the changes here.

**Comment by dagood** [comment]
Pushed the upgrade to https://github.com/dagood/coreclr/tree/update-deps-latest instead of here because it's known that it won't pass CI. (Still needs test-runtime, and either a `Targets` dependency or a CoreFX build with the fix in https://github.com/dotnet/corefx/pull/10377.)

**Comment by wtgodbe** [comment]
Alright, added the dependency on test-runtime (called test_runtime in coreCLR since we already had a folder named such with a .csproj file in it). Here's the commit - https://github.com/dotnet/coreclr/pull/6479/commits/407987432d1e48ad280688aa5ae9dfb94c09b00d (Each file should've been changed in the same way, so once you've seen one, you've seen 'em all)

**Comment by wtgodbe** [comment]
@dotnet-bot test this please

**Comment by wtgodbe** [comment]
@dagood I may be missing something here - does coreFX do something explicit to make the string `"test-runtime"` reference the project.json file under `src\Common\test-runtime` ? I imagine I'd have to do something to achieve that in coreCLR for the string `test_runtime` and the project.json under '`tests\src\Common\test_runtime`

**Comment by dagood** [comment]
`dotnet restore` uses the folder name the project.json is in and matches it up, so nothing extra needs to happen there. I don't know the exact rules but I used it to make that downgrade example.

About the CI dependency validation failure, the test_runtime deps have `"targets": "project"` instead of `"target": "project"`. (When I said `Targets` I meant the `Microsoft.NETCore.Targets` dependency--sorry if that tripped this up. On that note, maybe `Targets` could just be added as a test_runtime dependency?)

I'll rerun the update-deps-latest changes, since they're conflicting with the test_runtime add now. I'll push it to this branch this time.

**Comment by wtgodbe** [comment]
Oh, crap, I don't know how that happened. I thought I ctrl-c'd straight from a corefx project.json, but I guess not... I'll go back and fix (& add Microsoft.NETCore.Targets)

**Comment by dagood** [comment]
I did a find-replace for targets->target and saw that there was a `test_runtime` dependency in `test_runtime` too, removed that. That `Microsoft.NETCore.Targets` dep is the last known-needed fix. :smile:

**Comment by wtgodbe** [comment]
You beat me to it! I'll pull down this change and add Microsoft.NETCore.Targets to test_runtime.

**Comment by wtgodbe** [comment]
Whoops, had the wrong version of NETCore.Targets. Just fixed.

**Comment by wtgodbe** [comment]
> EXEC : error : Unable to resolve 'test_runtime' for '.NETStandard,Version=v1.6'. [D:\j\workspace\debug_windows---17180f1b\tests\build.proj]

Looks like we're seeing this error 1164 times, which is about 2 times the number of project.json files we modified. Any idea what we're missing to fix this?

**Comment by dagood** [comment]
Taking a look, I guess there is more to the linkage than folder name if the parent folders aren't adjacent.

**Comment by dagood** [comment]
Where dotnet looks is determined by the global.json in the working directory. Pushing a commit to add one, but I do get more package restore errors afterwards so I'm using `update-deps-latest`.

**Comment by dagood** [comment]
Merged that up, and a few more things. I have a test build going locally with these changes, and it hasn't failed so far.

* Added the global.json.
* Removed test_runtime from TestWrapperConfig, since it's `net45` and not compatible with a bunch of stuff.
*  I changed `netstandardapp1.6` to `netcoreapp1.0` because I saw the huge number of warnings telling me to and https://github.com/dotnet/coreclr/pull/6112 attempting to do so. The warnings stopped showing up, and I haven't seen any new errors coming from it.

**Comment by wtgodbe** [comment]
Sweet! Yeah I'm realizing now I probably added test_runtime in a couple places it shouldn't be, I just did a big find+replace across all the project.jsons...

**Comment by dagood** [comment]
Yeah, and it's tough to validate these things when the builds take so long.

Speaking of which, errors happened when I got to runtests with that last commit, but I changed the framework being published from dnxcore50 to netcoreapp1.0, and some tests are actually completing! We'll see if there are any errors later on in. I've created a new deduped `RunTimeDependecyCopyLocal` list, looking a lot better: https://gist.github.com/dagood/78452aba6a59c740b1595ce0c6fe374a.

**Comment by wtgodbe** [comment]
Well it definitely got a lot further than last time... I'm seeing a lot of these:

> Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Linq, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference.

I gotta run, but I can take a look tomorrow.

**Comment by dagood** [comment]
Cool, that just meant we needed more test-runtime entries. I added `System.Linq` and two others, since they were the duplicates in the file:
```
System.Linq
    4.1.1-beta-24328-05
    4.1.0

System.Reflection.Emit.Lightweight
    4.0.1
    4.0.2-beta-24328-05

System.Threading.Overlapped
    4.0.1
    4.0.2-beta-24328-05
```

I got a successful runtest locally, hopefully CI agrees.

**Comment by wtgodbe** [comment]
Nice! Got any last minute tweaks? If not, I'm gonna merge this after my 1-on-1

**Comment by dagood** [comment]
Ah, cool, it worked! I'll squash the commits, but other than that seems fine to me.

**Comment by RussKeldorph** [comment]
Anybody know if it's easy to make this warning break the build so no one can inflict this on us in the future and leave it broken for so long?

**Comment by ericstj** [comment]
Yeah, once you're clean just add the appropriate RegEx's to the restore command Exec invocation so that it propagates the errors/warnings from the commandline spew.

**Comment by dagood** [comment]
I think the warnings fixed by this PR are from `PrereleaseResolveNuGetPackageAssets`, not restore. (Maybe there are both, not sure.) It looks like changing [`AllowFallbackOnTargetSelection`](https://github.com/dotnet/coreclr/blob/4e87b31976f92f9c9d9d1a835c7b4b6d939c4091/tests/publishdependency.targets#L32) to `false` will make these kinds of warnings into errors, validating that now.

**Pull request merged**
