### PR TITLE
Generate CoreCLR Nuget Package for CentOS, Debian and RHEL

### PR DESCRIPTION
**Pull request by gkhanna79**
@ellismg PTAL

### CODE REVIEW

**Comment by gkhanna79** [comment]
@ellismg @mmitche Can you remind me how do I ask CI to be tested (this is a CI specific change)?

**Comment by mmitche** [comment]
Test ci please

Sent from my Windows Phone
________________________________

**Comment by gkhanna79** [comment]
Test ci please

**Comment by gkhanna79** [comment]
@dotnet-bot test CentOS7.1 x64 Checked Build please

**Comment by gkhanna79** [comment]
@mmitche How can I test this CI change without committing? The change makes CentOS no longer pass "skipmscorlib" to build but the CentOS CI build still passes it.

**Comment by stephentoub** [comment]
@gkhanna79, unfortunately I believe there's no current way... it'll only pick up the checked in file rather than what's in the PR.  @mmitche can correct me if I'm wrong.  The "test ci please" helps to verify syntax and the like, but for the semantics you'll need to cross your fingers and merge I think.

**Comment by gkhanna79** [comment]
@stephentoub Thank you. I will merge this once the job completes.

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@gkhanna79 That's correct.  The reasons behind this are both technical and security.

**Pull request merged**
