### PR TITLE
Port fix for ARM in ildasm

### PR DESCRIPTION
**Pull request by kyulee1**
This is port for ARM that Serge Lidin fixed.

### CODE REVIEW

**Comment by jkotas** [comment]
What is this needed for? ARM managed images never had the legacy entrypoint. See https://github.com/dotnet/coreclr/blob/master/src/dlls/mscorpe/pewriter.cpp#L800

**Comment by pgavlin** [comment]
Ping. Any updates here?

**Comment by BruceForstall** [comment]
@kyulee1 Is this ready to be merged? Do you need to rebase/retest?

**Comment by adityamandaleeka** [comment]
Is this PR still relevant/needed @kyulee1?

**Pull request closed without merging**
