### PR TITLE
Revert "Delete suspicious code in delegate construction (#22830)"

### PR DESCRIPTION
**Pull request by jashook**
This reverts commit 674bdcbc2ac824d005b5179cee3c5826b582b9a6.

This is to test if the outerloop jobs are fixed with a revert.

### CODE REVIEW

**Comment by jashook** [comment]
This cleanly runs the outerloop tests. @MichalStrehovsky let me know if you want to merge the revert, disable the tests or you have another fix.

/cc @RussKeldorph

**Comment by MichalStrehovsky** [comment]
Let's merge. No need to put the fix for #23317 on a hot path.

**Pull request merged**
