### PR TITLE
Update the lst file to exclude failing tests.

### PR DESCRIPTION
**Pull request by jashook**
These are new regressions that were introduced during CI downtime.

### CODE REVIEW

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Checked

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Release

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@dotnet-bot test Windows_NT Arm64 Release

**Comment by mmitche** [comment]
@dotnet-bot test Windows_NT Arm64 Checked

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Checked

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Checked

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Release

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Release

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Checked

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Release

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Checked

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Release

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Checked

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Release

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Release

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Checked

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Release

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Checked

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Checked

**Comment by jashook** [comment]
@mmitche ptal

**Comment by jashook** [comment]
@briansull ptal

**Comment by briansull** [comment]
LGTM

**Pull request merged**
