### PR TITLE
Adding Trim, TrimStart and TrimEnd for single char.

### PR DESCRIPTION
**Pull request by annagalaeva**
Implementing additional signature for Trim function that would take a single char as the argument to address this issue: https://github.com/dotnet/coreclr/issues/1826

### CODE REVIEW

**Comment by annagalaeva** [comment]
@ellismg

**Comment by shahid-pk** [comment]
wow i tried to resist but could not, seriously this is the third or fourth time in one day when four different people send the same pr . amazing.

**Comment by ellismg** [comment]
@shahid-pk This is part of an internal exercise we're using to help some internal folks get up to speed with CoreCLR, CoreFX, git and GitHub.

**Comment by shahid-pk** [comment]
@ellismg got it. thanks for clearification

**Comment by annagalaeva** [comment]
Happy to be the one who broke resistance to ask ☺
You should get a dozen more – pick the one you like the most ☺

**Comment by jkotas** [comment]
Dup of #2070

**Pull request closed without merging**
