### PR TITLE
Enable unix readytorun tests

### PR DESCRIPTION
**Pull request by janvorli**
Enable readytorun tests on Unix.

### CODE REVIEW

**Comment by janvorli** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
CC @JohnChen0 as well.

**Comment by janvorli** [comment]
@jkotas can you take a look please? It should be final now. 
I have made few additional changes. 
 - The native images are now generated side by side with the IL assemblies and not into the NI subfolder. 
 - I have added a coreroot option to the generated scripts - the same as we have in the generated batch files on Windows. It is useful for running the test script standalone.
 - I have fixed a bug in the generated script where instead of **Bash**CLRTestExecutionScriptArgument, it was using **Batch**CLRTestExecutionScriptArgument.
 - Like on Windows, the test script changes the current directory to the directory of the script at the beginning.

**Comment by jkotas** [comment]
LGTM. Thanks!

**Pull request merged**
