### PR TITLE
Use the alt JIT for S.P.CoreLib if altjitcrossgen is specified and change crossgen to always pass USE_SSE2 to the JIT.

### PR DESCRIPTION
**Pull request by pgavlin**
The check for altjitcrossgen was previously located s.t. only mscorlib
was being crossgen'd using the alt JIT (which is not very insteresting,
as mscorlib is just a facade these days). This change moves the check
back s.t. the alt JIT is also used for System.Private.CoreLib.

Moving this check revealed that the JIT wil now assert if SSE2 is not
enabled on x86. These changes also update crossgen to always pass
USE_SSE2 for FEATURE_CORECLR.

### CODE REVIEW

**Comment by pgavlin** [comment]
@BruceForstall @jkotas @dotnet/jit-contrib PTAL

**Comment by pgavlin** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Comment by pgavlin** [comment]
`jit-diff` indicates no diffs with this change.

**Comment by BruceForstall** [comment]
There was a discussion that the zapper change causes bad diffs on x86 (JIT32 and RyuJIT?). Are you going to investigate those before merging?

**Comment by pgavlin** [comment]
@BruceForstall I do intend to collect and investigate diffs before merging. It will probably be a bit challenging, as I will first need to find the last commit at which we were able to successfully run crossgen.

**Comment by pgavlin** [comment]
@BruceForstall: AFAICT this does not cause diffs for RyuJIT. I am now looking into JIT32.

**Comment by pgavlin** [comment]
@BruceForstall: there are code size regressions on JIT32. All of those that I've looked at involve struct copies moving from `push` (for outgoing arguments) or `movsd` to moves through SSE2 registers. I still think that we should take this, as it is blocking our S.P.CoreLIb coverage for RyuJIT/x86 (which is our primary scenario in any case).

**Comment by BruceForstall** [comment]
ok. Agreed.

**Pull request merged**
