### PR TITLE
ARM64:Increase test timeout

### PR DESCRIPTION
**Pull request by rahku**

### CODE REVIEW

**Comment by rahku** [comment]
@dotnet-bot test Windows_NT arm64 checked gcstress0x3

**Comment by rahku** [comment]
@dotnet-bot test Windows_NT arm64 checked gcstress0x3

**Comment by danmosemsft** [comment]
@rahku what remains to get this PR closed one way or another?

**Comment by rahku** [comment]
waiting for arm64 test infra to be back up again. @jashook  is working on it.

**Comment by danmosemsft** [comment]
@jashook any update on the ARM infra?

**Comment by danmosemsft** [comment]
@dotnet-bot test this

**Comment by jashook** [comment]
@danmosemsft this is still being worked on. The arm64 tests are still expected to fail but should give the tests that failed during the run. Some of these are due to an out of date set of framework assemblies which is being refreshed now.

**Comment by danmosemsft** [comment]
Thanks @jashook

**Comment by Petermarcu** [comment]
@jashook , Any update here?

**Comment by jashook** [comment]
@Petermarcu @danmosemsft the CI is operational again for arm64. It has failures which are currently being worked on to be baselined away to get the jobs green.

**Comment by rahku** [comment]
Closing this PR. We need to do more investigation that just these failing tests.

**Pull request closed without merging**
