### PR TITLE
Refactor context register access in seh-unwind.cpp

### PR DESCRIPTION
**Pull request by janvorli**
This change refactors the native context register access to use the
MCREG_xxx macros so that it can compile on FreeBSD too.

### CODE REVIEW

**Comment by janvorli** [comment]
@sergiy-k Can you take a look please?
cc: @josteink, @kangaroo

**Comment by josteink** [comment]
I've fetched the sources, manually patches for my changes in [this PR](https://github.com/dotnet/coreclr/pull/647) and done a local build on FreeBSD x86_64.

I can confirm this PR solves the problems encountered in https://github.com/dotnet/coreclr/issues/639 

LGTM.

**Comment by kangaroo** [comment]
LGTM

**Comment by sergiy-k** [comment]
LGTM

**Pull request merged**
