### PR TITLE
Allow remorph of SIMD assignment

### PR DESCRIPTION
**Pull request by CarolEidt**
This fixes an assert exposed by JitStress=1.

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL. This fixes Bug 288220

**Comment by pgavlin** [comment]
LGTM

**Comment by CarolEidt** [comment]
@briansull could you look at this? You suggested eliminating the assert, but I thought it might be better to simply change it to only apply to `fgGlobalMorph`

**Comment by briansull** [comment]
I still believe that the assert should probably be removed.
In fgGlobalMorph all nodes start off with that flag cleared.
And I don't understand what piece of code wants/depends on this flag being clear.
What would change if that flag was set (even though this never happens)

I also think that we should eventually remove this flag as it  job is to ensure that we morph each node in fgMorphSmpOp. (and it doesn't really do that)

**Comment by briansull** [comment]
LGTM (either with this or with it deleted)

**Pull request merged**
