### PR TITLE
Remove `fgSplitMethodTrees`.

### PR DESCRIPTION
**Pull request by pgavlin**
This code attempted to split trees that contained multiple calls
that returned floating-point values when targeting ARM. This code
was clearly incorrect--no attempt is made to obey the original tree
ordering (or indeed any valid ordering)--and it was in fact disabled
in JIT32. Remove it.

### CODE REVIEW

**Comment by pgavlin** [comment]
@briansull @dotnet/jit-contrib PTAL

**Comment by briansull** [comment]
Yes,  this method was incorrect and was called on ARM32 and we had to remove that call shortly before shipping, because as you say the implementation was clearly incorrect.

Good to remove this code

**Comment by briansull** [comment]
LGTM, except that Jenkins tests are all reporting failures :-(

**Comment by pgavlin** [comment]
This is the same issue I am seeing in #5650:

```
11:27:59 D:\j\workspace\debug_windows---17180f1b\tests\tests.targets(47,5): error MSB4062: The "Xunit.Runner.MSBuild.xunit" task could not be loaded from the assembly D:\j\workspace\debug_windows---17180f1b\tests\..\packages\xunit.runner.msbuild\2.1.0\build\portable-net45+win8+wp8+wpa81\xunit.runner.msbuild.dll. Could not load file or assembly 'file:///D:\j\workspace\debug_windows---17180f1b\packages\xunit.runner.msbuild\2.1.0\build\portable-net45+win8+wp8+wpa81\xunit.runner.msbuild.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [D:\j\workspace\debug_windows---17180f1b\tests\runtest.proj]
```

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test

**Comment by pgavlin** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Comment by pgavlin** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT x86 legacy_backend Checked Build and Test

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT x86 ryujit Checked Build and Test

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test

**Comment by CarolEidt** [comment]
LGTM - I like the cleanup!

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT x86 ryujit Checked Build and Test

**Comment by pgavlin** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Comment by pgavlin** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Pull request merged**
