### PR TITLE
Generate the dac table RVA using nm at build time.

### PR DESCRIPTION
**Pull request by mikem8361**
Remove the temporary PAL dac table file at runtime. Replaced it with dactablerva.h file generated at build time from the libcoreclr module. nm works across Linux, OSx and FreeBSD. Issue #501.

### CODE REVIEW

**Comment by mikem8361** [comment]
@Djuffin and @pgavlin can you review?

**Comment by Djuffin** [comment]
LGTM

**Comment by pgavlin** [comment]
LGTM as well.

**Comment by OtherCrashOverride** [comment]
Doesn't this introduce a version dependency on DAC:  If DAC changes, you have to rebuild (make) and recompile everything?  Shouldn't this use OS symbol resolution services like dlsym instead?

**Comment by mikem8361** [comment]
Yes, the DAC and DBI are already very version dependent on the coreclr. Most of the DAC code is the coreclr classes/code rebuilt with some different macros/defines so there is already the tight binding.

We could have still done the dactable copying at runtime via dlsym except then the coreclr module would have to be loaded in the debugger side process just to get the symbol. Since the module can be unloaded that may not be a big deal.

mikem

**Comment by OtherCrashOverride** [comment]
Also, how well does this method interact with Address Space Layout Randomization?

**Comment by Djuffin** [comment]
Coreclr module base address is detected at runtime, it's only DAC table offset inside the module that is "hardcoded", that's why randomization shouldn't affect it in any way.

**Comment by kangaroo** [comment]
That presumes that any ASLR mechanism does not do segment reordering.  This is called an RVA, but its not really an RVA.  Its a compile time constant offset from 0x0.

**Comment by Djuffin** [comment]
@kangaroo - good point. In case of segment reordering, loading coreclr into debugger process and calling dlsym() wouldn't help either. 

Are there any systems out there known to do segment randomization for shared libraries? We'd like to  test it properly.

**Comment by kangaroo** [comment]
@Djuffin Why would dlsym() not work?  dlsym (should) get fixup information from the rt linker.  I think you're making assumptions about the dlsym implementation.

I'm not sure if there are public implementations, but I am aware of systems that do segment randomization.

**Comment by Djuffin** [comment]
Correct me if I'm wrong, but if a managed **debugger** loads libcoreclr and calls dlsym("g_dacGlobals") on it, this address would in no way help to locate address of g_dacGlobals in a **debugee** process, assuming segment randomization is working.

**Comment by kangaroo** [comment]
I understand now.  I don't think its possible to resolve this without debugee cooperation.

**Comment by mikem8361** [comment]
@kangaroo, @Djuffin, @OtherCrashOverride

I’m assuming you mean resolve any problems with ASLR.  I’m going to go ahead and merge this change because it fixes a bunch of other problems for crashdumps, etc.

**Pull request merged**
