### PR TITLE
update xunit-performance to build0047

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Seeing if this will fix recent issues with the serialization tests (#9733)

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
Doesn't work for me locally, so not optimistic. Failure was:
```
C:\repos\coreclr2\Tools\VersionTools.targets(47,5): error : Dependency verification errors detected. To automatically f
ix based on dependency rules, run the msbuild target 'UpdateDependencies' [C:\repos\coreclr2\tests\build.proj]
C:\repos\coreclr2\Tools\VersionTools.targets(47,5): error : Dependencies invalid: In 'C:\repos\coreclr2\tests\src\Commo
n\test_dependencies\project.json', 'Microsoft.DotNet.xunit.performance 1.0.0-alpha-build0047' must be '1.0.0-alpha-buil
d0040' (Microsoft.DotNet.xunit.performance)
```
Tried running the UpdateDependencies build target as directed but nothing happened.

Am going to retry after a `git clean -dfx`

**Comment by AndyAyersMS** [comment]
CI hitting the same issue so evidently there's something else that must be changed.

**Comment by jkotas** [comment]
@AndyAyersMS You also need to update it in https://github.com/dotnet/coreclr/blob/master/dependencies.props#L72

**Comment by AndyAyersMS** [comment]
Thanks, trying that locally now...

**Comment by AndyAyersMS** [comment]
Locally still having issues, though am also experiencing some network flakiness.
```
EXEC : error : Unable to resolve 'Microsoft.DotNet.xunit.performance.analysis (>= 1.0.0-alpha-build0047)' for '.NETStan
dard,Version=v1.4'. [C:\repos\coreclr2\tests\build.proj]
```

**Comment by AndyAyersMS** [comment]
Based on dotnet/corefx#15767 it looks like packages were added/dropped and so a simple version bump is not likely to work.

**Comment by brianrob** [comment]
@AndyAyersMS, you're right.  We'd need to publish more packages from xunit.performance to make this work.  I want to see if we can keep the xunit.performance files that come in from corefx from being copied.

**Pull request closed without merging**
