### PR TITLE
Add linux-musl build leg

### PR DESCRIPTION
**Pull request by weshaggard**
cc @eerhardt @janvorli 

fyi @RussKeldorph

### CODE REVIEW

**Comment by sdmaclea** [comment]
Any comment on this ?   Is this intended to be experimental ?  New direction ?

**Comment by kasper3** [comment]
@sdmaclea, trivia: it started at https://github.com/dotnet/core/issues/1331, moved to https://github.com/dotnet/core-setup/issues/3817, assembly names discussion https://github.com/dotnet/corefx/issues/28554, RIDs updated with `linux-musl` PR https://github.com/dotnet/corefx/pull/28560 and corresponding corefx PR to this change: https://github.com/dotnet/corefx/pull/29168.

In short:

* `linux-x64` continues to mean "linux x64 with glibc-ism", no change there
* `linux-musl-x64` triplet, which does not inherit from `linux-x64` but instead is its sibling, means "linux x64 with muscle libc"

In future, we can add dietlibc, uclibc, bionic-libc etc. to give some room for non-gnu-ism, other POSIX candidates: busybox, toybox etc.

**Comment by eerhardt** [comment]
@kasper3 - that is a pretty good summary of the activity.  However, one piece was incorrect:

> linux-musl-x64 triplet, which does not inherit from linux-x64 but instead is its sibling,

Actually, `linux-musl-x64` does inherit from `linux-x64`.  See the [RID hierarchy here](https://github.com/dotnet/corefx/blob/ab8e81453fa869556821c464bd5824b588d679cd/pkg/Microsoft.NETCore.Platforms/runtimeGroups.props#L12-L15) and the reasoning/justification in the discussion starting [here](https://github.com/dotnet/core-setup/issues/3817#issuecomment-377328964).

**Comment by eerhardt** [comment]
Note - the over-arching idea here is to not produce "alpine" branded packages/tarballs.  Instead these binaries and packages are intended to work across any musl based Linux.  So we are in the process of renaming "alpine" in the packages to "linux-musl".  The steps are:

1. Add the new linux-musl packages.
1. Do this throughout the stack to keep it building. (coreclr -> corefx -> core-setup -> CLI)
1. Remove the "alpine" packages in the reverse order.  (CLI -> core-setup -> corefx -> coreclr)

This way nothing breaks during the rename process.

**Comment by kasper3** [comment]
While building CoreCLR, should we expect output directory to be `bin/Product/Linux.musl.arm.Debug/` or `bin/Product/Linux.arm.Debug/`? If former is expected than I am getting latter with current master.

**Comment by kasper3** [comment]
@weshaggard, I noticed when working on https://github.com/dotnet/coreclr/pull/17730. Using build steps from https://github.com/dotnet/coreclr/issues/17468#issuecomment-382831060 on `troyfontaine/armhf-alpinelinux` docker (it's pure alpine 3.7 arm32 with additional qemu layer for x64), and changes from my branch; coreclr built successfully.
Was just wondering if `OutputDir` should also have a different name on alpine (as in on x64; `Linux.musl.x64.Debug`)?

**Comment by AddRemover** [comment]
I am looking for a dotnet runtime compliled to run on arm32 bin with musl.
The target is to run one .net app on my OpenWRT router Linksys WRT3200ACM which is arm32.
So, I can't use musl-arm64, I need musl-arm32.

**Pull request merged**
