### PR TITLE
Add symbol publishing exclusion list.

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
See: https://github.com/dotnet/arcade/pull/3681

/cc @dotnet/coreclr-infra @JohnTortugo @mikem8361

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
@JohnTortugo I would be grateful if you can use the file I am inserting as a test case for your changes just to ensure this will also work. Thanks.

**Comment by AaronRobinsonMSFT** [comment]
Confirmed this will not be needed - https://github.com/dotnet/arcade/pull/3681#discussion_r314399326

**Comment by mikem8361** [comment]
We should still add this file for coreclr (and probably core-setup), but it can be done at a later date.

**Comment by AaronRobinsonMSFT** [comment]
@mikem8361 I am fine keeping it. Just figured defaults are always nice to accept. Will commit so we have the file.

**Pull request merged**
