### PR TITLE
Arm64 define FEATURE_DATATARGET4

### PR DESCRIPTION
**Pull request by sdmaclea**
FEATURE_DATATARGET4 enables the portable out of
process stack unwind

### CODE REVIEW

**Comment by hoyosjs** [comment]
https://github.com/dotnet/coreclr/pull/15060 had the arm context of this.

**Comment by jkotas** [comment]
Is there a good reason why this is not enabled unconditionally for all platforms?

**Comment by sdmaclea** [comment]
The logic that uses it is inverted.  This is the portable implementation, but the code that uses this #if doesn't use the optimized version unless this is not defined.  We only have an optimized version for amd64 at the moment.

Since this is really intended to be cherry-picked to 3.0, I made the minimal change.

For 5.0 we can rework this logic so that it is correct by default.

Also we will enable the optimized version for arm64

**Comment by sdmaclea** [comment]
@jhoyos Has confirmed this allows the debugger to walk the stack frames of a live process.
@mikem8361 Has noted that this will not work for a coredump, as there is no live process,  This is mentioned in #15062,

I am going to merge this as it will allow the debugger team to run tests.

I'll look at enabling PAL_VirtualUnwindOutOfProc for arm64.  As Mike say the arm64 unwind info is similar to amd64.

**Pull request merged**
