### PR TITLE
ARM/Linux: Add codename xenial

### PR DESCRIPTION
**Pull request by seanshpark**
Add Ubuntu 16.04 code name Xenial to cross rootfs option

### CODE REVIEW

**Comment by seanshpark** [comment]
@dotnet-bot test please

**Comment by seanshpark** [comment]
@dotnet-bot test Linux ARM Emulator Cross Build please

**Comment by seanshpark** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by seanshpark** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build please

**Comment by seanshpark** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build and Test please
@dotnet-bot test Linux ARM Emulator Cross Release Build and Test please

**Comment by seanshpark** [comment]
@janvorli @mikem8361 PTAL
ARM Emulator builds fails suddenly for all PRs, can you please take a look?

**Comment by janvorli** [comment]
The change LGTM. 
Regarding the ARM test failures, they are due to System.Runtime.InteropServices.Marshal.PtrToStringAnsi being passed a string with location below 64kB and it seems that the code in StringObject::StringInitCharHelper should not consider it a problem when FEATURE_PAL is defined.

**Comment by janvorli** [comment]
@seanshpark I'll fix the issue causing the CI failures in a minute.

**Comment by seanshpark** [comment]
@janvorli , Thank you :)

**Comment by janvorli** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by janvorli** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build please

**Pull request merged**
