### PR TITLE
Fix #15035

### LINKED ISSUE #15035: [RyuJIT][arm32][arm64] Assertion failed '(code & 0xFF00) == 0xC000'
Failures with:
```
set COMPlus_EnableAVX=0
set COMPlus_EnableSSE3_4=0
```

Both x86 and x64:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_jitsse2only_prtest/5/consoleText
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_arm_altjit_checked_windows_nt_jitsse2only_prtest/8/consoleText

(these are altjit jobs, but the failure is with the x86 and x64 "fallback" compilers)

Example:
```
Assert failure(PID 16072 [0x00003ec8], Thread: 19948 [0x4dec]): Assertion failed '(code & 0xFF00) == 0xC000' in 'System.Numerics.Vector3:op_Multiply(struct,float):struct' (IL size 13)

    File: e:\gh\coreclr2\src\jit\emitxarch.cpp Line: 10791
    Image: E:\gh\coreclr2\bin\tests\Windows_NT.x64.checked\Tests\Core_Root\CoreRun.exe
```

Test failures:
```
JIT\Performance\CodeQuality\SIMD\RayTracer\RayTracer\RayTracer.cmd
JIT\SIMD\Vector3_r\Vector3_r.cmd
JIT\SIMD\VectorArray_r\VectorArray_r.cmd
JIT\SIMD\VectorArray_ro\VectorArray_ro.cmd
JIT\SIMD\VectorDiv_r\VectorDiv_r.cmd
JIT\SIMD\VectorDiv_ro\VectorDiv_ro.cmd
JIT\SIMD\VectorDot_r\VectorDot_r.cmd
JIT\SIMD\VectorInit_r\VectorInit_r.cmd
JIT\SIMD\VectorInit_ro\VectorInit_ro.cmd
JIT\SIMD\VectorMax_r\VectorMax_r.cmd
JIT\SIMD\VectorMax_ro\VectorMax_ro.cmd
JIT\SIMD\VectorMin_r\VectorMin_r.cmd
JIT\SIMD\VectorMin_ro\VectorMin_ro.cmd
JIT\SIMD\VectorMul_r\VectorMul_r.cmd
JIT\SIMD\VectorMul_ro\VectorMul_ro.cmd
JIT\SIMD\VectorReturn_r\VectorReturn_r.cmd
JIT\SIMD\VectorReturn_ro\VectorReturn_ro.cmd
JIT\SIMD\VectorUnused_r\VectorUnused_r.cmd
```

### PR DESCRIPTION
**Pull request by fiigii**
@BruceForstall

### CODE REVIEW

**Comment by fiigii** [comment]
@dotnet-bot test Ubuntu armlb Cross Debug Innerloop Build

**Comment by BruceForstall** [comment]
cc @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
Adding link to bug: #15035

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT jitsse2only
@dotnet-bot test Windows_NT x64_arm64_altjit Checked jitsse2only
@dotnet-bot test Windows_NT x86 Checked jitsse2only
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitsse2only

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitsse2only

**Comment by fiigii** [comment]
@BruceForstall Question. How can we set environment variables (i.e., COMPlus_EnbaleAVX) in the CI tests?

**Comment by BruceForstall** [comment]
> @BruceForstall Question. How can we set environment variables (i.e., COMPlus_EnbaleAVX) in the CI tests?

There needs to be a job defined (in the netci.groovy file) for the specific environment variable(s) you want set. The jobs use the "TestEnv" option to RunTests.cmd (on Windows; equivalent on non-Windows) to pass the path to a generated batch file with the environment variables desired.

**Comment by fiigii** [comment]
Got it. I saw that `netci.groovy` sets these variables correctly. Thank you for explaining.

**Comment by fiigii** [comment]
All tests passed.

**Pull request merged**
