### PR TITLE
Refactor fgComputeFPlvls

### PR DESCRIPTION
**Pull request by pgavlin**
- Rename fg{FPstLvlRedo,ComputeFPlvls} to gt{FPstLvlRedo,ComputeFPlvls}. This variable
  and function are more appropriately grouped with the GenTree-related functionality, as they
  are peers of gtSetEvalOrder.
- Move gtComputeFPlvls next to gtSetEvalOrder.

### CODE REVIEW

**Comment by pgavlin** [comment]
@dotnet/jit-contrib PTAL. I left this change as two commits to make it easier to review the rename and the code movement by keeping them isolated from one another; I can squash before merging if that's preferable.

**Comment by pgavlin** [comment]
Anybody?

**Comment by pgavlin** [comment]
@CarolEidt @russellhadley?

**Comment by CarolEidt** [comment]
LGTM. I didn't scrutinize to verify that the code was moved verbatim, but it appears to be. I might suggest that you make the pasted code conform the coding conventions, but that seems undue burden for a pure cut-and-past.

**Comment by briansull** [comment]
LGTM

**Pull request merged**
