### PR TITLE
Fix build.cmd return codes

### PR DESCRIPTION
**Pull request by mmitche**
Build script was accidentally wiping the return code of the first msbuild step, causing us to continue building even in failure.  Fix this and do a little extra cleanup.

### CODE REVIEW

**Comment by gkhanna79** [comment]
Why are we not in the project dir folder when we exit the build script? We would do that for the success case.

Can you please ensure we do that now as well and while you are at it, do the same for failure case too?

**Comment by mmitche** [comment]
We are still in the project dir folder after the build is finished.

**Comment by mmitche** [comment]
Slight tweak to push/popd dir around the gen made.

**Comment by AlexGhiondea** [comment]
@mmitche Do we need 2 separate commits for this or can we squash them? LGTM otherwise.

**Comment by mmitche** [comment]
@AlexGhiondea okay done

**Pull request merged**
