### PR TITLE
Fix the remaining unused variable/label warnings

### PR DESCRIPTION
**Pull request by adityamandaleeka**
Fix the remaining warnings about unused labels and variables.

### CODE REVIEW

**Comment by janvorli** [comment]
LGTM, just consider my suggestion using the INDEBUG macro, please. Feel free to leave it as you have it if you prefer it the other way though.

**Comment by adityamandaleeka** [comment]
>`INDEBUG(DWORD size = )FILEGetDirectoryFromFullPathA(g_szCoreCLRPath, MAX_LONGPATH, coreCLRDirectoryPath);`

I am a bit concerned that someone might see a line that starts with `INDEBUG(` and assume they can ignore that whole line because it's debug only. The void cast is a pretty common pattern to get around the unused variable problem.

I don't have a very strong opinion about this though, so if you don't think readability is a concern, I'd be happy to change it. I see both styles in our codebase already :)

**Comment by janvorli** [comment]
It is probably just a matter of personal preference. I find the INDEBUG cleaner. To make your concern go away, you might just place the INDEBUG on a separate line from the function call.

**Comment by sergiy-k** [comment]
My personal is preference is same as @janvorli’s. :) I like how the code looks with the INDEBUG macro better.
Do you think it would help readability if we changed @janvorli’s sample to have two lines? Something like this:

```
INDEBUG(DWORD size = )
FILEGetDirectoryFromFullPathA(g_szCoreCLRPath, MAX_LONGPATH, coreCLRDirectoryPath);
```

**Comment by adityamandaleeka** [comment]
Sure, sounds good.

**Comment by sergiy-k** [comment]
LGTM

**Comment by adityamandaleeka** [comment]
Looks like there was some intermittent failure in the CI build. @dotnet-bot retest this please.

**Pull request merged**
