### PR TITLE
Set SetIsGeneratingNgenPDB flag early

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
@echesakovMSFT Could you please check that it is fixing the problem on ARM?

**Comment by echesakovMSFT** [comment]
@jkotas Sure, I will let you know once the build is done. Thanks

**Comment by echesakovMSFT** [comment]
@jkotas Still hitting the same issue. I can look more into this on Monday to see why this didn't work.

**Comment by jkotas** [comment]
@echesakovMSFT I have taken a look and pushed updated fix. It should work now (it worked for me on x64 with R2R forced for CoreLib).

**Comment by echesakovMSFT** [comment]
@jkotas Confirm that this works for Windows/ARM as well

**Comment by jkotas** [comment]
Thanks for confirming it

**Pull request merged**
