### PR TITLE
[WIP] ThreadPool fix 2 thread requests per dequeue

### PR DESCRIPTION
**Pull request by sdmaclea**
Only request an additional thread on dequeue if
enqueue request was supressed

### CODE REVIEW

**Comment by sdmaclea** [comment]
@kouvel @stephentoub @benaadams Optimization notes...

This patch is significantly less effective than either #13386 or #13274.

This patch only limits thread requests form the Dispatch() loop.  So it suppresses thread requests which would have been made in the dispatch loop.  This will effectively limit the thread request to a maximum of one thread per work item.

In contrast, #13386 does better.  It limits thread request to the number of items currently in the queue.  So this also effectively limits the threadRequests to one thread per work item.  However it is better than that.  During `Enqueue()` if another thread has processed a work item which has an outstanding thread request, another thread will not be requested.  That is because threads requests are limited to the number of unprocessed work items.  So #13386 does a substantially better job of limiting thread requests.

#13274 also does better.  It limits thread request in `Enqueue()` based on a simple hard limit.  This allows threads in Dispatch() to process more work items.  

#13386 is more robust than #13274 and seems preferable.  However as noted elsewhere the approaches could be combined for improved perf gain.

**Comment by kouvel** [comment]
There's one issue in MarkThreadRequestSatisfied, the gap of time between decrementing and incrementing the thread request count when it's at max. During that time, other threads can decrement the count further and cause problems.

For instance:
- Say there are 8 procs and a large number of work items are queued
- 8 threads are requested and wake up (requestCount == 8)
- Thread 1 decrements the thread request count (requestCount == 7)
- Thread 2 decrements the thread request count (requestCount == 6)
- Thread 1 increments the thread request count and actually requests a thread with RequestThread (requestCount == 7)
- Thread 2 sees requestCount == 7 before its decrement, so it does not request a thread
- Threads 3-8 decrement the request count and all see request count < 8 before their decrement, so they also don't request a thread (requestCount == 1)
- Thread 1 exits Dispatch due to the quantum expiring
- Thread 1 enters Dispatch again, decrements the request count (requestCount == 0)
- At this point, any thread that exits Dispatch due to the quantum expiring will not process any more work items until new work is queued

If MarkThreadRequestSatisfied avoids decrementing and incrementing the request count when it's at max and a work item was dequeued, and instead keeps the count at max and just calls RequestThread, then this wouldn't be an issue and seems a reasonable change.

**Comment by kouvel** [comment]
> In contrast, #13386 does better.

It would be interesting to see what the gain of this change and #13386 are on top of #13010, because there is likely some overlap between all three of these, and #13386 I believe would overlap more with #13010.

**Comment by sdmaclea** [comment]
> ~~the gain of this change and #13386 are on top of #13010~~

I tried #13010 on top of #13431 w/ Cache line padding.  This should be similar #13386.  The result was very significant performance regression.  

I suspect #13010 will no longer give an improvement.  The baseline plaintext scores on arm64 have improved 2.5x since I was testing #13010.  I spent a lot of time making sure extra threads did not reduce performance.

**Comment by sdmaclea** [comment]
> If MarkThreadRequestSatisfied avoids decrementing and incrementing the request count when it's at max and a work item was dequeued, and instead keeps the count at max and just calls RequestThread, then this wouldn't be an issue and seems a reasonable change.

I pushed a patch to do what you suggested.

The results are very modal.  Run to run varies a lot.  I have seen perf improvement and degradation with this patch as is.  I think this is again false sharing, but it doesn't seem to be on `numOutstandingThreadRequests` like #13431 

In the best case this is give 25% improvement.  Worst case 40% degradation.  Result is consistent for a given run.  Restarting corerun will result in different numbers.  Restart wrk will not.

**Comment by kouvel** [comment]
I don't immediately see any other reason for the fixed behavior to be worse other than if it was actually running into the issue that was fixed where it may have been behaving well for the wrong reasons. At the very least, I don't see any reason for the fixed behavior to be worse than the baseline.

**Comment by kouvel** [comment]
> I tried #13010 on top of #13431 w/ Cache line padding. This should be similar #13386. The result was very significant performance regression.

Maybe reducing threads below proc count is actually hurting, and the main issue may be that it releases too many threads unnecessarily. I don't understand though why it would be so significant.

**Comment by kouvel** [comment]
> I suspect #13010 will no longer give an improvement.

Does it still give an improvement on its own without #13431?

**Comment by kouvel** [comment]
Of the several PRs we have on this issue, I feel it is still not clear why any particular change is giving the perf improvement it is and I feel we don't have a good understanding of what actually needs fixing.

Maybe we can go about this a step at a time. This change for instance, is perhaps the simplest way to fix the problem of multiple thread requests per enqueued item. If we're agreed that theoretically, we don't see any reason why this should be worse than before, and we don't see any consistent results indicating that it would be worse, I think that is satisfactory enough to solve that problem this way to begin with, and go from there.

From what I see, the main advantage of #13386 over this change is that it limits the number of requests based on the number of running threads (in particular, it almost ensures that there is only one thread request when at least proc count threads are running). That could be a win over this change, but at least theoretically, I don't see it being a significant win over this change. Given that I'm not confident yet what is the problem that needs fixing and the additional complexity involved, I'm inclined to go with this simple change for now until we have more data.

Thoughts?

If I take a step back and look at this issue from afar several things seem just wrong to me:
1. Dispatch should never need to cause a new thread to look for work. That should be the business the number of work items and the thread pool's choice of number of threads to schedule based on that information.
2. The thread pool should not care about how many thread requests there are because "number of thread requests" is a poor estimation for "number of work items left in the queue"
3. We don't want to have to notify the thread pool of every work item that is enqueued, but only because it currently costs a p/invoke to do so

I generally believe that this can be designed in a way that avoids a lot of these problems. Unfortunately, that's hard to do without justification.

**Comment by sdmaclea** [comment]
@kouvel 
> I feel we don't have a good understanding of what actually needs fixing

This is partly my fault because I am not sharing all the information I have gathered.

Fundamentally CoreCLR is ThreadPool is inefficient on arm64 44/48 cores.  This is most easily demonstrated using the plaintext benchmark and toggling the `--KestrelThreadPollDispatching` flag.  I am testing plaintext in two modes : pipelined and non-pipelined.  `wrk` is running on target because the network capacity is saturated by the benchmark.  Score measured in `Transfers/sec` are **2x** when 
`--KestrelThreadPollDispatching=false` (without any of these patches).  This is in both the pipelined and the non-pipelined case.  

Plaintext is a pathological ThreadPool test case.  Does it matter?  Is it important?  It does exaggerate the magnitude of the problems of ThreadPool.  However, intuitively it seems to be representative of a very real world web workloads workloads.  It has also helped identify inefficiencies in the ThreadPool implementation.

If I look at Thread Requests, I can characterize them as `useful` or `useless` based on whether the workItem queue was empty when the threadRequest was satisfied.  So in the baseline the stats show ~90% of the thread requests were `useless`.  So we are request 10x the threads we actually need.

Why?
1.  We request up to two threads for every work item enqueued
2.  Work items are short
3.  Each threads process more than one work item.
4.  Thread requests have a long latency
5.  When the queue is empty all threads are returned to the native thread pool.  This magnifies the cost of 3
6.  When we request more threads than hillclimbing has allocated the thread request are very slowly satisfied.

**Comment by sdmaclea** [comment]
@kouvel
> I feel we don't have a good understanding of what actually needs fixing

The other part of the problem:
+ The problems are non-trivial.  Some have no easy answer.  Some have no answer
+ The solutions are compromises.  They are reducing a general problems, but not fixing it completely.
+ The set of PR is incomplete.  A managed threadpool might solve many of the problems, but also may be insufficient

> I feel it is still not clear why any particular change is giving the perf improvement it is

#13010 seems to have been obsoleted by #13007 and possibly other patches.

#13408 only requests a single thread from Dispatch() if and only if the thread did not find the queue empty and the enqueue thread request was clipped.
1. This (mostly) eliminates the possibility of two requests per item.

#13431 is effectively limiting the thread requests to the number of items in the queue and num proc.  
1. See above ~~mostly~~
2. This also has the advantage of partially recycling useless thread requests.  So if there are more outstanding thread requests than items in the queue, another thread request will not be made during enqueue.  This occurs when workers are consuming items in the queue before thread requests are satisfied.  This is the most simplistic implementation of @benaadams idea.

#13386 is effectively limiting the thread requests to the number of items in the queue and (running < numProc ? numproc. - running threads : 1) 
1. See above ~~mostly~~
2. See above ~~most simplistic implementation~~
3.  This also limits requests which will typically not be satisfied until queue is empty due to hillclimbing.

#13274 limits maxThread requests
4.  This is based on the observation that the ThreadPool design is based toward long running work items.   
 IT is assuming that all work items will run faster with more threads.

**Comment by sdmaclea** [comment]
@kouvel 
> Thoughts?

I believe #13431 is currently the best candidate patch.  I think it can/should be amended:
+ Only call EnsureThreadRequested() once in Dispatch().  (idea from #13408) 
+ Track running threads and limit based on running threads.  (idea from #13386)

I also believe there should be another PR focused on the managed/unmanaged p/invoke issues.  Add spin/sleep/wait logic to the managed ThreadPool to eliminate the need for UnfairSemaphore.  This would be an alternative to the pure managed CoreRT ThreadPool.  I think it can be simple enough to be review-able.  I have been thinking about drafting this for a few days now.

It may e wise to delay merging the #13431 derivative until the new UnfairSemaphore PR is drafted/tested.

**Comment by sdmaclea** [comment]
> If I take a step back and look at this issue from afar several things seem just wrong to me:

> Dispatch should never need to cause a new thread to look for work. That should be the business the number of work items and the thread pool's choice of number of threads to schedule based on that information.

This is a side effect of the long latency of starting threads.  I think limiting `numOutstandingThreadRequests` to `Environment.ProcessorCount` was actually trying to solve the same problem.  It was effectively the same approach as #13274, but easier to justify because it was tied to a physical parameter.

Right now it is important for the ThreadRequest generator to know that thread requests have been satisfied.  I think that might always be the case, but I'd be pleased if I was wrong.

> The thread pool should not care about how many thread requests there are because "number of thread requests" is a poor estimation for "number of work items left in the queue"

But "number of work items left in the queue" is correlated to "thread requests" required.

> We don't want to have to notify the thread pool of every work item that is enqueued, but only because it currently costs a p/invoke to do so

Hence the need for the addtional PR suggested above.

> I generally believe that this can be designed in a way that avoids a lot of these problems. Unfortunately, that's hard to do without justification.

Designing without justification is easy.  😃 

I have sufficient justification to work on this for a while.   ThreadPool is not as scale-able as it needs to be for high CPU count machines.  I see 2x improvement when disabling the ThreadPool.  Either would be sufficient for my management.

The design needs to be rational enough that the benefits can be explained and they are reasonably optimal.  It should also be apparent that there is no reason to believe there will be a regression in other use cases.

Some of this work is/maybe redundant with the CoreRT managed ThreadPool work.  That is unfortunate, but it also situation normal.

**Comment by sdmaclea** [comment]
@kouvel I have merged the ideas from this patch with #13431.  I am closing this patch in favor of #13431

**Comment by kouvel** [comment]
> This is a side effect of the long latency of starting threads. I think limiting numOutstandingThreadRequests to Environment.ProcessorCount was actually trying to solve the same problem.

The thread pool could choose to schedule any number of threads it wants based on the number of work items. I don't follow what this has to do with the latency of starting threads. The number of threads that are started/released could be exactly the same regardless of the number of thread requests.

> But "number of work items left in the queue" is correlated to "thread requests" required.

Ya I just meant why use an estimate when the real value can be available.

I agree with your last comments.

**Comment by kouvel** [comment]
> Add spin/sleep/wait logic to the managed ThreadPool to eliminate the need for UnfairSemaphore.

I think the best way to solve this is release threads that most recently started waiting. I'm planning on working on this soon. Spinning has been problematic for a while here and it may not even be necessary or worth it since typically either work would continuously be available or work would deplete to a level for some time before new work comes in. At the very least, I think any spinning done here should be very minimal because bursty work is very common.

> I also believe there should be another PR focused on the managed/unmanaged p/invoke issues.

What are you planning to do for this? I'm a bit concerned about going down this path when the best solution would be to port.

**Comment by sdmaclea** [comment]
@kouvel 

>>> Dispatch should never need to cause a new thread to look for work

>> This is a side effect of the long latency of starting threads. I think limiting numOutstandingThreadRequests to Environment.ProcessorCount was actually trying to solve the same problem.

> The thread pool could choose to schedule any number of threads it wants based on the number of work items. I don't follow what this has to do with the latency of starting threads. The number of threads that are started/released could be exactly the same regardless of the number of thread requests.

Limiting numOutstandingThreadRequests to Environment.ProcessorCount prevents infinite thread requests pending (because hill climbing will defer satisfying them).  However running threads do not want to be limited to Environment.ProcessorCount. 
So the limit must be transient.  As designed, another request must be made whenever request is satisfied.  Creating requests here in Disparch() is in part due to lack of a managed gating thread.  This is a cheap functional equivalent.






Ideally
+ Thread request cost is low
+ Thread request latency is low
+ Work Item cost much larger than thread reuest cost
WIth hillclimbing controlling native threads, the numOutstandingThreadRequests limit seems out of place.  With the limit in this design, Dispatch() must request more threads.  

An optimization added a loop in Dispatch() to process more than one item per request.  This

**Comment by sdmaclea** [comment]
@kouvel 

> What are you planning to do for this?

I was experimenting with replacing `UnfairSemaphore` with `CLRSemaphore` today.  There are weird side effects which do not make sense.  I was trying to move the sleep logic into managed space to save the p.invokes.  So far I was only able to create perf regressions 😞 .

I still don't understand why it is so bad.

Planning is difficult, because a lot of the work is experimental.  Ultimately, I'd like to reduce TP overhead

If you want to coordinate our work, we should move discussion to an issue....

> I'm a bit concerned about going down this path when the best solution would be to port.

Agreed, but if the port will not make 2.1, and may not fix everything, it is hard to wait.  After the other patch, there is a 40% overhead as I measure it when running plaintext with TP vs w/o.  For server workloads, I am not convinced there is another opportunity as big.

I was hoping to simplify the managed/native ThreadPool to improve perf.  I can spend a few weeks on this yet.  Of course I'd rather do the port.

**Comment by kouvel** [comment]
> Limiting numOutstandingThreadRequests to Environment.ProcessorCount prevents infinite thread requests pending (because hill climbing will defer satisfying them). However running threads do not want to be limited to Environment.ProcessorCount.
So the limit must be transient. As designed, another request must be made whenever request is satisfied. Creating requests here in Disparch() is in part due to lack of a managed gating thread. This is a cheap functional equivalent.

I was contemplating removing the concept of "thread request" altogether (except when using the windows thread pool, we'll probably still need it for that one). The thread adjustment heuristics are limited to thread requests until more are requested by Dispatch, which I feel is an artificial limitation.

> I was experimenting with replacing UnfairSemaphore with CLRSemaphore today

CLRSeamphore would make the queue fair and would not allow threads to become cold.

> I was trying to move the sleep logic into managed space to save the p.invokes.

I guess it depends on whether the spinning would help. If you're seeing a lot of overhead here, it could be that spinning is just wasting time, or spinning is actually helping. If the latter, it may help to do a little bit of spinning on the managed side, but this would be hard to do properly before the port because delaying return from Dispatch would also delay processing the unmanaged work queue (timer callbacks and other things). The unmanaged work queue would need to be removed. What happens if you just disable the spinning? I'll be trying this as well once I have a fix for unfair semaphore.

**Comment by sdmaclea** [comment]
@kouvel 

> What happens if you just disable the spinning?

Here is what I see on arm64 with my working tip.  Performance is optimal around the current default.

COMPlus_ThreadPool_UnfairSemaphoreSpinLimit | % Relative to baseline (50)
------------------------------------------------------ | -------------------------------
0 | 20
1 | 60
2 | 70
4 | 80
8 | 85
16 | 90
32 | 90
64 | 100
128 | 90
256 | 90
512 | 80
1K | 85
2K | 85
4K | 85
8K | 85
16K | 80
32K | 80
64K | 85
128K | 80

**Comment by sdmaclea** [comment]
@kouvel 

> I was contemplating removing the concept of "thread request" altogether

Sounds like a useful experiment.

It is sort of similar to my idea of moving all active threads into managed code.  Eliminating the need for UnfairSemaphore in native space except for native clients of the Native ThreadPool.

**Comment by kouvel** [comment]
> Here is what I see on arm64 with my working tip. Performance is optimal around the current default.

Just want to clarify the number in the second column, is that throughput? If it means that the throughput is 20% of the default when spinning is disabled then that is a pretty strong indication that spinning a bit is beneficial.

**Comment by sdmaclea** [comment]
@kouvel 

> is that % of baseline throughput?

Yes, The throughput with spinning disabled is 20% of the throughput with spinning enabled and set to 50.

**Pull request closed without merging**
