### PR TITLE
Avoid __declspec(uuid(x)) for better portability

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
@franksinankaya Could you please give this a try with GCC?

**Comment by am11** [comment]
I added a [`.travis.yml`](https://github.com/am11/coreclr/commit/a77e187f5b32bdaa4f4177ef741286d79cf27422) in your branch, @jkotas. Here are the gcc build logs: https://travis-ci.org/am11/coreclr/builds/603589305#L789. It is complaining about `__declspec(uuid(x))`.

**Comment by jkotas** [comment]
> It is complaining about __declspec(uuid(x)).

The last commit should fix this.

**Comment by am11** [comment]
Anonymous struct issue fixed by https://github.com/dotnet/coreclr/pull/27485.

**Comment by franksinankaya** [comment]
@am11 

Thanks for the fix. Last issue remaining to declare victory:

coreclr/src/jit/hwintrinsic.cpp:24:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘unsigned int’ inside { } [-Wnarrowing]
 };
 ^
coreclr/src/jit/hwintrinsic.cpp:24:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘unsigned int’ inside { } [-Wnarrowing]
coreclr/src/jit/hwintrinsic.cpp:24:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘unsigned int’ inside { } [-Wnarrowing]
I

There is a -1 somewhere in the intrinsic table.

**Comment by am11** [comment]
@franksinankaya, I looked into it and it is a weird case. We are picking up ARM64 branch on XARCH: https://github.com/dotnet/coreclr/blob/822cdffb88b6acbeae7d3ee1fb3fe28d90b2ba92/src/jit/hwintrinsic.cpp#L18
 The error is coming from expansion of this macro: https://github.com/dotnet/coreclr/blob/822cdffb88b6acbeae7d3ee1fb3fe28d90b2ba92/src/jit/hwintrinsiclistarm64.h#L63.

On the other hand, this is the only place where `size` is negative. Is it correct? If so, we can use `static_cast<unsigned>(size)` in `hwintrinsic.cpp` and figure out why are we hitting ARM64 branch. I am testing it at the moment.

**Comment by jkotas** [comment]
> ARM64 branch on XARCH

X64 builds x64-hosted arm64-targeting JIT flavor.

**Pull request merged**
