### PR TITLE
Fixing the return type of the ArmBase.ReverseElementBits methods in the PlatformNotSupported file

### PR DESCRIPTION
**Pull request by tannergooding**
This was a bug in https://github.com/dotnet/coreclr/pull/27582

### CODE REVIEW

**Comment by tannergooding** [comment]
CC. @TamarChristinaArm, @echesakovMSFT

**Comment by Mistuke** [comment]
Ugh, sorry about that. Is the only way to check this file to compile for x86?

**Comment by TamarChristinaArm** [comment]
Ugh, Sorry about that, is the only way to check this file to compile for x86?

**Comment by tannergooding** [comment]
> Ugh, Sorry about that, is the only way to check this file to compile for x86?

Unfortunately, I don't think that would have necessarily caught it either. The ref assembly generation only runs against the local copy of corelib; so you need to ultimately test both the ARM and the x86 copies to ensure they are consistent with eachother.

**Pull request merged**
