### PR TITLE
[x86/Linux] Corretly pop args after unmanaged function call

### LINKED ISSUE #11006: [x86/Linux] Interop.PrimitiveMarshalling.UIntPtr.PInvokeUIntPtrTest failure (in Checked build)
This happens only for Checked build:
```
FAILED   - [ 660 :    0 sec ] Interop/PrimitiveMarshalling/UIntPtr/PInvokeUIntPtrTest/PInvokeUIntPtrTest.sh
               BEGIN EXECUTION
               /root/dotnet-test/coreclr_unittest_20170417_083705_x86_x86-emu/coreclr-unittest-170416-233746/Core_Root/corerun PInvokeUIntPtrTest.exe
               ./PInvokeUIntPtrTest.sh: line 200: 18098 Segmentation fault      (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
               Expected: 100
               Actual: 139
               END EXECUTION - FAILED
```

### PR DESCRIPTION
**Pull request by parjong**
In CodeGen::genCallInstruction, call->callSig may be incorrect for direct unmanaged calls, which results in #11006. 

This commit suppresses calling convention inference for unmanaged calls to fix #11006.

This commit also resolves signature mismatch in HFA tests. hfa_interop.cs declares each native function explicitly as stdcall. Unfortunately, hfa_native.h (and hfa_native.cpp) does not specify calling convention, and thus the corresponding functions use cdecl.

### CODE REVIEW

**Comment by danmosemsft** [comment]
retest

**Comment by parjong** [comment]
@janvorli @BruceForstall Please take a look.

**Comment by janvorli** [comment]
@parjong I'll let @BruceForstall review this. I don't understand JIT well enough to understand why "CodeGen::genCallInstruction, call->callSig may be incorrect for direct unmanaged calls".

**Comment by parjong** [comment]
@janvorli I notice that this PR is solely about JIT only after your comment. Sorry for disturbing you.

**Comment by BruceForstall** [comment]
cc @dotnet/jit-contrib

**Pull request merged**
