### PR TITLE
BinaryReader perf improvements on little-endian machines

### PR DESCRIPTION
**Pull request by jamesqo**
Created from #1618.

Changes:

- use pointers instead of manual bitshifting if the target machine is already little-endian

Can someone verify the changes to `ReadDecimal` are correct? I got somewhat confused because the old implementation (`decimal.ToDecimal`) seems to interpret it differently than the actual layout of the decimal (if you casted the pointer to a `decimal*` and dereferenced that). Did I overlook something in the changes?

### CODE REVIEW

**Comment by mikedn** [comment]
Some quick perf numbers for ReadInt32 (26214400 calls, 100 megabyte file already cached in memory, AV turned off, Core i5 Haswell 3.1 GHz).

Old implementation: 557ms
New implementation: 529ms

I suppose it's a reasonable improvement but overall the performance of BinaryReader is pretty low anyway because every ReadX call has to go through FillBuffer and Stream.Read.

**Comment by jkotas** [comment]
@mikedn Thanks for a quick read on the perf improvement. I have expected it to be more - I am not sure whether a bunch of unsafe is worth it for 5% improvement in a micro-benchmark. 

@jamesqo Could you please collect more comprehensive numbers about the perf improvements?

**Comment by stephentoub** [comment]
@jamesqo, are you still working on this and responding to @jkotas' request for more comprehensive perf numbers?

**Comment by jamesqo** [comment]
@stephentoub I wasn't sure whether this PR still applies, since it looks like `IsLittleEndian` is [determined dynamically](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/BitConverter.cs#L17) in CoreFX. Will the changes to `BitConverter` in that repo eventually be brought over here?

**Comment by jamesqo** [comment]
Never mind, looks like from #1079 `IsLittleEndian` will become a constant when it is jitted (haven't tested this for myself, though). Looks like I can remove all of those `#if` conditionals and continue with this PR.

**Comment by jamesqo** [comment]
Well, this was from a pretty long time ago... I think I'm going to close this since `BinaryReader` / `BinaryWriter` are fundamentally slow, I don't know if it's worth optimizing. Additionally maybe the JIT could eventually do this as an optimization by itself.

**Pull request closed without merging**
