### PR TITLE
[release/2.1] Enable Tizen CI

### PR DESCRIPTION
**Pull request by gbalykov**
cc @alpencolt

### CODE REVIEW

**Comment by jkotas** [comment]
Could you please re-enable it in the master branch first? Once it gets some millage in the master branch, we can consider porting it to release branch.

**Comment by gbalykov** [comment]
@jkotas Tizen testing is enabled for coreclr master branch already

**Comment by jkotas** [comment]
> @jkotas Tizen testing is enabled for coreclr master branch already

You are right - thanks. I thought they are not enabled on https://github.com/dotnet/corefx/issues/28901#issuecomment-410882335 . cc @BruceForstall

**Comment by gbalykov** [comment]
@jkotas yes, currently only coreclr testing works. Tizen 5.0 build still do not work for corefx and core-setup, and we wait for #19058 to get to sdk to fix this

**Comment by gbalykov** [comment]
@dotnet-bot test ci please

**Comment by gbalykov** [comment]
@dotnet-bot help

**Comment by gbalykov** [comment]
@dotnet-bot test ci please

**Comment by gbalykov** [comment]
@jkotas, is there a way to test Tizen CI job on this PR? `test ci` doesn't seem to regenerate jobs

**Comment by jkotas** [comment]
> test ci doesn't seem to regenerate jobs

@mmitche Do you know?

**Comment by mmitche** [comment]
It only tests compilation of jobs.  It doesn't actually run them.  I can manually enable the generated job and run it.

**Comment by gbalykov** [comment]
@jkotas @mmitche Now the regeneration job has started. I think some time had to pass after request

**Comment by gbalykov** [comment]
@dotnet-bot test Tizen armel Release Build

**Comment by mmitche** [comment]
@dotnet bot test Tizen armel Cross Checked Innerloop Build and Test

**Comment by gbalykov** [comment]
@jkotas could this be merged?

**Comment by jkotas** [comment]
Thanks all

**Pull request merged**
