### PR TITLE
Set FEATURE_READYTORUN_COMPILER for legacyjit and compatjit

### PR DESCRIPTION
**Pull request by BruceForstall**

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet-bot help

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT x86 compatjit Checked
@dotnet-bot test Windows_NT x86 legacy_backend Checked

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT x86 compatjit Checked
@dotnet-bot test Windows_NT x86 legacy_backend Checked

**Comment by BruceForstall** [comment]
Ubuntu x64 failed with:
```
03:18:40 GDB was not found. Unable to print core file.
03:18:40 Copying core file core to /tmp/coredumps_coreclr
03:18:41 Downloading latest version of dumpling script.
03:18:41 --2016-11-26 03:18:41--  https://raw.githubusercontent.com/Microsoft/dotnet-reliability/master/src/triage.python/dumpling.py
03:18:41 Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.40.133
03:18:41 Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.40.133|:443... connected.
03:18:41 HTTP request sent, awaiting response... 200 OK
03:18:41 Length: 12411 (12K) [text/plain]
03:18:41 Saving to: ‘dumpling.py’
03:18:41 
03:18:41      0K .......... ..                                         100% 18.3M=0.001s
03:18:41 
03:18:41 2016-11-26 03:18:41 (18.3 MB/s) - ‘dumpling.py’ saved [12411/12411]
03:18:41 
03:18:41 Uploading core to dumpling service.
03:18:41 Uploading CoreCLR binaries with dump.
03:19:35 http://dotnetrp.azurewebsites.net/dumpling/download/2136
03:19:35 FAILED   - GC/Scenarios/DoublinkList/doublinkgen/doublinkgen.sh
03:19:35                BEGIN EXECUTION
03:19:35                /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/jit-dasm.dll --crossgen /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/crossgen.exe --platform /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay --output D:/j/workspace/checked_windo---f6dc6fe4/bin/tests//Windows_NT.x64.Checked/dasm/GC/Scenarios/DoublinkList/doublinkgen doublinkgen.exe
03:19:35                Managed assembly not found: No such file or directory
03:19:35                ./doublinkgen.sh: line 90: [: -ne: unary operator expected
03:19:35                /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun doublinkgen.exe
03:19:35                Test should return with ExitCode 100 ...
03:19:35                ./doublinkgen.sh: line 137: 22104 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" doublinkgen.exe $CLRTestExecutionArguments
03:19:35                Expected: 100
03:19:35                Actual: 134
03:19:35                END EXECUTION - FAILED
```
@swgillespie @mmitche Is this GC test accessing the network during the test run? That seems like a huge robustness problem

Gonna run it again.

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Comment by BruceForstall** [comment]
@RussKeldorph PTAL
cc @dotnet/jit-contrib

**Comment by mmitche** [comment]
@BruceForstall That's not actually the test, just the test harness (and I think only in CI). It's uploading a crash dump, which should appear on the build page.

**Pull request merged**
