### PR TITLE
Complete JIT port to GCC

### PR DESCRIPTION
**Pull request by franksinankaya**
These is the complete GCC port after removing all instances of __declspec(property)

### CODE REVIEW

**Comment by mikedn** [comment]
The `AsXRef()` calls should really be `AsX()` (with the appropriate transformation of the subsequent `.` into `->`). The "Ref" version exists only to support declspec property but it is otherwise unused throughout the JIT (and should be removed together with the declspec).

**Comment by BruceForstall** [comment]
@franksinankaya .NET Core 3.0 is almost out the door, and is no longer in the master branch. So we're ready to take this change.

Do you want to rebase and fix the conflicts? (Or re-apply the changes based on the live master branch)

@dotnet/jit-contrib Any last comments on naming, etc.? (Also previously discussed here: https://github.com/dotnet/coreclr/issues/23386)

**Comment by BruceForstall** [comment]
Just to be clear, as far as I know, we have no goal to add a GCC compilation step as part of our CI system, so presumably the .NET Core GCC compilation will periodically be broken/regressed.

**Comment by franksinankaya** [comment]
Great news! I'll send out patches in pieces.

**Comment by jkotas** [comment]
Superseded by other PRs

**Pull request closed without merging**
