### PR TITLE
Use ArrayPool in Stream.CopyTo{Async}

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @jkotas, @JeremyKuhne

### CODE REVIEW

**Comment by jkotas** [comment]
Can we also delete ArrayPoolCopyToAsync helper now?

**Comment by stephentoub** [comment]
> Can we also delete ArrayPoolCopyToAsync helper now?

Yup, assuming we merge this, once this is consumed into corefx I'll delete that and uses of it.  Streams may still choose to override these if they can do better, but just using ArrayPool won't be a reason to override them.

**Comment by stephentoub** [comment]
Oh, I just realized ArrayPoolCopyToAsync has made its way into coreclr as well.  I'll delete it from coreclr as part of this change then.

**Comment by stephentoub** [comment]
I've removed ArrayPoolCopyToAsync.

**Pull request merged**
