### PR TITLE
Fix `fgOrderBlockOps`.

### PR DESCRIPTION
**Pull request by pgavlin**
This function was incorrect when the target was a `DYN_BLK` with
`gtEvalSizeFirst` set to `true`.

Fixes VSO 468726.

### CODE REVIEW

**Comment by pgavlin** [comment]
@BruceForstall @CarolEidt @dotnet/jit-contrib PTAL

**Comment by CarolEidt** [comment]
> This function was incorrect when the target was a DYN_BLK with gtEvalSizeFirst set to true.

The `gtEvalSizeFirst` was added during the 1st class structs work, to get to zero diffs. However, the value of being able to control the order of evaluation of these rare nodes is probably pretty low. We may want to open an issue to consider removing this.

**Comment by pgavlin** [comment]
> Can you extract a test case?

I haven't been able to yet, but I will keep trying.

> The `gtEvalSizeFirst` was added during the 1st class structs work, to get to zero diffs. However, the value of being able to control the order of evaluation of these rare nodes is probably pretty low. We may want to open an issue to consider removing this.

I concur--I'll file an issue.

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test

**Pull request merged**
