### PR TITLE
Fix build on NetBSD: Support different versions of "struct reg"

### PR DESCRIPTION
**Pull request by krytarowski**
FreeBSD style: `.r_rax`
NetBSD x86_64 style: `.regs[_R_RAX]`

NetBSD i386 style: `._r_eax` will be defined once the amd64 version will be
finished.

### CODE REVIEW

**Comment by krytarowski** [comment]
I've pushed incomplete patch. I will fix it.

**Comment by krytarowski** [comment]
I fixed the typo. Thanks @jasonwilliams200OK for remarking that FreeBSD version had "._r_reg" instead of ".r_reg".

Checking with build bots.

**Comment by krytarowski** [comment]
Should be good now.

**Comment by jasonwilliams200OK** [comment]
:+1:

**Comment by jkotas** [comment]
:+1:

**Pull request merged**
