### PR TITLE
[XUnit] Use ParallelRun==Collections on all platforms.

### LINKED ISSUE #11921: JIT_Generics._Coverage_chaos65204782cs sometime fails with timed out.
For example in this [PR ](https://ci.dot.net/job/dotnet_coreclr/job/master/job/debug_windows_nt_prtest/7262/)both non-optimized and optimized versions failed.

Sometimes this tests take less then a minute. The task is to find which component causes this fluctuations and fix them.

category:correctness
theme:testing
skill-level:beginner
cost:medium

### LINKED ISSUE #22419: [arm64] Frequent test timeouts
We seem to be seeing more frequent test timeouts recently, especially superpmicollect. When run locally on a Windows arm64 machine, this test finishes in about 3.5 minutes, when run alone (not in parallel with anything else). When run in the CI (on a faster machine) under xunit, with "-parallel all", it frequently times out at 15 minutes.

e.g.,
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_tailcallstress_tst/60/consoleFull#-9820345932d31e50d-1517-49fc-92b3-2ca637122019

### PR DESCRIPTION
**Pull request by sandreenko**
There is an old issue about unstable failures of chaos65204782cs and SuperPMI collect (that uses chaos65204782cs) #11921. I made a stress test for it #22474 with ~300 instances of this test and saw that the difference between the slowest and the fastest result during one run on my machine was 13x (~280s against 20s). With `ParallelRun==none` the test takes ~9s, with `ParallelRun=collections` it is the same ~9s.

My local measurements for the master branch (Windows x64, 4 cores, 8 threads) shows these results for pri0 tests:
```
collections: 25m;
all: 64m;
none: 71m.
```

with my stress chaos testing:
```
collections: 38m;
all: 68m;
none: 128m.

```
I was told that `ParallelRun==collections` is ~10-20% slower then `ParallelRun==all` but I got opposite results in my local runs. Lets see what ci shows us.

However, even if `ParallelRun==collections`  is slower we want to use it to get rid of these issues in Jenkins CI (ADO is running each assembly on a separate machine, so it has `ParallelRun==collections` by default).

FIxes #22419, fixes #11921.

### CODE REVIEW

**Comment by sandreenko** [comment]
PTAL @echesakovMSFT @RussKeldorph @dotnet/jit-contrib.

**Comment by jashook** [comment]
This will fix superPMI collections on x86 Windows and should lower test timeout frequency on OSX.

**Comment by echesakovMSFT** [comment]
@jashook There was slowdown on both Linux and Windows x64/x86 (see my comment https://github.com/dotnet/coreclr/pull/20349#issuecomment-429038030)
However I support eliminating flakiness in Jenkins CI at all costs.

**Comment by RussKeldorph** [comment]
I think this fixes #19108 as well.

**Comment by sandreenko** [comment]
Windows_NT arm Cross Checked Innerloop Build and Test  fails in each PR, that is flaky Interop_COM._NETClients.

**Pull request merged**
