### PR TITLE
Fix file-too-long errors caused by adding R2R tests to CI

### PR DESCRIPTION
**Pull request by wtgodbe**

### CODE REVIEW

**Comment by wtgodbe** [comment]
@dotnet-bot test CI please

**Comment by wtgodbe** [comment]
@dotnet-bot test Windows_NT Release r2r please.

**Comment by wtgodbe** [comment]
@gkhanna79 there was a problem with my original R2R PR which caused "file-too-long" errors on certain pri1 tests - I'd run into this problem before, and just forgot to implement the fix for the newly added R2R tests. You can see the failure here - http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_release_windows_nt_pri1r2r_bld/lastBuild/

This should fix that. You can also see above an example of how to trigger the Pri0 r2r tests - the "Windows_NT x64 Release R2R pri0 Build & Test" running right now is the test I triggered.

**Comment by gkhanna79** [comment]
LGTM

**Pull request merged**
