### PR TITLE
Fix Linux/x86 call alignment calculation and insertion

### LINKED ISSUE #10122: [x86/Linux] Nested calls don't handle stack alignment properly
On Linux/x86, the stack must be aligned to 16 bytes when a call is made. We do this by computing the number of alignment bytes required, saving this on the first PUTARG_STK node, and generating an additional, preceding "sub esp, N" instruction before the first stack argument is generated. Then, after the call, we add back the alignment value, if any.

The alignment is calculated in fgArgInfo::ArgsAlignPadding().

The problem is, it assumes the stack is aligned when the arguments for a call start being pushed. This is not true for nested calls, for which we may push some args for an outer call, then push some args for an inner call, make the inner call, push some more args for the outer call, then make the outer call.

Consider the following program:
```
using System;
using System.Runtime.CompilerServices;

public class Program
{

    [MethodImplAttribute(MethodImplOptions.NoInlining)]
    public static float f1(float a)
    {
        Console.WriteLine(a);
        return a + 1.0f;
    }

    [MethodImplAttribute(MethodImplOptions.NoInlining)]
    public static float f2(float a, float b)
    {
        Console.WriteLine(a);
        return a + b + 1.0f;
    }

    public static int Main(string[] args)
    {
        float b = f2(2.0f, f1(1.0f));
        Console.WriteLine(b);

        return 100;
    }
}
```
which generates this code:
```
movss    xmm0, dword ptr [@RWD00]
sub      esp, 8 // f2 takes 8 bytes of stack arguments, so generate an 8-byte alignment adjustment
sub      esp, 4 // "push" the float argument
movss    dword ptr [esp], xmm0
movss    xmm0, dword ptr [@RWD04]
sub      esp, 12 // f1 takes 4 bytes of stack arguments, so generate a 12-byte alignment adjustment
                        // NOTE: the stack has already been adjusted by 12 bytes! No alignment adjustment is needed!
sub      esp, 4 // "push" the inner float arg
movss    dword ptr [esp], xmm0
call     [Program:f1(float):float]
add      esp, 12 // restore adjustment
fstp     dword ptr [TEMP_01 ebp-04H]
movss    xmm0, dword ptr [TEMP_01 ebp-04H]
sub      esp, 4 // "push" second outer arg
movss    dword ptr [esp], xmm0
call     [Program:f2(float,float):float]
add      esp, 8 // "restore" alignment
```

Option 1 for fixing this would be to have ArgsAlignPadding() take into account all argument and alignment stack adjustments that have been made by outer calls at the point the inner call args start being pushed.

Option 2 for fixing this would be to hoist all nested calls, preventing arguments from multiple nested calls being on the stack simultaneously (one one call's arguments would be set up and pushed at a time). This is done (and required by ABI) for all non-x86 targets. It might lead to sub-optimal code due to the need for temps to store intermediate results.

Related issues: #10002, #10059.

### PR DESCRIPTION
**Pull request by BruceForstall**
The existing system of calculating per-call alignment adjustments
did not consider the possibility of nested calls. On x86, some
arguments for a call might be pushed on the stack before a
nested call's arguments start being pushed. Thus, a call can't
consider only its own arguments when determining the stack level.

Instead, use the existing genStackLevel variable, updated
dynamically during code generation, to determine the baseline
stack alignment when a call first needs to push something on
the stack, or if it has no stack arguments, whether it needs to
align the stack before a call.

One wrinkle here is that the fgAddCodeRef() function for adding
throw blocks for array bounds checks, and other similar helpers,
need to know the stack level on entry, and this stack level is
computed during argument morphing. There is a tough phase ordering
problem here. So, we bail out and force an EBP frame if there are
any such throw helpers in the function. When using an EBP frame,
the helper block doesn't need to know the stack level -- it is
only needed for ESP frames, needed for unwinding. Note that this
bail out already existed if the same helper needed multiple different
stack levels on entry. We could do slightly better without too much
work by not bailing out for top-level calls with no stack arguments.

Fixes #10122

### CODE REVIEW

**Comment by BruceForstall** [comment]
@seanshpark @parjong This change fixes to Linux/x86 alignment problem detailed in #10122 . The asm diffs look good to me. Can you test it on whatever Linux/x86 testing you do to see if it fixes the problem?

With this, I'm not sure we need to define `FEATURE_FIXED_OUT_ARGS` as described in #10012 .

**Comment by BruceForstall** [comment]
@briansull PTAL
cc @dotnet/jit-contrib

**Comment by briansull** [comment]
LGTM

**Comment by parjong** [comment]
@BruceForstall I'm not sure whether the following result is valid or not as I currently have a problem with overlay creation (#10299), the current patch looks fine except that it introduces two regressions (which looks like #10059):
```
FAILED   - [ 1335 :    1 sec ] JIT/Directed/perffix/primitivevt/mixed2_cs_do/mixed2_cs_do.sh
               BEGIN EXECUTION
               /root/dotnet-test/coreclr_unittest_20170320_111107_x86_x86-emu/coreclr-unittest-170320-021145/Core_Root/corerun mixed2_cs_do.exe
               
               Assert failure(PID 2212 [0x000008a4], Thread: 2212 [0x08a4]): Assertion failed 'getEmitter()->emitMaxStackDepth <= maxAllowedStackDepth' in 'testout1:Func_0_1_1_1_1():long' (IL size 242)
               
                   File: /home/parjong/projects/dotnet/coreclr/src/jit/codegencommon.cpp Line: 3206
                   Image: /root/dotnet-test/coreclr_unittest_20170320_111107_x86_x86-emu/coreclr-unittest-170320-021145/Core_Root/corerun
               
               ./mixed2_cs_do.sh: line 131:  2212 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" mixed2_cs_do.exe $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
         - [ 1336 :    2 sec ] JIT/Directed/perffix/primitivevt/mixed2_cs_r/mixed2_cs_r.sh
FAILED   - [ 1337 :    2 sec ] JIT/Directed/perffix/primitivevt/mixed2_cs_ro/mixed2_cs_ro.sh
               BEGIN EXECUTION
               /root/dotnet-test/coreclr_unittest_20170320_111107_x86_x86-emu/coreclr-unittest-170320-021145/Core_Root/corerun mixed2_cs_ro.exe
               
               Assert failure(PID 2265 [0x000008d9], Thread: 2265 [0x08d9]): Assertion failed 'getEmitter()->emitMaxStackDepth <= maxAllowedStackDepth' in 'testout1:Func_0_1_1_1_1():long' (IL size 242)
               
                   File: /home/parjong/projects/dotnet/coreclr/src/jit/codegencommon.cpp Line: 3206
                   Image: /root/dotnet-test/coreclr_unittest_20170320_111107_x86_x86-emu/coreclr-unittest-170320-021145/Core_Root/corerun
               
               ./mixed2_cs_ro.sh: line 131:  2265 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" mixed2_cs_ro.exe $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
```

**Comment by parjong** [comment]
This PR fixes #10001.

**Comment by BruceForstall** [comment]
@parjong you wrote:

> The number of failures increases from 41 into 43 with this patch.

Is this from a full run of the dotnet/coreclr test tree? Or do you run a subset of the tests? If it is a subset, what are the tests that are run?

Can you tell me the list of the 41 failing tests?

**Comment by parjong** [comment]
@BruceForstall The results come from a full run of coreclr unittest (priority 0).

Here are related XMLs:
 - [XML (41 failures)](https://github.com/dotnet/coreclr/files/856702/coreclrtests.xml.41.txt)
 - [XML (43 failures)](https://github.com/dotnet/coreclr/files/856703/coreclrtests.xml.43.txt)

**Comment by BruceForstall** [comment]
@parjong check my latest commit; I think it should fix that assert.

**Comment by parjong** [comment]
@BruceForstall Wow! Updated PR resolves all the assert failures when I checked manually. I'm currently running full test, but I could let you know its result tomorrow as I'll be absent in the afternoon.

I found that there is a compile error in Release build:
```
/home/parjong/projects/dotnet/coreclr/src/jit/codegencommon.cpp:3209:33: error: use of undeclared identifier 'maxNestedAlignment'
        maxAllowedStackDepth += maxNestedAlignment;
                                ^
```

**Comment by BruceForstall** [comment]
@parjong I fixed the release build issue (I hadn't noticed the assert was noway_assert(), which is available in release).

**Comment by BruceForstall** [comment]
@parjong This is ready to be merged, if you think it looks good. PTAL.

I know #10012 might mean we reimplement this again, but until that happens, if this unblocks your work, it's at least better that what is there right now.

**Comment by parjong** [comment]
@BruceForstall LGTM, Thank you! 

This PR allows me to focus on stack misalignment issue while @seanshpark is working on #10012.

**Pull request merged**
