### PR TITLE
Move all JIT stress jobs into a sub directory on CI

### PR DESCRIPTION
**Pull request by sejongoh**

### CODE REVIEW

**Comment by sejongoh** [comment]
@dotnet-bot test ci please

**Comment by sejongoh** [comment]
@dotnet-bot test Windows_NT jitstress1

**Comment by sejongoh** [comment]
@dotnet-bot test jitstress2_jitstressregs1

**Comment by sejongoh** [comment]
@dotnet-bot test Windows_NT jitstress2_jitstressregs1

**Comment by sejongoh** [comment]
It looks like the previous changes work.

[http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/jitstress/]()

**Comment by sejongoh** [comment]
@mmitche PTAL

**Comment by mmitche** [comment]
Doesn't this not end up changing the location of the windows stress jobs?

**Comment by sejongoh** [comment]
The Windows thing is done by the previous PR like below, so it is not included in this PR. 

[Previous PR changes in the Windows loop]
```
                    def folderName = isJITStressJob(scenario) ? 'jitstress' : '';
                    
                    // Create the new job
                    def newJob = job(Utilities.getFullJobName(project, jobName, isPR, folderName)) {}
```

**Comment by mmitche** [comment]
Oh oh okay.  LGTM

**Comment by sejongoh** [comment]
Thanks for review!

**Pull request merged**
