### PR TITLE
Fix resources lookup to use satellite assembly resouce lookup inside AppX when the assembly is Private.Corelib

### PR DESCRIPTION
**Pull request by safern**
Necessary changes in CoreFX are in. 

cc: @tarekgh @jkotas

### CODE REVIEW

**Comment by tarekgh** [comment]
LGTM

**Comment by tarekgh** [comment]
@dotnet-bot help

**Comment by tarekgh** [comment]
@dotnet-bot test Ubuntu x64 corefx_baseline
@dotnet-bot test Windows_NT x64 corefx_baseline

**Comment by safern** [comment]
@stephentoub just as an FYI this shouldn't affect the coreclr ingestion into corefx because I did all the required work for it in that side, but just in case you see a UWP failure in the next PR to ingest it so that you know it was me so that I can fix it.

**Comment by stephentoub** [comment]
Ok, thanks, @safern.

**Comment by safern** [comment]
@mmitche looks like this jobs never kicked off.

**Comment by safern** [comment]
Merging as the CI legs seem to be blocked.

**Pull request merged**
