### PR TITLE
Handle null ref in Compiler::optCreateAssertion

### LINKED ISSUE #10359: [Arm64/Unix] Crossgen System.Private.DataContractSerialization.dll hits unreached()
Crossgen System.Private.DataContractSerialization.dll hits unreached().

Unreached is in frame 10.  

Incoming type is TYP_REF (leads to in frame 11 line 1330).

The error seems to be that we were supposed to use the size_t specialization of the ValueNumStore::CoerceTypRefToT template.  But frame 14 is instantiating template with ssize_t which apparently is not a match.

```
#10 0x0000007fb6c95970 in ValueNumStore::CoerceTypRefToT<long> (c=0xf6fc70, offset=0) at /home/sdmaclea/git/coreclr/src/jit/valuenum.h:1381
#11 0x0000007fb6c957ec in ValueNumStore::SafeGetConstantValue<long> (this=0xf6f228, c=0xf6fc70, offset=0) at /home/sdmaclea/git/coreclr/src/jit/valuenum.h:1330
#12 0x0000007fb6c95664 in ValueNumStore::ConstantValueInternal<long> (this=0xf6f228, vn=0, coerce=true) at /home/sdmaclea/git/coreclr/src/jit/valuenum.h:724
#13 0x0000007fb6c8f190 in ValueNumStore::CoercedConstantValue<long> (this=0xf6f228, vn=0) at /home/sdmaclea/git/coreclr/src/jit/valuenum.h:746
#14 0x0000007fb6c8359c in Compiler::optCreateAssertion (this=0xe7b7b0, op1=0xf58ee8, op2=0x0, assertionKind=Compiler::OAK_NOT_EQUAL, assertion=0x7fffffc6b8) at /home/sdmaclea/git/coreclr/src/jit/assertionpro
p.cpp:965
```

### PR DESCRIPTION
**Pull request by sdmaclea**
Code as recommended by Eugene Rozenfeld in #10359

Fixes #10359

### CODE REVIEW

**Comment by sdmaclea** [comment]
@erozenfeld Your fix allowed crossgen to finish without assertion.

**Comment by RussKeldorph** [comment]
Windows_NT x86 Checked Build and Test is #10022.  Ignore.

**Comment by RussKeldorph** [comment]
@dotnet/jit-contrib

**Comment by JosephTremoulet** [comment]
LGTM too

**Pull request merged**
