### PR TITLE
Ignore FileStream.FlushWriteBuffer failures during finalization

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/corefx/issues/17086
cc: @JeremyKuhne

### CODE REVIEW

**Comment by jkotas** [comment]
All OSX Release builds are failing with:

ERROR: Unable to find project for artifact copy: dotnet_corefx/master/osx_release

@wtgodbe Any ideas?

**Comment by wtgodbe** [comment]
Matt Mitchell is taking a look at this failure: https://github.com/dotnet/coreclr/pull/10054

It looks like it's because CoreFX job names changed recently.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@ianhays or @ericstj, could you review?

**Comment by stephentoub** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Pull request merged**
