### PR TITLE
Fix the arm/arm64 jobs on Windows.

### PR DESCRIPTION
**Pull request by tannergooding**
This should resolve https://github.com/dotnet/coreclr/issues/22654

### CODE REVIEW

**Comment by tannergooding** [comment]
@RussKeldorph, what is the testing phrase for the Windows_NT arm jobs?

I went and looked at the job configuration in Jenkins and it doesn't appear to be connected to any build-triggers.

**Comment by tannergooding** [comment]
Hmm, this won't actually work, `init-tools.cmd` isn't supported on `arm32`.

**Comment by tannergooding** [comment]
Ok, this should hopefully be good. I just switched the jobs back to conditionally importing RoslynPropsFile based on whether or not it exists.

This is slightly unfortunate as it means that you can't guarantee deterministic builds (you could build with the desired roslyn toolset or you could end up fallback to something else entirely).

**Comment by tannergooding** [comment]
test Windows_NT arm Cross Checked Innerloop Build and Test
test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by tannergooding** [comment]
@dotnet-bot test \QWindows_NT arm Cross Checked Innerloop Build and Test\E

**Comment by tannergooding** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test

**Comment by tannergooding** [comment]
hmm, tried using the exact job name and the trigger phrase listed in the help_message: https://ci.dot.net/job/dotnet_coreclr/job/master/job/help_message/311/console

**Comment by RussKeldorph** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test

**Comment by RussKeldorph** [comment]
@tannergooding You have to be in the whitelist: https://github.com/dotnet/coreclr/blob/e3d4b9c7e355ca67b4717e212497fe4d8a05eb57/netci.groovy#L1650-L1669 to trigger these jobs.  Another unfortunate limitation from the past.  Not worth fixing at this point since we're moving to Azure DevOps.  Though, you might want to add yourself to this list in this PR since it's a simple change.

**Comment by tannergooding** [comment]
@RussKeldorph, thanks for the info. I've added myself to the list in a separate PR (https://github.com/dotnet/coreclr/pull/22665) so that it doesn't block this from going in.

**Pull request merged**
