### PR TITLE
Run dotnet/codeformatter on S.P.CoreLib sources.

### PR DESCRIPTION
**Pull request by alexperovich**

### CODE REVIEW

**Comment by jkotas** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by jkotas** [comment]
@alexperovich Could you please resolve the conflict?

**Comment by jamesqo** [comment]
Have been waiting for this for years. ❤️ 🎉

**Comment by perlun** [comment]
Nice stuff! Where is the dotnet/codeformatter, if I want to run it on my own codebase?

**Comment by jkotas** [comment]
https://github.com/dotnet/codeformatter

**Comment by perlun** [comment]
> https://github.com/dotnet/codeformatter

Great, thanks!

**Pull request merged**
