### PR TITLE
Fix lldb header error on FreeBSD

### PR DESCRIPTION
**Pull request by ajensenwaud**

### CODE REVIEW

**Comment by janhenke** [comment]
LGTM

**Comment by josteink** [comment]
I think it's weird that this should be needed at this point, if it's not needed for the other platforms.

Apart from that, and unless anyone objects: LGTM.

**Comment by janvorli** [comment]
LGTM  modulo @jkotas comment

**Comment by jkotas** [comment]
Superseded by #819

**Pull request closed without merging**
