### PR TITLE
Add JIT Coding Conventions document in markdown format

### PR DESCRIPTION
**Pull request by BruceForstall**
Please review that I've done the markdown formatting "correctly", not the content of the document.

/cc @richlander @briansull @CarolEidt @sivarv @schellap @cmckinsey

### CODE REVIEW

**Comment by CarolEidt** [comment]
LGTM

**Comment by ellismg** [comment]
Bugs me a little bit that the TOC starts numbering at 4, but I sort of understand why that happened.

**Comment by ThomsonTan** [comment]
I am wondering why the "Contents" section starts from #4.

**Comment by BruceForstall** [comment]
Regarding TOC starting at section 4: that's a remnant of the conversion from Word. Unfortunately, markdown format is, uh, simple, so renumbering everything would be a huge pain. Maybe there's a tool that can do this easily (that I don't know about). Anyway, IMO, not a big deal. If we ever want to add sections and need to renumber, then it will become annoying and problematic.

**Comment by BruceForstall** [comment]
I responded to feedback and squashed the commits.

**Pull request merged**
