### PR TITLE
Move runincontext to src/tools

### PR DESCRIPTION
**Pull request by RussKeldorph**
This SDK-style project is causing problems on some machines with VS
installs that can't build it.  For now, move it to a place where it
doesn't build with the tests.

### CODE REVIEW

**Comment by jashook** [comment]
I believe the runincontext.cmd/sh will need to be updated; however the can be done in a separate pr.

**Comment by janvorli** [comment]
> I believe the runincontext.cmd/sh will need to be updated; however the can be done in a separate pr.

Yes, we don't need to do it in this change.

**Comment by RussKeldorph** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Pull request merged**
