### PR TITLE
Disable armlb windows jobs

### PR DESCRIPTION
**Pull request by jashook**
@RussKeldorph @echesakovMSFT @BruceForstall ptal

### CODE REVIEW

**Comment by jashook** [comment]
@dotnet-bot test ci please

**Comment by BruceForstall** [comment]
I have some concerns with this:
1. I would prefer to see the arm legacy jit bug fixed
2. If (1) is not high enough priority, I would prefer a solution that allows armlb jobs to continue running, either (a) set `COMPlus_ZapDisable=1` for the jobs, or (b) don't crossgen S.P.C.dll, or (c) crossgen using RyuJIT but still run tests using armlb, e.g., by commenting out the following:
```
// For 'armlb' (the JIT LEGACY_BACKEND architecture for arm), tell build.cmd to use legacy backend for crossgen compilation.
// Legacy backend is not the default JIT; it is an aljit. So, this is a special case.
if (architecture == 'armlb') {
    buildOpts += ' -crossgenaltjit legacyjit.dll'
}
```

While I would like to see armlb go away (soon-ish), I don't think now is the time. We haven't yet extracted all the value we can from it.

**Comment by RussKeldorph** [comment]
I favor disabling the job now to reduce the load on our ARM machines.  We need to be kicking off a lot of jobs in the near future to do 2.1 signoff.  If LB does have value, we can bring it back after signoff.

**Comment by RussKeldorph** [comment]
@dotnet/jit-contrib

**Comment by jashook** [comment]
@dotnet-bot test ci please

**Pull request merged**
