### PR TITLE
Delete unused leftovers from binary serialization

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
@dotnet-bot test Windows_NT x64 Checked corefx_baseline

**Comment by sdmaclea** [comment]
test Ubuntu arm64 Cross Debug Innerloop Build

**Comment by jkotas** [comment]
> setting the _callingAssembly to null but I guess you there is a reason for that.

I have renamed the actually used `m_callingAssembly` field to `_callingAssembly`. Pretty safe change - just hard to see in the diff.

**Comment by ViktorHofer** [comment]
Ah now I see it.

**Pull request merged**
