### PR TITLE
Specialize IndexOf, LastIndexOf for the enum equality comparers

### PR DESCRIPTION
**Pull request by jamesqo**
Overrides the internal `IndexOf`/`LastIndexOf` methods for `EqualityComparer`, so only one virtual method call is made as opposed to however many elements are in the array. I also made some other changes to bring the code in line with what I did in #5503, namely using `sealed` where applicable and not calling `Name` for `GetHashCode`.

### Performance impact

Test code:

```cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Reflection;

namespace ConsoleApplication
{
    public class Program
    {
        const int Index = Length / 2;
        const int Length = 5000;
        const int Iterations = 100000;
        const int OuterIterations = 5;
        
        public static void Main(string[] args)
        {
            var array = new StringSplitOptions[Length];
            array[Index] = StringSplitOptions.RemoveEmptyEntries;

            for (int i = 0; i < OuterIterations; i++)
            {
                var watch = Stopwatch.StartNew();
                for (int j = 0; j < Iterations; j++)
                    Array.IndexOf(array, StringSplitOptions.RemoveEmptyEntries);
                watch.Stop();
                Console.WriteLine(watch.Elapsed);
            }

            Console.WriteLine();

            for (int i = 0; i < OuterIterations; i++)
            {
                var watch = Stopwatch.StartNew();
                for (int j = 0; j < Iterations; j++)
                    Array.LastIndexOf(array, StringSplitOptions.RemoveEmptyEntries);
                watch.Stop();
                Console.WriteLine(watch.Elapsed);
            }
        }
    }
}
```

Before:

```
00:00:01.0684618
00:00:01.0321808
00:00:01.5014109
00:00:01.9096960
00:00:01.1151452

00:00:01.0152761
00:00:01.2019504
00:00:01.0269755
00:00:01.1227927
00:00:01.2432870
```

After (5x speedup):

```
00:00:00.3152865
00:00:00.2413720
00:00:00.2654954
00:00:00.2776022
00:00:00.2525021

00:00:00.2897419
00:00:00.2840207
00:00:00.2761021
00:00:00.3039447
00:00:00.2753199
```

@jkotas @omariom

### CODE REVIEW

**Comment by SunnyWar** [comment]
nit: I really dislike this style:
`if (toFind == current) return i; `

**Comment by jasonwilliams200OK** [comment]
> I really dislike this style

Me too, so would probably K&R themselves .. but that's irrelevant because contribution guideline: https://github.com/dotnet/coreclr/blob/03cd4bc/Documentation/project-docs/contributing.md#dos-and-donts, point 2 say:

> **DO** give priority to the current style of the project or file you're changing even if it diverges from the general guidelines.

Looking at rest of the file `EqualityComparer.cs`, this style is heavily used.

**Comment by SunnyWar** [comment]
@jasonwilliams200OK .... ya. *sigh*. I know. I'm not convinced it's the best policy to have but I understand why it's there.

**Comment by jamesqo** [comment]
> I think that a really bad coding style should be changed regardless.

Is it really that bad? IMO, I prefer it since it's more terse than using brackets for single statements. If this was changed, then other places that use this style should be changed beforehand.

**Comment by jkotas** [comment]
Do we have test coverage for this in corefx?

**Comment by jamesqo** [comment]
@jkotas Very unfortunately, I think we lack test coverage for any sort of Comparer/EqualityComparer in corefx-- see dotnet/corefx#10110, which I just raised yesterday.

**Comment by jamesqo** [comment]
@jkotas It should be safe to merge this now. @hughbe's work at dotnet/corefx#11716 has added extensive coverage for this, and I just supplemented his with dotnet/corefx#12108. PTAL

**Comment by jkotas** [comment]
@dotnet-bot test OSX x64 Checked Build and Test  please

**Pull request merged**
