### PR TITLE
Fix to gc-stress issue #2921.

### LINKED ISSUE #2921: GCStress: JitStress: Crash in ldloca_s_r4
```
export COMPlus_ZapDisable=1
export COMPlus_JitStress=2
export COMPlus_GCStress=1

corerun JIT/IL_Conformance/Old/directed/ldloca_s_r4/ldloca_s_r4.exe
{0x1e5a-0x7fd937b17c30} ASSERT [THREAD ] at /home/swaroops/git/coreclr/src/pal/src/thread/context.cpp.685: Got unknown signal number 11 with code 128
/home/swaroops/bin/runn: line 3:  7770 Aborted                 (core dumped) ./corerun ~/test/$1.exe
134
```

### PR DESCRIPTION
**Pull request by sivarv**
Repro is a case of converting addr of a local to float. The type on GT_LCL_VAR_ADDR could be TYP_BYREF.  genIntToFloatCast() passes source operand type as emitAttr to generate cvtsitoss.  xarch emitter cannot handle casting-away gc-ness and incorrectly considers that this instruction operates on gc-byrefs and reports xmm0 becoming alive with a byref and hence the reason for crash under gc-stress.

The source operand of a cast operation is never a gc-type except for GT_LCL_VAR_ADDR and GT_LCL_FLD_ADDR both which can be considered as non-gc types (i.e TYP_I_IMPL).  In all other cases where a gc-type is not on stack fgMorphCast() create a non-gc temp, assigns gc-type val to temp and uses temp for cast operation.

Fixes #2921

### CODE REVIEW

**Comment by sivarv** [comment]
@dotnet/jit-contrib - Please review this.

**Comment by BruceForstall** [comment]
LGTM

**Comment by sivarv** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test

**Comment by CarolEidt** [comment]
LGTM

**Comment by briansull** [comment]
LGTM

**Pull request merged**
