### PR TITLE
[WIP] Enable cast operand containment

### LINKED ISSUE #12595: [RyuJit/x64] Generates extra movsxd when using a byte value as an address offset
In image processing, it's common to map byte values (8-bit-per-channel pixels) through a lookup table.

RyuJit x64 apparently uses a 32-bit `movzx` to read byte values, then widens using `movsxd` before using them as address offsets.

Here's a quick sample program demonstrating the issue:

```C#
using System;
using System.Runtime.CompilerServices;

class Program
{
	[MethodImpl(MethodImplOptions.NoInlining)]
	unsafe static void LUTMap(byte* src, float* dest, float* lut, int cb)
	{
		byte* end = src + cb - 4;
		while(src <= end)
		{
			dest[0] = lut[src[0]];
			dest[1] = lut[src[1]];
			dest[2] = lut[src[2]];
			dest[3] = lut[src[3]];

			src  += 4;
			dest += 4;
		}
	}

	unsafe static void Main(string[] args)
	{
		var bytes = new byte[1024 * 1024];
		var floats = new float[bytes.Length];
		var lut = new float[256];


		new Random(42).NextBytes(bytes);
		for (int i = 0; i < lut.Length; i++)
			lut[i] = (float)Math.Pow(i, 1 / 2.4);

		fixed (byte* pbytes = &bytes[0])
		fixed (float* pfloats = &floats[0], plut = &lut[0])
		{
			LUTMap(pbytes, pfloats, plut, bytes.Length);
		}
	}
}
```

RyuJit x64 generates the following for the LUTMap method
```asm
; Assembly listing for method Program:LUTMap(long,long,long,int)
; Emitting BLENDED_CODE for X64 CPU with AVX
; optimized code
; rsp based frame
; fully interruptible
; Final local variable assignments
;
;  V00 arg0         [V00,T00] ( 11, 32   )    long  ->  rcx
;  V01 arg1         [V01,T01] (  8, 26   )    long  ->  rdx
;  V02 arg2         [V02,T02] (  6, 18   )    long  ->   r8
;  V03 arg3         [V03,T04] (  3,  3   )     int  ->   r9
;  V04 loc0         [V04,T03] (  3,  6   )    long  ->  rax
;# V05 OutArgs      [V05    ] (  1,  1   )  lclBlk ( 0) [rsp+0x00]
;
; Lcl frame size = 0

G_M15454_IG01:
       C5F877               vzeroupper

G_M15454_IG02:
       4963C1               movsxd   rax, r9d
       488D4401FC           lea      rax, [rcx+rax-4]
       483BC8               cmp      rcx, rax
       7760                 ja       SHORT G_M15454_IG04

G_M15454_IG03:
       440FB609             movzx    r9, byte  ptr [rcx]
       4D63C9               movsxd   r9, r9d
       C4817A100488         vmovss   xmm0, dword ptr [r8+4*r9]
       C4E17A1102           vmovss   dword ptr [rdx], xmm0
       440FB64901           movzx    r9, byte  ptr [rcx+1]
       4D63C9               movsxd   r9, r9d
       C4817A100488         vmovss   xmm0, dword ptr [r8+4*r9]
       C4E17A114204         vmovss   dword ptr [rdx+4], xmm0
       440FB64902           movzx    r9, byte  ptr [rcx+2]
       4D63C9               movsxd   r9, r9d
       C4817A100488         vmovss   xmm0, dword ptr [r8+4*r9]
       C4E17A114208         vmovss   dword ptr [rdx+8], xmm0
       440FB64903           movzx    r9, byte  ptr [rcx+3]
       4D63C9               movsxd   r9, r9d
       C4817A100488         vmovss   xmm0, dword ptr [r8+4*r9]
       C4E17A11420C         vmovss   dword ptr [rdx+12], xmm0
       4883C104             add      rcx, 4
       4883C210             add      rdx, 16
       483BC8               cmp      rcx, rax
       76A5                 jbe      SHORT G_M15454_IG03

G_M15454_IG04:
       C3                   ret

; Total bytes of code 108, prolog size 3 for method Program:LUTMap(long,long,long,int)
; ============================================================
```

Can it be modified to use the 64-bit `movzx` in cases like this?

### PR DESCRIPTION
**Pull request by mikedn**
This improves code generation for (u)int -> (u)long casts without overflow when the cast operand is a GT_IND node. Currently this is a two step process - first load the value from memory (and widen it to TYP_INT if it's a small int value) and then widen to TYP_LONG. This can be avoided by containing the cast operand.

Fixes #12595

### CODE REVIEW

**Comment by mikedn** [comment]
jit-diff summary:
```
Total bytes of diff: -1185 (-0.01% of base)
    diff is an improvement.
Total byte diff includes 0 bytes from reconciling methods
        Base had    0 unique methods,        0 unique bytes
        Diff had    0 unique methods,        0 unique bytes
Top file improvements by size (bytes):
        -383 : System.Reflection.Metadata.dasm (-0.50% of base)
        -246 : System.Private.CoreLib.dasm (-0.01% of base)
        -195 : System.Runtime.Numerics.dasm (-0.33% of base)
         -44 : Microsoft.CodeAnalysis.dasm (-0.01% of base)
         -44 : System.Security.Cryptography.Algorithms.dasm (-0.05% of base)
27 total files with size differences (27 improved, 0 regressed), 52 unchanged.
Top method improvements by size (bytes):
         -99 : System.Reflection.Metadata.dasm - MetadataReader:InitializeTableReaders(struct,ubyte,ref,ref):this
         -39 : System.Private.CoreLib.dasm - EventProvider:WriteEvent(byref,long,long,long,ref):bool:this
         -35 : System.Reflection.Metadata.dasm - MetadataReader:InitializeStreamReaders(byref,ref,byref,byref,byref):this
         -26 : System.Security.Cryptography.Algorithms.dasm - DES:QuadWordFromBigEndian(ref):long
         -23 : System.Diagnostics.Process.dasm - NtProcessManager:GetProcessInfos(ref,int,int,ref):ref
259 total methods with size differences (259 improved, 0 regressed), 65310 unchanged.
```
Sample diffs:
```diff
        movzx    r8, byte  ptr [rcx+17]
-       mov      r8d, r8d

        mov      edx, dword ptr [rsi+rcx+40]
-       mov      edx, edx

-       movsx    rcx, word  ptr [rsi+8]
-       movsxd   rax, ecx
+       movsx    rax, word  ptr [rsi+8]

-       mov      ecx, dword ptr [rsi]
-       movsxd   rcx, ecx
+       movsxd   rcx, dword ptr [rsi]
```

**Comment by mikedn** [comment]
It's worth pointing out that casts involving lclvars have a similar issue:
```C#
static ulong Test(byte x) => x
```
generates
```asm
0FB6C1               movzx    rax, cl ; eax actually but it doesn't really matter
8BC0                 mov      eax, eax
```
but the IR causing this is different so a separate solution/fix will be needed:
```
N005 (  2,  2) [000001] ------------ t1 =    LCL_VAR   int    V00 arg0         u:2 rcx (last use) REG rcx $80
                                                 /--*  t1     int
N007 (  3,  4) [000005] ------------ t5 = *  CAST      int <- ubyte <- int REG rax $100
                                                 /--*  t5     int
N009 (  4,  6) [000002] ---------U-- t2 = *  CAST      long <- ulong <- uint REG rax $140
                                                 /--*  t2     long
N011 (  5,  7) [000003] ------------ *  RETURN    long   REG NA $180
```

**Comment by mikedn** [comment]
Waiting for #12680

**Comment by mikedn** [comment]
@CarolEidt Is it correct for a cast with overflow to store its result in the target register before checking for overflow? 

I assume that it is because in case of exception the result can only be observed if we're in a try block and the destination is a lclvar. But if we're in a try block the lclvar won't be enregistered so the result of the cast won't be stored in the lclvar by the cast node itself but by a subsequent `GT_STORE_LCL_VAR`.

**Comment by CarolEidt** [comment]
> Is it correct for a cast with overflow to store its result in the target register before checking for overflow?

I believe that it would only be incorrect, as you suggest, if the register is the home of the lclVar, and is live outside of the try block. But, as you say, that won't be the case in a try. Even when we enable write-thru of EH variables, as is currently being worked on, the memory location is what will be the definitive copy. If/when we consider keeping these lclVars in registers across exception edges, this would be a concern - but I don't see that happening in the near term.

**Comment by karelz** [comment]
What is status of this PR? What are the next steps to move it forward?

**Comment by mikedn** [comment]
Waiting for #13501 to be sorted out

**Comment by CarolEidt** [comment]
> Waiting for #13501 to be sorted out

Now that #13501 is addressed, we should look at this for 2.1

**Comment by mikedn** [comment]
Things to sort out:
* Code duplication - both the new code and the existing code are relatively complex, I'm not sure if it's possible to merge them without making things worse so they'll probably stay as is. But arm64 could use a similar fix, I don't know it would be similar enough to allow code reuse without a pile of ifdefs though.
* I need to figure out what was the test case that failed because of 13501. AFAIR I generated all possible combinations in an IL file and a few failed. Now where did I put that generator...
* A few more comments here and there wouldn't hurt...

**Comment by CarolEidt** [comment]
@mikedn - thanks. And to correct my earlier comment, I should have said "we should look at this for 2.2" (not 2.1). I have reviewing this on my list of "to do"s, so let me know when you think it's ready for review.

**Comment by mikedn** [comment]
This is on hold until #19296 is done. Attempting to extend containment support to ARM is a waste of time in the current state of the code. The XARCH and ARM cast codegen implementations are completely different even though there's no need to be like that.

**Comment by sandreenko** [comment]
@mikedn what about this one, Is it ready for review?

**Comment by mikedn** [comment]
@sandreenko Ha ha, as much as I would love for this particular one to be ready it still isn't. The ARM version is busted. For one thing, ARM64's emitter unexpectedly emits `ldrsw` instead of `ldr`. And then there appears to be some other issue that leads to asserts during crossgen.

**Comment by mikedn** [comment]
The ARM story is pretty hairy:
* ARM32 asserts when attempting to emit ldrb/ldrsb/ldrh/ldrsh with EA_4BYTE. IMO the assert is bogus, the instruction size is really 4 bytes, ARM does not have 1/2 byte instructions like xarch has.
* Lack of support for reg optional on ARM, the relevant code in `genConsumeRegs` is ifdefed out, even if `SetRegOptional` is available.
* `OptimizeConstCompare` removes a cast node and does not call `ClearContained` on the cast operand. We end up with a compare instruction with a contained operand, inherited from the cast. Naturally, that fails on ARM.
* Broken register requirements on casts with contained operand. The contained indir may require a temporary register to deal with unsupported address modes. `BuildCast` doesn't know that.
* `emitInsLoadStoreOp` emits a 64 bit `ldr` when asked to emit a 32 bit `ldr`. There seems to be some confusion throughout ARM64 codegen - for `TYP_INT` indirs it emits `sxtw` instead of a 32 bit `ldr`. This deviates from X64 codegen and other ARM64 compilers.

I'll see what I can do about all this.

The last one is pretty dubious to fix. But it's probably a good idea to fix it rather than attempt to workaround it. Having `emitInsLoadStoreOp` unexpectedly emit a 64 bit `ldr` is asking for trouble.

**Comment by mikedn** [comment]
On hold again until #20126 is done.

**Comment by karelz** [comment]
What's the plan for this PR @russellhadley? Maybe we should close it until it is ready - it's almost 2y old now, with last changes from 7 months ago ...

**Comment by mikedn** [comment]
OK, I'm going to close this until #20126 is merged. I should have probably ignored ARM and finish this for x86/64 but I wasn't expecting that it would take so long. Oh well, it's too late for 3.0 anyway.

**Pull request closed without merging**
