### PR TITLE
Add RunBenchmarks.sh for unix-like systems

### PR DESCRIPTION
**Pull request by wateret**
Usage is basically the same as RunBenchmarks.cmd.

### CODE REVIEW

**Comment by lemmaa** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build

**Comment by wateret** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build

**Comment by danmosemsft** [comment]
@janvorli does this look good to merge?

**Comment by janvorli** [comment]
LGTM, thank you and apologies for missing it when it was created.

**Comment by wateret** [comment]
CI checks failed so I rebased it to recent master.

**Comment by danmosemsft** [comment]
@janvorli please merge if its ready.

**Pull request merged**
