### PR TITLE
Fix build on OSX with CMake version >= 3.4

### PR DESCRIPTION
**Pull request by janvorli**
The new CMake version 3.4 has split `<FLAGS>` into `<FLAGS>` `<INCLUDES>`, so the
assembler invocation was not passing include paths anymore.
This fix adds the `<INCLUDES>` to the CMAKE_ASM_COMPILE_OBJECT variable
in the root CMakeLists.txt.

### CODE REVIEW

**Comment by jkotas** [comment]
Could you please make the same fix for corert too (will fix https://github.com/dotnet/corert/issues/582)?

**Comment by jkotas** [comment]
LGTM

**Comment by jkotas** [comment]
Fixes #2054

**Comment by jasonwilliams200OK** [comment]
Is this backward compatible in terms of older versions? The first line in this file should probably be changed from:

```cmake
cmake_minimum_required(VERSION 2.8.12)
```

to:

```cmake
cmake_minimum_required(VERSION 3.4.0)
```

**Comment by janvorli** [comment]
I was hoping that it would work on the older cmake - I couldn't install the old cmake for some reason anymore, so I have used the CI as a test. But obviously from the CI results it doesn't work.

**Comment by jasonwilliams200OK** [comment]
Probably a better backwards-compatible solution would be:

```cmake
cmake_minimum_required(VERSION 2.8.12)

...
...

if(CMAKE_VERSION VERSION_LESS "3.4.0")
  set(CMAKE_ASM_COMPILE_OBJECT "${CMAKE_C_COMPILER} <FLAGS> <DEFINES> -o <OBJECT> -c <SOURCE>")
else()
  set(CMAKE_ASM_COMPILE_OBJECT "${CMAKE_C_COMPILER} <FLAGS> <DEFINES> <INCLUDES> -o <OBJECT> -c <SOURCE>")
endif()
```

**Comment by janvorli** [comment]
@jasonwilliams200OK I have also come to the same conclusion. Especially since the max version available in Ubuntu 14.04 is still 2.8.12.

**Comment by jkotas** [comment]
@dotnet-bot test OSX x64 Release Build and Test

**Comment by jkotas** [comment]
@dotnet-bot retest OSX x64 Release Build and Test

**Comment by jkotas** [comment]
@dotnet-bot test OSX x64 Release Build and Test

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by janvorli** [comment]
@dotnet-bot test OSX x64 Release Build and Test

**Pull request merged**
