### PR TITLE
Reword invalid program exception message

### PR DESCRIPTION
**Pull request by danmosemsft**
This message occurs when the IL has unexpected structure: make it clearer. It basically originates whenever BADCODE3 macro is hit.  

There is one other case: CORINFO_VERIFICATION_DONT_JIT which is only set when CORINFO_VERIFICATION_RUNTIME_CHECK is set and that is never set. Perhaps there is cleanup that can be done around this zap code?

Also removed a string I saw was dead. There may be others.

### CODE REVIEW

**Comment by jkotas** [comment]
> This message occurs when the IL has unexpected structure:

Yes, but it also occurs when the JIT hits internal limitation.

If your IL is invalid, it can lead to pretty much any error - NullRefenceException, ... . We do not augment the errors that can be result of invalid IL with a note that maybe your IL was invalid.

**Comment by jkotas** [comment]
@AndyAyersMS change #16320 was specifically about making sure that we print the "JIT hit internal limitation" error in this case. You can get this error e.g. if you create a very big method in C#.

**Comment by danmosemsft** [comment]
How about  "The Just-In-Time compiler encountered invalid IL code or an internal limitation." ? 

Sure invalid IL can cause other possible issues, but this message does not claim otherwise. 

I would like to make it clearer that ref-emit may be the cause - with the original message, I at first thought there was some problem with the JIT itself.

**Comment by jkotas** [comment]
I do not have strong opinion either way. I think that the current message is more accurate.

If you are using Reflection.Emit, you have to know what you are doing. This error message is not going to save you when you screw up.

**Comment by danmosemsft** [comment]
My thinking was that we wouldn't consider "unable to compile invalid input" to be an example of an "internal limitation" of the compiler 😉  I may be misunderstanding though.

@AndyAyersMS ?

**Comment by AndyAyersMS** [comment]
The 'or' version seems fine to me.

I suppose it would be somewhat better to split apart the two cases.

**Comment by danmosemsft** [comment]
OK, updated to "or" form. Also changed back to "JIT" rather than "Just-In-Time-Compiler" because that seems to be more consistent with other messages.

**Comment by danmosemsft** [comment]
@AndyAyersMS could you please take a look?

**Pull request merged**
