### PR TITLE
Fix cross component builderror - CMakeLists.txt for PAL

### PR DESCRIPTION
**Pull request by hseok-oh**
define & use PAL_ARCH_SOURCES_DIR in PAL's CMakeLists.txt. 
define PAL_ARCH_SOURCES_DIR based on platform architecture, not JIT target architecture.

### CODE REVIEW

**Comment by hseok-oh** [comment]
related issue: #9818

**Comment by hseok-oh** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by janvorli** [comment]
This fix is strange. It seems that rather the ARCH_SOURCES_DIR should be fixed. It doesn't make sense to compile PAL for different arch than the other runtime parts during the crosscomponent build and so the ARCH_SOURCES_DIR should reflect the platform we are targetting with the build.

**Comment by hseok-oh** [comment]
It seems that PAL and other runtime part uses ARCH_SOURCES_DIR as different usage. For example, src/vm/arch is related to code generation. And some debug interfaces in src/debug uses to decode generated code or simulating. (I'm not familiar with debuggin interface). These parts uses ARCH_SOURCES_DIR as target architecture. On the other hand, it seems that ARCH_SOURCES_DIR is used for platform architecture in src/pal/src.

**Comment by janvorli** [comment]
Ah, I have missed the fact that we don't have just asm files but we also have .cpp files in the arch specific directories and that some of those (but not all) are used for crossbuild tools. 
So it seems we should actually split the ARCH_SOURCES_DIR into two ones - one for the files that we use in the crossbuild and one for the ones that are only meant to run on the target (like the .asm files plus some of the cpp ones).
However, that would be a cleanup that's out of scope of this change. So I'll create a separate issue for that and merge your change as is.

**Comment by hseok-oh** [comment]
@janvorli I complete agree with your opinion. Thanks.

**Pull request merged**
