### PR TITLE
Speed up package resotre of JIT Test build

### PR DESCRIPTION
**Pull request by ellismg**
We spend a fair amount of time (six wall clock minutes on my machine)
doing package restore for the JIT tests. This is because each project
has its own packages.config file, so during the build we call nuget
restore for each project.

There are only four unique packages.config files for all these tests, so
this change moves them to tests/src/JIT/config and updates the project
files to consume them from there.

This means during the build the `EnsureDependencies` target does not
need to invoke nuget restore as often and the build is much faster as a
result.

### CODE REVIEW

**Comment by ellismg** [comment]
I would like to look at the time savings in a CI run before merging this.  /cc @pgavlin

**Comment by ellismg** [comment]
Doing another run with time stamps enabled.

@dotnet-bot test this please.

**Comment by ellismg** [comment]
@dotnet-bot test this please

**Comment by pgavlin** [comment]
LGTM. Thanks for doing this.

**Pull request merged**
