### PR TITLE
CMake touchups

### PR DESCRIPTION
**Pull request by mathstuf**
---
Somewhat related to #50. Conflicts at least.

Other than these simple transformations, I see a few other things which should be addressed:

  - assumption that `WIN32` means Visual Studio:
    * in some places `CMAKE_CONFIGURATION_TYPES` should be used to detect multi-config generators;
    * `MSVC` should be used to detect the VS compiler;
  - detection of 64-bit should use `CMAKE_SIZEOF_VOID_P` rather than checking the CPU architecture name (though the architecture *should* be detected for arch-specific files elsewhere);
  - I don't think this is [CMP0054](http://www.cmake.org/cmake/help/v3.1/policy/CMP0054.html)-clean, so some things might need cleaning up there where variables expand to `MSVC` or the like (these are usually actual bugs);
  - `target_*` functions could likely be used to cut down on the number of `include_directories` and the like; and
  - the configuration stuff is odd (see #50).

### CODE REVIEW

**Comment by AlexGhiondea** [comment]
Thanks @mathstuf for this change. Would you mind updating the commit message to follow our guidelines described here https://github.com/dotnet/corefx/wiki/Contributing#commits ?

@rahku could you take a look?

**Comment by mathstuf** [comment]
@AlexGhiondea provided more info in the commit messages. Or do you mean something closer to "don't use a 'cmake:' prefix and make the summary a sentence"?

**Comment by AlexGhiondea** [comment]
@mathstuf Yes -- that is what I meant. Thank you!

**Comment by rahku** [comment]
@mathstuf can you modify your changes accordingly.

**Comment by mathstuf** [comment]
On Wed, Feb 04, 2015 at 13:53:19 -0800, Rahul Kumar wrote:
> @mathstuf can you modify your changes accordingly.

Yep, tomorrow if I don't get a chance tonight.

**Comment by mathstuf** [comment]
Branch rebased for conflicts and comments addressed.

**Comment by rahku** [comment]
LGTM

**Comment by jkotas** [comment]
LGTM

**Comment by jkotas** [comment]
@mathstuf Could you please rebase one more time for conflicts?

**Comment by mathstuf** [comment]
Looking into [the failure](http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_windows_debug_prtest/161/console), seems transient:

```
Slave went offline during the build
ERROR: Connection was broken: java.io.IOException: Connection aborted: org.jenkinsci.remoting.nio.NioChannelHub$MonoNioTransport@4f731cca[name=dci-win-fbld-9]
	at org.jenkinsci.remoting.nio.NioChannelHub$NioTransport.abort(NioChannelHub.java:211)
	at org.jenkinsci.remoting.nio.NioChannelHub.run(NioChannelHub.java:631)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
	at org.jenkinsci.remoting.nio.FifoBuffer$Pointer.receive(FifoBuffer.java:136)
	at org.jenkinsci.remoting.nio.FifoBuffer.receive(FifoBuffer.java:306)
	at org.jenkinsci.remoting.nio.NioChannelHub.run(NioChannelHub.java:564)
	... 6 more

Build step 'Execute Windows batch command' marked build as failure
FATAL: channel is already closed
hudson.remoting.ChannelClosedException: channel is already closed
	at hudson.remoting.Channel.send(Channel.java:549)
	at hudson.remoting.Request.call(Request.java:129)
	at hudson.remoting.Channel.call(Channel.java:751)
	at hudson.Launcher$RemoteLauncher.kill(Launcher.java:941)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:542)
	at hudson.model.Run.execute(Run.java:1718)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
Caused by: java.io.IOException: Connection aborted: org.jenkinsci.remoting.nio.NioChannelHub$MonoNioTransport@4f731cca[name=dci-win-fbld-9]
	at org.jenkinsci.remoting.nio.NioChannelHub$NioTransport.abort(NioChannelHub.java:211)
	at org.jenkinsci.remoting.nio.NioChannelHub.run(NioChannelHub.java:631)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
	at org.jenkinsci.remoting.nio.FifoBuffer$Pointer.receive(FifoBuffer.java:136)
	at org.jenkinsci.remoting.nio.FifoBuffer.receive(FifoBuffer.java:306)
	at org.jenkinsci.remoting.nio.NioChannelHub.run(NioChannelHub.java:564)
	... 6 more
```

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Pull request merged**
