### PR TITLE
Fixing tracelogging on linux

### PR DESCRIPTION
**Pull request by davmason**
The WriteEvent code path worked on non-windows platforms, but all of TraceLogging was broken. This fixes it so we can enable the EventSource tests on non-windows platforms.

### CODE REVIEW

**Comment by davmason** [comment]
@stephentoub This fixes EventSource tests so they can run on linux, so I also have to submit a PR to corefx than removes all of the attributes preventing the tests from running on non-windows platforms. Is there a way to synchronize the changes so the tests automatically enable when this change is picked up as a last known good by the corefx branch?

**Comment by stephentoub** [comment]
> Is there a way to synchronize the changes so the tests automatically enable when this change is picked up as a last known good by the corefx branch?

You'll want to wait to merge that change in corefx until this change has been checked in, is in the next day's packages, and corefx has been updated to use those packages.  You can submit the PR to corefx once this change has been merged and the main build (what's represented by the badges on the home page of the repo) has completed, as the PR legs in corefx pick up the last successful corresponding build from coreclr, but some of the other CI jobs pull coreclr from packages, and so we shouldn't merge that PR until updated coreclr packages are being consumed, or else those CI jobs will break.

**Comment by stephentoub** [comment]
LGTM
cc: @vancem

**Comment by stephentoub** [comment]
Test Windows_NT x64 Release Priority 1 Build and Test please
Test Windows_NT x86 Debug Legacy Backend Build and Test please
Test Windows_NT x86 Release Legacy Backend Build and Test please

**Comment by davmason** [comment]
Looks like there were some Jenkins issues this morning

Test Windows_NT x64 Release Priority 1 Build and Test please
Test Windows_NT x86 Debug Legacy Backend Build and Test please
Test Windows_NT x86 Release Legacy Backend Build and Test please

**Pull request merged**
