### PR TITLE
Run-xunit-perf: update TraceEvents version number

### PR DESCRIPTION
**Pull request by JosephTremoulet**
The perf harness needs 1.0.3-alpha-experimental now.

### CODE REVIEW

**Comment by JosephTremoulet** [comment]
@dotnet-bot test Windows_NT x64 perf

**Comment by JosephTremoulet** [comment]
@jorive thanks diagnosing the issue; the [perf job kicked off for this PR](https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_perflab_Windows_NT_x64_prtest/38/) has already gotten farther than [other recent ones](https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_perflab_Windows_NT_x64/)

**Comment by JosephTremoulet** [comment]
I did check and couldn't find any other references to the 1.0.0 version in the tree.

**Comment by adiaaida** [comment]
I have a change that will programmatically figure out which version of TraceEvents we have in the packages directory so we don't have to update this every time we update the version number, but for now, this LGTM

**Comment by jorive** [comment]
LGTM!

As a side note, I noticed this message on the run:
`Unable to create custom test framework discoverer type 'xunit.performance.execution.{Platform}, Microsoft.Xunit.Performance.BenchmarkTestFrameworkTypeDiscoverer'`.

It is not related to your changes, but it can be fixed by bumping the version of the xUnit Performance API (xunit.peformance.api, xunit.peformance.core, xunit.peformance.metrics, xunit.peformance.execution) to the latest (1.0.0-beta-build003).

**Comment by JosephTremoulet** [comment]
I think I'll defer updating the xunit.performance references since it can affect benchmark results and so should be done deliberately.

**Comment by jorive** [comment]
@JosephTremoulet Makes sense

**Comment by JosephTremoulet** [comment]
Test [failure](https://ci.dot.net/job/dotnet_coreclr/job/master/job/debug_windows_nt_prtest/5772/) looks like an unrelated timeout, so I'm going to go ahead and merge this to get benchmarking unstuck.

**Pull request merged**
