### PR TITLE
Fixing GUID_NULL.

### PR DESCRIPTION
**Pull request by rajkumar42**
Fixing GUID_NULL.

### CODE REVIEW

**Comment by rajkumar42** [comment]
@gregg-miskelly @mikem8361

**Comment by gregg-miskelly** [comment]
👍

**Comment by gregg-miskelly** [comment]
@janvorli we checked TFS history, and apparently this bogus definition of GUID_NULL comes from Rotor, but we didn't know how to go any further back. Obviously GUID_NULL should be fixed no mater what, but from history, can you see if anything else should be fixed along with this? (ex: something that might rely on the bogus definition)

**Comment by mikem8361** [comment]
LGTM modulo Gregg's comment.

**Comment by janvorli** [comment]
I really don't have historical knowledge here, @jkotas should know better.

**Comment by jkotas** [comment]
This looks like a simple copy&paste mistake. If there is something that took accidental dependency on it, we will find out eventually.

**Pull request merged**
