### PR TITLE
Inliner: enable inlining of methods with cpblk

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Allow jit to inline methods with the cpblk IL opcode. Add a test case
where such an inline happens.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
Desktop testing shows one diff in what looks like C++ CLI code.

@kyulee1 @geoffkizer PTAL
cc @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
Not sure why CI only kicked off 4 tests. Restarting....

@dotnet-bot retest this please

**Comment by kyulee1** [comment]
LGTM

**Comment by JosephTremoulet** [comment]
Looks like you didn't need to add any implementation, and this already worked?  Any idea why it was originally disabled?

**Comment by briansull** [comment]
For the original x86 JIT it can be a bad idea to inline cpblk operations into methods that previously didn't contain a cpblk operation.

The implementation of cpblk on x86 typically uses the movsd instruction and requires setting up of ESI and EDI which are two most important registers as they are two of the three caller saved registers.

Using this instruction would greatly pessimize the legacy JIT32 register allocations.

So it was probably put on the list of IL instructions that we didn't want to inline back them and has been carried forward until now.

**Comment by AndyAyersMS** [comment]
@JosephTremoulet I don't know why it was disabled -- there's no indication if the blocker is capability, legality, or profitability. Brian's explanation seems likely though.

**Pull request merged**
