### PR TITLE
Delete dead code from IdnMapping

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/corefx/issues/33269
cc: @tarekgh

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet/dnceng, is something wrong with CI / Jenkins?  This PR has had legs pending for 11 hours.  Same on other PRs.  And legs it has that have started running have been going for 10 hours, e.g. https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_ubuntu_innerloop_flow_prtest/6866/.

**Comment by mmitche** [comment]
@stephentoub Taking a look.  The helix agents aren't taking work

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by tarekgh** [comment]
Thanks @stephentoub

**Pull request merged**
