### PR TITLE
Disable node reuse

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@weshaggard PTAL

**Comment by mmitche** [comment]
@maririos What's the right way to do this?  Is there a document describing how this file is put together?

**Comment by maririos** [comment]
Not an updated document :( 
This changes just got in in [CoreFx](https://github.com/dotnet/corefx/commit/e62285793d285c546d8ef4121db849fe6e8d0506) and [Build Tools](https://github.com/dotnet/buildtools/commit/8d9fe4d23fc465f4c33ef81c94148bdd1e69f104).

It would be the same thing.
Make sure to the version of Build tools to use `1.0.26-prerelease-00719-02` and delete any calls from removed properties.

@Priya91 is there something else we need to take into account in order to make this change?

**Comment by weshaggard** [comment]
Assuming you have the right build tools then the change LGTM

**Comment by maririos** [comment]
The documentation of how the config.json file works is [here](https://github.com/dotnet/buildtools/blob/master/Documentation/RunCommand.md)

**Comment by maririos** [comment]
If you are deleting the Setting `` you should delete also all the calls we do to it like for example: https://github.com/dotnet/coreclr/pull/6868/files#diff-06b2d3b23dce96e1619d2b53d6c947ecR492

It looks like every command has it.

Also, we could do some clean up. We don't need the [maxcpucount](https://github.com/mmitche/coreclr/blob/8f0110976eb58cd036be540457f72d8d75cc66fd/config.json#L225) property anymore so we could delete it too

**Comment by mmitche** [comment]
@maririos What about the sequential build thing?  Is the sequential nature of the build for that setting handled internally?

**Comment by maririos** [comment]
It looks like before we were always passing it as a default value so it doesn't make sense having it anymore.

**Comment by maririos** [comment]
I'm not very familiar with this config.json file, but it LGTM.
@Priya91 could you please take a look to see if we are missing something?

**Comment by maririos** [comment]
Thanks for making these changes Matt

**Comment by Priya91** [comment]
LGTM, there was a sequential option before, but the builds were run with /m by default to improve CI performance.

**Pull request merged**
