### PR TITLE
 Fix the calling convention for P/Invokes and delegates to hostpolicy

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
When building the x86 in core-setup the default calling convention is defined to be `__cdecl` - since that is the default for Visual Studio projects. In the coreclr repo, the default calling convention for x86 is defined to be `__stdcall`. This has caused an issue between the API contracts for testing and has created a rather big mess. It isn't possible to change the calling convention for these APIs so we must accept them to be `__cdecl` and update the coreclr testing and product to match the API.

This issue was found when running an official SDK scenario on x86. This issue only impacts x86.

This is another issue that could have been caught with https://github.com/dotnet/core-setup/issues/5379.

cc @vitek-karas @jkoritzinsky @jeffschwMSFT

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
@dotnet-bot test Windows_NT x64 Release CoreFX Tests please

**Comment by vitek-karas** [comment]
Just curious - can you please check that the shipped versions of `hostfxr` and `hostpolicy` all use `__cdecl`. I don't like the discrepancy, but let's make sure we're not breaking across releases.

**Comment by AaronRobinsonMSFT** [comment]
I already verified `hostpolicy`, but I will check `hostfxr` just to be sure as well.

**Comment by vitek-karas** [comment]
If one day we have the `.h` files for these libraries, then it would go there (and into the API docs for those).
Right now we don't have a good place to put it.
Unless you feel like starting a doc in the repo with descriptions of the APIs... which we don't have either :-(

**Pull request merged**
