### PR TITLE
Fix two sos issues.

### PR DESCRIPTION
**Pull request by mikem8361**
ARM Disassemble problem and reenterency bug on Windows.

### CODE REVIEW

**Comment by mikem8361** [comment]
@bendono  and @benpye could you review the appropriate changes. Thanks.

**Comment by benpye** [comment]
Change in services.cpp LGTM.

**Comment by bendono** [comment]
@mikem8361 The g_Initialized flag looks good to me. I briefly tested it again and it workarounds the second call to DebugExtensionInitialize. Why such code is necessary is not quite apparent, so it might be best to add a short comment, something like:

// Workaround to prevent DebugExtensionInitialize from being called multiple times.
bool g_Initialized = false

Otherwise looks good to me. Thanks!

**Comment by mikem8361** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Pull request merged**
