### PR TITLE
Add -skipcrossarchnative option to build.cmd

### PR DESCRIPTION
**Pull request by BruceForstall**
This allows you to skip building the cross-architecture native components.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet-bot test this please

**Comment by echesakovMSFT** [comment]
@BruceForstall Sorry, missed this one in my email inbox. 

What is the original purpose of adding this? to workaround https://github.com/dotnet/coreclr/issues/22090?

**Comment by BruceForstall** [comment]
Partially to work around that non-incremental build. But mostly because I didn't need the cross components when iterating on JIT changes, so want my build to be faster.

**Comment by echesakovMSFT** [comment]
Makes sense to me. Do you mind adding similar opt-out mechanism for crossarch components to build.sh, so we will have consistency between cross builds?

**Comment by BruceForstall** [comment]
Added `-skipcrossarchnative` to build.sh

**Pull request merged**
