### PR TITLE
Start using dumpling service to upload dumps from CI runs

### PR DESCRIPTION
**Pull request by adityamandaleeka**
This is an initial step towards getting all the core dumps generated during CI runs uploaded to the dumpling service. It means that debugging crashes in CI runs will be a much better experience.

Since dumpling is still being developed and hasn't yet been tested for scale, we will start off by continuing to use the same rate-limiting mechanism we use today. We will also continue to save the core dump on the machine for now, until we have reasonable confidence in the reliability and stability of the service (I've been told by someone working on dumpling that things may be a bit unstable for a week or so while they work on improvements).

In the future, we should skip the local storage step entirely, and have a limit on the number of dumps that get uploaded per run, rather than per machine. One way to do this may be to create some unique ID that gets passed to each child shell, which they can use to find out how many other dumps were created in this run. We should also establish a different way to acquire the dumpling script.

For now, I'm also including the contents of the CoreCLR bin directory in the payload that gets uploaded. I've verified that I'm able to download a package from dumpling by ID, open the dump in GDB, load the symbols from the bin directory, and view a full stack and disassembly with symbols.

@schaabs @bryanar @wtgodbe PTAL

### CODE REVIEW

**Comment by wtgodbe** [comment]
LGTM

**Comment by bryanar** [comment]
Just out of curiosity, what is wrong with the way you are grabbing the dumpling script?

**Comment by adityamandaleeka** [comment]
@bryanar It's okay for now, but it would be nicer if it were somehow already on the machine so it's not pulled down all the time, and I'm not sure pulling the latest one from the master branch is a good long-term solution (if nothing else, it raises the bar for what goes into the dumpling master branch).

**Comment by bryanar** [comment]
I see, I see. This looks good to me too. Just note that the service is down a bit today while I am moving pieces around. I'll catch up with you when things are coming back.

**Comment by adityamandaleeka** [comment]
Sure, no worries. That's why we still have the dump on disk for now. Merging this PR.

**Pull request merged**
