### PR TITLE
[ARM32/Linux] Prepare rootfs to build libcoreclrtraceptprovider.so

### PR DESCRIPTION
**Pull request by hseok-oh**
Prepare rootfs to build libcoreclrtraceptprovider.so
by adding fix process of rootfs for ubuntu 14.04 armhf

### CODE REVIEW

**Comment by hseok-oh** [comment]
This commit does not include build `libcoreclrtraceptprovider.so` because of CI failure.
I'll make new commit when CI and rootfs in docker file are updated

related issue: #8684

cc/ @gkhanna79

**Comment by gkhanna79** [comment]
@hseok-oh Sounds like this patch will enable building libcoreclrtraceptprovider.so, right? If so, can you get this patch and fix in core-setup repo as well since we use that to generate the Docker Images with RootFS embedded?

CC @MichaelSimons

**Comment by hseok-oh** [comment]
@gkhanna79 I'll make PR in core-setup, too. Thanks.

**Comment by gkhanna79** [comment]
@hseok-oh I have merged the Core-Setup PR and will merge this as well. Do we need similar change for CoreFX?

**Comment by hseok-oh** [comment]
@gkhanna79 It does not seems need similar change in CoreFX.

**Comment by gkhanna79** [comment]
@hseok-oh My point was to ensure that RootFS is consistent for all cross builds. In that view, shouldn't we have this change in CoreFX and Core-Setup as well? do keep in mind that this change will be present in Docker images and thus, will get used for building CoreFX and Core-Setup as well.

Given that, are you fine with have it different for the repos?

**Comment by hseok-oh** [comment]
@gkhanna79 In that point of view, it may be better to apply this change in CoreFX to ensure RootFS consistancy in coreclr, corefx, and core-setup. 

I'll make new PR in CoreFX, too.

**Comment by gkhanna79** [comment]
Thank you @hseok-oh

**Pull request merged**
