### PR TITLE
Update CoreClr, CoreFx to beta-24625-03, beta-24625-02, respectively (master)

### PR DESCRIPTION
**Pull request by dagood**
Auto-update, plus updating `System.Runtime.Serialization.Primitives` to the current prerelease.

Replaces https://github.com/dotnet/coreclr/pull/7790 if the stable version of the package was causing the tests to fail.

### CODE REVIEW

**Comment by dagood** [comment]
@wtgodbe Does this help? I don't know what the Windows_NT x64 Formatting build is, but it looks like this fixes the tests.

**Comment by wtgodbe** [comment]
@dotnet-bot test Windows_NT x64 Formatting please

**Comment by wtgodbe** [comment]
Awesome, thanks @dagood! Safe to merge?

**Comment by dagood** [comment]
Looks good to me as far as the upgrades go, so since CI is green I'll go ahead and merge it.

/cc @gkhanna79

**Pull request merged**
