### PR TITLE
Replace install with _install in all superpmi CMakeLists.txt files

### PR DESCRIPTION
**Pull request by echesakovMSFT**
Currently, we don't build cross-architecture superpmi when running on Linux (as defined in crosscomponents.cmake), but we continue installing them in superpmi CMakeLists.txt files which causes CMake errors during build. For example, when running the following command: `build.sh arm checked cross crosscomponent`

This PR will replace `install` with `_install` in superpmi CMakeLists.txt files which install only if we are NOT building cross-architecture components (i.e., if we do native build)
 
@BruceForstall @dotnet/jit-contrib @janvorli PTAL

### CODE REVIEW

**Comment by 4creators** [comment]
Related issue #14596

**Comment by echesakovMSFT** [comment]
After discussion with @BruceForstall we agreed that we don't need superpmi as crosscomponents at all. @dotnet/jit-contrib any other thoughts?

**Comment by echesakovMSFT** [comment]
@dotnet-bot test CentOS7.1 x64 Checked Innerloop Build and Test
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test
@dotnet-bot test Windows_NT x64 Checked Innerloop Build and Test

**Comment by echesakovMSFT** [comment]
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test please

**Pull request merged**
