### PR TITLE
Update arm64 tests used by the CI

### PR DESCRIPTION
**Pull request by jashook**
Title says everything.

### CODE REVIEW

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT arm64 Release

**Comment by jashook** [comment]
@adiaaida ptal
/cc @RussKeldorph @dotnet/arm64-contrib

**Comment by adiaaida** [comment]
LGTM

**Pull request merged**
