### PR TITLE
Add Arm64 Ubuntu jobs

### PR DESCRIPTION
**Pull request by jashook**
This will use the arm64_ubuntu label.

This re-defines the arm64 job create a non-pr trigger arm64 job which builds and runs the pal tests. Note this is not complete and kept simple to test.

### CODE REVIEW

**Comment by jashook** [comment]
@dotnet test CI Please

**Comment by jashook** [comment]
@dotnet test CI Please

**Comment by jashook** [comment]
@dotnet test CI Please

**Comment by jashook** [comment]
@dotnet test CI Please

**Comment by jashook** [comment]
@dotnet test CI Please

**Comment by jashook** [comment]
@dotnet-bot test CI Please

**Comment by jashook** [comment]
@dotnet-bot test CI Please

**Comment by jashook** [comment]
@dotnet-bot test CI Please

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Pull request merged**
