### PR TITLE
Add vector Conversion/Narrow/Widen tests

### PR DESCRIPTION
**Pull request by helloguo**
This PR adds tests for vector Conversion, Narrow and Widen. It is built on https://github.com/dotnet/coreclr/pull/9318 and https://github.com/dotnet/coreclr/pull/9920.

### CODE REVIEW

**Comment by helloguo** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by danmosemsft** [comment]
@dotnet-bot test OSX x64 Checked Build and Test (Sierra update)

**Comment by danmosemsft** [comment]
Reset OSX runs

**Comment by helloguo** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please
@dotnet-bot test OSX10.12 x64 Checked Build and Test please

**Comment by helloguo** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by helloguo** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by helloguo** [comment]
@BruceForstall Can you take a look at this? It seems OSX x64 Checked Build and Test is disabled.

**Comment by BruceForstall** [comment]
@mmitche Do you know why the OSX runs are working? I see:
```
22:51:13 ERROR: Unable to find project for artifact copy: dotnet_corefx/master/osx_release
22:51:13 This may be due to incorrect project name or permission settings; see help for project name in job configuration.
```

**Comment by helloguo** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by mmitche** [comment]
@BruceForstall Ignore the OSX one..  The OSX10.12 is the only interesting one.  The OSX one is deprecated and will only appear on old PRs

**Comment by helloguo** [comment]
@BruceForstall should I resubmit the PR?

**Comment by BruceForstall** [comment]
@helloguo That might be best. Thanks.

**Pull request closed without merging**
