### PR TITLE
Add option to skip test build in build.cmd

### PR DESCRIPTION
**Pull request by mmitche**
Not added to build.sh since it doesn't build the tests yet.

### CODE REVIEW

**Comment by mmitche** [comment]
@jasonwilliams200OK Added skiptestbuild to build.cmd #1240

**Comment by jasonwilliams200OK** [comment]
@mmitche, thank you! Would be really nice to have a note in Windows documentation as well. :)

Copy @AtsushiKan.

Also copy @akoeplinger and @stephentoub as the participant of related conversation in CoreFX: https://github.com/dotnet/corefx/issues/2357.

I think the same solution can be provided for CoreFX.

```bash
build.cmd skiptestbuild
```

**Comment by AtsushiKan** [comment]
Seconding request to include a note in the documentation. Otherwise, LGTM.

**Comment by mmitche** [comment]
@jasonwilliams200OK I'll take a look at it.  It looks like build /? is broken anyway (appears to be printing the help for FOR)

**Comment by mmitche** [comment]
Updated

**Comment by AtsushiKan** [comment]
Update LGTM.

**Pull request merged**
