### PR TITLE
Add CoreCLR and CoreFX bug bar to Documentation/project-docs/

### PR DESCRIPTION
**Pull request by leecow**
Bug bar definitions used by the CoreFX and CoreCLR teams in the latter stages of a release.

### CODE REVIEW

**Comment by joshfree** [comment]
@blackdwarf can you take a look?

**Comment by joshfree** [comment]
file contents look OK to me.  Only concern is whether this should actually go in /dotnet/coreclr or some other general location for all repos(/dotnet/coreclr, /dotnet/corefx, /dotnet/wcf, /dotnet/cli, /dotnet/Roslyn, etc) to reference.

**Comment by blackdwarf** [comment]
Looks good to me. 

@joshfree maybe we put this in dotnet/core and link from READMEs?

**Comment by joshfree** [comment]
@blackdwarf that seems reasonable to me; @leecow any concerns?

**Comment by leecow** [comment]
@joshfree @blackdwarf /core with README links sounds good.

**Comment by joshfree** [comment]
ok.  I'll close this PR out then;

**Pull request closed without merging**
