### PR TITLE
Do not devirtualize indirect calls

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Not sure if this is the right fix but it makes my problem go away.

I'm seeing the affected code take the `impDevirtualizeCall` code path
with CT_INDIRECT calls. `gtCallMethHnd` is a `GenTreePtr` in that case
(it's a union) and passing that as as `CORINFO_METHOD_HANDLE` leads
to bad things.

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
JitDump for the method that was failing for me (up to the point when bad things happened): [devirt-fail.txt](https://github.com/dotnet/coreclr/files/1247409/devirt-fail.txt)

@AndyAyersMS PTAL

**Comment by AndyAyersMS** [comment]
The fix looks good.  Can you add a test case?

**Comment by MichalStrehovsky** [comment]
I've added a regression test, but couldn't make this repro with CoreCLR - it only reproes with the CoreRT compiler. We do run CoreCLR regression tests in CoreRT though.

**Comment by MichalStrehovsky** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Comment by AndyAyersMS** [comment]
The fact that this repros only on CoreRT is actually good news... thanks for the test.

**Pull request merged**
