### PR TITLE
Fix arm64 build issue #7355.

### PR DESCRIPTION
**Pull request by mikem8361**
@jkotas @rahku review?

### CODE REVIEW

**Comment by jkotas** [comment]
LGTM

**Comment by rahku** [comment]
@dotnet-bot test WIndows_NT arm64 Checked

**Comment by mikem8361** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test please

**Comment by mikem8361** [comment]
@rahku I don't think the above ARM64 build failure is related to my change.

**Comment by rahku** [comment]
Yes that's not related and don't see crossgen failure any more...you should be good to merge.

**Pull request merged**
