### PR TITLE
Fix unwinding past main on OSX

### LINKED ISSUE #510: Fix unwinding out of Main on OSX
See PR https://github.com/dotnet/coreclr/pull/509 for some background.

The PR itself isn't correct, since unw_step will return 0 in two cases:

1. When it unwinds all the way past main().
2. When it unwinds to a managed frame, since it doesn't know what to do.

The PR as is, will break #2, so we need to come up with a plan to differentiate #1 and #2, so that we can bail out and dump the unhanded exception for #1.

It seems the Rip == 0 is llvm libunwind specific, OS X leave the $pc unchanged, so one possibility would be to track the previous pc and cur pc, and enter the guard if they matched.

### PR DESCRIPTION
**Pull request by kangaroo**
When reaching the bottom of the real stack, OSX does not change the $pc
to 0x0, like llvm libunwind.  It returns 0 from unw_step, and leaves the
$pc unchanged, so we will track cur and prev pc and guard for this as well
Fixes Localloc codegen test, and also verified a simple throw from main
works as expected.

Fixes #510

### CODE REVIEW

**Comment by sergiy-k** [comment]
@kangaroo Nice finding! I wonder if this logic is platform specific enough that we should consider moving it into PAL under platform specific ifdefs and change PAL_VirtualUnwind to return a status code instead of a boolean so we don't have to derive the current state in VirtualUnwindToFirstManagedCallFrame based on the ControlPc value? What do you think?

**Comment by janvorli** [comment]
@kangaroo I would also prefer doing that in PAL. We can either change the PAL_VirtualUnwind to return status as Sergiy has suggested or, detecting that the PC has not changed over the unw_step call and zero the PC in the context in that case. It seems to me that the latter would be reasonable.
You've also said in #510 that we cannot differentiate between walking out of stack and walking to a managed frame. Are you sure about that? Since when we step out of the last native frame, the unwinder still has all the information to do so, it just cannot move further. And if it didn't work, I don't see how the current exception handling could work, since the first step is to move to the first managed frame by walking out of the native ones.

**Comment by kangaroo** [comment]
@janvorli Sorry I meant we cannot detect it on the result code of unw_step alone.

@sergiy-k I think a status flag could work possibly be a little cleaner -- I'll try it out tonight.

**Comment by kangaroo** [comment]
Implemented it by coercing the $pc to 0x0 in the degenerate case as suggested by @janvorli.  It turned out to be code cleaner than the flag, since it will return 0 from unw_step when it steps beyond the bottom, and into a managed frame, so we need to track $pc regardless.

The code isn't 32-bit safe.  I don't personally have any plan on doing bring up on OS X 32-bit, and would rather actually just remove all the 32-bit code, but thats a separate discussion.

**Comment by janvorli** [comment]
LGTM modulo the nits in the comments

**Comment by kangaroo** [comment]
Fixed comment nits, squashed and pushed.

**Comment by jkotas** [comment]
Thanks!

**Pull request merged**
