### PR TITLE
Add back some surface area to thinned corelib

### PR DESCRIPTION
**Pull request by ellismg**
We are working on expsosing some existing exception types from
System.Runtime in CoreFX. The implementations will facade over
System.Private.CoreLib, but we need to make sure all the members we expect
to expose from the contract are present in the implementation assembly.

Expose the missing members for ExecutionEngineException,
NotFiniteNumberException and ExternalException.

### CODE REVIEW

**Comment by ellismg** [comment]
/cc @stephentoub @Lixire 

Steve, once this is good to go, I will merge it and #6205 and then deal with the asmmeta fallout in TFS once the changes are mirrored over.

This is needed to unblock @Lixire adding back this stuff to CoreFX (and then we need to get a new targeting pack built which is not currently happening per build but we can fix).  She's been working around the issue for now by suppressing the validation failures.

**Comment by stephentoub** [comment]
Thanks, Matt. LGTM.

**Comment by danmosemsft** [comment]
Matt #6230 also modified model.xml recently. I was assuming that corefx would see the changes tomorrow. It sounds like this isn't, in fact, happening nightly?

**Comment by stephentoub** [comment]
> It sounds like this isn't, in fact, happening nightly? 

Have you seen those "Updating CoreClr dependencies to beta-*" PRs from dotnet-bot?  Those are what update corefx to pull in the latest coreclr.  You'll also notice none of them have been merged in the last two weeks.  They're all failing due to https://github.com/dotnet/corefx/issues/10014.  Once that's fixed, we should be able to merge them, at which point we should be pulling in the latest CoreCLR at least once a day.

**Pull request merged**
