### PR TITLE
Fix line endings

### PR DESCRIPTION
**Pull request by sdmaclea**
#17505 Introduced corrupt line endings.  This fixes them.

@jkotas @luqunl

### CODE REVIEW

**Comment by sdmaclea** [comment]
It has crlf in git.  

When checked out on linux, git is automatically fixing the line endings, but it leaves the tree in a dirty state.  Git diff on a clean checkout on linux shows this file as completely rewritten.  git commit --all, leeads to exactly this commit

.gitattribute change might help, but I haven't figured out what it should be changed to.  @CarolEidt and I went through this a few months ago.

Usually a crlf file committed from windows is automatically converted to lf in git.  Sometimes things are messed up.  A file authored on Windows is copied to Linux and checked in...

**Comment by jkotas** [comment]
> Sometimes things are messed up

I assume that this was introduce while fixing https://github.com/dotnet/coreclr/pull/17505#issuecomment-381309884

I do not think there is a way to prevent the operator error that led to this via .gitattribute.

**Comment by kasper3** [comment]
@jkotas, adding `*.cs text eol=lf` would do the trick. I don't think fixing UTF16LE conversion has any affect on CRLF. It is more likely what @sdmaclea said "A file authored on Windows is copied to Linux and checked in..." which can be enforced by .gitattribute for all git clients agnostic of OS/environment.

**Comment by jkotas** [comment]
> adding `*.cs text eol=lf`

Would that kick in on both Windows and Unix? I do not think we want to have C# files checked out with lf line endings on Windows.

**Comment by luqunl** [comment]
Thanks!

**Pull request merged**
