### PR TITLE
[ARM/CI] Fix ARM32 CI scripts - managed & native directory changed

### PR DESCRIPTION
**Pull request by hseok-oh**
The name of CoreFX Native & Managed build directories have changed.

### CODE REVIEW

**Comment by hseok-oh** [comment]
These changes must be merged after dotnet/corefx#15311 landed.
reference: #9002

**Comment by hqueue** [comment]
Thank  you ! I was also faced same trouble using runtest.sh to perform whole unit test on Linux ARM32.

**Comment by hseok-oh** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by hseok-oh** [comment]
runtest.sh fixed. And ARM32 CI uses runtest.sh in emulator image.

**Pull request closed without merging**
