### PR TITLE
[Arm64] Mark removed compare zero nodes unused

### LINKED ISSUE #16176: [Arm64] Lower Unsigned Vector Compare LT/GE Zero discards side effects
Side effects of vector `a` are discarded when `T` is unsigned

`Intrinsics.Arm.Arm64.Simd.CompareLessThanZero<Vector*<T>(a);`
`Intrinsics.Arm.Arm64.Simd.CompareGreaterThanOrEqualZero<Vector*<T>(a);`

Per @CarolEidt this is generally something we want to avoid.

In this case these are forms which should not be used.  They are non-sensical returning always `false` or `true` respectively.  An analyzer module is recommended to detect these useless forms.

Lowering is replacing these with a const vector.  Removing the tree `a`.

If `a` has side effects lowering could be changed to either 
+ actually do a compare against an const zero vector (slower)
+ add a comma operator to maintain the side effect.

### PR DESCRIPTION
**Pull request by sdmaclea**
@CarolEidt PTAL

Based on my interpretation of your comments in #16176 

I only see `markOperandsUnused` being set when `(gtFlags & GTF_ALL_EFFECT) == 0`

Fixes #16176

### CODE REVIEW

**Comment by sdmaclea** [comment]
test Tizen armel Cross Checked Innerloop Build and Test

**Comment by sdmaclea** [comment]
@CarolEidt All tests passed (Tizen armel passed, but did not upate above).  PTAL

**Comment by CarolEidt** [comment]
I'm still uncertain as to why the side-effects check is required. `LIR::Range::Remove()` will always remove the node (whether or not it is marked as having side-effects. All the parameter does is determine whether the *operands* of the node being deleted will be marked as unused, which is needed because the caller may be reusing those operands. The only side-effects issue would be caused by `node` itself having side-effects, and then it would be a problem whether or not the operands are being marked unused. In this case, the operands of `origOp1`, if any, are not being reused, so I think the right answer is to always pass `true`.

**Comment by sdmaclea** [comment]
@CarolEidt This was the example use case I found:
https://github.com/dotnet/coreclr/blob/8dde886767682feac4b5414366dfae7be3c08412/src/jit/decomposelongs.cpp#L1169-L1176

Since you had said we do not have a eliminate side effects issue, I did not do the whole thing.  However you latest comment leads me to believe this is actually what should be done.  But you do not seem to be saying exactly that.

**Comment by sdmaclea** [comment]
> I'm still uncertain as to why the side-effects check is required

So if we have `CompareLessThanZero(LoadVector128(ptr))`  We need to throw an exception if the LoadVector128 would have thrown.

**Comment by CarolEidt** [comment]
> So if we have CompareLessThanZero(LoadVector128(ptr)) We need to throw an exception if the LoadVector128 would have thrown.

I don't think this fix will accomplish that. It will still remove the `LoadVector128` from the execution stream, and if that node would have caused an exception, that exception won't happen. If there's a concern about whether `origOp1` can cause a side-effect, then I think you need to check for that *before* calling `LIR::Range::Remove()` - you can either do the simple check for `GTF_SIDE_EFFECT` on that node and conservatively just keep it (and mark it as unused), *or* then check `gtNodeHasSideEffects(origOp1,GTF_SIDE_EFFECT)` to see if the node itself has side-effects (or if it's just due to its children, in which case you can remove the node with `markOperandsUnused` set to true.

Do you have a test case that was failing, and that passes with this fix?

**Comment by sdmaclea** [comment]
> I don't think this fix will accomplish that

Agreed 

> Do you have a test case that was failing, and that passes with this fix?

No nothing is failing.  This was based purely on comment on lowering in x86 HW intrinsic work. 
 
LoadVector128 is not yet implemented either.  So this hypothetical example does not yet exist.

**Comment by CarolEidt** [comment]
@sdmaclea - thanks for the clarification. I think the right fix is:
```
if ((origOp1->gtFlags & GTF_ALL_EFFECT) == 0)
{
    BlockRange().Remove(origOp1, true);
}
else
{
    origOp1->SetUnusedValue();
}
```
This will conservatively leave an unused `origOp1` even if its children are the source of the side-effect, but it's a cheaper check than calling `gtNodeHasSideEffects(origOp1,GTF_SIDE_EFFECT)` and I think it will be somewhat rare that `origOp1` has side effects at all, and even more rare that those side effects are due to children, rather than `origOp1` itself.

**Comment by sdmaclea** [comment]
@CarolEidt done

**Comment by sdmaclea** [comment]
Can this be merged?

**Pull request merged**
