### PR TITLE
[Linux][GDB-JIT] Remove (nothrow) when using new

### PR DESCRIPTION
**Pull request by ayuckhulk**
This PR removes usage of (nothrow) in gdbjit by refactoring memory management code in gdbjit.

Summary:

* Code hardening against oom exceptions: always use a holder as receiver of `new` operator and every object that owns a pointer to another objects manages it using a holder. So most `delete` operators are gone. The only remaining are in allocators/traits and in code related to `__jit_debug_register_code` function.

* Fix some memory leak/double free issues.

* Wrap NotifyGdb::MethodCompiled entry point in EX_TRY/EX_CATCH.

* Remove CalledMethod list cleanup - avoid having dangling pointer in CodeHeader class.

* Simplify of `GetTypeInfoFromTypeHandle` function: most type creation code moved into type constructors.

Related issue: #10033 

@mikem8361, @janvorli PTAL

cc @Dmitri-Botcharnikov @chunseoklee @seanshpark @lucenticus @kvochko

### CODE REVIEW

**Comment by ayuckhulk** [comment]
@dotnet-bot test Tizen armel Cross Debug Build please
@dotnet-bot test Windows_NT x64 Debug Build and Test please

**Comment by ayuckhulk** [comment]
@janvorli Thank you for the review!

**Comment by ayuckhulk** [comment]
@janvorli  I this PR ready to be merged?

**Comment by janvorli** [comment]
@ayuckhulk sure, it is. I just wish github could notify me when all tests pass or if I could tell it to merge after the tests pass. This happened to me multiple times before - the test are still running when I review and the next day I forget about it.

**Pull request merged**
