### PR TITLE
Fix PIE options

### PR DESCRIPTION
**Pull request by janvorli**
We were missing passing the -pie linker option. That means that while we
were compiling our code as position independent, the executables
(not shared libraries) were not marked as position independent and
ASLR was not applied to them. They were always loaded to fixed addresses.

This change adds the missing -pie option and also replaces all the individual
settings of -fPIE / -fPIC on the targets we build by a centralized setting
of CMAKE_POSITION_INDEPENDENT_CODE variable that causes cmake to add the
appropriate compiler options everywhere.

### CODE REVIEW

**Comment by janvorli** [comment]
cc: @jkotas

**Comment by janvorli** [comment]
Hmm, building the native parts of coreclr tests fail, I'm taking a look:
```
/usr/bin/ld: ../../Common/Platform/libplatformdefines.a(platformdefines.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
```

**Comment by jkoritzinsky** [comment]
The native test build doesn't use the root `CMakeLists.txt` maybe we want to move the `set(CMAKE_POSITION_INDEPENDENT_CODE 1)` statement into the start of `configurecompiler.cmake`?

**Comment by janvorli** [comment]
Ah, I've though it does use it, as it conditionally includes the tests folder. That explains the problem then. @jkoritzinsky your suggestion makes sense, I'll move it there.

**Pull request merged**
