### PR TITLE
ARM64: Running cmd instead of exe

### PR DESCRIPTION
**Pull request by kyulee1**
Our test framework (smarty) directly runs test executable on corerun.exe.
But some of tests expect arguments via environment variable specified in .cmd.
The fix is to change the test list file to run .cmd. So the expected pass
value is also updated to 0 instead of 100. Now we don't need to pass /host
that specifies corerun.exe.
3 additional tests are now passed:
InterlockedAddLongWithSubtract/CompareExchangeTString/Polyrec

### CODE REVIEW

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64

**Comment by kyulee1** [comment]
@dotnet/jit-contrib PTAL

**Comment by jashook** [comment]
Have we verified that the cmd files exit 100 if they pass?

**Comment by BruceForstall** [comment]
Seems very odd that you'd want to change the "pass" convention from 100 to 0

**Comment by kyulee1** [comment]
cmd file exits 0 if they pass, which I reflected in this change (Tests.lst). The convention that returns 100 for pass from executable is same as before.

**Comment by jashook** [comment]
LGTM

**Comment by kyulee1** [comment]
I need to update lab script that runs without /host and with /noecid. Will test it again after that.

**Comment by briansull** [comment]
LGTM, 
FYI I checked in a modification to Tests.Lst

**Pull request merged**
