### PR TITLE
Up the timeout for gcstress arm64 jobs.

### PR DESCRIPTION
**Pull request by jashook**

### CODE REVIEW

**Comment by jashook** [comment]
@dotnet-bot test CI Please

**Comment by jashook** [comment]
@dotnet-bot test CI Please

**Comment by mmitche** [comment]
@jashook Because you have a minus sign (-) at the start of line 2030.  It think you're attempting to negate the function call.

**Comment by jashook** [comment]
I see thanks

**Comment by jashook** [comment]
@dotnet-bot test CI Please

**Comment by jashook** [comment]
@mmitche @adiaaida ptal

**Comment by adiaaida** [comment]
LGTM

**Pull request merged**
