### PR TITLE
Only run Debug and Release WinArm32 PR Builds

### PR DESCRIPTION
**Pull request by gkhanna79**

### CODE REVIEW

**Comment by gkhanna79** [comment]
@dotnet test ci please

**Comment by gkhanna79** [comment]
@dotnet-bot skip ci please

**Comment by gkhanna79** [comment]
@mmitche Can you PTAL?

**Comment by gkhanna79** [comment]
@dotnet-bot test ci please

**Comment by gkhanna79** [comment]
@mmitche I have confirmed in the CI generated job list (in https://ci.dot.net/job/dotnet_coreclr/job/master/job/GenPRTest/job/generator_prtest/18/) that we only generate Debug and Release jobs for WinArm32.

PTAL at the change.

**Comment by mmitche** [comment]
LGTM

**Comment by gkhanna79** [comment]
Merging since this is a change in netciy.groovy for WinArm32 builds and that is confirmed to do what is intended.

**Pull request merged**
