### PR TITLE
Linux/ARM: Support -O3 optimization level in release build mode

### PR DESCRIPTION
**Pull request by leemgs**
Currently, we can build coreclr with -O1 flag of clang in release build mode for Linux/ARM. This instruction is to enable -O3 optimization level of clang on ARM/Linux by fixing the bug of llvm.

Signed-off-by: Geunsik Lim <geunsik.lim@samsung.com>

### CODE REVIEW

**Comment by leemgs** [comment]
\CC: @myungjoo , @benpye , @jkotas , @janvorli , @lemmaa 

This PR is done as a next step of the existing PR https://github.com/dotnet/coreclr/pull/4904.

**Comment by leemgs** [comment]
Here is clan-3.6.2/llvm-3.6.2 binary(patched) for Ubuntu 14.04 LTS X64 PC. 
https://dncorerepo.blob.core.windows.net/armemulator/%5Bubuntu14.04.x64%5Dllvm-3.6.2.20160527.tls.fixed.binary.tar.bz

We have evaluated the effect of the llvm bugfix with the above binary. 

* Before the PR: (with -O2, -O3, -Os, and -Ofast) 
```
arm-emul@u1404> ./corerun ../hello.exe
Segmentation fault (core dumped)
```


* After the PR: (with -O2, -O3, -Os, and -Ofast) 
```
arm-emul@u1404> ./corerun ../hello.exe
Hello World

```

**Comment by myungjoo** [comment]
Tested-by: MyungJoo Ham

Tested on:
https://github.com/myungjoo/coreclr/tree/work/release based on 98568fb845ccaa97e18433ac13741913d6c8ffec

`Linux localhost 3.10.65-00001-g3e64e27-dirty armv7l GNU/Linux`

**Comment by jkotas** [comment]
Great work!

**Pull request merged**
