### PR TITLE
Arm64: Take more bounds checks into consideration when inlining immediates

### LINKED ISSUE #24711: [ARM64/Linux] Range checks against constants contain unneeded moves
It seems like the sequence for doing range checks was optimized for the variable case. when the index is a constant the comparison generates suboptimal code (with `QuickJIT` off).

```
static int[] Test(int[] a, int n)
{
  a[2] = n;
  return a;
}
```
generates
```
        52800041          mov     w1, #2
        B9800803          ldrsw   x3, [x0,#8]
        6B03003F          cmp     w1, w3
        54000082          bhs     G_M32566_IG04
        B9001802          str     w2, [x0,#24]
```

while flipping the branch condition would have gotten

```
        B9800803          ldrsw   x3, [x0,#8]
        6B03003F          cmp     w3, #2
        54000082          bls     G_M32566_IG04
        B9001802          str     w2, [x0,#24]
```

saving the need for a move and register usage.

/CC @CarolEidt @tannergooding

### PR DESCRIPTION
**Pull request by TamarChristinaArm**
This add `GT_ARR_BOUNDS_CHECK` to the list of operations that `IsContainableImmed` should consider in-lining the immediate for in the `cmp`.

changes

```
        52800041          mov     w1, #2
        B9800803          ldrsw   x3, [x0,#8]
        6B03003F          cmp     w1, w3
        54000082          bhs     G_M32566_IG04
        B9001802          str     w2, [x0,#24]
```

into 

```
        B9800803          ldrsw   x3, [x0,#8]
        6B03003F          cmp     w3, #2
        54000082          bls     G_M32566_IG04
        B9001802          str     w2, [x0,#24]
```

Fixes #24711

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib

**Comment by mikedn** [comment]
Hmm, not sure what's the status of SIMD & HWIntrinsic on ARM64. If they're a thing it might make sense to add `GT_SIMD_CHK` and `GT_HW_INTRINSIC_CHK` as well.

**Comment by TamarChristinaArm** [comment]
I'm currently expanding the list of HWintrinsics on ARM64,it was as part of that that I noticed this. I assume those two are related to the `IsSupported` checks?

**Comment by CarolEidt** [comment]
> I assume those two are related to the IsSupported checks?

No, they are used to generate the equivalent of array bounds checks when accessing elements of hardware or SIMD vectors.

**Comment by CarolEidt** [comment]
... and I agree with @mikedn that those two could be added to this case (thanks @mikeden for spotting this!)

**Comment by TamarChristinaArm** [comment]
> No, they are used to generate the equivalent of array bounds checks when accessing elements of hardware or SIMD vectors.

Ahh, fair enough.

**Pull request merged**
