### PR TITLE
Fix CI test error: permission error

### PR DESCRIPTION
**Pull request by hseok-oh**
Fix CoreCLR/CoreFX copy order: permission problem

### CODE REVIEW

**Comment by hseok-oh** [comment]
@dotnet-bot test ci

**Comment by hseok-oh** [comment]
@gkhanna79 PTAL

**Comment by pgavlin** [comment]
LGTM. Any idea why this is suddenly necessary? What changed?

cc @adityamandaleeka @janvorli

**Comment by janvorli** [comment]
@pgavlin my guess is that the issue is rather at the other side where we tar the files.

**Comment by pgavlin** [comment]
> my guess is that the issue is rather at the other side where we tar the files.

Yeah, that was my hypothesis as well. Is that scripting in netci.groovy?

**Comment by janvorli** [comment]
I am not sure. There is some tar-ing in the corefx netci.groovy, but those lines haven't changed recently.
@mmitche do you know where the problematic package is being tar-ed?

**Comment by BruceForstall** [comment]
@hseok-oh It looks like this change causes tizen jobs to fail. See

https://ci.dot.net/job/dotnet_coreclr/job/master/job/armel_cross_debug_tizen_prtest/939/console

from log:
```
10:51:32 + chmod a+x ./bin/CoreFxBinDir/corerun
10:51:32 chmod: cannot access ‘./bin/CoreFxBinDir/corerun’: No such file or directory
```

**Comment by pgavlin** [comment]
@BruceForstall do you think we should roll this back for now (i.e. is having the tizen jobs clean a higher priority than having the OSX/Ubuntu jobs clean)?

**Comment by BruceForstall** [comment]
@pgavlin Not sure, because the Ubuntu ARM jobs now seem to be working, where they weren't before, and they do have this code.

**Pull request merged**
