### PR TITLE
Fix more save/restore code for HVAs

### PR DESCRIPTION
**Pull request by CarolEidt**

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dnceng - there seem to be a number of instances of:
```
DownloadError: Unable to download https://helixexternaldrops.blob.core.windows.net/helix-job-43974c42-f67c-4bcf-b1fd-8882894d3720e2e9661c3354b95b9/c8155c91-9708-48cc-852c-eef95158913d.zip after retrying. Execution may fail as a result.
```
and not just on my jobs. Is this a known issue?

**Comment by BruceForstall** [comment]
@dotnet/dnceng 

I've seen the same thing.

**Comment by MattGal** [comment]
@BruceForstall , @CarolEidt , from the logs:

```
Traceback (most recent call last):
  File "/usr/local/bin/helix/scripts/helix/executor.py", line 194, in _download_and_unpack
    self._unpack(partial_file_path, contents_root, is_workitem_payload)
  File "/usr/local/bin/helix/scripts/helix/executor.py", line 243, in _unpack
    unzipped_file_paths = self._get_unpacked_file_paths(file_path, contents_root)
  File "/usr/local/bin/helix/scripts/helix/executor.py", line 452, in _get_unpacked_file_paths
    with zipfile.ZipFile(file_path) as zfile:
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
```
... I'll take a peek.

**Comment by MattGal** [comment]
@JpratherMS / @ilyas1974 I wasn't able to reproduce the problems folks are reporting for these but @ulisesh and I noticed a pattern of very slow network performance from machines in the lab.  Can either of you check that out?

**Comment by BruceForstall** [comment]
@MattGal I opened https://github.com/dotnet/core-eng/issues/6266

**Comment by CarolEidt** [comment]
Is there any point in retrying these failing jobs? My experience has been that they simply fail again in the same way. Guidance would be useful.

**Comment by MattGal** [comment]
@CarolEidt probably not;  until the network lab issue is understood I'd expect these machines will continue to have downloading problems, thus far the DDFUN folks have been trying things without luck.

**Comment by CarolEidt** [comment]
In two runs of the Linux arm64 tests, there were infra/time-out failures, but they were disjoint. Plus the new test GitHub_24159 fails, but that and its fix were merged after this.

**Comment by CarolEidt** [comment]
Fixes #24224

**Pull request merged**
