### PR TITLE
Remove redundant symbols disabled in CoreCLR

### PR DESCRIPTION
**Pull request by danmosemsft**
Contributes to https://github.com/dotnet/coreclr/issues/8857

### CODE REVIEW

**Comment by danmosemsft** [comment]
@jkotas can you have a quick look?

**Comment by danmosemsft** [comment]
As far as further cleanup (on the managed side) there are a lot of symbols that are in clrdefines.targets that do not appear in the code. (https://gist.github.com/danmosemsft/81b28745c0886e81e307d8339a21c286)

It wouldn't be hard to remove those from the props/targets, but it's just clutter in those, not in the code.

**Comment by danmosemsft** [comment]
Verified that linux debug and windows x64 debug disassembly is unaffected by above changes.

**Comment by danmosemsft** [comment]
@tarekgh could you okay this commit: https://github.com/dotnet/coreclr/pull/9058/commits/4c81ba582c4e9a9128c917ccb25ecac19824b1f9 (it removes only dead code)

**Comment by jkotas** [comment]
@danmosemsft Looks great! Thanks

**Comment by tarekgh** [comment]
@danmosemsft 

we may need to do more clean up as I am seeing FEATURE_CODEPAGES_FILE used in the following files 

```
src\classlibnative\inc\nlsinfo.h:#if FEATURE_CODEPAGES_FILE
src\classlibnative\inc\nlsinfo.h:#endif // FEATURE_CODEPAGES_FILE
src\classlibnative\nls\nlsinfo.cpp:#if FEATURE_CODEPAGES_FILE
src\classlibnative\nls\nlsinfo.cpp:#endif // FEATURE_CODEPAGES_FILE
src\classlibnative\nls\nlstable.cpp:#if FEATURE_CODEPAGES_FILE
```

**Comment by danmosemsft** [comment]
Yep for sure, I opened https://github.com/dotnet/coreclr/issues/9067 to do the native side. I"ll take a look when I have time but since that code isn't going to sync with CoreRT it's no hurry. Thanks

**Comment by tarekgh** [comment]
@danmosemsft thanks for the clean up. this really nice to see it.

**Pull request merged**
