### PR TITLE
Clarify register aliasing in the X86 encoder.

### PR DESCRIPTION
**Pull request by pgavlin**
Certain registers are aliased with control bits in the ModRM byte
of an X86 instruction. Encapsulate the checks that accommodate this
aliasing into a pair of functions.

### CODE REVIEW

**Comment by pgavlin** [comment]
@dotnet/jit-contrib @BruceForstall @briansull @CarolEidt PTAL

**Comment by briansull** [comment]
Nice improvement in readability

LGTM

**Comment by CarolEidt** [comment]
LGTM

**Comment by pgavlin** [comment]
@dotnet-bot test this please

**Comment by pgavlin** [comment]
The test failures appear to be due to missing assemblies.

**Comment by BruceForstall** [comment]
IMO, the new helpers should be private static member functions of emitter, not global static functions.

Otherwise, LGTM. I like the improvement.

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Pull request merged**
