### PR TITLE
Fix timing in PAL-tests for FreeBSD on hypervisors.

### PR DESCRIPTION
**Pull request by josteink**
This closes https://github.com/dotnet/coreclr/issues/1044

### CODE REVIEW

**Comment by jkotas** [comment]
I would make these change unconditionally for all platforms, and with large enough margin to make the test reliable. E.g. if you are seeing values 60-110 on hypervisor FreeBSD, make it 200.

> Linux, Windows and OSX does for whatever reason not show this same behavior

I expect that these numbers will depend a lot on the total load of the physical machine. It should not be hard to make these tests fail on hypervisor even on other OSes, by overloading the physical machine.

**Comment by kangaroo** [comment]
If @jkotas is ok bumping for all platforms I am as well.  Can you update please?

**Comment by josteink** [comment]
@jkotas If that's the official line, I have no problems fixing that.

I may have jumped the gun on claiming this will fix all issues for all tests though.

````
Thread waited for 4254 ms! (Acceptable delta: 150)

FAILED: threading/WaitForSingleObject/WFSOExSemaphoreTest/paltest_waitforsingleobject_wfsoexsemaphoretest. Exit code: 1

.Expected thread to wait for 4000 ms (and not be interrupted).
Thread waited for 4241 ms! (Acceptable delta: 150)

FAILED: threading/WaitForSingleObject/WFSOExThreadTest/paltest_waitforsingleobject_wfsoexthreadtest. Exit code: 1
````

The WaitForSingleObject-tests is still outside the deltas established. Obviously the threads *are* being interrupted, but not within the time-frames set by the tests.

is it acceptable to increase the accepted delta to 250 or 300 for the failing WFSO tests?

**Comment by jkotas** [comment]
> Would it be acceptable to increase the accepted delta to 250 or 300 for the failing WFSO tests? 
Yes.

**Comment by josteink** [comment]
All tests updated to have deltas matching values observed during testing. TDD in practice, eh? :)

**Comment by jkotas** [comment]
LGTM. Thanks!

**Pull request merged**
