### PR TITLE
JIT: fix byte range used by RangeCheck

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Fix wrong byte range introduced in #21857.

Thanks to @jakobbotsch for spotting this.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib

**Comment by hughbe** [comment]
Just curious and for a bunch of small jit fixes, why do they not have tests? I get slightly confused when code changes occur without tests? In llvm, for example, all small changes verify actual asm output (obviously too much in clr) but does the type of testing in coreclr need to be improved?

**Comment by BruceForstall** [comment]
@hughbe It's generally a good idea to add tests, when possible. If @AndyAyersMS can come up with a test exhibiting a difference here, that would be great. Sometimes it's too expensive or not feasible.

**Comment by AndyAyersMS** [comment]
I'll see if I can come up with something, though the most likely impact is a missed optimization, and we don't have a great testing strategy for those.

**Comment by filipnavara** [comment]
Looks like in this case you may end-up with missing bounds check in extreme case. That probably should be testable. Feel free to correct me if I am wrong.

**Comment by AndyAyersMS** [comment]
Test covers some of the byte/sbyte boundaries, and will fail without this fix.

**Pull request merged**
