### PR TITLE
[release/3.1-crossdac] Merge 3.1.29 changes into crossdac

### PR DESCRIPTION
**Pull request by hoyosjs**

### CODE REVIEW

**Comment by carlossanlop** [comment]
@hoyosjs the CI didn't run.

@mmitche can this get into the October release?

**Comment by carlossanlop** [comment]
Also, there's one product code change. This should go through Tactics.

**Comment by hoyosjs** [comment]
This is not release/3.1, rather another branch that doesn't build the product. It doesn't have CI and doesn't go through tactics.

**Comment by carlossanlop** [comment]
Ah my bad. GitHub is unable to filter the exact string for the base branch, so it ends up matching all substrings:  https://github.com/dotnet/coreclr/pulls?q=is%3Apr+is%3Aopen+base%3Arelease%2F3.1

**Review by tommcdon — APPROVED** [review]

**Pull request merged**
