### PR TITLE
Add the "createdump" to the linux runtime package.

### PR DESCRIPTION
**Pull request by mikem8361**

### CODE REVIEW

**Comment by mikem8361** [comment]
@dotnet-bot test Windows_NT x64 CoreCLR Perf Tests Correctness
@dotnet-bot test Windows_NT x86 CoreCLR Perf Tests Correctness

**Comment by mikem8361** [comment]
@dotnet-bot test Windows_NT x64 CoreCLR Perf Tests Correctness
@dotnet-bot test Windows_NT x86 CoreCLR Perf Tests Correctness

**Comment by brianrob** [comment]
@dotnet-bot test Windows_NT x64 CoreCLR Perf Tests Correctness

**Comment by brianrob** [comment]
@dotnet-bot test Windows_NT x86 CoreCLR Perf Tests Correctness

**Pull request merged**
