### PR TITLE
Fix and re-enable some GC finalizer tests

### PR DESCRIPTION
**Pull request by swgillespie**
This PR makes a few tests more robust against races against the finalizer thread (https://github.com/dotnet/coreclr/issues/4093). To do this, it runs `GC.Collect`, `GC.WaitForPendingFinalizers`, and `GC.Collect` in a loop for as long as the test success metrics are changing (i.e. finalizers are being run). If they remain the same after a Collect/WFPF/Collect iteration, there's a real issue.

Fixes https://github.com/dotnet/coreclr/issues/4093.

### CODE REVIEW

**Comment by swgillespie** [comment]
@dotnet-bot test this please

**Comment by swgillespie** [comment]
All re-enabled tests are passing - cc @sergiy-k @Maoni0 ptal?

**Comment by sergiy-k** [comment]
LGTM. Thank you!

**Comment by swgillespie** [comment]
thanks!

**Pull request merged**
