### PR TITLE
Fix BBF_HAS_NULLCHECK test

### PR DESCRIPTION
**Pull request by svick**
The variable was introduced by https://github.com/dotnet/coreclr/pull/6631, but it seems it was never used.

cc: @erozenfeld

### CODE REVIEW

**Comment by erozenfeld** [comment]
@svick Thank you for spotting this. The correct place for this is at the beginning of optFoldNullCheck. Right after the initial comment we should have
```
if((compCurBB->bbFlags & BBF_HAS_NULLCHECK) == 0)
{
    return;
}
```
It doesn't affect correctness but may save a tiny bit of throughput since optFoldNullCheck is called when (bbHasArrayRef || bbHasVtableRef || bbHasNullCheck) is true but has any chance to find something relevant only if bbHasNullCheck is true.

**Comment by svick** [comment]
@erozenfeld Done.

**Comment by erozenfeld** [comment]
LGTM

**Comment by pgavlin** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Pull request merged**
