### PR TITLE
Workaround for  compiler.hpp (1848) - Assertion failed 'lvRefCnt'

### PR DESCRIPTION
**Pull request by sandreenko**
The description is in #18291.

The fix is to replace `JTRUE` `relop` before morph the list of its side effects. In this case when we have `fgRemoveRestOfBlock` and call `fgRemoveStmt` it removes updated `JTRUE` and this part works correct.

The problem that `optVNConstantPropCurStmt` could receive a statement that was already removed still exists.

### CODE REVIEW

**Comment by sandreenko** [comment]
ci example: [Windows_NT x64 Checked Innerloop Build and Test ](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_windows_nt_innerloop_prtest/4000/testReport/junit/JIT_Regression/_JitBlue_GitHub_18291_GitHub_18291_GitHub_18291_/_JitBlue_GitHub_18291_GitHub_18291_GitHub_18291_cmd/)

**Comment by sandreenko** [comment]
PTAL @dotnet/jit-contrib

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT x64 Checked jitstress2
@dotnet-bot test Windows_NT x86 Checked jitstress2

**Comment by AndyAyersMS** [comment]
Our ambition is to remove all incremental ref count maintenance -- in part because of issues like this -- in the not too distant future.

So if this is some kind of artificial bug case, perhaps we can just hold off fixing it for now?

**Comment by AndyAyersMS** [comment]
Going to re-trigger the formatting tests to make sure my recent jitutils update is OK.

@dotnet-bot test Windows_NT x64 Formatting

**Comment by sandreenko** [comment]
> So if this is some kind of artificial bug case

Yes, it is an  artificial bug case, however, I think it  can be recreated with C# code.

> Our ambition is to remove all incremental ref count maintenance -- in part because of issues like this -- in the not too distant future.

Do we have an issue to track that ambition?
The problem is not only that we decrease counters twice, but also that we remove other trees twice. The PR makes things better, we replace `JTRUE` `relop` with a new created tree and then start extracting and morphing side effects, it means we do not have a moment when IR has duplicates, as it was before (`JTRUE` has old relop tree and part of it was already extracted and inserted before `JTRUE`). So we need this change even after removing all incremental ref count maintenance.

> perhaps we can just hold off fixing it for now?

I do not see why we should hold it.

**Comment by sandreenko** [comment]
Could somebody pls take a look, @dotnet/jit-contrib ?

**Comment by AndyAyersMS** [comment]
Issue for incremental ref count removal is #13280.

The change you made looks ok but it rreallly needs a comment saying why things must be done in this particular order as it's not obvious.

I wonder how many other places we may have similar ordering issues and haven't hit the right test case yet?

I'm also surprised we don't hit other asserts when trying to remove trees twice. Seems like we should be calling `DEBUG_DESTROY_NODE` in `fgRemoveStmt`. Though I recall being confused as to what the expected behavior of this method was in the past  (#8059)-- it seemingly can't destroy everything in the statement. But perhaps it can destroy the statement expression?

**Comment by sandreenko** [comment]
I have added 2 comments to explain it better.

I think we should add a separate issue to better check and assert flowGraph transformations.

For example in the existing code when `JTRUE` has two side effects, `THROW` and something else, and `THROW` goes first, that code
```
    while (sideEffList != nullptr) <- sideEffList = {THROW, smth else}
    {
        GenTree* newStmt;
        if (sideEffList->OperGet() == GT_COMMA)
        {
            newStmt     = fgInsertStmtNearEnd(block, sideEffList->gtGetOp1());
            sideEffList = sideEffList->gtGetOp2();
        }
        else
        {
            newStmt     = fgInsertStmtNearEnd(block, sideEffList); <-- will delete stmts after THROW, including JTRUE on the first iteration.
            sideEffList = nullptr;
        }
        // fgMorphBlockStmt could potentially affect stmts after the current one,
        // for example when it decides to fgRemoveRestOfBlock.
        fgMorphBlockStmt(block, newStmt->AsStmt() DEBUGARG(__FUNCTION__));
    }
```
on the second iteration `something else` will call `fgInsertStmtNearEnd` and the statement will be inserted after `THROW` without any need.

**Pull request merged**
