### PR TITLE
GitHub issue #497: Identical expressions to the left and right of the ||...

### PR DESCRIPTION
**Pull request by CarolEidt**
... operator

This was very old code that was needed before the rationalization of assignments (should have been GT_CLS_VAR and GT_IND).  GT_CLS_VAR should now never be seen post-rationalizer.

### CODE REVIEW

**Comment by CarolEidt** [comment]
#479

**Comment by CarolEidt** [comment]
@BruceForstall please take a look.

**Comment by BruceForstall** [comment]
LGTM

**Comment by jkotas** [comment]
cc @cmckinsey 

@CarolEidt I would be nice to fix the commit title to follow the conventions (starts with noun, and make it shorter)

**Comment by cmckinsey** [comment]
LGTM

**Comment by akoeplinger** [comment]
@CarolEidt Looks like you accidentally mentioned #497 instead of #479 in the commit message, which means the wrong issue got closed. Can you please reopen that one and close the other?

**Comment by CarolEidt** [comment]
@ellismg beat me to it.

**Pull request merged**
