### PR TITLE
Implement GC BulkTypeEvent firing on Linux

### PR DESCRIPTION
**Pull request by Lucrecious**
Before, the method, "FireBulkTypeEvent" implementation only worked on Windows. As a result, GC BulkType events would not fire on Linux. This PR implements the method, "FireBulkTypeEvent" so that it works both on Linux and Windows.

### CODE REVIEW

**Comment by Lucrecious** [comment]
@vancem This is the PR with the implementation for FireBulkTypeEvent for Linux (which should work on Windows as well).

**Comment by vancem** [comment]
@dotnet-bot test OSX x64 Checked Build and Test
@dotnet-bot test  Ubuntu x64 Checked Build and Test  
@dotnet-bot test  Windows_NT x64 Debug Build and Test

**Comment by danmosemsft** [comment]
@Lucrecious could you please rebase so the tests can run again?

**Comment by Lucrecious** [comment]
@vancem https://github.com/dotnet/coreclr/pull/4518#issuecomment-253656630

**Comment by vancem** [comment]
I am going to close this PR, so I can open it again under my own account and will complete the checkin process.

**Pull request closed without merging**
