### PR TITLE
Set helix source correctly for prodcon build (#16412)

### PR DESCRIPTION
**Pull request by mmitche**
This change should have been ported to master

### CODE REVIEW

**Comment by ChadNedzlek** [comment]
Same question about how long ProdCon v1 and master are going to be friends.

**Comment by mmitche** [comment]
@ChadNedzlek Probably for a while.  At least until the end of 2.1

**Comment by mmitche** [comment]
@MattGal Are you thinking of the docker container issue? Not in coreclr because the tests only build on windows.

**Comment by MattGal** [comment]
@mmitche I simply meant misreporting of the tests, which this PR would indicate we had the same problem :)

**Pull request merged**
