### PR TITLE
Disable a tail call test when using minopts

### PR DESCRIPTION
**Pull request by kouvel**
Fixes https://github.com/dotnet/coreclr/issues/24424

### CODE REVIEW

**Comment by kouvel** [comment]
CC @sandreenko @dotnet/jit-contrib 

Is there a way to kick off a minopts run on arm32? I hadn't seen the failure in https://github.com/dotnet/coreclr/issues/24424 before in a default CI run.

**Comment by kouvel** [comment]
@dotnet-bot help

**Comment by kouvel** [comment]
@dotnet-bot test Ubuntu arm Cross Checked minopts Build and Test

**Comment by kouvel** [comment]
@dotnet-bot test ci Linux arm Checked jitminopts

**Comment by kouvel** [comment]
Hmm looks like that added an old style job. Is there a way to run optional jobs like minopts in coreclr-ci?

**Comment by sandreenko** [comment]
@kouvel Yes, it is a bit tricky right now, it should get better soon, but you still can do that:
1. go to https://dev.azure.com/dnceng/public/_build?definitionId=348, 
2. log in,
3. click "queue",
4. in branch replace "master" with "refs/pull/YOUR_PR_NUMBER/head",
5. click queue.

You can do the same with other testing modes (like jit stress regs or GCStress) and you can see what is available for triggering via "comment" on GitHub with "/azp list".

But please wait for #24421 to be merged first. I have changed the name of jitstress testing group and until it is merged it is not possible to trigger them via the new name. It will be merged in an hour or less.

**Comment by kouvel** [comment]
Thanks!

**Comment by sandreenko** [comment]
Other jobs are not shown in this list/cannot be triggered by "/a_z_p run name" because the default behaviors for "/a_z_p run" with 0 arguments is to run all jobs from the list.  When it happened it used all available arm machines and hanged PR testing for other people and we saw it quite a lot so we removed these stress jobs from this list.

**Comment by sandreenko** [comment]
@kouvel  could you please rebase your PR to the latest master? Because it doesn't have changes from https://github.com/dotnet/coreclr/pull/24421 it doesn't want to work correctly.

**Comment by kouvel** [comment]
I see thanks, done

**Comment by sandreenko** [comment]
LGTM, the failures are unrelated. Thank you.

**Comment by sandreenko** [comment]
> Please use this mechanism to disable this test:
> 
> coreclr/tests/src/JIT/Directed/IL/Tailcall/JitTailcall2.ilproj
> 
> Line 27 in f00fa5b
> 
>  <JitOptimizationSensitive>true</JitOptimizationSensitive> 
> . MinOpts can be triggered by more than just COMPlus_JITMinOpts.

The test is failing only on arm32 Linux minopts, I do not think we should lose all stress coverage for this because of that. If the fix in this PR is not sufficient I would prefer to disable if for arm32 Linux in issues.targets.

**Comment by RussKeldorph** [comment]
@sandreenko The change proposed in this PR would also disable it for all platforms--just under MinOpts only.  If the test should be disabled under MinOpts, it should be disabled under JitStress modes that might trigger MinOpts; otherwise it's just a ticking time bomb.

If we want to keep the test running for other platforms even under MinOpts, then my preference would be to adjust the test to fit within the stack limits on all platforms, possibly by making the test determine the stack limit dynamically if you really need to toe the line.  If that's not reasonable, you might be able to conditionalize the `<JitOptimizationSensitive>` element.  I don't think we've tried that yet, but it might work now that we always build tests for the target they run on.  Not ideal, but you wouldn't be making the current problem worse since we already have a few other examples affecting predefined macros in IL.

**Comment by sandreenko** [comment]
@RussKeldorph agree, thank you.

> you might be able to conditionalize the <JitOptimizationSensitive> element. I don't think we've tried that yet, but it might work now that we always build tests for the target they run on. 

I have used it, it works fine, https://github.com/dotnet/coreclr/blob/b7836c0b6e59f4e6bd6af984569f4ce8b3573f4e/tests/src/JIT/jit64/opt/cse/hugeexpr1.csproj#L27-L29

**Comment by kouvel** [comment]
The intention of the test is to overflow the stack if a tail call is not generated, so it is kind of optimization-sensitive (on all platforms, even if there currently isn't an issue). As to whether explicit tail calls should generate actual tail calls in minopt cases, maybe, but that would be a separate issue. I forgot about the JitOptimizationSensitive attribute. For now I'll use the attribute. Eventually, it may be appropriate to remove that attribute from the test and have it apply to any mode.

**Comment by kouvel** [comment]
Looks like none of the failures are related to the change

**Comment by RussKeldorph** [comment]
Sorry for the delay.  I missed the request.

**Comment by kouvel** [comment]
Thanks! None of the failures are related to the change.

**Pull request merged**
