### PR TITLE
Ensure that platform is considered for LongPlatformName instead of PackagePlatform

### PR DESCRIPTION
**Pull request by karajas**
Port of https://github.com/dotnet/coreclr/pull/11900 

/cc @ellismg @ericstj @mikem8361 @gkhanna79 @chcosta

### CODE REVIEW

**Comment by karajas** [comment]
OSX is hitting a machine error https://ci.dot.net/job/dotnet_coreclr/job/release_2.0.0/job/checked_osx10.12_flow_prtest/171/consoleFull#16132091256ee26338-6221-4f7c-8c8f-1d1d5cb4704a /cc @mmitche

**Comment by karajas** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test please

**Comment by karajas** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test please

**Comment by mikem8361** [comment]
LGTM

**Comment by gkhanna79** [comment]
Merging since change does not affect OSX and OSX ran into infra issues earlier.

**Pull request merged**
