### PR TITLE
Waitany test debug and cleanup

### PR DESCRIPTION
**Pull request by sdmaclea**
@kouvel Following your lead adding diagnostics and similar cleanup to more `waitany*` tests.

### CODE REVIEW

**Comment by sdmaclea** [comment]
@kouvel abandoning in favor of marking gcstress incompatible

**Comment by kouvel** [comment]
Sorry didn't get a chance to look at this until now, and thanks for doing this. I'd like to check this in as well if possible.

**Review by kouvel — COMMENTED** [review]
LGTM

**Comment by sdmaclea** [comment]
@BruceForstall @kouvel I amended this change to fix a small number of tests and marked many more `GCStressIncompatible`  PTAL

**Comment by BruceForstall** [comment]
Seems reasonable to me. I'll leave it to @kouvel to have the final say.

**Review by kouvel — APPROVED** [review]

**Comment by kouvel** [comment]
Thanks!

**Comment by BruceForstall** [comment]
Jenkins died in the interim. Retest:

@dotnet-bot test this please

**Pull request merged**
