### PR TITLE
Document new GC configuration knobs

### PR DESCRIPTION
**Pull request by ghost**
* Adds a new column "Minimum `dotnet` Version" as the new knobs are only available in dotnet 3.0+.
* The changes to `clr-configuration-knobs.md` are due to running
  `dotnet-script clr-configuration-knobs.csx` which causes some
  unrelated changes. Only `clr-configuration-knobs.csx` was manually
  edited.
* The new properties are:
  - "System.GC.HeapHardLimit"
  - "System.GC.HeapHardLimitPercent"
  - "System.GC.HeapAffinitizeMask"
  - "System.GC.HeapCount"
  - "System.GC.NoAffinitize"
* These properties are supported as of #25574 and #25653

### CODE REVIEW

**Comment by Maoni0** [comment]
apparently this generates tons of changes in the .md that are not related to the changes in the .csx file. does this matter? @jkotas do you know? is it because some of the changes to the .md were manually done instead of auto generated?

**Comment by jkotas** [comment]
This generated doc file is perpetually out of data. I was not fan of having it in the first place: https://github.com/dotnet/coreclr/pull/844#issuecomment-96904360

Also, I do not think it is useful to have the minimum supported version in this doc. It is just going to be another bit of information that will be wrong or confusing half of the time. The information about supported versions is only useful for officially supported and documented knobs. I think it should be only in the official documentation where small subset of these knobs are documented.

**Comment by jkotas** [comment]
Related: https://github.com/dotnet/docs/pull/12959/ . You should make sure that the documentation for the officially supported knobs is in the official docs. 

Also, we should have tests for all officially supported knobs. (Ignore this comment if you have the test coverage already.)

**Comment by Maoni0** [comment]
without the min support version this is basically useless. and if we are counting on the official doc to document these anyway why do we have this doc in our repo at all? we should just get rid of this doc and only update the one in the docs repo.

**Comment by jkotas** [comment]
> we should just get rid of this doc and only update the one in the docs repo.

I would be happy to approve PR that gets rid of this doc, and points people to the official docs for the officially supported knobs.

**Comment by maryamariyan** [comment]
Thank you for your contribution. As announced in dotnet/coreclr#27549 this repository will be moving to dotnet/runtime on November 13. If you would like to continue working on this PR after this date, the easiest way to move the change to dotnet/runtime is:
1.	In your coreclr repository clone, create patch by running `git format-patch origin`
2.	In your runtime repository clone, apply the patch by running `git apply --directory src/coreclr <path to the patch created in step 1>`

**Comment by maryamariyan** [comment]
Thank you for your contribution. As announced in #27549 the dotnet/runtime repository will be used going forward for changes to this code base. Closing this PR as no more changes will be accepted into master for this repository. If you’d like to continue working on this change please move it to dotnet/runtime.

**Pull request closed without merging**
