### PR TITLE
Clear side-effect flags on local reads in rationalize.

### PR DESCRIPTION
**Pull request by pgavlin**
These operations are always side-effect free.

### CODE REVIEW

**Comment by pgavlin** [comment]
Fixes VSO 280103.

**Comment by pgavlin** [comment]
@adiaaida @BruceForstall @dotnet/jit-contrib PTAL

**Comment by BruceForstall** [comment]
LGTM

**Comment by adiaaida** [comment]
LGTM

**Comment by CarolEidt** [comment]
Can you construct a test case?

**Comment by pgavlin** [comment]
@CarolEidt: this popped up with PMI under JIT stress. I made a number of attempts to construct a minimal repro and was unsuccessful.

**Pull request merged**
