### PR TITLE
Exit runtest.sh with a failure code if any tests fail

### PR DESCRIPTION
**Pull request by adityamandaleeka**
This script was previously exiting with '0' regardless of whether there were any test failures. Changing this allows the status of the CI runs in Jenkins to reflect whether the tests actually passed.

/cc: @mmitche

### CODE REVIEW

**Comment by sergiy-k** [comment]
LGTM

**Comment by mmitche** [comment]
@adityamandaleeka Do you want to iterate on/disable those last few failing tests before merging?

**Comment by adityamandaleeka** [comment]
Oops, fixing that last commit.

**Comment by adityamandaleeka** [comment]
@dotnet-bot test Ubuntu release

**Comment by adityamandaleeka** [comment]
@dotnet-bot test Ubuntu release

**Comment by adityamandaleeka** [comment]
@dotnet-bot test Ubuntu release

**Pull request merged**
