### PR TITLE
Fixes issue #21484 createdump segfaults

### PR DESCRIPTION
**Pull request by mikem8361**
Issue #21484: createdump segfaults with ASP.NET app

The problem is the ClrDataModule Request faulted on a dynamic module
getting the file layout flag.

Fixed the Request code not get the file layout and in the crash dump
code skip any dynamic modules.

Issue #21485: fix EnumProcessModules hPseudoCurrentProcess bug.

### CODE REVIEW

**Comment by mikem8361** [comment]
**Description**

The createdump utility segfaults with ASP.NET Core 2.2 applications.  

**Customer Impact**

Customers can't create a core dump and diagnostic there ASP.NET app or any .NET Core that has dynamic modules.

**Regression?**

Not a regression.

**Risk**

Low.  Affects Linux only.

**Comment by mikem8361** [comment]
@Maoni0, does it make sense that GC heap globals like ephemeral_heap_segment and finalize_queue were null for some apps?

**Comment by mikem8361** [comment]
@dotnet-bot test Windows_NT x64 Formatting

**Comment by mikem8361** [comment]
@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test

**Comment by jamshedd** [comment]
@russk to follow up on test coverage with @mikem8361 .

**Comment by mikem8361** [comment]
I tested createdump manually on ubuntu and fedora against a webapp.  I also ran our diagnostictests against the changes and everything succeeds. The diagnostic tests contain createdump tests.

**Comment by RussKeldorph** [comment]
@mikem8361 Are you adding/have you added test coverage that would have caught this?  I assume there was a hole before; shiproom would like to know if it is plugged.

**Comment by mikem8361** [comment]
I haven't added any additional test coverage yet. I created issue #21892 to track this.

**Comment by RussKeldorph** [comment]
@mikem8361 ok, so it sounds like in any case any additional test coverage wouldn't be included in this change since it wouldn't be in the coreclr repo.  Thanks for the additional issue to track that.

**Comment by jamshedd** [comment]
Approved for 2.2.2.

**Pull request merged**
