### PR TITLE
fix generic attribute bug when generic attribute has parameters and the parameters

### PR DESCRIPTION
**Pull request by AviAvni**
I'm checking the tests but this fixes the bug

### CODE REVIEW

**Comment by AviAvni** [comment]
@jkotas I added the missing test cases sorry for that

**Comment by davidwrighton** [comment]
@AviAvni I like this fix, but could you please link to the associated CoreCLR issue?

**Comment by AviAvni** [comment]
@davidwrighton there is no issue i implemented this feature and while debugging it in preview when working on the parallel Roslyn PR I found the bug that I introduced

**Comment by davidwrighton** [comment]
@AviAvni, ah, I see. Well, the fix looks good. I would have used th instead of gc.refCaType->GetType(), but the behavior is correct, and there is no performance difference.

**Comment by AviAvni** [comment]
@davidwrighton  Great thanks I hope to see this in next preview

**Pull request merged**
