### PR TITLE
Disable tiered compilation for collectible assemblies

### PR DESCRIPTION
**Pull request by kouvel**
- An assembly can be marked collectible with methods not marked as dynamic
- The method desc and code can be deleted and a new method desc reallocated in the same location, code versioning doesn't handle this at the moment

### CODE REVIEW

**Comment by jkotas** [comment]
> The method desc and code can be deleted and a new method desc reallocated in the same location

The same can happen for collectible generic methods: The method module can be non-collectible, but the module of one of the instantiation arguments can be collectible. Do you need to handle this case as well?

**Comment by jkotas** [comment]
Checking `GetLoaderAllocator()->IsCollectible()` instead should handle the collectible generic method case.

**Comment by kouvel** [comment]
Thanks, changed

**Comment by noahfalk** [comment]
Since Jan pointed out the generics + collectible assembly case which needed different handling, how about we add a test case for that too? I'm fine if it is this PR or a separate one though.

**Comment by kouvel** [comment]
I tried modifying this test to have a class with a generic method that takes a T and calls `((IHelloWorld)obj).Hello()`, and calling it through reflection using the collectible helloType as the generic type parameter, but I wasn't able to repro a failure without any fix or with the previous fix, so I left it out. I'd have to look into it a bit closer to see why, but since the loader allocator is what is actually collectible in the end, it makes sense to me that we check for that.

**Comment by noahfalk** [comment]
Yeah, I'm happy to take code fix even if we don't have the test that proves it - the test was just additional insurance. Thanks Kount!

**Pull request merged**
