### PR TITLE
[Testing] Undo a bug fix - it should cause R2R CI job to fail

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
@dotnet-bot test Windows_NT Checked pri1r2r please

**Comment by jkotas** [comment]
@dotnet-bot test Ubuntu Checked pri1r2r please

**Comment by jkotas** [comment]
This change should cause both Windows and Ubuntu R2R legs to fail. (It does fail for me locally on both.)

For some reason, the Windows R2R leg is passing. 

@fadimounir @JohnChen0  Could you please take a look when you get a chance?

cc @gkhanna79

**Comment by gkhanna79** [comment]
Thanks Jan. Can you please file an issue for this and assign it to @JohnChen0 to take look?

**Pull request closed without merging**
