### PR TITLE
Add azure-pipeline job: coreclr-ci (Test Pri0 Linux_musl x64 release)

### PR DESCRIPTION
**Pull request by briansull**

### CODE REVIEW

**Comment by briansull** [comment]
@echesakovMSFT  PTAL

**Comment by briansull** [comment]
Azure DevOps Notifications <azuredevops@microsoft.com>

Build Linux_musl x64 checked
--
1 error(s), 0 warning(s)                                      Unable to locate dotnetcore on build agent. | 1 error(s), 0 warning(s) |   | Unable to locate dotnetcore on build agent.
1 error(s), 0 warning(s)
  | Unable to locate dotnetcore on build agent.

**Comment by briansull** [comment]
@dotnetbot Test coreclr-ci (Test pri0 Linux arm64 checked

**Comment by briansull** [comment]
@dotnetbot Test pri0 Linux arm64 checked

**Comment by briansull** [comment]
@dotnetbot Test coreclr-ci  pri0 Linux arm64 checked

**Comment by echesakovMSFT** [comment]
dotnetbot command wouldn't work here. If you want to re-try you need to go the build definition page https://dev.azure.com/dnceng/public/_build/results?buildId=130106

**Comment by echesakovMSFT** [comment]
cc @RussKeldorph

**Pull request merged**
