### PR TITLE
Port EH tests. Adds 34 tests from legacy test bed

### PR DESCRIPTION
**Pull request by rahku**
Below is the EH test port status for each of sub-category of Exception tests
AccessViolationException - ported except which depend on AccessViolationException type which is not supported in .netcore
CorruptedStateExceptions - NA
CrossDomainExceptions - NA
CTI - depend on MathodBase.MethodHandle & other reflection apis not supported in .netcore
Generics - all ported
legacyUnhandledExceptionPolicy - NA
LogFatalError - NA
MacExceptionHandling - Not Done. As can't verify.
OutOfMemoryException - depends on CER not present in .netcore
Regressions - ported except those which were not applicable like security, appdomain, vb etc...
PInvokesOnMac - Not Done. As can't verify.
SafeExceptionHandler - test for frameworkSDK and not product
Security - NA
SharedExceptions - ported except NA like rudethreadabort
simple - ported except StackOverflow.cs(depend on StackOverflowException type - not present) and unhandled.cs (NA)
StackTracePreserve - ported
SxSExceptions - NA
ThreadAbortReraise - NA
UEF - NA
UnhandledExceptionMarshaling - NA
UnitTests - all ported

We can now run a total of 114 EH tests in GitHub.

### CODE REVIEW

**Comment by rahku** [comment]
PTAL @gkhanna79

**Comment by rahku** [comment]
@dotnet-bot test Windows_NT

**Comment by rahku** [comment]
EnhancedExceptionNotification - NA
FailFast - tests are disabled for desktop 
ExceptionDriver - tests need to be modified to not depend on appDomain apis

**Comment by gkhanna79** [comment]
Please squash the commits. Are these getting added to P0 or P1 test runs?

**Comment by rahku** [comment]
these are getting added to P1

**Comment by gkhanna79** [comment]
In that case, please ensure that you are testing the P1 run in CI to confirm they are passing there as well.

**Comment by rahku** [comment]
@dotnet-bot test OSX pri1 please

**Comment by rahku** [comment]
@dotnet-bot test Ubuntu pri1 please

**Comment by rahku** [comment]
@dotnet-bot test CentOS pri1 please

**Comment by rahku** [comment]
Do you know how I can trigger windows P1 test in CI

**Comment by rahku** [comment]
@janvorli can you look at EH tests that are failing for ubuntu if they are supported on non-windows (like filter & fault)
all of filter & fault tests are failing due to missing system.console but passes locally on my machine
some more EH tests are also failing which I would expect to pass on non-windows

**Comment by rahku** [comment]
@dotnet-bot test Ubuntu pri1 please

**Comment by gkhanna79** [comment]
Ubuntu has the failure shown at http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x64_release_windows_nt_pri1_bld_prtest/27/consoleFull#1911792873a82fefab-f698-416f-8fca-58544c94cd4e.

**Comment by rahku** [comment]
@dotnet-bot test Ubuntu pri1 please

**Comment by rahku** [comment]
@dotnet-bot test Windows_NT x86 Debug Legacy Backend Build and Test

**Comment by rahku** [comment]
@dotnet-bot test Ubuntu pri1 please

**Comment by rahku** [comment]
@dotnet-bot test Ubuntu pri1 please

**Comment by ramarag** [comment]
@rahku arm64 test build is failing, can you take a look ?
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/arm64_cross_checked_windows_nt_prtest/14/consoleFull#-800107690a82fefab-f698-416f-8fca-58544c94cd4e

**Pull request merged**
