### PR TITLE
[Arm64] Use proper lowering for TYP_SIMD8/TYP_LONG type

### PR DESCRIPTION
**Pull request by debayang**
Not sure if this function call (FixupIfSIMDLocal) is needed for ARM64.
@CarolEidt @sdmaclea PTAL.

Removing the FixupIfSIMDLocal() in Rationalizer  fixes the SIMD assertion error seen with JITMinOpts=1 (Ref #17111 ) for type TYP_SIMD8 below.

Assert failure(PID 9366 [0x00002496], Thread: 9366 [0x2496]): Assertion failed '(consume > 1) || (regType(store->gtOp1->TypeGet()) == regType(store->TypeGet()))' in 'Arm64intrisicsTest.Program:testBinOp(ref,ref,ref)' (IL size 408)
File: /home/debayan/coreclr/src/jit/lsrabuild.cpp Line: 1383

### CODE REVIEW

**Comment by CarolEidt** [comment]
@debayang - I believe that you are correct that this is not needed for ARM64. It is designed to work around issues relating to the fact that `TYP_SIMD8` is passed and returned in integer registers on x86/x64.
However, I would like to understand what went wrong with this, as it's not clear to me what it would not be harmless. Could you show the before-and-after for the affected node that this is called on?

**Comment by debayang** [comment]
For this failure case, below change in node 
Before : 
N002 (  3,  4) [000009] D------N----              *  LCL_FLD   long   V04 loc1         [+0]
After FixupifSIMDLocal(node->AsLclVarCommon()):
N002 (  3,  4) [000009] D------N----              *  LCL_VAR   simd8  V04 loc1

**Comment by CarolEidt** [comment]
@debayang - thanks. So, the lclVar is `TYP_SIMD8`, but the value getting stored into it is a `TYP_LONG`, it seems. Do you know why that's happening?

**Comment by debayang** [comment]
Not sure at this point. Need to debug more.
The lclVar as TYP_SIMD8 is only seen when MinOpt is Set.

**Comment by sdmaclea** [comment]
@CarolEidt @debayang Until #16310 merges, JIT is not aware of ShortVector or HVA Arm64 ABI.  SIMD8 is therefore treated like any other struct.  It is passed in a single 8 byte register as a packed long.

**Comment by CarolEidt** [comment]
If `TYP_SIMD8` is passed as a `TYP_LONG`, it may be that Lowering is not inserting a `GT_BITCAST` for these cases. For example, see `Lowering::LowerArg()`. It sounds, though, as if ARM64 might require some special handling, so that the HFA types are not lowered in this way.

**Comment by debayang** [comment]
@CarolEidt  Probably we need to extend these as below:
```
diff --git a/src/jit/lower.cpp b/src/jit/lower.cpp
index 3f609e7..976ef02 100644
--- a/src/jit/lower.cpp
+++ b/src/jit/lower.cpp
@@ -281,7 +281,7 @@ GenTree* Lowering::LowerNode(GenTree* node)

         case GT_STORE_LCL_FLD:
         {
-#if defined(_TARGET_AMD64_) && defined(FEATURE_SIMD)
+#if (defined(_TARGET_AMD64_) || defined(_TARGET_ARM64_)) && defined(FEATURE_SIMD)
             GenTreeLclVarCommon* const store = node->AsLclVarCommon();
             if ((store->TypeGet() == TYP_SIMD8) != (store->gtOp1->TypeGet() == TYP_SIMD8))
             {
@@ -1428,7 +1428,7 @@ void Lowering::LowerArg(GenTreeCall* call, GenTree** ppArg)
             }
         }
     }
-#elif defined(_TARGET_AMD64_)
+#elif (defined(_TARGET_AMD64_) || defined(_TARGET_ARM64_))
     // TYP_SIMD8 parameters that are passed as longs
     if (type == TYP_SIMD8 && genIsValidIntReg(info->regNum))
     {
@@ -3065,7 +3065,7 @@ void Lowering::LowerRet(GenTree* ret)
     DISPNODE(ret);
     JITDUMP("============");

-#if defined(_TARGET_AMD64_) && defined(FEATURE_SIMD)
+#if (defined(_TARGET_AMD64_) || defined(_TARGET_ARM64_)) && defined(FEATURE_SIMD)
     GenTreeUnOp* const unOp = ret->AsUnOp();
     if ((unOp->TypeGet() == TYP_LONG) && (unOp->gtOp1->TypeGet() == TYP_SIMD8))
     {
``` 

With these Bitcast ops introduced the failure case is handled.

However, I see some other passing tests to fail (below) due to the above change.

```
corerun JIT/SIMD/VectorReturn_ro/VectorReturn_ro.exe

Assert failure(PID 16220 [0x00003f5c], Thread: 16220 [0x3f5c]): Assertion failed '((consume == 0) && (produce == 0)) || (ComputeAvailableSrcCount(tree) == consume)' in 'VectorTest:Main():int' (IL size 511)

    File: /home/debayan/coreclr/src/jit/lsrabuild.cpp Line: 1330
```
Need to debug these.

**Comment by sdmaclea** [comment]
@debayang If the SIMD8 element type is float, the code above is inserting an incorrect bitcast.

**Comment by debayang** [comment]
@CarolEidt , @sdmaclea 
I modified the condition with explicit checks for TYP_LONG and TYP_SIMD8.
from
    ` if ((store->TypeGet() == TYP_SIMD8) != (store->gtOp1->TypeGet() == TYP_SIMD8))`
to
    ` if ((store->TypeGet() == TYP_SIMD8) && (store->gtOp1->TypeGet() == TYP_LONG))`

This seems to fix the issue and both the tests passed.  Updated the commit.

**Comment by sdmaclea** [comment]
The PR looks internally consistent now.  All three new `#if` handle the `SIMD8 <-> LONG` case.  

I am wondering 
+ Why we don't have to handle GT_LCL_FLD lowering?
+ Why we dont have the handle the `SIMD8 <-> DOUBLE` case?  Is it because they are allocated the same registers and the `GT_BITCAST` is effectively a nop.

**Comment by CarolEidt** [comment]
> Why we don't have to handle GT_LCL_FLD lowering?

This is because a `GT_LCL_FLD` never refers to a value in a register - it is always on the stack. So it doesn't have the issue with assigning between incompatible register files - which is what the `GT_BITCAST` takes care of.

> Why we dont have the handle the SIMD8 <-> DOUBLE case? Is it because they are allocated the same registers and the GT_BITCAST is effectively a nop.

Yes, exactly. `GT_BITCAST` is only needed when the types live in different register files.

**Comment by debayang** [comment]
@CarolEidt  On testing found seems that the above constraint was not enough as in some scenarios, I see
`store->gtOp1->TypeGet() ` is TYP_STRUCT and `store->TypeGet() =TYP_SIMD8`  

Changed to below:
`if ((regType(store) != regType(store->gtOp1)) && (store->gtOp1->TypeGet() == TYP_LONG))`

**Comment by CarolEidt** [comment]
> On testing found seems that the above constraint was not enough as in some scenarios, I see
store->gtOp1->TypeGet() is TYP_STRUCT and store->TypeGet() =TYP_SIMD8

Your proposed change, though, will not handle the case where op1 is a `TYP_SIMD8` but the store is expecting an integer register, which is, I believe, what the original code was also intended to handle.

If you're seeing a store of a `TYP_STRUCT` to a `TYP_SIMD8` I think that indicates a bug, because an assignment to a `TYP_SIMD8` field would expect a register source, and a `TYP_STRUCT` node won't be allocated a register.

**Comment by debayang** [comment]
@CarolEidt ,
> If you're seeing a store of a TYP_STRUCT to a TYP_SIMD8 I think that indicates a bug, because an assignment to a TYP_SIMD8 field would expect a register source, and a TYP_STRUCT node won't be 
allocated a register.

Dumping the node in the above case (below) points to a call node with a struct type.  ( a multireg return value ?) .  Not sure if this is a bug.

```
N007 ( 17,  7) [000008] DA-XG-------              *  STORE_LCL_VAR simd8  V06 tmp0         d:3
N005 ( 17,  7) [000004] --CXG-------                 *  CALL      struct VectorTest.F2_v2 $200,NA
               [001365] ------------ arg0 in d0      \--*  PUTARG_REG float  REG d0
N003 (  3,  4) [000003] ------------                    \--*  CNS_DBL   float  0.50000000000000000 $41
```
If not, does skipping the condition `(regType(store) != regType(store->gtOp1))` if typ_struct makes sense ?

**Comment by debayang** [comment]
@CarolEidt , @sdmaclea 
Some updates on this one:
All of the below conditions to enable bitcast causes failures for arm64 or x64 or both.

- `(regType(store) != regType(store->gtOp1))`
- `(store->TypeGet() == TYP_SIMD8) &&  (regType(store) != regType(store->gtOp1))`
- `(regType(store) != regType(store->gtOp1)) && (store->gtOp1->TypeGet() != TYP_STRUCT)`
- `(store->TypeGet() == TYP_SIMD8) && (regType(store) != regType(store->gtOp1)) && (store->gtOp1->TypeGet() != TYP_STRUCT)`

I have not analyzed the failure reasons for the x64 tests.
So far the only condition which works for both seems to be skipping the TYP_STRUCT with existing condition 
- `(((store->TypeGet() == TYP_SIMD8) != (store->gtOp1->TypeGet() == TYP_SIMD8)) &&
              (store->gtOp1->TypeGet() != TYP_STRUCT))
`

**Comment by BruceForstall** [comment]
@debayang @sdmaclea @CarolEidt This PR is stale; no activity for 3 months. Is someone still working on it? 

Are there GitHub issues (e.g., test failures) that this should fix?

**Comment by sdmaclea** [comment]
@BruceForstall 

No one is working on this.  #17111 is still failing in my nightlies.

`JIT/HardwareIntrinsics/Arm64/Simd/Simd.sh` fails in these configs
```
jitMinOpts
jitStress=1
jitStress=2
jitStressRegs=0x1
jitStressRegs=0x3
jitStressRegs=0x80
jitStressRegs=0x8
```

Also note that although possibly not related, there are a series of HWIntrinsic unit tests disabled because SIMD argument passing convention code was broken in 2/2018.

https://github.com/dotnet/coreclr/blob/5cdf8755129b79fa040b10c4d621e822346c3ab6/tests/src/JIT/HardwareIntrinsics/Arm64/Simd.cs#L1358

https://github.com/dotnet/coreclr/blob/5cdf8755129b79fa040b10c4d621e822346c3ab6/tests/src/JIT/HardwareIntrinsics/Arm64/Simd.cs#L1531

**Comment by sdmaclea** [comment]
Since #17111 is closed, I am closing this.

**Pull request closed without merging**
