### PR TITLE
Port to release/1.0.0: Shrink Task size by 10%

### PR DESCRIPTION
**Pull request by stephentoub**
Port of #4918 to release/1.0.0

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test OSX x64 Checked Build and Test (pal test directory was not writeable)

**Comment by joshfree** [comment]
@mmitche still seeing OS X infra issue on rerun

11:16:15 .tee: /pal_test_out: Permission denied
11:16:15 src/pal/tests/palsuite/runpaltests.sh: line 146: /pal_tests.xml.tmp: Permission denied

**Comment by mmitche** [comment]
@joshfree Attempting to fix the other issue by moving to SSH connections.  Turns out we were running all the tests as root for osx.  I fixed that but the pal test dir was still around

**Comment by mmitche** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Pull request merged**
