### PR TITLE
[ARM/Linux] Set R2R_INDIRECT_PARAM before R2R call

### LINKED ISSUE #12660: [RyuJIT/ARM32] pImportSection == pModule->GetImportSectionForRVA(rva) in DynamicHelperFixup
With COMPlus_AltJit=* COMPlus_AltJitAssertOnNYI=0 options, following assertion is observed.

```
FAILED   - [7077][   8s]readytorun/tests/genericsload/callgenericctor/callgenericctor.sh
               BEGIN EXECUTION
               Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
               Copyright (c) Microsoft Corporation.  All rights reserved.

               Native image genericslib.ni.dll generated successfully.
               Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
               Copyright (c) Microsoft Corporation.  All rights reserved.

               Native image callgenericctor.ni.exe generated successfully.
               /home/dotnet_jenkins/workspace/hqueue/Run_coreclr_tests_Checked_ryujit_nyi_all/runtime/tests/Tests/coreoverlay/corerun callgenericctor.exe

               Assert failure(PID 13694 [0x0000357e], Thread: 13694 [0x357e]): pImportSection == pModule->GetImportSectionForRVA(rva)
                   File: /opt/code/github/hqueue/coreclr/src/vm/prestub.cpp Line: 2519
                   Image: /home/dotnet_jenkins/workspace/hqueue/Run_coreclr_tests_Checked_ryujit_nyi_all/runtime/tests/Tests/coreoverlay/corerun

               ./callgenericctor.sh: line 244: 13694 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
```

## Failed tests
```
readytorun/tests/genericsload/callgenericctor/callgenericctor.sh
readytorun/tests/genericsload/usegenericfield/usegenericfield.sh
```

/cc: @dotnet/arm32-contrib

### PR DESCRIPTION
**Pull request by parjong**
Ryu JIT currently inserts R2R_INDIRECT_PARAM  load while lowering. Unfortunately, Legacy JIT has no corresponding implementation, which results in #12660.

This commit attempts to set R2R_INDIRECT_PARAM (R4 for ARM) before R2R call to fix #12660.

### CODE REVIEW

**Comment by parjong** [comment]
\CC @sjsinju

**Comment by parjong** [comment]
@BruceForstall Could you let me know how to properly spill register during codegen in Legacy JIT?

**Comment by parjong** [comment]
\CC @dotnet/arm32-contrib

**Comment by parjong** [comment]
@dotnet/jit-contrib @BruceForstall @pgavlin Please take a look.

Internal evaluation confirms that this PR resolves all the R2R test failures (#12659 and #12660), but I'm not sure whether R2R_INDIRECT_PARAM save & restore is correctly implemented.

**Comment by BruceForstall** [comment]
It looks like this would work, but it is not the "proper" fix.

It looks like the VSD code has a similar kind of problem. You should do what that does, namely: add the proper register interference (to R4 / REG_R2R_INDIRECT_PARAM) for the GT_CALL node in question, and then the register will be guaranteed to be available.

See uses of `virtualStubParamInfo->GetRegMask();`, `virtualStubParamInfo->GetReg();` and `virtualStubParamInfo->GetPredict();` in regalloc.cpp and codegenlegacy.cpp.

cc @briansull

**Comment by parjong** [comment]
@BruceForstall Updated as suggested. Could you please take a look?

**Pull request merged**
