### PR TITLE
Decorate SuperPMI DllMain jitStartup getJit with DLLEXPORT

### PR DESCRIPTION
**Pull request by echesakovMSFT**
SuperPMI collector doesn't work on Linux. DllMain, getJit and jitStartup symbol are hidden so EEJitManager won't be called to initialize AltJITCompiler in EEJitManager::LoadJIT. 

This PR makes the methods to have the same visibility as the corresponding methods in libclrjit.so have (i.e. the same as in jit/ee_il_dll.cpp)

### CODE REVIEW

**Comment by jashook** [comment]
>SuperPMI collector doesn't work on Linux. 

This has worked in the past, is this an issue due to a product change?

**Comment by echesakovMSFT** [comment]
@jashook Could be due to this change #21924, specifically https://github.com/dotnet/coreclr/pull/21924/files#diff-1bedfd692dc28379c1b150f81dd68de5

**Comment by echesakovMSFT** [comment]
@dotnet/jit-contrib PTAL

**Pull request merged**
