### PR TITLE
Fix a couple errors in the ARM32 lst file.

### PR DESCRIPTION
**Pull request by pgavlin**
- Remove an entry for a test that has been deleted
- Disable ForeignThreadExceptions against its active bug

### CODE REVIEW

**Comment by pgavlin** [comment]
@BruceForstall @jashook @RussKeldorph @dotnet/jit-contrib PTAL

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Build and Test

**Comment by pgavlin** [comment]
@dotnet-bot test Tizen armel Cross Debug Build

**Comment by jashook** [comment]
This drives our arm32 testing to green merging. Thanks for doing this!

**Pull request merged**
