### PR TITLE
Enable Go To Definition for VSCode in VM

### PR DESCRIPTION
**Pull request by danmosemsft**
This change enables VSCode to "go to definition" in the \vm\ folder. It contains no user-specific paths. 

At this point it only includes the default, Windows configuration. This alone is helpful, and we can use it as the basis for improvement. This change does not affect anyone not using VS Code with the C++ extension.

It may be possible to improve this by using the [CMAKE compile commands feature](https://cmake.org/cmake/help/v3.5/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html) to remove hard coded defines, as well as by adding more platforms and configurations and supporting the rest of the tree.

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
I have a fix for the test failing on the ARM64 leg - see https://github.com/dotnet/coreclr/pull/24539

**Comment by danmosemsft** [comment]
@aaronrobinson perhaps you'd like to review?

**Comment by jkotas** [comment]
I do not have an opinion. I do not use any of this for my day-to-day work.

**Comment by danmosemsft** [comment]
My hope is that the cruft does not build up much because we can use the cmake integration. Meantime it's just an experiment to see whether we can improve the VS Code experience for contributors.

**Comment by stephentoub** [comment]
We have cpp code in the repo not under /vm/. We also have editor related files (e.g. .editorconfig) at the root of the repo. Sould this .vscode directory be at the root, too?

**Comment by janvorli** [comment]
Nice. I've been using the same thing that I've created locally for my purposes and I haven't realized it might be something that would be worth checking in.

**Comment by janvorli** [comment]
Btw, it is not just to enable go to definition. Another value it has that it also correctly shows blocks of code under specific defines as active or inactive (displayed in dimmed colors) based on the definitions in the config file.

**Comment by danmosemsft** [comment]
>  Sould this .vscode directory be at the root, too?

I'm learning how this works but my assumption is that we need a separate folder for each unique set of include paths and defines, or some approximate group. The defines and include paths for eg., \vm and \classlibrary are not the same (although mostly the same). Eg., the latter does not define `WRITE_BARRIER_CHECK=1 `. It may not matter much in practice of course. I"ll merge this and we can refine over time.

**Comment by danmosemsft** [comment]
BTW I think this will really be valuable when they implement Find References. It is the #2 ask for the VSCode C++ plugin and it appears as if it will come soon.
https://github.com/microsoft/vscode-cpptools/issues/15

**Pull request merged**
