### PR TITLE
Fix to add error checks for crossgen compilation

### PR DESCRIPTION
**Pull request by gkhanna79**

### CODE REVIEW

**Comment by gkhanna79** [comment]
@LLITCHEV @wtgodbe Just got a change for PR testing

**Comment by LLITCHEV** [comment]
Looks fine to me.

**Comment by gkhanna79** [comment]
@dotnet-bot test OSX Release prir2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test Ubuntu Release prir2r please

**Comment by wtgodbe** [comment]
LGTM

**Comment by gkhanna79** [comment]
@dotnet-bot test CentOS7.1 x64 Checked Build please

**Comment by gkhanna79** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by gkhanna79** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by gkhanna79** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test please

**Comment by gkhanna79** [comment]
@dotnet-bot test Windows_NT x86 Debug Legacy Backend Build and Test please

**Comment by wtgodbe** [comment]
@gkhanna79 there aren't currently any trigger phrases to re-test the default per-PR jobs - if you want to run those again, you have to redo the whole test suite (T e s t   T h i s   P l e a s e)

**Comment by wtgodbe** [comment]
Whoops, just realized you're trying to test other configurations. I'll go check what the phrases are for those.

**Comment by wtgodbe** [comment]
It doesn't look like we have phrases for those jobs - you can trigger pri1 jobs by phrase, but I don't believe there are any basic pri0 jobs you can trigger by phrase.

**Comment by gkhanna79** [comment]
@dotnet-bot test OSX Release pri1r2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test Ubuntu Release pri1r2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
@dotnet-bot test Windows_NT x86 Release Legacy Backend Build and Test please

**Comment by gkhanna79** [comment]
@dotnet-bot test Ubuntu x64 Release R2R pri1 Build & Test please

**Comment by wtgodbe** [comment]
@dotnet-bot test Ubuntu Release pri1r2r please

**Comment by wtgodbe** [comment]
@dotnet-bot test Ubuntu Release pri1r2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test Ubuntu Release pri1r2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test OSX Release pri1r2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
@dotnet-bot test OSX Release pri1r2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
@dotnet-bot test Ubuntu x64 Release R2R pri1 Build & Test please

**Comment by gkhanna79** [comment]
@dotnet-bot test Ubuntu Release pri1r2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test OSX Release pri1r2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test Ubuntu Release pri1r2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test Ubuntu Release pri1r2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test OSX Release pri1r2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test OSX Release pri1r2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test Ubuntu Release pri1r2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test Windows_NT Release pri1r2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test OSX Checked pri1r2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test Ubuntu Checked pri1r2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test CentOS7.1 Release pri1r2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test Windows_NT Release pri1r2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test CentOS7.1 Checked pri1r2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test Windows_NT Release pri1r2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test CentOS7.1 Release pri1r2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test CentOS7.1 Release pri1r2r please

**Comment by gkhanna79** [comment]
Windows_NT x86 Release Legacy Backend Build and Test failed due to infra issue but had passed over the weekend and last week.

Merging the change.

**Pull request merged**
