### PR TITLE
Fix issue #2944, rounding errors in decimal.GetHashCode.

### PR DESCRIPTION
**Pull request by slavanap**
Simplify VarR8FromDec in decimal.GetHashCode in order to reduce rounding error caused by division big double by big power of 10 for decimal with big scale.
Fix issue #2944

Unfortunately I had to add `VarHashFromDec` to `oleauto.h` header file because I need constants `DECMAX` and `ds2to64` for hash computation. I know that's not a good way to do it, thus I'm open to suggestions how to reorganize these code changes if they are necessary.

### CODE REVIEW

**Comment by slavanap** [comment]
I've found this one: https://stackoverflow.com/questions/33482020/mathematical-explanation-why-decimals-conversion-to-double-is-broken-and-decima
Reconsidering solution.

**Comment by slavanap** [comment]
I'm planning to optimize multiplication with intrinsics on platforms where it's possible.

**Comment by danmosemsft** [comment]
@tannergooding

**Comment by danmosemsft** [comment]
Thanks @slavanap but I wonder whether it is worth changing the native implementation when we want to delete it : https://github.com/dotnet/coreclr/issues/18249
Maybe you'd like to contribute to that?

**Comment by slavanap** [comment]
I can do that in few days.

**Comment by jkotas** [comment]
Superseded by #18288

**Pull request closed without merging**
