### PR TITLE
Add folks to private run

### PR DESCRIPTION
**Pull request by kyulee1**

### CODE REVIEW

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64

**Comment by kyulee1** [comment]
@mmitche PTAL. It appears the above command didn't work. I guess it is effective after it is merged?

**Comment by jasonwilliams200OK** [comment]
@kyulee1, I think it is something like `@dotnet-bot test CI please`, in order to ask Bob to consider CI script changes. :smile:

**Comment by kyulee1** [comment]
@dotnet-bot test CI please

**Comment by mmitche** [comment]
@kyulee1 Yes effective after merge.

**Pull request merged**
