### PR TITLE
Add coreclr_preload_assembly to CoreCLR host API

### PR DESCRIPTION
**Pull request by kbaladurin**
This pull request adds `coreclr_preload_assembly` to host API, which loads assembly image to memory and applies relocations. `coreclr_preload_assembly` is supposed to be called only before initialization of CoreCLR.

This PR is the continuation of the https://github.com/dotnet/coreclr/pull/14227

### CODE REVIEW

**Comment by jkotas** [comment]
Is this still worth doing? This API was proposed before you have made he changes to make a lot of things relocation-free.

**Comment by kbaladurin** [comment]
@jkotas yes, this API provides ability to preload NI dlls before coreclr initialization, so we can preload libraries and fork, and it will reduce pss of application.

**Comment by jkotas** [comment]
Your team have submitted two other alternative solutions to reduce pss already: switched many pointers to be relative, and added a switch to skip relocations (`FEATURE_ENABLE_NO_ADDRESS_SPACE_RANDOMIZATION`). Do we really need a third solution to the same problem? Would it be better to fix the remaining relative pointers instead?

**Comment by alpencolt** [comment]
@jkotas as I remember it's not possible to make all pointers relative so that's why we started to use `FEATURE_ENABLE_NO_ADDRESS_SPACE_RANDOMIZATION`. But this feature doesn't guarantee that all DLLs will be loaded to specified way. And this solution not applicable in common usage since of security restriction.

Preload and `fork()` is more flexible and may give additional benefits.

**Comment by jkotas** [comment]
What are the pointers that it is not possible to make relative? I think some of them may be less straightforward, but there is nothing fundamental preventing all pointers in the images to be relative.

If we take this change, are you still going to need the relative pointers - is it going to ok to undo the relative pointer changes to simplify the code?

**Comment by alpencolt** [comment]
Using fork with absolute addresses is better option for memory consumption and performance in theory. 
But to do it we have to enable fork in production for doing this we have to overcome many barriers (like overall architecture, security, etc..).

cc @gbalykov

**Comment by maryamariyan** [comment]
Thank you for your contribution. As announced in dotnet/coreclr#27549 this repository will be moving to dotnet/runtime on November 13. If you would like to continue working on this PR after this date, the easiest way to move the change to dotnet/runtime is:
1.	In your coreclr repository clone, create patch by running `git format-patch origin`
2.	In your runtime repository clone, apply the patch by running `git apply --directory src/coreclr <path to the patch created in step 1>`

**Comment by janvorli** [comment]
@kbaladurin is there a plan to finalize this PR based on the feedback before we move to the dotnet/runtime repo tomorrow?

**Comment by kbaladurin** [comment]
@janvorli I think more time is needed to finalize this PR. Also we need to discuss this new hosting API and its relation to other pss optimizations.
cc @alpencolt

**Comment by janvorli** [comment]
@kbaladurin thank you for your response. I'm going to close the PR here and you can move the change to dotnet/runtime repo after it is open.

**Pull request closed without merging**
