### PR TITLE
Un-clang-format-horrible-ify emitIns_Call() and genEmitCall()

### PR DESCRIPTION
**Pull request by BruceForstall**
Only reformatting. No code changes.

@dotnet/jit-contrib PTAL

### CODE REVIEW

**Comment by mikedn** [comment]
Can't we actually stop clang-format from unwrapping lines? It makes sense for a formatting tool to wrap lines if they are too long but doing the opposite is rather bizarre.

**Comment by BruceForstall** [comment]
@mikedn there may be knobs we could turn off from the clang-format settings we use. I lost the fight over clang-format long ago, and am only fixing the most egregious awfulness when it impacts me.

**Comment by mikedn** [comment]
So we went from battling inconsistent code formatting piled up over the years to battling dubious code formatting imposed by a robot. Oh well, maybe we should rename clang-format to T-1000.

**Comment by pgavlin** [comment]
FWIW, I think that we could probably avoid some of these issues if we used format settings that were shared by other projects (e.g. the [Google style](https://google.github.io/styleguide/cppguide.html), which is a pack-in with `clang-format`).

LGTM, in any case, though examples like this really make me wonder about our tendency to `MACRO(parameters)`, which IMO is the more fundamental readability problem here.

**Comment by JosephTremoulet** [comment]
> this really make me wonder about our tendency to MACRO(parameters), which IMO is the more fundamental readability problem here

+1

**Pull request merged**
