### PR TITLE
Port more C# unit tests

### PR DESCRIPTION
**Pull request by richardlford**
The project files were generated automatically from a database
and the source files scrubbed and formatted.

### CODE REVIEW

**Comment by richardlford** [comment]
@pgavlin, please review.

**Comment by richardlford** [comment]
I have push a (squashed) update the removes tests that used BeginInvoke.
In addition some exclusions were added for some of the added tests
that fail.

**Comment by richardlford** [comment]
I pushed an update that does not include the changes to add the
Exclude2 option for runtest.cmd as that has been separated out
into a separate PR.

**Comment by richardlford** [comment]
@pgavlin, I pushed a change that locks the new project.lock.json. Now builds and runs fine locally.

**Comment by richardlford** [comment]
I've pushed a change to coreclr\tests\testsFailingOutsideWindows.txt
to skip tests failing on non-windows platforms.

**Comment by richardlford** [comment]
The ubuntu failure looks like an infrastructure problem.

@dotnet-bot, please retest this.

**Comment by richardlford** [comment]
Retest this please.

**Comment by richardlford** [comment]
retest this please.

**Comment by richardlford** [comment]
@pgavlin, all tests have passed now. The LLILC exclusions have been
merged. Am I ok to merge?

**Comment by pgavlin** [comment]
Yes, LGTM.

**Pull request merged**
