### PR TITLE
Refactor integer cast codegen

### PR DESCRIPTION
**Pull request by mikedn**
The ARM version of `CodeGen::genIntToIntCast` is completely different from the XARCH version, even though `GT_CAST` behaves identically on both architectures and both ISAs have very similar instructions (e.g. `movsx eax, al` and `sxtb w0, w0`). This difference can cause arch specific bugs (e.g. #18063) and makes it more difficult to improve the codegen (e.g. #12676).

`Lowering::getCastDescription` attempts to put some of the cast handling logic in a common place but it is only used by ARM codegen and anyway falls short of its goal - it provides a bunch of booleans that codegen has to figure out how to use properly (e.g. `else if (castInfo.unsignedSource || castInfo.unsignedDest)`).

It also turns out that the overflow checking logic is unnecessarily complicated due to a mix of `test` and `cmp` instructions when most of the time just `cmp` will suffice. This is especially bad on ARM32 where this translates into more complicated register requirements.

This PR started as a bit of refactoring of `genIntToIntCast` but it turned into a complete rewrite. In the end the ARM and XARCH versions ended up being so similar that I reintroduced a form of "getCastDescription" that I initially removed. The net result is that the list of individual commits and the diff itself is kind of useless, the only thing that's probably worth looking at is the final result. Hopefully this will be compensated by the fact that the rather hairy cast handling logic is in one place and the actual codegen code has become trivial.

### CODE REVIEW

**Comment by mikedn** [comment]
x64 crossgen diffs:
```
Total bytes of diff: -401 (0.00% of base)
    diff is an improvement.
Top file improvements by size (bytes):
        -106 : System.Private.CoreLib.dasm (0.00% of base)
         -80 : System.Private.Xml.dasm (0.00% of base)
         -50 : System.Memory.dasm (-0.05% of base)
         -39 : Microsoft.VisualBasic.dasm (-0.02% of base)
         -22 : System.Linq.Expressions.dasm (0.00% of base)
29 total files with size differences (29 improved, 0 regressed), 101 unchanged.
Top method improvements by size (bytes):
         -15 : Microsoft.VisualBasic.dasm - Conversions:ToSByte(ref):byte (2 methods)
         -14 : System.Linq.Expressions.dasm - Checked:ConvertUInt64(long):ref:this
          -7 : System.Linq.Expressions.dasm - Checked:ConvertInt64(long):ref:this
          -7 : System.Private.Uri.dasm - Uri:UnescapeOnly(long,int,byref,ushort,ushort,ushort)
          -6 : System.Memory.dasm - Utf8Formatter:TryFormat(int,struct,byref,struct):bool (2 methods)
231 total methods with size differences (231 improved, 0 regressed), 142693 unchanged.
```

TODO x86,arm,arm64

**Comment by mikedn** [comment]
I wasn't after CQ improvements with this but there are a couple of small ones.

There is a trivial change that affects x64 - 64-to-32 bit narrowing casts were generating 64 bit MOVs when 32 bit would be sufficient. 32 bit MOVs do not need a REX prefix an that accounts for most of the 401 bytes improvement seen on x64.

Then there are the overflow check codegen changes. `test`/`tst` instructions are now used only when they provide some benefit, otherwise `cmp` is used.

Indiscriminate use of test was just making things worse, especially on ARM32:
```diff
-            movw    r2, 0xd1ff
-            movt    r2, 0xd1ff
-            tst     r1, r2
+            cmp     r1, 0x10000
```

On ARM some max values required for overflow checking of small int type casts (32767 and 65535) cannot be encoded in the immediate operand but fortunately they can be replaced with power of 2 values (32768 and 65536) that can be encoded due to ARM's fancy imm shifting facility.

This changes apply to xarch as well but there they don't have much of an impact on codesize due immediate operand encoding being far less restrictive.

**Comment by BruceForstall** [comment]
@mikedn Are you ready to have this reviewed?

cc @dotnet/jit-contrib

**Comment by mikedn** [comment]
@BruceForstall Hmm, looks like I was, until it conflicted.

**Comment by mikedn** [comment]
@BruceForstall Conflict fixed

**Pull request merged**
