### PR TITLE
ARM: Add Ubuntu Codename vivid, wily for arm-linux image

### PR DESCRIPTION
**Pull request by seanshpark**
Add Ubuntu code name as an option to choose Ubuntu release

### CODE REVIEW

**Comment by jkotas** [comment]
@manu-silicon @benpye Could you please take a look at this change and let me know whether it looks good?

**Comment by manu-silicon** [comment]
I did not try but it looks good to me. A side node for arm-softfp, the name of the Ubuntu distribution is simply called `stable`, a better name could be chosen as `stable` could also mean the stable version of Ubuntu for any architecture.

**Comment by seanshpark** [comment]
@manu-silicon , um..., does `stable` needs change? 
\CC @papaslavik

**Comment by manu-silicon** [comment]
Since this is debian, in this particular case, since the stable version is called jessie if I'm not mistaken, why don't we do like for ubuntu and call it jessie?

**Comment by seanshpark** [comment]
I'm also curious about `stable` and don't know much about ubuntu code names. @papaslavik, can you tell about this?

**Comment by papaslavik** [comment]
Actually the scripting part was done by @kvochko let's ask his opinion.

**Comment by kvochko** [comment]
Current `stable` version of debian is indeed jessie, and it should be fine to rename it

**Comment by seanshpark** [comment]
Sure, `stable` to `jessie` done and rebased to master.

**Comment by seanshpark** [comment]
@dotnet-bot Windows_NT x86 Debug Legacy Backend Build and Test please

**Comment by seanshpark** [comment]
@dotnet-bot test Windows_NT x86 Debug Legacy Backend Build and Test

**Comment by seanshpark** [comment]
@dotnet-bot test Windows_NT x86

**Comment by seanshpark** [comment]
@jkotas , @manu-silicon , is there anything to do for this PR? or can you merge this?

**Comment by seanshpark** [comment]
Thanks!

**Pull request merged**
