### PR TITLE
[Release/3.1] Port profiler APIs to set and retrieve environment variables to 3.1

### PR DESCRIPTION
**Pull request by davmason**
This ports #27157 to 3.1.

**Issue**
On linux/unix/mac platforms the PAL creates a cache of the system environment variables at startup since accessing environment variables is not thread safe. This means that any call the `putenv` or `getenv` by native code after process startup will be ignored in managed code or any child processes spawned by managed code. 

Profilers often use environment variables to communicate with child processes or managed code, historically on Windows they could just call SetEnvironmentVariable and it would be picked up, but now on cross plat scenarios the only workaround is to use IL rewriting to inject a call to `Environment.SetEnvironmentVariable`, which is a substantial amount of work if the profiler is not already doing IL rewriting.

**Customer impact**
Without this fix profilers won't be able to coordinate with child processes while debugging. See this comment by the profiler author requesting this be included in 3.1:
>@davmason Without this, we can lost all of our features related to child processes: 1) ability to profile child processes (for details see https://github.com/dotnet/coreclr/issues/23383#issuecomment-514587669), 2) ability to take snapshots automatically depending on child processes hierarchy, 3) unit-testing profiler support. Most likely, end user experience will be significantly worsened if our "tricks" stop working.

>_Originally posted by @k15tfu in https://github.com/dotnet/coreclr/pull/27157#issuecomment-546945910_

**Fix description**
Expose the PAL's implementation of `SetEnvironmentVariable` and `GetEnvironmentVariable` on the profiler interfaces.

**Risk**
There is very low risk (essentially no risk) to existing codepaths since the existing codepaths are unchanged. This fix only exposes new functionality and does not modify existing behavior.

### CODE REVIEW

**Comment by MeiChin-Tsai** [comment]
approved for 3.1. For customer unblocking.

**Comment by k15tfu** [comment]
@davmason Do you need anything from me?

**Comment by davmason** [comment]
@k15tfu nothing is needed, it was approved and I'm waiting merge until the branch is open for checkins. The release branch is currently locked down waiting for the preview release to build

**Comment by k15tfu** [comment]
@davmason BTW, how do you generate corprof.h without all of these extra spaces I have? I use `midl src\inc\corprof.idl` from VS2017 developer console.

**Comment by davmason** [comment]
> 
> 
> @davmason BTW, how do you generate corprof.h without all of these extra spaces I have? I use `midl src\inc\corprof.idl` from VS2017 developer console.

If you build on windows midl will run automatically and you can grab corprof.h out of the obj folder, but there's no way around the whitespace issues. I don't know why midl constantly changes whitespace but it does.

**Comment by k15tfu** [comment]
@davmason Is there any ETA for 3.1-preview3?

**Pull request merged**
