### PR TITLE
Small refactoring in DateTime comparing methods

### PR DESCRIPTION
**Pull request by tarekgh**

### CODE REVIEW

**Comment by tarekgh** [comment]
@ellismg could you have a quick look? this is a small refactoring requested by @Dmitry-Me in #3227

**Comment by ellismg** [comment]
LGTM

**Comment by tarekgh** [comment]
test Ubuntu x64 Checked Build and Test please

**Comment by Dmitry-Me** [comment]
Will this not have any notable effect on performance?

**Comment by tarekgh** [comment]
@Dmitry-Me I don't think so. small methods usually get inlined by the compiler

**Pull request merged**
