### PR TITLE
Modify rebuild scenario.

### PR DESCRIPTION
**Pull request by Priya91**
cc @wtgodbe @maririos

### CODE REVIEW

**Comment by maririos** [comment]
LGTM

**Comment by wtgodbe** [comment]
LGTM

**Comment by adityamandaleeka** [comment]
Thanks. If possible, can you please add a concise explain of what it actually does? This explanation is only useful if you already understand what passing /t:Rebuild to the build projects does.

**Comment by Priya91** [comment]
> Thanks. If possible, can you please add a concise explain of what it actually does? This explanation is only useful if you already understand what passing /t:Rebuild to the build projects does.

Am not sure, can you provide the help text?

**Comment by Priya91** [comment]
Merging this PR, to unblock @ericbrumer

**Pull request merged**
