### PR TITLE
Reduce volume of MSBuild logging when running tests via xunit

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Speeds up my local LLILC testing by about 20%

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@mmitche PTAL

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by AndyAyersMS** [comment]
@dotnet-bot retest this please

**Comment by AndyAyersMS** [comment]
@mmitche ping...

**Comment by jkotas** [comment]
LGTM

**Pull request merged**
