### PR TITLE
Enable tailcall_v4\smallFrame\smallFrame

### PR DESCRIPTION
**Pull request by sandreenko**
PR #11316  removed the bad IL sequences from this test, but left these tests disabled for arm/arm64.

### CODE REVIEW

**Comment by sandreenko** [comment]
The test passed on [arm64 ](https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_checked_windows_nt_innerloop_tst_prtest/841/artifact/bin/tests/Windows_NT.arm64.Checked/Smarty.run.0/Smarty.0.pass.smrt/*view*/)and arm.

**Comment by sandreenko** [comment]
PTAL @RussKeldorph @dotnet/jit-contrib

**Comment by sandreenko** [comment]
Who uses "coreclr\tests\testsUnsupported.arm.txt" and "coreclr\tests\testsUnsupportedOutsideWindows.txt" files?

It still includes this test.

**Comment by BruceForstall** [comment]
> Who uses "coreclr\tests\testsUnsupported.arm.txt" and "coreclr\tests\testsUnsupportedOutsideWindows.txt" files?

runtest.sh

**Pull request merged**
