### PR TITLE
Update URLs and exclusion list for staging

### PR DESCRIPTION
**Pull request by A-And**
Testing the new set of test binaries.

### CODE REVIEW

**Comment by A-And** [comment]
@BruceForstall - seems Jenkins is not recognizing test logs in Ubuntu. Any idea on why it might be temperamental?

**Comment by brianrob** [comment]
@A-And it looks like all of the legs, including Ubuntu, passed.  Is there anything else needed to move forward with the refresh?  Thanks.

**Comment by A-And** [comment]
@dotnet-bot test Windows_NT x64 Release CoreFX Tests please

**Comment by BruceForstall** [comment]
> @BruceForstall - seems Jenkins is not recognizing test logs in Ubuntu. Any idea on why it might be temperamental?

not sure. can you link to a failure, or excerpt a log?

**Comment by A-And** [comment]
@BruceForstall -
Windows CI Jobs - https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_release_windows_nt_corefx_innerloop_prtest/643/ 
Ubuntu - https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_ubuntu_corefx_innerloop_prtest/1136/ 

The Test Result pane is missing on Ubuntu - I suspect the test logs aren't being found correctly. Something to do with a test directory structure change?

**Comment by BruceForstall** [comment]
The Ubuntu job doesn't archive any results: https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_ubuntu_corefx_innerloop_prtest/configure

whereas the Windows job as a couple post-build actions to archive various files, and process them via an xunit result parsing plug-in:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_release_windows_nt_corefx_innerloop_prtest/configure

**Pull request merged**
