### PR TITLE
ConsoleMandel jit benchmark

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Initial port of this benchmark.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@CarolEidt PTAL.

Let me know if you really want to benchmark all 24 variations here. If not, we can trim this back.

**Comment by AndyAyersMS** [comment]
Also I'll need to modify the behavior when launching from the command line with no args to run one or some subset of the configurations or perhaps just print usage and report success. 

Thoughts?

**Comment by AndyAyersMS** [comment]
Grr, CodeFormatter messed things up. Fixing it now... will add a default case that just does Usage since from command line you can run the variations by passing args.

**Comment by AndyAyersMS** [comment]
Updated.

**Comment by CarolEidt** [comment]
I believe that we have previously run just two of the modes (8 and 9) - i.e. the Vector Single with and without abstract data types. I don't know whether it is useful to run more.
Also, I don't now how the perf tests are generally structured, but I would have expected these files to live in their own directory - otherwise, perhaps the names should be changed to make it clear which benchmark they belong to (given that there are/will be multiple SIMD benchmarks).

**Comment by AndyAyersMS** [comment]
Updated -- moved it down one level under SIMD, only measuring modes 8 and 9.

**Comment by CarolEidt** [comment]
The "files changed" is now showing them as in both the SIMD and SIMD/ConsoleMandel directories

**Comment by AndyAyersMS** [comment]
Thanks for catching that. Fixed.

**Comment by CarolEidt** [comment]
LGTM - thanks!

**Comment by AndyAyersMS** [comment]
OSX CI still seems broken. Merging.

**Pull request merged**
