### PR TITLE
Fix ARM32/Linux release CI test failure

### PR DESCRIPTION
**Pull request by hseok-oh**
Fix ARM32/Linux release CI test failure by removing libcoreclrptprovider.so from CoreFX build result.

related issue: #10986

### CODE REVIEW

**Comment by hseok-oh** [comment]
I've confirmed this solution works well at #10987 
https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_release_ubuntu_prtest/1219/console

PTAL @gkhanna79 @jkotas @danmosemsft

**Comment by hseok-oh** [comment]
@dotnet-bot test ci

**Comment by hseok-oh** [comment]
@dotnet-bot test ci

**Comment by hseok-oh** [comment]
@dotnet-bot test ci

**Comment by danmosemsft** [comment]
If this fixes it could you please ask dotnet-bot to rerun the broken job on ask the stuck pr's? Thanks

**Comment by hseok-oh** [comment]
@danmosemsft Sure. If this commit merged, we can fix CI crash by rerun without rebase other PRs.

**Comment by gkhanna79** [comment]
I am merging this to get it unblocked.

**Pull request merged**
