### PR TITLE
[xplat] LTTNG is not availabe on all platforms

### PR DESCRIPTION
**Pull request by kangaroo**
aarch64 and arm do not have working lttng in their ubuntu/debian repos
Lets only build the eventprovider backend for amd64 for now, and we can
expand to other platforms in the future as they become supported

### CODE REVIEW

**Comment by jkotas** [comment]
The `eventprovider` test is failing on FreeBSD and OSX. I am wondering whether we need a central switch to control the event tracing, like `CLR_CMAKE_ENABLE_TRACE` from https://github.com/dotnet/coreclr/pull/2262

**Comment by gkhanna79** [comment]
CC @ramarag  and @brianrob to take  look at as well.

**Comment by jkotas** [comment]
I have included improved version of this fix in https://github.com/dotnet/coreclr/pull/2935

**Comment by kangaroo** [comment]
Happy to close this and focus there.

**Pull request closed without merging**
