### PR TITLE
[Arm64/Windows] Make r2r green in CI

### PR DESCRIPTION
**Pull request by sdmaclea**
@BruceForstall @jashook PTAL Not verified.  Based on @BruceForstall citation of most recent failing test.

### CODE REVIEW

**Comment by sdmaclea** [comment]
@dotnet-bot help

**Comment by sdmaclea** [comment]
test Windows_NT arm64 Cross Checked r2r Build and Test

**Comment by sdmaclea** [comment]
@BruceForstall I ran r2r baseline on passing PR1 tests.  I see exactly the same 3 failures.

I'll open issues.

**Comment by sdmaclea** [comment]
test Windows_NT arm64 Cross Checked r2r Build and Test

**Comment by BruceForstall** [comment]
Looks like there's a bug in netci.groovy: it's not using all the data in the `validArmWindowsScenarios` table. The smarty command doesn't contain `/exc R2R_FAIL` as expected:

```
C:\Tools\Smarty.exe /noecid /noie /workers 9 /inc EXPECTED_PASS /exc pri1 /exc LONG_RUNNING /lstFile Tests.lst 
```

It's also excluding Pri-1 tests, which I think is wrong.

I'll look into this.

**Comment by BruceForstall** [comment]
test Windows_NT arm64 Cross Checked r2r Build and Test

**Comment by BruceForstall** [comment]
test Windows_NT arm64 Cross Checked r2r Build and Test

**Comment by BruceForstall** [comment]
Seeing unrelated failures:
```
Tests.lst=DoubleGetHashCode.cmd_1368, , , Smrt00000001, , # CoreMangLib\cti\system\double\DoubleGetHashCode\DoubleGetHashCode.cmd  CATS: Pri1;RT;EXPECTED_PASS
Tests.lst=SingleGetHashCode.cmd_2434, , , Smrt00000001, , # CoreMangLib\cti\system\single\SingleGetHashCode\SingleGetHashCode.cmd  CATS: Pri1;RT;EXPECTED_PASS
```

**Pull request merged**
