### PR TITLE
Fix missing references in FEATURE_MERGE_JIT_AND_ENGINE

### PR DESCRIPTION
**Pull request by parjong**
This commit allows uses to enable FEATURE_MERGE_JIT_AND_ENGINE via command-line. 

Note that this commit does NOT change the default build.

### CODE REVIEW

**Comment by parjong** [comment]
@jkotas Is there any problem in CI? 
Ubuntu/OSX10.12 x64 Checked failure seems to be irrelevant to this PR.
and FX binaries that CI currently uses look suspicious:
```
FAILED   - JIT/Performance/CodeQuality/Span/SpanBench/SpanBench.sh
               BEGIN EXECUTION
               /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun SpanBench.exe
               TestSpanClear<Byte>(100): 0.5588ms
               TestSpanClear<String>(100): 0.0092ms
               TestArrayClear<Byte>(100): 0.0096ms
               TestArrayClear<String>(100): 0.0098ms
               TestSpanAsBytes<Byte>(100): 0.008ms
               TestSpanAsBytes<Int32>(100): 0.0084ms
               TestSpanNonPortableCast<Byte, Int32>(100): 0.0079ms
               TestSpanNonPortableCast<Int32, Byte>(100): 0.0086ms

               Unhandled Exception: System.MissingMethodException: Method not found: 'System.ReadOnlySpan`1<Char> System.SpanExtensions.AsSpan(System.String)'.
                  at Span.SpanBench.TestSpanAsSpanStringChar(String s, Int32 iterationCount, Boolean untrue)
                  at Span.SpanBench.Invoke(Action`1 innerLoop, String nameFormat, Object[] nameArgs)
                  at Span.SpanBench.Main(String[] args)
               ./SpanBench.sh: line 243: 58004 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
```

**Comment by jkotas** [comment]
> FX binaries that CI currently uses look suspicious:

We have two problems:
1. The CI is still using "live" build of CoreFX on Unix and so it is prone to these sort of breakages
2. The perf tests are hardcoded to fixed versions of CoreFX packages. This is not good because of CoreCLR and chunk of CoreFX is tightly coupled. Latest CoreCLR may not work well with CoreFX.

@wtgodbe Any thoughts about these?

Anyway, I will try to path this up in https://github.com/dotnet/coreclr/pull/12414

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by parjong** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test please

**Comment by parjong** [comment]
@dotnet/jit-contrib Please take a look

**Comment by wtgodbe** [comment]
I know @rartemev implemented package restore on non-Windows during his work to get tests building on those platforms - Roman, do you think it'd be possible to port that functionality to the current runtest.sh? That would allow us to stop relying on a live build of CoreFX in the CI.

**Pull request merged**
