### PR TITLE
[release/2.0.0][ARM] Update rootfs for Tizen armel

### PR DESCRIPTION
**Pull request by hqueue**
*This PR is duplicate of https://github.com/dotnet/coreclr/pull/11202 in master branch.*

This is required to build CoreCLR for Tizen armel as a part of .NET Core 2.0.0 for Tizen.

Existing rootfs for armel Tizen is out-of-dated and not suitable for .NET Core 2.0.0 for Tizen.

Two changes are made.
* Update rootfs for Tizen armel to recent version
* Updates CI for Tizen armel to make use of a prebuilt embedded rootfs as Ubuntu arm does.

Please merge this PR before related PR in corefx and core-setup.

Relate PRs:
https://github.com/dotnet/corefx/pull/19085
https://github.com/dotnet/core-setup/pull/2219

### CODE REVIEW

**Comment by hqueue** [comment]
CC @leecow @gkhanna79

**Comment by gkhanna79** [comment]
@hqueue As I mentioned in https://github.com/dotnet/coreclr/pull/11202#issuecomment-297909225, are you okay to bake this change first in master and not port it to release/2.0.0?

**Comment by hqueue** [comment]
> are you okay to bake this change first in master and not port it to release/2.0.0?

@gkhanna79 Just postpone scheudle of merging this PR to release/2.0.0 some days ? or meaning this PR is not included in release/2.0.0 ? 
If you meant latter case, then I'm afraid not, because .NET Core 2.0.0 for Tizen should runs on Tizen rootfs which is included in this PR.

If you are worrying about stability, then this PR affects (1) behavior of  build-rootfs.sh for Tizen armel and (2) behavior of Tizen armel CI. No other side effect is introduced.

**Comment by gkhanna79** [comment]
@hqueue Yes, my suggestion is to merge this in master for now. When we make master 2.1 on 5/10 (as I explained at https://github.com/dotnet/coreclr/issues/11248), this change (and the related CoreFX and Core-Setup changes) will automatically get into release/2.0.0 branch for our Preview2 release. 

Currently, we are out of runway to merge changes into release/2.0.0 which contains payload for Preview1 release.

**Comment by gkhanna79** [comment]
Closing per my comment above.

**Pull request closed without merging**
