### PR TITLE
Fix LLDB header related build error on FreeBSD

### PR DESCRIPTION
**Pull request by ajensenwaud**
Fixed lldb header related build errors on FreeBSD (this timearound with no platform specific includes)

### CODE REVIEW

**Comment by ajensenwaud** [comment]
Thanks @jkotas. I just submitted a new PR, which addresses this.

**Comment by josteink** [comment]
If I were to make a nit, it would be that the commits should be squashed.

**Comment by ajensenwaud** [comment]
You are right, please disregard this PR and use https://github.com/dotnet/coreclr/pull/819 instead.

**Comment by josteink** [comment]
@ajensenwaud For future reference I usually do this to squash commits:

````bash
# to merge the last 2 commits in the current branch into one
git rebase -i HEAD~2 
# set last commit to "squash" or "fixup"

# overwrite PR-branch where I've been asked to fix issues with my PR.
git push --force remote
````

This combines the commits into one and in the case of `squash` lets you rewrite the commit-message. It then pushes a forced update to  the PR-branch, causing a single, new, clean commit to be ready and reviable to everyone else.

If you're coming from an hg world it might be different, but once you get used to it, it's not that bad :)

**Pull request closed without merging**
