### PR TITLE
Use logf() instead of JitDump()

### PR DESCRIPTION
**Pull request by BruceForstall**
This allows more JitDump output to get routed through the CLR
logging facility.

### CODE REVIEW

**Comment by BruceForstall** [comment]
cc @dotnet/jit-contrib

**Comment by pgavlin** [comment]
Where is `logf` defined?

**Comment by BruceForstall** [comment]
> Where is logf defined?

error.cpp

**Comment by pgavlin** [comment]
> error.cpp

Ah, yep. I'm not familiar with the EE's logging capabilities--what effect does this have?

**Comment by BruceForstall** [comment]
For the JIT, it means JitDump can be redirected to a file or the debugger, e.g.:
```
set COMPlus_LogEnable=1                                                                                                                                             set COMPlus_LogToFile=1                                                                                                                                             set COMPlus_LogFile=c:\dump.txt                                                                                                                          set COMPlus_LogFileAppend=                                                                                                                                          set COMPlus_LogToConsole=                                                                                                                                           set COMPlus_LogWithPid=                                                                                                                                             set COMPlus_LogLevel=a                                                                                                                                                                                                                                                                                                                  @REM LF_JIT           0x00000008                                                                                                                                    set COMPlus_LogFacility=8                                         
```

Note that the JIT's `printf` is really `logf`.

**Comment by pgavlin** [comment]
> For the JIT, it means JitDump can be redirected to a file or the debugger, e.g.:

Neat! Thanks for the explanation.

**Comment by briansull** [comment]
LGTM

**Pull request merged**
