### PR TITLE
Enable Ubuntu x64 Release test runs in CI by default

### PR DESCRIPTION
**Pull request by adityamandaleeka**
This change changes the CI configuration so we will now run the CoreCLR tests on Ubuntu with x64 Release bits by default. The remaining configurations (x86, Debug, and x86 Debug) will still require trigger phrases to launch.

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
test ci please

**Comment by adityamandaleeka** [comment]
Note: please don't merge until we start getting consistent runs from this with no git issues.

**Pull request merged**
