### PR TITLE
Fix GCStress modes that do code instrumentation to work with code versioning

### PR DESCRIPTION
**Pull request by kouvel**
- SOS changes are in dotnet/diagnostics#369
- Fixes https://github.com/dotnet/coreclr/issues/17646

### CODE REVIEW

**Comment by kouvel** [comment]
Ping for review please

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib 

Do we have any GcStress CI that runs with tiering enabled? If not, we should add it....

**Comment by jashook** [comment]
Based on: https://github.com/dotnet/coreclr/blob/master/tests/testenvironment.proj#L112 we are not setting TieredCompilation, so it should use the default value.

**Comment by BruceForstall** [comment]
TieredCompilation=0 is the default: https://github.com/dotnet/coreclr/blob/c81d3caee2cfd7a401429dea9709acc18064acdd/tests/testenvironment.proj#L50

So, we always have tiering disabled for GCStress legs

**Pull request merged**
