### PR TITLE
ARM64: Another round of clean-up Tests.lst

### PR DESCRIPTION
**Pull request by kyulee1**
- Removed UNSTABLE category completely
- Tag more issues to failure cases

### CODE REVIEW

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Release

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Release

**Comment by kyulee1** [comment]
@dotnet/arm64-contrib PTAL

**Comment by briansull** [comment]
LGTM

**Pull request merged**
