### PR TITLE
JIT: fix some bad asserts

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Fix a few asserts that use = instead of ==.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@JosephTremoulet PTAL
cc @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
Yikes!

LGTM

**Comment by briansull** [comment]
The compilers really should be flagging this and the other case (possibly with warning as errors)

if (i = 0)

**Comment by briansull** [comment]
LGTM

**Comment by adityamandaleeka** [comment]
😮 LGTM

**Pull request merged**
