### PR TITLE
Introduce FEATURE_CONSERVATIVE_VSD_CALL

### LINKED ISSUE #14031: [ARM/Linux] Segmentation fault inside SIGSEGV signal handler
We often see the following segmentation fault in ARM/Linux:
```
Program received signal SIGSEGV, Segmentation fault.
0xf76e0ee2 in VirtualCallStubManager::predictStubKind(unsigned int) () from /home2/parjong/projects/dotnet/dotnet-overlay/Linux.x86.Release.Release/libcoreclr.so
(gdb) bt
#0  0xf76e0ee2 in VirtualCallStubManager::predictStubKind(unsigned int) () from /home2/parjong/projects/dotnet/dotnet-overlay/Linux.x86.Release.Release/libcoreclr.so
#1  0xf76e902e in VirtualCallStubManager::getStubKind(unsigned int) () from /home2/parjong/projects/dotnet/dotnet-overlay/Linux.x86.Release.Release/libcoreclr.so
#2  0xf76e4b7f in VirtualCallStubManager::FindStubManager(unsigned int, VirtualCallStubManager::StubKind*) () from /home2/parjong/projects/dotnet/dotnet-overlay/Linux.x86.Release.Release/libcoreclr.so
#3  0xf77a03d0 in IsSafeToHandleHardwareException(_CONTEXT*, _EXCEPTION_RECORD*) () from /home2/parjong/projects/dotnet/dotnet-overlay/Linux.x86.Release.Release/libcoreclr.so
#4  0xf7a1be08 in SEHProcessException(PAL_SEHException*) () from /home2/parjong/projects/dotnet/dotnet-overlay/Linux.x86.Release.Release/libcoreclr.so
#5  0xf7a1d4c7 in common_signal_handler(int, siginfo_t*, void*, int, ...) () from /home2/parjong/projects/dotnet/dotnet-overlay/Linux.x86.Release.Release/libcoreclr.so
#6  0xf7a1d30e in signal_handler_worker () from /home2/parjong/projects/dotnet/dotnet-overlay/Linux.x86.Release.Release/libcoreclr.so
#7  0xf7a58497 in CallSignalHandlerWrapper12 () from /home2/parjong/projects/dotnet/dotnet-overlay/Linux.x86.Release.Release/libcoreclr.so
#8  0x00000007 in ?? ()
```

I could reproduce this issue with the following code:
 - Program.cs
```cs
using System;
using System.Reflection;
using System.Runtime.Loader;
using System.Runtime.InteropServices;

namespace ReversePInvoke
{
    class Program
    {
        [DllImport("libmiddle.so")]
        static extern int Invoke(int n);

        static void Main(string[] args)
        {
            Invoke(0);
        }
    }
}
```
 - native.c
```c
#include <stdio.h>

typedef void (*cb_t)(int);

int Invoke(int n)
{
    printf("Invoke!\n");
    cb_t fn = (cb_t)0x7;
    fn(4);
    return 0;
}
```

The issue itself comes from native code, but coredump debugging would be much easier if CLR's signal handler does not crash for this case.

### PR DESCRIPTION
**Pull request by parjong**
FEATURE_CONSERVATIVE_VSD_CALL enforces Legacy JIT to emit null-check before VSD call to fix #14031.

This commit does not change the default behavior. The changed behavior will be enabled only when CLR is built with FEATURE_CONSERVATIVE_VSD_CALL.

### CODE REVIEW

**Comment by parjong** [comment]
@dotnet/arm32-contrib @jkotas @janvorli Could you please take a look?

**Comment by janvorli** [comment]
@jkotas, the issue happens due to the `VirtualStubManager::getStubKind` using the `predictStubKind` that peeks to the code at the failing address as an optimization measure. I wonder if a better solution 
than emitting a null check before the VSD call would be to add an extra `bool` argument to the `getStubKind` that would disable the call to `predictStubKind`. We would need to add the same argument to the `VirtualCallStubManager::FindStubManager` too and pass it as `true` only from the `IsSafeToHandleHardwareException`. During hardware EH, we don't care about the fact that the non-optimized lookup is slower.

**Comment by jkotas** [comment]
> add an extra bool argument to the getStubKind

Yes, I agree that this would be better. It will make work well by default without need for a new `FEATURE` flag.

**Comment by parjong** [comment]
Close this PR as #14051 is submitted.

**Pull request closed without merging**
