### PR TITLE
Beef up / clean up GenTree struct info dumps.

### PR DESCRIPTION
**Pull request by pkukol**
Moves most of the GenTree dump stuff from compiler.cpp into gentree.cpp, dumps a lot more info, fixes a few things; all of this is #if'd out by default.

Y'all PTAL ... @pgavlin @BruceForstall @CarolEidt
/cc @dotnet/jit-contrib

### CODE REVIEW

**Comment by mikedn** [comment]
> Moves most of the GenTree dump stuff into compiler.cpp

It seems that it's the other way around, moves from compiler.cpp to gentree.cpp. And I wonder if all this dump/debug stuff shouldn't be moved to a "dump.cpp" file...

Do we really need all this? As far as I can tell this code dumps the size and layout of various interesting structs. This can also be done with a small tool that reads the information from the PDB files, without having to add more code to the compiler.

**Comment by pkukol** [comment]
@mikedn , thanks for catching the typo and commenting. For background, the long term plan is that many of these will turn into (effectively) regression tests that auto-magically raise an alarm whenever things get bigger (or whatever we think we should guard against); it is also agreed that not everything I've found useful for my work should necessarily be accepted into the "real" code base. As for this one specifically, I did look into grocking over PDB's - since that has a number of obvious advantages - but I confess that last time I messed with CodeView debug info was back in 1995 and things have changed enough since then that it might take too much time to learn the new ways (plus, using debug info has its own set of issues, of course - dealing with different toolchains, etc). Having said that, if the consensus is that this change doesn't meet the bar, I'm happy to just open a low-pri issue to do something in the future (assuming we agree that we do need to watch for this stuff without asking devs to jump through hoops to detect potential problems). Hope this makes sense.

**Comment by mikedn** [comment]
> plus, using debug info has its own set of issues, of course - dealing with different toolchains, etc

Yep, that's the biggest issue with reading debug info, we'd probably need a tool that works with both PDBs and whatever debug information is generated by Linux/OSX compilers.

> As for this one specifically, I did look into grocking over PDB's - since that has a number of obvious advantages - but I confess that last time I messed with CodeView debug info was back in 1995 and things have changed enough since then that it might take too much time to learn the new ways

In case you want to explore this approach here's a quick C# [tool](https://gist.github.com/mikedn/855ba343214ebf5b700cac6326581c35) I recently wrote when I was trying to find alignment gaps in GenTree and a few other compiler structures.

> assuming we agree that we do need to watch for this stuff without asking devs to jump through hoops to detect potential problems

IMO yes, one way or another we should keep an eye on this kind of stuff. We can't expect developers to count bits and figure out that, for example, if one additional bit is added to `TreeNodeInfo` then the size of `GenTree` increases by 8 bytes.

**Comment by pgavlin** [comment]
@pkukol @mikedn 

> > plus, using debug info has its own set of issues, of course - dealing with different toolchains, etc
>
> Yep, that's the biggest issue with reading debug info, we'd probably need a tool that works with both PDBs and whatever debug information is generated by Linux/OSX compilers.

In principle this shouldn't be too difficult to deal with if we're willing to depend on LLVM's object reader. It is able to read DWARF symbols and IIRC can now read PDBs as well.

> > assuming we agree that we do need to watch for this stuff without asking devs to jump through hoops to detect potential problems
>
> IMO yes, one way or another we should keep an eye on this kind of stuff. We can't expect developers to count bits and figure out that, for example, if one additional bit is added to TreeNodeInfo then the size of GenTree increases by 8 bytes.

I agree. Frankly, this is the primary problem I have with this change: it adds further overhead to the process of adding/updating/etc. IR nodes, as each node type now needs to be properly represented in the code that dumps node layouts as well. I'd much rather see a small, cross-platform static analysis tool (besides the C++ compiler ;)) do this job.

**Comment by pkukol** [comment]
@mikedn , that little utility is a good starting point - thanks for posting it. Now that I've thought about it a lot more, it may not be a bad idea to try both avenues for a while and see what works best (anything we do will be 100% optional to begin with anyway, I assume). The code I added to gentree.cpp doesn't cost anything in the resulting binary but it does add a lot more text to the source etc which is certainly not completely without cost, so we could move it out into a .hpp file that is only #include'd when the macro is enabled, or alternatively we could stuff it at the end of gentree.h (since the hope is that when people mess with things in there that's the time to update the dumping code and also make sure no bad surprises have been introduced), or we could say that everything to do with GenTree sizes / layout should be in one place where folks won't miss it. Thoughts, please @pgavlin @BruceForstall @CarolEidt .

**Comment by pkukol** [comment]
@pgavlin and @mikedn - can I at least keep the little loop that prints out the GenTree flavor sizes? This replaces the long (and always incomplete) list of individual printf's that we have today. I'll create an issue to write the little utility some day.

**Comment by pgavlin** [comment]
@pkukol: SGTM

**Pull request closed without merging**
