### PR TITLE
[release/2.1] JIT: Fix bug in finally cloning caused by unsound callfinally reordering

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Port of #18348 to release 2.1.

Related issue #18332. Not a regression. This optimization was introduced
in 2.0 and the bug has been there from the beginning.

We need to make sure that if we reorder a callfinally during finally cloning
that the callfinally is actually the one being targeted by the last block in
the try range.

Linked issue has some more detailed notes.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
Formatting leg is building latest jitutils which now requires a 2.1 CLI.

Either need to port the "use 2.1 CLI" fix for the formatter over too, or modify the formatting leg to pull an older hash of jitutils.

**Comment by AndyAyersMS** [comment]
Going to retest...

@dotnet-bot retest this please

**Comment by AndyAyersMS** [comment]
@danmosemsft can I update the label to 2.1 approved or should somebody official be doing that?

**Comment by danmosemsft** [comment]
@AndyAyersMS I think the "approved" label is probably not adding much value. Just ignore, we should probably delete it.

**Comment by danmosemsft** [comment]
This is approved and good to submit though

**Comment by AndyAyersMS** [comment]
@dotnet/dnceng  @jashook arm/arm64 jobs don't seem to be getting scheduled, can somebody investigate? For instance: [arm64_cross_checked_windows_nt_innerloop_tst_prtest](https://ci.dot.net/job/dotnet_coreclr/job/release_2.1/job/arm64_cross_checked_windows_nt_innerloop_tst_prtest/)

**Comment by jkotas** [comment]
You can fix that by closing and opening the PR again so that it picks up updated CI definition. 

However, it is still going to fail on ARM64. The ARM64 leg is not clean in the release/2.1 branch. We should consider disabling it. This leg does not actually run for most PRs by default - it is triggered by default for PRs done by folks on the ARM64 contributor lists only.

**Comment by mmitche** [comment]
@AndyAyersMS Most of the arm64 machines are offline.  @jashook can you take a look?

**Comment by AndyAyersMS** [comment]
Ok, ignoring arm64 failure.

**Pull request merged**
