### PR TITLE
Implement regression test for hardware exception handling on Unix

### PR DESCRIPTION
**Pull request by janvorli**
This implements regression test for issue fixed by #1700

### CODE REVIEW

**Comment by janvorli** [comment]
Implements #1703
@jkotas can you take a look please?

**Comment by krytarowski** [comment]
Looks useful, there are issues with it on NetBSD.

**Comment by jkotas** [comment]
There are like 100 tests that check different permutations of null reference exceptions. The problem is that we have not been running the CoreCLR tests back in October. I do not think we need yet another one.

E.g. \coreclr\tests\src\Regressions\coreclr\0014\avtest.cs looks exactly like what you are adding here.

**Comment by janvorli** [comment]
Ok, makes sense. But then we need to enable these tests. Nothing under tests\src\Regressions\coreclr is still being executed as none of them is referenced by the tests/src/AllTestProjects.sln.

**Comment by jkotas** [comment]
tests/src/AllTestProjects.sln is just a convenience file that somebody added for hacking on the tests in visual studio. It is very outdates, and it is not what we use to control which tests to run.

The test runner does recursive directly search for all tests. Presence of the test is sufficient to add it to the test runs.

**Comment by janvorli** [comment]
Closing this issue. I will rather make one of the existing tests priority zero so that it is run in the lab.

**Pull request closed without merging**
