### PR TITLE
Reduce case iteration counts in SeekUnroll.

### PR DESCRIPTION
**Pull request by pgavlin**
This test was taking too long to run on x86. After investigation, it
does not appear that there is a fundamental problem with the code
generated for the test; rather, it seems that we are running an
excessive number of iterations when using this test as a correctness
test. This change reduces the number of times we run each case from 10
to 1 unless otherwise specified on the command line.

[Here is an example of a job where this test has hit the timeout.](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x86_release_windows_nt/967/)

### CODE REVIEW

**Comment by pgavlin** [comment]
@JosephTremoulet @AndyAyersMS @dotnet/jit-contrib PTAL

**Comment by pgavlin** [comment]
cc @RussKeldorph

**Comment by pgavlin** [comment]
> Seems more sensible to me to reduce InnerIterations for x86 rather than do this...

What value do you see in running all 5 cases for 10 iterations each during a normal test run? Note that this change does not affect the iteration count when running as a perf test.

> Also if x64 does not time out it is probably worth opening an issue to better understand why x86 does.

I've already looked into this. The root cause appears to be due to the fact that we retire about 5-6x as many instructions on x86 due to the use of longs in `FindByte`. The primary differences are the decomposed index into a `Vector<long>` and the use of a helper call to multiply two longs. The former is especially impactful, as it accounts for 20 extra instructions per call to `FindByte` (or ~1 trillion extra instructions over the entire test).

**Comment by AndyAyersMS** [comment]
In the past we've tried to keep these tests somewhat viable as benchmarks when run as exes. I suppose getting back just one timed result by default might be suggestive enough to remember that this test needs extra inputs to trigger benchmark mode, and one can go look at the sources and see how to make that happen. So unless @JosephTremoulet chimes in I'll leave it up to you to decide what to do.

**Comment by JosephTremoulet** [comment]
Or the test could just print out something like "command-line argument IterationCount not supplied; defaulting to 1 iteration", that ought to be "suggestive enough to remember that this test needs extra inputs to trigger benchmark mode".

**Comment by pgavlin** [comment]
> Or the test could just print out something like "command-line argument IterationCount not supplied; defaulting to 1 iteration"

Good suggestion. I will make that change.

**Pull request merged**
