### PR TITLE
Add R2R outerloop test mode without any stress modes

### PR DESCRIPTION
**Pull request by fadimounir**
@sandreenko PTAL. Is this the right way of adding an R2R test mode without any stress mode?

### CODE REVIEW

**Comment by fadimounir** [comment]
@BruceForstall @echesakov Could you please take a look? I'm trying to add a mode where we simply run R2R without any stress mode. I'm not super familiar with the infra scripts, so let me know what's the right way to do that.
My understanding is that the current state of the outerloop-r2r-extra runs will give a set of R2R results for the no_tiered_compilation mode, in addition to all the various jitstress modes that exist, is that right?

**Comment by echesakovMSFT** [comment]
After talking with Fadi I am convinced that we should have a separate "coreclr-outerloop-r2r" build definition triggerable from PR by **a.z.p  r.u.n** command that will run only normal and no_tiered_compilation

**Comment by echesakovMSFT** [comment]
@fadimounir This can be done the following way:
1. Add this block in /azure-pipelines.yml 
```
        ${{ if eq(variables['Build.DefinitionName'], 'coreclr-outerloop-r2r') }}:
          testGroup: outerloop
          readyToRun: true
          displayNameArgs: R2R
```
2. Change this condition `${{ if in(variables['Build.DefinitionName'], 'coreclr-outerloop-gcstress0x3-gcstress0xc', 'coreclr-outerloop-gcstress-extra', 'coreclr-outerloop-r2r-extra') }}:` to include coreclr-outerloop-r2r scenario for build and test jobs
3. Add the corresponding build definition in Azure DevOps UI with appropriately set triggers

Come to ask me or @sandreenko if you need help with the last or other steps

**Comment by fadimounir** [comment]
Yep. Your suggested changes are what I had initially proposed in this PR. I'm currently updating the PR with them and will ping you for the last step.

**Comment by fadimounir** [comment]
I've also changed the timeout values to be equal to the regular non-stress modes. Crossgen runs pretty fast on the test assemblies

**Pull request merged**
