### PR TITLE
Integration from dev/local-gc into master

### PR DESCRIPTION
**Pull request by swgillespie**
Now that master is back open for feature work, we can merge dev/local-gc back into it. This PR contains all of the relevant commits that have gone into the feature branch since it opened, rebased against master. PRs https://github.com/dotnet/coreclr/pull/11379 and https://github.com/dotnet/coreclr/pull/11628 are still pending against dev/local-gc, so those will be added to this PR once they merge.

Marking as no merge initially, since there are still outstanding commits that will be rolled into this PR.

cc @sergiy-k @Maoni0 @adityamandaleeka

### CODE REVIEW

**Comment by swgillespie** [comment]
@dotnet-bot test test Windows_NT Checked standalone_gc
@dotnet-bot test test OSX10.12 Checked standalone_gc
@dotnet-bot test test Ubuntu Checked standalone_gc

**Comment by swgillespie** [comment]
@dotnet-bot test Tizen armel Cross Release Build

**Comment by swgillespie** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test

**Comment by swgillespie** [comment]
@dotnet-bot test Windows_NT Checked gc_reliability_framework

**Comment by swgillespie** [comment]
The last commit should be the final commit that's present in dev/local-gc. Once everything looks good, we can merge this PR and delete the branch.

**Comment by swgillespie** [comment]
@dotnet-bot test Windows_NT Checked standalone_gc
@dotnet-bot test OSX10.12 Checked standalone_gc
@dotnet-bot test Ubuntu Checked standalone_gc

**Comment by swgillespie** [comment]
@dotnet-bot test Windows_NT Checked standalone_gc
@dotnet-bot test OSX10.12 Checked standalone_gc
@dotnet-bot test Ubuntu Checked standalone_gc

**Comment by swgillespie** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test (remoting error)

**Comment by swgillespie** [comment]
Hmm, looks like this PR broke Tizen armel. @mmitche would you know how we'd go about getting a repro environment for Tizen?

**Comment by swgillespie** [comment]
Trying to see if this repros...

@dotnet-bot test Tizen armel Cross Debug Build [failed](https://ci.dot.net/job/dotnet_coreclr/job/master/job/armel_cross_debug_tizen_prtest/3054/)
@dotnet-bot test Tizen armel Cross Release Build [failed](https://ci.dot.net/job/dotnet_coreclr/job/master/job/armel_cross_release_tizen_prtest/3035/)

**Comment by swgillespie** [comment]
Ok, then!

cc @Maoni0 @adityamandaleeka @sergiy-k @jkotas - any objections/feedback about merging this? All of the commits in here have been reviewed in separate PRs already (except https://github.com/dotnet/coreclr/pull/11699/commits/0597a34b570d359d34a03c74e1007025c43ae7e8 , which fixed some warnings on 32-bit platforms).

**Comment by jkotas** [comment]
👍

**Comment by Maoni0** [comment]
no objections from me!

**Comment by swgillespie** [comment]
Great, thanks!

**Pull request merged**
