### PR TITLE
An UnusedValue still requires a target reg

### PR DESCRIPTION
**Pull request by CarolEidt**
The BuildSimple method wasn't creating a def for an unused value. Although (in this case) the code is dead, the code generator must still be able to generate code for it.

### CODE REVIEW

**Comment by CarolEidt** [comment]
The test case here was a small repro that @sandreenko found using ILGEN on desktop. It gets the same assert as #18295, but I still need to validate that it fixes that case.

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL
@jashook - can you help me understand why the AVX/MaskLoad tests are still being run? The associated csproj files were deleted in #17637, which was merged 2 days ago, but they still show up failing on the arm and arm64 legs.

**Comment by jashook** [comment]
It is most likely because they need to also be removed from the .lst files as well. Will open a pr in a little addressing it.

**Comment by CarolEidt** [comment]
@jashook - should I add this test to the arm/arm64 test lst files as well?

**Comment by jashook** [comment]
Yes please :)

**Pull request merged**
