### PR TITLE
Changes to use VNNormalValue in assertionProp

### PR DESCRIPTION
**Pull request by briansull**
Removed the excSet argument to the constant folding EvalOp methods.
We no longer will fold an expression when an exception must be generated.
Don't ignore the unsigned flag when trying to fold overflow checking casts.

### CODE REVIEW

**Comment by briansull** [comment]
@dotnet-bot Test Windows_NT x64 Formatting

**Comment by briansull** [comment]
@AndyAyersMS PTAL
@dotnet/jit-contrib  PTAL

**Comment by AndyAyersMS** [comment]
Is this change simplifying things because a prior change removed the need to check for exceptions, or is this change implementing new policy? I assume the former since the code diffs so far look fairly mechanical and you're not adding any new tests or resolving open issues.

Can you run diffs when you get a chance?

It seems like introducing yet a method to capture `vnStore->VNNormalValue(vn, VNK_Conservative)` would make the code more readable, eg `vnStore->vnNormalConservativeValue(vn)` ?

**Comment by briansull** [comment]
I have an upcoming change that adds a lot of execrption sets to the nodes.  
This change makes the assertion prop logic use the normal values when performing assertion prop.

This change has no AsmDiff's 

I have VNNormalValue which takes a ValueNum and another one that takes a ValueNumPair.
When you have a ValueNumPair you need to specific which part ofthe Pasir you want the normal valeu for so that what I have done here.

**Comment by AndyAyersMS** [comment]
Right, I get that -- I am suggesting rather than repeating `vnStore->VNNormalValue(vn, VNK_Conservative)` over and over you introduce yet another helper for it ....

**Comment by briansull** [comment]
@AndyAyersMS PTAL
 Updated as you requested.

**Comment by briansull** [comment]
@dotnet-bot Test Windows_NT x64 Formatting

**Comment by AndyAyersMS** [comment]
There are still lots of instances of this to update in assertinprop.cpp.

**Pull request merged**
