### PR TITLE
Move ArrayPool to System.Private.CoreLib

### PR DESCRIPTION
**Pull request by JeremyKuhne**
Copy ArrayPool source from CoreFX and expose in System.Private.CoreLib.

This is part of facilitating the move of FileStream.
https://github.com/dotnet/corefx/issues/12810

@ianhays, @stephentoub, @sokket, @jkotas

### CODE REVIEW

**Comment by JeremyKuhne** [comment]
@dotnet-bot Test this please (Jenkins rebooted)

**Comment by ericstj** [comment]
It looks ok to me.  In corefx we'll want to cross-compile buffers for netcoreapp1.1 as a partial facade.

**Comment by JeremyKuhne** [comment]
@ianhays This was just a straight copy, except for the string resource.

**Comment by jamesqo** [comment]
Awesome! We should definitely look into using this for the default `Stream.CopyTo` / `CopyToAsync` impl.

**Comment by jkotas** [comment]
@Maoni0 The ArrayPool is part of CoreLib now .... it may be interesting to look into whether it would be  worth it to make GC aware of it, to get better perf characteristics.

**Comment by Maoni0** [comment]
thanks Jan. @vancem did a pinnable buffer pool implementation. I can see some of the heuristics being used in this buffer pool as impl well. it goes the other way - it's aware of GCs happening; we can look at it from that direction first.

@swgillespie @adityamandaleeka

**Pull request merged**
