### PR TITLE
JIT: modify inline budget update to use estimated imported IL size

### LINKED ISSUE #21794: Vector128/256<T>: Too many calls to "ThrowIfUnsupportedType" prevents inlining
I am trying to optimize certain generic helpers of `Vector128/256<T>` by HW intrinsic and other helpers, which relies on inlining to get the optimal codegen. However, sometimes these helpers cannot get inlined due to "inline exceeds budget" because too many `ThrowIfUnsupportedType` need to be eliminated by inlining. This issue may give users unexpected codegen when they heavily use generic `Vector128/256<T>` helpers (e.g., `Count`, `GetLower`, etc.)
https://github.com/dotnet/coreclr/blob/10c3e60c863d01f638daa240af957c3c5791cda5/src/System.Private.CoreLib/shared/System/Runtime/Intrinsics/Vector256_1.cs#L342-L347
https://github.com/dotnet/coreclr/blob/10c3e60c863d01f638daa240af957c3c5791cda5/src/System.Private.CoreLib/shared/System/Runtime/Intrinsics/Vector256_1.cs#L78-L103

We need to find an approach to reduce the number of `ThrowIfUnsupportedType` call-site.

@CarolEidt @tannergooding @eerhardt @AndyAyersMS

### PR DESCRIPTION
**Pull request by AndyAyersMS**
The inliner keeps a time budget to try and avoid pathological runaway inline
behavior (see #4375). The jit estimates the time impact of an inline using a
simple projection based on IL size. If an prospective inline would put the jit
over the time budget, the inline is blocked -- and note even aggressive inlines
can be blocked this way.

We now have a fair number of aggressive inline methods like
`Vector256<T>.IsSupported` where the IL is optimized early on by the jit and the
actual impact on the calling method is much less than the initial IL size would
suggest. For instance `IsSupported` is 286 bytes of IL, but the net contribution
of this method at jit time is either a constant 0 or 1, and so the effective size
is more like 2 bytes of IL.

This set of changes updates the jit to estimate the imported IL size of a method
when updating the budget.

Closes #21794.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@briansull PTAL
cc @fiigii @dotnet/jit-contrib 

PMI diffs shows a few HW intrinsic methods impacted in a good way. Other diffs are for methods where aggressive inlines were blocked and now are unblocked.

```
Total bytes of diff: -790 (0.00% of base)
    diff is an improvement.

Top file regressions by size (bytes):
        1893 : System.Security.Cryptography.X509Certificates.dasm (1.14% of base)
         346 : System.Memory.dasm (0.21% of base)
          19 : System.Net.Http.dasm (0.00% of base)

Top file improvements by size (bytes):
       -3048 : System.Private.CoreLib.dasm (-0.08% of base)

4 total files with size differences (1 improved, 3 regressed), 125 unchanged.

Top method regressions by size (bytes):
        1373 (27.93% of base) : System.Security.Cryptography.X509Certificates.dasm - AsnWriter:WriteUtcTimeCore(struct,struct):this
         520 ( 4.80% of base) : System.Security.Cryptography.X509Certificates.dasm - AsnWriter:WriteGeneralizedTimeCore(struct,struct,bool):this
         346 (10.88% of base) : System.Memory.dasm - BuffersExtensions:ToArray(byref):ref (5 methods)
          19 ( 2.08% of base) : System.Net.Http.dasm - HttpConnection:WriteDecimalInt32Async(int):ref:this

Top method improvements by size (bytes):
        -878 (-41.34% of base) : System.Private.CoreLib.dasm - Vector64`1:Equals(struct):bool:this (4 methods)
        -581 (-31.89% of base) : System.Private.CoreLib.dasm - Vector128`1:<Equals>g__SoftwareFallback|22_0(byref,struct):bool (4 methods)
        -581 (-31.89% of base) : System.Private.CoreLib.dasm - Vector256`1:<Equals>g__SoftwareFallback|24_0(byref,struct):bool (4 methods)
        -336 (-32.34% of base) : System.Private.CoreLib.dasm - Vector64`1:GetHashCode():int:this (4 methods)
        -336 (-32.28% of base) : System.Private.CoreLib.dasm - Vector128`1:GetHashCode():int:this (4 methods)

Top method regressions by size (percentage):
        1373 (27.93% of base) : System.Security.Cryptography.X509Certificates.dasm - AsnWriter:WriteUtcTimeCore(struct,struct):this
         346 (10.88% of base) : System.Memory.dasm - BuffersExtensions:ToArray(byref):ref (5 methods)
         520 ( 4.80% of base) : System.Security.Cryptography.X509Certificates.dasm - AsnWriter:WriteGeneralizedTimeCore(struct,struct,bool):this
          19 ( 2.08% of base) : System.Net.Http.dasm - HttpConnection:WriteDecimalInt32Async(int):ref:this

Top method improvements by size (percentage):
        -878 (-41.34% of base) : System.Private.CoreLib.dasm - Vector64`1:Equals(struct):bool:this (4 methods)
        -336 (-32.34% of base) : System.Private.CoreLib.dasm - Vector64`1:GetHashCode():int:this (4 methods)
        -336 (-32.28% of base) : System.Private.CoreLib.dasm - Vector128`1:GetHashCode():int:this (4 methods)
        -336 (-32.28% of base) : System.Private.CoreLib.dasm - Vector256`1:GetHashCode():int:this (4 methods)
        -581 (-31.89% of base) : System.Private.CoreLib.dasm - Vector128`1:<Equals>g__SoftwareFallback|22_0(byref,struct):bool (4 methods)

10 total methods with size differences (6 improved, 4 regressed), 193425 unchanged.
```

**Comment by AndyAyersMS** [comment]
Looking at this on top of https://github.com/fiigii/coreclr/tree/reproduce, there are still a few calls to `IsSupported` left around, eg in ```System.Runtime.Intrinsics.Vector256`1[Int32][System.Int32]:<Equals>g__SoftwareFallback|25_0(byref,struct):bool```

Looks like we are not getting importer-time folding so are importing calls to the exception throwing paths too. 

It would help if you'd convert everything over to use throw helpers instead of direct throws, but that might not be enough.

For instance we start with:
```
               [000138] ------------              *  STMT      void  (IL 0x004...  ???)
               [000137] I-C-G-------              \--*  CALL      int    System.Runtime.Intrinsics.Vector256`1[Int32][System.Int32].get_IsSupported (exactContextHnd=0x00007FFA9CBC5FA9)

***** BB17, stmt 2
               [000143] ------------              *  STMT      void  (IL 0x004...  ???)
               [000142] --C---------              \--*  JTRUE     void  
               [000140] ------------                 |  /--*  CNS_INT   int    0
               [000141] --C---------                 \--*  NE        int   
               [000139] --C---------                    \--*  RET_EXPR  int   (inl return from call [000137])
```
and the inline decides to use a spill temp so after inlining we end up with
```
***** BB37, stmt 2
               [000233] ------------              *  STMT      void  (IL 0x004...  ???)
               [000230] ------------              |  /--*  CAST      int <- bool <- int
               [000229] ------------              |  |  \--*  CNS_INT   int    1
               [000232] -A----------              \--*  ASG       bool  
               [000231] D------N----                 \--*  LCL_VAR   bool   V08 tmp5         

------------ BB38 [???..???) -> BB19 (cond), preds={} succs={BB18,BB19}

***** BB38, stmt 3
               [000143] ------------              *  STMT      void  (IL 0x004...  ???)
               [000142] --C---------              \--*  JTRUE     void  
               [000140] ------------                 |  /--*  CNS_INT   int    0
               [000141] --C---------                 \--*  NE        int   
               [000234] ------------                    \--*  LCL_VAR   int    V08 tmp5         
```
so we end up with this fairly hefty inline subtree for `ThrowIfUnsupportedType`:
```
    [2 IL=0000 TR=000069 06003D02] [aggressive inline attribute] System.Runtime.Intrinsics.Vector256`1[Int32][System.Int32]:ThrowIfUnsupportedType()
      [3 IL=0000 TR=000137 06003D01] [aggressive inline attribute] System.Runtime.Intrinsics.Vector256`1[Int32][System.Int32]:get_IsSupported():bool
      [4 IL=0007 TR=000146 06000D16] [below ALWAYS_INLINE size] System.SR:get_Arg_TypeNotSupported():ref
      [5 IL=0012 TR=000155 06001394] [profitable inline] System.NotSupportedException:.ctor(ref):this
        [6 IL=0002 TR=000245 060015C1] [profitable inline] System.SystemException:.ctor(ref):this
          [7 IL=0002 TR=000258 06000352] [below ALWAYS_INLINE size] System.Exception:.ctor(ref):this
            [0 IL=0001 TR=000268 06000351] [FAILED: noinline per IL/cached result] System.Exception:.ctor():this
          [8 IL=0013 TR=000263 06000376] [below ALWAYS_INLINE size] System.Exception:set_HResult(int):this
        [9 IL=0013 TR=000250 06000376] [below ALWAYS_INLINE size] System.Exception:set_HResult(int):this
      [0 IL=0006 TR=000239 06000945] [FAILED: noinline per IL/cached result] System.SR:GetResourceString(ref,ref):ref
```
Let me dig in some more, but I am starting to think we'd be better of expressing some of this with intrinsics.

**Comment by benaadams** [comment]
https://github.com/dotnet/coreclr/pull/21795 should block the inlines of the Exception stuff? (Using basic non-returning throw helper)

**Comment by BruceForstall** [comment]
@AndyAyersMS I thought `IsSupported` was always supposed to be an intrinsic. There's at least one bug to that effect: https://github.com/dotnet/coreclr/issues/20379

**Comment by benaadams** [comment]
> I thought IsSupported was always supposed to be an intrinsic. There's at least one bug to that effect: #20379

A lot look to be infinite loops if not https://github.com/dotnet/coreclr/blob/eaf9823a0ba090826ed6cb3763fdce93f16199f0/src/System.Private.CoreLib/shared/System/Runtime/Intrinsics/X86/Popcnt.cs#L18-L23

**Comment by tannergooding** [comment]
@BruceForstall, this is the `IsSupported` check for the `Vector64/128/256<T>` types themselves, it is currently implemented in software since it was believed to be sufficient.

The core types expose some functionality that is always available (and provides software fallbacks) but which is limited to a set of well defined primitive types (10 of them).

**Comment by AndyAyersMS** [comment]
There are different flavors of methods with this name.

The `Intrinsic.Somearch.SomeIsaVariant.IsSupported` methods need to be intrinsics, but here we are asking if `Vector128<T>` supports a particular `T`, which is a different kind of question.

**Comment by tannergooding** [comment]
The ISA specific `IsSupported` checks are the ones that are intrinsic (as they require JIT support to return true, since it needs to check the corresponding CPUID bit).

**Comment by benaadams** [comment]
Ubuntu arm 
```
GC_Scenarios._Dynamo_dynamo_dynamo_._Dynamo_dynamo_dynamo_sh [FAIL]
 - Check Test Results for specific test information and call stack.
```
Windows_NT arm64 - Jenkins fail

@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by benaadams** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by benaadams** [comment]
Don't think I have permissions to restart the Windows_NT arm64 job (or am using wrong incantation)

**Comment by AndyAyersMS** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by AndyAyersMS** [comment]
I think there's still constraints on who can submit to arm64.

**Pull request merged**
