### PR TITLE
Fix Linux public pool.

### PR DESCRIPTION
**Pull request by sandreenko**

### CODE REVIEW

**Comment by sandreenko** [comment]
@dotnet-bot test this please

**Comment by jashook** [comment]
Can we add a comment to Renable these queues once the core-eng issue is fixed. Long term we do not want to transition off the hosted pool.

**Comment by sandreenko** [comment]
> Can we add a comment to Renable these queues once the core-eng issue is fixed. Long term we do not want to transition off the hosted pool.

Done.

**Comment by MattGal** [comment]
I think both of these queues are actually ready to be used again.  (definitely on 16.04, checking in on the 18.04)

**Comment by MattGal** [comment]
(18.04 was OK too, thanks for staying with it)

**Pull request closed without merging**
