### PR TITLE
Restore some changes lost in a merge conflict

### PR DESCRIPTION
**Pull request by swgillespie**
Unfortunately some recent changes to the `gc` directory got lost in a merge conflict, so this PR restores them.

### CODE REVIEW

**Comment by swgillespie** [comment]
Hit my nemesis #6574 on the Ubuntu build, will merge if the others are clean.

**Comment by swgillespie** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by swgillespie** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by jkotas** [comment]
cc @pkukol

**Pull request merged**
