### PR TITLE
Use a new COR_PRF_SUSPEND_FOR_PROFILER in ICorProfilerCallback::Runti…

### PR DESCRIPTION
**Pull request by k15tfu**
Use a new COR_PRF_SUSPEND_FOR_PROFILER in ICorProfilerCallback::RuntimeThreadSuspended() when requested by profiler

Fixes https://github.com/dotnet/coreclr/issues/26576

### CODE REVIEW

**Comment by k15tfu** [comment]
btw, I have to re-generate src/pal/prebuilt/inc/corprof.h file. How I can do it?

**Comment by davmason** [comment]
> btw, I have to re-generate src/pal/prebuilt/inc/corprof.h file. How I can do it?

Build on windows and then it will be generated in the bin folder, you can copy and paste the generated file to the checked in one.

**Comment by k15tfu** [comment]
@davmason done. but there are lot of whitespace changes in `src/pal/prebuilt/inc/corprof.h`

**Comment by davmason** [comment]
@k15tfu it looks good to me, have you done any testing?

When I open issues to port this and #26985 to 3.1 my manager will want to know if these are the only fixes you need. What we want to avoid is finding more issues in the future.

Can you confirm if these two fixes unblock your sampling?

**Comment by davmason** [comment]
@k15tfu It would be best if we could try and get this ported to 3.1 by Tuesday, in order to do that I will need confirmation that you have tested by early Monday at the latest. Is that something you can do?

**Comment by k15tfu** [comment]
@davmason Yes, I have already checked it on Linux (#27041 & #26985, based on 3.0), and today/tomorrow I want to try it on Mac OS X as well.

We really depend on #23383. It's not a show-stopper right now but it can be in the near future, so I'll appreciate if you could help me with getting this ready for 3.1. I plan to provide an implementation for Set/Get methods in few days.

**Comment by k15tfu** [comment]
@davmason Mac OS X also looks good, and there are no other known issues (except #23383). I think that's all at the moment. Thanks.

**Pull request merged**
