### PR TITLE
Tar arm build outputs to workaround unicode issues

### PR DESCRIPTION
**Pull request by adiaaida**

### CODE REVIEW

**Comment by adiaaida** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by adiaaida** [comment]
@jashook I'm testing the generated jobs to make sure this solves the problem here: https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/GenPRTest/job/perf_throughput_linux_arm_flow/1/

**Comment by adiaaida** [comment]
@jashook PTAL

**Pull request merged**
