### PR TITLE
ARM-CI: Convert Linux ARM emulator CI check to cross build (fixes PR #5680)

### PR DESCRIPTION
**Pull request by prajwal-aithal**
ARM-CI: Convert Linux ARM emulator CI check to cross build (fixes PR #5680)

* Previously used emulated build took a lot of time leading to timeout errors
* Changing this CI check to build using cross build
* Resolves CI issues caused by previous identical PR #5680

Signed-off-by: Prajwal A N <an.prajwal@samsung.com>

### CODE REVIEW

**Comment by prajwal-aithal** [comment]
@jashook @mmitche @wtgodbe I have made a new PR (identical to PR #5680 ) with the environment variable error fixed.

Summary of changes from PR #5680 are
* `armarmemul_path` and `armrootfs_mountpath` are now declared as groovy variables (instead of bash shell variables)
* The above groovy variables are used in the build commands using groovy string interpolation (`${}`)
* The `$LINUX_ARM_INCPATH` and `$LINUX_ARM_CXXFLAGS` environment variables are used in the build commands with the `$` escaped (need comments on correctness of this change). I am assuming that the previous error was due to groovy parsing the `$` symbol according to its string interpolation rules, and that the commands in the exact string form will be executed on the bash shell.

Could you please review this PR and confirm if the above summarized changes fixes the errors caused by PR #5680 ?

cc: @leemgs

**Comment by jashook** [comment]
@dotnet-bot test CI Please

**Comment by prajwal-aithal** [comment]
@jashook The previous version of this PR was breaking the CI test due to the assert condition to test if the configuration that is being built was one of either `Debug` or `Release`. I have changed this check to an `if` condition (breaking if the configuration is neither of the two).

**Comment by prajwal-aithal** [comment]
@dotnet-bot test CI please

**Comment by wtgodbe** [comment]
Thanks for doing this! Everything looks good to me (I believe escaping the $ before $LINUX_ARM_INCPATH was the right thing to do, but you might want to get a second opinion on this one. The CI test passing is a pretty good indicator that it was correct, though).

**Comment by prajwal-aithal** [comment]
@jashook Can we merge this?

**Comment by jashook** [comment]
lgtm

**Pull request merged**
