### PR TITLE
[x86/Linux] Change EventPipeProviderConfiguration layout

### PR DESCRIPTION
**Pull request by kbaladurin**
Change EventPipeProviderConfiguration layout to avoid mismatches on x86/Linux.

This patch fixes sigfaults in tracing tests.

### CODE REVIEW

**Comment by kbaladurin** [comment]
cc @Buyduck 
@jkotas @janvorli PTAL

**Comment by kbaladurin** [comment]
Seems like on x86/Linux packing of the structs with doubles and 64-bit integers works incorrectly:
`Interop/StructPacking/StructPacking/StructPacking`:
```
Unexpected Size for DefaultLayoutDefaultPacking`1[System.Double].
     Expected: 12; Actual: 16
Unexpected Offset for DefaultLayoutDefaultPacking`1[System.Double].Value.
     Expected: 4; Actual: 8

Unexpected Size for SequentialLayoutDefaultPacking`1[System.Double].
     Expected: 12; Actual: 16
Unexpected Offset for SequentialLayoutDefaultPacking`1[System.Double].Value.
     Expected: 4; Actual: 8

Unexpected Size for SequentialLayoutMaxPacking`1[System.Double].
     Expected: 12; Actual: 16
Unexpected Offset for SequentialLayoutMaxPacking`1[System.Double].Value.
     Expected: 4; Actual: 8

Unexpected Offset for AutoLayoutDefaultPacking`1[System.Double].Byte.
     Expected: 0; Actual: 8
Unexpected Offset for AutoLayoutDefaultPacking`1[System.Double].Value.
     Expected: 4; Actual: 0

Unexpected Offset for AutoLayoutMinPacking`1[System.Double].Byte.
     Expected: 0; Actual: 8
Unexpected Offset for AutoLayoutMinPacking`1[System.Double].Value.
     Expected: 4; Actual: 0

Unexpected Offset for AutoLayoutMaxPacking`1[System.Double].Byte.
     Expected: 0; Actual: 8
Unexpected Offset for AutoLayoutMaxPacking`1[System.Double].Value.
     Expected: 4; Actual: 0

Unexpected Size for DefaultLayoutDefaultPacking`1[System.Int64].
     Expected: 12; Actual: 16
Unexpected Offset for DefaultLayoutDefaultPacking`1[System.Int64].Value.
     Expected: 4; Actual: 8

Unexpected Size for SequentialLayoutDefaultPacking`1[System.Int64].
     Expected: 12; Actual: 16
Unexpected Offset for SequentialLayoutDefaultPacking`1[System.Int64].Value.
     Expected: 4; Actual: 8

Unexpected Size for SequentialLayoutMaxPacking`1[System.Int64].
     Expected: 12; Actual: 16
Unexpected Offset for SequentialLayoutMaxPacking`1[System.Int64].Value.
     Expected: 4; Actual: 8

Unexpected Offset for AutoLayoutDefaultPacking`1[System.Int64].Byte.
     Expected: 0; Actual: 8
Unexpected Offset for AutoLayoutDefaultPacking`1[System.Int64].Value.
     Expected: 4; Actual: 0

Unexpected Offset for AutoLayoutMinPacking`1[System.Int64].Byte.
     Expected: 0; Actual: 8
Unexpected Offset for AutoLayoutMinPacking`1[System.Int64].Value.
     Expected: 4; Actual: 0

Unexpected Offset for AutoLayoutMaxPacking`1[System.Int64].Byte.
     Expected: 0; Actual: 8
Unexpected Offset for AutoLayoutMaxPacking`1[System.Int64].Value.
     Expected: 4; Actual: 0

Unexpected Size for DefaultLayoutDefaultPacking`1[System.UInt64].
     Expected: 12; Actual: 16
Unexpected Offset for DefaultLayoutDefaultPacking`1[System.UInt64].Value.
     Expected: 4; Actual: 8

Unexpected Size for SequentialLayoutDefaultPacking`1[System.UInt64].
     Expected: 12; Actual: 16
Unexpected Offset for SequentialLayoutDefaultPacking`1[System.UInt64].Value.
     Expected: 4; Actual: 8

Unexpected Size for SequentialLayoutMaxPacking`1[System.UInt64].
     Expected: 12; Actual: 16
Unexpected Offset for SequentialLayoutMaxPacking`1[System.UInt64].Value.
     Expected: 4; Actual: 8

Unexpected Offset for AutoLayoutDefaultPacking`1[System.UInt64].Byte.
     Expected: 0; Actual: 8
Unexpected Offset for AutoLayoutDefaultPacking`1[System.UInt64].Value.
     Expected: 4; Actual: 0

Unexpected Offset for AutoLayoutMinPacking`1[System.UInt64].Byte.
     Expected: 0; Actual: 8
Unexpected Offset for AutoLayoutMinPacking`1[System.UInt64].Value.
     Expected: 4; Actual: 0

Unexpected Offset for AutoLayoutMaxPacking`1[System.UInt64].Byte.
     Expected: 0; Actual: 8
Unexpected Offset for AutoLayoutMaxPacking`1[System.UInt64].Value.
     Expected: 4; Actual: 0

```
 It's the root of this problem.

**Comment by janvorli** [comment]
@kbaladurin it also seemed to me that it must be a problem in how we handle the packing and that this PR should not be needed. So I am glad you have confirmed that.

**Comment by brianrob** [comment]
Yes, I'm wondering if we can handle this in a more holistic way.  I'd be surprised if this is the only x86 packing issue.

**Comment by kbaladurin** [comment]
Thank you! Yes, seems like it's x86 System V ABI packing problem. I'm working on patch that will fix it.

**Comment by brianrob** [comment]
Thanks @kbaladurin!

**Comment by kbaladurin** [comment]
Fix for x86 System V ABI packing problem: https://github.com/dotnet/coreclr/pull/17455

**Pull request closed without merging**
