### PR TITLE
Reduce the BUGS!!!

### PR DESCRIPTION
**Pull request by mattwarren**
There's been [multiple studies](http://resources.sei.cmu.edu/asset_files/TechnicalNote/2014_004_001_428597.pdf) (PDF) that show a link between '# of bugs' and '# of lines of code' in software.

So as **early April** present to all the CoreCLR devs who are working hard on the next release, **I've just reduced your bug count** (probably)!!

The PR removes 28,478 lines across 933 files, I'll let you do the maths to calculate how many bugs that equates to!!

### CODE REVIEW

**Comment by terrajobst** [comment]
I see what you did there :-)

nope

**Comment by adityamandaleeka** [comment]
:shipit:

**Comment by mmitche** [comment]
It's proven that when the parser can read the brace on the same line as the class/method/enum declaration it is "happier" and inject fewer "syntax errors" into the output.

Share if you like happy parsers.

**Comment by ahsonkhan** [comment]
@mattwarren, please rebase away the extra commits. I think there are 3 unnecessary commits that should get squashed to keep the commit history clean.

**Comment by PRIMETSS** [comment]
ahhh it good to have a laugh now and again! Even on April Fools
But maybe the best place to share them is System.Ben!
https://github.com/benaadams/System.Ben/issues/102
Oh no!!! hang on.....

**Pull request closed without merging**
