### PR TITLE
OS X tests should now be run with each PR

### PR DESCRIPTION
**Pull request by wtgodbe**

### CODE REVIEW

**Comment by wtgodbe** [comment]
@dotnet-bot test ci please

**Comment by wtgodbe** [comment]
@dotnet-bot test osx debug please

**Comment by wtgodbe** [comment]
@dotnet-bot test ci please

**Comment by wtgodbe** [comment]
@dotnet-bot test ci please

**Comment by kangaroo** [comment]
:+1:

**Comment by wtgodbe** [comment]
@dotnet-bot test ci please

**Pull request merged**
