### PR TITLE
Revert Improve narrowing of GT_AND nodes. (#18916)

### PR DESCRIPTION
**Pull request by jkotas**
This reverts commit c0bad3c66218f61dd3e4f151b9d2eae22c6d88d2.

### CODE REVIEW

**Comment by jkotas** [comment]
OSX failure is https://github.com/dotnet/coreclr/issues/18858

**Comment by jkotas** [comment]
@dotnet-bot test Windows_NT x64 full_opt ryujit CoreCLR Perf Tests Correctness please
@dotnet-bot test Windows_NT x64 min_opt ryujit CoreCLR Perf Tests Correctness please
@dotnet-bot test Windows_NT x86 full_opt ryujit CoreCLR Perf Tests Correctness please
@dotnet-bot test Windows_NT x86 min_opt ryujit CoreCLR Perf Tests Correctness please

**Comment by jakobbotsch** [comment]
@erozenfeld Here is a short repro in case it helps:
```csharp
// Generated by Fuzzlyn on 2018-07-18 01:01:07
// Seed: 16170027368425612823
// Reduced from 23.6 KiB to 0.2 KiB
// Debug: Throws 'System.InvalidProgramException'
// Release: Runs successfully
class C0
{
    public long F2;
}

public class Program
{
    static C0 s_3 = new C0();
    public static void Main()
    {
        byte vr15 = (byte)(s_3.F2 & 0);
    }
}
```

**Comment by jkotas** [comment]
@adiaaida Could you please take a look at the  CoreCLR Perf Tests Correctness failures? I am not able to figure out what's wrong by looking at the logs.

**Comment by adiaaida** [comment]
@jkotas submission-metadata.py failed because there are quotes in the title of the PR. We have an issue (#18855) open for this. Removing the quotes and rerunning the job should get them running.

**Comment by stephentoub** [comment]
@dotnet-bot test CentOS7.1 x64 Checked Innerloop Build and Test please (https://github.com/dotnet/coreclr/issues/18993)

**Pull request merged**
