### PR TITLE
Add generated document for ComPlus_* configurations

### PR DESCRIPTION
**Pull request by milizhang**
The commit contains a markdown table that documents all configurations that exist in src/inc/clrconfigvalues.h, as well as the script used to generate this document.

### CODE REVIEW

**Comment by richlander** [comment]
Thanks! Good idea.

Is it possible to make the first column more narrow (wrap the longest lines)?

/cc @jkotas

**Comment by jkotas** [comment]
I am not sure whether it is useful to have a markup version of this list. To me, it is about as hard to read as the header file; and I tend to prefer a single source of truth. I can live with it though.

If you feel that there is value in having a markup version of this list, could you please add the following note to the top: 

This list was auto generated from [src\inc\clrconfigvalues.h](https://github.com/dotnet/coreclr/blob/master/src/inc/clrconfigvalues.h). It may be out of date.

**Comment by kangaroo** [comment]
I tend to agree with @jkotas -- unless this is the canonical source, or is generated as a post commit, I'm worried this will harm more than it helps.  Is there a reason the docs can't just point at the header?

**Comment by milizhang** [comment]
@jkotas Sure I can add this notification to the document.

One of the point is that this document can be regenerated anytime using the provided script, thus it would be fairly simple to update the table.

Also talking about the format, I am thinking about moving the comments to the second column. Do you think that will make the document a little bit easier to read?

**Comment by Eyas** [comment]
If you will add a comment saying the document is auto-generated, it might be a good idea to state that is accurate as of `<commit id>` (the last commit in which this particular file changed), rather than stating it "may be out of date".

**Comment by milizhang** [comment]
@Eyas Great idea. I will modify the script to automatically insert this information.

**Comment by milizhang** [comment]
Added some modifications to make this markdown document more readable.
Also added the information about both the hash of the latest commit, and the generation date of this document.

**Comment by richlander** [comment]
I personally think that this is a benefit. The rendered view is significantly easier to read than the header file.

@milizhang can you squash?

If anyone else has a strong issue with this, please say. Otherwise, we'll merge (post-squash).

**Comment by milizhang** [comment]
Squashed and regenerated the document to reflect recent changes.

**Pull request merged**
