### PR TITLE
Fixing GC stress test layout and Creating a Sanity Run for it

### PR DESCRIPTION
**Pull request by ramarag**
@Maoni0  PTAL

### CODE REVIEW

**Comment by Maoni0** [comment]
Rama, LGTM. Could you please also update the readme to say that the tests will be built to the Tests dir instead of what it says currently? Also @swgillespie

**Comment by ramarag** [comment]
i believe it already says that in : https://github.com/dotnet/coreclr/blob/master/tests/src/GC/Stress/stress_run_readme.txt#L23

Can you point me to the location that needs to be corrected ?

**Comment by Maoni0** [comment]
It's the step above that. It says:

>The stress framework is built from <REPO_ROOT>\tests\src\GC\Stress\Framework and the resulting .exe is in \<REPO_ROOT\>\binaries\tests\<arch>\<buildtype>\GC\Stress\Framework\ReliabilityFramework.exe.

>The tests are built from <REPO_ROOT>\tests\src\GC\Stress\Tests and the resulting .exe's are in \<REPO_ROOT\>\binaries\tests\<arch>\<buildtype>\GC\Stress\Framework\\*.exe.

First of all, the directory is different from what we have currently. I see ReliablityFramework.exe in 
\<REPO_ROOT\>\bin\tests\Windows_NT.arch.buildtype\GC\Stress\Framework\ReliabilityFramework. Do you mind updating that too?

Then for the tests, they are in \<REPO_ROOT\>\bin\tests\Windows_NT.arch.buildtype\GC\Stress\Framework\ReliabilityFramework\\**Tests**\\*.exe, instead of in the same dir with ReliabilityFramework.exe as the original instructions said.

**Comment by ramarag** [comment]
@dotnet-bot test   Windows_NT x64 Release Priority 1 Build and Test

**Pull request merged**
