### PR TITLE
[ARM] Update rootfs for Tizen armel

### PR DESCRIPTION
**Pull request by hqueue**
This is required to build CoreCLR for Tizen armel as a part of .NET Core 2.0.0 for Tizen.

Existing rootfs for armel Tizen is out-of-dated and not suitable for .NET Core 2.0.0 for Tizen.

Two changes are made.
* Update rootfs for Tizen armel to recent version
* Updates CI for Tizen armel to make use of a prebuilt embedded rootfs as Ubuntu arm does.

*Please merge this PR first before following related PR merged.*

Related PR:
https://github.com/dotnet/corefx/pull/18916
https://github.com/dotnet/core-setup/pull/2163

### CODE REVIEW

**Comment by hqueue** [comment]
@dotnet-bot please test Windows_NT x64 Release Priority 1 Build and Test

**Comment by hqueue** [comment]
/cc: @gkhanna79 PTAL. For 2.0.0 release, this should be applied to sync with Tizen. Do I need to make same PR for release/2.0.0 branch too ?

**Comment by hqueue** [comment]
@gkhanna79 Yes, please merge this :) 
Just make sure CoreFX and CoreCLR are merged after this PR. Thanks!

**Comment by hqueue** [comment]
@gkhanna79 Please ignore my previous comment.

I'm afraid, PRs in CoreCLR may be failed with Tizen armel CI, if they are not rebased to master with this PR merged. 
Therefore please merge this PR first and  merge CoreFX after several days later, if possible.
Sorry for any confusions I made in previous comment.

**Comment by gkhanna79** [comment]
@hqueue How long do I wait to merge CoreFX and Core-Setup changes after this one is merged? Also, given this delay, I think we should just make this change in master and not release/2.0.0 for now.

**Comment by hqueue** [comment]
@gkhanna79 You can merge CoreFx after CoreCLR is merged.

What I'm worrying is that other PRs which is not rebased to this PR may fail in Tizen CI, because native binary in CoreFx (which is used in unittests) are not compatiable with old rootfs used by ARM32 emulator.
This PR also replaces Tizen CI to make use of new rootfs.
Can this be an answer to your question ?

**Comment by hqueue** [comment]
@gkhanna79 Thank you for merging this. Will this master branch be automatically merged to release/2.0.0-preview 2 later ? or should I prepare another PR for preview 2 ?

**Comment by gkhanna79** [comment]
@hqueue On 5/10, master will be merged into release/2.0.0 as mentioned at https://github.com/dotnet/coreclr/issues/11248

**Pull request merged**
