### PR TITLE
Delete unused file expandarray.h

### PR DESCRIPTION
**Pull request by mikedn**
This was used by the JIT but now it has its own copy (src\jit\jitexpandarray.h).

### CODE REVIEW

**Comment by Rattenkrieg** [comment]
In expand and shrink routines comments I've noticed explicit statements that elements are copied bitwise and copy constructors are not invoked. Why not to place `static_assert(std::is_trivially_copyable<T>::value, "...")`? There are lot of generic containers across codebase which are obliviously memmoving and memcpying elements.

**Comment by mikedn** [comment]
> Why not to place static_assert(std::is_trivially_copyable<T>::value, "...")? There are lot of generic containers across codebase which are obliviously memmoving and memcpying elements.

STL cannot be used inside the runtime so `std:::is_trivially_copyable` isn't readily available. And when that code was written, `is_trivially_copyable` didn't exist or was not available in the compiler used at the time.

**Comment by Rattenkrieg** [comment]
> STL cannot be used inside the runtime

I think I can understand rationale behind this, but are anywhere in the docs explicit guidlines regarding this?

> And when that code was written, `is_trivially_copyable` didn't exist or was not available in the compiler used at the time.

If we really need this, today we can mimmick such behavior as other cpp codebases do.

I'm ok with answers provided and don't want to raise debates - just was curious, especially when stumbled upon explicit comments in code.

**Comment by mikedn** [comment]
> I think I can understand rationale behind this, but are anywhere in the docs explicit guidlines regarding this?

None that I know of. Recently the JIT team told me that they tried to use STL and ran into problems with the CLR PAL and `wchar_t` platform differences. In the past there were also problems with (older) compiler support and maybe with STL's use of exceptions.

To that I'd add that STL (containers, that is) is sometimes not the best choice. Like all general purpose library implementations it tends to more than one needs and that comes at a cost - increased memory usage for example.

Note that I tend to see the world through JIT coloured glasses. The VM may have other constraints. And both the JIT and the VM ended up implementing some parts of STL (in jitstd and clr_std).

> If we really need this, today we can mimmick such behavior as other cpp codebases do.

In the case of ExpandArray (and any other similar code) it's probably best to use a simple for copy loop and let the compiler sort it out. Usually they recognize such patterns and do the right thing. Sometimes that may even result in faster code.

IMO the best solution would be to use those parts of the STL that do not cause problems and are relatively difficult to reimplement (basically all the meta programming goo like traits) but continue to use custom made containers that fit the requirements of various runtimes components.

**Pull request merged**
