### PR TITLE
Expose Exception.set_HResult as Public

### PR DESCRIPTION
**Pull request by luqunl**
This is to change Excetion.set_HResult from protected to public, so that others can set HResult value for a given exception.

Approved API: https://github.com/dotnet/corefx/issues/29696
Related Corefx Change(ref assembly): https://github.com/dotnet/corefx/pull/29986

### CODE REVIEW

**Comment by jkotas** [comment]
You will need to do the same change in ProjectN/CoreRT as well.

**Comment by luqunl** [comment]
@dotnet-bot  test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by luqunl** [comment]
@dotnet-bot help

**Comment by luqunl** [comment]
@dotnet-bot test Innerloop OSX x64 Checked Build

**Pull request merged**
