### PR TITLE
More Struct-related Refactorings

### PR DESCRIPTION
**Pull request by CarolEidt**
- Make GT_OBJ and GT_NULLCHECK derive from GenTreeIndir, as they are also indirections.
- Extract the ordering-related methods from gentree and optcse, as they will need to be used slightly differently for struct assignments.
- Make fgMorphImplicitByRefArgs take a pointer to the tree, as it may need to replace the tree with one that a simple CopyFrom() will not work for.
- In gtSetEvalOrder(), in the addressing mode code, replace "adr" with "base" and "op1" with "addr", as the existing names are quite confusing.
- Other minor refactorings to reduce future diffs.

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

**Comment by adityamandaleeka** [comment]
I checked out the Ubuntu failure and it's the same issue (#6222) where the code generated for `AppendFormatHelper` XOR's edi with itself and then immediately dereferences it.

Dump and binaries: http://dotnetrp.azurewebsites.net/dumpling/download/1523

**Comment by CarolEidt** [comment]
Thanks for looking into that. I will try again to see if I can repro it locally, but I'm not optimistic.

**Comment by adityamandaleeka** [comment]
Yea, I'm not optimistic about being able to reproduce it locally either. It's worrying that it's still happening and so infrequently. Do you know of possible sources of non-determinism in how the JIT generates code for this type of block?

If we're entirely out of options, a last resort might be to kick off CI jobs with COMPlus_JitDump set to dump this method until one of them hits this issue, at which point we can (hopefully) see why it decided to generate the erroneous code. This should be pretty straightforward to do (albeit resource intensive on the CI machines).

What do you think?

**Comment by CarolEidt** [comment]
I'm also still working on getting a cross-build working with the arm emulator, as it *seems* to be the case that the arm-softfp failures, that look similar to this (#6179), are more deterministic. However, I have no clue about why the JIT would be non-deterministic for any code (if we knew about such a case we would get rid of it!). 
Let me try these two avenues - attempting to reproduce on x64/ux with the latest sources + these changes, and getting the arm tests running. If neither of those are successful, I think what you suggest might be fruitful.

**Comment by adityamandaleeka** [comment]
Sounds good :+1:

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib - ping. The Linux ARM tests do not seem to be related.

**Comment by briansull** [comment]
LGTM

**Pull request merged**
