### PR TITLE
  Porting tests that have references 

### PR DESCRIPTION
**Pull request by hoyMS**

### CODE REVIEW

**Comment by hoyMS** [comment]
@pgavlin Please review

**Comment by hoyMS** [comment]
@dotnet-bot test Ubuntu x64 Release Build

**Comment by hoyMS** [comment]
@dotnet-bot test OSX x64 Release Build

**Comment by hoyMS** [comment]
@dotnet-bot test OSX x64

**Comment by hoyMS** [comment]
@dotnet-bot test Ubuntu x64 Debug Build

**Comment by hoyMS** [comment]
@dotnet-bot test OSX x64 Debug Build

**Comment by pgavlin** [comment]
@hoyMS The OS X queues are unreliable at the moment due to infrastructural issues: please don't rerun those legs if they fail.

**Comment by hoyMS** [comment]
I see. The Ubuntu x64 Debug Build  also seems not reliable:

/src/vm/amd64    -fno-omit-frame-pointer -fms-extensions -ferror-limit=4096 -Werror -Wno-unused-private-field -Wno-unused-variable -Wno-microsoft -Wno-tautological-compare -Wno-constant-logical-operand -Wno-unknown-warning-option -Wno-invalid-offsetof -Wno-incompatible-ms-struct -nostdinc -fPIC -o CMakeFiles/cee_wks.dir/__/amd64/calldescrworkeramd64.S.o -c /mnt/j/workspace/dotnet_coreclr/debug_ubuntu_prtest/src/vm/amd64/calldescrworkeramd64.S
09:48:27 fatal error: error in backend: IO failure on output stream.
09:48:27 make[2]: *** [src/vm/wks/CMakeFiles/cee_wks.dir/__/amd64/calldescrworkeramd64.S.o] Error 1
09:48:27 make[2]: *** Waiting for unfinished jobs....
09:48:27 make -f 

Those tests were green before. I just did a rebase.

**Comment by hoyMS** [comment]
@dotnet-bot test Ubuntu x64 Debug Build

**Comment by hoyMS** [comment]
@pgavlin is this failure JIT.Methodical.Boxing.misc._dbgconcurgc_il._dbgconcurgc_il known on Ubuntu x64? Looks unrelated to this PR.

**Comment by pgavlin** [comment]
No, that's new--would you mind filing a bug and disable the test for *nix as part of this PR?

**Comment by hoyMS** [comment]
How do I file a bug? Should I do it in VSO?

**Comment by hoyMS** [comment]
Issue 2311 has been filed.

**Comment by hoyMS** [comment]
@pgavlin Please review and merge it for me. Thanks.

**Comment by pgavlin** [comment]
LGTM.

**Pull request merged**
