### PR TITLE
Add error logging to 4 PAL tests that fail periodically on OSX

### PR DESCRIPTION
**Pull request by wtgodbe**

### CODE REVIEW

**Comment by wtgodbe** [comment]
@sergiy-k PTAL

**Comment by sergiy-k** [comment]
LGTM

**Comment by wtgodbe** [comment]
@dotnet-bot test this please

**Comment by wtgodbe** [comment]
@dotnet-bot test this please

**Comment by wtgodbe** [comment]
@dotnet-bot test Windows_NT corefx_baseline

**Pull request merged**
