### PR TITLE
Comment out use of GetSystemTimePreciseAsFileTime

### PR DESCRIPTION
**Pull request by stephentoub**
https://github.com/dotnet/coreclr/issues/14187
cc: @jkotas, @vancem

### CODE REVIEW

**Comment by vancem** [comment]
I am trying to understand the value of getting  a change in quickly like this.    

It does seem we have a significant problem, but clearly commenting things out as done here is not the ultimate solution.    If this update is there to get a build to someone then it can make sense, but I want to make sure that we don't leave it this way (at the last we should create an issue to fix it properly).

My inclination, however is to first understand the problem more.   My expectations is that the problem on occurs on some version of windows.    Things that would make me feel better include

1. If we put in a version check here to only use the new API on WIn-10 OSes
2. Having a config switch to opt out (which allows people to fix it.
3. Auto-opt-out if the two APIs diverge by more that a very reasonable amount (e.g. 100 msec).  

In the very short term just doing (2), seems appropriate.  

We can also put in a test for drift, which may help figure out exactly when it happens. 

Vance

**Comment by stephentoub** [comment]
> I am trying to understand the value of getting a change in quickly like this.

It's an inexpensive / easily verified solution that brings us back to a known working state and that we can ship as servicing for 2.0.  We've apparently broken real apps with this.

**Comment by vancem** [comment]
> It's an inexpensive / easily verified solution that brings us back to a known working state and that we can ship as servicing for 2.0. We've apparently broken real apps with this.

Yes, but if a servicing release is not going out in the next couple days, it seems reasonable to take that time to identify what ultimately will be the more permanent fix, and simply check in that...

**Comment by stephentoub** [comment]
> it seems reasonable to take that time to identify what ultimately will be the more permanent fix, and simply check in that...

We can wait.  Personally I prefer to take the approach of getting back to a known-good state, and then once we have a better solution, if there's still time, pushing that as well.

**Comment by jkotas** [comment]
There is a non-zero chance that some apps or libraries took a dependency on the higher precision in .NET Core 2.0 already. Unless we can come up with something better, we should add this workaround under a switch for servicing.

**Comment by stephentoub** [comment]
Ugh.  I will close this and we can wait then.  The nice aspect of this as a quick-and-easy change to service is that it was very contained; the moment we talk about adding switches, that's no longer the case.

**Pull request closed without merging**
