### PR TITLE
SpinWait - always spin once

### PR DESCRIPTION
**Pull request by benaadams**
When `m_count == 0` `SpinOnce()` calls through to [`ThreadNative::SpinWait`](https://github.com/dotnet/coreclr/blob/master/src/vm/comsynchronizable.cpp#L1886-L1915) but doesn't actually issue a pause as iterations are zero.

/cc @stephentoub PTAL

### CODE REVIEW

**Comment by benaadams** [comment]
Not sure about the test in the `else` of `m_count == int.MaxValue`

**Comment by benaadams** [comment]
Instant retry (as now) might be desirable rather than a single pause? If so does it need to call into vm for that?

**Comment by stephentoub** [comment]
What effect does this have on various benchmarks? It's adding a yield where there wasn't one before... could be good, could be bad. I expect it's the right thing to do, but...

**Comment by benaadams** [comment]
Will try, also with adding a single pause e.g. 0, 1, 16...

**Comment by benaadams** [comment]
Ahh... read the bit shift wrong. Spin sequence is PAUSE x 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, Yields

Was wondering if it should start around 4 as `LOCK CMPXCHG8B` is 19 cycles and `PAUSE` is 5 cycles on broadwell... 😁

**Comment by benaadams** [comment]
Basically was reading code too late at night 😆

**Comment by benaadams** [comment]
Increased some of the timeouts on spinwait for higher numbers of cores and could get a x2-3 improvement on the global threadpool - so it is pure raw contention at play. 

Couldn't work out a sensible general improvement though; and it shouldn't exhibit much where actual work is being done (where increasing the spinning times would likely reduce overall work done anyway).

**Pull request closed without merging**
