### PR TITLE
JIT: fix filter liveness computation

### LINKED ISSUE #22820: Access Violation on x86
We have a scenario in which we are getting an access violation exception during a particular load in our system.
I have a full dump of the process when the crash happened, available here:
https://drive.google.com/file/d/11oqZaegxKcoNT8Xj1u9YDIcH7LcmMBsW/view?usp=sharing

The scenario we have is a few servers running and communicating with one another on the same process.
This is part of our test setup. We recently started seeing hard failures, such as this one: `(d2c.3390): Access violation - code c0000005 (first chance)`

The event log reports:

```
Application: dotnet.exe
CoreCLR Version: 4.6.27317.3
Description: The process was terminated due to an internal error in the .NET Runtime at IP 5A29AA9B (5A230000) with exit code 80131506.


Faulting application name: dotnet.exe, version: 2.1.27130.1, time stamp: 0x5c007ea0
Faulting module name: coreclr.dll, version: 4.6.27317.3, time stamp: 0x5c40c18e
Exception code: 0xc0000005
Fault offset: 0x0006aa9b
Faulting process id: 0x52d4
Faulting application start time: 0x01d4cc3f7d83fa59
Faulting application path: C:\Program Files (x86)\dotnet\dotnet.exe
Faulting module path: C:\Users\ayende\.nuget\packages\runtime.win-x86.microsoft.netcore.app\2.1.8\runtimes\win-x86\native\coreclr.dll
Report Id: ff99edfe-baf1-431a-9ce3-06e987219e6c
Faulting package full name: 
Faulting package-relative application ID: 
```

This machine has the following hot fixes applies:

```
PS C:\Windows\SysWOW64> Get-HotFix

Source        Description      HotFixID      InstalledBy          InstalledOn
------        -----------      --------      -----------          -----------
OREN-PC       Update           KB4100347     NT AUTHORITY\SYSTEM  2/18/2019 12:00:00 AM
OREN-PC       Update           KB4343669     NT AUTHORITY\SYSTEM  7/11/2018 12:00:00 AM
OREN-PC       Update           KB4456655     NT AUTHORITY\SYSTEM  9/13/2018 12:00:00 AM
OREN-PC       Security Update  KB4465663     NT AUTHORITY\SYSTEM  11/14/2018 12:00:00 AM
OREN-PC       Security Update  KB4471331     NT AUTHORITY\SYSTEM  12/6/2018 12:00:00 AM
OREN-PC       Security Update  KB4477137     NT AUTHORITY\SYSTEM  12/12/2018 12:00:00 AM
OREN-PC       Security Update  KB4480979     NT AUTHORITY\SYSTEM  1/9/2019 12:00:00 AM
OREN-PC       Security Update  KB4485449     NT AUTHORITY\SYSTEM  2/19/2019 12:00:00 AM
OREN-PC       Security Update  KB4487038     NT AUTHORITY\SYSTEM  2/19/2019 12:00:00 AM
OREN-PC       Security Update  KB4480966     HRHINOS\Ayende       2/21/2019 12:00:00 AM
OREN-PC       Security Update  KB4487017
```

The actual stack we are seeing is always something similar to:

```
0:043> kp
 # ChildEBP RetAddr  
00 (Inline) -------- coreclr!VolatileLoad+0x3 [e:\a\_work\335\s\src\inc\volatile.h @ 153] 
01 (Inline) -------- coreclr!Volatile<unsigned long>::Load+0x3 [e:\a\_work\335\s\src\inc\volatile.h @ 292] 
02 (Inline) -------- coreclr!Volatile<unsigned long>::operator unsigned long+0x3 [e:\a\_work\335\s\src\inc\volatile.h @ 346] 
03 (Inline) -------- coreclr!RelativePointer<Module *>::GetValue+0x3 [e:\a\_work\335\s\src\inc\fixuppointer.h @ 68] 
04 (Inline) -------- coreclr!RelativePointer<Module *>::GetValueAtPtr+0x3 [e:\a\_work\335\s\src\inc\fixuppointer.h @ 85] 
05 (Inline) -------- coreclr!ReadPointer+0x3 [e:\a\_work\335\s\src\inc\fixuppointer.h @ 954] 
06 (Inline) -------- coreclr!ReadPointer+0x3 [e:\a\_work\335\s\src\inc\fixuppointer.h @ 954] 
07 (Inline) -------- coreclr!MethodTable::GetLoaderModule+0x3 [e:\a\_work\335\s\src\vm\methodtable.inl @ 176] 
08 (Inline) -------- coreclr!MethodTable::GetLoaderAllocator+0x3 [e:\a\_work\335\s\src\vm\methodtable.inl @ 182] 
09 0e60d0a0 5a299c42 coreclr!VirtualCallStubManager::ResolveWorker(struct StubCallSite * pCallSite = 0x0e60d13c, class Object ** protectedObj = 0x0e60d180, struct DispatchToken token = struct DispatchToken, VirtualCallStubManager::StubKind stubKind = SK_DISPATCH (0n2))+0x6b [e:\a\_work\335\s\src\vm\virtualcallstub.cpp @ 1719] 
0a 0e60d168 5a34a26b coreclr!VSD_ResolveWorker(struct TransitionBlock * pTransitionBlock = 0x0e60d17c, unsigned long siteAddrForRegisterIndirect = 0, unsigned int token = 0xa0000)+0x24f [e:\a\_work\335\s\src\vm\virtualcallstub.cpp @ 1611] 
0b 0e60d190 0e995fca coreclr!ResolveWorkerAsmStub(void)+0x1b [e:\a\_work\335\s\src\vm\i386\virtualcallstubcpu.hpp @ 525] 
WARNING: Frame IP not in any known module. Following frames may be wrong.
0c 0e60d194 5a33afeb 0xe995fca
0d 0e60d1a8 5a47fc7f coreclr!CallJitEHFinallyHelper(void)+0x28 [E:\A\_work\335\s\src\vm\i386\asmhelpers.asm @ 390] 
0e 0e60d200 5a3a2acc coreclr!CallJitEHFinally(class CrawlFrame * pCf = 0x43a07fdc, unsigned char * startPC = <Value unavailable error>, struct EE_ILEXCEPTION_CLAUSE * EHClausePtr = 0x0e60d260, unsigned long nestingLevel = 0)+0xb8 [e:\a\_work\335\s\src\vm\i386\excepx86.cpp @ 3385] 
0f 0e60d2d0 5a249cf5 coreclr!COMPlusUnwindCallback+0x15a70c [e:\a\_work\335\s\src\vm\i386\excepx86.cpp @ 2996] 
10 (Inline) -------- coreclr!Thread::MakeStackwalkerCallback+0x151 [e:\a\_work\335\s\src\vm\stackwalk.cpp @ 877] 
11 0e60d59c 5a2525c1 coreclr!Thread::StackWalkFramesEx(struct REGDISPLAY * pRD = 0x0e60d5c8, <function> * pCallback = 0x0ddb401c, void * pData = 0x0e60d954, unsigned int flags = 4, class Frame * pStartFrame = 0x00000000)+0x1d4 [e:\a\_work\335\s\src\vm\stackwalk.cpp @ 958] 
12 0e60d8d0 5a251f60 coreclr!Thread::StackWalkFrames(<function> * pCallback = 0x5a2483c0, void * pData = 0x0e60d954, unsigned int flags = 4, class Frame * pStartFrame = 0x00000000)+0xa1 [e:\a\_work\335\s\src\vm\stackwalk.cpp @ 1042] 
13 0e60d8f0 5a252a52 coreclr!UnwindFrames(class Thread * pThread = 0x0ddb3ea8, struct ThrowCallbackType * tct = 0x0e60d954)+0x3e [e:\a\_work\335\s\src\vm\excep.cpp @ 2228] 
14 (Inline) -------- coreclr!COMPlusAfterUnwind+0x98 [e:\a\_work\335\s\src\vm\i386\excepx86.cpp @ 482] 
15 0e60db48 5a2512fa coreclr!CPFH_RealFirstPassHandler(struct _EXCEPTION_RECORD * pExceptionRecord = 0x0e60dcb0, struct _EXCEPTION_REGISTRATION_RECORD * pEstablisherFrame = <Value unavailable error>, struct _CONTEXT * pContext = 0x0e60dd00, int bAsynchronousThreadStop = 0n0)+0x459 [e:\a\_work\335\s\src\vm\i386\excepx86.cpp @ 1263] 
16 0e60db88 5a250ef3 coreclr!CPFH_FirstPassHandler(struct _EXCEPTION_RECORD * pExceptionRecord = 0x0e60dcb0, struct _EXCEPTION_REGISTRATION_RECORD * pEstablisherFrame = 0x0e60e650, struct _CONTEXT * pContext = 0x0e60dd00)+0xc3 [e:\a\_work\335\s\src\vm\i386\excepx86.cpp @ 1401] 
17 0e60dbac 7772f1a2 coreclr!COMPlusFrameHandler(struct _EXCEPTION_RECORD * pExceptionRecord = 0x0e60dcb0, struct _EXCEPTION_REGISTRATION_RECORD * pEstablisherFrame = 0x0e60e650, struct _CONTEXT * pContext = 0x0e60dd00, struct _DISPATCHER_CONTEXT * pDispatcherContext = 0x0e60dc38)+0x83 [e:\a\_work\335\s\src\vm\i386\excepx86.cpp @ 1821] 
18 0e60dbd0 7772f174 ntdll!ExecuteHandler2+0x26
19 0e60dc98 7771cd86 ntdll!ExecuteHandler+0x24
1a 0e60dc98 76f21812 ntdll!KiUserExceptionDispatcher+0x26
1b 0e60e1bc 5a252d94 KERNELBASE!RaiseException+0x62
1c 0e60e264 5a3248fb coreclr!RaiseTheExceptionInternalOnly(class Object * throwable = <Value unavailable error>, int rethrow = <Value unavailable error>, int fForStackOverflow = 0n0)+0x11d [e:\a\_work\335\s\src\vm\excep.cpp @ 3039] 
1d 0e60e32c 2ed2b3e4 coreclr!IL_Throw(class Object * obj = <Value unavailable error>)+0x11b [e:\a\_work\335\s\src\vm\jithelpers.cpp @ 4860] 
1e 0e60e33c 0e3bd604 0x2ed2b3e4
1f 0e60e354 0e99a747 0xe3bd604
20 0e60e384 0e999f92 0xe99a747
21 0e60e3b0 0eecd3c9 0xe999f92
22 0e60e400 0e995ad1 0xeecd3c9
23 0e60e578 0e9934e6 0xe995ad1
24 0e60e5b0 0c3c7770 0xe9934e6
25 0e60e5d8 593868dd 0xc3c7770
26 0e60e5f4 59cfa31d System_Threading_Thread+0x68dd
27 0e60e624 59cfc0cc System_Private_CoreLib+0x4ca31d
28 0e60e638 5a33b0ef System_Private_CoreLib+0x4cc0cc
29 0e60e644 5a26fbf1 coreclr!CallDescrWorkerInternal(unsigned long pParams = 0xe60e6b8)+0x34 [E:\A\_work\335\s\src\vm\i386\asmhelpers.asm @ 618] 
2a (Inline) -------- coreclr!CallDescrWorkerWithHandler+0x52 [e:\a\_work\335\s\src\vm\callhelpers.cpp @ 78] 
2b 0e60e6e4 5a32d4e4 coreclr!MethodDescCallSite::CallTargetWorker(unsigned int64 * pArguments = 0x0e60e730, unsigned int64 * pReturnValue = 0x00000000, int cbReturnValue = 0n0)+0x235 [e:\a\_work\335\s\src\vm\callhelpers.cpp @ 620] 
2c 0e60e7bc 5a342b06 coreclr!ThreadNative::KickOffThread_Worker(void * ptr = 0x0e60e948)+0x104 [e:\a\_work\335\s\src\vm\comsynchronizable.cpp @ 260] 
2d 0e60e7d4 5a26f86a coreclr!ManagedThreadBase_DispatchInner(struct ManagedThreadCallState * pCallState = <Value unavailable error>)+0x70 [e:\a\_work\335\s\src\vm\threads.cpp @ 8852] 
2e 0e60e880 5a26f7bb coreclr!ManagedThreadBase_DispatchMiddle(struct ManagedThreadCallState * pCallState = <Value unavailable error>)+0x65 [e:\a\_work\335\s\src\vm\threads.cpp @ 8902] 
2f 0e60e8e4 5a3352b9 coreclr!ManagedThreadBase_DispatchOuter(struct ManagedThreadCallState * pCallState = 0x0e60e8ec)+0x78 [e:\a\_work\335\s\src\vm\threads.cpp @ 9161] 
30 0e60e908 5a2d9e7c coreclr!ManagedThreadBase_FullTransitionWithAD(struct ADID pAppDomain = struct ADID, <function> * pTarget = <Value unavailable error>, void * args = <Value unavailable error>, UnhandledExceptionLocation filterType = ManagedThread (0n2))+0x2f [e:\a\_work\335\s\src\vm\threads.cpp @ 9200] 
31 (Inline) -------- coreclr!ManagedThreadBase::KickOff+0x15 [e:\a\_work\335\s\src\vm\threads.cpp @ 9234] 
32 0e60e984 5a2d9d90 coreclr!ThreadNative::KickOffThread(void * pass = 0x0ad364d0)+0xcc [e:\a\_work\335\s\src\vm\comsynchronizable.cpp @ 380] 
33 0e60f824 76388484 coreclr!Thread::intermediateThreadProc(void * arg = 0x0abac020)+0x50 [e:\a\_work\335\s\src\vm\threads.cpp @ 2255] 
34 0e60f838 77713ab8 KERNEL32!BaseThreadInitThunk+0x24
35 0e60f880 77713a88 ntdll!__RtlUserThreadStart+0x2f
36 0e60f890 00000000 ntdll!_RtlUserThreadStart+0x1b
```

The managed stack, FWIW, is:

```
0:043> !clrstack
OS Thread Id: 0x3390 (43)
Child SP       IP Call Site
0e60d0d8 5a29aa9b [GCFrame: 0e60d0d8] 
0e60d118 5a29aa9b [StubDispatchFrame: 0e60d118] System.IDisposable.Dispose()
0e60d198 0e995fca Raven.Server.Rachis.FollowerAmbassador.Run()
0e60e580 0e9934e6 Raven.Server.Rachis.FollowerAmbassador.b__58_0(System.Object)
0e60e584 0c3c8000 Raven.Server.Utils.PoolOfThreads+PooledThread.DoWork()
0e60e5b8 0c3c7770 Raven.Server.Utils.PoolOfThreads+PooledThread.Run()
0e60e5e0 593868dd System.Threading.Thread.ThreadMain_ThreadStart() [E:\A\_work\321\s\corefx\src\System.Threading.Thread\src\System\Threading\Thread.cs @ 93]
0e60e5e8 59cfc00c System.Threading.ThreadHelper.ThreadStart_Context(System.Object) [E:\A\_work\335\s\src\mscorlib\src\System\Threading\Thread.cs @ 62]
0e60e5fc 59cfa31d System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [E:\A\_work\335\s\src\mscorlib\shared\System\Threading\ExecutionContext.cs @ 167]
0e60e630 59cfc0cc System.Threading.ThreadHelper.ThreadStart() [E:\A\_work\335\s\src\mscorlib\src\System\Threading\Thread.cs @ 91]
0e60e718 5a33b0ef [GCFrame: 0e60e718] 
0e60e8a8 5a33b0ef [DebuggerU2MCatchHandlerFrame: 0e60e8a8] 
```

We are using unsafe code, but we are pretty sure that we aren't corrupting the heap in any manner (lots of tests cover that) and if we were, I would expect to see the failure in different locations.

From trying to figure out what is going on, a few really strange things seem to be happening here:

Here is the actual failure:

```
FAULTING_IP: 
KERNELBASE!RaiseException+62
76f21812 8b4c2454        mov     ecx,dword ptr [esp+54h]
```

And the full register usage is:

```
(d2c.3390): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
eax=00000000 ebx=00e527a0 ecx=00000010 edx=15554140 esi=5a339280 edi=00e527a0
eip=5a29aa9b esp=0e60ce44 ebp=0e60d0a0 iopl=0         nv up ei pl zr na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010246
```

As you can see, the `esp` value has a non null value, but checking the memory location with the offset provided to the instruction shows just zeros.

While troubleshooting this, we found a `NullReferenceException` in our code. We fixed it, but that made the problem go away. 
We suspect that this is some issue related to error handling inside the CoreCLR during JIT generation.
We have run into a different issue with KB4487017 (See: https://github.com/dotnet/coreclr/issues/22597), but we are reproducing this on different versions of Windows and without the KB in question.

We aren't able to reproduce this issue in 64 bits.

### PR DESCRIPTION
**Pull request by AndyAyersMS**
When a filter is finished executing, control can logically pass to the
associated handler, any enclosing handler or filter, or any finally or fault
handler nested within the associated try. This is a consequence of two-pass EH.

The jit was not propagating liveness from the nested handlers, which lead to a
live object being collected inadvertently.

This change updates `fgGetHandlerLiveVars` to find the nested handlers and
merge their live-in into the filter block live sets.

Because these implicit EH flow edges can create cycles in the liveness dataflow
equations, the jit will also now always iterate liveness when it sees there is
exception flow, to ensure livness reaches the appropriate fixed point.

Added test case.

Closes #22820.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@BruceForstall PTAL
cc @dotnet/jit-contrib @janvorli 

No diffs on x64 (with `--gcinfo`).

Diffs on x86 on the test case and in a handful of places in corelib and fx.
```
PMI Diffs for System.Private.CoreLib.dll, framework assemblies for x86 default jit
Summary:
(Lower is better)
Total bytes of diff: 16 (0.00% of base)
    diff is a regression.
Top file regressions by size (bytes):
          10 : Microsoft.CodeAnalysis.dasm (0.00% of base)
           3 : System.Security.Cryptography.Algorithms.dasm (0.00% of base)
           3 : System.Security.Cryptography.Cng.dasm (0.00% of base)
3 total files with size differences (0 improved, 3 regressed), 126 unchanged.
Top method regressions by size (bytes):
           5 ( 0.18% of base) : Microsoft.CodeAnalysis.dasm - <ComputeAnalyzerDiagnosticsAsync>d__51:MoveNext():this
           5 ( 0.46% of base) : Microsoft.CodeAnalysis.dasm - <SetActiveTreeAnalysisTaskAsync>d__58:MoveNext():this
           3 ( 0.16% of base) : System.Security.Cryptography.Algorithms.dasm - System.Security.Cryptography.RsaPaddingProcessor:PadOaep(struct,struct):this
           3 ( 0.16% of base) : System.Security.Cryptography.Cng.dasm - System.Security.Cryptography.RsaPaddingProcessor:PadOaep(struct,struct):this
Top method regressions by size (percentage):
           5 ( 0.46% of base) : Microsoft.CodeAnalysis.dasm - <SetActiveTreeAnalysisTaskAsync>d__58:MoveNext():this
           5 ( 0.18% of base) : Microsoft.CodeAnalysis.dasm - <ComputeAnalyzerDiagnosticsAsync>d__51:MoveNext():this
           3 ( 0.16% of base) : System.Security.Cryptography.Algorithms.dasm - System.Security.Cryptography.RsaPaddingProcessor:PadOaep(struct,struct):this
           3 ( 0.16% of base) : System.Security.Cryptography.Cng.dasm - System.Security.Cryptography.RsaPaddingProcessor:PadOaep(struct,struct):this
4 total methods with size differences (0 improved, 4 regressed), 225979 unchanged.
System.Private.CoreLib.dasm had 2616 diffs
NuGet.Protocol.Core.v3.dasm had 156 diffs
System.Net.WebSockets.dasm had 13 diffs
```
Corelib text diffs seem to be an interleaving artifact. Looked at random sampling of the other diffs and all the methods with diffs had a filter with a nested try/finally. For example:

https://github.com/dotnet/corefx/blob/f7539b726c4bc2385b7f49e5751c1cff2f2c7368/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L442-L464

Size regressions are from extra prolog inits.

**Comment by AndyAyersMS** [comment]
Oops, forgot to have the new test case return 100 on success.

**Comment by AndyAyersMS** [comment]
Actually I was wrong about no diffs on x64 (forgot to rebuild the new jit). Actual diffs are similar to those on x86:
```
PMI Diffs for System.Private.CoreLib.dll, framework assemblies for x64 default jit
Summary:
(Lower is better)
Total bytes of diff: 18 (0.00% of base)
    diff is a regression.
Top file regressions by size (bytes):
          14 : Microsoft.CodeAnalysis.dasm (0.00% of base)
           4 : NuGet.Protocol.Core.v3.dasm (0.00% of base)
2 total files with size differences (0 improved, 2 regressed), 127 unchanged.
Top method regressions by size (bytes):
           9 ( 0.29% of base) : Microsoft.CodeAnalysis.dasm - <ComputeAnalyzerDiagnosticsAsync>d__51:MoveNext():this
           5 ( 0.37% of base) : Microsoft.CodeAnalysis.dasm - <SetActiveTreeAnalysisTaskAsync>d__58:MoveNext():this
           4 ( 0.24% of base) : NuGet.Protocol.Core.v3.dasm - <OpenNupkgStreamAsyncCore>d__26:MoveNext():this
Top method regressions by size (percentage):
           5 ( 0.37% of base) : Microsoft.CodeAnalysis.dasm - <SetActiveTreeAnalysisTaskAsync>d__58:MoveNext():this
           9 ( 0.29% of base) : Microsoft.CodeAnalysis.dasm - <ComputeAnalyzerDiagnosticsAsync>d__51:MoveNext():this
           4 ( 0.24% of base) : NuGet.Protocol.Core.v3.dasm - <OpenNupkgStreamAsyncCore>d__26:MoveNext():this
3 total methods with size differences (0 improved, 3 regressed), 193918 unchanged.
5 files had text diffs but not size diffs.
System.Private.CoreLib.dasm had 720 diffs
System.Security.Cryptography.Algorithms.dasm had 433 diffs
System.Security.Cryptography.Cng.dasm had 433 diffs
System.Net.WebClient.dasm had 84 diffs
System.Net.WebSockets.dasm had 78 diffs
```
File line diff count is high because GC info doesn't diff very well. Corelib file diff again appears to be an interleaving issue; something has changed recently that breaks jit-diff determinism, or maybe it's an issue with the `--gcinfo` variant that I don't use all that often.

**Comment by AndyAyersMS** [comment]
Ubuntu test builds failing in msbuild with errors like:
```
System.IO.IOException: Broken pipe ---> System.Net.Sockets.SocketException: Broken pipe
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
```
@dotnet-bot retest Ubuntu x64 Checked Innerloop Build and Test
@dotnet-bot retest Ubuntu x64 Checked Innerloop Build and Test (Jit - TieredCompilation=0) 

OSX with its usual hangup issue.

@dotnet-bot retest OSX10.12 x64 Checked Innerloop Build and Test

Throwing in some GC stress legs...

@dotnet-bot test Windows_NT x86 Checked gcstress0xc
@dotnet-bot test Windows_NT x86 Checked gcstress0xc_jitstress1
@dotnet-bot test Windows_NT x86 Checked gcstress0xc_jitstress2
@dotnet-bot test Windows_NT x64 Checked gcstress0xc

**Comment by janvorli** [comment]
The change doesn't look right for non-x86 (tried on x64). It does what I was afraid of - it causes double reporting of the problematic variable during GC scan. As i've mentioned in https://github.com/dotnet/coreclr/issues/22820#issuecomment-469859758, the variable is not expected to be reported by the GC info as live in the filter, since when the filter runs, we have the frame that has thrown the exception on stack and so we report it during the stack walk twice - once from the filter frame and second time from the frame of the throw.
Moreover, the GC info now contains records for the stack slot twice (slots 0 and 1). Once reported as pinned (?) in the filter and once as not pinned out of the filter. See from the jitdump of the simple repro:
```
Stack slot id for offset -16 (0xfffffff0) (frame) (pinned) = 0.
Stack slot id for offset -16 (0xfffffff0) (frame) = 1.
Register slot id for reg rax = 2.
Register slot id for reg rsi = 3.
Register slot id for reg rcx = 4.
Register slot id for reg rdx = 5.
Set state of slot 0 at instr offset 0x82 to Live.
Set state of slot 0 at instr offset 0xc4 to Dead.
Set state of slot 1 at instr offset 0x15 to Live.
Set state of slot 1 at instr offset 0x56 to Dead.
Set state of slot 1 at instr offset 0x5e to Live.
Set state of slot 1 at instr offset 0x82 to Dead.
```

The stack walker for non windows-x86 has an extremely complicated logic full of assumptions about what GC info does report and what it doesn't in funclets and filters and their parent frames. So while we could possibly modify it to reflect this new way of reporting liveness and prevent the double reporting, I would like to avoid touching that code as much as I can. Bugs in this code usually result in very hard to reproduce and debug GC holes. 

So I would prefer modifying the change to be x86 windows only (not even x86 Unix as that one uses the same EH as x64, arm and arm64 everywhere, the x86 windows is an exception).

@jkotas do you have any opinion here?

**Comment by janvorli** [comment]
Here is a GC stack walk log on x64 showing the double reporting (see `Reporting frame sp-0x10`)
```
TID 1610: condemned generation num: 2
TID 1610: { =========== BEGINGC 1, (requested generation = 2, collect_classes = 1) ==========
TID 1610: GCScan: Promotion Phase = 1
TID 1610: { Starting scan of Thread 0000023027567F70 ID = 1
TID 1610: Scanning ExplicitFrame 0000006660979510 AssocMethod = 00007FFEB9365A60M frameVTable = 00007FFF18EE8DC0V
TID 1610: Scanning ExplicitFrame 0000006660979510 AssocMethod = 00007FFEB9365A60M frameVTable = 00007FFF18EE8DC0V
TID 1610: Scanning Frameless method 00007FFEB9498370M ControlPC = 00007FFEB91F8FB8
TID 1610: Scanning Frame for method ILStubClass:IL_STUB_PInvoke
TID 1610: Scanning Frameless method 00007FFEB9365D58M ControlPC = 00007FFF1609AAFB
TID 1610: Scanning Frame for method System.GC:Collect
TID 1610: Scanning Frameless method 00007FFEB93831D8M ControlPC = 00007FFEB91F5F0F
TID 1610: Scanning Frame for method SimpleAyendeRepro.Program:IsExpectedException
TID 1610: Reporting r6 at 00000066`60979580 as base pointer  00000230`2965ee10 System.Exception
TID 1610: Returning 0x000000666097CF80 as the parent stack frame for filter funclet 0x0000006660979660
TID 1610: STACKWALK: Found Filter funclet @ SP: 0000006660979620, m_crawl.pFunc = 00007FFEB9383248; FuncletParentCallerSP: 000000666097CF80
TID 1610: Scanning Frameless method 00007FFEB9383248M ControlPC = 00007FFEB91F5A15
TID 1610: Scanning Frame for method SimpleAyendeRepro.Program:Main
TID 1610: "Live" scratch register r1  not reported
TID 1610: Reporting frame sp-0x10 at 00000066`6097cf60 as pinned base pointer  00000230`2965edf8 SimpleAyendeRepro.DisposableObject
TID 1610: Scanning ExplicitFrame 000000666097CC28 AssocMethod = 0000000000000000M frameVTable = 00007FFF18EAC100V
TID 1610: STACKWALK: Reached parent of filter funclet @ CallerSP: 000000666097CF80, m_crawl.pFunc = 00007FFEB9383248
TID 1610: Scanning Frameless method 00007FFEB9383248M ControlPC = 00007FFEB91F59B5
TID 1610: Scanning Frame for method SimpleAyendeRepro.Program:Main
TID 1610: "Live" scratch register r1  not reported
TID 1610: Reporting r6 at 00000066`6097cc78 as base pointer  00000230`2965ee10 System.Exception
TID 1610: Reporting frame sp-0x10 at 00000066`6097cf60 as base pointer  00000230`2965edf8 SimpleAyendeRepro.DisposableObject
TID 1610: Scanning ExplicitFrame 000000666097D6F8 AssocMethod = 0000000000000000M frameVTable = 00007FFF18F28370V
TID 1610: Scanning ExplicitFrame 000000666097E090 AssocMethod = 0000000000000000M frameVTable = 00007FFF18F28370V
TID 1610: Ending scan of Thread 0000023027567F70 ID = 0x1 }
TID 1610: { Starting scan of Thread 0000023027599A80 ID = 2
TID 1610: Scanning ExplicitFrame 00000066610FF930 AssocMethod = 0000000000000000M frameVTable = 00007FFF18EC7DE0V
TID 1610: Ending scan of Thread 0000023027599A80 ID = 0x2 }
TID 1610: { Starting scan of Thread 00000230294C9270 ID = 3
TID 1610: Ending scan of Thread 00000230294C9270 ID = 0x3 }
TID 1610: GcScanHandles (Promotion Phase = 1)
TID 1610: ========== ENDGC 1 (gen = 2, collect_classes = 1) ===========}
```

**Comment by janvorli** [comment]
I've spent more time debugging on x86 and I have realized that I got mislead by the fact that the "k" windbg command was not showing the frame where the "throw" happened. It turns out the frame is still there and our stack walker still walks it. 
So it seems to me now that we may be able to actually fix the issue in the runtime without touching the JIT. The stack walker code for x86 was written with the assumption that the filter frame reports the variables of the parent frame (the one that has thrown the exception), which as we've seen was true for the old JIT32. Now with the new x86 JIT behaving the same way as the x64 one and not reporting those locals, it seems we may be able to change the x86 part of the stack walker to not to handle the filter frame in a special way and it seems it would fix the problem too.

However, I am a bit torn here, as your current change that reports the variables in the filter on all platforms is actually better tracking the object lifetime reality. So it seems more "correct". Moreover, I've found that the double reporting on the other platforms doesn't cause trouble thanks to the fact that it is reported as "pinned" for the filter. It seems it just adds some overhead.

**Comment by BruceForstall** [comment]
fyi, there is a discussion of GC, filters, and pinning here: https://github.com/dotnet/coreclr/blob/master/Documentation/botr/clr-abi.md#filter-gc-semantics

**Comment by AndyAyersMS** [comment]
There was already an edge case for extending liveness reporting in filters in funclet EH models:

https://github.com/dotnet/coreclr/blob/5a2650959268bf0a760965a2bd8cca34301cd1a1/src/jit/liveness.cpp#L1071-L1082

And there is this bit of compensating logic in the jit GC encoder:

https://github.com/dotnet/coreclr/blob/5a2650959268bf0a760965a2bd8cca34301cd1a1/src/jit/gcencode.cpp#L107-L128

So the pinning is evidently the thing that makes the double reporting work out.

**Comment by janvorli** [comment]
@BruceForstall thank you for the pointer to the doc. Then this change is definitely correcting the existing state according to the doc and should go in as is.

**Comment by janvorli** [comment]
@AndyAyersMS I think we should port this to 2.1 (and 2.2 unless changes from 2.1 flow automatically to 2.2).

**Comment by AndyAyersMS** [comment]
> I think we should port this to 2.1

I was thinking along those lines too. Let me look into it.

**Pull request merged**
