### PR TITLE
[release/2.2] Port the fix for JIT IMPL_LIMITATION for EntityFramework 

### PR DESCRIPTION
**Pull request by briansull**
Port the following two fixes that address the JIT's IMPL_LIMITATION associated with offsets > 255 for LclVar with LclVar numbers above 32767.

Allocate the lvaOutgoingArgSpaceVar early #17793 
The SIMD types must use the struct code path #19065

### CODE REVIEW

**Comment by briansull** [comment]
Fixes #21303

**Comment by briansull** [comment]
#### Description
The JIT compiler has a limitation that can be encountered by users of the EntityFrameworks.
This issue has been fixed in master since April 27th and we have a request to back port this into 2.2
The limitation occurs only in methods that have more than 32767 LclVars 
(typically most of these will be JIT internal compiler temps)
and we have one or more callsites that require more than 256 bytes of stack to pass arguments.
When this occurs  the JIT throws an IMPL_LIMITATION and fails to compile the method.

This fix addresses this issue by changing when we allocate the lvaOutgoingArgSpaceVar.
Previously we allocated this variable after we completed the importing and inlining phases,
and these phases often will create a large number of compiler temps. 

This resulted in this variable being assigned a LclVar number greater than 32767.
This variable is used to store the stack based out going arguments for all the calls in the method.
Andwhen the method had a callsite that beeded more than 256 bytes of stack space, we hit the
IMPL_LIMITATION.

This fix here is to allocate the lvaOutgoingArgSpaceVar very early right, before the JIT runs 
the importing and inlining phases.  THis ensures that this important LclVar will get a low LclVar
number, thus avoiding this IMPL_LIMITATION.
#### Customer Impact
Users of the EntityFrameworks, and some other machine generated methods can hit this limiation in the JIT.
This fix greatly reduces the number of programs that hit this JIT limitation.
#### Regression?
No
#### Risk
Very low, This fix has been present in both the Desktop CLR 4.8 and in the master branch for over 6 months.

**Comment by briansull** [comment]
@dotnet-bot Test Windows_NT x64 Formatting

**Comment by briansull** [comment]
@dotnet-bot Test  Ubuntu x64 Checked Innerloop Build and Test

**Comment by briansull** [comment]
@AndyAyersMS @RussKeldorph 
One of you may want to Merge this after shiproom approves it

**Comment by RussKeldorph** [comment]
@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test
@dotnet-bot test Ubuntu arm Cross Checked no_tiered_compilation_innerloop Build and Test
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test 
@dotnet-bot test Ubuntu x64 Checked no_tiered_compilation_innerloop Build and Test

**Comment by vivmishra** [comment]
Approved for 2.2.2

**Comment by briansull** [comment]
Branch not yet open for 2.2.2

**Pull request merged**
