### PR TITLE
Fixed build step, Priority 1 tests should now run nightly for OSX/Linux

### PR DESCRIPTION
**Pull request by wtgodbe**

### CODE REVIEW

**Comment by wtgodbe** [comment]
@dotnet-bot test this please.

**Comment by wtgodbe** [comment]
@dotnet-bot test FreeBSD x64 Debug please

**Comment by wtgodbe** [comment]
@dotnet-bot test this please.

**Comment by gkhanna79** [comment]
@rahku Can you please enable the P1 tests for Windows build as well?

**Comment by rahku** [comment]
I believe you meant for arm64....

**Comment by gkhanna79** [comment]
Nope - I meant to enable them for Windows x64.

**Pull request merged**
