### PR TITLE
printing dumpling url at dumpling upload time

### PR DESCRIPTION
**Pull request by bryanar**
Proposal to take care of issue #6710

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
You may want to pipe stderr and stdout to `tee` rather than reading from the file you just wrote (especially since you seem to be appending to this file, so it may have other stuff in it that you don't want to print each time something gets added).

**Comment by bryanar** [comment]
@adityam Never used tee, how does this look?

**Comment by adityamandaleeka** [comment]
It would be something like `./dumpling blah blah 2>&1 | tee filename`.

BTW, you mentioned the wrong Aditya again :wink:

**Comment by bryanar** [comment]
I do not have a linux box on me at the moment, help me understand something: If I pipe error to tee will it end up in the file? I do not want that. I'd rather the error just show up on the console.

**Comment by adityamandaleeka** [comment]
@bryanar Sure. If you don't want stderr in the file you don't need the `2>&1` part.

**Comment by adityamandaleeka** [comment]
LGTM (I assume you tested locally to make sure it actually works).

**Comment by bryanar** [comment]
Sure did, this was the perfect solution. Thanks for showing me Tee.

**Pull request merged**
