### PR TITLE
Use BYOC pools in finalize-publish.yml

### PR DESCRIPTION
**Pull request by echesakovMSFT**
See https://github.com/dotnet/coreclr/pull/23501#issuecomment-479993414 

@sdmaclea Since you setup a pool for `Finalize_Publish_Versions` job in https://github.com/dotnet/coreclr/commit/51d033897eb5663ea8bab53704406d9fd82af98f - is there any reason why this is `Hosted VS2017`? Should we use BYOC internal pools instead?

### CODE REVIEW

**Comment by sdmaclea** [comment]
I just copied what was being used in core-setup and/or corefx.

**Comment by echesakovMSFT** [comment]
@dagood Then I will just only change the pool for "Publish to BAR" job

**Comment by echesakovMSFT** [comment]
No yaml syntax errors - merging since it's not going to affect the public CI and can be tested in the internal project only

**Pull request merged**
