### PR TITLE
ARM64: Add email notification for failing job

### PR DESCRIPTION
**Pull request by kyulee1**
Similar to roslyn job, added an email publisher to the job.
Fixed job title to reflect "Test" for Checked/Release case.
Refined triggered message to enable individual configuration.
So, instead of "test Windows_NT arm64" that runs all configurations,
just "test Windows_NT arm64 Checked" for instance.

### CODE REVIEW

**Comment by kyulee1** [comment]
@dotnet-bot test ci

**Comment by kyulee1** [comment]
@mmitche @dotnet/arm64-contrib PTAL

**Comment by mmitche** [comment]
LGTM

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by jashook** [comment]
LGTM

**Comment by kyulee1** [comment]
@dotnet-bot test ci

**Comment by mmitche** [comment]
@kyulee1 There is a bug in the regex for one of the jobs that is blocking things

**Comment by kyulee1** [comment]
@mmitche Can you elaborate this? Does it mean my change in the regex is wrong? Then which part?

**Comment by mmitche** [comment]
No you're good, there was an invalid regex in the checked in sources, which was causing issues with the system initializing new pull requests.  I fixed this, and it should be good in 10-15 mns (whenever the generator reruns)

**Comment by kyulee1** [comment]
@dotnet-bot test ci

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
Okay well that didn't do it either, hmm

**Pull request merged**
