### PR TITLE
Speed up StringBuilder.Append(char, int) for null chars

### PR DESCRIPTION
**Pull request by jamesqo**
Supplants #3277 by addressing the issue at its root; if a null char is passed into `Append`, we don't have to fill the array with it since the memory is already zero-initialized.

### CODE REVIEW

**Comment by jkotas** [comment]
This does not work. Consider:

```
            var sb = new StringBuilder("Hello world");
            sb.Length = 1;
            sb.Append('\0', 10);
            Console.WriteLine(sb);
```

Without your change: H
With your change: Hello world

**Comment by davidfowl** [comment]
@jkotas is there a test case for that? Seems like everything is green...

**Comment by jkotas** [comment]
- This change is introducing a new special path. The tests had to be written with the implementation in mind: adding a new special path in the implementation had to be matched with adding a test that is exercising the special path. It is not possible to have tests for all special paths that somebody may add in the implementation - it is unbounded problem.

- Even if there was coverage, the CI is running P1 tests only. The coverage for such special path is unlikely to be P1 test.

**Comment by stephentoub** [comment]
I'm going to close this.  Besides the change being broken, appending null chars is not at all common and doesn't need to be optimized like this, especially when it introduces cost for other more common cases.

**Pull request closed without merging**
