### PR TITLE
Refactor `StructArrayList` for the GC info encoder.

### PR DESCRIPTION
**Pull request by pgavlin**
The GC info encoder is the only client of `StructArrayList`. This change moves
the type into the encoder's sources and refactors it to remove utilcode dependencies.
There are still a few dependencies on CLR headers for assertions and safe integer
math.

### CODE REVIEW

**Comment by pgavlin** [comment]
I've presented this change as two commits to (hopefully) make the refactoring a bit easier to follow. I will squash away the first commit (which does not build) before merging this PR.

**Comment by pgavlin** [comment]
@jkotas @russellhadley @BruceForstall @dotnet/jit-contrib PTAL

**Comment by pgavlin** [comment]
This is part of #4127.

**Comment by pgavlin** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Comment by pgavlin** [comment]
Ping.

**Comment by russellhadley** [comment]
@pgavlin It's good to see the cleanup.  The code looks simpler.  I do wonder that it was done in one step (the first commit, which shows just the move, doesn't build).  Also what's the risk of gcinfo changes here.  Does it make sense to diff the gcinfo output?

**Comment by pgavlin** [comment]
> I do wonder that it was done in one step (the first commit, which shows just the move, doesn't build)

I hoped that including the two commits in the PR would make the refactorings (i.e. the second commit) easier to grok. As mentioned above, I'll squash the first commit away now that the code has been reviewed.

> Does it make sense to diff the gcinfo output?

Sure. There shouldn't be any changes assuming that the refactored code is functionally equivalent to the original.

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test

**Comment by pgavlin** [comment]
@russellhadley I've verified that there are no diffs with this change.

**Comment by russellhadley** [comment]
LGTM - merge away.

**Comment by pgavlin** [comment]
The OS X failure is an infrastructural issue; the earlier (pre-squash) run passed.

**Pull request merged**
