### PR TITLE
Increase timeouts for R2R jobs to 4 hours. Also enable mistakenly disabled CentOS R2R jobs

### PR DESCRIPTION
**Pull request by wtgodbe**

### CODE REVIEW

**Comment by wtgodbe** [comment]
@gkhanna79 PTAL

**Comment by gkhanna79** [comment]
LGTM

**Comment by gkhanna79** [comment]
Can you please issue a Pri1r2r job on OSX and Ubuntu (checked build) to confirm it works before merging the PR?

**Comment by wtgodbe** [comment]
@dotnet-bot test CI please

**Comment by wtgodbe** [comment]
@dotnet-bot test OSX Checked pri1r2r please.

**Comment by wtgodbe** [comment]
@dotnet-bot test Ubuntu Checked pri1r2r please.

**Comment by wtgodbe** [comment]
@gkhanna79 I don't think the r2r jobs I just triggered will have the 4 hour timeouts yet, since PRs are tested with the version of netci.groovy that's currently in master. We'd have to merge this, then trigger a pr1 job to see if it times out after 4 hours.

**Comment by gkhanna79** [comment]
Ok - in that case, once this is merged, can you please trigger test jobs to confirm the checked and Release Ubuntu and OSX Pri1r2r runs are clean?

**Comment by wtgodbe** [comment]
Can do

**Comment by wtgodbe** [comment]
GenPRTest passed, so I'm merging

**Pull request merged**
