### PR TITLE
ThreadPool limit outstanding thread requests

### PR DESCRIPTION
**Pull request by sdmaclea**

### CODE REVIEW

**Comment by sdmaclea** [comment]
@benaadams @stephentoub This is an alternative to #13010.  It provides similar benefits.

In looking at the issue, ThreadPool.cs was requesting an additional thread anytime the work item queue was not empty.  That meant on high core count machines, any time there was a backlog, ThreadPool request numProcessors more threads.  So once the backlog was cleared, there would be numProcessor outstanding thread requests to be satisfied.

The patch as drafted limits outstanding requests to 4 additional threads.  This is essentially a slew rate limit on the requested threads.  It may impact the step response, but 4 is probably where this design was originally tested.

I have tried other variants of this patch, with a little or a lot more complexity.  This seems like the simplest approach.  Here are some of the alternatives

1. Keep accurate count of outstanding requests and limit requested threads to 1 per request.  This is better, but adds overhead of counting requests.  Also in many case more than one request will be handled per thread.  There still will be excessive threads requested, but arguably fewer (4 per burst).
2. Keep statistics avgReq/sec, avgReq/sec/perThread, avgBacklog.. Predict needed threads based on history.  Surprisingly the statistics are not incredibly stable.  They are good enough for a first order estimate, but not much better than limiting the slew rate.

I actually slightly prefer the alternatives, but testing seems to indicate they add a lot of complexity w/o much additional improvement.  The basic patch as written improves the unpipelined plaintext score when driven from the same machine by 35%.  The more complicated patches are able to improve by 50%, but they need much more testing to justify.  Since the affected configuration is pretty niche, simpler seems better.

Note: I also fiddled with 8 instead of 4, since it corresponded to typical desktops, but I settled on 4.

I have not tested SkyLake yet, but wanted feedback before spending too much time optimizing another approach.

I think if something like this is accepted, we can abandon #13010

**Comment by jkotas** [comment]
cc @kouvel @jkoritzinsky

**Comment by sdmaclea** [comment]
https://github.com/benaadams/coreclr/commit/1912680e27cb4f21a69c751020e31867a25622fd as drafted by @benadams in comments for #6476 should also be considered.  As it represents the original seed of this idea.

A hybrid approach may also be valuable.  Limit outstanding thread requests to some function of queued items.  i.e. `Math.Min(queuedItems, 4+ queuedItems/4)`

**Comment by sdmaclea** [comment]
Observations while trying to find a better solution

- UnfairSemaphore is operating blind.  For the managed thread pool there is more information available in ThreadPool.cs
- Queue theory requires Worker capacity to exceed Work.  So we need more than enough worker threads.
- When we run out of work all threads currently return to UnfairSemaphore
- Ideal productivity of worker threads occurs when the thread is kept active.  This prevents it returning to UnfairSemaphore and cooling it's cache.
- The delicate balance requires managing the Work item back log to add threads if the backlog grows
- In a perfectly balanced system one work item arrives as one item is consumed.  A backlog of one item would be sufficient to keep the system humming if the items arrived at a perfectly regular rate.
- Item arrival is more likely to follow a Poisson distribution.  So when balance the probability of item enqueue approximately equal to the probability of an item dequeue.  A Poisson distribution has a standard deviation equal to the square root of the expected item.  To handle the distribution of item arrival we would probably need a 3 SD or 4 items in the backlog.
- Reality is the arrival rate is even more unpredictable than a Poisson distribution.  There are feedback interaction, GC affects.
- The system is a bit over constrained to be able to be perfectly optimized.
- Adding local spin/sleep would allow more control of workers and possibly reduce latency
- Dead time can be long, sleeping/spinning might be insufficient to cover latency
- Real systems are noisy.  
- While step response is theoretically interesting and perhaps interesting for specific benchmarks.  It is an corner case.
- Thread wake time is critical.  The problem is improved by reducing the period of time waiting for threads.
- Pipelining thread wakeup helps cover the long wakeup latency, but the benefits are limited.  The longer pipeline requires more speculation on whether threads will be needed.  Some limit is appropriate.  For low number of requests 1:1 is appropriate.  For larger it seems like an asymptotic function is more appropriate.  Something like `threadRequests = sqrt(2 * workItemBacklog) - runningThreads` might be ideal.
- A thread pool is by definition for background work items.  Absolute latency is not necessarily a critical parameter.

**Comment by kouvel** [comment]
This would have an issue with bursty work. When a burst of work is queued from an idle state, 4 threads are requested. More threads won't be requested until those 4 wake up and decrease the request count. In that gap of time, many work items may be queued and that burst would only run on 4 threads. This may work well when fewer threads are desired as the system may be busy, but it could hurt when the system is not busy by underutilizing the CPU.

I think it may work to keep track of how many threads are processing work in Dispatch and use it to determine the max thread requests at any given time. Somewhat similar to what you suggested as an alternative, but something simpler like:

```c#
private static readonly int MaxThreadRequestsWhenIdle = ThreadPoolGlobals.processorCount;
private const int MaxThreadRequestsWhenSaturated = 4;

EnsureThreadRequested:
int numSatisfiedThreadRequests = Math.Min(_numWorkingThreads, MaxThreadRequestsWhenIdle);
int maxThreadRequests = Math.Max(MaxThreadRequestsWhenIdle + MaxThreadRequestsWhenSaturated - numSatisfiedThreadRequests, MaxThreadRequestsWhenIdle);
```

With that from an idle state it would request proc count threads and scale it down to a maximum of 4 requests when at least proc count threads are processing work in Dispatch. That would avoid having too many pending requests while the thread pool is saturated. Thoughts?

**Comment by sdmaclea** [comment]
@kouvel I am out of office at the moment.  I'll think about it some more next week.  I am trying to solve the problem when requests do not saturate.  Work is only sufficient to keep 16-20 processors busy of 48 available.

Right now there is a ~2 threads request per enqueued item.  If we could eliminate requesting multiple threads per item, the problem might also be greatly reduced.  I'll play with it next week.  I'll also upload the more complicated solution

**Comment by kouvel** [comment]
How are there 2 thread requests per enqueued item? It looks like it would request a thread if the number of threads requested and not yet started processing work is less than the proc count, so it would request at most one thread per enqueued item. Once saturated, it would not request a thread for an enqueued item and there would be proc count thread requests pending.

> I am trying to solve the problem when requests do not saturate. Work is only sufficient to keep 16-20 processors busy of 48 available.

Any solution we use for that should be able to revert back to using proc count threads when it would be appropriate to do so, even while new requests are not coming in, as otherwise it would suffer from underutilizing the CPU.

Regarding your idea of allowing hill climbing to reduce the min number of threads below the proc count, perhaps it could be combined with checking the CPU utilization. If the CPU utilization is high (> 90 or 95%), then it could allow hill climbing to use fewer threads than the proc count. Once the CPU utilization drops, it would have to reset to using proc count threads if the thread count is currently lower, and make sure new threads are started/awakened to pick up already queued work in case new work is not entering the queue. That would allow hill climbing to reduce the number of threads and keep the thread count low as long as the CPU utilization remains high. The gate thread already monitors CPU utilization, so maybe it can be the trigger to allow fewer number of threads and to raise the thread count.

**Comment by kouvel** [comment]
> CPU utilization

This may not work on Unixes. We're using getrusage for CPU utilization and it looks like it only gets the calling process' utilization and not the total utilization. Is there a way to get system-wide utilization?

**Comment by benaadams** [comment]
> How are there 2 thread requests per enqueued item? 

Queuing an item [makes a thread request](https://github.com/dotnet/coreclr/blob/51713ad7d142a726c54c6e7ae3996fe0ccb1e1d6/src/mscorlib/src/System/Threading/ThreadPool.cs#L468) and dequeuing an item [makes a thread request](https://github.com/dotnet/coreclr/blob/51713ad7d142a726c54c6e7ae3996fe0ccb1e1d6/src/mscorlib/src/System/Threading/ThreadPool.cs#L599), so there can be 2 thread requests per item (caps on outstanding requests aside)

**Comment by kouvel** [comment]
Ah I see, missed that. Not sure why it is done, but in light of that, I guess the effect of this change is only to delay using proc count threads by requesting only 4 at a time. With a long enough queue, it would eventually use proc count threads, just slower than before since it has to wait for the queued threads to wake up before more threads are requested. So I suspect it would only help to use fewer threads when it is beneficial to do so (such as in the scenario you're testing) when it gets short bursts of work frequently and the work is processed before more threads are requested. I still think it would be better to use hill climbing for this purpose, as it can also work for non-bursty work.

@stephentoub, do you happen to know why a thread is requested every time an item is dequeued in Dispatch?

**Comment by benaadams** [comment]
I think its if you hit the cap while queuing; you need to add requests back when dequeuing. Since its based on a capped value rather than a total outstanding, you have to make a request to be sure.

**Comment by kouvel** [comment]
Yea it looks like the thread pool does not use the return value from Dispatch to determine when to stop working. Instead, it looks at requested threads. So if Dispatch returns while there is still work (due to quantum expiring for instance), it looks like it would need to request a thread to have the current thread continue working. Seems like something that could be fixed.

**Comment by sdmaclea** [comment]
As I have been thinking about this patch.  It is particularly bad for the following case;

+ Burst of >4 work items.
+ Each request is long.
+ No additional requests

I this case the items, 5-N would be delayed until the first item completed.  If it was minutes that would be very bad.

I will clean up and test @benaadams draft.  I think it is a solid approach and will at least fix the two threads requested per work item.  It also occasionally has the benefit of reducing thread requests for work items which have already been completed (by reusing an existing request).  I think the races can be handled.

If we get rid of the excess thread requests, hill climbing should be fine.

**Comment by sdmaclea** [comment]
@kouvel 

> it looks like it would need to request a thread

I think that case is handled by the finally clause.

There is also the need to support more than `ThreadPoolGlobals.processorCount` running threads for the  case where work items are blocking on I/O...

**Comment by kouvel** [comment]
> I think that case is handled by the finally clause.

Yea I was thinking that would be enough but:

> There is also the need to support more than ThreadPoolGlobals.processorCount running threads for the case where work items are blocking on I/O...

That's very true, without a pending request it would block the starvation heuristic from adding more threads. I think it's still possible to reduce the number of thread requests upon dequeue (it shouldn't be necessary to request a thread if there is already at least one thread request pending). I'll think about it a bit more and will try some things.

**Comment by sdmaclea** [comment]
I updated the comment with :bulb::ok_hand: above.  I realized, I had miss-predicted the behaviour in the case described above.  When the work items take a long time, the throttling of threads is gated by the thread start time and not the work item time.  So for work items with long run time, the thread start time will be negligible.

This is still a reasonable patch.  It throttles the thread creation to allow the Dispatch loop to work through the queued items before before creating excessive threads.

This will merge conflict with #13386, but can the same idea can be incorporated into #13386 w/o much trouble.

**Comment by kouvel** [comment]
@kouvel:
> I guess the effect of this change is only to delay using proc count threads by requesting only 4 at a time. With a long enough queue, it would eventually use proc count threads, just slower than before since it has to wait for the requested threads to wake up before more threads are requested. So I suspect it would only help to use fewer threads when it is beneficial to do so (such as in the scenario you're testing) when it gets short bursts of work frequently and the work is processed before more threads are requested.

Is the above correct? If the only reason it's helping is because it slows down the rate at which threads begin working, that may be working well for this scenario, but there would be cases where the slower rate of starting work would have a negative impact. For instance, if we are getting bursts of work long enough to benefit from using proc count threads, this change would typically use fewer threads and underutilize the CPU. Hill climbing may not work well when workloads are changing (which has to be accounted for) but I believe it would work for more scenarios than this solution, though it may take a bit longer to get to the right number of threads. I'm not seeing how this would work better than hill climbing in steady state (after warmup to let hill climbing reach the appropriate thread count).

**Comment by sdmaclea** [comment]
@kouvel 
> Is the above correct?

Roughly.  
+ Every time one thread request is satisfied another can be requested.
+ It also suppresses many of the duplicate thread requests.  This is a poor mans solution to the 2 threads per work item problem addressed by #13386.
+ There is  also the benefit that more threads are actually hot/warm.  If threads are starting and getting no work they are not warming their caches.  By reducing threads work can be run faster because the threads are hot.

> if we are getting bursts of work long enough to benefit from using proc count threads, this change would typically use fewer threads and underutilize the CPU

Part of the assumption is that thread wake up is significantly less important as the length of work items increase.  Threads should be able to start/wake in very short time.  10us might be a reasonable guess.  So the assumption is that slowing thread start should not have a measurable negative impact for longer work items.

> work better than hill climbing in steady state

I think if hillclimbing was revised to allow threads to decrease below numProcessors it might work better.

Part of the idea is that this has a much higher frequency response rate.  This will handles changes in the <100us range.  That is much too fast for hillclimbing.  

Your previous comments about hillclimbing needing to be returned for below numproc threads made me think it was better to solve outside of hillclimbing.  ThreadPool has more information available than hillclimbing, so it hypothetically can make more intelligent decisions.  Also it is really addressing a different problem.  There really is an discontinuity around numProc threads.  

I had hoped to use descriptive statistic to be able to predict how many thread requests were finding the queue empty when satisfied.  That info could theoretically predict whether to ask for another thread.  To get good stats they need to be averaged, so it has a slower response rate (100ms).  I have a nearly working draft, but it is complicated and adds similar problems, but potentially worse because it makes the assumption that future work items will be similar to past work items.  I can upload it as WIP if you like, but I had basically abandoned it.

**Comment by sdmaclea** [comment]
> I had hoped to use descriptive statistics

If we used descriptive statistic to adjust the MAX Thread requests, that might work.  Depending on whether threads are being used it would increase/decrease the max requests.  Since I am asserting this is not terribly sensitive, it should be OK for it to have a slow response rate.

**Comment by kouvel** [comment]
>> if we are getting bursts of work long enough to benefit from using proc count threads, this change would typically use fewer threads and underutilize the CPU

> Part of the assumption is that thread wake up is significantly less important as the length of work items increase. Threads should be able to start/wake in very short time. 10us might be a reasonable guess. So the assumption is that slowing thread start should not have a measurable negative impact for longer work items.

Sorry, by "bursts of work long enough" I meant long bursts not long work items. For example from idle state if we get a burst of 100 short work items that should ideally use all of the procs, with this change it would be much more likely that the first 4 threads that wake will process all 100 work items before more threads are attempted to be utilized. Frequent bursts of work with short idle or low quantity of work in-between bursts is a common usage scenario for the thread pool so I'm a little worried about that.

> Part of the idea is that this has a much higher frequency response rate. This will handles changes in the <100us range. That is much too fast for hillclimbing.

Agreed, but it's hard to tune for those time scales. This change I think could help or hurt the situation, depending on other factors.

RE: hill climbing
I discussed with @vancem your previous proposal about allowing hill climbing to lower the thread count below the proc count. It introduces the issue after lowering the thread count, where long-running/blocking work would trigger starvation more easily. As long as work is completing, if we assume hill climbing does a reasonable job, when work is not completing a simple way to counter that issue is to bump the thread count to at least the proc count on the first trigger of starvation (500-1000 ms during which no work has completed). @vancem also suggested generally increasing the rate at which starvation increases the thread count, up to a limit. I'll put up a PR with a proposal.

>  Also it is really addressing a different problem.

I assume you're referring to the two thread requests per enqueued work item problem. I'd like to understand this problem a bit better. What is the actual issue behind this that fixing it is this way is helping?
- It's possible that proc count thread requests are too many, meaning that when the queue empties, that many threads have to search the queue unnecessarily before going to sleep. Since you have already fixed a perf problem with searching the queue I'm guessing this is not the main concern.
- With two thread requests per enqueued item, it would reach proc count thread requests more quickly and wake up threads unnecessarily. I can see this being an issue for very short bursts of work (< proc count work items per burst).
  - If this is the main issue, this can be fixed by only requiring that there is at least one thread request in Dispatch (no need to increment beyond 1), along with having the dispatch thread keep working until there is no more work instead of relying on thread requests to do that.
- If the main thing this change is helping with is to use fewer threads than proc count, then I think hill climbing is a safer bet to fixing that. If you suspect this is the main benefit of this change, would it be possible for you to try this change on top of your hill climbing change to see if there is any additional gain after reaching steady state (allowing time for hill climbing to lower the thread count)?

Could also be a combination of the last two issues.

**Comment by sdmaclea** [comment]
> if we get a burst of 100 short work items that should ideally use all of the proc

So this hypothetical ideal condition would require
+ Work items with sufficient work to warrant waking a thread and warming a cache
+ Be short enough so that 1/4 of the thread wake up time is significant

There could be classes of work items that fall into this category.

> it would be much more likely that the first 4 threads that wake will process all 100 work items before more threads are attempted to be utilized

This is more difficult.  To get in this class it requires work items which complete in 1/25 of the thread wake up time.

In any case that is the goal and fundamental assumption about this patch.  It is better to have fewer threads running in the tight `Dispatch()` loop, than more threads running in the UnfairSemaphore outer loop.  So it is really the goal of this patch.  It is based on the assumption that if a few threads can get all the work done before the other workers arrive, then we don't need more workers.

> Frequent bursts of work with short idle or low quantity of work in-between bursts is a common usage scenario for the thread pool so I'm a little worried about that.

It is an important concern.  It is the class of workload I think I am trying to optimize.  But of course plaintext is an extremely short work item.  (On the order of a small string copy).

> >Also it is really addressing a different problem.

> I assume you're referring to the two thread requests per enqueued work item problem

So in my opinion there are separate problems
+ Scaling available threads to account for blocking threads and other system influences (hillclimbing)
+ Using threads efficiently (ThreadPool)

> What is the actual issue behind this that fixing it in this way is helping?

> + It's possible that proc count thread requests are too many

> + With two thread requests per enqueued item, it would reach proc count thread requests more quickly and wake up threads unnecessarily

I think of these as causing the same issue(s).

Queue searching is probably only a small part of the side effect of too many thread requests.  It is probably unimportant now.

+ If I look at profiles on Unix, I was seeing a lot of transitions from native to managed code.  They seemed to be expensive.  For short work items it seems better to stay in managed code. (Adding spinning/sleeping to ThreadPool is another possibly useful optimization I tried).
+ `Dispatch()` has a dequeue loop which is significantly more efficient.  (For the loop to be effective the queue needs to not be empty all the time.  Too many threads keep the queue empty.)
+ `UnfairSemaphore` on Unix is spinning on `sched_yield()`.  The spin time is inversely proportional to the number of spinning threads.  So if more threads are requested the threads spin for less wall time.  So the wake up time may be slower.
+ Also looking at `UnfairSemaphore` it seems to be blamed for threadpool inefficiency on Unix.  While it does show up in plaintext profiles, it seems to be a symptom of ThreadPool inefficiently using threads rather than in and of itself.  Every time the queue empties all threads return to UnfairSemaphore and spin.  More threads means the queues empties more frequently and all thread requests are no longer needed.
+ There is no way to cancel an outstanding thread request.  So when we speculatively request a thread for every work item, we can not cancel the order.

Ultimately, this comes from trying to make ThreadPool more efficient with high proc count and low work items.

Setting the MaxThreads is not a clear and perfect solution, but it seems to be low cost and relatively low risk.  #13386 may be a more direct solution.

> If this is the main issue, this can be fixed by only requiring that there is at least one thread request in Dispatch (no need to increment beyond 1),  along with having the dispatch thread keep working until there is no more work instead of relying on thread requests to do that.

This is insufficient.  This needs to be also gated by whether Outstanding Thread Requests were at Max when the request was satisfied.  Only then request another thread if Dequeue() succeeds.

Than may work and be simpler than #13386.

I'll draft/test the idea.

**Comment by sdmaclea** [comment]
> This needs to be also gated by whether Outstanding Thread Requests were at Max when the request was satisfied. Only then request another thread if Dequeue() succeeds.

Thinking...

**Comment by kouvel** [comment]
> UnfairSemaphore on Unix is spinning on sched_yield(). The spin time is inversely proportional to the number of spinning threads. So if more threads are requested the threads spin for less wall time. So the wake up time may be slower.
> Also looking at UnfairSemaphore it seems to be blamed for threadpool inefficiency on Unix. While it does show up in plaintext profiles, it seems to be a symptom of ThreadPool inefficiently using threads rather than in and of itself. Every time the queue empties all threads return to UnfairSemaphore and spin. More threads means the queues empties more frequently and all thread requests are no longer needed.

Let's consider this a separate issue. I think we're all in agreement that UnfairSemaphore does not work as intended. I was hoping that porting the CoreRT implementation over to CoreCLR would solve this issue, but seeing as that is not likely to happen for 2.1, I'll just fix this separately in the meantime.

**Comment by kouvel** [comment]
> If I look at profiles on Unix, I was seeing a lot of transitions from native to managed code. They seemed to be expensive. For short work items it seems better to stay in managed code. (Adding spinning/sleeping to ThreadPool is another possibly useful optimization I tried).

@jkoritzinsky ported the CoreCLR thread pool to C# for CoreRT. The plan is to eventually port that back to CoreCLR. There's one last PR to be merged before it's active in CoreRT. It needs some bake time in CoreRT first to weed out major issues then some bake time in CoreCLR, so likely after 2.1. Hopefully that should address any p/invoke overhead you're seeing.

**Comment by kouvel** [comment]
> This is more difficult. To get in this class it requires work items which complete in 1/25 of the thread wake up time.

> In any case that is the goal and fundamental assumption about this patch. It is better to have fewer threads running in the tight Dispatch() loop, than more threads running in the UnfairSemaphore outer loop. So it is really the goal of this patch. It is based on the assumption that if a few threads can get all the work done before the other workers arrive, then we don't need more workers.

> Dispatch() has a dequeue loop which is significantly more efficient. (For the loop to be effective the queue needs to not be empty all the time. Too many threads keep the queue empty.)

I see your point, but there's a balance to be struck here. I guess the question is what is "too many threads". Answering that question without any information about the scenario is quite difficult and heuristics must be involved. Is it better to schedule a proc count threads to process a set of work items, or is it better to schedule fewer threads? Without more information about the state of the machine and at least CPU utilization across the whole system, as a heuristic, I would lean towards the former even if a particular scenario performs worse as a result. That said, I think with hill climbing allowed to go lower than proc count threads, the initial guess at how many threads would be appropriate, I think would be a fair one, assuming of course a perfect hill climbing algorithm.

**Comment by kouvel** [comment]
> There is no way to cancel an outstanding thread request. So when we speculatively request a thread for every work item, we can not cancel the order.

Agreed, but it should not be necessary to speculatively request a thread. I question the reason for speculatively requesting a thread at all.

**Comment by kouvel** [comment]
> Setting the MaxThreads is not a clear and perfect solution, but it seems to be low cost and relatively low risk. #13386 may be a more direct solution.

I have not looked at that one yet, I'll get back to you once i have.

**Comment by kouvel** [comment]
> This is insufficient. This needs to be also gated by whether Outstanding Thread Requests were at Max when the request was satisfied. Only then request another thread if Dequeue() succeeds.

I did not follow that, could you please elaborate?

**Comment by sdmaclea** [comment]
>  port that back to CoreCLR. ... likely after 2.1

That would be a real shame considering priority for 2.1 is performance.  I woul dbe happy to do the back port /test.

> Thinking...

#13408 is my attempt at the proposed change.  Unfortunately my testing indicates it does not help the problem I am seeing.  At first glance it looks like the change should help as much as #13386, I am surprised it didn't.  Might still be a good change.

**Comment by sdmaclea** [comment]
> could you please elaborate?

See #13408

**Comment by kouvel** [comment]
> That would be a real shame considering priority for 2.1 is performance. I woul dbe happy to do the back port /test.

That's very kind of you, but considering it hasn't even been merged/enabled yet in CoreRT it's not quite ready yet. I don't think there is any shortcut that would adequately solve this problem until we can port that back, considering it would be a rather significant change to even port it.

**Comment by sdmaclea** [comment]
#13431 was merged instead.  This could be rebased and redesigned, but needs more justification

**Pull request closed without merging**
