### PR TITLE
Revert "Improve CompareOrdinalIgnoreCaseHelper performance for matching chars"

### PR DESCRIPTION
**Pull request by jkotas**
Reverts dotnet/coreclr#9091

### CODE REVIEW

**Comment by jkotas** [comment]
This is causing corefx tests to fail

cc @bbowyersmyth

**Comment by tarekgh** [comment]
test Ubuntu x64 Checked Build and Test please
test Windows_NT x64 Release Priority 1 Build and Test please

**Comment by jkotas** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by tarekgh** [comment]
test Ubuntu x64 Checked Build and Test please
test Windows_NT x64 Release Priority 1 Build and Test please

**Comment by tarekgh** [comment]
test OSX x64 Checked Build and Test please

**Comment by AndyAyersMS** [comment]
I think Ubuntu/OSX legs may be broken right now...

**Pull request merged**
