### PR TITLE
Ensure fallback to English resources on non-Windows platforms

### PR DESCRIPTION
**Pull request by adityamandaleeka**
Take the resources in RC files and build a static library that contains
the ID->English string mappings. Use those strings as the key to gettext
so that when gettext is not able to find a suitable string in the desired
language, it falls back on returning the English string.

#854

### CODE REVIEW

**Comment by janvorli** [comment]
There is also a build failure on Windows which I guess is caused by the including the cstdlib. The issue is different in release / debug build. 
It seems that defining the _ALLOW_KEYWORD_MACROS before including the cstdlib would fix the debug build issue. This issue is caused by the fact that we define "return" as a macro in debug builds so that we can verify that return isn't done from places where we explicitly disable returns.
But the release build issue is a different thing and we would hit it in the debug build as well if we fixed the first issue there.
The issue is that we define rand to Do_not_use_rand to prevent using the rand function from coreclr. But the cstdlib contains this:
```using _CSTD rand;```
Since rand is defined as Do_not_use_rand, it obviously tries to use a nonexistent function.
I think the solution here is to include stdlib.h instead of cstdlib or to not include any of these and just declare the bsearch in the src/utilcode/ccomprc.cpp.

**Comment by adityamandaleeka** [comment]
Thanks for looking at this @janvorli.

I agree with all the suggestions and have made the changes locally. I'm currently investigating the issue with negative numbers and awk. I guess the build server's version of awk is handling them differently from mawk 1.3.3, which is what I have on my machine.

**Comment by janvorli** [comment]
LGTM modulo the nit comments. Thanks for making this change, it is great that now we have english resource strings on the OSX too!

**Comment by adityamandaleeka** [comment]
Thanks Jan. I updated the loop and clarified the comment. Merging this PR...

**Pull request merged**
