### PR TITLE
Use hkp protocol on port 80 to get mono

### PR DESCRIPTION
**Pull request by manu-silicon**
Minor formatting to be consistent with the rest of the document.

### CODE REVIEW

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by jkotas** [comment]
@manu-silicon  Is there a reason to specify the protocol explicitly?

**Comment by jkotas** [comment]
LGTM otherwise

**Comment by manu-silicon** [comment]
Yes because my company doesn't allow the standard hkp protocol. And the instructions for mono also explicitly refers to hkp on port 80. So they must have had the same issue.

**Pull request merged**
