### PR TITLE
[x86/Linux] add creating the READYTORUN_HELPER_PersonalityRoutine chuck for x86/Linux.

### PR DESCRIPTION
**Pull request by ragmani**
The personality routine thunk is created in case all FEATURE_PAL.

### CODE REVIEW

**Comment by ragmani** [comment]
@parjong This PR is from #10139

**Comment by ragmani** [comment]
It succeeded in generating ni after creating the personality routine thunk.
But the TC has failed with the following logs:
```
Assert failure(PID 404 [0x00000194], Thread: 404 [0x0194]): !"Unknown READYTORUN_HELPER"
    File: /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/jitinterface.cpp Line: 13543
    Image: /home/jang/DotNet/enable_x86/work/ragmani/overlay.debug/corerun


Program received signal SIGABRT, Aborted.
0xf7fdace0 in ?? ()
(gdb) bt
#0  0xf7fdace0 in ?? ()
#1  0xf7914011 in TerminateProcess (hProcess=0xffffff01, uExitCode=123456789) at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/pal/src/thread/process.cpp:1301
#2  0xf6cca032 in TerminateOnAssert () at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/utilcode/debug.cpp:183
#3  0xf6ccb2be in _DbgBreakCheck (szFile=0xf795d154 "/home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/jitinterface.cpp", iLine=13543, szExpr=0xf795f98b "!\"Unknown READYTORUN_HELPER\"", 
    fConstrained=0) at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/utilcode/debug.cpp:436
#4  0xf6ccba45 in _DbgBreakCheckNoThrow (szFile=0xf795d154 "/home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/jitinterface.cpp", iLine=13543, szExpr=0xf795f98b "!\"Unknown READYTORUN_HELPER\"", 
    fConstrained=0) at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/utilcode/debug.cpp:548
#5  0xf6ccc0c7 in DbgAssertDialog (szFile=0xf795d154 "/home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/jitinterface.cpp", iLine=13543, szExpr=0xf795f98b "!\"Unknown READYTORUN_HELPER\"")
    at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/utilcode/debug.cpp:735
#6  0xf6dbd9d0 in LoadDynamicInfoEntry (currentModule=0xf6357af0, fixupRva=8710, entry=0x30001004) at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/jitinterface.cpp:13543
#7  0xf721661d in Module::RunEagerFixups (this=0xf6357af0) at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/ceeload.cpp:10877
#8  0xf72b048e in DomainFile::EagerFixups (this=0x80a8c30) at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/domainfile.cpp:1136
#9  0xf72aec3c in DomainFile::DoIncrementalLoad (this=0x80a8c30, level=FILE_LOAD_EAGER_FIXUPS) at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/domainfile.cpp:587
#10 0xf71a965b in AppDomain::TryIncrementalLoad (this=0x80798d0, pFile=0x80a8c30, workLevel=FILE_LOAD_EAGER_FIXUPS, lockHolder=...)
    at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/appdomain.cpp:6010
#11 0xf71a83cc in AppDomain::LoadDomainFile (this=0x80798d0, pLock=0x80a8930, targetLevel=FILE_LOADED) at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/appdomain.cpp:5942
#12 0xf71a8b83 in AppDomain::LoadDomainAssemblyInternal (this=0x80798d0, pIdentity=0xffffd240, pFile=0x80a8038, targetLevel=FILE_LOADED, pLoadSecurity=0x0)
    at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/appdomain.cpp:5772
#13 0xf7198d30 in AppDomain::LoadDomainAssembly (this=0x80798d0, pSpec=0xffffd240, pFile=0x80a8038, targetLevel=FILE_LOADED, pLoadSecurity=0x0)
    at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/appdomain.cpp:5657
#14 0xf6f2a1f2 in AssemblySpec::LoadDomainAssembly (this=0xffffd240, targetLevel=FILE_LOADED, pLoadSecurity=0x0, fThrowOnFileNotFound=1, fRaisePrebindEvents=1, pCallerStackMark=0x0)
    at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/assemblyspec.cpp:929
#15 0xf6f29d2d in AssemblySpec::LoadAssembly (this=0xffffd240, targetLevel=FILE_LOADED, pLoadSecurity=0x0, fThrowOnFileNotFound=1, fRaisePrebindEvents=1, pCallerStackMark=0x0)
    at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/assemblyspec.cpp:732
#16 0xf6f2a7c9 in AssemblySpec::LoadAssembly (pFilePath=0x80a8828 u"/home/jang/DotNet/enable_x86/work/ragmani/unittest/readytorun/mainv1/mainv1.exe")
    at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/assemblyspec.cpp:975
#17 0xf6d00fcf in CorHost2::ExecuteAssembly (this=0x80567a0, dwAppDomainId=1, pwzAssemblyPath=0x80a8828 u"/home/jang/DotNet/enable_x86/work/ragmani/unittest/readytorun/mainv1/mainv1.exe", argc=0, 
    argv=0x0, pReturnValue=0xffffd60c) at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/corhost.cpp:479
#18 0xf6c898d6 in coreclr_execute_assembly (hostHandle=0x80567a0, domainId=1, argc=0, argv=0x0, 
    managedAssemblyPath=0x80520fc "/home/jang/DotNet/enable_x86/work/ragmani/unittest/readytorun/mainv1/mainv1.exe", exitCode=0xffffd60c)
    at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/dlls/mscoree/unixinterface.cpp:376
#19 0x0804c594 in ExecuteManagedAssembly (currentExeAbsolutePath=0x8052014 "/home/jang/DotNet/enable_x86/work/ragmani/overlay.debug/corerun", 
    clrFilesAbsolutePath=0x80520b4 "/home/jang/DotNet/enable_x86/work/ragmani/overlay.debug", 
    managedAssemblyAbsolutePath=0x80520fc "/home/jang/DotNet/enable_x86/work/ragmani/unittest/readytorun/mainv1/mainv1.exe", managedAssemblyArgc=0, managedAssemblyArgv=0x0)
    at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/coreclr/hosts/unixcoreruncommon/coreruncommon.cpp:420
#20 0x0804b216 in corerun (argc=2, argv=0xffffd7f4) at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/coreclr/hosts/unixcorerun/corerun.cpp:149
#21 0x0804b34a in main (argc=2, argv=0xffffd7f4) at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/coreclr/hosts/unixcorerun/corerun.cpp:161
```

**Comment by ragmani** [comment]
I added the personality routine helper on jitinterface for matching jitinterface with zapper.

**Comment by parjong** [comment]
@ragmani  I'm not sure whether we need these helpers. Please refers to #10378 for details.

**Comment by jkotas** [comment]
Agree. These should not be needed.

**Comment by ragmani** [comment]
This PR was closed because it was not necessary.

**Pull request closed without merging**
