### PR TITLE
Fire tracepoints for methods with no template

### PR DESCRIPTION
**Pull request by nategraf**
Related: #14985

### CODE REVIEW

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by brianrob** [comment]
@dotnet-bot test 
Windows_NT arm Cross Checked Innerloop Build and Test
@dotnet-bot test 
Windows_NT x86 Checked Innerloop Build and Test

**Comment by brianrob** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test

**Comment by nategraf** [comment]
As best I can tell `[AddUsageTest.cmd_5454] GC\API\GC\AddUsageTest\AddUsageTest.cmd` and `[b59948.cmd_2769] JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b59948\b59948\b59948.cmd` are failing on `Windows_NT arm Cross Checked Innerloop Build and Test` and `Windows_NT x86 Checked Innerloop Build and Test` has a Jenkins error. Neither should matter for this change.

@brianrob In this kind of situation can I check in the PR despite failing (but irrelevant) tests?

**Comment by brianrob** [comment]
@nategraf, from my review of the last few runs of these legs, it doesn't look like they are failing for the same reason.  Let's try once more:


@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT x86 Checked Innerloop Build and Test

**Comment by nategraf** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test

**Pull request merged**
