### PR TITLE
Use roslyn common props in test build

### PR DESCRIPTION
**Pull request by wtgodbe**
Attempts to resolve https://github.com/dotnet/coreclr/issues/11914

@JosephTremoulet I haven't been able to repro that failure locally using my VS2017 command prompt, but I suspect this change might fix it - https://github.com/dotnet/coreclr/pull/10430, which you referenced in the issue, only applied to the product build, and not the test build. This change should bring in the same change to the test build. Can you try running a local build with these changes to see if the error goes away?

CC @ViktorHofer @briansull

### CODE REVIEW

**Comment by wtgodbe** [comment]
@weshaggard can you take a look at the errors in the Windows test build? I don't know enough about compilers to diagnose what's happening here

**Comment by JosephTremoulet** [comment]
FWIW, I've verified that on a machine with only VS2017 installed, which runs into the "TaskOverride" error message w/o this patch, applying this patch brings it to the same slew of csc errors showing up in the CI runs here.

**Comment by briansull** [comment]
Any new status on this? @weshaggard @wtgodbe

**Comment by weshaggard** [comment]
I'm going to spend some time digging into this today. I'm currently trying to get a local repro.

**Comment by weshaggard** [comment]
@wtgodbe Your change is the correct fix but in doing so we are hitting compiler bug https://github.com/dotnet/roslyn/issues/14785. So we will either need to workaround that bug or pick-up a newer compiler with the fix. I suspect it will be easiest to workaround it for now. I'm going to see if I can do that.

**Comment by weshaggard** [comment]
Assuming full CI is green we should merge this and file a tracking bug to undo the tests that were commented out. 

cc @pgavlin in case he has concerns with the commented out JIT tests.

**Comment by pgavlin** [comment]
Please file an issue to track re-enabling these tests and reference that issue in a comment somewhere in each changed file (e.g. at the top of the file or near the first test that is commented out).

**Comment by weshaggard** [comment]
I've filed https://github.com/dotnet/coreclr/issues/12233 to track the test changes and I will add a link to that in the commit for this PR before merging, just waiting to ensure CI is green before pushing that commit update.

**Comment by wtgodbe** [comment]
CI is green, so I'll go ahead and merge. Thanks @weshaggard for getting this green!

**Comment by briansull** [comment]
Note that after a sync of this change, I needed to do a full clean to get this working:

git clean -d -x -f

**Comment by ViktorHofer** [comment]
Should this be moved into the release/2.0.0 branch? I just pulled it down and wanted to build it and faced them same issue again.

**Pull request merged**
