### PR TITLE
Keep the file name of awk script consistently.

### PR DESCRIPTION
**Pull request by leemgs**
Let's maintain the file name of the generate****.awk consistently
to understand intuitionally the meaning of the file name.

Signed-off-by: Geunsik Lim <geunsik.lim@samsung.com>

### CODE REVIEW

**Comment by leemgs** [comment]
This PR is submitted as a next step of https://github.com/dotnet/coreclr/pull/4084 .

\CC: @janvorli

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by janvorli** [comment]
@leemgs I believe the original naming was a better match for the reality. On Linux, we generate version script that contains the exported symbols, but also a version. And the "version script" is the official name for it (the linker option name to include it is `--version-script`). On OSX, we generate just the symbols, since there is no concept of version script.

**Comment by leemgs** [comment]
@janvorli ,  Thank you for your feedback. I also know the difference of the two awk scripts (for Linux and OSX). I think that we may keep more consistent file name to encourage the contribution activities. Note that there are not enough documentation in CoreCLR of .NET Core.  As you described, the two awk scripts generate the symbols with version (or w/o the concept of version script). If you have more good naming to understand know intuitively similar awk script files more than my proposal, Let's use it for them.

**Comment by janvorli** [comment]
@leemgs I was trying to say that I prefer the existing different naming rather than trying to unify it.

**Comment by adityamandaleeka** [comment]
I agree with @janvorli about keeping the names as they are.

**Comment by leemgs** [comment]
@janvorli , @adityamandaleeka , I will close this PR according to the above feedback.

**Pull request closed without merging**
