### PR TITLE
Upgrade Linux build to use Unicode 8.0

### PR DESCRIPTION
**Pull request by tarekgh**
We have done this upgrade for Windows awhile ago. the change here is to do the same for Linux
The fix should take care with the issue https://github.com/dotnet/corefx/issues/7351

### CODE REVIEW

**Comment by tarekgh** [comment]
@ellismg could you please have a look? this is pure data changes and there is no real code change. let me know if you have any question

**Comment by ellismg** [comment]
LGTM

**Comment by tarekgh** [comment]
test Ubuntu x64 Checked Build and Test please

**Comment by tarekgh** [comment]
test Ubuntu x64 Checked Build and Test please

**Comment by tarekgh** [comment]
test OSX x64 Checked Build and Test please

**Comment by tarekgh** [comment]
thanks @ellismg

**Comment by hughbe** [comment]
Nice. I'm curious: why do we have two separate implementations of System.Globalisation. It seems that the Windows code is already there In the corefx but uses a different code base in the src folder

**Comment by tarekgh** [comment]
@hughbe 

> I'm curious: why do we have two separate implementations of System.Globalisation

we are planning at some point to consolidates the code between Windows and Linux. we originally used the refactored code in Linux implementation but didn't have chance to consolidate it with Windows implementation.

**Comment by hughbe** [comment]
Why didn't you have the chance? Thanks

**Comment by tarekgh** [comment]
@hughbe because it needs some effort and time. for example, we'll need to consolidate the PAL layer. and carefully look at the two implementation and pick the reasonable one without introducing any regression. there is also part o the code need to be more refactored (like TimeZoneInfo)...etc. so this is not a priority item for now to do.

**Pull request merged**
