### PR TITLE
Fix pragma-pack warning for pshpack?.h & poppack.h files

### PR DESCRIPTION
**Pull request by k15tfu**
Fix pragma-pack warning for pshpack?.h & poppack.h files

Use #pragma diagnostic to ignore the following:
```
  warning: the current #pragma pack aligment value is modified in the included file
```

### CODE REVIEW

**Comment by k15tfu** [comment]
@janvorli could you please also look into this? =)

The other way how to fix this is to move these pragma's into pshpack?.h & poppack.h files, but in this case I have to create one more file because I cannot `pop` old configuration from the poppack.h file, so I will rename poppack.h to something else (poppack_impl.h), and then do #include for this file, followed by diagnostic pop. What do you think?

**Comment by janvorli** [comment]
@k15tfu these warnings are disabled in https://github.com/dotnet/coreclr/blob/master/configurecompiler.cmake#L476, so it seems something is wrong with your build.

**Comment by k15tfu** [comment]
@janvorli I get these warnings in my project which uses your cor.h header. If it's not something that you would like to fix in the code, I can fix it using my CXXFLAGS.

**Comment by k15tfu** [comment]
Whops, build has failed...

**Comment by k15tfu** [comment]
The point is to localize the problem, because if I disable this in my CXXFLAGS I will not get any warnings caused by my own errors.

**Comment by janvorli** [comment]
There are 30 places in the runtime code where we include the pshpack headers and people may add more in the future. So I would prefer not suppressing the warnings at all the usage spots. 
For warnings in general where there is a hope that we could fix them one day, I prefer keeping them disabled in a central location, the configurecompiler.cmake. However this specific one is something we cannot fix, so if you'd be able to make the change the other way you've proposed, it would be great. Then we could remove disabling of this warning from the configurecompiler.cmake.

**Comment by k15tfu** [comment]
@janvorli Well.. I wanted to leave the same semantic, but it turns out it's not possible right now. #pragma diagnostic pop cannot be done in the #include hierarchy which also restores pack() alignment. So to fix it in the code we can:
* Create poppack_cleanup.hpp which does diagnostic pop, and include it always together with poppack.hpp:
```C++
#include "poppack.hpp"
#include "poppack_cleanup.hpp"
```
* Add `POPPACK()` macro which will do everything:
```C++
// poppack_macro.hpp:
#define POPPACK() \
    _Pragma("pack(pop)") \
    _Pragma("clang diagnostic pop")
```
and its usage:
```C++
#include "pshpack1.hpp"
struct A {
    char c;
    int i;
};
POPPACK()
```
* [In future] Use `#pragma warning(once)` if it will be ever supported by Clang

So, I feel that you want to leave everything as it is :)

**Comment by janvorli** [comment]
> So, I feel that you want to leave everything as it is

Right. I've tried to solve this in a centralized way long time ago and failed, so I was hoping I've missed something :-)

**Pull request closed without merging**
