### PR TITLE
Fixing issue with perf targets restoring test runtime  

### PR DESCRIPTION
**Pull request by dsgouda**
Adding locally built package reference so that perf targets can correctly restore those packages 
Adding runtime reference to the test runtime project
@lt72 @rahku

### CODE REVIEW

**Comment by dsgouda** [comment]
@dotnet-bot Test this please

**Comment by rahku** [comment]
LGTM

**Comment by dsgouda** [comment]
@dotnet-bot Test this please

**Comment by dsgouda** [comment]
@dotnet-bot Test this please

**Comment by dsgouda** [comment]
@dotnet-bot Test this please

**Comment by dsgouda** [comment]
@dotnet-bot Test this please

**Comment by dsgouda** [comment]
@dotnet-bot Test OSX x64 Checked Build and Test please

**Comment by dsgouda** [comment]
@dotnet-bot Test Ubuntu x64 Checked Build and Test please

**Comment by dsgouda** [comment]
@dotnet-bot Test OSX x64 Checked Build and Test please

**Comment by dsgouda** [comment]
@dotnet-bot Test OSX x64 Checked Build and Test please

**Pull request merged**
