### PR TITLE
Enable coreclr tests by default

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test ubuntu release

**Comment by mmitche** [comment]
@dotnet-bot test ubuntu release

**Comment by mmitche** [comment]
@dotnet-bot test ubuntu release

**Comment by sergiy-k** [comment]
@dotnet-bot test ubuntu release

**Comment by mmitche** [comment]
@dotnet-bot test ubuntu release

**Pull request merged**
