### PR TITLE
[x86/Linux] Fix pow of tryrun

### PR DESCRIPTION
**Pull request by seanshpark**
x86/Linux has compatible math pow()
This will fix CoreFX System.Tests.MathFTests.Pow() failures

### CODE REVIEW

**Comment by seanshpark** [comment]
CC @parjong

**Comment by BruceForstall** [comment]
@janvorli

**Comment by janvorli** [comment]
@dotnet-bot test Tizen armel Cross Debug Build please

**Comment by seanshpark** [comment]
Thank you!

**Pull request merged**
