### PR TITLE
Fix ARM64 HFA arguments passing via reflection

### LINKED ISSUE #25993: Wrong reflection invocation on ARM64 with HFAs
The following example should print 1 twice but prints 0 when invoked through reflection on ARM64:
```csharp
public struct Hfa
{
    public double A, B, C, D;
    public Hfa(double a, double b, double c, double d)
    {
        A = a;
        B = b;
        C = c;
        D = d;
    }
}
public class Program
{
    [MethodImpl(MethodImplOptions.NoInlining)]
    public static double Foo(double a, Hfa b, Hfa c) => c.B;

    internal static void Main()
    {
        Console.WriteLine(Foo(0, new Hfa(), new Hfa(0, 1, 0, 0)));

        object[] arr = { 0d, new Hfa(), new Hfa(0, 1, 0, 0) };
        MethodInfo fooMI = typeof(Program).GetMethod("Foo");
        Console.WriteLine(fooMI.Invoke(null, arr));
    }
}
```

### PR DESCRIPTION
**Pull request by janvorli**
There was an issue happening in case there were not enough floating point
registers for passing a HFA argument. The argument iterator was returning
confusing result for such argument. The offset was correctly pointing to
stack, but the state indicated that the arguments should be passed in
registers. That caused the argument to be passed incorrectly.

The fix is to not set m_hasArgLocDescForStructInRegs when the HFA doesn't
fit into registers.

Close #25993

### CODE REVIEW

**Comment by janvorli** [comment]
@MeiChin-Tsai does this fix seem to you like something we can still fit into the 3.0? The bug causes some HFA arguments (structures with float / double fields only) to be passed incorrectly via reflection (the values the callee gets are different from the values passed by the caller).

**Comment by janvorli** [comment]
@jakobbotsch the ABI stress tests with the change you've suggested are consistently failing. Would you please mind taking a look at the change in the test to see if I have possibly made some mistake?

**Comment by jakobbotsch** [comment]
Sure, I'll take a look. It is also weird that another pinvoke related test is failing (on Linux x64 where this change should have no effect)...

**Comment by jakobbotsch** [comment]
I have a guess. The reflection path probably needs to generate shuffle thunks more often (now they are needed for each caller too, not just for callees), so the timeout might be because of #26054. Were the current tests run with your fix for that pulled in?

**Comment by jakobbotsch** [comment]
I am pretty sure that is the reason. The PR is not rebased on top of current master:
```
git fetch upstream pull/26174/head:reflection-pr && git merge-base reflection-pr upstream/master
From https://github.com/dotnet/coreclr
 * [new ref]               refs/pull/26174/head -> reflection-pr
bf9f5a7444fdabaa37b1575b4b2455fda2ab5cb5
```
That commit is 2 days old: https://github.com/dotnet/coreclr/commit/bf9f5a7444fdabaa37b1575b4b2455fda2ab5cb5

I think you will need to push a dummy change for GitHub to update it.

**Comment by jakobbotsch** [comment]
Well, looks like the new test run is ok and I also cannot reproduce it locally, so I guess it was some kind of stale sources anyway.

**Comment by janvorli** [comment]
Right. I have retried the CI before several times and it kept failing, so I've thought that it is broken.

**Pull request merged**
