### PR TITLE
Fix IL JIT tests

### PR DESCRIPTION
**Pull request by BruceForstall**
The JIT tests in IL files need to change from directly referencing [mscorlib] for System.Console types to referencing [System.Console] instead. This allows them to run on Linux.

### CODE REVIEW

**Comment by mmitche** [comment]
Taking a look

**Comment by mmitche** [comment]
While I didn't look through all the files, the ones I perused looked good, though do you know why the ".assembly extern legacy library mscorlib {}" is still required?

LGTM

**Comment by BruceForstall** [comment]
There are still lots of references to mscorlib, e.g. for System.Object, etc. I don't know if all those should also be changed to be "fully correct", but at least the tests run now on Linux, just changing the System.Console stuff.

**Comment by mmitche** [comment]
Sounds good to me

**Pull request merged**
