### PR TITLE
Clean up clrjit from using sizeof(void*) when meant TARGET_POINTER_SIZE

### PR DESCRIPTION
**Pull request by echesakovMSFT**
This replaces usages `sizeof(void*)` or `sizeof(size_t)` in clrjit with macro `TARGET_POINTER_SIZE` or, in some cases, with macro `REGSIZE_BYTES` when referring to target arch pointer size (target arch gen-purpose register size).

### CODE REVIEW

**Comment by echesakovMSFT** [comment]
@dotnet-bot test Ubuntu16.04 arm Cross Debug Innerloop Build

**Comment by echesakovMSFT** [comment]
@jkotas @BruceForstall @RussKeldorph PTAL 
CC @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
Did we ever run diffs for this? If not, it would be nice to retroactively show it did not cause any diffs.

**Comment by BruceForstall** [comment]
> Did we ever run diffs for this? If not, it would be nice to retroactively show it did not cause any diffs.

As an aside, we really need to get all-platform diffs generated in the CI...

**Comment by echesakovMSFT** [comment]
@AndyAyersMS @dotnet/jit-contrib 
Just confirmed that no diffs introduced for Windows_NT.x64 and Windows_NT.x86

**Comment by CarolEidt** [comment]
FYI - codegenlegacy.cpp now fails to build on desktop

**Pull request merged**
