### PR TITLE
Add GC.KeepAlive to keep collectible ALC alive across usage in ICustomMarshaler tests

### LINKED ISSUE #22109: [x86] Test failed: Interop_ICustomMarshaler._ConflictingNames_MultipleALCs_MultipleALCs_._ConflictingNames_MultipleALCs_MultipleALCs_cmd
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_gcstress0xc_zapdisable/114/

**Failed tests:**
Interop_ICustomMarshaler._ConflictingNames_MultipleALCs_MultipleALCs_._ConflictingNames_MultipleALCs_MultipleALCs_cmd

**Log:**
```
Interop_ICustomMarshaler._ConflictingNames_MultipleALCs_MultipleALCs_._ConflictingNames_MultipleALCs_MultipleALCs_cmd [FAIL]
        
  
  Return code:      1
  Raw output file:      D:\j\workspace\x86_checked_w---34329519\bin\tests\Windows_NT.x86.Checked\Reports\Interop.ICustomMarshaler\ConflictingNames\MultipleALCs\MultipleALCs.output.txt
  Raw output:
  BEGIN EXECUTION
         "D:\j\workspace\x86_checked_w---34329519\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" MultipleALCs.exe 
        System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
           at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(String unmanagedDllName, IntPtr gchManagedAssemblyLoadContext)
           at CustomMarshalers.CustomMarshalerTest.NativeParseInt(WrappedString str)
           at CustomMarshalers.CustomMarshalerTest.ParseInt(String str) in D:\j\workspace\x86_checked_w---34329519\tests\src\Interop\ICustomMarshaler\ConflictingNames\CustomMarshaler.cs:line 50
           --- End of inner exception stack trace ---
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
           at RunInALC.Run(AssemblyLoadContext context) in D:\j\workspace\x86_checked_w---34329519\tests\src\Interop\ICustomMarshaler\ConflictingNames\RunInALC.cs:line 48
           at RunInALC.ConflictingCustomMarshalerNamesInCollectibleLoadContexts_Succeeds() in D:\j\workspace\x86_checked_w---34329519\tests\src\Interop\ICustomMarshaler\ConflictingNames\RunInALC.cs:line 32
           at RunInALC.Main(String[] args) in D:\j\workspace\x86_checked_w---34329519\tests\src\Interop\ICustomMarshaler\ConflictingNames\RunInALC.cs:line 18
        Expected: 100
        Actual: 101
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
```

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes #22109.

cc: @BruceForstall @sandreenko

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
Is this what we want? Isn't this a bug in the ALC work?

**Comment by jkoritzinsky** [comment]
I'm investigating that right now. I think there is a bug here where we don't add a strong reference to the collectible ALC when we have other objects using it, but I'm not sure what we want to do for the fix. The code in `AssemblyLoadContext.cs` seems to very deliberately make the GCHandle to the managed object a weak handle when the ALC is collectible.

**Comment by jkoritzinsky** [comment]
@janvorli @sdmaclea any suggestions for what we should do here?

**Comment by sdmaclea** [comment]
@janvorli I am not sure what the design is supposed to be, but I would think that as long as there are any strong references to objects implemented by the ALC it shouldn't be collected.  That should include assembly references and method info.  So I think I agree with @AaronRobinsonMSFT that this seems like a unloadable ALC bug...

**Comment by janvorli** [comment]
It is not that simple. AssemblyLoadContext is only held alive by the user code. When user code doesn't hold reference to AssemblyLoadContext, it eventually results in its finalizer being called. That starts the unloading process the same way as if the Unload method was called. And the first thing that happens is that the native runtime creates a strong handle to the AssemblyLoadContext and it keeps it until everything is unloaded. Then it destroys the handle and the AssemblyLoadContext can be collected.
Regarding the #22109, it is hard to guess what's wrong without debugging. It is not clear where the "null" came from. Maybe the native runtime should not have called the AssemblyLoadContext.ResolveUnmanagedDll at that point (if the context was already beyond the point when the strong handle to it was destroyed).
Is the test failure reproducible enough so that I can debug it locally?

**Comment by jkoritzinsky** [comment]
Yep the failure is reproducable. Use the following environment variables:
```
COMPlus_TieredCompilation=0
COMPlus_GCStress=0xC
COMPlus_ZapDisable=1
COMPlus_ReadyToRun=0
```
Run the test in a Windows x86 Checked build and it should trigger.

The collectible ALC was being collected between lines 44 and 45 of RunInAlc.cs.

Btw if you look at AssemblyLoadContext.cs, you will see that it creates a weak handle instead of a strong handle to the managed object if the ALC is collectible:

https://github.com/dotnet/coreclr/blob/b9e88989458e24fa9764e045917b141e3338eae7/src/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.cs#L75-L86

**Comment by janvorli** [comment]
> Btw if you look at AssemblyLoadContext.cs, you will see that it creates a weak handle instead of a strong handle to the managed object if the ALC is collectible

I didn't say it doesn't :-). But once the Unload is called or the finalizer is called, it gets changed to a strong handle:
https://github.com/dotnet/coreclr/blob/b9e88989458e24fa9764e045917b141e3338eae7/src/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.cs#L118-L122

**Comment by jkoritzinsky** [comment]
Interesting... totally didn't see that.

In my repro it looks like it never calls `PrepareForAssemblyLoadContextRelease` before it crashes.

**Comment by janvorli** [comment]
> In my repro it looks like it never calls `PrepareForAssemblyLoadContextRelease` before it crashes.

Hmm, that sounds like some race then. As if the weak handle didn't get resolved to a valid AssemblyLoadcontext while the AssemblyLoadContext was still on the finalizer queue before calling the finalizer.

**Comment by jkoritzinsky** [comment]
Do we want to merge this for now to stop the test failure or wait for the full fix?

**Comment by sdmaclea** [comment]
@jkoritzinsky I would create a new issue for the race @janvorli describes, then merge this.

**Comment by jkoritzinsky** [comment]
Last time I tried to repro it on x64 I couldn't, but I'll try again when I've got a chance and let you know.

**Comment by jkoritzinsky** [comment]
It doesn't repro on x64. Looks like `PrepareAssemblyLoadContextRelease` does get called on x64 in time....

I'll go open another issue so I can merge this in.

**Pull request merged**
