### PR TITLE
Explicitly download correct version of CoreDisTools package

### PR DESCRIPTION
**Pull request by wtgodbe**
Looks to fix failures mentioned in https://github.com/dotnet/coreclr/pull/11901 and https://github.com/dotnet/coreclr/pull/12011

### CODE REVIEW

**Comment by wtgodbe** [comment]
@dotnet-bot test Ubuntu gcstress0x3
@dotnet-bot test Ubuntu gcstress0xc_minopts_heapverify1
@dotnet-bot test Windows_NT x86 Checked gcstress0xc_minopts_heapverify1

**Comment by wtgodbe** [comment]
@dotnet-bot test Windows_NT gcstress0xc_jitstress1
@dotnet-bot test Windows_NT x86 Checked gcstress0x3
@dotnet-bot test Ubuntu gcstress0x3

**Comment by wtgodbe** [comment]
@pgavlin @swaroop-sridhar PTAL

**Comment by wtgodbe** [comment]
@dotnet-bot test Windows_NT gcstress0xc_jitstress1
@dotnet-bot test Windows_NT x86 Checked gcstress0x3
@dotnet-bot test Ubuntu gcstress0x3

**Comment by wtgodbe** [comment]
@dotnet-bot test Ubuntu gcstress0x3
@dotnet-bot test Ubuntu gcstress0xc_minopts_heapverify1
@dotnet-bot test Windows_NT x86 Checked gcstress0xc_minopts_heapverify1

**Comment by wtgodbe** [comment]
@dotnet-bot test Ubuntu gcstress0x3
@dotnet-bot test Ubuntu gcstress0xc_minopts_heapverify1
@dotnet-bot test Windows_NT x86 Checked gcstress0xc_minopts_heapverify1
@dotnet-bot test Windows_NT gcstress0xc_jitstress1
@dotnet-bot test Windows_NT x86 Checked gcstress0x3
@dotnet-bot test Ubuntu gcstress0x3

**Comment by swaroop-sridhar** [comment]
Looks like the libcoredistools.so issue is still there in the runs.

**Comment by wtgodbe** [comment]
> ./tests/runtest.sh: line 1209: ./tests/setup-stress-dependencies.sh: Permission denied

Looks like permissions for the shell script I added aren't set right. Anybody know how to fix this in github?

**Comment by wtgodbe** [comment]
Never mind, figured it out - I just updated the permissions on the shell script, so it should be running now & we should see libcoredistools.so showing up in non-Windows coreoverlay.

**Comment by wtgodbe** [comment]
@dotnet-bot test Ubuntu gcstress0x3
@dotnet-bot test Ubuntu gcstress0xc_minopts_heapverify1
@dotnet-bot test Windows_NT x86 Checked gcstress0xc_minopts_heapverify1
@dotnet-bot test Windows_NT gcstress0xc_jitstress1
@dotnet-bot test Windows_NT x86 Checked gcstress0x3
@dotnet-bot test Ubuntu gcstress0x3

**Comment by wtgodbe** [comment]
@dotnet-bot test Ubuntu gcstress0x3
@dotnet-bot test Ubuntu gcstress0xc_minopts_heapverify1

**Comment by wtgodbe** [comment]
@dotnet-bot test Ubuntu gcstress0x3
@dotnet-bot test Ubuntu gcstress0xc_minopts_heapverify1

**Comment by wtgodbe** [comment]
GC Stress tests seem to be running along smoothly, other than Windows x86, which is expected. @swaroop-sridhar @pgavlin are you OK with merging this?

**Comment by pgavlin** [comment]
@wtgodbe I've just updated the CoreDisTools packages to the newest version, so I'm going to go ahead and retrigger the x86 and x64 GC stress jobs.

test test Windows_NT gcstress0xc
test test Windows_NT x86 Checked gcstress0xc

**Comment by wtgodbe** [comment]
test test Windows_NT x86 Checked gcstress0xc

**Comment by wtgodbe** [comment]
@dotnet-bot test Windows_NT x86 Checked gcstress0xc

**Comment by wtgodbe** [comment]
@dotnet-bot test Windows_NT x86 Checked gcstress0xc_minopts_heapverify1

**Comment by pgavlin** [comment]
@dotnet-bot test Ubuntu gcstress0xc

**Comment by pgavlin** [comment]
@dotnet-bot test Ubuntu gcstress0xc

**Comment by pgavlin** [comment]
@dotnet-bot test Ubuntu gcstress0xc

**Comment by pgavlin** [comment]
It looks like something is causing the Linux GC stress jobs to hang. I'll investigate this today--it seems prudent to get the hang fixed before merging this change. LGTM otherwise.

**Comment by wtgodbe** [comment]
@pgavlin any update on the hang?

**Comment by pgavlin** [comment]
I have it open right now. It looks like we're getting stuck during exception handling, but I'm not yet sure why. If I can't make any progress, I will disable this test for GC stress and try a fresh run.

**Comment by pgavlin** [comment]
I was not able to fully diagnose the issue, so I've filed #12224 to track. Applying this patch should disable the tests that are hanging s.t. we can merge this PR and bring cross-plat GC stress back online:

```diff
diff --git a/tests/src/Interop/MarshalAPI/ReadWrite/ReadWriteByte.csproj b/tests/src/Interop/MarshalAPI/ReadWrite/ReadWriteByte.csproj
index 4a206ae..c78ffef 100644
--- a/tests/src/Interop/MarshalAPI/ReadWrite/ReadWriteByte.csproj
+++ b/tests/src/Interop/MarshalAPI/ReadWrite/ReadWriteByte.csproj
@@ -11,6 +11,9 @@
     <ProjectTypeGuids>{786C830F-07A1-408B-BD7F-6EE04809D6DB};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
     <SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\..\</SolutionDir>
 
+    <!-- This test is disabled until #12224 is fixed -->
+    <GCStressIncompatible>true</GCStressIncompatible>
+
     <DefineConstants>$(DefineConstants);STATIC</DefineConstants>
   </PropertyGroup>
   <!-- Default configurations to help VS understand the configurations -->
diff --git a/tests/src/Interop/MarshalAPI/ReadWrite/ReadWriteInt16.csproj b/tests/src/Interop/MarshalAPI/ReadWrite/ReadWriteInt16.csproj
index b540fb1..fc63d21 100644
--- a/tests/src/Interop/MarshalAPI/ReadWrite/ReadWriteInt16.csproj
+++ b/tests/src/Interop/MarshalAPI/ReadWrite/ReadWriteInt16.csproj
@@ -11,6 +11,9 @@
     <ProjectTypeGuids>{786C830F-07A1-408B-BD7F-6EE04809D6DB};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
     <SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\..\</SolutionDir>
 
+    <!-- This test is disabled until #12224 is fixed -->
+    <GCStressIncompatible>true</GCStressIncompatible>
+
     <DefineConstants>$(DefineConstants);STATIC</DefineConstants>
   </PropertyGroup>
   <!-- Default configurations to help VS understand the configurations -->
diff --git a/tests/src/Interop/MarshalAPI/ReadWrite/ReadWriteInt32.csproj b/tests/src/Interop/MarshalAPI/ReadWrite/ReadWriteInt32.csproj
index 7b6a948..0aea271 100644
--- a/tests/src/Interop/MarshalAPI/ReadWrite/ReadWriteInt32.csproj
+++ b/tests/src/Interop/MarshalAPI/ReadWrite/ReadWriteInt32.csproj
@@ -11,6 +11,9 @@
     <ProjectTypeGuids>{786C830F-07A1-408B-BD7F-6EE04809D6DB};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
     <SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\..\</SolutionDir>
 
+    <!-- This test is disabled until #12224 is fixed -->
+    <GCStressIncompatible>true</GCStressIncompatible>
+
     <DefineConstants>$(DefineConstants);STATIC</DefineConstants>
   </PropertyGroup>
   <!-- Default configurations to help VS understand the configurations -->
diff --git a/tests/src/Interop/MarshalAPI/ReadWrite/ReadWriteInt64.csproj b/tests/src/Interop/MarshalAPI/ReadWrite/ReadWriteInt64.csproj
index 91e6ea7..685368b 100644
--- a/tests/src/Interop/MarshalAPI/ReadWrite/ReadWriteInt64.csproj
+++ b/tests/src/Interop/MarshalAPI/ReadWrite/ReadWriteInt64.csproj
@@ -11,6 +11,9 @@
     <ProjectTypeGuids>{786C830F-07A1-408B-BD7F-6EE04809D6DB};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
     <SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\..\</SolutionDir>
 
+    <!-- This test is disabled until #12224 is fixed -->
+    <GCStressIncompatible>true</GCStressIncompatible>
+
     <DefineConstants>$(DefineConstants);STATIC</DefineConstants>
   </PropertyGroup>
   <!-- Default configurations to help VS understand the configurations -->
diff --git a/tests/src/Interop/MarshalAPI/ReadWrite/ReadWriteIntPtr.csproj b/tests/src/Interop/MarshalAPI/ReadWrite/ReadWriteIntPtr.csproj
index 366a5c5..5287d88 100644
--- a/tests/src/Interop/MarshalAPI/ReadWrite/ReadWriteIntPtr.csproj
+++ b/tests/src/Interop/MarshalAPI/ReadWrite/ReadWriteIntPtr.csproj
@@ -11,6 +11,9 @@
     <ProjectTypeGuids>{786C830F-07A1-408B-BD7F-6EE04809D6DB};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
     <SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\..\</SolutionDir>
 
+    <!-- This test is disabled until #12224 is fixed -->
+    <GCStressIncompatible>true</GCStressIncompatible>
+
     <DefineConstants>$(DefineConstants);STATIC</DefineConstants>
   </PropertyGroup>
   <!-- Default configurations to help VS understand the configurations -->
diff --git a/tests/src/JIT/Regression/CLR-x86-JIT/V1-M10/b08944/b08944b.csproj b/tests/src/JIT/Regression/CLR-x86-JIT/V1-M10/b08944/b08944b.csproj
index 755d0f4..7d1df36 100644
--- a/tests/src/JIT/Regression/CLR-x86-JIT/V1-M10/b08944/b08944b.csproj
+++ b/tests/src/JIT/Regression/CLR-x86-JIT/V1-M10/b08944/b08944b.csproj
@@ -11,6 +11,9 @@
     <ProjectTypeGuids>{786C830F-07A1-408B-BD7F-6EE04809D6DB};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
     <SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\..\</SolutionDir>
 
+    <!-- This test is disabled until #12224 is fixed -->
+    <GCStressIncompatible>true</GCStressIncompatible>
+
   </PropertyGroup>
   <!-- Default configurations to help VS understand the configurations -->
   <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
```

**Comment by wtgodbe** [comment]
@dotnet-bot test Ubuntu gcstress0x3
@dotnet-bot test Ubuntu gcstress0xc_minopts_heapverify1
@dotnet-bot test Windows_NT x86 Checked gcstress0xc_minopts_heapverify1
@dotnet-bot test Windows_NT gcstress0xc_jitstress1
@dotnet-bot test Windows_NT x86 Checked gcstress0x3
@dotnet-bot test Ubuntu gcstress0x3

**Comment by wtgodbe** [comment]
@pgavlin thanks, I applied the change & kicked off the tests again.

**Comment by pgavlin** [comment]
@dotnet-bot test Ubuntu gcstress0xc

**Comment by pgavlin** [comment]
@wtgodbe this should be good to go. Thanks for doing this!

**Comment by wtgodbe** [comment]
@pgavlin are the x64 failures expected?

**Comment by pgavlin** [comment]
Yes.

**Comment by wtgodbe** [comment]
Cool, merged. Are you taking https://github.com/dotnet/coreclr/pull/12011 to 2.0.0?

**Pull request merged**
