### PR TITLE
Fix DecomposeStoreInd comments

### PR DESCRIPTION
**Pull request by BruceForstall**

### CODE REVIEW

**Comment by BruceForstall** [comment]
@pgavlin PTAL
cc @dotnet/jit-contrib

**Comment by pgavlin** [comment]
LGTM

**Comment by BruceForstall** [comment]
@mmitche I assume this is failing in all CI runs?
```
D:\j\workspace\x64_release_w---0575cb46\bin\tests\Windows_NT.x64.Release\TestWrappers\baseservices\baseservices.XUnitWrapper.cs(243): error : baseservices._compilerservices_dynamicobjectproperties_TestAPIs_TestAPIs_._compilerservices_dynamicobjectproperties_TestAPIs_TestAPIs_cmd [FAIL] [D:\j\workspace\x64_release_w---0575cb46\tests\runtest.proj]
        
  
  Return code:      1
  Raw output file:      D:\j\workspace\x64_release_w---0575cb46\bin\tests\Windows_NT.x64.Release\Reports\baseservices\compilerservices\dynamicobjectproperties\TestAPIs\TestAPIs.output.txt
  Raw output:
  BEGIN EXECUTION
         "D:\j\workspace\x64_release_w---0575cb46\tests\..\bin\tests\Windows_NT.x64.Release\Tests\Core_Root\corerun.exe" TestAPIs.exe 
        Test threw unexpected exception:
  System.TypeLoadException: Could not load type 'CreateValueCallback' from assembly 'System.Runtime, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
           at Driver`2.GetValueValidations(K[] keys, V[] values)
           at TestAPIs.Main() in D:\j\workspace\x64_release_w---0575cb46\tests\src\baseservices\compilerservices\dynamicobjectproperties\testapis.cs:line 508
        Expected: 100
        Actual: 102
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        
  To run the test:
  > set CORE_ROOT=D:\j\workspace\x64_release_w---0575cb46\bin\tests\Windows_NT.x64.Release\Tests\Core_Root
  > D:\j\workspace\x64_release_w---0575cb46\bin\tests\Windows_NT.x64.Release\baseservices\compilerservices\dynamicobjectproperties\TestAPIs\TestAPIs.cmd
  
        Expected: True
        Actual:   False
          D:\j\workspace\x64_release_w---0575cb46\bin\tests\Windows_NT.x64.Release\TestWrappers\baseservices\baseservices.XUnitWrapper.cs(243,0): at baseservices._compilerservices_dynamicobjectproperties_TestAPIs_TestAPIs_._compilerservices_dynamicobjectproperties_TestAPIs_TestAPIs_cmd()
```

**Comment by BruceForstall** [comment]
That's `Windows_NT x64 Release Priority 1 Build and Test `

**Comment by mmitche** [comment]
Yeah, I filed an issue on it earlier today.

**Pull request merged**
