### PR TITLE
Fix for a bug in tail recursion elimination.

### PR DESCRIPTION
**Pull request by erozenfeld**
Tail recursion elimination transforms a tail call into a loop.
If compInitMem is set, we may need to zero-initialize some locals. Normally it's done in the prolog
but the loop we are creating can't include the prolog. The fix is to insert zero-initialization
for all non-parameter non-temp locals in the loop. Liveness phase will remove unnecessary initializations.

We never hit this case with normal C# code since C# definite assignment rules ensure that there are
no uninitialized locals in the generated msil. In the repro the method with tail recursion is a dynamic method and it has an uninitialized local.

### CODE REVIEW

**Comment by erozenfeld** [comment]
@briansull PTAL @dotnet/jit-contrib

**Comment by erozenfeld** [comment]
I will also add simple .il tests later.

**Comment by erozenfeld** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test

**Comment by CarolEidt** [comment]
> If compInitMem is set, we may need to zero-initialize some locals. Normally it's done in the prolog
but the loop we are creating can't include the prolog.

Just to make sure I understand correctly, the issue is that the call being transformed into a loop has some lclVars that require zero-init and, for the semantics to be correct, they need to be zero-initialized on each iteration (since each iteration was a separate call), which is why it can't be done on the prolog outside of the loop. Is that correct?

**Comment by erozenfeld** [comment]
Yes, correct.

**Comment by CarolEidt** [comment]
@erozenfeld thanks for the confirmation. LGTM.

**Comment by erozenfeld** [comment]
Desktop SuperPMI: 85 methods had diffs. 882 bytes regression (1.53% of the affected methods).

**Comment by CarolEidt** [comment]
@erozenfeld just out of curiosity - did you do any examination of the methods to see whether we're missing any obviously dead zero-inits?

**Comment by erozenfeld** [comment]
Yes, there are some cases like that. I assume these are cases where the locals are not tracked.

**Comment by CarolEidt** [comment]
> Yes, there are some cases like that. I assume these are cases where the locals are not tracked.

Would it be worth filing an issue to investigate? Or are these all large test cases that are unlikely to represent real world code?

**Pull request merged**
