### PR TITLE
merge master into release/2.1

### PR DESCRIPTION
**Pull request by RussKeldorph**

### CODE REVIEW

**Comment by RussKeldorph** [comment]
@MichalStrehovsky There are a few DefaultInterface tests failing after this merge. Can you suggest how these should be resolved?

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky There are a few DefaultInterface tests failing after this merge. Can you suggest how these should be resolved?

Disabling the tests sounds like a good plan to me. I did the same after the initial branch population when I was disabling the feature itself. They're disabled in the `Tests for features we are not shipping in this release` section of `issues.targets`. I didn't use an issue number because frankly I don't know what to do with such issue.

**Comment by RussKeldorph** [comment]
@MichalStrehovsky Ok, thanks.  I'll probably merge this as is if the tests come back passing.  Do you mind if I delete the tests in the release/2.1 branch so I can remove the exclusions?  If not, I'll move the exclusions to your existing block in issues.targets, etc.  Either way I need to follow up after this merges.

**Comment by RussKeldorph** [comment]
`Windows_NT armlb` failure is expected.  Will need to address that in master as well.

@noahfalk @kouvel `src/vm/tieredcompilation.cpp` had a large number of conflicts, so I just accepted the `master` version.  Please review and/or fix if you have concerns.

**Comment by MichalStrehovsky** [comment]
> Do you mind if I delete the tests in the release/2.1 branch so I can remove the exclusions?

Deleting sounds like a good plan too.

**Comment by kouvel** [comment]
@RussKeldorph, src/vm/tieredcompilation.cpp looks fine to me

**Pull request merged**
