### PR TITLE
Port https://github.com/dotnet/runtime/pull/46057

### PR DESCRIPTION
**Pull request by pgovind**
This ports the coreclr changes

cc @Anipik @safern

### CODE REVIEW

**Comment by pgovind** [comment]
I don't think the failures are related to the code change. Will kick off a new build just in case

**Review by safern — APPROVED** [review]
LGTM. @Anipik can we fix the corefx tests build?

**Comment by Anipik** [comment]
@wtgodbe @mmitche do we need to update the feeds here ?

**Comment by wtgodbe** [comment]
You do need to delete myget from nuget.config as it is now deprecated. I don't know where ILLink.tasks likes now, though - maybe dotnet-eng or dotnet-tools?

**Comment by Anipik** [comment]
@jkoritzinsky @ViktorHofer @safern @ericstj can you help with getting the ci green here ?
i am hitting this 
```
Running: /__w/1/s/.packages/microsoft.dotnet.buildtools/3.0.0-preview4-04022-01/lib/init-tools.sh /__w/1/s /__w/1/s/.dotnet/dotnet /__w/1/s/Tools /__w/1/s/.packages
Running: eval "/__w/1/s/.dotnet/dotnet restore "/__w/1/s/.packages/microsoft.dotnet.buildtools/3.0.0-preview4-04022-01/lib/tool-runtime/project.csproj" --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://dotnetfeed.blob.core.windows.net/dotnet-coreclr/index.json --no-cache --packages "/__w/1/s/.packages" --source https://dotnet.myget.org/F/roslyn/api/v3/index.json --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --source https://api.nuget.org/v3/index.json "
/__w/1/s/.dotnet/sdk/3.1.100/NuGet.targets(123,5): error : Unable to load the service index for source https://dotnet.myget.org/F/roslyn/api/v3/index.json. [/__w/1/s/.packages/microsoft.dotnet.buildtools/3.0.0-preview4-04022-01/lib/tool-runtime/project.csproj]
/__w/1/s/.dotnet/sdk/3.1.100/NuGet.targets(123,5): error :   Response status code does not indicate success: 404 (Feed does not exist.). [/__w/1/s/.packages/microsoft.dotnet.buildtools/3.0.0-preview4-04022-01/lib/tool-runtime/project.csproj]

```

This is repro on the local achine as well. This is failing as a result of removing the myget feeds

**Comment by wtgodbe** [comment]
@Anipik I think you need to update buildtools itself so that init-tools doesn't point to myget anymore: https://github.com/dotnet/buildtools/blob/248c82a6614c45daab4e85939a67587b5c14fa00/src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh#L38-L39, https://github.com/dotnet/buildtools/blob/248c82a6614c45daab4e85939a67587b5c14fa00/src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd#L36-L37

**Comment by Anipik** [comment]
> @Anipik I think you need to update buildtools itself so that init-tools doesn't point to myget anymore:

I can throw up a pr to fix that. do we also need to update the buildtools version after that ?

**Comment by wtgodbe** [comment]
> do we also need to update the buildtools version after that ?

Yes - will need to do the same in corefx & core-setup too (if I'm remembering correctly that both of those repos use buildtools as well)

**Comment by Anipik** [comment]
> Yes - will need to do the same in corefx & core-setup too (if I'm remembering correctly that both of those repos use buildtools as well)

the change in the buildtools will be in 2.1 and 3.0 branch correct ?

**Comment by wtgodbe** [comment]
> the change in the buildtools will be in 2.1 and 3.0 branch correct ?

I don't remember, maybe @ericstj @safern or @joperezr would?

**Comment by safern** [comment]
Based on the version of buildtools in the logs, yeah, it would need to be in the 3.0 branch: `3.0.0-preview4-04022-01` that's the version that it's used at the moment.

**Comment by safern** [comment]
> Yes - will need to do the same in corefx & core-setup too (if I'm remembering correctly that both of those repos use buildtools as well)

I don't think corefx and core-setup need buildtools in 3.1 anymore as those did fully onboard arcade for the 3.0 timeframe.

**Comment by Anipik** [comment]
adding servicing approved label as it was approved here https://github.com/dotnet/runtime/pull/46057  cc @danmosemsft

**Comment by wtgodbe** [comment]
Github UI is being weird, this is the pipeline to watch: https://dev.azure.com/dnceng/public/_build/results?buildId=953332&view=results

**Pull request merged**
