### PR TITLE
Delete EnvironmentAugments

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by filipnavara** [comment]
I didn't see a CoreFX PR switching back from `EnvironmentAugments` to `Environment`. Did I miss it?

**Comment by jkotas** [comment]
> CoreFX PR

https://github.com/dotnet/corefx/commit/5d43b70e75fc9419d9a39ca7d8f4e7143c74b235#diff-c2575c0f880b096356277e8cc2b31462

**Comment by jkotas** [comment]
Looks like CoreCLR does not have CoreFX with that change yet...

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by jkotas** [comment]
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test please
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test (Jit - TieredCompilation=0) please

**Comment by jkotas** [comment]
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test please
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test (Jit - TieredCompilation=0) please

**Comment by AaronRobinsonMSFT** [comment]
@dotnet-bot test coreclr-ci please

**Pull request merged**
