### PR TITLE
[RyuJIT/armel] Fix double reg arg passing

### LINKED ISSUE #13622: [RyuJIT/armel] Regressions with double reg arg passing
Following TCs fail from CodeGenBringUpTests

- JIT.CodeGenBringUpTests.DblAdd.DblAdd 
- JIT.CodeGenBringUpTests.DblArea.DblArea
- JIT.CodeGenBringUpTests.DblArray.DblArray
- JIT.CodeGenBringUpTests.DblAvg2.DblAvg2
- JIT.CodeGenBringUpTests.DblAvg6.DblAvg6
- JIT.CodeGenBringUpTests.DblCall2.DblCall2
- JIT.CodeGenBringUpTests.DblDist.DblDist
- JIT.CodeGenBringUpTests.DblDiv.DblDiv
- JIT.CodeGenBringUpTests.DblMul.DblMu
- JIT.CodeGenBringUpTests.DblRem.DblRem
- JIT.CodeGenBringUpTests.DblSub.DblSub
- JIT.CodeGenBringUpTests.DblVar.DblVa
- JIT.CodeGenBringUpTests.InstanceCalls.InstanceCalls
- JIT.CodeGenBringUpTests.OpMembersOfStructLocal.OpMembersOfStructLocal
- JIT.CodeGenBringUpTests.StaticCalls.StaticCalls
- JIT.CodeGenBringUpTests.struct16args.struct16args

Seems like TCs that contain double arg reg passing fail. With pri2, several hundereds of TCs fail.

### PR DESCRIPTION
**Pull request by wateret**
Fix reg count for double arg reg

Fix #13622

### CODE REVIEW

**Comment by wateret** [comment]
cc: @dotnet/arm32-contrib @CarolEidt @BruceForstall

**Comment by CarolEidt** [comment]
@dotnet-bot test Tizen armel Cross Release Build

**Comment by CarolEidt** [comment]
I'm not worried about the x86 failures - they're clearly process problems and cannot possibly be caused by a change to lsraarmarch.cpp. However, it would be nice to see the armel Release tests complete.

**Comment by wateret** [comment]
@CarolEidt Here's armel Release pri2 test results.

```
=======================
     Test Results
=======================
# CoreCLR Bin Dir  :
# Tests Discovered : 11380
# Passed           : 10552
# Failed           : 11
# Skipped          : 817
=======================
```

9 tests are due to input file path error, and the other two are readytorun tests that was failed by `crossgen` not found. Before this patch, we had 500+ failures.

**Comment by wateret** [comment]
@dotnet-bot test Tizen armel Cross Release Build

**Comment by wateret** [comment]
@dotnet-bot test Tizen armel Cross Release Build

**Comment by wateret** [comment]
@dotnet-bot test Tizen armel Cross Debug Build

**Pull request merged**
