### PR TITLE
Enable JIT\superpmi\superpmicollect on Linux and macOS

### PR DESCRIPTION
**Pull request by echesakovMSFT**
Fixes https://github.com/dotnet/coreclr/issues/22009.

Depends on: https://github.com/dotnet/coreclr/pull/24537 https://github.com/dotnet/coreclr/pull/24508

### CODE REVIEW

**Comment by echesakovMSFT** [comment]
Now when https://github.com/dotnet/coreclr/pull/24537 https://github.com/dotnet/coreclr/pull/24508 are both merged the superpmicollect test should pass on Linux and macOS

**Comment by echesakovMSFT** [comment]
@dotnet/jit-contrib PTAL

**Comment by sandreenko** [comment]
It fails in ADO with:
```
Failed to load alternative JIT compiler
   at System.RuntimeTypeHandle.GetInstantiation(System.RuntimeTypeHandle, System.Runtime.CompilerServices.ObjectHandleOnStack, Boolean)
   at System.RuntimeTypeHandle.GetInstantiationPublic()
```

**Comment by echesakovMSFT** [comment]
@sandreenko The failure is from old test run - before the PRs I mentioned had been merged. The "right" one is https://dev.azure.com/dnceng/public/_build/results?buildId=190463

**Comment by echesakovMSFT** [comment]
The test is passing on Linux and macOS. The only failing job is Build Windows_NT x86 Debug

**Pull request merged**
