### PR TITLE
Rename MemoryHandle PinnedPointer to Pointer and add property HasPointer

### PR DESCRIPTION
**Pull request by ahsonkhan**
Fixes https://github.com/dotnet/corefx/issues/24426 and https://github.com/dotnet/corefx/issues/23974

Related PR: https://github.com/dotnet/corefx/pull/24764

cc @KrzysztofCwalina, @stephentoub, @jkotas

### CODE REVIEW

**Comment by ahsonkhan** [comment]
@dotnet-bot test CentOS7.1 x64 Release Priority 1 Build and Test

**Comment by ahsonkhan** [comment]
@dotnet-bot test CentOS7.1 x64 Release Priority 1 Build and Test

**Comment by jkotas** [comment]
CentOS failure is known issue. You can ignore it.

**Comment by ahsonkhan** [comment]
> CentOS failure is known issue. You can ignore it.

OK. Thanks. Is there an issue filed?

**Comment by jkotas** [comment]
https://github.com/dotnet/coreclr/issues/14581

**Pull request merged**
