### PR TITLE
Update ibc deps

### PR DESCRIPTION
**Pull request by DrewScoggins**
These are some changes to fix the updating of both IBC and PGO package info.

### CODE REVIEW

**Comment by DrewScoggins** [comment]
@adiaaida @mmitche  PTAL

**Comment by adiaaida** [comment]
LGTM

**Comment by DrewScoggins** [comment]
Sorry, I missed this. As we speak today we had our first drop of IBC get created correctly. So at least for now we should be good going forward. The run still seems to be a little flaky, but now we should end up in a place where we are not generating IBC data and not causing crashing of the auto-updater.

**Comment by DrewScoggins** [comment]
Just want to follow up here @dagood. It looks like the jobs are completing successfully now so I don't think that there is anything we need to revert at this time, yeah?

**Comment by dagood** [comment]
Yep, it's working fine now. Thanks. 😄

**Pull request merged**
