### PR TITLE
Fix build breaks in Linux ARM port

### PR DESCRIPTION
**Pull request by jkotas**
- Add missing files for ARM legacy JIT
- Cleanup top-level defines
- Introduce central location for turning FEATURE_EVENT_TRACE on/off

There are likely more fixes required ... waiting for a new SSD card for my Raspberry Pi2 to arrive.

### CODE REVIEW

**Comment by jkotas** [comment]
cc @benpye @kangaroo

**Comment by jkotas** [comment]
@ramarag Could you please take a look?

**Comment by kangaroo** [comment]
FEATURE_EVENT_TRACE stuff LGTM.

armv7 stuff _looks_ GTM, but I haven't bootstrapped it locally.

**Comment by benpye** [comment]
LGTM on a quick glance, I will try and build this locally tomorrow.

**Comment by ramarag** [comment]
FEATURE_EVENT_TRACE changes LGTM

**Comment by richlander** [comment]
@jkotas how big of an SD card do you recommend?

**Comment by jkotas** [comment]
8GB was not enough for Raspbian + CoreCLR build. 16GB should be enough. If you are buying a new SD card, I would recommend 64GB - it is where the best $/GB point seems to be these days.

**Pull request merged**
