### PR TITLE
Fix configuration of ptrace on FreeBSD.

### PR DESCRIPTION
**Pull request by josteink**
This closes dotnet#625

### CODE REVIEW

**Comment by kangaroo** [comment]
Right now the upper level else() kind-of-sort-of means 'Linux'.  I'm not sure I like where this is canonically.  It might be nice to refactor out all the common stuff between Darwin, FBSD and Linux (if I didn't already) and then introduce an explicit FBSD block in addition to the Darwin block.

**Comment by josteink** [comment]
There wasn't really a whole lot to refactor out, but there you go.

Seems a bit redundant, but at the same time it's obviously clear what config values belongs to what platform.

**Comment by kangaroo** [comment]
LGTM

**Comment by sergiy-k** [comment]
LGTM

**Pull request merged**
