### PR TITLE
ARM-CI : Fix segmentation faults on running tests

### PR DESCRIPTION
**Pull request by sjsinju**
To make sure the reason of test failure ramdomly( #6298 ),
We checked segmentation faults occurred from mounted rootfs and the multi thread processing.

So I changed root-fs to the archived root-fs and run tests with --sequential option.

PS. The location of root-fs folder was changed from '/opt' wrote on reverted commit(#7991) to '/mnt' for resolving no space issue.

### CODE REVIEW

**Comment by sjsinju** [comment]
@dotnet-bot  test Linux ARM Emulator Cross Release Build please

**Comment by sjsinju** [comment]
@dotnet-bot test ci please

**Comment by sjsinju** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build please

**Comment by sjsinju** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by sjsinju** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build please
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by sjsinju** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build please
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by sjsinju** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build please
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by sjsinju** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build please
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by sjsinju** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build please
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by sjsinju** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build please
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by sjsinju** [comment]
@jkotas The location of root-fs folder was changed from '/opt' to '/mnt'. I checked this commit makes any more no space problems by several tests. PTAL.

**Comment by danmosemsft** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test (#8061)

**Comment by jkotas** [comment]
Thanks!

**Pull request merged**
