### PR TITLE
Moved allocator and GCStatistics into their own files.

### PR DESCRIPTION
**Pull request by ala53**
It's a small change (mostly for code clarity) but now the allocator and statistics classes are no longer part of the 36,210 line monster that is `gc.cpp` - now `gc.cpp` is only 35,905 lines. Progress!

### CODE REVIEW

**Comment by ala53** [comment]
On the CLA, is there a way not to give my home address?

**Comment by ala53** [comment]
AAAAAAAAAAAaaaaaaaaaaaaaaaAAAAAAAAAAAAAAaaaaaaaaaaaaAAAAaaaaaaaaaaaaaaAAAA!!!!!1!1!!!!!1!!! The `#includes` will probably haunt me for the rest of my life. A literal copy paste change turned into a 2 hour project because of `#include`.

**Comment by jkotas** [comment]
cc @Maoni0

**Comment by brianrob** [comment]
@ala53, thank you very much for your contribution.

It looks like this change is limited to formatting/re-organization changes.  Per our contribution guidelines, we aren't planning to take pure formatting changes (https://github.com/dotnet/coreclr/wiki/Contribution-guidelines#formatting-changes).  In addition to merge issues on the internal mirror, this also opens us up to copy-and-paste issues/bugs, as you experienced with the #includes.

If you would like to see gc.cpp re-organized, I would recommend opening an issue so that we can discuss how best to approach this.

**Pull request closed without merging**
