### PR TITLE
Fix optdata restore functionality (port #11935)

### LINKED ISSUE #11796: OptData sync needs to be re-enabled
The BuildTools/CLI update that migrated CoreCLR from project.json -> \*.csproj removed the support for syncing optdata packages. This blocks PGO and IBC optimizations from being applied on release builds.

### PR DESCRIPTION
**Pull request by dpodder**
Bring back optdata restore functionality following the move to 2.0
BuildTools and csproj-based CLI. Disable a harmless warning that broke
the Linux build when consuming PGO counts due to -Werr.

This is a port of #11935 (8f5d775cb4de2b3e765251106991940c09c0859e) from
master into release/2.0.0. The only change on top of what is is master
is the version of the optdata package declared in dir.props, which is
branch-specific.

Fixes #11796

### CODE REVIEW

**Comment by dpodder** [comment]
@gkhanna79 This will bring the PGO fixes into release/2.0.0 and enable PGO optimizations, just as #11935 did for master. Will be sending details in shiproom e-mail momentarily.

/cc: @dotnet/rap-team

**Comment by gkhanna79** [comment]
The Escrow build for Preview2 is already underway.

**Comment by gkhanna79** [comment]
Failing leg details at https://ci.dot.net/job/dotnet_coreclr/job/release_2.0.0/job/debug_windows_nt_prtest/169/

**Comment by gkhanna79** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test please

**Pull request merged**
