### PR TITLE
Add more pre-computed prime numbers to avoid expensive computation

### PR DESCRIPTION
**Pull request by ViktorHofer**
cc @jkotas

### CODE REVIEW

**Comment by jkotas** [comment]
Where is this computation showing up as expensive? The cost of the prime computation should be noise compare to the time required to fill in the Dictionary with this many elements.

Also, if somebody is using `Dictionary(int capacity)` constructor to right size the Dictionary, they will observe up to 20% more memory consumption with this change for large numbers.

**Comment by danmosemsft** [comment]
It hadn't occurred to me that the table might be cut off intentionally in order to get less than 20% overhead  for sizes over 1395263. If that's useful, then perhaps HashHelpers in corefx should copy this one.

**Comment by jkotas** [comment]
Agree. I do not think that https://github.com/dotnet/corefx/pull/6203/ was a good change to make. The only observable effect of that change is up to 20% memory consumption for right-sized collections.

**Comment by ViktorHofer** [comment]
Very interesting, thanks Jan. I haven't thought about that at all. I will close the PR and modify the corefx one to adapt this behavior.

**Pull request closed without merging**
