### PR TITLE
Revert "Enable optimization of structs"

### PR DESCRIPTION
**Pull request by jkotas**
Reverts dotnet/coreclr#7677

### CODE REVIEW

**Comment by tarekgh** [comment]
should we just merge it and not wait for CI to finish?

**Comment by jkotas** [comment]
I would rather wait to check for unexpected interactions for JIT changes that went in in the meantime.

**Comment by RussKeldorph** [comment]
@dotnet/jit-contrib @CarolEidt

**Comment by JeremyKuhne** [comment]
@jkotas It looks like the ARM packages didn't get generated successfully?

**Comment by jkotas** [comment]
Do you mean ARM package from the official build? 
@gkhanna79 has been working on the ARM packages.

**Comment by JeremyKuhne** [comment]
> Do you mean ARM package from the official build? 

Yes, apparently. Updating to 24703-04 is failing on ARM packages.

**Comment by gkhanna79** [comment]
That failure is for arm64 and not arm. I had requested @wtgodbe to disable arm64 build in official pipeline build since jit failure was keeping it broken. Given that it is disabled, are you still seeing issues with it?

**Comment by JeremyKuhne** [comment]
Was this a recent thing? Trying to update packages for CoreFX fails with a bunch of arm64 errors:

```
Unable to resolve 'runtime.win10-arm64.Microsoft.NETCore.TestHost (>= 1.2.0-beta-24703-04)' for '.NETCoreApp,Version=v1.1 (win10-arm64)'.
``

**Comment by gkhanna79** [comment]
Yes, they were disabled in the morning today. @wtgodbe can you please re-enable arm64 build and queue one to see if it comes clean? If it does, then corefx would get a new pr from maestro that should work.

**Comment by wtgodbe** [comment]
I've reverted my change from this morning, here's the queued build - https://devdiv.visualstudio.com/DevDiv/Net%20CoreFX/_build/explorer?_a=summary&buildId=414246

-Will

On Nov 3, 2016, at 9:18 PM, Gaurav Khanna <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, they were disabled in the morning today. @wtgodbe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwtgodbe&data=02%7C01%7Cwigodbe%40microsoft.com%7Cdd07e0f60fac415931d608d40469ae2a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636138299318877542&sdata=ppq8dinjprhF4rHoZhYXprzU8Ns2aW7dvQnqexjXDPI%3D&reserved=0> can you please re-enable arm64 build and queue one to see if it comes clean? If it does, then corefx would get a new pr from maestro that should work.

-

**Pull request merged**
