### PR TITLE
Load JIT from custom location for Crossgen

### PR DESCRIPTION
**Pull request by gkhanna79**
Enable crossgen to take a custom JIT location using command line. This will be helpful when we have to make changes in CLI to consume crossgen.

@jkotas PTAL

### CODE REVIEW

**Comment by gkhanna79** [comment]
Fixes https://github.com/dotnet/coreclr/issues/4531

**Comment by gkhanna79** [comment]
@dotnet-bot test Windows_NT Checked Arm64

**Comment by gkhanna79** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by rahku** [comment]
It seems x64 crossgen for arm64 is broken currently for checked & rel builds due to below error
Unable to load Jit Compiler: clrjit.dll, hr=0x800700c1

This has been failing in CI as well. In build.cmd we check incorrect errorlevel for crossgen cmd so it does not fail the build. It will be helpful if you can merge this PR soon. I will update crossgen command in build.cmd accordingly to specify JITPath parameter

CC: @kyulee1

**Comment by gkhanna79** [comment]
The failure to load the JIT stems from the fact that clrjit.dll is built as Arm64 binary. As a result, crossgen will not be able to load. I suspected as much and this confirms that for cross-targeting builds, we will need to produce two standalone JIT binaries:

1) clrjit.dll will run native on the intended arch (e.g. Arm64) and be used by the runtime.
2) clrjit_<host_arch>_<target_arch>.dll will be loaded by tools like crossgen for cross-compilation scenarios.

I will file an issue for this and to unblock this PR, will merge the JIT for Arm64.

**Comment by gkhanna79** [comment]
Filed https://github.com/dotnet/coreclr/issues/4717 and assigned to @pgavlin.

CC @russellhadley

**Comment by gkhanna79** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by gkhanna79** [comment]
@rahku The PR is clean with Arm64 since I am statically linking the JIT for now. Can you PTAL?

**Comment by rahku** [comment]
Looks good. I do see mscorlib.ni.dll being generated now. Thanks.

**Pull request merged**
