### PR TITLE
Simplify ext ver

### PR DESCRIPTION
**Pull request by gkhanna79**
@weshaggard PTAL

### CODE REVIEW

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by gkhanna79** [comment]
@weshaggard PTAL at this as well.

**Pull request merged**
