### PR TITLE
Eliminate extra time zone conversions in DateTimeOffset

### PR DESCRIPTION
**Pull request by ts2do**
PR recreated here (originally dotnet/corefx#38790)

Revised members dealing specifically with local time by removing delegation to `DateTime` methods to avoid an extra call to `TimeZoneInfo` to determine offset:
> Now
> FromFileTime(long)
> ToLocalTime()

**Before**

|        Method |      Mean |     Error |    StdDev |  Gen 0 |  Gen 1 |  Gen 2 |  Allocated |
| ------------- | --------- | --------- | --------- | ------ | ------ | ------ | ---------- |
|           Now |  474.7 ns |  1.913 ns |  1.790 ns |      - |      - |      - |          - |
|  FromFileTime |  498.1 ns |  1.685 ns |  1.494 ns |      - |      - |      - |          - |
|  ToLocalTime  |  459.5 ns |  1.732 ns |  1.620 ns |      - |      - |      - |          - |

**After**

|        Method |      Mean |     Error |    StdDev |  Gen 0 |  Gen 1 |  Gen 2 |  Allocated |
| ------------- | --------- | --------- | --------- | ------ | ------ | ------ | ---------- |
|           Now |  303.8 ns |  1.438 ns |  1.269 ns |      - |      - |      - |          - |
|  FromFileTime |  290.1 ns |  1.611 ns |  1.507 ns |      - |      - |      - |          - |
|   ToLocalTime |  236.7 ns |  0.881 ns |  0.824 ns |      - |      - |      - |          - |

```csharp
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System;

[MemoryDiagnoser]
public class Program
{
    static void Main(string[] args) => BenchmarkSwitcher.FromTypes(new[] { typeof(Program) }).Run(args);

    private long _fileTime;
    private DateTimeOffset _utc;

    [GlobalSetup]
    public void GlobalSetup()
    {
        _utc = DateTimeOffset.UtcNow;
        _fileTime = _utc.ToFileTime();
    }

    [Benchmark] public DateTimeOffset Now() => DateTimeOffset.Now;
    [Benchmark] public DateTimeOffset FromFileTime() => DateTimeOffset.FromFileTime(_fileTime);
    [Benchmark] public DateTimeOffset ToLocalTime() => _utc.ToLocalTime();
}
```

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @tarekgh

**Comment by tarekgh** [comment]
@ts2do which OS did you run this perf tests on? I am asking because I am seeing on Windows OS we are caching the TZ rule to speed up DateTime.Now which will avoid searching for the adjustment rule matching the current year.

https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/TimeZoneInfo.Win32.cs#L372

**Comment by ts2do** [comment]
I ran it on Windows.

**Comment by tarekgh** [comment]
@ts2do  could you change the test to call DateTime.Now at least one before doing the measurement?  maybe in GlobalSetup, call DateTime.Now once. then paste the results.

**Comment by tarekgh** [comment]
@ts2do nevermind, I am seeing DateTimeOffset constructor is calling TZI again and that is why this optimization is showing up on Windows too. I'll take more look at the change. Thanks. You can ignore my previous comment.

**Comment by tarekgh** [comment]
@ts2do the changes here looks good. Thanks you for getting this ready. Is it possible you can add some tests to validate the corner cases to confirm we are not behaving differently than before? 

for example, test ToLocalTime when having the ticks+offset is less than min date, or greater than max date. Also, when we having ambiguous time.

**Comment by ts2do** [comment]
It appears to me that these new test cases belong in DateTimeOffsetTests.cs in corefx if I'm not mistaken.
Should I make a new PR on corefx to simply test these cases?

**Comment by tarekgh** [comment]
> Should I make a new PR on corefx to simply test these cases?

Yes, please create the test cases in corefx and try to run these test cases manually with and without your fix. just in case, you may look at https://github.com/dotnet/corefx/blob/ab58ff6e649852b85fdb99b15992a2fa3a7d8834/Documentation/project-docs/developer-guide.md#testing-with-private-coreclr-bits to kno whow you test with your private coreclr. Thanks!

**Comment by ts2do** [comment]
I'm not exactly sure what I'm doing wrong:
At H:\coreclr: `.\build release skiptests`
At H:\corefx: `.\build /p:CoreCLROverridePath=H:\coreclr\bin\Product\Windows_NT.x64.Release\`
At H:\corefx\src\System.Runtime\tests: `H:\dnn\dotnet msbuild /t:Test`
The last command gives me a bunch of CS0436 errors for CoreFx.Private.TestUtilities. I'm running it on the nightly build [3.0.0-preview8-27919-09].

**Comment by tarekgh** [comment]
@ts2do ensure you have the latest preview installed on your machine. and try to do 

dotnet msbuild /t:rebuildandtest

**Comment by ts2do** [comment]
I got it building and running tests after cleaning my local repo and running it again. Thanks.
Because it works with the local timezone, there doesn't seem to be a good way to make straightforward unit test for it.
Perhaps it would be better to use a shared implementation in a method that accepts a `TimeZoneInfo` parameter. I don't know how that would work without `InternalsVisibleTo`.

**Comment by tarekgh** [comment]
@ts2do 

You can write the test in the way it will get validated if running on specific time zone. For example, check if the Local time zone is pacific time zone and then run the test accordingly.  of course, you can have it run on multiple time zone if you choose too.

**Comment by tarekgh** [comment]
@ts2do I know we merged this and that is good. I just came across one issue which is in the new introduced method ToLocalTime, I believe we need to call 

```C#
    ValidateOffset(offset);
```

ValidateOffset is called in DateTimeOffset(DateTime) which we changed and not calling this constructor any more. Yes this is unlikely scenario but it may happen if anyone faked time zone which can return Utc offset more/less than 14 hours.

**Comment by tarekgh** [comment]
@ts2do did you have a chance to look at my last comment?

**Comment by ts2do** [comment]
Yes, sorry for the delay. The ValidateOffset method is also invoked from the DateTimeOffset(long, TimeSpan) constructor, so I don't believe there's anything amiss here.

**Comment by tarekgh** [comment]
@ts2do that is right. thanks for confirming. we should be good here then.

**Pull request merged**
