### PR TITLE
Rename attribute to IsReadOnlyAttribute

### PR DESCRIPTION
**Pull request by OmarTawfik**
Updating type per last comments in https://github.com/dotnet/corefx/issues/17741

### CODE REVIEW

**Comment by VSadov** [comment]
LGTM

**Comment by OmarTawfik** [comment]
@jkotas Is these timeouts in Tizen expected? (not first time)

**Comment by OmarTawfik** [comment]
Retrying for failure https://ci.dot.net/job/dotnet_coreclr/job/master/job/armel_cross_release_tizen_prtest/1239/

**Comment by jkotas** [comment]
> these timeouts in Tizen expected

Know issue: https://github.com/dotnet/coreclr/issues/10986

**Pull request merged**
