### PR TITLE
format spmi sources.

### PR DESCRIPTION
**Pull request by sandreenko**
Format spmi sources with jit-format.
Most changes look reasonable, maybe only multiline define becomes worse.

### CODE REVIEW

**Comment by sandreenko** [comment]
Where is `ICorJitInfo interface declaration`?

**Comment by BruceForstall** [comment]
corjit.h/corinfo.h

**Comment by sandreenko** [comment]
Fixed. However, I was trying to compare these two files and there were many diffs except `virtual` and `= 0` already.

**Comment by BruceForstall** [comment]
We should make the files as similar as possible, at least for the main parts. As long as they are (relatively) easy to compare, though, that is the goal.

**Pull request merged**
