### PR TITLE
Update sync.cmd to download Azure Blobs. Also change publish.proj to …

### PR DESCRIPTION
**Pull request by wtgodbe**
…publish packages into symbol/pkg directories

### CODE REVIEW

**Comment by wtgodbe** [comment]
@maririos PTAL - I didn't add Azure Blobs functionality to sync.sh since we'll only need to use it once, on windows, after all packages have been created on all OS's.

**Comment by wtgodbe** [comment]
@dotnet-bot test this please

**Comment by wtgodbe** [comment]
@dotnet-bot test this please

**Comment by wtgodbe** [comment]
@dotnet-bot test this please

**Comment by wtgodbe** [comment]
@mmitche do you know why some of the Windows jobs are failing? The error message seems to indicate it's on the Hudson end

**Comment by mmitche** [comment]
@wtgodbe This is a new one for me. I wonder if it is related to the upgrade to java 8.  Hmm.  Thanks for the heads up

**Comment by wtgodbe** [comment]
@dotnet-bot test this please

**Comment by maririos** [comment]
LGTM

**Comment by wtgodbe** [comment]
Failures seem to be on Windows builds, and due to recent Jenkins issues with the update from Java 7 to Java 8 (there's no reason this change would affect the test jobs). Merging.

**Pull request merged**
