### PR TITLE
Fix processing of unhandled exception in exception filter

### PR DESCRIPTION
**Pull request by janvorli**
This change fixes processing of unhandled exceptions in exception filter on Unix.
Before this fix, such exception leads to assert in the exception handling code
due to the fact that the exception tracker of the unhandled exception is not
popped from the exception tracker stack of the thread.
Although the PopTrackers method was being called, it bailed out due to the fact
that the exception tracker belonging to the unhandled exception has empty scanned
stack range.
The fix is to explicitly pop the tracker in the EX_CATCH that catches the
exception from the filter.

### CODE REVIEW

**Comment by janvorli** [comment]
@jkotas can you take a look please?
CC: @sergiy-k, @adityamandaleeka

**Comment by sergiy-k** [comment]
LGTM.

Could you please also re-enable the test that was failing due to this issue? Thank you.

**Comment by janvorli** [comment]
@sergiy-k Sure, I'll enable the test and amend this commit.

**Comment by jkotas** [comment]
LGTM

**Comment by sergiy-k** [comment]
Thank you!

**Comment by adityamandaleeka** [comment]
LGTM

**Comment by adityamandaleeka** [comment]
#1969

**Comment by janvorli** [comment]
@mmitche it looks like the Ubuntu release build and test still has the problem of timing out when restoring packages. Or is it something different than the issue we were observing last week or so?

**Comment by mmitche** [comment]
@dotnet-bot test Ubuntu x64 Release Build and Test

**Comment by mmitche** [comment]
@dotnet-bot test Ubuntu release

**Pull request merged**
