### PR TITLE
Move wiki files to coreclr repo

### PR DESCRIPTION
**Pull request by richlander**
- Move remainder of wiki documents to CoreCLR repo
- Intend to keep the wiki open, with one file that provides a small set of helpful links into the repo.

See https://github.com/dotnet/corefx/pull/1879. It is an analogous PR on the CoreFX repo. They should be merged at the same time, since there are links that cross-reference new content.

In response to: https://github.com/dotnet/corefx/issues/1781.

Earlier wiki migration: https://github.com/dotnet/coreclr/pull/662.

/cc @ellismg, @janvorli, @blackdwarf, @terrajobst, @akoeplinger

### CODE REVIEW

**Comment by akoeplinger** [comment]
Looks great, thanks for doing this work :+1: 

The only gripe I have left is that currently when I browse the [Documentation root](https://github.com/richlander/coreclr/tree/rich-docs-update2/Documentation) I need to scroll down 2+ pages until I get to the rendered readme content, cause there are so many files in the root.

Now that we're no longer limited by the GH wiki's flat file structure, can we move the files into subfolders? I think the categorization you already did on the readme (`get-dotnet-core\`, `project-docs\`, `coding-guidelines\`) would make the most sense.

**Comment by jasonwilliams200OK** [comment]
:+1: to the additions and @akoeplinger's suggestion about subdirectories.

**Comment by richlander** [comment]
Good point @akoeplinger and @jasonwilliams200OK. It was always the plan to wait until good categories of docs presented themselves. That does indeed seem to happening. Let's merge these two PRs first and then figure that out.

**Comment by richlander** [comment]
Looking for some validation on this one before I merge it and the corefx one.

/cc @janvorli, @jkotas, @kangaroo, @gkhanna79

**Comment by kangaroo** [comment]
LGTM -- I'm not sure if its an anomaly, but github took FOREVER to render Documentation when I clicked on it in your repo.

@akoeplinger feedback is valid, but I'm not sure its a huge deal.  I think if we choose to move to folders, that can be done in a follow up PR.

**Comment by jasonwilliams200OK** [comment]
>  github took FOREVER to render

try switching :b:rowser!

**Comment by richlander** [comment]
@kangaroo Just clicked (presumably) on the same buttons and didn't see the big slow-down. 

Agreed. No need to re-work the directory structure in this PR, but a good idea.

**Pull request merged**
