### PR TITLE
Replace HNDTYPE defines with enum

### PR DESCRIPTION
**Pull request by adityamandaleeka**
As part of the work to move handle-related code to the GC interface and stop VM code from using things objecthandle.h directly, this change turns the #define'd `HNDTYPE_*` values into an enum class `HandleType` that's in gcinterface.h.

In the future, I'd like all the code that touches these types to use the new type, but there is so much code that uses integral types to deal with these values that it isn't practical to change everything right now. I've changed some functions (where practical) to use the new type, and for the rest I've added casts liberally to keep the existing code working.

### CODE REVIEW

**Comment by jkotas** [comment]
This is just a nice to have cleanup, not strictly required for the standalone GC work, correct? If it is the case, I would like to see it done completely so that it is net improvement. I do not think it is a net improvement right now because of the casts that are everywhere.

**Comment by adityamandaleeka** [comment]
@jkotas I'm actually removing all the casts and making it a plain enum instead of enum class. We can do the work to make it enum class and use that type everywhere later.

**Comment by jkotas** [comment]
Also, I am not sure whether it is a good idea to make this `enum class HandleType`...

**Comment by adityamandaleeka** [comment]
@jkotas I just pushed a commit undoing all the `enum class` stuff which necessitated all the casts. It's much simpler. Please let me know what you think.

**Comment by jkotas** [comment]
Looks much better to me know.

**Comment by adityamandaleeka** [comment]
The JIT test failure is a known issue: https://github.com/dotnet/coreclr/issues/10022

@dotnet-bot test Windows_NT x86 Checked Build and Test

**Pull request merged**
