### PR TITLE
Fix IJW test failing on Linux

### PR DESCRIPTION
**Pull request by morganbr**
Attempt to fix testsUnsupportedOutsideWindows to not call the IJW test

### CODE REVIEW

**Comment by tannergooding** [comment]
Issue is now tracked by https://github.com/dotnet/coreclr/issues/19731

**Comment by morganbr** [comment]
@dotnet-bot build and test this please

**Comment by morganbr** [comment]
@dotnet-bot test CentOS7.1 x64 Checked Innerloop Build and Test please

**Comment by morganbr** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by morganbr** [comment]
@dotnet-bot test Windows_NT arm64 Cross Debug Innerloop Build

**Pull request merged**
