### PR TITLE
Throw InvalidProgramException when VarArgs are encountered

### PR DESCRIPTION
**Pull request by gkhanna79**
@jkotas PTAL

### CODE REVIEW

**Comment by jkotas** [comment]
LGTM

**Comment by gkhanna79** [comment]
@dotnet-bot test  Windows_NT x86 legacy_backend Checked Build and Test please

**Comment by gkhanna79** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build and Test please

**Comment by gkhanna79** [comment]
@janvorli Are you aware of this failure in CentOS?

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/debug_centos7.1_prtest/1634/

**Comment by gkhanna79** [comment]
@janvorli Thoughts?

**Comment by janvorli** [comment]
@gkhanna79 this is a new test that @kouvel has added yesterday when checking in the cross process named mutexes stuff. He has a PR pending with a fix for some issues he has discovered later. @kouvel - is the error in the test something that you'd expect to be fixed by your pending change?

**Comment by kouvel** [comment]
This seems like a new issue - basic named mutex creation is failing. I suspect it's an intermittent issue, I'll take a look.

**Comment by gkhanna79** [comment]
@kouvel Thank you. I would like to merge this PR today, so please let me know if you think this test failure would be a blocker.

**Comment by kouvel** [comment]
I don't think it's related to your change, so it shouldn't block your change. It may pass on rerun, this may be something special about that machine.

**Comment by kouvel** [comment]
I can continue to investigate this separately

**Comment by gkhanna79** [comment]
Thank you. I will merge the PR.

**Comment by gkhanna79** [comment]
Fixes https://github.com/dotnet/coreclr/issues/4940

**Pull request merged**
