### PR TITLE
Add #!/bin/bash to beginning of shell test scripts

### PR DESCRIPTION
**Pull request by wtgodbe**
Should solve baseservices test failures in Helix

### CODE REVIEW

**Comment by wtgodbe** [comment]
@ramarag @MattGal PTAL

**Comment by MattGal** [comment]
LGTM.

**Comment by ramarag** [comment]
i thought there was a good reason in not having them. I am no longer sure what it is,
it probably is because some distros don't have bash on them or something like that

@mmitche do you know if it so ?

cc @adityam i kind of remember hearing this from you

**Comment by ramarag** [comment]
cc @adityamandaleeka  i kind of remember hearing this from you

**Comment by mmitche** [comment]
@ramarag I can't think of one.

**Comment by adityamandaleeka** [comment]
This looks fine to me. The only thing I might change is to use `#!/usr/bin/env bash` instead, since some OS's don't have bash in `/usr/bin`.

**Pull request merged**
