### PR TITLE
ARM-CI : Use archived root-fs and run tests with --sequential option

### PR DESCRIPTION
**Pull request by sjsinju**
To make sure the reason of test failure ramdomly( #6298 ), We tried many solutions locally.
And We figured out segmentation faults occurred from mounted root-fs and the multi thread processing.

So I changed root-fs to archived root-fs and run tests with --sequential option.

### CODE REVIEW

**Comment by sjsinju** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by jkotas** [comment]
@mmitche PTLA

**Comment by mmitche** [comment]
I don't think I know enough about this to comment.  Does this look good to you @jashook ?

**Comment by jkotas** [comment]
Ok. It looks good to me.

**Comment by jkotas** [comment]
@sjsinju Thanks a lot for coming up with a fix - hopefully, it will fix the CI failures on Linux ARM.

**Comment by sjsinju** [comment]
@jkotas Sorry, Revert please. It looks like to make a side effect about storage size likes #6676. 
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/arm_emulator_cross_debug_ubuntu/430/

After checking and fix, I will make PR again.  Sorry

**Comment by jkotas** [comment]
reverted

**Pull request merged**
