### PR TITLE
Improve performance of parsing Version

### PR DESCRIPTION
**Pull request by hughbe**
Up to x6 perf improvement and x7 allocation reduction by using custom specific parsing code and avoiding split allocations

## Benchmark results
benchmark

## Benchmark code
<details>
<summary>Click Here</summary>
```
public static void TimeAction(string prefix, Action action)
{
    var sw = new Stopwatch();
    for (int iter = 0; iter < 5; iter++)
    {
        int gen0 = GC.CollectionCount(0);
        sw.Restart();
        for (int i = 0; i < 10000000; i++)
        {
            action();
        }
        sw.Stop();
        Console.WriteLine($"{prefix}Time: {sw.Elapsed.TotalSeconds}\tGC0: {GC.CollectionCount(0) - gen0}");
    }
}

static void Main(string[] args)
{
    Console.WriteLine("**** Measure x.x ****");
    TimeAction("Old: ", () => new VersionOld("1.1"));
    TimeAction("New: ", () => new VersionNew("1.1"));

    Console.WriteLine("**** Measure x.x.x ****");
    TimeAction("Old: ", () => new VersionOld("1.1.1"));
    TimeAction("New: ", () => new VersionNew("1.1.1"));

    Console.WriteLine("**** Measure x.x.x.x ****");
    TimeAction("Old: ", () => new VersionOld("1.1.1.1"));
    TimeAction("New: ", () => new VersionNew("1.1.1.1"));

    Console.WriteLine("**** Measure x.x.x.x with whitespace ****");
    TimeAction("Old: ", () => new VersionOld("   1   .   1   .   1   .   1   "));
    TimeAction("New: ", () => new VersionNew("   1   .   1   .   1   .   1   "));

    Console.ReadLine();
}
```
</details>

### CODE REVIEW

**Comment by stephentoub** [comment]
Nice improvement, but wouldn't it be better to improve the performance of Int32.TryParse (at least for the Integer / InvariantCulture case) so that the benefit is available everywhere TryParse is used rather than just for Version?  Integer parsing is *much* more common than version parsing. Or is the improvement somehow specific to Version?

**Comment by hughbe** [comment]
@stephentoub good suggestion, I'll take a look

**Comment by hughbe** [comment]
Test Windows_NT x64 Release Priority 1 Build and Test

**Comment by Petermarcu** [comment]
@stephentoub , @hughbe , Any update on this one. Is the current change good as is and the perf improvement in Int32.TryParse is a bonus or should we only be doing it in Int32.TryParse?

**Comment by stephentoub** [comment]
I would prefer we not add all of this complexity to Version unless we actually have evidence that Version parsing is a bottleneck somewhere.
cc: @jkotas

**Comment by hughbe** [comment]
I agree. I'll close this!

**Pull request closed without merging**
