### PR TITLE
Improve hardware intrinsic tests

### PR DESCRIPTION
**Pull request by fiigii**
This PR removes redundant checks for 64-bit intrinsics https://github.com/dotnet/coreclr/pull/21264#discussion_r238410886 and moves more `Sse2` and `Sse2.X64` intrinsic tests into templates.

### CODE REVIEW

**Comment by fiigii** [comment]
@dotnet-bot test Windows_NT x64 Checked jitsse2only
@dotnet-bot test Windows_NT x64 Checked jitincompletehwintrinsic
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnoavx
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnoavx2
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnosimd
@dotnet-bot test Windows_NT x64 Checked jitnox86hwintrinsic

@dotnet-bot test Windows_NT x86 Checked jitsse2only
@dotnet-bot test Windows_NT x86 Checked jitincompletehwintrinsic
@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnoavx
@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnoavx2
@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnosimd
@dotnet-bot test Windows_NT x86 Checked jitnox86hwintrinsic

@dotnet-bot test Ubuntu x64 Checked jitsse2only
@dotnet-bot test Ubuntu x64 Checked jitincompletehwintrinsic
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnoavx
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnoavx2
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnosimd
@dotnet-bot test Ubuntu x64 Checked jitnox86hwintrinsic

**Comment by fiigii** [comment]
@dotnet-bot test Ubuntu x64 Checked jitincompletehwintrinsic

**Comment by fiigii** [comment]
@tannergooding Could you please merge this?

**Comment by tannergooding** [comment]
This one should have at least one other sign-off.

**Comment by fiigii** [comment]
@CarolEidt PTAL

**Comment by fiigii** [comment]
@CarolEidt ping?

**Pull request merged**
