### PR TITLE
Build using clang38

### PR DESCRIPTION
**Pull request by jashook**
** Note this is a merge to dev/unix_test_workflow **

### CODE REVIEW

**Comment by jashook** [comment]
@dotnet-bot test CI Please

**Comment by jashook** [comment]
@dotnet-bot test CI Please

**Comment by jashook** [comment]
@dotnet-bot test CI Please

**Comment by janvorli** [comment]
@jashook why clang 3.8 and not 3.9? We have moved ARM32 to clang 3.9 and we would like to move x64 to clang 3.9 soon as well.

**Comment by jashook** [comment]
Currently 3.8 is the version @sdmaclea has been using, this was to achieve parity with his own dev workflow.

**Pull request merged**
