### PR TITLE
Restore original dll names, use Define constants.

### PR DESCRIPTION
**Pull request by richardlford**
This changes set has no functional change, rather it cleans
up some aspects of a previous port.

When the hfa dlls were originally ported it was not known that
C# #defines could be used in the tests, so source files that
use #if were expanded to multiple source files with the preprocessing
being done manually. This changes goes back to using the original
files with appropriate define constants in the project files.

In addition, when these dlls were ported abbreviated names were
used. This change restores the dll names to the originals.

### CODE REVIEW

**Comment by richardlford** [comment]
@pgavlin, PTAL.

**Comment by pgavlin** [comment]
LGTM

**Comment by richardlford** [comment]
There were failure on non-windows platforms because the common hfa_interop.cs file that I restored did not have a change the had been made in the original port, namely omitting the ".dll" suffix on the DLL name. I've pushed that fix.  @pgavlin, please take another look. I've not squashed the commits yet so you can just see what I changed. I'll squash before merging.

**Comment by richardlford** [comment]
The OSX failure looks to be an infrastructure failure. I'll wait for Ubuntu to finish. If it succeeds I'll retry the testing.

**Comment by richardlford** [comment]
@dotnet-bot, retest this please.

**Comment by richardlford** [comment]
Ubuntu passed so I restarted testing to see if the OS X failure was intermittent.

**Pull request merged**
