### PR TITLE
Write barrier optimizations for ARM64 Windows

### PR DESCRIPTION
**Pull request by adityamandaleeka**
This change is a step towards unification of the ARM64 write barrier logic between Windows and Unix. It brings over some of the changes that were done for Unix in https://github.com/dotnet/coreclr/pull/12334 such as using a literal pool to hold heap location/geometry information used in the barriers.

Parts of the code have been tweaked in pursuit of performance gains.

- The cmp+ccmp pair has been replaced with two discrete cmp/branches to detangle it and allow for a faster exit if the lower bound check fails.
- The ephemeral bounds are now being loaded simultaneously with an ldp rather than separately prior to each compare.
- The shift for indexing into the card table has been separated out into its own instruction.

Sampling a write barrier-heavy test after these changes shows a ~7-12% decrease in the time spent in the barrier relative to the current, post-optimization version that's in use on Unix today.

Once this is in, I plan to port the deltas over to Unix so that the barriers will be in sync. I left the CLR writewatch and manually managed card bundles stuff alone on Windows for now since it's not enabled yet, but I'll likely experiment with those in the near future and check in the remaining pieces after doing so.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
> The cmp+ccmp pair has been replaced with two discrete cmp/branches to detangle it and allow for a faster exit if the lower bound check fails.

It looks like you changed from two compare/branches to two compares and one branch, not the other way round...

**Comment by adityamandaleeka** [comment]
@AndyAyersMS Sorry for the confusion. My comment was in reference to the ways my change digresses from the optimizations done on ARM64 Unix. With that in mind, the cmp+ccmp in `JIT_WriteBarrier` has been replaced with the two discrete cmps/branches.

The checked write barrier, where the cmp+ccmp thing was also done, has not been modified in this way. It will be interesting to get data about whether the address tends to be within the bounds of the heap, but until then I'll leave it alone.

**Comment by adityamandaleeka** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by adityamandaleeka** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by adityamandaleeka** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by adityamandaleeka** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Pull request merged**
