### PR TITLE
Use beforefieldinit field for Comparer/EqualityComparer.Default 

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
Fixed #1157

**Comment by jkotas** [comment]
@stephentoub PTLA

**Comment by VSadov** [comment]
LGTM

**Comment by stephentoub** [comment]
LGTM.  Should we do the same for ```Comparer<T>.Default```?
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/Comparer.cs#L20

**Comment by jkotas** [comment]
Fixed `Comparer.Default` as well.

**Comment by jkotas** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by jkotas** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test  please

**Pull request merged**
