### PR TITLE
Fix legacy Globalization tests to work on Linux

### LINKED ISSUE #9289: CoreMangLib/cti/system/globalization/datetimeformatinfo/DateTimeFormatInfoGetMonthName and CoreMangLib/cti/system/globalization/datetimeformatinfo/DateTimeFormatInfoGetAbbreviatedMonthName tests fail on Fedora23 and Ubuntu16.04
We haven't caught this before because we don't run tests for these distros in the CI, but they're failing in Helix - https://mc.dot.net/#/product/netcore/master/source/official~2Fcoreclr~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170202.02/workItem/CoreMangLib.XUnitWrapper

Error messages look like the following:
`expected[i] = janv., actual = Janv.\nERROR!!!`

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes #9289

### CODE REVIEW

**Comment by tarekgh** [comment]
https://github.com/dotnet/coreclr/pull/9315

**Comment by tarekgh** [comment]
@AlexGhiondea could you please have a quick look? these are trivial test fixes

**Comment by tarekgh** [comment]
cc @wtgodbe

**Comment by wtgodbe** [comment]
Did you confirm these tests pass on Ubuntu16.04 and Fedora23? Unfortunately we don't have CI support to run tests for those distros currently

**Comment by wtgodbe** [comment]
Otherwise LGTM

**Comment by tarekgh** [comment]
> Did you confirm these tests pass on Ubuntu16.04 and Fedora23? Unfortunately we don't have CI support to run tests for those distros currently

I confirmed on Ubuntu16.04 but it should pass now on Fedora23 too..

**Comment by jkotas** [comment]
Do we have appropriate coverage in corefx? If yet, can we delete these tests here? If not, we should add the coverage in corefx and delete these tests here.

**Comment by tarekgh** [comment]
> Do we have appropriate coverage in corefx? If yet, can we delete these tests here? If not, we should add the coverage in corefx and delete these tests here.

we have good coverage on corefx. I thought we have these in coreclr just for basic validation before consuming coreclr on corefx. I am not sure who added these in the first place here.

**Comment by jkotas** [comment]
These tests were added in the early days when there was not a very good coordination. Folks were looking just at number of tests ported, without noticing that the same tests has been or are being ported in corefx repo as well...

**Comment by tarekgh** [comment]
ok, I'll go ahead and remove these.

**Comment by tarekgh** [comment]
@jkotas I have removed all globalization tests from coreclr. please let me know if you have any other comments. thanks

**Comment by jkotas** [comment]
Awesome! Thanks.

**Pull request merged**
