### PR TITLE
Add missing file to the previous hardware exceptions fix

### PR DESCRIPTION
**Pull request by janvorli**
I've forgotten to add one change to the fix.

### CODE REVIEW

**Comment by janvorli** [comment]
@jkotas, can you please take a quick look at this trivial change?

**Comment by mmitche** [comment]
Trivial is good, then I get to check out whether the new PRs worked properly.  For now just ignore anything but 'default'

**Comment by jkotas** [comment]
LGTM

**Comment by sergiy-k** [comment]
LGTM

**Comment by mikem8361** [comment]
@janvorli, does this fix #1700?

**Comment by janvorli** [comment]
@mikem8361 #1699 fixes that and this change was a missing file that should have been merged in with #1699.

**Pull request merged**
