### PR TITLE
Fix failing tests on Ubuntu R2R configuration

### PR DESCRIPTION
**Pull request by fadimounir**
I fixed the dependencies on 2 tests.

For the RMV* tests, they are much more complicated to fix, with little value. They require a 'runner' app that performs some reflection operations on the compiled assemblies. The runner app uses a couple of APIs not available on CoreCLR, so I decided to delete the tests.

### CODE REVIEW

**Comment by fadimounir** [comment]
Fix for #5419

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu Checked pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu Release pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Windows_NT Checked pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu x64 Checked R2R pri1 Build & Test please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu x64 Release Priority 1 Build and Test please

**Comment by fadimounir** [comment]
@dotnet-bot test Windows_NT x64 Checked R2R pri1 Build & Test please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu Release pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu Checked pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu x64 Release Priority 1 Build and Test please

**Comment by fadimounir** [comment]
@dotnet-bot test Windows_NT Checked pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu Release pri1 please

**Comment by fadimounir** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu Release pri1 please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu Checked pri1 please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu Release pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu Checked pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu Release pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu x64 Release Priority 1 Build and Test please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu x64 Release R2R pri1 Build & Test please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu Release pri1r2r please

**Comment by gkhanna79** [comment]
Changes are working as expected on Ubuntu - http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_checked_ubuntu_pri1r2r_tst_prtest/11/#showFailuresLink

Others failures are infra issues.

**Comment by fadimounir** [comment]
I am going to merge this into master. Here are the reasons for the 4 failing CI jobs:

1. Ubuntu Checked R2R: 5 failing tests not related to this PR. This PR really fixes the previously failing tests
2. Ubuntu Release: Infrastructure issue (out of disk space).
3. Ubuntu Release R2R: Same reason as number 1 above.
4. Windows Checked R2R: One failing test, due to a product bug that was fixed yesterday with another PR.

**Pull request merged**
