### PR TITLE
[RyuJIT/ARM32] Move genJumpKindsForTree into common part

### PR DESCRIPTION
**Pull request by mskvortsov**
Moves `genJumpKindsForTree()` into common part and makes use of it in `GT_JTRUE` codegen.
Fixes failures of
```
JIT.IL_Conformance.Old.Conformance_Base.bge_r4
JIT.IL_Conformance.Old.Conformance_Base.bge_un_r4
JIT.IL_Conformance.Old.Conformance_Base.ble_r4
JIT.IL_Conformance.Old.Conformance_Base.ble_un_r4
JIT.IL_Conformance.Old.Conformance_Base.blt_r4
JIT.IL_Conformance.Old.Conformance_Base.blt_un_r4
JIT.IL_Conformance.Old.Conformance_Base.clt_r4
JIT.IL_Conformance.Old.Conformance_Base.clt_un_r4
```
cc @dotnet/arm32-contrib

### CODE REVIEW

**Comment by mskvortsov** [comment]
@dotnet-bot test Windows_NT arm64 Checked
@dotnet-bot test Windows_NT arm64 Release

**Comment by BruceForstall** [comment]
cc @dotnet/jit-contrib

**Comment by CarolEidt** [comment]
:shipit:

**Comment by BruceForstall** [comment]
arm64 testing failed with:
```
TestID: calli_excep.cmd_4061
Path  : JIT/Directed/pinvoke/calli_excep/calli_excep.cmd

Started: Thu Apr 20 10:14:56 2017
Started: Thu Apr 20 10:15:01 2017
Output: TEST_CMD_LINE: JIT\Directed\pinvoke\calli_excep> C:\Users\DDJOIN\arm64_ci\tests\JIT\Directed\pinvoke\calli_excep\calli_excep.cmd 
BEGIN EXECUTION
 "C:\Users\DDJOIN\arm64_ci\tests\Tests\Core_Root\corerun.exe" calli_excep.exe 
Expected: 100
Actual: 255
END EXECUTION - FAILED
FAILED
```

@jashook Can I assume this test should pass, and there is no infrastructure/test issue right now?

**Comment by BruceForstall** [comment]
fyi, https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_checked_windows_nt_prtest/177/, https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_release_windows_nt_prtest/19/

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm64 Checked
@dotnet-bot test Windows_NT arm64 Release

**Comment by BruceForstall** [comment]
@mskvortsov In the future, if you need to move code from codegenarm64.cpp to codegenarmarch.cpp (or similar, from arm32 or arm64 specific, to shared), it would be useful to have one commit that copies the code *exactly*, without changing anything, and a subsequent commit that has any required changes to make it work for both platforms. Then I could easily review both parts independently.

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm64 Checked
@dotnet-bot test Windows_NT arm64 Release

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm64 Checked
@dotnet-bot test Windows_NT arm64 Release

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by BruceForstall** [comment]
The arm64 CI is not working right now. I'm going to merge this instead of waiting, this time.

**Pull request merged**
