### PR TITLE
ARM64 out of proc unwind for DAC

### PR DESCRIPTION
**Pull request by mikem8361**
Removed FEATURE_DATATARGET4 for arm64

Added SP check to createdump's native unwind loop to make it more robust.

Issue: https://github.com/dotnet/coreclr/issues/15062

### CODE REVIEW

**Comment by mikem8361** [comment]
#### Description

Without this change, our diagnostics tools like CLRMD and dotnet-dump on Linux arm64 are not able to unwind certain special HelperMethodFrames breaking commands like "clrstack" and any CLRMD based tool that unwinds stack frames.

Implementing this for Linux arm64 is important for three scenarios:

1) "createdump" uses PAL_VirtualUnwindOutOfProc directlry to make sure the code/stack for all the native stack frames.
2) dotnet-dump for linux/ELF core dumps on arm64.  There is no way to implement the data target 4 interface.
3) Same with any CLRMD code using it's managed stack unwind API on Linux core dumps.                         

#### Customer Impact

Our diagnostic tools don't display the complete stack trace.
                             
#### Regression?

This is not a regression.

#### Risk

There is no risk to the normal runtime in-proc unwinding. 

This change affects the DAC unwinding of the HelperMethodFrames for the arm64 architecture. This change affects the "createdump" utility. Could affect managed debugging (VSCode) on Linux. 

This risk is mitigated by extensive manually testing using "createdump" which enumerates all the thread's stacks. I added some temp code to compare/assert the new code with the old code results on arm64. On all three architectures, I manually verified that createdump was correctly enumerating all the thread's stack frames by comparing the debug logging with a native debugger backtrace under lldb/gdb on the core dump generated. Also verified that the DAC's usage of this PAL unwind function (via SOS's clrstack cmd) works to unwind the special uncached method helper frame.

**Comment by mikem8361** [comment]
@MeiChin-Tsai, the changes for just ARM64 are a lot less.  Do you approve?

/cc: @tommcdon

**Comment by mikem8361** [comment]
@tommcdon

**Comment by MeiChin-Tsai** [comment]
approved.

**Comment by MeiChin-Tsai** [comment]
Please get it in before preview 9 snap which is Aug 20th.

**Pull request merged**
