### PR TITLE
Add x86 legacy backend exclusions.

### PR DESCRIPTION
**Pull request by jashook**
Pass this file to runtest.cmd using exclude0 or exclude.

### CODE REVIEW

**Comment by jashook** [comment]
@mmitche @adiaaida PTAL

**Comment by adiaaida** [comment]
Can you change the commit description to something like "Add x86 legacy backend exclusions"?

**Comment by adiaaida** [comment]
Otherwise. LGTM

**Comment by jashook** [comment]
@dotnet-bot test OSX x64 Release Build and Test

**Comment by jashook** [comment]
@dotnet-bot test Ubuntu x64 Release Build and Test

**Comment by jashook** [comment]
@dotnet-bot test Ubuntu x64 Release Build and Test

**Pull request merged**
