### PR TITLE
Pull master changes into NullableFeature

### PR DESCRIPTION
**Pull request by safern**
There where merge conflicts this time in Delegate as @danmosemsft anticipated due to it being moved into the shared partition. I fixed them under a separate commit so that it is review-able.

Let's merge into master after this PR is merged to avoid fixing more conflicts like this and from talking with @joshfree he suggested that we could make preview4 cut and start exposing this annotations on the ref assemblies, have people try it out, and then have the compiler fix the initialization issue that would impact the perf and also remove the Nullable attributes from private/internal members in the ILLinker, that would put some pressure on them to fix it during next previews.

### CODE REVIEW

**Comment by safern** [comment]
This is the commit where I fixed merge conflicts: 
https://github.com/dotnet/coreclr/pull/23735/commits/adef84e398c0c2743d5f1f3900db989a6819b653

**Comment by stephentoub** [comment]
> This is the commit where I fixed merge conflicts:

Just for my reference, did the Array.Empty change in MemoryStream we talked about end up needing to be resolved?

**Comment by safern** [comment]
> Just for my reference, did the Array.Empty change in MemoryStream we talked about end up needing to be resolved?

Nope, that didn't show as a conflict, apparently git was smart enough 😄

**Comment by stephentoub** [comment]
@safern, thanks.  Nothing in the merge commit stands out to me... was there anything of note in the conflicts to be resolved?

**Comment by safern** [comment]
> was there anything of note in the conflicts to be resolved?

Not really, just that since the file was split into 2 in master, it was hard to do it, and a lot of eye validation that I didn't miss any annotation, that is why I separated the commit, so that it was clear what I did... thanks for reviewing it 😄

**Pull request merged**
