### PR TITLE
Fix for issue 5639

### PR DESCRIPTION
**Pull request by briansull**
Added check for hfa type

Fixes issue #5639 - ARM64 R2R: Assertion failed 'varDsc->lvOnFrame'\

Failures in these tests
JIT\jit64\hfa\main\testA\hfa_sd2A_d\hfa_sd2A_d.cmd
 JIT\jit64\hfa\main\testA\hfa_sd2A_r\hfa_sd2A_r.cmd
 JIT\jit64\hfa\main\testA\hfa_sf2A_d\hfa_sf2A_d.cmd
 JIT\jit64\hfa\main\testB\hfa_sd2B_d\hfa_sd2B_d.cmd
 JIT\jit64\hfa\main\testA\hfa_sf2A_r\hfa_sf2A_r.cmd
 JIT\jit64\hfa\main\testB\hfa_sf2B_d\hfa_sf2B_d.cmd
 JIT\jit64\hfa\main\testB\hfa_sf2B_r\hfa_sf2B_r.cmd
 JIT\jit64\hfa\main\testB\hfa_sd2B_r\hfa_sd2B_r.cmd
 JIT\jit64\hfa\main\testC\hfa_sd2C_r\hfa_sd2C_r.cmd
 JIT\jit64\hfa\main\testC\hfa_sd2C_d\hfa_sd2C_d.cmd
 JIT\jit64\hfa\main\testC\hfa_sf2C_r\hfa_sf2C_r.cmd
 JIT\jit64\hfa\main\testC\hfa_sf2C_d\hfa_sf2C_d.cmd

### CODE REVIEW

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked
@dotnet-bot test Windows_NT arm64 Checked pri1r2r

**Comment by briansull** [comment]
@dotnet/arm64-contrib PTAL

**Comment by kyulee1** [comment]
Can you update Tests.lst to delete "R2R_FAIL"?

**Comment by briansull** [comment]
OK I will update Tests.lst

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked pri1r2r

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked pri1r2r

**Comment by kyulee1** [comment]
LGTM

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked pri1r2r

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked pri1r2r

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 checked pri1r2r

**Pull request merged**
