### PR TITLE
Adding perf tests for the single precision math functions in System.MathF.

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves https://github.com/dotnet/coreclr/issues/7691

### CODE REVIEW

**Comment by tannergooding** [comment]
This replaces https://github.com/dotnet/coreclr/pull/8012 (I couldn't reopen after I rebased onto dotnet/master).

FYI. @danmosemsft, this should pass now. I just needed to retarget the Math/Functions project from `.NETStandard,Version=1.4` to `.NETCoreApp,Version=1.1` and I needed to drop the benchmark project.json override.

**Comment by tannergooding** [comment]
Now they should pass (see sample log below). The additional two commits do the following:
* Updates the tests to print the expected and actual result with appropriate precision (9 digits for single, 17 digits for double) when tests fail
* Updates the single precision tests to have the correct expected result. Initial values were just straight ported from the double precision tests and cut back to 9 digits of precision. These initial values were not accurate due to loss of precision over the 5000 iterations that occur in the inner loop.

```
Running absdouble test...
  Warming up...
    Total Time: 0.0049748
  Executing 1 iterations...
    Total Time: 0.0015359 seconds
    Average Time: 0.0015359 seconds
Running abssingle test...
  Warming up...
    Total Time: 0.0039861
  Executing 1 iterations...
    Total Time: 0.0016183 seconds
    Average Time: 0.0016183 seconds
Running acosdouble test...
  Warming up...
    Total Time: 0.0046479
  Executing 1 iterations...
    Total Time: 0.0018227 seconds
    Average Time: 0.0018227 seconds
Running acossingle test...
  Warming up...
    Total Time: 0.0043521
  Executing 1 iterations...
    Total Time: 0.0018746 seconds
    Average Time: 0.0018746 seconds
Running asindouble test...
  Warming up...
    Total Time: 0.0043872
  Executing 1 iterations...
    Total Time: 0.0017134 seconds
    Average Time: 0.0017134 seconds
Running asinsingle test...
  Warming up...
    Total Time: 0.0036376
  Executing 1 iterations...
    Total Time: 0.0015619 seconds
    Average Time: 0.0015619 seconds
Running atandouble test...
  Warming up...
    Total Time: 0.0039094
  Executing 1 iterations...
    Total Time: 0.0018966 seconds
    Average Time: 0.0018966 seconds
Running atansingle test...
  Warming up...
    Total Time: 0.0037516
  Executing 1 iterations...
    Total Time: 0.0015992 seconds
    Average Time: 0.0015992 seconds
Running atan2double test...
  Warming up...
    Total Time: 0.004315
  Executing 1 iterations...
    Total Time: 0.0018239 seconds
    Average Time: 0.0018239 seconds
Running atan2single test...
  Warming up...
    Total Time: 0.0041613
  Executing 1 iterations...
    Total Time: 0.0018053 seconds
    Average Time: 0.0018053 seconds
Running ceilingdouble test...
  Warming up...
    Total Time: 0.0036829
  Executing 1 iterations...
    Total Time: 0.0014785 seconds
    Average Time: 0.0014785 seconds
Running ceilingsingle test...
  Warming up...
    Total Time: 0.0038422
  Executing 1 iterations...
    Total Time: 0.0013956 seconds
    Average Time: 0.0013956 seconds
Running cosdouble test...
  Warming up...
    Total Time: 0.0038004
  Executing 1 iterations...
    Total Time: 0.0015128 seconds
    Average Time: 0.0015128 seconds
Running cossingle test...
  Warming up...
    Total Time: 0.0036717
  Executing 1 iterations...
    Total Time: 0.0014262 seconds
    Average Time: 0.0014262 seconds
Running coshdouble test...
  Warming up...
    Total Time: 0.0039785
  Executing 1 iterations...
    Total Time: 0.0018858 seconds
    Average Time: 0.0018858 seconds
Running coshsingle test...
  Warming up...
    Total Time: 0.0036041
  Executing 1 iterations...
    Total Time: 0.0016201 seconds
    Average Time: 0.0016201 seconds
Running expdouble test...
  Warming up...
    Total Time: 0.0038334
  Executing 1 iterations...
    Total Time: 0.0015691 seconds
    Average Time: 0.0015691 seconds
Running expsingle test...
  Warming up...
    Total Time: 0.0036742
  Executing 1 iterations...
    Total Time: 0.001458 seconds
    Average Time: 0.001458 seconds
Running floordouble test...
  Warming up...
    Total Time: 0.0042954
  Executing 1 iterations...
    Total Time: 0.0014802 seconds
    Average Time: 0.0014802 seconds
Running floorsingle test...
  Warming up...
    Total Time: 0.0035456
  Executing 1 iterations...
    Total Time: 0.0014395 seconds
    Average Time: 0.0014395 seconds
Running logdouble test...
  Warming up...
    Total Time: 0.0036202
  Executing 1 iterations...
    Total Time: 0.001522 seconds
    Average Time: 0.001522 seconds
Running logsingle test...
  Warming up...
    Total Time: 0.0039698
  Executing 1 iterations...
    Total Time: 0.0015817 seconds
    Average Time: 0.0015817 seconds
Running log10double test...
  Warming up...
    Total Time: 0.0036873
  Executing 1 iterations...
    Total Time: 0.0014808 seconds
    Average Time: 0.0014808 seconds
Running log10single test...
  Warming up...
    Total Time: 0.0036985
  Executing 1 iterations...
    Total Time: 0.0015538 seconds
    Average Time: 0.0015538 seconds
Running powdouble test...
  Warming up...
    Total Time: 0.0040948
  Executing 1 iterations...
    Total Time: 0.0017809 seconds
    Average Time: 0.0017809 seconds
Running powsingle test...
  Warming up...
    Total Time: 0.0037173
  Executing 1 iterations...
    Total Time: 0.0016916 seconds
    Average Time: 0.0016916 seconds
Running rounddouble test...
  Warming up...
    Total Time: 0.003773
  Executing 1 iterations...
    Total Time: 0.0015676 seconds
    Average Time: 0.0015676 seconds
Running roundsingle test...
  Warming up...
    Total Time: 0.0038139
  Executing 1 iterations...
    Total Time: 0.0014821 seconds
    Average Time: 0.0014821 seconds
Running sindouble test...
  Warming up...
    Total Time: 0.0039822
  Executing 1 iterations...
    Total Time: 0.0014703 seconds
    Average Time: 0.0014703 seconds
Running sinsingle test...
  Warming up...
    Total Time: 0.0035311
  Executing 1 iterations...
    Total Time: 0.0014413 seconds
    Average Time: 0.0014413 seconds
Running sinhdouble test...
  Warming up...
    Total Time: 0.0039207
  Executing 1 iterations...
    Total Time: 0.001933 seconds
    Average Time: 0.001933 seconds
Running sinhsingle test...
  Warming up...
    Total Time: 0.0036364
  Executing 1 iterations...
    Total Time: 0.0015984 seconds
    Average Time: 0.0015984 seconds
Running sqrtdouble test...
  Warming up...
    Total Time: 0.0038034
  Executing 1 iterations...
    Total Time: 0.0014649 seconds
    Average Time: 0.0014649 seconds
Running sqrtsingle test...
  Warming up...
    Total Time: 0.0039848
  Executing 1 iterations...
    Total Time: 0.001409 seconds
    Average Time: 0.001409 seconds
Running tandouble test...
  Warming up...
    Total Time: 0.0036974
  Executing 1 iterations...
    Total Time: 0.0015209 seconds
    Average Time: 0.0015209 seconds
Running tansingle test...
  Warming up...
    Total Time: 0.0036312
  Executing 1 iterations...
    Total Time: 0.0017673 seconds
    Average Time: 0.0017673 seconds
Running tanhdouble test...
  Warming up...
    Total Time: 0.0038927
  Executing 1 iterations...
    Total Time: 0.0015925 seconds
    Average Time: 0.0015925 seconds
Running tanhsingle test...
  Warming up...
    Total Time: 0.0037168
  Executing 1 iterations...
    Total Time: 0.001724 seconds
    Average Time: 0.001724 seconds
Expected: 100
Actual: 100
END EXECUTION - PASSED
PASSED
```

**Comment by tannergooding** [comment]
Looks like the checked build has an actual failure, investigating:
```
Assert failure(PID 58004 [0x0000e294], Thread: 58004 [0xe294]): Assertion failed 'treeNode->TypeGet() == TYP_DOUBLE' in 'Functions.MathTests:SqrtSingleTest()' (IL size 99)
File: /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu_prtest/src/jit/codegenxarch.cpp Line: 7362
```

**Comment by tannergooding** [comment]
The assert was because `codegenxarch` asserted that `CORINFO_INTRINSIC_Sqrt` could only ever by `TYP_DOUBLE`. I have updated it to properly handle `TYP_FLOAT` and to use the `sqrtss` instruction.

**Comment by tannergooding** [comment]
Debug, Checked, and Release are all passing locally now. Hopefully they pass in the Jenkins runs as well :smile:

**Comment by tannergooding** [comment]
The Windows x86 CRT implementation for `atan2` seems to produce slightly different results from the other platforms.

Specifically, it calculates `3924.2312f` while the other platforms and x64 Windows calculates `3930.14282f`.

I validated that this matches the behavior of calling the `atan2` function directly from C/C++, so this is not an issue with the runtime, but rather with the native method implementation.

I have updated the test to expect the different value for x86 Windows only.

**Comment by am11** [comment]
ChakraCore team has hardcoded assembly when SSE2 is available on x86 https://github.com/Microsoft/ChakraCore/pull/593/files.
Also, this seems to be related: https://social.msdn.microsoft.com/Forums/en-US/37504f44-e28d-4a35-9f3d-c8ff5ddd3029.

**Comment by tannergooding** [comment]
Ok, so this is runtime after all. It seems we end up calling `_CIatan2 = {coreclr.dll!_CIatan2(void)}`. This in turn ends up calling `d:\th\minkernel\crts\ucrt\src\appcrt\tran\i386\87ctriga.asm`, which uses a lookup table and the x87 FPU for computations.

I am still trying to determine what is causing us to call that implementation rather than the SSE2 implementation.

**Comment by tannergooding** [comment]
FYI. @DrewScoggins  and @john-soklaski who moved the benchmarks away from .netcoreapp back in October here: https://github.com/dotnet/coreclr/commit/ef60f7921285baef7257b79fa79443ff15205d57

As context, this only moves the Math tests back to netcoreapp1.1, which is required to get perf numbers over the System.MathF functions.

**Comment by DrewScoggins** [comment]
test Windows_NT_x64 perf

**Comment by DrewScoggins** [comment]
I just started a perf run in our lab to confirm, but I believe that this will break our runs for these tests.

We use a runner that runs on the Desktop framework, and all though this eventually invokes corerun to actually run the tests we do all of the test discovery in the Desktop runner.  As a result of this tests that are built against things higher than netstandard1.4 fail because we are unable to locate System.Object as we started type-forwarding those type to System.Private.Corelib instead of mscorlib.  We have been planning to do this work, and in fact we have hit another issue with it [here](https://github.com/dotnet/coreclr/issues/9314#event-948631017).

**Comment by tannergooding** [comment]
@DrewScoggins, so, I would need to add the Math/Functions tests to the ExcludeList and update the work item (9314) that tracks enabling them once netcoreapp is supported, correct?

**Comment by tannergooding** [comment]
It looks like it is currently failing due to a lack of Python on the machine.

**Comment by DrewScoggins** [comment]
Yeah, I had just added a new machine and I had installed the wrong version of Python.  I have fixed that now and it is in the middle of building.

As for mitigation just adding them to the exclude list will not work.  That list is just for excluding tests that get run in Helix as part of functional test runs, not performance runs.  We currently do not have any way that, I am aware of, to turn-off certain tests in a performance run.

Given this I think that we should wait on checking this in until we have finished the work to update the runner in CoreCLR.  It seems incorrect to make this check-in and break all of our current Math tests in the lab.

**Comment by tannergooding** [comment]
@DrewScoggins, it actually appears to have passed.

**Comment by DrewScoggins** [comment]
Yea the run did finish and it says pass, but if you look at the log you will see that the Functions test failed.

**Comment by tannergooding** [comment]
Alright.

Is there an ETA on when Helix will support CoreCLR or when it will support skipping specific performance tests?

If the latter were possible, I could move the single precision functions into their own library (double-precision in Math\Functions and single-precision in MathF\Functions respectively). Then we could just skip MathF\Functions and not need to worry about blocking the Math tests.

**Comment by DrewScoggins** [comment]
So it can already skip tests.  The problem is that making this change will stop the performance runs that we have in Jenkins.  So the blocking bit is moving the CoreCLR Jenkins runs to use a core version of the performance runner, rather than the Desktop version.  We do not currently have an exact ETA, but I expect to finish it this month.

**Comment by tannergooding** [comment]
Any update here? It would be great to get the System.MathF perf tests merged

**Comment by DrewScoggins** [comment]
I am actively working on moving us over to the new harness.  I should have an ETA by tomorrow.

**Comment by DrewScoggins** [comment]
Here is the (PR)[https://github.com/dotnet/coreclr/pull/9947].  We will need to make sure that this harness change does not perturb the numbers, but if that looks good we should be able to merge it relativily quickly.

**Comment by tannergooding** [comment]
So this:
> The Windows x86 CRT implementation for atan2 seems to produce slightly different results from the other platforms.
>
>Specifically, it calculates 3924.2312f while the other platforms and x64 Windows calculates 3930.14282f.

Ended up being caused by this: https://github.com/dotnet/coreclr/issues/9954. We iterate over the range of -1.0 to 1.0 for both x and y, but in reverse order (Y starts at -1.0 and increases forwards to 1.0, while X starts at 1.0 and decreases backwards to -1.0). Additionally, we increment before the first computation, so the first call should have been `Atan2(-0.9996, 0.9996)` (`-0.785398163`) and the last computation should have been `Atan2(1.0, -1.0)` (`2.35619449`). However, given that the x/y arguments were swapped we had a larger initial starting value (2.3 rather than -0.78) which actually makes all the difference over 4999 iterations, as the minor discrepancies in the results add up entirely differently 😄

**Comment by danmosemsft** [comment]
@tannergooding who owns the next step here?

**Comment by tannergooding** [comment]
@danmosemsft, waiting on @DrewScoggins to finish up the Perf infrastructure work: https://github.com/dotnet/coreclr/pull/9947

Without it, this change would break the running of the System.Math Perf tests.

**Comment by tannergooding** [comment]
test Windows_NT_x64 perf

**Comment by tannergooding** [comment]
@DrewScoggins, I believe you mentioned something about the Ubuntu perf jobs as well. Does that still need to be handled before this can be merged?

**Comment by tannergooding** [comment]
test Windows_NT x64 perf

**Comment by tannergooding** [comment]
test Ubuntu14.04 perf

**Comment by DrewScoggins** [comment]
Yes, we still need to make the changes on Ubuntu.  I have the work done, but we had to update one of the packages that we were using as it was P/Invoking into a Windows API.  My guess is I should be able to push the change today.

**Comment by danmosemsft** [comment]
@tannergooding I believe @DrewScoggins is on vacation .. did you get what you needed so we can merge this?

**Comment by tannergooding** [comment]
Not quite. Linux per tests will still be broken by the merge.

**Comment by tannergooding** [comment]
test Ubuntu14.04 perf

**Comment by tannergooding** [comment]
Rebased onto dotnet/master

test Windows_NT x64 perf
test Ubuntu14.04 perf

**Comment by danmosemsft** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test  (network)

**Comment by tannergooding** [comment]
Ubuntu per job is still silently failing. So this will need to continue waiting until @DrewScoggins gets the corresponding fix in.

**Comment by DrewScoggins** [comment]
I will take a look at this today.  I am trying to remember where we were at for moving the Linux runs to the new harness, but I believe that we are close.  I will update this PR when I know later today.

**Comment by danmosemsft** [comment]
@DrewScoggins ?

**Comment by DrewScoggins** [comment]
I did look at this, but the work here as been subsumed by higher priority benchmark stabilization work.  I should be able to actually get a fix for this done this week though.

**Comment by tannergooding** [comment]
Rebased onto current head of dotnet/master

**Comment by tannergooding** [comment]
Rebased onto current head of dotnet/master

**Comment by tannergooding** [comment]
@DrewScoggins, has there been any update here?

**Comment by DrewScoggins** [comment]
Yeah, sorry.  I have been pulled over to working on stress for a while and this fell off of my radar.  We can go ahead and merge this.

**Comment by tannergooding** [comment]
Awesome. Thanks!

**Pull request merged**
