### PR TITLE
Fix typo in Buffer.BlockCopy

### PR DESCRIPTION
**Pull request by EgorBo**
Once it's merged this test needs to be fixed as well: https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/BufferTests.cs#L34
(line 34 expects ParamName="dst", [line 41](https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/BufferTests.cs#L41) expects ParamName="dest").

### CODE REVIEW

**Comment by jkotas** [comment]
Could you please disable the failing tests in https://github.com/dotnet/coreclr/blob/master/tests/CoreFX/CoreFX.issues.json

**Comment by jkotas** [comment]
@dotnet-bot test Windows_NT x64 Checked CoreFX Tests  please

**Comment by jkotas** [comment]
cc @stephentoub https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/BufferTests.cs#L34 will need adjustment once this hits corefx.

**Comment by stephentoub** [comment]
Thanks.

**Pull request merged**
