### PR TITLE
Make Delegate BeginInvoke/EndInvoke throw PlatformNotSupportedException

### PR DESCRIPTION
**Pull request by adityamandaleeka**
Make BeginInvoke/EndInvoke throw PlatformNotSupportedException instead of NotSupportedException.

Addresses #3811. 

cc: @KrzysztofCwalina @stephentoub @jkotas

### CODE REVIEW

**Comment by stephentoub** [comment]
You might undo the whitespace changes, but otherwise LGTM. Do we have any tests for this?

**Comment by jkotas** [comment]
LGTM

**Comment by adityamandaleeka** [comment]
@dotnet-bot test this please

**Comment by adityamandaleeka** [comment]
@dotnet-bot test this please

**Comment by adityamandaleeka** [comment]
@stephentoub I don't think there are any tests for this. As far as I can tell, all the occurrences of Begin/EndInvoke were removed as tests were open sourced. If it's valuable to ensure that PlatformNotSupportedException is thrown when these methods are called, I can add a test for that.

I'll leave the whitespace changes as they are. I intentionally did those since I was touching the method anyway.

**Comment by adityamandaleeka** [comment]
I just pushed another commit adding a test for this. It fails before my change and passes with it.

**Comment by adityamandaleeka** [comment]
The OS X CI failure is unrelated to this change. Merging.

**Pull request merged**
