### PR TITLE
Adding perf tests for the single precision math functions in System.MathF.

### PR DESCRIPTION
**Pull request by tannergooding**

### CODE REVIEW

**Comment by tannergooding** [comment]
Looks like this is failing because `System.MathF` is only in `netcoreapp11`. I'll take another look here tomorrow or Sunday if I get a chance.

**Comment by danmosemsft** [comment]
@tannergooding have you had a chance to take another look?

**Comment by tannergooding** [comment]
Not yet. I have been busy with other feature work. I understand the problem (the new APIs only exist in netcoreapp, so we need to ensure we compile/run against that TFM for some subset of tests), I just haven't been able to look into getting a fix yet.

**Comment by tannergooding** [comment]
@danmosemsft, I have some time to look at this again. What is the recommended way to run the perf tests from PR (it seems they are disabled by default now)?

**Comment by danmosemsft** [comment]
I do not know. @dotnet/jit-contrib

**Comment by tannergooding** [comment]
test this please

**Comment by tannergooding** [comment]
Actually, based on the job that reran and failed this time, it looks like they may be running again.

**Comment by danmosemsft** [comment]
@dotnet-bot test this (logs gone..)

**Comment by danmosemsft** [comment]
@tannergooding got time to finish so we can close this one out?

**Comment by tannergooding** [comment]
@danmosemsft, sorry, got pulled off onto other work over the holidays.

Do you know if we have any other locations where perf tests call netcore exclusive APIs?

That is essentially the only blocker currently. The new MathF apis are netcore exclusive and need to be sectioned off and run separately.

**Comment by danmosemsft** [comment]
@tannergooding I don't know -- I haven't worked with the perf tests.

**Comment by danmosemsft** [comment]
I'm not sure who to ask that of - maybe @brianrob to start with.

**Comment by danmosemsft** [comment]
@tannergooding do you want to close this PR as it's so old now? We try to not let them pile up.

**Comment by tannergooding** [comment]
Closing for the time being. The tests, as is, are still valid, I just need to know how to run netcore exclusive APIs for perf testing.

**Pull request closed without merging**
