### PR TITLE
Add Regression/VS-ia64-JIT test cases for JIT.

### PR DESCRIPTION
**Pull request by libengu**
Add Regression/VS-ia64-JIT test cases for JIT. Related proj, config files added.
AllTestProjects.sln update delayed for a batch adding. Passed build, buildtest, runtest.

### CODE REVIEW

**Comment by libengu** [comment]
@pgavlin PTAL

**Comment by pgavlin** [comment]
LGTM. Is there a corresponding PR for the LLILC exclusions?

**Comment by kangaroo** [comment]
Is there an answer to @pgavlin's question?

**Comment by pgavlin** [comment]
Yes; https://github.com/dotnet/llilc/issues/602

**Comment by libengu** [comment]
@kangaroo The reference line above answered the question. Please let me know if such a reference line is easy to ignore then I will answer directly next time.

**Comment by richlander** [comment]
@libengu Being explicit is good practice. Not trying to make a _thing_ of it, but it's a bit rude to answer an explicit question with an implicit gesture. No harm, no fowl. Just sharing my viewpoint.

**Comment by libengu** [comment]
@ Sure.  I will follow the good practice. Thanks for making it clear.

**Pull request merged**
