### PR TITLE
Convert Array.IsPrimitiveTypeArray to C#

### PR DESCRIPTION
**Pull request by EgorBo**
Another baby steps towards https://github.com/dotnet/coreclr/issues/18111 (along with https://github.com/dotnet/coreclr/pull/27216)

Ported line by line C++ to C# for these structs (missing some debug asserts, `#if FEATURE_PREJIT` parts and I don't know to to set `g_pEnumClass` global in order to test if a type is an enum, also I am not sure in the pointer arithmetic e.g. when I do `addr -2`).

@jkotas I was just learning CoreCLR internals, let me know if it worth continuing or feel free to take over.

But it already works for me, e.g. I can obtain a correct `CorElementType` for any Array I tried.

### CODE REVIEW

**Comment by jkotas** [comment]
Does this change make any measurable performance difference?

If we start duplicating the VM code in C# just because we can, it will tun into maintenance nightmare. For now, I would prefer to keep this duplication at minimum and do as needed only if there is a measurable benefit.

**Comment by jkotas** [comment]
> I don't know to to set g_pEnumClass global in order to test 

I do not think we want to keep these in a global. Ideally, This should just be `typeof(Enum).MethodTable` or something like that. It is what we do in CoreRT.

**Comment by jkotas** [comment]
> `#if FEATURE_PREJIT` parts

Yep, these would need to be much more complex, otherwise this will break Samsung folks who stilll use fragile NGen.

**Comment by EgorBo** [comment]
@jkotas ok, makes sense, will wait for CI test results just to make sure it works 
PS: Also, could re-use this code for `Enum.InternalGetCorElementType` internal call.
But yeah don't want to break anyone or increase maintenance costs.

**Pull request closed without merging**
