### PR TITLE
Update setup-runtime-dependencies.cmd to specify runtime explicitly

### PR DESCRIPTION
**Pull request by sejongoh**

### CODE REVIEW

**Comment by sejongoh** [comment]
@dotnet-bot test Windows_NT gcstress0xc

**Comment by sejongoh** [comment]
@dotnet-bot test Windows_NT gcstress0xc

**Comment by sejongoh** [comment]
@dotnet-bot test Windows_NT gcstress0xc

**Comment by sejongoh** [comment]
@dotnet-bot test Windows_NT gcstress0xc

**Comment by sejongoh** [comment]
@swaroop-sridhar PTAL

**Comment by swaroop-sridhar** [comment]
Green, thanks for the fix.

**Pull request merged**
