### PR TITLE
Fix an AV in crossgen caused by invalid profiling data

### PR DESCRIPTION
**Pull request by fadimounir**
Fixes https://github.com/dotnet/coreclr/issues/27780 and unblocks repo consolidation work

### CODE REVIEW

**Comment by fadimounir** [comment]
@jkotas PTAL

**Comment by jkoritzinsky** [comment]
The test `tracing/eventpipe/providervalidation/providervalidation/providervalidation.sh` timed out on Linux arm.

Re-running the test leg to try to get this to green.

**Comment by jashook** [comment]
@josalem

**Comment by fadimounir** [comment]
I think we can merge at this point. I don't think the failure on arm is related.

**Comment by josalem** [comment]
@MattGal In that failing test, there was an artifact saved to `HELIX_WORKITEM_UPLOAD_ROOT`.  How do I go about getting that artifact now?

```log
  3.3s: [Error] Attempted to read 16392 bytes into a buffer of length 16392 at offset 8
  3.3s: Exception thrown while reading; dumping culprit stream to disk...
  3.3s:  HELIX_WORKITEM_UPLOAD_ROOT = /root/helix/work/workitem/uploads
  3.4s:  Writing stream to /root/helix/work/workitem/uploads/streamdump.nettrace
```

**Pull request merged**
