### PR TITLE
Fix for CoreRT issue https://github.com/dotnet/corert/issues/3672 (armel tizen)

### PR DESCRIPTION
**Pull request by sergign60**

### CODE REVIEW

**Comment by sergign60** [comment]
@dotnet-bot test this

**Comment by sergign60** [comment]
@dotnet-bot test Tizen armel Cross Release Build

**Comment by sergign60** [comment]
@dotnet-bot test this please

**Comment by sergign60** [comment]
https://github.com/dotnet/corert/issues/3672

**Comment by sergign60** [comment]
CC: @jkotas @Dmitri-Botcharnikov @BredPet @mskvortsov

**Comment by sergign60** [comment]
@dotnet-bot test this please

**Comment by sergign60** [comment]
@dotnet-bot test Ubuntu arm Cross Release Build

**Comment by jkotas** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test please

**Pull request merged**
