### PR TITLE
Revert "Revert "Remove useless security checks""

### PR DESCRIPTION
**Pull request by vancem**
This reverts commit a5e803cf70d861022f3b6cddb9045edb8a222e78.
Remove more calls to PerformSecurityCheck.  

@jkotas @stephentoub 

This was originally checked in as #3027 but then reverted by #3063 because of a Ubuntu failure.  

Issue #3064 is tracking putting this back and this this pull request is trying to do that.

In #3063 the failure gave the following output:

03:21:48 Type: System.Diagnostics.Tests.ProcessTestBase+<>c
 03:21:48 Method: Int32 b__7_0()
 03:21:48 Exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
 03:21:48 at System.RuntimeMethodHandle.PerformSecurityCheck(Object obj, IRuntimeMethodInfo method, RuntimeType parent, UInt32 invocationFlags)
 03:21:48 at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
 03:21:48 at RemoteExecutorConsoleApp.Program.Main(String[] args)

Now interestingly the original OutOfMemory failure seems to come out of the PerformSecurityCheck method which after the change shoudl have been EMPTY.   This suggests that there is something more 'magical' going on and this method just happens to be the point where it happens.

It turns out that  there are only a small number of calls to the empty PerformSecurityCheck function, and in fact removing the calls actually made the #ifdefs simpler, so that is what this change does.

Note that I have not root caused the original failure.   However clearly it can't repro in the same way because the method on the stack above does not event exist.

We should certainly retry the test.  If it does not get run as part of normal pull request validation I will need instructions on doing that run.

### CODE REVIEW

**Comment by jkotas** [comment]
@dotnet-bot test corefx_baseline

**Comment by jkotas** [comment]
@dotnet-bot test Ubuntu x64 Checked corefx_baseline

**Comment by sejongoh** [comment]
@dotnet-bot test Ubuntu corefx_baseline

**Comment by sejongoh** [comment]
@dotnet-bot test Ubuntu corefx_baseline

**Comment by stephentoub** [comment]
@dotnet-bot test Ubuntu corefx_baseline

**Comment by sejongoh** [comment]
@dotnet-bot test Ubuntu corefx_baseline

**Comment by sejongoh** [comment]
@dotnet-bot test Ubuntu corefx_baseline_manual

**Comment by sejongoh** [comment]
@dotnet-bot test Ubuntu corefx_baseline_manual

**Comment by sejongoh** [comment]
@dotnet-bot test Ubuntu corefx_baseline_manual

**Comment by sejongoh** [comment]
@dotnet-bot test Ubuntu corefx_baseline_manual

**Comment by jkotas** [comment]
@dotnet-bot test Ubuntu corefx_baseline_manual

**Comment by jkotas** [comment]
@dotnet-bot test Ubuntu corefx_baseline

**Comment by sejongoh** [comment]
I realized that corefx_baseline and corefx_baseline_manual build checked corefx today and just changed them. I am wondering if checked build is okay for this PR.

Also a PR is opened to switch to release build: https://github.com/dotnet/coreclr/pull/3259.

**Comment by stephentoub** [comment]
It looks like an old System.Console.dll is being used somehow with a much newer System.Native.so, causing this mismatch:
```
14:19:55 Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.Build.CommandLine.MSBuildApp' threw an exception. ---> System.EntryPointNotFoundException: Unable to find an entry point named 'Dup' in DLL 'System.Native'.
14:19:55    at Interop.Sys.Dup(Int32 oldfd)
14:19:55    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(Func`1 fdFunc)
14:19:55    at System.ConsolePal.OpenStandardOutput()
14:19:55    at System.Console.<>c.<get_Out>b__13_0()
14:19:55    at System.Console.EnsureInitialized[T](T& field, Func`1 initializer)
14:19:55    at System.Console.WriteLine(String value)
14:19:55    at Microsoft.Build.CommandLine.MSBuildApp.HandleConfigurationException(Exception ex)
14:19:55    at Microsoft.Build.CommandLine.MSBuildApp..cctor()
14:19:55    --- End of inner exception stack trace ---
14:19:55    at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)
```

**Comment by jkotas** [comment]
I am running the tests locally - the failures in the CI results above (http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x64_release_ubuntu_corefx_baseline_prtest_manual/11/) are actually valid:

**Comment by jkotas** [comment]
DynamicMethodctor*.NegTest* tests are verifying that there is argument exception thrown when null module gets passed into dynamic method. This is no longer happening because of the argument validation in dynamicmethod.cs is ifdefed out - perhaps the ifdef should be moved to be after the argument validation.

**Comment by jkotas** [comment]
(I have used instructions from https://github.com/dotnet/coreclr/blob/master/Documentation/building/testing-with-corefx.md to run the corefx tests.)

**Comment by vancem** [comment]
I have updated the code to avoid commenting out the parameter checking.

**Comment by stephentoub** [comment]
@dotnet-bot test Ubuntu corefx_baseline

**Comment by stephentoub** [comment]
@dotnet-bot test Ubuntu corefx_baseline_manual

**Comment by stephentoub** [comment]
@sejongoh, what's the magic incantation needed here to kick off another leg of corefx testing?

**Comment by jkotas** [comment]
I have rerun the corefx tests on this one locally - it looks good to go.

**Pull request merged**
