### PR TITLE
Explicitly load libcoreclrpal in corerun

### LINKED ISSUE #709: Fix or document the requirement for LD_LIBRARY_PATH to be set to the runtime path
After the change to move PAL to a separate module (libcoreclrpal.so) is causing the following problem. A workaround for now is to set the LD_LIBRARY_PATH environment variable to the runtime binaries (where corerun/lib* are). The reason we didn’t hit this problem is because LD_LIBRARY_PATH is required to use the lldb sos plugin and debugger binaries.  

We need to look at removing the environment variable requirement by looking for libraries in corerun's directory or document this new requirement.

./corerun HelloWorld.exe linux
dlopen failed to open the libcoreclr.so with error libcoreclrpal.so: cannot open shared object file: No such file or directory

### PR DESCRIPTION
**Pull request by ellismg**
libcoreclr has a dependency on libcoreclrpal, but libcoreclrpal is
usually not on the path the loader probes, since it is SxS with the
runtime itself.

Instead of forcing LD_LIBRARY_PATH to be set just have corerun load the
PAL from the same folder as the runtime before loading libcoreclr.

Fixes #709

### CODE REVIEW

**Comment by ellismg** [comment]
@janvorli @mikem8361 PTAL

**Comment by pgavlin** [comment]
LGTM.

**Comment by janvorli** [comment]
LGTM, I'm glad it worked this way.

**Comment by kangaroo** [comment]
:+1: LGTM.  Relying on *_LIBRARY_PATH would have been horrible.

**Comment by mikem8361** [comment]
LGTM. Thanks.

**Comment by ellismg** [comment]
@kangaroo Playing around with this more today, it seems like while the fix works for Linux, it doesn't work for OSX.  OSX will pick up the PAL if the CWD contains it, otherwise even pre-loading it doesnt' seem to work.

Reading the [dyld(1) man page](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/dyld.1.html), it would appear that we might want to use something like `@loader_path/` to solve all our problems.

I tried using install_name_tool to update the dynamic library name like this:

```
install_name_tool -change 'libcoreclrpal.dylib' '@loader_path/libcoreclrpal.dylib' ~/coreclr-demo/runtime/libcoreclr.dylib
```

And after that I was able to have things work even if I didn't launch corerun from the directory it lived in.

Is the right way to handle this to just call install_name_tool via cmake during the build when targeting OSX?  Is there some better thing to be doing here?

**Comment by kangaroo** [comment]
@ellismg set_target_properties(bar PROPERTIES INSTALL_RPATH "@loader_path/../lib")  (or the appropriate variant thereof) should work.

**Pull request merged**
