### PR TITLE
[x86/Linux] Fix all paths through this function will call itself

### PR DESCRIPTION
**Pull request by seanshpark**
Fix compile error for x86/Linux
- disable "infinite-recursion" for "recursiveFtn" function
- only for clang

### CODE REVIEW

**Comment by seanshpark** [comment]
cc @parjong

**Comment by seanshpark** [comment]
@jkotas , @janvorli , PTAL

**Comment by jkotas** [comment]
This looks fine to make progress on the port; but we may end up ditching this whole file and replacing it with solution based on libunwind, similar to what is done for amd64.

**Comment by seanshpark** [comment]
> we may end up ditching this whole file and replacing it with solution based on libunwind

Thank you :)

**Pull request merged**
