### PR TITLE
[WIP] [Test] Enable USE_UPPER_ADDRESS on Unix

### PR DESCRIPTION
**Pull request by briansull**
This will allow 32-bit PC-rel for class static variables

### CODE REVIEW

**Comment by briansull** [comment]
@AndyAyersMS  Issue #12809 
This change is passing UNIX testing and should enable PC-REL32 class static vars
You can try it out locally.

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64 Checked
@dotnet-bot test Ubuntu arm64 Cross Debug Build please

**Comment by briansull** [comment]
@dotnet-bot test CentOS7.1 Checked r2r
@dotnet-bot test CentOS7.1 Release r2r

**Comment by jkotas** [comment]
This is reverting change done for https://github.com/dotnet/coreclr/pull/2205. I doubt that it is going to work...

**Comment by karelz** [comment]
What is status of this PR? No update for last month :( ...

**Comment by karelz** [comment]
(accidentally closed it, sorry)

**Comment by briansull** [comment]
Closing this for now

**Pull request closed without merging**
