### PR TITLE
System.Private.CoreLib: Move ResoureReader/ResourceSet to shared.

### PR DESCRIPTION
**Pull request by filipnavara**
The implementation in CoreRT and CoreClr for these two classes are nearly identical. The differences should not be significant and are more of a code cleanup artifacts.

### CODE REVIEW

**Comment by jkotas** [comment]
Could you please check that the shared copy is going to be build in CoreRT?

**Comment by jkotas** [comment]
Contributes to #17901

**Comment by filipnavara** [comment]
Builds just fine in both CoreCLR and CoreRT now. The Ubuntu CI failures are due to the machine running out of disk space.

**Comment by jkotas** [comment]
@Anipik The mirror is not picking this one up. Could you please take a look?

**Comment by Anipik** [comment]
Done :)

**Comment by karelz** [comment]
@dotnet/dncenghot seems like Ubuntu machine(s) ran out of disk space:
* https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_no_tiered_compilation_innerloop_flow_prtest/1853/
    * _Disk has run out of space and cannot get latest changes. Please contact netciadmin@microsoft.com. IOException: No space left on device_
* https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_ubuntu_formatting_prtest/22421/
    * _Disk has run out of space and cannot get latest changes. Please contact netciadmin@microsoft.com. IOException: No space left on device_

Thanks @filipnavara for raising it up on gitter

**Comment by karelz** [comment]
BTW: It seems that the email alias in the error message (netciadmin) is no longer valid ...

**Comment by jkotas** [comment]
> Ubuntu machine(s) ran out of disk space:

This has been affecting many CoreCLR jobs. #19982 is the tracking issue.

**Comment by Chrisboh** [comment]
Yeah a lot of people have been reporting space issues building CoreCLR on Ubuntu.  So far it appears that only CoreCLR is effected and I have @jonfortescue investigating and tracking the issue with https://github.com/dotnet/core-eng/issues/4203.

**Pull request merged**
