### PR TITLE
Update buildtools version to 00198

### PR DESCRIPTION
**Pull request by rahku**

### CODE REVIEW

**Comment by gkhanna79** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by gkhanna79** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by rahku** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by rahku** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by rahku** [comment]
OSX x64 Checked Build and Test is failing for other PR's as well. So it does not seem related to this PR.

**Pull request merged**
