### PR TITLE
find ./ -type f -exec sed -i -e 's/\<gtNextStmt\>/GetNextStmt()/g' {} \;

### PR DESCRIPTION
**Pull request by franksinankaya**
@am11 @jkotas @janvorli @dotnet/jit-contrib

### CODE REVIEW

**Comment by franksinankaya** [comment]
cc @dotnet/jit-contrib

**Comment by am11** [comment]
probably it is also one step towards removing `-Wno-*microsoft*`, `-Wno-*ms*`, `-fms-extensions` etc. from cmake configs. :)

**Comment by mikedn** [comment]
cc @sandreenko Since he's working on statements :)

**Comment by franksinankaya** [comment]
Please help review and merge these small changes.

**Pull request merged**
