### PR TITLE
[WIP] Remove tailcall limitations on unix64 and arm64

### PR DESCRIPTION
**Pull request by jakobbotsch**

### CODE REVIEW

**Comment by jakobbotsch** [comment]
The basic problem is the following: `PUTARG_STK` will write values into the arg space area which, for fast tail calls, is the area of the incoming args. A `PUTARG_STK` may therefore end up overwrite (parts of) an argument that is used later in the call sequence. On Windows the ABI allows us to know that, if we are doing a `PUTARG_STK` for argument at index `i`, then this will overwrite the `i`th argument to the caller. Thus it is easy to introduce a temp for the `i`th arg if it is used later than the `PUTARG_STK`.

On Unix this assumption about the ABI does not hold. The argument position does not tell us anything about where the argument will go on the stack; for instance, `void foo(S32 a, int b)` and `void foo(int b, S32 a)` will both have `a` in the first 4 stack slots and `b` in a register.

This PR fixes this in a simple way: just introduce temps for any stack arg with uses before tailcalls. The harder way is to figure out if they are read after they would be overwritten by a `PUTARG_STK` and only introduce a temp in that situation. This is what the previous Windows implementation did based on the argument position.

Generally this might introduce copies in cases where there previously would have been none. However since we now allow tailcalls in more situations, this still turns out to be a net win space wise on unix64 (following is PMI over frameworks):
```
Found 38 files with textual diffs.

Summary:
(Lower is better)

Total bytes of diff: -296 (-0.001% of base)
    diff is an improvement.

Top file regressions by size (bytes):
        1547 : System.Linq.Parallel.dasm (0.089% of base)
         335 : System.Data.Common.dasm (0.022% of base)
         262 : Microsoft.CodeAnalysis.dasm (0.014% of base)
          44 : System.Numerics.Vectors.dasm (0.089% of base)
          42 : System.Threading.Tasks.Parallel.dasm (0.025% of base)

Top file improvements by size (bytes):
       -1002 : Microsoft.CodeAnalysis.VisualBasic.dasm (-0.017% of base)
        -598 : Microsoft.CodeAnalysis.CSharp.dasm (-0.013% of base)
        -516 : System.Private.CoreLib.dasm (-0.011% of base)
        -113 : System.Collections.Immutable.dasm (-0.010% of base)
         -49 : System.Reflection.Metadata.dasm (-0.011% of base)

35 total files with size differences (21 improved, 14 regressed), 94 unchanged.

Top method regressions by size (bytes):
         490 (3.163% of base) : System.Linq.Parallel.dasm - FirstQueryOperator`1:WrapPartitionedStream(ref,ref,bool,struct):this (49 methods)
         490 (3.163% of base) : System.Linq.Parallel.dasm - LastQueryOperator`1:WrapPartitionedStream(ref,ref,bool,struct):this (49 methods)
         490 (3.163% of base) : System.Linq.Parallel.dasm - TakeOrSkipQueryOperator`1:WrapPartitionedStream(ref,ref,bool,struct):this (49 methods)
         490 (3.163% of base) : System.Linq.Parallel.dasm - TakeOrSkipWhileQueryOperator`1:WrapPartitionedStream(ref,ref,bool,struct):this (49 methods)
         100 (0.345% of base) : System.Linq.Parallel.dasm - ConcatQueryOperator`1:WrapPartitionedStream(ref,ref,ref,bool,struct):this (49 methods)

Top method improvements by size (bytes):
        -442 (-1.724% of base) : System.Linq.Parallel.dasm - ILStubClass:IL_STUB_InstantiatingStub(ref,ref,bool,struct):this (221 methods)
        -205 (-50.000% of base) : System.Private.CoreLib.dasm - Marshal:AllocCoTaskMem(int):long (2 base, 1 diff methods)
        -144 (-50.000% of base) : System.Private.CoreLib.dasm - AnsiCharMarshaler:DoAnsiConversion(ref,bool,bool,byref):ref (2 base, 1 diff methods)
        -120 (-17.595% of base) : System.Collections.Immutable.dasm - ILStubClass:IL_STUB_InstantiatingStub(ref,struct):struct (6 methods)
        -106 (-50.000% of base) : System.Private.CoreLib.dasm - Buffer:Memcpy(long,int,ref,int,int) (2 base, 1 diff methods)

Top method regressions by size (percentage):
          55 (98.214% of base) : Microsoft.CodeAnalysis.CSharp.dasm - PEParameterSymbol:Create(ref,ref,int,struct,byref):ref
          35 (36.082% of base) : Microsoft.CodeAnalysis.dasm - VtblGap:Microsoft.Cci.ISignature.GetType(struct):ref:this
          35 (36.082% of base) : Microsoft.CodeAnalysis.dasm - ArrayMethodParameterInfo:GetType(struct):ref:this
          35 (36.082% of base) : Microsoft.CodeAnalysis.dasm - ArrayConstructor:GetType(struct):ref:this
          35 (36.082% of base) : Microsoft.CodeAnalysis.dasm - ArraySet:GetType(struct):ref:this

Top method improvements by size (percentage):
        -106 (-50.000% of base) : System.Private.CoreLib.dasm - Buffer:Memcpy(long,int,ref,int,int) (2 base, 1 diff methods)
        -144 (-50.000% of base) : System.Private.CoreLib.dasm - AnsiCharMarshaler:DoAnsiConversion(ref,bool,bool,byref):ref (2 base, 1 diff methods)
        -205 (-50.000% of base) : System.Private.CoreLib.dasm - Marshal:AllocCoTaskMem(int):long (2 base, 1 diff methods)
         -21 (-35.593% of base) : Microsoft.DotNet.Cli.Utils.dasm - ILStubClass:IL_STUB_InstantiatingStub(struct):struct:this
         -23 (-27.711% of base) : System.Threading.Tasks.Dataflow.dasm - WriteOnceBlock`1:CloneItem(struct):struct:this

917 total methods with size differences (543 improved, 374 regressed), 200968 unchanged.
```

How this affects perf is harder to measure, however. Instead I will continue to see if I can improve this to only introduce necessary temps by computing the correct stack offsets of arguments and then using this information in the same way that the code used the argument positions before.

cc @jashook @AndyAyersMS @RussKeldorph

**Comment by NinoFloris** [comment]
@jakobbotsch could you easily add the F# compiler? It makes heavy use of explicit tail calls.

/cc: @cartermp

**Comment by jakobbotsch** [comment]
@NinoFloris there is some data collected over F# tests in https://github.com/dotnet/jitutils/pull/213#issuecomment-513011840. Once this PR is in a working state I will try to collect this data for F# tests again. What would really help would be perf tests making heavy use of tail calls – does F# have any of those?

**Comment by cartermp** [comment]
@jakobbotsch We'll work to get a good repro.

**Comment by adamsitnik** [comment]
@cartermp @NinoFloris it would be great if you could add a new F# project with BenchmarkDotNet microbenchmarks to the [performance repo](https://github.com/dotnet/performance/blob/master/src/benchmarks/micro/MicroBenchmarks.sln). We are using it to continuously track the performance of the entire .NET Runtime for all hardware architectures and most commonly used OSes.

/cc @billwert

**Comment by jakobbotsch** [comment]
The only diffs I see on Windows x64/x86 are situations where we now insert the temps a bit earlier:
```diff
+               [000053] ------------                 START_NONGC void
+N001 (  3,  2) [000054] ------------        t54 =    LCL_VAR   int    V04 arg4
+                                                  /--*  t54    int
+N002 (  4,  3) [000056] DA----------              *  STORE_LCL_VAR int    V07 rat0
 N024 (  1,  1) [000014] ------------        t14 =    CNS_INT   int    0 $40
-N001 (  3,  2) [000053] ------------        t53 =    LCL_VAR   int    V04 arg4
-                                                  /--*  t53    int
-N002 (  4,  3) [000055] DA----------              *  STORE_LCL_VAR int    V07 rat0
-               [000056] ------------                 START_NONGC void
                                                   /--*  t14    int
                [000047] ------------              *  PUTARG_STK [+0x20] void
```
This leads to swapped order in some cases:
```diff
-       xor      ecx, ecx
-       mov      r9d, ebx
G_M5466_IG03:

+       mov      r9d, ebx
+       xor      ecx, ecx
```

I will investigate the OSX failure next.

**Comment by jakobbotsch** [comment]
Subsumed by #26255 (I was not able to reopen this after force-pushing my branch)

**Pull request closed without merging**
