### PR TITLE
Add `COMPlus_FeatureSIMD=0` testing

### PR DESCRIPTION
**Pull request by BruceForstall**

### CODE REVIEW

**Comment by BruceForstall** [comment]
cc @RussKeldorph

**Comment by jashook** [comment]
@dotnet-bot test CI please

**Comment by jashook** [comment]
Summary:

```
Cron Jobs

-- Added Jobs --
jitstress/x64_arm64_altjit_checked_windows_nt_jitnosimd (@daily)
jitstress/x64_checked_osx10.12_jitnosimd_flow (@daily)
jitstress/x64_checked_ubuntu_jitnosimd_flow (@daily)
jitstress/x64_checked_windows_nt_jitnosimd (@daily)
jitstress/x86_arm_altjit_checked_windows_nt_jitnosimd (@daily)
jitstress/x86_checked_windows_nt_jitnosimd (@daily)

-- Removed Jobs --

-- Changed Jobs --

Unrefferenced Jobs

-- Added Jobs --
jitstress/x64_arm64_altjit_checked_windows_nt_jitnosimd
jitstress/x64_arm64_altjit_checked_windows_nt_jitnosimd_prtest
jitstress/x64_checked_centos7.1_jitnosimd_flow
jitstress/x64_checked_centos7.1_jitnosimd_flow_prtest
jitstress/x64_checked_centos7.1_jitnosimd_tst
jitstress/x64_checked_centos7.1_jitnosimd_tst_prtest
jitstress/x64_checked_osx10.12_jitnosimd_flow
jitstress/x64_checked_osx10.12_jitnosimd_flow_prtest
jitstress/x64_checked_osx10.12_jitnosimd_tst
jitstress/x64_checked_osx10.12_jitnosimd_tst_prtest
jitstress/x64_checked_ubuntu_jitnosimd_flow
jitstress/x64_checked_ubuntu_jitnosimd_flow_prtest
jitstress/x64_checked_ubuntu_jitnosimd_tst
jitstress/x64_checked_ubuntu_jitnosimd_tst_prtest
jitstress/x64_checked_windows_nt_jitnosimd
jitstress/x64_checked_windows_nt_jitnosimd_prtest
jitstress/x86_arm_altjit_checked_windows_nt_jitnosimd
jitstress/x86_arm_altjit_checked_windows_nt_jitnosimd_prtest
jitstress/x86_checked_windows_nt_jitnosimd
jitstress/x86_checked_windows_nt_jitnosimd_prtest

```

**Comment by CarolEidt** [comment]
> Seems strange to run the altjit jobs daily with no simd; however, if that is expected then it lgtm

For now at least the arm and arm64 targets don't support SIMD. So, when we run altjit tests, we want to have FeatureSIMD turned off so that we compile the IL version, as we would on the actual target.

**Comment by jashook** [comment]
Sorry I didn't mean to come off as saying they are unnecessary. Instead was attempting to comment on the cadence these jobs will run outerloop. Daily seems a bit much to me.

**Comment by jashook** [comment]
After speaking with @BruceForstall I think we agree and are willing to standardize these cron jobs in a later pr.

**Pull request merged**
