### PR TITLE
Add specialized allocation helpers

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
This is to support dotnet/corert#6688. They don't exist in CoreCLR (yet).

### CODE REVIEW

**Comment by jkotas** [comment]
Build breaks...

**Comment by jkotas** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test please
@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test please
@dotnet-bot test Ubuntu arm Cross Checked no_tiered_compilation_innerloop Build and Test please

**Comment by MichalStrehovsky** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test please
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test (Jit - TieredCompilation=0)

**Comment by sandreenko** [comment]
We need to port this change to desktop. I will do it tomorrow morning.

**Comment by MichalStrehovsky** [comment]
> We need to port this change to desktop. I will do it tomorrow morning.

Thank you!

**Pull request merged**
