### PR TITLE
Update named mutex PAL tests to include case of file locks being inherited by child process

### PR DESCRIPTION
**Pull request by kouvel**
Included case fixed by https://github.com/dotnet/coreclr/pull/21458. Fixes https://github.com/dotnet/coreclr/issues/21494.

### CODE REVIEW

**Comment by danmosemsft** [comment]
I assume the test fails before #21458 then :)?

**Comment by kouvel** [comment]
Yes it does

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by kouvel** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test
test Ubuntu x64 Checked CoreFX Tests

**Pull request merged**
