### PR TITLE
Frkaya/gccfix07102019

### PR DESCRIPTION
**Pull request by franksinankaya**
@am11  @jkotas @janvorli

### CODE REVIEW

**Comment by franksinankaya** [comment]
@dotnet-bot test coreclr-ci

**Comment by franksinankaya** [comment]
what's the new way to force a retest?

**Comment by janvorli** [comment]
@franksinankaya I've restarted the failed test legs.

**Comment by franksinankaya** [comment]
ping for merge

**Comment by janvorli** [comment]
Ah, great, the first restart of the tests failed, so I've restarted it again today. I haven't noticed that they have already succeeded.

**Pull request merged**
