### PR TITLE
Historical debugging feature

### PR DESCRIPTION
**Pull request by kvochko**
We would like to implement a feature within CoreCLR similar to intellitrace's historical debugging, which would allow to roll the execution back to a previous point in time. We considered a few different approches.
An approach taken by GDB steps through the execution and creates checkpoints at every statement. This seems costly both in terms of implementation effort and execution overhead, and the limit for the number of steps a user can roll back is relatively small.
An approach taken by Intellitrace seems more balanced in that regard, creating log entries on function enters/leaves, breakpoints and watchpoints.
Right now we have a limited implementation of the second approach, which records only on function enter/leave events and only records a stack frame and a register context. We've also implemented a reverse-finish and reverse-continue commands in SOS, and it only works on ARM. 

We also want to implement checkpointing the heap: could anybody provide directions/pitfalls of this?

This requires PRs #6960, #6933 and #6976 
@Dmitri-Botcharnikov @chunseoklee @mikem8361 @jkotas @noahfalk

### CODE REVIEW

**Comment by jkotas** [comment]
Do you really need to add profiler that you are using to build this into the VM? It should be separate from the runtime - same as how Intellitrace is done.

**Comment by kvochko** [comment]
Just to clarify - should we put it in a separate folder? Right now this builds into a standalone shared library.

**Comment by jkotas** [comment]
It should be in separate folder, and built into separate .so. 

I am not sure how far you are planning to go with this. There is a lot of complex powerful features one can build around historical debugging that are independent on the runtime. If you are planning to go far enough with this, it may be better for it to live in separate repo and talk to the runtime using interfaces.

**Comment by kvochko** [comment]
I've put it in a separate folder. If it's possible, we would like for the feature to live in the CoreCLR repository for now, and move it to a separate repo when it matures enough.

**Comment by jkotas** [comment]
We try hard to develop tools that are pretty independent on the runtime in independent repos. The CoreCLR repo cannot scale to accommodate every tool like this. https://github.com/microsoft/clrmd and same tools built on top of it https://github.com/Microsoft/dotnetsamples/tree/master/Microsoft.Diagnostics.Runtime/CLRMD are good examples from the diagnostic space.

As far as I can tell, your current implementation is using public runtime interfaces only and thus it is pretty independent on the runtime. It is good design. If there are places where the existing public interfaces are not sufficient, we are happy to have design discussion on how to extend them and accommodate the different needs.

**Comment by lemmaa** [comment]
@jkotas Can we make a common repo, like `coreclr-tools`, for this kind of projects?

**Comment by jkotas** [comment]
Historic debugging engine is pretty non-trivial project. I appreciate that you have started a prototype. It would need to solve number of hard problems to be useful and dependable, like low-overhead checkpointing of object values that you have mentioned. Solving these problems requires a lot of code to be written. It would be better for the repo to be specific to the historic debugging project.

You can setup the repo yourself and have full control over it. It does not have to live under dotnet organization on github. Many (.NET Foundation Projects)[http://www.dotnetfoundation.org/projects] are run this way. Hosting of public repos on github is free.

**Comment by adityamandaleeka** [comment]
@kvochko Do you agree with the suggestion to implement this in a separate repo? If so, we can close this PR.

**Comment by kvochko** [comment]
Yes, we agree, thank you all for comments!

**Pull request closed without merging**
