### PR TITLE
Mark legacy ByRef-like types as ref in sources

### PR DESCRIPTION
**Pull request by jkotas**
Delete special casing for these in the type loader

### CODE REVIEW

**Comment by jkotas** [comment]
cc @weshaggard @VSadov

**Comment by weshaggard** [comment]
Once this merges should we do the same in the ref?

**Review by weshaggard — APPROVED** [review]

**Comment by jkotas** [comment]
> Once this merges should we do the same in the ref?

Yes.

**Review by VSadov — APPROVED** [review]
LGTM

**Comment by jaredpar** [comment]
FYI: the compiler special cases most of the types in this PR at a lower level than `ref struct`. No testing, or accounting, has gone into the possibility that these could be implemented as a `ref struct`. Generally they're restricted at a lower level than `ref struct` but it's possible there are gaps in the enforcement here.

**Comment by jkotas** [comment]
The restrictions for these types in the compiler and for verifiability/safety have to be super set of the restrictions that the runtime enforces. I think it may be possible to unify the restrictions for these types with `ref structs` once we have the support for ref fields.

**Comment by VSadov** [comment]
I do not think support for ref fields is a prerequisite to generalize restricted types and ref structs. C# compiler does not know about `ByReference<T>` either.
If C# escape analysis learns how to assign escape values to `__arglist` and `__makeref` it may rely entirely on escape analysis for safety of these. It may enable a few new scenarios.

One thing I am less certain - `TypedReference` has some special encoding in signatures. I assume that can work as a return type, element of a byref type, field type, yes?

**Pull request merged**
