### PR TITLE
Fix managed breakpoints on OSX

### PR DESCRIPTION
**Pull request by mikem8361**
Changed the OSX exception initialization to enable breakpoints/stepping.

Fix problem with faults and breakpoints in coreclr code not being forwarded to
native debugger (if being debugged).

Fix debugger shutdown where we release the transport too many times and assert in debug.

When building the register context for an exception don't save/restore the debug
registers because they cause an priviledged instruction fault.

Fixed the PAL's TRACE formatting by merging the printfcpp.cpp formatting into
silent_printf.cpp. "%p" wasn't being formatted correctly in a PAL TRACE statement.

The executable heap zone wasn't being set because the process heap
is used instead of creating a new heap.

### CODE REVIEW

**Comment by mikem8361** [comment]
@janvorli, @jkotas and @kangaroo could you review?

**Comment by ellismg** [comment]
NIT: Can you please case it as OSX, makes it much easier to understand, IMHO.

**Comment by mikem8361** [comment]
@dotnet-bot test this please

**Comment by ellismg** [comment]
@mmitche These all seem to be failing because they try to run centos pr test runs that don't exist.  Do you want me to just remove these legs from the build definitions for now?

**Comment by mmitche** [comment]
Removed.  I realized I never added the PR test side of the legs for those OSs.  Since I have a PR out for enabling that through the scripting, I'll remove that for now.

**Comment by mmitche** [comment]
(removed)

**Comment by ellismg** [comment]
Thanks!  The new scripting stuff looks super sweet.

**Comment by janvorli** [comment]
@dotnet-bot test this please

**Comment by mikem8361** [comment]
@janvorli and/or @jkotas: I would like to merge this before I go on vacation tomorrow.  Review?

**Comment by janvorli** [comment]
LGTM

**Comment by mikem8361** [comment]
@dotnet-bot test this please

**Pull request merged**
