### PR TITLE
Enabling profiling on Unix/OS X

### PR DESCRIPTION
**Pull request by sperling**
Building with PROFILING_SUPPORTED. #2519 

Some functionality is still missing.
* MovedReferences, MovedReferences2, SurvivingReferences and SurvivingReferences2 will only
  be called when FEATURE_EVENT_TRACE is defined.
* Enter, Leave and Tailcall function hooks is not implemented for Unix.
* DoStackSnapshot is not implemented when PLATFORM_SUPPORTS_SAFE_THREADSUSPEND is
  not defined.

### CODE REVIEW

**Comment by jkotas** [comment]
LGTM

@noahfalk Could you please take a look as well?

**Comment by jkotas** [comment]
@noahfalk Could you please take a look?

**Comment by jkotas** [comment]
I have talked to @noahfalk and @Maoni0 offline about this change. They expressed concerns about the gc.cpp change, but the change looks good otherwise. 

@sperling Could you please undo the change in gc.cpp, and instead add dummy implementations of the ETW::GCLog methods to eventtrace.h for now to make things compile (w/ TODO to fix it properly)? The workaround will be in one central location this way, no spread through.

While you are on it, you could also remove delete incorrect `#ifdef FEATURE_EVENT_TRACE` around ETW::GCLog::MovedReference in gc.cpp, line ~23780. Thanks!

**Comment by noahfalk** [comment]
I should also mention if anyone asked I'm not planning to claim officially that Coreclr supports profiling until we get automated tests up to validate behavior/catch regressions. However I'm also not going to discourage anyone from calling the profiler APIs if they are content with the results they are get now.

Thanks for putting this together!

**Comment by sperling** [comment]
@jkotas Sure, will do the changes.
@noahfalk Yeah this is only a small first step to get the ball rolling:smile:

**Comment by Maoni0** [comment]
LGTM. Please squash commits to merge. Thanks for doing this!

**Comment by jasonwilliams200OK** [comment]
:+1:

**Pull request merged**
