### PR TITLE
Fix accidental assignment inside an assert

### PR DESCRIPTION
**Pull request by calumgrant**
Fixed a small problem found by [lgtm.com](https://lgtm.com/projects/g/dotnet/coreclr/snapshot/dist-1505965926042-1548102289075/files/src/jit/morph.cpp#x202d60abc530dc82:1).

### CODE REVIEW

**Comment by filipnavara** [comment]
Wow, the tool is great. I filed another issue for a bug found by it (#22150). Thanks for broadening my horizons!

**Comment by CarolEidt** [comment]
test OSX10.12 x64 Checked Innerloop Build and Test
Ubuntu x64 Checked Innerloop Build and Test (Jit - TieredCompilation=0)

**Comment by CarolEidt** [comment]
> wonder if there are any asm diffs

The only way this could change behavior, I believe, is if it was hiding an assert that should have fired. That is, if `!argx->IsVarAddr()` is false, then it is currently setting `(argx->gtType = TYP_I_IMPL)` instead of asserting that it already has that value. So ... if we don't see new asserts then I don't see how we could be changing the code.

**Pull request merged**
