### PR TITLE
Add a subset of benchmark game benchmarks

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Add tests that are not multithreaded and don't rely on large input files. These are adapted for xunit-performance.

Add license and readme.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@cmckinsey one more for you.

**Comment by benaadams** [comment]
Some of these could now be Vector types? Though that might be testing a different thing.

**Comment by AndyAyersMS** [comment]
Hmm, more odd CI failures.

@dotnet bot retest Windows_NT x86 Release Build

**Comment by AndyAyersMS** [comment]
@benaadams New contributions are always welcome.

**Comment by AndyAyersMS** [comment]
x86 CI failures unrelated, see #2588.

**Comment by AndyAyersMS** [comment]
Retrying to see if the fix worked...

@dotnet bot retest Windows_NT x86 Release Build
@dotnet bot retest Windows_NT x86 Debug Build

**Comment by cmckinsey** [comment]
LGTM.

**Comment by AndyAyersMS** [comment]
Windows_NT x86 Release Build issues unrelated... going to ignore and merge.

**Pull request merged**
