### PR TITLE
Delete SingleGetHashCode and DoubleGetHashCode tests for arm/arm64

### PR DESCRIPTION
**Pull request by BruceForstall**
The tests themselves were deleted with #16567.

### CODE REVIEW

**Comment by BruceForstall** [comment]
cc @dotnet/arm32-contrib @dotnet/arm64-contrib

**Comment by BruceForstall** [comment]
Also delete StringCompare tests deleted with #16571

**Comment by sdmaclea** [comment]
Is there a reason we have to manually manage these lists for Arm64.  Can the test list be updated automatically?  At test runtime?

**Comment by BruceForstall** [comment]
We could probably auto-create the lists with some automation -- @jashook has some automation to update them, but it hasn't been used in a while.

Ideally, we would create a single cross-platform test infrastructure so we wouldn't have all three (or more?) msbuild/xunit, runtest.sh, and smarty.

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked normal Build and Test
@dotnet-bot test Windows_NT arm64 Cross Checked normal Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked normal Build and Test
@dotnet-bot test Windows_NT arm64 Cross Checked normal Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked normal Build and Test
@dotnet-bot test Windows_NT arm64 Cross Checked normal Build and Test

test Windows_NT armlb Cross Checked Innerloop Build and Test
test OSX10.12 x64 Checked Innerloop Build and Test

**Pull request merged**
