### PR TITLE
Fixed regex [:space:] warnings

### PR DESCRIPTION
**Pull request by pi1024e**
During build of "Coreclr", awk prints out the following warning:

> warning: regexp component `[:space:]' should probably be `[[:space:]]'
So I fixed the script and code to fix the warning, so that this issue could be resolved without any major workaround or code breakage.

### CODE REVIEW

**Comment by janvorli** [comment]
@pi1024e there is already PR #25670 for fixing that.

Your changes in the C++ files just modifies the code style and they are not needed.

**Comment by pi1024e** [comment]
Not only does that PR forget to change the [:space:] to [[:space:]] in the .sh file, but it also has a failing test. I changed the pull request to ONLY include the [:space:] to [[:space:]]

**Comment by janvorli** [comment]
@pi1024e the test failure in the other PR is not related to the change, it is an infrastructure problem. 
As for the .sh change, do you get any warnings in your build without that change? Manpage for the `tr` command has examples that use just single `[`.

**Comment by pi1024e** [comment]
Yes I do, I get the warning when I build it. This PR is for consistency in the [[:space:]] to eliminate any possible warnings regarding [:space:].

**Comment by janvorli** [comment]
@pi1024e what is your Linux distro? I've tried to run the following on my Ubuntu 16.04 and OSX and they accept both forms happily:
```
echo "a   b            c" | tr -d [:space:]
abc
echo "a   b            c" | tr -d [[:space:]]
abc
```

**Comment by pi1024e** [comment]
Ubuntu 19.0.

**Comment by pi1024e** [comment]
So, should we pull this, or are there other concerns regarding this request?

**Comment by janvorli** [comment]
@pi1024e i've realized that the .sh script needs to be fixed in the dotnet/arcade repo (https://github.com/dotnet/arcade/blob/master/eng/common/init-tools-native.sh). The files in the `eng` directory in the coreclr repo are copied to the coreclr repo from the arcade repo automatically.
So I'll merge the PR #25670 and you can make the .sh script change in the arcade repo.

**Comment by pi1024e** [comment]
Made changes in the arcade repository. Now I am just waiting for THAT pull request to be merged.

**Comment by pi1024e** [comment]
I just rebased the PR so it is up to date with the current official repo.

**Comment by janvorli** [comment]
We can close this PR as I've already merged in the #25670 and the only difference in your PR was the .sh change that is now in the arcade repo.

**Pull request closed without merging**
