### PR TITLE
Linux/ARM: Add 'initial-exec' tls model by default for RELEASE build

### PR DESCRIPTION
**Pull request by leemgs**
The clang compiler has the four tls models (e.g., global-dynamic,
local-dynamic, local-exec, and initial-exec) as following:

The default value of clang  is "global-dynamic". However, the thread-local
storage (TLS) model does not guarantee the normal execution of TLS's symbol
relocation due to the misaligned __tls_get_addr symbol in case of the
aggressive optimizations on Linux/ARM architecture.

a. Global Dynamic:
Fully general access to the TLS variables from an executable or a shared
object. Note that the Global Dynamic and Local Dynamic models also
require using -fpic. When compiling code which will be in an executable and
never be in a shared library, the developer may choose to set the TLS storage
model to Initial Executable.

b. Local Dynamic:
Permits access to a variable which is bound locally within the executable
or shared object from which it is referenced. This is true for all static
TLS variables, for example. It is also true for protected symbols.

c. Initial Executable:
Permits access to a variable which is known to be part of the TLS image of
the executable. This is true for all TLS variables defined in the executable
itself, and for all TLS variables in shared libraries explicitly linked with
the executable. This is not true for accesses from a shared library, nor for
accesses to TLS variables defined in shared libraries opened by dlopen(3).

d. Local Executable:
Permits access to TLS variables defined in the executable itself. However,
most of the frond-end compiler do not support this TLS model.

VER2:
===========
Let's set the 'initial-exec' TLS model by default to avoid misaligned
TLS alignment because of the aggressive optimization levels (e.g.,
O2, O3, and Os) such as release build mode at build-time for Linux/ARM.

---- How do we know wheter clang/LLVM create executable or share lib? ----
In practice, developers often do not know where code will be used. And
developers may not be aware of the intricacies of TLS models.
The LLVM program linker knows whether it is creating an executable or
a shared library, and it knows whether the TLS variable is defined locally.
So the program linker gets the job of automatically optimizing references
to TLS variables when possible. These references take the form of relocations,
and the linker optimizes the references by changing the code in various ways.

Also, the LLVM program linker is responsible for gathering all TLS variables
together into a single TLS segment. The dynamic linker has to group together
the TLS segments of the executable and all included shared libraries, resolve
the dynamic TLS relocations, and has to build TLS segments dynamically
when dlopen(3) is used. The kernel has to make it possible for access to
the TLS segments be efficient.

VER1: (a workaround)
===================
Replace -O3 with -O1 to avoid the segmentation fault due to the aggressive
optimization level of the clang (front-end for the LLVM compiler).

The difference among the optimization levels (e.g. O1, O2, O3)is as following:

-O2 is based on -O1:
 .Adding: -gvn -constmerge -globaldce -slp-vectorizer -mldst-motion -inline
 .Removing: -always-inline

-O3 is based on -O2:
 .Adding: -argpromotion

Evaluation:
===========
- Build: (on Ubuntu 14.04 X64 PC)
u1404@clr$> time ROOTFS_DIR=/work/dotnet/rootfs-coreclr/arm \
            ./build.sh arm release clean cross skiptests

- Run: (on Linux/ARM Emulator)
u1404@clr$> ./start.sh
target@emul> cd /dotnet/runtime-vfp-release-mode/
target@emul> time ./corerun /dotnet/example/hello.exe

References:
===========

a. GCC/(e)Glibc Ports:
GCC's Internal TLS Library - https://github.com/gcc-mirror/gcc/blob/master/libgcc/emutls.c
glibc's __tls_get_addr (ARM) - https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/arm/dl-tls.h

b. Clang/LLVM Ports:
Clang Compiler Flags (ver. 3.5.0) - http://llvm.org/releases/3.5.0/tools/clang/docs/ReleaseNotes.html
Clang Compiler Flags (ver. 3.8.0) - http://llvm.org/releases/3.8.0/tools/clang/docs/ReleaseNotes.html
LLVM Transform Passes - http://llvm.org/docs/Passes.html#always-inline-inliner-for-always-inline-functions

c. Thread-Local Stroage (TLS):
ELF Handling For Thread-Local Storage: https://www.akkadia.org/drepper/tls.pdf

Signed-off-by: Geunsik Lim <geunsik.lim@samsung.com>

### CODE REVIEW

**Comment by leemgs** [comment]
* Run hello!!! before this PR
```
-----------------------------------
release-buil@armemul#> 
release-buil@armemul#> time ./corerun  /dotnet/example/hello.exe
Segmentation fault

real	0m0.448s
user	0m0.210s
sys	0m0.090s
```



* Run hello!!! this PR
```
---------------------------------
release-buil@armemul#> 
release-buil@armemul#> time ./corerun  /dotnet/example/hello.exe
Hello World

real	0m3.170s
user	0m2.360s
sys	0m0.160s
```

**Comment by leemgs** [comment]
This PR is to run normally the `hello world!!!` console application in release-build mode. It is based on https://github.com/dotnet/coreclr/issues/4583. We have experimented the compilation and the running test both DEBUG and RELEASE build mode. The Linux/ARM Emulator is used as a Testbed. 

\CC: @jkotas , @janvorli , @benpye

**Comment by leemgs** [comment]
After applying this PR, The execution time of the release build mode is faster about 3 ~ 4 times than the debug build mode on the Linux/ARM emulator.  @jyoungyun Could you check and share the uni-test time of coreCLR between DEBUG and RELEASE build mode on your development board. 

\CC: @myungjoo, @jyoungyun , @prajwal-aithal , @manu-silicon

**Comment by myungjoo** [comment]
Great! This is supposed to fix #3182 as well!

**Comment by janvorli** [comment]
Is it really generating a correct TLS accesses? The part that makes me feel there could be a problem is the last sentence of your description of the initial executable mode:
> This is not true for accesses from a shared library, nor for
accesses to TLS variables defined in **shared libraries opened by dlopen(3)**.

We are loading libcoreclr.so using dlopen, so that's why I am worried about it. And reading the https://www.akkadia.org/drepper/tls.pdf section 4.3 seems to confirm my worries.

**Comment by leemgs** [comment]
> This is true for all TLS variables defined in the executable itself, 
> and for all TLS variables in shared libraries explicitly linked with the executable. 

@janvorli , As an example of loading shared libraries using dlopen with the executable, 
the libcoreclr.so is normally run by dlopen in the executable such as corerun. 

> This is not true for accesses from a shared library, nor for
> accesses to TLS variables defined in shared libraries opened by dlopen(3).

My intention of the above description is that Clang/LLVM cannot guarantee the accesses  to TLS variables in case that some developers try to use dlopen(libcoreclr.so) in the their shared libraries for the debugging. If you want, I can remove this description (or modify with more appropriate content).

> Is it really generating a correct TLS accesses?

We have verified the normal execution of some console applications including hello world!!!
on Linux/ARM Emulator, Raspberry Pi2 board, and Samsung ARM Chromebook before submitting the PR.

**Comment by janvorli** [comment]
@leemgs I don't think running simple console apps really verifies that it works correctly. It might be overwriting some memory that doesn't belong to it and still appear to work until you start running many threads in parallel, pulling in more shared libraries that use TLS as well using dlopen (or interop in managed code, which is essentially the same thing), etc.
I'll need to study the https://www.akkadia.org/drepper/tls.pdf in deeper detail to convince myself that using the initial-exec mode is really correct.

**Comment by janvorli** [comment]
Reading the relevants part of the document in detail I am really convinced that we cannot use the initial-exec model for TLS variables in shared libraries loaded using dlopen. The reason is that this model takes advantage of the fact that the thread local variables for each module are stored at a fixed offset from the TCB and that is not true for shared libraries used using dlopen (each of them has dynamically allocated TLS block, so its location is determined at runtime based on where the block gets allocated). 
Also, there is an ARM32 specific doc that describes the TLS access modes, reassuring me in my assumption:
http://infocenter.arm.com/help/topic/com.arm.doc.ihi0045e/IHI0045E_ABI_addenda.pdf
It says (see the bold text):
> 3.3.2 Linux for ARM static (initial exec) model
**If DSOs need not be loaded dynamically**, more efficient addressing modes can be constructed if the run-time
system allocates TLS at process creation time.

**Comment by jkotas** [comment]
I agree with @janvorli that `initial-exec` mode cannot be used as long as libcoreclr.so is loaded via dlopen.

Does the bug repro with `local-dynamic` as well? `local-dynamic` should be fine to use.

**Comment by leemgs** [comment]
> The reason is that this model takes advantage of the fact that the thread local variables 
> for each module are stored at a fixed offset from the TCB and that is not true 
> for shared libraries used using dlopen...

@janvorli , According to the "3.3.2 Linux for ARM static (initial exec) model" of the ARM information center, It's possible to make a thread safe issue in case of the multi-threaded programs due to the dlopen(3) with initial-exec model.

> Does the bug repro with local-dynamic as well? local-dynamic should be fine to use.

@jkotas , Unfortunately, the local-dynamic model always reproduces the bug such as global-dynamic (by default) in case that we enable the aggressive optimization levels (e.g., -O2, -O3). Does -O1 optimization level is a best method until we find more appropriate solution for release build mode?

**Comment by leemgs** [comment]
In order  to check the relationship between TLS models and optimization levels, I have tried to modify the relation codes by adding "__attribute(tls_model("{**tls-model**}"))". It seems that the TLS model issue by aggressive optimization levels is related to the below three sources. 
a. src/pal/src/exception/seh.cpp
b. src/vm/corhost.cpp
c. src/vm/threads.inl

> Also, there is an ARM32 specific doc that describes the TLS access modes, reassuring me in my assumption:
>> 3.3.2 Linux for ARM static (initial exec) model
>> If DSOs need not be loaded dynamically, more efficient addressing modes can be constructed 
>> if the run-time system allocates TLS at process creation time.

@janvorli , One question, If you know a person who is in charge of the Linux/ARM64 architecture, could you share us his name? If we can get TLS experience of Linux/ARM64 from them, It will be helpful to enable the aggressive optimization flags (-O3) flag in release build mode for Linux/ARM.  As a next step, It seems that we need to dig the clang/LLVM internals to set higher optimization flag in release build mode.

**Comment by janvorli** [comment]
@leemgs I would like to better understand the actual issue with the __tls_get_addr misalignment. What is actually misaligned? The address of the function itself after it gets relocated or some other address the function tries to access? I have tried to find it in your analysis, but I am missing it there.

**Comment by janvorli** [comment]
As for the Linux/ARM64, the initial work was done by @kangaroo, but there is no-one "in charge" for it.

**Comment by leemgs** [comment]
> I would like to better understand the actual issue with the __tls_get_addr misalignment.

Right, I agree. I would like to understand thread-local storage (TLS) misalignment issue more deeply.

However, before fully understanding TLS implementation and acquiring a perfect solution,
we'd like to have a workaround to enable RELEASE build for ARM that are optimized enough
to run the CoreCLR unittest in reasonable time.

It has been taking more than 13 hours and with this build, it takes less than 4 hours.
(A big boost on the productivity)

```
+# Todo: Replace -O1 with -O3 after fixing Clang/LLVM to support __thread variable
+if(CMAKE_SYSTEM_NAME STREQUAL Linux AND CMAKE_SYSTEM_PROCESSOR STREQUAL armv7l)
+    SET (CMAKE_C_FLAGS_RELEASE_INIT        "-g -O1")
+else()
+    SET (CMAKE_C_FLAGS_RELEASE_INIT        "-g -O3")
+    message(FATAL_ERROR "RELEASE... c flag no-arm")
+endif()

```
> What is actually misaligned? 

The __tls_get_addr misalignment means that the program linker/loader does not correctly find the address of the thread-local storage (TLS) via GOT/PLT tables when we enable the dynamic TLS model (e.g., the global-dynamic and the local-dynamic). At that time, I had wanted to use static TLS model to resolve this issue without the any modification of the Clang/LLVM. However, As you shared, 
the coreCLR is working with dlopen(3).

So, After posting this bug to the Clang/LLVM community to get the technical support from LLVM guys, As a long-term assignment, I am going to dig the internals of optimization flags about the eight Transform Passes of the LLVM as following: 

- -O2 level is based on -O1 level:
   .Adding  : 1) -gvn 2) -constmerge 3) -globaldce 4) -slp-vectorizer 4) -mldst-motion 6) -inline
   .Removing: 7) -always-inline

- -O3 level is based on -O2 level:
   .Adding  : 8) -argpromotion

**Comment by leemgs** [comment]
> we'd like to have a workaround to enable RELEASE build for ARM that are optimized enough
> to run the CoreCLR unittest in reasonable time.
>
> It has been taking more than 13 hours and with this build, it takes less than 4 hours.
> (A big boost on the productivity)
>

I will close this PR because `initial-exec `TLS model can not handle the thread-safe issue of the multi-threaded in case of the dlopen() usage. Then, I will re-submit another (workaround) PR for Linux/ARM's release-build until fixing the bug of Clang/LLVM. Thanks all of you.

**Pull request closed without merging**
