### PR TITLE
Android cross-build script update

### PR DESCRIPTION
**Pull request by cydhaselton**
Updates download URLs and folders for libandroid-support-dev and libandroid-support packages. Downloads were failing and consequently cross-build failed early due to missing headers.

Tagging @qmfrederik for review

### CODE REVIEW

**Comment by cydhaselton** [comment]
Unwanted changes in PR…removing and re-submitting

**Comment by qmfrederik** [comment]
@cydhaselton PS - if you're going to update the build script, Termux now also packages libunwind so we can just use the Termux package instead of compiling it ourselves.

**Comment by cydhaselton** [comment]
@qmfrederik Sweet. Will add.

**Comment by cydhaselton** [comment]
@qmfrederik At some point we should come up with logic to handle updated packages; I'll add it as a TODO in the script

**Pull request closed without merging**
