### PR TITLE
Remove always-defined symbols

### PR DESCRIPTION
**Pull request by danmosemsft**
These are always defined in the CoreCLR build, and now we no longer want to preserve mergeability with desktop, we can remove them.

Fixes https://github.com/dotnet/coreclr/issues/8883

Verification in progress: diff decompilation for each architecture.

### CODE REVIEW

**Comment by danmosemsft** [comment]
Verified by building before and after and decompiling then diffing the code across Windows debug, Windows x86, Linux debug, Linux release. The only diff in each case is the dead string I removed.

**Comment by danmosemsft** [comment]
@jkotas could you or someone review?

**Comment by jkotas** [comment]
FeatureAppdomainResourceMonitoring should be deleted & disabled instead.

**Comment by jkotas** [comment]
LGTM. Thanks for getting this started!

BTW: I have opened the following issues related to the NetStandard2.0 work as I was reviewing this:

https://github.com/dotnet/coreclr/issues/9045
https://github.com/dotnet/coreclr/issues/9047

cc @gkhanna79 @rahku

**Comment by hughbe** [comment]
Can you clarify why we've abandoned mergeability with Desktop? Thanks

**Comment by jkotas** [comment]
It is not completely abandoned, e.g. it is still maintained for some parts like JIT or GC. The corelib is on the port the selected fixes plan - same as corefx, for the same reasons as corefx - the .NET Core corelib is too different from the desktop one.

**Comment by danmosemsft** [comment]
OK, removed and disabled FEATURE_APPDOMAIN_RESOURCE_MONITORING. This is the only change affecting the final binary (save removing a string)

**Comment by danmosemsft** [comment]
@jkotas merged, but just a note to confirm that you meant me to remove FEATURE_APPDOMAIN_RESOURCE_MONITORING (it was previously enabled)

**Comment by jkotas** [comment]
@danmosemsft Yes, looks good.

**Pull request merged**
