### PR TITLE
Fix for issue #5537: dotnet build is slower on Linux than Windows

### PR DESCRIPTION
**Pull request by fadimounir**
Fixing the loader logic on Unix to mimic the behavior on Windows,
in order to be able to successfully load and use R2R images on
Unix where the file extension does not have the ".ni." portion.

@gkhanna79 @jkotas PTAL

### CODE REVIEW

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu x64 Checked pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Windows_NT Checked pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu Checked pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu Release pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Windows_NT Release pri1r2r please

**Comment by jkotas** [comment]
👍

**Comment by gkhanna79** [comment]
@dotnet-bot test OSX Checked pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by fadimounir** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by fadimounir** [comment]
@dotnet-bot test OSX Checked please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by gkhanna79** [comment]
@mmitche should we restart the entire job?

**Comment by mmitche** [comment]
Not yet.  I'm looking into it.  If anything, that would make it worse.

**Comment by gkhanna79** [comment]
@mmitche These jobs appear to be hung. Can you please kill all of them and restart them all?

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
@dotnet-bot test OSX Checked pri1r2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test Ubuntu Checked pri1r2r please

**Comment by gkhanna79** [comment]
@dotnet-bot test Windows_NT Checked pri1r2r please

**Comment by mmitche** [comment]
@gkhanna79 In cases like this, closing and reopening the PR will do a forced retrigger

**Pull request merged**
