### PR TITLE
Removing NYI for ZapUnwindData

### LINKED ISSUE #2964: ARM64: Implement ZapUnwindData
coregen.exe on ARM64 fails with

    PORTABILITY_ASSERT("ZapUnwindData::GetAlignment");
    PORTABILITY_ASSERT("ZapUnwindData::GetSize");
    PORTABILITY_ASSERT("ZapUnwindData::Save");

  File: d:\projectk\src\ndp\clr\src\zap\zapcode.cpp Line: 1463
    Image: C:\Arm64\arm64coresyschk\ProjectK\Runtime\coregen.exe

### PR DESCRIPTION
**Pull request by ramarag**
This fixes #2964 and mscorlib.ni.dll gets generated for Arm64
@rahku @gkhanna79 PTAL
@dotnet/arm64-contrib FYI

### CODE REVIEW

**Comment by gkhanna79** [comment]
Are you able to run HelloWorld against mscorlib.ni.dll?

**Comment by gkhanna79** [comment]
Please also update the build script to generate mscorlib.ni.dll as part of the product build, similar to other platforms.

**Comment by ramarag** [comment]
crossgen currently works only on the target machine. Unitll we get a cross build for it we can not add to the build scripts
There are more NYI's and asserts in VM\crossgen for running hello world. I will file issues for them

**Comment by ramarag** [comment]
@dotnet-bot test Windows_NT arm64 Debug
@dotnet-bot test Windows_NT arm64 Checked
@dotnet-bot test Windows_NT arm64 Release

**Comment by rahku** [comment]
Looks good. There is still one remaining place in these files which require arm64 porting Eg. ZapMethodEntryPointTable::CanDirectCall . Can you fix that as well.

**Comment by ramarag** [comment]
will look into them

**Pull request merged**
