### PR TITLE
Add the bytemark benchmarks

### PR DESCRIPTION
**Pull request by AndyAyersMS**
These are C# versions of benchmarks that originally appeared in BYTE magazine in 1995.
See file headers for attribution.

I've added [Benchmark] entry points for xunit-performance, and tuned each portion to run for
about 1 second per xunit-performance iteation. Note a couple of the tests have variant
implementations in C# -- either jagged vs MD arrays, or class vs struct. When run under xunit
the work per test is fixed.

When run as a command line app this will auto-tune (adjust iterations to try and hit some
running time threshold).  We may want to reduce the running time here

I've also tried to enable validation code where possible, both to ensure that the compiler
gets the right answers, and also so it can't cheat and remove computation.

There are two issues requiring follow up work:

The two assign benchmarks seem to report varying times in xunit mode, and will need to be investigated further.

IDEA is currently disabled because it fails to validate with Ryujit.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@cmckinsey PTAL.

Issues for follow up coming up shortly.

**Comment by AndyAyersMS** [comment]
The IDEA issue in #2615 no longer repros. So it's enabled now.

**Comment by AndyAyersMS** [comment]
@cmckinsey one last one to look at....

**Comment by cmckinsey** [comment]
You might want to add Copyright for the additional 8 benchmarks that use jagged/rect. But otherwise LGTM.

**Comment by AndyAyersMS** [comment]
All the source files have the same copyright notice right now -- are you suggesting I do something else?

**Comment by cmckinsey** [comment]
My understanding is that our contractor years back added these sub-benchmarks:

    // Added for control of new C# rect/jagged struct/class tests 
552         DONUMJAGGED = 42,        /* DONUMSORTJAGGED */ 
553         DONUMRECT = 43,          /* DONUMSORTRECT */ 
554         DOEMFSTRUCT = 44,        /* DOEMFSTRUCT */ 
555         DOEMFCLASS = 45,         /* DOEMFCLASS */ 
556         DOASSIGNJAGGED = 46,     /* DOASSIGNJAGGED */ 
557         DOASSIGNRECT = 47,       /* DOASSIGNRECT */ 
558         DONNETJAGGED = 48,       /* DONNETJAGGED */ 
559         DONNETRECT = 49,         /* DONNETRECT */ 
560 
 
I'm saying update the header for all files to outline those in addition to simply porting to C# unaltered. Since it's our standard to add our copyright on contributions seems would be appropriate here as well.

**Comment by AndyAyersMS** [comment]
@cmckinsey updated, PTAL

**Comment by AndyAyersMS** [comment]
Timed out in debug mode... looks like iteration counts will need some adjusting.

**Comment by AndyAyersMS** [comment]
Pushed an update that slims down debug build execution time to around 100 sec. Still kinda slow but more extensive changes are needed to get the time below where it is now.

**Comment by AndyAyersMS** [comment]
Pushed a second update to reduce release time (was ~600 seconds).

Likely I'll need to rework the code so that we can specify desired time in fractional seconds, since when running these as correctness tests we should really only spend a few seconds at most. 

Will address this as part of #2655 .

**Comment by cmckinsey** [comment]
Thanks. LGTM.

**Comment by AndyAyersMS** [comment]
Ubuntu failure is CscBench acting up yet again on dci-ub-fbld-2 (#2728). Merging.

**Pull request merged**
