### PR TITLE
[WIP] Introduce GT_ADD_LO and GT_SUB_LO

### LINKED ISSUE #5698: RyuJIT x86: Lowering sometimes replaces ADD with LEA when ADD is required to set flags
Found in #4986. JIT\Methodical\fp\exgen\10w5d_cs_do\10w5d_cs_do.cmd fails because an `ADD` used by low part of a long `ADD` operation was replaced with a `LEA`:

```
81EA3BD6A42A sub      edx, 0x2AA4D63B
B90087947F   mov      ecx, 0x7F948700
1BC1         sbb      eax, ecx
8D0C16       lea      ecx, [esi+edx]  ; the carry flag is required by the adc below
8BD7         mov      edx, edi
13D0         adc      edx, eax
8BC1         mov      eax, ecx
```

### PR DESCRIPTION
**Pull request by mikedn**
Fixes #5698

### CODE REVIEW

**Comment by mikedn** [comment]
I don't know how the team feels about adding new genTreeOps but in this case it seems simpler and safer to me. The new ops are mostly added where `GT_ADD_HI`/`GT_SUB_HI` already exists, if a flag is used code that otherwise has no idea about decomposition needs to be changed (`LowerAdd` for example).

Also, I'm thinking that the existing `GTF_SET_FLAGS` could be used in the future to allow integer compares to reuse CPU flags set by a previous instructions, RyuJIT unfortunately lacks this optimization currently.

**Comment by CarolEidt** [comment]
LGTM. I'm not sure where flag reuse falls in the priority list, but this seems to me to be a clean solution to this at least for now.
@adiaaida @BruceForstall PTAL.
cc @dotnet/jit-contrib

**Comment by pgavlin** [comment]
LGTM as well. I also personally prefer using new operators rather than flags for this scenario.

**Comment by adiaaida** [comment]
LGTM.

**Comment by BruceForstall** [comment]
@mikedn Thanks for the investigation and the fix!

**Pull request merged**
