### PR TITLE
Fix for CoreCLR issue 3049

### PR DESCRIPTION
**Pull request by gkhanna79**

### CODE REVIEW

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
@jkotas PTAL.

**Comment by gkhanna79** [comment]
Fixes https://github.com/dotnet/coreclr/issues/3049

**Comment by AndyAyersMS** [comment]
Not part of your change, but related... Why do we link with `/LTCG` (in release modes) if we never compile with `/GL`?

**Comment by jkotas** [comment]
https://github.com/dotnet/coreclr/blob/master/CMakeLists.txt#L426 is passing `/GL` for release modes. I have done a quick check and I see it passed in to cl in the .rsp file. Do you see it not getting passed it to the compiler in some cases?

**Comment by AndyAyersMS** [comment]
Sorry for the false alarm, I was confused. I was just randomly looking through the file and didn't see the `/GL`.

**Comment by AndyAyersMS** [comment]
@gkhanna79 I'm still seeing frequent linker crashes. Not a blocker since I can just rebuild, but annoying. Happens when I'm doing development and so am always incrementally rebuilding stuff. 

@dotnet/jit-contrib anybody else running into this?

**Comment by jashook** [comment]
I see link errors for the arm64 cross build only on certain machines. Unknown if it is related.

**Comment by gkhanna79** [comment]
CFG is not enabled for Arm64

**Comment by LLITCHEV** [comment]
I used to see this every other time for Debug builds for Windows. Fr some reason the installation of My VS got corrupted yesterday (the mspdb14.dll) was failing version check, so I reinstalled VS last night. This morning I have seen the crash only twice.

**Comment by pgavlin** [comment]
I've also run into this, specifically when incrementally linking crossgen.exe.

**Comment by BruceForstall** [comment]
I hit it almost every build. Succeeds on rebuild.

**Comment by gkhanna79** [comment]
Do you see this on debug or release build? Also, does the failing build command line having incremental linking disabled (which is what this change enabled)?

**Comment by BruceForstall** [comment]
I mostly do plain vanilla debug x64 builds. Don't know what flags are used.

**Pull request merged**
