### PR TITLE
[ARM/Linux] Fix HFA unit test regression

### LINKED ISSUE #7398: [ARM/Linux] Regression: HFA unit tests fail
Some of HFA tests fail on RPi2.

Error message and backtrace for `JIT.jit64.hfa.main.testE.hfa_nf2E_d.hfa_nf2E_d`:

```
Assert failure(PID 9468 [0x000024fc], Thread: 9468 [0x24fc]): Assertion failed 'found' in 'HFATest.TestCase:Main():int' (IL size 590)

    File: /home/hanjoung/ws/dotnet/coreclr/src/jit/gtstructs.h Line: 91
    Image: /home/ubuntu/ws/dotnet/set/corerun


Program received signal SIGABRT, Aborted.
__libc_do_syscall () at ../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:44
44      ../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S: No such file or directory.
(gdb) bt
#0  __libc_do_syscall () at ../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:44
#1  0x76db8f0e in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#2  0x76dbb766 in __GI_abort () at abort.c:89
#3  0x76baa642 in PROCEndProcess (hProcess=0xffffff01, uExitCode=1, bTerminateUnconditionally=1) at /home/hanjoung/ws/dotnet/coreclr/src/pal/src/thread/process.cpp:1385
#4  0x76baa796 in TerminateProcess (hProcess=0xffffff01, uExitCode=1) at /home/hanjoung/ws/dotnet/coreclr/src/pal/src/thread/process.cpp:1301
#5  0x764d0a4c in _DbgBreakCheck (szFile=0x718ed2ba "/home/hanjoung/ws/dotnet/coreclr/src/jit/gtstructs.h", iLine=91, 
    szExpr=0x7eff9dd0 "Assertion failed 'found' in 'HFATest.TestCase:Main():int' (IL size 590)\n", fConstrained=0) at /home/hanjoung/ws/dotnet/coreclr/src/utilcode/debug.cpp:492
#6  0x76542dd8 in CEEInfo::doAssert (this=0x7effd2a8, szFile=0x718ed2ba "/home/hanjoung/ws/dotnet/coreclr/src/jit/gtstructs.h", iLine=91, 
    szExpr=0x7eff9dd0 "Assertion failed 'found' in 'HFATest.TestCase:Main():int' (IL size 590)\n") at /home/hanjoung/ws/dotnet/coreclr/src/vm/jitinterface.cpp:10298
#7  0x71671374 in assertAbort (why=0x718ed7d6 "found", file=0x718ed2ba "/home/hanjoung/ws/dotnet/coreclr/src/jit/gtstructs.h", line=91)
    at /home/hanjoung/ws/dotnet/coreclr/src/jit/error.cpp:287
#8  0x7165b5da in GenTree::AsBlk (this=0x849b8) at /home/hanjoung/ws/dotnet/coreclr/src/jit/gtstructs.h:91
#9  0x71769e76 in Compiler::rpPredictBlkAsgRegUse (this=0x7b130, tree=0x84a70, predictReg=PREDICT_NONE, lockedRegs=0, rsvdRegs=0)
    at /home/hanjoung/ws/dotnet/coreclr/src/jit/regalloc.cpp:1651
#10 0x717652ec in Compiler::rpPredictTreeRegUse (this=0x7b130, tree=0x84a70, predictReg=PREDICT_NONE, lockedRegs=0, rsvdRegs=0)
    at /home/hanjoung/ws/dotnet/coreclr/src/jit/regalloc.cpp:2420
#11 0x71762acc in Compiler::rpPredictRegUse (this=0x7b130) at /home/hanjoung/ws/dotnet/coreclr/src/jit/regalloc.cpp:6476
#12 0x717620a8 in Compiler::raAssignVars (this=0x7b130) at /home/hanjoung/ws/dotnet/coreclr/src/jit/regalloc.cpp:736
#13 0x7164f044 in Compiler::compCompile (this=0x7b130, methodCodePtr=0x7effcde8, methodCodeSize=0x7effd1a8, compileFlags=0x7effcdec)
    at /home/hanjoung/ws/dotnet/coreclr/src/jit/compiler.cpp:4492
```

### PR DESCRIPTION
**Pull request by wateret**
Fix #7398

### CODE REVIEW

**Comment by wateret** [comment]
@CarolEidt PTAL

**Comment by CarolEidt** [comment]
The changes look reasonable. Can you tell me what the test was that encountered this? With the previous round of block op IR changes, we shouldn't be seeing lclVars on the lhs of an assignment (though that WILL be enabled with the next round of changes).

**Comment by CarolEidt** [comment]
@dotnet-bot test OSX x64 Checked Build and Test
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Comment by CarolEidt** [comment]
@mmitche do you know why we are seeing repeated failures of the form "Unhandled Exception: System.MissingMethodException: Method not found: 'System.IO.TextWriter System.Console.get_Out()'" in the OSX and Ubuntu tests?

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Pull request merged**
