### PR TITLE
WIP DO NOT MERGE Dummy change: ARM native

### PR DESCRIPTION
**Pull request by BruceForstall**

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked gcstress0x3
@dotnet-bot test Windows_NT arm Cross Checked gcstress0xc
@dotnet-bot test Windows_NT arm Cross Checked gcstress0xc_jitstress1
@dotnet-bot test Windows_NT arm Cross Checked gcstress0xc_jitstress2
@dotnet-bot test Windows_NT arm Cross Checked jitstress1
@dotnet-bot test Windows_NT arm Cross Checked jitstress2
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs0x10
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs0x1000
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs0x80
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs1
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs2
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs3
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs4
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs8
@dotnet-bot test Windows_NT arm Cross Checked minopts
@dotnet-bot test Windows_NT arm Cross Checked r2r
@dotnet-bot test Windows_NT arm Cross Checked tailcallstress
@dotnet-bot test Windows_NT arm Cross Checked zapdisable
@dotnet-bot test Windows_NT arm Cross Debug
@dotnet-bot test Windows_NT arm Cross Release r2r
@dotnet-bot test Windows_NT arm Cross Release

**Comment by BruceForstall** [comment]
ARM native Windows testing

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked r2r
@dotnet-bot test Windows_NT arm Cross Release r2r
@dotnet-bot test Windows_NT arm64 Cross Checked r2r
@dotnet-bot test Windows_NT arm64 Cross Release r2r
@dotnet-bot test Windows_NT armlb Cross Checked r2r
@dotnet-bot test Windows_NT armlb Cross Release r2r

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked gcstress0x3
@dotnet-bot test Windows_NT arm Cross Checked gcstress0xc
@dotnet-bot test Windows_NT arm Cross Checked gcstress0xc_jitstress1
@dotnet-bot test Windows_NT arm Cross Checked gcstress0xc_jitstress2
@dotnet-bot test Windows_NT arm Cross Checked jitstress1
@dotnet-bot test Windows_NT arm Cross Checked jitstress2
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs0x10
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs0x1000
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs0x80
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs1
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs2
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs3
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs4
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs8
@dotnet-bot test Windows_NT arm Cross Checked minopts
@dotnet-bot test Windows_NT arm Cross Checked r2r
@dotnet-bot test Windows_NT arm Cross Checked tailcallstress
@dotnet-bot test Windows_NT arm Cross Checked zapdisable
@dotnet-bot test Windows_NT arm Cross Debug
@dotnet-bot test Windows_NT arm Cross Release
@dotnet-bot test Windows_NT arm Cross Release r2r

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked minopts

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked jitstress1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs0x10 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs0x1000 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs0x80 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs3 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs4 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs8 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs0x10 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs0x1000 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs0x80 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs3 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs4 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs8 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked minopts Build and Test
@dotnet-bot test Windows_NT arm Cross Checked tailcallstress Build and Test
@dotnet-bot test Windows_NT arm Cross Checked zapdisable Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked jitstress1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2 Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm64 Cross Debug Innerloop Build

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked jitstress1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs0x10 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs0x1000 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs0x80 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs3 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs4 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs8 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs0x10 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs0x1000 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs0x80 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs3 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs4 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs8 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked minopts Build and Test
@dotnet-bot test Windows_NT arm Cross Checked tailcallstress Build and Test
@dotnet-bot test Windows_NT arm Cross Checked zapdisable Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked jitstress1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs0x10 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs0x1000 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs0x80 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs3 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs4 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs8 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs0x10 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs0x1000 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs0x80 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs3 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs4 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs8 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked minopts Build and Test
@dotnet-bot test Windows_NT arm Cross Checked tailcallstress Build and Test
@dotnet-bot test Windows_NT arm Cross Checked zapdisable Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked gcstress0x3 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked gcstress0xc Build and Test
@dotnet-bot test Windows_NT arm Cross Checked gcstress0xc_jitstress1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked gcstress0xc_jitstress2 Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked gcstress0x3 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked gcstress0xc Build and Test
@dotnet-bot test Windows_NT arm Cross Checked gcstress0xc_jitstress1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked gcstress0xc_jitstress2 Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot help

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked forcerelocs Build and Test
@dotnet-bot test Windows_NT arm Cross Checked gcstress0xc_minopts_heapverify1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked gcstress0xc_zapdisable Build and Test
@dotnet-bot test Windows_NT arm Cross Checked gcstress0xc_zapdisable_heapverify1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked gcstress0xc_zapdisable_jitstress2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked heapverify1 Build and Test

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs3 Build and Test

**Comment by sandreenko** [comment]
Lets check again:
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs3 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs2 Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked jitstress1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs0x10 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs0x1000 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs0x80 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs3 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs4 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs8 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs0x10 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs0x1000 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs0x80 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs3 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs4 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs8 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked minopts Build and Test
@dotnet-bot test Windows_NT arm Cross Checked tailcallstress Build and Test
@dotnet-bot test Windows_NT arm Cross Checked zapdisable Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked jitstress1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs0x10 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs0x1000 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs0x80 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs3 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs4 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs8 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs0x10 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs0x1000 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs0x80 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs3 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs4 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs8 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked minopts Build and Test
@dotnet-bot test Windows_NT arm Cross Checked tailcallstress Build and Test
@dotnet-bot test Windows_NT arm Cross Checked zapdisable Build and Test

**Comment by BruceForstall** [comment]
test CentOS7.1 x64 Checked Innerloop Build and Test
test CentOS7.1 x64 Debug Innerloop Build
test OSX10.12 x64 Checked Innerloop Build and Test
test Ubuntu arm64 Cross Debug Innerloop Build
test Ubuntu x64 Checked Innerloop Build and Test
test Ubuntu x64 Innerloop Formatting
test Windows_NT arm Cross Debug Innerloop Build
test Windows_NT arm Cross Release Innerloop Build and Test
test Windows_NT arm Cross Release r2r Build and Test
test Windows_NT x64 Checked Innerloop Build and Test
test Windows_NT x64 Innerloop Formatting

**Comment by BruceForstall** [comment]
@dotnet-bot test this please

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked jitstress1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs0x10 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs0x1000 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs0x80 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs3 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs4 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs8 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs0x10 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs0x1000 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs0x80 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs3 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs4 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstressregs8 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked minopts Build and Test
@dotnet-bot test Windows_NT arm Cross Checked tailcallstress Build and Test
@dotnet-bot test Windows_NT arm Cross Checked zapdisable Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT armlb Cross Checked jitstress1 Build and Test
@dotnet-bot test Windows_NT armlb Cross Checked jitstress2 Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot help

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked r2r Build and Test
@dotnet-bot test Windows_NT arm Cross Checked r2r_jitminopts Build and Test
@dotnet-bot test Windows_NT arm Cross Checked r2r_jitstress1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked r2r_jitstress2 Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked r2r Build and Test
@dotnet-bot test Windows_NT arm Cross Checked r2r_jitstress1 Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked r2r Build and Test

**Comment by sandreenko** [comment]
ci deleted the last results. Lets run them again.
@dotnet-bot test Windows_NT arm Cross Checked r2r Build and Test
@dotnet-bot test Windows_NT arm Cross Checked r2r_jitminopts Build and Test
@dotnet-bot test Windows_NT arm Cross Checked r2r_jitstress1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked r2r_jitstress2 Build and Test

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT arm Cross Checked r2r_jitstress1 Build and Test

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT arm Cross Checked r2r Build and Test
@dotnet-bot test Windows_NT arm Cross Checked r2r_jitminopts Build and Test
@dotnet-bot test Windows_NT arm Cross Checked r2r_jitstress1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked r2r_jitstress2 Build and Test

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT arm Cross Checked r2r Build and Test

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT arm Cross Checked r2r_jitstress1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked r2r_jitstress2 Build and Test

**Comment by sandreenko** [comment]
@dotnet-bot help

**Comment by BruceForstall** [comment]
@dotnet-bot help

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstress1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs0x10 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs0x1000 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs0x80 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs3 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs4 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs8 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_minopts Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstress1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs0x10 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs0x1000 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs0x80 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs3 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs4 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs8 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_minopts Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstress1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs0x10 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs0x1000 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs0x80 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs3 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs4 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs8 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_minopts Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu x64 Checked corefx_baseline

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu x64 Checked corefx_baseline
@dotnet-bot test Windows_NT arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Windows_NT x64 Checked corefx_baseline
@dotnet-bot test Windows_NT x64_arm64_altjit Checked corefx_baseline
@dotnet-bot test Windows_NT x86 Checked corefx_baseline
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_baseline

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstress1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs0x10 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs0x1000 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs0x80 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs1 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs2 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs3 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs4 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_jitstressregs8 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked corefx_minopts Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test this please

**Pull request closed without merging**
