### PR TITLE
[ARM64] genSIMDIntrinsicInit contain 0

### PR DESCRIPTION
**Pull request by sdmaclea**
First of PR replacing #14637 

@dotnet/jit-contrib @dotnet/arm64-contrib PTAL

### CODE REVIEW

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by jkotas** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test please
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test please
@dotnet-bot test Windows_NT armlb Cross Checked Innerloop Build and Test please

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by CarolEidt** [comment]
armlb failure is not a concern - these are ARMARCH/RyuJIT only files.
arm failures are known.

**Pull request merged**
