### PR TITLE
Add more lldbplugin/libsosplugin tests

### PR DESCRIPTION
**Pull request by sam-baravy**
This pull request is to extend existing lldbplugin/libsosplugin test framework.
Framework architecture and basic test cases are covered at the moment.

### CODE REVIEW

**Comment by sam-baravy** [comment]
@Dmitri-Botcharnikov, @mikem8361

**Comment by mikem8361** [comment]
LGTM but I don't know python.

**Comment by Dmitri-Botcharnikov** [comment]
@kvochko @lucenticus @seanshpark @chunseoklee

**Comment by Dmitri-Botcharnikov** [comment]
LGTM

**Comment by mikem8361** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build and Test

**Comment by Dmitri-Botcharnikov** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build and Test

**Comment by danmosemsft** [comment]
Freshening up test run so hopefully we can close this PR>
@dotnet-bot test this please

**Comment by danmosemsft** [comment]
@dotnet-bot test this please ('remoting error')

**Comment by danmosemsft** [comment]
@dotnet-bot test OSX x64 checked build and test ("12:52:33 FATAL: Failed to copy /jenkins/jobs/dotnet_coreclr/jobs/master/jobs/checked_windows_nt_bld_prtest/builds/1263/archive/bin/tests/tests.zip to /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/checked_osx_tst_prtest/bin/tests/tests.zip" .. @mmitche any idea ?)

**Comment by danmosemsft** [comment]
@mmitche can you make sense of these two? neither finished but they didn't time out either.

**Comment by stephentoub** [comment]
> @mmitche can you make sense of these two? neither finished but they didn't time out either.

Looks like Jenkins rebooted while they were in progress.

**Comment by mmitche** [comment]
@danmosemsft Part of a restart (items were in the queue when they were cancelled)

**Comment by mmitche** [comment]
Actually the ubuntu one finished.  It probably hit rate limiting issues and couldn't update GH.

**Comment by danmosemsft** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test  (no log)
@dotnet-bot  test OSX x64 Checked Build and Test  (no log)

**Comment by danmosemsft** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test (no log)
@dotnet-bot test OSX x64 Checked Build and Test (no log)

**Comment by mmitche** [comment]
@danmosemsft FYI all GH hooks, login and such across multiple servers appears down (this may be related to a GH DNS attack)

**Comment by mmitche** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test (no log)
@dotnet-bot test OSX x64 Checked Build and Test (no log)

**Pull request merged**
