### PR TITLE
Port of #12563 to release/2.0.0

### PR DESCRIPTION
**Pull request by swgillespie**
Port of PR #12563 (fixing issue #12560) to release/2.0.0 for shiproom approval.

### CODE REVIEW

**Comment by Petermarcu** [comment]
@dotnet-bot test FreeBSD x64 Checked Build please

**Comment by Petermarcu** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test please

**Comment by Petermarcu** [comment]
@dotnet-bot test Tizen armel Cross Release Build please

**Comment by swgillespie** [comment]
@dotnet-bot test FreeBSD x64 Checked Build
@dotnet-bot test OSX10.12 x64 Checked Build and Test

**Comment by swgillespie** [comment]
@dotnet-bot test FreeBSD x64 Checked Build

**Comment by swgillespie** [comment]
@Petermarcu should I merge this or leave it up to shiproom? Looks like it's good to go here.

**Comment by Petermarcu** [comment]
@swgillespie normally people merge once they have approval and CI is green. That said, I just merged :)

**Comment by swgillespie** [comment]
I usually do that for master, but I figured if there's any branch I don't want to rock, it's this one 😄

**Pull request merged**
