### PR TITLE
Initial changes to move JIT stress jobs into jitstress directory on CI

### PR DESCRIPTION
**Pull request by sejongoh**
Add jitstress2_jitstressregs1 scenario first and then will add others after testing.

### CODE REVIEW

**Comment by sejongoh** [comment]
@mmitche Could you take a look? I added only one scenario to see if this works well.

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
Fancy: http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/GenPRTest/job/jitstress/

**Comment by mmitche** [comment]
The only question here is whether you will need to delete the old jobs later (whether they will know they were not generated). We can cross that bridge later though.

**Comment by sejongoh** [comment]
I think that we can delete the old jobs later once new jobs are stabilized and get some green history. 

cc @RussKeldorph

**Comment by RussKeldorph** [comment]
Nice.  If it's that easy, we should move the PR jobs to their own folder ASAP. :)  LGTM.

**Pull request merged**
