### PR TITLE
Launch perf process with high priority

### PR DESCRIPTION
**Pull request by DrewScoggins**
This change uses the stability prefix flag that was already in
run-xunit-perf to pass flags to set the affinity of the process to a
single processor and to run the process at high priority.

### CODE REVIEW

**Comment by DrewScoggins** [comment]
test ci please

**Comment by DrewScoggins** [comment]
test ci please

**Comment by DrewScoggins** [comment]
PTAL @jorive

**Comment by jorive** [comment]
test ci please

**Comment by jorive** [comment]
LGTM

**Pull request merged**
