### PR TITLE
Added version increment for TrimExcess and EnsureCapacity

### PR DESCRIPTION
**Pull request by davidkaya**
Relates dotnet/corefx#31062 and dotnet/corefx#31007.

### CODE REVIEW

**Comment by jkotas** [comment]
Could you please add the invalidated test to https://github.com/dotnet/coreclr/blob/master/tests/CoreFX/CoreFX.issues.json to make the CI green

**Comment by davidkaya** [comment]
It seems that I have not excluded all of the old unit test's generic combinations, I will exclude them tomorrow.

**Comment by davidkaya** [comment]
@jkotas It look like those builds are stuck on something. Any idea what could happened?

**Comment by danmosemsft** [comment]
ARM legs always seem finicky. Let's try again:
@dotnet-bot test Tizen armel Cross Checked Innerloop Build and Test

Although I think we can ignore them.

**Pull request merged**
