### PR TITLE
Allow CORINFO_BOX_THIS for primitives and enums

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
We abort R2R compiling methods with `thisTransform == CORINFO_BOX_THIS`. This means we don't R2R compile some methods that do virtual calls on valuetypes (e.g. calling `ToString` on a struct that doesn't itself provide a `ToString` method).

We can't allow this in general, but enums and primitives should be fine.

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
@davidwrighton This is the reason why we were spending 7 ms JITting the CreateManifestString method...

Cc @sergiy-k

**Comment by jkotas** [comment]
Adding a new `ToString` override is a valid version compatible change. If the R2R code is compiled against the old reference and run against the new reference, is the override still going to be called correctly?

**Comment by jkotas** [comment]
It would be nice to add coverage for whatever we do here to https://github.com/dotnet/coreclr/tree/master/tests/src/readytorun/tests

**Comment by MichalStrehovsky** [comment]
> Adding or removing `ToString` override is a valid IL compatible change. If the R2R code is compiled against the old reference and run against the new reference, is the override still going to be called correctly?

It should be. This will be generated as a regular virtual call after this change. The only difference would be that the boxing becomes unnecessary if a `ToString` override gets added on the value type. The boxing should not be visible though because valuetypes are not allowed to have finalizers.

Your concern would be more applicable if we get DEREF_THIS at compile time (because there is a ToString override) and someone removes the ToString override from the valuetype later. I didn't look at whether this is something that can happen, but it seems orthogonal to this problem.

**Comment by jkotas** [comment]
> valuetypes are not allowed to have finalizers.

But they are allowed to have state. Boxing will make the state visibile.

We have hit similar problem with marking `Nullable<T>` as readonly: https://github.com/dotnet/corefx/issues/24900

It is fine to allow this for valuetypes in the same version bubble; or for valuetypes that are known to be immutable like enums. I think allowing this wholesale is a slippery slope.

> CreateManifestString 

The problem with this specific method can be also fixed by letting `Append` to call `ToString` and not do it in the method itself.

**Comment by MichalStrehovsky** [comment]
> It is fine to allow this for valuetypes in the same version bubble; or for valuetypes that are known to be immutable like enums. I think allowing this wholesale is a slippery slope.

Restricted this to enums and primitive types. Enums is all that I really need.

**Pull request merged**
