### PR TITLE
ARM64: Update email notification2

### PR DESCRIPTION
**Pull request by kyulee1**
Only for arm64 group.

### CODE REVIEW

**Comment by kyulee1** [comment]
@dotnet-bot test ci

**Comment by kyulee1** [comment]
@mmitche Is this right syntax to send email only to arm64 group? PTAL

**Comment by mmitche** [comment]
maaaybe? :) Not sure but looks like a fine experiment.

**Comment by kyulee1** [comment]
Okay. Then I will experiment with arm64 PR first to see if a failing notification is sent to only this group, and then follow-up another commit to make it for push only.

**Pull request merged**
