### PR TITLE
We need to have seg_mapping_table aligned on its natural alignement

### PR DESCRIPTION
**Pull request by Maoni0**
When it's not aligned, aside from the perf problem, we also have a functional problem when an address that's not on a heap segment is passed - we could read an intermediate value which would cause an AV. If the address is on a heap segment it means we are guaranteed to read a ptr size atomically. This only affects functions like IsHeapPointer which can be run when EE is not suspended.

### CODE REVIEW

**Comment by Maoni0** [comment]
@sergiy-k @swgillespie PTAL

**Comment by Maoni0** [comment]
@dotnet-bot test Windows_NT Release gcsimulator
@dotnet-bot test Windows_NT Release longgc

**Comment by Maoni0** [comment]
@dotnet-bot test Ubuntu Release gcsimulator
@dotnet-bot test Ubuntu Release longgc
@dotnet-bot test OSX Release gcsimulator
@dotnet-bot test OSX Release longgc

**Comment by swgillespie** [comment]
@dotnet-bot test Ubuntu Release gcsimulator

**Comment by sergiy-k** [comment]
LGTM

**Comment by swgillespie** [comment]
LGTM. The Ubuntu failures are from tests getting killed by the OOM killer and the Windows failure is from one GCSimulator test timing out, which is not uncommon - I've been bumping the timeout recently to cover GCSimulator tests but it looks like I'll just need to disable that one.

**Pull request merged**
