### PR TITLE
Use Alpine container with Node.js in Azure DevOps

### PR DESCRIPTION
**Pull request by echesakovMSFT**
Use an alpine container with node built from source (microsoft/dotnet-buildtools-prereqs:alpine-3.6-WithNode-f4d3fe3-2018121300501)

Testing in https://dnceng.visualstudio.com/public/_build/results?buildId=59687
/cc: @safern

### CODE REVIEW

**Comment by echesakovMSFT** [comment]
@safern As soon as the Linux_musl build jobs are succeeded I will push commit enabling this in publish step as well. Thanks

**Comment by echesakovMSFT** [comment]
Got the build failing with 
```
2018-12-17T19:26:52.4028429Z Invoking "/__w/1/s/src/pal/tools/gen-buildsys-clang.sh" "/__w/1/s" 3 "9" x64 Debug   -DCLR_CMAKE_TARGET_OS=Linux -DCLR_CMAKE_PACKAGES_DIR=/__w/1/s/packages -DCLR_CMAKE_PGO_INSTRUMENT=0 -DCLR_CMAKE_OPTDATA_VERSION=99.99.99-master-20181210-0037 -DCLR_CMAKE_PGO_OPTIMIZE=1 
2018-12-17T19:26:52.4974763Z -- The C compiler identification is Clang 4.0.0
2018-12-17T19:26:52.5607461Z -- The CXX compiler identification is Clang 4.0.0
2018-12-17T19:26:52.5673690Z -- Check for working C compiler: /usr/bin/clang
2018-12-17T19:26:52.6297956Z -- Check for working C compiler: /usr/bin/clang -- works
2018-12-17T19:26:52.6312599Z -- Detecting C compiler ABI info
2018-12-17T19:26:52.6952678Z -- Detecting C compiler ABI info - done
2018-12-17T19:26:52.7077410Z -- Detecting C compile features
2018-12-17T19:26:52.8960029Z -- Detecting C compile features - done
2018-12-17T19:26:52.9012915Z -- Check for working CXX compiler: /usr/bin/clang++
2018-12-17T19:26:52.9733621Z -- Check for working CXX compiler: /usr/bin/clang++ -- works
2018-12-17T19:26:52.9746131Z -- Detecting CXX compiler ABI info
2018-12-17T19:26:53.0588511Z -- Detecting CXX compiler ABI info - done
2018-12-17T19:26:53.0716266Z -- Detecting CXX compile features
2018-12-17T19:26:53.4386433Z -- Detecting CXX compile features - done
2018-12-17T19:26:53.4408879Z -- Performing Test HAVE_LTO
2018-12-17T19:26:53.5015118Z -- Performing Test HAVE_LTO - Failed
2018-12-17T19:26:53.5033406Z -- The ASM compiler identification is Clang
2018-12-17T19:26:53.5040173Z -- Found assembler: /usr/bin/clang
2018-12-17T19:26:53.5091160Z Detected Linux x86_64
2018-12-17T19:26:53.5146714Z -- Performing Test HAVE_UDAT_STANDALONE_SHORTER_WEEKDAYS
2018-12-17T19:26:53.7771722Z -- Performing Test HAVE_UDAT_STANDALONE_SHORTER_WEEKDAYS - Success
2018-12-17T19:26:53.7784565Z -- Looking for ucol_setMaxVariable
2018-12-17T19:26:54.0525312Z -- Looking for ucol_setMaxVariable - found
2018-12-17T19:26:54.0555177Z -- LLDB_LIB: 
2018-12-17T19:26:54.0577064Z CMake Error at src/ToolBox/SOS/lldbplugin/CMakeLists.txt:120 (message):
2018-12-17T19:26:54.0577594Z   Cannot find LLDB.h Try installing lldb-3.9-dev (or the appropriate package
2018-12-17T19:26:54.0577773Z   for your platform).  You may need to set LLVM_HOME or LLDB_INCLUDE_DIR if
2018-12-17T19:26:54.0578297Z   the build still can't find it.
2018-12-17T19:26:54.0578389Z 
```
seems that LLDB dependency is missing

**Comment by safern** [comment]
You would need to submit a PR to our repo containing the docker images to add lldb. This is the one you will want to add it to, since the one containing node is built on top of this one: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/master/src/alpine/3.6/Dockerfile

**Comment by echesakovMSFT** [comment]
From reading https://github.com/dotnet/diagnostics/issues/73 and https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/55 seems that there is an issue with lldb on Alpine.

**Comment by echesakovMSFT** [comment]
Is it possible to disable building libsosplugin.so from build.sh?

**Comment by echesakovMSFT** [comment]
It seems that what was recommended in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/55#issuecomment-406112919 works
```bash
/ # echesako@echesako2:~$ docker run --rm -it alpine:3.6
/ # apk update
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
v3.6.3-56-ge3af38305d [http://dl-cdn.alpinelinux.org/alpine/v3.6/main]
v3.6.3-57-gfd0de89d0b [http://dl-cdn.alpinelinux.org/alpine/v3.6/community]
OK: 8439 distinct packages available
/ # apk -X https://uk.alpinelinux.org/alpine/edge/main add --no-cache llvm
fetch https://uk.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
WARNING: This apk-tools is OLD! Some packages might not function properly.
(1/5) Installing libffi (3.2.1-r5)
(2/5) Installing libgcc (8.2.0-r1)
(3/5) Installing libstdc++ (8.2.0-r1)
(4/5) Installing llvm5-libs (5.0.1-r5)
(5/5) Installing llvm5 (5.0.1-r5)
Executing busybox-1.26.2-r11.trigger
OK: 50 MiB in 18 packages
/ # apk -X https://uk.alpinelinux.org/alpine/edge/testing add --no-cache lldb-dev
fetch https://uk.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
WARNING: This apk-tools is OLD! Some packages might not function properly.
(1/12) Installing ncurses-terminfo-base (6.0_p20171125-r1)
(2/12) Installing ncurses-terminfo (6.0_p20171125-r1)
(3/12) Installing ncurses-libs (6.0_p20171125-r1)
(4/12) Installing libbz2 (1.0.6-r5)
(5/12) Installing expat (2.2.0-r1)
(6/12) Installing gdbm (1.12-r0)
(7/12) Installing readline (6.3.008-r5)
(8/12) Installing sqlite-libs (3.20.1-r2)
(9/12) Installing python2 (2.7.15-r0)
(10/12) Installing libxml2 (2.9.8-r1)
(11/12) Installing lldb (5.0.1-r1)
(12/12) Installing lldb-dev (5.0.1-r1)
Executing busybox-1.26.2-r11.trigger
OK: 139 MiB in 30 packages
/ #
```

**Comment by mikem8361** [comment]
There is a cmake variable called "SKIP_LLDBPLUGIN" that if set, doesn't require the plugin to build. From build.sh there looks like a -cmakeargs option that may work:

    build.sh -cmakeargs SKIP_LLDBPLUGIN

**Comment by janvorli** [comment]
@echesakovMSFT - is this used for official builds? If it is I don't think we want to skip building the plugin, but rather re-enable installation of the lldb-dev package in the docker image. It seems like the issue that we used to have with the package being present only on some CDNs was likely a temporary one.

**Comment by echesakovMSFT** [comment]
@janvorli Yes, this is going to be used for CI **and** official builds. We can include lldb-dev from one of the official mirrors (it appears that root cause is https://bugs.alpinelinux.org/issues/8087)

**Comment by janvorli** [comment]
I've just tried and surprisingly the CDN issue is still there. So yes, let's use other official mirror.

**Comment by echesakovMSFT** [comment]
Updated container name to what was generated in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/70#issuecomment-449132034
Testing in https://dnceng.visualstudio.com/public/_build/results?buildId=61941

**Comment by echesakovMSFT** [comment]
Build Linux_musl x64 jobs succeeded.
Test Linux_musl x64 jobs *almost* succeeded, all the tests got built, the failure happened during one of the last steps - "Creating test overlay" which I doubt related to the container
```
2018-12-20T22:19:56.6047791Z Building step 'Creating test overlay' via "/__w/1/s/run.sh" build -Project=/__w/1/s/tests/runtest.proj -MsBuildLog="/flp:Verbosity=normal;LogFile=/__w/1/s/bin/Logs/Tests_Overlay_Managed.Linux.x64.Checked.log" -MsBuildWrn="/flp1:WarningsOnly;LogFile=/__w/1/s/bin/Logs/Tests_Overlay_Managed.Linux.x64.Checked.wrn" -MsBuildErr="/flp2:ErrorsOnly;LogFile=/__w/1/s/bin/Logs/Tests_Overlay_Managed.Linux.x64.Checked.err" -MsBuildEventLogging="/l:BinClashLogger,Tools/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log" -testOverlay -BuildArch=x64 -BuildType=Checked -BuildOS=Linux 
2018-12-20T22:19:56.6081808Z Running init-tools.sh
2018-12-20T22:19:56.6138816Z Tools are already initialized
2018-12-20T22:19:56.6142321Z Running: /__w/1/s/Tools/dotnetcli/dotnet /__w/1/s/Tools/run.exe /__w/1/s/config.json build -Project=/__w/1/s/tests/runtest.proj -MsBuildLog=/flp:Verbosity=normal;LogFile=/__w/1/s/bin/Logs/Tests_Overlay_Managed.Linux.x64.Checked.log -MsBuildWrn=/flp1:WarningsOnly;LogFile=/__w/1/s/bin/Logs/Tests_Overlay_Managed.Linux.x64.Checked.wrn -MsBuildErr=/flp2:ErrorsOnly;LogFile=/__w/1/s/bin/Logs/Tests_Overlay_Managed.Linux.x64.Checked.err -MsBuildEventLogging=/l:BinClashLogger,Tools/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log -testOverlay -BuildArch=x64 -BuildType=Checked -BuildOS=Linux
2018-12-20T22:19:56.8017725Z Running: /__w/1/s/Tools/msbuild.sh /nologo /verbosity:minimal /clp:Summary  /l:BinClashLogger,Tools/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log  /__w/1/s/tests/runtest.proj /p:__BuildType=Checked /p:__BuildArch=x64 /p:__BuildOS=Linux  /maxcpucount /p:RestoreDefaultOptimizationDataPackage=false /p:UsePartialNGENOptimization=false /p:PortableBuild=true  /flp:Verbosity=normal;LogFile=/__w/1/s/bin/Logs/Tests_Overlay_Managed.Linux.x64.Checked.log  /flp1:WarningsOnly;LogFile=/__w/1/s/bin/Logs/Tests_Overlay_Managed.Linux.x64.Checked.wrn  /flp2:ErrorsOnly;LogFile=/__w/1/s/bin/Logs/Tests_Overlay_Managed.Linux.x64.Checked.err /t:CreateTestOverlay 
2018-12-20T22:19:57.6371177Z /__w/1/s/tests/publishdependency.targets(49,5): error : Your project.json doesn't have a runtimes section. You should add '"runtimes": { "ubuntu.14.04-x64": { } }' to your project.json and then re-run NuGet restore. [/__w/1/s/tests/runtest.proj]
2018-12-20T22:19:57.6720314Z 
2018-12-20T22:19:57.6720739Z Build FAILED.
2018-12-20T22:19:57.6720800Z 
2018-12-20T22:19:57.6727108Z /__w/1/s/tests/publishdependency.targets(49,5): error : Your project.json doesn't have a runtimes section. You should add '"runtimes": { "ubuntu.14.04-x64": { } }' to your project.json and then re-run NuGet restore. [/__w/1/s/tests/runtest.proj]
2018-12-20T22:19:57.6727436Z     0 Warning(s)
2018-12-20T22:19:57.6727567Z     1 Error(s)
2018-12-20T22:19:57.6727630Z 
```

**Comment by jashook** [comment]
The error you are seeing normally is related to the RID being used to pull packages. It would not surprise me that this has yet to have been done on alpine.

**Comment by sbomer** [comment]
Merged this since the build is working (the tests are still being investigated). This gets us closer to enabling corefx to consume our new official builds: https://github.com/dotnet/corefx/pull/34169.
Thanks @echesakov!

**Pull request merged**
