### PR TITLE
Remove replaced Span/ReadOnlySpan methods.

### PR DESCRIPTION
**Pull request by ianhays**
Continuation of https://github.com/dotnet/coreclr/pull/15941

This PR removes the old functions that are no longer being exposed in corefx as of the merging of https://github.com/dotnet/corefx/pull/26467.

cc: @ahsonkhan @stephentoub

### CODE REVIEW

**Comment by jkotas** [comment]
Could you please also delete `DangerousGetPinnableReference` while you are on it?

**Comment by jkotas** [comment]
The few places that started using it again should just use `_pointer.Value` directly.

**Comment by ianhays** [comment]
>Could you please also delete DangerousGetPinnableReference while you are on it?

Sure thing, done.

**Comment by ianhays** [comment]
It would appear that some of the tests are using an older version of system.private.corelib. I'm getting errors that functions I added last week aren't available:
```
SpanBench.cs(509,42): error CS0117: 'MemoryMarshal' does not contain a definition for 'CreateSpan' [D:\j\workspace\x64_checked_w---76911707\tests\src\JIT\Performance\CodeQuality\Span\SpanBench.csproj]
SpanBench.cs(1005,44): error CS0117: 'MemoryMarshal' does not contain a definition for 'Cast' [D:\j\workspace\x64_checked_w---76911707\tests\src\JIT\Performance\CodeQuality\Span\SpanBench.csproj]
```

**Comment by jkotas** [comment]
Yes, you need to get https://github.com/dotnet/coreclr/pull/16091 through first.

**Comment by ianhays** [comment]
Ah, that explains it. Thanks. I'll push the test change to that PR

**Pull request closed without merging**
