### PR TITLE
Disable special put args for LIMIT_CALLER on x86.

### PR DESCRIPTION
**Pull request by pgavlin**
On x86, `LSRA_LIMIT_CALLER` is too restrictive to allow the use of special
put args: this stress mode leaves only three registers allocatable--eax,
ecx, and edx--of which the latter two are also used for the first two
integral arguments to a call. This can leave us with too few registers to
succesfully allocate in situations like the following:

    t1026 =    lclVar    ref    V52 tmp35        u:3 REG NA <l:$3a1, c:$98d>

            /--*  t1026  ref
    t1352 = *  putarg_reg ref    REG NA

     t342 =    lclVar    int    V14 loc6         u:4 REG NA $50c

     t343 =    const     int    1 REG NA $41

            /--*  t342   int
            +--*  t343   int
     t344 = *  +         int    REG NA $495

     t345 =    lclVar    int    V04 arg4         u:2 REG NA $100

            /--*  t344   int
            +--*  t345   int
     t346 = *  %         int    REG NA $496

            /--*  t346   int
    t1353 = *  putarg_reg int    REG NA

    t1354 =    lclVar    ref    V52 tmp35         (last use) REG NA

            /--*  t1354  ref
    t1355 = *  lea(b+0)  byref  REG NA

Here, the first `putarg_reg` would normally be considered a special put arg,
which would remove `ecx` from the set of allocatable registers, leaving
only `eax` and `edx`. The allocator will then fail to allocate a register
for the def of `t345` if arg4 is not a register candidate: the corresponding
ref position will be constrained to { `ecx`, `ebx`, `esi`, `edi` }, which
`LSRA_LIMIT_CALLER` will further constrain to `ecx`, which will not be
available due to the special put arg.

Fixes VSO 299202.

### CODE REVIEW

**Comment by pgavlin** [comment]
@CarolEidt @sivarv @dotnet/jit-contrib PTAL

**Comment by sivarv** [comment]
Looks good to me.
(Discussed this offline with @pgavlin).

**Comment by pgavlin** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build and Test

**Comment by CarolEidt** [comment]
I may not be remembering this correctly, but I thought that the `isSpecialPutArg` was created for correctness reasons - due to the fact that the `GT_PUT_ARG` is basically a pass-through, and if its operand is a `GT_LCL_VAR` this can mess with the effective live range. I would strongly recommend putting this through the various modes of JitStressRegs to validate.

**Comment by pgavlin** [comment]
@CarolEidt: this only disables `isSpecialPutArg` for `JitStressRegs=2`. I will run all variations of that stress mode.

@dotnet-bot test Windows_NT x86 checked jitstressregs2
@dotnet-bot test Windows_NT x86 checked jitstress2_jitstressregs2

**Comment by pgavlin** [comment]
There are also a couple of other obvious approaches we could take to fix this issue:
1. We could attempt to widen the set of allocatable registers only in this specific case
2. We could widen `JitStressRegs=2` on x86 to include one additional register

The former is likely to be somewhat elaborate and may not catch all of the problematic cases (e.g. a `rep stosb` that occurs when special put args exist for `ecx` and `edx` could be problematic), while the latter seems to diminish the value of this stress mode.

**Comment by pgavlin** [comment]
Regarding `isSpecialPutArg` being related to correctness: I did verify that the RA correctly marks the expected nodes for spilling, and that these nodes are reloaded at the point of use:

```
Generating: N633 (  1,  1) [001026] -----------Z             *  lclVar    ref    V52 tmp35        u:3 ecx REG ecx RV <l:$3a1, c:$98d>
Generating: N635 (???,???) [001352] -----------Z             *  putarg_reg ref    REG ecx
IN00af:        mov      gword ptr [V52 ebp-17CH], ecx
							V52 in reg ecx is becoming dead  [001026]
							Live regs: 00000002 {ecx} => 00000000 {}
							GC regs: 00000002 {ecx} => 00000000 {}
							Var V52 becoming live
reused temp #1, slot 0, size = 4
							The register ecx spilled with    [001352]
IN00b0:        mov      gword ptr [TEMP_01 ebp-184H], ecx
Generating: N637 (  1,  1) [000342] -----------z             *  lclVar    int    V14 loc6         u:4 REG eax $50c
Generating: N639 (  1,  1) [000343] ------------             *  const     int    1 REG NA $41
Generating: N641 (  3,  3) [000344] ------------             *  +         int    REG eax $495
IN00b1:        mov      eax, dword ptr [V14 ebp-38H]
IN00b2:        inc      eax
Generating: N643 (  3,  2) [000345] ------------             *  lclVar    int    V04 arg4         u:2 REG ecx $100
IN00b3:        mov      ecx, dword ptr [V04 ebp+14H]
Generating: N645 ( 26,  8) [000346] ---X--------             *  %         int    REG edx $496
IN00b4:        cdq      
IN00b5:        idiv     edx:eax, ecx
Generating: N647 (???,???) [001353] ---X--------             *  putarg_reg int    REG edx
Generating: N649 (  1,  1) [001354] -----------z             *  lclVar    ref    V52 tmp35         (last use) REG ecx
Generating: N651 (  2,  2) [001355] ------------             *  lea(b+0)  byref  REG NA
Generating: N653 (  5,  4) [001356] ------------             *  indir     int    REG ecx
IN00b6:        mov      ecx, gword ptr [V52 ebp-17CH]
							Removing V52 from gcVarPtrSetCur
							V52 in reg ecx is becoming live  [001354]
							Live regs: 00000000 {} => 00000002 {ecx}
							GC regs: 00000000 {} => 00000002 {ecx}
							V52 in reg ecx is becoming dead  [001354]
							Live regs: 00000002 {ecx} => 00000000 {}
							Live vars: {V00 V01 V02 V03 V04 V05 V06 V07 V09 V10 V11 V14 V52 V59} => {V00 V01 V02 V03 V04 V05 V06 V07 V09 V10 V11 V14 V59}
							GC regs: 00000002 {ecx} => 00000000 {}
IN00b7:        mov      ecx, dword ptr [ecx]
Generating: N655 (  6,  5) [001357] ------------             *  lea(b+48) int    REG NA
Generating: N657 (  9,  7) [001358] ------------             *  indir     int    REG eax
IN00b8:        mov      eax, dword ptr [ecx+48]
Generating: N659 ( 10,  8) [001359] ------------             *  lea(b+12) int    REG NA
Generating: N661 ( 13, 10) [001360] ------------             *  indir     int    REG NA
Generating: N663 ( 87, 43) [000347] -ACXG-------             *  callv ind ref    System.Collections.ArrayList.get_Item $98f
							Tree-Node marked unspilled from  [001352]
IN00b9:        mov      ecx, gword ptr [TEMP_01 ebp-184H]
release temp #1, slot 0, size = 4
							GC regs: 00000000 {} => 00000002 {ecx}
							GC regs: 00000002 {ecx} => 00000000 {}
							Call: GCvars=0000008080000008 {V09 V10 V11}, gcrefRegs=00000000 {}, byrefRegs=00000000 {}
IN00ba:        call     gword ptr [eax+12]System.Collections.ArrayList:get_Item(int):ref:this
```

The `putarg_reg` is spilled by `IN00b0` and reloaded by `IN00b9`.

**Pull request merged**
