### PR TITLE
Fix hang on Ctrl+C when tiering is enabled

### PR DESCRIPTION
**Pull request by kouvel**
- When the work thread count is nonzero at the time of Ctrl+C, by the time `TieredCompilationManager::Shutdown(BOOL)` runs (during `DllMain` for process detach), the background worker thread has already been torn down abruptly and it does not get a chance to exit gracefully and set the event, and Shutdown() hangs the process waiting for the event forever.
- It looks like there is no benefit to waiting for the work to complete, fixed by removing the wait and the event
- In the MusicStore benchmark it looks like the arch folder was missing in the 'publish' folder path. In case there is a difference in bin directory layout between the CI dotnet and current dotnet, changed to check for both paths.

### CODE REVIEW

**Comment by noahfalk** [comment]
what causes the threadpool threads to die? I was searching around for code that appeared to shutdown the threadpool but I must have missed it.

**Comment by kouvel** [comment]
I think the OS does all of that. According to https://msdn.microsoft.com/en-us/library/windows/desktop/ms686722(v=vs.85).aspx:
> For console processes, the default console control handler calls ExitProcess when the console receives a CTRL+C or CTRL+BREAK signal.

And according to https://msdn.microsoft.com/en-us/library/windows/desktop/ms682658(v=vs.85).aspx:
> - All of the threads in the process, except the calling thread, terminate their execution without receiving a DLL_THREAD_DETACH notification.
> - The states of all of the threads terminated in step 1 become signaled.
> - The entry-point functions of all loaded dynamic-link libraries (DLLs) are called with DLL_PROCESS_DETACH.
> - After all attached DLLs have executed any process termination code, the ExitProcess function terminates the current process, including the calling thread.

**Comment by noahfalk** [comment]
In that case it seems like we'd want to avoid invoking TieredCompilationManager::ShutdownAllDomains at all. Shutdown still acquires the SpinLock and if the threads were terminated I assume the SpinLock could be unaquirable. Perhaps?

    EEShutdownHelper(BOOL fIsDllUnloading)
    {
        ...
        if(!fIsDllUnloading)
        {
            GCX_PREEMP();
            TieredCompilationManager::ShutdownAllDomains();
        }
        ...
    }

I'm hesitant to eliminate the cooperative shutdown that is occurring in the other cases - it seems like we could be opening the door to other issues where we've left our background thread running inside the AppDomain at the same time the AppDomain unload code on the foreground thread is racing to destroy the domain?

**Comment by kouvel** [comment]
> In that case it seems like we'd want to avoid invoking TieredCompilationManager::ShutdownAllDomains

That's true, it should actually be unnecessary to call Shutdown at all.

> Shutdown still acquires the SpinLock and if the threads were terminated I assume the SpinLock could be unaquirable. Perhaps?

Indeed it seems like any lock or wait during process detach would be prone to issues

> I'm hesitant to eliminate the cooperative shutdown that is occurring in the other cases - it seems like we could be opening the door to other issues where we've left our background thread running inside the AppDomain at the same time the AppDomain unload code on the foreground thread is racing to destroy the domain?

For Core it shouldn't be an issue. I think even during graceful shutdown background threads would be abruptly torn down, as we only wait for non-background threads to finish gracefully. So long as the work being done is on a background thread, there shouldn't be a need to gracefully complete that work (it would be ideal to do so anyway, but if that's the desire then we should do that work on a non-background and hence non-threadpool thread but ctrl+c case is still an issue, where the only reasonable resolution would be to always override the default ctrl+c handler with custom shutdown logic).

As for AppDomain unload on the desktop framework, I don't know what is involved there, but I would hope that it would not be able to complete the (at least asynchronous) unload without waiting for all threads that are holding references to objects in, or running code in, that AppDomain. If there's an issue to be worried about there that would be a design issue with AppDomain unload, so I expect that it is taken care of properly.

**Comment by kouvel** [comment]
At least conceptually it looks like it would work with AppDomain unload without races:
- After `RestrictThreadEntrance` (https://github.com/dotnet/coreclr/blob/master/src/vm/appdomain.cpp#L8037), trying to enter the domain here (https://github.com/dotnet/coreclr/blob/master/src/vm/tieredcompilation.cpp#L461) would throw
- Then, `UnwindThreads` is called (https://github.com/dotnet/coreclr/blob/master/src/vm/appdomain.cpp#L8048) and it waits for any threads that had entered the domain to exit

**Comment by kouvel** [comment]
>> In that case it seems like we'd want to avoid invoking TieredCompilationManager::ShutdownAllDomains

> That's true, it should actually be unnecessary to call Shutdown at all.

On second thought Shutdown is still necessary for the appdomain exit case, I'll just remove ShutdownAllDomains

**Comment by kouvel** [comment]
OSX failure: https://github.com/dotnet/core-eng/issues/2808

**Pull request merged**
