### PR TITLE
Change IBC package layout to match what we generate

### PR DESCRIPTION
**Pull request by adiaaida**
We now produce the packages in the data/<AssemblyName> directory, so fix this in coreclr's build.

### CODE REVIEW

**Comment by adiaaida** [comment]
The optimization repo PR is in, so once we get the maestro update with the new packages, I will do a quick test to make sure that we are applying the data, and this can be committed.

**Comment by jkoritzinsky** [comment]
@dotnet-bot test this please

**Comment by jkoritzinsky** [comment]
@dotnet-bot test Ubuntu x64 Checked CoreFX Tests

**Comment by hoyosjs** [comment]
@adiaaida I'm merging this before 12 so that the new package doesn't trip now that the new package is in. 

Cc @jkoritzinsky

**Pull request merged**
