### PR TITLE
Fix corerun issue when loaded from PATH

### LINKED ISSUE #10712: corerun issue when loaded from PATH on Linux
`corerun` works correctly when the current directory is the same as the one in which it resides or when an explicit full path is specified. However, when loaded from PATH, an error is emitted. This is similar to #3190 and can be easily fixed in the same way. In fact, this issue was pointed out there but was only fixed for `ildasm`.

### PR DESCRIPTION
**Pull request by hadibrais**
Fixes #10712

### CODE REVIEW

**Comment by janvorli** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by janvorli** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test please

**Comment by janvorli** [comment]
@dotnet-bot test Ubuntu16.04 arm Cross Debug Build please

**Comment by janvorli** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test please

**Comment by janvorli** [comment]
@hadibrais it looks like you've made a mistake when rebasing your local state or merging changes from the upstream master.

**Comment by hadibrais** [comment]
@janvorli Yep, sorry. I think everything is fine now.

**Comment by danmosemsft** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test  (network)

**Pull request merged**
