### PR TITLE
[Arm64/Win] Revise JIT_MemCpy

### PR DESCRIPTION
**Pull request by sdmaclea**
This is the Windows equivalent of #11143 which merged

### CODE REVIEW

**Comment by sdmaclea** [comment]
@jkotas This is a cut, paste, and tweak for asm format from #11143

**Comment by sdmaclea** [comment]
@jkotas Note I have not assembled this on Windows Arm64.  Relying on Windows arm64 leg to catch any problem.

cc @dotnet/arm64-contrib

**Comment by jkotas** [comment]
@dotnet/arm64-contrib could you please trigger the Windows arm64 leg?

**Comment by jashook** [comment]
@sdmaclea currently the windows arm64 ci is down. I am working to fix it. Until then only debug and release is available and both of these do not run tests.

They will at least give a build.

@dotnet-bot test Windows_NT Arm64 Debug
@dotnet-bot test Windows_NT Arm64 Release

**Comment by sdmaclea** [comment]
@jashook @jkotas Build should be sufficient to test as this was tested on arm64/unix

**Comment by sdmaclea** [comment]
@jashook Looks like Windows arm64 assembler did not like the b.eq / b.gt mnemonics.  I have switched them to beq & bgt which I assume it will handle.  Can you retrigger one arm64 windows build.

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Debug
@dotnet-bot test Windows_NT Arm64 Release

**Comment by sdmaclea** [comment]
@jashook Thanks.  It looks like the Debug trigger "Windows_NT Arm64 Debug" is triggering "Windows_NT x64 Debug Build and Test"

**Comment by jashook** [comment]
@dotnet-bot help

**Comment by jashook** [comment]
Windows_NT arm64 Cross Debug Build

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT arm64 Cross Debug Build

**Comment by jashook** [comment]
@sdmaclea thank you, I had forgotten that changed.

**Comment by sdmaclea** [comment]
arm64 debug build succeeded.  
the arm64 release build was a timeout

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Release

**Comment by sdmaclea** [comment]
@dotnet-bot test Tizen armel Cross Debug Build

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Checked

**Comment by jashook** [comment]
@sdmaclea just giving you a heads up that I am slowly turning the arm64 windows ci back on. For now I will be launching only a few jobs to meticulously monitor them.

/cc @BruceForstall @dotnet/arm64-contrib

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Checked

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by sdmaclea** [comment]
@dotnet/arm64-contrib @jkotas @janvorli ping

**Pull request merged**
