### PR TITLE
Allow FEATURE_INTERPRETER to be enabled by command-line option

### PR DESCRIPTION
**Pull request by parjong**

### CODE REVIEW

**Comment by BruceForstall** [comment]
Who is going to define the cmake `FEATURE_INTERPRETER` variable? What platforms/configurations do you expect to enable the interpreter?

**Comment by BruceForstall** [comment]
cc @dotnet/jit-contrib

**Comment by parjong** [comment]
@BruceForstall I would like to take a look it just for fun.

**Comment by parjong** [comment]
To be more specific, I recently read [this article](http://mattwarren.org/2017/03/30/The-.NET-IL-Interpreter/ ) and am interested in the interpreter internal.

**Comment by BruceForstall** [comment]
Presumably you could just add the
```
add_definitions(-DFEATURE_INTERPRETER)
```
in a private branch. Why do you need to merge this change? I'm no cmake expert: how does merging this change make it easier?

Bottom-line: I don't want there to be any chance the interpreter is accidentally compiled in by default.

**Comment by parjong** [comment]
This PR allows users to enable FEATURE_INTERPERTER using the following command-line:
```
$ ./build.sh cmakeargs "-DFEATURE_INTERPRETER=1"
```
I want to build and test this feature without additional patch, but I also do not want to turn it default. I updated PR to prevent accidental enable that you are currently worry. 

Now, FEATURE_INTERPRETER will be turned off by default if the additional command-line option mentioned above is not provided.

**Comment by mattwarren** [comment]
@parjong glad your found the blog post useful, it was fun to write!]

BTW if you want to get all the statistics printed out at the end of a program run, you also need to make the following changes in `interpreter.h`, I didn't make that clear in the post

``` diff
// If this is set, we keep track of extra information about IL instructions executed per-method.
-#define INTERP_PROFILE 0
+#define INTERP_PROFILE 1

// If this is set, we track the distribution of IL instructions.
-#define INTERP_ILINSTR_PROFILE 0
+#define INTERP_ILINSTR_PROFILE 1
```

**Comment by parjong** [comment]
@mattwarren Thanks you for comment :+1: I'll try.

**Pull request merged**
