### PR TITLE
Fix ICU detection in System.Globalization.Native build

### PR DESCRIPTION
**Pull request by janvorli**
The config.cmake was not getting the ICU library paths it requires to
build a code that detects presence of the ucol_setMaxVariable.
I have excluded the libraries detection from the CMakeLists.txt
some time ago since they are not used in the build itself anymore,
but I have not realized that they are needed for this detection
script that's included from the CMakeLists.txt.

### CODE REVIEW

**Comment by janvorli** [comment]
Fixes #7376

**Comment by janvorli** [comment]
@gkhanna79 can you take a look please?

**Comment by tarekgh** [comment]
LGTM

**Pull request merged**
