### PR TITLE
Fixing some issues with the decimal parser/formatter

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves the two actual issues in https://github.com/dotnet/coreclr/issues/22046.

It was determined that, for `System.Decimal`, `-0` should continue formatting as `0`, so this reverses the early change to this area.
This also fixes the parser so that it considers digits still in the buffer as part of the zero or non-zero tail, when it is important for midpoint rounding.

### CODE REVIEW

**Comment by tannergooding** [comment]
CC. @jkotas, @pentp

**Comment by tannergooding** [comment]
I also called out (see https://github.com/dotnet/coreclr/issues/22046#issuecomment-455630503) a question around the parsing of `-0` (which, in prior releases, was considered different from `-0.0` and `-0.00`). We should determine the appropriate behavior and, if required, include the additional change as part of this PR.

**Comment by pentp** [comment]
After the formatting change, there should be no practical difference between -0 and 0 again, so the parsing question might be a non-issue?

**Comment by tannergooding** [comment]
> After the formatting change, there should be no practical difference between -0 and 0 again, so the parsing question might be a non-issue?

Agreed for the most part. However, it is (from the perspective of the compiler) a breaking change (it impacts the code that is emitted, see https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABADAAmwEYBuAWAChsBmQgJnwGF8BvS/Dw27AFnwFkiAChRwAxgEtIAG3wp8AXnwBaXGACUrdpwC+2jvq6E+/OiPFSIs+UtUA6NZrYVO+PRR1A=). It is also observable to the end-user from `decimal.GetBits`.

I think it is probably a fine change, and if nothing else makes `decimal d = -0m` and `decimal d = 0; d = -0;` produce internally equivalent values. However, we should likely be explicit that this is desirable.

**Comment by pentp** [comment]
I thinks it's fine also - the compiler baseline needs updating anyway because of the more precise remainder calculations. I would go with option that causes less friction.

**Comment by tannergooding** [comment]
test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by tannergooding** [comment]
Tests never updated, retrying.

**Comment by tannergooding** [comment]
test Ubuntu arm Cross Checked Innerloop Build and Test
test Ubuntu arm Cross Checked no_tiered_compilation_innerloop Build and Test
test Ubuntu16.04 arm64 Cross Checked Innerloop Build and Test
test Ubuntu16.04 arm64 Cross Checked no_tiered_compilation_innerloop Build and Test
test Windows_NT arm Cross Debug Innerloop Build
test Windows_NT arm64 Cross Debug Innerloop Build

**Pull request merged**
