### PR TITLE
Remove S.P.C.dll from nuget package

### PR DESCRIPTION
**Pull request by gkhanna79**
@jkotas PTAL

Fixes https://github.com/dotnet/coreclr/issues/10097

### CODE REVIEW

**Comment by gkhanna79** [comment]
Confirmed that Pri1 test build is clean.

**Comment by jkotas** [comment]
tests\src\managed\Compilation\Compilation.cs may need updating - it assumes that there is System.Private.CoreLib.dll. Not sure how many other places like that are there.

It may be better to put the corelib native image into the package as System.Private.CoreLib.dll (consistent with what we are doing for R2R native images).

**Comment by gkhanna79** [comment]
I am doing test run to identify issues from this change - hopefully, this will come through.

With that said, if the IL is required by some tests, I am just wondering if the fix is, instead, to exclude S.P.C.dll from sharedFX package, as opposed to excluding it from CoreCLR nuget package. What do you think @jkotas?

**Comment by jkotas** [comment]
The native image contains the IL. For example, you can `/r:<native image>` on the C# compiler command line just fine. I would love to be in a situation where people just do not need to care that there is .ni.dll suffix sometimes. We are almost there. CoreLib is the only exception as far as I know.

**Pull request closed without merging**
