### PR TITLE
Put back Open key signing on the SOS.NETCore assembly.

### PR DESCRIPTION
**Pull request by mikem8361**
Fix failure in SOS if System.Reflection.Metadata is missing.

### CODE REVIEW

**Comment by mikem8361** [comment]
@jhendrixMSFT @gkhanna79 @weshaggard @joperezr

**Comment by gkhanna79** [comment]
Do we understand if the change was accidentally lost or intentionally?

**Comment by mikem8361** [comment]
Not sure. Jose did the merge.

**Comment by mikem8361** [comment]
Sorry, probably wasn't Jose and that merge.  It may be from this commit:

@ramarag 

Author:		Rama krishnan Raghupathy <ramarag@microsoft.com>
Date:		19 hours ago (8/23/2016 10:18:47 PM)
Committer:	GitHub <noreply@github.com>
Commit hash:	d7821eb792915fa64ff6219c7ce4b9abc195ab7e
Children:	809524536f
Parent(s):	bf5d75d55a 71dd695fae

Merge pull request #6851 from ramarag/unifytestbuild

Changing The way Coreclr Test Builds

**Comment by ramarag** [comment]
git log  src\ToolBox\SOS\NETCore\SOS.NETCore.csproj shows:
commit 69ac976d48950b618993bc7a5e854eb1145c36e3
Author: dotnet bot <dotnet-bot@dotnetfoundation.org>
Date:   Tue Aug 23 12:58:41 2016 -0700

    Add missing .gitmirror file. (#6864)

    [tfs-changeset: 1623730]

reverted the changes to src\ToolBox\SOS\NETCore\SOS.NETCore.csproj

**Comment by pgavlin** [comment]
cc @ellismg, who put together the change.

**Comment by gkhanna79** [comment]
@dotnet-bot test Windows_NT x86 ryujit Checked Build and Test please

**Comment by joperezr** [comment]
@mikem8361 are we only waiting for the CI to be green(not counting Linux ARM Emulator one since that one is broken) to merge this? I ask because looks like we need this to produce coreclr packages again and folks in corefx side are blocked on getting a new one.

**Comment by tarekgh** [comment]
CC myself to get the notification when this get merged as it is blocking.

**Comment by weshaggard** [comment]
Signing part LGTM

**Comment by weshaggard** [comment]
this is blocking coreclr official builds so I'm merging to unblock those builds. Only CI leg failure is Linux ARM Emulator which is not related and the ryujit leg which doesn't seem to be correctly triggering.

**Pull request merged**
