### PR TITLE
Test failure: TwoKeywords: Time Out: Issue #23224

### LINKED ISSUE #23224: Test failure: tracing_keyword._TwoKeywords_TwoKeywords_TwoKeywords_/_TwoKeywords_TwoKeywords_TwoKeywords_cmd
Opened on behalf of @AriNuer

The test `tracing_keyword._TwoKeywords_TwoKeywords_TwoKeywords_/_TwoKeywords_TwoKeywords_TwoKeywords_cmd` has failed.

Failure Message:
```

cmdLine:C:\\dotnetbuild\\work\\594f9a96-809a-4e18-9bd6-6d37ed8c15a9\\Work\\6f602446-99d4-46b8-b5dd-f9b3792db854\\Exec\\TwoKeywords\\TwoKeywords\\TwoKeywords.cmd Timed Out\r


Return code:      -100
Raw output file:      C:\\dotnetbuild\\work\\594f9a96-809a-4e18-9bd6-6d37ed8c15a9\\Work\\6f602446-99d4-46b8-b5dd-f9b3792db854\\Exec\\Reports\\tracing.keyword\\TwoKeywords\\TwoKeywords\\TwoKeywords.output.txt
Raw output:
BEGIN EXECUTION\r
        1 file(s) copied.\r
\" C:\\dotnetbuild\\work\\594f9a96-809a-4e18-9bd6-6d37ed8c15a9\\Payload\\crossgen.exe\"  /Platform_Assemblies_Paths C:\\dotnetbuild\\work\\594f9a96-809a-4e18-9bd6-6d37ed8c15a9\\Payload;C:\\dotnetbuild\\work\\594f9a96-809a-4e18-9bd6-6d37ed8c15a9\\Work\\6f602446-99d4-46b8-b5dd-f9b3792db854\\Exec\\TwoKeywords\\TwoKeywords\\IL;C:\\dotnetbuild\\work\\594f9a96-809a-4e18-9bd6-6d37ed8c15a9\\Work\\6f602446-99d4-46b8-b5dd-f9b3792db854\\Exec\\TwoKeywords\\TwoKeywords /in TwoKeywords.org /out TwoKeywords.exe\r
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0\r
Copyright (c) Microsoft Corporation.  All rights reserved.\r
\r
Native image TwoKeywords.exe generated successfully.\r
 \"C:\\dotnetbuild\\work\\594f9a96-809a-4e18-9bd6-6d37ed8c15a9\\Payload\\corerun.exe\" TwoKeywords.exe \r
Calculated config file path: C:\\dotnetbuild\\work\\594f9a96-809a-4e18-9bd6-6d37ed8c15a9\\Work\\6f602446-99d4-46b8-b5dd-f9b3792db854\\Exec\\TwoKeywords\\TwoKeywords\\TwoKeywords.eventpipeconfig\r
Wrote contents of config file.\r
Waiting 25 seconds for the config file to be picked up by the next poll operation.\r
Do some work that will be captured by the trace.\r
Done with the work.\r
Deleted the config file.\r

cmdLine:C:\\dotnetbuild\\work\\594f9a96-809a-4e18-9bd6-6d37ed8c15a9\\Work\\6f602446-99d4-46b8-b5dd-f9b3792db854\\Exec\\TwoKeywords\\TwoKeywords\\TwoKeywords.cmd Timed Out\r
Test Harness Exitcode is : -100\r

To run the test:
> set CORE_ROOT=C:\\dotnetbuild\\work\\594f9a96-809a-4e18-9bd6-6d37ed8c15a9\\Payload
> C:\\dotnetbuild\\work\\594f9a96-809a-4e18-9bd6-6d37ed8c15a9\\Work\\6f602446-99d4-46b8-b5dd-f9b3792db854\\Exec\\TwoKeywords\\TwoKeywords\\TwoKeywords.cmd
\r
Expected: True\r
Actual:   False
```

Stack Trace:
```
   at tracing_keyword._TwoKeywords_TwoKeywords_TwoKeywords_._TwoKeywords_TwoKeywords_TwoKeywords_cmd() in F:\vsagent\6\s\bin\tests\Windows_NT.arm64.Release\TestWrappers\tracing.keyword\tracing.keyword.XUnitWrapper.cs:line 109
```

Build : 3.0 - 20190312.77 (Ready-To-Run Tests)
Failing configurations:
- Windows.10.Arm64
  - arm64

Details:
https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fr2r~2Fcli~2F/build/20190312.77/workItem/tracing.keyword/analysis/xunit/tracing_keyword._TwoKeywords_TwoKeywords_TwoKeywords_~2F_TwoKeywords_TwoKeywords_TwoKeywords_cmd

### PR DESCRIPTION
**Pull request by jorive**
Fixes #23224

### CODE REVIEW

**Comment by cshung** [comment]
https://github.com/dotnet/coreclr/pull/23237

**Comment by sandreenko** [comment]
I have excluded this test for x86 Windows in https://github.com/dotnet/coreclr/pull/23237 (have not noticed this PR).

**Comment by jorive** [comment]
@sandreenko @cshung Should I close this PR, or keep it, and undo the change in `tests/issues.targets`?

**Comment by hoyosjs** [comment]
I'd privilege the target file as a centralized disable mechanism. The only reason to disable a project build explicitly is if the bug is at msbuild time.

**Comment by sandreenko** [comment]
@jorive I think you can close this PR. Sorry that I had not noticed that.

**Comment by jorive** [comment]
This PR was previously addressed by @sandreenko 's PR

**Pull request closed without merging**
