### PR TITLE
[x86/Linux] Fix LLDB Plugin Build Error

### PR DESCRIPTION
**Pull request by parjong**

### CODE REVIEW

**Comment by parjong** [comment]
\CC @seanshpark @wateret

**Comment by parjong** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test please

**Comment by parjong** [comment]
@jkotas @janvorli Could you let me know who is responsible for LLDB plugin?

**Comment by jkotas** [comment]
cc @mikem8361

**Pull request merged**
