### PR TITLE
Stabilize CoreCLR version to 1.0.5

### PR DESCRIPTION
**Pull request by gkhanna79**
@weshaggard PTAL

CC @leecow

### CODE REVIEW

**Comment by weshaggard** [comment]
cc @ericstj 

Are we preferring the StableVersion property over the separate stable packages list?

**Comment by ericstj** [comment]
That's fine for CoreCLR.  The list is necessary when we also generate references to the specific versions.

**Comment by gkhanna79** [comment]
@weshaggard CoreCLR does not use that file.

**Comment by leecow** [comment]
LGTM

**Pull request merged**
