### PR TITLE
Port some concurrent collection implementations with latest fixes fro…

### PR DESCRIPTION
**Pull request by kouvel**
…m CoreFX into CoreCLR copies

Relevant to https://github.com/dotnet/corefx/pull/22382

Would be better to compare the CoreFX files to the new ones.

### CODE REVIEW

**Comment by stephentoub** [comment]
It looks like this is adding back a bunch of members that were explicitly removed due to not being needed once the tree shaker was disabled on corelib (it had been removing them during the build).

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by karelz** [comment]
What is status of this PR? No update for last 2+ weeks ...

**Comment by kouvel** [comment]
Fixed conflicts and pulled some recent changes, need a review

**Comment by karelz** [comment]
OK, please nominate and/or ping people you need code review from ... @tarekgh might help.

**Comment by tarekgh** [comment]
Looks @stephentoub and @pjanotti were already reviewing it.

**Comment by pjanotti** [comment]
@kouvel and @tarekgh I pulled that into my branch unintentionally, I actually didn't look at it.

**Comment by kouvel** [comment]
Rebased and squashed to simplify resolving merge conflicts. @stephentoub or @tarekgh, could you please take a look? This ports some concurrent collection implementations from CoreFX to CoreCLR, to match the CoreFX implementations as most of the fixes are going into CoreFX.

**Comment by tarekgh** [comment]
LGTM.

**Comment by kouvel** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test
@dotnet-bot test Windows_NT x64 full_opt ryujit CoreCLR Perf Tests Correctness

**Comment by kouvel** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test

**Pull request merged**
