### PR TITLE
IndexOfAny(values.Length == 0) == -1

### PR DESCRIPTION
**Pull request by benaadams**
Resolves https://github.com/dotnet/corefx/issues/32334

### CODE REVIEW

**Comment by benaadams** [comment]
Test updates

**Comment by danmosemsft** [comment]
Thanks @benaadams

**Comment by bartonjs** [comment]
Are all the IndexOfAnys behaving the same now?  It doesn't look like your corefx PR changed this test:

https://github.com/dotnet/corefx/blob/082499823f9a80e1d47b3574743f24d8a1447cfa/src/System.Memory/tests/Span/LastIndexOfSequence.byte.cs#L74-L81

which I think means that for at least some types IndexOfAny(empty) and LastIndexOfAny(empty) aren't matching.

**Comment by benaadams** [comment]
> Are all the IndexOfAnys behaving the same now? It doesn't look like your corefx PR changed this test:

That's IndexOf searching for an empty span (equivalent of `string.IndexOf(string.Empty)`); this is changing IndexOfAny searching for one of a zero set of chars (equivalent of `string.IndexOfAny(new char[]{})`)

`"Hello".IndexOf(string.Empty)` == 0
`"Hello".IndexOfAny(new char[]{})` == -1

**Comment by jkotas** [comment]
Could you please disable the failing tests in https://github.com/dotnet/coreclr/blob/master/tests/CoreFX/CoreFX.issues.rsp

**Comment by benaadams** [comment]
Rebased as I don't have permission to retrigger the pipeline

**Pull request merged**
