### PR TITLE
[Arm64] Add instructions needed by SIMD

### PR DESCRIPTION
**Pull request by sdmaclea**
@dotnet/jit-contrib @dotnet/arm64-contrib PTAL

### CODE REVIEW

**Comment by BruceForstall** [comment]
How did you test this? It's hard to review these kind of things, really.

We have a function, `CodeGen::genArm64EmitterUnitTests()`, that we've used in the past for manual testing of emitter changes, by having it generate all kinds of instructions (in the prolog, or maybe first block), and compare what JitDump says we generated against what a platform disassembler says we generated (on Windows, we used the msvcdis disassembler, but unfortunately that's not open source. You could probably hook up CoreDisTools disassembler for this purpose). It might be useful to add a bunch of your new instructions to this function.

**Comment by sdmaclea** [comment]
@BruceForstall 
Testing
+ Type all instructions
+ Visually verify against ARMv8 ARM
+ Built
+ Use internal disassembler to cross check every encoding using hex codes in patch

My guess is this is 99% accurate.  The second pass required 15% fixes.  The compiler caught one typo.  In the final pass I found and fixed one encoding I missed on the first two passes.

I will test further when I add the emitters and codegen.

I don't mind waiting, but the SIMD code change is becoming large and possibly hard to review.  I am trying to get separable bits uploaded.  At a minimum for general feedback.

**Comment by BruceForstall** [comment]
Thanks for the info. I definitely appreciate splitting the SIMD work into multiple changes, as appropriate.

**Comment by BruceForstall** [comment]
Ignoring CentOS x64 failure

**Pull request merged**
