### PR TITLE
Correct assert w.r.t meaning of lvRegister

### LINKED ISSUE #9898: [Arm64/Unix] Unexpected Crossgen fails
```
Precompiling /home/sdmaclea/overlay.c5dff6f.d/Microsoft.CodeAnalysis.VisualBasic.dll
./tests/runtest.sh: line 397: 26782 Aborted                 $overlayDir/crossgen /Platform_Assemblies_Paths $overlayDir $filename > $filename.stdout 2> $filename.stderr
Unable to precompile /home/sdmaclea/overlay.c5dff6f.d/Microsoft.CodeAnalysis.VisualBasic.dll.
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

ReadyToRun: Implicit boxing for calls to constrained methods not supported

Assert failure(PID 26782 [0x0000689e], Thread: 26782 [0x689e]): Assertion failed '(varDsc->lvIsParam && !varDsc->lvIsRegArg && varDsc->lvRegister) || isPrespilledArg' in 'Microsoft.CodeAnalysis.VisualBasic.Binder:CompleteAggregateClauseBinding(ref,struct,struct,struct,ref,ref,struct,ref,ref,ref,ref):ref:this' (IL size 898)

    File: /home/sdmaclea/git/coreclr/src/jit/compiler.hpp Line: 2345
    Image: /home/sdmaclea/test.c5dff6f.d/Tests/coreoverlay/crossgen

exit 134
```
```
Precompiling /home/sdmaclea/overlay.c5dff6f.d/System.Net.NameResolution.dll
./tests/runtest.sh: line 397: 27263 Aborted                 $overlayDir/crossgen /Platform_Assemblies_Paths $overlayDir $filename > $filename.stdout 2> $filename.stderr
Unable to precompile /home/sdmaclea/overlay.c5dff6f.d/System.Net.NameResolution.dll.
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.


Assert failure(PID 27263 [0x00006a7f], Thread: 27263 [0x6a7f]): Assertion failed 'dsc->TypeGet() == TYP_REF || dsc->TypeGet() == TYP_BYREF' in 'System.Net.InteropIPAddressExtensions:GetIPAddress(struct):ref' (IL size 114)

    File: /home/sdmaclea/git/coreclr/src/jit/emit.cpp Line: 4710
    Image: /home/sdmaclea/test.c5dff6f.d/Tests/coreoverlay/crossgen

exit 134
```
```
Precompiling /home/sdmaclea/overlay.c5dff6f.d/System.Net.Sockets.dll
./tests/runtest.sh: line 397: 27324 Aborted                 $overlayDir/crossgen /Platform_Assemblies_Paths $overlayDir $filename > $filename.stdout 2> $filename.stderr
Unable to precompile /home/sdmaclea/overlay.c5dff6f.d/System.Net.Sockets.dll.
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.


Assert failure(PID 27324 [0x00006abc], Thread: 27324 [0x6abc]): Assertion failed 'dsc->TypeGet() == TYP_REF || dsc->TypeGet() == TYP_BYREF' in 'System.Net.InteropIPAddressExtensions:GetIPAddress(struct):ref' (IL size 114)

    File: /home/sdmaclea/git/coreclr/src/jit/emit.cpp Line: 4710
    Image: /home/sdmaclea/test.c5dff6f.d/Tests/coreoverlay/crossgen

exit 134
```
```
Precompiling /home/sdmaclea/overlay.c5dff6f.d/System.Net.Primitives.dll
./tests/runtest.sh: line 397: 27330 Aborted                 $overlayDir/crossgen /Platform_Assemblies_Paths $overlayDir $filename > $filename.stdout 2> $filename.stderr
Unable to precompile /home/sdmaclea/overlay.c5dff6f.d/System.Net.Primitives.dll.
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

ReadyToRun: Implicit boxing for calls to constrained methods not supported
ReadyToRun: Implicit boxing for calls to constrained methods not supported
ReadyToRun: Implicit boxing for calls to constrained methods not supported

Assert failure(PID 27330 [0x00006ac2], Thread: 27330 [0x6ac2]): Assertion failed 'dsc->TypeGet() == TYP_REF || dsc->TypeGet() == TYP_BYREF' in 'IPAddress:Equals(struct):bool:this' (IL size 179)

    File: /home/sdmaclea/git/coreclr/src/jit/emit.cpp Line: 4710
    Image: /home/sdmaclea/test.c5dff6f.d/Tests/coreoverlay/crossgen

exit 134
```

### PR DESCRIPTION
**Pull request by sdmaclea**
Per recomendation of @pgavlin  in #9898

Fixes #9898

### CODE REVIEW

**Comment by sdmaclea** [comment]
cc @dotnet/jit-contrib

**Comment by sdmaclea** [comment]
@pgavlin I tested this on arm64 and it fixes the crossgen error reported in #9898.  Your suggested patch looked rational to me.

**Comment by BruceForstall** [comment]
Since isPrespilledArg is always false for x86, you could simplify this to remove an ifdef, e.g.:
```
...
#elif !defined(LEGACY_BACKEND)
            // For !LEGACY_BACKEND on other platforms, a stack parameter, or prespilled argument for profiling on ARM,
            // will have a stack location.
            assert((varDsc->lvIsParam && !varDsc->lvIsRegArg) || isPrespilledArg);
#else  // !(_TARGET_AMD64 || defined(LEGACY_BACKEND))
              // Otherwise, we only have a valid stack location for:
              // A parameter that was passed on the stack, being homed into its register home,
              // or a prespilled argument on arm under profiler.
              assert((varDsc->lvIsParam && !varDsc->lvIsRegArg && varDsc->lvRegister) || isPrespilledArg);
#endif // !(_TARGET_AMD64 || defined(LEGACY_BACKEND))
...
```

**Comment by sdmaclea** [comment]
@BruceForstall yes.  simpler is better.

**Comment by sdmaclea** [comment]
@BruceForstall done

**Pull request merged**
