### PR TITLE
Remove LONG_MATH_REGPARAM from the JIT.

### PR DESCRIPTION
**Pull request by pgavlin**
This symbol was never defined as true, and as such the various bits of code predicated
on it were dead. This change removes the symbol and its associated code.

### CODE REVIEW

**Comment by pgavlin** [comment]
@briansull @CarolEidt @adiaaida @dotnet/jit-contrib PTAL

**Comment by adityamandaleeka** [comment]
LGTM

**Comment by CarolEidt** [comment]
LGTM. Always nice to get rid of some old dead code!

**Comment by adiaaida** [comment]
LGTM

**Comment by briansull** [comment]
LGTM

**Pull request merged**
