### PR TITLE
Fix #14773

### LINKED ISSUE #14773: [RyuJit/Arm32/JitStress=1]Assertion failed '!GenTree::IsExOp(tree->OperKind()) && tree->OperIsSimple()'
There are 4 new failures in [arm32 JitStress leg](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_arm_altjit_checked_windows_nt_jitstress1_prtest/9/#showFailuresLink): 
```
JIT_HardwareIntrinsics._Lzcnt_r_Lzcnt_r_._Lzcnt_r_Lzcnt_r_cmd
JIT_HardwareIntrinsics._Popcnt_r_Popcnt_r_._Popcnt_r_Popcnt_r_cmd
JIT_HardwareIntrinsics._Lzcnt_ro_Lzcnt_ro_._Lzcnt_ro_Lzcnt_ro_cmd
JIT_HardwareIntrinsics._Crc32_ro_Crc32_ro_._Crc32_ro_Crc32_ro_cmd
```

This is presumably due to #14456.

### PR DESCRIPTION
**Pull request by fiigii**
Fix #14773

### CODE REVIEW

**Comment by fiigii** [comment]
@dotnet-bot test Windows_NT jitstress1
@dotnet-bot test Windows_NT jitstress2
@dotnet-bot test Windows_NT x86 jitstress1
@dotnet-bot test Windows_NT x86 jitstress2

**Comment by fiigii** [comment]
@dotnet-bot test Windows_NT x86_arm_altjit Checked  jitstress1

**Comment by fiigii** [comment]
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2

**Comment by BruceForstall** [comment]
cc @dotnet/jit-contrib

**Comment by fiigii** [comment]
Failures are not from hardware intrinsic code. @CarolEidt PTAL

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu x64 Innerloop Formatting 
@dotnet-bot test Windows_NT x64 Innerloop Formatting

**Pull request merged**
