### PR TITLE
System.IO.Path.IsPathRooted does not check if valid drive letter on W…

### PR DESCRIPTION
**Pull request by ViktorHofer**
…indows

https://github.com/dotnet/coreclr/issues/10297

### CODE REVIEW

**Comment by ViktorHofer** [comment]
I will add tests in corefx

**Comment by danmosemsft** [comment]
@dotnet-bot test osx10.12 x64 checked build and test please (@mmitche - https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_osx10.12_flow_prtest/238/)

**Comment by mmitche** [comment]
@danmosemsft Check the log for that one, there are a lot of errors:

14:52:47 Installing dotnet cli...
14:53:10 Restoring BuildTools version 1.0.27-prerelease-01413-01...
14:53:10 
14:53:10 Unhandled Exception: System.ArgumentNullException: Value cannot be null.
14:53:10 Parameter name: path1
14:53:10    at System.IO.Path.Combine(String path1, String path2, String path3)
14:53:10    at Microsoft.DotNet.ProjectModel.Resolution.PackageDependencyProvider.ResolvePackagesPath(String rootDirectory, GlobalSettings settings)
14:53:10    at Microsoft.DotNet.Configurer.NuGetCacheSentinel.get_NuGetCachePath()
14:53:10    at Microsoft.DotNet.Configurer.NuGetCacheSentinel.Exists()
14:53:10    at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.ShouldPrimeNugetCache()
14:53:10    at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
14:53:10    at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
14:53:10    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
14:53:10    at Microsoft.DotNet.Cli.Program.Main(String[] args)
14:53:10 /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/checked_osx10.12_tst_prtest/tests/../init-tools.sh: line 164:  1325 Abort trap: 6           $__DOTNET_CMD restore "$__PROJECT_JSON_FILE" --no-cache --packages $__PACKAGES_DIR --source $__BUILDTOOLS_SOURCE >> $__init_tools_log
14:53:10 
ERROR: Could not restore build tools correctly. See '/Users/dotnet-bot/j/workspace/dotnet_coreclr/master/checked_osx10.12_tst_prtest/init-tools.log' for more details.1
14:53:10 Initializing BuildTools...

**Comment by danmosemsft** [comment]
@livarcocc is the callstack above the CLI? or Nuget? ..

**Comment by ViktorHofer** [comment]
Any reason to not merge as I see all tests passing?

**Comment by danmosemsft** [comment]
Since @ianhays signed off...

**Pull request merged**
