### PR TITLE
Fix #14427

### LINKED ISSUE #14427: Breakpoints aren't hit if tiered jitting recompiled the method before the debugger was attached
This is related but not identical to #14423.

To repro:
1. Execute a method Foo in a loop many times so that tiered compilation generates and publishes Tier1 code for it.
2. Attach Visual Studio to the application
3. Set a breakpoint in Foo
The correct behavior is for the debugger to stop at the breakpoint but that won't occur.

The is caused because the runtime's debugger code fails to properly enumerate all the code bodies where the breakpoint needs to be placed. The code at 
https://github.com/dotnet/coreclr/blob/master/src/debug/ee/functioninfo.cpp#L2005
only winds up enumerating the Tier0 version of the code but not any other version of the code.

### PR DESCRIPTION
**Pull request by noahfalk**
Enumerate all of the jitted instances of a method using the tiered compilation manager

### CODE REVIEW

**Comment by noahfalk** [comment]
@davmason - please take a look

cc @dotnet/dotnet-diag @janvorli

**Comment by davmason** [comment]
The code here looks good to me, I don't know the debugger space well enough to think through all the scenarios. What you've added makes sure there is a DJI for every native code version, but will the debugger know to put the breakpoint on the newest one? I.e. I don't see any changes to the path that actually adds the breakpoint.

Other than that, looks good.

**Comment by noahfalk** [comment]
Thanks!
The debugger adds a breakpoint on every returned jit info. Historically enumerating more than one item meant the method was generic so you needed breakpoints on each generic instantiation. Now it means every version of every native code version of every generic instance.

**Comment by noahfalk** [comment]
rebased to eliminate the conflicts

**Comment by noahfalk** [comment]
@dotnet-bot test windows_NT x64 debug build and test

**Pull request merged**
