### PR TITLE
Fix Invalid Parameter to CoreFx Test CI Legs

### PR DESCRIPTION
**Pull request by brianrob**
The skiptests parameter is specified, but it is no longer a valid parameter.

### CODE REVIEW

**Comment by brianrob** [comment]
@dotnet-bot test ci please

**Comment by brianrob** [comment]
@dotnet-bot test ci please

**Comment by brianrob** [comment]
@dotnet-bot test ci please

**Comment by brianrob** [comment]
@dotnet-bot test ci please

**Comment by brianrob** [comment]
@dotnet-bot test ci please

**Comment by jkotas** [comment]
The same problem was fixed by the change that conflicts with this. Please submit a new PR if it is still an issue.

**Pull request closed without merging**
