### PR TITLE
[Linux][ARM] Add Linux/ARM/SoftFP profiler

### PR DESCRIPTION
**Pull request by Dmitri-Botcharnikov**
This PR adds libcoreprof.so - an implementation of profiler for Linux/ARM. Currently it was checked only on ARM/softfp. 
The build is wrapped with FEATURE_LINUX_PROFILER:

```
$ ./build.sh arm-softfp cross cmakeargs -DFEATURE_LINUX_PROFILER=TRUE
```

To run:

```
CORECLR_PROFILER={101DA8FE-FDCA-4D0E-9712-7639CDE48EBA} CORECLR_ENABLE_PROFILING=1 CORECLR_PROFILER_PATH=./libcoreprof.so PROF_EXECUTION_TRACE=1 PROF_COLLECT_METHOD=Sampling PROF_LINE_TRACE=1 PROF_TRACE_FILENAME=profile.log ./corerun demoapp.dll
```

The resulting log file contains VM events and samplings based on Ltt ng.
cc @chunseoklee @seanshpark @lemmaa @kvochko @lucenticus

### CODE REVIEW

**Comment by Dmitri-Botcharnikov** [comment]
@dotnet-bot test  Linux ARM Emulator Cross Debug Build please

**Comment by danmosemsft** [comment]
@Dmitri-Botcharnikov where do we stand on this one? just need a review and we can get it in?

**Comment by danmosemsft** [comment]
@chunseoklee @seanshpark @lemmaa @kvochko @lucenticus since you were referenced earlier -- can you take a look and merge if appropriate.

**Comment by mjsabby** [comment]
I would prefer if we not add a specific profiler inside the CoreCLR repo. The Profiling APIs exist as part of the runtime but different ones are kept outside.

For example, we have a reference one for building new ones at https://github.com/Microsoft/clr-samples.

**Comment by danmosemsft** [comment]
Just realized those above don't have merge powers. /cc @lt72 to review this change also.

**Comment by lt72** [comment]
@Dmitri-Botcharnikov: we have a linux profiling story based on LTTng. Documentation is available here: [Performance Tracing on Linux](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/linux-performance-tracing.md). 
The ideal interface to extend or use for profiling CoreCLR is the ProfilingAPI. Adding a specific profiler implementation for a specific OS though does not look like the right thing to do. The ASM helpers may be useful though. Could you please try the current profiler for Linux and let us know if it is usable for your purposes?

@noahfalk @brianrob: could you please check the ASM helper and see if they could be of general use?

**Comment by noahfalk** [comment]
Echoing other comments above, I would also prefer not to check in this profiler in the coreclr repo itself. The https://github.com/dotnet/corefx-tools repo might be a more appropriate place? @brianrob - I think you are a little more active in the corefx-tools repo, does that seem like a good fit?

@lt72 - I wouldn't take the assembly helpers on their own unless we had a specific purpose to use them for. We've already got an implementation in the test profiler code @kspawa was working on and I haven't come up with any other purpose for keeping them.

**Comment by Dmitri-Botcharnikov** [comment]
Ok, if this repo is inappropriate for specific profiler implementation I code the PR.

**Pull request closed without merging**
