### PR TITLE
Inline refactoring: header cleanup and some renaming

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Move inlining classes and related bits of code into inline.h.
Rename `JitInlineResult` to `InlineResult` and `InlInlineHints` to
`InlineHints`.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@dotnet/jit-contrib PTAL

**Comment by mikedn** [comment]
Nice to see stuff moved out of the huge compiler.h/.cpp files :+1:

**Comment by AndyAyersMS** [comment]
Updated to pick up the change from #3203.

**Comment by briansull** [comment]
LGTM

**Comment by AndyAyersMS** [comment]
@dotnet/jit-contrib this one's ready for review now that the memory fix is merged.

**Comment by AndyAyersMS** [comment]
Anybody have time to review this? I have more changes queued up behind this one....

**Comment by pgavlin** [comment]
LGTM. Glad to see this moving right along!

**Comment by CarolEidt** [comment]
LGTM

**Comment by AndyAyersMS** [comment]
Thanks everyone.

**Pull request merged**
