### PR TITLE
Make a few VN methods tolerant of NoVN.

### PR DESCRIPTION
**Pull request by pgavlin**
There were a few methods on the VN store that were not resilient to
being provided with the "no value number" sentinel value. This lack of
resilience caused assertion failures during assertion propagation when
generating assertions for trees marked with "no value number".

### CODE REVIEW

**Comment by pgavlin** [comment]
@BruceForstall @briansull @erozenfeld @dotnet/jit-contrib PTAL

Fixes VSO 280123.

**Comment by JosephTremoulet** [comment]
The explanation of the issue in the test case points the finger at unreachable code.  Do we expect `NoVN` to pop up in reachable code?  Would it be better to have assertion prop avoid running on unreachable code?

**Comment by pgavlin** [comment]
> Would it be better to have assertion prop avoid running on unreachable code?

This would also be good, yes, but I don't think it obviates being resilient to `NoVN`. There are other VN-related methods that are resilient to the same, so it follows that we do expect this under certain circumstances (whether or not they involve reachable code is not clear).

**Comment by pgavlin** [comment]
Perhaps we could also be a bit less conservative about removing blocks in EH regions s.t. this unreachable code simply isn't present in the method.

**Comment by JosephTremoulet** [comment]
>  I don't think it obviates being resilient to `NoVN`

I guess my concern is that this might just kick the can down the road and pressure the callers to be tolerant of the various "no info" returns and now when we run into crashes when the callers fail to do so it will be further from the point of failure.  If it's just unreachable code and we can avoid assertion prop on that, then we can make "must take valid VN" part of the contract of these methods and assert against `NoVN` instead of translating it.


> Perhaps we could also be a bit less conservative about removing blocks in EH regions s.t. this unreachable code simply isn't present in the method

Yeah, that would be best, but as a general rule I'm more willing to say we require phases to gracefully handle unreachable code than to require all phases to remove all unreachable code (since trying to maintain that invariant in arbitrary flow-altering transformations can be awkward).

**Comment by pgavlin** [comment]
@JosephTremoulet: after some digging, it does appear that we expect `NoVN` to crop up in some circumstance, even in reachable code (e.g. on lclVars that are excluded from SSA).

**Comment by JosephTremoulet** [comment]
>it does appear that we expect NoVN to crop up in some circumstance, even in reachable code (e.g. on lclVars that are excluded from SSA)

I see, thanks for checking.  IMO it would be reasonable to require callers not to ask details about the VN of a local that's excluded from SSA, and even preferable since the bail-outs would happen sooner and the crashes would be closer to the point of failure, but I think you understand the feedback so I have no problem if you simply disagree and want to merge as-is.

**Comment by pgavlin** [comment]
I will keep this as-is for now. We can reconsider the API design in the future.

**Pull request merged**
