### PR TITLE
Nullable feature into master

### PR DESCRIPTION
**Pull request by safern**
Draft PR, once we're ready to merge into master again, I'll promote it to be a real PR. In the meantime we will use this one for potential test failures or build breaks.

### CODE REVIEW

**Comment by safern** [comment]
This PR is ready to be merged once CI is green 😄

**Comment by danmosemsft** [comment]
Just curious, have you guys tried diffing the IL (`ildasm /out ...`) either side of these big nullability merges into master? There will be noise in offsets etc but I am guessing there will be very few IL changes and it should be possible to confirm they are expected ones.

**Comment by safern** [comment]
> Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'xunit.runner.utility.netcoreapp10, Version=2.4.1.4059, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'. An operation is not legal in the current state. (0x80131509)
   at Xunit.ConsoleClient.ConsoleRunner..ctor(Object consoleLock)
   at Xunit.ConsoleClient.Program.Main(String[] args) in /_/src/Microsoft.DotNet.XUnitConsoleRunner/src/Program.cs:line 19

@jashook @echesakovMSFT  is this a known issue? A lot of tests are failing with that error.

**Comment by safern** [comment]
> Just curious, have you guys tried diffing the IL (ildasm /out ...) either side of these big nullability merges into master? There will be noise in offsets etc but I am guessing there will be very few IL changes and it should be possible to confirm they are expected ones.

I tried doing a diff yesterday as per your suggestion and mostly all of the changes are because of all the `NullableAttribute` that the compiler adds. It is hard to do the diff because the ildasm has ~800000 lines 😄 -- I'll try and remove all the `NullableAttribute` and see if something else changed drasticly.

**Comment by echesakovMSFT** [comment]
> Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'xunit.runner.utility.netcoreapp10, Version=2.4.1.4059, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'. An operation is not legal in the current state. (0x80131509)
> at Xunit.ConsoleClient.ConsoleRunner..ctor(Object consoleLock)
> at Xunit.ConsoleClient.Program.Main(String[] args) in /_/src/Microsoft.DotNet.XUnitConsoleRunner/src/Program.cs:line 19
> 
> @jashook @echesakovMSFT  is this a known issue? A lot of tests are failing with that error.

It's a known issue with xunit.console runner - you would need to take https://github.com/dotnet/coreclr/pull/23944 to make R2R jobs working

**Comment by safern** [comment]
> It's a known issue with xunit.console runner - you would need to take #23944 to make R2R jobs working

Thanks! I'll update the branch.

**Comment by safern** [comment]
@echesakovMSFT I merged with master on this branch and now getting another error which seems related to the xunit runner:

> Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (64-bit .NET Core 3.0.0-preview5.27616.0)
System.IO.FileLoadException: Could not load file or assembly 'JIT.SIMD.XUnitWrapper, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509 (COR_E_INVALIDOPERATION))
System.IO.FileLoadException: Could not load file or assembly 'JIT.opt.XUnitWrapper, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509 (COR_E_INVALIDOPERATION))
System.IO.FileLoadException: Could not load file or assembly 'JIT.RyuJIT.XUnitWrapper, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509 (COR_E_INVALIDOPERATION))
System.IO.FileLoadException: Could not load file or assembly 'JIT.Intrinsics.XUnitWrapper, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509 (COR_E_INVALIDOPERATION))
System.IO.FileLoadException: Could not load file or assembly 'JIT.Performance.XUnitWrapper, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509 (COR_E_INVALIDOPERATION))
System.IO.FileLoadException: Could not load file or assembly 'JIT.CheckProjects.XUnitWrapper, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509 (COR_E_INVALIDOPERATION))
+ export _commandExitCode=1
+ _commandExitCode=1

**Comment by echesakovMSFT** [comment]
@safern This doesn't seem familiar to me. 

The *.XUnitWrapper run under the same runtime as the tests (i.e. in theory any "bad" change to coreclr or S.P.C.dll can cause this). 

/cc @RussKeldorph This is one of the situations justifiying why we need to use LKG version of dotnet instead of "live"

R2R OSX fails with the different message
```
export COMPlus_TieredCompilation=0
+ /Users/dotnet-bot/dotnetbuild/work/9acba257-d5a1-45b6-b17c-243645d965a3/Payload/corerun /Users/dotnet-bot/dotnetbuild/work/9acba257-d5a1-45b6-b17c-243645d965a3/Payload/xunit.console.dll JIT/jit64/JIT.jit64.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml -trait TestGroup=JIT.jit64

Assert failure(PID 1164 [0x0000048c], Thread: 10357382 [0x9e0a86]): IsZapped() || HaveValueTypeParametersBeenWalked()
    File: /Users/vsts/agent/2.149.2/work/1/s/src/vm/method.cpp Line: 5733
    Image: /Users/dotnet-bot/dotnetbuild/work/9acba257-d5a1-45b6-b17c-243645d965a3/Payload/corerun

/Users/dotnet-bot/dotnetbuild/work/9acba257-d5a1-45b6-b17c-243645d965a3/Payload/scripts/a5f8c4a4ada9441ba5d8d0ac2ea6c8d5/execute.sh: line 9:  1164 Abort trap: 6           $CORE_ROOT/corerun $CORE_ROOT/xunit.console.dll JIT/jit64/JIT.jit64.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml -trait TestGroup=JIT.jit64
```

**Comment by safern** [comment]
@jkotas do you have any clue what could have caused this form the nullable annotations? 

The debug assert failing on the example above is: https://github.com/dotnet/coreclr/blame/NullableFeature/src/vm/method.cpp#L5733

**Comment by safern** [comment]
I think I found the root cause of the assembly load failures:

https://github.com/dotnet/coreclr/pull/23774/files#diff-9ab5f75a643869b8dfb2deaa39d28b66R145

@stephentoub seems like on the extra validation, we missed a `!` in 

`if (string.IsNullOrEmpty(loadedSimpleName) || requestedSimpleName.Equals(loadedSimpleName, StringComparison.InvariantCultureIgnoreCase))`

It seems it should be:

`if (string.IsNullOrEmpty(loadedSimpleName) || !requestedSimpleName.Equals(loadedSimpleName, StringComparison.InvariantCultureIgnoreCase))`

**Comment by safern** [comment]
So it seems like that was the issue... the only pending failure is the following corefx test: https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.StackTrace/tests/StackTraceTests.cs#L324 which is expecting a NullReferenceException... however here we decided to avoid throwing a NRE: https://github.com/dotnet/coreclr/pull/23753/files#r272596362

Per the test, it seems like that behavior was expected... should we instead throw an ArgumentNullException there? Or just delete the test? @stephentoub ?

**Comment by stephentoub** [comment]
> seems like on the extra validation, we missed a !

Ugh, yes, thanks for fixing.

> Per the test, it seems like that behavior was expected

Not really; the test was just added to exercise existing behavior.

> Or just delete the test?

Ideally we'd keep the test but fix it to expect the revised behavior.

**Comment by safern** [comment]
Yep, I’ll suppress the test in this PR and then fix the test in corefx to expect the new behavior.

**Comment by safern** [comment]
The only remaining issue is a corefx test failure in string builder -- 

>    System.Text.Tests.StringBuilderTests.Test_Insert_Float [FAIL]
22:02:16       Exit code was 134 but it should have been 42
22:02:16       Expected: True
22:02:16       Actual:   False
22:02:16       Stack Trace:
22:02:16 Assertion Failed
22:02:16 we should never get past last chunk because range should already be validated before calling
22:02:16 
22:02:16    at System.Text.StringBuilder.ReplaceInPlaceAtChunk(StringBuilder& chunk, Int32& indexInChunk, Char* value, Int32 count) in /mnt/j/workspace/dotnet_coreclr/master/x64_checked_ubuntu_corefx_innerloop_prtest/src/System.Private.CoreLib/shared/System/Text/StringBuilder.cs:line 2233

This is failing in the following Debug.Assert... it seems like to avoid making `chunk` nullable we did this workarounds which are breaking its behavior.

https://github.com/dotnet/coreclr/blob/NullableFeature/src/System.Private.CoreLib/shared/System/Text/StringBuilder.cs#L2233

@krwq is taking a look

**Comment by safern** [comment]
Looks like crossgen builds are hung in all other PRs as well. Merging since everything else is finally green :smile:

**Comment by jkotas** [comment]
@Anipik Could you please take a look at the mirror? It is not picking up this change.

**Comment by safern** [comment]
It just picked it up: https://github.com/dotnet/corefx/pull/37003

**Pull request merged**
