### PR TITLE
CI fix: arm-softfp to armel

### PR DESCRIPTION
**Pull request by hseok-oh**
Fix corefx directory: arm-softfp to armel
related PR: dotnet/corefx#14843

issue: #8872

### CODE REVIEW

**Comment by hseok-oh** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build
@dotnet-bot test Linux ARM Emulator Cross Debug Build

**Comment by hseok-oh** [comment]
@dotnet-bot test ci please

**Comment by hseok-oh** [comment]
@gkhanna79 PTAL

**Comment by gkhanna79** [comment]
@dotnet-bot test  Linux ARM Emulator Cross Debug Build please

**Comment by gkhanna79** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build please

**Comment by AndyAyersMS** [comment]
I already fixed this over in https://github.com/dotnet/coreclr/pull/8875.

**Comment by gkhanna79** [comment]
Closing this PR since @AndyAyersMS has already fixed this issue.

**Pull request closed without merging**
