### PR TITLE
Remove code corresponding to always defined symbols

### PR DESCRIPTION
**Pull request by danmosemsft**
Contributes to https://github.com/dotnet/coreclr/issues/9067

### CODE REVIEW

**Comment by danmosemsft** [comment]
No need to review this yet, I"ll carry on for the undefines.

**Comment by danmosemsft** [comment]
This is halfway. @jkotas @gkhanna79 I'm going to take a break at this point, if you'd like to review.

**Comment by danmosemsft** [comment]
Please let's **not** squash on merge, obviously.

**Comment by jkotas** [comment]
FEATURE_CODEPAGES_FILE: delete nlstable.h as well

**Comment by jkotas** [comment]
FEATURE_APPX_BINDER: Delete `vm\clrprivbinderappx.*` as well

**Comment by jkotas** [comment]
FEATURE_FUSION: Delete `vm\fusion*.` as well

**Comment by jkotas** [comment]
LGTM otherwise. Thank you for doing this!

**Comment by danmosemsft** [comment]
@dotnet-bot test osx x64 checked buil dan test (https://github.com/dotnet/coreclr/issues/9388)

**Comment by danmosemsft** [comment]
@dotnet-bot test osx x64 checked build and test (https://github.com/dotnet/coreclr/issues/9388)

**Comment by mattwarren** [comment]
@danmosemsft have you seen [my comment on your other PR](https://github.com/dotnet/coreclr/pull/9269#issuecomment-278637567)?

I noticed that in at least one case only the `public` code was stipped, but `private`/`internal` fields were left behind, e.g. see [SharedStatics.cs](https://github.com/dotnet/coreclr/blob/beaf718cc6e3a0e786191ce322839e66619b5a54/src/mscorlib/src/System/SharedStatics.cs#L37-L40)

**Pull request merged**
