### PR TITLE
Disable default BuildNumberMajor

### PR DESCRIPTION
**Pull request by wtgodbe**
For https://github.com/dotnet/coreclr/issues/13395

@weshaggard is this all that is required?

### CODE REVIEW

**Comment by weshaggard** [comment]
>@weshaggard is this all that is required?

I believe so but please verify that the file version looks correct now. As a bonus it would be good to figure out how long this has been broken because I don't believe it has been broken since 2016 when the original line was added so something else must have changed.

**Comment by wtgodbe** [comment]
@dotnet-bot test this please

**Comment by wtgodbe** [comment]
@weshaggard BuildNumberMajor was set to 25622 in my local build

**Comment by weshaggard** [comment]
@wtgodbe can you also please get this ported to 2.0.0 branch so it can be included in the next servicing build?

**Comment by wtgodbe** [comment]
@weshaggard sure, once this is green I will merge & port the PR.

**Pull request merged**
