### PR TITLE
Bump the version of the xUnit-Performance package (#11793)

### PR DESCRIPTION
**Pull request by jorive**
- In a previous PR this was reverted and broke the Profile On/Off perf runs

### CODE REVIEW

**Comment by gkhanna79** [comment]
Does this fix the perf test failures in https://github.com/dotnet/coreclr/pull/11809?

**Comment by jorive** [comment]
@gkhanna79 No, it does not. This fixes the version of the xUnit-Performance API we use, which enable us to run the benchmarks with and without ETW profiler and do benchmark analysis.

**Comment by jorive** [comment]
@dotnet-bot test Windows_NT x64 perf

**Comment by jorive** [comment]
@dotnet-bot test Windows_NT x86 perf

**Comment by DrewScoggins** [comment]
@dotnet-bot test Windows_NT x64 perf
@dotnet-bot test Windows_NT x86 perf

**Pull request merged**
