### PR TITLE
Don't use code rejitted at tier 1 when the JIT falls back to min-opts due to method size/complexity

### PR DESCRIPTION
**Pull request by kouvel**
Fixes https://github.com/dotnet/coreclr/issues/26419

### CODE REVIEW

**Comment by BruceForstall** [comment]
cc @briansull This has a relationship with your proposed "AOT penalty" and perf score work.

**Comment by AndyAyersMS** [comment]
I think we can come up with a better fix for this.

* when prejitting, we can have the jit check if it would fall back to minopts if asked to jit the method at Tier1, and if so, communicate this back to the runtime, so that the runtime knows not to ask for a rejit.
* when jitting at Tier1, we usually make the determination to run at minopts very early, and we can just abort the jit request, instead of rejitting the entire method at Tier0 and then deciding not to use the result.

If necessary we can also adjust the jit logic so that the only time it will do a complexity-based fallback is via this early check, and we can force later phases (eg inlining) that might increase method complexity to be more conservative if we've passed the complexity check and decided to jit at Tier1.

That leaves the case where the jit falls back to minopts because of an internal error, but those are hopefully quite rare (we should surface this in the jit ETL too).

**Comment by briansull** [comment]
When building the crossgen AOT image the JIT can persist the necessary information so that we do not attempt to perform a Tier1 recompilation.   
As for the current fix, since this is such an extremely rare corner case, I am fine with the approach that Kount used, which trades off some wasted extra Tier1 compilation time, for now.

**Comment by kouvel** [comment]
I'm hoping that we can also get similar information from a tier 0 JIT when there is no prejitted code to avoid rejitting

**Comment by BruceForstall** [comment]
> when prejitting, we can have the jit check if it would fall back to minopts if asked to jit the method at Tier1, and if so, communicate this back to the runtime, so that the runtime knows not to ask for a rejit.

If this is persisted in a R2R image, presumably that image _could_ be used by a later JIT that would not fall back, due to JIT improvements. But maybe that's not worth considering.

**Pull request merged**
