### PR TITLE
Move R2R JitStress jobs into the jitstress folder with the others.

### PR DESCRIPTION
**Pull request by RussKeldorph**

### CODE REVIEW

**Comment by RussKeldorph** [comment]
test ci please

**Comment by RussKeldorph** [comment]
@sejongoh PTAL
/cc @mmitche

**Comment by sejongoh** [comment]
LGTM

**Comment by RussKeldorph** [comment]
@jashook FYI

**Comment by RussKeldorph** [comment]
Ubuntu failure is #5686.  Ignoring.

**Pull request merged**
