### PR TITLE
Ensure ReadyToRun test verifies version resiliency

### PR DESCRIPTION
**Pull request by janvorli**
This change modifies the ReadyToRun test so that it verifies assembly version resiliency.

### CODE REVIEW

**Comment by janvorli** [comment]
@jkotas I have figured out a way to make the current testing infrastructure to actually test the version resiliency. While the mainv2.exe is still built, only the mainv1.exe is used with both versions of the test.dll. The pre-test and post-test commands enabled me to do that with some file copying.

**Comment by jkotas** [comment]
@janvorli Thanks for looking into this again.

The test is failing in CI...

I think that the right fix for this problem should be around building the v1 and v2 test.dll into two different directories, and copying it from there for execution.

**Comment by janvorli** [comment]
The failure is strange. The test works ok on my machine locally. Ill look into that

**Comment by janvorli** [comment]
@jkotas I have modified it so that the testv1 and testv2 projects are in subdirectories and both build assembly with the same name `test`. Now it should work properly.

**Comment by janvorli** [comment]
Hmm, still some issue with the test. I'm looking into it.

**Comment by janvorli** [comment]
@jkotas, the CI is passing now.

**Comment by jkotas** [comment]
LGTM otherwise. Thanks!

**Pull request merged**
