### PR TITLE
Fixing the StackOverflowException error message.

### PR DESCRIPTION
**Pull request by vijayrkn**
Fixing the StackOverflowException error message - #4756

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
If we're going to change this, I suggest 'Process is terminating due to StackOverflowException.' since at the point we're showing the message we haven't aborted yet. It would be jarring to be debugging and see a message saying 'process was terminated' while the process is still alive.

**Comment by vijayrkn** [comment]
Most of the time (except for the debug scenario) this message would be displayed as part of the exception message (long after the process has terminated). If we show a message that "'Process is terminating" at this point, it could be even more confusing.

**Comment by Petermarcu** [comment]
@vijayrkn, Do you want to finish this up based on the feedback?

**Comment by vijayrkn** [comment]
Sure, Let me send an update based on the feedback. (I somehow missed this PR, Sorry about that)

**Comment by vijayrkn** [comment]
I have updated the PR.

**Comment by adityamandaleeka** [comment]
LGTM

**Comment by vijayrkn** [comment]
Can I go ahead and merge the PR ?

**Comment by Petermarcu** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Pull request merged**
