### PR TITLE
Create Long-running GC test job for the CI

### PR DESCRIPTION
**Pull request by swgillespie**
This PR introduces a new CI mode that runs long-running GC tests, tests that are not appropriate to run as a part of any other test mix. These tests that are run in this job are designed to stress the GC and may take a lot of time or memory to do so.

No new tests are added in this PR - rather, a number of tests are marked as long-running GC tests and will be run in this new test scenario. A release run of the long GC test scenario takes about 50 minutes to an hour on my machine. In order to ensure that the test run completes in a reasonable time, the CI job is only enabled for Release and Checked builds - debug builds increase the running time tenfold.

This change also contains minor changes to the test infrastructure, in particular:

1) The `sequential` parameter `runtests.cmd` now runs tests sequentially,
2) An environment variable `__TestTimeout` is queried by the xunit test wrapper and, if present, uses it as a timeout instead of the default 10 minutes for a test.
3) Removed the GC\Coverage\concurrentspin2 test, since it's a duplicate to an already-existing test.

### CODE REVIEW

**Comment by swgillespie** [comment]
@dotnet-bot test CI please

**Comment by swgillespie** [comment]
@dotnet-bot test CI please

**Comment by swgillespie** [comment]
@dotnet-bot test Windows Release longgc please

**Comment by swgillespie** [comment]
@dotnet-bot test CI please

**Comment by swgillespie** [comment]
@sergiy-k @wtgodbe @mmitche PTAL? 

I'll rebase against master (fix the merge conflicts) and add the new trigger phases that I added to the docs that Will merged yesterday.

**Comment by wtgodbe** [comment]
LGTM

**Comment by swgillespie** [comment]
@dotnet-bot test CI please

**Comment by swgillespie** [comment]
@dotnet-bot test CI please

**Comment by swgillespie** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Pull request merged**
