### PR TITLE
Fixed issue #5391 "libsosplugin.so getting an RPATH of /usr/lib/llvm on RHEL"

### PR DESCRIPTION
**Pull request by mikem8361**
Add RPATH CMakeList.txt logic to sosplugin.

### CODE REVIEW

**Comment by ellismg** [comment]
I will verify.

**Comment by ellismg** [comment]
Verified.

**Comment by joshfree** [comment]
@mmitche it looks like the Ubuntu x64 Checked leg finished but did not report status back to github: http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/release_1.0.0/job/checked_ubuntu_flow_prtest/93/

**Comment by joshfree** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Comment by sergiy-k** [comment]
@joshfree, all tests in the Ubuntu x64 Checked leg (that you referenced) have succeeded. So it should be safe to merge this PR.

**Comment by mmitche** [comment]
@joshfree Rate limit.  Working on improvements.

**Comment by joshfree** [comment]
@mmitche cool no problem; I just wanted to make sure you saw it

**Pull request merged**
