### PR TITLE
GitHub actions: add auto PR labeler for Jit changes.

### PR DESCRIPTION
**Pull request by sandreenko**
Try a new GitHub feature: actions https://github.com/dotnet/coreclr/actions/new

Add a labeler as described here: https://github.com/actions/labeler/blob/master/README.md#create-workflow

I wanted to test it in my fork first but it is blocked by https://github.com/actions/labeler/issues/12

PTAL @dotnet/coreclr-infra  (for some reason I can't request a review from that team, but can mention it).

That will replace the manual script that I run from time to time to track new CodeGen PRs.

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
My only concern with this is the "moving target" problem. If I am reading this yml correctly, whenever a PR is built its labels can change. This means that someone labels their PR `area-VM` but because it has a single file from under the JIT directory it gets automatically moved to `area-CodeGen`. So the user re-assigns, pushes another change and again the label is updated. 

Basically I don't like automation that I have to fight. If it can't be done in a way that is smart and tries once and then never again I would prefer to not have auto-tagging PRs trigger via the build. If this isn't a build trigger please disregard.

**Comment by sharwell** [comment]
It looks like it might just add a label and not remove others. I'm super interested to see how this works out!

**Comment by sandreenko** [comment]
@AaronRobinsonMSFT that change will only add labels and won't delete them. In 99% cases if you have a change in src/jit then you need a review from the jit team. So I don't see any harm in having an area-CodeGen label on such PRs.

The additional benefit is that if you have a huge PR that got area-Codegen from that auto-labeler the author will see that and add other relevant labels instead of leaving labels empty (as it happens now with most PRs).

**Comment by AaronRobinsonMSFT** [comment]
@sandreenko If it doesn't delete them, then I don't see much issue with it. However, there has been a concerted effort to only have a single area path tag on a PR. So simply adding them seems to break that. @danmosemsft mentioned the desire to have a single area tag but perhaps that policy has changed.

**Comment by jashook** [comment]
Having multiple area labels I believe is still frowned upon.

**Comment by danmosemsft** [comment]
In corefx the PR's are being labeled by the bot using ML. It not only looks at the paths changed in the PR's but also the text and the title. Because it learns, it doesn't need manual configuration.  Results in CoreFX are almost always correct.

@maryamariyan were you planning to enable this for CoreCLR, or wait for the repo consolidation? If the issue is that not many PR's were already labeled in CoreCLR, I would expect that it could still do a fair job based on text content.

**Comment by danmosemsft** [comment]
And yes, please let's stick to just 1 area tag as it makes it easier to report without double counting, and helps accountability

**Comment by sandreenko** [comment]
Closed for now, with 1-area policy it is not useful to have that change.

Thanks.

**Comment by maryamariyan** [comment]
Thanks I am working on training a model for coreclr changes, similar to how we have models trained for corefx repo. It won't just be for predicting area-CodeGen labels.

I just need to work on it a bit further until I get better accuracy with it.

**Pull request closed without merging**
