### PR TITLE
[Arm64/Linux] Enable crosscomponent build in CI

### LINKED ISSUE #17650: [Arm64/Linux] Enable crosscomponent build in CI
#16962 Broke arm64 crosscomponent build.  It would be better to catch these earlier during build.  This would also provide some JIT testing as the S.P.C.dll will be crossgened

### PR DESCRIPTION
**Pull request by sdmaclea**
Fixes #17650

@weshaggard @jashook 
@dotnet/arm64-contrib FYI

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet-bot test ci please

**Comment by BruceForstall** [comment]
@sdmaclea AFAIK, all parts of the build use clang 3.9, except Linux arm, which uses clang 5.0. Does it make sense for arm64 to still use 3.8, explicitly?

**Comment by sdmaclea** [comment]
I was going to leave it for now.
I want to switch to the using the docker image which has clang 3.9, but that is a bigger change (rework the arm64 build system).

**Comment by sdmaclea** [comment]
If the machines it is running on already have clang 3.9, I can make the switch now.

**Comment by sdmaclea** [comment]
This won't pass until #17654  is fixed.

**Comment by weshaggard** [comment]
Given this just merged that means all PRs are going to be failing this leg until https://github.com/dotnet/coreclr/issues/17654 is addressed. @CarolEidt

**Comment by BruceForstall** [comment]
Sorry, I was ahead of the curve. I read "This won't pass until #17654 is fixed." and thought "that's not true, since netci.groovy changes don't get testing except for ensuring the job creation happens."

**Comment by sdmaclea** [comment]
> netci.groovy changes don't get testing except for ensuring the job creation happens

The created jobs can be manually enabled and actually run by those in the know

**Comment by CarolEidt** [comment]
> Given this just merged that means all PRs are going to be failing this leg until #17654 is addressed. 

I'm a bit confused. Does merging this mean that all jobs will trigger this crosscomponent build?

**Comment by sdmaclea** [comment]
All arm64 jobs will trigger this crosscomponet build.  It is distributed as part of coreclr official build to enable core-setup, cli, asp-net to crossgen for arm64 on x64 build boxes.

**Pull request merged**
