### PR TITLE
Don't reload or spill for keepAliveThis

### LINKED ISSUE #25433: JIT: Assertion failed 'regNum != REG_NA'
corefx tests, Windows x86, JitStressRegs=4
```
C:\dotnetbuild\work\dd0fb0da-9dc2-422a-bb34-0b497b2d126b\Work\e0f577b1-ac35-4da2-8e74-c9e10e160187\Exec>set __TestEnv=C:\dotnetbuild\work\dd0fb0da-9dc2-422a-bb34-0b497b2d126b\Payload\SetStressModes_jitstressregs4.cmd 

C:\dotnetbuild\work\dd0fb0da-9dc2-422a-bb34-0b497b2d126b\Work\e0f577b1-ac35-4da2-8e74-c9e10e160187\Exec>type C:\dotnetbuild\work\dd0fb0da-9dc2-422a-bb34-0b497b2d126b\Payload\SetStressModes_jitstressregs4.cmd 
set COMPlus_TieredCompilation=0
set COMPlus_JitStressRegs=4

C:\dotnetbuild\work\dd0fb0da-9dc2-422a-bb34-0b497b2d126b\Work\e0f577b1-ac35-4da2-8e74-c9e10e160187\Exec>call C:\dotnetbuild\work\dd0fb0da-9dc2-422a-bb34-0b497b2d126b\Payload\SetStressModes_jitstressregs4.cmd 

C:\dotnetbuild\work\dd0fb0da-9dc2-422a-bb34-0b497b2d126b\Work\e0f577b1-ac35-4da2-8e74-c9e10e160187\Exec>set COMPlus_TieredCompilation=0 

C:\dotnetbuild\work\dd0fb0da-9dc2-422a-bb34-0b497b2d126b\Work\e0f577b1-ac35-4da2-8e74-c9e10e160187\Exec>set COMPlus_JitStressRegs=4 

C:\dotnetbuild\work\dd0fb0da-9dc2-422a-bb34-0b497b2d126b\Work\e0f577b1-ac35-4da2-8e74-c9e10e160187\Exec>set COMPlus 
COMPlus_JitStressRegs=4
COMPlus_TieredCompilation=0

C:\dotnetbuild\work\dd0fb0da-9dc2-422a-bb34-0b497b2d126b\Work\e0f577b1-ac35-4da2-8e74-c9e10e160187\Exec>call RunTests.cmd -r C:\dotnetbuild\work\dd0fb0da-9dc2-422a-bb34-0b497b2d126b\Payload --rsp-file C:\dotnetbuild\work\dd0fb0da-9dc2-422a-bb34-0b497b2d126b\Payload\CoreFX.issues.rsp  
----- start Wed 06/26/2019  2:02:08.22 ===============  To repro directly: ===================================================== 
pushd C:\dotnetbuild\work\dd0fb0da-9dc2-422a-bb34-0b497b2d126b\Work\e0f577b1-ac35-4da2-8e74-c9e10e160187\Exec\
"C:\dotnetbuild\work\dd0fb0da-9dc2-422a-bb34-0b497b2d126b\Payload\dotnet.exe" xunit.console.dll System.Threading.Tasks.Dataflow.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonwindowstests -notrait category=OuterLoop -notrait category=failing @C:\dotnetbuild\work\dd0fb0da-9dc2-422a-bb34-0b497b2d126b\Payload\CoreFX.issues.rsp
popd
===========================================================================================================

C:\dotnetbuild\work\dd0fb0da-9dc2-422a-bb34-0b497b2d126b\Work\e0f577b1-ac35-4da2-8e74-c9e10e160187\Exec>"C:\dotnetbuild\work\dd0fb0da-9dc2-422a-bb34-0b497b2d126b\Payload\dotnet.exe" xunit.console.dll System.Threading.Tasks.Dataflow.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonwindowstests -notrait category=OuterLoop -notrait category=failing @C:\dotnetbuild\work\dd0fb0da-9dc2-422a-bb34-0b497b2d126b\Payload\CoreFX.issues.rsp 
  Discovering: System.Threading.Tasks.Dataflow.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Threading.Tasks.Dataflow.Tests (found 290 of 297 test cases)
  Starting:    System.Threading.Tasks.Dataflow.Tests (parallel test collections = on, max threads = 2)

Assert failure(PID 3176 [0x00000c68], Thread: 3368 [0x0d28]): Assertion failed 'regNum != REG_NA' in 'System.Threading.Tasks.Dataflow.BroadcastBlock`1[__Canon][System.__Canon]:.ctor(ref,ref):this' (IL size 232)

    File: f:\workspace.2\_work\1\s\src\jit\lsra.cpp Line: 10413
    Image: C:\dotnetbuild\work\dd0fb0da-9dc2-422a-bb34-0b497b2d126b\Payload\dotnet.exe
```

### PR DESCRIPTION
**Pull request by CarolEidt**
Fix #25433

### CODE REVIEW

**Comment by CarolEidt** [comment]
This code was introduced in #20457
When `compiler->lvaKeepAliveAndReportThis()` is true, we must either keep `this` always in memory, or always in the same register.
This is accomplished via a post-pass over the references. In the case where we are forcing all the references to memory, and we have a `RegOptional` reference, we simply mark it as not getting a register. However, for consistency, the `RefPosition` should *not* be marked `reload` or `spillAfter`.
For this situation, the presence or lack of those flags won't impact the code generation, as the node will be marked as contained, causing the value to be loaded from memory.
This simply makes the `RefPosition` consistent so that the final checks are successful.

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

**Comment by CarolEidt** [comment]
@dotnet/dnceng - it appears that the Windows_NT formatting job is broken. Multiple PRs are getting the following failure:
```
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler
    "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe"
  is not able to compile a simple test program.
  It fails with the following output:
    Change Dir: F:/workspace/_work/1/s/bin/nmakeobj/Windows_NT.x64.Release/CMakeFiles/CMakeTmp
    
    Run Build Command:"nmake" "/nologo" "cmTC_47c73\fast"
    	"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\nmake.exe" -f CMakeFiles\cmTC_47c73.dir\build.make /nologo -L                  CMakeFiles\cmTC_47c73.dir\build
    Building C object CMakeFiles/cmTC_47c73.dir/testCCompiler.c.obj
    	C:\PROGRA~2\MICROS~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx86\x64\cl.exe @C:\Users\vsagent\AppData\Local\Temp\nmB37.tmp
    testCCompiler.c
    Linking C executable cmTC_47c73.exe
    	"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_47c73.dir --manifests  -- C:\PROGRA~2\MICROS~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx86\x64\link.exe /nologo @CMakeFiles\cmTC_47c73.dir\objects1.rsp @C:\Users\vsagent\AppData\Local\Temp\nmBC5.tmp
    LINK Pass 1: command "C:\PROGRA~2\MICROS~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx86\x64\link.exe /nologo @CMakeFiles\cmTC_47c73.dir\objects1.rsp /out:cmTC_47c73.exe /implib:cmTC_47c73.lib /pdb:F:\workspace\_work\1\s\bin\nmakeobj\Windows_NT.x64.Release\CMakeFiles\CMakeTmp\cmTC_47c73.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\cmTC_47c73.dir/intermediate.manifest CMakeFiles\cmTC_47c73.dir/manifest.res" failed (exit code 1104) with the following output:
    LINK : fatal error LNK1104: cannot open file 'ucrtd.lib'
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe"' : return code '0xffffffff'
    Stop.
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\nmake.exe"' : return code '0x2'
    Stop.
```

**Comment by CarolEidt** [comment]
FWIW, I don't think this needs to be back-ported to Preview7, since it is a checked-only issue, and considerably less likely to happen without jitStressRegs.

**Comment by MattGal** [comment]
@CarolEidt : @wtgodbe and I looked at this and it seems to be a regression from VS 15.9.12 -> 15.9.13.  I can add you to the thread where I'm trying to get someone to acknowledge if it you'd like.

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib ping
There are still infra issues in CI, but I'm not going to worry about them. I ran the formatter locally, and the x64 failure is irrelevant since the only changes are under `#ifdef JIT32_GCENCODER`.

**Pull request merged**
