### PR TITLE
Don't optimize MultiplyNoFlags away

### PR DESCRIPTION
**Pull request by fiigii**
Contribute to https://github.com/dotnet/coreclr/issues/21899

### CODE REVIEW

**Comment by fiigii** [comment]
@CarolEidt @AndyAyersMS PTAL

I am not sure if the solution is correct or not. The code below was compiled incorrectly that `MultiplyNoFlags` was optimized away.
```csharp
        static unsafe ulong test(ulong a, ulong b)
        {
            ulong r;
	    Bmi2.X64.MultiplyNoFlags(a, b, &r);
            return r;
        }
```

My current solution is to assign the intrinsic call to a local variable. Although it would have a redundant `ASG` IR for "normal usages" (i.e., `res = Bmi2.X64.MultiplyNoFlags(a, b, &r)`), the final codegen does not have redundant movs.

**Comment by mikedn** [comment]
Hmm, this intrinsic should be treated as a memory store. Is it? I guess this is another peculiar thing about it - the other memory stores don't return a value AFAIR.

**Comment by fiigii** [comment]
Right, the importer usually forces to append the expr into the IR tree if it returns VOID. But this intrinsic has a real return value and memory store semantic simultaneously.

**Comment by tannergooding** [comment]
Do we know why this isn't this covered by it both being a memory store (https://github.com/dotnet/coreclr/blob/master/src/jit/gentree.cpp#L17920) and the intrinsics having been updated to be special handled in `fgComputeLifeLIR` and `fgCheckRemoveStmt` (see https://github.com/dotnet/coreclr/issues/16088 for more details)?

**Comment by fiigii** [comment]
@tannergooding this happens in the importer and doesn’t reach that point.

**Comment by mikedn** [comment]
Check how `GT_CMPXCHG` is handled in the importer, maybe it helps. It has the same characteristics - writes to memory and returns a value.

**Comment by CarolEidt** [comment]
I believe that it needs to be marked as having a side-effect. In the `GT_CMPXCHG` case, this is the `GTF_ASG` flag. The method `GenTree::OperRequiresAsgFlag()` is where the conditions for this are checked. I suspect that any memory store intrinsic should also be handled there.

**Comment by fiigii** [comment]
> I believe that it needs to be marked as having a side-effect. In the GT_CMPXCHG case, this is the GTF_ASG flag.

Ah, thank you so much, will try.

**Comment by fiigii** [comment]
Added `GTF_GLOB_REF` and `GT_ASG` flags to solve the issue. Checked JitDump that does not have redundant IRs or codegen.

@CarolEidt @AndyAyersMS @mikedn PTAL

**Comment by fiigii** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by CarolEidt** [comment]
I think that you should also change `GenTree::OperRequiresAsgFlag()` to return true for these intrinsics. @erozenfeld would know better than I, but I believe that, even though these intrinsics are setting it in the constructor, we may need this to also return true for checking of flags.

**Comment by erozenfeld** [comment]
Yes, `GenTree::OperRequiresAsgFlag()` should also be changed. It's used both for flags validation and for recomputing the flags.

**Comment by fiigii** [comment]
@CarolEidt @erozenfeld `OperRequiresAsgFlag` has already had the code to check these intrinsics. 
https://github.com/dotnet/coreclr/blob/459b58a7766707fb059a5762c7d72cb0af42a6ff/src/jit/gentree.cpp#L5063-L5081

**Comment by CarolEidt** [comment]
> OperRequiresAsgFlag has already had the code to check these intrinsics.

Wow, right there as I was looking at it, and I missed it! Thanks.

**Comment by CarolEidt** [comment]
test Ubuntu arm Cross Checked Innerloop Build and Test

**Pull request merged**
