### PR TITLE
Make FreeBSD handle exceptions like Linux.

### PR DESCRIPTION
**Pull request by josteink**
Partially addresses https://github.com/dotnet/coreclr/issues/626

### CODE REVIEW

**Comment by kangaroo** [comment]
Is the FreeBSD define coming from cpp, or are we defining it in cmake?  If its from CPP, we might want to switch this to a defined() check and not rely on the compiler setting it to 1 for us.

**Comment by josteink** [comment]
I meant that it was the compiler providing it, but I'd hate to make any absolute claims regarding things I'm not certain about, soI devised this little test:

````
$ cat test.cpp
#include <stdio.h> 
int main(void) {
  printf("Start\n");
 
#ifdef __FreeBSD
  printf("#ifdef __FreeBSD");
  printf("\n")
#endif
 
#if __FreeBSD__
  printf("#if __FreeBSD__");
  printf("\n");
#endif
 
#if defined(__FreeBSD__)
  printf("#if defined(__FreeBSD__)");
  printf("\n");
#endif
    }
$

# Linux 
$ clang test.cpp && ./a.out
Start
$

# FreeBSD
$  clang test.cpp && ./a.out
Start
#if __FreeBSD__
#if defined(__FreeBSD__)
$
 
````

As far as I can tell the statements are equivalent. Any reason to prefer one over the other?

**Comment by kangaroo** [comment]
The question is if the compiler is free to chance the preprocessor from:

#define __FreeBSD__ 1

to

#define __FreeBSD__

I think this is highly unlikely.

**Comment by josteink** [comment]
It's easter. Have one for free :)

**Comment by janvorli** [comment]
LGTM

**Pull request merged**
