### PR TITLE
Partially remove relocations from Module section of NGEN-ed images

### PR DESCRIPTION
**Pull request by ruben-ayrapetyan**
Related issue: #10380

@Dmitri-Botcharnikov @gbalykov

### CODE REVIEW

**Comment by ruben-ayrapetyan** [comment]
@jkotas, Please, take a look.

**Comment by jkotas** [comment]
Is this change worth it? There is just one of these sections in the image so the impact is low, and unless you remove all relocations from it you are still going to pay the private page for it.

**Comment by jkotas** [comment]
The part of the change for EEClass looks fine.

**Comment by ruben-ayrapetyan** [comment]
@jkotas, Thank you for review.

The relocations, which were not removed, in most cases are located on the same page, as the `Module` structure. The `Module` structure is modified after being loaded, so the page anyway becomes private.

These changes remove relocations for the following fields:
- `LookupMapBase::pTable`
- `LookupMapBase::pIndex`
- `EEClassOptionalFields::m_pVarianceInfo`
- `DelegateEEClass::m_pInvokeMethod`
- `DelegateEEClass::m_pBeginInvokeMethod`
- `DelegateEEClass::m_pEndInvokeMethod`
- `EEClass::m_pGuidInfo`
- `NgenHashTable::m_pModule`
- `NgenHashTable::m_pWarmBuckets`
- `NgenHashTable::m_sHotEntries.m_pEntries`
- `NgenHashTable::m_sHotEntries.m_pBuckets`
- `NgenHashTable::m_sColdEntries.m_pEntries`
- `NgenHashTable::m_sColdEntries.m_pBuckets`
- `TypeVarTypeDesc::m_pModule`

As far as I understand, the several left fields are those, which exist only in debug build, and also the one in release mode - `LookupMapBase::hotItemList`, which seem to be not fixed up (because there is no profile used).

Is it better to also change the `hotItemList` to relative?

Currently, the changes completely remove Module section's relocations from about 80% of pages on set of images, which was referenced in https://github.com/dotnet/coreclr/issues/11363#issuecomment-299180256). However, the section is sometimes located on same page with other sections, so about 25 of the pages can still contain relocations.

On application, which is referenced in https://github.com/dotnet/coreclr/issues/10380#issuecomment-291146637, the following memory consumption changes occur for mappings of images:
- Rss: 8832 -> 8648 (2% improvement)
- Private_Dirty: 3020 -> 2708 (10% improvement)
- Shared: 5352 -> 5416 (64 kilobytes of Private_Dirty moved there)
- Private_Clean:  460 -> 524 (64 kilobytes of Private_Dirty moved there)

// The base for measurements is currently another than was used in #10380
// Fix of #10382 increased count of relocated images, so the absolute values of memory consumption
// became greater, and so absolute difference related to relocations removal also became greater.

**Comment by jkotas** [comment]
> the changes completely remove Module section's relocations from about 80% of pages

I guess you meant something else than `CORCOMPILE_SECTION_MODULE` ... that's what confused me.

> The relocations, which were not removed, in most cases are located on the same page, as the Module structure

Right. And the Module structure will be pretty much always written into anyway, so it should not matter that it has relocations.

LookupMapBase should be inline in the Module structure, and so the relocations inside should not matter either.

**Comment by ruben-ayrapetyan** [comment]
> I guess you meant something else than CORCOMPILE_SECTION_MODULE

I meant `ModuleSection` (`ZapVirtualSectionType`), which includes `CORCOMPILE_SECTION_MODULE` and `CORCOMPILE_SECTION_MODULE_COLD` (`CorCompileSection`).

> LookupMapBase should be inline in the Module structure, and so the relocations inside should not matter either.

There is `LookupMapBase::pNext` field that seems to be used for pointing to non-inlined map. I missed it at first, because there is no `Fixup` call for the field - only `ZeroPointerField`. Is the field always zero in ngen-ed images?
If so, I think it is better to remove changes for the structure, and otherwise its better to update `hotItemList` and `pNext`.
What do you think about this?

**Comment by jkotas** [comment]
> the field always zero in ngen-ed images?

Correct.

>  I think it is better to remove changes for the structure,

Agree.

**Comment by ruben-ayrapetyan** [comment]
@jkotas, Thank you.

The changes for `LookupMapBase` were removed.

**Comment by jkotas** [comment]
Thanks

**Pull request merged**
