### PR TITLE
Updating the x86 hardware-intrin test templates to use named format arguments

### PR DESCRIPTION
**Pull request by tannergooding**
This modifies the test templates and GenerateTests.csx to use "named arguments" (rather than "indexed arguments") when formatting.

This makes it easier to modify the templates without breaking everything.

### CODE REVIEW

**Comment by tannergooding** [comment]
FYI. @CarolEidt, @fiigii, @4creators

**Comment by 4creators** [comment]
Thanks, this will be very handy.

**Comment by CarolEidt** [comment]
It's just a bit unfortunate that GenerateTests.csx has even longer lines, and yet larger expanses of white space to navigate across when reading, but it's clearly an improvement. Thanks!

**Comment by tannergooding** [comment]
@CarolEidt, we could possibly improve the line situation by having each key-value-pair on its own line, and properly indented for the table.

It would make the file longer (height wise) but possibly easier to read.

Thoughts?

**Comment by CarolEidt** [comment]
> we could possibly improve the line situation by having each key-value-pair on its own line, and properly indented for the table

That might make it easier to navigate, but perhaps something for another day.

**Pull request merged**
