### PR TITLE
Move files to shared CoreLib partition

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
cc @jamesqo This will take care of porting #12692 to CoreRT

**Comment by jkotas** [comment]
@dotnet-bot test Ubuntu arm Cross Release Build please

**Comment by jamesqo** [comment]
> This will take care of porting #12692 to CoreRT

I had forgotten about porting the PR, so sounds good :smile:

**Comment by jkotas** [comment]
@dotnet-bot test Windows_NT x64 corefx_baseline

**Pull request merged**
