### PR TITLE
Fix GC tests.

### LINKED ISSUE #17588: [arm32/Ubuntu] Failures in R2R JitStressRegs3
These may occur in the baseline, but I haven't seen results there due to infrastructure issues.

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_r2r_jitstressregs3_tst/2/consoleText

Tests:
```
GC/Scenarios/DoublinkList/dlbigleakthd/dlbigleakthd.sh
GC/Scenarios/DoublinkList/dlbigleakthd_v2/dlbigleakthd_v2.sh
GC/Scenarios/DoublinkList/doublinkstay/doublinkstay.sh
```

Failures:
```
FAILED   - GC/Scenarios/DoublinkList/dlbigleakthd/dlbigleakthd.sh
               BEGIN EXECUTION
               in takeLock
               /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstressregs3_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/crossgen /Platform_Assemblies_Paths /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstressregs3_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root:/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstressregs3_tst/bin/tests/Linux.arm.Checked/GC/Scenarios/DoublinkList/dlbigleakthd/IL:/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstressregs3_tst/bin/tests/Linux.arm.Checked/GC/Scenarios/DoublinkList/dlbigleakthd /in dlbigleakthd.org /out dlbigleakthd.exe
               Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
               Copyright (c) Microsoft Corporation.  All rights reserved.
               
               Native image dlbigleakthd.exe generated successfully.
               in ReleaseLock
               in takeLock
               /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstressregs3_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun dlbigleakthd.exe
               Test should return with ExitCode 100 ...
               980/1000 DLinkNodes finalized
               Test Failed
               in ReleaseLock
               Expected: 100
               Actual: 1
               END EXECUTION - FAILED
FAILED   - GC/Scenarios/DoublinkList/dlbigleakthd_v2/dlbigleakthd_v2.sh
               BEGIN EXECUTION
               in takeLock
               /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstressregs3_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/crossgen /Platform_Assemblies_Paths /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstressregs3_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root:/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstressregs3_tst/bin/tests/Linux.arm.Checked/GC/Scenarios/DoublinkList/dlbigleakthd_v2/IL:/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstressregs3_tst/bin/tests/Linux.arm.Checked/GC/Scenarios/DoublinkList/dlbigleakthd_v2 /in dlbigleakthd_v2.org /out dlbigleakthd_v2.exe
               Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
               Copyright (c) Microsoft Corporation.  All rights reserved.
               
               Native image dlbigleakthd_v2.exe generated successfully.
               in ReleaseLock
               in takeLock
               /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstressregs3_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun dlbigleakthd_v2.exe
               Test should return with ExitCode 100 ...
               980/1000 DLinkNodes finalized
               Test Failed
               in ReleaseLock
               Expected: 100
               Actual: 1
               END EXECUTION - FAILED
FAILED   - GC/Scenarios/DoublinkList/doublinkstay/doublinkstay.sh
               BEGIN EXECUTION
               in takeLock
               /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstressregs3_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/crossgen /Platform_Assemblies_Paths /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstressregs3_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root:/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstressregs3_tst/bin/tests/Linux.arm.Checked/GC/Scenarios/DoublinkList/doublinkstay/IL:/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstressregs3_tst/bin/tests/Linux.arm.Checked/GC/Scenarios/DoublinkList/doublinkstay /in doublinkstay.org /out doublinkstay.exe
               Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
               Copyright (c) Microsoft Corporation.  All rights reserved.
               
               Native image doublinkstay.exe generated successfully.
               in ReleaseLock
               in takeLock
               /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstressregs3_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun doublinkstay.exe
               Test should return with ExitCode 100 ...
               19990 DLinkNodes finalized
               Test Failed
               in ReleaseLock
               Expected: 100
               Actual: 1
```

### PR DESCRIPTION
**Pull request by sandreenko**
Jit can extend lifetime of temp objects after call to GC.Collect(), so we should not have any temp in the same scope with final `GC.Collect();`.

incorrect example 1:
```
var a = new Object(); // Jit can create a temp that will be alive after GC.Collect().
a = null;
GC.Collect();
GC.WaitForPendingFinalizers();
GC.Collect();
```

incorrect example 2:
```
SetLink();
GC.Collect();
GC.WaitForPendingFinalizers();
GC.Collect();

void SetLink() // this method could be inlined, we will get the first example.
{
       var a = new Object();
       a = null;
}
```

Incorrect example 3:
```
var a = SetLink(); // Jit can create a temp here with a long lifetime.
a = null;
GC.Collect();
GC.WaitForPendingFinalizers();
GC.Collect();

[MethodImpl(MethodImplOptions.NoInlining)]
Object SetLink()
{
       return new Object();
}
```

correct example 1:
```
SetLink();
GC.Collect();
GC.WaitForPendingFinalizers();
GC.Collect();

[MethodImpl(MethodImplOptions.NoInlining)]
void SetLink() // All temps are in this method and it is protected with NoInlining attribute.
{
       var a = new Object();
       a = null;
}
```

Fixes #17588.

The same problem as #15156.

### CODE REVIEW

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs3 Build and Test

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT arm Cross Checked r2r_jitstressregs3 Build and Test

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT arm Cross Checked r2r_jitstressregs3 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs3 Build and Test

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT arm Cross Checked r2r_jitstressregs3 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs3 Build and Test

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT arm Cross Checked r2r_jitstressregs3 Build and Test
@dotnet-bot test Windows_NT arm Cross Checked jitstress2_jitstressregs3 Build and Test

**Comment by sandreenko** [comment]
cc @Maoni0

**Comment by Maoni0** [comment]
thanks!

**Pull request merged**
