### PR TITLE
Upstream source build patches

### PR DESCRIPTION
**Pull request by ellismg**
This is a set of patches I've developed to aid in building CoreCLR as part of Red Hat's build process.

At a high level, we have the following changes:

1. Remove the dependency on the source tree being a git repository by allowing us to pass some git information (the SHA1 of the logical "HEAD commit " and the date of that commit) to the build. This information is fed into the versioning logic we have.
2. Support "offline" mode of init-tools.sh where it will just copy a pre-existing version of the CLI instead of downloading one. This mode is activated by setting `DOTNET_TOOLSET_DIR` to a directory which has a subfolder who's name matches what's in `DotnetCLIVersion.txt`.  In addition, we provide the same behavior for `BUILD_TOOLS_TOOLSET_DIR` to pick up a local copy of BuildTools.  Note in both cases we just do a straight copy of what ever is in these folders, with no post-processing afterwards (e.g. we don't call the "second stage" init-tools.sh, we assume the output we are picking up already had it run)
3. Move to the newest version of buildtools that's in use between CoreCLR, CoreFX and Core-Setup. This is to remove duplication when we need to carry pre-downloaded copies of build tools with us.

### CODE REVIEW

**Comment by ellismg** [comment]
@gkhanna79 When the merge window for 1.1.0 RTM is open, I would like to land these changes, to reduce the number of Red Hat specific patches Red Hat needs as part of their source build.  I will be making similar changes in CoreFX and Core-Setup.

**Comment by gkhanna79** [comment]
@ellismg Sounds good. It will likely be next week.

**Comment by ellismg** [comment]
Due to the tight timeline for 1.1, I'm not going to try to land this for 1.1.  We can continue to apply the patches locally to get the behavior we want.  The actual relevant fixes have been merged into master already.

**Comment by vindicatorr** [comment]
AGH! Why was offline stuff DOTNET_TOOLSET_DIR and BUILD_TOOLS_TOOLSET_DIR removed? f75e211ded5c832611f140c0f4ed710425c73772
I thought it was a great idea.

**Pull request closed without merging**
