### PR TITLE
Added dumpling collection for the CI to pick up.

### PR DESCRIPTION
**Pull request by bryanar**
Testing a CI extension + dump collection in Ubuntu tests (hence the code that is meant to cause a crash).

This PR is likely to be closed and reopened a handful of times, and also contain commits that we do NOT want kept around.

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Comment by mmitche** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Comment by mmitche** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Comment by adityamandaleeka** [comment]
Hey @bryanar the code where you injected the bug is part of a test that's been disabled on Linux, so it's being skipped (hence the passing CI).

BTW, can you add a comment to this PR explaining what this change is intended for?

**Comment by bryanar** [comment]
@adityamandaleeka  Thank you Aditya! I'll move my crash to another test :P

**Comment by bryanar** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Comment by adityamandaleeka** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Comment by bryanar** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Pull request closed without merging**
