### PR TITLE
[release/2.1] Port Preserve pinned flag in {ReadOnly}Memory<T>.Slice

### PR DESCRIPTION
**Pull request by ahsonkhan**
Fixes https://github.com/dotnet/corefx/issues/29239 (from https://github.com/dotnet/coreclr/pull/17712)

cc @joshfree, @GrabYourPitchforks, @geoffkizer, @stephentoub, @benaadams, @davidfowl

### CODE REVIEW

**Comment by davidfowl** [comment]
There needs to be a test for this.

**Comment by ahsonkhan** [comment]
> There needs to be a test for this.

There is a PR with tests in master. Since it depends on a new coreclr build, we need the change to propagate first.
https://github.com/dotnet/corefx/pull/29257

**Comment by danmosemsft** [comment]
@ahsonkhan can you manually mirror into corefx until mirror is up?

**Comment by ahsonkhan** [comment]
> can you manually mirror into corefx until mirror is up?

It already got merged: https://github.com/dotnet/corefx/pull/29252

**Pull request merged**
