### PR TITLE
Update prerelease label and dependencies.props

### PR DESCRIPTION
**Pull request by zamont**

### CODE REVIEW

**Comment by zamont** [comment]
@tommcdon This results in the dependency updates pulling in the latest release/uwp6.2 versions of CoreCLR/CoreFX, and release/2.1 of the other dependencies.

**Comment by zamont** [comment]
After the second commit, the dependencies are now release/2.1 for all dependencies except for release/uwp6.2 for CoreCLR

**Comment by zamont** [comment]
> Extract.SByte.1.cs(136,17): error CS1503: Argument 1: cannot convert from 'System.Runtime.Intrinsics.Vector256<sbyte>' to 'System.Runtime.Intrinsics.Vector256<byte>' [D:\j\workspace\x64_checked_w---12a1553c\tests\src\JIT\HardwareIntrinsics\X86\Avx\Avx_r.csproj]

@sergiy-k do you know what this might be about? I'm skeptical that updating the dependencies would cause this error.

**Comment by AndyAyersMS** [comment]
We made a breaking change to System.Runtime.Intrinsics.Experimental that could be inadvertently getting pulled in. You may need the same fix as in #19260.

**Pull request merged**
