### PR TITLE
Add build-tools.cmd

### PR DESCRIPTION
**Pull request by janvorli**
This script builds selected tools in the src/tools directory (for the
time being, it builds just the runincontext tool). This is a preparation
step to enable nightly runs with unloadability tests. The
build-tools.cmd should build helper tools needed during test runs.

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
cc @RussKeldorph

**Comment by AaronRobinsonMSFT** [comment]
I think it would make a lot more sense if the needed tools were chained into `tests\build.proj` via project reference. This would ensure the projects are built when needed and the new script is no longer needed.

**Comment by janvorli** [comment]
@AaronRobinsonMSFT we had some discussion with @echesakovMSFT  and @jashook about this some time ago and they have recommended adding this script so that the tool can be used in test running. They said that if it was build as part of the tests (which was what I was doing originally when I've added the tool - it used to live under tests\src\Common), there would be a problem with the lab testing infra due to the partitioning of the tests. They suggested to move it to src\tools and add a build script.
I don't really care how this thing is build as long as it can be used in nightly test runs.

**Comment by RussKeldorph** [comment]
@janvorli The build system has evolved quite a bit since your earlier discussions.  It's possible, but I'm not certain that they have evolved to the point that we have a good story for how this tool should build yet.  It might be worth another meeting with everyone mentioned here to see if there is an obvious best answer now.  This doesn't look that hard to clean up later, so I'm not necessarily opposed to checking this in as is, but we should synch on where we are.

**Comment by AaronRobinsonMSFT** [comment]
> they have recommended adding this script so that the tool can be used in test running

@janvorli Okay, thanks for the additional context. I agree with @RussKeldorph that the meeting in question was probably before the recent changes and the original way you were proposing should now be feasible. I would really like to avoid new scripts if possible since there are simple way to chain in the logic contained in the two function lines of the script.

If this is a pressing change we should of course check this in and unblock your progress since it was the POR, but it would be a form of debt that will need to be folded into an MSBuild project at some point.

**Comment by jashook** [comment]
My personal preference would not be to fold this into build.cmd. The following are tools that for many do not need the tests to be built, some do not require the product to be built:

```
r2rdump
superpmi
runincontext
CheckProjects
```

In general the tools have more in common with tests than the product, and if we were to fold them somewhere I would prefer they remain as a separate step in build-test.cmd/sh. However, all these tools are more or less not required for our product/build. I understand the desire to have less cmd/sh scripting, I think we all share the vision; however, the logic to add to build-test.cmd/sh is not straightforward. We would essentially be adding a new run mode to the test build, where we do not build the tests only build the tools. Which is the essentially the same thing as a separate script, just less intuitive.

**Comment by AaronRobinsonMSFT** [comment]
@jashook I am not tied to `build.cmd` or `build-test.cmd`, which ever makes most sense for the scenario. In principle there should be at most 2 main scripts in this entire repo (`dotnet.cmd` and `init.cmd`). All other logic should be folded into an MSBuild project and called as `dotnet.cmd <project>.proj`. There is little need for any of these scripts other than personal preference for scripting rather than MSBuild - I would be interested in any counter examples this principle.

**Comment by echesakovMSFT** [comment]
@AaronRobinsonMSFT Personally, I did not know that we want to converge to "at most 2 scripts in the repo". So in this case we would just call `dotnet.cmd src/tools/runincontext/runincontext.csproj`?

**Comment by janvorli** [comment]
@AaronRobinsonMSFT I am actually not sure how we could get rid of the build.cmd - a lot of the logic in there is related to native build using cmake. And it would worry me to switch that to be driven by some msbuild logic. For bootstrapping new platforms, it would be really bad. The way the bootstrapping works is that you first bring up the native build and just copy managed assemblies from a platform that can already build them. And only once native components from coreclr, corefx and core-setup repos work, we can forge a bootstrap cli that allows us to start building managed code on that platform.

**Comment by AaronRobinsonMSFT** [comment]
>And it would worry me to switch that to be driven by some msbuild logic. For bootstrapping new platforms, it would be really bad

@janvorli There are definitely issues with that and I fully agree with the above statement. It is more aspirational than anything, but I think we can address even new platform bring up. However, that is all much farther down the road and not something we need to address at the moment.

After chatting with @echesakovMSFT and @jashook , I can see how we got here and in the spirit of moving forward I think we should just get this in and we can fold this into the longer term plan of moving logic to MSBuild. Alternatively you could try and add project references to `src/build.proj` and `tests/build.proj` and see if that works - which would be the ideal solution. If that proves to be too much then please consider me signed off once the CI is green.

**Comment by janvorli** [comment]
I've removed the build-tools script and added building of the runincontext into the src/build.proj. I've also updated the runincontext.csproj and R2RDump.csproj to place the binaries into the bin/Project/... folder.
@echesakovMSFT, @jashook, @AaronRobinsonMSFT can you please take a look?

**Comment by echesakovMSFT** [comment]
@janvorli Can you please open an issue on GitHub describing the remaining work for runincontext nightly testing?

**Comment by janvorli** [comment]
@echesakovMSFT there already is an issue for that, #20168. I've just added details on how to execute the tests in this mode both using the scripts or by setting env variables (which is, IIRC, the way you'd use in the lab tests)

**Pull request merged**
