### PR TITLE
Removed dead strings used in debug-only code

### LINKED ISSUE #18420: Make a pass to remove dead strings from mscorrc.rc
Some strings in [mscorrc.rc](https://github.com/dotnet/coreclr/blob/master/src/dlls/mscorrc/mscorrc.rc) seem to be dead. eg
`IDS_SERIALIZATION_NONFREEZABLE_TYPE` `IDS_EE_IJWLOAD_CROSSVERSION_DISALLOWED` `IDS_EE_TORNSTATE` `IDS_CLASSLOAD_SH_SUBCLASS_FINALIZER`

It should not be too hard to write a script that removes any strings whose identifiers only appear in mscorrc\mscorrc.rc and mscorrc\resource.h.

Separately, src\inc\corerror.xml which generates mscorurt.rc and coreerror.h may also be worth looking at. eg : `CLR_OPTSVC_E_CONTROLLER_INTERRUPT` `NGEN_E_EXE_MACHINE_TYPE_MISMATCH`

### PR DESCRIPTION
**Pull request by hsharber**
Removed strings used in debug-only code in ex.cpp

Fix #18420

### CODE REVIEW

**Comment by jkotas** [comment]
Thank you for doing this!

Could you please share the process you have used to do this? Have you used any scripts to automate this?

I have spot checked the delta. I did not find anything deleted but should not have been (good!). I have found some that I think might have been deleted, but they were not. For example, `VER_E_STACK_P_VALCLASS_OBJREF_VAR` or `VER_E_INITIALIZE_ARRAY_MISSING_TOKEN` does not seem to be used anywhere.

**Comment by hsharber** [comment]
The first PR that I did on this issue, I looked at all the strings in \src\dlls\mscorrc\mscorrc.rc and searched the codebase to determine which ones appeared only in \src\dlls\mscorrc\resource.h. Also, I removed those in \src\inc\corerror.xml that were found only in \src\pal\prebuilt\inc\corerror.h

In this second PR, I looked only at the strings that were in the DEBUG section of \src\utilcode\ex.cpp and removed them if they were only found in \src\dlls\mscorrc\mscorrc.rc or \src\inc\corerror.xml or \src\pal\prebuilt\inc\corerror.h or \src\pal\prebuilt\corerror\mscorurt.rc

I both cases, I wrote a few lines of code to find the strings that met the criteria.

I noticed that the second PR failed two checks related to test artifacts. I not sure how the error message in the log relates to the changes that I've made.

**Comment by jkotas** [comment]
Thanks. Would you mind doing more scrub for strings like `VER_E_STACK_P_VALCLASS_OBJREF_VAR or `VER_E_INITIALIZE_ARRAY_MISSING_TOKEN`  ?

> I noticed that the second PR failed two checks related to test artifacts

It is infrastructure problem.

**Comment by hsharber** [comment]
Sure. In fact I did a search for strings that appear in
\src\inc\corerror.xml

and only appear in one or more of the following:

\src\dlls\mscorrc\mscorrc.rc
\src\pal\prebuilt\corerror\mscorurt.rc
\src\pal\prebuilt\inc\corerror.h

There are 143 including the two that you cited. The list is attached.
[coreclr_4.txt](https://github.com/dotnet/coreclr/files/2131569/coreclr_4.txt)

Do you think is it safe to remove all of these?

**Comment by jkotas** [comment]
Yes, I think it is safe to remove all of these.

**Pull request merged**
