### PR TITLE
Add test for issue 4115.

### PR DESCRIPTION
**Pull request by LLITCHEV**
This test exposes the problem described in issue 4115. At the
current state of GC stress the test will not fail deterministically. When
a guaranteed move objects on GC in stress mode happens the test will fail
deterministically.

### CODE REVIEW

**Comment by LLITCHEV** [comment]
@RussKeldorph @pgavlin @swaroop-sridhar PTAL
/cc @dotnet/jit-contrib

**Comment by swaroop-sridhar** [comment]
Ref: #4115, #4222

**Comment by swaroop-sridhar** [comment]
LGTM

**Comment by LLITCHEV** [comment]
@dotnet-bot test Windows_NT x86 Debug Legacy Backend Build and Test please

**Pull request merged**
