### PR TITLE
Enable HighEntropyVA in mscorlib.dll

### PR DESCRIPTION
**Pull request by JohnChen0**

### CODE REVIEW

**Comment by gkhanna79** [comment]
@jkotas PTAL as well.

**Comment by jkotas** [comment]
@dotnet/jit-contrib The JIT formatting tests are failing on all PRs. Could you please take a look?

**Comment by adiaaida** [comment]
Thanks Jan. I'll open a jitutils issue for this.

**Comment by adiaaida** [comment]
Ah. @sbomer introduced a change that seems to have caused this. He's going to revert his change.

**Comment by sbomer** [comment]
Fixed in [jitutils](https://github.com/dotnet/jitutils/commit/470d8d6908fc0cb85f53de91ea41ba1a20945a66).
@dotnet-bot test Ubuntu x64 Formatting please
@dotnet-bot test Windows_NT x64 Formatting

**Pull request merged**
