### PR TITLE
Revert: Simplify test dependencies for benchmarks

### PR DESCRIPTION
**Pull request by AndyAyersMS**
This reverts commit 0598b6b8af0fb560837ce0bb8f3c8236c05bbdc9.

Updates to xunit console runner breaks building tests in Helix. So reverting
until we can get that part sorted.

See dotnet/core-eng#2781.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
Hmm, looks like we can't update xunit perf like I thought. Will need to undo the most recent commit.

**Comment by brianrob** [comment]
@AndyAyersMS, I'm surprised that you need to undo #16597 as well.  The difference between the two versions of xunit.performance shouldn't have any dependency changes other than TraceEvent which didn't change its dependencies.  Were there changes directly in xunit.performance that broke?

**Comment by AndyAyersMS** [comment]
As part of all this reversion we're temporarily back to netstandard1.4 for the benchmarks, and that led to package errors [like this](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_windows_nt_innerloop_prtest/1175/) before I reverted your update:
```
error NU1202: Package xunit.performance.api 1.0.0-beta-build0018 is not compatible 
    with netstandard1.4 (.NETStandard,Version=v1.4). 
    Package xunit.performance.api 1.0.0-beta-build0018 supports: 
error NU1202: - net461 (.NETFramework,Version=v4.6.1) 
error NU1202: - netstandard1.6 (.NETStandard,Version=v1.6)
```
It might be we could make it to up to netstandard1.6 without too much trouble. We are limited in how far forward we can go by the prerelease xunit.console.netcore that helix tests builds rely on.

**Comment by AndyAyersMS** [comment]
Arm tests currently taking forever, and nothing arm specific here. So I am going to merge to try and unblock things.

**Pull request merged**
