### PR TITLE
Simple serialization benchmarks

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Benchmarking a few serialization methods. Not really trying to compare them, just setting things up to see how well the JIT does at each.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@cmckinsey PTAL (or anyone else interested)

**Comment by mikedn** [comment]
Have you tried to profile the tests to see if the result is significant as far as the JIT is concerned? It's possible that the time includes reflection, garbage collection and who knows what else.

**Comment by AndyAyersMS** [comment]
@mikedn The profile looks reasonable for a first cut. About 0.5% time in GC, 15% time in the jit (when run as an exe -- this should get factored out in xunit-performance mode as we'll discard the warm up iteration), most of the rest of the time in the jitted code. Might hit the float artifacts like the CRT"s `ecvt` and the CoreDLL's `NumberToString` a bit too hard.

**Comment by AndyAyersMS** [comment]
Added simple benchmarks for deserialization.

Anyone on @dotnet/jit-contrib feel free to PTAL.

**Comment by kyulee1** [comment]
LGTM. Nit. Can we just inline DeserializeObject() into Deserialize()? Probably same thing for SerializeObject() into Serialize(). I'm also seeing cases where *Bench() simply invokes *BenchInner(). But if you want to keep them for consistency, it's okay too.

**Comment by LLITCHEV** [comment]
LGTM

**Comment by AndyAyersMS** [comment]
@kyulee1 will probably leave as is in case I expand this later to include other aspects.

Odd that the CI report above says two checks are pending but when clicking through they are done. Will wait a bit and see if the status updates, if not I'll merge anyways.

**Pull request merged**
