### PR TITLE
JIT: make sure to use normalized type when retyping box temp

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Take advantage of the fact that `lvaSetStruct` figures out the right
type to use in the IR.

Fixes first part of #20260.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@echesakov PTAL
cc @dotnet/jit-contrib 

No diffs from PMI, though corelib diffs were incomplete because of #20284.

**Comment by echesakovMSFT** [comment]
> No diffs from PMI, though corelib diffs were incomplete because of #20284.

You can run `pmi.dll DriveAll` to get the rest of SPC jitted.

**Comment by AndyAyersMS** [comment]
Need to update the test as expected output depends on vector length.

**Comment by AndyAyersMS** [comment]
Since we have some successful arm testing for Ubuntu I'll skip waiting for the windows arm testing.

**Pull request merged**
