### PR TITLE
Fix SIGSEGV in EventPipe on Shutdown (#14123)

### PR DESCRIPTION
**Pull request by nategraf**
This PR fixes a segmentation fault which occurs on EventPipe Shutdown

Follow-up  #15147

### CODE REVIEW

**Comment by vancem** [comment]
Do we know what is going on with ARM builds?

**Comment by nategraf** [comment]
Three failed because they couldn't pull artifacts from Jenkins. One with this message

```
11:46:52 The input line is too long.
11:46:52 :export_x86
11:46:52  was unexpected at this time.
11:46:52 
```

I'm rerunning all 4

**Comment by vancem** [comment]
Nate, can you describe roughly what cause the segment violation and high level goal of the changes you are making and how it fixes that issue?

**Comment by nategraf** [comment]
So the issue is a double delete of the m_pConfigProvider, which is an EventPipeProvider held by the EventPipeConfiguration. Because it was tracked both in a private variable pointer and in the list of registered providers it had the potential to be deleted twice. This occured when the m_pConfigProvider was deleted, but not deregistered from the provider list, then deleted again from its registration entry

These changes, written mostly by Brian with one fix from me, change how registration and deregistration is handled, which allows use to ensure it is handled properly.

**Comment by vancem** [comment]
Nate, I have approved, this.  There is the nagging issue of the failed tests, which seem to be infrastructure issues.   We should check if other PRs are having the same problem.   We should invest some time in trying to get it fixed, but it does look like the failures are unrelated to this change.

**Comment by nategraf** [comment]
OK, I will do that. If I am confident it’s just infrastructure I will send a request to ship room to get this merged

**Comment by nategraf** [comment]
@jashook @RussKeldorph this seems to be the issue related to https://github.com/dotnet/coreclr/pull/15067

**Comment by RussKeldorph** [comment]
@nategraf Yes, arm testing in 2.0 is offline and we are working on it.  You should not block on it at the moment.

**Comment by Imisnew2** [comment]
@nategraf Is this issue the correct issue to follow to see when this fix makes it into a servicing release? #16084 doesn't have any details and this issue is now marked 'merged', so I'm left wondering.

**Comment by nategraf** [comment]
@Imisnew2  Sorry for the confusion: I had merged this PR without realising `release/2.0.0` was closed at the time. These changes are now in #16152 which will be merged for servicing release 2.0.7

**Pull request merged**
