### PR TITLE
Bug Fix: Calling System.Diagnostics.Tracing.EventPipe.Enable twice asserts #22247

### LINKED ISSUE #22247: Calling System.Diagnostics.Tracing.EventPipe.Enable twice asserts
While running unloadability tests in a mode where each coreclr test is executed **twice** in the same process, I have hit an assert in the CLREventBase::CreateManualEvent called from SampleProfiler::Enable due to the fact that the event was already created before.
I have investigated it a bit and the issue has nothing to do with unloadability and just the sequence of calling System.Diagnostics.Tracing.EventPipe.Enable / System.Diagnostics.Tracing.EventPipe.Disable / System.Diagnostics.Tracing.EventPipe.Enable causes the assert.

I've hit that while running the `tracing\tracevalidation\jittingstarted`, `tracing\tracevalidation\inducedgc` and `tracing\tracevalidation\rundown` tests.

### PR DESCRIPTION
**Pull request by jorive**
After disabling EventPipe -> SampleProfiler, we were not closing the thread shutdown event, thus asserting on reentrance of the EventPipe::Enable.
```log
Assert failure(PID 20732 [0x000050fc], Thread: 672 [0x02a0]): Precondition failure: FAILED: (m_handle == ((HANDLE)(LONG_PTR)-1))

CORECLR! CHECK::Trigger + 0x2C4 (0x00007ffd`628fcf94)
CORECLR! CLREventBase::CreateManualEvent + 0x1D1 (0x00007ffd`62a5cc05)
CORECLR! SampleProfiler::Enable + 0x47C (0x00007ffd`6307ff4c)
CORECLR! EventPipe::Enable + 0x383 (0x00007ffd`62ceead3)
CORECLR! EventPipe::Enable + 0x102 (0x00007ffd`62ceec76)
CORECLR! EventPipeInternal::Enable + 0x174 (0x00007ffd`62ceee44)
<no module>! <no symbol> + 0x0 (0x00007ffd`037a9fce)
<no module>! <no symbol> + 0x0 (0x00000000`000f4240)
<no module>! <no symbol> + 0x0 (0x00000000`00000400)
    File: c:\github\jorive\coreclr\src\vm\synch.cpp Line: 74
    Image: C:\GitHub\jorive\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe
```
Fixes #22247

### CODE REVIEW

**Comment by jorive** [comment]
I'm testing now, I'll add it with this PR.

**Comment by jorive** [comment]
After doing some more testing with a slightly modified version of this bug I encounter this new issue https://github.com/dotnet/coreclr/issues/22337

**Comment by jorive** [comment]
@dotnet-bot test this please

**Comment by jorive** [comment]
@dotnet-bot test this please

**Comment by jorive** [comment]
[Windows_NT x64 Checked Innerloop Build and Test](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_windows_nt_innerloop_prtest/12146/)
```log
#################################################################
Output of failing tests:

[D:\j\workspace\x64_checked_w---eac6a79c\bin\tests\Windows_NT.x64.Checked\tracing\regress\GitHub_22247\GitHub_22247\GitHub_22247.cmd]: 


Assert failure(PID 4364 [0x0000110c], Thread: 4536 [0x11b8]): Precondition failure: FAILED: (m_handle != ((HANDLE)(LONG_PTR)-1))
    File: d:\\j\\workspace\\x64_checked_w---eac6a79c\\src\\vm\\synch.cpp Line: 338
    Image: D:\\j\\workspace\\x64_checked_w---eac6a79c\\bin\\tests\\Windows_NT.x64.Checked\\Tests\\Core_Root\\CoreRun.exe



Return code:      1
Raw output file:      D:\\j\\workspace\\x64_checked_w---eac6a79c\\bin\\tests\\Windows_NT.x64.Checked\\Reports\\tracing.regress\\GitHub_22247\\GitHub_22247\\GitHub_22247.output.txt
Raw output:
BEGIN EXECUTION
 \"D:\\j\\workspace\\x64_checked_w---eac6a79c\\bin\\tests\\Windows_NT.x64.Checked\\Tests\\Core_Root\\corerun.exe\" GitHub_22247.exe 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1

To run the test:
> set CORE_ROOT=D:\\j\\workspace\\x64_checked_w---eac6a79c\\bin\\tests\\Windows_NT.x64.Checked\\Tests\\Core_Root
> D:\\j\\workspace\\x64_checked_w---eac6a79c\\bin\\tests\\Windows_NT.x64.Checked\\tracing\
egress\\GitHub_22247\\GitHub_22247\\GitHub_22247.cmd

Expected: True
Actual:   False
```

**Comment by jorive** [comment]
@dotnet-bot test this please

**Comment by jorive** [comment]
@noahfalk @vancem Could you please take another look?

**Comment by vancem** [comment]
Definitely better to only close event after you finish waiting on it (that is last use).   
I approve this.

**Comment by jorive** [comment]
Thanks @vancem. I have also changed the call to `Wait` from `0` to `INFINITE` (before we were returning and calling `CloseEvent` before signaling that the thread was done).

**Comment by vancem** [comment]
@jorive.  Yes, waiting (forever if needed) until the event is set is definitely needed.

**Pull request merged**
