### PR TITLE
Add DefaultBinder.CanChangePrimitive overload

### PR DESCRIPTION
**Pull request by EgorBo**
We'd like to re-use this type conversion check in Mono's managed version of `Array.Copy` and in order to be able to normalize (like @jkotas did [here](https://github.com/dotnet/coreclr/pull/25209/files#diff-b378ad87d76d7a53ad8576a457eee387R1406)) types we need an overload accepting TypeCodes instead of Types. Probably makes sense to move this logic to a separate class? 

/cc @jkotas @filipnavara

### CODE REVIEW

**Comment by jkotas** [comment]
>  in order to be able to normalize

How are you going to normalize {U}IntPtrs with TypeCodes? TypeCode is not able to describe {U}IntPtr.

**Comment by EgorBo** [comment]
@jkotas in a separate check (just like this CanChangePrimitive(Type,Type) actually contains an additional check for them)

**Comment by jkotas** [comment]
Does Mono uses TypeCode in lower-level parts like `Array.Copy` or casting, or does it use something else like `ELEMENT_TYPE`?

CoreCLR uses `ELEMENT_TYPE` in the lower-level parts. The advantage of using `ELEMENT_TYPE` is that it has the right level of expressiveness. E.g. it has value for `{U}IntPtr`. I am wondering whether it would be better to leave this one alone, and rather introduce a different method that operates with `ELEMENT_TYPE`.

**Comment by EgorBo** [comment]
I think you are right, I see I can actually do it in the native code indeed.

**Pull request closed without merging**
