### PR TITLE
Use PublishBuildArtifacts instead of PublishPipelineArtifact

### PR DESCRIPTION
**Pull request by echesakovMSFT**
Workaround #24787

### CODE REVIEW

**Comment by jahsu-MSFT** [comment]
@echesakovMSFT Thanks for checking. Looks like it's getting the same "TF400677: Host b55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8 does not exist." error when using PublishBuildArtifacts task? 
I'm current not sure how this error can be related to the changes for the default artifact name but let me know if there is a need to revert the changes.

**Comment by echesakovMSFT** [comment]
@jahsu-MSFT 
>  Looks like it's getting the same "TF400677: Host b55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8 does not exist." error when using PublishBuildArtifacts task?

No, PublishBuildArtifacts works fine. If you look at Build jobs - they all succeeded. The failures you see are coming from the remaining usages of PublishPipelineArtifact in test-job.yaml.

However, there is a difference in behavior between DownloadBuildArtifacts and DownloadPipelineArtifact. The former creates a folder with artifact name while the latter doesn't. Our pipeline needs to account for this.

**Comment by echesakovMSFT** [comment]
@sandreenko @RussKeldorph @elinor-fung PTAL

**Comment by stephentoub** [comment]
Merging to unblock CI.

**Comment by echesakovMSFT** [comment]
@RussKeldorph 

> Could you explain what happened to make this necessary?

I don't know about the root cause of https://github.com/dotnet/coreclr/issues/24787 but for some reason PublishPipelineArtifact stopped working in CI - this PR was an attempt to mitigate the issue and unblock CI by switching to "functioning" PublishBuildArtifacts task which has slightly different behavior but does its job of moving artifacts from one pipeline job to another.

**Pull request merged**
