### PR TITLE
Add XUnit results for Windows_NT x86 jobs.

### PR DESCRIPTION
**Pull request by pgavlin**
Just what it says on the tin.

### CODE REVIEW

**Comment by pgavlin** [comment]
@mmitche PTAL

**Comment by pgavlin** [comment]
@dotnet-bot test ci please

**Comment by pgavlin** [comment]
cc @russellhadley @RussKeldorph

**Comment by pgavlin** [comment]
(and @jashook)

**Comment by jashook** [comment]
We will need to make sure that this will not cause job failures for arm64 windows. I believe it will not, but it will be worth explicitly checking post checkin.

**Comment by russellhadley** [comment]
Speaking of multiple target.  Will will just start getting arm64 and arm32 results from this too?  Is it really only x86?

**Comment by jashook** [comment]
Arm64 Windows will not come online with this, we still need to enable xunit archiving for the jobs. Once arm64 unix is online though it will be enabled.

**Comment by pgavlin** [comment]
> We will need to make sure that this will not cause job failures for arm64 windows
> ...
> Speaking of multiple target. Will will just start getting arm64 and arm32 results from this too? Is it really only x86?

The affected code is guarded on Windows_NT + {x86,x64} + !buildOnly, so it really should be just x86 jobs.

**Comment by jashook** [comment]
I see makes sense.

**Pull request merged**
