### PR TITLE
JIT: describe requested and actual opt levels more accurately

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Note in jit dump headers and in `COMPlus_DumpJittedMethods` traces when the jit
changed the optimization level that the VM requested.

Also remove the FCOMI handling in the jit, x87 is not longer a thing. Needs to
stay in the options for now though.

Finally, reorder the `Options` struct fields to avoid gratiuitous padding.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
Some follow up from https://github.com/dotnet/coreclr/pull/27079#discussion_r332347806

@sandreenko PTAL
cc @dotnet/jit-contrib 

Sample output:
```
Compiling   10 System.Runtime.Intrinsics.Vector128::AsByte, IL size = 7, hsh=0xf84f63ff Tier-0
Compiling   11 System.Text.ASCIIUtility::NarrowUtf16ToAscii, IL size = 695, hsh=0x80737645 Tier-0 switched to FullOpts
Compiling   12 X::Main, IL size = 46, hsh=0x9ef3c9ae Tier-0
```

Note it seems possible the jit might make two such switches -- a Tier0 request becomes FullOpt and then that becomes MinOpts. If so, then one might be able to be trapped in Tier0 code in very large methods with loops. Will investigate.

**Comment by AndyAyersMS** [comment]
FWIW double switches can happen, most obviously in .cctors with loops, eg:
```
Compiling   67 JIT.HardwareIntrinsics.X86.SimpleBinaryOpTest__AddSingle::.cctor, IL size = 202, hsh=0x7949b34b Tier-0 switched to FullOpts, then to MinOpts
```
Added extra diagnostic text for this case as shown above.

**Comment by sandreenko** [comment]
> FWIW double switches can happen, most obviously in .cctors with loops, eg:
> Compiling   67 JIT.HardwareIntrinsics.X86.SimpleBinaryOpTest__AddSingle::.cctor, IL size = 202, hsh=0x7949b34b Tier-0 switched to FullOpts, then to MinOpts
> 
> Added extra diagnostic text for this case as shown above.

Why does it fail to minopts?

**Comment by AndyAyersMS** [comment]
When jitting, we always compile .cctors with minopts, since they're only ever called once.

https://github.com/dotnet/coreclr/blob/7e518f820a5db8f61ffe0dd653852558f1f238d9/src/jit/compiler.cpp#L2556-L2561

**Pull request merged**
