### PR TITLE
Disable tests for a clean official build

### PR DESCRIPTION
**Pull request by jashook**

### CODE REVIEW

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by hoyosjs** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by hoyosjs** [comment]
test Windows_NT arm Cross Checked Innerloop Build and Test

**Comment by RussKeldorph** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test

**Pull request merged**
