### PR TITLE
Changed 22 UNSTABLE tests to EXPECTED_PASS

### PR DESCRIPTION
**Pull request by briansull**
This reduces the number in the UNSTABLE catagory to 24 tests

### CODE REVIEW

**Comment by briansull** [comment]
This is after Rahul's checkin to implement GC hijacking stubs for ARM64

@rahku FYI
@jashook  FYI
@kyulee1  FYI

**Comment by briansull** [comment]
@dotnet-bot test Windows_NT arm64

**Comment by rahku** [comment]
Thanks....missed changing tests.lst

**Comment by jashook** [comment]
LGTM

**Pull request merged**
