### PR TITLE
FieldDescSlot generic handle support

### PR DESCRIPTION
**Pull request by fadimounir**
Adding Support for FieldDescSlot generic dictionary entries for R2R generic code.

This enables generic code with ldtoken instructions for fields on generic types to be compiled into R2R.

This change makes newer versions of the runtime compatible with older version R2R images,
but not vice-versa. Therefore, the major version is increased to 2 with this change.

This change adds more encodings to a R2R image without changing the format of any previously encoded entity, and is backwards compatible.

### CODE REVIEW

**Comment by fadimounir** [comment]
@dotnet-bot test Windows_NT Checked pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu Checked pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Windows_NT Checked pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu Checked pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build please

**Comment by fadimounir** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by fadimounir** [comment]
@JohnChen0 @jkotas PTAL

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu Checked pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Windows_NT Checked pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu Checked pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by fadimounir** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build please

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu Checked pri1r2r please

**Comment by fadimounir** [comment]
@jkotas PTAL :)

**Comment by fadimounir** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test  please

**Comment by jkotas** [comment]
LGTM. Thanks!

**Comment by fadimounir** [comment]
@dotnet-bot test Ubuntu Checked pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Windows_NT Checked pri1r2r please

**Comment by fadimounir** [comment]
@dotnet-bot test Windows_NT Checked pri1r2r please

**Pull request merged**
