### PR TITLE
Fix build failure on Ubuntu14.04 when libnuma-dev is installed

### PR DESCRIPTION
**Pull request by helloguo**
fix https://github.com/dotnet/coreclr/issues/12725

### CODE REVIEW

**Comment by helloguo** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test

**Comment by helloguo** [comment]
@janvorli @jkotas PTAL

**Comment by 4creators** [comment]
Has anyone tested if this PR resolves the same issue on WSL Ubuntu 16.04.2 on Windows 10 Creators Update?

**Comment by helloguo** [comment]
@4creators I did not have a chance to test it on WSL Ubuntu 16.04.2 on Windows 10 Creators Update yet.

**Comment by helloguo** [comment]
@adityamandaleeka Can you take a look at this change?

**Pull request merged**
