### PR TITLE
Revert "Allow building arm64 using VS2017 tools"

### PR DESCRIPTION
**Pull request by jashook**
Reverts dotnet/coreclr#14712

### CODE REVIEW

**Comment by jashook** [comment]
This will unblock Pipeline builds until the toolset dir dependency is removed.

**Comment by karajas** [comment]
@DrewScoggins Any idea why perf is failing?

**Comment by BruceForstall** [comment]
@DrewScoggins Looks like the perf jobs can't handle PRs with quotes in the title.

**Comment by karajas** [comment]
I'll go ahead and merge in https://github.com/dotnet/coreclr/pull/14755 and see if that just works. If it doesn't I can revisit this fix.

**Comment by karajas** [comment]
The other change seemed to have gotten us further but still seeing product issues.

**Comment by DrewScoggins** [comment]
Hmm, @jorive I thought that we had fixed this issue?  Was that just in CoreFX?

**Comment by jashook** [comment]
Revert seems unnecessary now.

**Pull request closed without merging**
