### PR TITLE
Tag Pri1+ tests as such in the ARM32/64 LST files.

### PR DESCRIPTION
**Pull request by pgavlin**
Just what it says on the tin.

### CODE REVIEW

**Comment by pgavlin** [comment]
@jashook @BruceForstall @RussKeldorph @dotnet/jit-contrib PTAL

**Comment by pgavlin** [comment]
@dotnet-bot test Tizen armel Cross Debug Build

**Comment by BruceForstall** [comment]
Looks like you added Pri1 to all the tests now marked Pri1.

There's a problem, though, since in the arm64 file many are marked both Pri0 and Pri1 (I would expect either one or the other, and the invoker to use smarty's "/inc+ Pri0 /inc+ Pri1" to get both).

Weirdly, the ARM file has exactly one test marked Pri0.

I presume merging arm/arm64 lst files is out-of-scope for this change.

**Comment by pgavlin** [comment]
> There's a problem, though, since in the arm64 file many are marked both Pri0 and Pri1 (I would expect either one or the other, and the invoker to use smarty's "/inc+ Pri0 /inc+ Pri1" to get both).

Interesting. This should be easy enough to fix.

**Comment by pgavlin** [comment]
> I presume merging arm/arm64 lst files is out-of-scope for this change.

Correct.

**Comment by BruceForstall** [comment]
@pgavlin Your commit is titled "Remove "Pri0" tags." Did you remove all Pri0 tags, or just the Pri0 tags that also had Pri1 tags?

What is the expected smarty command line if you want to run (1) Pri0 tests, (2) Pri1 tests, (3) both? Presumably we still use `EXPECTED_PASS` and/or `EXPECTED_FAIL`?

**Comment by pgavlin** [comment]
> Your commit is titled "Remove "Pri0" tags." Did you remove all Pri0 tags, or just the Pri0 tags that also had Pri1 tags?

I removed all Pri0 tags.

> What is the expected smarty command line if you want to run (1) Pri0 tests, (2) Pri1 tests, (3) both? Presumably we still use `EXPECTED_PASS` and/or `EXPECTED_FAIL`?

1. `smarty /inc EXPECTED_PASS /exc EXPECTED_FAIL;PRI1`
2. `smarty /inc PRI1 /exc EXPECTED_FAIL`
3. `smarty /inc EXPECTED_PASS /exc EXPECTED_FAIL`

**Comment by BruceForstall** [comment]
Hmmmm... wouldn't it make more sense to be:

1. smarty /inc PRI0 /exc EXPECTED_FAIL
2. smarty /inc PRI1 /exc EXPECTED_FAIL
3. smarty /inc PRI0;PRI1 /exc EXPECTED_FAIL

?

I guess I don't see the point of `EXPECTED_PASS` the way it is currently defined.

**Comment by pgavlin** [comment]
> I guess I don't see the point of `EXPECTED_PASS` the way it is currently defined.

I'll let @jashook comment on that. FWIW, I don't think that it's worth changing these invocations given the current thinking re: running tests using Xunit. This change is intended solely to unblock the use of test priorities on ARM/ARM64.

**Comment by BruceForstall** [comment]
ok.

Did you check if anyone is using the existing Pri0 tags?

**Comment by pgavlin** [comment]
> Did you check if anyone is using the existing Pri0 tags?

Yes. Nothing in this repo uses them.

**Comment by jashook** [comment]
```
I guess I don't see the point of EXPECTED_PASS the way it is currently defined.
I'll let @jashook comment on that. FWIW, I don't think that it's worth changing these invocations given the current thinking re: running tests using Xunit. This change is intended solely to unblock the use of test priorities on ARM/ARM64.
```

I have no preference whether it is used or not. Just note that changing EXPECTED_PASS will require a ci change.

**Comment by pgavlin** [comment]
The x64 perd job did complete successfully: https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_perflab_Windows_NT_x64_full_opt_ryujit_smoketest_prtest/311/

Not sure why it still appears yellow.

**Pull request merged**
