### PR TITLE
Update the linux get started instructions

### LINKED ISSUE #1941: ICU 52 requirement not documented
I've installed DNX SDK and some parts of coreCLR were not working for me. It was because my distro (Arch Linux) have ICU 55, and coreCLR from this site is build for ICU 52 ( so I had to rebuild coreCLR, or put ICU 52 in linker path ).

There should be mention about ICU 52 on DNX SDK instruction for Linux.

### PR DESCRIPTION
**Pull request by blackdwarf**
Add current dependencies. Remove Mono dependency. 

Fixes #1941 
/cc @richlander @ellismg

### CODE REVIEW

**Comment by ellismg** [comment]
This is not the complete set of dependencies (the general building document has a more complete set) but nothing takes into account dependencies from CoreFX.

I sort of wonder if we should just delete all these DNX focused docs and instead point at documentation on the aspnet site so we have an authorative place for them.

**Comment by blackdwarf** [comment]
Actually, that is a very, **very** good point. We should, since it will actually help keep everything in sync. @richlander thoughts?

**Comment by Marqin** [comment]
You should also mentions version. For example now coreCLR is compiled for libicu 52, so won't work on newer systems with 55 without recompilation of some parts.

**Comment by blackdwarf** [comment]
Closing this PR as there is another with a new set of documents that use the CLI tools instead of DNX.

**Pull request closed without merging**
