### PR TITLE
Fixed failing test 'InnerFinally'

### PR DESCRIPTION
**Pull request by wtgodbe**

### CODE REVIEW

**Comment by akoeplinger** [comment]
I think a better fix would be to make sure `Env.NewLine` returns the correct value. Right now it always returns `\r\n` because `IsWindows` is hardcoded to true in [Utilities.cs#L79](https://github.com/dotnet/coreclr/blob/926fc21d22a63b0efa98556cba9f6397027e574b/tests/src/Common/CoreCLRTestLibrary/Utilities.cs#L79).

Note: I've been working on adding the CoreCLR testcases to Mono and the Env helper causes trouble in a lot of tests because of things like this :)

**Comment by wtgodbe** [comment]
From what I understand, it's better practice to use 'Environment', but I could be wrong. I will poke around a bit.

**Comment by akoeplinger** [comment]
IMHO, I think we can just get rid of the Env helper class, it doesn't add much value. I've done it in the Mono fork already, if the MS folks agree I can send a PR :)

**Comment by wtgodbe** [comment]
Sounds good to me.

**Comment by akoeplinger** [comment]
@wtgodbe yes, I'll open a PR for removing the Env helper then.

**Comment by wtgodbe** [comment]
Great, thanks!

**Pull request merged**
