### PR TITLE
Remove native build warnings

### PR DESCRIPTION
**Pull request by joperezr**
Updating buildtools to latest package to remove the warnings that the native build throws today.

fixes: #4208 

CC: @BruceForstall @AndyAyersMS

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
There are now a lot of warnings about missing `runtimes` section in the various project.jsons.
```
00:42:33.053 D:\j\workspace\x64_release_w---0575cb46\tests\xunitwrapper.targets(9,5): warning : Your project.json doesn't have a runtimes section. You should add '"runtimes": { "dotnet": { } }' to your project.json and then re-run NuGet restore. [D:\j\workspace\x64_release_w---0575cb46\tests\src\TestWrappers_x64_Release\Regressions\Regressions.XUnitWrapper.csproj]
```
Seems like something we should fix along with this toolset update.

**Comment by joperezr** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by joperezr** [comment]
@AndyAyersMS 113a5f3 should address that. I'll take a look once CIs are done to check if warnings still exist.

FYI: @mellinoe

**Comment by joperezr** [comment]
@AndyAyersMS All the new added warnings are gone now. Is there any feedback before I merge this?

**Comment by AndyAyersMS** [comment]
LGTM. Thanks...

**Comment by joperezr** [comment]
Merging since I already got a green build, and last commit is only a squash.

**Pull request merged**
