### PR TITLE
Fixing https://github.com/aspnet/JitBench/issues/80

### PR DESCRIPTION
**Pull request by jorive**
- Issue was fixed with this: https://github.com/aspnet/JitBench/pull/82

### CODE REVIEW

**Comment by jorive** [comment]
@dotnet/rap-team PTAL

**Comment by jorive** [comment]
@dotnet-bot help

**Comment by jorive** [comment]
@dotnet-bot test Windows_NT x64 perf scenarios
@dotnet-bot test Windows_NT x86 perf scenarios

**Comment by DrewScoggins** [comment]
If those runs pass LGTM

**Comment by jorive** [comment]
@AndyAyersMS  yes, JitBench broke due to this bug.

**Comment by adiaaida** [comment]
So it looks like the perf-off run worked, but then we had some access denied issues when trying to run perf-on.

**Comment by jorive** [comment]
Automation is failing to delete sandbox :(

**Comment by jorive** [comment]
@dotnet-bot test Windows_NT x64 perf scenarios
@dotnet-bot test Windows_NT x86 perf scenarios

**Comment by jorive** [comment]
@dotnet-bot test Windows_NT x64 perf scenarios
@dotnet-bot test Windows_NT x86 perf scenarios

**Pull request merged**
