### PR TITLE
Set locked to true in project.lock.json

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Otherwise it's not really locked.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
Should help with #2575. @dagood PTAL.

**Comment by dagood** [comment]
`tests\src\GC\Performance\Tests\project.lock.json` needs the same fix, but other than that looks good to me.

**Comment by AndyAyersMS** [comment]
Thanks, updated.

I also see `"locked": false` in the test wrappers, but this doesn't seem to cause me trouble.

EG: `test\src\TestWrappers_x64_Release\Exceptions\project.lock.json:  "locked": false`

**Comment by dagood** [comment]
Ah, I didn't see that one in my file search--I'm assuming it's generated? Since locked lockfiles are deprecated, though, maybe it's not important to figure that out and fix it. (Especially if it doesn't cause restore issues!)

**Comment by AndyAyersMS** [comment]
Yes, it's created when you run tests.

If lockfiles are deprecated, any idea when CoreCLR gets updated?

**Comment by AndyAyersMS** [comment]
@dotnet-bot retest this please

**Comment by dagood** [comment]
I'll be removing the lockfiles before (or at the same time as) adding the option to restore with nuget.exe where it's available. I'm not sure yet exactly how that's going to happen, but I'm thinking/hoping within a week.

**Pull request merged**
