### PR TITLE
Use movsdsse2 for HW intrinsic SSE2_ConvertToDouble

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Instead of movsd, which is for GPRs. Fixes one of the stress failures
seen in #17027.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@4creators @fiigii @tannergooding PTAL
cc @dotnet/jit-contrib 

Feel free to add whatever other legs are appropriate, I'm not familiar with most of them.

@dotnet-bot test Windows_NT x64 Checked jitstressregs4
@dotnet-bot test Windows_NT x86 Checked jitstressregs4

**Comment by 4creators** [comment]
test Windows_NT x64 Checked gcstress0x3
test Windows_NT x64 Checked gcstress0xc
test Windows_NT x64 Checked gcstress0xc_jitstress1
test Windows_NT x64 Checked gcstress0xc_jitstress2
test Windows_NT x64 Checked gcstress0xc_minopts_heapverify1
test Windows_NT x64 Checked gcstress0xc_zapdisable
test Windows_NT x64 Checked gcstress0xc_zapdisable_heapverify1
test Windows_NT x64 Checked gcstress0xc_zapdisable_jitstress2

test Windows_NT x86 Checked gcstress0x3
test Windows_NT x86 Checked gcstress0xc
test Windows_NT x86 Checked gcstress0xc_jitstress1
test Windows_NT x86 Checked gcstress0xc_jitstress2
test Windows_NT x86 Checked gcstress0xc_minopts_heapverify1
test Windows_NT x86 Checked gcstress0xc_zapdisable
test Windows_NT x86 Checked gcstress0xc_zapdisable_heapverify1
test Windows_NT x86 Checked gcstress0xc_zapdisable_jitstress2

test Ubuntu x64 Checked gcstress0x3
test Ubuntu x64 Checked gcstress0xc
test Ubuntu x64 Checked gcstress0xc_jitstress1
test Ubuntu x64 Checked gcstress0xc_jitstress2
test Ubuntu x64 Checked gcstress0xc_minopts_heapverify1
test Ubuntu x64 Checked gcstress0xc_zapdisable
test Ubuntu x64 Checked gcstress0xc_zapdisable_heapverify1
test Ubuntu x64 Checked gcstress0xc_zapdisable_jitstress2

**Comment by 4creators** [comment]
test Windows_NT x64 Checked jitincompletehwintrinsic
test Windows_NT x64 Checked jitx86hwintrinsicnoavx2
test Windows_NT x64 Checked jitx86hwintrinsicnosimd

test Windows_NT x86 Checked jitincompletehwintrinsic
test Windows_NT x86 Checked jitx86hwintrinsicnoavx2
test Windows_NT x86 Checked jitx86hwintrinsicnosimd

test Ubuntu x64 Checked jitincompletehwintrinsic
test Ubuntu x64 Checked jitx86hwintrinsicnoavx2
test Ubuntu x64 Checked jitx86hwintrinsicnosimd

**Comment by AndyAyersMS** [comment]
Wow, that is a lot of testing. Not sure we really needed all those GC stress legs, as this was an encoding assert that reproed deterministically, but I suppose it's harmless to run them again.

**Comment by fiigii** [comment]
@AndyAyersMS Thanks for the work!

@4creators we do not need to run the hwintrinsic tests, SSE2 is already fully implemented.

**Comment by 4creators** [comment]
> we do not need to run the hwintrinsic tests, SSE2 is already fully implemented.

This are stress jobs with different configurations as default one which runs with AVX/AVX2 encoding.

**Comment by AndyAyersMS** [comment]
It occurs to me that we have no really effective way with dealing with this volume of tests when the baseline quality (especially for stress) is unclear and failures are either nondeterministic or known in baselines.

So I'm tempted to just ignore all the GC stress tests here as there is little reason to believe this change will impact them one way or another.

So far there are 3 non-GC stress failures
* [tizen](https://ci.dot.net/job/dotnet_coreclr/job/master/job/armel_cross_checked_tizen_innerloop_prtest/2033/) not impacted, perennially broken.
* [x64 incomplete ISA](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_jitincompletehwintrinsic_prtest/228/) two failures. Will try to repro these locally.
* [x86 incomplete ISA](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_jitx86hwintrinsicnoavx2_prtest/209/) timed out, looks like maybe we should retry.

@dotnet-bot retest test Windows_NT x86 Checked jitincompletehwintrinsic

**Comment by AndyAyersMS** [comment]
I can't repro the two x64 failures,  and I don't see any diffs in the disassembly for `pow_do` or `raytracer` with `complus_enableincompleteisaclass=1`. So I can't explain why these failed.

**Comment by 4creators** [comment]
AFAIR there are some SIMD tests which tend to fail sporadically but I have not seen `pow_do` or `raytracer` failing in this way before.

**Comment by AndyAyersMS** [comment]
Continuing to categorize non-stress failures:
* [armlb](https://ci.dot.net/job/dotnet_coreclr/job/master/job/armlb_cross_checked_windows_nt_innerloop_flow_prtest/495/) is #16961
* [tizen](https://ci.dot.net/job/dotnet_coreclr/job/master/job/armel_cross_checked_tizen_innerloop_prtest/2033/) not impacted, perennially broken.
* [x64 incomplete ISA](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_jitincompletehwintrinsic_prtest/228/) two failures that I haven't been able to repro locally. Tempted to retry.
* [x86 incomplete ISA](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_jitx86hwintrinsicnoavx2_prtest/209/) has timed out twice now.

I sampled some of the failing GC stress legs and there weren't any new failures, just things that had also failed in a prior run. Since the CI system tracks failures on an order-run basis that's not definitive but it suggests (as we would suspect) that this change hasn't impacted GC stress itself one way or another.

So I will keep looking at the x64 cases locally and am going to give in and retry too.

@dotnet-bot retest test Windows_NT x64 Checked jitincompletehwintrinsic

**Comment by fiigii** [comment]
The [failures ](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_gcstress0xc_jitstress2_prtest/13/)of AVX/AVX2 `ConvertToVector*` look like managed code bugs (related to https://github.com/dotnet/coreclr/pull/16957 ?) because they even failed with disabled AVX/AVX2 intrinsics.

@tannergooding could you help?

**Comment by fiigii** [comment]
Detected a new bug from https://github.com/dotnet/coreclr/pull/17030/commits/c488262bad100464c720c6c53a60e24f27d13cc7, will be fixed by https://github.com/dotnet/coreclr/pull/17180

**Comment by AndyAyersMS** [comment]
x64 passed on rerun. I think despite the large number of GC stress failures this is ready to merge. Those will have to be sorted separately.

**Pull request merged**
