### PR TITLE
Fix value numbering of ReadyToRunGenericStaticBase

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Fixes dotnet/corert#2080.

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
Thanks for the pointers, @jkotas @JosephTremoulet!

Cc @sandreenko

**Comment by JosephTremoulet** [comment]
LGTM

**Comment by sandreenko** [comment]
Did you test the case with A<Object>.getStaticField + A<String>.getStaticField with this change?

**Comment by MichalStrehovsky** [comment]
@sandreenko Can you clarify the scenario a little?

If you're asking whether I tested that getting the static base is properly hoisted when relevant, the answer is yes:

```nasm
00007FF6F490F0D1 E8 F2 08 1B 00       call        __GenericLookupFromDict_repro_WithCctor_1__System___Canon_GCStaticBase_repro_WithCctor_1__T_System___Canon (07FF6F4ABF9C8h)  
00007FF6F490F0D6 48 8B 50 08          mov         rdx,qword ptr [rax+8]  
00007FF6F490F0DA 4C 8B 40 10          mov         r8,qword ptr [rax+10h]  
```

The above is a load of two reference-typed fields.

**Comment by sandreenko** [comment]
`internal class Program {
    class A<U, V> {
        public static int foo() {
            return B<U>.v + B<V>.v;
        }
    }
    class B<U> {
        public static int v;
    }
    private static int Main(string[] args) {
        B<String>.v = 1;
        B<Object>.v = 10;
        Console.WriteLine(A<String, Object>.foo());
        return 100;
    }
}`
Does it print 11?

**Comment by MichalStrehovsky** [comment]
Yup, 11. It's loading both static bases and doesn't try to combine them.

**Pull request merged**
