### PR TITLE
Add missing value to arm tryrun.cmake

### PR DESCRIPTION
**Pull request by benpye**
A new check has been added to the PAL configure script requiring an addition to the ARM tryrun.cmake file. This value was captured on a Jetson TK1 running Ubuntu 14.04.

@kangaroo This case needs adding to arm64 too but I have no hardware.

cc: @jkotas

### CODE REVIEW

**Comment by kangaroo** [comment]
LGTM -- I'm OOO but I'll check on hardware tomorrow or tuesday.

**Comment by benpye** [comment]
Sorry, do not merge this yet, #2195 added new configure options that need to be added also.

**Comment by manu-silicon** [comment]
@benpye Do you mind adding :
```
SET( HAVE_CLOCK_THREAD_CPUTIME_EXITCODE
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( HAVE_SCHED_GETCPU_EXITCODE
     0
     CACHE STRING "Result from TRY_RUN" FORCE)
```
for arm and arm64?

Thanks

**Comment by benpye** [comment]
@manu-silicon I'll update my PR, thanks!

**Comment by benpye** [comment]
@kangaroo PTAL

**Comment by benpye** [comment]
The OS X failures shouldn't be as a result of this change.

**Pull request merged**
