### PR TITLE
Implement long to float cast for x86

### PR DESCRIPTION
**Pull request by mikedn**
Contributes to #4169

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib PTAL

**Comment by mikedn** [comment]
Some tests failed because a uint->double cast is converted to a uint->long cast and a long->double cast. The newly created long->double cast wasn't converted into a helper call.

**Comment by mikedn** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build

**Comment by mikedn** [comment]
Initially I was pretty sure that using a helper call would be significantly slower than the JIT32 approach. But it turns out that using `FILD` as JIT32 does is anything but efficient due to a store forwarding stall:
```
       890424       mov      dword ptr [esp], eax
       89542404     mov      dword ptr [esp+04H], edx
       ...
       DF2C24       fild     qword ptr [esp] ; loading 8 bytes after two 4 byte stores
```
Given that the helper call implementation is also trivial the choice is obvious, let's use the helper.

It is possible to make the `FILD` based implementation perform well by doing a single 8 byte store before it. For example:
```
        vmovd       xmm0, dword ptr [ebp + 8]
        vpinsrd     xmm0, xmm0, dword ptr [ebp + 12], 1
        vmovq       qword ptr[ebp + 8], xmm0

        fild        qword ptr[ebp + 8]
```
I've made a test in VC++ using inline assembly and the above implementation is 3x faster (on a Haswell i5) than using `FILD` alone. We could try to use this but anyway all `FILD` based implementations seem a bit problematic because the operand has to be in memory. I tried to use a temp in codegen but it seem that we need to modify LSRA to make it reserve a temp that codegen can use.

Also, there's a SSE/AVX only implementation that doesn't need a temp and produces the result in a SSE/AVX register. Unfortunately it's quite large, almost 40 bytes.

**Comment by pgavlin** [comment]
LGTM

**Comment by adiaaida** [comment]
LGTM

**Pull request merged**
