### PR TITLE
Perf tweaks/cleanup to AppDomain.Setup

### PR DESCRIPTION
**Pull request by stephentoub**
- AppDomain.Setup currently has the same code repeated four times for handling four different properties.  Condense those down to a single block.
- Then make a few tweaks to avoid some unnecessary allocation: reuse the StringBuilder and char[] allocations across all four properties, and size the StringBuilder correctly rather than having it grow repeatedly.

cc: @jkotas, @ellismg

### CODE REVIEW

**Comment by stephentoub** [comment]
I've added another commit.  One of the biggest remaining allocations in my setup during startup was coming from String.Split; while Split allocates a string[] to store the strings being returned, it also allocates an int[] with a length equal to the input string.  For my runs, that causes an ~94K int[] allocation.

For a "hello, world" console app, profiling it before this PR (just showing objects with at least 10o0 bytes of allocations):
image
and after:
image

**Comment by ellismg** [comment]
@dotnet-bot test OSX x64 Release Build and Test please (checkout failed)

**Comment by jkotas** [comment]
LGTM. Thanks!

**Comment by stephentoub** [comment]
Test OSX x64 Release Build and Test please ("Could not checkout")

**Comment by ayende** [comment]
How did you get those results (what tool gave you them, I mean).

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by stephentoub** [comment]
> How did you get those results (what tool gave you them, I mean).

The memory profiler in Visual Studio:
Debug -> Start Diagnostics Tools Without Debugging... -> Performance Wizard -> .NET Memory Allocation

**Comment by ayende** [comment]
Thanks

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ellismg** [comment]
LGTM as well.  Thanks Steve!

**Pull request merged**
