### PR TITLE
RyuJit Version Update

### PR DESCRIPTION
**Pull request by kyulee1**

### CODE REVIEW

**Comment by jkotas** [comment]
Do you also need to update the .dll names in the nuspecs? There is no ryujit.dll anymore after #4449.

cc @pgavlin

**Comment by kyulee1** [comment]
Okay. Will update it for now. Eventually it would be automated by @pgavlin.

**Comment by jkotas** [comment]
Why we would want to have automation for changing the name of JIT .dll? (I understand automation for updating versions, but names?)

**Comment by kyulee1** [comment]
I meant updating version and push from automation. I will send CR for name change shortly.

**Pull request merged**
