### PR TITLE
Inliner: gather summary stats and dump to Jit CSV log

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Collect per-method summary stats about inlining: number of calls,
number of candidates, etc.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@pkukol PTAL
cc @dotnet\jit-contrib

**Comment by AndyAyersMS** [comment]
[Another instance](http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x86_ryujit_checked_windows_nt_prtest/2698/) of `GC\Scenarios\DoublinkList\dlstack` failing (re #6574).

Planning on just ignoring this.

**Comment by AndyAyersMS** [comment]
@dotnet/jit-contrib Peter may not be geared up for @ mentions yet, can somebody else take a look?

**Comment by JosephTremoulet** [comment]
LGTM

**Comment by CarolEidt** [comment]
LGTM

**Pull request merged**
