### PR TITLE
 Explode generic Intel hardware intrinsic on all the supported types

### PR DESCRIPTION
**Pull request by fiigii**
close https://github.com/dotnet/coreclr/issues/20057

This PR removes all the generic Intel hardware **intrinsic** and explodes them on all the supported types. The generic helpers (e.g., `GetLowerHalf<T>`) are not handled in this PR, we will move them into `Vector128/256<T>` classes.

### CODE REVIEW

**Comment by jkotas** [comment]
There is a bunch of new warnings like `shared\System\Runtime\Intrinsics\X86\Avx2.cs(742,40): warning CS0108: 'Avx2.ExtractVector128(Vector256<sbyte>, byte)' hides inherited member 'Avx.ExtractVector128(Vector256<sbyte>, byte)'. Use the new keyword if hiding was intended. [D:\j\workspace\x64_checked_w---43686a05\src\System.Private.CoreLib\System.Private.CoreLib.csproj]`. Could you please fix those?

**Comment by fiigii** [comment]
@jkotas Thank you so much! Will fix it tomorrow.

**Comment by fiigii** [comment]
@CarolEidt @tannergooding @eerhardt

**Comment by fiigii** [comment]
@dotnet-bot test Windows_NT x64 Checked CoreFX Tests 
@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test

**Comment by CarolEidt** [comment]
@fiigii - you removed a bunch of related tests. Will they be replaced once this flows through corefx?

**Comment by fiigii** [comment]
Yes, I will rewrite/re-enable them later.

**Comment by CarolEidt** [comment]
@fiigii - Great, thanks!

**Pull request merged**
