### PR TITLE
Fix build breaks on VS2015 RTM

### PR DESCRIPTION
**Pull request by jkotas**
Most of the changes are about mismatches between printf formatting strings and argument types.

### CODE REVIEW

**Comment by jkotas** [comment]
@adityamandaleeka Could you please take a look?

**Comment by akoeplinger** [comment]
Fixes https://github.com/dotnet/coreclr/issues/1294 I guess?

**Comment by jkotas** [comment]
Yes, thanks for pointing it out. I have update the commit message.

**Comment by adityamandaleeka** [comment]
LGTM

**Pull request merged**
