### PR TITLE
Fix buildsystem for linux cross-architecture component build

### PR DESCRIPTION
**Pull request by hseok-oh**
related issue: #8495 
Fix build system for cross-architecture component build on linux (such as x86-host/arm-target build)

default: disabled cross-architecture component build

### CODE REVIEW

**Comment by hseok-oh** [comment]
push commit
1. Refactoring `build.sh`
2. Remove `crosscomp` argument in `gen-buildsys-clang.sh`: use environment variable 
2. Add new argument in `build.sh`: crosscomponent (default: disabled)
3. Fix bug: check host-target pair for cross-architecture component build in CMakeLists.txt
4. Fix typo

**Comment by janvorli** [comment]
Except for the function name I have asked to rename, LGTM

**Comment by janvorli** [comment]
Thank you for the refactoring, it looks much better now!

**Comment by hseok-oh** [comment]
@janvorli I've rename the function. Thank you.

**Pull request merged**
