### PR TITLE
Import more JIT tests.

### PR DESCRIPTION
**Pull request by pgavlin**
This imports the remainder of the tests under JIT\Methodical that are
able to target CoreCLR.

This also contains build fixes for tests under
JIT\Directed\coverage\oldtests that were mangled during a previous import.

### CODE REVIEW

**Comment by pgavlin** [comment]
@AndyAyersMS @CarolEidt PTAL.

**Comment by AndyAyersMS** [comment]
LGTM

**Comment by jasonwilliams200OK** [comment]
:+1: all tests passed on Windows.

**Comment by jasonwilliams200OK** [comment]
Does this also fix: #1036, #1037 and #1038?

**Comment by josteink** [comment]
Tests run on FreeBSD, with 4 failures, but that's currently where the tests are, so this does not represent a degredation.

````
Finished running PAL tests.

The following test(s) failed:
threading/SleepEx/test2/paltest_sleepex_test2. Exit code: 1
threading/WaitForSingleObject/WFSOExMutexTest/paltest_waitforsingleobject_wfsoexmutextest. Exit code: 1
threading/WaitForSingleObject/WFSOExSemaphoreTest/paltest_waitforsingleobject_wfsoexsemaphoretest. Exit code: 1
threading/WaitForSingleObject/WFSOExThreadTest/paltest_waitforsingleobject_wfsoexthreadtest. Exit code: 1

PAL Test Results:
  Passed: 817
  Failed: 4
````

**Comment by jasonwilliams200OK** [comment]
@josteink, isn't it same amount of tests as described here: https://github.com/dotnet/coreclr/issues/1010#issuecomment-104266582. I mean with this PR, the total would probably be higher?

**Comment by josteink** [comment]
Sorry. My bad. I ran the PAL tests only.

Currently I don't know how to get the full coreclr trst-suite running on FreeBSD or if it even can be done. If someone can show me how to get the JIT tests running, I'll give it a try.

**Comment by pgavlin** [comment]
@jasonwilliams200OK this fixes #1038.

**Pull request merged**
