### PR TITLE
[RyuJIT/ARM32] Fix helper kill mask and call target consuming

### PR DESCRIPTION
**Pull request by mskvortsov**
Fix for a couple of issues described in #9556.
(Re-)enables rel/chk altjit compilation of S.P.CoreLib.dll methods for the `JIT/CodeGenBringUpTests`.

(This is a part of #8496.)

### CODE REVIEW

**Comment by mskvortsov** [comment]
@BruceForstall Please take a look.

**Comment by BruceForstall** [comment]
I think you should instead change the target.h code to read:

```
#ifdef LEGACY_BACKEND
  #define RBM_CALLEE_TRASH_NOGC   (RBM_R2|RBM_R3|RBM_LR)
#else
  #define RBM_CALLEE_TRASH_NOGC   RBM_CALLEE_TRASH
#endif
```

And then in getKillSetForNode():
```
        case GT_STOREIND:
            if (compiler->codeGen->gcInfo.gcIsWriteBarrierAsgNode(tree))
            {
                killMask = RBM_CALLEE_TRASH_NOGC;
#if !NOGC_WRITE_BARRIERS && (defined(_TARGET_ARM_) || defined(_TARGET_AMD64_))
                killMask |= (RBM_ARG_0 | RBM_ARG_1);
#endif // !NOGC_WRITE_BARRIERS && (defined(_TARGET_ARM_) || defined(_TARGET_AMD64_))
            }
```

delete the `#if` condition. Note that `NOGC_WRITE_BARRIERS` is zero for both ARM and AMD64 in all cases. AMD64 already has:
```
  #define RBM_CALLEE_TRASH_NOGC   RBM_CALLEE_TRASH
```

Thus, that `#if` would no longer do anything. Thus, the code should simply read:
```
        case GT_STOREIND:
            if (compiler->codeGen->gcInfo.gcIsWriteBarrierAsgNode(tree))
            {
                killMask = RBM_CALLEE_TRASH_NOGC;
            }
```

(fyi, the legacy back end picks a register very late, in code generation, and R4 happens to be available -- its register allocator just makes sure at least one is free. In RyuJIT, we have to choose in advance which registers to use. We can use R12 because it is callee-trash and not an argument register.)

**Comment by BruceForstall** [comment]
The codegenarm.cpp change looks fine.

**Comment by BruceForstall** [comment]
@mskvortsov This looks good to me. Can you squash the commits?

**Comment by BruceForstall** [comment]
@dotnet-bot test OSX x64 Checked Build and Test
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Pull request merged**
