### PR TITLE
[release/3.0] Fix nullability annotations for static

### PR DESCRIPTION
**Pull request by stephentoub**
Port #25913 to release/3.0 branch.

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @danmosemsft, @safern, @cston

**Comment by danmosemsft** [comment]
Ok.

**Comment by danmosemsft** [comment]
Are we also picking up a new compiler? We should ship 3.0 compiled with the latest 3.0 compiler, presumably.

**Comment by stephentoub** [comment]
> Are we also picking up a new compiler?

Don't know.  @agocke? @safern?

**Comment by safern** [comment]
> Don't know. @agocke? @safern?

The only thing that I would think we need to update the compiler for in 3.0 would be in order to get static nullability tracking working in this branch for our code, I don't think it should affect the final customer as the nullable metadata should be emitted, @cston can correct me if wrong.

**Comment by cston** [comment]
> I don't think it should affect the final customer as the nullable metadata should be emitted

Correct, the changes to the compiler to warn for uninitialized non-nullable static fields should not affect the emitted metadata.

**Pull request merged**
