### PR TITLE
Port of fix for issue  #5467: [R2R] InvalidCastException in timer tests. (#5478)

### PR DESCRIPTION
**Pull request by fadimounir**
Port of commit #2507807811cf6a33a946c2382e6d56961e4bff74 from master to release/1.0.0

### CODE REVIEW

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by sergiy-k** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by sergiy-k** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by sergiy-k** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test please

**Comment by sergiy-k** [comment]
All tests have passed on OSX but the job failed at the end due to an infrastructure issue.

**Pull request merged**
