### PR TITLE
Adding perf tests for some of the new math functions that are implemented as FCALLs

### PR DESCRIPTION
**Pull request by tannergooding**
This fixes up an issue with the existing perf tests, in that they were off by one and many produced NaN rather than the actual result.

This also adds perf tests to cover all the new Math/MathF functions that were added recently and that are implemented as FCALLs in the runtime (the non FCALL functions that were added should be covered as perf tests in CoreFX).

### CODE REVIEW

**Comment by tannergooding** [comment]
CC. @eerhardt 

Also CC. @AndyAyersMS who was reviewed my previous PRs for this

**Comment by tannergooding** [comment]
Also CC. @ViktorHofer, who is the other System.Numerics area owner.

**Comment by tannergooding** [comment]
Are those already running/testable from CI and if not, do we have an ETA of when they will be?

I'm happy to put them in the appropriate place, but I would also like to get some cross-plat numbers and validate the FMA improvement once I make it intrinsic.

**Comment by brianrob** [comment]
Yes, agreed.  These should go into the performance repo.  @adamsitnik can you point @tannergooding to instructions on how to do this?

**Comment by brianrob** [comment]
cc: @billwert

**Comment by brianrob** [comment]
I suspect that the CI jobs will be implemented early next year.  You can run the repo directly against the outputs of a CoreCLR build today.  The main blocker for the new jobs right now is the on-boarding to Arcade.

**Comment by adamsitnik** [comment]
> @adamsitnik can you point @tannergooding to instructions on how to do this?

sure! I even have docs for that!

@tannergooding  after reading https://github.com/dotnet/performance/blob/master/docs/porting-to-benchmarkdotnet.md you should be able to port those benchmarks and add them to https://github.com/dotnet/performance/tree/master/src/benchmarks/micro/coreclr/Math/Functions

please let me know if something is not clear or outdated

**Comment by tannergooding** [comment]
Closing in favor of https://github.com/dotnet/performance/pull/166

**Pull request closed without merging**
