### PR TITLE
[ARM] gcinfodecoder: handle case when GetRegisterSlot returns NULL

### PR DESCRIPTION
**Pull request by kbaladurin**
It improves robustness in cases when GetRegisterSlot returns NULL. I think this change could be useful for  the release branch.

### CODE REVIEW

**Comment by kbaladurin** [comment]
@alpencolt @BredPet

**Comment by alpencolt** [comment]
Related to https://github.com/dotnet/coreclr/issues/19273
cc @jkotas

**Comment by BredPet** [comment]
LGTM

**Comment by jkotas** [comment]
Do you know about an actual bug in current master or release/2.1 branch that this is fixing? As discussed in the issue, this should not be needed with the statically linked libunwind that is used by default.

> this change could be useful for the release branch.

This can be candidate for the release branch only if it is fixing a real bug.

**Comment by BredPet** [comment]
Original root cause was fixed in another [PR](https://github.com/dotnet/coreclr/pull/19332).
This PR improves stability as itself for ARM as for x64. We think this is really needed for ARM too.

**Comment by alpencolt** [comment]
@jkotas we've found at least 2 bugs in 2.1 for ARM. PRs which fix them:
https://github.com/dotnet/coreclr/pull/18129
https://github.com/dotnet/coreclr/pull/19332
I think would be good to see both in 2.1 branch. Current PR can be replaced with https://github.com/dotnet/coreclr/pull/19332.

**Comment by jkotas** [comment]
> I think would be good to see both in 2.1 branch. 

Agree. @chsienki Do you plan to port your ARM debugging fixes (#18129) to release/2.1 ?

**Comment by alpencolt** [comment]
It looks https://github.com/dotnet/coreclr/pull/19332 doesn't fix all possible case. So the current PR helps with stability, but  from the other side it may hide other crashes or postpone them.
It may be useful on release branches. @jkotas how do you think?

**Comment by jkotas** [comment]
>  So the current PR helps with stability, but from the other side it may hide other crashes or postpone them.

Right, this is exactly what I am worried about - that this change will just delay the crash a bit, and make the actual root cause much harder to debug and fix.

**Comment by chsienki** [comment]
@jkotas We had talked about it, but without an impacting customer figured it wouldn't meet the bar.

@tommcdon Now there are people hitting issues with ARM on 2.1, should we port the fixes over?

**Comment by BruceForstall** [comment]
@jkotas @alpencolt @kbaladurin Is this PR still active? It looks from the discussion that @jkotas didn't want to take it.

**Comment by tommcdon** [comment]
@BruceForstall we have already ported the following 5 ARM debugger fixes to .NET Core 2.1 servicing on PR #19652:
- #17617
- #17879
- #17990
- #18129 (mentioned above)
- #18247

Adding @hoyosjs to investigate porting #19332 to 2.1 servicing as it looks like we should port that one too.

**Comment by kbaladurin** [comment]
@BruceForstall yes, this patch isn't necessary.

**Pull request closed without merging**
