### PR TITLE
Move to 3.0 SDK

### PR DESCRIPTION
**Pull request by elinor-fung**

### CODE REVIEW

**Comment by jashook** [comment]
This seems like it no longer needs the WIP

**Comment by elinor-fung** [comment]
cc @RussKeldorph

**Comment by elinor-fung** [comment]
cc @janvorli

**Comment by ericstj** [comment]
This version of the SDK had a bug in process that causes MSBuild to crash on Ubuntu 18.04.  You probably want to update to a newer SDK version.  See https://github.com/dotnet/corefx/pull/38185.  /cc @RussKeldorph

**Pull request merged**
