### PR TITLE
Port of dotnet/runtime#1059 to 3.1 branch

### PR DESCRIPTION
**Pull request by CarolEidt**
This is the fix for #27924. This is a GC hole bug that was found externally, #27590.
The cause is that the JIT was using the target type of the subtract when it needed
to make a copy of the source, but it needs to use the source type.

## Customer Impact
Corruption of state that is non-deterministic and hard to track down.

## Regression?
Not a recent regression, but exposed by Unsafe.ByteOffset.

## Testing
The fix has been verified in the runtime repo.

## Risk
Low: The fix is straightfoward and only impacts 3 lines of code.

## Code Reviewer
@jaschook and @jkotas

### CODE REVIEW

**Comment by wtgodbe** [comment]
Is this for 3.1.3? CC @jeffschwMSFT

**Comment by MeiChin-Tsai** [comment]
It has to be 3.1.3. Miss the 3.1.2 window already.

**Comment by MeiChin-Tsai** [comment]
Please add code reviewer.

**Comment by CarolEidt** [comment]
> Please add code reviewer.

Added above

**Review by jkotas — APPROVED** [review]

**Comment by jeffschwMSFT** [comment]
Approved for .NET Runtime

**Comment by jeffschwMSFT** [comment]
Approved for 3.1.3 (March) - need to wait for the branch to open before merging

**Pull request merged**
