### PR TITLE
Fix incorrect exception parameter name in GC

### PR DESCRIPTION
**Pull request by hughbe**
Found in https://github.com/dotnet/corefx/pull/6510
/cc @mellinoe

### CODE REVIEW

**Comment by swgillespie** [comment]
LGTM - I suppose could use `nameof` instead of hardcoding the parameter name but I doubt there's much value in that, I doubt that parameter name will ever change.

Also, there are some GC tests coming to CoreCLR too: https://github.com/dotnet/coreclr/pull/3394 . They are mostly orthogonal to the ones in CoreFX (with CoreFX focusing on parameter validation, etc. like you cleaned up) but feel free to check them out if you're interested. `System.GC` lies at the boundary of CoreCLR and CoreFX so there might be some test duplication between here and there, but I (personally) think that's fine.

Thanks!

**Comment by stephentoub** [comment]
LGTM

**Comment by hughbe** [comment]
Ah right, I wasn't aware nameof was brought to coreclr yet

**Comment by jkotas** [comment]
@hughbe Would you mind submitting the same fix to corert as well? Thanks!

**Pull request merged**
