### PR TITLE
Use INS_mvsdsse2 for SSE2_ConvertToDouble

### LINKED ISSUE #17261: ConvertToDouble_r fails with jitstressregs4
Test is JIT\HardwareIntrinsics\X86\Sse2\ConvertToDouble_r\ConvertToDouble_r.exe
It gets the following assert:
```
Assert failure(PID 80348 [0x000139dc], Thread: 80668 [0x13b1c]): Assertion failed '(unsigned)ins < _countof(insCodesRM)' in 'IntelHardwareIntrinsicTest.Program:Main(ref):int' (IL size 243)

    File: c:\git2\coreclr\src\jit\emitxarch.cpp Line: 1249
    Image: C:\git2\coreclr\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
```
I believe it's yet another case of using `INS_movsd` when it should be `INS_movsdsse2`.

### PR DESCRIPTION
**Pull request by CarolEidt**
Fix #17261

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT x86 Checked jitstressregs4

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib @tannergooding @4creators @fiigii PTAL

**Comment by mikedn** [comment]
Maybe we should rename `INS_movsd` to `INS_movs_dword` to avoid such confusions...

**Comment by 4creators** [comment]
> Maybe we should rename INS_movsd to INS_movs_dword to avoid such confusions...

This type of confusions in theory should not happen but there are three "problems" in `instrxarch.h` that could be addressed: (i) duplicate names of instructions from Intel manual which could disambiguated, (ii) ordering of instructions by (i) functionality followed by (ii) alphabetical.

**Comment by AndyAyersMS** [comment]
Isn't this the same fix as in #17110?

**Comment by fiigii** [comment]
> Isn't this the same fix as in #17110?

I think so...

**Comment by CarolEidt** [comment]
Ah, I missed that.

**Pull request closed without merging**
