### PR TITLE
Adding Serviceable attribute to mscorlib

### PR DESCRIPTION
**Pull request by joperezr**
cc: @weshaggard @gkhanna79 

fixes: #4336

### CODE REVIEW

**Comment by weshaggard** [comment]
LGTM cc @ericstj

**Comment by ericstj** [comment]
LGTM

**Comment by gkhanna79** [comment]
Is there a way to confirm that, post this change, the nuget package will be marked servicable?

**Comment by joperezr** [comment]
mm I'm not sure, I did validate that the mscorlib binary has the attribute now, but I'm not sure of how to see if the package is marked

**Pull request merged**
