### PR TITLE
Adjust expected file size if ZapDisable is true

### PR DESCRIPTION
**Pull request by nategraf**
Adjust expected size of the events file to a lower value is COMPlus_ZapDisable is set to reflect the lack of rundown events

Closes: 16238
Related: 16220

### CODE REVIEW

**Comment by nategraf** [comment]
@dotnet-bot test Windows_NT x86 Checked zapdisable
@dotnet-bot test Windows_NT x64 Checked zapdisable

**Comment by nategraf** [comment]
@dotnet-bot test Windows_NT x86 Checked zapdisable
@dotnet-bot test Windows_NT x64 Checked zapdisable

**Comment by nategraf** [comment]
The ZapDisable tests passed. This should ready to go

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_zapdisable_prtest/17/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_zapdisable_prtest/6/

**Comment by AndyAyersMS** [comment]
Can you also make sure this passes with
```
COMPlus_ZapDisable=1
COMPlus_ReadyToRun=0
```
which is how we run the tests in CI.

**Comment by nategraf** [comment]
@AndyAyersMS The CI runs `Windows_NT {Arch} Checked zapdisable` will do that, no?

**Comment by AndyAyersMS** [comment]
Indeed it does exactly that. Your changes LGTM.

**Pull request merged**
