### PR TITLE
Reduce CreateContinuationWrapper allocations

### PR DESCRIPTION
**Pull request by benaadams**
Removes CreateContinuationWrapper closures (and related allocation) for 
* `AsyncMethodBuilderCore.OutputAsyncCausalityEvents`
*  `TaskAwaiter.OutputWaitEtwEvents`

Reduces `YieldAwaitable.OutputCorrelationEtwEvent` closure to one int field.

Don't think its necessarily a hot, hot path; but is used for etw (and debugging; hopefully doesn't break it...)

/cc @vancem @jkotas @stephentoub

### CODE REVIEW

**Comment by benaadams** [comment]
Easier to compare ignoring whitespace [`https://github.com/dotnet/coreclr/pull/8864/files?w=1`](https://github.com/dotnet/coreclr/pull/8864/files?w=1) due to indention changes.

**Comment by benaadams** [comment]
@dotnet-bot retest Linux ARM Emulator Cross Debug Build
@dotnet-bot retest Linux ARM Emulator Cross Release Build

**Comment by stephentoub** [comment]
> hopefully doesn't break it

How have you verified it doesn't?

**Comment by benaadams** [comment]
No, I'm having issues using current coreclr builds directly - runtime version conflicts, missing methods, type conflicts etc

I'm assuming its stuff being moved around for 2.0 and my tooling not quite recent enough

**Comment by benaadams** [comment]
And the docs on [how to use the build](https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/UsingYourBuild.md) are for project.json not msbuild but give runtime version conflicts when I use with project.json; so I assume there is an interming sdk version between the two I should be using but am not.

**Comment by stephentoub** [comment]
> And the docs on how to use the build

I typically just get my tests set up the way I want them, with a locally x-copied runtime, and then just overwrite the runtime binaries with ones I've built myself:
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md#testing-with-private-coreclr-bits

**Comment by benaadams** [comment]
Haha; ok I've been doing this; and debugging with attach and a console readline; then periodically have to restart as something more major changes in coreclr. 

Was wondering if there was a more efficient method; I tried dogfooding https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md which I was hoping would give me a good starting point without a full source rebuild; but the daily builds don't seem to be too daily (issues raised) but I have learnt how to do standalone with the new csproj so I do have an efficient process once it gets going; until the next mismatch.

Its also a little error prone, so I end up doing "just to be sure" rebuilds frequently also

**Comment by danmosemsft** [comment]
@benaadams unblocked on this one?

**Comment by danmosemsft** [comment]
@benaadams as this is not changed for >month I'll close it. Feel free to reopen or start a new one if you want to continue.

**Pull request closed without merging**
