### PR TITLE
Update windows-test-instructions.md

### PR DESCRIPTION
**Pull request by kingces95**
Got a build error: `Error: Parameter not recognized: crossgen.`

image

### CODE REVIEW

**Comment by kingces95** [comment]
Hm. Pretty sure I didn't break `Tizen`...

**Comment by BruceForstall** [comment]
This doesn't look correct; build-test.cmd looks like it takes "crossgen" as an argument but not "-crossgen".

**Comment by kingces95** [comment]
@BruceForstall I guess I should have opened this as an issue. I got an error when I just used `crossgen` (see screen shot) and things seemed to work when I used `-crossgen` so I thought it was just a typo.

**Comment by kingces95** [comment]
Eh, Google will find this if someone needs it.

**Pull request closed without merging**
