### PR TITLE
change cmake settings to fix build issue on Linux CentOS

### LINKED ISSUE #299: building fails on CentOS cause by SET (CMAKE_C_FLAGS_INIT "-Wall -std=c11")
When building coreclr on CentOS, get the following failures.
```
-- Check size of siginfo_t
-- Check size of siginfo_t - failed
-- Check size of ucontext_t
-- Check size of ucontext_t - failed
...
[  0%] Building CXX object src/palrt/CMakeFiles/palrt.dir/bstr.cpp.o
In file included from /data/git/coreclr/src/pal/src/arch/i386/context.cpp:25:
/data/git/coreclr/src/pal/src/include/pal/context.h:40:2: error: 
Native context type is not known on this platform!
```
When remove the line `SET (CMAKE_C_FLAGS_INIT  "-Wall -std=c11")` in the file `src/pal/tools/clang-compiler-override.txt`, the failures are gone.

### PR DESCRIPTION
**Pull request by cnblogs-dudu**
Fixes #299 
`-std=c11` lead to `check_type_size(siginfo_t SIGINFO_T)` and `check_type_size(ucontext_t UCONTEXT_T)` fail on Linux CentOS. Only the pal tests need `-std=c11`.

### CODE REVIEW

**Comment by janvorli** [comment]
@cnblogs-dudu I don't like dropping  the c11 standard option there. The sigaction man page says that siginfo_t requires `_POSIX_C_SOURCE >= 199309L` 
I would add definition of the macro to the root CMakeLists.txt (using add_definitions(-D_POSIX_C_SOURCE=199309L)) under if(CLR_CMAKE_PLATFORM_LINUX) that you'd add probably right before the first function definition there.

I am not sure about the ucontext_t issue, there is no information about it being conditionally available in the manpage, but you should be able to figure it out if you look into the ucontext.h and the headers it includes.

**Comment by kangaroo** [comment]
@cnblogs-dudu Can you upload the CMakeError.log so we can figure out exactly whats wrong?

**Comment by cnblogs-dudu** [comment]
@kangaroo CMakeError.log: https://gist.github.com/cnblogs-dudu/6365bf9b89b538bacf70

**Comment by cnblogs-dudu** [comment]
@janvorli Add add_definitions(-D_POSIX_C_SOURCE=199309L) in the root CMakeLists.txt and checking size of siginfo_t likewise fails. I digg into the /usr/include/signal.h.

**Comment by kangaroo** [comment]
Your error is:

```
In file included from /usr/include/ucontext.h:26:
/usr/include/sys/ucontext.h:137:5: error: unknown type name 'stack_t'
    stack_t uc_stack;
```

This was fixed for me on ubuntu with the  set(CMAKE_REQUIRED_DEFINITIONS "-D_DEFAULT_SOURCE")  in configure.cmake.  Can you check your features.h to figure out why stack_t isn't being found?

**Comment by cnblogs-dudu** [comment]
@kangaroo There is not stack_t in /usr/include/features.h in CentOS and Ubuntu.

**Comment by kangaroo** [comment]
It's not directly in features.h, you will need to find where it is, and what its guarded by.

**Comment by cnblogs-dudu** [comment]
@kangaroo Find it. It's in /usr/include/asm/signal.h on CentOS and in /usr/include/x86_64-linux-gnu/asm/signal.h on Ubuntu.

**Comment by kangaroo** [comment]
@cnblogs-dudu Right, but you need to figure out what #ifdef is preventing it from getting included.

**Comment by cnblogs-dudu** [comment]
@kangaroo changing `set(CMAKE_REQUIRED_DEFINITIONS "-D_DEFAULT_SOURCE")` to `set(CMAKE_REQUIRED_DEFINITIONS "-D_BSD_SOURCE")` fixes `unknown type name 'stack_t` and checking size of ucontext_t gets done.
```
-- Check size of ucontext_t
-- Check size of ucontext_t - done
```
But the following error occurred.
```
/data/git/coreclr/src/pal/src/include/pal/locale.h:70:2: 
error: Insufficient platform support for text encodings
```

**Comment by cnblogs-dudu** [comment]
@janvorli Adding `-D_POSIX_C_SOURCE=199309L` into CMAKE_C_FLAGS_INIT in `src/pal/tools/clang-compiler-override.txt` fixes siginfo_t issue.
```
SET (CMAKE_C_FLAGS_INIT "-Wall -std=c11 -D_POSIX_C_SOURCE=199309L")
```
```
-- Check size of siginfo_t
-- Check size of siginfo_t - done
```

**Comment by cnblogs-dudu** [comment]
@kangaroo Addint `-D_XOPEN_SOURCE=500` fixes `error: Insufficient platform support for text encodings`.

**Comment by cnblogs-dudu** [comment]
Replacing `-std=c11` with `-std=gnu11` can keep the c11 standard option and fix the build issue on CentOS. 
The new commit has been built successfully on CentOS and Ubuntu and OS X.

**Comment by janvorli** [comment]
I would still prefer using the defines if it is feasible. The -std=gnu11 means c11 with gnu extensions. Since we are using clang and not gcc, I'd prefer stayng away from gcc extensions and staying on pure c standard. 
@jkotas, @sergiy-k, what do you think?

**Comment by kangaroo** [comment]
I'm fetching a CentOS vagrant image before heading to the airport, hopefully I'll be able to get the toolchain and such installed and then I'll fix this on my flight.

**Comment by kangaroo** [comment]
The CentOS features.h guards the stack_t declaration with:

```
#if defined __USE_BSD || defined __USE_XOPEN_EXTENDED || defined __USE_XOPEN2K8
# define __need_size_t
# include <stddef.h>

/* If INTERRUPT is nonzero, make signal SIG interrupt system calls
   (causing them to fail with EINTR); if INTERRUPT is zero, make system
   calls be restarted after signal SIG.  */
extern int siginterrupt (int __sig, int __interrupt) __THROW;

# include <bits/sigstack.h>
# if defined __USE_XOPEN || defined __USE_XOPEN2K8
/* This will define `ucontext_t' and `mcontext_t'.  */
#  include <sys/ucontext.h>
# endif
```

I think we should switch to -D_XOPEN_SOURCE=500

**Comment by kangaroo** [comment]
@cnblogs-dudu Can you try this fork https://github.com/kangaroo/coreclr/tree/centos-fix

Thanks!

**Comment by cnblogs-dudu** [comment]
@kangaroo Tried it and got the following error:
```
/data/git/centos-fix/coreclr/src/pal/src/file/file.cpp:1828:33: 
error: no member named 'st_ctimensec' in 'stat'
 ST_CTIME_NSEC(&stat_data) );
```

**Comment by kangaroo** [comment]
@cnblogs-dudu Pushed up an additional commit.  Can you try again please?

**Comment by cnblogs-dudu** [comment]
@kangaroo Same error.

**Comment by kangaroo** [comment]
Alright, I'll need to check on CentOS directly.  Where did you get clang 3.5 for CentOS from?  afaict EPEL only has 3.4?

**Comment by cnblogs-dudu** [comment]
@kangaroo Download source from http://llvm.org/releases/download.html#3.5.0 and build/install on CentOS.

**Pull request closed without merging**
