### PR TITLE
Add glossary to documentation

### PR DESCRIPTION
**Pull request by poizan42**

### CODE REVIEW

**Comment by jkotas** [comment]
@richlander Could you please take a look?

**Comment by richlander** [comment]
Thanks @poizan42. Appreciated. 

Can you PR in a short intro to the documentation, explaining what it is? It is good for readers that happen on the document via search, and in fact, it helps with the document showing up on search.

**Comment by richlander** [comment]
@poizan42. Friendly ping to respond to my feedback.

**Comment by poizan42** [comment]
Yes I can, but I wasn't sure what to write in the introduction.

**Comment by richlander** [comment]
Ok, @poizan42. I'll accept it and write the intro. That's fine. Probably more appropriate, anyway.

**Pull request merged**
