### PR TITLE
Remove incorrect UNIX_AMD64_ABI define

### LINKED ISSUE #17654: [Arm64/Linux] #16962 Broke arm64 crosscomponent build
@CarolEidt 
cc/ @weshaggard

### PR DESCRIPTION
**Pull request by CarolEidt**
Fix #17654

### CODE REVIEW

**Comment by CarolEidt** [comment]
I visually examined the generated code for a test that I know passes structs in regs, and it still produces the correct code for both the native and the linuxnonjit case.
I'm running linuxnonjit diffs now.
@sdmaclea - it also appears that this is passing an arm64 leg that was failing.
@janvorli @weshaggard

**Comment by weshaggard** [comment]
Looks reasonable to me. I don't really have a lot of context but we should try to get this merged ASAP to get the builds unblocked.

**Comment by sdmaclea** [comment]
LGTM thanks @CarolEidt

**Comment by weshaggard** [comment]
Enough CI legs have passed so I'm merging to unblock builds.

**Comment by CarolEidt** [comment]
> Enough CI legs have passed so I'm merging to unblock builds.

Thanks @weshaggard - I was waiting for the arm64 build to complete, but you're right, it's probably best to have merged it.

**Pull request merged**
