### PR TITLE
Rewrite CalleeSavedRegisters for x86

### PR DESCRIPTION
**Pull request by parjong**
This commit revises CalleeSavedRegisters for x86 using
ENUM_CALLEE_SAVED_REGISTERS as in x64.

### CODE REVIEW

**Comment by janvorli** [comment]
@mmitche the Ubuntu and OSX legs have failed with
`21:40:06 D:\j\workspace\checked_windo---f6dc6fe4\Tools\Packaging.targets(1061,5): error MSB4018: System.IO.IOException: The process cannot access the file 'D:\j\workspace\checked_windo---f6dc6fe4\bin\Product\Windows_NT.x64.Checked\mscordaccore_amd64_amd64_4.6.24910.00.dll' because it is being used by another process. [D:\j\workspace\checked_windo---f6dc6fe4\src\.nuget\Microsoft.NETCore.Runtime.CoreCLR\Microsoft.NETCore.Runtime.CoreCLR.pkgproj]`
See https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_windows_nt_bld_prtest/2400/consoleFull#167644425379494335-f7bd-47d0-8771-8661e00c2db2 for the whole exception stack trace.

**Comment by mmitche** [comment]
@dotnet/dnceng https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_windows_nt_bld_prtest/2400/consoleFull#167644425379494335-f7bd-47d0-8771-8661e00c2db2

Looks internal to the build  Any ideas?

**Comment by dagood** [comment]
Judging by a local build-packages, it looks like that error could happen if multiple packages contain that DAC DLL. I think the package report tried to read the file twice at the same time when analyzing both packages in parallel. I don't know why multiple packages would have the DAC in it in this case, though.

I recently upgraded the buildtools package used by CoreCLR, and it was last updated two months ago, so some other behavior change might be to blame.

**Comment by janvorli** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by janvorli** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build please

**Comment by janvorli** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by janvorli** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by janvorli** [comment]
@parjong can you please resolve the conflicts in this change?

**Comment by parjong** [comment]
@janvorli I resolved the conflicts. Please take a look.

**Pull request merged**
