### PR TITLE
Expose String.Concat overloaded API with __arglist

### PR DESCRIPTION
**Pull request by tarekgh**

### CODE REVIEW

**Comment by tarekgh** [comment]
CC @jkotas @weshaggard @danmosemsft

**Comment by jkotas** [comment]
We have been holding back on the native vararg APIs. Ideally, they should not be part of the netstandard2.0. If they have to be part of netstandard2.0 for one reason or another, we want to throw PNSE from them.

**Comment by tarekgh** [comment]
@jkotas I didn't know that. I'll follow up with what we need to do here.

**Comment by tarekgh** [comment]
reopen it just to run the CI on it and I'll follow up meanwhile.

**Comment by weshaggard** [comment]
Yes my plan is to try and keep them out of netstandard 2.0.

**Pull request closed without merging**
