### PR TITLE
Correctly sequence fgMorphModToSubMulDiv

### PR DESCRIPTION
**Pull request by CarolEidt**
This method was creating a temp, but the final result was a GT_SUB with
a use of the temp as its op1, and it was not setting GTF_REVERSE_OPS.
This led to a liveness assert in LSRA.

### CODE REVIEW

**Comment by mikedn** [comment]
Oops, I take it this was indirectly caused by my recent change that moved magic division to lowering. But how come this worked for ARM64? Lack of tests?

**Comment by CarolEidt** [comment]
@mikedn - Yes, the specific scenario needed to reproduce this wasn't covered by existing tests. But at least it was reproducible with a very small test case :-)

**Comment by mikedn** [comment]
Hmm, I need to take a closer look at this. It seems to me that even with this fix something doesn't work right, if we do `arg % 0` we end up with `arg`, the division by 0 is nowhere to be seen and no exception is thrown. There's actually a bug in my code, it should not call `fgMorphModToSubMulDiv` if the divisor is 0. But then the ARM64 specific morph code appears to be calling `fgMorphModToSubMulDiv` unconditionally so presumably it should handle division by 0 correctly.

**Comment by mikedn** [comment]
I opened a separate issue for the problem I'm seeing, it appears to be completely unrelated to the bug you are fixing here - #8648.

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL. This fixes bug 359736

**Comment by sivarv** [comment]
:shipit:

**Comment by briansull** [comment]
LGTM

**Pull request merged**
