### PR TITLE
IDeserializationCallback cleanup

### PR DESCRIPTION
**Pull request by morganbr**
Throws PlatformNotSupportedException from IDeserializationCallback and IObjectReference implementations on types that are no longer serializable.

Progress toward dotnet/corefx#19119

### CODE REVIEW

**Comment by morganbr** [comment]
CC @dotnet/corert-contrib @krwq

**Comment by morganbr** [comment]
@dotnet-bot test Tizen armel Cross Release Build

**Comment by danmosemsft** [comment]
@morganbr do you need further review?

**Comment by morganbr** [comment]
@danmosemsft I was waiting on a previous change to finish mirroring. Merging now.

**Comment by ViktorHofer** [comment]
@karelz this went into 2.0.0 not into 2.1.0

**Comment by karelz** [comment]
Was there 2.0 PR? Looking at the [commit](https://github.com/dotnet/coreclr/commit/68570e183b2dc53682079d8ab4dac24f893aebfa), it was not integrated into rel/2.0.0.

**Pull request merged**
