### PR TITLE
Port type moves to UWP 6.2 branch

### PR DESCRIPTION
**Pull request by morganbr**
Ports the Hashtable and ConcurrentQueue type moves to CoreLib from master in order to make CoreLib match the .NET Native CoreLib. This will allow the UWP 6.2 CoreFX to build against both CoreLibs.

### CODE REVIEW

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by zamont** [comment]
https://github.com/dotnet/dotnet-ci/pull/1025 was just merged which should enable CI tests for this branch. Not sure how long it will take to propagate.

**Comment by zamont** [comment]
@dotnet-bot test this please

**Comment by zamont** [comment]
@dotnet-bot test this please

**Pull request merged**
