### PR TITLE
Improve performance of string.IndexOf for large strings on 64-bit

### PR DESCRIPTION
**Pull request by jamesqo**
## Summary

This pull request improves the performance of the char-based `string.IndexOf` by about 30% for large strings.

## Description

Right now, the current implementation of `IndexOf` checks each char in the string individually for `value`. While its performance isn't too bad since it's loop unrolled and (I'm asumming) the branch predictor helps out for larger strings, it could be improved.

On 64-bit, I've changed the function to use an approach where instead it reads in one word at a time from the string, and uses a trick to determine if any of the individual 4 chars in it are likely to contain value. If it does, it checks each individual char for value; otherwise, it continues the loop.

### How it works

1. We first align the pointer on an 8-byte boundary by calculating the number of bytes left until the next aligned address, aka `alignment`. We then divide this by 2, since we're counting by chars and not bytes (and `char*` obtained from strings will always have an even address, so the number of bytes to the next aligned address should be even, too).

  - Before aligning, we calculate whether `count` is enough for aligning the pointer + at least one iteration of the loop. If not, we jump straight to the fallback loop where we check one char at a time.

  - We then align the pointer, checking each char at a time for value until we do; since we know that `pAlign` is less than `pEnd` due to the earlier calculation, we don't need to check `pCh < pEnd`.

2. We then go into the main loop, where we process 12 chars at a time. What we do here is create a mask out of value repeated 4x into a word; for example if someone passes in `\u1234` then we want to create `0x1234123412341234`.

  - We then read a word at a time from the target string and xor it with this mask, which is basically equivalent to xoring every individual char in the word with `0x1234`. If there is a `0x1234` in the string, it will be zeroed out.

  - Then, the same trick as #6125 is used to check if a zero is present in the xored string, by adding 0x7fff to each of the chars and checking if any of the high bits are unset. If one of them is, we check each individual char in the word for value. If we find it, we return the index.

    - It's possible for this algorithm to misfire if there's a char >= 0x8000 in the string (besides value | 0x8000, which will yield 0x8000 when xored); in that case, we simply skip the word we just processed and continue the loop if there's enough space left.

3. When the number of chars left goes below the number of chars we can process in the loop (12 in this case), we leave the loop and fallback to processing individual chars.

It's also helpful to read the comments, as I've explained everything there as well.

### Notes

  - If the char we need to find is >= 0x8000, this new algorithm won't work very nicely; assuming a string of ASCII chars, xoring with value would yield something with its high bit set, and adding 0x7fff (unless it's value & ~0x8000) would yield something with its high bit *not* set, and then we would be jumping to `MaybeReturn` for basically *every iteration* of the loop. This is more of a concern than if the string itself contains chars >= 0x8000, since that would only cause a hiccup for one iteration of the loop. (Also, people might use it to check if a string contains invalid chars, e.g. `IndexOf('\uffff') != -1`.) So I fell back to the old algorithm if the char has its high bit set.

  - I had to keep the old implementation for x86 as well; using `uint` instead of `ulong` and even unrolling turned out to have much slower results than the old implementation on 32-bit.

  - I initially loop-unrolled by 8 chars (`Chunk = 8`) due to code size concerns (each check does a xor/add/or/cmp/jne and some other stuff), but unrolling more aggressively to 12 chars at-a-time seemed to yield better performance results (by about 1/16 for larger strings), so I went with that.

    - There appears to be two unnecessary `mov r11, 0x7FFF7FFF7FFF7FFF` in the generated assembly (see below) which are taking up quite a bit of code space inside the loop (probably hurting performance). I don't know if there's a way to tell the JIT to remove them, or I should just wait for the JIT to become better and eliminate these.

  - I also saved on writes to `count` by pre-adding it to `pCh` and comparing `pCh` to that per-iteration of the loop, rather than checking how large `count` was. This saves 1 write per iteration of the loop, which adds an additional 1/15 speedup for larger strings. (I also applied this for the fallback loop.)

### Performance results

Performance results are in [this Gist](https://gist.github.com/jamesqo/df6ab15c3e23d6c3e2bbd68c8f9ce278), including the asm/test source code and results.

  - There is a negligible slowdown for strings of lengths 3/7.

  - There are significant slowdowns for lengths 8-16, especially with length 14 (where the old loop runs thrice and then falls back, and the new loop runs once). However, I'm assuming this is OK since larger strings are more likely to be the bottleneck in an app (otherwise we should just replace all of the code in `String` with naive loops that check one char at a time, since that performs better for smaller strings, right?)

  - The slowdown gets smaller by length 32- it's around 8%.

  - By the 64th position, the new loop is starting to beat the old one by about 7%.

  - **At the 128th and above positions, the new loop is running in about 65-75% the time of the old one.**

  - When 0x8000 is passed in, where we fall back to the old implementation, the new results are still slightly faster; this is presumably due to cfd49d7 so we only make one write per iteration of the loop.

  - When the string itself has lots of 0x8000s, the new loop is of course much slower than the old one (since we have to do constant jumping around and end up with a lot of misfires).

Everything passes the CoreFX test suite; more tests are coming soon to cover the codepaths introduced in this PR. (will post here once that's merged)

Please let me know if there's anyway the performance could be improved. I did some fine tuning for the assembly in some of the commits, but there may still be more opportunities for optimization.

cc: @jkotas @bbowyersmyth @GSPP @stephentoub @omariom

### CODE REVIEW

**Comment by mikedn** [comment]
> There are significant slowdowns for lengths 8-16, especially with length 14 (where the old loop runs thrice and then falls back, and the new loop runs once). However, I'm assuming this is OK since larger strings are more likely to be the bottleneck in an app 

Something's fishy about this assumption. The fact that a string is large or not should be irrelevant in this case. What matters is where in the string the character is found. I could parse a 100 megabytes string containing CSV data using `IndexOf` to find commas and then the 8-16 case could be hit pretty often.

> (otherwise we should just replace all of the code in String with naive loops that check one char at a time, since that performs better for smaller strings, right?)

Who knows? It's difficult to make optimizations if trade-offs need to be made and there are no statics, use cases or any other kind of information to guide those trade-offs.

**Comment by bbowyersmyth** [comment]
That's a great write up @jamesqo 

I'm seeing some different results when re-running the perf tests from https://github.com/dotnet/corert/pull/1339
https://gist.github.com/bbowyersmyth/81cd1b6155d70fb9c6b416ec3660cb89
Running on an Intel i5-6600.

It would be good if long strings don't come at the cost of short searches, as @mikedn mentions.

**Comment by GSPP** [comment]
During my testing I'm hitting an assertion failure for

    Contract.Assert(((uint)pCh + ualign) % 8 == 0);

where `pCh == 0x00000000023e9aac && ualign == 2`. Looks like this line assumes alignment to be in bytes.

I suggest making a new variable for `ualign /= 2` to improve code quality. Right now this variable changes meaning in the middle of the code. It's also a bit easier to debug when the previous value is still around.

Disclaimer: I copied the code out to test it on Desktop CLR. I hope I did not break anything but I don't think I did. This runs on x64 and I deleted the preprocessor directives.

Another question is why this assertion failure was not previously discovered? This should trigger quite frequently.

**Comment by jamesqo** [comment]
@mikedn You're probably right. I'm considering doing some kind of thing where we use the regular (unrolled) loop written by @bbowyersmyth for X characters, and if we don't find it by then (and there's still enough room for 3 iterations of the optimized loop) then the optimization kicks in. That way the overhead of aligning everything/calculating the mask/etc. will be limited to larger strings, and only if we don't find it first using the smaller loop (at which point the overhead will be negligible).

**Comment by jamesqo** [comment]
@bbowyersmyth You need to define the `BIT64` symbol in your perf tests, otherwise the code I've written won't get compiled.

**Comment by jamesqo** [comment]
@GSPP Whoops, my bad. Thanks for pointing that out. It should have been

```cs
Contract.Assert((uint)(pCh + ualign) % 8 == 0);
```

since when adding an int/uint to a pointer Roslyn will automatically multiply it by the sizeof the type (in this case char, so `sizeof(char) == 2`), but I accidentally cast to uint prematurely so that didn't happen.

> Another question is why this assertion failure was not previously discovered? This should trigger quite frequently.

I ran the CoreFX tests with release builds of mscorlib (in which all of the `Contract.Asserts` are compiled out) since I was lazy (I used the same builds for performance testing). Lesson learned, I guess ;)

**Comment by GSPP** [comment]
Maybe  performance increases by saying `x + 1 == 0` instead of `x == ulong.MaxValue`? That gets rid of the large constants. Not sure how efficient such large instructions are on x86. This also might help with the JIT issue you created.

**Comment by jamesqo** [comment]
@GSPP `ulong.MaxValue` is just `-1` when converted to a signed integer, so it can be represented as `FF` (one byte) in assembly. `0x7fff7fff7fff7fff` is the constant that's causing problems, since it can't fit in an int it's taking up 8 bytes.

> Maybe performance increases by saying x + 1 == 0 instead of x == ulong.MaxValue?

I suspect the JIT would probably reduce that to what I've already written anyways (haven't tested, though).

**Comment by jamesqo** [comment]
I'm deciding to close this PR. In the end I'm not too sure this optimization is worth it for a number of reasons:

- It's going to create additional (if slight) overhead for small strings

- It may still create overhead for large strings assuming we do find it soon after the threshold (the one I mentioned in an above comment)

- It's likely to create some subtle bug that goes undetected for a long time due to bad logic in an off-by-one error/misfire (TBH I was surprised there were no issues that came up when running this with the [new CoreFX tests](https://github.com/dotnet/corefx/pull/10266)

- It adds > 200 LOC, most of them comments since the new implementation is so hard to understand

- It only increases the performance (at least for now) for the scenario it's optimized for by about 30%.

The unrolled loop we have in place right now is probably good enough. (This was an interesting PR to code, though.)

**Comment by jkotas** [comment]
Thanks for giving a try anyway!

**Comment by GSPP** [comment]
Maybe this can be salvaged by:

1. Adding a short circuit case for short strings. Another idea is to test the first N chars with the simple loop and only branch to the fast loop if it looks like there will be no early match.
2. Exhaustive testing. This code could be tested through nested loops for all possible [0-N] char strings, search strings and ranges. For each test case we compare the optimizes version with a naive guaranteed correct algorithm. Obviously, we need to restrict the input a bit to make that feasible. But we only need 2 different characters making this actually fairly cheap. For example, a 20 char string would only contain 2^20 possible variations. 1M trials are quick to execute. What about the following testing plan:

We define the strings to be tested as all string with [0, N] character with all character 'A' except for up to two characters 'B'. With N = 30 (two blocks plus padding) there are about 15000 such strings (`comb(30, 2)*30`). There are roughly 30*30/2 possible subranges. That results in `15000*(30*30/2)=6750000` test cases. Should take a few seconds to run.

The testing would even find bugs due to overreaching the string through out of bounds pointer accesses. Since we are also testing subrange if we were to overreach we'd find false matches and the test would fail. For the same reason any bugs caused by alignment issues would be found.

**Comment by jamesqo** [comment]
> Another idea is to test the first N chars with the simple loop

I suggested that in an earlier comment, however that would still add some overhead (i.e. calculating when to stop, we would add an extra branch). Also all of the new code would increase code size/make jumps in assembly farther.

> and only branch to the fast loop if it looks like there will be no early match.

See, that's the problem-- we don't know where in the string the char could be. In certain scenarios, it could appear just as we decide to align and switch to the fallback loop.

> With N = 30

My first estimate for N would be something more like 64.

> That results in `15000(30*30/2)=6750000` test cases. Should take a few seconds to run.

It's not just the test case that's going to cost time; dynamically generating 7M strings at runtime is going to cause a lot of overhead (and trigger GC quite frequently).

> The testing would even find bugs due to overreaching the string through out of bounds pointer accesses.

It would not, however, cover cases where the string contains some weird data (i.e. chars >= 0x8000) and something goes wrong with the bit manipulation (misfires) and we end up returning the wrong index.

**Comment by GSPP** [comment]
The wrong index would be detected because we `assert(old(input) == new(input))`. We only need to cover each branch, so two optimized blocks should be enough. And the optimized path is not triggered by the special character class `chars >= 0x8000`. Generating 7M strings and collecting them also is a matter of seconds. I did similar things in the past, sometimes to great effect. This technique is fanatastic for establishing confidence in something complicated. Normally, I would have suggested Microsoft Pex now called Smart Unit Tests but that technology cannot deal with pointers I think.

Anyway, regardless of what you decide this was great work by you!

**Comment by jamesqo** [comment]
I have actually changed my mind on this after what I learned from #6638; we could simply do 1 unaligned read at the beginning instead of having complex alignment logic, which would make this substantially better in the case where the char in question is near the start of the string, and eliminate the need for any "threshold" where we switch loops. Also, I forgot a common case this PR would benefit is when the char is never actually found in the string (d'oh).

Anyway, I may reopen this PR in the future when I have time to work on it.

**Pull request closed without merging**
