### PR TITLE
Make coreclr buildable on 32bit Windows 10.

### LINKED ISSUE #6308: Build fails on 32bit Windows 10
I ran below command to build the coreclr from source on 32bit Windows 10:
build clean x86

After stuck in "Installing dotnet cli..." for 5 mins, I got following error:
dotnet.exe is not compatible with current running Windows version.

So is build coreclr from source supported on Windows 10?

### PR DESCRIPTION
**Pull request by mazong1123**
Automatically determine the OS architecture(x86 or x64) and download the
correct dev tool.

Fix #6308

### CODE REVIEW

**Comment by mazong1123** [comment]
@jkotas This PR makes coreclr buildable on 32bit Windows 10. Please check.

**Comment by rahku** [comment]
@joperezr can you take a look

**Comment by jkotas** [comment]
@mazong1123  Could you please resolve the merge conflicts?

**Comment by mazong1123** [comment]
@jkotas sure. I'll resolve the conflicts tonight.

**Comment by mazong1123** [comment]
@jkotas Conflicts resolved. Please check :)

**Comment by jkotas** [comment]
LGTM. Thanks!

**Pull request merged**
