### PR TITLE
Fix warnings in interop tests

### LINKED ISSUE #4230: test build warnings: Interop\MarshalAPI\UnsafeAddrOfPinnedArrayElement\UnsafeAddrOfPinnedArrayElement.csproj
```
  3180>UnsafeAddrOfPinnedArrayElement.cs(16,52): warning CS0618: 'Marshal.UnsafeAddrOfPinnedArrayElement(Array, int)' is obsolete: 'UnsafeAddrOfPinnedArrayElement(Array, Int32) may be unavailable in future releases. Instead, use UnsafeAddrOfPinnedArrayElement<T>(T[], Int32). For more info, go to http://go.microsoft.com/fwlink/?LinkID=296517' [D:\gh\coreclr\tests\src\Interop\MarshalAPI\UnsafeAddrOfPinnedArrayElement\UnsafeAddrOfPinnedArrayElement.csproj]
```

### PR DESCRIPTION
**Pull request by yizhang82**
Fix #4230 #4228 #4225 #4224
@tijoytom  FYI

### CODE REVIEW

**Comment by yizhang82** [comment]
@dotnet-bot Test Windows_NT x64 Release Priority 1 Build and Test please

**Comment by yizhang82** [comment]
@dotnet-bot Test Linux ARM Emulator Cross Release Build OSX x64 Checked Build and Test Ubuntu x64 Checked Build and Test please

**Comment by yizhang82** [comment]
@dotnet-bot Test OSX x64 Checked Build and Test please

**Comment by tijoytom** [comment]
LGTM

**Comment by yizhang82** [comment]
@dotnet-bot test Windows_NT x86 ryujit Checked Build and Test please

**Pull request merged**
