### PR TITLE
Enable additional functionality for OS X CI dumps.

### PR DESCRIPTION
**Pull request by adityamandaleeka**
Our CI Macs are being modified so that generated core dumps will no longer be placed in the /cores directory. Instead, they will be put in the test's directory just like they are on Linux.

This change modifies the infrastructure used in CI runs to take advantage of this and unify how we handle dumps on Linux and OS X/macOS. For instance, we should now start uploading dumps from our OS X runs to dumpling, and the retention model for saving them locally will match what we do on Linux.

_I'd like to test this end-to-end before merging, so expect this PR to be open for a while._

cc: @mmitche @bryanar

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Comment by adityamandaleeka** [comment]
@bryanar PTAL. The last commit also makes it so that we'll no longer see "Crash dumps from this run: (from ####):" (and an empty bullet) when there are no dumps.

**Comment by adityamandaleeka** [comment]
cc: @wtgodbe @sergiy-k

**Comment by adityamandaleeka** [comment]
I've also changed the core dump printing code so that it uses LLDB on OS X, and verified that the call stack with the crash is printed in the CI output (this functionality currently doesn't work on CI Linux machines because they don't have a compatible debugger available).

**Comment by adityamandaleeka** [comment]
@dotnet-bot test  Windows_NT x86 ryujit Checked Build and Test

**Comment by wtgodbe** [comment]
Awesome! LGTM

**Comment by adityamandaleeka** [comment]
Checking this in. OS X dumps won't be uploaded to dumpling just yet because of a missing Python module required by the dumpling script, but @schaabs is working on a fix for that which will come in the next version of dumpling.

**Pull request merged**
