### PR TITLE
Add a CI job for openSUSE 42.1

### PR DESCRIPTION
**Pull request by mellinoe**
This changes netci.groovy to consult a list of "boostrap RIDs" to use when building the command line arguments for x-plat CI runs. If there is a mapping in [this table](https://github.com/dotnet/dotnet-ci/blob/master/jobs/generation/Utilities.groovy#L91), then that CI job will override the __PUBLISH_RID enviroment variable in order to publish buildtools for an alternative RID (namely one that exists).

I've added openSUSE 42.1 as the first new distro to try this out on.

@ellismg , @joperezr

### CODE REVIEW

**Comment by mellinoe** [comment]
@dotnet-bot test ci please

**Comment by mellinoe** [comment]
@dotnet-bot test ci please

**Comment by mellinoe** [comment]
@dotnet-bot skip ci please

**Comment by mellinoe** [comment]
@dotnet-bot skip ci please

**Comment by mellinoe** [comment]
@dotnet-bot skip ci please

**Comment by mellinoe** [comment]
@dotnet-bot test ci please

**Comment by mellinoe** [comment]
@dotnet-bot test ci please

**Comment by mellinoe** [comment]
@dotnet-bot test ci please

**Comment by mellinoe** [comment]
@dotnet-bot test ci please

**Comment by joperezr** [comment]
@mellinoe do you know how to run the CI that you just generated? if not let me know

**Comment by mellinoe** [comment]
@joperezr Still getting the jobs correct, I think the latest change should be right. Before the PR I set up a private job definition and tested that, but it would be good to test these too. How can I do that?

**Comment by jasonwilliams200OK** [comment]
Test CI please

^ there used to be something like that before this document: https://github.com/dotnet/coreclr/blob/d3cba55/Documentation/project-docs/ci-trigger-phrases.md, where CI test is not mentioned.

**Comment by jasonwilliams200OK** [comment]
Oh it worked! openSUSE42 testing.. http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/GenPRTest/job/generator_prtest/228/ :blush:

**Pull request merged**
