### PR TITLE
Enable telemetry for official builds

### PR DESCRIPTION
**Pull request by RussKeldorph**

### CODE REVIEW

**Comment by RussKeldorph** [comment]
@chcosta Does this have chance of working, or do I definitely need to call the tasks individually?

**Comment by RussKeldorph** [comment]
@echesakov 

> do we need telemetry enabled for public projects as well?

I'm not sure.  I believe corefx only sends telemetry for official builds currently.  At any rate this is easy to change in the future if we want.

**Comment by echesakovMSFT** [comment]
Closes https://github.com/dotnet/coreclr/issues/21885

**Comment by RussKeldorph** [comment]
ARM* failures are #22657.  Merging this to see what happens.

**Comment by RussKeldorph** [comment]
@echesakovMSFT FYI I believe the "closes XXX" comment has to appear in the description comment at the top for it to work when merging.

**Pull request merged**
