### PR TITLE
Change AMD64 direct call behavior

### PR DESCRIPTION
**Pull request by BruceForstall**
Currently, when AMD64 generates direct calls, it always assumes the
calls are in rel32 range. The VM creates "jump stubs" if that ends
up not being true. Change this behavior such that the JIT generates
large call sequences "mov rax, <8-byte-address>; call rax" whenever
the VM says that rel32 calls are out-of-range. This will only occur
if we've ever failed to fix up a rel32 relocation, but, once that
happens, we will never generate rel32 addresses for the duration
of the process.

This resolves problems of failure to allocate the jump stubs themselves,
which is currently a fatal error in the process.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet-bot help

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT forcerelocs
@dotnet-bot test Windows_NT Checked r2r_jitforcerelocs
@dotnet-bot test Windows_NT x86 Checked forcerelocs
@dotnet-bot test Ubuntu Checked r2r_jitforcerelocs

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT forcerelocs
@dotnet-bot test Windows_NT Checked r2r_jitforcerelocs
@dotnet-bot test Windows_NT x86 Checked forcerelocs
@dotnet-bot test Ubuntu Checked r2r_jitforcerelocs

**Comment by BruceForstall** [comment]
@jashook @RussKeldorph I triggered "Ubuntu x64 Checked ForceRelocs R2R Build & Test" which failed with:
```
java.util.concurrent.ExecutionException: com.cloudbees.plugins.flow.JobNotFoundException: Item dotnet_coreclr/master/x64_checked_windows_nt_r2r_jitforcerelocs_bld_prtest not found (or isn't a job).
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at java_util_concurrent_Future$get.call(Unknown Source)
	at com.cloudbees.plugins.flow.FlowDelegate$_parallel_closure6.doCall(FlowDSL.groovy:456)
	at sun.reflect.GeneratedMethodAccessor2237.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2030)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2015)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2056)
	at org.codehaus.groovy.runtime.dgm$162.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.cloudbees.plugins.flow.FlowDelegate.parallel(FlowDSL.groovy:454)
	at sun.reflect.GeneratedMethodAccessor2243.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1215)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:812)
	at com.cloudbees.plugins.flow.FlowDelegate.invokeMethod(FlowDSL.groovy)
	at hudson.util.spring.ClosureScript.invokeMethod(ClosureScript.java:83)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:75)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
	at Script1.run(Script1.groovy:3)
	at Script1$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at Script1$run.call(Unknown Source)
	at com.cloudbees.plugins.flow.FlowDSL.executeFlowScript(FlowDSL.groovy:84)
	at com.cloudbees.plugins.flow.FlowRun$BuildWithWorkspaceRunnerImpl.doRun(FlowRun.java:180)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1720)
	at com.cloudbees.plugins.flow.FlowRun.run(FlowRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
```

Doesn't this seems to indicate this is not a job that works, or has been tested?

**Comment by BruceForstall** [comment]
@briansull PTAL
cc @dotnet/jit-contrib @jkotas 

Calls in the "large mode" will look like:
```
IN0007: 000026 48B8780092DB0F000000 mov      rax, 0xFDB920078
IN0008: 000030 FFD0                 call     rax
```

**Comment by sivarv** [comment]
Looks good.
Zero asm diffs?

**Comment by briansull** [comment]
This seems too easy.
LGTM

**Comment by BruceForstall** [comment]
failed test:
```
CoreMangLib._cti_system_threading_autoresetevent_AutoResetEventReSet_AutoResetEventReSet_._cti_system_threading_autoresetevent_AutoResetEventReSet_AutoResetEventReSet_cmd
```
trying again:

@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test

**Comment by mikedn** [comment]
Hmm, can't the VM reserve 4GB of VA space upfront to ensure that all JITed code is close enough so this isn't a problem? Or are there cases where more than 4GB of code is generated?!?

**Comment by BruceForstall** [comment]
@mikedn There are cases where that is not enough. Yes, it's true. If you look at the VM CodeHeap implementations, you'll see how it tries very hard to put all JIT, NGEN, and dynamic code generation near each other, and near clr.dll.

**Comment by janvorli** [comment]
@BruceForstall is there a reason why this was not merged? Have we discovered some issue with it?

**Comment by BruceForstall** [comment]
@janvorli still discussing with management about the performance implications and need for this.

**Comment by BruceForstall** [comment]
We don't plan to merge this.

**Pull request closed without merging**
