### PR TITLE
Relax signed/unsigned checks in Array.Copy to match other places

### PR DESCRIPTION
**Pull request by jkotas**
Fixes dotnet/corefx#38535

### CODE REVIEW

**Comment by jkotas** [comment]
CoreFX test update to follow

**Comment by jkotas** [comment]
Test updates in https://github.com/dotnet/corefx/pull/38631

**Comment by EgorBo** [comment]
@jkotas does it also mean I can do: 
```csharp
Array a = new int[] { 1, 2, 3, 4 };
uint b = 10;
a.SetValue(b, 0);
``` 
?

**Comment by jkotas** [comment]
The flexible array casing rules lead to problems. I do not think it is reasonable to expect that everything is going to work well when you cast `int[]` to `uint[]` or cast `string[]` to `object[]`; and start passing the result around. We need to draw the line somewhere.

I think it is important for the lowest level operations like `Array.Copy` to work well. I think it is fine for  higher levels of the stack to not handle these cases (like reflection - where Array.SetValue belong to).

**Comment by EgorBo** [comment]
@jkotas yeah I am porting this fix to mono now and want to know where that line is 🙂 
Also wondering if signed/unsigned conversions should be added here: https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/DefaultBinder.cs#L1228-L1236

**Comment by jkotas** [comment]
I suspect that adding the conversions to the reflection binder would likely break more things that it would fix because of the binder would start picking up different overloads of overloaded methods.

**Comment by EgorBo** [comment]
@jkotas one more question:
```csharp
Array a = new short[] { 1, 2, 3 };
Array b = new char[] { '1', '2', '3' };
a.CopyTo(b, 0);
b.CopyTo(a, 0);
```
this PR doesn't handle `short` <--> `char` is it expected?

**Comment by EgorBo** [comment]
However the comment states `neither CHAR -- with I2/U2`
but 
```csharp
Array a = new ushort[] { 1, 2, 3 };
Array b = new char[] { '1', '2', '3' };

a.CopyTo(b, 0);
b.CopyTo(a, 0);
```
works.

So the comment should be `neither CHAR -- with I2` ?

**Comment by jkotas** [comment]
`Array.Copy` is overload to do per-element reflection-like conversions when the elements cannot be copied one by one. The USHORT->CHAR takes the same path as e.g.:

```
Array a = new short[] { 1, 2, 3 };
Array b = new double[3];

a.CopyTo(b, 0);
```

You are right that we could take the block-copy path for the ushort-> char case if we cared.

**Comment by EgorBo** [comment]
@jkotas what about this test case https://github.com/dotnet/corefx/blob/51a9c8f1dc56d366f5eb435f231052e2614c7a76/src/System.Runtime/tests/System/ArrayTests.cs#L1401
it basically states that you can't do:
```csharp
Array a = new int[1000];
Array b = new ulong[1000];
Array.Copy(a, 0, b, 0, 1);
```
is it correct? 

Full list of problematic cases:
```csharp
int -> ulong
short -> ulong
sbyte -> ulong
sbyte -> uint
sbyte -> ushort
```

**Comment by jkotas** [comment]
It is not a particularly great design, but it is what `Array.Copy` has done since forever. 

I guess that these widening conversions are disallowed because of they may drop sign and change the value, and it is not clear what the right behavior would be in that case: check and throw, sign-extend first, zero-extend first, ... .

I do not think there is anything to fix since these paths are pretty much never used in any real world apps.

**Pull request merged**
