### PR TITLE
Update the package verification to the newest version

### PR DESCRIPTION
**Pull request by agocke**

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet/dnceng These failures look interesting and related to the native bootstrapping. Can you take a look?

**Comment by michellemcdaniel** [comment]
@jonfortescue Is working on native assets stuff

**Comment by jonfortescue** [comment]
The problem is that someone deleted the python 2.7.15 package in netcorenativeassets at some point, I think.

@agocke Can you try changing the python reference in the global.json to 2.7.18 ?

**Comment by agocke** [comment]
I think this is because we retired global.json for native assets entirely. I deleted the section in my other PR and it seems to be passing.

**Comment by ViktorHofer** [comment]
@carlossanlop I don't have any context on this change. @hoyosjs, @jkoritzinsky can you PTAL?

**Comment by jkoritzinsky** [comment]
I have no context here either.

**Comment by hoyosjs** [comment]
This is an edit in eng/common so this is not the right place to do them, but I have no context

**Comment by carlossanlop** [comment]
@agocke what's the status on this? Do we want it merged in the last servicing release for 3.1?

**Comment by carlossanlop** [comment]
3.1 is going out of support in December. We should probably close this @agocke.

**Comment by agocke** [comment]
Yeah, I don't think this is necessary now. We can bring it back if we need to.

**Pull request closed without merging**
