### PR TITLE
fix for issue #16289

### PR DESCRIPTION
**Pull request by davmason**

### CODE REVIEW

**Comment by davmason** [comment]
@sandreenko can you trigger the arm64 run that failed?

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by davmason** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by davmason** [comment]
The OSX job appears broken, it is failing for everyone

**Pull request merged**
