### PR TITLE
Disable FEATURE_HIJACK in NetBSD as unimplemented

### PR DESCRIPTION
**Pull request by krytarowski**

### CODE REVIEW

**Comment by jkotas** [comment]
LGTM

**Comment by krytarowski** [comment]
Besides everything. There is still an issue with undefined `SIGRTMIN` with this patch.

**Comment by jkotas** [comment]
You can leave the FEATURE_HIJACK enabled here then, and just ifdef out the implementation in the PAL - everything should still work when the PAL_InjectActivation API returns failure.

**Comment by krytarowski** [comment]
I'm afraid that `PAL_InjectActivation` return is ignored.

What about this code:

```
--- src/pal/src/exception/signal.cpp.orig	2016-01-28 19:04:13.000000000 +0000
+++ src/pal/src/exception/signal.cpp
@@ -45,7 +45,9 @@ using namespace CorUnix;
 
 SET_DEFAULT_DEBUG_CHANNEL(EXCEPT);
 
+#ifdef SIGRTMIN
 #define INJECT_ACTIVATION_SIGNAL SIGRTMIN
+#endif
 
 /* local type definitions *****************************************************/
 
@@ -125,7 +127,9 @@ BOOL SEHInitializeSignals()
     handle_signal(SIGINT, sigint_handler, &g_previous_sigint);
     handle_signal(SIGQUIT, sigquit_handler, &g_previous_sigquit);
 
+#ifdef SIGRTMIN
     handle_signal(INJECT_ACTIVATION_SIGNAL, inject_activation_handler, NULL);
+#endif
 
     /* The default action for SIGPIPE is process termination.
        Since SIGPIPE can be signaled when trying to write on a socket for which
```

Perhaps along with the `FEATURE_HIJACK` disabled. Maybe `ifdef` it with `FEATURE_HIJACK` instead of `SIGRTMIN`?

**Comment by krytarowski** [comment]
I ended up with:

```
$ cat patches/patch-src_pal_src_exception_signal.cpp       
$NetBSD$

--- src/pal/src/exception/signal.cpp.orig	2016-01-28 19:04:13.000000000 +0000
+++ src/pal/src/exception/signal.cpp
@@ -45,7 +45,9 @@ using namespace CorUnix;
 
 SET_DEFAULT_DEBUG_CHANNEL(EXCEPT);
 
+#ifdef SIGRTMIN
 #define INJECT_ACTIVATION_SIGNAL SIGRTMIN
+#endif
 
 /* local type definitions *****************************************************/
 
@@ -70,7 +72,9 @@ static void sigquit_handler(int code, si
 static void common_signal_handler(PEXCEPTION_POINTERS pointers, int code, 
                                   native_context_t *ucontext);
 
+#ifdef SIGRTMIN
 static void inject_activation_handler(int code, siginfo_t *siginfo, void *context);
+#endif
 
 static void handle_signal(int signal_id, SIGFUNC sigfunc, struct sigaction *previousAction);
 static void restore_signal(int signal_id, struct sigaction *previousAction);
@@ -125,7 +129,9 @@ BOOL SEHInitializeSignals()
     handle_signal(SIGINT, sigint_handler, &g_previous_sigint);
     handle_signal(SIGQUIT, sigquit_handler, &g_previous_sigquit);
 
+#ifdef SIGRTMIN
     handle_signal(INJECT_ACTIVATION_SIGNAL, inject_activation_handler, NULL);
+#endif
 
     /* The default action for SIGPIPE is process termination.
        Since SIGPIPE can be signaled when trying to write on a socket for which
@@ -496,6 +502,7 @@ Parameters :
 
 (no return value)
 --*/
+#ifdef SIGRTMIN
 static void inject_activation_handler(int code, siginfo_t *siginfo, void *context)
 {
     // Only accept activations from the current process
@@ -523,6 +530,7 @@ static void inject_activation_handler(in
         }
     }
 }
+#endif
 
 /*++
 Function :
@@ -538,6 +546,7 @@ Parameters :
 --*/
 PAL_ERROR InjectActivationInternal(CorUnix::CPalThread* pThread)
 {
+#ifdef SIGRTMIN
     int status = pthread_kill(pThread->GetPThreadSelf(), INJECT_ACTIVATION_SIGNAL);
     if (status != 0)
     {
@@ -550,6 +559,9 @@ PAL_ERROR InjectActivationInternal(CorUn
     }
 
     return NO_ERROR;
+#else
+    return ERROR_CANCELLED;
+#endif
 }
 
 /*++
```

**Comment by krytarowski** [comment]
@adityamandaleeka ^

**Comment by krytarowski** [comment]
@janvoroli ^

**Comment by krytarowski** [comment]
without libunwind I cannot build test it fully

**Comment by krytarowski** [comment]
I will hold on with this till libunwind will be ported.

**Comment by jkotas** [comment]
FEATURE_HIJACK is optional performance optimization. It explains why errors from InjectActivation are ignored - they are not fatal: the program may run slower, but it will still work.

On the other hand, libunwind is not optional - we have a hard dependency on it.

I think what you have proposed above to fix the compile error sounds reasonable. It may be better to use INJECT_ACTIVATION_SIGNAL for the ifdefs except the first one. Maybe something like:

```
#ifdef SIGRTMIN
#define INJECT_ACTIVATION_SIGNAL SIGRTMIN
#endif

#if !defined(INJECT_ACTIVATION_SIGNAL) && defined(FEATURE_HIJACK)
#error FEATURE_HIJACK requires INJECT_ACTIVATION_SIGNAL to be defined
#endif
...
...
#ifdef INJECT_ACTIVATION_SIGNAL
     handle_signal(INJECT_ACTIVATION_SIGNAL, inject_activation_handler, NULL);
#endif
...
```

+ keep the change to disable FEATURE_HIJACK for NetBSD in the top level CMakefile.

**Comment by krytarowski** [comment]
Thank you! I will be back to it with libunwind aboard.

**Comment by krytarowski** [comment]
Done!

**Pull request merged**
