### PR TITLE
ARM64: update tests.lst

### PR DESCRIPTION
**Pull request by rahku**

### CODE REVIEW

**Comment by rahku** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by rahku** [comment]
@dotnet-bot test Windows_NT arm64 Release

**Comment by rahku** [comment]
@dotnet-bot test Windows_NT arm64 Checked pri1r2r

**Comment by rahku** [comment]
@dotnet-bot test Windows_NT arm64 Release pri1r2r

**Comment by rahku** [comment]
Mark 25 additional tests as passing. Fixed by PR #5978

**Comment by rahku** [comment]
PTAL @dotnet/arm64-contrib

**Comment by briansull** [comment]
Looks Fine, I also have updated my local version

**Comment by kyulee1** [comment]
LGTM

**Pull request merged**
