### PR TITLE
[master] Update buildtools to add Serviceable to nupkgs

### PR DESCRIPTION
**Pull request by ericstj**
Updates buildtools to bring changes to write Serviceable element in nuspecs.

/cc @gkhanna79 @schellap @joshfree @weshaggard

### CODE REVIEW

**Comment by gkhanna79** [comment]
LGTM. Thanks @ericstj. @schellap Are you making the change for Core-setup as well?

**Comment by ericstj** [comment]
I can do core-setup.

**Comment by gkhanna79** [comment]
Thanks @ericstj

**Comment by weshaggard** [comment]
LGTM

**Pull request merged**
