### PR TITLE
FI Test 

### PR DESCRIPTION
**Pull request by briansull**
Testing .Net 4.6.1 changes

### CODE REVIEW

**Comment by jkotas** [comment]
> assigning to 'LPCWSTR' (aka 'const char16_t *') from incompatible type 'const wchar_t [2]'

These errors are caused by Unicode strings - they need to be defined using `L"foo"` needs to be replace by `W("foo")`

**Comment by mikedn** [comment]
Yay for `JitDumpIR`, I hate trees, I was about to write something like that myself!

**Comment by jashook** [comment]
@dotnet-bot test ubuntu debug

**Comment by briansull** [comment]
@dotnet-bot test ubuntu debug

**Comment by briansull** [comment]
@dotnet-bot test ubuntu debug

**Comment by briansull** [comment]
@dotnet-bot test ubuntu debug

**Comment by briansull** [comment]
@dotnet-bot test ubuntu debug

**Comment by briansull** [comment]
@dotnet-bot test ubuntu debug

**Comment by jashook** [comment]
@dotnet-bot test ubuntu debug

**Comment by briansull** [comment]
@dotnet-bot test ubuntu debug

**Comment by jashook** [comment]
@dotnet-bot test Ubuntu x64 Release

**Comment by briansull** [comment]
@dotnet-bot test ubuntu debug

**Pull request closed without merging**
