### PR TITLE
Fixes #37 Missing Files to build GC stress Tests

### LINKED ISSUE #37: Missing projects in AllTestProjects.sln
Opening `.\tests\src\AllTestProjects.sln` in VS2013 indicates a couple of `csproj` files are missing:

> C:\Users\brendanforster\Documents\windows\coreclr\tests\src\GC\Stress\Framework\ReliabilityFramework.csproj : error  : The project file could not be loaded. Could not find file 'C:\Users\brendanforster\Documents\windows\coreclr\tests\src\GC\Stress\Framework\ReliabilityFramework.csproj'.  C:\Users\brendanforster\Documents\windows\coreclr\tests\src\GC\Stress\Framework\ReliabilityFramework.csproj
>
> C:\Users\brendanforster\Documents\windows\coreclr\tests\src\GC\Stress\Tests\GC_Stress_tests_collection.csproj : error  : The project file could not be loaded. Could not find file 'C:\Users\brendanforster\Documents\windows\coreclr\tests\src\GC\Stress\Tests\GC_Stress_tests_collection.csproj'.  C:\Users\brendanforster\Documents\windows\coreclr\tests\src\GC\Stress\Tests\GC_Stress_tests_collection.csproj

There's source code at these locations, so I guess something got lost in the transition. I gather these use a similar csproj setup as other test projects - if there's nothing fancy about them it should be easy to include...

### PR DESCRIPTION
**Pull request by ramarag**

### CODE REVIEW

**Comment by brianrob** [comment]
Thanks @ramarag.  Were these files just missed as part of the original PR?

**Comment by ramarag** [comment]
Yes, I forgot to add them to the git staging area, so the commit did not pick them up

**Comment by brianrob** [comment]
LGTM

**Comment by AlexGhiondea** [comment]
LGTM

**Pull request merged**
