### PR TITLE
Transform SIMD8 to FIELD_LIST if promoted

### LINKED ISSUE #21546: Test failure: JIT_SIMD._CircleInConvex_ro_CircleInConvex_ro_._CircleInConvex_ro_CircleInConvex_ro_cmd
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86_arm_altjit/job/jitstress/job/x86_arm_altjit_checked_windows_nt_jitstress1/373/
**Failed test:**
JIT_SIMD._CircleInConvex_ro_CircleInConvex_ro_._CircleInConvex_ro_CircleInConvex_ro_cmd

**Log:**
```
JIT_SIMD._CircleInConvex_ro_CircleInConvex_ro_._CircleInConvex_ro_CircleInConvex_ro_cmd [FAIL]
        
  
  Return code:      1
  Raw output file:      D:\j\workspace\x86_arm_altji---c75e0863\bin\tests\Windows_NT.x86.Checked\Reports\JIT.SIMD\CircleInConvex_ro\CircleInConvex_ro.output.txt
  Raw output:
  BEGIN EXECUTION
         "D:\j\workspace\x86_arm_altji---c75e0863\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" CircleInConvex_ro.exe 
        Expected: 100
        Actual: 0
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        
  To run the test:
  > set CORE_ROOT=D:\j\workspace\x86_arm_altji---c75e0863\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root
  > D:\j\workspace\x86_arm_altji---c75e0863\bin\tests\Windows_NT.x86.Checked\JIT\SIMD\CircleInConvex_ro\CircleInConvex_ro.cmd
  
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\x86_arm_altji---c75e0863\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT.SIMD\JIT.SIMD.XUnitWrapper.cs(949,0): at JIT_SIMD._CircleInConvex_ro_CircleInConvex_ro_._CircleInConvex_ro_CircleInConvex_ro_cmd()
```

### PR DESCRIPTION
**Pull request by CarolEidt**
Fix #21546

### CODE REVIEW

**Comment by CarolEidt** [comment]
test Windows_NT x86 Checked Innerloop Build and Test
test CentOS7.1 x64 Checked Innerloop Build and Test

**Comment by CarolEidt** [comment]
test Windows_NT x86 Checked Innerloop Build and Test

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

**Comment by tannergooding** [comment]
Should this also test `x86_arm_altjit_checked_windows_nt_jitstress1_prtest`, since that was what was repro'ing the bug 100% of the time in CI (I had to tweak things locally to get it to fail otherwise).

**Comment by CarolEidt** [comment]
test Windows_NT x86_arm_altjit Checked jitstress1

**Comment by sandreenko** [comment]
Could you please give an example how it changed IR from the regression:
```
lvaGrabTemp returning 3 (V03 tmp0) called for struct address for call/obj.
  Known type Vector2
               [000035] ------------              *  STMT      void  (IL   ???...  ???)
               [000026] --C---------              \--*  RET_EXPR  void  (inl return from call [000023])
resulting tree:
               [000036] ------------              *  LCL_VAR   simd8  V03 tmp0 
```

**Comment by CarolEidt** [comment]
> Could you please give an example how it changed IR from the regression:

I'm having some difficulty at the moment connecting to the machine with my fix, but the IR you show above doesn't change. The problem was the code surrounding where I've made the fix - it wasn't prepared for a lclVar without an `OBJ(ADDR)`. My fix allows that to be handled correctly.

**Comment by CarolEidt** [comment]
@sandreenko - the IR looks basically the same as above:
```
lvaGrabTemp returning 3 (V03 tmp1) called for struct address for call/obj.
  Known type Vector2


               [000036] ------------              *  STMT      void  (IL   ???...  ???)
               [000027] --C---------              \--*  RET_EXPR  void  (inl return from call [000024])
resulting tree:
               [000037] ------------              *  LCL_VAR   simd8  V03 tmp1         
```
The difference is that downstream this same node:
```
               [000037] ------------ arg1         +--*  LCL_VAR   simd8 (P) V03 tmp1         
                                                  +--*    float  V03.X (offs=0x00) -> V10 tmp8         
                                                  +--*    float  V03.Y (offs=0x04) -> V11 tmp9       
```
Gets morphed into this instead of being left as-is:
```
               [000278] ------------              |  /--*  FIELD_LIST float  float at offset 4
               [000277] ------------              |  |  \--*  LCL_VAR   float  V11 tmp9         
               [000276] Hc---------- arg1         +--*  FIELD_LIST float  float at offset 0
               [000037] -----+------              |  \--*  LCL_VAR   float  V10 tmp8  
```

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib ping

**Pull request merged**
