### PR TITLE
[Arm64 Unix CI] Update the steps for build cross

### PR DESCRIPTION
**Pull request by jashook**
This will fix the cross build and correctly run tests.

** NOTE this is a change to dev/unix_test_workflow

### CODE REVIEW

**Comment by jashook** [comment]
@dotnet-bot test CI Please

**Comment by jashook** [comment]
Note we have successful end to end testing based on this change. See https://ci.dot.net/job/dotnet_coreclr/job/dev_unix_test_workflow/job/arm64_checked_small_page_size_tst/5/console for more details

**Comment by jashook** [comment]
@dotnet-bot test CI Please

**Comment by jashook** [comment]
@dotnet-bot test CI Please

**Comment by jashook** [comment]
@dotnet-bot test CI Please

**Comment by sdmaclea** [comment]
@jashook Thanks

**Pull request merged**
